### PR TITLE
CRM: Client Portal custom fields not working

### PR DESCRIPTION
**Pull request by gogdzl**
## Proposed changes:

* This PR fixes the following problems in the Client Portal
  * Numeric Fields (this includes Numeric with decimals) - numeric fields were not being rendered
  * TextAreas - Special characters in textareas were not being displayed correctly. This could potentially insert wrong data in the database (characters that were wrongly inserted by the escape function used)
  * Date Fields - Date fields were not working correctly

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to Settings -> Custom Fields (`wp-admin/admin.php?page=zerobscrm-plugin-settings&tab=customfields`) and add the following for Contacts:
  * Numeric Field
  * Numeric (Decimals) Field
  * Textarea
  * Date
* Log in the Client Portal (`/clients`) as a Contact (if you don't have one yet, you can add the client portal access to contacts in their edit page `admin.php?page=zbs-add-edit&action=view&zbstype=contact&zbsid=1`)
* Change the information for each field, making sure to add special characters to the textarea (e.g. `<some spéciál $# characters>`

In `trunk` numeric fields don't get rendered, textareas will fail to escape special characters and date fields won't work.

In `crm/fix/client_portal_custom_fields_not_working` everything should work as expected.

### CODE REVIEW

**Comment by cleacos** [comment]
This is the authentic combo PR :)

**Comment by cleacos** [comment]
I'm getting these JS errors in my browser console:

image

I've run `jetpack build plugins/crm` and shift+refresh the browser

**Comment by cleacos** [comment]
Same error testing it via Jurassic Ninja site and Jetpack Beta with this branch

**Comment by gogdzl** [comment]
Some monorepo move fixes weren't merged in trunk when I did my previous rebase.
NoW everything should be working just fine.

**Comment by cleacos** [comment]
Yes, but I was trying to create a new contact to add them as Client Portal, but I cannot because of the JS error. Trying to click on the `Save` button, but nothing happens.

**Review by cleacos — APPROVED** [review]
It works as expected. I tested the custom field for `decimals`, `integers` and `dates`.

**Pull request merged**
