### PR TITLE
Migration plugin: refactor migration component

### PR DESCRIPTION
**Pull request by bogiii**
## Proposed changes:

- Exported existing `ConnectScreenLayout` component from the `js connection package`
- Introduced Migration component, which replaced the Jetpack logo and styling with WordPress.
- Adjusted the admin page to consume the Migration component.
For more details, see the screenshot below.

Closes https://github.com/Automattic/dotcom-forge/issues/1491

## Testing instructions:
* Launch a [JN site with the migration plugin](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack-migration=update/migration-plugin&wp-debug-log).
* Check if there is a new WordPress.com branding style
* Click on the `Get Started` button and check if everything works as before this PR

## Does this pull request change what data or activity we track or use?
No

## Screenshot
Screenshot 2023-02-06 at 10 21 33

### CODE REVIEW

**Review by ouikhuan — CHANGES_REQUESTED** [review]
Everything looks great to me, nice work @bogiii ! The only thing here is that we need to address the Linting warnings before handing it out to the jetpack crew to review 👍

**Comment by ouikhuan** [comment]
Hi @jennyzhu 👋  We've talked about moving terms above the button in this thread ( pcmemI-1GG-p2#comment-1312 ).
However, in the latest design there's no terms of service in the page, will this be a problem? Or it's a must to include it in the page? Thanks.

cc @vishnugopal

**Comment by jennyzhu** [comment]
@ouikhuan Thanks for checking in! I need to know a bit more about what this screen is and when it's displayed before I can answer that. I'll ping you on Slack!

**Comment by jennyzhu** [comment]
@ouikhuan Since clicking "Get started" kicks off the Jetpack connection, we'll need to bring back the legal language and put it directly above the button:

> By clicking "Get Started," you agree to our [Terms of Service](http://wordpress.com/tos/) and to [share details](https://jetpack.com/support/what-data-does-jetpack-sync/) with WordPress.com.

**Comment by ouikhuan** [comment]
Thanks for the confirmation @jennyzhu, we'll wrap this PR up and work on the terms and conditions in another ticket.

**Review by ouikhuan — DISMISSED** [review]
LGTM!

**Comment by sdixon194** [comment]
Looks like there are a few failing tests on this one that will have to be resolved before we can merge it! Also could probably use a merge with trunk and conflict cleanup.

**Comment by bogiii** [comment]
Hey @sdixon194, the rebase has been done, and it seems that tests are ok now.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
