### PR TITLE
Contact Form: refactor editor to use forms package

### PR DESCRIPTION
**Pull request by monsieur-z**
## Proposed changes:

As part of the Contact Form module deprecation, this PR refactors the `Grunion_Editor_View` class to reference the Forms package.

The refactored code calls the static methods of `Editor_View`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Project thread: pf5801-Aj-p2
Issue: https://github.com/Automattic/jetpack/issues/35653

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Let's do some regression testing.

- Spin up a test site with this branch
- Update the file `/projects/plugins/jetpack/modules/contact-form.php` so the condition on line 33 is falsy (or comment the block). This ensures we're loading the Contact Form module.
- Create a new post
- Check you can still add a Contact Form block and that nothing breaks

### CODE REVIEW

**Comment by sergeymitr** [comment]
I replaced `return true` with `return false` as instructed, and couldn't get the form to display.

Screenshot 2024-03-08 at 16 39 27
Clicking the button sends a request to `jetpack/v4/module/contact-form/active`, which returns the "was activated" response, but it doesn't change anything.

I was testing on a JN site with Jetpack Beta if that matters.

**Comment by monsieur-z** [comment]
> I replaced return true with return false as instructed, and couldn't get the form to display.

@sergeymitr, I realize my instructions may have been confusing. The condition should be falsy, or the whole block can be commented out.
Screenshot 2024-03-11 at 2 47 45 PM

**Review by sergeymitr — DISMISSED** [review]
Discussed in slack: p1710184175632159-slack-C05PV073SG3
Works well 👍

**Comment by monsieur-z** [comment]
Sorry @sergeymitr, I noticed an error and had to push another commit: https://github.com/Automattic/jetpack/pull/36089/commits/b3aaf6be0f73508ba898699a799a278437e4ff28

**Review by sergeymitr — APPROVED** [review]

**Pull request merged**
