### PR TITLE
If both queues didn’t send data, wait 5 seconds before sending again

### PR DESCRIPTION
**Pull request by gravityrail**
Adds a 5 second delay before we next try to send data if both queues returned false, since this is a signal that there was no data to send.

### CODE REVIEW

**Comment by lezama** [comment]
let's 🚢 this

**Comment by jeherve** [comment]
A few of the tests appear to be failing:

```
WP_Test_iJetpack_Sync_Replicastore::test_checksum_histogram with data set #1 (Jetpack_Sync_Test_Replicastore Object (...))
Undefined offset: 1
```
https://travis-ci.org/Automattic/jetpack/builds/151270966

Is this related?

**Comment by lezama** [comment]
Let's not ship this right now, moving it to 4.4

**Comment by zinigor** [comment]
@gravityrail I have rebased this PR, but judging by what Travis says I have botched it. Can you please take a look?

**Comment by lezama** [comment]
@zinigor, I am closing this one, things have changed a lot. :)

**Pull request closed without merging**
