### PR TITLE
Jetpack Setup Wizard: Add Updates Question Page

### PR DESCRIPTION
**Pull request by robertf4**
#### Changes proposed in this Pull Request:

This PR builds on the work in #15429 by adding the updates question page.

Figma design desktop:
image

Figma design mobile:
image

Current state desktop:
image

Current state mobile:
image

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Project: p1HpG7-8BF-p2
Design: pbtFPC-ol-p2

#### Testing instructions:

1. Add the following to the end of wp-config.php: add_filter( 'jetpack_show_setup_wizard', '__return_true' );
2. Visit the Jetpack plugin and visit the `/setup` page, then advance to the `/setup/updates` page.
3. Verify that the back/forward button works.
4. Verify that the page design matches the Figma.
5. Shrink the window and again verify that the page design matches the Figma.

#### Proposed changelog entry for your changes:
* None needed; the setup wizard project as a whole should have one entry.

### CODE REVIEW

**Comment by robertf4** [comment]
I've set this PR to Do Not Merge until https://github.com/Automattic/jetpack/pull/15501 is merged into master and this is rebased, but in the meantime it is ready for review.

**Comment by jeffgolenski** [comment]
Hey @robertf4 At first glance it's looking good based on your screenshots, although I'm unable to test this particular PR based on the instructions. 

> Visit the Jetpack plugin and visit the /setup page, then advance to the /setup/updates page.

I used the same JN site that I whipped up for #15501 but I can navigate past the first question. If I input `/wp-admin/admin.php?page=jetpack#/setup/updates/` or `/wp-admin/admin.php?page=jetpack#/setup/updates` nothing loads. Thoughts?

**Comment by robertf4** [comment]
> I used the same JN site that I whipped up for #15501 but I can navigate past the first question. If I input `/wp-admin/admin.php?page=jetpack#/setup/updates/` or `/wp-admin/admin.php?page=jetpack#/setup/updates` nothing loads. Thoughts?

@jeffgolenski if you used the same site as you did for #15501 then it's probably because you need to spin up a new JN with this PR, #15579. #15579 is branched from #15501, so #15501 doesn't have the code from this PR in it.

**Review by pidgeonman — DISMISSED** [review]
WFM in a local environment doing a fresh build. It doesn't work in a JN environment, doesn't go past the first question. Approving. 👍

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]

**Pull request merged**
