### PR TITLE
Admin: add width and height attributes to the Happiness Engineer avat…

### LINKED ISSUE #4837: Admin: Footer HE images need height / width attributes
Not urgent, but the Happiness Engineer photos need height and width attrs within the `img` tag, so they don't break the layout if the app loads slow. 

screen shot 2016-08-16 at 5 38 10 pm

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #4837

#### Changes proposed in this Pull Request:
- add width and height attributes to the Happiness Engineer avatar at the bottom,

#### Testing instructions:
- go to Jetpack admin and make sure the HE avatar looks fine

cc @jeffgolenski for review

### CODE REVIEW

**Comment by zinigor** [comment]
Avatars look fine to me after applying that PR. I don't know if Jeff maybe has another solution in mind, like adding styles to the stylesheet, but it's up to him. To me LGTM!

**Comment by eliorivero** [comment]
I don't think this is important enough to have a changelog line. @jeherve should I just add the Has Changelog label? How do I tell you that nothing should be added?

**Comment by jeherve** [comment]
> should I just add the Has Changelog label?

That works for me 👍 . Or you could add a small mention of this in the changelog, and we'll see if this is worth keeping when we review and edit the full changelog before the release.

**Comment by jeffgolenski** [comment]
Gah, sorry I missed this @eliorivero – IPF

**Pull request merged**
