### PR TITLE
Notes: Disable Admin menu in Jetpack Notifications when in Site Editor

### LINKED ISSUE #50246: Site Editor: unable to type N in Dotcom integration
A Dotcom integration was reported in testing round that's not happening in core. It's not possible to type in the `N` letter into text.

### PR DESCRIPTION
**Pull request by ramonjd**
(Maybe) Fixes https://github.com/Automattic/wp-calypso/issues/50246

#### Changes proposed in this Pull Request

Notification shortcuts take over certain keystrokes in the Site Editor.

Jun-03-2021 13-45-40

D60728-code addressed this issue on WPCOM, but the problem persists on Atomic sites.

This PR adds the check from D60728-code to Jetpack Notifications.

❓ Is there a more appropriate way to do this in Jetpack? Would a filter be better?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions

Apply this PR to Atomic (or ephemeral) site with:

- Gutenberg activated
- Jetpack connected and Jetpack beta activated

Change your theme to TT1 blocks.

Screen Shot 2021-06-03 at 1 52 52 pm

Open the Site Editor and type away, paying particular attention to `n` and `s` and `a`.

after-typing

### CODE REVIEW

**Comment by jeherve** [comment]
> Is there a more appropriate way to do this in Jetpack? Would a filter be better?

That's a good question. Would it be an option, and would it work to use something like `wp_should_load_block_editor_scripts_and_styles()`?
https://developer.wordpress.org/reference/functions/wp_should_load_block_editor_scripts_and_styles/

If that were to work for the full site editor too, we could bail early if that function returns true?

**Comment by ramonjd** [comment]
> Would it be an option, and would it work to use something like wp_should_load_block_editor_scripts_and_styles()?

Thnaks for the idea @jeherve  - I didn't know about this function!

I tested but unfortunately `wp_should_load_block_editor_scripts_and_styles()` returns `false` for both block and site editors when used in notes.php's `action_init`. 

I think this is because, at this point, `$current_screen` is `null`. 

This was the reason why @vindl checked for the admin.php query param in D60728-code I believe.

Using [gutenberg_is_edit_site_page](https://github.com/WordPress/gutenberg/blob/306566f9b8832c551667817a02e0f3f6145f6bb6/lib/full-site-editing/edit-site-page.php#L30) would have been a neat way to do it as well, however it also relies on `$current_screen->id`.

```php
$is_site_editor = ( function_exists( 'gutenberg_is_edit_site_page' ) && gutenberg_is_edit_site_page( $current_screen->id ) );
```

> Although part of me wonders if this should be handled from within the notifications script instead?

There might be a JS solution. 

I expect it would be something similar, that is, checking the URL for `?page=gutenberg-edit-site`. 

Or we could look at site editor globals, assuming they're set in time, e.g., 

```js

// Could also try `wp.editSite`
const isSiteEditor = !! wp.data.select('core/edit-site') // returns `null` on the post editor.
```

I does mean that we're loading a bunch of assets just to make this check. Is it worth it?

**Comment by jeherve** [comment]
> I does mean that we're loading a bunch of assets just to make this check. Is it worth it?

That's a good point. Do we need to load those assets, or can we check that they're available since they must be loaded in the editor?

**Comment by ramonjd** [comment]
> Do we need to load those assets, or can we check that they're available since they must be loaded in the editor?

That's a neat idea.

If I understand you correctly, we could try checking whether the [Gutenberg Site Editor scripts](https://github.com/WordPress/gutenberg/blob/306566f9b8832c551667817a02e0f3f6145f6bb6/lib/full-site-editing/edit-site-page.php#L129) are queued (?)

```php
// If Gutenberg Site Editor scripts are queued don't load the notes module.
if ( wp_script_is( 'wp-edit-site' ) ) {
	return;
}
```

I'll give it a whirl today or tomorrow and see! :)

**Comment by jeherve** [comment]
> Site Editor scripts are enqueued always it appears so notes is broken across the admin :(

Oh, that's interesting. Not great for us though :(

**Review by jeherve — APPROVED** [review]
Approving this for now, since it does the trick.

**Pull request merged**
