### PR TITLE
Instagram Gallery Block

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request:

* Add the scaffolding for a new Instagram Gallery block.

See https://github.com/Automattic/explorers-private/issues/36

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* pb5gDS-lF-p2

#### Testing instructions:

* Make sure the Instagram Gallery block is registered and can be added to a post.

#### Proposed changelog entry for your changes:

* New Instagram Gallery block.

### CODE REVIEW

**Comment by creativecoder** [comment]
I have some code from an earlier version of the Eventbrite block that does the keyring connection from the block--I'll add that to this PR tomorrow.

**Comment by jeherve** [comment]
Do you think we could ship this initial PR right now, and then iterate in another, just so we can keep PRs smaller when possible?

**Review by jeherve — APPROVED** [review]

**Comment by Copons** [comment]
@jeherve That was my plan too! 🙂 
I didn't open this for review just yet because I was trying something, but since that didn't turn out to be anything useful, we might as well ship this!

@creativecoder thanks for looking into the API side of this. Feel free to open a new PR following up to this.

**Comment by Copons** [comment]
r204505-wpcom

**Comment by creativecoder** [comment]
> @creativecoder thanks for looking into the API side of this. Feel free to open a new PR following up to this.

Will do. Always happy for smaller PRs!

**Pull request merged**
