### PR TITLE
Blocks: update to latest version of blocks for 6.9 release

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Blocks: update to latest version of blocks for 6.9 release

The blocks were released here:
https://github.com/Automattic/wp-calypso/releases/tag/%40automattic%2Fjetpack-blocks%4011.1.0

#### Testing instructions:

* Open your block editor.
* Do you see blocks?
* 💥

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

**Review by sirreal — APPROVED** [review]
I didn't test but this looks good. 👍

**Review by brbrr — APPROVED** [review]
All blocks are still there 🚢

**Review by tyxla — APPROVED** [review]
🚢

**Comment by jeherve** [comment]
Cherry-picked to `branch-6.9` in e2e377a04b1c1e6525b6cb7208a7fbbb8f25c749

**Pull request merged**
