### PR TITLE
Masterbar: Rename and reorder Pages menu

### PR DESCRIPTION
**Pull request by shaunandrews**
Rename "Pages" to "Site Pages" and move above "Blog Posts"

Keeping in sync with Calypso: https://github.com/Automattic/wp-calypso/pull/17016

### CODE REVIEW

**Comment by lancewillett** [comment]
Related WP.com navigation change ready for review in D6871-code.

**Comment by lancewillett** [comment]
Visual record from testing this change — using a Jetpack test site (not Atomic) on Dreamhost. I have bleeding edge running via Jetpack Beta plugin, and just overwrote the changed PHP file by hand.

Testing with `testerlance` user connected to WP.com, with Mac-n-Chrome OS/browser.

Front-end of the site, navigation bar updates:
screen shot 2017-08-16 at 11 26 48

Calypso logged-in as the connect user:
screen shot 2017-08-16 at 11 26 56

WP Admin for the Jetpack site, logged in:
screen shot 2017-08-16 at 11 27 03

**Comment by lancewillett** [comment]
I think since we're changing the navigation — let's go ahead and match the WP.com navigation recent changes.

1. Change "Publish" to "Manage" in the section label.
2. Add the new "Comments" link. (Or break that into a new PR?).

**Comment by shaunandrews** [comment]
I missed an instance of "Pages". Fixed it, and updated the "Publish" label to "Manage." The Comments link can be addressed in a separate PR.

**Comment by lancewillett** [comment]
This is looking great now — ready to merge IMO.

screen shot 2017-08-17 at 07 09 39

**Pull request merged**
