### PR TITLE
Premium content block: Add a warning message for invalid plans

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
When a Premium content block is configured with an invalid plan (subscription), the user is not aware that there's a problem with it. To handle this, we can add a warning message that would inform the user that the block is currently in an invalid state.

Fixes https://github.com/Automattic/wp-calypso/issues/49103
#### Changes proposed in this Pull Request:

* Added a warning message at the top of the block
* Changed the plan (subscription) description with the message "Subscription not found".

#### Testing instructions:

* On Atomic, use Jetpack beta to switch to this branch
* On Simple, apply D73590-code on your sandbox
* Create a new Premium Content Block
* Connect it to Stripe (I think you'll need to create a Stripe test account :( )
* Configure the subscription in the controls and save the post
* Use incognito and go to the post you just published. Make sure that when you click on the "Subscribe" button the Stripe payment form is loaded
* Back in the editor, enable the Code Editor
* In the content, replace the "selectedPlanId" attribute with a non-existing plan.
* Exit the Code Editor and you should be able to see a warning message saying that the plan is invalid.

**Before**
Screenshot 2022-01-24 at 11 23 28

**After**
Screenshot 2022-01-24 at 11 20 41

### CODE REVIEW

**Comment by dsas** [comment]
This fixes the linked issue when changing the `selectedPlanId` attribute 👍 . It doesn't fix the problem when changing the `planId` attribute on the jetpack/recurring-payments block.

https://user-images.githubusercontent.com/93301/150961240-dbd96074-4365-446d-9275-6dfa653a9b73.mp4

**Comment by BogdanUngureanu** [comment]
@dsas, thanks for the review, nice finding. I've looked into it and noticed that when you switch back to the visual editor, the block will automatically refresh the planId of the inner block(recurring block) to the correct one. However, in order to persist the changes, the user will have to manually press the update button, which imo, it's not clear that that the operation is needed.

It looks like this might be an edge-case and would require a lot more thought on how to deal with this scenario, what do you think if we handle in a different PR? 🤔

**Comment by dsas** [comment]
> what do you think if we handle in a different PR/issue? 🤔

Definitely the right move 👍 this PR fixes a bigger and more likely scenario so shouldn't be held up on that smaller one.

**Review by dsas — APPROVED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM in r239318-wpcom

**Pull request merged**
