### PR TITLE
Story block: Improve rendering in email notifications

### PR DESCRIPTION
**Pull request by Tug**
This PR attempts to fix 2 issues with email notifications of blog posts containing a story block on WPCOM:
- Fix scaling the image to 180x320
- Fix story preview link

sh-merged

#### Changes proposed in this Pull Request:
This PR updates some CSS rules to makes sure the story blocks renders ok in preview mode, even without javascript. This fixes an issue where the first image in a story would not properly scale to the size of the story.
We also update the whole story rendering logic on the server to reuse the CSS classes but with a different DOM structure, more suited for consumption without javascript (the whole story is an anchor tag for instance).

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
TBD

* Apply D61026-code to your sandbox
* Find the blog id and post id of a story you want to test
* From your sandbox run `php ./bin/subscriptions/send.php BLOG_ID post POST_ID YOUR_EMAIL_ADDRESS`
* Check the email in different clients (gmail had the issue before this fix), the image should be scaled to the size of the preview (180x320), since https://github.com/Automattic/jetpack/pull/18609 the full size image is loaded
* Click on the image, your email client should open a new tab which loads the story in fullscreen
* Disable javascript and reload the page without the query args
* The story should look the same (in embed format), clicking on it should open the same page with the query arguments needed to view it fullscreen
* Go to the WPCOM reader, and find a story post, make sure the image is propely scaled (it's actually using a 180x320px image, so no "retina" support yet) and that it still has a link to the playable story

### CODE REVIEW

**Review by aforcier — APPROVED** [review]
@Tug I went through the steps for a Jetpack site and everything was working well 🎉 

* Correct preview image sizing in email
* Tapping preview plays story
* JS disabled worked
* Checked WPcom Reader
* Checked Reader on iOS and Android

I tried to verify for a WP.com site but it doesn't look like it worked. Inspecting the email sent using the command-line tool, it doesn't look like it has the updated `a` tag structure, so I'm not sure that it was taking into account the changes applied to my sandbox. I'm not too worried about it but I wonder if you know how to test that.

**Comment by Tug** [comment]
I believe it should work the same with wpcom sites. Did you disable the cache for this?
```
define( 'BLOCK_FALLBACKS_DEBUG', true );
```

**Comment by aforcier** [comment]
@Tug that helped, or at least I was able to verify for existing posts by disabling the cache 👍 Working well! :shipit: from me

**Review by jeherve — APPROVED** [review]
Looks good to me. 🚢

**Comment by Tug** [comment]
Deployed on WPCOM with changeset id 225690

**Pull request merged**
