### PR TITLE
Jetpack: Likes: Import changes from wpcom

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

This brings in a few changes that had been made on wpcom which were never copied back to Jetpack.

* Add cachebuster and index.html to iframe (D10021-code)
  * Also added this to the adminbar widget's iframe, which does not exist on wpcom.
* Fix locale handling (D10955-code)
* Pass "domain" parameter to login (D25102-code)
* Enable reblog button if like button is disabled (D66115-code)

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

https://github.com/Automattic/jetpack/issues/25205#issuecomment-1287253394

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Make sure Likes stuff works right?

### CODE REVIEW

**Comment by sdixon194** [comment]
Looks like maybe the tests need to be updated as well?

**Comment by kraftbj** [comment]
Marking for 11.6. Let's add this early in the cycle instead of right before beta.

**Comment by sdixon194** [comment]
Dropping notes as I test:

- enable likes site wide in jetpack settings
- turn off likes on a specific post from the block editor
- see there's still a "Like this" section appear:

Screen Shot 2022-10-25 at 12 20 09 PM

Same behavior doesn't happen on trunk.

**Comment by anomiex** [comment]
> turn off likes on a specific post from the block editor

Where is the option for that in the first place?

**Comment by sdixon194** [comment]
> Where is the option for that in the first place?

Under the Jetpack menu:

Screen Shot 2022-10-25 at 1 23 26 PM

**Comment by anomiex** [comment]
... Grumble. The same misbehavior happens on wpcom, but apparently they always hide that header with CSS so no one notices the problem.

**Comment by anomiex** [comment]
Tempted to abandon this in favor of #27062.

**Comment by anomiex** [comment]
Abandoning in favor of https://github.com/Automattic/jetpack/pull/27062.

**Pull request closed without merging**
