### PR TITLE
Search: Use API values for paid allowance limits shown in the new pricing table

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:

Make certain values API-driven within the new pricing table.

image

image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1666032314887379-slack-C02ME06LF?thread_ts=1666026581.553339&cid=C02ME06LF

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

Changing the API:
* Apply this change to your Jetpack site without a Search subscription.
* Sandbox your site's API connection using the `JETPACK__SANDBOX_DOMAIN` constant.
* Try changing the values returned for `monthly_search_request_limit`, `record_limit`, `quantity_per_unit`, and `per_unit_fee` in the pricing API.
* Ensure the new values are shown in the pricing table (`/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`).

Changing the selector:
 * Apply this change to your Jetpack site without a Search subscription.
 * Change the selector code (e.g. `getPaidRequestsLimit: state => 40000`) to force a different value.
 * Ensure that different values are shown in the pricing table (`/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`).

### CODE REVIEW

**Review by kangzj — COMMENTED** [review]
Thanks for the PR. Should we take the chance to fix the hard coded "50%" as well? And possibly some other hard coded values. Thanks

**Comment by jsnmoon** [comment]
> Should we take the chance to fix the hard coded "50%" as well? (@kangzj)

Just added improved discount handling. What other hard-coded values are you referring to? 

If they're trivial, then let's add them here. If not, then we can do them in a follow-up PR.

**Comment by gibrown** [comment]
The $7.50 should also match the $8.25 price right? Every 10k is just one more at the lowest tier.

**Comment by jsnmoon** [comment]
> The $7.50 should also match the $8.25 price right? Every 10k is just one more at the lowest tier. (@gibrown)

The dashboard is using `quantity_per_unit` and `per_unit_fee` values from the pricing API, so we can control that there 🙂

**Comment by gibrown** [comment]
Ok, sounds good to me. Does the 50% off come from the API also?

Screen Shot 2022-10-17 at 15 50 04

I don't think we want to launch with the discount and it looks like we may be removing them in general.

**Review by kangzj — COMMENTED** [review]
image

The per_unit_fee is in currency's smallest unit, so probably there's a gap in the API.

**Comment by kangzj** [comment]
> Just added improved discount handling. What other hard-coded values are you referring to?

Haven't looked. The discount should be good enough to ship with. Thanks.

**Comment by jsnmoon** [comment]
> Ok, sounds good to me. Does the 50% off come from the API also?
> 
> Screen Shot 2022-10-17 at 15 50 04
> 
> I don't think we want to launch with the discount and it looks like we may be removing them in general. (@gibrown)

The latest version of this branch calculates the discount based on the original and discounted prices returned by the API. So if the API doesn't return a discounted price (or if the two prices are the same), then it'll show the following:

image

**Comment by trakos** [comment]
That was super quick, thanks Jason!

I've noticed the thing Jasper mentions:

image

Additonally, looks like it's a price per year instead of a monthly one. I found that for full price we're just dividing it by 12 [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/dashboard/components/pages/connection-page.jsx#L93), do you think we could do something similar here for the tier fee?

I'll look into the price being returned as an integer, we should probably be more consistent in the API.

**Comment by jsnmoon** [comment]
@trakos: The unit price is now being divided by twelve before rendering! As Jasper already stated, the `per_unit_fee` is in the smallest unit of the customer's currency (10000 for $100.00, for example). I could divide the figure by 100 in the interface to correct this, but it probably makes sense to address this in the API.

Let me know if you see anything else I can address! 👍

**Comment by trakos** [comment]
I made a diff to fix the endpoint: D90067-code. With this, it would return the float value instead of an integer in the smallest units.

With that diff and this PR, I got the right values 🎉 :

image

Can't comment on the frontend code too much, as that's outside my expertise, but the output is as expected 😉 Nice job.

**Review by trakos — DISMISSED** [review]

**Comment by jsnmoon** [comment]
Got it! I will do another self-review and ship this if no reviews come in from my team in the next 24 hours 🙂

**Comment by trakos** [comment]
I've deployed the related D90067-code that fixes the `per_unit_fee` field in API. It is returned as a float now instead of the integer with the smallest unit of currency.

**Review by kangzj — APPROVED** [review]
LGTM

**Pull request merged**
