### PR TITLE
Search: Apply design polish to the Customberg customization interface

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
* Changes links from the Customizer to Customberg for Search configuration.

#### Jetpack product discussion
See pcNPJE-7J-p2.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Ensure you have a Jetpack Search subscription for your site.
* Navigate to the following four pages and ensure that they link to the new customization interface (Customberg):
  1. At-a-glance: `/wp-admin/admin.php?page=jetpack#/dashboard`
  2. My plan: `/wp-admin/admin.php?page=jetpack#/my-plan`
  3. Performance settings: `/wp-admin/admin.php?page=jetpack#/performance`
  4. New Jetpack Search page: `wp-admin/admin.php?page=jetpack-search&a8ctest`
* Ensure that the new customization interface works as expected: 
`/wp-admin/admin.php?page=jetpack-search-configure`.

#### Notes for design reviewers:
* The new Jetpack Search customization interface (dubbed Customberg) can be found at: 
`/wp-admin/admin.php?page=jetpack-search-configure`
* Customberg currently looks like the following:
> Screen Shot 2021-08-18 at 5 17 16 PM
* This PR changes existing links for configuring Search to point to Customberg.
* Customberg is feature-complete compared to configuring Jetpack Search within the Customizer.
* Customberg automatically collapses the wp-admin sidebar upon initialization.
* Customberg only works for WordPress 5.8 and up. The page will redirect to the Customizer experience if the installed WordPress version is less than 5.8.
* It's not possible to directly edit the blocks in the search overlay sidebar in Customberg. One must navigate to the Widgets editor to do so.

### CODE REVIEW

**Review by bluefuton — DISMISSED** [review]
Looks great! So much faster than the Customizer. 🚀 

Found a few things, which I'll list below:
- [x] Typography, borders and spacing are different between customization + site front end (possibly a wontfix, but would be interesting to know how hard it would be to sort out)
- [x] Not enough text contrast on 'Save' button when disabled. I know this is an 'off' state but perhaps the button should be grey? What's the RNA standard?

Screen Shot 2021-08-23 at 14 49 22

- [x] The light/dark images are missing an image description (a11y).

- [x] Color picker has a broken layout in French. The length of this text will vary between languages. Perhaps we could move the custom color link underneath?

Screen Shot 2021-08-23 at 14 47 46

- [x] On mobile, the page has no title
- [x] On mobile, it's not totally clear what I have to do to get started customizing. Do we need some text to direct the user to the cog?

Screen Shot 2021-08-23 at 14 49 47

- [x] UI does not appear in my chosen language (logged also for new wp-admin section https://github.com/Automattic/jetpack/issues/20757) - only selected strings are translated
- The sort link separator has some a11y issues - will log this issue separately as it affects the front-end too.

**Comment by keoshi** [comment]
This is looking great! Ditto to what @bluefuton said above, this feels sooo much smoother than the Customizer experience, kudos!

Thanks for switching the options under “Additional settings” to toggles instead of checkboxes, I don't know what I was thinking!

Also replying to what Chris said above:

> Not enough text contrast on 'Save' button when disabled. I know this is an 'off' state but perhaps the button should be grey? What's the RNA standard?

This is the core button behavior/styling. It's not ideal, but it will hopefully improve over time or, at least, be a discernible status that people can get familiar with since it's used everywhere in WP. We don't want to bring RNA into this UI because it should feel like a core component.

Here's what I've found in my testing:

- [ ] The loupe icon is slightly nudged to the left (2px?) when any text is entered in the search input:

image

- [ ] The top bar that holds the “Jetpack Search” title has a grey-ish white background, and it should be white.
```diff
.interface-interface-skeleton__header {
+  background-color: #ffffff;
}
```

- [ ] The Search color picker has less vertical padding that Core's. Our of curiosity: are we reusing the original components or changing them in some way? My assumption was that we could simply add Core components, so I'd hate if we had to add exceptions.

Core | Jetpack Search
--|--
image | image

- [ ] Turning off the “Powered by Jetpack” badge, the layout misbehaves in desktop and the bottom padding is set by the content on the left pane (search results) rather than the tallest pane (left or right). Maybe this was already true for the instant search layout?

image

- [ ] The highlight color takes into consideration the text color, but not when changing to the Dark theme. Note how it behaves with the “june bud” swatch. Maybe this was already true for the instant search layout?

Light theme | Dark theme
--|--
image | image
image | image

**Comment by jsnmoon** [comment]
> Typography, borders and spacing are different between customization + site front end (possibly a wontfix, but would be interesting to know how hard it would be to sort out) (@bluefuton)

This is currently a wontfix, but worth investigating in the future. It'll likely require us to figure out how to [enqueue the theme's frontend CSS](https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/script-loader.php#L2275) directly onto the wp-admin section.

> The light/dark images are missing an image description (a11y). (@bluefuton)

Fixed — improved aria labels for the theme selector component.

> On mobile, the page has no title (@bluefuton)

This is the standard pattern from Core. @keoshi, what do you recommend? Should we show the Jetpack Search title in the mobile viewport?

> On mobile, it's not totally clear what I have to do to get started customizing. Do we need some text to direct the user to the cog? (@bluefuton)

Again, this is the standard pattern from Core. @keoshi, what do you recommend here?

> UI does not appear in my chosen language (logged also for new wp-admin section #20757) - only selected strings are translated (@bluefuton)

My guess is that it's because the new strings from this interface have not yet been sent out for translations. IIRC, Glotpress will generate a list of translatable strings following a Jetpack stable release.

> The loupe icon is slightly nudged to the left (2px?) when any text is entered in the search input (@keoshi)

Fixed!

> The top bar that holds the “Jetpack Search” title has a grey-ish white background, and it should be white. (@keoshi)

Fixed!

> Turning off the “Powered by Jetpack” badge, the layout misbehaves in desktop and the bottom padding is set by the content on the left pane (search results) rather than the tallest pane (left or right). Maybe this was already true for the instant search layout? (@keoshi)

Fixed!

> The highlight color takes into consideration the text color, but not when changing to the Dark theme. Note how it behaves with the “june bud” swatch. Maybe this was already true for the instant search layout? (@keoshi)

The text color with the highlight is algorithmically determined to optimize for readability, so it won't take the theme selection into account. 

----

I'm still working on addressing feedback for the color control.

**Comment by jsnmoon** [comment]
> Color picker has a broken layout in French. The length of this text will vary between languages. Perhaps we could move the custom color link underneath?  (@bluefuton)

> The Search color picker has less vertical padding that Core's. Our of curiosity: are we reusing the original components or changing them in some way? My assumption was that we could simply add Core components, so I'd hate if we had to add exceptions. (@keoshi)

We were previously using a combination of ColorIndicator and ColorPalette components to mimic the experimental ColorGradientControl from the `@wordpress/block-editor` package.

I went ahead and replaced our existing implementation with the ColorGradientControl. I also populated the selectable colors using a default set of colors provided by Gutenberg.

Screen Shot 2021-08-23 at 5 39 38 PM

**Comment by bluefuton** [comment]
Thanks for the fixes! 🙌

I had a second run through on iPad and spotted some small issues.

- [ ] Are we missing an overlay trigger? I think we should have "when user submits form" in there too:

Screen Shot 2021-08-24 at 14 48 33

- [ ] We have a mixture of sentence case ("First second") and title case ("First Second") for form labels. Can we choose one and use it consistently? I think we've used sentence case elsewhere.

- [ ] In Safari, the color picker form label is a bit too tight to the picker itself and slightly overlaps it:

Screen Shot 2021-08-24 at 15 00 05

**Comment by annacmc** [comment]
This is so beautiful, you've done an amazing job here! I really enjoyed having a play around with it and seeing it all in action. 

One tiny _(possibly inconsequential)_ detail I noticed in testing is that there is a range between breakpoints when resizing the window where there are no filters displayed nor is there a filter drop down menu item. So if you resize your window to this size, there's no way to see the filters in the demo. 

image

I tested this out in the customiser, and on a live site, and in both cases it normally flows smoothly between showing filters, to having the filter drop down, without any size in the middle which has neither. Here's a screencast of resizing from my end:
https://d.pr/v/Pu88Zc

**Comment by kangzj** [comment]
Hey Jason, Thanks for the awesome job 👍 

My findings are as follows.

- The sorting options is not in the right place, or this only happens for me?
image

- Translations: Had some investigation over this - I don't see any Customberg strings on [translate.wordpress.com](https://translate.wordpress.org/projects/wp-plugins/jetpack/), It seems the [build](https://plugins.trac.wordpress.org/browser/jetpack/trunk/_inc/build/instant-search?order=name) on .org is not up to date or broken, as I couldn't find `jp-search-configure-main.min.js` there.

- Could we choose either `customize` or `configure` code-wise just to be consistent?

**Comment by keoshi** [comment]
> This is the standard pattern from Core. @keoshi, what do you recommend?

> Again, this is the standard pattern from Core. @keoshi, what do you recommend here?

I'd honestly rather follow Core patterns to avoid building exceptions on top of it. If we feel passionate about any of these let me know and I'll open tickets in Core to get them fixed upstream.

> The text color within the highlight is algorithmically determined for readability, so it shouldn't take the theme selection into account.
>
> I'm actually a little curious why your example using #C9D377 results in differing text colors depending on the theme...

Yeah, those were exactly my thoughts. I remember we added that neat ability to algorithmically determine the best contrast, but the theme colors do seem to take precedence in this scenario.

**Comment by jsnmoon** [comment]
> Are we missing an overlay trigger? I think we should have "when user submits form" in there too (@bluefuton)

✅ Good catch. Added!

> We have a mixture of sentence case ("First second") and title case ("First Second") for form labels. Can we choose one and use it consistently? I think we've used sentence case elsewhere. (@bluefuton)

✅ We were using title-case for all form labels in the Customizer, but have applied casing inconsistently in Customberg.

This has now been fixed by converting all appropriate form labels to title-case. Controls under "Additional Settings" remain sentence-cased just like the Customizer.

> In Safari, the color picker form label is a bit too tight to the picker itself and slightly overlaps it (@bluefuton)

✅ Fixed; worth noting that this is also broken on Core. 

When testing this, ensure that you empty your Safari cache (`Develop -> Empty Caches`) to ensure that the updated stylesheet is being loaded.

> there is a range between breakpoints when resizing the window where there are no filters displayed nor is there a filter drop down menu item. So if you resize your window to this size, there's no way to see the filters in the demo. (@annacmc)

✅ Good catch. I went ahead and revamped breakpoint handling in Instant Search to better support Customberg's novel breakpoint requirements.

This should be fixed now, so give it another try!

> The sorting options is not in the right place, or this only happens for me? (@kangzj)

❓ I __think__ this should be fixed with the revamped breakpoint handling. Could you give it another try with the latest code?

If this bug is still occurring, could you tell me what browser and viewport size you're using? I've been having difficulties reproducing this, unfortunately.

> I don't see any Customberg strings on translate.wordpress.com, It seems the build on .org is not up to date or broken, as I couldn't find jp-search-configure-main.min.js there. (@kangzj)

❓ I'm pretty sure that the strings aren't sent to Glotpress for translation until some sort of a release (e.g. beta or official releases).

> Could we choose either customize, configure or customberg code-wise just to be consistent? (@kangzj)

✅ Good point. I went ahead and removed all references of "customize" and standardized to "configure". I left the folder path and the PHP class with references to Customberg, which should improve code navigation since "customberg" is much easier to search than "configure".

**Comment by jsnmoon** [comment]
Note to future reviewers: Customberg now lives on `/wp-admin/admin.php?page=jetpack-search-configure` instead of `/wp-admin/admin.php?page=jetpack-search-customize`! Original post has been updated.

**Comment by kangzj** [comment]
>❓ I think this should be fixed with the revamped breakpoint handling. Could you give it another try with the latest code?
I can confirm it's working fine now. Thanks.

>❓ I'm pretty sure that the strings aren't sent to Glotpress for translation until some sort of a release (e.g. beta or official releases).

Ah I see. I had another look, as we've already have the first PR merged in `master`, there should be some of strings already. But there aren't any, because we didn't reference the components which have the strings - [no strings at all in the target file](https://plugins.trac.wordpress.org/browser/jetpack/trunk/_inc/build/instant-search/jp-search-configure-main.bundle.js), which is probably the reason (and also a different name) we don't have any translations available yet if that makes sense.

There shouldn't be any problem on our side then since this PR is going to be built and synced to Glotpress afterwards. Good job.

**Comment by annacmc** [comment]
> Good catch. I went ahead and revamped breakpoint handling in Instant Search to better support Customberg's novel breakpoint requirements. This should be fixed now, so give it another try!

I think it's improved from previously, but I'm still seeing no filter options between 1000 - 1200px. I've tried rebuilding and cache clearing, but it hasn't resolved yet. Is there anything else I need to do to ensure I'm seeing these changes correctly?

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Review by keoshi — APPROVED** [review]
Looks great to me!

**Pull request merged**
