### PR TITLE
Remove "login" from Jetpack

### PR DESCRIPTION
**Pull request by MichaelArestad**
Removes "login" from Jetpack.

#### Before
image

image

#### After
image

image

### CODE REVIEW

**Comment by rickybanister** [comment]
There are no images in the pr 📦

**Comment by MichaelArestad** [comment]
@rickybanister what the hay? I added them after I created it, but I must have spaced clicking the save button... Adding/

**Comment by MichaelArestad** [comment]
@rickybanister added

**Comment by rickybanister** [comment]
looks 🥚 cellent

**Pull request merged**
