### PR TITLE
Premium Content Block: Add missed blockprops change

### PR DESCRIPTION
**Pull request by apeatling**
Follow up to https://github.com/Automattic/jetpack/pull/19844

#### Changes proposed in this Pull Request:

* Replace the experimental block with blockProps.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Insert a premium content block in a post, and confirm it looks and works correctly.
* Use an existing post with a premium content block, and confirm it continues to work correctly.
* Publish a post with the block and confirm it works on the front end.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Tests well for me.

Check editor and frontend before and after connecting stripe. All worked as expected.

Screen Shot 2021-05-20 at 10 12 17 am
Screen Shot 2021-05-20 at 10 12 31 am
Screen Shot 2021-05-20 at 10 13 50 am
Screen Shot 2021-05-20 at 10 14 16 am

**Review by jeherve — COMMENTED** [review]
I get a validation error on my end when trying to edit an existing block on WordPress.com Simple:

image

**Comment by ramonjd** [comment]
> I get a validation error on my end when trying to edit an existing block on WordPress.com Simple:

Ah thanks for noticing that. Looks like we'll need a deprecation?

**Comment by jeherve** [comment]
> Looks like we'll need a deprecation?

I believe so, yes.

**Comment by apeatling** [comment]
@jeherve Was that premium content button added using my previous PR? https://github.com/Automattic/jetpack/pull/19844

It seems to be a deprecation notice complaining about the buttons block, which is not changed in this PR. There is a deprecation that handles that, but this looks to be in reverse.

**Review by jeherve — APPROVED** [review]
That must have been it. It looks good to me on second try!

**Comment by jeherve** [comment]
r226548-wpcom

**Pull request merged**
