### PR TITLE
Contact Form: deprecate old temporary filter

### PR DESCRIPTION
**Pull request by kraftbj**
When looking through the code for something else, I found this undocumented filter (in the package) and the documentioned version in the module. It was always marked as temporary and noted that it would be removed around Jetpack 5.8, some 73 or so releases ago.

## Proposed changes:

* Mark the filter as officially deprecated so we can remove it later.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* None needed, but make sure the admin view still works if you want to!

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
I did a quick check in opengrok and wpdirectory. No references in opengrok other than this itself. wpdirectory turned up two plugins using it:

* https://plugins.trac.wordpress.org/browser/so-widgets-bundle/tags/1.58.3/so-widgets-bundle.php#L85
* https://plugins.trac.wordpress.org/browser/my-calendar/tags/3.4.23/my-calendar-core.php#L1961

I have no idea if we want to do anything about them, I'm just pointing it out.

**Comment by jeherve** [comment]
> No references in opengrok other than this itself. wpdirectory turned up two plugins using it:

That's a good catch. 

- For the first plugin, it looks like the filter was used to fix a bug, discussed in https://github.com/siteorigin/so-widgets-bundle/issues/528
- For the second plugin, it looks like it was added before the plugin was made open source ([see initial commit with the filter here](https://github.com/joedolson/my-calendar/commit/affe8d1969bdcea692f0a34e0c8c22d20a609337#diff-0f74d5a66644cdd1e5cc7247bfcb1f659e8853778e5b9e75a13ecaf8906eaa05)) so we would have to reach out to find out more.

I think it may be interesting to figure out if the filter is used on VIP sites, too. I asked in p1707733467258789-slack-CDD9LQRSN

**Comment by jeherve** [comment]
Maybe we could deprecate it first, before we remove it, just to avoid any bad surprises?

**Comment by kraftbj** [comment]
> Maybe we could deprecate it first, before we remove it, just to avoid any bad surprises?

That's fair. I'll update the PR to do that for the time being.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
