### PR TITLE
Boost: Add more context to api fetch error

### LINKED ISSUE #20946: Boost: Add more context to errors happening while doing API fetch calls
The following error was reported 2 times on the Jetpack Boost support forum (([here](https://wordpress.org/support/topic/critical-css-failed-to-fetch/) and [here](https://wordpress.org/support/topic/failed-to-generate-critical-css-7/))) when a user tried to generate Critical CSS.

```
Failed to generate Critical CSS
Hmm, looks like something went wrong. We’re still seeing an unexpected error. Please reach out to our support to get help.

Hide error message
TypeError: Failed to fetch
```

Unfortunately, this error is quite obscure and difficult to know the cause. As a result, there is a need to provide more context to this error.

### PR DESCRIPTION
**Pull request by davidlonjon**
Fixes #20946

#### Changes proposed in this Pull Request:

The following error was reported 2 times on the Jetpack Boost support forum ((here and here)) when a user tried to generate Critical CSS.

```
Failed to generate Critical CSS
Hmm, looks like something went wrong. We’re still seeing an unexpected error. Please reach out to our support to get help.

Hide error message
TypeError: Failed to fetch
```

Unfortunately, this error is quite obscure and difficult to know the cause. 

Originally I thought that this error was caused by a fetch call in the code from the [jetpack-boost-critical-css-gen](https://github.com/Automattic/jetpack-boost-critical-css-gen) repo [here](https://github.com/Automattic/jetpack-boost-critical-css-gen/blob/trunk/lib/browser-interface-iframe.js#L87) or [here](https://github.com/Automattic/jetpack-boost-critical-css-gen/blob/trunk/lib/css-file-set.js#L57) but after some tests, it seems that as these fetch calls surrounded by a try/catch statement and the error repurposed, then the error cannot come from here.

The other place where the error may come from is the [fetch call in the api.ts](https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/assets/src/js/api/api.ts#L34) file from the Jetpack Boost plugin. Possible errors with this call are caught at a higher level and only the error itself is captured. As a result, if it failed as reported we only get the `TypeError: Failed to fetch` message displayed to the user for reporting but it is not really useful. 

With the PR I am attempting to catch the error when the call is done, create a more useful error with extra context to it so it can be displayed to the user and provide more information to us when reported.

image

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

It is difficult to test because this error as I actually could not work out the cause for it. But there is a way to 'kind of' simulate it.

* In this PR change [line 39 of the api.ts file](https://github.com/Automattic/jetpack/blob/improve/add-more-context-to-api-fetch-error/projects/plugins/boost/app/assets/src/js/api/api.ts#L39) from
```
const endpointFullUrl = getEndpointUrl( path );
```

to 
```
let endpointFullUrl = getEndpointUrl( path );
	if ( path.includes( 'success' ) ) {
		endpointFullUrl = endpointFullUrl.replace( '://', '://admin.' );
	}
```

* Regenerate Critical Css 
* See a more detailed error message being displayed than just `TypeError: Failed to fetch`

### CODE REVIEW

**Review by eAdnan007 — DISMISSED** [review]
Looks good to me. Should it be a minor or patch though? (Regarding changelogger)

**Review by thingalon — DISMISSED** [review]

**Comment by thingalon** [comment]
Oh, just noticed @eAdnan007's point. It should be a patch change - we'll want to release this as 1.2.1 so we can help the users affected by these unknown errors.

**Comment by davidlonjon** [comment]
Thank you @eAdnan007 for looking at it and catching the changelog.

Updated it now in the 7fccce2a350ea70aa9d73dfec56afafa23b40a6f commit.

**Review by thingalon — APPROVED** [review]
👍

**Review by eAdnan007 — APPROVED** [review]

**Pull request merged**
