### PR TITLE
Packages: enable autotagger for packages

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Follow-up from #19238 to enable autotagging (tagging new package releases in the mirror repos when a new release is available for that package) for more packages.

#### Jetpack product discussion

* p1617119943221100-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Check the output of the Build workflow, the new action should be present for these projects.
* Once this is merged, check that the mirror repos did not auto-tag (I already manually tagged all releases for those packages).
* When we do do a release, the mirror repos should get correctly tagged.

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Looks good once you finish fixing the linting issues.

* Only Jetpack accepts "compat", everything else uses the subheadings defined by keep-a-changelog.
* Monorepo root composer.lock needs updating too.

**Review by anomiex — APPROVED** [review]
Looks ok, assuming CI is happy with it

**Comment by jeherve** [comment]
Sorry about that PR, I was multitasking yesterday and not paying enough attention obviously. I should know better. It should be better now, indeed.

**Comment by jeherve** [comment]
Had to update more version numbers, so this will need another review.

**Review by anomiex — APPROVED** [review]

**Pull request merged**
