### PR TITLE
Fix 1302 Sharing: Added dailymotion screenshots to Open Graph meta tags

### LINKED ISSUE #1302: Sharing: add Dailymotion screenshots to Open Graph meta tags
Jetpack currently automatically generates images for both Vimeo and Youtube videos, but not from Dailymotion.

It'd be a nice addition.

Suggested here:
https://wordpress.org/support/topic/problem-to-share-dailymotion-video-on-facebook?replies=1

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
Fix #1302

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Review was completed by @zinigor on #1302

**Comment by samhotchkiss** [comment]
Per an internal discussion, we've decided not to include dailymotion at this point due to their small marketshare.  We can re-evaluate down the road if this is a widely requested feature.

**Comment by PatelUtkarsh** [comment]
Great! Thank you for your time.

**Comment by samhotchkiss** [comment]
@PatelUtkarsh -- @zinigor made some good arguments, and we've agreed to reconsider and include this into 3.7 -- Thanks for submitting it!

**Pull request merged**
