### PR TITLE
Fix/banner styles - fixes #2031

### LINKED ISSUE #2031: Manage: Activate Now button isn't pretty in smaller viewports
We should make this button look nicer:
screen shot 2015-04-27 at 8 32 42 am
screen shot 2015-04-27 at 8 34 00 am
cc @jeffgolenski

### PR DESCRIPTION
**Pull request by jeffgolenski**
As documented in https://github.com/Automattic/jetpack/issues/2031, the "activate now" banner for activating Jetpack Manage is displayed on the dashboard, has some visual issues on certain screen sizes. 

I fixed this + tidied up some of the css, and also fixed an issue with the underlines that were occurring on certain devices as well.

BEFORE:
image

image

screen shot 2015-04-28 at 6 44 57 pm

image

AFTER:

screen shot 2015-04-28 at 7 35 35 pm

image

### CODE REVIEW

**Comment by georgestephanis** [comment]
:+1: 

Should be good for the point release.

@samhotchkiss -- are you okay with rolling this in to the next beta?

**Comment by jeffgolenski** [comment]
Thanks @georgestephanis

**Comment by dereksmart** [comment]
Tested, looks great. :+1:

**Comment by zinigor** [comment]
Read the changes, tested, looks good, merging!

**Pull request merged**
