### PR TITLE
Remove not used Gravatar subdomain

### PR DESCRIPTION
**Pull request by unDemian**
## Proposed changes:

* Update `en.gravatar.com` url to `gravatar.com` the `en` subdomain has been removed and is redirecting to the main domain as per pMz3w-iie-p2 

Should be deployed after D123925-code which temporarily fixes the failing test

## Testing instructions:
* Code looks good
* Gravatar user profile (in CRM?) and hovercards work as expected

### CODE REVIEW

**Comment by jcheringer** [comment]
The code looks good, @unDemian!
But I couldn't find a way to test it properly.
Is there a way to see the changes in action?

**Review by kraftbj — APPROVED** [review]

**Comment by unDemian** [comment]
@kraftbj thanks for the review and merge, I'm still not sure based on the new sun-moon flow if I need to do anything or this will land in wpcom with the next daily deploy.

**Comment by kraftbj** [comment]
No action needed. It'll go out with the next daily deploy.

**Comment by unDemian** [comment]
Thank you

**Pull request merged**
