### PR TITLE
i18n-check-webpack-plugin: Allow specifying the expected textdomain

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

If the textdomain used is not the expected domain, raise an error.

Then set this in our webpack-config based on the contents of
composer.json, to help ensure that plugins and packages actually use the
expected domain.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Edit `projects/plugins/backup/babel.config.js` to set the domain to something other than "jetpack-backup", and see if a production build fails with the appropriate error.

### CODE REVIEW

**Comment by sdixon194** [comment]
So this does error out for me, but I don't think this stderr is what we were looking for, right? 

```
  stderr: '> Composer\\Config::disableProcessTimeout\n' +
    '> pnpm run build-production-concurrently\n' +
    'Script pnpm run build-production-concurrently handling the build-production event returned with error code 1',```

**Comment by anomiex** [comment]
It could be. If you look in the stdout field you should see something like 
```
    '[1] \n' +
    '[1] ERROR in index.js: Expected textdomain "jetpack-backup", but the asset uses "not-jetpack-backup" instead.\n' +
    '[1] You may want to use @automattic/babel-plugin-replace-textdomain to fix that.\n' +
    '[1] \n' +
    '[1] webpack 5.64.1 compiled with 1 error in 5757 ms\n' +
    '[1]  ELIFECYCLE  Command failed with exit code 1.\n' +
    '[1] NODE_ENV=production BABEL_ENV=production pnpm run build-client exited with code 1\n' +
    ' ELIFECYCLE  Command failed with exit code 1.',
```

**Comment by sdixon194** [comment]
Ah I see it now, it was quite buried in there.

**Review by sdixon194 — APPROVED** [review]

**Comment by anomiex** [comment]
r237072-wpcom

**Pull request merged**
