### PR TITLE
JS Components: Add Mastodon icon

### PR DESCRIPTION
**Pull request by fmfernandes**
## Proposed changes:

* This PR adds a new Mastodon icon.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* pewaj1-3x-p2.

## Does this pull request change what data or activity we track or use?

* No.

## Testing instructions:

* The icon is not being used yet, but there's some instructions on how to test this on pewaj1-3x-p2. The icon should also appear on the sharing sidebar:
image

* It is possible to check the new icon by checking out this branch, then running `cd projects/js-packages/storybook && pnpm run storybook:dev`.

* Initially, as can be seen on the image, the icon will not have the Mastodon color (#6364ff) but it was added on https://github.com/Automattic/wp-calypso/pull/72876. We'll need to update the package's version and dependency version on Jetpack as well.

### CODE REVIEW

**Comment by fmfernandes** [comment]
cc'ing @retrofox for visibility as you appeared on `git blame` for those files 🙂

**Review by jeherve — DISMISSED** [review]
The icon looks good, this should be good to merge!

I created #29020, so that in the future we can consider pulling our own logos from the Automattic/social-logos.

**Review by retrofox — DISMISSED** [review]
LGTM 🚢 
Screen Shot 2023-02-17 at 10 35 33

**Comment by fmfernandes** [comment]
Hi @jeherve, @retrofox 👋🏻 

I've had to update the branch with `trunk` as there was a conflict preventing merge. Could you please review again? 

Thanks!

_Would `rebase` prevent your reviews from being dismissed?_

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
> Would rebase prevent your reviews from being dismissed?

*merge* would, *rebase* will always dismiss reviews.

**Pull request merged**
