### PR TITLE
Boost: Fix UI issues

### PR DESCRIPTION
**Pull request by haqadn**
## Proposed changes:

* Fix alignment, consistency and formatting for link buttons:
  * Button icon spacing (Speed Score refresh, C.CSS Regenerate, Exclude UI buttons, Image CDN expand/collapse buttons, ISA UI button)
  * Icon spacing for ISA summary paragraph;
  * Image CDN image quality icon spacing;
  * Speed score title adjustment:
    * Reduce font size on mobile (like 2.2.1 Boost).
    * Move tooltip icon outside title element;
    * Adjust position of tooltip on mobile.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pedxs5-mg-p2#comment-219
pedxs5-mg-p2#comment-233

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Make sure UI isn't broken on Desktop and Mobile.

### CODE REVIEW

**Review by dilirity — DISMISSED** [review]
## Addressed

The alignment for the ISA "Analyze again" icon is off compared to the rest (for example C.CSS).

CleanShot 2024-01-29 at 14 42 12

### C.CSS Regenerate

CleanShot 2024-01-29 at 14 42 23

~Shouldn't all buttons use the same component so we don't have these alignment issues?~ They already use the same markup, so no component is necessary.

~This is still a problem - pedxs5-mg-p2#comment-222~ I see this is ticketed in https://github.com/Automattic/jetpack/issues/35292

EDIT:

I've updated the description to include a list of changes.

**Comment by dilirity** [comment]
## Addressed

Score tooltip is over the ( i ) icon on mobile.

CleanShot 2024-01-29 at 14 52 12

**Review by thingalon — APPROVED** [review]
Nice; the details make a difference to the overall look of the page, and the changes look good to me 👍

**Comment by thingalon** [comment]
Cherry-picked to 3.0.0 in dd216ed0a4.

**Pull request merged**
