### PR TITLE
Connection: Add ConnectionErrorNotice React Component

### PR DESCRIPTION
**Pull request by chrisbliss18**
#### Changes proposed in this Pull Request:
Add the `ConnectionErrorNotice` React component to display connection verified errors. This is part of a bigger project (1202697549597858-as) to provide consistent failed connection error reporting and an interface to reconnect (1202697549597858-as-1202697549597864). 

The changes will affect the following:
* Jetpack
* Connection

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
* p9dueE-5w8-p2

#### Does this pull request change what data or activity we track or use?
* No

#### Testing instructions:
* Run `jetpack build packages/my-jetpack`.
* Enable the "Jetpack Debug Tools" plugin.
* Go to Jetpack Debug > Jetpack Debug.
* Enable "Broken token Utilities" and click "Save".
* Go to Jetpack Debug > Connection Errors
* Under "Create fake errors", select "With the blog token", select "Verified", and click the "Create error" button.
* Go to Jetpack > My Jetpack.
* You should see an error message as shown in the below screenshot:
jetpack-connection-error-example

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @chrisbliss18.

I added a couple of edits to your PR, please review:
1. The errors coming from the initial state are objects inside an array inside an object (🤯). So I [modified](https://github.com/Automattic/jetpack/pull/26259/commits/7932e486d1783c8bbce9374bc7f4d2510baa3feb#diff-3a2b64f97b466ed5a751d8eae7c9e74041a7e07ee6a268257b3112706e09946aR16-R27) the code to accommodate that.
2. [Renamed](https://github.com/Automattic/jetpack/pull/26259/commits/7932e486d1783c8bbce9374bc7f4d2510baa3feb#diff-1ff38acc2e7fd6668a17e4e3a3e0f572d5d41eb3fd8b9a911392e5f85fd52a56R41) the initial state key to match the selector/dispatcher.

Everything else looks good and works well.

**Comment by chrisbliss18** [comment]
Thanks for the fixes @sergeymitr. I wasn't aware of the complex nature of these messages. The changes mean that my testing instructions no longer work. Do you have a new way to test that is valid with these changes?

Edit: I was able to update the testing instructions to work with the changes.

**Comment by nunyvega** [comment]
@chrisbliss18 testing instructions updated.
edit: the instructions that I added also don't work, a different message without the reconnect option was displayed. I reverted back to your testing instructions.

I'll focus in the styling in a follow-up PR.

**Comment by chrisbliss18** [comment]
Sorry about that @nunyvega. I was able to update the testing instructions to work with the changes @sergeymitr made and failed to update my comment indicating as such. Are you able to successfully execute the current testing steps?

**Comment by nunyvega** [comment]
@chrisbliss18 since the component was removed [here](https://github.com/Automattic/jetpack/pull/26259/commits/7b546aeb3b37c7a683c42517e1ab57e42b965fd7), it is not visible anymore. 

If I revert that change, I can see it, the Restore connection button is there, but the link does not work. 

Is this intended?

**Comment by chrisbliss18** [comment]
@nunyvega The non-functional link is intentional. The functionality of that link is part of another task/PR, which is what resulted in pulling the integration from My Jetpack for now.

**Review by sergeymitr — APPROVED** [review]
👍

**Comment by sergeymitr** [comment]
r252785-wpcom

**Comment by chrisbliss18** [comment]
r252785-wpcom

**Pull request merged**
