### PR TITLE
Cover Block: Remove the upgrade banner

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/view-design/issues/210

#### Changes proposed in this Pull Request:

* Remove the upgrade banner notice for video backgrounds. This is confusing users because it makes the whole cover block seem as though it is a premium block.

| Before      | After |
| ----------- | ----------- |
| 106206346-c1c5d300-6174-11eb-9de2-50b16004c872 | Screen Shot 2021-01-28 at 2 47 32 PM |

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Unfortunately this change won't work with the Jetpack sync to sandbox, so you will need to manually remove: `projects/plugins/jetpack/extensions/extended-blocks/core-cover/core-cover.php` from your sandbox and reload the page.

Confirm that you do not see the upgrade banner when the block is selected.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Review by andrewserong — DISMISSED** [review]
Works nicely, confirmed that the `UpgradePlanBanner` is no longer displayed in the inspector controls for the cover block while on a Free site, and that the cover block still works as expected on a Premium site. Double-checked the loader in [class.jetpack-gutenberg.php](https://github.com/Automattic/jetpack/blob/83241dba4e7a4899332b86d40f73e8093c9e0079/projects/plugins/jetpack/class.jetpack-gutenberg.php#L758) that it's safe to remove PHP files in `extended-blocks` without causing issues 👍

**Comment by aaronrobertshaw** [comment]
This tests well for me 👍 

Cover block works as expected on both free and premium site. Checked deleting both file and the `core-cover` extended block directory. Lines up with the [loader](https://github.com/Automattic/jetpack/blob/83241dba4e7a4899332b86d40f73e8093c9e0079/projects/plugins/jetpack/class.jetpack-gutenberg.php#L758) as per Andrew's comment.

Screen Shot 2021-01-29 at 11 01 21 am

**Review by jeherve — CHANGES_REQUESTED** [review]
Wouldn't it be better to have the sidebar banner behave like the block banner, and only show up when you try to upload videos?
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/shared/plan-utils.js#L101-L114

image

**Comment by apeatling** [comment]
I think it still looks too much like the block is a premium block -- users are probably blind to the actual message in the banner. The banner needs to be more selective on adding a video background.

**Comment by jeherve** [comment]
> I think it still looks too much like the block is a premium block -- users are probably blind to the actual message in the banner. The banner needs to be more selective with the messaging on adding a video background

It only shows when you try to upload a video though, so I think by that point, it's quite clear for site owners that they need to upgrade if they want to upload videos.


https://user-images.githubusercontent.com/426388/106459346-01046480-6492-11eb-93f9-c01836f2fb81.mov

Maybe we should only remove the upgrade nudge from the block sidebar, or only add it when necessary like for the main upgrade nudge?

**Comment by apeatling** [comment]
I've gone ahead and removed editor sidebar upgrade nudges for two reasons:

1. Their click through rate is low compared to the canvas banners. See tracks event `jetpack_editor_block_upgrade_click` on property `context`.
2. They are superfluous with the canvas banner, there is no way to miss that banner so seeing them in the sidebar is unnecessary. 

The video upload nudge has been added back. :+1:

/cc @ianstewart

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
@apeatling When do you think you could commit the matching WordPress.com diff? Thank you!

**Comment by jeherve** [comment]
r221694-wpcom

**Pull request merged**
