### PR TITLE
VideoPress: Add settings to the React interface

### PR DESCRIPTION
**Pull request by rcoll**
#### Changes proposed in this Pull Request:

Removes stale VideoPress settings. Creates some modifications to the VideoPress React settings to make them compatible with Jetpack plans, and only active with the use of a plan.

#### Testing instructions:

* Apply this PR to a clean master branch, build, and test on a site without a Jetpack plan.
* Apply this PR to a clean master branch, build, and test on a site with a Jetpack plan.
* Ensure the interface is clean and all links work on both sites.
* Ensure the interface changes when a plan is purchased for a site.

#### Screenshots:

Interface without a Jetpack plan:
a85fbcda-a203-11e6-90d8-90609bf4512d

Interface with a Jetpack plan:
ae80e3f0-a203-11e6-8ef5-60d4242fc9f0

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If [Gulp](http://gulpjs.com/) is installed on your testing environment, run `gulp js:hint` before to commit your changes. It will allow you to [detect errors in Javascript files](http://jshint.com/about/).
- [x] Did you create a **new action or filter**? [Add inline documentation](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters) to help others understand how to use the action or the filter.
- [x] Create **[unit tests](https://github.com/Automattic/jetpack/tree/master/tests)** if you can. If you're not familiar with Unit Testing, you can check [this tutorial](https://pippinsplugins.com/series/unit-tests-wordpress-plugins/).

### CODE REVIEW

**Comment by rcoll** [comment]
Fixes issues with original PR: https://github.com/Automattic/jetpack/pull/5233

**Comment by jeherve** [comment]
#5457

**Comment by samhotchkiss** [comment]
Looks good, although it's not currently showing in any of the sections.  @zinigor, I'm assuming this will be fixed when you finish the UI updates?

**Comment by zinigor** [comment]
Yes, I'll roll this into the Settings UI update, please don't merge yet.

**Comment by rcoll** [comment]
@MichaelArestad is mocking this up shortly, it will be rolled into the Media group in Writing.

**Comment by MichaelArestad** [comment]
Quick mockup. Working on an active state.

**Comment by dbtlr** [comment]
I did a quick rebase to test this. Still don't see it in the settings. Will test again later :)

**Comment by samhotchkiss** [comment]
@zinigor -- #5553 is merged, and it looks like this is still clear to go.

I'll let you merge at will

**Comment by rcoll** [comment]
Rebase is clean, and this still tests good after #5553. I think the action of the "SET UP" button is a bit strange for this module, but works the same as the button for "Scanner". That's probably a conversation for a different time, but both buttons are equally as confusing since there are no longer any options.

We should be ready for merge here.

**Pull request merged**
