### PR TITLE
Record meter: format the numbers in each bar entry.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Related: #24810

Let's use formatted numbers whenever possible, it looks better with bigger numbers.

**Before**

Screen Shot 2022-06-22 at 15 15 46

**After**

Screen Shot 2022-06-22 at 15 24 45

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start with a site with a Jetpack Search plan, and with more than 1,000 posts.
* Go to `yoursite.com/wp-admin/admin.php?page=jetpack-search&features=record-meter`
* Notice that the post count is now formatted.

### CODE REVIEW

**Comment by jeherve** [comment]
Hm, the tests are failing. :(

https://github.com/Automattic/jetpack/runs/7005046172?check_suite_focus=true

```
FAIL components/record-meter-bar/test/component.tsx
    ● Test suite failed to run
  
      Jest encountered an unexpected token
  
      Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
  
      Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
  
      By default "node_modules" folder is ignored by transformers.
  
      Here's what you can do:
       • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
       • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
  
      You'll find more details and examples of these config options in the docs:
     [ https://jestjs.io/docs/configura](https://jestjs.io/docs/configuration)
      For information about custom transformations, see:
     [ https://jestjs.io/docs/code-transforma](https://jestjs.io/docs/code-transformation)
  
      Details:
  
      /home/runner/work/jetpack/jetpack/projects/js-packages/components/components/number-format/index.ts:1
      ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { getUserLocale } from '../../lib/locale';
                                                                                        ^^^^^^
  
      SyntaxError: Cannot use import statement outside a module
```

I'm not sure how to go about fixing this. @Automattic/jetpack-agora Could I get some help on this one? Do I need to import `numberFormat` differently, even though it's just another component?

Thank you!

**Comment by anomiex** [comment]
Add `'.ts'` to https://github.com/Automattic/jetpack/blob/5d48d3c7a6e18022bc29efacb601d8195c482b45/projects/js-packages/components/jest.config.cjs#L5

Apparently nothing tried to require a `.ts` file from a test before, so we didn't notice that was missing.

**Review by samiff — APPROVED** [review]
Worked well for me even with larger numbers (multiple commas).

**Comment by annacmc** [comment]
🚢 shipped in r247852-wpcom

**Pull request merged**
