### PR TITLE
Recommendations: improve usability of Recommendations' dismiss options

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

This PR aims to make it easier for site owners to understand that they can dismiss the Recommendations banner appearing on their site after a successful connection to WordPress.com:
﻿- I've added a "dismiss" text next to the existing dismiss icon.
﻿- I've restyled that dismiss option based on the discussions below.
- ~~I've added a new "Not now" option to the main banner.~~

**Before**

image

**After**

image

#### Jetpack product discussion

* p1614892057083100-slack-C0299DMPG

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Connect a brand new Jetpack site to WordPress.com.
* When coming back to your site post-connection, go to the Plugins page or the main dashboard page.
* Check banner and try to use one of the dismiss options
    * The banner should remain dismissed.

### CODE REVIEW

**Review by leogermani — DISMISSED** [review]
tested following the instructions and it worked as expected

**Comment by leogermani** [comment]
Just checking

Captura de Tela 2021-03-16 às 11 39 30

Should the "dismiss" label be vertical aligned with the button? Do we have guidelines for that?

**Comment by jessefriedman** [comment]
@jeherve thank you for jumping on this.  Can we darken the "X" so it's a bit more contrasting? 
Also, this may require a second PR but I think it'd be good if we could shave off 50 vertical pixels to make the banner a tad smaller.  

The text that reads: "All of Jetpack's features..." 
I'd like to replace with: "The following Jetpack recommendations are available to you later in the Jetpack dashboard" 

The "dismiss" text in the top right and the "Non now" look good to me too.  Thank you!

**Comment by jeffgolenski** [comment]
### Dismiss icon

@jeherve Thanks for jumping into this Jer! I'm here to complicate the issue! Just kidding. The original close icon for assistant was actually never realized during development, so the default wp-admin was used in its stead.

If possible, I'd like to switch that dismiss icon. It's currently a dashicon, but dashicons are [no longer being updated](https://make.wordpress.org/core/2020/07/15/dashicons-in-wordpress-5-5-the-final-update/). The future is the material icons being used within the block editor. I'd love to use the dismiss icon from material. If not, we can still use the dashicon.
 

**How the current dismiss icon looks on various screen sizes**
assistant-current-dismiss-icon


**Proposed dismiss icon with text at various screen sizes**

Screen Shot 2021-03-16 at 4 52 28 PM



assistant-proposed-dismiss-icon

* "Dismiss" should be vertically centered with the icon
* Icon + text color: Gray 70 from our [color studio](https://github.com/Automattic/color-studio)
* Icon + text hover: on `:hover` & `:active` let's change it to gray 100 and underline the text

Screen Shot 2021-03-16 at 4 59 21 PM


Currently, we have different breakpoints built for the assistant to accommodate different screen sizes. I don't anticipate too much complication here, but for mobile, I'd like us to keep the dismiss icon in line with the logo.

Screen Shot 2021-03-16 at 4 51 38 PM

### Details about the design patterns used within Jetpack

* Throughout Jetpack products moving forward, we should always be using an 8px scale to space elements—every single one of them. 8px, 16, 24, 32, 48, etc.
* Colors should always come from our [color studio](https://github.com/Automattic/color-studio)

### "Not now" link

This is important. The "not now" link **should not display on the banner that resides in the dashboard of wp-admin**, but it should reside in the banner that lives under the recommendations tab within Jetpack.

The dismiss icon exists to serve that purpose, so "not now" is a redundant link. Let's try not to bloat the banner here. 

**Flow detail**

The first step of the banner exists in two locations and has different functionality. When displayed on the wp-admin dashboard it should be dismissible. When it's displayed under the "recommendations" tab it should not be dismissible. 

Screen Shot 2021-03-16 at 5 05 23 PM

### Overall spacing

Screen Shot 2021-03-16 at 5 09 09 PM


@jessefriedman Just as a friendly FYI, we shouldn't be changing spacing in increments of 10, everything is based on an 8px grid. I see that the spacing of the live assistant is a little quirky, but it's being increased by the content. We need to alter the content to alter the size of the banner, and probably clean up some rogue pattern and margins throughout. 

That being said, the Assistant also scales to meet different screen-sizes, so it's not going to look the same on every screen, and that's okay. 

cc @leogermani  @jessefriedman

**Comment by jeffgolenski** [comment]
Here's the optimized code for the dismiss svg, if we can't pull it from the block editor

`<svg xmlns="http://www.w3.org/2000/svg" width="25" height="24" viewBox="0 0 25 24" fill="none"><mask mask-type="alpha" maskUnits="userSpaceOnUse" x="2" y="2" width="21" height="20"><path d="M12.5 2C7 2 2.6 6.5 2.6 12 2.6 17.5 7 22 12.5 22 18 22 22.5 17.5 22.5 12 22.5 6.5 18 2 12.5 2ZM15.1 8L12.5 10.6 9.9 8 8.5 9.4 11.1 12 8.5 14.6 9.9 16 12.5 13.4 15.1 16 16.5 14.6 13.9 12 16.5 9.4 15.1 8ZM4.6 12C4.6 16.4 8.1 20 12.5 20 16.9 20 20.5 16.4 20.5 12 20.5 7.6 16.9 4 12.5 4 8.1 4 4.6 7.6 4.6 12Z" fill="white"/></mask><g mask="url(#mask0)"><rect x="0.6" width="23.9" height="24" fill="#1E1E1E"/></g></svg>`

**Comment by jeffgolenski** [comment]
Just leaving a note here: @jeherve and myself sync'd this morning and I'm going to try and implement these changes next week!

**Comment by folletto** [comment]
> The dismiss icon exists to serve that purpose, so "not now" is a redundant link. Let's try not to bloat the banner here.

+1 on this. 

Let's first change just the × Dismiss at the top, that should be enough for any concern. Also because it matches other WP Admin interactions.

**Comment by jeffgolenski** [comment]
@jeherve As we're getting closer to code freeze, I just wanted to let you know I may not get to this in time due to my primary projects. I'll do my best, but may have to revisit it for the next release cycle.

**Comment by jeffgolenski** [comment]
Thanks for your help today @jeherve — like I mentioned earlier, I just cleaned up some of the structure and styling that will allow for proper scaling on various screen sizes. Can you give this a test and let me know how it works for you?

Here's a quick video with the changes in action:
https://user-images.githubusercontent.com/214813/112538100-e5c51f80-8d85-11eb-84e8-e1a4044e67d8.mp4

Something of note: 
I noticed a bit of css and scaling with the images that should be addressed in the different PR. I think we can clean up that image jumping that you see in the video above, but it'll require a rebuild.  It probably won't make code freeze, but I'll revisit and clean that up in a subsequent release!

**Review by jeherve — COMMENTED** [review]
This tests well for me. I'll let another Crew member review this; since it's my PR I cannot approve it myself.

**Comment by keoshi** [comment]
@jeffgolenski That looks really great to me. The new version is so classy — ship it! 🚀

**Review by keoshi — APPROVED** [review]

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
