### PR TITLE
Fix exceeding search limits in Jetpack Complete

### PR DESCRIPTION
**Pull request by trakos**
#### Changes proposed in this Pull Request:

A site that has Jetpack Complete with exceeded Jetpack Search limits cannot use the instant search feature.
We should not allow toggling the instant search option, the same way we don't allow it for Jetpack Search Free that is over limit.

In the past, `must_upgrade` didn't check for the plan that blog has, but now it's safe to base the decision to disable instant search option only on that parameter.

Additionally, I've added one final CTA that's shown to both Jetpack Search Free and Jetpack Complete users once their search plan is disabled after three months of overages:

image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion
panfyZ-1wq-p2#comment-3810

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

A8C-only:

- Purchase Jetpack Complete for your blog.
- Apply sticker `jetpack_search_comp_disabled` to your blog (for example using wpsh).
- Search dashboard should now gray out option to enable instant search and the final CTA should be visible.

Alternatively, have Jetpack Search Free plan, and apply sticker `jetpack_search_free_disabled`.

### CODE REVIEW

**Comment by trakos** [comment]
I realized that there's one flaw with this approach: if we disable the instant search option while the blog had it enabled, there's no way to disable it. It could happen if the request to disable it doesn't reach the blog from overages cron.

**Review by kangzj — APPROVED** [review]
Thanks for fixing this and it works as described 👍 

The PR resolves the possible issue where if the disable call doesn't reach the blog, right? I assume there is such a call, am I right?

**Comment by trakos** [comment]
Thanks for the review!
 
> The PR resolves the possible issue where if the disable call doesn't reach the blog, right? I assume there is such a call, am I right?

Yes, there is, in fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Swrgcnpx%2Qfrnepu%2Qbirentrf%2Spynff%2Qbirentr%2Qunaqyre.cuc%3Se%3Qnp0s79n9%23140%2Q140-og

**Comment by kangzj** [comment]
@trakos Nice one! Let's :shipit:

**Review by bisko — APPROVED** [review]

**Pull request merged**
