### PR TITLE
Fix carousel full image not being served by Photon

### PR DESCRIPTION
**Pull request by Draikin**
Fixes a bug that causes full images in the carousel to not be served by Photon.

### CODE REVIEW

**Comment by kraftbj** [comment]
@Draikin - this looks to be an empty/off commit, which the direct link showing a lot of changes: https://github.com/Automattic/jetpack/commit/49bedc688b687f47b312cbb7e8b623bf648dbd71

**Comment by Draikin** [comment]
Sorry, I'm still new at working with Githuh. Should I start over? In terms of changes it's only showing the one file I edited, but I'm not sure if this is usable or not.

**Comment by kraftbj** [comment]
Possibly :) Walking through Git stuff isn't always straightforward. No need to apologize, all started somewhere with the joys of git.

I'd suggest something like this....
1. `git checkout master` to make sure you're on master
2. Make sure you've set Automattic as an upstream repo, e.g. `git add upstream https://github.com/Automattic/jetpack.git`. You can check by `git remote -v`
3. `git pull upstream master` to pull in the latest master from the Automattic repo.
4. `git checkout -b [branch-name]` probably best as a new branch at this point.
5. Make your changes, then commit, `git push origin [branch-name]`

Then do all of the PR stuff on github.com. If you're using a client, I'm of no help. I've only use git via CLI. There is a better/more detailed walkthrough at http://jetpack.me/contribute/#patch

**Comment by Draikin** [comment]
I'm using Github for Windows, as I was hoping that would be easier to understand, but it actually seems to make things more complicated. I'll try using the CLI tomorrow and follow the steps you noted.

**Comment by kraftbj** [comment]
Git itself has a Windows UI built-in ( https://git-scm.com/download/win ). I didn't use it all that much when I was starting out and using Windows most of the time, but the Git Bash client is what got me hooked on the CLI.

**Comment by jeherve** [comment]
Replaced by #3065

**Pull request closed without merging**
