### PR TITLE
Jetpack mu and wpcomsh - hide wpcom items for non wpcom site users, hide hosting card from non-admins

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Fixes # Automattic/dotcom-forge#7892

## Proposed changes:

Hides various wpcom items in wp-admin when the current user is not connected to wpcom:

* Hosting card on the dashboard. Note - this PR also hides this for connected users who are not admins
Screenshot 2024-07-02 at 2 54 33 PM

* WPcom command palette
Screenshot 2024-07-02 at 2 54 56 PM

* Themes banner (seen at themes -> add new)
Screenshot 2024-07-02 at 2 55 19 PM

* themes showcase sidebar link.
Screenshot 2024-07-02 at 2 55 31 PM

* plugins marketplace sidebar link
Screenshot 2024-07-02 at 2 55 47 PM

* plugins banner under 'add plugins'
Screenshot 2024-07-02 at 2 55 57 PM

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Set up a woa dev blog.
* install the jetpack beta tester plugin and ensure your test site has the JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLGUIN constant defined (both noted in github-actions comment below).
* In the jetpack beta tester plugin's settings, find "jetpack beta tester" and activate the "bleeding edge" version. This is necessary to activate this branch on wpcomsh here.
* Next, activate this branch in both "WordPress.com Features" and "WordPress.com Site Helper" sections of the jetpack beta tester plugin.
* Verify all of the above items shown in the description still show up as expected in wp-admin.
* Visit Users-> add new user. Create a new user and password for the site, do not invite them to wpcom.
* Open wp-admin for this site in an incognito tab. Instead of logging in via wordpress.com, login via the new site user/pw combo you created.
* In wp-admin, verify the above items are not visible.

* Add another user who is connected to wpcom, and add them as something that is not an administrator (i did editor).
* In the wp-admin dashboard, verify the site hosting management card is not available to the non-admin user.

### CODE REVIEW

**Review by DustyReagan — DISMISSED** [review]
Works as described!

**Comment by Addison-Stavlo** [comment]
I resolved the merge conflicts with version numbers that started blocking this at some point after the approval. Now merging is blocked again for another review. 😞

**Comment by Addison-Stavlo** [comment]
enabling auto-merge this time so that doesnt happen again...

**Comment by Addison-Stavlo** [comment]
Im pushing another small change here ([9533bc5](https://github.com/Automattic/jetpack/pull/38155/commits/9533bc5b1dfa647659388112be79ce14161576dd)). [Eric pointed out that we have no role check](https://github.com/Automattic/dotcom-forge/issues/7892#issuecomment-2204399306) on the site management card. So I am adding a commit to handle that as well.

To test this you can add a wpcom connected user with any role less than 'administrator'. Log into wp-admin with that wpcom user and verify the management card is visible on the dashboard.

**Review by DustyReagan — APPROVED** [review]
Tested again with the new commit. The original functionality still works 👍, and non-administrators do NOT see the "Site Management Panel" on the Dashboard.

**Pull request merged**
