### PR TITLE
Connection: extract restore connection into the JS package

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
* Extract the "Restore Connection" functionality from Jetpack into the Connection JS package

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
1202829334238225-as-1202734545165082

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Connect Jetpack and set invalid blog and user tokens using the "Jetpack Debug -> Broken Token" tool.
2. Go to Jetpack Dashboard, you should see the "Restore Connection" notice, click on it.
3.1 The error notice should disappear
3.2 The "Reconnecting Jetpack" notice on the top right should show up
3.3 After a few seconds, the Dashboard should be replaced with the "Unlock all the amazing features..." screen (user connection screen).
4. Click on "Connect your user account", finish the connection, go back to Jetpack Dashboard and confirm everything is connected correctly.
5. Go to the "Broken Token" and set invalid blog and user tokens.
6. Go to the "Reconnect Modal" page: `/wp-admin/admin.php?page=jetpack#/reconnect`, confirm that the "Reconnect Jetpack" modal shows up.
7. Click "Reconnect Jetpack", the "Reconnecting Jetpack" notice should appear in the top right corner.
8. In a few seconds you should see the user connection screen again. Complete the connection flow and confirm you've been reconnected successfully.

### CODE REVIEW

**Review by fgiannar — CHANGES_REQUESTED** [review]
Great job here, Sergey!

I haven't yet looked at the code, however here are a few comments from manual testing on a JN site:

**After setting an invalid blog token**
In a broken site connection scenario, after I successfully restore my connection I still see the "Restore Connection" notice as displayed below:
Screenshot 2022-09-14 at 09 16 37

**After setting an invalid user token**
In a broken user connection scenario, after I successfully restore my connection I still see the "Restore Connection" notice as displayed below after being redirected back to the site:
Screenshot 2022-09-14 at 09 22 22

Note that I reproduced the first case on RC branch, therefore I don't believe your changes introduced this, still it would be nice to address this here as it might be very confusing for our users.

**Comment by sergeymitr** [comment]
Hi @fgiannar.
Thanks for discovering the issue!
I was able to reproduce it a couple of times, but as I got to debugging, the issue disappeared, and I never saw the error message after restoring connection again.

It seems to me that the error is on Jetpack side, and since you have also seen the error outside of this PR, I think we should merge this when it's ready, and I'll keep digging into this problem separately.

**Review by fgiannar — APPROVED** [review]
Looks good to me! Let's 🚢 !

**Comment by kraftbj** [comment]
Committed as part of r252613-wpcom

**Pull request merged**
