### PR TITLE
Remove $connected_destination_account_id from call

### LINKED ISSUE #32092: Donations Block: Incorrect Contribution Amount
### Quick summary

When donating, the Contribution Amount is incorrect. Although it's possible to edit it, it's ideal to display the same amount. 

### Steps to reproduce

1. Add a donations block in a page and publish. 
2. Create Payment plans.
3. Visit the page and donate. 
4. The price in Contribution Amount will not be the same as the amount chosen to donate. 

### What you expected to happen

If the donation is $5, the amount in Contribution Amount should show $5, the same as the amount chosen to be donated. 

### What actually happened

The Contribution Amount is not the same as the amount chosen to be donated. 

### Impact

All

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

6567163-zd

The user has One-time payment plans of $25, $50 and $100. On the page with Donations Block, clicking $50 or $100 shows the Contribution Amount as $25. This amount can be manually edited, but can the donation amount be the same as the Contribution Amount? 

Screenshot 2023-07-22 at 18 26 32

It's the same issue for Custom Amount, Monthly and Yearly payment plans. The Contribution Amount is not the same as the chosen donation amount.

### PR DESCRIPTION
**Pull request by pottedmeat**
Fixes #32092 

## Proposed changes:

* A recent refactor (D115524-code#C8427620OL522) in WPCOM code changed the call signature for `generate_default_products` by removing `connected_account_id`
* This removes the same argument in the function call

## Testing instructions:

- Use a site where you've never added a Donations Block or a create new site
- Use store sandbox (PCYsg-IA-p2)
- Connect a Stripe account  following these instructions (PCYsg-lW4-p2)
- On a new or existing page, add a new block and choose "Donation Form"
- Pause a second and then press "Update" to save the page
- Using wpsh (PCYsg-4Ki-p2), run `gpr SELECT post_id, meta_key, meta_value FROM wp_[site_id]_postmeta WHERE meta_key IN ('jetpack_memberships_acct_id', 'jetpack_memberships_is_editable') ORDER BY post_id, meta_key` where `site_id` is the site ID
- verify that `jetpack_memberships_is_editable` returns either 0 or 1 values and no `post_id` has the `jetpack_memberships_acct_id` in the `jetpack_memberships_is_editable` value

### CODE REVIEW

**Review by n3f — DISMISSED** [review]
LGTM 👍

**Comment by kraftbj** [comment]
I've updated this PR to bring it up to date with trunk (it looks like it was branched off of a commit from April one way or another) and add the changelog file.

@pottedmeat @n3f would you mind doing a second review to ensure rebasing it didn't cause any issues?

**Comment by pottedmeat** [comment]
> @pottedmeat @n3f would you mind doing a second review to ensure rebasing it didn't cause any issues?

Rebase looks good, thanks.

**Comment by millerf** [comment]
Duplicates https://github.com/Automattic/jetpack/pull/31749

**Comment by millerf** [comment]
Closed by https://github.com/Automattic/jetpack/pull/31749

**Pull request closed without merging**
