### PR TITLE
Connection: trigger "Restore Connection" flow

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
* Trigger restore connection flow via the connection error notice

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
p9dueE-5zL-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
_This PR can no longer be tested, because we removed the My Jetpack integration.
Please look at the code and see if it makes sense, and confirm Jetpack Connection still works
No actual testing needed._

_SQL query to remove transients:_
```delete from wp_options where option_name like '%jetpack_connection_error_reporting_gate_%';```

1. Connect Jetpack, use "Broken Token" to set invalid blog and user tokens.
2. Go to "Jetpack -> My Jetpack", you should see the error. If it doesn't show up, remove the transients using the SQL query above. Screen Shot 2022-09-28 at 17 18 03
3. Click "Restore Connection", the notice should say "Reconnecting Jetpack":  Screen Shot 2022-09-28 at 17 18 41
4. The connection screen should show up. Finish the connection flow, confirm it works well.
5. Go back to "Broken Token" and break only the blog token, leaving the user token intact.
6. Remove the transients using the SQL query above.
7. Go to "Jetpack -> My Jetpack", you should see the same error notice. Click "Restore".
8. The same "Restoring Jetpack" notice should show up.
9. After a few seconds, the page should reload. The error notice should no longer appear.
10. Go to "Broken Token" and confirm that the blog token has been restored.

### CODE REVIEW

**Comment by chrisbliss18** [comment]
I'm having trouble running the testing instructions from step 5 down. Here's how I replicated my experience:
1. Disconnect Jetpack to start from fresh.
2. Complete setting up Jetpack.
3. Go to Jetpack Debug > Broken Token and click "Set invalid blog token".
4. Run query `delete from wp_options where option_name like '%jetpack_connection_error_reporting_gate_%';`.
5. Go back to Jetpack > My Jetpack and confirm that the new error message displays.
6. Click on "Restore Connection".
7. Both the new error message and the old error message (`There was an error fetching your purchases information. Check your site connectivity and try again.`) disappear.
8. The `Reconnecting Jetpack` message appears with the animating wait image.
9. The `Reconnecting Jetpack` connection disappears.
10. The `It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting.` message with the "Restore Connection" link reappears.
11. Click on "Restore Connection".
12. The new error message disappears.
13. The `Reconnecting Jetpack` message appears with the animating wait image.
14. I'm taken to the Jetpack connect page

**Comment by sergeymitr** [comment]
Thanks for taking a look @chrisbliss18.
Turns out stored connection errors weren't cleaned after blog token restore when full reconnect wasn't performed.
Please give it another try.

**Comment by chrisbliss18** [comment]
@sergeymitr I was able to successfully run the testing instructions with the latest commit. Thanks!

**Review by chrisbliss18 — DISMISSED** [review]

**Comment by sergeymitr** [comment]
Thanks @chrisbliss18!
I've removed the "My Jetpack" integration, please re-approve and then we'll merge it.

**Review by chrisbliss18 — APPROVED** [review]

**Pull request merged**
