### PR TITLE
Payments Block: Fix placeholder alignment and spacing issues

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/view-design/issues/226

#### Changes proposed in this Pull Request:

* Fix spacing, alignment and font size issues with the placeholder of the payments block using Twenty Twenty One, and Twenty Twenty.

| Before        | After           | 
| ------------- |:-------------:| 
| Screen Shot 2021-03-30 at 1 32 18 PM |  Screen Shot 2021-03-30 at 12 36 59 PM |

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Activate Twenty Twenty One theme
* Insert payments block and click the button to add a new payment plan.
* Do the same with Twenty Twenty.
* Confirm the placeholder design matches the above.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
For me on twentytwentyone the bottom of the y is cut off on 'Monthly' select box, but looks ok in your screen shot:
Screen Shot 2021-03-31 at 10 19 52 AM

**Comment by apeatling** [comment]
Thanks for the reviews, I've fixed the button spacing:

Screen Shot 2021-04-08 at 12 09 54 PM

**Comment by ramonjd** [comment]
Not sure if this falls in the sphere of this PR, I noticed that the indentation looks off in narrow widths
Apr-09-2021 11-44-34

Otherwise it looks good in my testing

Screen Shot 2021-04-09 at 11 46 18 am

Screen Shot 2021-04-09 at 11 43 25 am

**Comment by apeatling** [comment]
Alignment fixed, good catch! 👍 

Screen Shot 2021-04-15 at 1 28 07 PM

**Review by ramonjd — APPROVED** [review]
LGTM
Screen Shot 2021-04-16 at 11 48 06 am

Also tested on mobile

Screen Shot 2021-04-16 at 11 52 30 am

**Review by samiff — APPROVED** [review]
Looks good to me.

@apeatling Unrelated to this specific PR, I did notice that the block becomes unusable  at smaller resolutions, whenever `components-placeholder is-large` drops to `is-medium` it seems. Wasn't sure if this is expected behavior? 

Markup on 2021-04-16 at 14:37:20

**Pull request merged**
