### PR TITLE
Whitelist `jetpack_memberships_site_subscriber` post meta

### PR DESCRIPTION
**Pull request by romarioraffington**
## Proposed changes:

Sync `jetpack_memberships_site_subscriber` post meta to WPCOM as we rely on this post meta for business logic

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Create a newsletter plan on a JP site that has a JP connection
* Verify that the post and `jetpack_memberships_site_subscriber` post meta is synced to WPCOM

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
Since we're making that change, should this be a new constant in `projects/plugins/jetpack/extensions/blocks/subscriptions/constants.php`

**Comment by millerf** [comment]
I really struggle to see how we have been able to test all previous times on JN without this on. I believe this is a red herring...

**Review by n3f — COMMENTED** [review]
I think a better solution is probably the one outlined [here](p1689712281078529/1689701094.306599-slack-CBG1CP4EN).  It seems that if you add it to the class-jetpack-memberships file it should get taken care of with the existing meta that's getting populated.

```php
	private static function get_plan_property_mapping() {
		$meta_prefix = 'jetpack_memberships_';
		$properties  = array(
			'price'    => array(
				'meta' => $meta_prefix . 'price',
			),
			'currency' => array(
				'meta' => $meta_prefix . 'currency',
			),
			'is_newsletter' => array(
				'meta' => $meta_prefix . 'site_subscriber',
			),
		);
		return $properties;
	}
```

**Comment by romarioraffington** [comment]
Thanks Brent, added your suggestion

**Review by millerf — APPROVED** [review]
LGTM

**Comment by millerf** [comment]
I verified:
- paid newsletters are not sent to paid subscribers on Atomic (and I think, also standalone Jetpack).
- unloggued subscribers cannot log via the subscribe block onAtomic and Jetpack

**Pull request merged**
