### PR TITLE
WPCOM MERGE Infinite Scroll

### PR DESCRIPTION
**Pull request by georgestephanis**
Update Jetpack with any relevant changes to wpcom on Infinite Scroll.

Fortunately, there seem to be few.  Some chaff that will get cleared out when squashed.

### CODE REVIEW

**Comment by georgestephanis** [comment]
cc: @thomasguillot as yours seems to be the only change that hadn't been in Jetpack previously.  Anything specific we need to watch out for when testing this, or should it be good to go?

**Comment by georgestephanis** [comment]
This ties in with D4225 on phabricator

**Comment by thomasguillot** [comment]
@georgestephanis should be good to go.

We had the issue on .com fixed for quite a while now.

Basically, Infinite Scroll (click) was not changing the class of the body once 100% loaded (end) which created some issues with themes relying on the `infinity-end` class for some design elements.

**Comment by jeherve** [comment]
Fixes #5737

**Comment by dereksmart** [comment]
This LGTM

**Comment by georgestephanis** [comment]
The WPCOM side of this merge has been committed in r150344-wpcom

**Pull request merged**
