### PR TITLE
Base Styles: Reduce specificity of body selector

### LINKED ISSUE #89631: Discrepancy in Font Family between Editor and Front End
### Quick summary

In the Page or Post Editor, the default font family is different from what is shown on the Front End. Initially thought the bug was similar to https://github.com/Automattic/wp-calypso/issues/86570 but it appears to occur on more themes (tested on Kingsley, Arbutus, Geologist, Archeo, Feelin' Good and Bedrock).

Editor View

Front End View

### Steps to reproduce

1. Open a test site and activate any of these themes: Kingsley, Arbutus, and Geologist (or probably any theme).
2. Create a new post.
3. Add a paragraph with sample text.
4. Preview your changes.

### What you expected to happen

Font family should be consistent in both the Editor and on the Front End.

### What actually happened

Font family in the Editor is different to what is shown on the Front End. Looks like the Editor is using the system font?

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Reported in 8056292-zen

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/wp-calypso/issues/89631
Related to https://github.com/WordPress/gutenberg/pull/60106, p1713865028094699-slack-CDLH4C1UZ

## Proposed changes:

Referring to https://github.com/WordPress/gutenberg/pull/60106, it would be better to reduce the specificity of the body selector on Jetpack to avoid the styles of the font family being overridden. I'm unsure of the purpose of the body styles but I guess we can consider removing them later

Here is the result of Bedrock theme:

Screenshot 2024-04-24 at 12 50 26 PM

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Follow https://github.com/Automattic/jetpack/pull/37043#issuecomment-2073950385 to apply the changes on your site
  * You have to apply this branch to Jetpack & Jetpack VideoPress on atomic sites
* Remember to disable the cache before getting started
* Go through pages under the Jetpack
* Make sure the styles look good
* Activate any of these themes: Kingsley, Arbutus, and Geologist (or probably any theme).
* Create a new post
* Add a paragraph with sample text.
* Make sure the fonts are rendered correctly
* Go to the Site Editor
* Add jetpack blocks
* Make sure the styles of jetpack blocks look good

### CODE REVIEW

**Comment by taipeicoder** [comment]
@arthur791004 I added a post using the Bedrock theme and the fonts render fine. The post also has Jetpack blocks. See https://griffithchen01.blog/2024/04/24/site-title/
Am I missing anything?

**Comment by arthur791004** [comment]
> I added a post using the Bedrock theme and the fonts render fine. The post also has Jetpack blocks. See https://griffithchen01.blog/2024/04/24/site-title/
Am I missing anything?

Do they render correctly in the post editor?

**Comment by taipeicoder** [comment]
> > I added a post using the Bedrock theme and the fonts render fine. The post also has Jetpack blocks. See https://griffithchen01.blog/2024/04/24/site-title/
> > Am I missing anything?
> 
> Do they render correctly in the post editor?

Thanks, I was testing the Front End 😄

**Review by taipeicoder — APPROVED** [review]
Works as intended!

| Before | After |
| --- | --- |
| Screenshot 2024-04-24 at 4 27 36 PM | Screenshot 2024-04-24 at 4 32 03 PM |

**Pull request merged**
