### PR TITLE
Just In Time Messaging tags added to the header of 30 Jetpack modules

### PR DESCRIPTION
**Pull request by jessefriedman**
These tags will be used to compare search queries to Jetpack modules, allowing for the display of JITM

### CODE REVIEW

**Comment by georgestephanis** [comment]
I'd prefer to change the term for this to Search Tags, so we can also use them on the module listing page to turn up relevant results.

**Comment by georgestephanis** [comment]
Just added a bit to the build module headings translations php file to extract out `Search Tags` and `JITM Tags` headers -- though I'd prefer we migrate to the former over the latter.

**Comment by jeherve** [comment]
Related: #2180

**Comment by jessefriedman** [comment]
Changed JITM Tags to Search Queries through here and #2213

**Comment by dereksmart** [comment]
Closing, as we've decided to not implement this feature.

**Pull request closed without merging**
