### PR TITLE
Fix: Contact form block dropdown arrow wrapping under field

### LINKED ISSUE #8035: Contact form block dropdown arrow wrapping under field in Assembler theme
### Quick summary

The dropdown arrow is under the dropdown field. It should be inline on the right side of the field.

contact-form-dropdown

### Steps to reproduce

1. Install and activate Assembler theme
2. Add a contact form to any page.
3. Add a dropdown field to the form
4. View the arrow under the form.

### A clear and concise description of what you expected to happen.

The arrow should be displayed on the right side of the field, inline with the text.

### What actually happened

The arrow is displayed under the dropdown field.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Using this CSS as a workaround:

```
.contact-form .contact-form__select-wrapper::after {
  right: 15px;
  top: 50%;
}
```

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I have tested the dropdown field on other themes like Twenty Twenty-Four, Annalee, and Outland. The issue does not occur on those themes. So it seems to only be an issue when using the Assembler theme.

### LINKED ISSUE #38470: Jetpack Contact form: dropdown arrow from the dropdown field missplaced
### Impacted plugin

Jetpack

### Quick summary

A user reported that the dropdown arrow in the dropdown field is misplaced. I couldn't fully replicate this issue; however, during my testing, the dropdown arrow appears misaligned for a brief moment when the page loads, but then it corrects itself.

User's screenshot: 

From this site: https://www.cscistok.eu/csc-uebersicht/csc-eintragen/

My test site (it's a GIF, wait for the page refresh to see the arrow "movement"):

I tested with Jetpack 13.6 similar to the user's plugin version, but also with beta version of 13.7. Tested with Twenty Twenty-Four and Twenty Twenty-Three.

### Steps to reproduce

1. Insert a contact form in a post or page
2. Use the dropdown field
3. Check the contact form on the live site and see the position of the dropdown arrow. 

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

Issue has been initially reported here: https://wordpress.org/support/topic/form-block-dropdown-menu-down-arrow-misplaced/#post-17894696

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Fixes https://github.com/Automattic/themes/issues/8035
Fixes #38470

## Proposed changes:

This PR fixes how we calculate the position for the arrow on a select element using the correct CSS variables. Before, it would only work if a theme had a singular value for all sides of padding (or none at all) on the element

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Install Assembler theme
* Insert the Register form on a post and save
* Go to the frontend and see the arrow is not aligned properly
* Checkout this PR and the arrow should be placed correctly
* This shouldn't break other themes

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This tests well on my end, thanks for working on that fix. 🚢

**Comment by coder-karen** [comment]
Thanks for taking a look at this issue!

I also gave this a test, and in doing so noticed that it looks like the issue itself affects more than one theme - Astra is another from what I can see. There are other themes who also have a slightly mis-placed selector - Twenty Fifteen and Dara are two that I've tested just now. 

Testing on a self-hosted (Jurassic Ninja) site, and using the Jetpack Beta plugin to apply this PR, I can confirm this PR fixes the selector placement for Assembler and Astra. There's no change for Twenty Fifteen and Dara but there must be a different style issue for those and others like them, which this issue can continue to cover: https://github.com/Automattic/jetpack/issues/38470

Testing on a Simple site, the change did apply for Astra and Assembler.

However testing on an WoA site, also using the Jetpack Beta tester plugin to apply this PR, I got two different results on two different sites. The arrow briefly displays on the other side of the dropdown field then moves back over to the left hand side. That's for Astra and also Assembler. Same results as with self-hosted for Twenty Fifteen and Dara.

I couldn't see what may be different between the two sites - same plugins active. Possibly something at my end. Anyway wanted to note that down, since I don't think it should block this being merged but just incase the issue crops up again there is a point of reference.

**Comment by MaggieCabrera** [comment]
> Thanks for taking a look at this issue!
> 
> I also gave this a test, and in doing so noticed that it looks like the issue itself affects more than one theme - Astra is another from what I can see. There are other themes who also have a slightly mis-placed selector - Twenty Fifteen and Dara are two that I've tested just now.
> 
> Testing on a self-hosted (Jurassic Ninja) site, and using the Jetpack Beta plugin to apply this PR, I can confirm this PR fixes the selector placement for Assembler and Astra. There's no change for Twenty Fifteen and Dara but there must be a different style issue for those and others like them, which this issue can continue to cover: #38470
> 
> Testing on a Simple site, the change did apply for Astra and Assembler.
> 
> However testing on an WoA site, also using the Jetpack Beta tester plugin to apply this PR, I got two different results on two different sites. The arrow briefly displays on the other side of the dropdown field then moves back over to the left hand side. That's for Astra and also Assembler. Same results as with self-hosted for Twenty Fifteen and Dara.
> 
> I couldn't see what may be different between the two sites - same plugins active. Possibly something at my end. Anyway wanted to note that down, since I don't think it should block this being merged but just incase the issue crops up again there is a point of reference.

Good catch. This PR only solves the problems related to the padding but if we look at 2015, the variable `--jetpack--contact-form--line-height` resolves to `normal`, which is a valid value for a CSS line height value but breaks completely the calculation of the top value for the arrow which uses that value for the calculations: `top: calc(var(--jetpack--contact-form--input-padding-top) + var(--jetpack--contact-form--line-height) / 2);  `

I think that can be covered on a follow up. I would suggest rethinking these styles and how else they could break given that themes could style their forms in any given way, this approach seems brittle to me.

**Comment by coder-karen** [comment]
That's really helpful info, thanks for clarifying. I'll add this in an additional comment to the other issue for when we follow up there, as that seems a good issue for follow-up.

**Pull request merged**
