### PR TITLE
VideoPress: fix printing the upload video date

### PR DESCRIPTION
**Pull request by retrofox**
This PR fixes the issue when printing the upload date of the video. For this, it stores only the date (not the formatted value) and applies the format at the component level.

Fixes #

#### Changes proposed in this Pull Request:

* VideoPress: fix printing the upload video date

#### Testing instructions:

* Go to VideoPress dashboard
* Edit video by clicking on the Edit Details button

before | after
------|------
Screen Shot 2022-09-21 at 18 06 35 | Screen Shot 2022-09-21 at 18 03 14

### CODE REVIEW

**Review by renatoagds — COMMENTED** [review]
IMO, keeping this in store was a good solution, and vote to keep it there, since it's not the only place that uses it.

It's being used in `VideoRow` too: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/admin/components/video-row/index.tsx#L109

Btw, keeping it in state, we could remove this format in `VideoRow`.

Maybe we could open a new field in state to store the "raw" date value.

**Comment by lhkowalski** [comment]
> Btw, keeping it in state, we could remove this format in VideoRow.

Having the formatted date version stored may be a simple shortcut to a consistent date experience on any screen/feature.

**Comment by lhkowalski** [comment]
Tested the change and it's working on a JN site:

videopress-details-upload-date

**Comment by retrofox** [comment]
> IMO, keeping this in store was a good solution, and vote to keep it there, since it's not the only place that uses it.

Why are we going to duplicate data in the store? You can use the function to apply the format when it's needed. I vote to remove it :-)

**Comment by retrofox** [comment]
> It's being used in `VideoRow` too: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/admin/components/video-row/index.tsx#L109

Exactly! 💯 

> Btw, keeping it in state, we could remove this format in `VideoRow`.

Why? 

> Maybe we could open a new field in state to store the "raw" date value.

Why duplicate the data in the store when never was so easy to format a date value in the client? 😿

**Review by lhkowalski — APPROVED** [review]
> You can use the function to apply the format when it's needed. I vote to remove it :-)

Yes, good point. LGTM this way.

**Pull request merged**
