### PR TITLE
Dashboard: Add a specific message for a site that is too new to have a rewind status

### PR DESCRIPTION
**Pull request by cbauerman**
Fixes 6844-gh-Automattic/jpop-issues

#### Changes proposed in this Pull Request:

* Handle new `site_new` rewind status reason ( introduced in D66042-code ) on Jetpack Dashboard. In cases where a new user is sent immediately to the dashboard after being connected to a premium plan a timing issue could cause a message about installing VaultPress. Now it should let them know we are setting up things behind the scenes.

Screen Shot 2021-08-27 at 3 46 24 PM

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Create a new jurassic.ninja site with a premium plan and this branch
2. Open the Jetpack wp-admin dashboard in two tabs, one with a dev console open.
3. On the non-dev console tab connect Jetpack.
4. Immediately reload the other tab after clicking "Authorize"
5. Verify that the `rewind` network response returned `unavailable` and `new_site` reason.
6. Verify the Backup dash status says "Your site is new and may still be preparing its backup config."

### CODE REVIEW

**Comment by sdixon194** [comment]
@cbauerman Heyo! Is this one ready for review?

**Comment by cbauerman** [comment]
> @cbauerman Heyo! Is this one ready for review? 

Yup! I am afk today but unless something is drastically wrong with the PR I should be able to give it enough attention to merge before the freeze.

**Comment by sdixon194** [comment]
Testing this out on some JN sites - it looks like it works at first, but then on refresh I get a notice about adding server credentials - is that expected?

Screen Shot on 2021-08-30 at 13:16:57

**Comment by cbauerman** [comment]
> Testing this out on some JN sites - it looks like it works at first, but then on refresh I get a notice about adding server credentials - is that expected?
> 

Yup! The message should only show up if you go to the dashboard _immediately_ after connecting. The "add credentials" message is what it should be.

**Comment by samiff** [comment]
> Your site is new and may still be preparing its backup config.

@cbauerman What do you think about phrasing this so it sounds a bit more sure? Maybe something like:

> Backups are currently being configured for your new site.

**Comment by cbauerman** [comment]
> > Your site is new and may still be preparing its backup config.
> 
> 
> 
> @cbauerman What do you think about phrasing this so it sounds a bit more sure? Maybe something like:
> 
> 
> 
> > Backups are currently being configured for your new site.
> 
> 
> 
> Other than that, this tests well and looks good to me.

The problem is we aren't necessarily sure if they have backups, which is why the message has the "maybe". It is worth noting it is pretty hard to get the message at all, you have to either be trying or in the situation described in the attached jpop issue, so whichever message we use should be fine.

**Review by samiff — APPROVED** [review]

**Pull request merged**
