### PR TITLE
Backup: Admin / Backup Component UI polish

### PR DESCRIPTION
**Pull request by jwebbdev**
#### Changes proposed in this Pull Request:

* Updating styling because current implementation is text-heavy, includes redundant links and content, and the alignment feels unpolished.

#### Jetpack product discussion

* p1HpG7-iU4-p2
* p1HpG7-iIT-p2
* MAuuSG24CfhAzTsm5N3xMI-fi-1%3A29

#### Screenshots
| Before | After |
| --- | --- |
| image | image |

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Launch a new JN site with Jetpack VaultPress Backup plugin.
* Connect your site to Jetpack and subscribe to a backup plan.
* After the initial backup is completed, refresh the page and validate the changes in the UI.

### CODE REVIEW

**Review by madebynoam — CHANGES_REQUESTED** [review]
This is looking great, @Initsogar! Thank you for tackling these changes.

I have one piece of feedback; if we could remove the `is-full-width` class on the main button until the screen size hits the smaller (tablet) breakpoint?

So it would look like this in larger sizes (giving the cards a bit of breathing space):
image

And then, on tablet (and phone size), it would be as is (with the class enabled):
image

**Comment by madebynoam** [comment]
@Initsogar, one more thing I noticed:
On VideoPress, the button is slightly shorter (40px height), whereas, in Backup, it ends up as 50px.
Could we match the VideoPress button?:

image

image

**Comment by Initsogar** [comment]
Nice feedback @madebynoam, thank you!

Just made the adjustments on the backups height and full-width. Could you take a look?

image

image

**Comment by madebynoam** [comment]
> Nice feedback @madebynoam, thank you!
> 
> Just made the adjustments on the backups height and full-width. Could you take a look?
> 
> image
> 
> image

Thank you @Initsogar! That looks perfect!

**Review by madebynoam — APPROVED** [review]

**Review by mavegaf — APPROVED** [review]
- Change looks good on desktop and mobile
- Links are working ok

👍

**Pull request merged**
