### PR TITLE
Contact Form: Sidebar Revamp

### LINKED ISSUE #26945: Form Block: Redesign Sidebar Area for Form Responses Management
Image

- Based on the copy text in this area it is also not easy to understand that this is about "receiving form responses" into your email inbox.

- What is completely missing here is to give any reference to the Form Responses area in WP-Admin, as well as the ability to download the data there.

- Also having the "Submission" settings behavior combined with the data management is confusing and should better live in two separate sections.

- Another thing: Getting responses per email is mandatory! Not appealing to all users, depending on your site's traffic. There should be an option to deactivate email notifications. 

Context and Design: https://wp.me/pcsBup-jw

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #26945

#### Changes proposed in this Pull Request:
* Include "Manage Responses" Section
* Split the "Forms Settings" section into "Submission Settings" and "Email Connection"

Before:
image

After:
image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Checkout this branch and create a Page/Post
* Add a Form block to the page and check if the block's Sidebar matches the description above

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
I am getting an error, testing via Jurassic Ninja, right after choosing a form template:

image

**Comment by jcheringer** [comment]
> I am getting an error, testing via Jurassic Ninja, right after choosing a form template:
> 
It should be fixed now 🙂

**Comment by digitalwaveride** [comment]
Looking good João! 👍 

One little thing I noticed:

#### Title of the Form 

The description text below the input field is missing:

image

**Comment by jcheringer** [comment]
@digitalwaveride, added the description to the Form Title field on 24bab39 . ✅

**Review by digitalwaveride — APPROVED** [review]
👍 Thanks!

**Review by CGastrell — APPROVED** [review]
LGTM!

**Review by samiff — APPROVED** [review]
Tested well for me 👍

**Pull request merged**
