### PR TITLE
Shortcopy: update illustrations on plan headers

### LINKED ISSUE #11541: My Plan: update heading illustration
Following up https://github.com/Automattic/jetpack/pull/11505#issuecomment-471639047

The illustration next to My Plan main header should be updated once we have a clear decision on the style direction.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #11541

#### Changes proposed in this Pull Request:

* add new illustrations on My Plan header
* update styles for a proper layout

## Desktop 
Captura de pantalla 2019-03-21 a la(s) 18 29 16

## Tablet
Captura de pantalla 2019-03-21 a la(s) 18 29 32

## Phone
Captura de pantalla 2019-03-21 a la(s) 19 03 57

## Small Phone <480
Captura de pantalla 2019-03-21 a la(s) 19 04 15

#### Testing instructions:

* Go to the Jetpack dashboard and click My Plan
* Ensure that everything looks correct

#### Proposed changelog entry for your changes:

* Not needed. Part of Shortcopy project.

### CODE REVIEW

**Comment by keoshi** [comment]
You're a champ, @eliorivero !

Will give it a run tomorrow morning, but from the screenshots it looks like their size is adding a lot of empty space at the bottom. Can we reduce their total size without losing the vertical alignment of the titles/paragraphs?

Thank you!

**Review by kraftbj — DISMISSED** [review]

**Comment by kraftbj** [comment]
Approved from the code POV. Merge when design review is finished if no changes are required.

**Comment by eliorivero** [comment]
@keoshi done, centered the title and paragraph as well as the icon. Screenshots are up to date. LMK if it's ok now.

**Review by keoshi — APPROVED** [review]
Beautiful stuff, Elio! Thanks so much again. Let’s ship it! 🛳

**Review by mdawaffe — APPROVED** [review]

**Pull request merged**
