### PR TITLE
Jetpack AI: add featured image styles support

### PR DESCRIPTION
**Pull request by CGastrell**
AI image generation styles dropdown implementation for Featured Image modal, following the latest implementation for General Image #39917

## Proposed changes:

**NOTE:** Requires D165926-code 

This PR implements the style dropdown on the Featured Image modal:
- adapt handlers to take the style and pass it down to the image generator
- adapt modal props and component effects to allow passing down both prompt and selected style
- auto generate image on first modal open ONLY if no featured image is set
- on auto generate, use style "Auto" to try and guess the best style for the image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Sandbox public-api and patch it with D165926-code

Open the post editor. If there's no content on the post, Featured Image should not trigger a generation on first open. 

Type a title for the post. Open the Featured Image modal and it should now attempt both guess a style for the image and generate an image. Repeat this process after typing (or generating) some content on the post. As long as you don't set a Featured Image, the modal will trigger an auto generation on open (this is also true if you remove the Featured Image).

If the post has content or title, the modal will allow to hit "Generate" even without a prompt, in which case the contextual data (post content and/or title) is used for the image generation.

NOTE: The auto generation starts with an empty prompt (as you couldn't type anything), once the generated image is back, it also brings the "enhanced" prompt the AI generated on backend to request for the image. This is an experiment on (maybe) let the users learn how to create an effective prompt for images.

**As the components are shared between the two, also check General Image modal continues to work without glitches.**

### CODE REVIEW

**Comment by mwatson** [comment]
image

me when I'm testing a pull request

**Review by mwatson — DISMISSED** [review]
Works great! :shipit:

**Review by vianasw — CHANGES_REQUESTED** [review]
Now it's taking into account user prompts, but the empty post case is not being handled. With a post with no text and no text in the prompt either, the generate button was enabled and when I clicked on it, it generated a random image:
Screenshot 2024-11-12 at 15 12 12
Screenshot 2024-11-12 at 15 15 01

The jetpack-ai-image request had this in the response:
```
"revised_prompt": "Capture a photo of a serene beach scene with soft, golden sunlight illuminating the sandy shore and gently lapping waves. In the foreground, a lone seashell is prominently positioned on the sand, casting a delicate shadow. The background features a clear blue sky with faint wispy clouds. Use high resolution and produce a highly detailed image, ensuring sharp focus on the seashell and maintaining clarity throughout the scene, creating a sense of tranquility and inviting warmth."
```

The generate button should be disabled if the post content and the user prompt are empty.

**Review by mwatson — DISMISSED** [review]
Working as expected, but I did find a weird (though non-blocking, I think) issue. After generating the first image you can click the right arrow on the bottom and it will display `< 2 / 1 >` and you can then ask it to generate another image and the count will always be off by one every time you generate an image. It looks like the non-featured image generator doesn't have this behavior (I can't click on the `>` to go to the next slide after generating an image).

Screenshot 2024-11-12 at 10 29 49 AM

Screenshot 2024-11-12 at 10 29 56 AM

**Comment by CGastrell** [comment]
> Working as expected, but I did find a weird (though non-blocking, I think) issue. After generating the first image you can click the right arrow on the bottom and it will display `< 2 / 1 >` and you can then ask it to generate another image and the count will always be off by one every time you generate an image. It looks like the non-featured image generator doesn't have this behavior (I can't click on the `>` to go to the next slide after generating an image).
> 

Yeah, thanks for pinpointing that one, I saw it at some point but then forgot about it. Not the smartest carousel in the park for sure!

**Review by vianasw — APPROVED** [review]
:shipit:

**Pull request merged**
