### PR TITLE
Fix: set plugins parameter as required to prevent internal errors

### PR DESCRIPTION
**Pull request by zaerl**
Fixes https://github.com/Automattic/dotcom-forge/issues/7222

## Proposed changes:

* Set `plugins` parameter as required to prevent internal errors

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Use `fix/plugins-param-default` for WordPress.com Features
* With the REST API plugin (not the API console) on `/wp-admin/tools.php?page=rest_api_console` do:

```
POST /wpcom/v2/update-schedules?schedule[interval]=daily&schedule[timestamp]=1715849595
```

Ensure no `internal_server_error: <p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/documentation/article/faq-troubleshooting/\">Learn more about troubleshooting WordPress.</a></p>` is spawned, but `Missing parameter(s): plugins`.

### CODE REVIEW

**Review by TimBroddin — APPROVED** [review]
CleanShot 2024-05-16 at 14 58 19@2x

All good!

**Comment by obenland** [comment]
@zaerl @ouikhuan What's causing the fatal error?

**Comment by zaerl** [comment]
> @zaerl @ouikhuan What's causing the fatal error?

A `null` parameter is passed to `usort`:
1. https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/src/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-update-schedules.php#L180
2. https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/src/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-update-schedules.php#L495

**Comment by obenland** [comment]
Thanks! Is this something we could have caught with a unit test?

**Comment by zaerl** [comment]
> Thanks! Is Is this something we could have caught with a unit test?

Yes. But all our unit tests pass a valid schema. I discovered this by chance.

**Pull request merged**
