### PR TITLE
Update hardcoded plan slug

### PR DESCRIPTION
**Pull request by dzver**
Update hardcoded plan slug after making Personal a legacy wpcom plan

Fixes #

#### Changes proposed in this Pull Request:

We want the Pro plan to be visible here instead of Personal:

Screenshot 2022-04-01 at 12 26 18

#### Testing instructions:

1. With a test site on the free plan, on WordPress.com
2. Add a new Payment Button block
3. See a notice with the Pro plan

Before:
Screenshot 2022-04-01 at 12 29 24

After:
Screenshot 2022-04-01 at 12 26 18

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
What will happen if someone has a legacy Personal plan in this case? Will they lose access to the blocks they've added so far? Should they?

**Comment by dzver** [comment]
> What will happen if someone has a legacy Personal plan in this case? Will they lose access to the blocks they've added so far? Should they?

No! The check if they have the right to use the button comes from the backend where all plans 
are listed. This is only if the plan is not supported, it will ask them to upgrade to pro.

Screenshot 2022-04-01 at 12 42 50

This is a screenshot with a site on the Pro plan (store sandboxed), the wpcom diff applied. No notice asking for Pro

**Comment by Copons** [comment]
Can confirm that the notice is showing up for me on a free site, and not showing up on a pre-existing business plan.

I'm currently trying to figure out why there build failures all over the place though.

**Comment by jeherve** [comment]
> I'm currently trying to figure out why there build failures all over the place though.

I would recommend:

1. Run `git checkout master && git pull && git checkout - && git merge origin/master && git push` to update this branch with the latest version of the monorepo, and thus run Fusion on top of the latest version of that code.
2. If that doesn't help, update the related diff manually to ensure there are no issues applying the diff cleanly, that would break the build.

**Comment by dzver** [comment]
> > I'm currently trying to figure out why there build failures all over the place though.
> 
> I would recommend:
> 
> 1. Run `git checkout master && git pull && git checkout - && git merge origin/master && git push` to update this branch with the latest version of the monorepo, and thus run Fusion on top of the latest version of that code.
> 2. If that doesn't help, update the related diff manually to ensure there are no issues applying the diff cleanly, that would break the build.

Okay. I rebased before creating the PR less than 1h ago but I can give it a try :)

**Comment by rcrdortiz** [comment]
Tests well for me.

Captura de pantalla 2022-04-01 a las 12 03 10

**Review by Copons — APPROVED** [review]

**Comment by dzver** [comment]
Deployed, r242950-wpcom

**Pull request merged**
