### PR TITLE
Backup: decouple connection screens from useConnection hook

### PR DESCRIPTION
**Pull request by Initsogar**
Fixes https://github.com/Automattic/jetpack-backup-team/issues/561

Currently, the `useConnection` hook is used in multiple places on the backup plugin, and it is calling a `backup-promoted-product-info` endpoint anytime the hook is used. Also, we are defining two backup connection screens inside this hook.

The idea is to decouple those components and ensure we are rendering them and calling any API only when it is actually needed.

The proposed approach also fixes https://github.com/Automattic/jetpack-marketing/issues/561. The testimonial carousel is being re-rendered anytime the `useConnection` hook is being used.

## Proposed changes:

* Move `BackupConnectionScreen` and `BackupSecondaryAdminConnectionScreen` into components, including the testimonial images.
  * The images were located on `hooks/assets` are now they are part of `backup-connection-screen/assets`, given they are only used there. 
* Move backup product info API call into a hook
* Refactor `useConnection` to keep it simple: just to return the `connectionStatus` object that comes from `jetpack-connection` package.
* Refactor usage of useConnection hook. Basically, we stop replaced restructured array usage with direct `connectionStatus` assignment.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack-backup-team/issues/561

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Spin up a Jurassic Ninja site using this branch: https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=fix/backup-duplicated-calls&wp-debug-log&nojetpack
* Open the developer tools and open the network tab.
* Navigate to the VaultPress Backup page.
* Ensure the `backup-promoted-product-info` is not being called repeatedly.
* Ensure the testimonial section doesn't flicker anymore. [Here is a video of how it is behaving before so you can easily spot the difference](https://github.com/Automattic/jetpack-marketing/issues/561#issuecomment-1953401723).
* Connect your site to Jetpack and purchase a VaultPress Backup plan by clicking on `Get VaultPress Backup`.
* Navigate to the backup admin page
* Ensure there are no attempts on calling the `backup-promoted-product-info` API.

### CODE REVIEW

**Comment by mavegaf** [comment]
I think the change may have broken some flow during license activation. 

1. You need to have some licenses you have not used (buy for example a backup product on https://cloud.jetpack.com/pricing )
2. Connect to Jetpack
Screenshot 2024-08-20 at 16 26 22
Screenshot 2024-08-20 at 16 26 30
Screenshot 2024-08-20 at 16 27 06
3. When you click on "Activate now", it returns to your site but to an empty page. 
Screenshot 2024-08-20 at 16 29 13
  it should be a page with an activation option
Screenshot 2024-08-20 at 16 29 21

**Comment by Initsogar** [comment]
> I think the change may have broken some flow during license activation.

Thanks for the feedback! I was able to reproduce this bug with the latest plugin version, so doesn't seem to be related to this PR.

After activating on wordpress.com/jetpack it is redirecting to: `?page=jetpack#/license/activation` and it should be `?page=my-jetpack#/add-license` (nothing `jetpack` vs `my-jetpack`). The logic of that activation button is located [here](https://github.com/Automattic/wp-calypso/blob/4900d3b69e7e68fc31e488babf408b6ed3d1df43/client/components/jetpack/licensing-prompt-dialog/index.tsx#L26C8-L26C27) and doesn't seem to be changed recently.

I will investigate a bit deeper and fix it in another PR, which is probably in this monorepo or in wp-calypso.

**Comment by Initsogar** [comment]
> After activating on wordpress.com/jetpack it is redirecting to: `?page=jetpack#/license/activation` and it should be `?page=my-jetpack#/add-license` (nothing `jetpack` vs `my-jetpack`). The logic of that activation button is located [here](https://github.com/Automattic/wp-calypso/blob/4900d3b69e7e68fc31e488babf408b6ed3d1df43/client/components/jetpack/licensing-prompt-dialog/index.tsx#L26C8-L26C27) and doesn't seem to be changed recently.

The `?page=jetpack#/license/activation` link works only when the Jetpack plugin is installed, so it seems to be a standalone plugin issue.

**Review by mavegaf — APPROVED** [review]
LGTM

**Pull request merged**
