### PR TITLE
Build: Fix imported modules breaking ie11

### LINKED ISSUE #12407: Dashboard: Not Displaying in IE 11
In 2035678-zen, the user reports that the Jetpack dashboard is blank in IE 11. I am able to replicate.

This user is blind and uses the Dolphin Supanova screen reader, which only fully works in IE. 

Per the customer:

> currently Dolphin are working on Chrome to try making it work there and so far it is about 50% working so unfortunately currently I can only work with IE.

There are no issues with Edge but the Dolphin Supanova doesn't work with that either.

There is a known issue with IE 11 in that the developer tools cause the tab to freeze - I've tried this many times now - so I'm not able to check the console for any errors.

#### Steps to reproduce the issue

1. Open IE 11
2. Go to Jetpack → Dashboard on a site with a Pro plan
3. Note that no information is displayed

#### What I expected

I should see the full Jetpack dashboard.

#### What happened instead

No information

**Screenshots**

image (1)

### PR DESCRIPTION
**Pull request by sirreal**
Fixes https://github.com/Automattic/jetpack/issues/12407

There were two issues:

---

## 1 - config module

Use local `config` module over `node_modules/config`:. https://github.com/Automattic/jetpack/pull/12403 added `config` dependency which is imported here:
 https://github.com/Automattic/jetpack/blob/597bc7ccbae70888cfa266c2fb30c09c235224cd/_inc/client/lib/analytics/index.js#L10

Due to module loading here:

https://github.com/Automattic/jetpack/blob/597bc7ccbae70888cfa266c2fb30c09c235224cd/webpack.config.js#L24

The new `node_modules/config` module is used over [the intended one](https://github.com/Automattic/jetpack/blob/597bc7ccbae70888cfa266c2fb30c09c235224cd/_inc/client/config.js). That introduced new ie11 errors. Fixed here by importing the module with a relative path.

We might consider ordering the module resolution so that local modules have preference.
 
---

## 2 - debug module

The debug module is used directly in the application:

https://github.com/Automattic/jetpack/blob/597bc7ccbae70888cfa266c2fb30c09c235224cd/_inc/client/lib/analytics/index.js#L4

This dependency was not declared in `package.json`, so the whatever version happened to be available as a transitive dependency was used. v4 appears to be incompatible with ie11 and webpack/babel compilation and it is not used in Calypso, likely for this reason.

Fix by adding `debug@3^` as a dependency.

We should enable an eslint lint rule like `'import/no-extraneous-dependencies': [ 'error', { packageDir: './' } ]` to help prevent errors like this.

#### Testing instructions:
Try loading `/wp-admin/admin.php?page=jetpack` for a Jetpack site in IE11. Smoke test. The page should work properly without errors.

#### Proposed changelog entry for your changes:
* Fix an issue with in ie11 with the Jetpack Dashboard.

### CODE REVIEW

**Review by simison — APPROVED** [review]
I haven't tested in IE but code changes make sense.

`debug@4` is tricky because some `node_modules` might start depending on it eventually.

**Review by jeherve — APPROVED** [review]
My IE11 VM won't start anymore, so I could only test in a different browser. I can confirm that the dashboard is displayed nicely and analytics still work.

I'll let someone else test in IE11.

**Review by brbrr — APPROVED** [review]
Dashboard works fine now! 

There is quite a problem with "My Plan" page though, which I think is not related to this PR.

**Comment by jeherve** [comment]
> There is quite a problem with "My Plan" page though, which I think is not related to this PR.

Logged in #12464

**Pull request merged**
