### PR TITLE
Carousel: Fix intermittent issue with unresponsive prev button

### PR DESCRIPTION
**Pull request by andrewserong**
In the carousel, while testing #20222, we noticed that the Previous button is intermittently unresponsive to clicks. This appears to be the result of using the default Swiper settings that has the threshold for swipe set to 0 so (and this is the working theory) clicking the Previous button sometimes gets handled as the beginning of a swiping gesture, instead of as the back button.

To get this working consistently, in this PR we're updating the settings to explicitly allow clicks, and click propagation, and updating the swipe threshold to a minimum `5px` so that if a user moves their mouse a handful of pixels while clicking the button, it will be handled as a click instead of a swipe action. Kudos @ramonjd for looking into these settings! 🙇‍♂️

#### Changes proposed in this Pull Request:

For the Swiper settings used in the carousel:

* Disable preventing clicks (allow clicks)
* Disable preventing click propagation (allow click propagation)
* Set the minimum pixel distance to be interpreted as a swipe to `5px`

More info on the parameters can be found at: https://swiperjs.com/swiper-api#parameters

##### Before

Sometimes (intermittently) the back/prev button wouldn't respond:

https://user-images.githubusercontent.com/14988353/123905004-d7098c80-d9b4-11eb-9622-20d06fb99cc4.mp4

##### After

The back button always behaves:

https://user-images.githubusercontent.com/14988353/123905018-dd980400-d9b4-11eb-8d20-67172f9d9b7d.mp4

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* In your test site enable the Carousel module: `/wp-admin/admin.php?page=jetpack#/writing`
* Add an image gallery to a post and publish
* View the post on the front end of your site and test the carousel on desktop — with this PR applied the back button should behave as expected when clicked
* Test this change on a real mobile device — is the threshold of `5px` okay, does it still feel responsive?

### CODE REVIEW

**Comment by ramonjd** [comment]
Nice fix!

This also fixes browsers interpreting clicks as short swipes for me as well:

**Before (only clicking on the next > arrows and/or anywhere on the carousel overlay) **

Notice the right swipe. This shouldn't happen as I'm clicking on the left arrow (and around it).

guitar-before


**After**

Clicking on the carousel doesn't trigger a slide in the browser. Clicking on the left/right arrows slides left/right as expected.

guitar-after


In my testing it doesn't affect swiping on mobile devices:


https://user-images.githubusercontent.com/6458278/123907175-d4a93180-d9b8-11eb-8ea6-b901dd67ee9f.MP4

**Review by ramonjd — APPROVED** [review]
Thanks for noticing this bug. It's a huge improvement and fixes the problem in my testing.

**Comment by ramonjd** [comment]
And good spotting `preventClicks` too! I missed that one in the API docs.

**Review by jeherve — APPROVED** [review]
This tests well for me. Merging.

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.9` in 918499f647ae6434407f0828568dadd31702fbcd

**Pull request merged**
