### PR TITLE
Remove Omnisearch.

### PR DESCRIPTION
**Pull request by georgestephanis**
When the time comes to remove Omnisearch, this pull request includes everything that should be deleted.

### CODE REVIEW

**Comment by kraftbj** [comment]
What's the backstory? Are we planning on removing Omnisearch? Personally, I find it really helpful.

**Comment by georgestephanis** [comment]
@kraftbj It's just a usage vs clutter question.  It didn't seem to get much usage on wpcom, so rather than have a bunch of unused features scattered around Jetpack, figured it may be better to ditch it.

**Comment by samhotchkiss** [comment]
Closing this for now, we can reopen when we're ready to pull the trigger...

**Comment by georgestephanis** [comment]
Reopening per discussion with @beaulebens on Slack.

**Comment by dereksmart** [comment]
replaced by #7590

**Pull request closed without merging**
