### PR TITLE
Prompt to auto verify existing Google Verify users

### PR DESCRIPTION
**Pull request by gravityrail**
#### Changes proposed in this Pull Request:

* Prompt existing google verify users with "auto verify" button
* Auto-verified sites will see a cancel button instead

#### Testing instructions:

*

### CODE REVIEW

**Comment by jeherve** [comment]
@gravityrail @Tug Will any of you have the chance to work on that before the code freeze next Tuesday (October 30)?

**Comment by gravityrail** [comment]
@jeherve I can take a look on Monday

**Comment by scottsweb** [comment]
Is this still being worked on? If so I can do a design review but it will need to be updated with changes from master.

Otherwise, time to close?

**Comment by eeeeevon13** [comment]
Removing design review from this issue as it does not appear to be being worked.

**Comment by Tug** [comment]
This doesn't look relevant anymore, I guess we should close it.

**Pull request closed without merging**
