### PR TITLE
Janitorial: update node version requirement to 14.16.1

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Calypso updated their requirements in https://github.com/Automattic/wp-calypso/pull/51756
Let's do the same in Jetpack and packages.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Test all the builds that were impacted. Do they run well?

### CODE REVIEW

**Comment by jeherve** [comment]
@anomiex Adding you as reviewer; is this version of node available to you yet?

**Comment by anomiex** [comment]
Still on 14.16.0 at the moment.

**Comment by jeherve** [comment]
> Still on 14.16.0 at the moment.

👍 I'll put this on hold for now then.

**Review by creativecoder — APPROVED** [review]
Tested this by running `yarn build` at the repo root. All projects were built successfully (without errors) for me.

**Comment by jeherve** [comment]
> Still on 14.16.0 at the moment.

@anomiex Is 14.16.1 available to you now, by any chance?

**Comment by anomiex** [comment]
Yeah, I can install 14.17.0 now.

**Comment by jeherve** [comment]
> Yeah, I can install 14.17.0 now.

Excellent! Let's bump to 14.16.1 then, since that's what Calypso is using at the moment.

**Review by anomiex — APPROVED** [review]
This made me realize something like #20200 could be useful, to avoid a potential situation where we merge this then #20085 resulting in CI breaking.

It wouldn't prevent vice versa though. I'm not sure what a good way to catch something like that might be, or if we even want to try.

**Comment by jeherve** [comment]
r227923-wpcom

**Pull request merged**
