### PR TITLE
webpack-config: Configure minifier to preserve translator comments

### LINKED ISSUE #16549: Admin Page i18n: translator comments are not available in production build
Now that we've moved to using `@wordpress/i18n`, we can rely on translator comments to provide some help to translators, like so:

```js
title = sprintf(
	/* translators: Placeholder is a version number. */
	__( 'New in Jetpack %s', 'jetpack' ),
	this.props.version
);
```

Unfortunately, those comments are dropped from our production build that is used by WordPress.org when extracting strings that need to be translated, so those comments are lost. Let's see if we can tweak Webpack config to avoid losing those comments in the production build.

Primary issue: #16481

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

This drops use of calypso-build's terser configuration in favor of one
that preserves the translator comments (and doesn't keep the various
licensing comments inline). It also simplifies the calculation of
terser's `ecma` option to match how terser actually uses it (e.g. terser
doesn't do anything different for "2015" versus "2019").
    
As for css-minimizer-webpack-plugin, this updates it from version 1.3.0
(used by calypso-build) to 3.1.1, which brings a new minification
technique that sorts the declarations for better compression.

This also fixes some code in Jetpack where the minifier loses translator
comments.

#### Jetpack product discussion

Fixes #16549

PT: p9dueE-3MG-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Is CI happy?
* Check the built JS files for the presence of "translators" comments.
* Maybe check various Jetpack JS UIs to make sure the sorting of CSS declarations doesn't somehow break something.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Looks good, translations appear in minified files, nothing broken. Just needs some merge conflict fixes 👍

**Comment by anomiex** [comment]
Needs re-review after merge conflict fixes

**Review by sdixon194 — DISMISSED** [review]

**Comment by anomiex** [comment]
Needs re-review (again) after merge conflict fixes.

On the plus side, I took advantage of that to drop the dep on calypso-build now instead of having to do a separate PR for it.

**Review by sdixon194 — APPROVED** [review]

**Comment by anomiex** [comment]
r234971-wpcom

**Pull request merged**
