### PR TITLE
Fix Network Admin screen connection status when Jetpack is installed in MU-Plugins

### LINKED ISSUE #13478: Placing Jetpack in mu-plugins causes Network Admin to report incorrectly
On the Network Sites page, Jetpack has a check here that looks to see if the Jetpack plugin is active:

https://github.com/Automattic/jetpack/blob/master/class.jetpack-network-sites-list-table.php#L82

An issue presents itself then if Jetpack is in the mu-plugins directory as it is on all VIP Go sites. This leads to a confusing experience because pages like this:

example.com/wp-admin/network/admin.php?page=jetpack

Will read Jetpack is not active on this site. under "Connected" despite the site actually being correctly connected and Jetpack being active.

@kraftbj suggested one possible approach:

> For the Jetpack network admin, we could add a check || array_keys( get_mu_plugins(), 'jetpack.php', true (need to check what the key is right, jetpack.php or mu-plugins/jetpack.php, etc) to match what is returned and match what VIP Go uses. It may be cleaner for us to add a filter there since any mu-plugin-loaded Jetpack network would have to be custom on some level.

This has come up with several VIP clients, and I imagine others that use a similar `mu-plugins` approach.

### PR DESCRIPTION
**Pull request by mikeyarce**
Fixes #13478

#### Changes proposed in this Pull Request:
* Add a check for the plugin located in mu-plugins

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

## Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Open up a WordPress Multisite
* Go to `wp-admin/network/admin.php?page=jetpack` 
* Verify that the "Connected" Column correctly displays the connection status of the network sites
Screen Shot 2022-07-18 at 1 41 30 PM

### CODE REVIEW

**Comment by jeherve** [comment]
@mikeyarce Is this still valid? If so, do you think you could update with latest `origin/trunk` and ensure the tests aren't failing and the comment above is all green?

Thank you!

**Comment by mikeyarce** [comment]
> @mikeyarce Is this still valid? If so, do you think you could update with latest `origin/trunk` and ensure the tests aren't failing and the comment above is all green?
> 
> Thank you!

I'm not sure if it's still valid.  Maybe @WPprodigy or @lschuyler can check?  This was an issue on VIP.

**Comment by oskosk** [comment]
Pushed a rebase in https://github.com/Automattic/jetpack/pull/25122/commits/95fe09cfd903d2b6bca063a6ca2349765d025edf

**Review by oskosk — APPROVED** [review]
LGTM

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
