### PR TITLE
Remove historical changelog data from readme.txt

### PR DESCRIPTION
**Pull request by dd32**
WordPress.org parses the readme.txt file for the information to use on the WordPress.org plugin pages.
There's a limitation that exists that many plugins never hit, but Jetpack has - only the first 50KB of the readme.txt file can be parsed.

Currently the readme.txt file is 86KB, ~80KB of that being the historical changelogs (all the way back to v1.0.0!). The size of readme.txt is 9.6K after this PR.
I'm proposing that the historical changelogs (In this PR, it's 3.6.1 and below) be moved to a changelog.txt file.

In my mind, the ideal scenario would be:
1) The current branch changelog is included in the readme
2) All of the changelogs (current branch, and historical) is available in changelog.txt.

You might want to also add a note somewhere (perhaps at the end of the existing changelog?) that further changelogs are available in the changelog.txt file.

### CODE REVIEW

**Comment by zinigor** [comment]
Looks good, thank you!

**Comment by dd32** [comment]
Something I forgot to mention here, was that as part of the WordPress.org translation efforts, readme's are also available for translation - including the changelogs, as can be seen within https://translate.wordpress.org/projects/wp-plugins/jetpack/stable-readme moving these old changelog entries out of the readme also avoids them being listed for translation.

**Comment by kraftbj** [comment]
I'm okay removing the historical changelog out of the plugin totally and pointing people to a jetpack.me/changelog page. 80kb less "bloat"!

**Comment by kraftbj** [comment]
@zinigor What do you think about doing some piece of this (either moving to changelog.txt per the PR or moving to the website) for 3.7.1 since the readme.txt is available for public translation now ( e.g. https://translate.wordpress.org/projects/wp-plugins/jetpack/stable-readme/la/default )?

AFAIK, this is separate from our discussion on language packs vs shipping with languages since readme translation is part of the directory, not WP itself.

**Comment by zinigor** [comment]
Since there's already a changelog for 3.7.1, this PR needs an update. I will update it next week.

**Comment by zinigor** [comment]
Closing in favor of #2735

**Pull request closed without merging**
