### PR TITLE
Sharing Plugin: Keep polishing implementation

### PR DESCRIPTION
**Pull request by retrofox**
This is a follow-up PR of https://github.com/Automattic/jetpack/pull/20944.

Enhancements

* Replace HOC with hooks
* Pick up store definition from a package instead of hardcoding its definition.
* Move components into its proper folder

Related https://github.com/Automattic/jetpack/issues/16816

#### Changes proposed in this Pull Request:

* Polish plugin sharing implementation

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Activate the `Like buttons` module from https://<your-deb-site>/wp-admin/admin.php?page=jetpack#/sharing
image

* Create a new post
* Confirm it's rendered in the Jetpack sidebar rightly.

* Confirm the `Show sharing buttons` value is properly updated by clicking on the proper checkbox after saving the post. Additionally, You can take a look at the async request from the dev tool - network tab:

Screen Shot 2021-09-08 at 2 25 09 PM

* In the end, simply confirm the feature keeps working as expected :smart:

### CODE REVIEW

**Comment by pablinos** [comment]
This is working well for me. There are some lint errors that we need to address, but apart from that I think it's good to go.

**Review by pablinos — APPROVED** [review]
LGTM!

**Review by jeherve — APPROVED** [review]
This looks good to me. 🚢

**Comment by retrofox** [comment]
Tested in JN and dotcom.  r231547-wpcom

**Pull request merged**
