### PR TITLE
ci: Test against PHP 8.4

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

It'll be released soon, let's try testing against it.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None worth linking.

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy?

### CODE REVIEW

**Comment by anomiex** [comment]
"In progress" because the first step here is to turn it on and see what breaks 😀

**Comment by anomiex** [comment]
First thing, Composer 2.7.7 raises a bunch of deprecation notices. So, #40257.

**Comment by anomiex** [comment]
Seems to be passing now

**Review by tbradsha — APPROVED** [review]
It passes!

**Pull request merged**
