### PR TITLE
Widget Visibility: Fix "Match all" setting being overwritten on saving in the block editor. 

### LINKED ISSUE #22249: Widget Visibility: "Match All" setting force-defaults on
### Impacted plugin

Jetpack

### Steps to Reproduce

    Install Jetpack
    Instal Classic Widgets plugin
    Enable Jetpack's Widget Visibility
    Add Categories widget to a widget area and add two conditions (I did show on page and post)
    Make sure visibility is not set to "match all conditions"
    Disable Classic Widgets plugin
    Go back to the Widgets and open the "Categories" widget
    Change something (such as dropdown) and update
    Navigate away and then back to the widgets screen and "Match All Conditions" will be checked

### A clear and concise description of what you expected to happen.

The Match All option should be optional.

### What actually happened

It stays checked.

### Other information

Reported via 4618949-zen

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #22249

#### Changes proposed in this Pull Request:

Checking for a non-empty value is necessary when saving in the widget block editor. I don't know exactly what changed in the block widgets update process, but this solves the issue at hand. 

#### Jetpack product discussion

No

#### Does this pull request change what data or activity we track or use?

No 

#### Testing instructions:

This is how to reproduce the issue and verify the fix: 

- Install Jetpack
- Instal Classic Widgets plugin
- Enable Jetpack's Widget Visibility
- Add Categories widget to a widget area and add two conditions (I did show on page and post)
- Make sure visibility is not set to "match all conditions"
- Disable Classic Widgets plugin
- Go back to the Widgets and open the "Categories" widget
- Change something (such as dropdown) and update
- Navigate away and then back to the widgets screen and "Match All Conditions" will be checked

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Tested with:
* Classic Widget Appearance->Widgets
* Classic Widget Customizer
* Block/Site Editor with WP 5.8.
* Block/Site Editor with WP 5.8 and latest stable Gutenberg.

**Comment by dereksmart** [comment]
I'm getting inconsistent testing results testing this patch in wpcom, but I think it's not making anything worse. Legacy widgets there seem very broken over all so it's hard to tell. Would appreciate an extra tester on the wpcom patch if possible D72642-code

**Comment by dereksmart** [comment]
The wpcom diff tested well (needed to sandbox public-api). Deployed in r237805-wpcom

**Comment by kraftbj** [comment]
cherry-picked to `jetpack/branch-10.5` via b8a99eb2c9

**Pull request merged**
