### PR TITLE
Masterbar: Improve menu items when Nav Unification is enabled

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/49122

#### Changes proposed in this Pull Request:

- Set the same admin bar link destinations that we use for Simple sites. These new links are ignored when the Nav Unification is disabled (since we display a custom menu when clicking on any menu item), but are used when enabled, effectively fixing the issues described in https://github.com/Automattic/wp-calypso/issues/49122 and p7DVsv-ago-p2#comment-33901 that was preventing users from managing their site, their reader subscriptions and their account.
- Display the same menu items on small viewports that we display on Simple sites when the Nav Unification is enabled.
- Small CSS fix so larger site icons don't exceed the max width allowed.

#### Jetpack product discussion
N/A.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

_Atomic_
* Use the Jetpack Beta plugin on an Atomic site and switch to this branch.
* On the frontend (any viewport):
    * Make sure "My Sites" redirects you to My Home in Calypso.
    * Make sure "Reader" redirects you to the Calypso Reader.
    * Make sure "Me" redirects you to your account page Calypso.
* On the admin (all viewports):
    * Make sure "My Sites" does not redirect to any place.
    * Make sure "Reader" redirects you to the Calypso Reader.
    * Make sure "Me" redirects you to your account page Calypso.

_Jetpack_
* Make sure the WordPress.com toolbar module is enabled.
* Make sure the Nav Unification is disabled (add `add_filter( 'jetpack_load_admin_menu_class', '__return_false' );`.
* On the frontend (desktop viewport):
    * Make sure "My Sites" shows a sidebar menu hidden on the left.
    * Make sure "Reader" shows a sidebar menu hidden on the left.
    * Make sure "Me" shows a sidebar menu hidden on the right.
* On the frontend (mobile viewport):
    * Make sure "My Sites" and "Reader" are hidden.
    * Make sure "Me" shows a sidebar menu hidden on the right.
* On the admin (desktop viewport):
    * Make sure "My Sites" shows a sidebar menu hidden on the left.
    * Make sure "Reader" shows a sidebar menu hidden on the left.
    * Make sure "Me" shows a sidebar menu hidden on the right.
* On the admin (mobile viewport):
    * Make sure "My Sites" ad "Reader" are hidden.
    * Make sure there is a new "Toggle menu" option that displays the admin menu.
    * Make sure "Me" shows a sidebar menu hidden on the right.
* Make sure the Nav Unification is enabled (add `add_filter( 'jetpack_load_admin_menu_class', '__return_true' );`.
* On the frontend (desktop viewport):
    * Make sure "My Sites" redirects you to Stats in Calypso (My Home is not supported on Jetpack sites).
    * Make sure "Reader" redirects you to the Calypso Reader.
    * Make sure "Me" redirects you to your account page Calypso.
* On the frontend (mobile viewport):
    * Make sure "My Sites" and "Reader" are hidden.
    * Make sure "Me" redirects you to your account page Calypso.
* On the admin (desktop viewport):
    * Make sure "My Sites" redirects you to Stats in Calypso (My Home is not supported on Jetpack sites).
    * Make sure "Reader" redirects you to the Calypso Reader.
    * Make sure "Me" redirects you to your account page Calypso.
* On the admin (mobile viewport):
    * Make sure "My Sites" opens the Admin menu.
    * Make sure "Reader" redirects you to the Calypso Reader.
    * Make sure "Me" redirects you to your account page Calypso.

#### Proposed changelog entry for your changes:
N/A.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
I'm not sure how much this matters, but the click isn't exactly "ignored" when in wp-admin; you still get a color effect on the menu when clicking:


https://user-images.githubusercontent.com/426388/105519883-45e20b80-5cda-11eb-9489-28580d67219b.mov

Other than this, this looks good to me.

**Comment by cpapazoglou** [comment]
This works for me too.

It still seems that Atomic has a totally different approach on how to present items in the masterbar for `max-width: 782px` which we should look further without blocking current PR though.

Simple | Atomic
-------|------
 |

**Comment by cpapazoglou** [comment]
@mmtr can we also address the "Reader" & "Me" links missing in this PR? Related convo p7DVsv-ago-p2#comment-33901

**Comment by mmtr** [comment]
Nice catches @cpapazoglou! Everything should be fixed now.

**Review by cpapazoglou — APPROVED** [review]
Thanks @mmtr for revisiting this! LGTM!

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by mmtr** [comment]
Deployed to WP.com in r219962-wpcom

**Pull request merged**
