### PR TITLE
Instagram Gallery: Add the local user ID as state to the connect URL

### PR DESCRIPTION
**Pull request by pablinos**
If the current user is logged out of WPCOM then the nonce checks fail
when they try to connect to Instagram. By adding the local user ID to
the connect URL the changes in D42574-code will run the nonce checks
against the connected Jetpack user account ID.

#### Testing instructions:

Using this branch and having applied D42574-code. Sandbox the API, and test connecting the Instagram gallery block to Instagram while your connected Jetpack user is logged out of WPCOM.

Everything should work as expected!

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
This is going to need a rebase now.

**Review by scruffian — DISMISSED** [review]
This looks good to me and tests well. The only question I had was whether the endpoints are authenticated.  did a cursory look and couldn't see how they were but I assume they are :)

**Comment by scruffian** [comment]
Rebase ✅

**Review by Copons — DISMISSED** [review]
COOL!

**Review by jeherve — DISMISSED** [review]
This should be good to merge, but I would recommend committing the WordPress.com diff first. 👍

**Comment by pablinos** [comment]
Just to say that I'm just waiting on a code/security review of D42574-code. It wouldn't break anything if this got merged first, but it might be best to wait. p1YhhO-M2-p2

**Comment by Copons** [comment]
@pablinos I've noticed this branch is set to merge onto `update/instagram-gallery-reuse-token`, which has been merged since.
We should rebase and set it to merge onto master.

**Comment by kraftbj** [comment]
I changed the base to `master` and marked it for a fresh review to make sure nothing odd changes.

**Comment by Copons** [comment]
Just FYI, we are exploring a different approach in D42794 that doesn't need any JP change. 🙂

**Comment by pablinos** [comment]
I've abandoned D42574-code in favour of D42794-code, so this is no longer needed.

**Pull request closed without merging**
