### PR TITLE
Add VIP slug

### LINKED ISSUE #8857: Admin Page: Add VIP slug
In #8306, we added using the 'vip' slug to influence the active feature array, but we didn't add it to the admin page.

The result is the admin pages thinks VIP sites are free and offer them upgrade prompts.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #8857

#### Changes proposed in this Pull Request:

* Add VIP as a plan type

#### Testing instructions:

* Flag a Jetpack site as VIP via the RC
* Visit the Jetpack->Settings page and notice upgrade prompts
* Apply patch
* Dashboard should reflect a professional-level plan

Note to the reviewer: I'm weak in react/JS/etc, so I'm not sure if I hit all of the right places for the Plans page to be okay and for the prompts to disappear.

### CODE REVIEW

**Comment by oskosk** [comment]
Checking... Looks like there's still a file where an updated could be needed. (settings-card/index.jsx)

**Comment by kraftbj** [comment]
I'm not really sure if it is needed in that file. The VIP slug should return true for being a business plan, and I think it all is just checking if an upgrade to professional should be offered, then offer that. As a business plan, none of those CTAs should fire either way.

I added it just to have it available.

**Comment by oskosk** [comment]
@kraftbj problem is that just importing it and not using it is making the linter fail in Travis (There's a rule for unused vars).

**Comment by kraftbj** [comment]
@oskosk Alrighty. It looks like @dereksmart took care of it, unless you see some reason it should be in the settings-card/index.jsx. I didn't so didn't include it originally.

**Pull request merged**
