### PR TITLE
Embed Blocks: Append 'Embed' to the titles of Facebook and Instagram embed blocks

### LINKED ISSUE #39965: Embed block names with same name as the social icon blocks are causing confusions and also E2E failure
### Impacted plugin

Jetpack

### Quick summary

We've recently change the name of YouTube, Twitter etc blocks to YouTube Embed and Twitter Embed, here https://github.com/WordPress/gutenberg/pull/63371/files .

However, the name of the embedding block for Facebook and Instagram has not been changed. Because these two embed blocks are variations of embed blocks added by Jetpack introduced here https://github.com/Automattic/jetpack/pull/17192 .

So it looks confusing for users. Also causd E2E test failures because we couldn't select the correct Embed by name which we temporarily fixed by https://github.com/Automattic/wp-calypso/pull/95282.

To have these properly fixed, we should be changing the name to Instagram Embed so the intention and functionality are more easily understandable.

#### Insta has two blocks with same name and icon
Image

#### Facebook has three!
Image

The issue was initially created on the [Gutenberg repo](https://github.com/WordPress/gutenberg/issues/66087). But it turned out to be a Jetpack issue. So we are creating here with more details

### Steps to reproduce

1. Create a fresh simple site
2. Create a new post
3. Go to block inserter and search by either Instagram or facebook.

### A clear and concise description of what you expected to happen.

Easily understand which one is an Embed block

### What actually happened

Multiple blocks with same name

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Imran92**
Fixes https://github.com/Automattic/jetpack/issues/39965

## Proposed changes:

* Appended the word "Embed" to Facebook and Instagram embed blocks similar to https://github.com/WordPress/gutenberg/pull/63371

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1730122114799509-slack-C02NWDZBL0H

## Does this pull request change what data or activity we track or use?

Not sure

## Testing instructions:

Follow instructions from https://github.com/Automattic/jetpack/pull/39970#issuecomment-2447698950

* Go to a Post/Page editor screen
* Search for the Instagram and Facebook embed block in the inserter
* Make sure the titles of both of these blocks have "Embed" appended to them

### Screenshots
Screenshot 2024-10-30 at 10 53 40 PM
Screenshot 2024-10-30 at 10 53 54 PM

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Since "Embed" is an English word, should we make that title translatable?

**Comment by Imran92** [comment]
> Since "Embed" is an English word, should we make that title translatable?

Thanks @jeherve ! I mistakenly took that as a Noun. I've updated them here https://github.com/Automattic/jetpack/pull/39970/commits/b2fc835ce3ec20b871881f420d24bb7a0fdbd25a.

Do we have anything like 'string-freeze' on Jetpack? I was curious about what should be the behavior till the translation becomes ready

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
> Do we have anything like 'string-freeze' on Jetpack? I was curious about what should be the behavior till the translation becomes ready

We don't anymore. I'm afraid the block will appear untranslated until the next batch of translations is pushed.

**Comment by Imran92** [comment]
> We don't anymore. I'm afraid the block will appear untranslated until the next batch of translations is pushed.

Oh, thanks for clarifying! I'll just go ahead and merge the branch to trunk then once CI passes.

**Pull request merged**
