### PR TITLE
Update jsdoc comments to better match WordPress coding standards

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

More specifically, this enables a few linting rules from `@wordpress/eslint-plugin` that had previously been disabled:

* For `jsdoc/check-tag-names`, prefer `@return` and `@yield` over `@returns` and `@yields`.
* Enable `jsdoc/check-line-alignment` for certain tags, most notably `@param.
* Exclude aligned tags from `jsdoc/check-indentation` to avoid conflict with `jsdoc/check-line-alignment`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Followup to #38436
Draft announcement: pdWQjU-OP-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Look sensible?

### CODE REVIEW

**Comment by anomiex** [comment]
Note we'll probably want to do a trunk merge just before merging this, to make sure this won't break on any jsdoc comments added in other commits. Then we'll want to update the pr-update-to tag to try to make sure people don't merge other PRs with jsdocs that would be broken with the changes here.

**Comment by anomiex** [comment]
If someone wants to get this merged while I'm AFK, here's about how I've been resolving the conflicts in a trunk merge:

* `git checkout --theirs <files>` to take the trunk versions.
* `pnpm dedupe` if pnpm-lock was one of the files.
* `tools/fixup-project-versions.sh` to fix any versions needing fixing.
* `pnpm lint-required --fix` to re-fix any issues in non-excluded files.
* `git add` everything done so far.
* To fix just the jsdoc errors in excluded files, do this (assuming your checkout is somewhere under `/usr/`): `for f in $(pnpm lint | perl -nwe 'BEGIN { $f = ""; } $f=$_ if /^\/usr\//; if ( /jsdoc\/(check-tag-names|check-line-alignment|check-indentation)$/ ) { print $f if $f; $f=""; }'); do  echo "== $f =="; pnpm lint-file --resolve-plugins-relative-to tools/js-tools/ --fix --no-eslintrc --config <( pnpm exec eslint --print-config "$f" | jq '.rules |= pick( .["jsdoc/check-line-alignment"], .["jsdoc/check-tag-names"], .["jsdoc/check-indentation"] )' ) "$f"; done`
  * Ignore the unfixable errors like "Invalid JSDoc tag name "ssr-ready"".
  * Note there are currently three fixed by that that aren't worth fixing right now since they cascade into more issues, you'd have to rewrite the entire doc blocks.
  * If you want a detailed explanation of how that works, ChatGPT's breakdown at p1722019255037219/1722019229.334469-slack-C02SV8APDTM seems accurate (but the summary at the end gets a little lost).

**Comment by zinigor** [comment]
This looks like it needs another trunk merge, sorry :) I have reviewed it before my AFK, but couldn't get to merge it.

**Comment by anomiex** [comment]
No problem, something like this needs very frequent merges 😀

**Review by zinigor — APPROVED** [review]

**Pull request merged**
