### PR TITLE
Search: Allow unconnected admins to manage settings

### PR DESCRIPTION
**Pull request by jsnmoon**
Requires D74015-code!

#### Changes proposed in this Pull Request:
Fixes a bug that prevented non-connected admins on Jetpack sites from managing Jetpack Search settings. We now query Search plan information as a blog, not as a user.

#### Jetpack product discussion
p8oabR-Nm-p2#comment-5924

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Ensure D74015-code has been applied and public-api sandboxed.
* Apply this change to your site with an active Jetpack Search subscription.
* Log into your wp-admin using an admin user that hasn't been connected to WPCOM.
* Navigate to the Search Dashboard (`/wp-admin/admin.php?page=jetpack-search`).
* Ensure that the dashboard works as expected.
* Click on the "Customize search results" button; ensure that the search configurator works as expected.

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
Thanks @jsnmoon this looks good and test well to me.

**Comment by kangzj** [comment]
Hi @jeherve could you please cherry pick this to 10.6. Thanks 🙏

**Comment by kangzj** [comment]
D74015-code is deployed already.

**Comment by jeherve** [comment]
- Cherry-picked to `jetpack/branch-10.6` in 56f55e476f9341bf6f3e8392acfe9e7dbb015146
- Releasing a new version of the package in #22560

**Pull request merged**
