### PR TITLE
My Jetpack: Add tracking events to Plans section external links

### LINKED ISSUE #23168: My Jetpack: Fire tracks event when clicking the manage/purchase link on the Plans section
image

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #23168

#### Changes proposed in this Pull Request:

* Added tracking events to Plans section external links

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

Yes, it adds two new links to the set of clicks we are tracking in the My Jetpack page. Under the Plans section, there's always a link to either "Purchase a plan" (when there's no current plan) or a link to "Manage your plan". We are now tracking clicks in these links.

#### Testing instructions:

* Go to My Jetpack
* enable debugging of tracking events (type: `localStorage.setItem('debug', 'dops:analytics');` in the console)
* Click "Manage your plan" or "Purchase a plan" and verify the correspondent event is tracked
* Make sure the event tracked matches the link label and destination
* Are the event names good?
* Check for typos

### CODE REVIEW

**Comment by sdixon194** [comment]
Looks like there's a file conflict here.

**Review by retrofox — DISMISSED** [review]
LGTM

**Review by oskosk — APPROVED** [review]
Thanks!

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-10.8` in 6a703e6653e30d2c7ed6f3a1490aaee43e272bd3
Automattic/jetpack-my-jetpack version `v0.6.13` published: https://packagist.org/packages/automattic/jetpack-my-jetpack#v0.6.13

**Pull request merged**
