### PR TITLE
E2E: test with latest Gutenberg

### PR DESCRIPTION
**Pull request by simison**
#### Changes proposed in this Pull Request:
* Run E2E setup with latest Gutenberg plugin active

##### TODO
Update some legacy CSS selectors in tests.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
- Update E2E setup

#### Testing instructions:
- CI E2E task

#### Proposed changelog entry for your changes:
- N/A

### CODE REVIEW

**Review by brbrr — CHANGES_REQUESTED** [review]
As you can see, E2E tests are failing due to TypeError: `TypeError: Cannot read property 'disableTips' of null`

FWIW, I think it makes more sense not to replace the existing setup, but run them in a separate job.

**Comment by simison** [comment]
Yeap, a bunch of CSS selectors and that tips disabling function need to be fixed. Happy if someone can help with those; I'm little limited by headspace.

Tips are no longer a thing in Gutenberg plugin (and thus in WP 4.5) — they replaced it with "welcome modal" instead.

Some CSS selectors have been deprecated and removed, too.

Do you have thoughts on how to check for the Gutenberg plugin version/availability in E2E tests to make them conditional based on it?

**Comment by simison** [comment]
An alternative to this would be running Jetpack E2E tests in Atomic container and use the latest Gutenberg plugin there. That would test the most relevant combo; wpcom+latest Gutenberg.

**Comment by ockham** [comment]
Possibly superseded by #15784.

**Comment by brbrr** [comment]
closing this since #15784 is merged

**Pull request closed without merging**
