### PR TITLE
Update boost score bar to use reusable component

### PR DESCRIPTION
**Pull request by CodeyGuyDylan**
Replaces existing `ScoreBar.svelte` component with the package React component. Also removes unused code

## Proposed changes:
 * Remove `ScoreBar.svelte`
 * Use React Score Bar package component instead
 * Remove unused SVGs
 * Remove unused CSS

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

P2: p1HpG7-k9o-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

1. Checkout these changes - `git switch update/boost-score-bar-to-use-reusable-component`
2. Start up your local environment
3. Run `jetpack install plugins/boost && jetpack build plugins/boost`
*Alternatively to steps 2 and 3, you can use the Jetpack Beta plugin on a jurassic ninja site
4. If you haven't already, install the Jetpack Boost plugin on your site
5. Go to `/wp-admin/admin.php?page=jetpack-boost` and make sure the score bars look and behave as they did before
image

### CODE REVIEW

**Comment by thingalon** [comment]
E2E tests are broken in trunk. Fix is here: https://github.com/Automattic/jetpack/pull/30809 will merge it here as soon as https://github.com/Automattic/jetpack/pull/30809 is merged.

**Review by IanRamosC — APPROVED** [review]
Nice cleanup. I can confirm it behaves as expected. ✅

**Review by thingalon — DISMISSED** [review]
Seems mostly good, thank you. There is one weird corner, though: 

image

The info popout is behind the checkbox below it :)

**Comment by CodeyGuyDylan** [comment]
@thingalon It looks like this issue was introduced [here](https://github.com/Automattic/jetpack/pull/30751/files#diff-ffee771c7c72d29cf41e4939f39b10e4cd0e08b264ea4423856d6b46918461c4R9), when I remove that z-index of 10, the text is now behind the modal

This PR didn't really touch anything outside of the specifically the score bars, so I think this one is good to go. I'll go ahead and merge for now since that was the only issue you found 😄 

Let me know if you see anything else and I can take a look

**Comment by CodeyGuyDylan** [comment]
FWIW I didn't want to just remove the z-index there, as the PR where it was introduced was fixing some UI bugs, so I thought it may re-introduce a bug or multiple bugs it was meant to fix, so I didn't want to get too into that 😄

**Pull request merged**
