### PR TITLE
Add License Activation Flow to Jetpack Plugin 

### PR DESCRIPTION
**Pull request by cbauerman**
#### Changes proposed in this Pull Request:

* Add `js-package/licensing` to Jetpack Plugin
* Add `js-package/api` to `js-package/licensing` and hook up activation flow.

**Note** The activation flow is functionally complete but will still need additional styling in a follow-up PR
**Note** This PR does not contain "success" screens for every Jetpack Product. Those will be added in #21770 

Un-activated                       |  Activation Success
:-------------------------:|:-------------------------:
Screen Shot 2021-11-16 at 4 45 54 PM | Screen Shot 2021-11-16 at 4 30 51 PM

#### Jetpack product discussion

p1HpG7-cSg-p2

#### Testing instructions:

1. Navigate to `/wp-admin/admin.php?page=jetpack#/license/activation`
2. Put an invalid license into the license field and click "Activate"
3. Verify an error appears underneath the license field
4. Aquire a valid license ( complete a siteless Jetpack purchase with `add_filter( 'jetpack_license_checkout_m2_enabled', '__return_true' );` included in your `0-sandbox.php` and `public-api.wordpress.com` )
5. Put a valid license into the license field and click "Activate"
6. Verify you are taken to the success screen

### CODE REVIEW

**Review by rcanepa — COMMENTED** [review]
Overall, the activation flow seems to work as expected.

Before shipping this, can we include these two points?
1. Make the `You have an inactive product.` banner lead users to `/license/activation`. 
 https://github.com/Automattic/jetpack/blob/13725698199e054f9ec34d2871d97d8d0a7ba629/projects/plugins/jetpack/_inc/client/components/jetpack-notices/user-license-activation.jsx#L47-L48
2. Refetch the site's products after a successful product activation. Currently, one has to refresh the page to see the activated product in the My Plan section. I'm not completely sure about this, but I suspect we need to distpach the `fetchSiteProducts` action after right after we verify the product has been activated. I also wonder whether we need to pass the `ActivationScreen` component a new prop (e.g., `onSuccess`) to avoid coupling the new JS package with the app state of the plugin.

**Comment by elliottprogrammer** [comment]
Also, in addition to @rcanepa's [comment](https://github.com/Automattic/jetpack/pull/21764#pullrequestreview-808587418), in order to get the `You have an inactive product` notice working properly, we need to trigger a couple actions upon successful license activation.  When the license is successfully attached without errors, (when we call `restApi.attachLicenses( [ license ] ).then(...`) we need to call `updateUserLicensesCounts();` and `updateLicensingActivationNoticeDismiss()` located in `state/licensing/actions.js`

I'm not sure if we want to do this in this PR, or in a follow up PR, but wanted to make a note of it here so we are all aware of it.

**Comment by rcanepa** [comment]
> Also, in addition to @rcanepa's [comment](https://github.com/Automattic/jetpack/pull/21764#pullrequestreview-808587418) above, in order to get the `You have an inactive product` notice working properly, we need to trigger a couple actions upon successful license activation. So for example, when the license is successfully attached without errors, (when we call `restApi.attachLicenses( [ license ] ).then(...`) we need to call `updateUserLicensesCounts();` and `updateLicensingActivationNoticeDismiss()` located in `state/licensing/actions.js`
> 
> I'm not sure if we want to do this in this PR, or in a follow up PR, but wanted to make a note of it here so we are all aware of it.

Thanks for providing those details, Bryan. I'm fine if we do all of these changes in a follow-up PR since they are not as simple as I thought before.

**Comment by cbauerman** [comment]
> 🔴 Add changelog entries to affected projects

This is from an accidental reformat to the api package, these PR contains _NO_ changes to the API package.

**Comment by cbauerman** [comment]
> > Also, in addition to @rcanepa's [comment](https://github.com/Automattic/jetpack/pull/21764#pullrequestreview-808587418) above, in order to get the `You have an inactive product` notice working properly, we need to trigger a couple actions upon successful license activation. So for example, when the license is successfully attached without errors, (when we call `restApi.attachLicenses( [ license ] ).then(...`) we need to call `updateUserLicensesCounts();` and `updateLicensingActivationNoticeDismiss()` located in `state/licensing/actions.js`
> > I'm not sure if we want to do this in this PR, or in a follow up PR, but wanted to make a note of it here so we are all aware of it.
> 
> Thanks for providing those details, Bryan. I'm fine if we do all of these changes in a follow-up PR since they are not as simple as I thought before.

I went ahead an put a `onActivationSuccess` function that is called when the API returns a successful activation.

**Review by rcanepa — APPROVED** [review]
LGTM! Everything looks and works as expected now.

I made a small recording of several activation attempts to test failure and success cases (I merged https://github.com/Automattic/jetpack/pull/21770 into your branch to see the success screens for other products).

https://user-images.githubusercontent.com/3418513/142419374-3cc30269-0ddc-4461-8062-2f6fd03f9ce9.mp4

**Review by elliottprogrammer — APPROVED** [review]
Yes, I tested this also, and the license activation flow (both error and success cases) are working good as expected.  LGTM also. 👍

**Comment by sdixon194** [comment]
The regular flow works well and is slick. I tried to break things a few ways and ran into a handful of errors that might need addressing:

**Upgrading Again**

I tried to activate a Backup license, which worked. Then I tried to activate a Complete license on top of that. The licensing page gave me an error, however the plan was upgraded correctly and viewable on my Plan page.
Screen Shot on 2021-11-19 at 14:33:51




**Userless Connection**

I tried activating a license after connecting without a wpcom account (Set Up Jetpack, then selecting back on the browser when routed to connect my wpcom account), and only got this Null error:
Screen Shot on 2021-11-19 at 14:17:28

**Comment by cbauerman** [comment]
> The regular flow works well and is slick. I tried to break things a few ways and ran into a handful of errors that might need addressing:

These errors look like they are coming directly from the API and will need to be addressed separately on the WPCOM side. However we may wish to follow up on this PR to improve the display of the errors, which seem rather unhelpful income cases.

**Comment by cbauerman** [comment]
@sdixon194 we are capturing the errors in Asana ( I'll add the links when we have them ) but we are sure they either involve the API in WPCOM or the underlying implementation of `attach_licenses` endpoint in the API package, both of which are out of the scope for this particular PR.

**Comment by cbauerman** [comment]
> @sdixon194 we are capturing the errors in Asana ( I'll add the links when we have them ) but we are sure they either involve the API in WPCOM or the underlying implementation of `attach_licenses` endpoint in the API package, both of which are out of the scope for this particular PR.

The Asana Tasks are:

- 1201096622142517-as-1201400491645539
- 1201096622142517-as-1201400491645534

**Review by sdixon194 — APPROVED** [review]

**Review by sdixon194 — APPROVED** [review]

**Comment by cbauerman** [comment]
> Great news! One last step: head over to your WordPress.com diff, D70262-code, and commit it. Once you've done so, come back to this PR and add a comment with your changeset ID.
> 
> **Thank you!**

> `Committed revision 235377.`

**Pull request merged**
