### PR TITLE
Publicize: Remove assets directory

### PR DESCRIPTION
**Pull request by mdawaffe**
These files are no longer required.

Some were no longer needed as of 3.0. Others as of 7.1. Others somewhere in between.

#### Changes proposed in this Pull Request:
* Removes the entire `modules/publicize/assets/` directory.

#### Testing instructions:
I couldn't find any reference to any of these files. Try playing around with Settings -> Sharing, and the Publicize UI in both Classic and Block editors to see if you can generate any 404s.

#### Proposed changelog entry for your changes:
* Remove files no longer required after recent Publicize changes.

### CODE REVIEW

**Comment by mdawaffe** [comment]
I don't think we need to ship this in 7.1.

**Comment by mdawaffe** [comment]
@zinigor, some of these files this PR removes are referenced in [`/modules/photon-cdn/jetpack-manifest.php`](https://github.com/Automattic/jetpack/blob/294ca9d8cd0bc6f4802d8bfac8f60110d382a180/modules/photon-cdn/jetpack-manifest.php).

I tried running [`/bin/build-asset-cdn-json.php`](https://github.com/Automattic/jetpack/blob/294ca9d8cd0bc6f4802d8bfac8f60110d382a180/bin/build-asset-cdn-json.php), but there were a few problems:
* It looks like that script should only be run in built branches (otherwise, it catches `/docker/`, `/vendor/`, `/.eslintrc.js`, etc.)
* Even taking those into account, there were a several other changes. That is, the version of jetpack-manifest.php in master is out of date.

Does the version of jetpack-manifest.php in master matter? Should we keep it up to date every now and then, or do we only ever care about the version(s) of that file built by `/tools/deploy-to-svn.sh`?

**Review by jeherve — APPROVED** [review]
This should be good to go.

> some of these files this PR removes are referenced in [`/modules/photon-cdn/jetpack-manifest.php`](https://github.com/Automattic/jetpack/blob/294ca9d8cd0bc6f4802d8bfac8f60110d382a180/modules/photon-cdn/jetpack-manifest.php).

We have a few things like that, like languages, that aren't always up to date on `master`. I don't know if that is really important, but we can always run an update on `master` after merging your PR?

**Comment by mdawaffe** [comment]
Running it on master generates a bunch of entries for `docker`, `vendor`, etc., which we don't want. We can make it work. Or ignore it :) As you say, I don't think it's too important.

**Pull request merged**
