### PR TITLE
Remove unnecessary React imports

### LINKED ISSUE #36764: Jetpack Blocks: ensure blocks import wordpress-element instead of React
Make sure blocks import `wordpress-element` instead of React, for consistency.

Idea brought up by @jeherve here: https://github.com/Automattic/jetpack/pull/36758#discussion_r1553892436.

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/36764

## Proposed changes:

This PR refactors the import statements of some blocks to:
- remove unnecessary React imports
- import functions from `@wordpress/element` instead of `react`, when possible

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

You might want to add some of the changed blocks (e.g., VideoPress, MailChimp, Eventbrite, Markdown, Contact Form) to a new post/page and check there's no error in the editor/site.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]

**Comment by dhasilva** [comment]
Typescript files on VSCode report errors when React is not imported. @jeherve @monsieur-z

**Comment by jeherve** [comment]
@dhasilva Do you still see the issue after installing all the dependencies? I don't see those warnings on my end for some reason. I'm not quite sure what `React` reference is triggering this error in your IDE.

image

**Comment by dhasilva** [comment]
Yes. I just ran `git pull && pnpm install && nice jetpack install -r && nice jetpack install --all && nice jetpack build --all` and restarted VSCode, the ts error is still there :thinking:

**Comment by jeherve** [comment]
👍 It may be something specific to my setup that gets rid of the error, so I'll let others weigh in on that.

**Comment by dhasilva** [comment]
Or something specific in mine somehow. I'll add the React import on the files I'm working on to avoid that distraction for now, until we find out what exactly is causing that and can make a P2 post on how to disable it for everyone.

**Pull request merged**
