### PR TITLE
Contact Form: Adjust Form placeholder colors

### LINKED ISSUE #27985: Form Block - Placeholder View: Fixing the color inconsistencies
This view has currently three different colors, for not particular reason.
If "green" would be used for Jetpack branding reasons, then let's use it consistently as primary color, for "icon boxes", button, and link colors?

Or only the main block icon on top stays green, and everything else has the primary color of the WP site, here "blue".

Image

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27985

#### Changes proposed in this Pull Request:
* Adjusts the Form placeholder icons and link colors for better consistency

Before
image

After
image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Create a post and add a Form block
* Check if the icons and link colors are more consistent now

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Nice João!

Color issue on the placeholder view is fixed, thanks so much!

But I noticed that in the block library, the icons of the "template blocks" are not green anymore 🤷 ?

Is this related to these changes?

image

**Comment by jcheringer** [comment]
Glad you noticed it, @digitalwaveride. Thanks!
My last commit should fix the issue.

**Review by digitalwaveride — APPROVED** [review]
Thanks João! 
Great! 🚀

**Review by coder-karen — APPROVED** [review]
Looks good :shipit:

**Pull request merged**
