### PR TITLE
API: bring in Mailchimp / AMP changes to bring files in sync

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* This PR brings in 4 changes from WordPress.com to bring files back in sync:
- r202919-wpcom
- r197819-wpcom
- r196688-wpcom
- r203171-wpcom

**However, we can't merge it as is just yet, as the changes add a number of PHPCS errors that trigger our pre-commit hook.**

```
FILE: ...ev/jpdev/wp-content/plugins/jetpack/class.json-api-endpoints.php
----------------------------------------------------------------------
 2078 | WARNING | [ ] Processing form data without nonce
      |         |     verification.
      |         |     (WordPress.Security.NonceVerification.Recommended)
 2078 | WARNING | [ ] Processing form data without nonce
      |         |     verification.
      |         |     (WordPress.Security.NonceVerification.Recommended)
 2081 | ERROR   | [ ] Doc comment for parameter "$siteurl"
      |         |     missing
      |         |     (Squiz.Commenting.FunctionComment.MissingParamTag)
 2082 | ERROR   | [x] Whitespace found at end of line
      |         |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 2087 | WARNING | [ ] parse_url() is discouraged because of
      |         |     inconsistency in the output across PHP
      |         |     versions; use wp_parse_url() instead.
      |         |     (WordPress.WP.AlternativeFunctions.parse_url_parse_url)
 2088 | ERROR   | [ ] Empty line required before block comment
      |         |     (Squiz.Commenting.BlockComment.NoEmptyLineBefore)
 2099 | ERROR   | [x] Short array syntax is not allowed
      |         |     (Generic.Arrays.DisallowShortArraySyntax.Found)
 2099 | ERROR   | [x] Short array syntax is not allowed
      |         |     (Generic.Arrays.DisallowShortArraySyntax.Found)
 2100 | ERROR   | [x] Short array syntax is not allowed
      |         |     (Generic.Arrays.DisallowShortArraySyntax.Found)
 2101 | ERROR   | [x] Whitespace found at end of line
      |         |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 2113 | ERROR   | [ ] Doc comment for parameter "$siteurl"
      |         |     missing
      |         |     (Squiz.Commenting.FunctionComment.MissingParamTag)
 2119 | WARNING | [ ] Processing form data without nonce
      |         |     verification.
      |         |     (WordPress.Security.NonceVerification.Recommended)
 2123 | WARNING | [ ] Processing form data without nonce
      |         |     verification.
      |         |     (WordPress.Security.NonceVerification.Recommended)
 2124 | WARNING | [x] Equals sign not aligned with surrounding
      |         |     assignments; expected 3 spaces but found 1
      |         |     space
      |         |     (Generic.Formatting.MultipleStatementAlignment.NotSameWarning)
 2125 | ERROR   | [x] Whitespace found at end of line
      |         |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
 2126 | ERROR   | [ ] Use Yoda Condition checks, you must.
      |         |     (WordPress.PHP.YodaConditions.NotYoda)
 2141 | ERROR   | [ ] Missing parameter comment
      |         |     (Squiz.Commenting.FunctionComment.MissingParamComment)
 2143 | ERROR   | [ ] Return type missing for @return tag in function
      |         |     comment
      |         |     (Squiz.Commenting.FunctionComment.MissingReturnType)
 2148 | ERROR   | [ ] Visibility must be declared on method
      |         |     "callback"
      |         |     (Squiz.Scope.MethodScope.Missing)
----------------------------------------------------------------------

FILE: ...ve/Sites/dev/jpdev/wp-content/plugins/jetpack/class.json-api.php
----------------------------------------------------------------------
 386 | ERROR   | [x] String "Access-Control-Allow-Origin: " does not
     |         |     require double quotes; use single quotes
     |         |     instead
     |         |     (Squiz.Strings.DoubleQuoteUsage.NotRequired)
----------------------------------------------------------------------
```

@jeffersonrabb Could you work on fixing those errors in a new WordPress.com diff, commit your changes there, and then bring those changes back to this PR in an additional commit, so we can solve those issues?

Thank you!

#### Testing instructions:

* TBD (see D33928-code and D38795-code)

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
> Could you work on fixing those errors in a new WordPress.com diff, commit your changes there, and then bring those changes back to this PR in an additional commit, so we can solve those issues?

Yup! `D38970-code`

The only confusing bits were the `Squiz.WhiteSpace.SuperfluousWhitespace.EndLine` items. I'm seeing all of the other errors/warnings in my local Jetpack repo, but not those. I checked and wasn't seeing any extra whitespace in those lines, so it's possible that issue still remains but I'm not sure how to verify.

**Comment by jeherve** [comment]
@jeffersonrabb Thank you. I reviewed the diff, it looks good, only one tiny change left to make phpcs happy :)

**Comment by jeherve** [comment]
@jeffersonrabb Thanks! I've brought your patch over to this PR now that you've committed it. Do you think you could review this PR to make sure it includes all your changes?

Thank you!

**Review by zinigor — APPROVED** [review]
The changes look consistent with what happened in WordPress.com, and I don't think these change any behaviour on Jetpack side. I couldn't find any usage of the newly added method either in existing code, or in the new code.

**Comment by jeffersonrabb** [comment]
> I couldn't find any usage of the newly added method either in existing code, or in the new code.

That's correct. These changes apply exclusively to WP.com, not Jetpack.

**Pull request merged**
