### PR TITLE
Contact Form: Remove textarea border setting

### PR DESCRIPTION
**Pull request by scruffian**
Fixes https://github.com/Automattic/themes/issues/4049

#### Changes proposed in this Pull Request:

By setting a specific color on the textarea, the block is preventing the theme CSS from being applied. This removes this specific style which allows the theme CSS to be applied, but it does also reveal an issue with the core CSS which is presumably why this rule was added. IMO the new issue is less severe so this solution is preferable.

Before:

Seedlet:
Screenshot 2021-06-30 at 17 35 17

Quadrat:
Screenshot 2021-06-30 at 17 36 41

After:

Seedlet:
Screenshot 2021-06-30 at 17 31 16

Quadrat:
Screenshot 2021-06-30 at 17 29 54

#### Testing instructions:

* Switch to the Quadrat theme
* Open the editor
* Add a contact form 
* Confirm that the textarea has the correct border color

### CODE REVIEW

**Comment by jeherve** [comment]
> it does also reveal an issue with the core CSS which is presumably why this rule was added.

Yes, it appears it was added in #15362 to solve the styling issues you pointed out. I'm honestly not sure which one is best; I suppose it depends on the percentage of themes that define custom styles for form elements.

If the issue is specific to one theme, would it be an option to make the change more specific in that specific theme?

**Comment by scruffian** [comment]
The practice of adding block specific fixes to themes leads to a lot of maintenance issues when changes are made to those blocks and potentially hundreds of themes need to be updated. I would rather add styles to Seedlet to target all textareas so it matches in the editor.

**Review by jeherve — APPROVED** [review]
Alright, let's merge this and see if we get any feedback from many folks about the change. 🚢

**Comment by scruffian** [comment]
Thanks!

**Comment by jeherve** [comment]
r228740-wpcom

**Pull request merged**
