### PR TITLE
Sync: Load listener and sender for cron jobs

### LINKED ISSUE #4977: Sync: Should we load the listener and sender in cron?
A user recently reported that his site was no longer publicizing to Twitter after the 4.2 update.

After quite a bit of debugging and a [test plugin](https://gist.github.com/ebinnion/423ae37f25fad6cabf4faea045db1691) I was able to confirm that posts were not synced to WP.com under certain when cron was disabled via `DISABLE_WP_CRON` and DISABLE_WP_CRON constant and I manually went to `$site/wp-cron.php?doing_wp_cron`.

I was able to get subscription emails and publicize to work by adding the following to my test plugin:

```
add_filter( 'jetpack_sync_listener_should_load', '__return_true' );
add_filter( 'jetpack_sync_sender_should_load', '__return_true' );
```

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #4977 by loading the sync listener and sender for cron jobs.

Marking as in progress while I test.

### CODE REVIEW

**Comment by gravityrail** [comment]
I’ve seen some code that also looks for $_GET[‘doing_cron’] - should we look for that too?

**Comment by ebinnion** [comment]
I don't believe so. To my knowledge, `doing_wp_cron` is a flag of sorts so that we don't fire off multiple crons at the same time.

To support WP Cron, it looks like there are two methods.

1) The standard method makes a POST request to `$site/wp-cron.php`. https://github.com/WordPress/WordPress/blob/master/wp-includes/cron.php#L329-L340

2) The alternate cron method redirects the user to `REQUEST_URI?doing_wp_cron` and then attempts to perform cron jobs in the current request.

In both cases, we load the `wp-cron.php` file which defines the `DOING_CRON` constant. https://github.com/WordPress/WordPress/blob/master/wp-includes/cron.php#L329-L340

So, I don't think we need to check for `$_GET['doing_wp_cron']`.

**Comment by ebinnion** [comment]
In my tests, posts were successfully publicized.

screen shot 2016-08-30 at 6 41 20 pm

**Comment by lezama** [comment]
:shipit:

**Comment by ebinnion** [comment]
Picked to `branch-4.2`.

**Pull request merged**
