### PR TITLE
Search: Fix PHP notices.

### PR DESCRIPTION
**Pull request by kraftbj**
While dogfooding, saw a few notices on my site.

2020-10-28 at 12 10 AM

#### Changes proposed in this Pull Request:
* Checks for an array key before using it.
* Fix a couple of other minor PHPCS violations.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
* Not 100% sure, but:
* Spin up a new JP site using 2019/
* Add JP Search to the site.
* Load homepage.
* It may be possible I have some legacy stuff hanging out in the site that's causing it.

#### Proposed changelog entry for your changes:
* Search: resolve a minor PHP notice.

### CODE REVIEW

**Comment by anomiex** [comment]
This sort of thing makes me wary. It doesn't look like a filter without a "type" is actually valid, but maybe I'm missing something. So where did the filters without a "type" come from? Should they be ignored entirely, instead of used with the empty string as a type?

**Comment by kraftbj** [comment]
That makes sense. I'll dig into my site a bit to figure out what is saved in there to produce this state.

**Comment by kraftbj** [comment]
```
array(2) {
    ["title"]=>
    string(0) ""
    ["filters"]=>
    array(8) {
      [0]=>
      array(1) {
        [0]=>       ///// Notice the extra level of array here compared to the one below. //////
        array(3) {
          ["name"]=>
          string(0) ""
          ["type"]=>
          string(9) "post_type"
          ["count"]=>
          int(5)
        }
      }
      [1]=>
      array(4) {
        ["name"]=>
        string(0) ""
        ["type"]=>
        string(8) "taxonomy"
        ["taxonomy"]=>
        string(9) "faq-topic"
        ["count"]=>
        int(5)
      }
```

I deleted the widget on my site and added a fresh set, which seemed to resolve the issue. I'm not sure how it got into that state. The better solution may be to fix the widget option, but I'm not too sure.

**Comment by jsnmoon** [comment]
> ```
> array(2) {
>     ["title"]=>
>     string(0) ""
>     ["filters"]=>
>     array(8) {
>       [0]=>
>       array(1) {
>         [0]=>       ///// Notice the extra level of array here compared to the one below. //////
>         array(3) {
>           ["name"]=>
>           string(0) ""
>           ["type"]=>
>           string(9) "post_type"
>           ["count"]=>
>           int(5)
>         }
>       }
>       [1]=>
>       array(4) {
>         ["name"]=>
>         string(0) ""
>         ["type"]=>
>         string(8) "taxonomy"
>         ["taxonomy"]=>
>         string(9) "faq-topic"
>         ["count"]=>
>         int(5)
>       }
> ```
> 
> I deleted the widget on my site and added a fresh set, which seemed to resolve the issue. I'm not sure how it got into that state. The better solution may be to fix the widget option, but I'm not too sure.

Could this be caused by the [option defaults value here](https://github.com/Automattic/jetpack/blob/master/modules/widgets/search.php#L253)? We appear to use a nested array for the `filters` value, which is [then defaulted to a taxonomy filter](https://github.com/Automattic/jetpack/blob/master/modules/widgets/search.php#L912).

**Comment by anomiex** [comment]
The nested array is certainly suspicious, although in Kraft's case it somehow got something added to it.

**Comment by gibrown** [comment]
@kraftbj this has been falling through the cracks. I guess it needs to get refactored now though for the repo changes? The changes themselves look good to me though.

**Comment by kraftbj** [comment]
Sounds good. I'll rebase and ping you for the checkmark when all checks pass.

**Comment by kraftbj** [comment]
@gibrown Rebased. Smaller diff since some of the minor phpcs tweaks I made while in there were already merged in other PRs since this was originally drafted.

**Review by jeherve — APPROVED** [review]

**Review by jeherve — DISMISSED** [review]

**Review by sergeymitr — APPROVED** [review]

**Pull request merged**
