### PR TITLE
Shared Extension Utilities: Initial setup of the package

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request:

This is the skeleton of the new shared-extension-utils package that will
house the code that currently resides in the `extensions/shared` folder
of the Jetpack plugin.

#### Jetpack product discussion
p9dueE-4cw-p2#comment-7082

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
There probably isn't much to test currently. Maybe we just need to check that it's setup correctly and that `jetpack install --all` works.

### CODE REVIEW

**Review by danielpost — DISMISSED** [review]
Looks good to me! I don't think there's much that I can offer input on here, Crew will know more 👍🏼

**Review by kraftbj — APPROVED** [review]
Everything installed well. I updated the PR to include the nyc devdep that was missing from the skeleton

**Review by jeherve — APPROVED** [review]

**Comment by pablinos** [comment]
Thanks for reviewing and merging this @kraftbj and @jeherve! Is `nyc` a new dependency? The package was generated using the `jetpack generate` command, so we might need to update the templates.

Do we need to merge D73808-code? It doesn't seem necessary as we're not using this package yet, but does that mean things get out of sync?

Lastly, in order to release the package, do we need to make mirror repos etc, as we do with the composer packages, and if so, is that something I can do?

**Comment by jeherve** [comment]
>  Is nyc a new dependency? The package was generated using the jetpack generate command, so we might need to update the templates.

Yes. #22471 added it to the template, but after you ran it I think.

> Do we need to merge D73808-code? It doesn't seem necessary as we're not using this package yet, but does that mean things get out of sync?

Yes, it would be nice to commit it, if only to keep the lock file in sync.

> in order to release the package, do we need to make mirror repos etc, as we do with the composer packages, and if so, is that something I can do?

For now we can use it within the monorepo, the common lock file will ensure that projects can use it within the monorepo.

To release it publicly, there are a few things that need to be done:
1. Remove `private` here: https://github.com/Automattic/jetpack/blob/3980b6e31b4bcb657b9efa5421389648a238fe43/projects/js-packages/shared-extension-utils/package.json#L2
2. Create a mirror repo as per https://github.com/Automattic/jetpack/blob/549a2d73505eb312fefa9b56f800abf16f407e5e/docs/monorepo.md#L259 and follow the instructions here; we'll need to add all the info in the package's `composer.json`, and the necessary secrets so it can be pushed to npm automatically. 

I'll take care of all of this for you later today.

**Comment by pablinos** [comment]
Ah of course, it's only going to be used by other projects in the repo for now. Thanks for taking care of it!

I'll get the patch merged.

**Comment by pablinos** [comment]
r239109-wpcom

**Pull request merged**
