### PR TITLE
Jetpack Sync: Ensure duplicate Sync modules are not loaded

### PR DESCRIPTION
**Pull request by fgiannar**
This PR ensures that no matter the consumer Sync configuration or usage of the `jetpack_sync_modules` filter, no duplicate Sync modules will be loaded.

## Proposed changes:

* `Automattic\Jetpack\Sync\Modules`: Update `initialize_modules` to ensure the list of Sync module classnames returned after applying the `jetpack_sync_modules` filter is unique.
* Update Sync's README to make it clear that only the default Sync modules are configurable by the consumers.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p9dueE-8kC-p2

## Testing instructions:

Pre-requisites: A JN site with WooCommerce and WooCommerce Payments plugins active (latest stable versions). We'll also need the Jetpack Beta plugin to switch between Bleeding Edge and this branch.

Attention: Make sure to setup your store by running the WooCommerce setup wizard before testing.

With the Jetpack plugin on Bleeding Edge:
* Run the following in `wp shell`: `return Automattic\Jetpack\Sync\Modules::get_modules()`
* Check the list of Sync modules and confirm that `WooCommerce` and `WooCommerce_HPOS_Orders` are listed twice

With the current branch:
* Repeat the above and confirm that `WooCommerce` and `WooCommerce_HPOS_Orders` are listed once (you'll need to exit `wp shell` first)

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
I have a Jurassic Ninja test site using bleeding edge Jetpack, WoCommerce and Woo Payments, 1 order (synced), set up to use HPOS, but the list of Sync modules has `WooCommerce` and `WooCommerce_HPOS_Orders` listed only once under `jetpack_sync_modules`. Is there something I might be missing in setting things up for testing?

**Comment by fgiannar** [comment]
> I have a Jurassic Ninja test site using bleeding edge Jetpack, WoCommerce and Woo Payments, 1 order (synced), set up to use HPOS, but the list of Sync modules has `WooCommerce` and `WooCommerce_HPOS_Orders` listed only once under `jetpack_sync_modules`. Is there something I might be missing in setting things up for testing?

It's possible that WooCommerce analytics tracking is off, which is strange because I thought it's enabled by default. Can you please got to WooCommerce->Settings->Advanced->Features and confirm that `Enable WooCommerce Analytics` is checked as displayed below?

Screenshot 2024-07-25 at 12 15 46

**Comment by fgiannar** [comment]
> I have a Jurassic Ninja test site using bleeding edge Jetpack, WoCommerce and Woo Payments,

Are you also testing with WCPay on bleeding edge? I'd suggest testing with the latest stable because WCPay also fixed this issue yesterday on their end: https://github.com/Automattic/woocommerce-payments/pull/9152

**Comment by fgiannar** [comment]
@coder-karen You were right, turns out we need to run the WooCommerce setup wizard before reproducing this. I have updated the test instructions accordingly

**Review by coder-karen — APPROVED** [review]
Running the tests on a second Jurassic Ninja site I was able to test properly, and the duplication was removed.

**Pull request merged**
