### PR TITLE
[WIP] Business Hours Block: v2 Updates

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/jetpack/issues/15702

#### Changes proposed in this Pull Request:
Update the business hours block to address the feedback in #15702. This is a work in progress.

#### Testing instructions:

* No testing yet please.

#### Proposed changelog entry for your changes:

* Will add at a later date.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
looking good @apeatling, just a thought on Aesthetics - the transition from view to edit is quote jarring, so I wonder of it is worth adding some animation to this, the following isn't perfect, but gives an idea of something that might work:

business-hours

This is done by adding and removing 'is-edit' and 'is-view' classes:
```javascript
const classes = classNames( className, ! hasFetched ? 'is-fetching' : undefined, isSelected ? 'is-edit' : 'is-view' );
```
and the following css
```css
	&.is-edit {
		opacity: 1;
		animation: fade-edit 0.2s ease-out;
		transform-origin: top left;
	}

	&.is-view {
		opacity: 1;
		animation: fade-view 0.2s ease-out;
		transform-origin: top left;
	}

	@keyframes fade-edit {
		0% { opacity: 0;
			transform: scaleX(0);
		 }
		100% { opacity: 1;
			transform: scaleX(1); 
		}
	}

	@keyframes fade-view {
		0% { opacity: 0;
			transform: scaleX(1.5);
		}
		100% { opacity: 1;
			transform: scaleX(1);
		}
	}
```
It is a bit glitchy as it runs on the initial add and load as well, but happy to do some more work on it if you think this is worth pursuing further. It would be great to have something like https://www.react-spring.io/ in the blocks, as it is hard to get good transitions back and forth as the different components are pulled in and out of the dom, but react-spring always you to animate this component transitions.

**Comment by glendaviesnz** [comment]
Another thing we started doing in the Instagram Gallery block is pulling out the api business logic into a custom hook. This helps to keep the component focused on the UI logic, and also makes it easier to share some of the api business logic between components. Here's how this would look in the terms of this component - https://github.com/Automattic/jetpack/commit/cc2f948b2433d637516a3095d5111930f3ec847f

**Comment by apeatling** [comment]
@glendaviesnz Thanks for taking a look. 

>  the transition from view to edit is quite jarring, so I wonder of it is worth adding some animation to this

Totally agree this is jarring, the animation helps. I think the ideal here is to remove the controls entirely from the canvas, see https://github.com/Automattic/jetpack/pull/15362. There shouldn't be a dramatic difference between editing and viewing, that way there is no transition at all. Similar to how the Contact Form block has been updated in https://github.com/Automattic/jetpack/pull/15362. Seeing how you did this animation work is really useful though and could still be applicable in the coming updates.

**Comment by apeatling** [comment]
Closing this one for now since it's not going to get any active work from me for some time. Can be referred back to later, or @glendaviesnz if you are interested in taking it further feel free to pick it up!

**Pull request closed without merging**
