### PR TITLE
CRM: UI Cohesiveness Project

### PR DESCRIPTION
**Pull request by gogdzl**
This is the feature branch for the Cohesiveness Project.

---------

## Proposed changes:
This PR is the feature branch for the Cohesiveness Project.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pbhBOz-2Wj-p2

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:

* Test all individual features from the following epics:
   * [Menu Overhaul](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Menu+Overhaul)
   * [Dashboard Facelift](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Dashboard+Facelift)
   * [Edit Quote Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Edit+Quote+Page)
   * [Settings Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Settings+Page)
   * [Edit Invoice Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Edit+Invoice+Page)
   * [Edit Transaction Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Edit+Transaction+Page)
   * [Edit Contact Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Edit+Contact+Page)
   * [Edit Company Page](https://github.com/orgs/Automattic/projects/524/views/14?layout=table&groupedBy%5BcolumnId%5D=32160120&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Linked+pull+requests%22%2C%22Status%22%2C22506999%2C32160120%2C22506998%2C%22Labels%22%2C22506925%2C%22Repository%22%2C%22Milestone%22%5D&filterQuery=project%3A%22UI+Cohesiveness+%28Light%29%22+Edit+Company+Page)

### CODE REVIEW

**Comment by coder-karen** [comment]
Tested everything (that wasn't added by me), looks good! 🥳  

I'm not sure whether you want an official approve by someone other than me though - someone who hasn't worked on as many UI cohesiveness PRs.

**Review by coder-karen — DISMISSED** [review]
Just realized you're AFK very soon, so adding an approve here now.

**Review by tbradsha — COMMENTED** [review]
While I didn't do a line-by-line review of the code, I've clicked through the various pages that should have been affected by the closed issues, and don't notice anything off.

I am curious about the standalone commit you added, which doesn't seem to have any impact. Can you clarify what the goal was there?

**Comment by gogdzl** [comment]
@coder-karen Thanks for testing it!

> I'm not sure whether you want an official approve by someone other than me though

Every approval counts! If yours is the only one I get it is already good enough!

**Comment by gogdzl** [comment]
> I am curious about the standalone commit you added, which doesn't seem to have any impact. Can you clarify what the goal was there?

I thought the chart was too close to the button, but turns out I was wrong. 
I have reverted it back, and removed my comment from the PR description.

**Comment by cleacos** [comment]
More eyes here... testing this too

**Review by cleacos — DISMISSED** [review]
In theory, all those PRs are already reviewed. This is a general EPIC review, right? before merging the branch into the trunk. I didn't see any console errors and nothing seems broken.

I don't know if this was part of this project, but creating a new Quote, the `Use Quote Builder` button needs some padding at the bottom:

image

Other than that, here is my 👍

**Comment by gogdzl** [comment]
> I don't know if this was part of this project, but creating a new Quote, the Use Quote Builder button needs some padding at the bottom

It wasn't, but this is a simple change that makes the CRM looks nicer. I've already made this change. c743d99

**Review by tbradsha — APPROVED** [review]
Make it so!

**Pull request merged**
