### PR TITLE
Update composer to 2.3.5

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

The `tool-setup` action will automatically install 2.2.12 instead if
it's setting up for an older PHP version.

#### Jetpack product discussion

p9dueE-4SC-p2#comment-7753

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Is CI happy?

### CODE REVIEW

**Comment by kraftbj** [comment]
For timing, let's merge this after Jetpack 10.9 goes stable and any other infra updates that are needed (I'm not aware of any atm).

**Comment by anomiex** [comment]
Note GitHub is going to suggest an incorrect commit message when this is squashed-and-merged (it'll say "2.2.11" rather than "2.2.12"). Please update it before merging.

**Review by sdixon194 — APPROVED** [review]

**Comment by anomiex** [comment]
r244968-wpcom

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-10.9` in 5823923ca913080a113bfa8cd2f340a926e5aede

**Pull request merged**
