### PR TITLE
Social Menu & Social Media Icons: Add Telegram

### LINKED ISSUE #16281: Social Menu & Social Media Icons: Add Telegram Support
When I add a **t.me/nickname** or **telegram.me/nickname** Telegram profile link the icon is a generic "chain" and not the official paper plane one:
image

### PR DESCRIPTION
**Pull request by 360fun**
Fixes #16281

#### Changes proposed in this Pull Request:

This PR: 
- Adds a new Telegram SVG from automattic/social-logos
- Starts using that SVG in both the widget and the Social Menu

#### Jetpack product discussion

* No

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

Start with a site that runs a theme such as [Floral](https://wordpress.com/theme/floral)

* Go to Jetpack > Settings, and enable the Widgets feature
* Go to Appearance > Customize > Widgets, and add a Social Icons widget to your site.
* Paste a link to a Telegram profile, e.g. t.me/nickname or telegram.me/nickname
* Ensure that the widget uses a Telegram logo.
* In Appearance > Customize > Menu, add a social menu using a similar link, then verify the icon displays as expected.

#### Proposed changelog entry for your changes:

* Social Menu & Social Media Icons: add support for Telegram profiles.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Thank you for your contribution!

For the new SVG to be usable, you would have to add references to it in the widget and Social menu. You can check https://github.com/Automattic/jetpack/pull/15065/files for an example.

You should be able to remove the alternate version of the logo for now. We'll only be able to refer to one of those in the widget and Social Menu, and Telegram seems to use the version with a background in [their branding documents](https://telegram.org/tour/screenshots).

I would also recommend that you add testing instructions to your Pull request.

**Review by 360fun — COMMENTED** [review]
I removed the alt icon

**Comment by 360fun** [comment]
I made a bit a mess with the pull requests...sorry 😩

**Comment by jeherve** [comment]
> I made a bit a mess with the pull requests...sorry 😩

No worries. I took the liberty to update this PR to bring in the different changes you had committed in the other branches. I also made a couple of changes to ensure the widget and the social menu would use the correct domains to detect Telegram links. I also updated the PR description to include testing instructions.

What I did not do, however, is test. :) Could you pull the changes I made to your own local copy of Jetpack, and test those changes? 

Let us know if everything works well.

**Comment by 360fun** [comment]
I found out that I've to compile it in order to test...it means create the environment to do so and I've no time do that. :(
I'll be happy to test the compiled version if you can make it, thanks! :)

**Review by jeherve — APPROVED** [review]
This tests well for me. Merging.

**Comment by jeherve** [comment]
Internal reference: r215491-wpcom

**Comment by 360fun** [comment]
Awesome 🥰 happy to help!

**Pull request merged**
