### PR TITLE
SEO Tools: add archive_title page title token

### LINKED ISSUE #8918: SEO Tools: Archive titles only support the date archive pages, not any other archives (CPT, ...)
974268-zen

The Archives setting only has options for Site Title, Tagline and Date:

image

For Custom Post Type archive pages, if you leave it blank, the title structure is:

**Post type - Site Title**

Could we add an option for 'Archive Title' so that the structure can be customized but still include the post type?

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

* For the custom Archives page title structure in SEO Tools, add a more generic `archive_title` token which builds on the current `date` token.
* Usage of `[date]` will continue to work on a site, but we'll hide the "Date" insertion button in favor of "Archive Title".
* This will allow sites to display proper names on custom post type archives (e.g. "Projects" for the JP CPT at `/portfolio`), while still showing the date on date-based archives.
* Fixes #8918

#### Jetpack product discussion

#8918
https://github.com/Automattic/wp-calypso/pull/56084

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* With changes pulled down, on a Jetpack connected site, head to `/wp-admin/admin.php?page=jetpack#/traffic`
* Make sure `Customize your SEO settings` is enabled.
* Click on `Expand to customize the page title structures of your site.`
* For `Archives` use the buttons to insert each token presented (Site Title, Tagline, and Archive Title).
* Since we are no longer showing the `+ Date` button, manually type in `[date]`.
* You should now see an updated preview beneath the input. Both [date] and [archive_title] will show "Example Archive Title/Date" in preview.
* Click `Save settings` and refresh to make sure the custom Archive title persists.
* Check a custom post type archive page. For example you can enable Jetpack's custom Portfolio type, then view that archive at `example.com/portfolio/`. In the `<title>` you should see "Projects" replacing the `[archive_title]` and `[date]` tokens.
* Check a date archive (e.g. `example.com/2019/09`. Here you should see the appropriate date replacing the `[archive_title]` and `[date]` tokens.

Next, spin up the Calypso portion: https://github.com/Automattic/wp-calypso/pull/56084

* Navigate to `calypso.localhost:3000/marketing/traffic/example.com`
* Find the `Archives` section and make sure you see the correct custom Archives title you set in WP Admin.
* Try removing the existing `Date` and `Archive Title` token by clicking, and then adding them again.
* Customize your title a bit more and save. Then refresh and make sure it persists.
* Again check on the frontend portfolio and date-based archive pages to make sure the correct `<title>` comes through.
* To note, the Date button will only be replaced with the Archive Title button on Jetpack versions `>= 10.2-alpha`

Before:

After:

Calypso After:

Example `/portfolio` title:

> Custom Archives Title - Site Title: Jurassic Testing - Tagline: Just another WordPress site - Date: Projects - Archive Title: Projects

Example `/2021/09/` title:

> Custom Archives Title - Site Title: Jurassic Testing - Tagline: Just another WordPress site - Date: September 2021 - Archive Title: September 2021

### CODE REVIEW

**Comment by samiff** [comment]
@jeherve Before I start poking around in Calypso, what do you think of this approach?

**Review by jeherve — COMMENTED** [review]
> @jeherve Before I start poking around in Calypso, what do you think of this approach?

I think that makes perfect sense, it's more logical than before.

I would, however, recommend that we keep transforming the `[date]` token in the interface, to avoid things like this on sites that are already set up:

image

**Comment by samiff** [comment]
> recommend that we keep transforming the `[date]` token in the interface

That makes sense, I've changed things up so we are essentially only hiding the `Date` button now in wp-admin and Calypso. We still want the [date] tokenization to occur as normal, otherwise someone might not notice the change to [date] when saving other titles.

**Review by jeherve — APPROVED** [review]
This tests well for me. I only have a minor remark, but that's not a blocker.

**Review by sdixon194 — APPROVED** [review]

**Comment by samiff** [comment]
@jeherve Could you help me wrap my head around the wp-admin vs Calypso side of this.

If the Calypso side is deployed, then connected WPorg JP sites will see the button to insert the `Archive Title` in Calypso, but this will only be saveable if they are running JP >= 10.2 which adds the `archive_title` to allowed tokens in `jetpack-seo-titles.php`. Otherwise they will get an error when saving custom titles with an `Archive Title` in it.

Is a JP version check needed when adding the `Archive Title` button on the Calypso side, or is there a better way to reconcile this?

**Comment by jeherve** [comment]
> Is a JP version check needed when adding the Archive Title button on the Calypso side, or is there a better way to reconcile this?

That's what I would recommend, yes. Calypso includes utility functions to help you with this.

**Comment by samiff** [comment]
r231579-wpcom

**Pull request merged**
