### PR TITLE
Add context to the "Upgrade" string to differentiate between an upsell and an update

### PR DESCRIPTION
**Pull request by sdnunca**
When a feature requires a user to buy a plan, we show a button with an "Upgrade" label in the product cards.
image

This button should have a separate context to allow for different translations for Upgrade as in Upgrade to a new plan and Upgrade as in Upgrade to the latest version.

This PR addresses all the instance of "Upgrade" I could find that mean Upgrade to a new plan. 

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Code review

## Does this pull request change what data or activity we track or use?
- No.

### CODE REVIEW

**Review by yuliyan — COMMENTED** [review]
It seems like there's already another [string with context](https://github.com/Automattic/jetpack/blob/7f6e4aacf945a419b415177fd7343922f23a505c/projects/plugins/jetpack/_inc/client/components/settings-card/index.jsx#L91-L95) that refers to `Upgrade` as an upsell action.

Would it make sense to use the same context so we can reuse the translations, or do you think it's a different use case?

**Comment by sdnunca** [comment]
The [translation](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/es/default/?filters%5Bterm%5D=Upgrade&filters%5Bcase_sensitive%5D=yes&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bwith_context%5D=yes&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) for "Upgrade" with that context in Spanish is "Actualizar", which is the translation we're trying to avoid.

I've checked a couple more languages and the meaning of the translation seems to be close to software version upgrade. 

I'm hoping that adding a clearer context might improve the translation quality.

**Comment by yuliyan** [comment]
> The [translation](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/es/default/?filters%5Bterm%5D=Upgrade&filters%5Bcase_sensitive%5D=yes&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bwith_context%5D=yes&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) for "Upgrade" with that context in Spanish is "Actualizar", which is the translation we're trying to avoid.
> 
> I've checked a couple more languages and the meaning of the translation seems to be close to software version upgrade.
> 
> I'm hoping that adding a clearer context might improve the translation quality.

Got it, thanks for checking!

**Review by yuliyan — DISMISSED** [review]

**Review by jeherve — COMMENTED** [review]
> Upgrade meaning an upsell

I wonder if this context may introduce another type of confusion. Is this meant to be a noun or a verb? "An upsell" would push me to translate "Upgrade" into a noun, when I think the UI expects a verb. 

How about being more explicit that this expects a verb?

**Comment by sdnunca** [comment]
@jeherve thank you for the feedback. 

Do you think "Call to action to buy a new plan" would better express the intention? 

I'm open to suggestions so if something better comes to mind please feel free to suggest it.

**Comment by jeherve** [comment]
> Do you think "Call to action to buy a new plan" would better express the intention?

I like it, it's clear to me. 👍

**Comment by leogermani** [comment]
I'd also suggest testing this with a couple of languages. Spanish, portuguese and French for instance, to see if there is a good translate.

When thinking in portuguese, I'm not sure there is another one word possible translation. It might become a bigger sentence, with implications in the UI... So there's a chance we'll need to rethink this as a UI.

In any case, this is not a blocker. Adding a context is an improvement anyway. Just saying we should come back later and check what the result is...

**Comment by sdnunca** [comment]
@jeherve I've updated the context string.

Thank you all for the feedback on this.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
