### PR TITLE
Social Menu & Social Media Icons: add StackOverflow support

### PR DESCRIPTION
**Pull request by asamolion**
I recently wanted to add my StackOverflow profile to my website but I found out that jetpack didn't have support for it.

So I decided to add the icons myself.

You can see it working here:
https://alazierplace.com/

I've also added support for [dev.to](https://dev.to/) and can make a PR for it if requried.

Furthermore, I read that there should be some general functionality i.e. the user should be able to add a custom icon that isn't supported. I'm willing to take that on as well if someone can point me in the right direction.

Regards.

#### Testing instructions:
1. Go to `Appearance -> Widgets`
2. Add `Social Icons (Jetpack)` widget to a widget area.
3. Add a stackoverflow.com link to the widget (e.g. https://stackoverflow.com/users/story/4678750)
4. The icon should render on the front-end with stackoverflow's logo icon. 

image

#### Proposed changelog entry for your changes:
* StackOverflow is now supported in Social Icons widget.

### CODE REVIEW

**Comment by jeherve** [comment]
> I've also added support for [dev.to](https://dev.to/) and can make a PR for it if requried.

That would definitely be appreciated, thank you!

**Review by jeherve — DISMISSED** [review]
Most of the other logos include some whitespace around them, but yours does not. As a result, it appears a bit misaligned, as we can see on your site:

image

I think things may look better with a smaller icon with some whitespace above and below it to let it breathe a bit.

**Comment by jeherve** [comment]
> the user should be able to add a custom icon that isn't supported. I'm willing to take that on as well if someone can point me in the right direction.

That could indeed be a nice addition.

**Comment by asamolion** [comment]
@jeherve I've resized the icon like you suggested. I think it fits more appropriately. Let me know what you think.

image

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Closing and re-opening the PR to try to kickstart Travis to connect the green build to the PR.

**Pull request merged**
