### PR TITLE
Markdown Block: Update icon

### PR DESCRIPTION
**Pull request by thomasguillot**
#### Changes proposed in this Pull Request:

* Update icon so it's consistent with Material icons

#### Testing instructions:

* In Post or Page, add a Markdown block via the Block picker
* Does the icon look out of place?

__Before:__
1 before

__After:__
2 after

_Note:
Markdown icon via https://github.com/dcurtis/markdown-mark_

#### Proposed changelog entry for your changes:

* Update Markdown Block icon so it's consistent with Material icons

### CODE REVIEW

**Comment by eeeeevon13** [comment]
@thomasguillot  Having the one filled icon for Markdown does break the UI pattern. Can you clarify for me why we're using the filled in material design icon instead of an outline?  Can I get a little background on this?

**Comment by thomasguillot** [comment]
@eeeeevon13 There is no official outline Material Design Markdown icon.

[The current icon](https://cloudup.com/csepCk7vNs6) is sort of outline style but the thickness of the border isn't [appropriate](https://cloudup.com/ctyZmsG-zef). I'm reluctant to tweak it as it's an official icon. That's why I'm more inclined to use the filled one 😊

**Review by jeherve — APPROVED** [review]
This looks good in my tests. Leaving this for the Design team to review!

**Comment by eeeeevon13** [comment]
@thomasguillot Hmmm, well while the original icon (w/the thinner outlines) is a little "off" the other material icons, using the filled in version IMO is more disruptive as when used next to the outlines, it implies a "selected" state.  Internally we see the lines are thinner on the original outlines and we KNOW that the "official" Material icon would technically be the filled in one. But your average user is not going to look at the icons from that perspective. The icons are there to inform. While our intention is good (to be consistent)  I would argue that we are going to create more confusion by having one singular filled in icon here.

**Comment by eliorivero** [comment]
I agree with that @eeeeevon13 said. The line based icon shares more similarity with the others than the solid shape based icon. I've tried increasing the `strokeWidth` attribute here to `16` https://github.com/Automattic/jetpack/blob/master/extensions/blocks/markdown/index.js#L43
and it looks much better than the thin line it had before and maybe it can be a bit more thicker.

### Before

Captura de Pantalla 2019-05-06 a la(s) 17 38 28

### After

Captura de Pantalla 2019-05-06 a la(s) 17 36 11

**Comment by thomasguillot** [comment]
Fair enough.

**Comment by thomasguillot** [comment]
I don't feel conformable an official icon just to make the lines a bit thicker (otherwise yes, that would have been my first move)

**Pull request closed without merging**
