### PR TITLE
Boost: On premium upgrade (if image guide is enabled), request an ISA report

### PR DESCRIPTION
**Pull request by dilirity**
Fixes https://github.com/Automattic/boost-cloud/issues/310

## Proposed changes:

* If Image Guide is enabled after upgrading to premium and landing on the Purchase Successful page, an Image Size Analysis report will be automatically requested.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup this version of Boost (use the free version);
* Make sure you have images on the website;
* Enable Image Guide;
* Upgrade to Premium;
* After you get redirected back to the Purchase Successful page, click continue and scroll down to the Image Size Analysis section
* There should be a report in progress (or maybe completed).

To easily test the above if you have premium, simply open `/wp-admin/admin.php?page=jetpack-boost#purchase-successful`. This will force the Image Size Analysis to request a report.

### CODE REVIEW

**Review by thingalon — COMMENTED** [review]
The changes here look like they would work.

However, I am not sure we want to kick off a report which will generate hundreds or thousands of requests. See: https://github.com/Automattic/boost-cloud/issues/310#issuecomment-1637306125

**Review by thingalon — DISMISSED** [review]
Ok, after a conversation (https://github.com/Automattic/boost-cloud/issues/310) about it, Iv'e been convinced that this will help demonstrate the value of the subscription after purchase.

**Comment by dilirity** [comment]
After merging with trunk, the linter somehow messed up and made changes to files outside this PR. Reverted the change with [b2be646](https://github.com/Automattic/jetpack/pull/31888/commits/b2be646fa64dfd1aa33e6c10defbf49dbd6d7649).

**Review by thingalon — APPROVED** [review]

**Comment by haqadn** [comment]
Cherry-picked 9cd5215a13

**Pull request merged**
