### PR TITLE
Packages: Use classmap instead of PSR-4

### PR DESCRIPTION
**Pull request by kraftbj**
WPCS disallowed underscores in file names and has a `class-this-is-the-class-name.php` for `Class This_Is_The_Class_Name {` rule.

This PR tries to switch over to composer `classmap` autoloading instead of PSR-4.

Unknown: What impact does this have on the Jetpack_Autoloader? From reading the code, looks like classmap is fine, but haven't confirmed.
 
#### Changes proposed in this Pull Request:
* Change almost all PSR-4 to `classmap`. Autoloader is the exception.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* pMz3w-ay3-p2

#### Testing instructions:
* Test Sync
* Test JITMs
* etc

Make sure everything is still working as expected -- JITMs show, posts are synced to the cache site, etc.

#### Proposed changelog entry for your changes:
* Jetpack Packages: Restructure to comply with WordPress Coding Standards.

cc: @dereksmart @gravityrail @jeherve

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
This is an interesting one. FWIW, when we started exploring splitting Jetpack to packages, we intentionally used PSR-4 as a move in the direction of making Jetpack a more modern piece of code (in terms of modern PHP). 

I'm wondering if we could have the best of both worlds: have some exceptions of the general rule in favor of modern code, while still supporting most of WPCS?

Also, FWIW, I remember some discussions about the fact that over time WPCS should and will start supporting PSR-4. Has that been considered, and is it something that we could suggest upstream?

I'm curious to hear what @enejb and @lezama think about that too.

**Comment by gravityrail** [comment]
I don't mind using classmap but it's a bit of a hack. I would prefer that we create our own classloader, similar to PSR-4, which complies with WP's naming conventions. You could call it "wp-classloader" or something. This will encourage more developer who use it to name their classes according to the WP conventions. This could be done as a composer plugin, perhaps by adding a new "autoload" type here:

https://github.com/Automattic/jetpack/blob/master/packages/autoloader/src/AutoloadGenerator.php#L113

**Comment by dereksmart** [comment]
@gravityrail do you mean that `classmap` generation itself is a hack? Or the way it is implemented in this PR is a hack?

**Comment by gravityrail** [comment]
@dereksmart classmap generation itself is a hack. It relies on parsing the files and figuring out which classes are loaded from which files at build time. That feels hacky to me. But it's not the end of the world.

**Comment by tyxla** [comment]
> @dereksmart classmap generation itself is a hack. It relies on parsing the files and figuring out which classes are loaded from which files at build time. That feels hacky to me. But it's not the end of the world.

Couldn't have said that in a better way, just wanted to drop a message here that this aligns perfectly with how I feel about this change. Since it unblocks us, though, I'm happy to proceed with it for now, if there's no way to get around it for now.

**Comment by enejb** [comment]
Can we do this the other way around. 

First add support for the way WordPress expects the files to be handled and then make the switch this way we only do one migration `PSR-4` => `wp-classname` vs 
`PSR-4` => `classname` => `wp-classname`.

**Comment by kraftbj** [comment]
@enejb To be direct, I don't want to put development time into building a custom WP style autoloader today. Core did a lot of that, but then reverted it out ( https://core.trac.wordpress.org/ticket/36335 ) and with PHP 7.4 having opcache preloading that WP would only benefit from if there was a WP-based autoloader, I would rather us to contribute to Core in landing 36335 versus developing something for us in particular, then maybe needing to migrate from a wp-classmap-by-jetpack to wp-classmap (or whatnot).

The only reason I'm proposing the PSR-4 to classmap migration is to make our file tree compatible with WordPress.com, which hard-enforced the "no underscores in file names" rule. Everything in Jetpack using packages are blocked from being updated on WordPress.com by that. With my belief we should land this first in Core, helping them land an autoloader that we would want to jump onto using or borrow from in the future is a longer term play than what needs to happen short-term to unblock keeping Jetpack functionality up to date on WP.com in a future-maintainable way.

In terms of developers consuming packages and the end result in production, it should be the same either way: just use a class when you need it, so the work of migration will fall on Crew.

In the meantime, there will be a minor headache of developers who are developing packages needing to run `composer dump-autoload` to refresh the mapping when adding/moving new classes. I think we probably could come up with a watcher or run a bit of an assistant during pre-commit to help devs with that.

**Comment by kraftbj** [comment]
Rebased.

**Review by jeherve — DISMISSED** [review]
This seems to test well for me. 👍

**Comment by kraftbj** [comment]
For when this is merged, I was going to run this script. @jeherve Does this look fine to you?

```
<?php
$releases = array(
    'abtest' => '1.0.2',
    'analyzer' => '1.0.3',
    'assets' => '1.0.2',
    // 'autoloader' => null, // (not bumped)
    'backup' => '1.0.1',
    'connection' => '1.1.1',
    'compat' => '1.0.4',
    'constants' => '1.1.3',
    'error' => '1.0.3',
    'jitm' => '1.0.7',
    'logo' => '1.1.3',
    'options' => '1.1.2',
    'roles' => '1.0.3',
    'status' => '1.0.4',
    'sync' => '1.3.3',
    'terms-of-service' => '1.0.1',
    'tracking' => '1.2.2',
);

foreach ( $releases as $package => $version ) {
    $command = sprintf(
        'php bin/release-package.php %1$s %2$s',
        escapeshellarg( $package ),
        escapeshellarg( $version )
    );
    execute( $command, 'Failed ' . $package );
}
```

**Comment by jeherve** [comment]
Sure thing, although I am happy to do it manually as well, it's fairly quick.

**Comment by kraftbj** [comment]
Off topic, but @jeherve, do you have any tricks for knowing the next version to bump to? I ended up just quickly opening github.com/automattic/jetpack-X/releases for each one, but that seems like a suboptimal way to do it as number of packages grow.

**Comment by jeherve** [comment]
@kraftbj I use a few cli autocomplete tools that make this easier for me by improving my cli history and display to show me what version I last released:

image

It's not pretty, obviously only works as long as I am the one running the commands, but it does the job and makes shipping new releases way faster for me so far.

**Comment by kraftbj** [comment]
Rebased again.

**Comment by kraftbj** [comment]
Rebased again.

**Comment by jeherve** [comment]
Rebasing again.

**Review by jeherve — DISMISSED** [review]
Everything seems to work well in my tests. I ran into some issues on a Jurassic Ninja site, but everything seemed to work locally. I would vote to merge this sooner rather than later to avoid having to rebase it again and again, and then see what happens.

**Review by dereksmart — APPROVED** [review]

**Review by zinigor — APPROVED** [review]
LGTM, let's get it in sooner than later to avoid conflicts.

**Pull request merged**
