### PR TITLE
remove get_blog_lang_code() call

### PR DESCRIPTION
**Pull request by paulschreiber**
Fixes `get_blog_lang_code is deprecated since version 2.0.0 with no alternative available.` warning.

### CODE REVIEW

**Comment by brbrr** [comment]
Hi there,

Could you please provide testing instructions for your changes

**Comment by paulschreiber** [comment]
There are no specific testing instructions for this change. Please read over the diff. Do not blindly add this comment to every pull request.

**Comment by brbrr** [comment]
Thanks for your suggestion, @paulschreiber.

One of the main reasons why we have PR template with `Changes proposed in this Pull Request` and `Testing instructions` is to make Jetpack maintainers life a bit easier. You know the context, you have tested your changes. Sharing your knowledge will significantly simplify reviewing your PR. Thanks for understanding.

**Comment by paulschreiber** [comment]
I don't know any of the above things. I saw a warning and removed deprecated code. If code inspection of this diff is not sufficient for you, then please assign this ticket to someone on the project who can perform the tasks you require.

**Comment by dereksmart** [comment]
Hey @paulschreiber thanks for submitting the patch!

Even with the most trivial looking diffs, providing reproducible steps makes things easier for all. Even if the "testing instructions" are as simple as `Do this > see warning.`. 

Example, this changeset is not so trivial when you look into it. The function is not defined nor used in Jetpack, and looks to be there for wordpress.com compatibility where the function is used in many places, and is not documented as deprecated in that codebase.  This file is shared with wordpress.com, and merging this means that we'd be removing it there as well. 

I assume you're seeing this on a VIP site (fivethirtyeight)? 

There is no mention of deprecation of this method in either of these VIP docs, so any more info you can provide would be useful: 
- https://vip.wordpress.com/functions/get_blog_lang_code/
- https://automattic.github.io/vip-go-mu-plugins/

Thanks!

**Comment by kraftbj** [comment]
We'll need to keep this in for the time being. While this function isn't used in Core or on VIP 2.0, it is still used/supported on VIP sites on the classic WordPress.com platform.

**Comment by davisshaver** [comment]
@kraftbj Should I open a Zendesk ticket for this to be revisited? I'm not sure about the long-term sustainability of leaving this deprecated function in there, even if it is used on VIP sites for the time being.

**Comment by davisshaver** [comment]
See https://wordpressvip.zendesk.com/hc/en-us/requests/107947

**Comment by GaryJones** [comment]
The function is indeed defined in WP.com, though there's no `_deprecated_function()` call in it.

It's also not mentioned in the [DeprecatedFunctionsSniff](https://github.com/WordPress/WordPress-Coding-Standards/blob/02af9f6dab171b5782d0945d994fce731915406d/WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php) for WPCS, so I'm unsure where the original warning was coming from.

**Comment by davisshaver** [comment]
@GaryJones It's coming from here: https://github.com/Automattic/vip-go-mu-plugins-built/blob/master/vip-helpers/vip-deprecated.php#L786

**Comment by kraftbj** [comment]
From the Jetpack perspective, I have no opinion on when to remove it since it doesn't impact the plugin proper.

On WP.com, it looks like we probably can switch over to `get_bloginfo`, but would need to look more to confirm.

Reopening for consideration.

**Comment by paulschreiber** [comment]
@kraftbj  what happens now?

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
closing this in favor of #17558. Travis CI does not seem to be too cooperative here for some reason.

**Pull request closed without merging**
