### PR TITLE
Add "noindex" meta to sites in Docker development environment

### PR DESCRIPTION
**Pull request by simison**
~A simple script that ensures search engines won't index your Ngrok-exposed development site. :-)~

~I've had this in my own setup for ages so thought I'd just PR it here.~

From @kraftbj : Modified PR to set the `blog_public` option to 0 upon install to match checking the "Discourage search engines" box when doing a tradition GUI install of WP.

### Testing
Install WordPress fresh within Docker.
Look for robots meta on every page:
```html
<meta name='robots' content='noindex,follow' />
```

### CODE REVIEW

**Comment by jeherve** [comment]
Is it an issue to have our test sites indexed by Google? I kinda like having my site public, as it makes it closer to what a real site looks like.

**Comment by simison** [comment]
Just personal preference — mostly for not end up having spam coming through and malicious robots not finding the site so easily.

Not really a big issue and definitely not feeling strong about having this in. :-)

Fine to close if you prefer to keep the site more close to a real deal. 👍

**Comment by kraftbj** [comment]
I appreciate the idea of this, but would think maybe setting a default of the WordPress option for hiding sites from search engines which will modify the default robots.txt. That may be something we could add to the install process and then could be overriden by changing the setting in the UI.

Would need to set the `blog_public` option to 0 upon install.

**Comment by kraftbj** [comment]
Trying new approach in c89e649 .

This would match if someone installed WordPress via the UI and selected the option to discourage search engines there ( see https://github.com/WordPress/wordpress-develop/blob/238e8991f883e9c09c044f2405f3b85409013e36/src/wp-admin/install.php#L357 )

**Comment by simison** [comment]
Nice idea @kraftbj , works for me!

I'll personally still keep my no-robots plugin locally in case I flip that public setting (as the setting itself affects how some part of Jetpack dashboard show up if I remember correctly).

**Review by simison — COMMENTED** [review]
Can't approve my own PR 😁 

✅  Looks good
✅  I tested the command via `yarn docker:wp ...` and it works
☑️  I haven't tested re-building Docker but I don't see why it wouldn't work.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
