### PR TITLE
Social Previews | Fix video previews

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Proposed changes:

* Update social-previews package to the latest version which contains the fix for video previews
* Pass video media to instagram preview to allow video preview
* Fix image preview for Mastodon which did not work when using a video
* Fix author display name for tumblr

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Checkout this PR and run `pnpm install`
* Run `jetpack build plugins/jetpack`
* Start writing a new post with a JT site with Social Advanced plan/features enabled
* Add a Featured Image to the post
* Click Jetpack icon on the top of the sidebar
* Add a custom image/video to Social sharing section
* Under "Social Previews", click on "Preview"
* Confirm that the previews work as expected for image and video

https://github.com/Automattic/jetpack/assets/18226415/2a2872db-7431-4652-9158-c19ca0b0c1cb

### CODE REVIEW

**Comment by gmjuhasz** [comment]
@manzoorwanijk  this works well for me other than Instagram, where I still get the featured image, even if `Share as a social post` is on. 


https://github.com/Automattic/jetpack/assets/36671565/f0a88f5e-5f8e-44c2-b418-69f28db1b4f3

**Comment by manzoorwanijk** [comment]
> @manzoorwanijk this works well for me other than Instagram, where I still get the featured image, even if `Share as a social post` is on.
> 
>  CleanShot.2023-09-18.at.10.11.43.png.mp4

Can you please run `pnpm install` and then `jetpack build plugins/jetpack`?

**Comment by gmjuhasz** [comment]
> Can you please run `pnpm install` and then `jetpack build plugins/jetpack`?

Thanks, running it a second time worked, maybe I ran it too soon previously. Just another question, is that intended that we have the video controls shown in all previews expect instagram?

**Comment by manzoorwanijk** [comment]
> Just another question, is that intended that we have the video controls shown in all previews expect instagram?

Yes, that's intended because Instagram doesn't show controls.

**Review by gmjuhasz — APPROVED** [review]
LGTM

**Pull request merged**
