### PR TITLE
Contact Form: Update Form block placeholder to include the patterns modal

### LINKED ISSUE #27295: Form Block: Improve Styling/Formatting of Form Submission View
Currently the submission view looks a bit off.

The feedback to users "Message sent" is shown in a H3 and can depending on the theme be pretty big.
The label of a data field is in the same styling as the response, which makes it hard to read.

Image

### LINKED ISSUE #27328: Form block - Placeholder - refresh design with link to patterns library
Update: 

pcsBup-lD-p2

-> regarding patterns library modal window compent:
pcsBup-lD-p2#comment-99

---

Image

Templates/patterns for forms are an essential feature. Competitors like [Jotform](https://www.jotform.com/form-templates/) have hundreds of form templates literally. Forms are tedious to build from scratch, and getting inspiration for form fields and questions to ask for standard usecase provides a lot of value.

The central question for the placeholder is how can we scale this?
Also from a visual perspective, things are a bit limited. Especially if we compare it to our beautiful Patterns feature in Gutenberg.
Can we make use of it? Providing a link to the "Patterns Preview" modal? Having there several form categories, and patterns ranging from as basic as an address field to later full-fledged survey forms.

Image

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27328

#### Changes proposed in this Pull Request:
* Update Form block placeholder to include the patterns modal
* The Patterns modal should show only patterns that contain the `jetpack/contact-form` block

Screen Shot 2022-11-09 at 11 53 02
 
#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Create a Post/Page and add a Form block
* Check if the Form block placeholder has the "Explore Forms Patterns" button
* Click the button and check if the modal shows only form related patterns

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Nice João!!!

There is one thing on the single pattern view that feels off with the "padding":

image


it looks good on the "grid view":

image


I checked the Query Loop integration, and it seems to be an issue there as well. Any chance that we can fix this?

**Comment by digitalwaveride** [comment]
And one more little finetuning thing:
On the placeholder, could we reduce the margin/line height between the links a little bit? Would be great if they roughly align with the height of the button on the left.

image

**Comment by CGastrell** [comment]
I'll agree the lack of _pattern title_ makes it look a bit "odd". 

Wondering where are these _patterns_ coming from, seems to be picking up the variations as patterns?

**Comment by jcheringer** [comment]
> I'll agree the lack of _pattern title_ makes it look a bit "odd".
> 
> Wondering where are these _patterns_ coming from, seems to be picking up the variations as patterns?

It's getting the registered patterns that contain a `jetpack/contact-form` block.
Wasn't you who registered these variations as patterns? 😬

**Comment by jcheringer** [comment]
It should look better now @digitalwaveride

**Comment by digitalwaveride** [comment]
Super nice João!!!! 🚀 

Two tiny little things: 

image

- Found a little typo:
The button should say "Explore Form Patterns"

- The color of the links on the right, shouldn't they be in the same color as the button? Not sure why they are in green for me.

**Comment by jcheringer** [comment]
@digitalwaveride I fixed the typo.
Regarding the color of the links, there's a CSS style (not related to these changes) that overrides the `a` element color.
I'm not sure why this style exists, but I'd say that's how it's supposed to work.
I tried using the `variation` property to change the style, but it had no effect.

**Review by digitalwaveride — DISMISSED** [review]
Looking good!!! Thanks João! 🚀

**Comment by CGastrell** [comment]
Looks good :) 

> It's getting the registered patterns that contain a jetpack/contact-form block.
> Wasn't you who registered these variations as patterns? 😬

I don't think so, I did register the pattern category `Forms`, but I see what you mean about the filter bringing any pattern containing a `jetpack/contact-form` block.

I guess the patterns we're registering comply to the filter using the `blockType` pattern attribute 👍

**Review by bindlegirl — DISMISSED** [review]
LGTM. Rebased and fixed conflict

**Comment by jcheringer** [comment]
@bindlegirl, thanks for the 👍!
I had to push a new commit (2e4edb8) to remove some unused imports that were causing linting errors after the rebase.
Could you give me another 👍, please?

**Review by bindlegirl — APPROVED** [review]

**Comment by pablohoneyhoney** [comment]
- I'd prefer if we find a different way of displaying the options in placeholder. The icons are foreign to the editor, the layout is scattered. I'd rather not have icons. 
- We need to change also the Form icon.
- `Start building a form by selecting one of these form templates, or search in the patterns library for more forms:` reads very confusing. `Choose a form type` or alike
- And display the options in simple buttons. And insert button if we want multiple inserts (no need). 
- Remove the punctuation on the links, and the external icon.  
- Lower the prominence of explore form patterns. Perhaps at the same level of the other options. Now it looks like a validation button.

**Comment by oskosk** [comment]
Cool, we’ll need to introduce a [deprecation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/)  for the old markup

**Comment by digitalwaveride** [comment]
> I'd prefer if we find a different way of displaying the options in placeholder. 

That's good news! Fully agree! 

We started to play with a different solution but then saw that these "icon buttons" are also used on other block placeholder views and shied away from it for version 1 and stayed with the pattern.

I will work on a redesign then!  👍

**Pull request merged**
