### PR TITLE
Instant Search: Fix search on private simple sites

### LINKED ISSUE #17269: Search: Simple private site search fails intermittently
#### Steps to reproduce the issue

1. Purchase and enable Instant Search on a simple WordPress.com site.
2. Set the site to `Private` visibility.
3. Search the site.

#### What I expected
Search results to appear.

#### What happened instead
The search interface is stuck in its loading state. 

> Screen Shot 2020-09-25 at 4 00 46 PM

The browser console shows errors relating to iframe message posting.

> Screen Shot 2020-09-25 at 4 00 57 PM

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #17269.

#### Changes proposed in this Pull Request:
* Temporarily forks `wpcom-proxy-request` to fix a bug caused by two instances of `wpcom-proxy-request` running on the same window. Also, strips unnecessary libraries from the request package.
* Moves `query-string-decode` into an externals folder.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Follow the testing instructions in D50535-code.
* Ensure that search works as expected on your Jetpack site.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by bluefuton** [comment]
> Temporarily forks wpcom-proxy-request to fix a bug

@jsnmoon can you highlight what the changes were with a comment?

**Comment by gibrown** [comment]
Seems to work, but I did get these console errors:

Screen Shot 2020-10-01 at 4 19 46 PM

Private atomic site.

**Comment by jsnmoon** [comment]
> @jsnmoon can you highlight what the changes were with a comment? (@bluefuton)

Sure! I've actually specified the changes in [the file directly](https://github.com/Automattic/jetpack/pull/17349/files#diff-bdb3cf8abe0740ab9dba3f385dfe2433R7-R18):

```
//
// NOTE: This is forked from:
//       https://github.com/Automattic/wp-calypso/blob/master/packages/wpcom-proxy-request/src/index.js.
//       from commit https://github.com/Automattic/wp-calypso/commit/4537033c6794449ce0a10b69d72daf5fa658d553.
//
//       Changes:
//       - Added checking for `e.source !== iframe.contentWindow` in onmessage function.
//       - `wp-error` and `debug` dependencies have been manually removed.
//       - Empty block statement following `! params.metaAPI` conditional has been fixed.
//
```

**Comment by jsnmoon** [comment]
> Seems to work, but I did get these console errors:
>
> Screen Shot 2020-10-01 at 4 19 46 PM
>
> Private atomic site. (@gibrown)

I'll investigate.

**Review by gibrown — DISMISSED** [review]
LGTM. Working on atomic site (both public and private) and on wp.com simple sites (public and private).

**Comment by jsnmoon** [comment]
The changes in this PR is only relevant to simple private sites, so there's no rush to merge and release this in a Jetpack release.

**Review by jeherve — DISMISSED** [review]
I believe you may have to rebase to fix those failing tests.

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
