### PR TITLE
Gutenberg extensions: use @wordpress/base-styles package

### PR DESCRIPTION
**Pull request by simison**
Switch Gutenberg extensions to use the new [`@wordpress/base-styles`](https://github.com/WordPress/gutenberg/tree/983c60f25e4bdb7432fde7afdf2b4cc16640f01e/packages/base-styles) package instead of manually copied over Gutenberg variables.

#### Changes proposed in this Pull Request:
* Import variables from `@wordpress/base-styles`

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
- Modify; no visible changes

#### Testing instructions:
- Build should obviously pass as usual; missing sass variables would break loudly
- Everything looks as it should; no visible changes 

#### Proposed changelog entry for your changes:
*

### CODE REVIEW

**Comment by simison** [comment]
Yarn.lock has suspicious changes, something is off...

**Comment by simison** [comment]
Rebased — ready for review again!

**Review by jeherve — DISMISSED** [review]
This looks good to me. 🚢

**Comment by simison** [comment]
Rebased against lastest `master`. For some reason, `yarn.lock` wasn't up to date — fixed.

**Review by jeherve — DISMISSED** [review]

**Comment by simison** [comment]
Forced ✅ for wpcom test — Syncing needs some manual work.

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by simison** [comment]
synced in r200692-wpcom

**Pull request merged**
