### PR TITLE
My Jetpack: change action buttons of the Product card

### PR DESCRIPTION
**Pull request by retrofox**
This PR changes the action buttons of the Product Card according to the design feedback,
p1HpG7-fbl-p2#comment-53119

before | after
------|------
image | image

Fixes https://github.com/Automattic/jetpack/issues/23483

#### Changes proposed in this Pull Request:

* My Jetpack: Replace Manage button with a simple button (no more dropdown). Disconnect button is removed, too.

#### Does this pull request change what data or activity we track or use?
Yes. We stop firing the `jetpack_myjetpack_product_card_deactivate_click` event

#### Testing instructions:

* Use storybook
* Go to Product Card story http://localhost:50240/?path=/story/packages-my-jetpack-product-card--default
* Change the status
* Confirm you see the changes in the Manage button
------------
* Go to My Jetpack overview
* Confirm you can activate the product for those inactive ones
* Confirm you see a (secondary) manage button for active products
* Confirm the manage button leads to the proper page

https://user-images.githubusercontent.com/77539/159478481-c42e5145-bedc-4095-8fc3-5eaf6e1bbe04.mov

### CODE REVIEW

**Comment by retrofox** [comment]
_Note. This PR needs design feedback because with these changes we are removing the ability to deactivate the product since the Manage button doesn't have the dropdown options anymore, where we use to show the Deactivate option._

**Comment by eeeeevon13** [comment]
I believe the goal in this iteration was to allow the user to deactivate the product by following the "manage" link, rather than directly from this page. Then readdress this idea if we find enough use cases that merit the shortcut to deactivate from My Jetpack.

**Comment by eeeeevon13** [comment]
pinging @jeffgolenski & @madebynoam  to ensure we're not missing anything here, but it looks good from what I can see.

**Comment by retrofox** [comment]
> I believe the goal in this iteration was to allow the user to deactivate the product by following the "manage" link, rather than directly from this page. Later, we'd readdress this idea if we find enough use cases that merit the shortcut to deactivate from My Jetpack.

that make sense. I suppose that that's doable from the manage page of every product. In the worse of cases, users will end up to the plugins page?

**Comment by retrofox** [comment]
Moving to RfR because of p1HpG7-fbl-p2#comment-53131

**Review by keoshi — APPROVED** [review]
Lovely!

**Comment by oskosk** [comment]
There are some unused styles being left in the stylesheet file

**Comment by retrofox** [comment]
> There are some unused styles being left in the stylesheet file

cleaning...

**Review by oskosk — APPROVED** [review]
LGTM!. 

Needs to be followed up by a PR that removes mechanics for deactivating products

**Pull request merged**
