### PR TITLE
CRM: Make form fonts smaller

### PR DESCRIPTION
**Pull request by gogdzl**
## Proposed changes:
This PR changes the fonts to a smaller size, and to the right family.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1HpG7-lcQ-p2
https://github.com/Automattic/zero-bs-crm/issues/2936

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by gogdzl** [comment]
I would like your feedback on the progress so far.
What do you think?

Before this PR:
image


After this PR: 
image

**Comment by cleacos** [comment]
The font size is too small for me. The font family is okay.

**Comment by gogdzl** [comment]
> The font size is too small for me. The font family is okay.

Family and size are following Jetpack's standards. 
Are you feeling that they are too small just by looking at the screenshots or did you try the branch?

**Comment by cleacos** [comment]
I checked out the branch in my local dev-env, and build it via jetpack cli

**Comment by gogdzl** [comment]
Closing this as duplicated (in favor of https://github.com/Automattic/jetpack/pull/29733).

**Pull request closed without merging**
