### PR TITLE
Social Preview: add to pre-publish sidebar 

### LINKED ISSUE #19915: Social Preview: Add to Pre- or Post-Publish Panel
#### Is your feature request related to a problem? Please describe.
The social preview is a bit buried in the Jetpack menu.

#### Describe the solution you'd like
Adding it to the Pre- or Post-Publish panels could help increase discoverability.

#### Describe alternatives you've considered
Adding it to the GB preview dropdown: https://github.com/Automattic/jetpack/issues/19914

#### Additional context
p1HpG7-c4u-p2

2021-05-21 at 1 21 PM
2021-05-21 at 1 21 PM

### PR DESCRIPTION
**Pull request by ramonjd**
Fixes https://github.com/Automattic/jetpack/issues/19915

#### Changes proposed in this Pull Request:

This PR adds the Jetpack Social Preview panel to the pre-publish sidebar.

Screen Shot 2021-06-01 at 12 32 19 pm

The Social Preview panel still appears in the Jetpack sidebar. (Or should we remove it from here?)

Screen Shot 2021-06-01 at 12 36 19 pm

#### Jetpack product discussion
p1HpG7-c4u-p2

#### Does this pull request change what data or activity we track or use?
Nah.

#### Testing instructions

1. Run locally and create a new post.
2. Check that the social preview appears (and the preview modal works) in the Jetpack menu, and in the pre-publish sidebar.
3. Apply `D62094-code` to your sandbox, and check that the panel displays the upgrade nudge for a free, sandboxed site.
4. Upgrade your test site to a Business plan. The Social Preview panel should show the preview modal.

Screen Shot 2021-06-01 at 12 54 23 pm

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
This is working nicely for me, a good simple addition! LGTM

image

> The Social Preview panel still appears in the Jetpack sidebar. (Or should we remove it from here?)

Personally, I like that it appears in multiple places. After the post or page is published, I might want to go back in and check what the preview looks like before I share a link on Twitter. And if I already know it's a Jetpack feature, then being able to find it from the Jetpack plugin menu as well is nice.

✅ Tested that it works correctly in my local development environment
✅ In wpcom, on a free plan site, and a personal plan site, the social preview button opens up the modal with the upgrade nudge
✅ In wpcom on a business plan site, the social preview behaviour works correctly in the pre publish panel and within the Jetpack plugin menu

**Comment by andrewserong** [comment]
Oh, and it looks like the failing CI jobs might be due to rate limiting? 🤞 they'll be resolved by re-running them at some stage?

**Review by jeherve — APPROVED** [review]

**Comment by kraftbj** [comment]
I'm okay with it being in both places, or at least removing it from the Jetpack panel later under a separate discussion.

**Comment by ramonjd** [comment]
r226584-wpcom

**Pull request merged**
