### PR TITLE
Add key attributes with unique values to module FoldableCards

### PR DESCRIPTION
**Pull request by oskosk**
Fixes warnings in console `Each child in an array or iterator should have a unique "key" prop`. 

#### Changes proposed in this Pull Request:
- Adds unique key attribute to engagemente, more, site health, and security `<FoldableCards>`s
- Adds unique key attribute to more sections' H1s

### CODE REVIEW

**Comment by oskosk** [comment]
cc @dereksmart

**Comment by dereksmart** [comment]
This is still failing on the `more` tab, because  the `h1` needs a key as well.  

also could we add a note about why this is needed for the next person who looks at it?  Just something like

`<FoldableCard key={ `module-card_${element[0]}` } // https://fb.me/react-warning-keys`

**Comment by oskosk** [comment]
@dereksmart I've updated this to:
- not error about the H1 uniqueness
- Include a dirty comment right besides the key value

**Comment by dereksmart** [comment]
LGTM thanks osk :shipit:

**Pull request merged**
