### PR TITLE
Color update: Update blue and gray illustration colors

### PR DESCRIPTION
**Pull request by davewhitley**
#### Changes proposed in this Pull Request

You can see the equivalent update in Calypso here https://github.com/Automattic/wp-calypso/pull/30248

This updates all svg illustration images with the new brand colors from [Color Studio](https://automattic.github.io/color-studio/). This handles only blue and gray colors. I did not touch any Jetpack colors or any color that was not blue or gray.

If the old color was blue, I used the new `Blue` color. If the old color was gray, I used the new `Gray` color.

I basically just searched and replaced hex code colors. I did not open or save the files in any program, so the surrounding html should be unaffected.

Sorry for the large PR. It looks like the diff is not helpful for svg files that have been compressed.

#### Testing instructions

I've checked every image by quickly previewing the local svg file on my machine. Everything looks 👍 

* Check through the images and compared them to master to see if there are any bugs
* I'm not sure where these illustrations are used

Here are some example before/after:

screen shot 2019-01-24 at 2 46 21 pm
screen shot 2019-01-24 at 2 45 59 pm

Some in context:

screen shot 2019-01-28 at 1 19 52 pm
screen shot 2019-01-28 at 1 19 47 pm

screen shot 2019-01-28 at 1 21 56 pm
screen shot 2019-01-28 at 1 21 46 pm

### CODE REVIEW

**Comment by rickybanister** [comment]
This definitely makes sense as a quick update to make sure everything 'matches', but I'd say we have an opportunity going forward to look at highly viewed locations and work on colorizing any svgs that show up in those spots more creatively. We have a broader color palette now and just shifting our blue-monotone palette to gray-monotone doesn't leverage the expanded color range we have now. The creme color works really well with the dark blue for instance.

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by torres126** [comment]
Not something for a PR but just throwing this out there, I wonder if the Twitter header should be updated to reflect the illustrations along with this.

screenshot_20190128-205119

I'd imagine that since they're being adjusted here, they'd be adjusted there too in favour of consistency to something more similar, like this. The table etc. would still need to be removed and this was just something I did super quickly, but I thought it'd be helpful to explain what I mean. 

fdgsgfsdfgsd

Not sure though, just wanted to throw that one out. :)

**Comment by rickybanister** [comment]
This looks fine to us, we'll likely want to update a few other colors later, but I don't see a reason to wait.

**Pull request merged**
