### PR TITLE
Jetpack Plugin: Fixing Infinite scroll allowed var result

### LINKED ISSUE #21448: Infinite scroll allowed vars are combined in a way which replaces rather than merges
I noticed while debugging a site using infinite scroll that some query args being posted from js were not being applied, specifically `post__in` and `post__not_in`, in this case. The method used here to combine the public and private query vars using `+=` means that some of the array values are replaced rather than added:-

https://github.com/Automattic/jetpack/blob/374f9afcb435e9480463dba7959fa408a68c4672/projects/plugins/jetpack/modules/infinite-scroll/infinity.php#L1501

Would this be better if it was changed to use `array_merge`?

### PR DESCRIPTION
**Pull request by amustaque97**
Fixes #21448

#### Changes proposed in this Pull Request:

* Calling `array_merge` instead of 
https://github.com/Automattic/jetpack/blob/374f9afcb435e9480463dba7959fa408a68c4672/projects/plugins/jetpack/modules/infinite-scroll/infinity.php#L1501

#### Testing instructions:

Not exactly sure what is going to be its testing instruction. If someone has any idea about it. Please feel free to update instructions or at least add a comment.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
> I'm wondering if adding a test case for this will be a good idea or not?

Yep, that sounds like a good idea!

> Could you please share how to run test cases? Since it is throwing me an error

This should work:

```
$ jetpack docker sh
$ cd wp-content/plugins/jetpack && composer phpunit -- --filter=WP_Test_The_Neverending_Home_Page
```

**Review by sdixon194 — APPROVED** [review]
Thanks for the contribution! Change seems logical. Thanks for adding tests as well!

**Comment by sdixon194** [comment]
Deployed to wpcom in r234742-wpcom

**Comment by sdixon194** [comment]
Looks like this caused some issues and prevents infinite scroll from working. Reverting for now, will need to do some further digging/testing: https://github.com/Automattic/jetpack/pull/21692

**Pull request merged**
