### PR TITLE
AI Assistant: Introduce plugin sidebar and proofread

### PR DESCRIPTION
**Pull request by renatoagds**
Related with #31946 

It brings back the changes reverted at #31979 with the proper fix.

You can check more about the `post-mortem` here: pe4Cmx-1wv-p2

## Proposed changes:

* Add new `AiAssistantPluginSidebar` component.
* Add new `Proofread` component.
* Add flag to hide sidebar.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Instructions to setup it:

*Jurassic Ninja*

* Spawn a new JN site.
* Download `Code Snippets` plugin.
* Introduce a new snippet to activate plugin sidebar: `define('JETPACK_AI_ASSISTANT_PLUGIN_SIDEBAR', true);`
* Goes into `Settings > Jetpack Constants`.
* Set the option `Type of blocks to load in the editor` as `Beta` and `Save changes`. 

*Locally*

* Download `Code Snippets` plugin.
* Introduce a new snippet to activate plugin sidebar: `define('JETPACK_AI_ASSISTANT_PLUGIN_SIDEBAR', true);`
* Introduce a new snippet to set Jetpack Beta blocks: `define('JETPACK_BLOCKS_VARIATION', 'beta');`

*After*:

* Go to an post.
* Check if `Jetpack` sidebar has `AI Assistant` panel.
* Click on publish.
* Check if `Pre Publish` sidebar has `AI Assistant` panel.
* Test it across P2 to check if isn't breaking other blocks.

### CODE REVIEW

**Comment by oskosk** [comment]
I added the snippet on a site launched with https://jurassic.ninja/create?jetpack-beta&branches.jetpack=add/ai-assistant-sidebar-proofread&wp-debug-log
image

but I couldn't find the sidebar. Do i need to purchase the plan first?


Note: I took the liberty to copy here the testing instructions from #31954

**NOTE 2:** I purchased the plan an also tried adding `define('JETPACK_AI_ASSISTANT_PLUGIN_SIDEBAR', true);` to wp-config.php but it didn't work even though `window?.Jetpack_Editor_Initial_State?.[ 'ai-assistant' ]?.[ 'is-plugin-sidebar-visible' ]` is true
image
image

**Comment by retrofox** [comment]
> I purchased the plan an also tried adding `define('JETPACK_AI_ASSISTANT_PLUGIN_SIDEBAR', true);` to wp-config.php but it didn't work even though `window?.Jetpack_Editor_Initial_State?.[ 'ai-assistant' ]?.[ 'is-plugin-sidebar-visible' ]` is true

Same:

Screenshot 2023-07-24 at 12 49 58

I'm not able to see the panel in the Jetpack sidebar.

**Comment by renatoagds** [comment]
@oskosk and @retrofox Thanks for pointing out, the instructions was wrong. I updated it to reflect the current stage, and how to activate it for *Jurassic Ninja* or *Locally*.

**Review by retrofox — APPROVED** [review]
LGTM. Tested locally, JN, and Simple (and P2) sites.
The feature is visible depending on the described conditions (`beta` extension and global var defined)

🚀🚀🚀🚀🚀

**Pull request merged**
