### PR TITLE
cli: Work around yarn cache concurrency bug

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

Yarn by default does not handle concurrent runs well, like what we do
for the CLI `jetpack install --all`. Multiple processes accessing the
same cache entry can interfere with each other leading to strange
errors.

The official workaround for that is to pass `--mutex` to yarn to have it
serialize its own runs (everything, not just the cache access,
unfortunately), rather than yarn implementing locking in the cache
accessing itself and using it by default.

See https://github.com/yarnpkg/yarn/issues/683 and https://github.com/yarnpkg/yarn/issues/4102
for details.

Since the yarn developers are uninterested in fixing any remaining bugs
in yarn (they've moved on to "yarn 2" aka "berry"), there's not even any
point in trying to get it fixed upstream.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Run `jetpack install --all` and see how it goes.

### CODE REVIEW

**Comment by kraftbj** [comment]
Ugh, good find.

**Review by kraftbj — APPROVED** [review]
Worked for me, but I haven't been having problems.

**Comment by briancolinger** [comment]
I can not figure out what I'm doing wrong. I'm out of ideas.

I thought maybe my environment is just messed up... so I cloned a whole new copy of the Jetpack repo. Started completely from scratch.
Now I'm getting a new error:
```
➜  jetpack git:(fix/workaround-yarn-issue-683) ✗ jetpack install --all
Something is missing from your install. Please run `yarn install` and try again.
```

I've tried every combination of yarn command that I can find... nothing works.

I've tried running the ./tools/check-development-environment.sh script. I get SUCCESS on each test except for:
* node_version_is_proper : FAILED.

```
➜  jetpack git:(fix/workaround-yarn-issue-683) ✗ node -v
v14.16.0
```

I don't know what else to try.

**Review by briancolinger — APPROVED** [review]
As far as I can tell, these changes work as expected. I can see the mutex file get created.
I think the errors I'm seeing are maybe unrelated?

**Pull request merged**
