### PR TITLE
Components: Update clicking a tooltip to toggle visibility instead of always show

### LINKED ISSUE #35294: [Components] Popover doesn't close on icon click
When clicking the i icon the popover opens as expected, but I would expect that clicking it again would close the popover, but it just keeps opening and I have to click somewhere else to close it.

Screen recording: pedxs5-mg-p2#comment-225

### PR DESCRIPTION
**Pull request by dilirity**
Fixes #35294

Please note, that this PR changes the default behavior throughout all products that use the component. I'm not sure if the way it was previously was better, but I think this is an improvement.

## Proposed changes:

* Update behavior to close the tooltip when clicking the tooltip icon again.

	<details><summary>Before</summary>
	
	CleanShot 2024-01-29 at 19 01 05
	
	
	</details>
	
	<details><summary>Now</summary>
	
	CleanShot 2024-01-29 at 19 00 47
	
	
	</details>

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup Boost;
* Check any tooltips (except the Critical CSS one as that's using an older component) and make sure they behave as displayed above (from the **Now** example).

### CODE REVIEW

**Comment by dilirity** [comment]
Not sure why tests are failing. The failures don't seem to be related to the tooltip changes.

Maybe this new functionality should be togglable (disabled by default)? Although, to me, the default way should be as proposed in this PR.

**Review by thingalon — APPROVED** [review]
LGTM

**Comment by thingalon** [comment]
> Not sure why tests are failing. The failures don't seem to be related to the tooltip changes.
> 
> Maybe this new functionality should be togglable (disabled by default)? Although, to me, the default way should be as proposed in this PR.

Merged from trunk, reran tests came back green.

**Comment by thingalon** [comment]
cherry-picked to 3.0.0 in 62100be531.

**Pull request merged**
