### PR TITLE
Locales: avoid Fatal Errors when GlotPress is active.

### PR DESCRIPTION
**Pull request by jeherve**
Reported here:
https://wordpress.org/support/topic/fatal-error-with-glotpress-activated

### CODE REVIEW

**Comment by jeherve** [comment]
cc @akirk

**Comment by zinigor** [comment]
Seeing how `locales.php` is more consistently updated in GlotPress than on our side I think it's going to be OK this way.

**Comment by akirk** [comment]
I agree to check if the class is defined, though I think it is safe to assume that if `GP_Locale` is defined then also `GP_Locales` is defined, so the patch can be reduced.

```

**Comment by jeherve** [comment]
@akirk That makes sense. I've edited my Pr accordingly.

**Comment by akirk** [comment]
LGTM!

**Comment by kraftbj** [comment]
Cherry-picked via 5f808582aa918b143e235073f6b1e46a31057969 to `branch-4.0`

**Comment by georgestephanis** [comment]
This is being reverted by a wpcom sync that has resolved the issue differently:

r135921-wpcom

**Pull request merged**
