### PR TITLE
Add back holiday snow

### PR DESCRIPTION
**Pull request by gravityrail**
#### Changes proposed in this Pull Request:

* Add back Holiday Snow. The primary goal of Jetpack is 1:1 features from WordPress.com, so we either need to add it back to Jetpack, or remove Holiday Snow from WPCOM.

#### Testing instructions:

* Enable Holiday Snow in the settings
* Set server time to any date between December 1st and January 1st
* Front end of your site should have delightful, whimsical holiday snow

### CODE REVIEW

**Comment by zinigor** [comment]
Because everything that was needed to remove Snow from Jetpack 6.0 was handled properly, it's safe to close this. Feel free to reopen if needed.

**Comment by Lenmaer** [comment]
Damn, I really hope you'll add this back for this winter, otherwise I don't see any reason to continue to use jetpack.

**Comment by jeherve** [comment]
@Lenmaer If you need the feature there are still plenty of options to add snow to your site. Here are a few options you can try:
https://wordpress.org/plugins/tags/snow/

**Comment by Rik67** [comment]
Well, still not re-added... Guess it's time to toss Jetpack, it has become useless.

**Pull request closed without merging**
