### PR TITLE
Security Settings: Convert to feature checks

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request:

* Introduces `hasActiveSiteFeature` selector.
* Replaces plan check in Security settings with feature checks.

#### Jetpack product discussion

Internal: p9dueE-4T6-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Go to `/wp-admin/admin.php?page=jetpack#/settings` on your test site
* Make sure the "Backups and security scanning" section shows the accurate date, based on plan level.

### CODE REVIEW

**Review by DustyReagan — APPROVED** [review]
This is testing well for me. 👍

**Review by coder-karen — COMMENTED** [review]
I added a Jetpack Scan (Daily) plan via Store Admin and this isn’t picked up:

Screenshot 2022-04-15 at 13 25 52


Clicking upgrade I’m prompted to add Scan, despite having it. The checkout then does tell me I currently own scan.

Screenshot 2022-04-15 at 13 26 53

That said, testing without this PR I experience the same (Scan plan isn't picked up) - only difference is that in checkout I'm not told I already have the plan. 

So it looks like this PR didn't introduce any issues but there may have been an existing one here, around Scan plans not being picked up? 🤔 

Maybe that's something for a separate PR though?

**Comment by obenland** [comment]
> I added a Jetpack Scan (Daily) plan via Store Admin and this isn’t picked up

Yeah, not sure if that is by design or by accent. [It looks like it always needs a backup feature](https://github.com/Automattic/jetpack/blob/ae52b7774fbb5d361681a14091a982f4eb5cbe05/projects/plugins/jetpack/_inc/client/security/backups-scan.jsx#L172) to display something other than that banner

**Comment by samiff** [comment]
> Clicking upgrade I’m prompted to add Scan, despite having it. The checkout then does tell me I currently own scan.

@coder-karen  Do you mean on the product specific screen? `/wp-admin/admin.php?page=jetpack#/product/scan`

Here is what I saw there with a Scan subscription active:

Screen Shot 2022-04-15 at 4 28 35 PM

So I think that would be the screen we would consider modifying (i.e. don't re-offer Scan if it's already active).

Though for the purpose of this PR, the feature check seem to function as intended.

**Review by samiff — APPROVED** [review]

**Comment by coder-karen** [comment]
@samiff Yes that's one of the screens that is confusing - also the initial settings page (`/wp-admin/admin.php?page=jetpack#/settings`) as it doesn't hint at there being a scan plan (same messaging shows both with and without a Scan plan) and the upgrade button then leads to that page you mentioned which adds to the confusion.

But it was an existing issue and from @obenland 's link the messaging on the settings page itself may be by design, so outside the remit of this PR like you say. I asked here - p1650273328930229-slack-C0D96691V - for now.

So we're good to go!

**Review by coder-karen — APPROVED** [review]

**Pull request merged**
