### PR TITLE
Update/info popover

### LINKED ISSUE #7195: Settings UI: Info popover contents differ from Calypso
As discussed in p1495025546143993-slack-jpop-design, contents of info popovers for settings UI cards differ between Jetpack and Calypso. As @keoshi clarified, these need to be updated accodingly to match Calypso.

For example, see the VideoPress setting info popover:

Calypso:

Jetpack:

/cc @eliorivero

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #7195

#### Changes proposed in this Pull Request:

* update SettingsGroup to receive a supportLabel property that will specify a custom link label. Display the info popover above the info icon. Add tests.
 
* pass complete module information so the module name and info link is correctly fetch. Remove support prop where it was redundant.

#### Testing instructions:

* build and make sure Info Popovers look fine

### CODE REVIEW

**Comment by eliorivero** [comment]
captura de pantalla 2017-05-29 a las 10 46 18

This is currently not looking excessively fine as can be seen above.

**Comment by tyxla** [comment]
Good catch, @eliorivero, thanks! I've opened https://github.com/Automattic/wp-calypso/issues/14580 and requested some design feedback there.

**Comment by tyxla** [comment]
In Automattic/wp-calypso#14580 I've suggested that we go with what's done in Jetpack (changing all labels to just "Learn more"). This would be the easiest solution and will not require any further changes to Jetpack as well. Let's wait and see how it goes before we continue here.

**Comment by AnnaMag** [comment]
@eliorivero, FWIW, we fixed bad popover positioning, in case this one is still relevant and worth a revamp.
/cc @tyxla

**Comment by eliorivero** [comment]
Thanks for the review. We're going with a new approach and will follow up on Calypso later.

**Pull request closed without merging**
