### PR TITLE
Stats: improve i18n for plural forms in the Stats Widget

### LINKED ISSUE #20005: Minor language issue: x amount of views singular / plural
So, in the stats widget we have a list of the popular posts and pages with the amount of views... 
But, here is the thing that I noticed as a polygot. 

There is no way to put the translation in singular / plural. So, we have to either put the plural between brackets OR have the plural in and have it look a bit strange when it's supposed to be singular. 

This is a permalink to the translation I'm talking about: 
https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=611393&filters%5Btranslation_id%5D=84519029

So, this should be on stats.php on line 1249. https://plugins.trac.wordpress.org/browser/jetpack/tags/9.7/modules/stats.php#L1249

(Is this correct? Since I don't see the string on said line. But GlotPress says it does)

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes #20005

#### Changes proposed in this Pull Request:

The primary change is the introduction of the `_n` function to add the option to include singular and plural versions of the ‘Views’ word in the Stats Widget, when viewed in the `wp-admin` dashboard. This is also relevant for translations.
 
#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

On a Jetpack connected live testing site, on the main dashboard (at `wp-admin/index.php`) view the Stats Widget on the dashboard when you have a post with 1 view and another with multiple views. What you should see is ‘x Views’ for multiple views, and ‘1 View’ for a singular view (when viewing in English).

Stats dashboard with singular and plural options

### CODE REVIEW

**Comment by coder-karen** [comment]
I manually created and added a changelogger which might be affecting the testing, I also see other failing tests here so I’m open to feedback on what I may have needed to do differently.
It has also been rebased but this doesn’t seem to be reflecting.

**Comment by coder-karen** [comment]
Before adding the 'needs review' status label I'll cc @kraftbj as a recent editor of this file in case this is something you can review?

**Comment by kraftbj** [comment]
Before reviewing, can you catch the PR up to date with master?

```
git fetch origin
git merge origin/master
git push origin
```

That'll clear one of the failures and then can look at the rest.

**Comment by coder-karen** [comment]
Thanks @kraftbj , hopefully I've done that correctly now.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
