### PR TITLE
Contact Form: Update Form block placeholder styles

### PR DESCRIPTION
**Pull request by jcheringer**
#### Changes proposed in this Pull Request:

* Improves the Form block placeholder styles
  *  Reduces the variation buttons size to fit the items better when all variations are available, and the theme has a smaller block container width
  * Changes the footer links alignment to the right

Before 
image

After
image

 
#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a post and add a Form block
* Check if the Form block placeholder matches the changes proposed above

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This looks good to me, in Chrome and on mobile.

On mobile, I did notice that the links at the bottom of the pattern picker could use some styling, but that's not something related to this PR, so definitely not a blocker; maybe something to fix in a future PR?

Screenshot_20221212-160805

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Thanks so much for this João! So much better! 🙏 

Two things for the smaller responsive views:
- The links at bottom would need to move to a new row.
- When icon boxes are moving in a new line, let's keep the padding between boxes in all lines the same.


image




In a separate PR, let's go after the color mess ;)

**Review by digitalwaveride — APPROVED** [review]
Thanks so much for the styling fixes João!
Looks good!

Padding between box in a second row are fixed, and the links at the bottom as well! 👍 
🙏

image

**Comment by jcheringer** [comment]
Hey @jeherve, thanks for reviewing it.
We ended up fixing the layout for smaller screens.
Could you give me another 👍 ?

**Review by jeherve — APPROVED** [review]

**Pull request merged**
