### PR TITLE
tools: Support shared prefixes in create-release-branch.sh

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

We're always going to want to release both Jetpack and jetpack-mu-wpcom together, so we may as well use just one release branch to do it. For that to work, we need to make sure that create-release-branch.sh runs plugin-version.sh and version-packages.sh on both plugins.

We might also want to add some of the other standalone plugins to that group in the future.

Also minor fixes to other scripts:
* Localize variables and update syntax in normalize-version.sh.
* Have `process_plugin_arg` always produce a full path.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

🤷

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Try using the script to create a release for one of the standalone plugins.
* Try using it to create a release for "jetpack". See that it does the right thing, releasing both jetpack and jetpack-mu-wpcom.
* Try using it to create a release for "jetpack-mu-wpcom". Try different answers to the prompts and see that it does the right thing.
* Try using it to create a release for "projects/plugins/jetpack". Try different answers to the prompts and see that it does the right thing.

### CODE REVIEW

**Review by sdixon194 — COMMENTED** [review]
Think this is tricky to test since the mu-wpcom plugin doesn't seem fully set up yet.

> No plugin file was detected in /Users/stevedixon/jetpack-dev/jetpack/projects/plugins/jetpack-mu-wpcom

Do we want to wait and merge this until that's had time to land more fully?

**Comment by anomiex** [comment]
> Think this is tricky to test since the mu-wpcom plugin doesn't seem fully set up yet.
> 
> > No plugin file was detected in /Users/stevedixon/jetpack-dev/jetpack/projects/plugins/jetpack-mu-wpcom

Why is it not finding https://github.com/Automattic/jetpack/blob/add/create-release-branch-support-shared-prefixes/projects/plugins/jetpack-mu-wpcom/jetpack-mu-wpcom.php for you?

**Comment by sdixon194** [comment]
Hmm strange, it's there initially, but then when I run `tools/create-release-branch.sh plugins/jetpack` it seems to delete the entire plugin contents except for the vendor folder?

**Comment by sdixon194** [comment]
Ahhh I know why, it's because I had a `prerelease` branch already, so it was checking that out instead of deleting and starting anew. Looks like it works for me now.

**Review by sdixon194 — APPROVED** [review]
Let's give it a go.

**Pull request merged**
