### PR TITLE
Forms: Fix Forms styles when inside Cover blocks

### LINKED ISSUE #74001: Cover Blocks Break Some Jetpack Form Background Settings
### Quick summary

The "Single Choice" and "Multiple Choice" blocks in Jetpack Form blocks, when added to a form inside a Cover block, do not obey the background setting set in the editor and display with a white background instead.

A workaround is to not place the Form block in a Cover block—using a Group block or similar instead.

### Steps to reproduce

1. Add a cover block to a page, and a form inside it.
2. Add a "Single Choice" or "Multiple Choice" block to the form.
3. Observe issue in editor.
4. Save changes.
5. Observe issue on front-end as well.

### What you expected to happen

For form blocks to always respect the background setting set in the block's settings, regardless of where they are placed.

### What actually happened

Some blocks inside form blocks do not respect the background setting set in the block's settings when placed in Cover blocks.

### Example in editor:
Markup on 2023-03-02 at 09:43:37

### Example on site:
Screenshot 2023-03-02 at 9 40 44 AM

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Reported in 5953824-zd-woothemes

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes https://github.com/Automattic/wp-calypso/issues/74001

## Proposed changes:

* Fix Forms styles when inside Cover blocks. More context in the issue above

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Follow the steps described in the issue above
* You shouldn't be able to reproduce the issue

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
Looks like this is causing the tests to fail at the moment:

```
  [test-extensions]   ● Contact form › renders a variation selector list
  [test-extensions] 
  [test-extensions]     Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
  [test-extensions] 
  [test-extensions]       56 |
  [test-extensions]       57 | 	test( 'renders a variation selector list', () => {
  [test-extensions]     > 58 | 		render( <JetpackContactFormEdit { ...defaultProps } /> );
  [test-extensions]          | 		      ^
  [test-extensions]       59 | 		// eslint-disable-next-line testing-library/no-node-access
  [test-extensions]       60 | 		expect( screen.getByRole( 'list' ).children ).toHaveLength( 2 );
  [test-extensions]       61 | 	} );
  [test-extensions] 
```

**Comment by digitalwaveride** [comment]
Thanks so much for looking into this João!
The UX issue is fixed, and worked for me as expected!

image

Up to Jeremy to give a 👍 regarding the issue with the tests!

**Comment by jcheringer** [comment]
Thanks for catching this, @jeherve! 
The tests should be fixed now.

**Review by CGastrell — APPROVED** [review]
LGTM!

**Pull request merged**
