### PR TITLE
Add `wpcom_ai_site_prompt` option to the site settings endpoint

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed changes:

This PR adds the `wpcom_ai_site_prompt` option to the site settings endpoint. This option stores the user input in the prompt screen in the WP.com's AI assembler flow (see pbxlJb-573-p2).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

This PR doesn't implement any functional changes. Ensure that all checks pass successfully.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Comment by jeherve** [comment]
This is looking good. You'd need to run `tools/fixup-project-versions.sh` to update version numbers before this can be merged, though.

**Comment by taipeicoder** [comment]
> This is looking good. You'd need to run `tools/fixup-project-versions.sh` to update version numbers before this can be merged, though.

Thanks @jeherve! Running the script bumped more plugins/packages than expected. Is this expected?

**Comment by jeherve** [comment]
> Thanks @jeherve! Running the script bumped more plugins/packages than expected. Is this expected?

It is, yes. The Sync package is required by multiple plugins, so when we update that package we must update all the plugins that require it.

**Review by jeherve — APPROVED** [review]

**Comment by taipeicoder** [comment]
> > Thanks @jeherve! Running the script bumped more plugins/packages than expected. Is this expected?
> 
> It is, yes. The Sync package is required by multiple plugins, so when we update that package we must update all the plugins that require it.

Makes sense! Thank you so much for the quick reply 🙂

**Pull request merged**
