### PR TITLE
jetpack AI package

### LINKED ISSUE #71330: Port the Coauthor plugin to Jetpack
### Details

The Coauthor plugin is shipped to WPCOM, but it is using a proprietary delivery mechanism. Instead, we need it to be shipped in Jetpack to be available to both WPCOM Simple and Atomic customers.

https://github.com/artpi/wp-writers-block-block

The goal of this task is to port the plugin to Jetpack.

**Please break it into smaller tasks if you find an opportunity.**

### Checklist

- [x] Create a Jetpack AI package - this is how  [Jetpack packages work](https://github.com/Automattic/jetpack/tree/trunk/projects/packages)
- [ ] Port Artur's Coauthor plugin as a Jetpack package https://github.com/artpi/wp-writers-block-block (skip the token settings screen, the OpenAI key should come from a Jetpack connection)
- [ ] Make sure API calls are going through Jetpack connection to the API endpoints - see this commit for some threads to pull: https://github.com/artpi/wp-writers-block-block/commit/e414fa153f741b16db0d91b966a9834d4c7e63aa
- [ ] Add blocks within that package to Jetpack plugin, as `JETPACK_BETA_BLOCKS`

### Related

_No response_

### PR DESCRIPTION
**Pull request by millerf**
Fixes https://github.com/Automattic/wp-calypso/issues/71330

#### Changes proposed in this Pull Request:

Port https://github.com/artpi/wp-writers-block-block to Jetpack

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

PT: pbOQVh-2Ot-p2

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* TBD

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
If you're interested in creating a new package, I would recommend using the Jetpack CLI tool to help you with that, as it will handle all the boilerplate for you.
`jetpack cli generate`.

That said, I don't know if we need a full Composer package for a standalone block. Is there maybe a post about the feature, where one could learn more about what's in the plans? We may be able to discuss details like that there.

Thank you!

**Comment by jeherve** [comment]
> That said, I don't know if we need a full Composer package for a standalone block.

To extend a bit on this and maybe help you with some ideas, I think we could structure this like the other blocks, with the block in `extensions/`, and the API endpoints in a new file like `projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-coauthor.php`, where we would be able to fetch data from WordPress.com using the API like we do in the other endpoints in that directory right now.

We could get started with a PR using the `scaffold` CLI tool we have at our disposal, and go from there. Here is an example PR where I've done this to show you what I had in mind: #28043

Let me know what you think.

I also found the PT and added a link to it in this PR, for easier reference.

**Comment by millerf** [comment]
Closing in favor of #28043

**Comment by millerf** [comment]
> That said, I don't know if we need a full Composer package for a standalone block. Is there maybe a post about the feature, where one could learn more about what's in the plans? We may be able to discuss details like that there.

You can find everything here:
pbOQVh-2Ot-p2

**Pull request closed without merging**
