### PR TITLE
Widget Visibility: Fixed several issues...

### PR DESCRIPTION
**Pull request by atrus1701**
I had some downtime during my trial and it was suggested I work on a few simple issues.  I found the following five issues related Widget Visibility in the GitHub issues.

[Undefined index has_children in widget-conditions.php](https://github.com/Automattic/jetpack/issues/3070)
[Widget Visibility for “All taxonomy pages” and “All [custom tax] pages” not working](https://github.com/Automattic/jetpack/issues/3020)
[Widget Visibility: support custom post type archive pages](https://github.com/Automattic/jetpack/issues/3020)
[Widget Visibility for Custom Post Type for Pages and Custom Taxonomies Concurrently](https://github.com/Automattic/jetpack/issues/2170)
[Widget Visibility: add an AND condition](https://github.com/Automattic/jetpack/issues/852)

I found solutions to all of the issues and have tested them on my test site several times.

### CODE REVIEW

**Comment by jeherve** [comment]
@atrus1701 Thanks a lot!

Fixes #3070, #80, #3020, #2170, #852

In the future, I'd recommend that you create separate Pull Requests for each bug fix, though. It's easier to test and merge that way.

**Comment by atrus1701** [comment]
I can resubmit the changes as 5 smaller Pull Requests that refer to this larger Pull Request.  Would you like for me to do that?

**Comment by jeherve** [comment]
@atrus1701 If you don't mind, that'd be great! Thanks!

**Comment by atrus1701** [comment]
Sorry for the late reply, but I will make the new Pull Requests.  Should be done by the end of the day.

**Comment by atrus1701** [comment]
I have created the following Pull Requests to replace this Pull Request:
#3286, #3287, #3288, #3289

**Comment by jeherve** [comment]
Thanks! Closing this PR then.

**Pull request closed without merging**
