### PR TITLE
VideoPress: fixed an incorrectly named method.

### PR DESCRIPTION
**Pull request by zinigor**
cc @jeherve @kraftbj @eliorivero please review and merge ASAP.

### CODE REVIEW

**Comment by dereksmart** [comment]
Is there a reason we had to change the method name from `jetpack_modules_loaded()` in the first place?

**Comment by zinigor** [comment]
I have suggested that because it was a misnomer since the method should be run on `init` and not on `jetpack_modules_loaded`. I am open to suggestions though!

**Comment by jeherve** [comment]
This solved the Fatal for me.

**Comment by dereksmart** [comment]
@zinigor no that makes sense.

**Pull request merged**
