### PR TITLE
Backup: Change some error messages to not trigger security scanners

### PR DESCRIPTION
**Pull request by pypt**
Some security scanners grep for `file_get_contents()` / `file_put_contents()`, and mark our log/error messages (where those functions are mentioned) as suspicious.

So, I rewrote some of these log/error messages.

## Proposed changes:

* Slightly different log/error messages and variable names.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1710895488797119-slack-C029WFNV69M

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Make sure the tests pass.

### CODE REVIEW

**Comment by pypt** [comment]
A bunch of tests are failing, but none of them are triggered/related to this change, plus the same tests are failing for other PRs too.

**Comment by anomiex** [comment]
> A bunch of tests are failing, but none of them are triggered/related to this change, plus the same tests are failing for other PRs too.

Looking at the failures:

* **E2E Tests / Jetpack connection e2e tests** is, unfortunately, flaky. You could try re-running.
* **Tests / Storybook tests** still needs people to fix the stuff mentioned in pdWQjU-Ip-p2.
* **WordPress.com Tests** is worth looking at; looking at D142732-code, it's something I've seen being flaky on the wpcom test suite. Re-running will probably make it pass.

**Comment by pypt** [comment]
@anomiex could these tests be disabled while they're so flaky/failing? They're blocking everybody else from getting their PRs through.

**Comment by anomiex** [comment]
They're not marked as "Required" so they don't actually block any PRs being merged.

Ideally we would mark the WordPress.com Tests one as required, but real failures often enough need the tests in wpcom updated rather than being something wrong with the code here. And while it would sometimes be possible to have people update those tests to pass with both old and new versions of the Jetpack code, it's seldom worth the effort versus just updating the test for the new version along with the switch.

**Comment by pypt** [comment]
OK, thanks. Thought that the requirement was for all the tests to be green.

**Review by jwebbdev — APPROVED** [review]
LGTM

**Pull request merged**
