### PR TITLE
Jetpack: Update Jetpack Plugin Sidebar icon size

### PR DESCRIPTION
**Pull request by oskosk**
Fixes extremely big appearance of the icon

#### After

<table>
<tr>
	<td><strong>After</strong><br/>
image
</td>
	<td><strong>Before</strong><br/>image</td>
</tr>
<tr>
	<td><strong>After</strong><br/>
image
</td>
	<td><strong>Before</strong><br/>image</td>
</tr>
</table>

#### Changes proposed in this Pull Request:

* Updates the logo to be 20px high

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* On a connected site
* Start writing a post
* Confirm in the right sidebar at the top that you see the Jetpack logo with a size of 20px.

### CODE REVIEW

**Comment by oskosk** [comment]
I'm updating the hacky way that currently exists for the sizing to be proper. At some point, the editor changed its class names, and we lost control of the size. The real fix is to come up with an SVG that includes the whitespace as part of the vector itself. Thus, when using it for the 24px size enforced by this section, it gets the same size as the sibling icons

**Review by lhkowalski — APPROVED** [review]
Checked the size for the icon on a JN site and it shows 20px. LGTM.

image

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by oskosk** [comment]
r252938-wpcom

**Comment by oskosk** [comment]
Thanks folks

**Pull request merged**
