### PR TITLE
Connection: Update connection banner text to clarify ToS acceptance on click

### PR DESCRIPTION
**Pull request by oskosk**
Follow-up to #9053.

Since some tracking begins upon any attempted connection, we need to clarify the statement provided alongside our connection (“Set up Jetpack”) button so that it is apparent to folks connecting to
WordPress.com. 

As mentioned by  @eliorivero in https://github.com/Automattic/jetpack/pull/9053#issuecomment-374216586 this banner may need an update too

#### Changes proposed in this Pull Request:

* Updates text from `By connecting your site you agree to our fascinating `, to `By clicking the Set up Button, you agree to our fascinating...`.

#### Testing instructions:
1. On a disconnected site, visit the plugins page (for example) and confirm the text before the button reads `By clicking the Set up Jetpack button, you agree to our fascinating...`.

##### Screenshot

**Before**

image

**After**

image

#### Proposed changelog entry for your changes:

Updated connection banner to clarify when tracking of events begins.

### CODE REVIEW

**Comment by bubel** [comment]
LGTM, thanks for following up. One minor request/thought: can we bold the "Set up Jetpack" text in the blurb?

**Comment by dereksmart** [comment]
> bold the "Set up Jetpack"

+1, should they be in quotes too? 

Also, hopefully translations work out here

**Comment by eliorivero** [comment]
Either bold or quotes, both are overkill in typesetting. I'd say bold.

**Comment by bubel** [comment]
I agree with @eliorivero; bolding should be enough.

**Comment by oskosk** [comment]
Made it bold in 18b3ae019bbaa4ab9ffd0ed8fcaf5e6d7cc815f8 @bubel @eliorivero @dereksmart . Also updated the screenshot to reflect the change

**Comment by dereksmart** [comment]
LGTM, and thanks @oskosk for you daily dose of inspiration 

screen shot 2018-03-27 at 9 41 36 am

**Comment by oskosk** [comment]
Showed Rick the screenshot over DM, said it's ok to go

**Pull request merged**
