### PR TITLE
PSH: update list of keywords

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

CDN feels more relevant here than SEO

#### Testing instructions:

* You can test this in the Plugin search screen or under Jetpack > Settings in the searchform.

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

**Review by oskosk — APPROVED** [review]
LGTM

**Comment by kraftbj** [comment]
I think as a small change, this is fine, but bigger, why have separate hints for Asset vs Image CDN?

**Review by kraftbj — APPROVED** [review]
This will only still display the image cdn since we only show one hint, but let's keep moving.

**Comment by kraftbj** [comment]
cherry-picked 4f2730c19 bb31696cf

**Pull request merged**
