### PR TITLE
Build: update both WordPress and React monorepos

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #13593
Fixes #13592

#### Changes proposed in this Pull Request:

This is a combination of 2 Renovate PRs, as the 2 monorepos's versions must match or you'll run into errors like the one mentioned here:
https://github.com/Automattic/jetpack/pull/13593#issuecomment-591460109

It impacts multiple areas of Jetpack:
- The React Dashboard
- The blocks' build and styles
- The Upgrade nudge that is displayed for Paid blocks when you are on a free plan and use the following filter: `add_filter( 'jetpack_block_editor_enable_upgrade_nudge', '__return_true' );`

#### Testing instructions:

* Test all aspects mentioned above. Everything should keep working properly.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by simison** [comment]
Recommend to combine these at [Renovate config](https://github.com/Automattic/jetpack/blob/9dc02e158f65f66c04f5258f00aedb62c165234d/.github/renovate.json) as well so that combining happens automatically in future.

**Comment by jeherve** [comment]
@simison Good point. I've opened #15066 to give this a try.

**Review by brbrr — APPROVED** [review]
It works well in my tests. I used Chrome and a few different wp sites.

**Review by kraftbj — APPROVED** [review]
Builds without error and tested with various blocks plus dashboard.

**Comment by jeherve** [comment]
r204762-wpcom

**Pull request merged**
