### PR TITLE
Update/donations block editable border styles

### LINKED ISSUE #17226: Donations block: Add color and width controls for the border
The light borders against dark background really stick out (in a bad way). It’s not just the dark background either, basically anytime I used colored background the grey border was throwing off the design. Having border controls would be ideal, but even the ability to remove the border would be a great start (maybe it could even be turned off by default?). 

Here's an example block pattern where I nested donations block in a Media & Text block. The border feels redundant in this context.

image

Here's how it would look like without the border:

image

As a side note, if we had the option to remove the border the left-side padding inside would have to be removed as well.

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes #17226 & #17227

#### Changes proposed in this Pull Request:

* We added border controls to the donations block. We can now control the border color and width.
* The color of the active tab now uses the color of the border of the block, the default border color of the block is the theme's primary or foreground color and has a default width of 1px.
* We now support a borderless mode that is activated by setting the border of the block to 0.

##### Basic Testing
* Edit or create a new Post
* Add a Donations block to your Post.
* Select the block and you should now see the border controls.
* The controls should update the border color and width in the Post editor screen.
* Open the Post, all the edited changes should be visible.

##### Borderless mode testing
* Edit or create a new Post
* Add a Donations block to your Post.
* Select the block and you should now see the border controls.
* Set the border width to 0, the left and right padding should be removed.
* The changes should be visible when you open/preview the Post.

##### Migration/Deprecation testing
* Create a previous version of the donations block (no inner block version).
* Edit the post that contains the old version of the block.
* The block should work as expected and load correctly.
* When viewing the Post as a User, the donations block should work as expected.

#### Test Evidence
https://user-images.githubusercontent.com/1989914/154490155-dc1f54c4-5ce0-4f88-b52d-67e73db34b9e.mp4

### CODE REVIEW

**Comment by BogdanUngureanu** [comment]
Did some testing on Atomic and noticed that the Stripe connect nudge is inside the border. Can we move it outside, as it used to be in the older version?
New version:
Screenshot 2022-02-17 at 17 32 21

Older version
Screenshot 2022-02-17 at 17 35 45

Also, when I pressed the "Revert all" option from the border section (there's a three dot menu), the border was removed even though by default we do have one.

I'll continue with the tests and review, but so far no major issues. 👍

**Comment by rcrdortiz** [comment]
> Also, when I pressed the "Revert all" option from the border section (there's a three dot menu), the border was removed even though by default we do have one.

Yes, I've tried to get around this. The thing is that this behavior is expected, resetting all isn't resetting, what it does is destroy all the properties at the block level. If you debug the attributes of the block you can see that they are being set to undefined by the controls. I think there isn't much we can do about that.

**Comment by rcrdortiz** [comment]
> Did some testing on Atomic and noticed that the Stripe connect nudge is inside the border. Can we move it outside, as it used to be in the older version?

It was never outside, but before the navigation and content components had their own border. Now the block has the border that's why it's now so obvious that it's inside.

I'll have a look and see what I can do about it.

**Comment by rcrdortiz** [comment]
> Did some testing on Atomic and noticed that the Stripe connect nudge is inside the border. Can we move it outside, as it used to be in the older version?
After testing different approaches I've come to the conclusion that it isn't possible to have the nudge outside the block. The nudge has been moved inside the contents for now. We might change this if we migrate the Navigation Tabs and Contents to InnerBlocks.

This is how you can expect the nudge to appear:
Captura de pantalla 2022-02-21 a las 9 53 29

**Review by dsas — APPROVED** [review]
Non-blocking feedback:
 1.  Changing the border colour changes the borders between the tabs, but the border style and thickness doesn't. I expected it to change initially, though thinking about it, I'm not sure how well this would work for borderless? image
 2. When editing a migrated block, the border style control is hidden initially (but can be displayed) whereas when adding a new block, that isn't the case. I'm not sure this really needs addressing - just mentioning it for completeness  https://user-images.githubusercontent.com/93301/154976092-a3a94e43-026d-435c-9dc5-ba67ba754abe.mp4

**Comment by dsas** [comment]
I have a site on a non-block theme ([flash](https://en-gb.wordpress.org/themes/flash/)) and the change to the border rules have made it look _slightly_ worse - the border changes. 

The [2019 theme](https://en-gb.wordpress.org/themes/twentynineteen/) has the same problem but the 2022, 2021, 2020 themes are fine.

1. Have a site on jetpack master (i.e. with the non-InnerBlocks donations block)
2. Add and active the flash theme
3. Create a post with a donations block and save it
4. View the post
4. Apply this patch
5. View the post


Before | After
-------|------
 image | image

If I re-open the post once on the new theme and this branch and press save it fixes itself.

**Comment by rcrdortiz** [comment]
> Changing the border colour changes the borders between the tabs, but the border style and thickness doesn't. I expected it to change initially, though thinking about it, I'm not sure how well this would work for borderless?

When I've implemented the thickness and style of the border, the best results were achieved by having a static width and style. If the width changes, the navigation starts to look odd quick (they stop looking like tabs and more like buttons), have a look at the following image:
Captura de pantalla 2022-02-21 a las 19 17 04

Also bear in mind that we might change the navigation tabs and content to blocks, so each one of them would have its own border controls. I wouldn't worry too much about this.

**Comment by rcrdortiz** [comment]
> When editing a migrated block, the border style control is hidden initially (but can be displayed) whereas when adding a new block, that isn't the case. I'm not sure this really needs addressing - just mentioning it for completeness https://user-images.githubusercontent.com/93301/154976092-a3a94e43-026d-435c-9dc5-ba67ba754abe.mp4

This should be really easy, I'll add it to the migration default properties.

- [ ] Migrated donations block should have a default border style = solid.

**Comment by rcrdortiz** [comment]
PR on hold until we make some product decisions regarding the Donations Block.

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage

**Pull request closed without merging**
