### PR TITLE
Admin Page: display more info and support link in error message

### LINKED ISSUE #20006: Admin Page: unhelpful error message without CTA when API requests fail
Today I came across this message while testing some flows. I was using Jurassic Ninja and the server seems to be going through major hiccups, but I'm not sure what the message is trying to communicate.

image

**Questions**

- Isn't Jetpack Dashboard a part of my site? If so, why would there be a miscommunication between the two?
- The message isn't that helpful. What's the underlying issue here, and can we explain it better to the customer?
- The next steps are not realistic for the average user, and it seems likely they would get in touch with us ASAP. Could we be sending them to our documentation instead?
- It was my first time seeing this error, but is this common enough that we should spend time on it? How much time?

Code: https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/_inc/client/state/site/reducer.js#L143

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #20006

Let's provide more potential debugging steps (refreshing the page) and an option to contact support when folks run into issues in the Jetpack dashboard.Fixes #20006

#### Changes proposed in this Pull Request:

Let's provide more potential debugging steps (refreshing the page) and an option to contact support when folks run into issues in the Jetpack dashboard.

**Before**

image

**After**

image

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

1. Find the `Jetpack_Core_Json_Api_Endpoints::get_site_data()` API endpoint method
2. Add some output into the first line of the method (e.g. `echo 'something';`) to break the output JSON.
3. Load the Jetpack dashboard, and check the notice. Try clicking the link.

### CODE REVIEW

**Comment by keoshi** [comment]
It's a bit longer than usual, but I don't mind it since Jetpack won't work unless you address it.

Can we introduce a line break before the last line, so it reads like this:

> Jetpack encountered an error and was unable to display the Dashboard. Please try refreshing the page.
> If the problem persists, get in touch with support.

**Comment by jeherve** [comment]
> Can we introduce a line break before the last line, so it reads like this:

I'm afraid that's not an option right now. We currently remove all HTML from those messages:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/_inc/client/components/notice/index.jsx#L81-L83

**Comment by keoshi** [comment]
What do your think about losing that last sentence? The link to support is already there so it could be a bit redundant and I imagine customers will be much more likely to refresh the page one or two times before wanting to contact us anyway.

**Comment by jeherve** [comment]
> What do your think about losing that last sentence? The link to support is already there so it could be a bit redundant and I imagine customers will be much more likely to refresh the page one or two times before wanting to contact us anyway.

That makes sense. I removed it. Thanks for the feedback!

image

**Review by keoshi — APPROVED** [review]
Lovely, let's ship it!

**Review by sdixon194 — APPROVED** [review]

**Pull request merged**
