### PR TITLE
Boost: Allow loading default pages for cornerstone pages UI

### PR DESCRIPTION
**Pull request by dilirity**
## Proposed changes:

- Add button that loads default pages for Cornerstone Pages UI.

CleanShot 2024-11-08 at 15 17 41

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

- Setup Boost;
- Make sure the "Load Default" button in the Cornerstone Pages UI works as expected.

### CODE REVIEW

**Review by haqadn — CHANGES_REQUESTED** [review]
The restore defaults button is identical to save. It should be a secondary button, e.g. a link.

**Comment by dilirity** [comment]
I've updated the button to be less priminent:

CleanShot 2024-11-11 at 16 50 08

**Review by haqadn — APPROVED** [review]
👍🏼

**Comment by donnchawp** [comment]
Cherry picked into 3.6.0 beta 2: 1d19ea3709cc7033c8f785aaf5d3dd9b12fcb01c

**Pull request merged**
