### PR TITLE
At A Glance: Update case in lodash/forEach import

### PR DESCRIPTION
**Pull request by oskosk**
Fixes _hopefully_ module resolution in environments where webpack is case sensitive.

#### Changes proposed in this Pull Request:

- Replaces usage of `'lodash/foreach'` for `'lodash/forEach'`

### CODE REVIEW

**Comment by oskosk** [comment]
cc @kraftbj

**Comment by dereksmart** [comment]
LGTM

**Comment by zinigor** [comment]
Case sensitivity FTW, so IPF, LGTM!

**Comment by kraftbj** [comment]
That resolved it for the system I was having trouble with. 👍

**Pull request merged**
