### PR TITLE
Add a feedback admin view switch

### PR DESCRIPTION
**Pull request by ice9js**
## Proposed changes:

This patch adds a 'view switch' which will allow for switching between the classic WP Admin view for the feedback area and the new Jetpack Forms dashboard once it becomes enabled.

The switch is similar to the one already implemented for switching between WP Admin and Calypso views but it is also quite different in that both views are actually part of WP Admin itself.

Choosing an option through the dropdown, will also set that as the preferred option for the future.

Screenshot 2023-03-02 at 11 31 04

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pcsBup-Pl-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Enable the new dashboard and the switch with these filters:

```
add_filter( 'jetpack_contact_form_use_package', '__return_true' );
add_filter( 'jetpack_forms_dashboard_enable', '__return_true' );
```

- Go to WP Admin and click `Feedback` in the sidebar, you should be redirected to the new dashboard which currently also saves as the default setting.
- There should be a `View` dropdown in the upper right corner of the screen.
- Select `Classic` from the dropdown.
- You should now be on the old WP Admin view.
- If you go to any other WP Admin screen and click back on 'Feedback', it should now automatically show you the WP Admin interface which was your last preferred option.
- Switch back to the `Modern` version.
- Verify that `Modern` is now the default again.
- You should be able to access either view manually using the URLs: `admin.php?page=jetpack-forms` or `edit.php?post_type=feedback`
- Accessing a view through the URL without the `preferred-view` param should not affect your default setting.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
> The switch is similar to the one already implemented for switching between WP Admin and Calypso views but it is also quite different in that both views are actually part of WP Admin itself.

It works for me locally, but not on WoA. Do the 2 views conflict with each other?

**Comment by ice9js** [comment]
It seems the issue is WP.com is using a separate entrypoint for the contact form module, which we never updated to use the package. I'd say that's probably a separate issue that needs addressing on it's own, especially in the context of #28791, but not sure if it's that relevant to this PR.

**Comment by ice9js** [comment]
On some further investigation, it seems that once WP.com does render the dashboard, there are indeed some conflicts between this switch and existing WP.com menu implementation. I'll need to add a few more changes to get this to work reliably in both environments.

**Comment by ice9js** [comment]
In the meantime, I'm hoping D103406-code will help sort things out on WP.com @jeherve.

**Review by CGastrell — DISMISSED** [review]
"View" dropdown shows up when filter is enabled. Switching worked fine on its own. We need to give that app some more love though

**Review by jeherve — COMMENTED** [review]
The buttons now work, but something seems off with the focus:

image

**Comment by ice9js** [comment]
Looks like there were some conflicting class names on .com, I think the latest changes should resolve that.

**Review by jeherve — DISMISSED** [review]
This tests well for me now.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
