### PR TITLE
CRM: move quote delete away from update button

### PR DESCRIPTION
**Pull request by gogdzl**
This PR moves the delete button further away from the update button.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/zero-bs-crm/issues/2947

## Testing instructions:

* Go to the edit page for a quote (e.g. `wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=quote&zbsid=1`)
* Check if the new placement of the Delete button looks like the after picture.

Before:
image

After:
image

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
The new placement matches.
I do notice that on browser widths between 992px to 1218px there is some overlap though:
Screenshot 2023-03-22 at 10 48 27


I also wonder what these means for other 'Actions' metabox - do they also need to change? Like the invoice actions metabox. Also the contact actions metabox - that doesn't have a delete button (part of the dropdown), so the style won't match anymore (once this PR is merged anyway. https://github.com/Automattic/jetpack/pull/29579 ).

Maybe instead of moving the link it could also be a button, but below the update button? There is a check to make sure you want to delete so it doesn't matter too much if it's accidentally clicked.

**Comment by tbradsha** [comment]
> Maybe instead of moving the link it could also be a button, but below the update button?

This is my thought as well. I prefer the original vertical alignment, and it's less likely to have overflow issues, so a button should make it clearer what one is pressing.

As @coder-karen mentioned, it's not so easy to accidentally delete, as there's a confirmation modal. Has this ever been a complaint or did design bring this up?

**Comment by gogdzl** [comment]
Fixed the overflow, can you two take a new look?

**Comment by cleacos** [comment]
It seems there is a conflict here

**Review by cleacos — COMMENTED** [review]
I still see the previous design:

image

I checked it on a fresh JN site, and also locally. @gogdzl is it okay?

**Comment by tbradsha** [comment]
@gogdzl I've looked at this, but am not quite sure what the end goal of the PR is; it doesn't look like the "After" picture indicated above, but instead looks like the before image.

**Comment by gogdzl** [comment]
> I checked it on a fresh JN site, and also locally. @gogdzl is it okay?

> @gogdzl I've looked at this, but am not quite sure what the end goal of the PR is; it doesn't look like the "After" picture indicated above, but instead looks like the before image.

Someone forgot to push... sorry about that.
Could you take another look?

**Review by cleacos — APPROVED** [review]
Now, I can see it as was expected:

image

Also, it works with different screen sizes.

**Comment by tbradsha** [comment]
This now works as intended by the PR, but I think it's a step back as to the design...

**Comment by gogdzl** [comment]
I'm closing this PR as we have decided to stick with the previous design that was more widely accepted as better.

**Pull request closed without merging**
