### PR TITLE
Search: Add story for the dashboard's NoticeBox component

### LINKED ISSUE #26056: JS Components: Build Search Status Info component
Presents the “we’re indexing your site” message to the user. Title, message, and icon. Possibly a callback to take action on clicking the icon? (jump to support docs)

Image

**Dynamic Properties:**

- icon
- localized title
- localized message

Please ensure the component could be previewed by storybook.

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #26056.

#### Changes proposed in this Pull Request:

Screen Shot 2022-09-22 at 3 13 38 PM

* Tweaks the NoticeBox component to adhere to the new design specs.
* Enables Storybook scanning for the Search package.
* Adds several stories for the NoticeBox component.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Spin up storybook via `cd projects/js-packages/storybook && npm run storybook:dev`.
* Ensure you can see the new Search package section. Ensure that you can see five new stories for the NoticeBox component.
* Ensure that each story renders as expected.

### CODE REVIEW

**Review by oskosk — DISMISSED** [review]
Tests as described

**Comment by oskosk** [comment]
Pushed rebase in [065bdc6](https://github.com/Automattic/jetpack/pull/26367/commits/065bdc6b4e312f5b91e7ba5d8d249dbff71d8f4b) and versions update in [158a7dd](https://github.com/Automattic/jetpack/pull/26367/commits/158a7dda5ab7d56ab50c4ae8a23282f1b7fec062)

**Review by oskosk — DISMISSED** [review]

**Review by kangzj — COMMENTED** [review]
It works as described 👍 

Only tests need a refresh 🧪

**Review by kangzj — DISMISSED** [review]
:shipit: 

-----

😮‍💨 I don't have the magic power apparently

**Review by kangzj — APPROVED** [review]

**Pull request merged**
