### PR TITLE
Improve translator comment about a taxonomy name

### PR DESCRIPTION
**Pull request by akirk**
Please check if this is really a taxonomy name that would be replaced here.

### CODE REVIEW

**Comment by jenial** [comment]
This is really hard to translate into Russian (and possibly other languages) because of concatenation. It is such a short string so hard to paraphrase, and the taxonomy word would need to change the form. Is there a way to rephrase the original string, and perhaps do without the placeholder?

**Comment by akirk** [comment]
Good call. I think the list is really indeterminable. What about an original with a colon? `All pages of the type:`

**Comment by jenial** [comment]
That would be better (assuming no space constraints), perhaps a native speaker could vet this too?

**Comment by akirk** [comment]
You mean native Russian or native English?

**Comment by dereksmart** [comment]
> All taxonomy elements of the type:

I think we should try to keep it as short as possible. it's displayed in a select dropdown.  https://cloudup.com/c_bcv9QzC7B

@zinigor as a native russian speaker, do you have any suggestions?

**Comment by zinigor** [comment]
Yeah, I agree, it's pretty tough to keep it short. The shortest easily translatable string that comes to my head would be: "All pages tagged: %s" And in Russian that would be a little longer: "Все страницы с тэгом: %s"

**Comment by dereksmart** [comment]
Brain dumping some other ideas -- not sure which would make sense in translations: 

- `%s (all)`
- `All pages in: %s`
- `Everything in: %s`
- `All pages with taxonomy: %s`

**Comment by akirk** [comment]
@dereksmart Thanks a lot! I took a closer look at the code: the "Project Tags:" seems already to be the label of the taxonomy. What's the reason you want to include the "internal" name of the taxonomy in the string? Wouldn't just `All pages` be enough? It's within the `optgroup` already.

**Comment by dereksmart** [comment]
@akirk That's a good thought, and I think it makes sense visually: 
https://cloudup.com/c2RM4qEIA0Q

**Comment by dereksmart** [comment]
alternatively we could use the label name instead, which is already plural.  `All %s`: 

screen shot 2015-11-27 at 10 20 17 am

**Comment by akirk** [comment]
@dereksmart probably again something that is possible in English, but not in all languages. Let's go for the simple solution without a variable, if that's ok for you :) I already committed it.

**Comment by dereksmart** [comment]
:+1: :shipit: thanks @akirk!

**Comment by akirk** [comment]
I defined a context when I meant to define the domain, sorry :( Please merge again

**Pull request merged**
