### PR TITLE
Make Main.shouldComponenUpdate return false by default

### PR DESCRIPTION
**Pull request by oskosk**
Fixes warnings in console about `shouldComponentUpdate` returning undefined

#### Changes proposed in this Pull Request:
- Adds a `return false` statement for default cases in `Main` component's `shouldComponentUpdate` method

### CODE REVIEW

**Comment by oskosk** [comment]
cc @dereksmart

**Comment by dereksmart** [comment]
My IDE is now flagging this as being able to be simplified, which is kinda annoying.  What if we did this? 

```
shouldComponentUpdate: function( nextProps ) {
		return nextProps.jetpack.connection.status !== this.props.jetpack.connection.status
			|| nextProps.jetpack.jumpstart.status.showJumpStart !== getJumpStartStatus( this.props )
			|| nextProps.route.path !== this.props.route.path;
	},
```

**Comment by oskosk** [comment]
@dereksmart I've updated this PR to include the expression you proposed

**Comment by dereksmart** [comment]
nice, :shipit:

**Pull request merged**
