### PR TITLE
Contact Form: Disable contact form for feedback submissions

### PR DESCRIPTION
**Pull request by kraftbj**
#### Changes proposed in this Pull Request:

* Disable Gutenberg for contact form submissions

The contact form submissions are editable in wp-admin; however, they are loading in the block editor. As this is all meta data (that is, I admit, stored in an interesting way), it doesn't make sense to edit them in the block editor. Let's keep it classic.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.
#### Testing instructions:

* Jetpack site, connected, new post, add a contact form block. Save and submit a contact form submissions.
* Via wp-admin, visit the feedbacks post list and click edit.
* Before patch, it'll open in the block editor.
* After patch, it won't.

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Doesn't seem to work when I test it according to the instructions.

When I search for information about the `gutenberg_can_edit_post_type` filter you're using, I find results that suggest it was replaced by `use_block_editor_for_post_type` in WordPress 5.0.

**Comment by kraftbj** [comment]
Thanks for catching that. Confirmed that this new hook works (without Gutenberg installed!)

**Review by anomiex — APPROVED** [review]
Works now

**Comment by kraftbj** [comment]
r229642-wpcom

**Pull request merged**
