### PR TITLE
Calendly block: Add default value to input field

### PR DESCRIPTION
**Pull request by ramonjd**
#### Changes proposed in this Pull Request

As noticed over in https://github.com/Automattic/jetpack/pull/19883#pullrequestreview-663951385, there is a react warning about 'component is changing an uncontrolled input' when you paste a url into placeholder url box the first time.

This PR adds a default value to the field to prevent this error.

Screen Shot 2021-05-20 at 4 39 41 pm

Props to @glendaviesnz for the suggestion.

#### Testing instructions:
1. Insert a Calendly block into the editor
2. Enter text in the input field and check the browser console.

The uncontrolled component error should be gone. Whoosh!

### CODE REVIEW

**Review by aaronrobertshaw — DISMISSED** [review]
This worked well for me in the block's placeholder embed field. 

There is also another embed field in the block's sidebar controls that still threw the uncontrolled input error.



I pushed a commit mirroring the placeholder fix for the second input. Hope you don't mind 🙂

**Comment by ramonjd** [comment]
> There is also another embed field in the block's sidebar controls that still threw the uncontrolled input error. I pushed a commit mirroring the placeholder fix for the second input. Hope you don't mind 🙂

Nice catch. Thanks for fixing! 🙇

**Review by samiff — APPROVED** [review]
LGTM 🚢

**Comment by ramonjd** [comment]
r226051-wpcom

**Pull request merged**
