### PR TITLE
Stats: Allow custom user role stats settings to be recognized

### LINKED ISSUE #8161: Stats: Modifying "Count logged in page views from" for custom roles does not work
Originally reported here: https://wordpress.org/support/topic/setting-to-count-logged-in-page-views-from-customers-does-not-stick/

I was able to reproduce this on my test site. I have several custom roles:

screen shot 2017-11-14 at 11 58 00 am

I can click one of them and Activate it, and I get a green success message. However, when I refresh the page, the role is deactivated again.

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes #8161

#### Changes proposed in this Pull Request:

* This PR adds custom roles to the SiteStatsComponent state. This means that the stats toggles for those custom roles are properly recognized when modified, and those changes also honored: custom user roles can view stats if that option is toggled on (and not otherwise), and similarly their logged in page views are recorded if that option is toggled on (and not otherwise).

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

Technically we're more reliably tracking non-standard user role activity or tracking how the settings are configured, but this is already [covered on our support doc](https://jetpack.com/support/wordpress-com-stats/#privacy).

#### Testing instructions:

* To test this out, you'll need to add several (more than one ideally) custom user roles on a Jetpack-connected site. The User Role Editor plugin is one way to do this.
* From a connected admin page, visit Jetpack > Settings > Traffic (`/wp-admin/admin.php?page=jetpack#/traffic`).
* In the 'Site Stats' section, test modifying the toggle state for various roles (custom and not custom). Do they correctly update? Try refreshing the page to make sure the changes have stuck.
* Then, logged in with the user roles in question, test to see if the changes applied are correctly reflected. 
  * For example, if the option to view stats is toggled on, can you view stats at this page, and is access denied if it is disabled? -> `/wp-admin/admin.php?page=stats`
  * Also, if the option to track logged in page views is enabled for any specific roles (custom and non custom), are logged in page views being correctly recorded (and not recorded if the toggle is disabled)?

### CODE REVIEW

**Comment by sdixon194** [comment]
Nicely done, this works for me! I'll cc @samiff who has a bit more react experience to give a second look at the code itself, but functionally it all seems to work very well.

**Comment by samiff** [comment]
I haven't dug into the code, but just did some quick functionality testing. I created a custom role "testEditor" based off the Editor role. When toggling on either the `Count logged in page views from` or `Allow stats reports to be viewed by` setting for a custom role, it seems to persist that state in the other section - they should be independent. For standard roles, those continue to toggle correctly in either section as expected with this PR.

@coder-karen are you seeing the same on your end?

https://user-images.githubusercontent.com/15803018/176748348-bd53d603-7911-43dc-a51d-c0a2e3714767.mov

**Comment by coder-karen** [comment]
Thank you @samiff ! I went back to this and did see an issue - basically the toggle for 'count logged in page views'  was not respecting state. This was only visible when the 'allow stats to be viewed by' toggle was disabled for a user role - when enabled everything appeared to be working properly (you could toggle  'count logged in page views' on and off without affecting the 'allow stats to be viewed by' option). Presumably that could have been what was happening for you too?

Anyway the issue was that I'd set state for the two different arrays of option names ( countRoles and roles ) in the same `if` statement (each of these control the two different toggle cases). Separating them out seems to have done the trick here, from what I'm seeing in testing.

Does this work for you now?

**Review by samiff — APPROVED** [review]
That looks much better 👍  Tested setting each section independently and the local and option states are persisted correctly. Permission to view stats page and view counts for custom roles also tested nicely for me.

**Pull request merged**
