### PR TITLE
Untangle: Do not add the dashboard switcher for the wp-admin interface

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/dotcom-forge/issues/5285

## Proposed changes:

This PR skips adding the dashboard switcher when the admin interface style is wp-admin.

| Before | After |
| --- | --- |
| Screenshot 2024-01-24 at 11 53 54 AM | Screenshot 2024-01-24 at 11 54 07 AM |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Head to Settings → Hosting Configuration.
- Scroll to the Admin interface style section, and select Classic style.
- Refresh the page if needed.
- Ensure that the dashboard switcher is no longer present in core pages.

### CODE REVIEW

**Review by okmttdhr — DISMISSED** [review]
Worked as intended 👍

**Comment by arthur791004** [comment]
I still see the switcher. Am I missing something 🤔

image

**Comment by arthur791004** [comment]
Tested and works as expected

image

**Review by arthur791004 — DISMISSED** [review]

**Comment by taipeicoder** [comment]
@okmttdhr @arthur791004 could I get another review at this? I've updated the implementation strategy.

**Review by okmttdhr — APPROVED** [review]
The new implementation made sense to me. Tested and looked good ☑️

**Pull request merged**
