### PR TITLE
Redirect Settings menu to calypso

### LINKED ISSUE #18216: Nav Unification: Settings Link in Calypso goes to WP-Admin
#### Steps to reproduce

1. Click on the "Settings" menu option in Calypso

#### What I expected

The menu to expand like the other menu options (Tools for example)

#### What happened instead

The Settings menu opened WP-Admin

#### Browser / OS version

MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198

#### Screenshot / Video

https://user-images.githubusercontent.com/1398304/103673482-7aac3f80-4f32-11eb-8a3a-c8aaf0fda1b5.mov

#### Context / Source

#manual-testing

### PR DESCRIPTION
**Pull request by cpapazoglou**
Fixes #18216

As [this spreadsheet](https://docs.google.com/spreadsheets/d/1i640dQt4vs2XYgqRA4YEH69ssR9UNcFJx49HUss0-q0/edit#gid=0) suggests, Settings should redirect to Calypso.

#### Changes proposed in this Pull Request:

* Changes link direction of Setting menu to Calypso rather than wp-admin

## Manually
* Enable nav-unification (paYJgx-1af-p2)

**Simple**
* Apply D54949-code in your sandbox

**Atomic**
* Use Jetpack Beta and select the current branch

**Result:**
* Inspect the Settings submenu, nothing should have changed except from the fact that Settings redirects to calypso now

## Automated
run `yarn docker:phpunit --filter Admin_Menu`

#### Proposed changelog entry for your changes:

* Settings menu now redirects to Calypso Settings when Dashboard Customizations are enabled.

### CODE REVIEW

**Review by obenland — CHANGES_REQUESTED** [review]
Let's hold off on this until we resolved https://github.com/Automattic/jetpack/issues/18216#issuecomment-755504146. I don't know if this is something we want to do.

**Comment by cpapazoglou** [comment]
> Let's hold off on this until we resolved [#18216 (comment)](https://github.com/Automattic/jetpack/issues/18216#issuecomment-755504146). I don't know if this is something we want to do.

I thought we have already concluded that:
1) The spreadsheet suggests so
2) There are missing features if we don't, like for example "Writing" & "Discussion" panes

**Review by obenland — APPROVED** [review]
> The spreadsheet suggests so

Indeed it does. I wish there was a better way to keep up with changes, even ones that were made four months ago, apparently.

I removed the cap check since that gets handled on render. Unit tests passed without changes.

**Comment by obenland** [comment]
@cpapazoglou Thanks for working on this, I missed this one.

**Review by jeherve — APPROVED** [review]
LGTM. Merging (I'll let you handle the wpcom counterpart).

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.3` in 073b0feb96080e17938dee8ee8708f850eb42258

**Comment by cpapazoglou** [comment]
Deployed r219076-wpcom

**Pull request merged**
