### PR TITLE
Fix contact form submission email formatting

### LINKED ISSUE #27897: Form Responses in the email are no longer formatted
### Quick summary

Form responses in the emails appear to be unformatted, since Dec 1, 2022.

I was able to replicate the issue on Gmail, where the class, `.field-name`, is no longer bold, and each div appears in a new line.

Was there anything that changed on our side?

18229723-hc → 5763907-zen

### Steps to reproduce

1. Add a Form block to a page and publish it.
2. Submit a form.
3. Check the email (I used Gmail).

### What you expected to happen

Each item was previously on the same line, where the `.field-name` was bold.

### What actually happened

The formatting was removed.

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by ice9js**
Fixes #27897

#### Changes proposed in this Pull Request:

This patch fixes contact form email formatting which was accidentally removed in #27392.
Because we plan on doing more work around the submission views, I opted to entirely decouple the logic for rendering the email so this doesn't become an issue again in the future.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

- Create a post and add a contact form, make sure to add your email in the sidebar so you receive a copy of every submission.
- Publish the post and visit it.
- Submit the contact form.
- You should receive an email with the basic formatting applied to the submission data.

### CODE REVIEW

**Review by digitalwaveride — DISMISSED** [review]
Thanks so much Kuba for fixing this!

Test worked for me!

Formatting in Gmail:
image

In my Email client:
image


The "sent message view" looks as expected:

image

**Review by digitalwaveride — DISMISSED** [review]

**Review by sdixon194 — DISMISSED** [review]
Works for me! Plaintext also retains the line breaks (but not the bold)

**Comment by jcheringer** [comment]
I think those changes will bring back this issue: https://github.com/Automattic/jetpack/pull/27628#pullrequestreview-1216485431

c.c. @ice9js @digitalwaveride

**Comment by ice9js** [comment]
Nice catch @jcheringer, thanks! I replicated the fix you added in that PR to work for emails as well.

**Review by jcheringer — APPROVED** [review]
Works for me! 👍

**Review by sdixon194 — APPROVED** [review]
Nice, still works for me!

**Comment by sophiegyo** [comment]
We did have someone asking if they could have responses on the same line as the label again:
https://wordpress.com/forums/topic/an-update-must-have-changed-the-way-i-receive-submited-orders-please-help/?view=all

I figured it was worth passing the request on, even if there aren't any plans to do that :)

**Pull request merged**
