### PR TITLE
Subscribers Page: Add `Subscribers` link to the menu

### PR DESCRIPTION
**Pull request by ivan-ottinger**
This PR adds the Subscribers link to the menu in these places:

- WPCOM & Atomic: Users menu
- Self-hosted Jetpack: Jetpack menu

It only adds them when the user locale is set to English.

### Other information:

- [X] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p1686580459461379-slack-C02TCEHP3HA

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Since the way menus work in Calypso ([more info](PCYsg-vFk-p2), this patch has to be deployed on your sandbox, and `public-api` needs to be sandboxed. 

I found it very difficult to properly test this for Atomic & self-hosted, as the API endpoint seemed to think that every site I gave it was a Simple Site. 

I resorted to unit testing, as the issue is probably with my setup. 

If you get this working please tell me how 👍 

To run the tests:

``` jetpack docker phpunit -- --filter=Admin_Menu ```

### CODE REVIEW

**Comment by jeherve** [comment]
Should we make this available to self-hosted sites as well, via a new item under the Jetpack menu maybe?

**Comment by ivan-ottinger** [comment]
> Should we make this available to self-hosted sites as well, via a new item under the Jetpack menu maybe?

Thank you for the comment, Jeremy!

I actually created a TODO item in the related GH task last week: https://github.com/Automattic/wp-calypso/issues/77531, just didn't get to it yet. 🙂 

By the "Jetpack" menu, do you mean this one?

Markup on 2023-06-05 at 15:15:56

Here's the project thread for context: pdDOJh-1TE-p2.

**Comment by jeherve** [comment]
> By the "Jetpack" menu, do you mean this one?

Yes, this one on WoA sites, and on self-hosted sites.

**Comment by TimBroddin** [comment]
Added to Jetpack. I still have to test this.

**Comment by ivan-ottinger** [comment]
Hey @jeherve 👋🏼 Just to double-check: If we understand correctly, there's currently a daily deploy to WPCOM Simple (p58i-eqs-p2). Is that correct?

Does that mean that once this PR is merged, it will be deployed to WPCOM Simple the next day?

Also, does this follow UTC time (e.g. everything merged prior the end of the day in UTC will get deployed the next day)? Thank you.

**Comment by jeherve** [comment]
> If we understand correctly, there's currently a daily deploy to WPCOM Simple (p58i-eqs-p2). Is that correct?

That's correct.

> Does that mean that once this PR is merged, it will be deployed to WPCOM Simple the next day?

It may even be deployed on the same day, if you merge it before deployment happens.

> Also, does this follow UTC time (e.g. everything merged prior the end of the day in UTC will get deployed the next day)?

There is no code freeze for those daily deployments, so anything you merge before the release lead starts the daily deployment (usually after 14:00 UTC).

**Review by phcp — DISMISSED** [review]
Code looks good and the tests are passing as expected. I also tried but couldn't find other ways to test it.

**Review by jeherve — DISMISSED** [review]
This tests well for me, it should be good to  merge. I must say I was a bit curious about the language restriction. Is there some background behind this? If we wanted to limit access, I would have expected it to limit access based on the user's language, not the site language.

**Comment by TimBroddin** [comment]
> This tests well for me, it should be good to merge. I must say I was a bit curious about the language restriction. Is there some background behind this? If we wanted to limit access, I would have expected it to limit access based on the user's language, not the site language.

You're 100% right, this should be user's language. I'll update the PR.

**Comment by TimBroddin** [comment]
I've updated the PR! We'll be pushing this only to English users if we don't have all translations when we merge this. Otherwise I'll remove this check.

**Review by yansern — APPROVED** [review]
Re-ran test, ~now no more failing tests~ (update: still failing). Re-approving.

Greenlight to merge: p1686869690550299/1686869270.217619-slack-CBG1CP4EN

**Pull request merged**
