### PR TITLE
Implements the php TUS client to upload videos from the Media Library 

### PR DESCRIPTION
**Pull request by leogermani**
Note: We are still considering whether this will live in the package or in the plugin, Not merging just yet.

#### Changes proposed in this Pull Request:

* Implements the php TUS client to upload videos from the Media Library directly to the VideoPress servers

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

1202184803119163-as-1202583706992777

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Setting up:

First of all, upload a video file to your Media Library

* Go to Media > Add new and upload a video
* Make sure you don't upload the video to VideoPress.
* On the Media Library, click the new video and find out the attachment ID

Testing

In order to test it, we are going to use WP CLI

* launch the interactive shell with `jetpack docker wp shell`

Let's follow the happy path:

* Create a new instance of the Uploader: `$u = new Automattic\Jetpack\VideoPress\Uploader(92);` where 92 is the ID of your video attachment
* Check the status: `$u->check_status()`
* You should see something like:

Captura de tela de 2022-07-27 18-16-07

* Now start the upload with `$u->upload()`
* It will upload your file in chunks of 1MB. You should see a response like this:
Captura de tela de 2022-07-27 18-17-03

* Call `$u->upload()` as many times as needed to upload your video completely. Hopefully your video is not to big and it will get only a couple of times
* Each time it will upload 1MB and increse the value of `bytes_uploaded`
* When the video is complete, you should see something like this:
```
>>> $u->upload();
=> [
     "status" => "complete",
     "bytes_uploaded" => 8589783,
     "upload_key" => "s-204213934-v-92",
     "uploaded_details" => [
       "guid" => "XXXXYYYZZZ"
       "media_id" => "156",
       "upload_src" => "https://videos.files.wordpress.com/XXXXYYYZZZ/file-name.mp4",
     ],
   ]
```

* Nice! it worked!
* Back on your browser, go to your Media Library and confirm you have a new attachment and that this attachment is a videoPress video with the file you just uploaded
* Back to the CLI, let's check some additional stuff:
* `$u->is_uploaded()` should return true
* `$u->get_uploaded_attachment_id()` should return the ID of the new attachment created.
* `$u->check_status()` and `$u->upload()` should return the same thing. Info that the file was already uploaded.

Note that you can close the shell and create a new instance of the Uploader at any time and the results should be the same.

Some unhappy paths

* Try to initialize the Uploader with an ID of a post that is not an attachment, or an attachment that is not a video, and confirm it throws

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202583706992777

### CODE REVIEW

**Comment by kraftbj** [comment]
A couple of open higher-level questions:
* this requires PHP 7 while the Jetpack plugin requires 5.6 still. What's the best way to safeguard to ensure we don't crosswires and either put something into Jetpack that wouldn't fly on older systems or degrade the functionality for those folks?
* let's ensure we audit the tus package for security.

Noting for future ref that it is MIT, which is GPL-compat, so no problems on that front. https://github.com/ankitpokhrel/tus-php/blob/main/LICENSE

**Comment by leogermani** [comment]
hey @kraftbj thanks for jumping in. I'm about to post a p2 to centralize this conversation, but to answer your questions:

. The Uploader class has a "is_supported" method. The idea is to only enable this feature in sites that support it. And that lib will only be loaded in those cases (https://github.com/Automattic/jetpack/pull/25302/files#diff-d023f18f671b4132f279bf23ed098c3e7f2e85710c9036374e4253fbf9cde4d9R67)
. We are still not sure if the new block that uses it will be shipped on Jetpack or only in VideoPress stand-alone plugin. This decision can change the approach a bit
. Since it's MIT, we also have the option to incorporate the code and modify it to support PHP 5.6

> let's ensure we audit the tus package for security.

Good point

**Comment by leogermani** [comment]
@kraftbj  pe4Cmx-92-p2

**Comment by kraftbj** [comment]
Regarding b3a33ff and 2d78db3, we've always allowlisted `vendor/**` directories that we needed in plugins, which seems to go back a long ways. With the ability to `production-exclude` anything that we really don't need and `--no-dev` working, it seems to me to be a solution without a problem that causes headaches to the development process.

Since it's early in the release cycle, we can check the production repo after merge and see the impact, then go from there.

**Comment by leogermani** [comment]
@kraftbj  as per pe4Cmx-92-p2#comment-91 I removed all external dependencies, so I reverted tha changes to `.gitattributes` from this PR. Letting you know in case you want to do this in another PR

**Review by retrofox — DISMISSED** [review]
First of all, upload a video file to your Media Library

-[x] Go to Media > Add new and upload a video
-[x] Make sure you don't upload the video to VideoPress.
-[x] On the Media Library, click the new video and find out the attachment ID

`5`

Let's follow the happy path:

-[x] Create a new instance of the Uploader: $u = new Automattic\Jetpack\VideoPress\Uploader(5);
-[x] Check the status: $u->check_status()

```
wp> $u->check_status();
=> array(5) {
  ["status"]=>
  string(3) "new"
  ["bytes_uploaded"]=>
  int(0)
  ["file_size"]=>
  int(1209066)
  ["file_name"]=>
  string(43) "Screen-Recording-2022-08-04-at-17.28.56.mov"
  ["upload_key"]=>
  string(15) "s-209899684-v-5"
```

-[x] Now start the upload with $u->upload()

It will upload your file in chunks of 1MB. You should see a response like this: 🔴 

I get an error because I hasn't had connected my user:

```
=> array(6) {
  ["status"]=>
  string(5) "error"
  ["bytes_uploaded"]=>
  int(-1)
  ["file_size"]=>
  int(1209066)
  ["file_name"]=>
  string(43) "Screen-Recording-2022-08-04-at-17.28.56.mov"
  ["upload_key"]=>
  string(15) "s-209899684-v-5"
  ["error"]=>
  string(29) "0: Unable to create resource."
}
```

Connected the user

```
=> array(6) {
  ["status"]=>
  string(8) "complete"
  ["bytes_uploaded"]=>
  int(1209066)
  ["file_size"]=>
  int(1209066)
  ["file_name"]=>
  string(43) "Screen-Recording-2022-08-04-at-17.28.56.mov"
  ["upload_key"]=>
  string(15) "s-209899684-v-5"
  ["uploaded_details"]=>
  array(3) {
    ["guid"]=>
    string(8) "UinAQZ45"
    ["media_id"]=>
    string(1) "6"
    ["upload_src"]=>
    string(87) "https://videos.files.wordpress.com/UinAQZ45/screen-recording-2022-08-04-at-17.28.56.mov"
  }
}
```

-[x] Back on your browser, go to your Media Library and confirm you have a new attachment and that this attachment is a videoPress video with the file you just uploaded

image

```
wp> $u->is_uploaded()
=> bool(true)
```

```
wp> $u->get_uploaded_attachment_id()
=> string(1) "6"
```

```
wp> $u->check_status()
=> array(4) {
  ["status"]=>
  string(8) "uploaded"
  ["upload_key"]=>
  string(15) "s-209899684-v-5"
  ["uploaded_post_id"]=>
  string(1) "6"
  ["uploaded_video_guid"]=>
  string(8) "UinAQZ45"
}
wp> $u->upload()
=> array(4) {
  ["status"]=>
  string(8) "uploaded"
  ["upload_key"]=>
  string(15) "s-209899684-v-5"
  ["uploaded_post_id"]=>
  string(1) "6"
  ["uploaded_video_guid"]=>
  string(8) "UinAQZ45"
}
```

**Comment by retrofox** [comment]
I've tested the PR and it works pretty well! Nice work 🚀 Maybe getting another ✅ from other folks won't hurt.

**Review by oskosk — DISMISSED** [review]
LGTM!

**Review by retrofox — APPROVED** [review]
LGTM

**Pull request merged**
