### PR TITLE
Update analytics events for JITMs

### PR DESCRIPTION
**Pull request by jboland88**
#### Changes proposed in this Pull Request:

* This PR adds a `jitm_message_path` property to JITM related analytics events. 
* This allows for some differentiation for a message that may show in multiple locations.

#### Jetpack product discussion

pbNhbs-1vV-p2#comment-5193

#### Does this pull request change what data or activity we track or use?

Yes, this PR adds a new `jitm_message_path` prop to `jitm_view_client` and `nudge_click` analytics events.

#### Testing instructions:

* Apply this PR to your Jetpack test site
* Make sure you build the following packages: `jetpack build packages/jitm` `jetpack build packages/tracking`
* Build the Jetpack plugin: `jetpack build plugins/jetpack` 
* Navigate to the Jetpack dashboard of your test site. If you have not dismissed it already in the past, you should see a JITM message show at the top of the page about the Jetpack Mobile App:
Screen Shot 2021-12-22 at 4 10 41 PM

* Click on the "Download for free CTA button"
* Wait a few minutes and confirm that Tracks has received the events for `jitm_view_client` and `nudge_click` and that both have the `jitm_message_path` prop set.

### CODE REVIEW

**Review by travisw — DISMISSED** [review]
LGTM 🚀 

Confirmed using Tracks live view that the `jetpack_jitm_view_client` and `jetpack_nudge_click` events both have the `jitm_message_path` property.

Screen Shot 2021-12-23 at 3 17 09 PM

**Comment by kbrown9** [comment]
Hi @jboland88! I was thinking about a way to handle the click tracking without adding special JITM handling to the Tracking package. What do you think of possibly handling the button clicks in the JITM package, in the `jetpack-jitm.js` file, and calling `jpTracksAJAX.record_ajax_event` directly with the `clicked` and `jitm_message_path` properties? (See https://github.com/Automattic/jetpack/tree/master/projects/packages/tracking#4-making-your-own-ajax-calls)

**Comment by leogermani** [comment]
Hi, I also like @kbrown9 proposal. Instead of relying on the approach of adding the `jptrack` class to the link, we can handle the click event in the jitm js and add any property we want.

Also dropping a reminder to update the FG page once this is merged: PCYsg-cLC-p2

And looking at the source code, apparently there is one JITM template that is not tracking events. I'm not sure if this is not in use anymore, but if you look at:

https://github.com/Automattic/jetpack/blob/e07b226a614128021f97ea43fb1ce99634d19faa/projects/packages/jitm/src/js/jetpack-jitm.js#L31

not only the event name is different from the others (`nudge_item_click` instead of `nudge_click`) but the `jptracks` class is missing from the link, so this is never tracked. Of course this could be addressed in a separate PR, but since you're there it would be nice at least to confirm the bug.

**Comment by jboland88** [comment]
Closing this one due to age, will revisit in a new PR

**Pull request closed without merging**
