### PR TITLE
Fix #2307 Stop scrolling to top when closing module description modal…

### LINKED ISSUE #2307: Clicking X to exit module description modal resets scroll position
To repro:

1. Visit Jetpack > Settings.
2. Scroll down a bit.
3. Click a module name to open the description modal.
4. Click the X in the upper-right to close the modal.

Your scroll position goes back to the top of the page, but ideally it should stay put?

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
Fix issue #2307

### CODE REVIEW

**Comment by dereksmart** [comment]
Many thanks for the PR, but we already have this fix submitted as a PR in #2311

**Comment by PatelUtkarsh** [comment]
Okay can you please close issue too it was open so i sent PR.

**Comment by kraftbj** [comment]
Thanks PatelUtkarsh. When viewing an issue, you can see if there is a PR that has referenced the issue: https://cloudup.com/cgYqb4rReKw

Generally, the issue will remain open until a fix has been merged in, in the event that a PR doesn't solve it or doesn't solve it in a way that makes sense for whatever particular reason. Cheers!

**Comment by PatelUtkarsh** [comment]
Okay, Thanks @kraftbj for info.

**Pull request closed without merging**
