### PR TITLE
Repo Gardening: Accept add_label input for passing custom path/label matching

### PR DESCRIPTION
**Pull request by dereksmart**
## Proposed changes:

Add add_labels input to addLabels task for setting custom path: label matching directly in the workflow like so: 
```
  with:
    tasks: 'addLabels'
    add_labels: '[
        {"path": "projects/your-project/", "label": "[Project] Your Project"},
        {"path": "somepath/", "label": "Some label"}
      ]'
```

This enables folks to not have to update the source in the monorepo for their own matching rules. 

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

You can test this by pointing the build to `uses: automattic/action-repo-gardening@ai-services`, which is [this branch](https://github.com/Automattic/action-repo-gardening/tree/ai-services/src/tasks) I created and hacked on in the action's mirror repo. Doing this allowed me to test it on both the ai-services repo as well as my personal fork. 

Note: the ai-services repo is currently running the ai-services branch and it seems to be fully functional. I plan to point it to trunk/stable again once this functionality is included. 
Check out the diffs that introduced it: 
- 221-gh-Automattic/ai-services
- 224-gh-Automattic/ai-services

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This tests well for me. 

We were discussing something like this in #19897. I think this is a good first pass, and if needed we can expand on that in the future, to extract the paths/labels to a separate file where it may be easier to manage labels when you start having a lot of them.

**Comment by dereksmart** [comment]
Thanks! 

> to a separate file where it may be easier to manage labels

Wonder what you have in mind for easier? The way I see it - whether it's the workflow file or another file, it's still editing one file.

**Comment by jeherve** [comment]
> Wonder what you have in mind for easier? The way I see it - whether it's the workflow file or another file, it's still editing one file.

You're right, it may not be that different after all.
I like the separate file idea since it only contains the path/labels and nothing else, it's focussed on one thing and you do not have to worry about anything else. If it gets quite long it's still easy to parse. But I can see how splitting things between 2 files would make other things more difficult.

**Comment by dereksmart** [comment]
Either way it should be pretty simple to modify handling of the add_labels input. Like if the string ends with `.json` assume it's a file to try to parse.

**Pull request merged**
