### PR TITLE
Contact Form: Update patterns modal filter query

### PR DESCRIPTION
**Pull request by jcheringer**
#### Changes proposed in this Pull Request:
* Updates the Contact Form patterns modal query to load the patterns correctly on WP.com

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a page/post
* Add a Form block
* Click the "Explore Form Patterns" button
* Check if the patterns load as expected

### CODE REVIEW

**Comment by CGastrell** [comment]
Works well on .com, not looking too good on AT sites.
image

**Comment by CGastrell** [comment]
New patterns are not present on self hosted installs, and the modal gets "shivery" on gallery mode:
patterns

**Review by CGastrell — APPROVED** [review]
This still needs work, but I'm not sure it can be done here. I'll approve only because it actually addresses part of the issue, but the overall behavior of the patterns modal is not ideal.

**Comment by sdixon194** [comment]
Thanks for the quick fix! Confirmed that this works with wpcom sites by using the downloader script. Also tested self hosted and atomic and didn't have the same issues as the jittering.

**Review by sdixon194 — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to release branch in 495e4f638719934fd1a707c18784e2e1ff5aed35

**Pull request merged**
