### PR TITLE
Button block: check block root parent attributes

### LINKED ISSUE #17425: Calendly Block: Link style does not work when used inside another block
When adding the Calendly block inside of a Cover block and using the Link style the button does not work properly. When a user clicks the button on the published page they see the Cover block image in a popup window instead of the Calendly page added in the settings.

#### Steps to reproduce the issue

1. Create a new page or post.
2. Add a Cover block.
3. Add Calendly block inside the Cover block.
4. Add a valid Calendly web address and click Embed.
5. Choose the "Link" style from the block Style settings.
6. Publish the page or post.
7. Click the Calendly button and see that it does not work correctly.

#### What I expected

When Calendly is used outside of a Cover block this is how it looks: 

Markup 2020-10-08 at 17 19 18

This is what should happen: 

Markup 2020-10-08 at 17 20 15

#### What happened instead

Instead of showing the scheduling page, as shown above, the Cover block background image is shown instead:

Annotation on 2020-10-08 at 17-23-42 (1)

### LINKED ISSUE #52687: Calendly Block: Popup not working as expected when placed inside of a column block
### Steps to reproduce the behavior

1. Create a page
2. Add a column block
3. Add the Calendly block within the column block
4. Embed an appropriate Calendly URL
5. Set Calendly block setting 'Styles' to 'Link'
6. Publish and view the page, click on the Calendly button

#### What I expected to happen

I expect a Calendly iframe to open up.

#### What actually happened

An iframe opens up with the address of the page you are currently on.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://d.pr/v/N0USWq

### PR DESCRIPTION
**Pull request by ramonjd**
When passing through attributes to a child Button block using `passthroughAttributes`, we want to make sure the Button looks to the correct parent block to fetch the attributes.

If a Calendly block is nested inside another block, previously the Button was looking to the top of the nesting tree rather than its parent.

## Changes proposed in this Pull Request

Rather than use [getBlockHierarchyRootClientId](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#getBlockHierarchyRootClientId), looks at the top of the tree in which a block is nested, we look to [getBlockRootClientId](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#getBlockRootClientId) so that we can get the immediate parent block.

Screen Shot 2021-05-19 at 3 32 31 pm

Fixes https://github.com/Automattic/jetpack/issues/17425
Fixes https://github.com/Automattic/wp-calypso/issues/52687

## Jetpack product discussion
See bug reports: 

https://github.com/Automattic/jetpack/issues/17425
https://github.com/Automattic/wp-calypso/issues/52687

#### Does this pull request change what data or activity we track or use?
Nope.

## Testing instructions:
1. Insert a Calendly block into the editor, and another inside a group or column block.
2. Add a Calendly url (you might have to sign up to Calendly) to each. Change each button to the "Link" style so that the button appears.
3. Change the buttons' text color.
4. Save and check the frontend.

- [ ] The button link should open the calendar.
- [ ] The text color should correspond to the one you chose.
- [ ] The universe is enormous. Feeling small is normal.

### CODE REVIEW

**Comment by Robertght** [comment]
Hey @ramonjd ! Is this a potential fix for this issue as well? https://github.com/Automattic/wp-calypso/issues/52687

**Comment by ramonjd** [comment]
> Is this a potential fix for this issue as well? Automattic/wp-calypso#52687

Thanks @Robertght ! Yes, that's a scenario I tested for this PR too. Appreciate the link! I'll add it to the PR desc

**Review by glendaviesnz — APPROVED** [review]
This all worked as advertised for me 👍 

The only thing I noticed is a react warning about  'component is changing an uncontrolled input' when you paste a url into placeholder url box the first time. Can be fixed by changing line 140 of edit.js to `value={ embedCode ? embedCode : '' }` ... but over to you if you want to sneak into this PR or we add a follow up

**Comment by ramonjd** [comment]
> The only thing I noticed is a react warning about 'component is changing an uncontrolled input' when you paste a url into placeholder url box the first time. Can be fixed by changing line 140 of edit.js to value={ embedCode ? embedCode : '' } ... but over to you if you want to sneak into this PR or we add a follow up

Thanks for testing @glendaviesnz ! I added your suggestion to a follow-up PR https://github.com/Automattic/jetpack/pull/19898

**Review by samiff — APPROVED** [review]
This tests well for me 👍   After patching, I didn't notice any new conflicts with existing Calendly blocks on a post, and updating that post allowed the Calendly blocks to work as expected.

**Comment by ramonjd** [comment]
r226052-wpcom

**Pull request merged**
