### PR TITLE
Use inline fill for form variation colours

### PR DESCRIPTION
**Pull request by scottsweb**
Re-introduce icon colors for Jetpack form variations:

Screenshot 2020-09-08 at 10 35 32

Relates to: #17089 #17092 

#### Changes proposed in this Pull Request:

* None, this reverts a revert

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* Pull the branch
* Head to the Gutenberg editor
* Check the icon colours for all Jetpack blocks are green

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by scottsweb** [comment]
One thing I did notice, is that the child form inputs are not green:

Screenshot 2020-09-08 at 10 45 49

**Review by keoshi — DISMISSED** [review]
Despite some color inconsistencies we're creating with Gutenberg itself, the changes on this PR look good to me.

image

**Comment by keoshi** [comment]
@folletto Would you mind weighing in on this change? The code looks great, just wondering how you feel about this introducing a variation on the existing Gutenberg patterns in favor of our branding.

**Comment by scottsweb** [comment]
I will add that I think in the block selector, having the green tie the blocks to Jetpack makes sense, but in the editor UI itself, we start to see the inconsistencies above and we move away from Gutenberg a little too much for my liking.

**Comment by folletto** [comment]
I agree. It starts feeling clashing a bit in the screenshot above. Also considered that we don't know future evolutions of Gutenberg itself in that regard (imagine if it goes full blue for selection/highlight).

Maybe we can limit the green only to the Inserter panel?

**Comment by scottsweb** [comment]
I am not sure we have that much context to inform different icon handling, but I will look into it.

**Comment by scottsweb** [comment]
Added support for the individual form fields:

Screenshot 2020-10-15 at 16 36 59

**Comment by scottsweb** [comment]
Screenshot 2020-10-15 at 16 24 17

Also noting that WooCommerce does the same.

**Comment by scottsweb** [comment]
I think we are good here now. 

I am unable to change the icons within the block independently

Screenshot 2020-10-15 at 17 14 21

So these will remain green too for now.

**Review by keoshi — APPROVED** [review]
Looks great in my testing! 🚀

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by jeherve** [comment]
r219420-wpcom

**Pull request merged**
