### PR TITLE
JSON API: set default for each input variable to avoid notices

### PR DESCRIPTION
**Pull request by jeherve**
Improves on #2393.

cc @dereksmart

### CODE REVIEW

**Comment by jeherve** [comment]
Fixes #2047

**Comment by samhotchkiss** [comment]
Looks good, but would like @dereksmart to give his input

**Comment by zinigor** [comment]
Read the changes, fixed some more notices in v1 version of the endpoint, rebased, looks good to go.

**Comment by samhotchkiss** [comment]
Thanks, @zinigor -- I pinged @dereksmart on this, would like his sign off too, once you check it out, Derek, feel free to merge

**Comment by dereksmart** [comment]
Looks good, tests well.  Don't see any more notices on update/publish

**Pull request merged**
