### PR TITLE
Protect: jpp_math_pass cookie and transient after generate_math_page form submission

### LINKED ISSUE #5646: jpp_math_pass cookie and transient are not set after generate_math_page form submission
When using a bbPress login widget, it seems the user always gets to see the math page generated by Jetpack_Protect_Math_Authenticate::generate_math_page (see issue #5144) 

This math puzzle form has the hidden form field "jetpack_protect_process_math_form" which (as I understand it) should trigger the method process_generate_math_page (see lines 21-23 of math-fallback.php) which in turn should set a cookie jpp_math_pass if the puzzle was solved. See lines 21-23 of math-fallback.php:

`
  if( isset( $_POST[ 'jetpack_protect_process_math_form' ] ) ) {
    add_action( 'init', array( $this, 'process_generate_math_page' ) );
  }
`

This does not seem to happen.

The problem is that math-fallback.php is not loaded except when the action hook login_init is fired. The init action that is then added by the above code will not be used because init has already passed...

Fix: make it priority 11 (or higher) and either use 'login_init' here or switch to 'init' on line 53 in protect.php

### PR DESCRIPTION
**Pull request by RavanH**
Fixes #5646

#### Changes proposed in this Pull Request:

**protect.php**

Load math fallback after math page form submission to run Jetpack_Protect_Math_Authenticate::process_generate_math_page()

Add a check if jpp_math_pass cookie is set and it matches valid transient to check_login_ability()

Fix "PHP Fatal error: Using $this when not in object context"

**math-fallback.php**

Remove redundant lines

Add title and error status to wp_die()

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Hey @RavanH -- are you able to rebase this, please?

**Comment by RavanH** [comment]
Updated my forks master branch (pull upstream) and fixed conflict in math-fallback.php now pending automated checks...

**Comment by RavanH** [comment]
... which seems to fail for some reason. No idea why :/

**Comment by RavanH** [comment]
Argh, this is horrible. Keep running around in circles hitting the same brick wall. Rebase exited with error code 128 and no helpful info.

**Comment by dereksmart** [comment]
@RavanH there is a problem with all of our tests, it is probably not related to this.  Please hold off on triggering more tests until we get it sorted.  Thanks!  

p.s. I am going to manually cancel all of your currently running tests

**Comment by RavanH** [comment]
@dereksmart OK thanks for letting me know :) I'll leave this alone for now and come back tomorrow...

**Comment by dereksmart** [comment]
Actually looks like we may have already solved it :fingers_crossed: -- waiting for the final tests but you should be coming back to green tomorrow :)

**Comment by RavanH** [comment]
@samhotchkiss should be OK now :)

**Comment by eliorivero** [comment]
@RavanH can you describe the steps to reproduce the bug?

**Comment by RavanH** [comment]
Hi @eliorivero this concerns some inconsistencies in the math fallback flow that I discovered when trying to find a way to make protect compatible with the bbPress login widget. The fix for that can be found at pull request #5647 but it does not tackle the inconsistencies. The problem is that these only appear in rare cases where the math fallback is used.

Is there an easy way to force Protect to **always** rely on the math fallback? If so, I can create some simple steps to reproduce that show the underlying issue...

**Comment by eliorivero** [comment]
@RavanH you can force math editing this file `jetpack/modules/protect.php`. Find this line
```
if ( $use_math ) {
```
and replace it with
```
if ( true ) {
```
Looking forward to the steps, thanks!

**Comment by RavanH** [comment]
Hi @eliorivero yes I did something like that already but the trouble is that that will not only force the math puzzle but defeat the fix (provided by this patch) at the same time... The patch is to prevent a second math puzzle (inserted into the login form) after having solved the stand-alone math puzzle generated by the generate_math_page method.

To be able to show the issue, I would need to make Protect choose the math fallback but for external reasons. Not always forcing it. So maybe I'll just give a long, step by stap walk-through the code where (almost) all the needed methods were already added but -- I suppose -- unintentionally made non-functional because of some changes in the init order that have occurred later.

Will come back to this...

**Comment by samhotchkiss** [comment]
Hey @RavanH -- no rush, but when you do come back to this, please ping me and I'll check it out!

**Comment by RavanH** [comment]
Hi @samhotchkiss this may not be as abandoned as it seems... There are many other issue reports that seem to be related like #5263 #5131 #5144 and #5262 but it seems to be difficult to reproduce these issues. The math fallback needs to be triggered but **not** forced.

**Comment by samhotchkiss** [comment]
Thanks, @RavanH -- I'm happy to dig on this a bit later on this week

**Comment by oskosk** [comment]
This branch needs a rebase against latest master. Do you have plans to continue working on it @RavanH ?

**Comment by RavanH** [comment]
Hi @oskosk the issue is still current so I'll have a new look at it. Problem is that it appears to be elusive and difficult to reproduce as it occurs only in very particular cases (my impression so far: when a object cache is active and then only sometimes)

**Comment by oskosk** [comment]
@RavanH thanks for replying!  I understand, but even when the problem is reported, when it comes to PRs it's hard to be sure that the changes won't affect anything else if the problem the PR is trying to solve is not reproduceable... 

PRs should have a "Testing instructions" section in the description telling someonen else how to follow a series of steps that they can reproduce. It's actually an important part for us because even when sometimes the changes in the code seem reasonable, we need to check that the proposal does what it says functionally. 

As an example, the changes of using `self` instead of `$this` are straightforward and seem to address one of the problems reported in #5646. Maybe a new PR doing just this replacement could work.

* How do you feel about closing this PR, leaving the issue in place and creating a new one tackling the part that we can reproduce?

**Comment by RavanH** [comment]
@oskosk I completely understand the need for reproduction and testing. In fact, I suspect the lack of that in the past has produced this issue. The sight on the logic behind the math fallback has been lost and it now gets triggered/called at the wrong time in the login process. Or at least in some cases it appears to fail...

I'll have to create a test setup where I can compare with/out object caching to be able to say more about reproduction. But I'm afraid I don't have huge amounts of time right now. So please be patient.

I'll consider splitting the PR in two as you suggest :)

**Comment by keoshi** [comment]
Hi @RavanH — It's been a while since this PR has been updated and I see you considered closing it and splitting it in two in December last year.

Any updates on that front, and should we keep this PR open?

Thank you!

**Comment by RavanH** [comment]
Hi @keoshi the issue is still relevant and remains unfixed. Here is a little screen cast which shows the math fallback page kicking in and then redirecting back to wp-login.php with yet another math puzzle. Note that the initial login is made from a bbPress widget which does not include a math puzzle in the first place (this is another issue) but it can also happen on the normal wp-login.php

It can happen that at first load Jetpack thinks it's not needed to add the math puwwle but at actual login the API connection fails (or something like that?) in which case the math fallback will be thrown. With the same result: passing or failing the fallback puzzle, the user will land on wp-login.php again, this time with a second math puzzle.

https://status301.net/wp-content/uploads/2018/06/Schermfilm-van-12-06-18-191954.webm

**Comment by RavanH** [comment]
@oskosk and @eliorivero this is actually why the issue is difficult to reproduce: the connection needs to work initially but fail on actual login (I suppose, not sure if that is actually what happens when this issue occurs, it's hard to figure out) ... adding `define( 'JETPACK_PROTECT__API_HOST', '' );` for example will make the API connection fail at all times, which will invoke the normal math puzzle on wp-login.php in which case the math fallback page is not invoked.

I'll have to find a way to make this rare occasion occur predictably...

**Comment by RavanH** [comment]
To compare with the screen cast above, here is the flow after applying this patch:
https://status301.net/wp-content/uploads/2018/06/Schermfilm-van-12-06-18-231024.webm

Notice that this time, after passing the math puzzle we still drop back to wp-login.php again but this time, there is no second math puzzle anymore.

When the math puzzle is failed, without this patch, the user will land on wp-login.php again (it does not matter if the puzzle was solved or not) but with this patch, the user will get the intended "Your answer was incorrect, please try again" message as can be seen here https://status301.net/wp-content/uploads/2018/06/Schermfilm-van-12-06-18-231831.webm (message in dutch, so translation works ;) )

This patch is still not ideal (it should actually pass straight to logged in status after the fallback math puzzle) but it's at least is seems to be what was intended by the math-fallback and better than having to solve two math puzzles, of which the first one may be failed or passed without any consequence.

Hope these screen casts help show the issue :)

**Comment by RavanH** [comment]
BTW, steps to reproduce the scenario from these screen casts:
1. Install Jetpack version 6.2.1, link it to WordPress.com and make sure Protect is activated (all other modules can be switched off)
2. Install bbPress with default settings and add the bbPress Login Widget to the sidebar
3. Add the line `define( 'JETPACK_PROTECT__API_HOST', '' );` to wp-config.php
4. Try to log in via the bbPress widget and NOT the wp-login.php screen because that will have the math puzzle already in place and will not invoke the math fallback stand alone page.

**Comment by brbrr** [comment]
Hi @RavanH 
I tested your change against your branch and your changes works well. Although, your branch is quite outdated - 6.3-alpha, when current stable is 6.6.1. May I ask you to rebase your changes against the latest master, so we'll be able to test it against fresh code? Thanks!

**Comment by RavanH** [comment]
Hi @brbrr yes I'll work on this for the latest release as the issue is still present. Just yesterday I ran into this on a multisite where the math fallback page came up and (as before) solving or failing the puzzle had the same effect: being redirected back to the login form, with again a math puzzle.

I just hope I can make some time for this in the coming days...

**Comment by RavanH** [comment]
Hi, unable to rebase this patch (I had removed the original fork already) I've manually ported all changes to a new fork of 6.8-alpha and created PR https://github.com/Automattic/jetpack/pull/10602 

Hope this can be looked at instead :)

**Comment by RavanH** [comment]
@brbrr Same pull request based on latest version here https://github.com/Automattic/jetpack/pull/10602 -- could you take a look?

**Pull request closed without merging**
