### PR TITLE
Add connection button to Welcome banner

### PR DESCRIPTION
**Pull request by IanRamosC**
Fixes pbNhbs-9bI-p2#comment-19686

image

## Proposed changes:

* This PR adds a button to the welcome banner in My Jetpack that links to the connection screen in case a user is not connected yet

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pbNhbs-9bI-p2#comment-19686

## Does this pull request change what data or activity we track or use?

Just another Tracks event

## Testing instructions:

* Spin up a JN site with Jetpack Beta pointing to this branch
* Without connecting to Jetpack, go to My Jetpack
* Confirm you see the Welcome banner, and that there's a button there
* When clicked, this button should trigger recordEvent (you can filter by the event name in the network tab of your browser's console), and redirect to the connection screen

### CODE REVIEW

**Review by CodeyGuyDylan — DISMISSED** [review]
Tests well, code looks good to me 😄

**Review by jboland88 — DISMISSED** [review]
Code LGTM - the banner looks to match the design.

The button looks a bit close to the text - that's the way it appears in the original @keoshi  - just mentioning this. not a blocker though

Screenshot 2024-01-05 at 3 57 14 PM

**Comment by keoshi** [comment]
Yeah, a bit too close to the text. Can we add 8 or 16px in between them?

Everything else looks perfect.

**Review by jboland88 — APPROVED** [review]
Thanks for the update, LGTM!

**Pull request merged**
