### PR TITLE
CRM: OAuth/Gmail issue stripes HTML code, including links and images

### PR DESCRIPTION
**Pull request by cleacos**
Fixes https://github.com/Automattic/zero-bs-crm/issues/3109

## Proposed changes:
This PR fixes an issue when users use the OAuth/Gmail method to send emails. It didn't send the plain/text part, so Gmail created a new one based on the HTML, which implies stripping HTML elements (i.e. links and images). But after debugging it in depth, the transfer encoding was also incorrect (`Content-Transfer-Encoding: quoted-printable`).

I added a new boundary (`Content-Type: multipart/mixed`) structure to allow attachments and plain/text content (`Content-Type: multipart/alternative`):

- multipart/mixed
   - multipart/alternative => for the plain and the HTML content
   - the attachments part

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
N/A

## Testing instructions:
- Apply this patch
- Set up an OAuth in Google and add the credentials to your testing site. If you are testing it locally, be sure you add the localhost URI, or if you use testing local domain, should be a `.com` domain (pointing to 127.0.0.1 in your hosts file). But better if you test it in an external testing site accessible because the Gmail image cache needs it to show you any image or logo.
- Configure OAuth/Gmail as email delivery system in the JPCRM Mail setting
- Create a mail campaign with MC with a small audience (less than 3 to not saturate your inbox). At least one contact email should be accessible to be able to check the email.
- Select the template with logo. Ensure you've set up one in the business information (JPCRM settings)
- Add any link
- Send the test to any valid email. You should able to see the unsubscribe link
- Send the broadcast
- Check that you receive the email, with the links you added, also you will see the company logo.
- **Bonus:** Because of I touched the email content at a low level using multiple boundaries, test this: Create an invoice and send it via email (valid email) as a PDF attachment. Check that you receive the email correctly with the attachment.

### CODE REVIEW

**Comment by gogdzl** [comment]
There is a strange bug going on. When I send a campaing all links point to the unsub link.

This is my email preview window:

image


This is what gmail is receiving in the campaing (source of the mail):

```
<body bgcolor=3D"#ffffff">
<table border=3D"0" width=3D"100%" cellspacing=3D"0" cellpadding=3D"10" bgc=
olor=3D"#ffffff">
<tbody>
<tr>
<td>
<table class=3D"content" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" a=
lign=3D"center" bgcolor=3D"#ffffff">
<tbody>
<tr>
<td id=3D"templateContainerHeader" valign=3D"top">
<p style=3D"text-align:center;margin:0;padding:0"></p>
<div class=3D"logo-wrap-100" style=3D"max-width:100px;margin-left:auto;marg=
in-right:auto"><img style=3D"max-width: 100px;" src=3D"https://assets.turbo=
logo.com/blog/pt/2019/11/19133547/gaming-logo-cover-958x575.jpg" alt=3D"MyB=
usnes Name"></div>
</td>
</tr>
<tr>
<td align=3D"center" valign=3D"top">
<table id=3D"templateContainerImageCurve" style=3D"min-height:15px" border=
=3D"0" width=3D"100%" cellspacing=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td class=3D"bodyContentImageFull" valign=3D"top">
<p style=3D"text-align:center;margin:0;padding:0"><img style=3D"display: bl=
ock;" src=3D"https://norubbish.com/wp-content/plugins/zero-bs-crm-mailcampa=
igns/i/email-templates/space-wide.jpg"></p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td align=3D"center" valign=3D"top">
<table id=3D"templateContainerMiddle" border=3D"0" width=3D"100%" cellspaci=
ng=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td class=3D"bodyContent" valign=3D"top">
<h3>Hello Mail test</h3>
<h2><strong>We&#39;re announcing something new!</strong></h2>
<p>There are lots o<a href=3D"https://norubbish.com?zlink=3DlFmk8zWdBKwgTfq=
37SF&amp;zorig=3Dk9NZJ2CSGQW91UZW7xd">f ways of saying it, but this email t=
emplate lets you announce something</a> new. This is great for a new produc=
t update or service offering.<br><br>You can edit this to cont<a href=3D"ht=
tps://norubbish.com?zlink=3DVp9yYhDXS8TYSDeqmvB&amp;zorig=3Dk9NZJ2CSGQW91UZ=
W7xd">ain any tex</a>t you want to let your customers know about, simply cl=
ick into the editor and type out your new announcement here!</p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td align=3D"center" valign=3D"top">
<table id=3D"templateContainerMiddle" border=3D"0" width=3D"100%" cellspaci=
ng=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td class=3D"bodyContentCenter" valign=3D"top"><a><strong>View New Product<=
/strong></a></td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td align=3D"center" valign=3D"top">
<table id=3D"templateContainerMiddleBtm" border=3D"0" width=3D"100%" cellsp=
acing=3D"0" cellpadding=3D"0">
<tbody>
<tr align=3D"top">
<td class=3D"bodyContentImage" valign=3D"top">
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td style=3D"margin:0;padding-top:10px;line-height:1" align=3D"left" valign=
=3D"top">
<h4><strong>John Doe</strong></h4>
<h5>MyBusnes Name</h5>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td id=3D"bodyCellFooter" class=3D"unSubContent" align=3D"center" valign=3D=
"top">
<table id=3D"templateContainerFooter" border=3D"0" width=3D"100%" cellspaci=
ng=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td valign=3D"top" width=3D"100%">
<p style=3D"text-align:center"></p>
<div class=3D"logo-wrap" style=3D"max-width:60px;margin-left:auto;margin-ri=
ght:auto"><img style=3D"max-width: 100px;" src=3D"https://assets.turbologo.=
com/blog/pt/2019/11/19133547/gaming-logo-cover-958x575.jpg" alt=3D"MyBusnes=
 Name"></div>
<h6 style=3D"text-align:center;margin-top:9px">MyBusnes Name</h6>
<h6 style=3D"text-align:center">##BIZ-CONTACT##</h6>
<h6 style=3D"text-align:center;margin-top:7px">Click to unsubscribe: <a hre=
f=3D"https://norubbish.com/unsubscribe/?zleave=3Dk9NZJ2CSGQW91UZW7xd">Unsub=
scribe</a></h6>
<h6 style=3D"text-align:center;margin-top:7px">---</h6>
<h6 style=3D"text-align:center;margin-top:7px"></h6>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<img alt=3D"" src=3D"https://norubbish.com?zpix=3Dk9NZJ2CSGQW91UZW7xd" widt=
h=3D"1" height=3D"1" border=3D"0"></body>
```

This should be pointing to `http://www.google.com`:

```
There are lots o<a href=3D"https://norubbish.com?zlink=3DlFmk8zWdBKwgTfq=
37SF&amp;zorig=3Dk9NZJ2CSGQW91UZW7xd">f ways of saying it, but this email t=
emplate lets you announce something</a> new.
```

**Comment by cleacos** [comment]
@gogdzl  That is expected. Those links are for tracking clicks, so when you click on it, they will be registered/tracked by the site, and then, it will redirect you to the final URL.

**Comment by cleacos** [comment]
I added to the description a new test case, an email with attachments (i.e. invoice). Be sure you've selected the Gmail method as the default delivery system.

**Review by gogdzl — DISMISSED** [review]
It works, even with attachments!
Good job!

**Review by gogdzl — APPROVED** [review]

**Pull request merged**
