### PR TITLE
Simple payments: add Gutenberg block

### PR DESCRIPTION
**Pull request by vindl**
Experimental branch that aims to create a Gutenberg block for Simple payments.

### Testing instructions

- test with `add/expose-react-create-class` Gutenberg branch.
- `yarn build` or `gulp gutenpack`.
- `yarn watch` or `gulp gutenpack:watch`.

### Visual changes

- Block selection

- Block edit view

blockexample

### CODE REVIEW

**Comment by jeherve** [comment]
For reference, my comment here probably also applies to this PR:
https://github.com/Automattic/jetpack/pull/8071#issuecomment-340425278

It would be great if we could know if Simple Payments is now going to be a free feature, or if it's okay to have it be pay-gated in wp-admin.

**Review by jeherve — COMMENTED** [review]
For reference, my comment here probably also applies to this PR:
https://github.com/Automattic/jetpack/pull/8071#issuecomment-340425278

It would be great if we could know if Simple Payments is now going to be a free feature, or if it's okay to have it be pay-gated in wp-admin.

**Comment by jeherve** [comment]
That sounds like a valid option. We would just have to make sure we warn the user properly when they don't have a plan. We don't want to create too much confusion. :)

**Comment by jasmussen** [comment]
Excited about this block. Anything I can do to help?

**Comment by zinigor** [comment]
This PR looks to be conflicting with the `yarn.lock` file we have in `master`. If you're not modifying `package.json`, you don't need to include `yarn.lock` changes into the PR. You can safely remove these changes to avoid conflicts.

**Comment by lamosty** [comment]
> Excited about this block. Anything I can do to help?

Heh, thanks for reviving this almost forgotten PR. 😆 

I think there is still quite a lot of work on the backend to figure out regarding the payments. Or maybe not a lot but a few days at least. I remember we had problems getting the payment button to actually work when you click on Pay and are probably missing some code.

I don't think I'll be able to work on it but I got an idea: we (@jsnajdr @apeatling and some guests) are having a team meetup early in March. It's possible we could get it working there. What do you think @apeatling?

**Comment by vindl** [comment]
IIRC this was mostly experimental in a period when Gutenberg wasn't supporting global blocks. I think that now some of our functionality could be replaced to leverage global blocks instead.

**Comment by jasmussen** [comment]
> Heh, thanks for reviving this almost forgotten PR. 😆

My pleasure!

To respond to both you and @vindl — Gutenberg is on the near horizon, and the Simple Payments button is a great tool. It would be very good to have this supported as a first class citizen in Gutenberg, from the start, no matter the team working on ti. It does sounds like a great meetup project to me too.

**Comment by lamosty** [comment]
> It does sounds like a great meetup project to me too.

Great. I'll try to push for it. :)

**Comment by iamtakashi** [comment]
Please take a look at the meetup project post. There is an updated design from @jasmussen.

**Comment by vindl** [comment]
Closing this one out for now. We might tackle this as part of our upcoming Simple payment improvements, in which case I'll reopen the PR.

**Pull request closed without merging**
