### PR TITLE
My Jetpack: fix stories of Interstitial Pages

### PR DESCRIPTION
**Pull request by retrofox**
Fixes #

#### Changes proposed in this Pull Request:

* My Jetpack: fix stories of Interstitial Pages

#### Testing instructions:

* Test with the Storybook

```
cd jetpack/projects/js-packages/storybook/
```

```
pnpm install & pnpm storybook:dev
```

Open a tab with `http://localhost:50240/`

* Confirm that Interstitial pages work (almost) as expected.
Known issues:
* Sometimes you need to change the Interstitial page in order to populate the mock data
* Prices are not properly mocked.
image

### CODE REVIEW

**Comment by oskosk** [comment]
Testing, but what's happening with the button color in those screenshots?

**Comment by retrofox** [comment]
> Testing, but what's happening with the button color in those screenshots?

Not sure but I think it's part of another issue

**Comment by oskosk** [comment]
Looks a bit fixed but  Default, Backup and Scan look like this

image

and Anti-spam likes this

image

**Comment by retrofox** [comment]
image

This is the primary issue to fix now.
I'm already working on these issues but in a follow-up PRs.

**Comment by oskosk** [comment]
ah alright then!

**Review by oskosk — APPROVED** [review]
Works as expected!

**Comment by retrofox** [comment]
Thanks, Osk 👍

**Pull request merged**
