### PR TITLE
Contact Form: Update/contact form allow layout blocks

### LINKED ISSUE #25123: Enhancement: Allow Group, Row, Stack, Columns, etc. in Form block
### Impacted plugin

Jetpack

### What

Allow layout blocks such as Group, Row, Stack, Columns, etc. as children in the Form block

### How

It's difficult to build something like this in a block theme using Jetpack's Form block, as you cannot group the Form fields (Date, Text, Select, etc.) into a Row block to have them arranged horizontally. 

Screen Shot 2022-07-19 at 14 01 01

You can use Field Width to have up to four items arranged horizontally, but this is obviously pretty limited compared to the layouts you can build using native layout blocks which are only getting more powerful with each Gutenberg release.

Screen Shot 2022-07-19 at 14 18 30

Ideally Form should not be so restrictive about what children it contain. In my mind Form should be analogous to `<form>` and allow _any_ block as a child **plus** additional Form field blocks.

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #25123

#### Changes proposed in this Pull Request:
* Updates the Form block to allow the following blocks as child blocks: `Columns`, `Row`, `Stack`, and `Group`.
* All the Form child blocks should still exist as standalone blocks. By adding one of the child blocks, a Form block should be added to wrap the child block, along with a submit button.
* If nested in any level inside a Form block, the child block should be added without any wrapper.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Create a Post/Page and add a Form block
* Select a variation and play with the block to confirm if the blocks described above are now available as child blocks
* Add some child blocks inside the layout blocks and check if they work as expected
* Outside the Form block, add some child blocks and check if they will be added wrapped by the Form block

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
João, nice job!!! 😍 

Technically all blocks work for me, data seems to be sent, even in weird nested structures. Looks good!

Two things though we might consider to optimize:

#### Form Field Widths inside of Row, Stack, Group 

If I added form fields inside of Row, Stack, and Group then the width of the form fields seems to be "fixed" with a randow width… meaning as a user you feel the urge that you want to make the fields a bit wider, but there is no way to change them.
The field width feature in the settings sidebar seems not to impact the width in this cases. 
I am wondering if we could make these work?

image


#### Block Library Filtering when Column, Row, Stack, Group is selected

The moment you select a block inside of the form wrapper, that is though not a “form-related block”, like for example a group block, then the library shows you ALL the blocks, not just the blocks that should be whitelisted for the form wrapper. 

This means relevant form blocks are hidden down at the bottom ... and and more importantly, blocks are shown that are not relevant for a form block, like “Post Author” or “Query Loop” etc… basically, all blocks seem to be available. See video.

Any chance to filter the library similar to what we do for form-related blocks? 


https://user-images.githubusercontent.com/5120357/202731319-3a562934-e0c8-4fab-84be-df1233a06051.mov

**Comment by jcheringer** [comment]
Hey Thomas, thanks for testing it!

> Form Field Widths inside of Row, Stack, Group

This is a bit tricky. Since the child block width is defined using the `flex-basis` CSS property, the block must be inside a Flex container for the width to work.
Adding the `display: flex` to the layout blocks caused some weird behavior. So, I kept it simple and ignored the `width` property inside the layout blocks.
We might be able to fix this, but it should require more time. I'd suggest handling this in another issue.

> Block Library Filtering when Column, Row, Stack, Group is selected

From my experience with Gutenberg, I'd say that's not possible, but I'm not a Gutenberg expert. I haven't seen this behavior in other blocks.
We could also create a new issue for another developer to investigate.

**Review by digitalwaveride — APPROVED** [review]
👍 

Yes, let's create two new issues to optimize the discussed topics above in separate PRs.

**Review by coder-karen — APPROVED** [review]
Looks good!

**Pull request merged**
