### PR TITLE
WCAG: Add alt if not set, but there is a title attribute.  

### LINKED ISSUE #2679: WCAG: Remove 'Tiled Gallery' image title attribute if the alt attribute is empty
As per http://www.w3.org/TR/WCAG20-TECHS/H67.html the title attribute should be absent if the image has no alt attribute to ensure that screen readers can ignore the image(s).

Issue raised when using Total Validator Pro during local development. My PR successfully resolves the issue and ensures the markup passes validation.

### PR DESCRIPTION
**Pull request by dereksmart**
replaces #2680 with a solution that will add an `alt` to the element if there is a title, but not an alt.  This is preferred to the prior fix that would delete the title if no alt found.  

fixes #2679

### CODE REVIEW

**Comment by dereksmart** [comment]
LGTSam

**Comment by samhotchkiss** [comment]
^that's a fact

**Comment by odie2** [comment]
It **have to** be _immediately_ reverted!

**First reason**:
Most of images are `P1040480.jpg` and `DSC06635.jpg`, so what sense makes to set `alt="DSC06635.jpg"` to make noise for screen readers?
In most of galleries (like my - even up to 200 random photos of past event) if Editor doesn't described photos, it's better to leave empty `alt` tag (as was before) as system can't provide any alternative info if human didn't provided it.
> Some images, such as invisible pixels or images used in toolbars, are used solely for layout purposes and provide no content. The ALT tag for these images should be blank ( <alt= "" >) so that screen readers will ignore them altogether.
> http://accessibility.psu.edu/images/imageshtml/ (header 2: "Alt Text for Filler or Decorative Images")

**Second reason**:
> If a text description is already provided for an image within the main text of the page, then the ALT tag can just provide a summary of the image, not a full description.
> http://accessibility.psu.edu/images/imageshtml/ (header 2: "Summary Alt Text")

Currently having a `title` set and no `alt` set gives cloned text:
`<div class="tiled-gallery-item">My title</div>`

This commit will mess in whoooole search engines indexes of tiled galleries, will annoying screen reader's users... I am luckily, that I readed changelog before updating as I am participate in WCAG competition for my country...

**Comment by jeherve** [comment]
@odie2 Let's have this discussion in the original issue, #2679. Feel free to share your opinion there!

**Pull request merged**
