### PR TITLE
Update notice styles to match Calypso

### LINKED ISSUE #8920: Notices are still using the old style
The notices that we display in Jetpack are still using Calypso's previous visual style, they should be updated:

screen shot 2018-02-22 at 6 32 22 pm
screen shot 2018-02-22 at 6 32 24 pm

vs

screen shot 2018-02-23 at 8 06 19 am
screen shot 2018-02-23 at 8 06 40 am

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #8920 

**To test:** 
Notices should look like this now: 

- Regular notices
screen shot 2018-03-19 at 2 18 19 pm

- Global notices: 
screen shot 2018-03-19 at 2 25 04 pm

- Compact
screen shot 2018-03-19 at 2 28 35 pm

### CODE REVIEW

**Comment by bsessions85** [comment]
I tested this in a few different browsers and it looks good, but I was wondering why some links are underlined and some are not. In this image there are links in all the notices, but some have the underline and some don't. I personally think it looks better without the underline, but we should at least have consistency.
image

**Comment by simison** [comment]
Noting that this is an accessibility improvement because new notification colours follow WCAG AA guidelines for contrast ratio. :tada:

PR in Calypso: https://github.com/Automattic/wp-calypso/pull/17796

**Comment by simison** [comment]
PR in Calypso to bring backups notice in-line with these: https://github.com/Automattic/wp-calypso/pull/23487

**Comment by rickybanister** [comment]
These look great @dereksmart thanks for getting this done.

**Comment by dereksmart** [comment]
@bsessions85 agreed.  Pushed an update 

https://cloudup.com/cb9c4MAl7rx

**Pull request merged**
