### PR TITLE
Contact Form: Front-end notification for post_author if invalid emails

### PR DESCRIPTION
**Pull request by dereksmart**
Any time the contact form shortcode is parsed, this checks if there's invalid emails set for submission notifications and will show a message to the post author informing them.  

enhances #1619 for issue #1610

### CODE REVIEW

**Comment by dereksmart** [comment]
The inline css is meant to be moved to the stylesheet if this is merged.

**Comment by georgestephanis** [comment]
The only notification I was thinking was an alert to the author when writing the post -- a page alert on the wp-admin/edit.php screen.

This seems like overkill, and could potentially cause more confusion.

**Comment by dereksmart** [comment]
Fair enough.  Should we then ignore instances when the shortcodes are used in places other than wp-admin/edit.php?

**Comment by georgestephanis** [comment]
The shortcodes don't work if used via `do_shortcode()` -- the only other place it could happen is in text widgets -- which I'm okay not showing the error message for.

**Comment by dereksmart** [comment]
Closing in favor of #1635

**Pull request closed without merging**
