### PR TITLE
Jetpack: Check $submenu is not NULL before adding Scan option

### LINKED ISSUE #39423: Fatal error when $submenu is NULL for cetain user roles
### Impacted plugin

Jetpack, ~CRM~
Initially reported for a CRM user, but this seems to happen for other sites without Jetpack CRM.

It could be related to users using SSO but needs more debugging.

### Quick summary

This error is happening for users with the role `zerobs_admin` (aka as `Jetpack CRM Admin (Full CRM Permissions)`), but I suspect it could happen to other custom user roles as well.

**The error**
> PHP Fatal error: Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, null given in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php:333
Stack trace:
#0 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php(333): array_column(NULL, 3)
#1 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-admin-menu.php(40): Automattic\Jetpack\Masterbar\Atomic_Admin_Menu->add_jetpack_menu()
#2 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php(76): Automattic\Jetpack\Masterbar\Admin_Menu->reregister_menu_items()
#3 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Masterbar\Atomic_Admin_Menu->reregister_menu_items('')
#4 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/core/6.6.2/wp-admin/includes/menu.php(161): do_action('admin_menu', '')
#7 /wordpress/core/6.6.2/wp-admin/menu.php(412): require_once('/wordpress/core...')
#8 /wordpress/core/6.6.2/wp-admin/admin.php(158): require('/wordpress/core...')
#9 /wordpress/core/6.6.2/wp-admin/index.php(10): require_once('/wordpress/core...')
#10 {main}
thrown in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php on line 333

This is happening for all Jetpack CRM Admin users that login via SSO.

The bug was added [back in March](https://github.com/Automattic/jetpack/pull/37459/files#diff-49661f625194f9a0604aecd4f8723215bdf82e9d63d7cbfefbbf977a90bebe5c), when adding the `Scan` option to the Jetpack submenu:

**Potential fix**
Here's a potential fix to the problem: [Pull Request #39424](https://github.com/Automattic/jetpack/pull/39424) 

### Steps to reproduce

Team 51 can provide you access to the error logs on one of our partner's sites.

1. Login to the site as an Admin
2. Create a user with the role Jetpack CRM Admin
3. On another browser, try to login with this new user using SSO
4. The new user is unable to login, and sees: _There has been a critical error on this website. Please check your site admin email inbox for instructions._

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by ecairol**
Fixes https://github.com/Automattic/jetpack/issues/39423

## Proposed changes:

* There might be some cases where `$submenu` is empty. It is happening for sites with Jetpack CRM that have users with the role "Jetpack CRM Admin" and login using SSO.
* The Fatal error happens when the Scan option is added to the submenu
* I suspect the error could happen for other custom user roles as well

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
TBD

### CODE REVIEW

**Comment by ecairol** [comment]
cc @vykes-mac since you're most likely familiar with the changes. Let me know if you have any thoughts or feedback.

**Comment by vykes-mac** [comment]
> cc @vykes-mac since you're most likely familiar with the changes. Let me know if you have any thoughts or feedback.

@ecairol Thanks for the ping. Based on the described issue this guard check looks reasonable.

**Comment by bryanwmiller** [comment]
@vykes-mac - Hello! We have a team51 partner who is waiting on this fix. Just so we know how to proceed with that particular site - would this patch just be added to the next release, or would it be sooner? I know it is an edge case (so not an urgent issue), but we want to know whether we should just patch it locally on this particular site until the next release. Thank you!

**Comment by vykes-mac** [comment]
> @vykes-mac - Hello! We have a team51 partner who is waiting on this fix. Just so we know how to proceed with that particular site - would this patch just be added to the next release, or would it be sooner? I know it is an edge case (so not an urgent issue), but we want to know whether we should just patch it locally on this particular site until the next release. Thank you!

I think it's okay to apply the patch on your end while waiting for the next jetpack release.

**Comment by mmtr** [comment]
Pushed an update to add the required changelog, so we can merge this.

**Comment by mmtr** [comment]
Also verified this PR indeed fixes the issue after following these steps:

- Install the Jetpack CRM plugin on Atomic site
- Go to `/wp-admin/user-new.php`
- Create a user with the role Jetpack CRM Admin, and invite it to WordPress.com
- On another browser, accept the invitation
- Go to `/wp-admin`
- ❌ There is a critical error

Screenshot 2024-10-01 at 16 10 23


- Install the Jetpack Beta plugin and switch to the branch of this PR
- ✅ The error is gone

Screenshot 2024-10-01 at 16 12 23

**Pull request merged**
