### PR TITLE
Jetpack Boost: Handle zero dimensions in getOversizedRatio

### LINKED ISSUE #32037: Boost: Image Guide (free) showing up on adminbar avatar
### Impacted plugin

Boost

### Quick summary

CleanShot 2023-07-24 at 18 08 22@2x

### Steps to reproduce

1. Setup latest (2.0.0) Boost;
2. Enable Image Guide;
3. Check any page in the front-end.

### A clear and concise description of what you expected to happen.

Bubble shouldn't show up for avatars.

### What actually happened

_No response_

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pyronaur**
Fixes #32037

## Proposed changes:
- Added comments to clarify why we return 1 when either dimension of the image is 0 in getOversizedRatio function
- Clarified why we only initialize the image guide after the window has loaded in a comment

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
N/A

## Testing instructions:
- Load an image with 0 width or height and ensure the oversized ratio returned is 1
- Check the guide doesn't initialize in an iframe
- Load a page where the image guide is expected, ensure it doesn't initialize until the window is fully loaded

### CODE REVIEW

**Review by haqadn — DISMISSED** [review]
👍🏼

**Review by haqadn — DISMISSED** [review]
Re ✅

**Review by haqadn — DISMISSED** [review]
Re-re ✅

**Review by dilirity — APPROVED** [review]
:shipit:

**Pull request merged**
