### PR TITLE
Subscribe block: Add sync between button background color and border color

### PR DESCRIPTION
**Pull request by ivan-ottinger**
The proposed changes provide an _automatic border color change_ when the user changes the _button background color_.

Screen recording displaying the proposed changes in action:

https://user-images.githubusercontent.com/25105483/154711704-c3408e4d-f54f-4470-8ffd-06e951a45ead.mp4

#### Changes proposed in this Pull Request:

The PR introduces new `useEffect()` that automatically sets the `borderColor` to the currently set `buttonBackgroundColor`.

The `borderColor` is set automatically if and only if the `borderColor` holds the same color as the `buttonBackgroundColor` (including a case when the colors haven't been set yet; for instance when the block is added to the page). The condition also makes sure that if the user already set a custom color for their border manually, it won't get overridden.

#### Jetpack product discussion
- p1645093761706199/1645006316.158349-slack-C02TCEHP3HA

#### Does this pull request change what data or activity we track or use?
No, it does not.

#### Testing instructions:
1. Add the Subscribe block to a post or a page
2. Adjust its Button Background Color and Border Color settings
3. If both colors are the same, changing the Button Background Color should automatically change the Border Color - as can be seen in the screen recording above

### CODE REVIEW

**Comment by yansern** [comment]
In general, the code works and the automation is nice, but it raises some questions:

1. User sets background color and the border color changes. Could this be seen as unexpected behavior by the user?
https://user-images.githubusercontent.com/1287077/155081308-111b2118-1772-42e8-ac3d-29aaf1d933b0.mp4

2. After that, the user decides that the background color should be different from the border color, but the user could not do that, because it changes the border color.
https://user-images.githubusercontent.com/1287077/155081591-4d28914a-1013-41e6-91e3-903edf4cd6ba.mp4

**Comment by yansern** [comment]
Just another test on setting custom border color & custom background color. This is OK.
https://user-images.githubusercontent.com/1287077/155082628-651d9413-c05f-49fc-8873-099a0d9f0369.mp4

.

**Comment by ivan-ottinger** [comment]
> 2. After that, the user decides that the background color should be different from the border color, but the user could not do that, because it changes the border color.
https://user-images.githubusercontent.com/1287077/155081591-4d28914a-1013-41e6-91e3-903edf4cd6ba.mp4

> Just another test on setting custom border color & custom background color. This is OK.
https://user-images.githubusercontent.com/1287077/155082628-651d9413-c05f-49fc-8873-099a0d9f0369.mp4

Yes, that's right. The idea is to automate the border color change only if the colors are the same. If the user changes the border color to some other color than the current background color, the color sync "is disabled" and additional changes to the background color won't affect the set border color.

This way, the user won't lose their custom border color.

---

At the same time there's the case you shared in your screen recording: https://user-images.githubusercontent.com/1287077/155081591-4d28914a-1013-41e6-91e3-903edf4cd6ba.mp4. Thank you for catching that, Yan!

When both colors are the same and the user wants to keep the border color and change only the background color, they would need to remember that border color - as if they switch the backgroud color to something else, the border color will be changed as well (as both colors were the same and color sync is "enabled").

Here's the conversation where Matiás shared the intended behavior: https://href.li/?p1645093761706199/1645006316.158349-slack-C02TCEHP3HA.

The question is now what is better from the user's perspective. 🤔

**Review by yansern — APPROVED** [review]
Although I have a small usability concern (over the steps needed to unsync background color with the border color to change just background colour), this PR does what it says, which is: 

Setting background color automatically sets border color:
  - when the border color is unset **OR**
  - when the border color is the same color as the background color 
 
I'll approve this, and will leave this for the 2nd round of review.

**Review by jeherve — APPROVED** [review]

**Comment by ivan-ottinger** [comment]
Successfully deployed to WPCOM. Changeset: r240597-wpcom.

**Comment by mtias** [comment]
Thanks for working on this! We can always revise the logic but I think it covers the most common expectation of wanting background to also affect the border color.

Maybe in the future we can pair this with whether compact or split is being used, though that could add another layer of hidden UX.

**Pull request merged**
