### PR TITLE
Remove/earn from wpteams

### PR DESCRIPTION
**Pull request by chrismccluskey**
Fixes 141-gh-automattic/gold

## Proposed changes:

* Removed the paywall feature for P2 blogs.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* First, let's recreate the issue. Do this by opening a new post on a P2 blog. The issue is that you can select the paywall block.
* To fix the issue and test this patch, download it to your sandbox and repeat the first step. You should no longer be able to select the paywall block.

### CODE REVIEW

**Comment by jeherve** [comment]
I see we had done that for Subscriptions as well, in #31374. I wonder if it wouldn't be best to keep that logic separated, and have a compatibility file on the p2 side, where we decide where we want to unregister some blocks. This way, we would also be able to do that without making any changes in Jetpack. It would look something like this:

```php
/**
 * Get rid of blocks we do not want.
 *
 * @param array $extensions List of available extensions.
 */
add_filter(
	'jetpack_set_available_extensions',
	function ( $extensions ) {
		$extensions = array_filter(
			$extensions,
			function ( $extension ) {
				return $extension !== 'subscriptions' && $extension !== 'paywall';
			}
		);
		return $extensions;
	}
);
```

What do you think?

**Comment by chrismccluskey** [comment]
> What do you think?

Hello @jeherve! I didn't see your message before I pushed 2bf4e81. I think that's a much cleaner approach. I'll refactor and use that approach instead. Thanks!

**Comment by chrismccluskey** [comment]
It looks like this PR isn't needed.

**Comment by millerf** [comment]
> It looks like this PR isn't needed.

~@chrismccluskey What do you mean?~

Just saw https://github.com/Automattic/gold/issues/141#issuecomment-1716705886 👍

**Pull request closed without merging**
