### PR TITLE
Only disable Related Posts if it's possible to re-enable it

### LINKED ISSUE #6323: Related Posts is permanently disabled if you edit settings via Customizer
#### Steps to reproduce the issue

1. On a fresh install (or with freshly-deleted jetpack_relatedposts options), enable the Related Posts module
2. Go into the customizer and edit Related Posts settings (e.g. disable show date)
3. Save

#### What I expected

Date is hidden

#### What happened instead

Related Posts is permanently disabled and there's no way to re-enable it!

#### Suggested solution

If we haven't enabled the UI which shows the "toggle" option for whether RP's are enabled, they should ALWAYS BE ENABLED since otherwise there's no way to switch them on. 

Right now the only workaround is for users to implement something like this in an mu-plugin:

```php
<?php

add_filter( 'jetpack_relatedposts_filter_allow_feature_toggle', 'enable_rp_feature_toggle' );

function enable_rp_feature_toggle( $val ) {
	return true;
}
```

and then manually re-enable RP's in the Reader settings every time they change a setting.

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes #6323

#### Changes proposed in this Pull Request:

* Only respect "enabled" flag of `jetpack_relatedposts` option if the ability to actually change it is enabled.

#### Testing instructions:

* On a fresh install (or with freshly-deleted jetpack_relatedposts options), enable the Related Posts module
* Go into the customizer and edit Related Posts settings (e.g. disable show date)
* Save
* This will trigger a bug which disables Related Posts
* However, they should still appear since the "toggle UI" is not enabled via the `jetpack_relatedposts_filter_allow_feature_toggle` filter

#### Proposed changelog entry for your changes:

Always enables Related Posts unless disabled by filter or toggle UI is enabled.

### CODE REVIEW

**Comment by eliorivero** [comment]
I've pushed a commit that will set `enabled` item of `jetpack_relatedposts` option to true if it wasn't passed in the saving request. This solves the issue where the Customizer won't pass `enabled` when `jetpack_relatedposts` doesn't exist.

**Comment by dereksmart** [comment]
This seems to be working for the customizer view, as I can see related posts when customizing.  But after I save, RP still acts as inactive, as in I can't see them on the front end of my site when viewing a single post.  

Also when I refresh the customizer page after saving, whatever value I saved does not update properly.  For example, uncheck `show date`, save, and on refresh the box will still be checked.

**Comment by eliorivero** [comment]
Thanks @dereksmart for the review.

I've updated this PR to set `enabled` to true if one of the Customizer options is being saved. Note that this is not a departure of the previous logic because previously to introduce RP into Customizer, if `enabled` was false, the other options were cleared: their value was not kept. So if user is going to save one value, it's necessarily because `enabled` is true. This updates solves the issue noticed by @dereksmart for users that have already run into the issue.

I've also introduced tests to ensure the integrity of the option.

**Comment by gravityrail** [comment]
LGTM!

**Pull request merged**
