### PR TITLE
External Media / AI Image Generator: update button style

### PR DESCRIPTION
**Pull request by jeherve**
See #39934

## Proposed changes:

Let's change the overall styles of the 2 buttons ("Select Image" and "Generate with AI"):

- the buttons should be 40px high, like in Core. See https://github.com/WordPress/gutenberg/issues/46741
- the buttons should use the secondary style variant by default, to match the "Insert from URL" button.
- the buttons should take the full width of the placeholder on mobile devices.

| Desktop | Mobile |
|--------|--------|
| Screenshot 2024-10-31 at 13 14 41 | Screenshot 2024-10-31 at 13 13 30 |

> [!WARNING]
> This PR only addresses the design issues outlined in the comments of #39934. It does not remove or make any changes to the duplicate "Generate with AI" button or the "Select Image" button, as we discussed in #39934 and #39933. This is something we can do in a follow-up PR, after more discussion if necessary.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

See conversation in #39934

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

> [!NOTE]
> This needs to be tested in different enviroments:
> - With the latest version of the Gutenberg plugin and the latest version of WordPress, like on WoA on WordPress.com Simple
> - On a site using the latest version of WordPress, but not the Gutenberg plugin.
> - On a site using WordPress 6.5.

1. Start by connecting your site to your WordPress.com account
2. Go to Posts > Add New
3. Add an Image block
4. View the different options, both on desktop and on mobile.

Once you've done this, you will also want to test the other blocks using the External Media option:

- Core Gallery block
- Tiled Gallery block
- Slideshow block

image

### CODE REVIEW

**Review by keoshi — CHANGES_REQUESTED** [review]
Thanks for spinning this up so quickly, @jeherve! Appreciate you.

#### Styling

- ✅ With Gutenberg, all buttons look great.
- 🟠 Without Gutenberg, I see the 40px height is being forced, but all other buttons are 36px tall.

Not sure what's the best way to handle this difference; cc'ing @jasmussen for guidance.

With Gutenberg | Without Gutenberg
--|--
image | image

image


#### Spacing

- ✅ All good here!

#### Breakpoints

- 🟠 Still seeing the buttons next to each other when the image block is included in a narrower parent element (e.g.: columns).

This one is not strictly about media queries and screen sizes, unfortunately. @jasmussen Can you please let us know what's the canonical way Core handles this? Are you using container queries or something else? Thanks in advance.

image

**Comment by jasmussen** [comment]
> Without Gutenberg, I see the 40px height is being forced, but all other buttons are 36px tall.

Good point. This is going to be addressed in 6.7, releasing Nov 12th. Whether you want to omit those height changes until then, or do something else in the mean-time, not sure what's best.

For what it's worth, it's been a mistake to introduce that height prop the way it was done, this has been acknowledged in the main issues. It was just a height change and should not have been opt-in.

**Comment by jasmussen** [comment]
> Still seeing the buttons next to each other when the image block is included in a narrower parent element (e.g.: columns).

@jeherve this can be solved if you include both `.is-small` and `.is-medium` in the responsive rules that stack the buttons. Though in 6.7, on the smallest state, the placeholder isn't even shown at all, it will show only the "Add media" button in the block toolbar.

**Comment by keoshi** [comment]
> This one is not strictly about media queries and screen sizes, unfortunately. @jasmussen Can you please let us know what's the canonical way Core handles this? Are you using container queries or something else? Thanks in advance.

Is this handled by `.is-medium` perhaps? 🤔 

Edit: ignore my comment, [Joen responded above](https://github.com/Automattic/jetpack/pull/39985#issuecomment-2449807545).

**Comment by jasmussen** [comment]
It's a resizeObserver under the hood, that's used for the placeholder componentry. But it adds classes, is-small, is-medium, and is-large depending on the placeholder width. This mainly becomes someting to be aware of when you change the DOM of the plugin, notably the wrapper around the two buttons here looks like it caused some of the incorrect stacking.

**Comment by keoshi** [comment]
> This is going to be addressed in 6.7, releasing Nov 12th.

Thanks for the context, @jasmussen! 

@jeherve considering the next Jetpack release is happening on November 5th, I'd say we should include the 40px change. Even if it causes differences in previous versions, that's the most future-proof option.

**Comment by jeherve** [comment]
> his can be solved if you include both `.is-small` and `.is-medium` in the responsive rules that stack the buttons. 

I just pushed 64dfc80409698edad197d346926bc5614aa6a861 to attempt to address that.

> Without Gutenberg, I see the 40px height is being forced, but all other buttons are 36px tall.
> This is going to be addressed in 6.7, releasing Nov 12th. Whether you want to omit those height changes until then, or do something else in the mean-time, not sure what's best.

This is annoying since we ideally want to support both the "soon to be current" version of WordPress (6.7) as well as the previous version (6.6).

**Comment by keoshi** [comment]
> This is annoying since we ideally want to support both the "soon to be current" version of WordPress (6.7) as well as the previous version (6.6).

The way I see it we're still supporting both, only optimizing for the newer version. It's not that different from a progressive enhancement: it won't appear broken in 6.6, but will it definitely look better from 6.7 onwards.

The alternative seems to not overcorrect right now which would mean:

- Buttons won't look right with Gutenberg installed. This includes all WordPress.com sites.
- When 6.7 ships, the buttons won't look right.
- It won't be future-proof, which means we would have to push another update later on.

**Review by keoshi — DISMISSED** [review]
Looks great in my testing after the latest change! Thanks again, @jeherve 🌟

**Review by dhasilva — COMMENTED** [review]
Code looks good. TIL about `__next40pxDefaultSize`.

On a fresh JN site I get this when the sidebar is removed, under a narrow range of window widths:
image

**Comment by keoshi** [comment]
Ugh, that doesn't look great. I can also replicate and this state is visible from `571px` to `782px` while the `is-large` class is being applied.

image

@jeherve Is there any chance we can tweak the parent container `jetpack-external-media-button-wrapper` so that this doesn't happen? Not ideal, but perhaps we can adjust the media query values.

I've also tried removing the parent container altogether but in some break points it looks like this:

image

It does seem to be the cleanest, most core-native solution though.

**Comment by jasmussen** [comment]
Forgive me if this is a dumb question, but do we have to have a jetpack-external-media-button-wrapper wrapper div? Without it, I think the core styles would simply take. I wonder even if this would help address some of the styling issues?

```
.jetpack-external-media-button-wrapper {
	display: contents;
}
```

**Comment by keoshi** [comment]
Gave this another quick spin and here's where I got to:

Nov-01-2024 10-17-56

- Remove the wrapper `.jetpack-external-media-button-wrapper` and replace by a `<>` fragment. `display: contents` would also solve this neatly. Code: https://github.com/Automattic/jetpack/blob/35bd7e0fe302acdd32ef6c225687a2b5a665d0ef/projects/plugins/jetpack/extensions/shared/external-media/media-button/index.js#L51
- Remove margin from this class: https://github.com/Automattic/jetpack/blob/35bd7e0fe302acdd32ef6c225687a2b5a665d0ef/projects/plugins/jetpack/extensions/shared/external-media/editor.scss#L571

**Comment by keoshi** [comment]
@jasmussen From what I understand we don't need that wrapper. Replacing by a fragment would solve this IMO.

**Review by keoshi — DISMISSED** [review]
Looks great, ship it! Thanks again, @jeherve 🙇

**Comment by jasmussen** [comment]
Thanks for pulling together on this one 🙏

**Comment by jeherve** [comment]
I just pushed a last commit, 475b87b847cecc512195f0291778712f09dd4dd9, to ensure that the buttons will match the size of the core buttons regardless of the version of WordPress or Gutenberg in use on the site.

That's quite a bit of extra logic, but I think it's worth it considering that the image block is a popular block, and that many folks will not be running the latest and greatest version of WordPress right away.

### WordPress 6.6, no Gutenberg

**Before**

image

**After**

image

### WordPress 6.6, Gutenberg

image

**Comment by keoshi** [comment]
Excellent, @jeherve !! Thanks for going the extra mile. Again, appreciate you drive this forward!

**Review by keoshi — APPROVED** [review]
The latest changes work perfectly in my testing! 🚀

**Pull request merged**
