### PR TITLE
Boost: Fix prettier configuration and fix linting issues

### PR DESCRIPTION
**Pull request by davidlonjon**
#### Changes proposed in this Pull Request:

* Transform the `.prettierrc` config file to its JavaScript version `.prettierc.js`.
* Extend Boost `.prettierc.js` file with the prettier config from the root of the repo.
* Fix linting issues.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* Inside the boost plugin root folder run `pnpm run lint:js` and make sure linting is successful.

### CODE REVIEW

**Comment by kraftbj** [comment]
Docs confirming that the different format is fine. https://prettier.io/docs/en/configuration.html

**Review by kraftbj — DISMISSED** [review]

**Comment by kraftbj** [comment]
Pulling back on the review. There's something with the renaming of the file that isn't sticking when building the changelogger package (see the build all projects check). It's the end of my day so I don't have time at the moment to figure out why that's happening.

**Review by thingalon — APPROVED** [review]
These changes look good to me. Consider it team-approved, waiting on approval from Ground Control (as it impacts overall builds). I can't see any errors in the changelogger package build, but I really want to know more - @kraftbj if you figure out what's going on there I would love to learn more.

**Comment by davidlonjon** [comment]
Thank you @kraftbj for having fixed the `tools/prettier` bash script.

Regarding the changelogger package build, I am not sure to see where the problem is either. Could it be intermittent? Right now It seems that the checks are ok. 

I merged the latest from `master` back in this PR so solve some conflicts resolutions on `.svelte` and `*.ts` files but I don't think that would have impacted on getting green ticks on checks now.

As with Mark I am curious.

**Comment by kraftbj** [comment]
Huh, very weird. It passes the build now. I wonder if there some caching issue or I don't know. 

GH Actions had some performance issues yesterday, so I'm okay chalking this up to a bug in the mainframe.

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
