### PR TITLE
IDC: customizing button labels and support URL

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
* add `migrateButtonLabel` and `startFreshButtonLabel` customization paremeters
* add `supportURL` customization parameter to replace the default support page URL

#### Jetpack product discussion
p9dueE-3Xf-p2#comment-7066
p9dueE-3Xf-p2#comment-7067

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Update the [customization plugin](https://gist.github.com/sergeymitr/f4257d64be6282e36b877a18a30d819f).
2. Get the site into the IDC mode and go to any non-Jetpack page in the admin area.
3. The "Migrate" and "Start Fresh" buttons should display the "sample" labels.
4. Switch the browser to the offline mode. Click the "start fresh" button, the error should appear. Click "find out more" link and confirm that it leads to `jetpack.com` main page.
5. Click the "migrate" button, confirm that the "find out more" link also leads to `jetpack.com` main page.
6. Click "Stay in safe mode", click "find out more", confirm it's `jetpack.com` main page.
7. Open the customizer plugin, comment out parameters `mainBodyText` and `nonAdminBodyText`.
8. Reload the IDC screen, the main body text should have the "Learn more about safe mode" link. Confirm that it also leads to `jetpack.com` main page.
9. Log in as a non-admin, repeat the previous step.

### CODE REVIEW

**Review by kbrown9 — COMMENTED** [review]
The changes look good to me. I tested using the provided testing instructions, and almost everything went well.

I noticed that the button text from the customizer plugin doesn't render correctly, but I'm not sure of the cause yet. For example, the space between "start" and "fresh" isn't displayed:
Screen%20Shot%20on%202022-01-19%20at%2023-43-23

**Comment by sergeymitr** [comment]
Hi @htdat.
Considering the issue @kbrown9 [found](https://github.com/Automattic/jetpack/pull/22394#pullrequestreview-857698377), do we need the button label to support the tags?
The buttons are already styled, and adding `em` tags breaks that styling.

**Comment by htdat** [comment]
@sergeymitr 

> do we need the button label to support the tags?

I don't think we need that as the current style of buttons look good already. Having ability to adjust texts is sufficient.

**Comment by sergeymitr** [comment]
I removed the `em` tags from the button labels.
@kbrown9 can you please take a look, everything should be ready now.

**Review by kbrown9 — APPROVED** [review]
Everything looks good to me! I tested the support URL links on both the admin and non-admin UIs, and they worked as expected. The custom button labels also worked as expected.

**Comment by sergeymitr** [comment]
r238700-wpcom

**Pull request merged**
