### PR TITLE
Forms: Allow fields style sync

### PR DESCRIPTION
**Pull request by jcheringer**
## Proposed changes:

* Include an option in the Form fields Sidebar to allow styles synchronization between the fields

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Create a post and add a Form block
* By default, the style sync is enabled, so changing any field style should affect the other fields
* Play with the style sync option and change the fields style to check if it work as expected

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Awesome João! 😍 
Sync worked great!!!

Two little things:

#### Copy
One copy suggestion to clarify a bit what this toggle option is about:

image


#### Multiple Choice Block

There is an issue with the styling of the multiple choice block regarding border and background.
Currently I think we have border and background styling disabled for this block.

image

**Comment by jcheringer** [comment]
Thanks for testing it, @digitalwaveride!
I added the help text to the toggle and changed the Multiple/Single Choice Block styles to handle the border and background color in a better way.
Let me know if that works.

**Review by digitalwaveride — DISMISSED** [review]
Thanks João! Works for me now as expected! 👍

**Review by jeherve — APPROVED** [review]
This tests well for me on my local environment. For some reason I couldn't see the new field in a remote site of mine, but that may just be an issue specific to my site.

**Comment by liviopv** [comment]
Hi @jcheringer could this option have changed the background of existing Form input fields from transparent to a solid color?

I couldn't reproduce it on my test site, but on a customer site, there's a difference between the background color shown in the editor and the background color shown in the front end:

CleanShot 2023-03-02 at 11 52 52@2x

In the frontend, the background color of the input field in the front end is defined by:

```
.contact-form :not(.is-style-outlined):not(.is-style-animated) .grunion-field-wrap .grunion-radio-options {
    background-color: var(--jetpack--contact-form--input-background);
}
```

And `var(--jetpack--contact-form--input-background)` is set to white as a custom style added to `body`. But I couldn't a way to change this variable either. What influences this color variable?

**Comment by jcheringer** [comment]
Hey @liviopv!
We've been trying to improve the Form block a lot, especially on the styling side of things.
I can't discard a side-effect. Maybe not caused by this PR itself, but it could be one of our recent changes.
Is there a URL I can access to take a closer look?
Thanks!

**Comment by liviopv** [comment]
Thanks for looking into it @jcheringer!

You can see an example of the issue on the front page of this site https://usvaagency.com/ (bottom right) and also on this page https://usvaagency.com/2023/03/02/open-project-mobile-developer/.

Those are live pages, so if you want to take a look at the backend on a "safe" page, use this draft https://usvaagency.com/?page_id=6132 where the issue is also present.

**Comment by jcheringer** [comment]
> 

@liviopv, for a bit of context: the `--jetpack--contact-form` CSS variables are created based on some form elements styles as soon as the page loads.
Those variables are used later to style custom elements used in Forms.

I'm not sure if that was an attempt to fix the issue, but I can see this site has some custom CSS affecting the form elements: 

image

As far as I'm concerned, the custom CSS is loaded only on the live pages, that'd explain the differences we're seeing between the editor and the published page.

Removing the custom CSS, or the selectors targeting form elements should make the input fields transparent again.

**Pull request merged**
