### PR TITLE
Sync: remove product_cat from blocked taxonomies

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes https://github.com/Automattic/jetpack/issues/19524.

#### Changes proposed in this Pull Request:
Remove `product_cat` from the list of taxonomies that are not synced by Jetpack Sync.

#### Jetpack product discussion
See @gibrown's comment at pcNPJE-5Y-p2#comment-203.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Do a Full Sync of functions. 
2. Verify the taxonomy blacklist no longer contains product_cat. 
3. Create a new post linked to the taxonomy and verify the post in the cache db has it as a linked taxonomy relationship.

### CODE REVIEW

**Comment by mdbitz** [comment]
I'll have to confirm with a round of testing myself but to test you can do a Full Sync of options and then verify the taxonomy blacklist no longer contains product_cat. After that create a new post linked to the taxonomy and verify the post in the cache db has it as a linked taxonomy relationship.

**Comment by bluefuton** [comment]
Thanks @mdbitz! I've updated the testing instructions.

How do we trigger a full sync of just options?

**Comment by mdbitz** [comment]
@bluefuton Hi Chris the easiest way is to use the Jetpack Debug Tool and expand the Full Sync module. In it you can choose options from the dropdown then "Schedule Sync" to do a full sync of options.

**Review by mdbitz — APPROVED** [review]
Approved removing product_cat. As a note its is a callable not an option so Full Sync of Functions to test :)

**Pull request merged**
