### PR TITLE
Widgets: Remove Google+ Badge

### PR DESCRIPTION
**Pull request by mdawaffe**
See #10950.

#### Changes proposed in this Pull Request:
* Removes the Google+ Badge widget completely.
* Purges those widgets from all sidebars.

#### Testing instructions:
1. `git checkout 6.9`
2. Add a Google+ Widget to your sidebar. See it in your sidebar.
3. `wp option get widget_googleplus-badge`. See the widget data.
4. `git checkout remove/google-plus-widget`.
5. Reload the front page. See no Google+ Widget in your sidebar.
6. `wp option get widget_googleplus-badge`. See the option has been deleted.

#### Proposed changelog entry for your changes:
Removed Google+ Badge Widget.

### CODE REVIEW

**Comment by jeherve** [comment]
> Should we remove the widget as in this PR

I would vote for this.

> Do we need the fancy purge routines?

In #8498 we deprecated another widget (and replaced it with another one of ours). 
In #8062 and #7103 we deprecated a widget in favour of one from Core. 
Maybe we could follow the lead of those last 2 in terms of deprecation?

**Comment by mdawaffe** [comment]
> Maybe we could follow the lead of those last 2 in terms of deprecation?

Since we're not replacing it with anything, I think there's really just two options:

1. Completely remove it (as in this PR). We could tell the user what has changed or not.
2. Edit the widget to only output an error and only to admins.

I'm fine with either option. Both are easy.

Is there some consideration I'm missing?

> Do we need the fancy purge routines?

I've decided to simplify the purge. As of a7effd97d, the code only deletes the option. It doesn't bother to clean up `sidebars_widgets` since that data will sort itself out the next time a widget is added, removed, moved, etc.

**Review by jeherve — COMMENTED** [review]
I got the following notices when trying to update from stable to your branch with 2 active Google+ widgets:

```
[28-Jan-2019 14:11:57 UTC] PHP Notice:  Undefined variable: widget_base in public/wp-content/plugins/jetpack-dev/modules/widgets.php on line 93
[28-Jan-2019 14:11:57 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at public/wp-content/plugins/jetpack-dev/modules/widgets.php:93) in public/wp-content/plugins/jetpack-dev/class.jetpack.php on line 5986
```

**Comment by jeherve** [comment]
> I'm fine with either option. Both are easy.

I guess the current PR makes sense. 👍

**Comment by mdawaffe** [comment]
> I got the following notices when trying to update from stable to your branch with 2 active Google+ widgets:
> 
> ```
> [28-Jan-2019 14:11:57 UTC] PHP Notice:  Undefined variable: widget_base in public/wp-content/plugins/jetpack-dev/modules/widgets.php on line 93
> ```

Oops! Great catch, thanks! Fixed in 9ebfd374e.

**Review by dereksmart — APPROVED** [review]
+1 on current PR. The usage of this widget is very low. 

Tested a few different ways. Works as expected.

**Review by jeherve — APPROVED** [review]
Working well now! Merging.

**Pull request merged**
