### PR TITLE
Audio Player: Fix the firing of multiple conflicting time changes

### PR DESCRIPTION
**Pull request by pablinos**
It was seen that if you click around on the timeline of the audio
player, that from time to time, the click will be ignored and the audio
will jump back to the previous position.

#### Changes proposed in this Pull Request:

This change updates the options passed to `throttle` as the problem
seemed to be caused by the prop changing every second and a click
happening within the second, this led to two calls to the throttled
function, on the leading and trailing edge of the time period.

It's probably not strictly necessary, but it also cancels the throttled
function in the unmount callback of the `useEffect`.

#### Testing instructions:

* Insert a podcast block and set it up with an RSS feed.
* Set an episode playing and click around on the timeline.
* From time to time you should see that the time change event on the timeline gets ignored and it jumps back to the previous position.
* With this PR do the same, and it should fix the problem.

#### Proposed changelog entry for your changes:

N/A as this fixes a problem in code that is yet to be released.

### CODE REVIEW

**Review by retrofox — DISMISSED** [review]
Tested. LGTM. 👍

**Review by jeherve — DISMISSED** [review]

**Review by retrofox — APPROVED** [review]
LGTM

**Review by jeherve — APPROVED** [review]
Re-approving after an update to attempt to fix those tests.

**Comment by retrofox** [comment]
r219559-wpcom

**Pull request merged**
