### PR TITLE
RFC: Would anything break if we did this?

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

Change Jetpack's changelog to https://keepachangelog.com/ format.

Would anything break if we did this? Other than the fact that it would
complicate copying the changelog into readme.txt for the release.

See also p9dueE-2qL-p2.

#### Jetpack product discussion

p9dueE-2qL-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* ???

#### Proposed changelog entry for your changes:

* None needed. Heh.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
> Would anything break if we did this? Other than the fact that it would
complicate copying the changelog into readme.txt for the release.

I like the idea. It's more readable and easier to edit.

I think it would be just fine! The markdown used in there, since it's quite simple, should be parsable by the WordPress.org parser without any issues.

My only recommendation would be to make the version headings (e.g. `[9.4] - 2021-02-02`) an H3 heading, and the following headings ("Enhancements", "Bug fixes") H4 headings. 
It seems that it would fit better with [the structure on WordPress.org](https://wordpress.org/plugins/jetpack/#developers), where we currently go from an H2 for the changelog title to H4 headings below, so we would be improving things!

**Comment by anomiex** [comment]
I'd like to keep to the https://keepachangelog.com/ format for CHANGELOG.md, since it's more likely to work with other tools and more likely for our tools to be able to work for other projects. It'd be neat if other projects could just `composer require automattic/jetpack-changelogs` and have the tools to manage CHANGELOG.md. Or, for that matter, maybe there are some tools out there that we could use instead of having to write our own.

It would be an easy munge when copying to readme.txt, just `s/^#/##/` to move every heading down a level.

**Comment by jeherve** [comment]
Makes sense. To be honest, I don't think it's that big of a deal if the headings aren't perfect. They aren't right now, after all, so I think we could do even without the search and replace. :)

**Comment by kraftbj** [comment]
Not required for accepting this, but it could be a nice tool to take the "unreleased" section, add the right details, and then copy it over to the readme.txt for a plugin modified for the right formatting.

I like the idea of following conventions and sounds good to follow one that's in the broader software engr ecosystem. 👍

**Comment by anomiex** [comment]
Closing this in favor of #18945

**Pull request closed without merging**
