### PR TITLE
Fix front-end performance of Tiled Gallery block

### LINKED ISSUE #22445: Tiled Galllery Block: update Platform implementation to avoid pulling too many dependencies
This is a follow-up from #21849. 

The block update pulls `Platform`, from `@wordpress/element`. That is problematic as the whole package (and its dependencies, React, React Dom, and lodash) is then added as a dependency and then enqueued in the editor as well as on the frontend to render the gallery.

It would be nice to refactor this so we only add what we need. While we do try to use WordPress packages whenever possible, we aim to be as frugal as possible for frontend dependencies.

*******

cc @illusaen, @guarani, and @SiobhyB who worked on the original PR. Do you think you could take a look?

Thank you!

### PR DESCRIPTION
**Pull request by guarani**
https://github.com/Automattic/jetpack/issues/22445 reports a performance regression affecting page views where the Tiled Gallery is used.
This PR simply reverts the change to `tiled-gallery/layout/mosaic/resize.js` to its previous contents (prior to https://github.com/Automattic/jetpack/pull/21849) and creates a native-specific file, `resize.native.js`, containing the file's current contents.
I'm proposing leaving web-specific code in `resize.native.js` since removing it is lower priority and it wasn't immediately obvious which code to remove.

Fixes https://github.com/Automattic/jetpack/issues/22445

#### Changes proposed in this Pull Request:
* Revert Tiled Gallery's `resize.js` file to a previous version to fix a performance regression on pages using the Tiled Gallery.

#### Jetpack product discussion
The only discussion is that on the issue this PR fixes.

#### Does this pull request change what data or activity we track or use?
No, it does not.

#### Testing instructions:

TO-DO

### CODE REVIEW

**Comment by guarani** [comment]
I'm not sure how to answer the questions in the PR template:
- Does this need to be tested by beta testers?
- Which Milestone should this be added to? I'm not sure which to choose, `beta/3.1.0`, `jetpack/10.6`, etc

**Comment by sgomes** [comment]
Thank you, @guarani, this looks like a good approach! 👍 This should isolate `@wordpress/element` to the React Native build and keep it away from the web one.

That said, whether this works or not will depend on how the Jetpack build is set up, and how it treats these `.native.js` files. I'm not familiar with that, so I'll let someone from @Automattic/jetpack-crew take a look and let us know whether this will have the desired effect; that is, removing the dependency on `@wordpress/element` (aka `wp-element`) from the web build.

**Comment by sgomes** [comment]
Also, CC @jeherve, who was kind enough to file the original issue (#22445).

**Comment by guarani** [comment]
Thanks @sgomes! 

I've moved this from Draft to Ready for Review 🙇

**Comment by guarani** [comment]
I've merged the latest from `master` into this branch because I see some failed test such as:
- Build / Build all projects (pull_request): `pnpm run build-production-extensions exited with code 1`
- Jetpack Boost E2E Tests / Check if Boost E2E tests should run (pull_request: Failing at "Run pnpm install"
- etc

- 🤞 that fixes the failing CI checks.

**Comment by anomiex** [comment]
The build is failing with this error:
```
  [2:24.757] [build-production-extensions] ERROR in ./extensions/blocks/tiled-gallery/layout/mosaic/index.js 118:20-35
  [2:24.757] [build-production-extensions] export 'getColumnWidths' (imported as 'getColumnWidths') was not found in './resize' (possible exports: getGalleryRows, handleRowResize)
  [2:24.757] [build-production-extensions]  @ ./extensions/blocks/tiled-gallery/layout/index.js 16:0-30 90:69-75
  [2:24.757] [build-production-extensions]  @ ./extensions/blocks/tiled-gallery/edit.js 19:0-30 307:34-40
  [2:24.757] [build-production-extensions]  @ ./extensions/blocks/tiled-gallery/index.js 16:0-26 329:2-6
  [2:24.757] [build-production-extensions]  @ ./extensions/blocks/tiled-gallery/editor.js 5:0-35 6:21-25 6:27-35
```
This appears to be due to the fact that this PR is deleting the `getColumnWidths` function.

**Comment by SiobhyB** [comment]
@anomiex, thank you for spotting this!

We've worked around this by moving the `getColumnWidths` to `mosaic/index.js` (the place it's called) in https://github.com/Automattic/jetpack/pull/22547/commits/b66df7bcbc44318ab01aad01598b3cd09867ef33. That way, the web isn't attempting to import it (which fails, as it's only defined in `resize.native.js`).

Looking forward to hearing whether this approach seems suitable as well as any other feedback on this PR. 🙇‍♀️

**Comment by SiobhyB** [comment]
@sgomes, thanks for checking in! It's been marked as ready for review on our side, so looking forward to hearing any feedback on the code or whether this is good to go :)

**Review by sgomes — APPROVED** [review]
Thank you, @SiobhyB! While I'm not an expert here, I can confirm that this does build correctly, and that it generates a `view.assets.php` without a dependency on `wp-element` 👍

I think it's only the Crew review missing, at this point.

**Review by jeherve — APPROVED** [review]

**Comment by guarani** [comment]
> Thank you @sgomes and @jeherve! 🙇‍♀️

💯 Thanks a lot, @sgomes, @jeherve and @SiobhyB!

**Pull request merged**
