### PR TITLE
Fix style inconsistency in ActionButton when Gutenberg plugin is active

### PR DESCRIPTION
**Pull request by jboland88**
#### Changes proposed in this Pull Request:

* This PR introduces CSS changes that fix some style inconsistencies in the `<ActionButton />` component that present when the Gutenberg plugin is active.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* The best place to see the original issue is on the Jetpack connection screen. However, it only seems to show following site disconnection.
* On your test site, first test the Disconnect Flow from the master branch.
* From the Jetpack dashboard, click on "Manage site connection" to open the disconnection flow.
Screen Shot 2021-12-06 at 3 29 53 PM

* Click on "Disconnect" from the first screen.
Screen Shot 2021-12-06 at 3 30 04 PM

* On the disconnect confirmation screen in the flow, click on "No thank you" to exit the flow and return to the connection screen. 
Screen Shot 2021-12-06 at 3 30 14 PM

* Notice here that the "Set up Jetpack" button is sized incorrectly, has incorrect border radius, text is misaligned, etc.
Screen Shot 2021-12-06 at 3 38 54 PM

* Now switch to this branch on your test site. Re-connect Jetpack and follow the same steps from above to disconnect and be redirected to the connection screen.
* The "Set up Jetpack" button on the connection screen should now appear correctly styled, as seen in the screenshot below.
Screen Shot 2021-12-06 at 3 40 10 PM

### CODE REVIEW

**Comment by jboland88** [comment]
On this one, is a version bump needed? I ran the `fixup-projects-versions.sh` script, but nothing happened :)

**Comment by travisw** [comment]
I've seen this issue before when testing something. However, when I test the production build now I'm not able to reproduce it. It seems to be intermittent.
In any case, the change looks good to me.

**Review by travisw — DISMISSED** [review]

**Review by jeherve — DISMISSED** [review]

**Comment by jboland88** [comment]
@jeherve - when I ran the `tools/fixup-project-versions.sh` script on this, I noticed some changes to react dependencies in the lock file. Disabled the auto-merge for now in case this is not expected.

**Comment by jboland88** [comment]
It appears a version bump is no longer needed, reverted the lock file back to where it was in master branch.

**Review by jeherve — DISMISSED** [review]

**Comment by jboland88** [comment]
Ack. This one fell to the back of my list and it looks like I missed my opportune time to merge. :/ Caught up and updated version management. Putting back into "Needs Review" since the previous ✅  was dismissed.

Noticed again some changes to React dependency versions in the `pnpm-lock` file after running the versioning script - not sure if that's expected?

**Comment by jboland88** [comment]
> Noticed again some changes to React dependency versions in the `pnpm-lock` file after running the versioning script - not sure if that's expected?

This got fixed :)

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r236700-wpcom

**Pull request merged**
