### PR TITLE
Bump version for beta

### PR DESCRIPTION
**Pull request by samhotchkiss**

### CODE REVIEW

**Comment by zinigor** [comment]
There's something wrong with this PR, can you please rebase or cherry-pick your latest commit?

**Comment by jeherve** [comment]
Rebased, should be fine now. Should we change the base branch to the release branch whenever we create it, so only the release branch gets the Beta version?

**Comment by zinigor** [comment]
Thank you, yes, we'lll change the target once the branch is created.

**Comment by zinigor** [comment]
On second thought, I'm going to merge it into master and then we'll just overwrite the version when we branch.

**Pull request merged**
