### PR TITLE
Add/reply to newsletter behaviour setting

### PR DESCRIPTION
**Pull request by enejb**
Fixes https://github.com/Automattic/jetpack-roadmap/issues/1409

## Proposed changes:

*

Screenshot 2024-04-29 at 11 45 23 AM

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by crisbusquets** [comment]
Hi @enejb !

I tested it following the JN link, and this is what I see.

Screenshot 2024-04-23 at 08 15 09

I can't enable the `Be sent to the post author's email` option. See the video below:

https://github.com/Automattic/jetpack/assets/25607244/d970d2bc-d17c-4a92-a18a-526359da6662

### About the copy
What about: 
- Heading: `Reply-to settings`
- Paragraph: `Choose who receives emails when subscribers reply to your newsletter.`
- Answer A: `Replies are not allowed.`
- Answer B: `Replies will be sent to the post author's email.`

**Comment by lezama** [comment]
@crisbusquets @enejb updated the wording and fixed the toggle not saving

**Comment by simison** [comment]
Let's add behind a feature flag at first, so that we can merge early and keep testing/iterating easily.

@pkuliga has good examples of feature flagging on this page with the subscription block toggle PRs.

**Comment by lezama** [comment]
Server side work code-D146194

**Comment by enejb** [comment]
@crisbusquets  Thanks for the review. 

@simison  and @lezama  I created a PR - https://github.com/Automattic/jetpack/pull/37041 
that ads a custom email text field. 

I didn't push my changes to this PR mostly since I think this PR is now ready to merge. After Miguel's code-D146194 changes are shipped.

**Comment by pkuliga** [comment]
> @pkuliga has good examples of feature flagging on this page with the subscription block toggle PRs.

We could do it similar to this:
https://github.com/Automattic/jetpack/pull/36073/files

Much simpler approach 😄

**Comment by lezama** [comment]
> We could do it similar to this:
https://github.com/Automattic/jetpack/pull/36073/files

adding it now

**Comment by lezama** [comment]
Feature flag added:

to turn it on access the newsletter settings like this: https://example.jurassic.tube/wp-admin/admin.php?page=jetpack&enable-newsletter-replyto=true#/newsletter

**Review by lezama — APPROVED** [review]

**Pull request merged**
