### PR TITLE
[Package] Constants: fix tests

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

Trying to fix the following tests:

```
Error:

1) Test_Constants::test_jetpack_constants_get_constant_null_when_not_set
Mockery\Exception\InvalidCountException: Method apply_filters('jetpack_constant_default_value', NULL, 'UNDEFINED') from Mockery_0 should be called exactly 1 times but called 0 times.
test-constants.php:35

Failure:

1) Test_Constants::test_jetpack_constants_get_constant_use_filter_value
Failed asserting that null matches expected 'test value'.
test-constants.php:153
```

I've simply adjusted the `once()` call on the expectation to after the `with()`, no clue why that should make a difference from [what I see in docs](https://brain-wp.github.io/BrainMonkey/docs/functions-expect.html) 🤷 

If adjusted to `twice()` with the new ordering, I can see the tests indeed then fail and run just once (while expecting to have run twice) - so the tests appear to be working?

#### Jetpack product discussion

Internal: p1629224704045800-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Pull down changes, and open the `projects/packages/constants` dir in your terminal, then run `composer phpunit --verbose` to run the updated tests.
* Verify that all tests are passing.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Comment by jeherve** [comment]
Noting that @gravityrail took a different stab at it in https://github.com/Automattic/jetpack/pull/20718/commits/9b47cd4184766777b49f0963f741d25c69cc30a0

**Comment by samiff** [comment]
> took a different stab at it in [9b47cd4](https://github.com/Automattic/jetpack/commit/9b47cd4184766777b49f0963f741d25c69cc30a0)

Ah thanks for letting me know, using `Filters\expectApplied` is probably a better solution here, so I'll let those changes get merged.

The uses of `->andReturn` to force a certain return value seems a bit odd to me, in my mind you would always want the "real" return value when possible, but I'm unfamiliar with this testing library and maybe there is a reason for that.

**Comment by gravityrail** [comment]
@samiff I hope you don't mind, I updated this patch with my alternative fix (which you seemed to prefer) and changed other tests to be consistent with the new technique. I expect the only reason the `->never()` tests were passing is the same reason the `->once()` tests were failing - that at some point the ability to generically mock `apply_filters` went away and the `Filters\expectApplied()` test is the required approach.

**Review by gravityrail — APPROVED** [review]
LGTM!

**Review by kraftbj — APPROVED** [review]

**Comment by anomiex** [comment]
It turns out that the newly failing tests were due to a bug in patchwork 2.1.13, which I reported upstream at antecedent/patchwork#114.

But the change here is probably still a good one, may as well use brain/monkey's provided mock instead of mocking the mock.

**Pull request merged**
