### PR TITLE
Build: remove externalized dependencies from `package.json`

### PR DESCRIPTION
**Pull request by simison**
- Remove `@wordpress/*` dependencies used in blocks that are anyway externalized and we don't thus control their versions (we control WordPress core version compatibility instead).

- We still need dependencies that Jest tests for extensions depend on, so `@wordpress/element` is still there, just in `devDependencies` instead of `dependencies`.

- Move `lodash` to devDependencies as it's required for build files and externalized for production files.

- Move `react` and `react-dom` to `optionalDependencies` ([docs](https://docs.npmjs.com/files/package.json#optionaldependencies)). They are externalized as well, but many other packages depend on React being installed as peer-dependency. This will cause them get installed, but won't fail the build if for some reason they're not available. This will still work just fine since they're externalized anyway. We could very well open up their semver to more relaxed with `^`; they're here mostly to silence warnings about required peer dependencies and we're not really controlling their exact versions here.

- Left `@wordpress/browserslist-config` intact  since our build depends on it, not blocks.

Note that differences between `dependencies`/`devDependencies`/`optionalDependencies` are mostly semantic and there's no real practical difference when just running `yarn`.
 
Supersedes and closes https://github.com/Automattic/jetpack/pull/11701

### Testing

- `yarn build`
- Linters happy? Seems like importing un-installed packages in JS files doesn't yell Eslint warnings in Jetpack. That's a problem in itself, but not in scope of this PR. :-)
- Admin dash and block editor extensions still work?

### CODE REVIEW

**Comment by sirreal** [comment]
After https://github.com/Automattic/jetpack/pull/11973 we could remove all of these dependencies. Why keep them here at all?

The one exception would be `lodash` which is used in a webpack config:

https://github.com/Automattic/jetpack/blob/a96be73cc1009f4a9f42240b1609d16f6054fd43/webpack.config.extensions.js#L9

We can keep that around as loose `devDependency`. Are these used in more places?

**Comment by lezama** [comment]
12k!

**Comment by simison** [comment]
Aight, made some changes and this is good for another test & review.

_Here's for less Renovate bot PRs!_ :muscle:

**Review by ockham — APPROVED** [review]
LGTM :+1:

**Review by jeherve — APPROVED** [review]
Seems to work in my tests. 👍

**Pull request merged**
