### PR TITLE
wp-admin Site Default: Fix admin bar when notifications are disabled

### LINKED ISSUE #34685: WP classic style admin bar is broken when Jetpack “Notifications” module is off
### Impacted plugin

mu wpcom

### Quick summary

I have to use Jetpack since it's mandatory on WP.com, but I don't use any of its modules except for VaultPress, so I deactivated all of them. When I tried to change the WP admin bar to the classic one, it showed completely broken.

Later on, I found out that this happens when Jetpack “Notifications” module is off. If I turn it on, classic style admin bar shows as expected.

### Steps to reproduce

1. Open Jetpack modules page: `[site]/wp-admin/admin.php?page=jetpack_modules`.
2. Turn off “Notifications” module.
3. Go to hosting settings: `https://wordpress.com/hosting-config/[site]`.
4. Scroll to the bottom, change `Admin interface style` to “Classic style”.

### A clear and concise description of what you expected to happen.

A perfect admin bar, like this:

Captura de Tela 2023-12-17 às 08 19 43

### What actually happened

A broken one, like this:

Captura de Tela 2023-12-10 às 16 21 11

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/jetpack/issues/34685

## Proposed changes:

In this PR, I propose to fix an issue with broken admin-bar styling when the Notifications module is disabled and the Admin interface style is set to “Classic style”.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Create a WoA site
2. Go to Settings -> Hosting Configuration: https://wordpress.com/hosting-config/
3. Scroll to the bottom and change the Admin interface style to “Classic style”.
4. Open the Jetpack modules page: [site]/wp-admin/admin.php?page=jetpack_modules.
5. Turn off the “Notifications” module.
6. Confirm that top bar has broken styling
7. Open Jetpack Debug and switch to the feature branch
8. Confirm that top bar styling is fixed

### CODE REVIEW

**Comment by kozer** [comment]
I tested it and worked as expected!
| **Before** | **After** |
| :---:         |    :---:       |
|2023-12-20T14:52:01,435735136+02:00| 2023-12-20T15:12:13,620755815+02:00|

Nice work @wojtekn !

**Review by kozer — APPROVED** [review]

**Comment by danielbachhuber** [comment]
> I tested it and worked as expected!

@kozer What non-happy path scenarios did you test?

**Comment by kozer** [comment]
I didn't think of any edge cases on this one. It's either 'wp~admin' or it's not, and we remove or not the style accordingly. Did you think aof any edge case you think worth investigating more @danielbachhuber ?
I suspect that if you haven't selected the 'wp-admin' interface and disable the notification module and visit /wp-admin the effect will be the 'broken' state. However, as this code was there before and it wasn't mentioned in the testing instructions, I think this is the expected behavior ( I'm not familiar with that part of the code and the expected behavior)

**Comment by danielbachhuber** [comment]
@kozer Did you test both the on and off states?

**Comment by kozer** [comment]
Not for the default ones. However, I spent some time today to do that and to provide more screenshots:

| **Notifications on, default interface before** | **Notifications disable, default interface before** | **Notifications on, classic interface before** | **Notifications disable, classic interface before** | **Notifications on, default interface after** | **Notifications disable, default interface after** | **Notifications on, classic interface after** | **Notifications disable, classic interface after** |
| :---:         |    :---:       |    :---:       |    :---:       | :---:       | :---:       | :---:       | :---:       |
|2023-12-21T11:47:52,008297018+02:00|2023-12-21T11:48:06,957948347+02:00|2023-12-21T11:48:38,507671326+02:00|2023-12-21T11:48:54,293525256+02:00|2023-12-21T11:50:16,575587341+02:00|2023-12-21T11:50:27,028374028+02:00|2023-12-21T11:50:44,176321593+02:00|2023-12-21T11:50:57,694217031+02:00|

**Pull request merged**
