### PR TITLE
Fix the display of listing reasons for being in dev mode

### LINKED ISSUE #6847: Admin Page: display Dev mode notice on one line
> Weird blocking/alignment thing going on that I don’t think is necessary. The bulk of that message can just go on a single line.

screen-shot-2017-03-30-at-3-52-02-pm

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #6847

Fixes the awkward/broken list of reasons for being in dev mode.  This style of listing the reasons provides a readable format for when there could be multiple reasons for dev mode.  For example: 

screen shot 2017-03-31 at 1 46 28 pm

### CODE REVIEW

**Comment by MichaelArestad** [comment]
I'm still not thrilled with it, but it is definitely an improvement. 🚢

**Comment by eliorivero** [comment]
Padding should be fixed in mobile screen size

captura de pantalla 2017-03-31 a las 15 26 22

Also, in desktop mode, the notice text isn't aligned with the icons. Maybe this should be addressed in a different PR in dops

captura de pantalla 2017-03-31 a las 15 27 05

**Comment by eliorivero** [comment]
Updated.

captura de pantalla 2017-03-31 a las 15 38 59

**Comment by dereksmart** [comment]
picked to 4.8 179d821e6

**Pull request merged**
