### PR TITLE
Settings UI: introduce actions for scan settings card

### LINKED ISSUE #6405: Update design of the Security and Backups group
The proposal is to move the status into the header as a compact notice. They will need to remain ultra short.

There will also be some copy added:

```
Don't worry about data loss, downtime, or hacking. Jetpack <PLAN> scans for malicious code and backs up all your data.
```

(where <PLAN> is the current plan like: "Jetpack Premium") We could also just drop the plan reference.

image

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6405 

#### Changes proposed in this Pull Request:

* if site has a free plan, prompt to upgrade. This is done only in dashboard item

captura de pantalla 2017-03-16 a las 16 31 47

* if there are threats, prompt to fix them

captura de pantalla 2017-03-16 a las 16 25 20
captura de pantalla 2017-03-16 a las 16 27 54

* if site is secure, display a success badge

captura de pantalla 2017-03-16 a las 16 24 07
captura de pantalla 2017-03-16 a las 16 24 53

* action text is not uppercased in mobile size

captura de pantalla 2017-03-16 a las 19 28 41

#### Testing instructions:

* test switching plans
* the threats badge can be tested by, standing on this branch in your local Git, cherry picking the commit from #6688 `git cherry-pick bd607587539c3c05c62476003a4f41d8fa822bb0`

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@eliorivero let's remove the compact (yellow) notice from the heading when they don't have either feature. Also, on mobile, let's no go all caps.

**Comment by eliorivero** [comment]
Updates:

- yellow notice will only be displayed in dash item
- in mobile size, the action text is not uppercased

captura de pantalla 2017-03-16 a las 19 28 41

**Comment by dereksmart** [comment]
Do we want the upgrade prompt for Backups too? 
screen shot 2017-03-17 at 10 50 30 am

**Comment by MichaelArestad** [comment]
@dereksmart Yes. Let's keep it in the AAG card. It's slightly redundant, but the card could use the boost in the visual hierarchy.

**Comment by dereksmart** [comment]
Unless I'm reading this wrong, it looks like these changes will not account for those who have purchased VaultPress separately without a plan.  In this case VP will be active and installed, but they'll still be shown the `Upgrade` prompts.

**Comment by dereksmart** [comment]
@eliorivero @MichaelArestad I've pushed two commits -- One that makes sure to show the `Upgrade` notice in the Backups card if on free version.  

The other commit makes sure to not show the upgrade prompt if VP is installed and has the correct feature active.  This can happen if the user has a `free` plan, but has purchased VaultPress independently prior.

**Comment by eliorivero** [comment]
It's good to go. I'll merge once Travis ends.

**Pull request merged**
