### PR TITLE
JITMS: Adding jp-admin-notices IDs for the Boost plugin

### PR DESCRIPTION
**Pull request by coder-karen**
Ideally there would be consistency in terms of JITM banner placement across all standalone Jetpack plugins, as well as within the Jetpack dashboard and My Jetpack.

This PR aimed to add more consistency where possible for the three standalones that did not have the 'jp-admin-notices' ID on their dashboard pages, however now just focuses on Boost.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

Related to this project: p9dueE-65G-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* If testing using the Beta plugin, make sure this branch is checked out for the VideoPress plugin within the Beta plugin dashboard
* Visit the Jetpack Boost admin page and confirm that the JITM is displayed as expected, which is not a full-screen banner at the top of the page (except Search) but a banner that fits the admin page content width. Check the page source to confirm it's being included via the 'jp-admin-notices' ID.

Expected Boost display:

Screen Shot 2022-11-16 at 4 34 02 pm

With Search and VideoPress (originally included in this PR), these are somewhat more complex so I will leave those to the product teams as it is outside the scope of the project that initiated this.

### CODE REVIEW

**Review by samiff — DISMISSED** [review]
Was able to see the `div#jp-admin-notices` on all the plugin pages. 

Minor question about the VideoPress one, should the notice go above the header logo there?

**Comment by coder-karen** [comment]
> Minor question about the VideoPress one, should the notice go above the header logo there?

I thought it would be better above but couldn't get it to work easily, and didn't want to invest too much time without there being a design priority. It looks like there is though: I've checked in with them and there are some new rules coming in: p1668426136904459-slack-C0D96691V

I'll wait for info on this before doing further updates.

**Comment by ederrengifo** [comment]
Hello! I hope it's not too late. Some weeks ago we addressed the positioning issue of the JITM for My Jetpack, and we set some rules that can be easily applied to all the standalone plugins. This is what we proposed:

Slice 1

And this is how this positioning rule would apply to all the plugins:

Slice 2

Let me know if this helps!

PS: Ignore the style of the JITM, that's part of another project

**Comment by coder-karen** [comment]
Thanks @ederrengifo ! In this PR I was able to make changes to Boost, but VideoPress and Search proved more difficult and since the location / design was outside the scope of the project I'm currently working on I'll leave those to their respective product teams.

**Review by samiff — DISMISSED** [review]
Expected display for Boost worked for me 👍

**Review by samiff — APPROVED** [review]

**Pull request merged**
