### PR TITLE
Don't Rely on HTTP Requests for Shortcode Tests

### PR DESCRIPTION
**Pull request by mdawaffe**
#### Changes proposed in this Pull Request:
1.  Use fake, predetermined HTTP responses via the `pre_http_request` filter for:
   * Ted
   * Instagram
   * Tweet
2. Standardize logic in tests about when to allow HTTP requests (if `@group external-http`), and when to bypass them (otherwise).

#### Testing instructions:
1. `yarn docker:phpunit --filter=WP_Test_Jetpack_Shortcodes`.
2. See that all tests pass and most are quick.
3. `yarn docker:phpunit --filter=WP_Test_Jetpack_Shortcodes --group=external-http`
4. See that all tests pass and that most are slow.

#### Proposed changelog entry for your changes:
None needed

### CODE REVIEW

**Comment by mdawaffe** [comment]
I'm also looking at non-shortcode tests in https://github.com/Automattic/jetpack/pull/12220.

**Comment by kraftbj** [comment]
It looks good to me, but defer to @brbrr to provide a more critical review.

**Review by brbrr — APPROVED** [review]
I like that! Since we testing our own code I don't think we should rely on external services in these tests as much as possible. 

I'm not sure that we run `external-http` tests somewhere, so it might be a good idea to integrate it into our release process. Maybe include these tests in release scripts, which will help us assure that API hasn't changed

**Comment by brbrr** [comment]
Or, we can use a travis cron builds to run `external-html` tests daily/weekly/whatever
https://docs.travis-ci.com/user/cron-jobs/

Going to dig into that

**Pull request merged**
