### PR TITLE
Dialogue: focus on rich text component when created

### PR DESCRIPTION
**Pull request by retrofox**
This PR implements an auto-focus behavior to the dialogue block. It will happen when:

1) block is mounted
2) block is selected
3) block is not empty

Fixes https://github.com/Automattic/jetpack/issues/18228

#### Changes proposed in this Pull Request:

* Dialogue: focus on content when it's convenient

#### Jetpack product discussion

https://github.com/Automattic/jetpack/pull/18176#issuecomment-755746402

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Try to test the experience described [here](https://github.com/Automattic/jetpack/pull/18176#issuecomment-755746402). Confirm that now, every time that dialogue block is created, it makes focus on the block content component.

#### Proposed changelog entry for your changes:
n/a

### CODE REVIEW

**Comment by mreishus** [comment]
This works, but I'm worried about the `setTimeout()`, it might be too fast on some computers and too slow on others.  I gave it a try at solving it without, take a look at this (some messy comments)

```diff
diff --git a/extensions/blocks/dialogue/edit.js b/extensions/blocks/dialogue/edit.js
index a4eebe87f..550322c23 100644
--- a/extensions/blocks/dialogue/edit.js
+++ b/extensions/blocks/dialogue/edit.js
@@ -27,6 +27,7 @@ import {
 	useContext,
 	useState,
 	useEffect,
+	useLayoutEffect,
 	useRef,
  } from '@wordpress/element';
 import { useSelect, dispatch } from '@wordpress/data';
@@ -123,26 +124,29 @@ export default function DialogueEdit ( {
 	}, [ participantSlug, participants, prevBlock, setAttributes, conversationBridge ] );
 
 	// Try to focus the RichText component when mounted.
-	useEffect( () => {
+	const hasContent = content?.length > 0; // Dont run hook if content length changes from 5 to 6 for example
+	const richTextRefCurrent = richTextRef?.current;
+	// ^ I made this weird seeming variable because of a lint warning
+	// "useLayoutEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked"
+	// (That's why I did this, this comment can be removed)
+	useLayoutEffect( () => {
 		// Bail if component is not selected.
 		if ( ! isSelected ) {
 			return;
 		}
 
 		// Bail if context reference is not valid.
-		if ( ! richTextRef?.current ) {
+		if ( ! richTextRefCurrent ) {
 			return;
 		}
 
 		// Bail if context is not empty.
-		if ( content?.length ) {
+		if ( hasContent ) {
 			return;
 		}
 
-		// Focus the rich text component,
-		// through a delay hack.
-		setTimeout( () => richTextRef.current.focus(), 250 );
-	}, [ isSelected, content ] );
+		richTextRefCurrent.focus();
+	}, [ isSelected, hasContent, richTextRefCurrent ] );
 
 	const showTimestamp = isCustomParticipant ? showTimestampLocally : showTimestampGlobally;
 ```
(If you don't have a good way of applying a diff, I can post the entire file somewhere, or push a branch w/ it)

**Comment by retrofox** [comment]
> (If you don't have a good way of applying a diff, I can post the entire file somewhere, or push a branch w/ it)

push it! Thanks for the explanation.

**Comment by mreishus** [comment]
Pushed.  (My commit hooks automatically run prettier on the files, so some other formatting-only changes sneaked in)

**Comment by retrofox** [comment]
> Pushed. (My commit hooks automatically run prettier on the files, so some other formatting-only changes sneaked in)

no worries. In fact it's even better.

**Review by mreishus — DISMISSED** [review]
:heavy_check_mark: LGTM, The onclick is working for me as well, and can be iterated on if needed

**Review by mreishus — DISMISSED** [review]
Works well for me with 627a946, too

**Comment by mreishus** [comment]
:grey_question: This one works great when clicking directly on conversation text; you're allowed to edit it directly without having to click twice.  I am wondering if removing the `blockProps` would cause any other issues, though, [this documentation](https://github.com/WordPress/gutenberg/blob/0d21f5a8175d159f4da419cc2e7495d529c09ee8/docs/designers-developers/developers/block-api/block-edit-save.md#L49-L51) says that gutenberg needs it to understand how to manipulate the block.

>but in order for the Gutenberg editor to know how to manipulate the block, add any extra classNames that are needed for the block... the block wrapper element should apply props retrieved from the useBlockProps react hook call.

Is there someone who knows gutenberg better than we can get to give a :+1:/:-1: ?

**Review by mreishus — APPROVED** [review]
Looking around in jetpack, 99% of blocks don't use `useBlockProps`.  Additionally, I don't see any problems while using the block.  It should be okay to remove.

**Comment by retrofox** [comment]
> Looking around in jetpack, 99% of blocks don't use `useBlockProps`. Additionally, I don't see any problems while using the block. It should be okay to remove.

Thanks, Matthew. Using `useBlockProps()` is something that we should start to do. Unfortunately, the hook for some reason interferes with the RichText component, blocking it and not being able to select text when the user blocks on there.
Something to dig deeply, btw.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by retrofox** [comment]
r219130-wpcom Thanks 👍

**Pull request merged**
