### PR TITLE
Social: Change the connections endpoint to connection-test-results

### PR DESCRIPTION
**Pull request by pablinos**
After merging #26216, we discovered that Jetpack Social was not using the same API endpoint to get the connection data in the editor. The one used by Jetpack and WPCOM already provided information about the health of the connection.

#### Changes proposed in this Pull Request:
This change reverts the addition of the `is_healthy` property in the `/publicize/connections` endpoint and updates Jetpack Social to use the `/publicize/connection-test-results` endpoint.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1663318602723539-slack-C02JJ910CNL

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
* With this PR and Jetpack Social active
* Load the block editor and toggle the sidebar for social
* In the network tab of developer tools you should see a request to `/jetpack/v4/publicize/connection-test-results`
* If you apply the associated patch and sandbox the WPCOM API, you should see that `is_healthy` is no longer returned by that endpoint.

### CODE REVIEW

**Review by gmjuhasz — DISMISSED** [review]
This looks, good and tests well! 👍

**Comment by sdixon194** [comment]
Tested this out but wasn't able to get it to work 🤔 

- Ran this branch on a JN site, no jetpack, just social plugin
- Pulled D87962-code into my sandbox
- Also applied the build `bin/jetpack-downloader test jetpack update/social-connections-endpoint` 
- made sure public-api-wordpress.com was sandboxed.
- EDIT: Also made sure JETPACK__SANDBOX_DOMAIN was set

Still see is_healthy in the response:

image

Not sure if I'm missing something!

**Comment by pablinos** [comment]
Thanks for looking at @sdixon194.

> made sure public-api-wordpress.com was sandboxed.

Was `JETPACK__SANDBOX_DOMAIN` set on the JN site? The API request calls into WPCOM, so it might have still been using the production API if not.

**Review by sdixon194 — DISMISSED** [review]

**Review by spsiddarthan — APPROVED** [review]

**Review by sdixon194 — APPROVED** [review]

**Comment by pablinos** [comment]
r253064-wpcom

**Pull request merged**
