### PR TITLE
Jetpack: Add form wrapper alignment control

### LINKED ISSUE #27149: Form block - Toolbar: Adding Alignment Option
Forms don't live only in the center of the page.
Multi-column forms might need some additional width.

We should give users more flexibility via adding the classic alignment options in the toolbar:

Image

---

Image

### PR DESCRIPTION
**Pull request by CGastrell**
This PR adds the BlockAlignmentControl for the form to allow custom alignment.

Fixes #27149 

#### Changes proposed in this Pull Request:
- add block alignment control
- restrict to center, wide and full as right/left remains a bit buggy

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

Insert a form block. Notice the new alignment control on the toolbar. Verify the alignment works as expected

### CODE REVIEW

**Review by digitalwaveride — DISMISSED** [review]
Thanks Christian for bringing this in!!!
Works for me! 👍

**Review by fgiannar — DISMISSED** [review]
I tested this using the provided instructions but in some cases it doesn't work as expected.

After selecting "Full width" or "Wide width", as displayed in the attached screenshot and selecting to align once more,  "None" seems to be selected still.
Upon saving the post, the changes don't seem to take effect as well.

Screenshot 2022-11-02 at 11 23 38

**Comment by CGastrell** [comment]
@fgiannar thanks for catching that.

While supports.align works well under normal circumstances, in this case the outmost element is a wrapper added when the block is rendered.

I added a new static method to map the `align` attribute to the corresponding CSS classes. I was hoping something like that already existed, but apparently not (ping me if you know of such attribute-to-css-class functionality elsewhere).

I think it's working better now. I also removed `center` alignment option as it doesn't make sense for the form. We can revisit this later.

**Review by digitalwaveride — APPROVED** [review]
Worked for me!
Thanks Christian!

**Review by bindlegirl — APPROVED** [review]
WFM

**Pull request merged**
