### PR TITLE
Analyzer: Change minimum PHP version to 7.4

### PR DESCRIPTION
**Pull request by dereksmart**
Updates the PHP requirement to allow using PHP 7.4. 

This allows us to run it in our wpcom sandboxes. 

#### Changes proposed in this Pull Request:

Changes minimum PHP version to 7.4

#### Jetpack product discussion

@brbrr said it's probably fine p1645624757709889/1645621224.278529-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No 

#### Testing instructions:

Not really sure. Testing in a PHP 7.4* environment (wpcom) WFM.

### CODE REVIEW

**Comment by jeherve** [comment]
cc @brbrr and @kraftbj, who recently upped the requirement as part of #22035

**Comment by dereksmart** [comment]
Build is failing... is it because of monorepo stuff? https://github.com/Automattic/jetpack/runs/5305835704?check_suite_focus=true

```The following builds failed:
 - packages/analyzer
Error: Process completed with exit code 1.
```

**Comment by jeherve** [comment]
> Build is failing... is it because of monorepo stuff?

Yes.

```
Problem 1
[packages/analyzer 24.682]     - Root composer.json requires php ^7.4 but your php version (8.0.15) does not satisfy that requirement.
[packages/analyzer 24.682] 
[packages/analyzer 24.682] ::error ::Your requirements could not be resolved to an installable set of packages.%0A%0A  Problem 1%0A    - Root composer.json requires php ^7.4 but your php version (8.0.15) does not satisfy that requirement.%0A
```
https://github.com/Automattic/jetpack/blob/5774b9d743c69e99dd93b2ae373732d85d2d075d/.github/versions.sh#L1-L2
I don't know if we can easily work around that.

**Comment by kraftbj** [comment]
Some of the changed code was PHP 8.0+ when the recent Analyser work landed IIRC. For the sake of testing, I changed @dereksmart's PR to `^7.4 || ^8.0` while looking for that change.

**Comment by dereksmart** [comment]
cool thanks 🤞

**Comment by dereksmart** [comment]
Cool, so we're good to merge this?

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
