### PR TITLE
Jetpack: Further cleanup to build-module-headings-translations.php

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

Following up on #20183, this does some further cleanup:

* Replace an unnecessary use of `isset()`
* Use `var_export()` instead of `addcslashes()` to export strings.
* Use `var_export()` instead of manual array building to export static
  arrays.
* Directly return the boolean from `in_array()` instead of using an `if`.
* Delete the built file from the repo.

#### Jetpack product discussion

See code review on #20183.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Run the script, then diff the version of the generated file from the previous commit with the version generated here. e.g.
  `diff -wu <( git show HEAD^:projects/plugins/jetpack/modules/module-headings.php ) projects/plugins/jetpack/modules/module-headings.php`

### CODE REVIEW

**Comment by kraftbj** [comment]
This looks good to me, but needs to be updated from `master`.

**Comment by kbrown9** [comment]
Thank you, this code cleanup looks great to me!

I'm curious about why we're removing the built file from the repo. What's the advantage of doing that? An advantage of keeping the built file in the repo is that contributors who are unfamiliar with how the `module_headings.php` file is generated will be able to quickly and easily find the functions in the repo.

I hesitated to use `var_export` because of coding style issues like those shown in the screenshots below. Since the issues are just whitespace/indentation issues, it's probably not worth the effort to fix them.

Screen%20Shot%20on%202021-07-15%20at%2010-49-09
Screen%20Shot%20on%202021-07-15%20at%2010-50-42

**Comment by anomiex** [comment]
> I'm curious about why we're removing the built file from the repo. What's the advantage of doing that? An advantage of keeping the built file in the repo is that contributors who are unfamiliar with how the module_headings.php file is generated will be able to quickly and easily find the functions in the repo.

Since the file is rebuilt on every build, I just don't see a point to keeping it checked in to the repo. It could easily enough get out of date if someone changes some of the data it includes but doesn't happen to run a build and commit the resulting change to the file. And if they do, it'll clutter their diff with those auto-generated changes.

If someone searches for the functions in their local copy, hopefully they've run a build at some point so the local copy of the file exists. If they're searching here on GitHub, it should turn up the build script in the search results.

> I hesitated to use `var_export` because of coding style issues like those shown in the screenshots below. Since the issues are just whitespace/indentation issues, it's probably not worth the effort to fix them.

That's another advantage of deleting it from the repo. We have a general policy of excluding such files from linting, since it's seldom worth the effort of making them conform to the coding styles. (:

We had already been disabling one lint in this file for similar "not worth it" reasons.

**Review by kbrown9 — APPROVED** [review]
This looks good to me!

**Pull request merged**
