### PR TITLE
My Jetpack: Add close button navigation into `ConnectionScreen` component

### PR DESCRIPTION
**Pull request by renatoagds**
Related with #22649 

#### Changes proposed in this Pull Request:

* Create `CloseLink` component.
* Add it to `ConnectionScreen` component.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Open `My Jetpack` page.
* Navigate to `#/connection`.
* You should see the `X` button.
* Clicks on it and go back to `my-jetpack`.

#### Demo

image

### CODE REVIEW

**Comment by retrofox** [comment]
Thanks, Renato for this enhancement. I wonder why we are putting the close icon in the layout instead of straight into the connection component?

Screen Shot 2022-02-21 at 9 05 15 AM

I think it belongs to it.

A different case is the `Back` button, which does belong to the header of the Layout, imo.
image

**Comment by renatoagds** [comment]
@retrofox I don't think it belongs to the component, because it's a navigation handling and not the component itself, it has the same purpose of back link, the only difference is the styling.

**Comment by retrofox** [comment]
> @retrofox I don't think it belongs to the component, because it's a navigation handling and not the component itself,...

It's a button to close the connection and goes back to the overview.

> ... it has the same purpose of back link, the only difference is the styling.

Yes, but anyway. This action happens in other components, in different cases too.

I have to say am totally disagree. It is moving the cross over the connection components via CSS.

```css
    position: absolute;
    right: 32px;
    top: 32px;
    z-index: 1;
```

If I add a `margin-top` at the Connection component, The close button gets unlinked to it:

image

**Comment by retrofox** [comment]
> @retrofox even if I move inside to the component I need to use the absolute because it relies on top of the image with z-index modified, ...

Yes, but it should be relative to the Connection component instead of the Layout. 

> I'm not seen the big deal here.

Me neither. It isn't a big deal but from my point of view, the approach is wrong. and changing it is not a big deal to do, either.
In the end, it's up to you. I just review the code and give my feedback.

**Comment by renatoagds** [comment]
> Yes, but it should be relative to the Connection component instead of the Layout.

@retrofox That's exactly what I'm trying to understand since I want to know the reasons behind your thought. We have the `Layout`, that implements the navigation and we use that structure of `Layout` on `Connection`, I'm taking advantage of this structure and switching between kinds of navigations (go back or close), which point of this flow you think is wrong? All of them? Should we move `Connection` out of `Layout` and implement everything directly on it?

It's ok for me to move `Connection` out of `Layout` and implement everything directly on the screen, just want to understand the thoughts, before doing it.

**Comment by retrofox** [comment]
> @retrofox That's exactly what I'm trying to understand since I want to know the reasons behind your thought.

My answer is pretty simple, Renato. From my PoV, the button belongs to the Connection component, and it Should be implemented there.

**Comment by renatoagds** [comment]
> > @retrofox the connection component is a shared component used in more places than my jetpack, we cannot put a close button there, you mean connection screen otherwise?
> 
> 
> 
> I mean the component that renders the connection screen in My Jetpack. 
> 
> Btw, we always can ask for feedback from other folks to weigh in.

Yes, I know that, I really just wanted to deep more on your thoughts since I'm not seeing the same than you and probably was missing something, but I'll get this conversation finished since it's taking too long. Thanks for your feedback and we can reimplement that if needed.

**Review by oskosk — DISMISSED** [review]
Noice!

**Comment by oskosk** [comment]
I'm not understanding the complexity introduced for this single new element. Do we need to include the go back link and the close one into the same abstraction? Can we just add a the close-link component and use it once there we we need it?

**Comment by renatoagds** [comment]
@oskosk Don't think is a complexity. We have the `Layout` structure, and it implements a navigation component, we just switch between kinds of navigations. If you prefer to move out only `Connection` from `Layout` np at all, but don't think it is a problem to keep it being used for both cases.

**Comment by renatoagds** [comment]
@oskosk and @retrofox so I did a refactor here and move all layout component structure to `product-interstitial` and `connection` themselves and used `AdminPage` on both, which made the `Layout` component useless. 

If you could take a look again.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
