### PR TITLE
JITMs: Fix styling to work better with a popular plugin

### LINKED ISSUE #9221: JITMs: be nice to Dolly
When Hello Dolly! is active and showing its paragraph, the JITM shows like this

captura de pantalla 2018-04-03 a la s 16 41 57

when it's not, the JITM shows correctly

captura de pantalla 2018-04-03 a la s 16 42 16

### PR DESCRIPTION
**Pull request by withinboredom**
@jeffgolenski and I worked together to fix some styling issues.

Fixes #9221

#### Changes proposed in this Pull Request:

Fix some spacing when a popular plugin is present:

screen shot 2018-11-05 at 5 50 24 pm

#### Testing instructions:

1. Turn on Hello Dolly on a site with no plan and akismet inactive
2. View the comments page
3. See a jitm that doesn't collide with the hello dolly text

#### Proposed changelog entry for your changes:

No changelog entry is needed except maybe: Improved plugin compatibility

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
It worked well for me in Safari, Firefox, Chrome, and on Chrome for Android. 👍

**Review by keoshi — APPROVED** [review]
Works great in my testing!

**Review by jeffgolenski — APPROVED** [review]
Confirmed: This fix works well on all sized screens — mobile through desktop

screen shot 2018-11-05 at 1 14 01 pm
screen shot 2018-11-05 at 1 14 42 pm
screen shot 2018-11-05 at 1 14 57 pm

**Comment by jeherve** [comment]
@jeffgolenski @withinboredom I'm seeing some issues now when Hello Dolly isn't installed:

- On the Dashboard > Updates page:

screenshot 2018-11-06 at 9 55 26

- On the Appearance > Themes page:

screenshot 2018-11-06 at 9 55 55

It looks like we have some missing padding on the right.

**Comment by jeherve** [comment]
Until the above is fixed, let's not ship that Hello Dolly fix: I reverted here:
b19f7fb5357ac7b911b240d15f1b347ef966ca20

**Comment by jeffgolenski** [comment]
I'll take another look at it soon, @jeherve - thanks for the double check

**Comment by jeffgolenski** [comment]
I just moved this into the early value project to ensure it gets fixed this week!

**Comment by jeffgolenski** [comment]
@jeherve were you only testing this on Jurassic ninja sites? 

I noticed that everything works and looks as intended, except for JN sites, because JN throws some CSS right in-between the screen meta box and the JITM, which is just messing with the JITM styles.

see how it works fine in a sandbox: https://cloudup.com/cMVM6scsT9h

But this CSS messed up the JITM declarations that we have written
screen shot 2018-12-08 at 4 39 28 pm

because it gets in the way of
`#screen-meta-links+.jitm-card {
	margin: rem( 40px ) 1.5385em 0 auto;
}`

**Comment by jeffgolenski** [comment]
@jeherve Here's an example of that I mean: https://cloudup.com/i5wSzcK89pb

**Comment by jeherve** [comment]
I don't recall, sorry. The screenshot above is from a JN site for sure, but I don't remember if I tested somewhere else as well. I'll test your patch in #10840!

**Pull request merged**
