### PR TITLE
Allow to toggle multiple modules, update multiple module options, and general settings

### PR DESCRIPTION
**Pull request by eliorivero**
- [x] allow to update any option from any module
- [x] allow to update any setting, even combined with module options
- [x] allow to toggle modules at the same time, even together with options: if module is inactive and there's a request to activate it and set an option, activate it first and set it.

#### Changes proposed in this Pull Request:
- allow to return the entire list of module options to be updated.
    - add empty option value to post_by_email_address so it doesn't fail when it's not passed.
    - set default site icon id to 1 instead of 0 so it passes positive integer validation.
- allow to update any module option.
    - the method that returns the list of admitted options can now accept as parameter an associative array. This array can be a list of options to update. The returned list of admitted options to update matches the options that will attempt to be updated and fires validation (and sanitization where needed) for each value trying to be saved.
- allow to toggle modules in the same request. If a module option is attempted to be set, in the same request the module must be activated.
For example, let's assume Infinite Scroll is deactivated. A request with this data won't set the `infinite_scroll_google_analytics` module option:
    ```js
    {
        'carousel_background_color': 'white',
        'infinite_scroll_google_analytics': false,
        'jetpack_holiday_snow_enabled': false
    }
    ``` 
    but this one will succeed:
    ```js
    {
        'carousel_background_color': 'white',
        'infinite_scroll_google_analytics': false,
        'infinite-scroll': true,
        'jetpack_holiday_snow_enabled': false
    }
    ```
    the modules are passed as any other item to update.

##### Multiple options in multiple modules
* Go to Jetpack admin, and set these modules:
active: Carousel and Tiled Galleries
inactive: Infinite Scroll, Custom CSS
Leave Holiday Snow turned off.
Open the JS console and test with something like:
```js
jQuery.ajax( {
    url: 'http://localhost/your-awesome-site/wp-json/jetpack/v4/settings',
    method: 'POST',
    beforeSend: function ( xhr ) {
        xhr.setRequestHeader( 'X-WP-Nonce', Initial_State.WP_API_nonce );
    },
    data: JSON.stringify( {
        'carousel_background_color': 'white',
        'tiled-gallery': true,
        'infinite_scroll_google_analytics': false,
        'infinite-scroll': true,
        'jetpack_holiday_snow_enabled': false,
        'custom-css': true
    } ),
    contentType: "application/json",
    dataType: "json"
} ).done( function ( response ) {
    console.log( response );
} ).error( function ( error ) {
    console.log( error.responseText );
} );
```

#### Proposed changelog entry for your changes:
Endpoints: a new endpoint `/jetpack/v4/update` allows to toggle multiple modules, update multiple modules options and update multiple general settings. It validates (and sanitizes where needed) each module, module option, and general setting value.

@samhotchkiss @zinigor

### CODE REVIEW

**Comment by samhotchkiss** [comment]
#5461

**Comment by eliorivero** [comment]
@zinigor let's stick to the Calypso style ternary, it makes it easy to always write it in the same way and it's easy to spot where the ternary sides are.
Also, if you have a moment, could you update the phpdoc for some of the methods that were introduced in the pre-4.3.0 refactoring?

**Comment by zinigor** [comment]
Rebased to fix conflicts.

**Comment by dereksmart** [comment]
Tests well 👍

**Pull request merged**
