### PR TITLE
My Plan: update page for all paid plans

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request:

* Similar to https://github.com/Automattic/jetpack/pull/11418
* Update My Plan page for paid plans:
  * Make plan feature cards more useful and actionable.
  * Reorder cards so that Security & Performance are the top two focuses.

#### Testing instructions:

* Create a [new Jetpack site using this link](https://jurassic.ninja/create?jetpack-beta&branch=update/my-plan-page-for-paid-plans&wp-debug-log).
* Connect Jetpack and buy a plan at the end of the flow.
* Go back to wp-admin and open the My Plan page.
* Make sure the page shows a focus on security and performance, and that all cards have a corresponding action.

#### Considerations:

- The number of blocks depends on the features available to different plans; please test this PR thoroughly.
- Having an odd number of features will make the last card span across the two columns. This was decided in https://github.com/Automattic/jetpack/pull/10911 but we can revisit that.
- I've decided to keep blue buttons for features that need activation; they will turn white and change copy once activated.
- We should create a new illo for SEO Tools; any ideas?

#### Before

screenshot 2019-03-06 at 17 01 33

#### After

image

#### Proposed changelog entry for your changes:

* My Plan page is now more useful and actionable for all plans.

### CODE REVIEW

**Comment by keoshi** [comment]
Pinging you both @jeffgolenski and @joanrho for a quick review on this first draft that approximates the My Plan page for the paid plans to the free one — https://github.com/Automattic/jetpack/pull/11418

**Comment by beaulebens** [comment]
Is the usage of primary b

**Comment by eliorivero** [comment]
Shouldn't the font size of "Welcome to Jetpack Premium" be larger? Right now it's at the same visual level than the other headings. Also, its illustration looks pale compared to the other ones that have darker tones.

**Comment by keoshi** [comment]
Good points, @eliorivero!

I'm inclined to leave the heading as is since that header element is quite useless and we want people to dig down further. Increasing the text size would demand more attention and bump the relevant content further down.

Re: illustration, I agree — until we have a clarification of the Jetpack brand, we're dealing with 3 different illustration styles. This is not ideal, and we certainly update all the plans illustrations for the next release. Would you mind opening a new issue for that, please?

**Comment by joanrho** [comment]
@keoshi just tested across all plan levels: Free, Personal, Premium, Pro: https://cloudup.com/cx9jzXz104m

The illustrations feel lower priority than the two-col span single card. I'd like to change that, if possible, to be a single col span card. The two-col span doesn't make sense unless it's a different info hierarchy item (e.g., upsell) than regular feature cards.

Agree with @eliorivero that the current plan card title should be higher priority, but that is also secondary to the goal at hand: prioritizing the security and performance feature cards above all others. If anything, please address that in a separate Issue for the future rather than this current PR.

Other than the above, the sec/perf cards (even on Free) seem to be properly prioritized above the other features. LGTM!

**Comment by keoshi** [comment]
@joanrho:

> The illustrations feel lower priority than the two-col span single card. I'd like to change that, if possible, to be a single col span card. The two-col span doesn't make sense unless it's a different info hierarchy item (e.g., upsell) than regular feature cards.

The mentions of illustrations threw me off for a bit, but I think you suggested getting rid of the two-col span formatting for the last feature card on this page, correct? If so, I've fixed that here: https://github.com/Automattic/jetpack/pull/11505/commits/a57a9b829a01e38aa772371016c4ef366bdf4d7f

**Comment by keoshi** [comment]
@eliorivero @joanrho:

> Agree with @eliorivero that the current plan card title should be larger in size (text hierarchy)

Since this came up again, I've gone ahead and increased the font-size a bit on https://github.com/Automattic/jetpack/pull/11505/commits/f113cd2406e03b2e06d693ed8d77a16311bbd096

Thank you both!

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by eliorivero** [comment]
Merging this one since it's good to go, and @joanrho said:

> our primary goal at hand: prioritizing the security and performance feature cards above all others. If anything, please address that in a separate Issue for the future rather than this current PR.

**Pull request merged**
