### PR TITLE
Widgets/Shortcodes: Twitter Timeline: remove widget ID requirement

### LINKED ISSUE #3993: Twitter timeline: remove widget ID requirement
Twitter no longer requires a widget ID generated through [twitter.com/settings/widgets](https://twitter.com/settings/widgets) to display a Twitter embedded timeline for a user, list, likes, or collection. A widget ID may still be provided by a Twitter user generating an ID for an embedded search timeline or from someone with a previously configured widget.

Treat widget id (`id` shortcode attribute) as optional when generating markup. Do not include a `data-widget-id` attribute when no widget ID provided. Provide an input for the expected datasource (e.g. Twitter username) in the widget config.

Remove "you need to create a widget at Twitter.com" help text for the Twitter embedded user timeline widget.

An [oEmbed API](https://dev.twitter.com/web/embedded-timelines/oembed) is available for generating markup for the provided Twitter profile URL given the widget options.

### PR DESCRIPTION
**Pull request by nylen**
This PR updates the Twitter Timeline widget and shortcode to no loner require a Twitter widget ID, per #3993.

Also contains lots of miscellaneous cleanup to this code, including:

- Added validation and documentation of width and height constraints (determined from playing around with the interface at publish.twitter.com)
- Tried to clean up long lines of HTML/PHP soup
- Removed "No Scrollbar" option which is not working for me

Closes #3993; also closes #3283 by moving the `width` and `height` attributes as follows:

```diff
- <a width="..." height="...">
+ <a data-width="..." data-height="...">
```

### To test - Widget

**Before** applying this patch, add a Twitter timeline widget to your site. Here is a widget ID you can use to show tweets about corgis - `741284449141334020`

Apply the patch and test the following:

- Existing timeline widgets display correctly on the site and in the admin settings (type should be set to "Widget ID")
- New timeline widgets are added with type set to "Profile", and display correctly on the site when a Twitter username is entered
- Changing the type of the widget changes the label of the next field to either "Twitter Username" or "Widget ID" (and this label loads correctly for existing widgets)

Test configuring the widget in both `wp-admin/widgets.php` and the Customizer.  Ensure that all settings still work, and that the new validation for `width` and `height` works correctly.

### To test - Shortcode

To test the `[twitter-timeline]` shortcode, specify either the `username` parameter (now supported without a widget ID) or the `id` parameter with an existing Twitter widget ID (now supported without a username, because the widget ID overrides the username anyway).

### More info

The new features of the Twitter widget and shortcode are documented at https://en.support.wordpress.com/widgets/twitter-timeline-widget/ .  Note that there are 3 places where the widget settings will link to the Jetpack documentation page:

- https://jetpack.com/support/extra-sidebar-widgets/twitter-timeline-widget/#widget-type
- https://jetpack.com/support/extra-sidebar-widgets/twitter-timeline-widget/#twitter-username
- https://jetpack.com/support/extra-sidebar-widgets/twitter-timeline-widget/#widget-id

The Jetpack documentation page should be updated to be similar to the WordPress.com page when these changes go live.

The changes introduced here have been deployed on WordPress.com, but this PR does not quite bring the Twitter Timeline widget into sync with WP.com because of #3543.  Per https://github.com/Automattic/jetpack/pull/3543#issuecomment-200037364 there is still some work left to do by the Jetpack team to merge these changes back.

cc @westonruter - I don't understand the selective refresh changes in #3543 very well and would like to make sure I didn't break anything introduced there.

### CODE REVIEW

**Comment by eliorivero** [comment]
@nylen 

**Widget**
I had a Twitter Timeline widget added to one of the sidebars, and after applying the patch and immediately reloading the front end, I got this notice (in debug.log, also visible with Query Monitor plugin):
```
Undefined index: type in /example/wp-content/plugins/jetpack/modules/widgets/twitter-timeline.php on line 112

dynamic_sidebar() /example/wp-content/themes/twentysixteen/sidebar.php:13
call_user_func_array:{/example/wp-includes/widgets.php:738}() /example/wp-includes/widgets.php:738
WP_Widget->display_callback() /example/wp-includes/widgets.php:738
Jetpack_Twitter_Timeline_Widget->widget() /example/wp-includes/class-wp-widget.php:3
```

The [line 112 is a switch statement](https://github.com/Automattic/jetpack/pull/4198/files#diff-a3c30af2849ad5f1deb4b9c70f28bb2cR112). The tweets continue to display normally. The only issue is the notice.

Adding this before the line fixes the issue:
```php
if ( ! isset( $instance['type'] ) ) {
	$instance['type'] = '';
}
```

**Shortcode**
It's working fine.

**Comment by nylen** [comment]
Fixed the notice in 7bed014.

**Comment by westonruter** [comment]
> I don't understand the selective refresh changes in #3543 very well and would like to make sure I didn't break anything introduced there.

I don't see a problem here. If the actual widget ID was removed, the `id` attribute in HTML, then that would be a problem. But this is something different.

**Comment by eliorivero** [comment]
It's good to go now! 💯

**Comment by jeherve** [comment]
It seems to work in my tests. Merging.

**Comment by nylen** [comment]
🎉 Thanks everyone for reviewing!

**Pull request merged**
