### PR TITLE
Search: Add search plan to dashboard

### PR DESCRIPTION
**Pull request by gibrown**
This merges the changes to the JP dashboard that allow management of the new Search Plan.

What is missing:
- [ ] APIs to trigger the auto-config https://github.com/Automattic/jetpack/pull/15105 
- [ ] The full end to end purchase flow with all the links won't work because Search plans work only in the development environment of Calypso

Testing Instructions:
- Create a local build of Calypso using this PR: https://github.com/Automattic/wp-calypso/pull/40306 (even if this gets merged it is still only in development)
- Spin up your test site with this PR
- Poke around in wp-admin before you buy a plan
- Go to calypso.local:3000 and go to the plans page for your site
- Purchase a Search plan
- Poke around in wp-admin some more

### CODE REVIEW

**Comment by mdbitz** [comment]
Did a brief code review of the PR and didn't see any immediate concerns that jumped out. The big item on this is going to be testing and regressions to Plans

1) Any impact to Backups plan? prevously purchase was specific to backups but now is split.
2) Legacy Jetpack Search functionality - is it still functional for business plans  and instant search is only for users with a paid search plan? (Have to confirm what desired behavior is)
3) Review of each plan type to ensure desired behavior (unavailable/available)
4) Auto Configure - as mentioned not current connected needs manual execution to test.
5) UX display of Plans, customize and front end
6) Record counts, as plans are based off counts would be good to spot check this for various content ranges

Misc Notes:
__ in jsx files is the translate function from calypso which doesn't utilize the domain property and has versions for singular and plural

**Comment by jsnmoon** [comment]
> 1. Any impact to Backups plan? previously purchase was specific to backups but now is split. @mdbitz 

We had to substantially refactor parts of Backups components in the Plans page. There shouldn't be any changes to its behavior, however.

> 2. Legacy Jetpack Search functionality - is it still functional for business plans and instant search is only for users with a paid search plan? (Have to confirm what desired behavior is) @mdbitz 

As I understand it, the Business/Professional plan will retain the ability to enable the Jetpack Search module. However, it will not be able to enable the new Instant Search feature.

> 3. Review of each plan type to ensure desired behavior (unavailable/available) @mdbitz 

👍 The only noticeable difference should be the ability to enable Instant Search with an active Jetpack Search product purchase.

**Comment by mdbitz** [comment]
Testing Continues :)

I'm seeing the new Instant Search toggle that is only "enable-able" (lol) if the search plan is added to the site.

Quick Question

On the Dashboard under Performance should there be similar details about instant search? 

Screen Shot 2020-03-29 at 9 36 57 AM

**Comment by mdbitz** [comment]
Screen Shot 2020-03-29 at 9 48 18 AM

I think the "Which backup option is best for me?" link should now be in the Backup plans card.

**Review by mdbitz — APPROVED** [review]
Marking as Approved.

No concerns at a code level, This needs copious levels of testing on plans and to ensure no regression to search. I've done a walk though on my site for different scenarios ( different plans, content sizes, etc) without any blockers being identified.

**Pull request merged**
