### PR TITLE
Launchpad: Add helper function to get the task statuses from site options

### PR DESCRIPTION
**Pull request by sixhours**
## Proposed changes:

* It looks like we will use this line of code frequently given the new method of marking tasks as complete, so create a function to return the task statuses from site options to avoid repetition.
* Update existing instances of the line of code to use the function instead.
* No visual/functional changes.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply this patch to your sandbox and sandbox the API
* Create a new site from `/start` and ensure the Launchpad still works as expected.
* You can double-check that you're getting the expected results from the developer console, too.

### CODE REVIEW

**Review by andres-blanco — COMMENTED** [review]
Looks like the option `launchpad_checklist_tasks_statuses` is being used [in other places](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20launchpad_checklist_tasks_statuses&type=code).
 Should those be updated to?

**Comment by sixhours** [comment]
> Looks like the option launchpad_checklist_tasks_statuses is being used [in other places](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20launchpad_checklist_tasks_statuses&type=code).
Should those be updated to?

Hmm, good point. I hadn't even seen one of those files. I dunno, now that I'm looking at it, do you think it's worth adding this helper at all? Or does it add an unnecessary layer of abstraction?

**Comment by andres-blanco** [comment]
> > Looks like the option launchpad_checklist_tasks_statuses is being used [in other places](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20launchpad_checklist_tasks_statuses&type=code).
> > Should those be updated to?
> 
> Hmm, good point. I hadn't even seen one of those files. I dunno, now that I'm looking at it, do you think it's worth adding this helper at all? Or does it add an unnecessary layer of abstraction?

It would be good to have it in the long run, but right now it's not really necessary. I think we can leave this as cleanup task for later.

**Comment by sixhours** [comment]
Closing, I don't think this is particularly useful!

**Pull request closed without merging**
