### PR TITLE
Contact Form: Simplify Form Sidebar

### LINKED ISSUE #27801: JP Form Block - Simplifying Inspector Sidebar
One thing that makes the form block special, is that it is not just a front-end element, but its functionality also relies heavily on its capabilities on the data-management side of things.

Naturally, this means there is a lot going on in the sidebar.

The Challenge:

We need to make sure that we do not overwhelm users with too many options and noise while making sure that users get a full overview of the capabilities of the block.

For optimization tasks and general context:
pcsBup-xy-p2

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27801

#### Changes proposed in this Pull Request:
* Simplify the Form block Sidebar based on the following guidelines: pcsBup-xy-p2

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a post and add a Form block
* Check if the block Sidebar matches the changes proposed above

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Thanks so much João!!! 🚀 

Looking good! Just one little thing is missing, the renaming of CRM Integration and Newsletter Integration into -> CRM Connection, Newsletter Connection

-----------------
Test Task list:

- [x] Expanded areas are only Manage Responses, Email Connection, Color. Other areas are collapsed
- [x] In Manage Responses: Hiding the “title of the form”
- [ ] Consistency in category naming -> Using the term "connection" consistently (CRM Connection, Newsletter Connection)
- [x] Deleting text below Email Subject Line

**Comment by jcheringer** [comment]
Ops... Missed that @digitalwaveride.
Should be good now.

**Review by digitalwaveride — APPROVED** [review]
👍 João, thank you!!!
All ✅ as advertised!


---
Test Task list:

- [x]  Expanded areas are only Manage Responses, Email Connection, Color/Dimension. Other areas are collapsed 
- [x] In Manage Responses: Hiding the “title of the form”
- [x] Consistency in category naming -> Using the term "connection" consistently (CRM Connection, Newsletter Connection)
- [x]  Deleting text below Email Subject Line

**Review by jeherve — APPROVED** [review]
This looks good, it matches the changes discussed on the P2. 👍

**Pull request merged**
