### PR TITLE
Colors: update Primary green reference to match latest brand book

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

The new color is already in use in some places, such as RNA styles. Let's make the switch everywhere.
Screenshot 2021-11-15 at 14 49 24

#### Jetpack product discussion

﻿Internal references:
- p6TEKc-3tD-p2
- PbJqbW-C-p2

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Check the Jetpack and VaultPress dashboard pages.
* Ensure that the Green matches your expectations.

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Looks like projects/packages/jitm/src/css/jetpack-admin-jitm.min.css and projects/packages/jitm/src/css/jetpack-admin-jitm-rtl.min.css also need updating. For some reason those are checked in instead of built.

**Comment by jeherve** [comment]
> Looks like projects/packages/jitm/src/css/jetpack-admin-jitm.min.css and projects/packages/jitm/src/css/jetpack-admin-jitm-rtl.min.css also need updating.

Done.

> For some reason those are checked in instead of built.

I think we may have to move away from the old gulp commands to build CSS in packages:
https://github.com/Automattic/jetpack/blob/d6abf8793fa3c35b33474101e0fa1942e89e5ee4/projects/plugins/jetpack/tools/builder/sass.js#L183-L244

**Review by anomiex — DISMISSED** [review]
I suspect that gulp command has been dead code since the monorepo reorg.

Anyway, seems ok to me. Even the "You’re almost done. Set up Jetpack to enable powerful security and performance tools for WordPress" that uses the Jetpack green as a background for white text seems better this way, although someone from Design might want to consider whether we want to adjust that even further for better contrast.

**Comment by eeeeevon13** [comment]
@jeherve 
Just to be clear on usage: 
#069e08 is the "brand" green as decided in the brand book, **but** when used as a background color (with white foreground) it's only for the brand mark (the logo circle) because it does not pass contrast accessibility requirements. 

For primary button backgrounds, for example,  the color should be the next brand color darker (from the color studio) hex: #008710.

**Review by samiff — DISMISSED** [review]
> #069e08 is the "brand" green as decided in the brand book, **but** when used as a background color (with white foreground) it's only for the brand mark (the logo circle) because it does not pass contrast accessibility requirements.

Thanks for the info @eeeeevon13 👋 

Do you know if such usage specifics are documented somewhere? It makes sense, but it was not obvious to me when looking at say these internal references: PbJqbW-J-p2 or PbJqbW-C-p2

---

I'm not sure how strict we currently are at differentiating between using `#069e08` or `#008710` given the info above. However, for the sake of this PR at least, I'm thinking that the color swap of `#00be28 > #069e08` shouldn't introduce new accessibility concerns given that `#069e08` has a higher contrast ratio with white text than `#00be28`.

A future PR perhaps could take a look at any unnuanced use of `#069e08` as the "primary color" across styles.

**Review by samiff — APPROVED** [review]

**Comment by samiff** [comment]
r235610-wpcom

**Pull request merged**
