### PR TITLE
Jetpack: Include Boost on "My Products"

### PR DESCRIPTION
**Pull request by haqadn**
Fixes Automattic/jpop-issues#7982

## Proposed changes:
* Include Boost on "My Products"

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Install and upgrade Boost on a test site
* Navigate to **Jetpack Dashboard > My Plan**
* Make sure boost is listed

image

### CODE REVIEW

**Review by dilirity — COMMENTED** [review]
Changes seem good.

Note to self: When testing, don't test with license for Jetpack Premium...

When setting up a test JN site, I included a license only for Jetpack Boost.
image

After setting up Jetpack on the site, Boost doesn't show up in the `My plan` section.
image

Jetpack Beta:
image

**Comment by haqadn** [comment]
No, you are right. Looks like it is not showing for the yearly plan. I had tested monthly but skipped testing yearly.

**Review by dilirity — APPROVED** [review]
> No, you are right. Looks like it is not showing for the yearly plan. I had tested monthly but skipped testing yearly.

Happy accident! I also missed that in code...

It's showing up properly now. 🚢🚢🚢

**Comment by thingalon** [comment]
Since this touches files outside our repos, I'm hoisting this up for review by Crew or Ground Control

**Review by jeherve — APPROVED** [review]

**Pull request merged**
