### PR TITLE
Boost: Integrate performance history graph

### PR DESCRIPTION
**Pull request by haqadn**
## Proposed changes:

* Add performance history graph to a panel
* Cleanup and refactor the svelte component

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None

## Does this pull request change what data or activity we track or use?
None

## Testing instructions:
Collapse/expand the panel and refresh the page to ensure the status sticks across browser reloads

### CODE REVIEW

**Review by sejas — APPROVED** [review]
@haqadn , Awesome! Thanks for the refactor 🙏  and adding the toggle interaction.

Working as expected.

Screen Capture on 2023-08-02 at 16-37-04

**Comment by thingalon** [comment]
Nice; I can see you're making the integration much more Boost-ey. 👍

This is not a blocker to merging this into the parent branch -- but I saw an error when I tested it out:

image

It turned out that error was caused by me having the Boost Developer plugin enabled. We'll need to take care of that side of things. :-)

**Comment by haqadn** [comment]
> Nice; I can see you're making the integration much more Boost-ey. 👍
> 
> This is not a blocker to merging this into the parent branch -- but I saw an error when I tested it out:
> 
> image
> 
> It turned out that error was caused by me having the Boost Developer plugin enabled. We'll need to take care of that side of things. :-)

Shouldn't we leave the error in place to have some visual feedback for the user?

**Comment by thingalon** [comment]
> Shouldn't we leave the error in place to have some visual feedback for the user?

If there is a problem we absolutely should show an error. In this case I would prefer a more meaningful error - but that isn't what I was getting at.

I meant that we should update the Boost Developer plugin to make it possible to use / test this graph feature with our local envs. :)

**Pull request merged**
