### PR TITLE
WordPress.com Toolbar module - remove sidebars for my sites and user info.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Fixes #

related to pe7F0s-1Bv-p2#comment-2050 and response pe7F0s-1Bv-p2#comment-2055

## Proposed changes:

* Removes the slide out menus for the "my sites" and "user info" sections of the masterbar module. This is accomplished by removing all menu items that are children of the `blog` and `user-info` menu ids.

Before:
masterbar-before

After:
masterbar-after

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* On a self hosted and jetpack connected site enable the "WordPress.com toolbar" setting. this can be found searching jetpack settings, or within the modules list:
Screenshot 2024-01-24 at 11 30 29 AM
Screenshot 2024-01-24 at 11 45 25 AM

* Enable this branch using the jetpack beta plugin. (instructions in github-actions comment below)
* Verify the "my sites" and "user info" sections of the masterbar redirect to WordPress.com when clicked, instead of opening the sidebars as shown in the gifs in the above description.
* Smoke test these changes on simple and WoA. There should be no changes in functionality here.

### CODE REVIEW

**Review by roo2 — APPROVED** [review]
LGTM, we tested that this redirected the user to `/sites/$site` which calypso handles and redirects to the calypso stats page 👍.

**Comment by davemart-in** [comment]
@kraftbj @jeherve who would be the best person on the JP side to review this prior to merging it?

**Comment by jeherve** [comment]
I will take a look later today. 👍 

Although I should say that if you're happy with this PR and there is an approval already, you can merge it without an additional review. The Masterbar is very much a WordPress.com feature, so teams who make changes to that module typically do not ask for reviews from the Jetpack side.

**Comment by davemart-in** [comment]
Sweet. Thank you @jeherve!

**Review by jeherve — COMMENTED** [review]
I'm afraid this may introduce a lot of the problems we ran into when we first tried to remove those side-panels, in #11766 (note that in that PR we had also done some cleanup around the things that were not needed anymore after removing the panels).

We ended up having to revert that change as it was breaking the navigation on self-hosted sites using the module. This was discussed here:
p9Jlb4-R8-p2

This really brings back the question about the need for a masterbar module when you're not on WoA or WordPress.com Simple. I do not think that module is of any use for someone who is not on the WordPress.com platform. Maybe that means we should just remove it, or rather move the module to the mu-wpcom plugin, that is only used on WordPress.com sites. That would be my vote right now.

Do the side-panels appear to folks on the WordPress.com platform today? I was under the impression that WordPress.com sites were getting the nav-unification experience instead with the custom menus. I guess a better way to phrase this would be to ask, will your changes impact WordPress.com sites in any way? If not, would it be okay to keep the side-panels and instead focus on getting rid of the whole module on self-hosted sites, and only keep it for WordPress.com sites via the mu-wpcom plugin?

**Comment by davemart-in** [comment]
> This really brings back the question about the need for a masterbar module when you're not on WoA or WordPress.com Simple. I do not think that module is of any use for someone who is not on the WordPress.com platform. Maybe that means we should just remove it, or rather move the module to the mu-wpcom plugin, that is only used on WordPress.com sites. That would be my vote right now.

From my perspective, this is a decision for Jetpack to make. Happy to support whatever decision y'all think is best for your customers. 

> Do the side-panels appear to folks on the WordPress.com platform today?

No. These are very dated. We've not had these for many years now.

> will your changes impact WordPress.com sites in any way?

No.

> If not, would it be okay to keep the side-panels and instead focus on getting rid of the whole module on self-hosted sites, and only keep it for WordPress.com sites via the mu-wpcom plugin?

Again, happy for us to move whatever direction y'all think is best. This doesn't feel like a call I can make though.

**Comment by kraftbj** [comment]
I'm going to dive into the product and business cases for this in the self-hosted world to confirm and make a decision in the next few days. My hypothesis is that we're good to move out of Jetpack. I'll mark this PR as blocked, but will prioritize making the decision so we can move forward.

**Comment by jeherve** [comment]
Follow-up on this: #37764

**Pull request closed without merging**
