### PR TITLE
Sync Listener: Don't enqueue actions when the site is disconnected

### PR DESCRIPTION
**Pull request by kbrown9**
#### Changes proposed in this Pull Request:
It's possible to enqueue actions when the site is in the process of disconnecting. For example, if the Jetpack plugin is disconnected and deactivated in the same requests, actions related to the plugin deactivation can be added to the queue.

To prevent this, check whether the site is connected before enqueuing actions. 

#### Jetpack product discussion
* n/a

#### Does this pull request change what data or activity we track or use?
* no

#### Testing instructions:
* tbd

### CODE REVIEW

**Review by mdbitz — APPROVED** [review]
Nice addition, is_connected checks only if the site thinks it should be connected. So even if a token is invalidated. actions will still queue so a reconnect allows the data to flow through. 

Approved, don't see any use cases where we want to enqueue if not connected.

**Comment by samiff** [comment]
Hmm, seems like the required PHP tests are timing out here but I can't see quite why 🤔

**Comment by fgiannar** [comment]
Hi @kbrown9 ,

I took a look at the [PHP tests' timeout](https://github.com/Automattic/jetpack/runs/4690219719?check_suite_focus=true) and it looks like the last one to run is: `WP_Test_Jetpack_Sync_Meta::test_meta_adheres_size_limit_max`

Screenshot 2022-01-03 at 3 06 11 PM

Apart from the one causing the timeout, we have various Sync related tests failing. I believe the reason is that with the test site not being connected, the corresponding test actions are not enqueued, causing the aforementioned errors.

I think we could update `WP_Test_Jetpack_Sync_Base`, adding the `id` and `blog_token` in `set_up` (and removing them in `tear_down`) so that the site is considered connected under the Sync related PHP tests' context. What do you think?

**Comment by kbrown9** [comment]
Thanks @fgiannar! Did you do anything special to see the failing tests? All I see is this:

Screen%20Shot%20on%202022-01-03%20at%2009-59-10



> I think we could update WP_Test_Jetpack_Sync_Base, adding the id and blog_token in set_up (and removing them in tear_down) so that the site is considered connected under the Sync related PHP tests' context. What do you think?

That seems like a good solution.

**Comment by kbrown9** [comment]
The tests are now passing and this is ready for another review.

**Review by fgiannar — APPROVED** [review]
Nice work! Thanks for fixing the failing PHP tests 👍

**Pull request merged**
