### PR TITLE
Infinite scroll: Fix pagination on themes with floating content

### LINKED ISSUE #15155: Infinite Scroll + Twenty Seventeen: Over-aggressive polling of additional posts.
Originally posted in this comment: https://github.com/Automattic/jetpack/pull/15017#issuecomment-605113105 discovered by @sergeymitr.

On Twenty Seventeen, there is an over-aggressive polling of additional posts.

@dero determined it was due to:
> It seems that the container element in twentyseventeen has no outerHeight (because the children are all floating elements), which makes the infinity scroller fetch an additional page on every little scroll. We can fix that by searching for maxims of the children bounds.

#### Steps to reproduce the issue

1. JP + IS + Twenty Seventeen
2. Scroll down using the down button on the keyboard on Firefox

#### What I expected
Nothing until reaching near the bottom of the page, then more posts inserted.

#### What happened instead
More posts are inserted on every down keystroke.

**Screenshots**
https://cloudup.com/c9xX-6_P3dt

### PR DESCRIPTION
**Pull request by dero**
Fixes #15155

#### Changes proposed in this Pull Request:
* Change the way wrapper dimensions are being measured to account for floating content.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is a bugfix for the Infinite Scroll module.

#### Testing instructions:
* Follow steps to reproduce: https://github.com/Automattic/jetpack/issues/15155
* Observe the expected behavior instead of the faulty one.

#### Proposed changelog entry for your changes:
* Fixes a bug with infinite scroll loading more posts than needed on themes with floating content.

### CODE REVIEW

**Review by brbrr — CHANGES_REQUESTED** [review]
I was not been able to reproduce the original issue with Firefox/MacOS, but I see it IE11. Unfortunately, the problem with IE11 not fixed by this PR. Was it working for you in IE11?

**Comment by dero** [comment]
@brbrr Yes, I've verified the fix in IE11 before I opened the PR and tested it again right now.

Could you please verify you're testing on the latest `fix/twentyseventeen-polling` branch and on `twentyseventeen`(though I've tested on all `twenty*` themes)? I've created a [short screencast](https://www.youtube.com/watch?v=CZ6-LomU9aw) showing what I observe in IE11.

**Comment by brbrr** [comment]
Screencast for IE11 running this branch: https://take.ms/k8yIU
Screencast for IE11 running `master`: https://take.ms/8Uspg

it does load the same amount of content for both tests

**Comment by dero** [comment]
@brbrr Both screencasts show correct behavior. This is a demonstration of the issue, recorded just now off the latest `master`.

* https://www.youtube.com/watch?v=6ZQAVftSopg

I took a look at your test site and you're not seeing the issue, because your site has a sidebar set up. Only when there is no sidebar, the main content is floated and triggers the bug:

image

I haven't realized until now there is this condition. Would you be so kind to test again without the sidebar populated? Please make sure the `<main>` element has height of `0` when you test the issue.

**Review by brbrr — APPROVED** [review]
LGTM!

**Pull request merged**
