### PR TITLE
Payments block: Add transform from buttons

### LINKED ISSUE #17249: Payments Block: Core button blocks should be transformable to a Payments block.
Users should be able to take an existing button (or just any new button) and transform it into a Payments button.

Screen Shot 2020-09-23 at 1 00 32 PM

### PR DESCRIPTION
**Pull request by dsas**
Allow the core/buttons block to be transformed to a jetpack/recurring-payments block

Fixes #17249

##### Limitations
 * It only offers the transform if there is one core/button block inside the core/buttons block.
 * It requires gutenberg >= 11.5.0, the transformation won't be offered in earlier versions. This means using the Gutenberg plug-in or using WordPress >= 5.9

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Check that you're using WordPress >= 5.9 or have the gutenberg plugin installed and activated.
* Apply patch
* Add a post
* Add button blocks to post
* Select the buttons block (the buttons block contains a button block, so you might have to click up the hierarchy)
* Press the transform/variations button
* Select payments
* You should see the block transformed to a payment block

https://user-images.githubusercontent.com/93301/149837755-acffa11a-2e8e-40a2-925c-65300bb9e728.mp4

### CODE REVIEW

**Comment by dsas** [comment]
The reason why I can't transform core/buttons into a core/group of jetpack/recurring-payment is that blocks can only transform blocks to themselves, not to other blocks. I've limited how this works accordingly.

**Comment by BogdanUngureanu** [comment]
I've applied the patch on my sandbox but it couldn't be applied cleanly because of conflicts (most likely) because the build files where updated when I deployed an unrelated fix for Pay with Paypal. Maybe you could re-run the build? I assume that how we can re-trigger the build process.

Anyway, I've used Jetpack beta on my Atomic site and tried to follow the testing instructions. Unfortunately, when I tried to add a button block on a new page, the editor broke with the following error:
```
TypeError: Cannot destructure property 'possibleBlockTransformations' of 'Object(...)(...)' as it is undefined.
    at $s (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/block-editor.min.js:12:263505)
    at we (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:84:293)
    at zj (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:226:496)
    at Th (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:152:223)
    at tj (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:152:152)
    at Te (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:146:151)
    at https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:61:68
    at unstable_runWithPriority (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react.min.js:25:260)
    at Da (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:60:280)
    at Pg (https://c0.wp.com/c/5.8.3/wp-includes/js/dist/vendor/react-dom.min.js:61:14)
```

It looks like it might be related to your changes.

**Comment by dsas** [comment]
> I've used Jetpack beta on my Atomic site and tried to follow the testing instructions. Unfortunately, when I tried to add a button block on a new page, the editor broke with the following erro

Looked at this with Bogdan and it appears to be a compatibility issue with older versions of Gutenberg. I'll investigate and check for issues with the gutenberg shipped in 5.7 and 5.8

**Review by BogdanUngureanu — APPROVED** [review]
LGTM! 🥳

**Review by jeherve — APPROVED** [review]
It works for me, but I must say I don't really understand the need for this; if I have an existing button, what are the changes that I want to transform it into a recurring payment option?
Anyway, approving :)

**Comment by dsas** [comment]
Hey @jeherve I completely agree it's a niche case, the recurring-payments block also supports one-off payments too though. This issue is something I started working in my 20% time because I was reading about the transformations API and remembered this already open issue while working on payments blocks.

**Comment by dsas** [comment]
Deployed as r238400-wpcom

**Pull request merged**
