### PR TITLE
Build: update node to version that matches Calypso

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* Calypso was updated earlier, in https://github.com/Automattic/wp-calypso/pull/47866/
* Let's follow suit so when you develop in both environments, you don't have to constantly switch.

**Note** Calypso was updated again https://github.com/Automattic/wp-calypso/pull/48852

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Does the Beta build?
* Does the dashboard still work?

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by anomiex** [comment]
Could probably use a rebase or master merge to get the checks to all re-run after Github's outage.

Also,
```
$ apt-cache show nodejs
Package: nodejs
Version: 12.19.0~dfsg-1
...
```
:disappointed:

**Comment by jeherve** [comment]
> Could probably use a rebase

Done.

> $ apt-cache show nodejs
> Package: nodejs
> Version: 12.19.0~dfsg-1

Does this mean you can't personally upgrade yet? :( Do you have a way to get a "non-stable" version?

**Comment by anomiex** [comment]
> Does this mean you can't personally upgrade yet? :( Do you have a way to get a "non-stable" version?

I'd have to figure out how to install node outside of the package manager. Which I'd prefer to not have to do, but I can if we have to make this upgrade.

**Comment by jeherve** [comment]
> we have to make this upgrade.

We don't "have to" right now, but it's a bit inconvenient when developing in both the `wp-calypso` repo and the Jetpack one since you have to remember to switch from one version to the other every time you want to work in one repo. `nvm` makes that fairly quick, but it can still be a bit of an annoyance.

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
@anomiex I'm putting this one on Hold for now; let me know when you've found a solution on your machine, and we'll merge it then.

**Comment by anomiex** [comment]
My secret plan of "let's see if I can wait long enough that Debian will upgrade their nodejs package" worked. Debian unstable now has 12.20.1, so I'm good.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
On the WP.com side, this is held pending pMz3w-ctz-p2 .

**Review by kraftbj — APPROVED** [review]
Upstream issues resolved. Tests pass cleanly.

**Comment by jeherve** [comment]
r220367-wpcom

**Pull request merged**
