### PR TITLE
Packages: release a new version of the Blocks package

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

﻿This also releases a new version of the Changelogger, which is a dependency.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Check for typos.

### CODE REVIEW

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
Hmm. On second though, I suppose we should update https://github.com/Automattic/jetpack/blob/cd3b87707c83365910621972765ec4af08bec810/projects/packages/blocks/composer.json#L10 to refer to 1.1.0 instead of 1.1.x-dev. Except that won't work in the monorepo. Maybe we should just make it `^1.1` like everything else, assuming renovate won't complain about that.

**Comment by jeherve** [comment]
> Maybe we should just make it ^1.1 like everything else, assuming renovate won't complain about that.

I updated it to that in baab26711555fa8594f78176be633db6b617f65b. Renovate will most likely open a PR to pin that dependency next weekend though, indeed. Maybe we should exclude changelogger from that Renovate config?

**Comment by anomiex** [comment]
Yeah, we probably should exclude it from the renovate config.

You'll need to update lock files now. Sigh.

**Comment by jeherve** [comment]
> You'll need to update lock files now. Sigh.

Ah, right, yes. Should be okay now.

**Review by anomiex — APPROVED** [review]
This is good now, but when you get around to merging this you need to first make sure that no PR has been merged to master that adds anything new to projects/packages/changelogger/changelog/ or projects/packages/blocks/changelog/. For the auto-tagger to work right, master must have those directories empty (except for .gitkeep).

**Comment by jeherve** [comment]
Looks like everything went well. 👍

**Pull request merged**
