### PR TITLE
Fix Latest Instagram Posts Images on AMP pages

### PR DESCRIPTION
**Pull request by carlosenamdev**
Fixes #
- Fix the images style layout of the Latest Instagram Posts block on AMPpages.
#### Changes proposed in this Pull Request:

* Apply object-fit CSS rule to images of the block

#### Testing instructions:

* Make sure AMP plugin is activated
* Create or edit a new post and add a `Latest Instagram Posts` block:
Selección_045
* Connect the block with your Instagram account. If you already connected the block with instagram, then choose a account:

* You should see a grid with the posts from your instagram account:

* Save the post and check the output on normal pages and then on AMP pages:

Normal Pages:
Normal pages
AMP Pages:
AMP Pages

Before:
Before Fix

#### Proposed changelog entry for your changes:

* Fix image layout for Latest Instagram Posts block

### CODE REVIEW

**Comment by jeherve** [comment]
Internal reference: D45577-code

**Comment by carlosenamdev** [comment]
Hi @jeherve, If I pass the CSS code to `view.scss` then the images doesn't look good on Reader Mode.

**Comment by jeherve** [comment]
> If I pass the CSS code to view.scss then the images doesn't look good on Reader Mode.

I'm seeing this too as well. Can you tell why this is happening? Is the CSS not loaded at all?

**Comment by carlosenamdev** [comment]
> > If I pass the CSS code to view.scss then the images doesn't look good on Reader Mode.
> 
> I'm seeing this too as well. Can you tell why this is happening? Is the CSS not loaded at all?

This is because the Reader Mode doesn't take the enqueued scripts/styles in account, but it considers the inline styles and the CSS inside `style` tags.

**Comment by jeherve** [comment]
r210310-wpcom

**Pull request merged**
