### PR TITLE
Jetpack Plugin Visual Refresh: fixing about page and my plan

### PR DESCRIPTION
**Pull request by bindlegirl**
Applying changes based on comments in #30259 and #30212 

## Proposed changes:

* Buttons are now using .is-rna
* Buttons text is using weight 500 instead of 600

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a
## Does this pull request change what data or activity we track or use?

no
## Testing instructions:

* Load this branch and see if styles look OK now
*

### CODE REVIEW

**Comment by jeffgolenski** [comment]
Most everything is looking great, @bindlegirl! Just some small things

**My Plan page:**

For individual products purchased, the alignment of the icons is still off, compared to the title and description

image

About page looks great! 

Thank you so much!

**Comment by darssen** [comment]
Amazing work @bindlegirl! 

I saw two minor things.

In the `About Us`, main content area I see we have removed the period for the **Automattic Creed** link but we still have the one in the **Learn more about us**

image

In the My Plan, at the **We're here to help** section, I feel we are still missing the gray horizontal border added to divide the upsell area.

image

**Comment by bindlegirl** [comment]
Thank you both! I fixed all noted issues in the latest commit.

**Comment by jeffgolenski** [comment]
@bindlegirl Looks great! 🚢

**Review by jeffgolenski — APPROVED** [review]

**Comment by jeffgolenski** [comment]
@bindlegirl Apologies, I just did a thorough check on mobile, and each page needs a few tweaks. Listing them below:

**My Plan** 

- [x] "View all purchases" & "Activate a product" buttons. On small screens, can we make each of them occupy ~50% of the container and stay on the same line?
-
IMG_8115

**About**

The cards seems to stay in a grid format on smaller screens. Can we have them stack and fix the white gap at the bottom of each card?

- [x] Fix cards on mobile

IMG_8116

IMG_8117

**Comment by zinigor** [comment]
Cherry picked in 5db9a59f99a703c00f492c0d7348b79f0b43bd60.

**Pull request merged**
