### PR TITLE
Update/redirect simple classic wpcom admin interface option update

### PR DESCRIPTION
**Pull request by candy02058912**
Related https://github.com/Automattic/dotcom-forge/issues/7760

## Proposed changes:

* Redirect to /home/:site when changing Admin Interface from Classic to Default in /wp-admin for Simple Classic

https://github.com/Automattic/jetpack/assets/6586048/6b3f5d82-dac2-433a-86c6-f7d58cc294c6

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Follow the instructions to apply changes to Sandbox
* You can skip the Simple Classic release experiment by using wpsh in sandbox and run
```
update_blog_option( blogID, 'wpcom_admin_interface', 'wp-admin');
```
* Go to Settings > General
* Change Admin Interface to Default
* Should be redirected to Calypso home

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
What do you think of redirecting to `/settings/general/:site` instead, so that they can still see the option in case they want to undo it?

**Comment by lupus2k** [comment]
> What do you think of redirecting to `/settings/general/:site` instead, so that they can still see the option in case they want to undo it?

Like this too :point_up:

**Review by lupus2k — DISMISSED** [review]
LGTM :tada: 

https://github.com/Automattic/jetpack/assets/402286/63a86e56-eb1e-46af-8e75-ba9eabb96c64

**Comment by candy02058912** [comment]
> What do you think of redirecting to /settings/general/:site instead, so that they can still see the option in case they want to undo it?

Initially I wanted to keep the same behavior as when we go from Default -> Classic, users get redirected to the /wp-admin home.
Another thing is that I observed yesterday was when directly going to `/settings/general/:site`, sometimes the option is still loading the "Classic" value.

I'll give it another test and see if it still happens as it might have been I wasn't testing with the final version of the code.

**Comment by candy02058912** [comment]
> I'll give it another test and see if it still happens as it might have been I wasn't testing with the final version of the code.

Confirmed if we directly redirect back to `/settings/general/:site`, it will still show Classic, after a refresh, it then updates to Default.  cc: @fushar @lupus2k 


https://github.com/Automattic/jetpack/assets/6586048/a92cf5f5-2ce4-47b6-b132-84a16c7cd50a

**Comment by arthur791004** [comment]
> Confirmed if we directly redirect back to /settings/general/:site, it will still show Classic, after a refresh, it then updates to Default

It would be better to fix the issue and redirect the user to the settings page 😉

**Review by lupus2k — APPROVED** [review]
LGTM, but should we link to Settings > General?

**Comment by candy02058912** [comment]
I'll keep the original issue open (https://github.com/Automattic/dotcom-forge/issues/7760) so once we investigate in why the option isn't updating, we can fix it and redirect to Settings > General.

I'll merge this as an incremental step towards the final fix.

**Pull request merged**
