### PR TITLE
Publicize: point wp-admin users to WP.com calypso sharing page instead

### PR DESCRIPTION
**Pull request by dereksmart**
Round two of #3194 which was merged/reverted because we need a way to handle connections/links/disconnections from `wp-admin/post.php`.  

@jkudish is AFK/on rotation, so tagging IO to help review. 
## Original PR comment: 

This PR seeks to remove the publicize connection settings from WP.com's wp-admin and instead point users to the Calypso sharing page for their site.

screenshot from 2015-12-18 14-55-01

The code that powers the wp-admin sharing screen is considered legacy code, and is out of date with our latest Publicize connections codebase (powered by the WP.com REST API). We're taking aim at cleaning up old, less reliable code and reducing our technical debt, while offering the best user experience for users.

The XML-RPC methods will continue to be supported for the foreseeable future, even though the UI will be gone, but may be retired at some point once usage of older versions of Jetpack drops to low enough numbers.

With that in mind, it would be possible to re-create a wp-admin experience using the REST API. All of the endpoints are fully available and documented here: https://developer.wordpress.com/docs/api/#sharing

This PR is a merge of r128505-wpcom with additional removals for some JP-specific code.

To test:
- Apply PR to your Jetpack site
- Activate Publicize
- Verify that you get the screenshot above in place of the publicize settings
- Verify that the button and link take you to the expected Calypso Sharing page
- Verify that you can still add and remove publicize connections
- Verify that your added connections show up in wp-admin's Editor and Calypso Editor's as available connections
- Verify that posting a post publicizes the post as expected
- Verify that all of the above occurs without any php errors in your site's error log
- Login with a secondary user on your JP site, verify that you're still presented with this:

screenshot from 2015-12-18 14-54-46

cc @timmyc @aduth @nylen for review

### CODE REVIEW

**Comment by aduth** [comment]
Are there any changes here that were not included in #3194?

**Comment by dereksmart** [comment]
@aduth changesets should be identical

**Comment by aduth** [comment]
Per this comment, should I assume that more changes are needed here, or that this is ready for review?

>we need a way to handle connections/links/disconnections from `wp-admin/post.php`.

**Comment by dereksmart** [comment]
Yes more changes will be needed.  We need to account for what I mentioned there.  Pinging you in slack

**Comment by aduth** [comment]
Summary of Slack conversation:

If we're going to direct users to the WordPress.com interface, we should go all-in and update any references, including "Settings", "Connect to", and "Refresh Connection". These links should direct the user to their site-specific route at https://wordpress.com/sharing .

At a point in the future, we should aim to restore some conveniences based on the intent of the action. For example, refreshing a Twitter connection or choosing to connect a Facebook account should immediately open the authorization prompt when landing on WordPress.com .

**Comment by josheby** [comment]
So am I reading this correctly that the current WP Admin interface for Publicize is going away?

If so, this troubles me as I have spent the last few weeks integrating Publizies into my SaaS project that I am working on to specifically streamline the intergace for it through WP Admin.

I am going to guess I am not along on this when I say that removing the option to use WP Admin seems short sighted and is going to alientate a large user base that is dealing with customers that we have spent lots of time familarizing with WP Admin and giving them two ways to do things is just going to be confusing.

Is there any chance that this can be done without loosing access to things within WP Admin?  I am all for brining Calypso into the fold and I think there is a definate market for it, however, I don't think WP Admin should be abandoned.

Let me know.  Thank you.

**Comment by kraftbj** [comment]
> So am I reading this correctly that the current WP Admin interface for Publicize is going away?

That is what's being explored. As far as how Publicize works, the connection data lives on WP.com and the Jetpack wp-admin is reflecting what's store on WP.com as saved locally, which means there are situations where the local wp-admin can be out of sync making things confusing (e.g. wordpress.com/sharing reports what is actually going out, while the wp-admin is displaying old, incorrect data).

That said, still exploring the best way of handling all of these pieces. The wp-admin view has been removed from wp.com and looking into the best way to keep parity, reduce technical debt/multiple codebases, reduce points of failure, etc.

**Comment by beaulebens** [comment]
@josheby can you talk a bit more (or link?) about how you've integrated things with the wp-admin version? If we understood a bit more about how you're using it, I think that'd help look at alternative approaches here.

One of the biggest motivators for removing this code, as @kraftbj mentioned above, is technical debt. We removed it on WP.com because that UI/code had all sorts of bugs and inconsistencies, which we just don't have in the code on Calypso. Unfortunately that same code is what's merged over to Jetpack, so we're trying to reduce duplicated, buggy code as much as possible.

**Comment by aduth** [comment]
@josheby: Adding to the points above, depending on how you plan to integrate with Publicize, we may suggest that you consider using our REST API endpoint offerings instead, as these will be more stable than depending upon any specific user interface:

https://developer.wordpress.com/docs/api/#sharing

**Comment by aduth** [comment]
Part of the hope with this change was to avoid maintaining two interfaces for connection settings and to consolidate management of connections through the REST API. Now that we've started incorporating React and Redux into Jetpack, it might be worth investigating reusing Sharing components between Jetpack and Calypso. For example, I might imagine we could reuse much of the Calypso Sharing components and state within the Jetpack wp-admin experience:

- https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/sharing
- https://github.com/Automattic/wp-calypso/tree/master/client/state/sharing

(Noting that there's still in-progress effort to port Calypso sharing to Redux state, most recently https://github.com/Automattic/wp-calypso/pull/8991)

**Comment by eliorivero** [comment]
Closing this since this is addressed in new settings UI
https://github.com/Automattic/jetpack/issues/6228

**Pull request closed without merging**
