### PR TITLE
Add JetpackBanner to Scan card in At-a-Glance

### LINKED ISSUE #12564: At a Glance: Switch to Upgrade banner on Security Scanning DashItem
### The problem
The Compact Notice components are no longer serving well as an upgrade call to action. They make the dashboard look broken. There is also a redundant text link that is a secondary redundant call to action.

Here is the current Security Scanning DashItem:
image

### Proposal

**Copy:**
Jetpack's comprehensive security scanning finds issues early so we can help fix them fast.

**Gridicon**
`icon="lock"`

**Mockup**
Security Scanning v3

### PR DESCRIPTION
**Pull request by crunnells**
Since we're removing the "scary" upgrade buttons, we're using the banner as a more gentle nudge towards upgrading. This PR is currently a **Work In Progress**, as this certainly isn't the best way to accomplish this task. 

To Do:

- [x] Ideally the JetpackBanner should be below the `.dops-section-header` instead of inside the `.jp-dash-item__card` so we don't have to use CSS to change the padding, etc.
- [x] It needs a sensible Tracks event name
- [x] Possibly update the Upgrade HREF (unless we plan on redirecting all traffic on the URI to the new landing page) (see: https://github.com/Automattic/jetpack/pull/12837)

Fixes #12564 

#### Changes proposed in this Pull Request:

* Updates the Security Scanning card in the At-a-Glance view to use the JetpackBanner component to nudge towards an upgrade

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is part of the At a Glance Tuneup project

#### Testing instructions:
* Go to At a Glance after connecting Jetpack on a Free plan
* See the JetpackBanner prompting an upgrade in the Security Scanning card

#### Proposed changelog entry for your changes:

* Changes to upgrade messaging in the Security Scanning card

#### Screenshots:

Before:
58902607-a6b17000-86c0-11e9-8abe-59a8d147cf9b
 
After:
Security Scanning v3

### CODE REVIEW

**Comment by pablohoneyhoney** [comment]
Have you designed and reviewed this solution in the context of the whole page? @crunnells

**Comment by brbrr** [comment]
I wonder why do we use a pencil icon here?

**Comment by crunnells** [comment]
> I wonder why do we use a pencil icon here?

The Banner component is _meant_ to show info associated with a plan, and in this case the icon corresponds a the WP.com Premium plan (which is the default icon if you don't set the `icon` property). The last commit to this PR changed the icon to a lock, and I've updated the mockup to show the change.

**Comment by crunnells** [comment]
@pablohoneyhoney 
> Have you designed and reviewed this solution in the context of the whole page?

@MichaelArestad and I considered which existing Jetpack components would work on this page, and used the one that felt the most appropriate without looking like there were _problems_ with the customer site. The current "Update" buttons make it look like an urgent problem with this and other feature cards.

**Comment by robertf4** [comment]
I pushed some changes to make the Tracks events work. The Banner component now uses the `eventFeature` and `path` properties to log `jetpack_wpa_click` events.

**Comment by MichaelArestad** [comment]
@robertf4 Can you resolve the conflicts? I tested this and it works like a charm. I think the conflicts were introduced via a copy change?

**Comment by robertf4** [comment]
The merge conflict is resolved.

**Review by robertf4 — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
This seems to work well for me. I only have one question.

Is this okay that the card does not line up with the one on its right?

image

**Comment by MichaelArestad** [comment]
@jeherve yes. That is expected.

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.5` in d62d71cd2ccb3f7610fd352c0544ca91c86e90a0

**Pull request merged**
