### PR TITLE
Blocks: Deprecations - ensure supports are exported within larger configuration objects.

### LINKED ISSUE #40055: Incompatible block(s?) with latest Gutenberg trunk: Site editor crashes
### Impacted plugin

Jetpack

### Quick summary

Some changes were made in https://github.com/WordPress/gutenberg/pull/63401 that causes one or some of the Jetpack blocks to crash the site editor. 

Honestly I'm not sure if it's a bug with how Jetpack is registering blocks, or if there needs to be more defensive code in Gutenberg. I'm having trouble tracking down the specific block that is causing the error to get minimal reproduction steps. 

### Steps to reproduce

1. Activate the Jetpack plugin
2. Checkout and build gutenberg commit [48341a1](https://github.com/WordPress/gutenberg/commit/48341a13f7ca383830fecc328b3e7e3131ba831a)
3. Visit `/wp-admin/site-editor.php`

### A clear and concise description of what you expected to happen.

No crash.

### What actually happened

Blank page. With console error 

Image

```
process-block-type.js:153 Uncaught TypeError: Cannot set property supports of #<Object> which has only a getter
    at process-block-type.js:153:25
    at Array.map (<anonymous>)
    at process-block-type.js:151:46
    at thunk-middleware.js:4:11
    at index.js:24:12
    at promise-middleware.js:20:9
    at Object.dispatch (resolvers-cache-middleware.js:45:10)
    at Object.apply (index.js:228:12)
    at private-actions.js:34:30
    at thunk-middleware.js:4:11
```

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Turn off Jetpack Blocks module. 

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes https://github.com/Automattic/jetpack/issues/40055

Note - this may be better dealt with at the Gutenberg end - comment left here: https://github.com/WordPress/gutenberg/pull/63401#discussion_r1832394335

## Proposed changes:

* The reported issue was that with the latest Gutenberg including the affected commit, the Site Editor (and post / page editors) do not load, with console errors displaying. Disabling Jetpack blocks allowed those editors to load again.
* The issue was due to deprecation object exports, and affected four blocks: Payments Intro, Related Posts, Slideshow and Tiled Gallery. 
* The new `stabilizeSupports` function in Gutenberg now expects supports to be part of a larger block configuration object that doesn’t have getter-only behavior.
* Previously, we were using named exports for each property, so each was exported as it's own standalone property (therefore with getter-only behaviour). With the change in this PR, the support export in particular is exported as a block configuration object, compatible with wa `stabilizeSupports` expects.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/40055

## Testing instructions:

To replicate the issue:

* In trunk locally or using the Jetpack Beta tester (even the latest stable), add the latest Gutenberg nightly plugin which includes the relevant commit. This can be downloaded from here: https://gutenbergtimes.com/need-a-zip-from-master/#nightly
* Ensure Jetpack blocks are enabled: `/wp-admin/admin.php?page=jetpack#/writing`
* Open up the site editor if using a block theme: `/wp-admin/site-editor.php`, or a post / page editor in wp-admin.
* You should notice that the editors do not load, and the console should show the following error: `process-block-type.js:153 Uncaught TypeError: Cannot set property supports of #<Object> which has only a getter`.

To test the fix:

* Follow the same steps as above, after applying this PR.
* The editors should load, with no console errors displayed.
* As this affects deprecation files, it would be wise to test deprecations work as expected. This may be better tested on a JN site:
  * Deactivate the Gutenberg nightly plugin.
  * Download and install an earlier version of Jetpack - 13.3 covers the most recent Payments Intro block deprecation changes, 13.0 covers the most recent Related Post block deprecation changes, 13.4 covers the most recent Slideshow block deprecation changes and 13.5 would cover the most recent Tiled Gallery block deprecation changes (however with TG there are other issues resulting in a broken block when updating version - see below. Best testing for this may just be to check the post and save content in the console matches, minus what is mentioned below).
    * The Payments Intro block is the Payments block without any options chosen.
    * Regarding the Tiled Gallery block, one issue is reported here: p8oabR-1At-p2#comment-8253, the other is related to aria-label, tabindex and role differences. Those are actually covered by the v6 deprecation, but are only showing as differences in the block saves content vs post body because of the other issue - you'll notice that upgrading from 13.5 to the previous latest stable (13.9) works just fine.
    * Previous releases can be selected more easily from the Beta tester, if using the Beta tester plugin
  * With each respective version installed, add a post with the relevant block - Tiled Gallery, Slideshow, Payments Intro or Related Posts.
  * Using the beta tester plugin, apply the branch with this fix.
  * Ensure the post editor is still loading properly.
  * Reactivate the Gutenberg nightly plugin - ensure everything continues to load as before.

### CODE REVIEW

**Comment by andrewserong** [comment]
Thanks for working on this and for identifying the issue in Gutenberg! This PR may not be necessary as there's an upstream PR now that I think should fix it: https://github.com/WordPress/gutenberg/pull/66849 (if you get a chance, please give it a test)

That said, the way that Jetpack Blocks structure the deprecations did look a little unusual to me, so for code quality reasons it might still be worth tidying up?

Something I was wondering about is why the `deprecated/index.js` files are structured like this:

```
import * as deprecatedV1 from './v1';
import * as deprecatedV2 from './v2';

export default [ deprecatedV2, deprecatedV1 ];
```

Instead of something like:

```
import v1 from './v1';
import v2 from './v2;

export default [ v2, v1 ];
```

Then in each deprecation, something like the following so that it's explicit what the `deprecation` object looks like, rather than it being implicit via `*`:

```
export default {
  attributes,
  supports,
};
```

Would that work? From my perspective the structure of the files in this plugin looks a bit more granular than I'm used to compared to core WP blocks.

This is just my first impression from looking at the Jetpack code, though, so please feel free to disregard this comment if there are good reasons why the Jetpack blocks are structured the way they are right now! 🙂

**Comment by annezazu** [comment]
Just a quick note of appreciation—thanks so much for flagging this up in Core!

**Comment by andrewserong** [comment]
> Just a quick note of appreciation—thanks so much for flagging this up in Core!

💯

Yes! This was exactly the kind of testing and feedback we needed for this work, so another big thank you from me!

**Comment by coder-karen** [comment]
Thanks for the quick fix @andrewserong ! It does work for Jetpack, so this PR isn't necessary and I'll close it out.

Good question re the current deprecation approach though. It appears that what has happened is that the approach was taken in one instance some time back, and has been copied in several cases since. I'll add a task for us to clean this up and look into the suggestions you've made here, thank you!

**Pull request closed without merging**
