### PR TITLE
codesniffer: Hack around mediawiki-codesniffer bug

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

Their test for whether a class is a PHPUnit test class is mainly
designed for their own use, and doesn't after all work for us.
Fortunately they have that logic isolated in a trait, which we can copy
and override.

Also fix the one file that was removed from the excludelist thanks to
this bug (https://phabricator.wikimedia.org/T273575), and four more
that had new errors not detected thanks to the bug.

And fix three other files that were removed from the excludelist thanks
to a different bug that broke detection of `dirname( __FILE__ )` in some
cases (https://phabricator.wikimedia.org/T273574).

#### Jetpack product discussion

None.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Do tests pass?
* Revert the changes to test-class.sitemap-stylist.php, are they detected.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Review by kraftbj — DISMISSED** [review]
Thanks for catching that and reporting upstream. 

One of the phpcs checks are failing now.

**Comment by anomiex** [comment]
Heh, more classes had problems with the change but were hidden by T273575. Will fix.

In the process, found [another upstream bug](https://phabricator.wikimedia.org/T273624).

**Comment by kraftbj** [comment]
@anomiex Adding the polyfill broke things.

**Review by kraftbj — APPROVED** [review]
Let's do it!

**Pull request merged**
