### PR TITLE
Revert "Updates module settings positions and renames tabs."

### PR DESCRIPTION
**Pull request by zinigor**
Backs out of the changes that are going to be a part of the next release.

### CODE REVIEW

**Comment by dereksmart** [comment]
Good 'ol general settings tab back in action!

**Comment by zinigor** [comment]
Rebased so it can be merged. @vindl can you please take a look at the SEO module settings. I have a feeling that I have missed something when rebasing.

**Comment by vindl** [comment]
@zinigor I think that we are now missing professional plan checks that I have added in `traffic` (Upgrade button and Pro label), since that functionality is not present in `appearance` tab. Here are the relevant commits: https://github.com/Automattic/jetpack/pull/5307/commits/a3775900c2a9a3ab4e2b2ff2f5f680c48b46e2da, https://github.com/Automattic/jetpack/pull/5307/commits/250d0c4d2e55451de499445bcc918e8c39820639, https://github.com/Automattic/jetpack/pull/5307/commits/ce47c47e0352565ceef890c84b28c8eb7050e0f9.

**Comment by vindl** [comment]
@zinigor Disregard my previous comment, it seems like those checks made it to `appearance/index.jsx`. I've tested it and it looks good so far.

**Comment by jeherve** [comment]
#5461

**Pull request merged**
