### PR TITLE
Admin Menus: Fix users menu item pointing to wp-admin.

### PR DESCRIPTION
**Pull request by yansern**
Fixes p1688556726242369-slack-CBG1CP4EN

## Proposed changes:

* Fixes users menu item pointing to the wp-admin version.

The PR https://github.com/Automattic/jetpack/pull/31170/ introduced a regression where the class `Atomic_Admin_Menu` extended the `add_users_menu` function from [Admin_Menu::add_users_menu](https://github.com/Automattic/jetpack/blob/3e036936f2385aaef046a5181d08ed263ff1c456/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L327-L335) but did not call the original parent function to run execute additional menu configuration.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Create a new Business site, mark it as a WoA Developer Blog, and take it Atomic.
* Install the Jetpack Beta Tester plugin and check out this branch on the site.
* Clicking on the Users menu should go to Calypso `/people/team`.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This tests well for me (I updated the tests following the changes).

**Comment by ivan-ottinger** [comment]
I have rebased the changes and tested them - all is working well. Now the remaining issue is failing tests which I am looking into now.

**Comment by ivan-ottinger** [comment]
The tests keep failing because of the following:

```
  There was 1 failure:
  
  1) Test_Atomic_Admin_Menu::test_add_users_menu
  Failed asserting that two strings are identical.
  --- Expected
  +++ Actual
  @@ @@
  -'https://wordpress.com/subscribers/example.org'
  +'https://wordpress.com/me/account'
  
  /tmp/wordpress-trunk/src/wp-content/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-admin-menu.php:315
```

But when I run those tests locally, they don't fail and the returned menu link is correct (`https://wordpress.com/subscribers/example.org`). 🤔 

→ Related discussion: p1688637692714229/1688556726.242369-slack-CBG1CP4EN.

**Review by jeherve — APPROVED** [review]
Tests seem to pass now.

**Pull request merged**
