### PR TITLE
Boost: Remove global state from BenefitsInterstitial component

### PR DESCRIPTION
**Pull request by dilirity**
## Proposed changes:

* Moves global state to parent component.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-286-p2

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Make sure the "Upgrade" page works as expected.
CleanShot 2023-09-18 at 17 30 59

### CODE REVIEW

**Review by pyronaur — DISMISSED** [review]
TIL `let:variable` syntax

**Comment by pyronaur** [comment]
Note: you can use the global Jetpack_Boost variable to infer the type of pricing:

```ts
export let pricing: typeof Jetpack_Boost['pricing'];
```

**Review by pyronaur — COMMENTED** [review]
:shipit:

**Review by pyronaur — DISMISSED** [review]

**Comment by dilirity** [comment]
@pyronaur sorry for requesting a review again - I decided to clean things up after the merge.

**Review by pyronaur — APPROVED** [review]
:shipit:

**Pull request merged**
