### PR TITLE
Scheduled updates: Update scheduled updates cron event name to jetpack_scheduled_plugins_update

### PR DESCRIPTION
**Pull request by ouikhuan**
Fixes Automattic/dotcom-forge#6125

## Proposed changes:

* Update cron event name from `jetpack_scheduled_update` to `jetpack_scheduled_plugins_update`  so that it’ll be easier in the future to extend it to themes.

**Note:** By updating the hook name here, this means the existing schedules will not be picked up anymore. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Follow pcmemI-2Sx-p2 to setup a testing WoA site.
* You can either select this branch in your Jetpack Beta tester under WordPress.com features or use jetpack rsync to sync the changes to your testing site.
* Navigate to https://wordpress.com/plugins/scheduled-updates/<site-slug> and try to create, edit, and remove your schedules.
* Make sure everything works as expected as before.

### CODE REVIEW

**Review by vishnugopal — COMMENTED** [review]
I haven't tested functionality yet, but is it a good time to declare `jetpack_scheduled_plugins_update` as a constant somewhere and import it in other places so that later on we can change this (if necessary) once?

**Review by vishnugopal — COMMENTED** [review]
Seems to have a couple of omissions here: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/tests/php/class-scheduled-updates-test.php#L80

**Comment by zaerl** [comment]
> I haven't tested functionality yet, but is it a good time to declare `jetpack_scheduled_plugins_update` as a constant somewhere and import it in other places so that later on we can change this (if necessary) once?

I second this. Having a `Scheduled_Updates::PLUGIN_EVENT`, or similar, constant is a good idea.

**Comment by ouikhuan** [comment]
> I haven't tested functionality yet, but is it a good time to declare `jetpack_scheduled_plugins_update` as a constant somewhere and import it in other places so that later on we can change this (if necessary) once?

Make sense, made the changes, thanks.

**Comment by ouikhuan** [comment]
> Seems to have a couple of omissions here: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/tests/php/class-scheduled-updates-test.php#L80

Nice catch, fixed!

**Comment by obenland** [comment]
I don't mind having it in a constant, just be aware that changing the hook name means that all existing schedules will stop working, unless migrated.

**Comment by ouikhuan** [comment]
> I don't mind having it in a constant, just be aware that changing the hook name means that all existing schedules will stop working, unless migrated.

@obenland Since this is not published yet and will likely only break for internal testing, I wonder if we should handle the migrated cases, or should we push this out directly? I've added a note in the PR to mention that the original schedules won't be picked up anymore.

**Comment by obenland** [comment]
Oh, it's fine to break internal schedules and notify folks in the CfT. I meant it more in the context of 

>  is it a good time to declare jetpack_scheduled_plugins_update as a constant somewhere and import it in other places so that later on we can change this

**Review by vishnugopal — APPROVED** [review]
Tested and everything seems to work as before. Thank you!

**Pull request merged**
