### PR TITLE
Backup: Write helper script to ABSPATH by default, just like we did before

### PR DESCRIPTION
**Pull request by pypt**
In https://github.com/Automattic/jetpack/pull/34297, among other things, we've changed the order of directories to which we try to write the helper script.

Before that PR, the order was:

1. ABSPATH
2. `wp-content/`
3. `wp-content/uploads/`

After that PR, the new order was:

1. `wp-content/`
2. `wp-content/uploads/`
3. ABSPATH

This is because on some hosts, ABSPATH might point to weird locations, and on others, writing to ABSPATH won't be allowed due to security reasons.

It turned out that quite a few hosts disallow us from accessing PHP scripts from `wp-content/` directly:

* p1707297095152959-slack-CS8UYNPEE

So, we're changing back the default to ABSPATH, i.e. the order is now going to be back to:

1. ABSPATH
2. `wp-content/`
3. `wp-content/uploads/`

Also, I've moved `Package_Version` class from a versioned `VXXXX` namespace because it's used in a filter, and due to the way it works, it would cause problems on plugin upgrades:

* p1707319616800829/1705089030.985119-slack-CBG1CP4EN

## Proposed changes:

* Just like we used to do before https://github.com/Automattic/jetpack/pull/34297, try writing the helper script to ABSPATH first, then to `wp-content/`, then to `wp-content/uploads/`.
* Bump namespace version number as per https://github.com/Automattic/jetpack/pull/34739
* Move `Package_Version` class back to the `Automattic\Jetpack\Backup` namespace

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1707297095152959-slack-CS8UYNPEE

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Just like with https://github.com/Automattic/jetpack/pull/34297, run a Jetpack VaultPress Backup backup without credentials set up, so that the tool is then forced to upload the helper script via Jetpack API and thus trigger this code.

Please test upgrades as well, we had some hiccups with the Backup plugin getting updated with the versioning: https://github.com/Automattic/jetpack/pull/34739#issuecomment-1893877905

### CODE REVIEW

**Review by Initsogar — APPROVED** [review]
Thanks for working on this. I just tested it using the core plugin and the standalone backup plugin, and it is working as expected.

**Comment by pypt** [comment]
Thank you Rafa!

**Comment by Initsogar** [comment]
I was taking a look into some manual upgrade tests using Beta Testers, and can confirm that upgrading from Jetpack 13.1.1 and Jetpack VaultPress Backup 2.4 to this branch is working as expected and no more PHP errors are thrown.

I think we are good to go ✅

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-13.1.3` in 05044180662dae189b300787817c75966b77fd28

Four-point package releases:

* https://packagist.org/packages/automattic/jetpack-backup#v3.1.4.1
* https://packagist.org/packages/automattic/jetpack-backup-helper-script-manager#v0.2.1.1

**Pull request merged**
