### PR TITLE
Improve/readme add jetpack ai

### PR DESCRIPTION
**Pull request by mikestottuk**
## Proposed changes:

Add a new section to the readme to promote the new AI features.

## Jetpack product discussion

pdhack-Fo-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Check for typos.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
This works for me. Should we mention translations too?

**Comment by mikestottuk** [comment]
> This works for me. Should we mention translations too?

We probably can add it, if we do it might start making Jetpack rank as a “translations” plugin though (for front end of the site, like https://wordpress.org/plugins/weglot/ )

**Comment by mikestottuk** [comment]
@jeherve I've added in a bullet on translations (the copy for this is part of the launch materials - i.e. I've not just made it up)

**Review by jeherve — APPROVED** [review]

**Comment by anomiex** [comment]
Cherry-picked as ea2d088d56

**Pull request merged**
