### PR TITLE
Payment Buttons: Add vertical margin dimension controls

### LINKED ISSUE #25927: Payment Buttons Block: Add Dimensions Panel
### Impacted plugin

Jetpack

### What

Add the Dimensions panel to the Payment Buttons block

### How

This will make the Payment Buttons block work like the Core Buttons block.

Screenshot 2022-08-30 at 13 59 15

_Note: the image above shows the panel with all the optional content enabled._

### PR DESCRIPTION
**Pull request by dsas**
Partly addresses #25927 - blockGap (block spacing) is not implemented in this PR, just vertical margins.

#### Changes proposed in this Pull Request:

Add vertical margin controls for the payment-buttons block (used to group recurring-payment buttons) in the dimensions panel. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Get a site on a paid JP/wpcom plan
* Insert a Payment Buttons block
* Go through the stripe set-up
* When returned to the editor, publish the page and view it
* Apply this patch / use this branch with jetpack beta on a JN/atomic site
* Refresh the page opened earlier - it should be unchanged
* Edit the block by changing the text etc
* Save the page
* View the page - it should look identical
* Go back to Gutenberg
* Select the payments-buttons block
* Open the sidebar and press plus on dimensions add margin settings
* Play with margins and notice the buttons change appropriately - the vertical margins only changing
* Save the page and review it - notice the margins settings have taken effect.
* Add a premium-content block, notice the buttons are unaffected.

https://user-images.githubusercontent.com/93301/188712559-b87214fc-3adc-4828-a100-f14ef282bf52.mp4

### CODE REVIEW

**Comment by dsas** [comment]
Haven't yet added [blockGap control support](https://fullsiteediting.com/lessons/theme-json-layout-and-spacing-options/#h-blockgap), this brings some extra challenges:
 * Backwards compatibility - a gap is currently already set, which might differ from the theme
 * It doesn't Just Work and I haven't yet figured out why.

**Comment by dsas** [comment]
I think adding blockGap support means either using [Gutenberg layouts](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php) or reinventing some of them. This is a bit of a pain, will _probably_ involve modifying payment-buttons, recurring-payment and jetpack/button blocks, which are due to be changed anyway by #25928. This may be better done in a follow-up PR.

**Comment by rcrdortiz** [comment]
Works as advertised, tested on a JN and simple sites.

**Review by rcrdortiz — DISMISSED** [review]

**Review by mmtr — CHANGES_REQUESTED** [review]
> Partly addresses https://github.com/Automattic/jetpack/issues/25927

I think the intention of that issue is to replicate the behavior of the Core buttons block which provides this panel:

Screen Shot 2022-09-07 at 11 00 14

There are a few things that are different in this PR:
- It's adding a padding control which doesn't exist in the Core buttons block.
- The margin control affects the left/right margin as well, while the margin control of the Core buttons block only changes the top/bottom margin.
- The block spacing control is missing.

**Comment by mmtr** [comment]
> The block spacing control is missing.

Is this the blockGap not being implemented that is mentioned in the summary? If so, feel free to ignore that :)

**Review by mmtr — APPROVED** [review]
Works great!

**Comment by dsas** [comment]
Deployed r252259-wpcom

**Pull request merged**
