### PR TITLE
jetpack (block editor): Only add `x-wp-api-fetch-from-editor` on non-CORS reqs

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

It turns out that `@wordpress/api-fetch` is used for cross-origin
requests too. We (probably) only need the added header for same-origin
requests, so detect for that.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1657539716330009-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* ?

### CODE REVIEW

**Review by thedebian — APPROVED** [review]
Code looks good and it fixed the cors header issue too 👍

**Review by jeherve — APPROVED** [review]
This looks good and tests well for me. 🚢

**Comment by anomiex** [comment]
r248899-wpcom

**Comment by coder-karen** [comment]
Cherry-picked to release branch in e5a767e2abbbff8f3bf674d1393524b6000cab57

**Pull request merged**
