### PR TITLE
Recurring Payments: Update price after currency changes

### PR DESCRIPTION
**Pull request by mmtr**
Fixes #42591

#### Changes proposed in this Pull Request:

Ensures a Recurring Payment price is updated to reflect the currency's minimum requirement if the previous price isn't valid for the new currency.

Before | After
--- | ---
May-27-2020 16-56-16 | May-28-2020 13-54-09

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

Updates the Recurring Payments block which is already an existing part of Jetpack.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

Jetpack
* Set up Recurring Payments on a JP site using the testing store and using this branch (a JN site works). More info in PCYsg-lW4-p2 #testing-with-jetpack.
* Add a Recurring Payments block to a page or post.
* Add a new plan.
* Note the defaults for currency and price - USD and $0.50.
* Change the currency to something else, like NOK or JPY.
* Make sure the price is updated to the minimum price for the selected currency.
* Make sure the price is not updated if you previously entered a price which is still above the minimum (like switching to NOK after entering USD 10).

WP.com
* Apply D44042-code.
* Set up Recurring Payments on a WP.com site using the testing store. More info in PCYsg-lW4-p2 #sandbox-method.
* Add a Recurring Payments block to a page or post.
* Add a new plan.
* Note the defaults for currency and price - USD and $0.50.
* Change the currency to something else, like NOK or JPY.
* Make sure the price is updated to the minimum price for the selected currency.
* Make sure the price is not updated if you previously entered a price which is still above the minimum (like switching to NOK after entering USD 10).

#### Proposed changelog entry for your changes:
* Recurring Payments: Update default minimum price when currency is changed

### CODE REVIEW

**Comment by mmtr** [comment]
> Non-blocking, but one thing I noticed: did we mean to have different behavior for currencies that use a different grouping (say comma instead of decimal for cents)?

Good catch! I think that's actually based on current locale rather than currency. For example in Spanish decimals are set with a comma, so the number input (`<input type="number">`) always use it for me:

Screen Shot 2020-05-28 at 12 22 14

Let me see if I can retrieve the decimal separator appropriate for the current locale and pass it down to `formatCurrency`.

**Comment by mmtr** [comment]
inpu

> Let me see if I can retrieve the decimal separator appropriate for the current locale and pass it down to `formatCurrency`.

Actually, just found out that values for `<input type="number">` elements need to always use a dot notation for decimals according to the [spec](https://web.archive.org/web/20190630021258/http://www.w3.org/TR/html5/forms.html#number-state-%28type=number%29), so the issue was that `formatCurrency` was using an invalid decimal separator for some currencies like NOK or DKK.

It should've been addressed in 54c46c8:

May-28-2020 13-54-09

**Comment by kwight** [comment]
This works great @mmtr 🎉 

One thing I find a little odd was going from dollar default (USD 0.50) to kroner (NOK 3.00), then back to USD – my brain expected USD 0.50, because I hadn't changed anything, but it stays at 3.00. I don't think there's anything that needs to be changed here, it was just an observation.

**Comment by gwwar** [comment]
> Actually, just found out that values for <input type="number"> elements need to always use a dot notation for decimals according to the spec,

Yes, the number localization support is a bit spotty :D. We're also dealing with money in a language that only supports numbers as floats so it'd probably be safer to eventually refactor to a string input with validation on client/server. That's a much bigger refactor though and we're tracking that in 

https://github.com/Automattic/wp-calypso/issues/42592

**Comment by gwwar** [comment]
> One thing I find a little odd was going from dollar default (USD 0.50) to kroner (NOK 3.00), then back to USD – my brain expected USD 0.50, because I hadn't changed anything, but it stays at 3.00.

We could fix that by checking to see if the user has edited the input field, vs us updating with defaults, but I'd agree that it's not blocking. @kwight do you mind adding an issue to track?

**Comment by mmtr** [comment]
I had to rebase to make the CI jobs to pass (re-running them didn't have any effect) and now the approval has been dismissed. @Automattic/serenity or @Automattic/earn would you mind giving a quick ✅ here to unblock merging this PR and D44042-code?

**Comment by mmtr** [comment]
Not sure what's blocking the merging now 🤔. Tests are green in D44042-code and this PR is approved. @Automattic/jetpack-crew do we need anything else?

**Comment by jeherve** [comment]
> do we need anything else?

Yes, a review from Crew :) Looking at it now.

**Comment by mmtr** [comment]
> > do we need anything else?
> 
> Yes, a review from Crew :) Looking at it now.

Oh, right! I thought the merging process maybe changed because Crew were not auto-added as reviewer like in previous PRs I worked on.

**Comment by mmtr** [comment]
Had to rebase again to regenerate the build in D44042-code (it wasn't applied cleanly, likely some changes to JP blocks have been recently merged) and that dismissed your review @jeherve. Would you mind re-approving?

**Comment by kraftbj** [comment]
r208274-wpcom

**Pull request merged**
