### PR TITLE
Add filters to the `js_templates` callback values

### PR DESCRIPTION
**Pull request by simonwheatley**
Possible solution for #2189 

This adds filters to the `js_templates` callback values, to allow other developers to override them.

### CODE REVIEW

**Comment by georgestephanis** [comment]
I far prefer the implementation in #2191

**Comment by simonwheatley** [comment]
I'm going to slightly refactor to separate out the `add_action` and `apply_filters` on this line, with the aim of making it clearer (and easier to document the hooks):

```php
add_action( "admin_footer-$hook", apply_filters( 'jetpack_landing_page_js_templates_callback', array( $this, 'js_templates' ), $hook ) );
```

**Comment by simonwheatley** [comment]
Second thoughts: it's fine and I need a screen break. Thanks for documenting the hooks, @jeherve :smiley:

**Comment by simonwheatley** [comment]
@kraftbj @zinigor I think this PR is ready when you are. :smile:

**Comment by zinigor** [comment]
Looks good!

**Comment by dereksmart** [comment]
:+1:

**Pull request merged**
