### PR TITLE
JS Components: Convert JetpackFooter component to TypeScript

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Changes proposed in this Pull Request:
* This PR converts `JetpackFooter` component to TypeScript.
* It also converts the `JetpackFooter` stories and unit tests to TS
* Adds more test cases for `JetpackFooter` unit tests

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Checkout the PR
* Run `cd projects/js-packages/storybook && pnpm run storybook:dev`
* Confirm that all the stories of `JetpackFooter` component work as expected
* Check the consumers of `JetpackFooter` and related components and confirm that they work as expected
* Check for any regression

Screenshot 2022-08-01 at 1 37 26 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202276314264001

### CODE REVIEW

**Comment by dhasilva** [comment]
It seems the controls are not there anymore:
https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-jetpack-footer--default

Before | After
------|------
Screenshot_2022-07-29_17-33-36-bef | Screenshot_2022-07-29_17-33-11

**Comment by manzoorwanijk** [comment]
> It seems the controls are not there anymore: https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-jetpack-footer--default

That's strange, I can see all the controls
Screenshot 2022-08-01 at 1 24 56 PM

**Comment by manzoorwanijk** [comment]
> It seems the controls are not there anymore: https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-jetpack-footer--default

@dhasilva Thank you for catching that. It looks like an issue with Storybook that default props don't seem to work with ES6 default values - https://github.com/storybookjs/storybook/issues/9626

I have added explicit default values.

**Review by dhasilva — APPROVED** [review]
:rocket: 
Screenshot_2022-08-01_10-30-48

**Review by retrofox — APPROVED** [review]

**Comment by manzoorwanijk** [comment]
r249899-wpcom

**Pull request merged**
