### PR TITLE
Masterbar: replace "Add new site" with "Add New Site"

### PR DESCRIPTION
**Pull request by AntonyRafael**
Fixes https://github.com/Automattic/wp-calypso/issues/50698

Replace "Add new site" with "Add New Site" #50698 on  projects\plugins\jetpack\modules\masterbar\admin-menu\class-wpcom-admin-menu.php

### CODE REVIEW

**Comment by jeherve** [comment]
Thanks for the contribution. As you can see in the list of checks below, you'll also need to update Unit Tests to match the new expected string. This needs to happen in `tests/php/modules/masterbar/test-class-wpcom-admin-menu.php`, for the `test_add_new_site_link` test.

I would also ask that you add some testing instructions for your changes, so one can easily test and review your suggested changes.

Thank you!

**Comment by AntonyRafael** [comment]
thank you very much for the tips @jeherve ! I will correct them right now 😀

**Comment by obenland** [comment]
Hey @AntonyRafael, have you had a chance to look into this again?

**Review by AntonyRafael — COMMENTED** [review]
Hey @obenland,, I corrected the unit tests I believe that now this PR will pass in all.

**Comment by obenland** [comment]
Thanks so much! I removed the merge conflicts and requested reviews as a next step.

**Comment by mmtr** [comment]
Thanks @AntonyRafael! Code changes look good. Note that you also need to address a couple of issues required by the CI checks:
- Add changelog: https://github.com/Automattic/jetpack/pull/18995/checks?check_run_id=2299360400. See instructions at https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#using-the-jetpack-changelogger.
- Fix linting issue: https://github.com/Automattic/jetpack/pull/18995/checks?check_run_id=2299386691

**Comment by AntonyRafael** [comment]
I thank you for the opportunity to contribute, added the changelog and corrected the linting error. now i believe i will pass all tests =)

**Review by mmtr — COMMENTED** [review]
Thanks @AntonyRafael! This tests well for me: 
Screen Shot 2021-04-09 at 15 44 43

However, I'm not sure we want to switch to a "Title Case" format since I had the impression we were trying to adapt a "Sentence case" format. I asked @cpapazoglou in https://github.com/Automattic/wp-calypso/issues/50698#issuecomment-816698236 for more context around why he opened that issue.

**Comment by mmtr** [comment]
All good now, @cpapazoglou clarify that the reason is to stay aligned with Core (https://github.com/Automattic/wp-calypso/issues/50698#issuecomment-817679485).

**Review by mmtr — APPROVED** [review]

**Comment by mmtr** [comment]
Internal reference: Deployed to WP.com in r224117-wpcom

**Pull request merged**
