### PR TITLE
[Package] Jetpack Backup: add review request component

### PR DESCRIPTION
**Pull request by nunyvega**
Create ReviewRequest component to prompt for a plugin review after a successful event:

Screen Shot 2022-07-22 at 01 25 20

#### Changes proposed in this Pull Request:

* Stop using ContextualUpgradeTrigger to ask for plugin review
* Add option to dismiss message
* Add JetpackOption to save dismiss value

#### Jetpack product discussion

P2 discussion: pbuNQi-3bh-p2
P2 project thread: pbuNQi-3eS-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
- Create Jurassic Ninja site. You can use this link:
https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=add/component-review-request&wp-debug-log
You can add &nojetpack at the end to run it without the JP plugin.
- Buy a Backup subscription and complete the initial backup
- Go to cloud.jetpack.com, add the SSH credentials and run a restore
- Once the restore is completed, verify that the message asking for a review is visible and that the link points to the plugin review page
- Click on the dismiss button and the component should hide
- Refresh the page and the component should not show

### CODE REVIEW

**Comment by nunyvega** [comment]
Hi @keoshi could you take a glance at this proposal for this new component I'm introducing here?
 It's based in the Contextual Upgrade Trigger component but has some extra logic for review requests on Backups, and adds a dismiss button.

**Comment by keoshi** [comment]
@nunyvega This is looking good!

To make it more distinct from the CUT and to make it more fun, I wonder if we could swap the arrow for an emoji. We could even swap the emoji out for a different one of hover as a silly easter egg.

One thing I'd recommend is changing the copy for the dismissal. “Maybe later” is more descriptive and more positive/hopeful.

Jul-22-2022 14-14-13

Edit: it seems like the padding on the original screenshot is slightly different from [our documentation](https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-contextual-upgrade-trigger--default)?

**Comment by nunyvega** [comment]
Thanks @keoshi , I'll give that a try!
About the padding, the PR to fix it [is here](https://github.com/Automattic/jetpack/pull/25131)

**Review by oskosk — APPROVED** [review]
LGTM

**Pull request merged**
