### PR TITLE
Custom CSS module: Add missing blank.css (404s when using Replacement Mode)

### PR DESCRIPTION
**Pull request by inderpreet99**
When using Replacement mode ("Replace theme's css") in Custom CSS module, a `blank.css` file should be output on the frontend. However, there is no `blank.css` file in the module, so it 404s.

### CODE REVIEW

**Comment by georgestephanis** [comment]
I'm not 100% sure if moving the file is wise -- this code does sync with WordPress.com and moving the location may affect it there.

**Comment by inderpreet99** [comment]
The file did not exist previously in the repo. I created it. While looking at the location, I realized it might be better served to place the new file in the `css` dir, rather than outside it.

I'd be perfectly fine if it was placed outside the `css` dir. So, do what works best for WordPress.com.

Let me know if you need me to submit another PR. Thanks.

**Comment by samhotchkiss** [comment]
@michaeldcain - is this going to cause you any headaches?  If not, let's get it in

**Comment by dereksmart** [comment]
Yep this is fine.  I will add the corresponding blank.css to the dotcom side as well.  weird that we're calling it though, as it exists nowhere.

**Comment by dereksmart** [comment]
synced in wpcom `r119963-wpcom`

**Pull request merged**
