### PR TITLE
Avoid local eslint errors from e2e dirs

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

We have the e2e test directories in separate pnpm workspaces because
they require large downloads for playwright that are not normally needed
in local development. But that can cause problems when trying to run
eslint as the plugins referenced from eslintrc are not available.

To avoid that, let's adjust the eslint configurations in the e2e dirs to
detect this situation and avoid trying to lint at all.

#### Jetpack product discussion

p1643055734132300/1643054245.126200-slack-CBG1CP4EN
p1642686982001900-slack-CBG1CP4EN
p1636751680290600-slack-CBG1CP4EN
p1634153125426300-slack-CBG1CP4EN
p1643631857393939/1634153125.426300-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Clone a fresh checkout. `pnpm install && pnpm lint-required` should succeed, with a note about eslint being disabled in `projects/plugins/boost/tests/e2e`.
* Do `CI=true pnpm lint-required`. This time it should fail with an error about being unable to find `jetpack-e2e-commons/.eslintrc.cjs`.
* Do `pnpm --dir projects/plugins/boost/tests/e2e install`, then run `pnpm lint-required` again. It should succeed, this time with no note about eslint being disabled.

### CODE REVIEW

**Comment by kraftbj** [comment]
That feels like a lot of boilerplate to add to each plugin. Is there a way to DRY it out?

**Comment by anomiex** [comment]
It would probably work to just change the `require.resolve( 'jetpack-e2e-commons/.eslintrc.cjs' )` to `'../../../../../jetpack-e2e-commons/.eslintrc.cjs'` in the two plugin files.

**Comment by anomiex** [comment]
> It would probably work to just change the `require.resolve( 'jetpack-e2e-commons/.eslintrc.cjs' )` to `'../../../../../tools/e2e-commons/.eslintrc.cjs'` in the two plugin files.

Well, it kind of works. If you happen to have run `pnpm install` in tools/e2e-commons/ but not the plugin directory, it still fails in that case.

**Comment by anomiex** [comment]
Another way to DRY it would be to do something like
```js
const loadIgnorePatterns = require( '../../../../../tools/js-tools/load-eslint-ignore.js' );
const eslintCheckPnpmInstall = require( '../../../../../tools/something.js' );

module.exports = eslintCheckPnpmInstall( __dirname, require, 'jetpack-e2e-commons/.eslintrc.cjs' ) || {
    extends: [ require.resolve( 'jetpack-e2e-commons/.eslintrc.cjs' ) ],
    ignorePatterns: loadIgnorePatterns( __dirname ),
};
```
Or something more specific to E2E could probably be like
```js
const eslintConfigForE2E = require( '../../../../../tools/e2e-commons/something.js' );

module.exports = eslintConfigForE2E( __dirname, require );
```

**Comment by kraftbj** [comment]
> Another way to DRY it would be to do something like
> 
> ```js
> const loadIgnorePatterns = require( '../../../../../tools/js-tools/load-eslint-ignore.js' );
> const eslintCheckPnpmInstall = require( '../../../../../tools/something.js' );
> 
> module.exports = eslintCheckPnpmInstall( __dirname, require, 'jetpack-e2e-commons/.eslintrc.cjs' ) || {
>     extends: [ require.resolve( 'jetpack-e2e-commons/.eslintrc.cjs' ) ],
>     ignorePatterns: loadIgnorePatterns( __dirname ),
> };
> ```

To me, this seems like a fair compromise between being overly verbose while helping make clear what's happening.

**Comment by adimoldovan** [comment]
Maybe we can stop excluding the e2e directories.

Right now, the browser binaries are downloaded in the `postinstall` script in e2e-commons, via the `playwright install` command. Playwright caches the binaries and they are only downloaded when a new version of Playwright is released (they usually release once a month). 

We can:
- remove the `postinstall` script and include the `playwright install` in the `test:run` command => binaries are downloaded only when actually needed, if there's a new version, or cache deleted. On the downside, every e2e project needs to include this command in `test:run`
- remove the `postinstall` script. Playwright throws a friendly error prompting the user to run `playwright install` => binaries are downloaded only when actually needed, if there's a new version, or cache deleted. The downside, users get an error, we'll probably get pinged for it from time to time.
- do nothing => binaries are downloaded even if not needed, but only if there's a new version, or cache deleted.

**Comment by anomiex** [comment]
Either the first or second bullets sound like they could be ok to me. The third is pretty much why we separated things in the first place.

**Comment by anomiex** [comment]
Took a shot at the first bullet in #22709

**Comment by anomiex** [comment]
Did #22709 instead.

**Pull request closed without merging**
