### PR TITLE
Simple Payments: Add generic currency fallback symbol

### PR DESCRIPTION
**Pull request by sirreal**
If a currency were missing from a simple payment, we'd just have a number.

#### Changes proposed in this Pull Request:

* In case of a missing currency, add a [generic fallback symbol](https://en.wikipedia.org/wiki/Currency_sign_(typography)): &curren;
* Update the fallback layout to as `{symbol}{value}`.
* i18n number format the value with 2 decimals.

#### Testing instructions:

It's intentionally not easy to have a missing currency. Simple Payment product should be made via UI and backend sanitization that attempts to ensure the data is well formed.

Try this patch to force the fallback to show:

```patch
diff --git a/modules/simple-payments/simple-payments.php b/modules/simple-payments/simple-payments.php
index a00850e81..31a719981 100644
--- a/modules/simple-payments/simple-payments.php
+++ b/modules/simple-payments/simple-payments.php
@@ -264,6 +264,7 @@ class Jetpack_Simple_Payments {
 	 * @return string           Formatted price.
 	 */
 	private function format_price( $price, $currency ) {
+		$currency = '';
 		$currency_details = self::get_currency( $currency );
 
 		if ( $currency_details ) {
```
```patch
diff --git a/modules/simple-payments/simple-payments.php b/modules/simple-payments/simple-payments.php
index a00850e81..31a719981 100644
--- a/modules/simple-payments/simple-payments.php
+++ b/modules/simple-payments/simple-payments.php
@@ -264,6 +264,7 @@ class Jetpack_Simple_Payments {
 	 * @return string           Formatted price.
 	 */
 	private function format_price( $price, $currency ) {
+		$currency = 'UNKNOWN';
 		$currency_details = self::get_currency( $currency );
 
 		if ( $currency_details ) {
```

#### Proposed changelog entry for your changes:

None.

#### Screens

`es_ES` locale. Uses `.` as thousands marker and `,` as decimal marker.

##### No currency:

screen shot 2018-11-09 at 14 08 13

##### Unrecognized currency:

screen shot 2018-11-09 at 14 08 32

### CODE REVIEW

**Comment by brbrr** [comment]
@sirreal WPCOM tests are failing (D20550-code). Would you mind taking a look?

**Comment by brbrr** [comment]
Looks like this PR needs rebase. I can not see s SP block in JN site otherwise

**Comment by sirreal** [comment]
Rebased

**Comment by sirreal** [comment]
The WPCOM test failures do not appear to be related. I'm happy to rebase and give this a try after the next release. This is not a high priority change.

**Comment by jeherve** [comment]
What happens if in the future we remove currencies that were previously included, like in #10581? Should we cover that use-case as well? I tried to remove a currency after creating a product using that currency, but removing support for that currency did not change the display of the product widget or block.

**Comment by sirreal** [comment]
> I tried to remove a currency after creating a product using that currency, but removing support for that currency did not change the display of the product widget or block.

How did you remove the currency? The currency is stored with the saved product (custom post type). If the formatter knows how to render that currency, it will.

We could validate currencies when we render the shortcode, what should we do if they're unsupported? Would we hide the output?

**Comment by jeherve** [comment]
> How did you remove the currency?

I might not have done it the right way. I followed the lead of what we had done in #10581.

**Review by jeherve — DISMISSED** [review]
It works for me. 👍

**Comment by jeherve** [comment]
@sirreal Is this something you are still interested in merging?

**Comment by sirreal** [comment]
Yes, I'd be happy to get this landed. I believe we held off because WPCOM tests were failing, but I've rerun them and they're green now.

@simison care to review and we can land this?

**Review by simison — APPROVED** [review]
Rebased + tested, works well!

I tested the Guten-block and the widget in the customizer.

Tested with known currencies, unknown currencies and an empty string as a currency.

Nice little fallback, thanks for improving this!

**Comment by sirreal** [comment]
Approval was dismissed, I'm blocked on merging this. @jeherve would you mind either approving and/or just proceeding to merge?

**Review by jeherve — APPROVED** [review]
Approving again, and merging.

**Pull request merged**
