### PR TITLE
Add new endpoint `attach-licenses` to Jetpack Plugin endpoints and API `js-package`

### PR DESCRIPTION
**Pull request by cbauerman**
#### Changes proposed in this Pull Request:

* Add new method `attach-licenses` to jetpack plugin
* Add support for new `attach-licenses` endpoint to `api` js package
* Add test to `licensing` package to clarify expected return 

#### Jetpack product discussion

Part of the on-going Jetpack License-based checkout project ( p1HpG7-cS-p2 )

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Verify new tests pass
* Make requests from console on Jetpack dashboard:

```
jQuery
  .ajax({
    url: "/wp-json/jetpack/v4/licensing/attach-licenses",
    method: "post",
    beforeSend: function (xhr) {
      xhr.setRequestHeader("X-WP-Nonce", Initial_State.WP_API_nonce);
    },
    contentType: "application/json",
    dataType: "json",
    data: JSON.stringify( {
        licenses: [
            'test'
        ]
    })
  })
  .done(function (response) {
    console.log(response);
  })
  .error(function (error) {
    console.log(error.responseText);
  });

```

with an invalid license like above, we would expect an array response with an error inside
Screen Shot 2021-11-09 at 1 38 43 PM

whereas with a proper license we would expect a proper response with the `activatedProductId`:
Screen Shot 2021-11-09 at 1 47 29 PM

### CODE REVIEW

**Review by rcanepa — DISMISSED** [review]
LGTM.

Code changes look sound (we already tested them in your previous PR that included a UI). 

Thanks for adding those tests 🙏🏻

**Review by jeherve — COMMENTED** [review]
Thanks for breaking this down.

I'm curious about the addition of a new method, vs. using the existing implementation that allowed to attach multiple licenses if necessary. Was this not an option to pass an array of one license?

**Comment by jeherve** [comment]
> It was really about me being unwilling to change the return type of the existing method. The new method will return the activated product Id

Ah, that makes sense. would an additional optional parameter to change the return type be an option / make sense? I'm mostly asking to avoid any potential confusion / provide additional context when we come back to that class in a few months / years.

**Comment by cbauerman** [comment]
> Ah, that makes sense. would an additional optional parameter to change the return type be an option / make sense? I'm mostly asking to avoid any potential confusion / provide additional context when we come back to that class in a few months / years.

Actually given that `attach_licenses` is not used at all I would prefer to completely replace it. If a compelling need arises for it later we can revisit, but at the moment we are going to be the first project to leverage the non-js licensing package.

**Comment by cbauerman** [comment]
> > Ah, that makes sense. would an additional optional parameter to change the return type be an option / make sense? I'm mostly asking to avoid any potential confusion / provide additional context when we come back to that class in a few months / years.
> 
> Actually given that `attach_licenses` is not used at all I would prefer to completely replace it. If a compelling need arises for it later we can revisit, but at the moment we are going to be the first project to leverage the non-js licensing package.


> > Ah, that makes sense. would an additional optional parameter to change the return type be an option / make sense? I'm mostly asking to avoid any potential confusion / provide additional context when we come back to that class in a few months / years.
> 
> Actually given that `attach_licenses` is not used at all I would prefer to completely replace it. If a compelling need arises for it later we can revisit, but at the moment we are going to be the first project to leverage the non-js licensing package.

Giving this more thought, it is needlessly incompatible. However, I will take your point that largely duplicating the method can be confusing. I will refit this PR to instead add the attach licenses method tests to make sure we are getting back the response we want.

**Comment by rcanepa** [comment]
> Giving this more thought, it is needlessly incompatible to remove things. However, I will take your point that largely duplicating the method can be confusing. I will refit this PR to instead add the attach licenses method tests to make sure we are getting back the response we want, and add it to the `api` package.

Just to verify that I understand this right. Instead of adding the new `attach_license` method, we will rely on the existing `attach_licenses` (with an s at the end) method. Is that correct? If so, this PR will only include a test to ensure the method returns what is expected, i.e., the id of the activated product, right?

**Comment by cbauerman** [comment]
So, new state of the new PR is this:

- This PR has minimal changes that touch multiple packages ( see PR description )
- We are moving them to a standalone PR to make the new package touch fewer package versions
- It is ready for review

**Comment by cbauerman** [comment]
> Just to verify that I understand this right. Instead of adding the new `attach_license` method, we will rely on the existing `attach_licenses` (with an s at the end) method. Is that correct? If so, this PR will only include a test to ensure the method returns what is expected, i.e., the id of the activated product, right?

Yes, except we can use this PR to add in an api endpoint our js-package will require.

**Review by rcanepa — APPROVED** [review]
Thanks for cleaning up this PR and explaining the reasoning behind these changes.

The approach makes sense to me and will certainly work well with the activation flow js-package. 

It ran some tests from the JS Console and things worked as expected.

**Review by jeherve — CHANGES_REQUESTED** [review]
This is looking good, but it's going to need a rebase before we can approve.

**Comment by cbauerman** [comment]
> This is looking good, but it's going to need a rebase before we can approve.

PR is clean again, ready to merge!

**Review by jeherve — APPROVED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by anomiex** [comment]
r235226-wpcom

**Pull request merged**
