### PR TITLE
General: Update description

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes https://github.com/Automattic/jetpack/pull/19822#issuecomment-839747973

#### Changes proposed in this Pull Request:

* Removes "the" from the description.

#### Jetpack product discussion

p1620818588110700/1620771107.102600-slack-GQK64C7B4

#### Does this pull request change what data or activity we track or use?

n/a

#### Testing instructions:

* n/a
*

### CODE REVIEW

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
You might want to change the repo description too (go to https://github.com/Automattic/jetpack and look at the "About" in the right sidebar).

**Comment by anomiex** [comment]
I see there's also similar text at [projects/plugins/jetpack/class.jetpack-connection-banner.php:385](https://github.com/Automattic/jetpack/blob/be8f01512cc7f28020c7aff56183a065194af99c/projects/plugins/jetpack/class.jetpack-connection-banner.php#L385) and [projects/plugins/jetpack/readme.txt:15](https://github.com/Automattic/jetpack/blob/be8f01512cc7f28020c7aff56183a065194af99c/projects/plugins/jetpack/readme.txt#L15).

**Comment by kraftbj** [comment]
@robertbpugh I defer to you on where, if anywhere else, we should tweak the description. My understanding is we're only looking at the text used in this particular place right now.

**Comment by kraftbj** [comment]
Rob green-lit the additional changes. Pushed and ready for re-review.

**Review by samiff — APPROVED** [review]
Couldn't find any more instances. Will you be updating the sidebars Brad mentioned @kraftbj ?

**Comment by kraftbj** [comment]
Yup!

**Pull request merged**
