### PR TITLE
Fix/pro (security) settings cards

### LINKED ISSUE #4495: Admin Page: can't install / activate Akismet & VaultPress from the admin page
jetpack43-bubel1

Switching the toggles on should allow one to turn on the plugins, and configure them maybe?

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #4495 && #3989 && #4481

This replaces the Pro settings toggles with buttons/notices mocked in p6TEKc-xF-p2.

**Note that this does not do anything to the content within the card itself.  That will be done in a following PR**

To test: 

**Akismet:**
- Active and installed
- Active and installed with no API key
- Inactive and installed
- Uninstalled

**Scan:**
- VaultPress Active and installed
- VaultPress Active and installed with spoofing a threat. You can change the `0` to any number in [this line](https://github.com/Automattic/jetpack/pull/4500/files#diff-5d91be5e15745cca6f9fc3fdb7b0483bR83)
- VP inactive but installed
- VP uninstalled

**Backups:**
- VaultPress Active and installed
- VP inactive but installed
- VP uninstalled

cc @jeffgolenski or @MichaelArestad for help with fixing the width of the notices with too much text, like 
screen shot 2016-07-21 at 5 28 01 pm

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@dagobertrenouf What's the link to the mockup for reference?

**Comment by dagobertrenouf** [comment]
@MichaelArestad I don't think I have anything to do with this :)

**Comment by MichaelArestad** [comment]
Sorry. 

@dereksmart What's the link to the mockup for reference?

**Comment by dereksmart** [comment]
@MichaelArestad it's linked in the design master thread

**Comment by MichaelArestad** [comment]
I'm unable to find the screenshot. @jeffgolenski can you review this?

**Comment by jeffgolenski** [comment]
Testing now.

@MichaelArestad for ref: 

premium feature states - 02

**Comment by jeffgolenski** [comment]
Tested your list of scenarios @dereksmart 

Everything in the settings areas looks good in regards to compact buttons and compact notices functionality. As mentioned, I just need to make a width adjustment to the foldable cards to accommodate the notices. 

I did however find some related issues for the dashboard to which I posted over at: https://github.com/Automattic/jetpack/issues/4540

cheers.

**Comment by jeffgolenski** [comment]
@dereksmart 

My latest commit takes care of the foldable card header styles. This is good to go from the design end.

BEFORE:
screen shot 2016-07-30 at 1 24 03 pm
screen shot 2016-07-30 at 1 25 25 pm


AFTER:
large screens...
screen shot 2016-07-30 at 2 27 14 pm

small & medium screens...
screen shot 2016-07-30 at 2 27 01 pm

super small screens...
screen shot 2016-07-30 at 2 26 49 pm

**Pull request merged**
