### PR TITLE
Widget Visibility: Apply widget filtering to customizer preview

### LINKED ISSUE #21446: Widget Visibility Doesn't Work in Customizer
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Turn on Widget Visibility module in Jetpack
2. Add widgets with conditions to restrict their visibility
3. Changes are not reflected in Customizer preview

### A clear and concise description of what you expected to happen.

The Customizer view should reflect what shows on the front-end of the site. 

### What actually happened

At present, widgets show in Customizer regardless of the visibility conditions you setup. By contrast, if you go to the actual site you will see a different view depending on how you have configured the Widget Visibility.

For example, a widget set to display only on the "blog" page will show everwhere in Customizer, while on the frontend it will show only when the criteria is met.

### Other information

Possibly related to:

* Automattic/jetpack/pull/20255

First reported here:

* Automattic/jpop-issues/issues/7024
* https://wordpress.org/support/topic/widgets-visibility-on-customizer/?view=all

### Operating System

macOS

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

v93

### PR DESCRIPTION
**Pull request by dsas**
The customizer screen was not applying saved visibility rules for
widgets in the preview on the right hand side. This change addresses
that by distinguishing between the customizer and the preview using the
`customize_changeset_uuid` GET var.

Note that when widget visibility rules are first added they will not be
respected until the preview is reloaded, e.g. by navigating inside the
preview or by refreshing page.

Fixes #21446

#### Changes proposed in this Pull Request:

* Preview part of Customizer screen will apply saved widget visibility rules when loaded

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* Go to /wp-admin/customize.php
* Press 'Widgets'
* Add a widget
* Use the 'three dots' menu to 'Show more settings'
* Scroll down to 'Advanced'
* Add a visibility rule like 'Show this block if page is about'
* Notice the widget disappear
* In the previewer, navigate to 'About', notice that the visibility rule is applied and you can see the widget
* In the previewer, navigate to any other page, notice that the visibility rule is applied and you cannot see the widget
* Refresh the whole page, notice that the visibility rule is applied and you cannot see the widget

Install and activate the [classic widgets](https://wordpress.org/plugins/classic-widgets/) plugin, and repeat the above. 

Should be tested again on wp.com by applying patch to your sandbox.

### CODE REVIEW

**Comment by sdixon194** [comment]
@dsas  - this PR is labeled as `in progress` still - I just wanted to check and see if this was still the case or if it's ready for review.

**Comment by dsas** [comment]
hey @sdixon194, I'm afraid it's still incomplete, it fixes part of the problem but not all of it from memory. I'll pick it back up on Monday and better document the status, or finish it up.

**Review by mmtr — APPROVED** [review]
This works well on my tests.

**Review by jeherve — APPROVED** [review]

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM in rWP235585-wpcom

**Pull request merged**
