### PR TITLE
REST API: Add list modules v1.2 endpoint

### PR DESCRIPTION
**Pull request by fgiannar**
Introduces a new v1.2 endpoint for listing modules.

#### Changes proposed in this Pull Request:

* Updates the min. max versions in the existing v1 modules list endpoint
* Adds a new v1.2 endpoint for listing modules that returns additional module info (same as `v4` endpoint excluding the `options` field)

#### Jetpack product discussion

p9dueE-2Lm-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
D60475-code

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I may be missing something here, but would it not be an option to use the existing `jetpack_modules` key in the `/sites/%s` endpoint?
https://github.com/Automattic/jetpack/blob/ac97b73710de4a9e901993f980e18d7ffd8965f5/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L405-L409

Or to expand on that instead of having to rely on `Jetpack_Admin` and a new endpoint?

**Comment by fgiannar** [comment]
> I may be missing something here, but would it not be an option to use the existing `jetpack_modules` key in the `/sites/%s` endpoint?
> https://github.com/Automattic/jetpack/blob/ac97b73710de4a9e901993f980e18d7ffd8965f5/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L405-L409
> Or to expand on that instead of having to rely on `Jetpack_Admin` and a new endpoint?

@jeherve Thanks for your suggestions, Jeremy! The reason I approached it like this was because of the corresponding core endpoint that uses this logic.
Essentially we need a `v1.*` endpoint that returns the modules the same way the existing `v4` core endpoint [does](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L192).

If there's an alternative given the above restriction I would be glad to incorporate it in order to avoid adding a new endpoint.

**Comment by jeherve** [comment]
> Essentially we need a v1.* endpoint that returns the modules the same way the existing v4 core endpoint does.

Thanks for the extra details!

In this case, is it okay that this endpoint will take `requires_user_connection` into account, while the core endpoint doesn't?

**Comment by fgiannar** [comment]
> > Essentially we need a v1.* endpoint that returns the modules the same way the existing v4 core endpoint does.
> 
> Thanks for the extra details!
> 
> In this case, is it okay that this endpoint will take `requires_user_connection` into account, while the core endpoint doesn't?

Great question! Yes, the core endpoint should actually be updated as well to take this into account but I intended to do so in another PR.

**Pull request merged**
