### PR TITLE
Social Menus: bring back SVG contents

### LINKED ISSUE #38959: Widgets: Social Icons Jetpack not Working in 13.7
### Impacted plugin

Jetpack

### Quick summary

The "Social Icons (Jetpack)" widget in Jetpack v13.7 isn't loading the icons

### Steps to reproduce

1. Install Jetpack 13.6
2. Add the "Social Icons (Jetpack)" widget (may need to add classic-widgets plugin)
3. Add social links and see the icons work
4. Upgrade to 13.7
5. See that the icons no longer work

### A clear and concise description of what you expected to happen.

Social icons should be working

### What actually happened

13.6: 

Annotation on 2024-08-19 at 16-55-02

13.7:

Annotation on 2024-08-19 at 16-55-15

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #38959

## Proposed changes:

Those were removed in #38573

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Go to Appearance > Themes 
* Install and activate a classic theme like the Twenty Ten theme.
* Go to Plugins > Add New
* Install and activate the Classic Widgets plugin.
* Go to Appearance > Widgets
* Drag and add a Social Icons widget to your sidebar.
* Add a few social networks to the widget's settings: `https://twitter.com/jetpack/` for example, or `https://www.facebook.com/jetpackme`
* Save your changes
* Check the frontend
    * The icons should be displayed properly.

### CODE REVIEW

**Comment by jeherve** [comment]
@danluu As you continue to work on image optimizations, it may be worth making sure this didn't happen with other SVG files in the repo I think.

**Review by coder-karen — APPROVED** [review]
This tests well for the Social Icon widget and Social Menus, thanks!

**Comment by danluu** [comment]
> @danluu As you continue to work on image optimizations, it may be worth making sure this didn't happen with other SVG files in the repo I think.

Sorry about that! I thought that `imagemagick compare` found these to be the same. I'll try to figure out what happened there.

**Comment by supernovia** [comment]
@jeherve any thoughts on whether this could affect themes, too?  I'm seeing broken social icons menus for all classic themes on atomic sites

**Comment by anomiex** [comment]
ImageMagick's `compare` doesn't seem to work on SVGs, which is why in the other PR I said "the non-SVGs". 🙂

**Comment by anomiex** [comment]
Plus, nothing visually changed in these two SVGs themselves anyway: they don't have any visible output when viewed directly. They exist to be written into the page HTML, where the `<symbol>` elements can then be referenced externally.

**Comment by danluu** [comment]
> ImageMagick's compare doesn't seem to work on SVGs, which is why in the other PR I said "the non-SVGs". 🙂

Whoops, thanks for pointing that out again!

I wonder if I should just revert all of the SVG changes since there's clearly some kind of bug in the optimization tool and this could've introduced other issues, and the SVGs tend to be relatively small, so the savings matters a lot less than for the big PNGs and JPEGs.

**Comment by anomiex** [comment]
I don't see anything else doing exactly what these two SVGs are doing. Looking for other stuff with `<defs>` and IDs that look like they may not be internal, I see the following files:
* `projects/plugins/crm/fonts/fontawesome-webfont.svg`
* `projects/plugins/jetpack/_inc/fonts/automatticons/automatticons.svg`
* `projects/plugins/jetpack/_inc/genericons/genericons/Genericons.svg`
* `projects/plugins/protect/assets/fonts/jetpack-protect.svg`
* `projects/plugins/vaultpress/fonts/vaultpress-regular.svg`

> I wonder if I should just revert all of the SVG changes since there's clearly some kind of bug in the optimization tool and this could've introduced other issues, and the SVGs tend to be relatively small, so the savings matters a lot less than for the big PNGs and JPEGs.

That would be the safest thing IMO.

**Pull request merged**
