### PR TITLE
CRM: Make form fonts smaller

### PR DESCRIPTION
**Pull request by gogdzl**
## Proposed changes:

This PR changes our input fonts (and some others) to the default size/family used by Jetpack.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p1HpG7-lcQ-p2

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:

To test this do a tour around the CRM and check for inconsistencies in font sizes/family.
Most notable changes:

Edit Contact:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=contact&zbsid=1`

Edit Company:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=company&zbsid=1`

Edit Quotes:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=quote&zbsid=1`

Edit Invoice:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=invoice&zbsid=1`

Edit Transaction:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=transaction&zbsid=1`

Edit Forms:
`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=form&zbsid=1`

### CODE REVIEW

**Comment by tbradsha** [comment]
Fonts are smaller in lots of places. I don't like the big gap between labels and fields, but will the label ultimately end up above the field as per the P2? If so, it's a non-issue.

It does look like we missed some textarea font sizes (e.g. on the Forms editor):
image

Likewise, we've got all sorts of font sizes on the WooSync pages (ignoring the dynamic count text):
image

Inconsistent font sizes in `/wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=event`:
image

Other than a click-through, though, I'm not sure the best way to review. Perhaps have Design take a look, or else fix the above and consider an iterative approach.

**Review by tbradsha — CHANGES_REQUESTED** [review]
Along with my comments above, I only saw one blocker: we shouldn't be editing a third-party library's code (`projects/plugins/crm/sass/semantic-ui/elements/_input.scss`). Instead, we should override the code elsewhere. :^)

**Comment by gogdzl** [comment]
> It does look like we missed some textarea font sizes (e.g. on the Forms editor):

Fixed.

> Likewise, we've got all sorts of font sizes on the WooSync pages (ignoring the dynamic count text):

This PR is focused in changing first forms, we will take an iterative approach making these changes. That being said, this change is out of scope. Please note that this will be merged in a feature branch, so it is safe to do so.

> Other than a click-through, though, I'm not sure the best way to review. Perhaps have Design take a look, or else fix the above and consider an iterative approach.

That's the idea!

Could you give it another go?

**Review by tbradsha — APPROVED** [review]
Looks good!

**Pull request merged**
