### PR TITLE
Manual Updates: Make sure manual updates are applied when auto updates are disabled

### PR DESCRIPTION
**Pull request by gavande1**
Fixes https://github.com/Automattic/dotcom-forge/issues/10096

## Proposed changes:

* It fixes a problem with manual plugin updates not being applied when auto-update is disabled for the plugin in WP Admin. 
* It fixes a problem by not using the `JETPACK_PLUGIN_AUTOUPDATE` constant in plugins modify endpoint

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Get WoA test site and install jetpack beta tester plugin 
* Once installed go to Jetpack -> Jetpack Beta -> Jetpack
* Select `fix/manual-plugin-updates` in feature branch option
* Download and Install an older version of .org plugin for example [Download Manager](https://wordpress.org/plugins/download-manager/advanced)
* Goto `/wp-admin/plugins.php` and disable auto-updates for the plugin. 

CleanShot 2024-12-10 at 12 33 01@2x

* Now goto All sites plugins view on WordPress.com. (https://wordpress.com/plugins/download-manager if you are using download-manager for testing)
* On the right end, look for an option to manage sites and click on it. 
CleanShot 2024-12-10 at 12 34 31@2x

* Upon clicking the button, the modal will be shown with the option to update the plugin on the site.  

CleanShot 2024-12-10 at 12 35 51@2x

* Click on the `Update to [Version]` button. 
* Wait for a few seconds while you see the success message.
* Go to`/wp-admin/plugins.php` and make sure updates are applied.

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as advertised. I can upgrade the plugin without any errors as described. I have also tested other upgrade scenarios successfully. LGTM!

|Plugin before | Upgrading|Plugins after|
|-------|------|------|
| CleanShot 2024-12-10 at 15 41 40@2x|  CleanShot 2024-12-10 at 15 41 11@2x  |     CleanShot` 2024-12-10 at 15 41 48@2x  |

**Review by jeherve — APPROVED** [review]
Tests well for me. 🚢

**Comment by ouikhuan** [comment]
@gavande1  Thanks for the ping, although I'm not familiar with how the original `JETPACK_PLUGIN_AUTOUPDATE` constant works, but looks like we're also using it to identify if it's doing an autoupdate during the update action. See: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/sync/src/modules/class-plugins.php#L153 This might be affected after this change.

**Comment by gavande1** [comment]
@ouikhuan, Based on my findings, the `JETPACK_PLUGIN_AUTOUPDATE` constant ensures the Jetpack plugin is auto-updated to the newest version. We set it to `true` in wpcomsh. My changes are scoped into the plugin modify endpoint only. It shouldn't affect other auto-update processes. Anyway, I have merged the pull request; I will monitor its deployment and see if we have any adverse effects because of my changes.

**Comment by ouikhuan** [comment]
@gavande1 Cheers, thanks for the context.

**Comment by fgiannar** [comment]
@gavande1 Hi there, I was led here as part of investigating an issue related to duplicate plugin update events displayed in the Activity Log.
Looks like this causes duplicate events in the Activity Log because we don't sync the JETPACK_PLUGIN_AUTOUPDATE constant anymore as @ouikhuan already pointed out above.
Please checkout my comment [here](https://linear.app/a8c/issue/ACTLOG-11/activity-logs-server-and-unknown-icons#comment-3dc08e01) for full context.

**Pull request merged**
