### PR TITLE
Carousel - fix bug with carousel swiper clashing with slideshow swiper

### LINKED ISSUE #20263: Carousel: Error With Slideshow Block
When a gallery block and a slideshow block are on the same page together (either in the same post, or on separate posts that are being displayed on the same page, like a homepage showing latest posts), it's not possible to close the carousel lightbox. 

To reproduce:

- enable the carousel
- Publish a post with a gallery and a slideshow block
- on the live post, click on an image in the gallery to open the carousel
- See how you're not able to close it.

When clicking the close button, the browser throws `Uncaught TypeError: e.destroy is not a function`

Surfaced during testing: p8oabR-GM-p2#comment-5382

### PR DESCRIPTION
**Pull request by glendaviesnz**
Fixes #20263

#### Changes proposed in this Pull Request:
* Give carousel swiper instance a unique class

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Check our PR and add a standard gallery block and a slideshow block to a single post
* Make sure that both galleries work correctly in the frontend

Before:
before-swiper

After:
after-swipe

### CODE REVIEW

**Review by sdixon194 — DISMISSED** [review]
Nice, I tested this out in individual posts, a home page, and with a gallery in the widget area and everything worked fine 👍 

Leaving open for a team review so someone more familiar with the code can take a look, but as soon as it's approved we can merge and cherry pick.

**Review by ramonjd — DISMISSED** [review]
Nice fix, thanks, Glen. 

Added a tiled gallery, regular gallery and a slideshow. All work as expected

gallery-double

**Comment by glendaviesnz** [comment]
@sdixon194  I don't think we need to worry about the broken WPcom diff with this one as we need to do a custom WPcom diff to bring across all the Carousel changes, so go ahead and merge if you are ok with that

**Comment by ramonjd** [comment]
I've just committed a change that also customizes the pagination and next/prev element class names. 

The pagination dots weren't showing on pages that had a carousel **and** a slideshow.

**Before**
Screen Shot 2021-07-06 at 11 31 05 am


**After**
Screen Shot 2021-07-06 at 12 08 37 pm


The prev/next element class names I updated as a preventative measure. :)

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.9` in a8e4b8b9d80e854323b25a74bea7bddec647862a

**Pull request merged**
