### PR TITLE
Tiled Gallery Block: allow in Offline Mode.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Classic Tiled Galleries (created via the Classic editor or within a Classic block in the block editor) can be used even when the site is in Offline mode, ever since #521.

The Tiled Gallery block, however, behaves differently; it requires an active connection. Let's try to be consistent with the feature by:

- Registering the Tiled Gallery block even when the site is in offline mode.
- Adding a new utility in the block editor to detect if a site is in offline mode.
- Short-circuiting and avoid trying to use Photon for Tiled gallery images in the block editor when a site is in offline mode.

#### Jetpack product discussion

* None, but this PR is a good follow-up from #13471 where we made the block not rely on the Photon module being active, and being more dynamic instead. 
* For reference, tiled gallery settings remain a bit confusing. #7576 is where this is discussed.

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

I would suggest testing on two different sites:

* One that's connected to WordPress.com.
    * The Tiled Gallery block should remain available in the block editor.
    * When publishing a post with a tiled gallery, you should see it use Photon for its images once published.
* One that's using [Offline mode](https://jetpack.com/support/development-mode/)
    * The Tiled Gallery block should now be available in the block editor.
    * Galleries should look good in the editor and on the frontend.
    * Gallery images should not be using Photon.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
This works correctly for me, although I couldn't reproduce the offline issue on latest stable. I also noticed that the photon toggle is still toggle-able, which I feel like I'd expect not to be the case in offline mode? 

Set offline by adding define( 'JETPACK_DEV_DEBUG', true ); to a JN's wp-config.

**Comment by jeherve** [comment]
> I also noticed that the photon toggle is still toggle-able, which I feel like I'd expect not to be the case in offline mode?
> Set offline by adding define( 'JETPACK_DEV_DEBUG', true ); to a JN's wp-config.

Could it be that Photon was active on your site before you switched on Offline mode?
Do you experience similar issues when using Offline mode on a fresh new install, before to even connect to WordPress.com, or on `https://localhost`?

**Comment by sdixon194** [comment]
> Could it be that Photon was active on your site before you switched on Offline mode?

Nope, I didn't activate photon at all. Same for localhost and on a clean JN install, and before connecting to wpcom. Photon toggle is always available to be activated, and tiled gallery shows up.

**Comment by jeherve** [comment]
Ah yes, I was able to reproduce. That's an issue with the toggle. I took care of this bug in #20555.

**Comment by jeherve** [comment]
r229845-wpcom

**Pull request merged**
