### PR TITLE
Use Modules class in My Jetpack

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

For Hybrid products use the new `Modules` class to activate modules and check if product is active

This allows hybrid products such as Search and Social to better integrate with My Jetpack, as they also use the Modules abstraction

#### Jetpack product discussion

p9dueE-55u-p2#comment-7978

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Spin up a new JN site with Jetpack Beta
* Activate Boost and Search on this branch
* Deactivate and delete Jetpack
* Connect Boost
* Go to My Jetpack and connect your user (we need to do this while we don't fix the purchase flow)
* Back to My Jetpack, click "Purchase" on the Search card and follow the flow. Buy Search
* You should go back to the Search dashboard with all enabled
* Go to My Jetpack and confirm the card shows Search as active with a "Manage" button
* Click Manage and confirm you go to the Search plugin page
* Deactivate Search (the toggle on the Search dashboard, not the plugin)
* Go back to My Jetpack and confirm the product appears as not active, with an "Activate" button
* Click Activate
* Go to Search page and confirm Search and Instant Search are re-enabled

### CODE REVIEW

**Review by kangzj — DISMISSED** [review]
This works well and looks good to me, just need a version bump 🎉

**Comment by leogermani** [comment]
Also enabling Instant Search now

**Comment by kangzj** [comment]
Hi @leogermani thanks for working on this, we are getting there yay 🎉 

I found an issue testing. When clicking activate for search, the search plugin is activated and but the UI didn't show any thing. It works on the second clicking. Steps to reproduce:

- Prepare a site with Search plugin deactivated, Boost installed and site fully connected
- Open My Jetpack admin page
- Click Activate button on Search product card
- Search is activated but the UI doesn't show success
- Click Activate button on Search product card again
- UI shows success

I had a look and it seems, `Plugins_Installer::is_plugin_active( )` doesn't return true if called direct after activation. We possibly want to clear cache. see:

https://github.com/Automattic/jetpack/blob/8d4703b56ed1084394dc366e83df291d11424135/projects/packages/my-jetpack/src/products/class-product.php#L293

https://github.com/WordPress/WordPress/blob/f6412575c890bf651cdaa8a2d60365c19f0d4173/wp-admin/includes/plugin.php#L276

And also I tweaked the available modules filter for search a bit, hope you don't mind.

Cheers.

**Comment by kangzj** [comment]
Revert my changes in 822bb which breaks tests, will do the refactoring in a another PR.

**Review by retrofox — DISMISSED** [review]
I followed the testing steps described in the PR description, and it works as expected.
A pair of extra 👀 won't hurt.
Anyway, LGTM.

**Comment by leogermani** [comment]
Sorry, just pushed a small fix. I was passing some useless parameters in `is_active`.. probably left overs of copying and pasting.

As you can see, these params don't exist: https://github.com/Automattic/jetpack/blob/update%2Fmy-jetpack-hybrid-module-activation/projects/packages/status/src/class-modules.php#L25

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by kangzj** [comment]
Good job @leogermani 🎉 
I cannot reproduce the issue on master, so I think all good 👍

**Pull request merged**
