### PR TITLE
Fix some styling inconsistencies in the disconnect flow

### PR DESCRIPTION
**Pull request by jboland88**
This PR fixes a few styling inconsistencies that affect the disconnect flow when the Gutenberg plugin is active.

#### Changes proposed in this Pull Request:

* This PR includes CSS changes to fix some styling inconsistencies that appear in the disconnect flow when the Gutenberg plugin is active.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* On a Jetpack test site, test first with the master branch to see the issue.
* On your test site, install the Gutenberg plugin: https://wordpress.org/plugins/gutenberg/
* Activate the Gutenberg plugin
* From the Jetpack Dashboard, in the "Site Connections" area, click on the "Manage site connection" link to open the disconnect flow.
* You should see the disconnect flow modal that looks like this:
Screen Shot 2021-12-06 at 9 40 26 AM
* Notice that there is extra whitespace at the top of the modal and that the modal is not width-limited, it scales with the width of the screen. As a consequence of the modal scaling, the CTA buttons appear to be aligned incorrectly - they should be on the left side of the modal.
* Now, deactivate the Gutenberg plugin and open the disconnect flow by repeating the steps above. Notice that the additional whitespace at the top of the modal is gone and the modal is limited to a max width of 1200px:
Screen Shot 2021-12-06 at 9 40 54 AM

* Switch now to this branch on your test site and activate the Gutenberg plugin. Even with the Gutenberg plugin active, the disconnect modal should look like the second screenshot with no styling inconsistencies.
* Test the remainder of the flow by disconnecting and providing feedback. Ensure that the width of the modal remains consistent and there is no additional whitespace showing at the top of the modal.

### CODE REVIEW

**Comment by sdixon194** [comment]
This works for me! I noticed one other inconsisency - if you decline the feedback after disconnecting, you're taken to this page which has some broken styling. Not related to this PR, though.

Screen Shot on 2021-12-06 at 13:01:25

Is this something worth addressing now as well, or leave that for a follow up?

**Comment by jboland88** [comment]
@sdixon194 
Very interesting. I can reproduce the button style inconsistency you showed in in the screenshot, but only after exiting the disconnect flow! For some reason it seems like the styles for the Gutenberg plugin and the Jetpack plugin are enqueued in a different order if you go through the disconnect flow vs going directly to the connect screen on a site that is already disconnected.

The `<ActionButton />` component  is used there. I'd say let's handle that change in a separate issue/ PR to keep this one moving. I can put something together for it.

Thanks for pointing that out!

**Review by sdixon194 — APPROVED** [review]

**Comment by jboland88** [comment]
r236140-wpcom

**Comment by sdixon194** [comment]
This was cherry picked to the release branch in c8edd919ccc23891ddd6c0157835ad7241ed7dbc

**Pull request merged**
