### PR TITLE
My Jetpack: Update licensing feature flag default

### PR DESCRIPTION
**Pull request by ebinnion**
Once #24395 is in, we should be in a state where the licensing UI in My Jetpack is ready for production. We now simply need to enable the licensing UI.

#### Changes proposed in this Pull Request:

* Updates the feature that controlled displaying the licensing UI in My Jetpack to default to true.

#### Jetpack product discussion

NA

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Checkout branch
* Install Jetpack
* Go to Jetpack Dashboard > My Plan
* Click "Activate a product" button and ensure that you land in licensing UI in My Jetpack
* Go to My Jetpack dashboard
* Ensure that "Activate a license" link shows in the "Your Plan" section
* Set `add_filter( 'jetpack_my_jetpack_should_enable_add_license_screen', '__return_false' );`
* Go to Jetpack Dashboard > My Plan
* Click "Activate a product" button and ensure that you stay in the main Jetpack dashboard
* Go to My Jetpack dashboard
* Ensure that you do not see a link to "Activate a license"

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
In testing, after adding the filter (I'm adding it using a code snippets plugin), clicking 'Activate a Product' exists and sends me to this page: `wp-admin/admin.php?page=jetpack#/license/activation`. So the link has changed from `wp-admin/admin.php?page=my-jetpack#/add-license`, but the page content is still the same (the 'add a licence key page').

With the snippet added, the 'Activate a License' link has however now gone from the My Jetpack dashboard as expected, based on the testing instructions.

**Comment by ebinnion** [comment]
Your comment sums up the expected behavior.

The feature flag that we're modifying here controls whether we use the licensing activation UI as packaged in the Jetpack plugin or as packaged in My Jetpack. Specifically, this PR changes the default such that we're defaulting to using the licensing activation UI in My Jetpack. This is important for allowing licensing activation for standalone plugins.

The licensing activation UI is nearly identical. There are some minor differences, basically the UI in My Jetpack has the "back" button and it also has the My Jetpack footer.

**Review by coder-karen — DISMISSED** [review]
> There are some minor differences, basically the UI in My Jetpack has the "back" button and it also has the My Jetpack footer.

Oh yes, I see that now.

Thanks for clarifying, I was misunderstanding the testing instructions, thinking that staying in the main dashboard meant not seeing the 'Add a license key' UI at all.

Acts as expected then! 🚢

**Review by coder-karen — APPROVED** [review]
An extra approval as tests were failing due to package versions, so a new commit updates those.

**Pull request merged**
