### PR TITLE
[Subscriptions] Add/redirect url once token is set in cookie

### PR DESCRIPTION
**Pull request by millerf**
Follow-up on this comment: https://github.com/Automattic/gold/issues/36#issuecomment-1735025461 and 6719026-zen

Content creators are complaining the access token is available and could eventually be shared amongst users.

This PR tries to fix it by reloading the page once it is saved in the session (cookie).

## Proposed changes:

* Redirect to the sae URL without the token param once it is set 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Subscribe to any test site and notice the "token" in the URL when coming back from payment
* Reloading the page should keep the param
Screenshot 2023-10-02 at 16 29 39

* Patch this on your sandbox (or use this branch on Jetpack beta) and reload the page
=> the URL should now be without "token"
=> you should still have access to the content
Screenshot 2023-10-02 at 16 38 05

### CODE REVIEW

**Review by n3f — APPROVED** [review]
WFM :shipit:

**Comment by kraftbj** [comment]
@ice9js did this get reverted per p1696930413601329/1696911339.732729-slack-C02FMH4G8 ?

**Comment by ice9js** [comment]
Not yet. It needs to be done manually hence the delay, I'm working on it now.

**Comment by millerf** [comment]
@ice9js I am back. Do you want me to revert it?

**Pull request merged**
