### PR TITLE
Customizer widgets: enqueue script dependencies 

### LINKED ISSUE #19980: Slideshow block: broken in block widgets
When added as a block widget the Slideshow block does not display in the customizer or on the frontend.

#### Steps to reproduce the issue

1. In local dev run latest Jetpack and gutenberg master/trunk and latest built of 5.8 core
2. Go to customizer widgets on a non-block theme, eg. tt1 standard and add a slideshow block. Notice that the block does not display correctly in the customizer preview, or on the frontend

**Screenshots**
Screen Shot 2021-05-31 at 10 49 42 AM

### PR DESCRIPTION
**Pull request by ramonjd**
Fixes https://github.com/Automattic/jetpack/issues/19980

Related to:
https://github.com/Automattic/jetpack/pull/20257

#### Changes proposed in this Pull Request

In https://github.com/Automattic/jetpack/pull/20044 we wrote the `view.js` script to the page so that blocks would have their scripts immediately available in the preview window after insertion from the **Customizer > Widgets** panel.

To ensure the inserted blocky wock has all the scripts/dependencies it needs to thrive we also jave to add its dependencies.

We've set a `defer` attribute to the block's `view.js` script to make sure it runs when the DOM is ready.

Screen Shot 2021-07-09 at 2 16 54 pm

As a bonus, we've also removed the invalid `isLarge` prop on the `<FormFileUpload />` component in the Slideshow block. This is free. You don't have to pay for it. :) It was throwing the following error:

Screen Shot 2021-07-09 at 2 11 24 pm

ALSO!

We've added a Twenty Twenty One compat fix to ensure the slideshow doesn't break out of the widget container:

**Before**
Screen Shot 2021-07-15 at 8 09 47 am

**After**
Screen Shot 2021-07-15 at 8 08 30 am

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

Running Jetpack + WordPress 5.8 or above, head over to **Customizer > Widgets**

Add the following blocks:

1. Tiled Gallery: add images and play with the gallery in the preview.
2. Slideshow: add images and play with the slideshow in the preview. Check that the console doesn't complain about the invalid `isLarge` prop.
3. Gif: search for GIF (try ponies!)
4. Other blocks (except Maps block 😄 ). Try to break it!
5. Switch to the 2021 theme and make sure the widgets (the slideshow in particular) look dandy

They should work in both the widgets editor and the preview (and the frontend).

Save and refresh the Customizer. It should look as you set it.

### CODE REVIEW

**Review by stacimc — DISMISSED** [review]
🎉 This is testing great for me! I tested with Gif, Gallery, Slideshow, and Premium Content in the customizer, the site editor, and the post editor. I'm getting some errors with the Map block but I see the same errors on master.

Pinging @apeatling on this just to double check if there's anything I haven't thought of since he worked in this area, but this LGTM!

**Comment by ramonjd** [comment]
@glendaviesnz has been testing this (Thank you!) and noticed that the Maps block is still complaining about dependencies (@wordpress/elements > Component).

Screen Shot 2021-07-12 at 1 16 47 pm

I'm not entirely sure why this is yet.

It would be nice to be able to work out a way to ensure dependencies are loaded dynamically for all blocks in the preview iframe.

I even tried this for the heck of it:

```php
				foreach ( $script_dependencies as $script_dependency ) {
						wp_enqueue_script( $script_dependency );
				}
				global $wp_scripts;
                foreach( $wp_scripts->queue as $handle ) {
	                if ( in_array( $wp_scripts->registered[ $handle ]->handle, $script_dependencies ) ) {
	                    echo '<script id="jetpack-block-' . esc_attr( $wp_scripts->registered[ $handle ]->handle ) . '" src="' . esc_attr( $wp_scripts->registered[ $handle ]->src ) . '" async></script>';
					}
				}
```

I'm testing on localhost using `wp-env`.

Strangely, the Maps block was working for me using Jurassic Tube. Maybe a caching issue.

**Comment by andrewserong** [comment]
I've only had a very quick glance, but it looks like the Map block maybe isn't listing its required dependency `wp-element` when it calls `load_assets_as_required`, here: https://github.com/Automattic/jetpack/blob/HEAD/projects/plugins/jetpack/extensions/blocks/map/map.php#L101 and here: https://github.com/Automattic/jetpack/blob/5605eb656d65149dbeebec31077bc13c8ea1d1a2/projects/plugins/jetpack/extensions/blocks/map/map.php#L148 — do we need to add an array as a second param to those calls? Not sure if it needs other dependencies, too?

**Comment by ramonjd** [comment]
> it looks like the Map block maybe isn't listing its required dependency wp-element when it calls load_assets_as_required

Thanks for looking!

Normally this would be taken care of by the `load_scripts_as_required` method, which is called by `load_assets_as_required`. It looks at the block's view.asset.php file and loads the dependencies:

https://github.com/Automattic/jetpack/blob/5605eb656d65149dbeebec31077bc13c8ea1d1a2/projects/plugins/jetpack/class.jetpack-gutenberg.php#L616

The map block's view assets file looks like: 

`<?php return array('dependencies' => array('lodash', 'wp-components', 'wp-dom-ready', 'wp-element', 'wp-i18n', 'wp-polyfill', 'wp-token-list'), 'version' => '4cef56c35a27e2a8b70e8e53f690b783');`

**Comment by andrewserong** [comment]
Ah, gotcha, that makes sense! Apologies for missing that with my quick drive-by 🙂

**Comment by stacimc** [comment]
> the Maps block is still complaining about dependencies (@wordpress/elements > Component).

@ramonjd Yep, this is the same error I mentioned in my review -- for me, I get this error on master as well, for which there's an existing issue #19976 (did not initially see that was linked on this PR). FWIW as this fixes Slideshow without regression, I think this could be merged if the Map issue is unlinked.

**Comment by glendaviesnz** [comment]
I agree with @stacimc that we should keep this as the slideshow fix and handle the map block separately.

**Comment by ramonjd** [comment]
Thanks folks! I've unlined the Maps issue.

**Comment by sdixon194** [comment]
Did some testing on this one. Everything worked fine in Twenty Nineteen, however when testing Twenty Twenty One, it looks like something is up with the slideshow. The only block that wouldn't work for me and wouldn't show the images (no console errors)

Screen Shot on 2021-07-13 at 16:58:52

**Comment by ramonjd** [comment]
> Everything worked fine in Twenty Nineteen, however when testing Twenty Twenty One, it looks like something is up with the slideshow. The only block that wouldn't work for me and wouldn't show the images (no console errors)

Thanks for testing @sdixon194 

This looks to me like a theme-specific issue too. All good on 2019, but the only way I can get things to look right in 2021 is to add `overflow: hidden` to the `<section />` element we wrap around the preview widgets (Selector `[data-customize-partial-type="widget"]`)

https://user-images.githubusercontent.com/6458278/125556413-32188bbf-17ba-4b21-96c4-478f3d04728e.mp4

Looks like these are [added in WordPress Core
](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/js/customize-preview-widgets.js#L417)

I don't know if this is the best fix since 2019 has `width: 100%;` and some other styles. It probably needs dedicated investigation outside this PR's scope.

So I'm wondering whether we should target the theme directly or ensure that it's not a generic issue affecting multiple blocks + themes.

I can't seem to find a block-specific way to fix this either as the slideshow block wants to take up the width of it's parent container.

**Comment by sdixon194** [comment]
> So I'm wondering whether we should target the theme directly or ensure that it's not a generic issue affecting multiple blocks + themes.

I think we can address it in a separate PR, but we'll definitely want to make sure that gets in before the next point release. I did a lot of testing with a handful of other themes, but so far Twenty Twenty One is the only one I've encountered the issue with, so a theme specific fix is probably okay for now.

**Comment by ramonjd** [comment]
> but we'll definitely want to make sure that gets in before the next point release. I did a lot of testing with a handful of other themes, but so far Twenty Twenty One is the only one I've encountered the issue with, so a theme specific fix is probably okay for now.

Thanks @sdixon194 TIL about the compat file. I've added it to this PR.

**Comment by sdixon194** [comment]
> Thanks @sdixon194 TIL about the compat file. I've added it to this PR.

Nice! I did some testing, and it looks like it's now ok in the customizer, but seems broken in the live site though :/ 

Screen Shot on 2021-07-15 at 09:13:36


Only in Twenty Twenty One. Other themes continue to work fine.

**Comment by glendaviesnz** [comment]
Same for me, works in customizer but not in front end. I think it is because `data-customize-partial-type="widget"` isn't used on the front-end, so needs a different selector to get the `overflow:hidden` added there. It is a shame we can't just target the slideshow widget (i can't see a way of doing this) as I wonder if adding that overflow property to all the widget containers is going to have an unforeseen impact on other widget content?

**Comment by ramonjd** [comment]
Thanks @glendaviesnz and @sdixon194 

I'll have a play around today to see if I can target that block.

**Comment by ramonjd** [comment]
> Nice! I did some testing, and it looks like it's now ok in the customizer, but seems broken in the live site though :/

I see that the problem affects all widgets, not just the slideshow. So right now I believe it's a more fundamental issue with theme:


**On the frontend, with overflow hidden on applied to** `.widget-area .widget_block`

Screen Shot 2021-07-16 at 11 19 16 am


**Without**
	
Screen Shot 2021-07-16 at 11 19 25 am

**Comment by ramonjd** [comment]
Google to the rescue:

https://css-tricks.com/preventing-a-grid-blowout/ 

🚀

**Comment by sdixon194** [comment]
Nice! This all works well for me now! 🎉

**Review by sdixon194 — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to release branch in ce37d0f81262c740dfaf2e7222adbd8391f11cdb

Also manually passed the wpcom teamcity test, so the wpcom diff will have to be handled manually 👍

**Pull request merged**
