### PR TITLE
svelte-data-sync-client: Remove unneeded JS deps

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

This package does not appear to actually use zod or tslib. Further, it doesn't need its own linting commands (and associated deps) as we have those at the monorepo level.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Is CI happy? Does everything still work?

### CODE REVIEW

**Review by pyronaur — CHANGES_REQUESTED** [review]
I'm not sure about tslib, copied it over from `js-packages/images-guide` assuming it was necessary for TypeScript to compile.

`zod` is currently unused because this is a skeleton package, I'll flesh it out next week, but it's very much needed here. I added it so that I don't have to deal with asking for pnpm lock reviews next week.

**Comment by pyronaur** [comment]
@anomiex How do you lint and reformat a specific project quickly at the monorepo level? That part of the config is copied over from Boost, so if there's an option to do that now, I think it needs fixing in both places.

**Comment by anomiex** [comment]
JS linting from the monorepo root can be done with `pnpm lint-file`, or `pnpm lint-required` if you want to lint everything not in the exclude list.

Reformatting is generally done by the pre-commit hooks, but `pnpm reformat-files` exists at the root too.

**Comment by anomiex** [comment]
Also, if zod is going to be used in a follow-up soon, feel free to adjust this PR.

**Comment by thingalon** [comment]
Is there a way to lint a specific directory in the monorepo? I've lost count of how often I've wanted that functionality :)

**Comment by anomiex** [comment]
`pnpm lint-file` can be passed directories too.

**Comment by pyronaur** [comment]
@anomiex `lint-file` doesn't run prettier, is there a way to make it run prettier too?

**Comment by jeherve** [comment]
> @anomiex `lint-file` doesn't run prettier, is there a way to make it run prettier too?

`reformat-files` should be what you're looking for here.

**Comment by pyronaur** [comment]
But that's going to to be extremely slow running on the whole monorepo, especially as the number of files increases.

**Comment by jeherve** [comment]
> But that's going to to be extremely slow running on the whole monorepo, especially as the number of files increases.

That's true. It may be worth adding a new script to run prettier on provided directories instead of that existing command. That's probably for another PR though :)

**Pull request closed without merging**
