### PR TITLE
Update phpcs-changed

### PR DESCRIPTION
**Pull request by kraftbj**
phpcs-changed updated to use `--git-base` as a more flexible alternative to --git-branch

#### Changes proposed in this Pull Request:

* Bumps phpcs-changed

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

n/a
#### Testing instructions:

* n/a
*

#### Proposed changelog entry for your changes:

* n/a

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
You'll need to update composer.lock again, it seems.

**Comment by kraftbj** [comment]
@anomiex It seems like the only difference is the hash. Are you aware of a functional reason the difference in hash between the PR version and the GH version would make a difference?

Thinking out loud, is there a way to make this check a little more permissive if this is the only delta? Is there a downside to that?

**Comment by kraftbj** [comment]
Or have the action commit the change to composer.lock itself if the change is only one line, etc.

**Comment by anomiex** [comment]
> @anomiex It seems like the only difference is the hash. Are you aware of a functional reason the difference in hash between the PR version and the GH version would make a difference?

If the hash is the only difference, it means that you changed composer.json in some way that doesn't change which packages are installed and doesn't change any of the other metadata that's tracked in composer.lock. That probably means there's no functional difference, other than that anyone running `composer install` is going to have a warning about the lock file not being up to date.
```
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

> Thinking out loud, is there a way to make this check a little more permissive if this is the only delta? Is there a downside to that?

Just that the repo can be in a state where anyone running `composer install` will get that warning.

> Or have the action commit the change to composer.lock itself if the change is only one line, etc.

We probably could. I wonder if it would be annoying if you push a change, then make a fix only to find that it won't let you because the bot pushed the commit in the mean time.

**Comment by kraftbj** [comment]
> We probably could. I wonder if it would be annoying if you push a change, then make a fix only to find that it won't let you because the bot pushed the commit in the mean time.

Unless you also changed composer.lock, just a merge should take care of it, but ¯\_(ツ)_/¯

**Review by anomiex — APPROVED** [review]
Looks like there's no actual change in behavior, they just renamed the parameter to be more accurate.

We should probably do the same for our eslint-changed, but if you want that can be a separate PR.

**Pull request merged**
