### PR TITLE
E2E Tests: Check if Chrome installed locally

### LINKED ISSUE #17870: Local E2E test runs assume they're on a Mac with Google Chrome installed
#### Steps to reproduce the issue

1. Be on Linux, or (probably) on a Mac without Google Chrome installed.
2. Follow the instructions in tests/e2e/README.md to configure the e2e tests.
3. Follow the instructions in tests/e2e/README.md to attempt to run the e2e tests.

#### What I expected

Tests run.

#### What happened instead
```
yarn run v1.22.4
$ NODE_CONFIG_DIR='./tests/e2e/config' NODE_CONFIG_ENV=test JEST_PUPPETEER_CONFIG=tests/e2e/jest-puppeteer.config.js jest --config tests/e2e/jest.config.js --runInBand --verbose
Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/src/automattic/jetpack/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/usr/local/src/automattic/jetpack/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Workaround

Edit tests/e2e/jest-puppeteer.config.js to change the hard-coded path to point to an installation of Chrome or Chromium.

### PR DESCRIPTION
**Pull request by brbrr**
Fixes #17870

#### Changes proposed in this Pull Request:

* Add check for a Mac OS and Chrome when running tests locally

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

n/a
#### Testing instructions:

* Test on MacOS without Chrome 😬 
* Make sure code make sense

#### Proposed changelog entry for your changes:

* n/a

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Thanks!

<details>
<summary>Still not working for me on Linux, but it gives a different error now when I try it.</summary>

```
yarn run v1.22.4
$ NODE_CONFIG_DIR='./tests/e2e/config' NODE_CONFIG_ENV=test JEST_PUPPETEER_CONFIG=tests/e2e/jest-puppeteer.config.js jest --config tests/e2e/jest.config.js --runInBand --verbose tests/e2e/specs/connection.test.js
Error: Failed to launch the browser process!
[1123/124717.766729:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55e520d96219 base::debug::CollectStackTrace()
#1 0x55e520cfa363 base::debug::StackTrace::StackTrace()
#2 0x55e520d0c195 logging::LogMessage::~LogMessage()
#3 0x55e52258800e service_manager::ZygoteHostImpl::Init()
#4 0x55e520903f27 content::ContentMainRunnerImpl::Initialize()
#5 0x55e520952afa service_manager::Main()
#6 0x55e520902501 content::ContentMain()
#7 0x55e5209518f5 headless::(anonymous namespace)::RunContentMain()
#8 0x55e52095159d headless::HeadlessShellMain()
#9 0x55e51e4c6aa7 ChromeMain
#10 0x7f4294706cca __libc_start_main
#11 0x55e51e4c68ea _start

Received signal 6
#0 0x55e520d96219 base::debug::CollectStackTrace()
#1 0x55e520cfa363 base::debug::StackTrace::StackTrace()
#2 0x55e520d95d61 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f4296677140 <unknown>
#4 0x7f429471bc41 gsignal
#5 0x7f4294705537 abort
#6 0x55e520d94b65 base::debug::BreakDebugger()
#7 0x55e520d0c634 logging::LogMessage::~LogMessage()
#8 0x55e52258800e service_manager::ZygoteHostImpl::Init()
#9 0x55e520903f27 content::ContentMainRunnerImpl::Initialize()
#10 0x55e520952afa service_manager::Main()
#11 0x55e520902501 content::ContentMain()
#12 0x55e5209518f5 headless::(anonymous namespace)::RunContentMain()
#13 0x55e52095159d headless::HeadlessShellMain()
#14 0x55e51e4c6aa7 ChromeMain
#15 0x7f4294706cca __libc_start_main
#16 0x55e51e4c68ea _start
  r8: 0000000000000000  r9: 00007ffc6b25a260 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffc6b25b528 r13: 00007ffc6b25a500 r14: 00007ffc6b25b530 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007ffc6b25a260  bp: 00007ffc6b25a4b0  bx: 00007f42930a5d40
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f429471bc41  sp: 00007ffc6b25a260
  ip: 00007f429471bc41 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/src/automattic/jetpack/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/usr/local/src/automattic/jetpack/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**Comment by anomiex** [comment]
I'm going to remove the 9.2 milestone here, the code freeze is today and this doesn't seem like it actually matters for the release.

**Comment by brbrr** [comment]
That's interesting. I'm not sure what's going on :) @anomiex can you explain how did you workaround it (as mentioned in https://github.com/Automattic/jetpack/pull/17868#pullrequestreview-536672094)

**Comment by anomiex** [comment]
My workaround was to just set the hard-coded path to /usr/bin/chromium, since I happen to have Chromium installed on my machine.

It seems like the real fix might be to just "live dangerously" and pass `--no-sandbox`, at least that's what people online seem to suggest. When I add that to the args in tests/e2e/jest-puppeteer.config.js it runs the tests.

**Review by anomiex — APPROVED** [review]
Works for me now!

**Pull request merged**
