### PR TITLE
Sitemaps: Fix the Hook from init to wp_loaded for Sitemap URL handler.

### PR DESCRIPTION
**Pull request by rutviksavsani**
Fixes #

## Proposed changes:

* This PR proposes to generate the permalinks on the `wp_loaded` hook instead of the `init` hook which would allow us to get all our plugins and theme changes loaded and the modified permalinks being generated properly.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
Steps to reproduce:

1. Setup a sitemap with active Jetpack and Sitemaps active.
2. Upload this plugin which registers a custom post type at a priority of 11 and adds it to the News Sitemap.
Plugin gist link : https://gist.github.com/rutviksavsani/4cd931d72a981b637a2b3d745ca5c359
3. Add a new post to the Artist post-type.
4. Now on checking the URL of the post on the News post-type, You should be able to see a raw URL and not a final Permalink.
5. Now when applying this PR, we should be able to see the correct URLs as we wait for all the plugins and theme actions to get registered. ( Note: Make sure to delete old Transient for new links to be showed. )

Video for reproducing:

https://github.com/Automattic/jetpack/assets/53530700/67c20d76-d94d-449e-9f87-e559a3d56290

Screenshots:

Before:
image

After: 

image

### CODE REVIEW

**Comment by monsieur-z** [comment]
It looks like a fair change to me. @nbloomf, it's been a while since [you worked on sitemaps](https://github.com/Automattic/jetpack/commit/918f0d31151c1b3ca448230804f75b36b720971b) but you might have some feedback to share. Any possible unwanted side effects?

**Review by monsieur-z — APPROVED** [review]
Works as advertised 👍

**Comment by monsieur-z** [comment]
A trunk rebase/merge is required.

**Comment by rutviksavsani** [comment]
Rebase done.

**Pull request merged**
