### PR TITLE
Add health check field to post fields

### PR DESCRIPTION
**Pull request by gmjuhasz**
This is a PR taken out from #25803. In this change there are the changes that involves the PHP changes to add the post field.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* See testing instructions on other PR
* This PR should not change any functionality yet, but publicize connections should work seamlessly from the editor and simple editor, and even on simple sites.

### CODE REVIEW

**Review by spsiddarthan — DISMISSED** [review]
This tests well, @gmjuhasz !

**Review by pablinos — DISMISSED** [review]
This looks good to me. I don't see the `is_healthy` field on WPCOM yet, but can see it on my local site.

**Review by pablinos — APPROVED** [review]
Still looking good!

**Comment by pablinos** [comment]
r252697-wpcom

**Pull request merged**
