### PR TITLE
Payments: Remove in-editor Stripe nudge

### PR DESCRIPTION
**Pull request by stacimc**
Fixes 178-gh-Automattic/view-design

#### Changes proposed in this Pull Request:

* Removes the old in-editor Stripe nudge on the Payments block, and adds a Connect Stripe button in the block toolbar. Similar to the work done for Premium Content.

Old version:
Screen Shot 2021-01-13 at 1 37 36 PM

New version:
Screen Shot 2021-01-13 at 12 59 52 PM

#### Testing instructions:

Use https://github.com/Automattic/a8c-wp-env to test.
* Start up a site with `npm run start`
* Check out this branch and activate jurassic.tube with npm run tube:init. 
* Activate jetpack on the new site but do not add a plan yet.
* Create a new post and insert the Payments block.
* Verify that there is an Upgrade banner, but the "Connect Stripe" button is not available in the block toolbar
* Add a "Security Daily" Jetpack plan to the site
* Go back to the post. Confirm that the upgrade banner has been removed, and the new "Connect Stripe" button is in the block toolbar (matching screenshot above)
* Click on the "Connect Stripe" button and verify that you are able to connect to a Stripe account (use the ryan.ray test stripe account in the secret store and confirm that the connection works)
* Confirm that the "Connect Stripe" button is now missing from the toolbar.

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Comment by apeatling** [comment]
@stacimc One change -- can you move the Stripe connection to be the first thing in the block toolbar, before the alignment?

**Comment by stacimc** [comment]
The Upgrade banner here (on free Jetpack sites, not wpcom) is the old version:
Screen Shot 2021-01-13 at 1 01 33 PM

This is because the Payments block's nudges are all custom, since it doesn't use the `plan_check` attribute in block registration that would allow it to get the new-style editor and frontend nudges for free. When the `jetpack_block_editor_enable_upgrade_nudge` filter is activated for jetpack, the custom code that adds this banner in can be removed and the new style of nudge will work automatically.

It is possible to manually use the refactored nudge from #18239 to at least update the styling of this custom nudge, but it won't behave the same way as the nudge that's added automatically:

1. It remains fixed above the block at all times, whereas the new-style nudge is only visible when the parent block is focused.
2. There are some styling issues related to spacing that would need to be manually tweaked for this block alone.

It's possible to fix those things but would add to the already significant amount of custom logic surrounding Payments' registration and nudges. I would suggest that we leave the nudge as is and prioritize getting the Payments block to a point where we can remove this customization.

**Comment by stacimc** [comment]
> One change -- can you move the Stripe connection to be the first thing in the block toolbar, before the alignment?

I'm not sure this is possible since the alignment control is inserted via a block support.

**Review by apeatling — CHANGES_REQUESTED** [review]
I'm not seeing the flash icon:

Screen Shot 2021-01-15 at 11 20 56 AM

I believe this is because this icon is not yet present in master, only in the Premium Content merge PR? You will need to include it separately in the meantime -- or add it in a separate PR.

**Review by apeatling — DISMISSED** [review]
Icon appearing now. :+1:

**Comment by stacimc** [comment]
Note for reviewers: this PR and #17907 both add the FlashIcon to `shared/icons`. Whichever PR gets merged second will need to rebase.

**Review by jeherve — CHANGES_REQUESTED** [review]
I'm not sure we can merge this as it is. While this works nicely for WordPress.com simple and Atomic sites, on standalone Jetpack sites folks with a free plan will be left with a block that's available, but with no indication whatsoever that it is a paid block and that it can be purchased with an upgrade.
This is caused by the issues with the previous custom implementation and that `jetpack_block_editor_enable_upgrade_nudge` filter, as you discussed earlier in this issue.

I agree that it would be nice to get rid of that custom implementation, but I don't think we can do so before we either:
- start displaying the upgrade nudges to everyone by default (see p1HpG7-aKx-p2)
- hide the block for free users just like we do for other paid blocks in Jetpack, with the `plan_check` parameter at registration.

What do you think?

**Comment by stacimc** [comment]
> I'm not sure we can merge this as it is. While this works nicely for WordPress.com simple and Atomic sites, on standalone Jetpack sites folks with a free plan will be left with a block that's available, but with no indication whatsoever that it is a paid block and that it can be purchased with an upgrade.

@jeherve  You're completely correct; this PR should only be altering the Stripe nudges. I got as far as replacing the upgrade nudge with the new styling on Jetpack but decided not to proceed for the reasons you listed above -- looks like I didn't quite finish cleaning up after myself and neglected to add the old nudge back. Thank you for catching it!

I have added the old upgrade nudge back and verified it only displays on Jetpack free sites :)

**Review by apeatling — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
This works well for me 🚢

**Comment by jeherve** [comment]
r220429-wpcom

**Pull request merged**
