### PR TITLE
Social: Add Nextdoor connection toggle

### PR DESCRIPTION
**Pull request by pablinos**
This makes the connections API call return Nextdoor connections and ensures that the icon has the correct colour.

## Proposed changes:

This adds Nextdoor to the 'known' connections when retrieving them via the API calls. It also adds the default colour to the icon for when it's displayed in the editor.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Create a Nextdoor connection on your site using D125526-code
* Load the editor and check that you can see the Nextdoor logo representing the connection

image

### CODE REVIEW

**Review by manzoorwanijk — COMMENTED** [review]
For a brief moment, I see the connection active and then it is greyed out with the notice that the connection is broken.

Screenshot 2023-10-19 at 11 43 59 AM


Debugging shows the `brokenConnections` array to be this

Screenshot 2023-10-19 at 11 46 32 AM


I can confirm that the connection in Calypso is OK.

**Comment by gmjuhasz** [comment]
> For a brief moment, I see the connection active and then it is greyed out with the notice that the connection is broken.

The editor tries the connection test endpoint after loading up, that's why it's healthy in the beginning and becomes broken afterwards when the request returns. As we cannot test the connection at the moment, we might have to hardcode to return true for nextdoor in the API too

**Comment by pablinos** [comment]
> As we cannot test the connection at the moment, we might have to hardcode to return true for nextdoor in the API too

We do at the moment, don't we? As we have the `test_connection` method returning `true`. Was your dev site sandboxing the API @manzoorwanijk ? If the Nextdoor connection wasn't coming back in the API response, then it would be broken.

**Review by manzoorwanijk — APPROVED** [review]
Works well.

> Was your dev site sandboxing the API @manzoorwanijk ?

No, that was the problem. Thanks

**Pull request merged**
