### PR TITLE
Admin menu: Add add-ons menu item

### PR DESCRIPTION
**Pull request by chriskmnds**
#### Changes proposed in this Pull Request:

Ports over changes to the admin menu for adding the "add-ons" item: D82535-code

The new add-ons menu, for now, should only appear for simple, non-atomic/jetpack sites.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

TBD

Fixes Automattic/martech#945

### CODE REVIEW

**Comment by coder-karen** [comment]
👋 It looks like this PR may be ready for review, since the changes are the same as those in the WPcom diff?

It may be that the labelling isn't quite right here but let me know if there is anything we (Crew / Ground Control) can do to help.

**Comment by chriskmnds** [comment]
> 👋 It looks like this PR may be ready for review, since the changes are the same as those in the WPcom diff?
> 
> It may be that the labelling isn't quite right here but let me know if there is anything we (Crew / Ground Control) can do to help.

Thanks. Anything to help test/confirm these changes to go on next JP release. 🙏  I've struggled with getting env and testing done. cc @dzver @gmovr if they can lend a hand

**Comment by coder-karen** [comment]
I think in this case it's more about keeping the files in sync (and confirming with test sites with this PR applied that the menu items aren't showing).

In that case it looks good to me, however there is a failing test: Test_WPcom_Admin_Menu::test_add_upgrades_menu.

For some reason I'm unable to run tests in my local environment just now, so while I debug that perhaps someone with a better understanding of tests can see what might be wrong here. @jeherve is this something you'd be familiar with?

**Comment by jeherve** [comment]
> For some reason I'm unable to run tests in my local environment just now, so while I debug that perhaps someone with a better understanding of tests can see what might be wrong here. @jeherve is this something you'd be familiar with?

You should be able to run them locally like so:

```
jetpack docker phpunit -- --filter=Test_WPcom_Admin_Menu
```

I get the same failing test on my test.

**Review by coder-karen — APPROVED** [review]
Thank you @jeherve !

So it was the changes to the tests that led to the test failures. Reverting that allows the tests to pass.

@chriskmnds  I'll be cutting the beta release tomorrow, so I'll mark this as ready to merge for now and can merge it by tomorrow morning at the latest to make sure it gets in, in case anyone else on your team wanted to take a look as well in the meantime.

**Comment by chriskmnds** [comment]
Nice work @coder-karen ! Thank you for taking ownership here 🙇

**Pull request merged**
