### PR TITLE
Admin - Post by Email: make each user have a different email address

### LINKED ISSUE #4949: Admin Page: PBE email address is the same for all users
#### Steps to reproduce the issue

1. Go to Jetpack > Settings, enable PBE.
2. Log out of your account, and log back in with a different account.
3. Go to Jetpack > Settings.
4. The PBE email address is the same as for the other user.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #4949

#### Changes proposed in this Pull Request:
- use have a different email address for each user
- allow users with edit_posts permissions to generate their address.

#### Testing instructions:
- make sure the email address of a user with edit_posts permissions, like an editor, is different than the one from another user with similar rights
- regenerate the email address of an editor, make sure it works

### CODE REVIEW

**Comment by dereksmart** [comment]
As an editor, I get a 403 when I try to regenerate my PBE email address in the new UI 

It works from `wp-admin/profile.php`

**Comment by dereksmart** [comment]
There seems to be a bug with the UI settings for any user, in that the UI is not updated when the PBE email is (re)generated from `wp-admin/profile.php`. 

For example, and editor creates/generates a PBE email for the first time from wp-admin/profile.php, and then when they navigate to the /writing settings card, the PBE email input is blank. 

It is not updated when it is regenerated for any user level.

**Comment by eliorivero** [comment]
Amend commit to fix issue with endpoint returning 403 on address creation or regeneration.

Working on the other.

Thanks for reviewing.

**Comment by eliorivero** [comment]
Fixed the other issue.

**Comment by zinigor** [comment]
Cool, works as expected for both admins and editors!

**Comment by zinigor** [comment]
I have added one commit that would remove caching using the `static` variable, which was introduced earlier in 97c13d4. I have run into a problem because of that when `$options` have gotten polluted with a non-array value.

**Comment by dereksmart** [comment]
When the secondary user is linked, this PR works as expected. 

_**However, when unlinked user...**_

We shouldn't be showing this form to unlinked users, as it won't work.  "Regenerating" the address as an unlinked user results in this: 
screen shot 2016-08-29 at 5 55 11 pm

The old settings page took this into account: 
screen shot 2016-08-29 at 5 54 53 pm

We should be doing the same in the new UI.

**Comment by eliorivero** [comment]
Tackling this in this PR

**Comment by eliorivero** [comment]
When user is unlinked, the following message shows up in the card:
captura de pantalla 2016-08-29 a las 20 50 00

**Comment by zinigor** [comment]
Tested with a non-connected non-admin, works fine!

**Pull request merged**
