### PR TITLE
Add title attribute to the iframe for the regular archive.org embed

### PR DESCRIPTION
**Pull request by rickcurran**
This commit adds a Title attribute to the iframe for the regular Archive.org book embed to improve the Section 508 and WCAG 2.0 accessibility compliance.

The change here tackles the open issue #7370 "Shortcode Embeds: should include title attribute on iframe output to meet accessibility standards" (There are multiple files which have iframes without a title attribute which are to be updated via separate PRs).

This change adds a fixed text string which would be a translatable string within Jetpack's i8ln language strings.

It also updates the test file `test-class.archiveorg.php` to include the new `title` attribute.

Fixes #

Changes proposed in this Pull Request:

A title attribute with a fixed i8ln string is added to the iframe that is rendered within this piece of code.

Is this a new feature or does it add/remove features to an existing part of Jetpack?

This adds to an existing feature of Jetpack.

Testing instructions:

To test this please try adding an Archive.org book using the archiveorg-book shortcode. E.g.

[archiveorg id=Wonderfu1958 width=320 height=240]

With the code in place the rendered iframe should now have a title attribute.

Proposed changelog entry for your changes:

This commit adds a Title attribute to the iframe for the regular Archive.org embed to improve the Section 508 and WCAG 2.0 accessibility compliance.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
You seem to have started that branch from an outdated version of `master`, so this needs a rebase. Could you rebase after pulling all latest changes into your `master` branch, as explained here:
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by rickcurran** [comment]
Weird, I thought I'd pulled in all the latest changes before doing it. I'll go sort that out.

**Comment by rickcurran** [comment]
@jeherve I'm trying to rebase this using the Github desktop app, but it seems to think that it's up to date with master and so it won't let me start a rebase? I'd thought I'd updated from master before making my new branch so this would tie in with that behaviour – I've likely done something wrong but not sure what! Any suggestions? (Sorry, I haven't rebased anything before so this is all new to me).

**Review by jeherve — APPROVED** [review]
I rebased the file for you. This should now be good to merge.

**Comment by rickcurran** [comment]
Thanks @jeherve, not sure what happened there! I'll double-check when I do the next one that I've pulled all updates from Master before making a branch for it.

**Pull request merged**
