### PR TITLE
Adds sharing buttons configuration screen.

### PR DESCRIPTION
**Pull request by zinigor**
#### Changes proposed in this Pull Request:
- Removes Sharing settings from the Engagement tab;
- Adds a new Traffic tab;
- Adds Sharing button configuration to Traffic tab;
#### Testing instructions:

[ ] This is a WIP, nothing gets saved - only the interface works, kind of.

@MichaelArestad please take a look and see if I can do better about the styles, and maybe you'll have some general comments.

sharing

#### Proposed changelog entry for your changes:
- Added new settings that allow you to change sharing buttons configuration in the new admin screen.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
From your screenshot, it looks like things are pretty close. Looks like some reset bugs, but nothing that can't be fixed quickly. I'm going to be AFK tomorrow, but will review and try to get it tested on Monday as soon as I can. I'm assuming we can drop the sharing settings in any container (including the foldable card you have it in). Will want to move it around at some point, but this works for now.

**Comment by samhotchkiss** [comment]
Closing this out as this is being reworked in the new interface

**Comment by MichaelArestad** [comment]
Unclosing this out as it simply needs to be reworked a little to match the new designs.

**Comment by rickybanister** [comment]
Sharing will henceforth occupy its own tab in settings, rather than the traffic tab. 

I would be happy enough leaving the sharing settings as calypso-only, but also happy to leave this open for now.

**Comment by samhotchkiss** [comment]
Let's roll with this as its own tab for now, we can reevaluate in the future if we feel it's necessary

**Pull request closed without merging**
