### PR TITLE
Use DEWP's new auto-wp-polyfill support

### LINKED ISSUE #39452: Blocks: require wp-polyfill only when really needed
Currently, all our blocks depend on the fairly large `wp-polyfill` package, even if they might not need it:

https://github.com/Automattic/jetpack/blob/70d1104596b18f7e16a5b705fa26c27d7581b35f/projects/plugins/jetpack/class.jetpack-gutenberg.php#L559

If I remember right, we added the dependency circa ~2019 after we had several bad breakages on the front end of the site in older Internet Explorer browsers (which we don't support anymore). I haven't actually reviewed our `view.js` builds to see if `wp-polyfill` is in any of them currently, but that might also change over time and be error-prone if we ignore it.

Meanwhile, in Gutenberg, there's some work by @sgomes on packages to depend on `wp-polyfill` only when truly needed:

- https://github.com/WordPress/gutenberg/pull/65292

This is great because now, even if we wouldn't require `wp-polyfill` for blocks, simply depending on any core package like `wp-dom-ready` would pull in the dependency anyway.

If I understand the PR correctly, [`dependency-extraction-webpack-plugin`](https://github.com/WordPress/gutenberg/tree/trunk/packages/dependency-extraction-webpack-plugin#readme) now supports the mechanism out of the box and would conditionally output the `wp-polyfill` in the `view.asset.php` file only when truly needed.

### Possible todos

- Update our use of `dependency-extraction-webpack-plugin`
- Remove [hardcoded](https://github.com/Automattic/jetpack/blob/70d1104596b18f7e16a5b705fa26c27d7581b35f/projects/plugins/jetpack/class.jetpack-gutenberg.php#L559) `wp-polyfill` dependency

cc @oskosk @kraftbj @jeherve

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

`@wordpress/dependency-extraction-webpack-plugin` has added the ability to detect a magic `/* wp:polyfill */` comment and only add `wp-polyfill` as a dependency if that is found. Since `wp-polyfill` is just a custom build of `core-js`, the intention is that `babel-plugin-polyfill-corejs3` (maybe via `@babel/preset-env`) would be used and then a custom Babel plugin would replace the `core-js` imports with the magic comment.

This updates our Babel config to do just that, and removes the blanket addition of `wp-polyfill` via `injectPolyfill` or otherwise.

### Effects

Removes unnecessary wp-polyfill from the following:
* packages/explat
* packages/forms block view.js
* packages/jitm
* packages/plugin-deactivation
* All Jetpack block view.js except Map, Recurring Payments, Subscriptions, Story, Nextdoor, and Podcast Player.
* packages/videopress `divi-editor/index.js`, `player-bridge.js`, and block view.js

Also it adds wp-polyfill as a dependency for a few things that were missing it before:
* Boost's `inline-liar.js`
* packages/connection scripts
* packages/forms `jetpack-forms-dashboard.js`
* Lots of mu-wpcom scripts:
  * `block-inserter-modifications.js`
  * `newspack-blocks-blog-posts-editor.js`
  * `newspack-blocks-blog-posts-view.js`
  * `newspack-blocks-carousel-editor.js`
  * `tags-education.js`
  * `verbum-comments.js`
  * `wpcom-block-description-links.js`
  * `wpcom-block-editor-nux.js`
  * `wpcom-blocks-event-countdown-editor.js`
  * `wpcom-blocks-timeline-editor.js`
  * `wpcom-global-styles-editor.js`
* js-packages/react-data-sync-client
* js-packages/svelte-data-sync-client

The following specifically weren't changed:
* packages/search and packages/wordads still unconditionally include the dep, and also embed core-js directly.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #39452

## Testing instructions:

* Verify that using Jetpack blocks other than the ones mentioned doesn't trigger `wp-polyfill` on the frontend anymore.
* Other than that, 🤷. There are no real changes in the bundled code here, only the addition or removal of polyfills for older-but-still-supported browsers.

P.S. If building locally to test, you may want to delete any stray `.cache/` directories first. Babel seems not to notice changes in the preset and so incorrectly reuses cache entries from older builds.

### CODE REVIEW

**Comment by simison** [comment]
Amazing!

> verbum-comments.js

This one is a bummer, because it'll force wp-polyfill to frontend of many sites on each post. cc @automattic/vertex in case anything could be done about it. Not a blocker at all for this PR.

**Comment by sgomes** [comment]
> > verbum-comments.js
> 
> This one is a bummer, because it'll force wp-polyfill to frontend of many sites on each post.

@simison I believe `verbum-comments.js` is loaded dynamically, not statically enqueued, so this shouldn't be a problem. The polyfills should simply be another dependency that gets lazily loaded immediately before `verbum-comments.js` itself.

**Comment by anomiex** [comment]
If we want Verbum not to check for polyfills, it looks like it's already set up so we would just have to change
https://github.com/Automattic/jetpack/blob/08733b8638ca6f45c4cbb660f082d07fdd07ee4f/projects/packages/jetpack-mu-wpcom/verbum.webpack.config.js#L17
to do `[ '@automattic/jetpack-webpack-config/babel/preset', { autoWpPolyfill: false } ]` instead. Looking back at #34993 it wasn't clear to me whether dropping `injectPolyfill` in 69dd8420e3f239d34e0aca84e5d8f2f622c73308 was intentional or accidental.

P.S. wp-polyfill is being triggered for Verbum because of use of `URLSearchParams` to polyfill [has](https://caniuse.com/mdn-api_urlsearchparams_has), [delete](https://caniuse.com/mdn-api_urlsearchparams_delete), and [size](https://caniuse.com/mdn-api_urlsearchparams_size). Which may not even be used, I think the polyfiller does it "just in case" when it sees `URLSearchParams` being used at all instead of trying to do a deep static analysis. Or even just `URL` in case its `.searchParams` gets used somewhere.

**Comment by sgomes** [comment]
> I think the polyfiller does it "just in case" when it sees `URLSearchParams` being used at all instead of trying to do a deep static analysis. Or even just `URL` in case its `.searchParams` gets used somewhere.

Yes, that's consistent with what I've seen, and with `core-js`'s general approach of polyfilling things just in case, at the slightest sign of spec deviation.

**Review by zinigor — DISMISSED** [review]
I obviously haven't tested all of these packages, but I like where this is going!

**Pull request merged**
