### PR TITLE
Replace `ts-loader` with `@babel/preset-typescript` and `fork-ts-checker-webpack-plugin`

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

We've decided (pdWQjU-FO-p2) to prefer `@babel/preset-typescript` over `ts-loader` for dealing with TypeScript in the context of Webpack. For generating the definition files, we're generally going to use `fork-ts-checker-webpack-plugin` (although `tsc --emitDeclarationOnly` is also an option).

Also, as cleanup, these packages are switched to `moduleResolution:nodenext` to ensure the `.d.ts` files are usable by consumers using that rather than `bundler`.

Of the packages affected by this:

* image-guide apparently just had a dep on ts-loader but doesn't use it.
* videopress-core has no changes in the build artifacts.
* boost-score-api, react-data-sync-client, and svelte-data-sync-client all wind up with smaller bundles (by 14K–19K) now that Babel decides what needs transpiling based on the browserslist config, so they use native classes, generators, promises, and array-spread operators now.

This PR also adds a linting check to warn against re-introduction of ts-loader, and mentions this in the relevant doc.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pdWQjU-FO-p2

## Testing instructions:

* CI happy?
* Changes in the artifacts for these packages should be as described above.
* Wouldn't hurt to give Boost's features a spin.

### CODE REVIEW

**Review by sdixon194 — DISMISSED** [review]

**Review by thingalon — DISMISSED** [review]
@anomiex - This PR broke `jetpack watch plugins/boost`; that gave the following error: 
```
[webpack-cli] Failed to load '/Users/thingalon/Projects/jetpack/projects/plugins/boost/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'fork-ts-checker-webpack-plugin'
```

After adding it as a dev dependency to Boost, it seems ok now. Have a look at https://github.com/Automattic/jetpack/pull/35713/commits/f94d4630d667c4acbdc1d0eb0c9f930a2557ae1b to verify that you're happy with the solution. 

Approving now that building and using Boost appear to work :)

**Comment by anomiex** [comment]
> This PR broke `jetpack watch plugins/boost`; that gave the following error

I'm having trouble reproducing that. It worked fine on my normal checkout. So then I made a fresh checkout, `pnpm install`, and `jetpack watch plugins/boost`. It gave a different error which suggested to me that I needed to run `jetpack build js-packages/image-guide`. After doing that, `jetpack watch plugins/boost` seems to work.

I'd rather not add the dep without understanding why it's needed. :confused:

**Review by thingalon — APPROVED** [review]
> I'm having trouble reproducing that. It worked fine on my normal checkout. So then I made a fresh checkout, pnpm install, and jetpack watch plugins/boost. It gave a different error which suggested to me that I needed to run jetpack build js-packages/image-guide. After doing that, jetpack watch plugins/boost seems to work.
> 
> I'd rather not add the dep without understanding why it's needed. 😕

To my own frustration, I can't replicate the issue either! So, I reverted my change(s) and can confirm this now compiles.

I guess my working copy must've been in a bad state when I tested.

**Comment by anomiex** [comment]
> To my own frustration, I can't replicate the issue either! So, I reverted my change(s) and can confirm this now compiles.

Thanks for checking again! 🙂

**Pull request merged**
