### PR TITLE
CRM: Resolves 3048 - remove refs to Slack community

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves Automattic/zero-bs-crm#3048 - remove refs to Slack community

## Proposed changes:

As we're retiring the Slack community, we need to remove relevant links to the plugin.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

`trunk` ("Join our Slack" menu item):
image

`fix/crm/3048/remove_slack_refs` (menu item is removed):
image

### CODE REVIEW

**Review by cleacos — DISMISSED** [review]
Link removed. LGTM!

**Comment by cleacos** [comment]
Conflict in `ZeroBSCRM.Core.Menus.Top.php` resolved

**Review by cleacos — DISMISSED** [review]
Re-approved

**Comment by coder-karen** [comment]
Adding unrelated Social plugin version update in order to be able to merge - see Slack thread here: p1681895089445129-slack-C01U2KGS2PQ

**Review by cleacos — APPROVED** [review]
Re-re-approved

**Pull request merged**
