### PR TITLE
Carousel: hide carousel controls onZoom

### PR DESCRIPTION
**Pull request by ramonjd**
Fixes https://github.com/Automattic/view-design/issues/289

#### Changes proposed in this Pull Request

On resize of an image in the carousel we're hiding the bottom bar and the close button. 

We'll show them again when the image's zoom is reset or the image is swiped/tapped.

https://user-images.githubusercontent.com/6458278/123911928-beeb3a80-d9bf-11eb-9d67-83044b534c3b.MP4

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

1. In your test site enable the Carousel module: `/wp-admin/admin.php?page=jetpack#/writing`
2. Add an image gallery to a post and publish
3. Zoom in on an image. The footer and close button should be hidden.
4. Clicking on the container, reseting the zoom or changing slides should show the footer and close button again.
5. Try in both desktop and mobile (also pinch and zoom/double and single taps)

### CODE REVIEW

**Comment by andrewserong** [comment]
Oh, nice one! I notice there's a bit of a jump when the `64px` footer is hidden. I wonder if we can use `visibility: hidden` or offset the container by `64px` when the other elements are hidden to disguise the jump so that the slide remains in the same position vertically when the elements are hidden.

I'm happy to have a go at that tomorrow if no-one else gets to it first.

**Comment by andrewserong** [comment]
I've updated this to use `visibility: hidden` instead of `display: none` and `overflow: visible` on the swiper container — this _should_ 🤞 now prevent the slide from jumping 64px when we start to zoom. It appears to be working okay for me on my iPhone 8 in Safari.

**Comment by stacimc** [comment]
I'm still experiencing some issues with this. Video below is on an iPhone X in Safari.

On the first image, it works pretty well. I double tap to zoom and hide controls, then tap once to get the controls to reappear, and there is only a minor bump in the image as the controls reappear.

On the second image though:
* First I double tap to zoom/hide controls, then tap once. Here you see a noticeable jump in the image when the controls reappear.
* Second I pinch-zoomed, and with this image you can see the noticeable jump when zooming starts.

https://user-images.githubusercontent.com/63313398/124161127-e4288900-da51-11eb-8d64-467084b8824c.mov

I also noticed that when I double tap to zoom, the zoomed image isn't centered over the spot I tapped; instead the spot I tapped is shifted up significantly. For example if I double tap on the top of a face, it zooms in on the bottom of the face.

**Comment by apeatling** [comment]
Let's let this one sit for a bit and come back to it. I think it needs to be consistently smooth for it to be worthwhile.

**Comment by andrewserong** [comment]
Thanks for testing Staci! There's definitely still some weirdness here. I wonder if setting the visibility or overflow has an effect on Swiper's calculations for where to double-tap zoom to 🤔. For centring vertically when the footer is hidden, we have an additional challenge in that using the overflow approach will mean that the "center" is 64px higher than what we want it to be (because we're retaining the position from when there was a footer). I wonder if adding a CSS animation to the class and then an additional transform/translate would do the trick... that could get more fiddly though!

> I think it needs to be consistently smooth for it to be worthwhile. If that can't be done, let's let this one sit for a bit and come back to it.

Agreed. I think this feels a little lower priority, but would still be a nice to have. And Ramon might have more thoughts next week, too.

**Comment by ramonjd** [comment]
Thanks for testing, everyone! 🙇 

After @andrewserong's update I can't see any jumping in my mobile browsers (Safari and Chrome), but I do notice the following on desktop (Chrome):

Jul-05-2021 12-38-54

On the master branch it's fine. 🤷 

> I wonder if setting the visibility or overflow has an effect on Swiper's calculations for where to double-tap zoom

Perhaps @andrewserong is on to something. 

So yeah, until we can work out a cleaner solution, I agree that we could park it for now.

**Comment by apeatling** [comment]
> Should we punt Automattic/view-design#289 to the backlog

Let's put it back in the backlog for now, and grab it next sprint. You could leave the PR or close it, up to you.

**Comment by apeatling** [comment]
I think setting opacity instead might help with this. I will have a go.

**Comment by apeatling** [comment]
I've updated the PR to use opacity with a transition to smooth out the show/hide.

**Comment by apeatling** [comment]
@stacimc Would you mind giving this another test to see if you still get the jumpiness? I'm not seeing it on my phone.

**Comment by stacimc** [comment]
@apeatling The transition is looking much smoother for me now, with no large jump 🥳

I'm still seeing the issue with double-tap to zoom not focusing on the tapped spot. So for example in this video, I'm double tapping on the eye on the left side of the image, but you can see that swiper zooms in on a spot quite a bit lower. The difference is enough that the spot I double-tapped isn't even visible in the frame, so it feels pretty noticeable.


https://user-images.githubusercontent.com/63313398/125859846-5126645f-438b-4db8-ac78-26f837a6db3d.mov

In the original implementation, the info bar would reappear if you swipe or tap the image, or if you unzoom. In this version it reappears when you fully unzoom or when you start swiping into the next image, but single tap does not restore the bar. It's especially frustrating on mobile Chrome because double-tap-to-zoom does not work there -- so to get the info bar back, you have to fully unzoom with the pinch gesture which can feel kind of clunky.

**Comment by apeatling** [comment]
@stacimc I'm not able to reproduce the double tap issue, here it is for me:


https://user-images.githubusercontent.com/1464705/126703265-c1ec1f66-e725-4a01-ad41-be4063c719ff.MOV

I'll see what I can do about the single tap. It was causing conflicts with the zoom and double tap.

**Comment by apeatling** [comment]
Found a way to restore the tap without messing with doubleTap. 👍

**Comment by apeatling** [comment]
@stacimc @ramonjd This one could use another review

**Review by stacimc — CHANGES_REQUESTED** [review]
This looks fantastic on mobile! I really like the effect. Swiping through images and zooming in and out it all feels very natural, with no jumps. I tested Safari and Chrome:
* double tap zooms to the correct place
* pinch to zoom works as well
* image doesn't jump when the info bar disappears/reappears
* info bar reappears on single tap and on swipe to next image

It just looks like there are a couple issues on desktop. Zooming now adds scroll bars to the screen, and for some reason on desktop the 'jump' when the info bar reappears is still visible. On Safari specifically the prev/next arrows also get moved lower down the screen while zoomed in. Here's a video of Safari on desktop for me:


https://user-images.githubusercontent.com/63313398/126720094-9f0da80f-ecfc-4b23-9d68-69a437069a18.mov

**Comment by ramonjd** [comment]
> It just looks like there are a couple issues on desktop. Zooming now adds scroll bars to the screen, and for some reason on desktop the 'jump' when the info bar reappears is still visible. On Safari specifically the prev/next arrows also get moved lower down the screen while zoomed in. Here's a video of Safari on desktop for me

I can also reproduce this. Somehow it's related to this CSS declaration:

```css

.jp-carousel-hide-controls .swiper-container {
	overflow: visible;
}

```

I'll see if I can tweak it a bit.

**Comment by ramonjd** [comment]
I've adjusted the position of the navigation buttons and the swiper container to account for the missing info bar height.

Also I noticed that the SwiperJS zoom module enables double tap zoom by default so we don't need toggle the classname in the `doubleTap` event handler.

https://user-images.githubusercontent.com/6458278/126735332-12425fc1-65b5-423e-9556-4834b22a8a8e.mp4

**Review by stacimc — APPROVED** [review]
This is testing well for me on desktop now as well! This looks like a great addition ✨ 

> I left the close button displaying since I don't think we should make it harder for the user to close the gallery.

Good point! +1

**Review by apeatling — APPROVED** [review]

**Review by samiff — APPROVED** [review]
Worked well for me 👍

**Comment by ramonjd** [comment]
r229200-wpcom

**Pull request merged**
