### PR TITLE
changelogger: Normalize UTC timezone

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

It seems that some versions of git may be returning `Z` rather than `+00:00` when reporting timezones from `%cI`, which broke a test. Normalize it to `Z` always so the test can have a consistent value to expect.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1715947110475729-slack-C034JEXD1RD

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy now?

### CODE REVIEW

**Review by tbradsha — APPROVED** [review]
The changes look sane and CI is happy.

An unlikely edge case of them changing this again could result it in breaking again. Any reason to not use `strtotime()` or `DateTime()` in the test, handling the timezone gracefully?

**Comment by anomiex** [comment]
How is that a risk? If git uses `Z`, `Utils::getRepoInfo()` function returns that. If it uses `+00:00`, it changes it to `Z`.

**Comment by tbradsha** [comment]
If the timezone changed to non-UTC for some reason, it'd break again.

We could make it less brittle by simply having PHP handle the timezone part automatically and providing a clean comparison no matter what. Like I said, though, it's an edge case we don't need to worry about. I was just curious why we went about it this way in the first place.

Edit: or even better, one could just compare the UTS:

```
git log -1 --first-parent "--format=%ct\n%s"
```

**Comment by anomiex** [comment]
That seems unlikely. The dates for the commit are being specified as UTC, so git would have to change its behavior to start using the local timezone by default.

As for why the test checks the string, that's because that's what the method under test returns.

**Pull request merged**
