### PR TITLE
fix default iframe heigh

### PR DESCRIPTION
**Pull request by leogermani**
Fixes the layout of the connection iframe when the user is connecting via one of the buttons in the Jetpack Dashboard.

What really changed here is that we're now displaying the TOS agreement on this context, and we didn't before.

I'd love a confirmation if the fix is to really adjust the height or to remove the TOS.

Before (see the scrollbar):
Captura de Tela 2021-04-29 às 15 51 46

After:
Captura de Tela 2021-04-30 às 12 55 43

#### Changes proposed in this Pull Request:

* Fix the height of the In-place Connection dialog on the Dashboard

#### Jetpack product discussion

p1619722373443900-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Test the iframe connection in every possible situation:
* Regular in-place connection flow while logged in to WPCOM
* Regular in-place connection flow while not logged in to WPCOM (option to skip user auth)
* Set up a site-only connection. Go to the Jetpack Dashboard and click in one of the "Connect your WordPress.com account" links -> Make sure the iframe looks good without any scrollbars

Test the Reconnection
* Set up a full connection
* Set up your site to an invalid sandbox
* Visit the Dashboard. You'll see a Connection Error notice and an invitation to Restore the connection
* (before clicking, remove the invalid sandbox)
* Click Restore connection and make sure the iframe looks good

### CODE REVIEW

**Review by sdixon194 — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]
This tests well for me, should be good to merge!

**Review by jeherve — CHANGES_REQUESTED** [review]
Hm no, we'll need to update the tests as well.

**Review by jeherve — APPROVED** [review]
Should be good to merge now.

**Comment by sdixon194** [comment]
Cherry picked `a4f54da5b51b03c4fd119deb0286a4c4506f662b` to `jetpack/branch-9.7`

**Pull request merged**
