### PR TITLE
Lazy Images: Start linting lazy-images.js

### LINKED ISSUE #9232: Lazy Images: Load Images for Printing
Lazy Images currently prevents printing images on posts and pages. 

To replicate:
1. Activate Lazy Images.
2. View a post or page with images.
3. Print.
4. Notice (in Chrome) that the preview is missing images. 

Deactivate Lazy Images and print works as expected. 

Reported here: https://wordpress.org/support/topic/lazy-load-and-printing/

### PR DESCRIPTION
**Pull request by anomiex**
Fixes #9232

#### Changes proposed in this Pull Request:

* Split the IntersectionObserver polyfill to a separate file, so we can start linting the code we write.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* No behavior should change, just verify things still work. Particularly on whichever browsers we support that need the polyfill (see https://caniuse.com/intersectionobserver?)

#### Proposed changelog entry for your changes:

* None should be necessary.

### CODE REVIEW

**Comment by anomiex** [comment]
Is there a better way to do this than by having two separate JS packages?

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r215460-wpcom added the new file to the Assets filter so when it is added via package upgrade, wp.com is ready for it.

**Comment by ockham** [comment]
This PR removes testing instructions for a number of blocks, and the entire "Embeds" section from `to-test.md` (see https://github.com/Automattic/jetpack/pull/17489/files#diff-ee09230c4b4e2b2f953e76549ab385f167433be4482f8d1d30ba7dbb6f0214d1). Since those changes are unrelated, I assume they are accidental?

**Comment by ockham** [comment]
I just merged https://github.com/Automattic/jetpack/pull/17127, which fails when running ES5 validation on the `lazy-images` package. I think there's a few issues with this:

1. We're only _bundling_ code here (through Webpack), not transpiling it (through Babel). This means that statements like `const` end up in built files, as detected by the ES5 validation script.
2. We're dropping our built files (*.min.js) into `src/`, rather than a separate location.
3. We're adding built files to GH.
4. We're including the Interaction Observer polyfill verbatim.
5. We're deleting some testing instructions ([see](https://github.com/Automattic/jetpack/pull/17489#issuecomment-713515269)).

In order to fix these issue, I suggest

- using `calypso-build` (which takes care of transpilation, and by default drops files into a separate `build/` directory, thus resolving items 1. and 2.)
- deleting built files from GH, and adding the `build/` subdirectory to `.gitignore` in order to prevent that from happening in the future
- adding the Interaction Observer npm to package.json (rather than copying it verbatim)
- restoring the deleted testing instructions in `to-test.md`

Also see Slack thread at p1603280236383200-slack-CBG1CP4EN.

cc/ @anomiex @kraftbj

**Comment by kraftbj** [comment]
@ockham We'll look into it. The testing instructions were deleted because they were referencing Jetpack 9.0 which has shipped.

**Comment by ockham** [comment]
> @ockham We'll look into it. The testing instructions were deleted because they were referencing Jetpack 9.0 which has shipped.

Ah, gtg, thanks! Didn't realize since there wasn't any note referring to that change -- it kinda looked like a rebase mishap.

> The built files for this feature had been in GH previous to this PR.

Yeah, I've noticed; we still probably want to remove those, no?

**Comment by kraftbj** [comment]
@ockham Yeah, your concerns are valid. They just all predate this PR. The polyfill was removed from lazy-image.js in this PR.

Didn't note the testing change since the version changed at the top.

**Comment by kraftbj** [comment]
Opened a new issue for tracking: https://github.com/Automattic/jetpack/issues/17562

**Pull request merged**
