### PR TITLE
IDC: Event tracking for the new screen

### PR DESCRIPTION
**Pull request by sergeymitr**
Extracted from #21822

#### Changes proposed in this Pull Request:
* migrated event tracking functionality from the old IDC banner
* adjusted property descriptions to the new convention
* fixed a minor styling bug

#### Jetpack product discussion
p9dueE-3Mn-p2

#### Does this pull request change what data or activity we track or use?
New tracking events were not introduced, only migrated existing ones to the new IDC package.

#### Testing instructions:

0. Rebuild the Connection Manager package: `jetpack build packages/connection-ui`.

##### Main screen
1. Connect Jetpack, go to Jetpack Debug and activate the IDC Simulator.
2. Go to "Jetpack Debug -> IDC Simulator", enable "IDC Simulation" and enter a "Spoof URL".
3. Edit a post and save to make the site sync. Wait a few seconds.
4. Go to "Tools -> Connection Manager", confirm that the RNA IDC screen appears.
5. Open the browser's dev console, enter `localStorage.debug = "dops:analytics";` to see the tracking events. Keep the console open, and activate the "Persist Log" feature.
7. Reload the page. The console should show two events being tracked: `jetpack_idc_notice_view` and `"notice-view" in group "jetpack-idc"`

##### Stay in safe mode

8. Click "Stay in Safe Mode". The page should reload, the IDC banners should disappear.
9. The console should log two events: `jetpack_idc_confirm_safe_mode` and `confirm-safe-mode`.
10. "Jetpack Safe Mode" button should appear in the top right corner, click it. The IDC banner should appear again.

##### Move your settings
11. Click "Move your settings", the "migrated successfully" screen should appear, click "Got it". The page should reload, IDC banners should disappear.
12. The console should log two events: `jetpack_idc_migrate` and `"migrate" in group "jetpack-idc"`.

##### Fresh connection
13. Go to the "IDC Simulator", disable simulation. Then disconnect Jetpack and connect again.
14. Enable the simulation, edit a post. You might need to wait a bit.
15. Go to Jetpack Dashboard, confirm that you see the IDC screen, and do not see the dashboard itself.
16. Keep the IDC screen browser tab open, in another tab go to the IDC simulator and disable the simulation. With simulation enabled you won't be able to connect the site.
17. Switch back to the IDC screen tab, click "Create a fresh connection". Confirm that you see the two events tracked in the console: `jetpack_idc_start_fresh` and `"start-fresh" in group "jetpack-idc"`.
18. Go through the connection process, confirm that you're redirected back to the Connection Manager page. IDC banners should disappear.

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @samiff.
I extracted some code from #21822 for easier review, can you please take a look?

**Review by samiff — APPROVED** [review]
Nice cleanup, still tests well for me 👍 

The `localStorage.debug = "dops:analytics";` did work for me this time around. Chrome dev tool's default logging level doesn't include "verbose" which the events show up under.

> Go to Jetpack Dashboard, confirm that you see the IDC screen, and do not see the dashboard itself.

This is a little bit different from #21822 since we aren't showing the new IDC screen on the JP Dashboard in this PR, but was able to see the `jetpack_idc_start_fresh` event fire okay.

**Comment by sergeymitr** [comment]
> This is a little bit different from #21822 since we aren't showing the new IDC screen on the JP Dashboard in this PR, but was able to see the jetpack_idc_start_fresh event fire okay from the Connection Manager screen.

Good call, I missed that while copying the testing instructions.
Thanks for taking a look!

**Comment by sergeymitr** [comment]
r235862-wpcom

**Pull request merged**
