### PR TITLE
Bump dependencies of our yarn dependencies

### PR DESCRIPTION
**Pull request by kraftbj**
#### Changes proposed in this Pull Request:
* A dependency downtree needed a bump to work with ~Node 12~. There's more than I thought.

#### Testing instructions:
* Build in node 10, 11, and 12. Does it build?
*

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Review by simison — DISMISSED** [review]
This works on Node.js v10.15.3 on MacOS.

On Node.js v12.2.0 this somehow fails on node-sass when it starts to manually compile some dependencies. That can be also just my system acting up.  :-/

I didn't dig  deeper what exactly is the trouble but we can figure that out once this is in `master`. Thanks for updating it!

**Comment by mdawaffe** [comment]
> On Node.js v12.2.0 this somehow fails on node-sass when it starts to manually compile some dependencies.

Same.

**Comment by kraftbj** [comment]
I hate dependencies. calypso-build needs updating to 4.12 https://github.com/Automattic/wp-calypso/blob/master/packages/calypso-build/package.json#L56

**Comment by kraftbj** [comment]
Need https://github.com/Automattic/wp-calypso/pull/33035 so Calypso can start using `calypso-build` and then we need to bump that to 4.12.

**Comment by ockham** [comment]
> Need [Automattic/wp-calypso#33035](https://github.com/Automattic/wp-calypso/pull/33035) so Calypso can start using `calypso-build` and then we need to bump that to 4.12.

I don't think Automattic/wp-calypso#33035 is strictly needed TBH (it just uses the `calypso-build` script to build Calypso, but that doesn't really have any implications for its dependency versions).

I've :heavy_check_mark:'d Automattic/wp-calypso#32630 though to unblock this PR.

One question though, shouldn't we stick to Node 10 and only switch to 12 when it becomes LTS in October? That's what we typically do with Calypso...

**Comment by simison** [comment]
>One question though, shouldn't we stick to Node 10 and only switch to 12 when it becomes LTS in October? 

I've understood that's the plan in general yeah (support v10); just if a simple dependency upgrade makes the build work for those who already use Node.js 12, then why not upgrade.

**Comment by kraftbj** [comment]
Marking this as blocked until https://github.com/Automattic/wp-calypso/pull/33035 comes through. Once that happens, we need to rebase this PR and run `yarn upgrade`. Since we pin versions for everything, it would only bump dependencies of dependencies that allow a range, which I think will get us to working with Node 12 "for free".

**Comment by kraftbj** [comment]
It isn't working locally, but sharing the current yarn.lock post-upgrade.

**Pull request closed without merging**
