### PR TITLE
Instant Search: Support yarn watch

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:

* Splits the existing `build-search` script into `build-search:scripts` and `build-search:styles`.
* Adds support for watching `build-search:scripts` via `yarn watch`. `build-search:styles` is already being watched via `sass:instant-search` in `tools/builder/sass.js`.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
* Run `yarn build-search`. Ensure assets build as expected. 
* Run `yarn watch` and try changing a script in `modules/search/instant-search`. Ensure that search assets are rebuilt.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by bluefuton** [comment]
> Run yarn build:search. Ensure assets build as expected.

Should it be `yarn build-search`? :)

My `yarn watch` complains about a missing dependency, `js-levenshtein`:

`jetpack/modules/search/instant-search/index.jsx: Cannot find module 'js-levenshtein'`

**Comment by bluefuton** [comment]
(Sidenote: it'd be great to update the setup guide at P9xfpQ-Dx-p2 when this lands.)

**Review by bluefuton — DISMISSED** [review]
`yarn build-search` and `yarn watch` built assets as expected 👍

**Review by jeherve — DISMISSED** [review]

**Comment by jsnmoon** [comment]
@jeherve / @Automattic/jetpack-crew: Any idea on how to make the CI hook pass? This looks good to merge.

Also, what's the protocol for handling the WPCOM differential (D43261-code)?

**Comment by jeherve** [comment]
It looks like Travis failed us on that one (see p7H4VZ-2yx-p2 for more details). I'll try to rebase to trigger the tests again.

> what's the protocol for handling the WPCOM differential (D43261-code)?

You can commit it yourself after testing it, once your Jetpack PR has been merged. There is some info about this here:
PCYsg-iiu-p2//#committing-block-changes-to-wordpress-com

**Review by jeherve — APPROVED** [review]

**Comment by jsnmoon** [comment]
Deployed via r207416-wpcom.

**Pull request merged**
