### PR TITLE
Typography: first pass at implementing a consistent type scale

### PR DESCRIPTION
**Pull request by keoshi**
### Changes proposed in this Pull Request:

This PR contains a first pass at implementing a consistent type scale across the entire plugin that matches what we use in Calypso. This type scale was inherited from Core, so the hope is that we can converge all 3 platforms with a consistent, harmonic typography.

As a rule of thumb to improve legibility, if the existing `font-size` was smaller than what is specified in the type scale — e.g.: 13px vs `rem( 14px )`, the `font-size` value was increased to the closest value available.

More details on p6TEKc-3Nh-p2

Here's a quick breakdown:

* Update typography partial with [Calypso's type scale](https://wpcalypso.wordpress.com/devdocs/typography).
* Updated main CSS file.
* Updated typography in all main pages:
  * At a Glance
  * My Plan
  * Plans
  * Settings
* Updated typography in components.
* Removed a duplicate `rem()` function file and updated all instances.

### Jetpack product discussion

More details on p6TEKc-3Nh-p2

### Testing instructions:

* Go to wp-admin.
* Browse around the entire plugin.
* Confirm that everything looks good and typography rules are updated.

### Proposed changelog entry for your changes:

* Improved legibility across all Jetpack interfaces.

### Screenshots

Before | After
--|--
image | image
image | image
image | image
image | image

### CODE REVIEW

**Comment by folletto** [comment]
I checked the after in isolation (without cross-checking) and it seems the visual hierarchy is overall preserved. Seems also more readable overall.

Side by side checking seems ok too.

👍

**Comment by eeeeevon13** [comment]
looks good! great job

**Comment by scottsweb** [comment]
Stella work @keoshi - I tested every screen and everything looks decent, with no obvious regressions. 

I wanted to flag 4 things that I think we might want to reflect on a little (possibly some were issues already):

The smaller text here seems really tiny:

Screenshot 2020-07-24 at 17 38 35

The email address is wrapping strangely onto a second line:

Screenshot 2020-07-24 at 17 39 00

Once again the small text on the plans page (gets used in most cards) seems just a fraction too small. Perhaps my eyes are getting tired.

Screenshot 2020-07-24 at 17 40 02

Zooming out a bit on the at-a-glance page makes for a slight jumble of hierarchies. This isn't all on the typography side of things, but it feels a little odd that the upgrade notices are bolder than the card heading for example. 

Screenshot 2020-07-24 at 17 43 38

I don't consider any of these blockers right now.

**Review by dereksmart — APPROVED** [review]
Took a nice tour through the dashboard! Didn't see anything amiss outside of what's already been commented. 🚀

**Pull request merged**
