### PR TITLE
Sharing: fix inconsistent horizontal spacing for official buttons.

### PR DESCRIPTION
**Pull request by JonahBraun**
The CSS buttons were setting margin on the a tag rather than the li. This results in double margins when using official buttons.

Before (note odd increase spacing after Print, Telegram, Whatsapp):
screen shot 2016-06-11 at 11 11 51

After (consistent spacing after all buttons):
screen shot 2016-06-11 at 11 12 30

Icon & Text mode continues to look the same.

### CODE REVIEW

**Comment by jeherve** [comment]
Could you rebase this branch to remove the extra commits it includes?

Thanks!

**Comment by JonahBraun** [comment]
Sure. Actually, @jeherve, since add/social-logos-telegram-whatapp is now merged into master, I should probably just open a new PR against master right?

**Comment by jeherve** [comment]
Yeah, that would probably be easier. I didn't even notice this PR was not against `master` 👍

**Comment by JonahBraun** [comment]
Done and retested: https://github.com/Automattic/jetpack/pull/4317

Closing this one.

**Pull request closed without merging**
