### PR TITLE
Dialogue: Connect podcast player with dialogue front-end

### PR DESCRIPTION
**Pull request by retrofox**
This PR adds the code to play the podcast player when the user clicks on the timestamp label button.

Fixes #

#### Changes proposed in this Pull Request:

* Dialogue: Connect podcast player with dialogue front-end

#### Does this pull request change what data or activity we track or use?

no

#### Testing instructions:

* Create/edit a post
* Add a podcast player with a valid RSS feed. For instance, https://distributed.blog/2020/10/15/episode-25-davit-baghdasaryan-on-the-science-of-sound-in-a-distributed-work-world/
* Add a transcription block
* Show timestamp in the Dialogue blocks.
* Set a custom time.
* Save the post
* Preview/see the post in the front-end
* Click on the ~timestamp label~ play/pause button.
* Confirm the player plays in the timestamp position.

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Comment by creativecoder** [comment]
I think keeping the timestamps as links that start the player at a particular time is more intuitive. When I click on one of those links, I'm looking to jump to a specific part of the episode to hear it, not have play/pause control of the audio, overall. And the multiple play/pause buttons carry a lot of visual weight that's distracting.

**Comment by retrofox** [comment]
> I think keeping the timestamps as links that start the player at a particular time is more intuitive.

👍 

> When I click on one of those links, I'm looking to jump to a specific part of the episode to hear it, ...

We can fix that

> ...not have play/pause control of the audio, overall. 

That's handled by the play/pause icon

> And the multiple play/pause buttons carry a lot of visual weight that's distracting.

fair enough

How do we pause the player? Does it make sense just by clicking on the timestamp again?

**Comment by pablinos** [comment]
>  How do we pause the player? Does it make sense just by clicking on the timestamp again?

Maybe. That could be confusing though. Have we got any keyboard controls for the player? If so, we could rely on them along with scrolling to the top to pause. Not ideal, but not awful.

It makes the case for having a sticky version of the player that gets anchored (sorry for the pun) to the top or bottom of the screen - a bit like a fixed navbar or something.

**Comment by sfougnier** [comment]
> I think keeping the timestamps as links that start the player at a particular time is more intuitive. When I click on one of those links, I'm looking to jump to a specific part of the episode to hear it, not have play/pause control of the audio, overall. And the multiple play/pause buttons carry a lot of visual weight that's distracting.

+1 to this.

**Review by jeherve — COMMENTED** [review]
This tests well for me. As we keep adding to the rendering of that block, I was wondering if we could refactor things a bit to escape things as late as possible, and to make things easier to read in the final markup. I created #18519 with some suggestions, let me know what you think.

**Comment by retrofox** [comment]
> This tests well for me. As we keep adding to the rendering of that block, I was wondering if we could refactor things a bit to escape things as late as possible, and to make things easier to read in the final markup. I created #18519 with some suggestions, let me know what you think.

merged

**Review by jeherve — APPROVED** [review]

**Comment by retrofox** [comment]
r219955-wpcom

**Pull request merged**
