### PR TITLE
Move/source sanitize to jetpack

### PR DESCRIPTION
**Pull request by chrisfromthelc**
Fixes https://github.com/Automattic/gold/issues/234
Companion diff: D130238-code

## Proposed changes:

* This will move this sanitization to the Memberships endpoint in Jetpack (`members.php`) so this is clearer, and then it can be removed from WPCOM's `connected-accounts.php`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* TBD

### CODE REVIEW

**Comment by n3f** [comment]
The code is looking good, but I haven't tested it.

**Comment by chrisfromthelc** [comment]
> The code is looking good, but I haven't tested it.

I changed from the nested ternaries that was on WPCOM to something a little more straightforward to read here. I can switch back to the ternaries if we really want to keep it that way.

**Review by millerf — DISMISSED** [review]
LGTM

**Review by n3f — APPROVED** [review]
LGTM

**Pull request merged**
