### PR TITLE
e2e tests: update setup to match updates in the Gutenberg repo

### LINKED ISSUE #33626: Block Performance tests: broken since August 18
We track the impact of Jetpack on the block editor's peformance by running tests every 12 hours:

https://github.com/Automattic/jetpack/blob/94cb7246636e7056ce30ab2a46116d1afccebd5f/.github/workflows/block-performance.yml
https://github.com/Automattic/jetpack/actions/workflows/block-performance.yml

Unfortunately, those tests broke on August 18, following changes in Gutenberg:
https://github.com/WordPress/gutenberg/pull/53768/

We would need to update our tests accordingly.

Previous art on this: #30128

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #33626

## Proposed changes:

Update our infrastructure following [changes in Gutenberg](https://github.com/WordPress/gutenberg/pull/53768). See https://github.com/Automattic/jetpack/issues/33626#issuecomment-1766190909 for more info

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* 8586-gh-jpop-issues

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* I will temporarily run the tests on this PR:
https://github.com/Automattic/jetpack/actions/runs/6944694826/job/18892395483?pr=33644

### CODE REVIEW

**Comment by WunderBart** [comment]
@jeherve, I've noticed that [this is now failing](https://github.com/Automattic/jetpack/actions/runs/6550369664/job/17789333469) with the following error:

```
Error: ENOENT: no such file or directory, open 'results/base.0.test.results.json'
```

If the `RESULTS_ID` env variable is not specified, the [curated results will be saved](https://github.com/WordPress/gutenberg/blob/19c8d6f12f0fd1b0f7efd10a813d90660eb0d87f/test/performance/config/performance-reporter.ts#L163) under `<artifactsFolder>/<testSuite>.performance-results.json`, which would be `./results/post-editor.performance-results.json` in this case. The `.performance-results.json` suffix is fixed, so if we want a custom name, like `base.0.performance-results.json`, the `RESULTS_ID` should be set to `base.0`.

**Comment by jeherve** [comment]
@WunderBart Thanks a lot for the help, I really appreciate it! 🙇 

Let's give it a try with `RESULTS_ID` 🤞

**Comment by WunderBart** [comment]
Looks like the tests are OK now, but we still need the following bit to account for the new results filename suffix (`*.test.results.json → *.performance-results.json`):

https://github.com/Automattic/jetpack/blob/7c37a31627e5b6194eb7d6b36cbd2813494a9102/tools/e2e-commons/bin/performance.js#L54-L68

**Comment by WunderBart** [comment]
Also, the following part is no longer true, so we should be OK without the `disable-animations.php` plugin.

https://github.com/Automattic/jetpack/blob/7c37a31627e5b6194eb7d6b36cbd2813494a9102/.github/workflows/block-performance.yml#L55

**Review by WunderBart — APPROVED** [review]
Running Gutenberg's performance tests in a different environment was an eye-opening challenge. It's also a great chance to suggest enhancements that could improve the flexibility of this setup. 💪 

cc: @swissspidy as there's a related [ongoing effort](https://github.com/WordPress/gutenberg/issues/55852) in making the perf tools shareable.

**Pull request merged**
