### PR TITLE
Package Jetpack blocks

### PR DESCRIPTION
**Pull request by gravityrail**
An experiment showing how we can refactor blocks into packages for sharing with other plugins.

Fixes something

#### Changes proposed in this Pull Request:

* Share blocks using Jetpack packages

#### Testing instructions:

* Use the gif block
* It should still work

Sample block: https://github.com/Automattic/jetpack-gif-block

### CODE REVIEW

**Comment by kraftbj** [comment]
I'm not sold on using packages natively. Shipping 3 MB of PHP per block plugin feels excessive to me.

I like the idea of ensuring that each block can be self-contained (at least the ones that are eligible for the block directory), but we can use a PHP template that is namespaced (e.g. `namespace Automattic/Jetpack/Block/{block-slug}`) that gets copied into each block.

For those that go into the ad hoc directory, we export a built version of that into a separate repo (like what you've done) and that repo can have a process to ship to SVN through a GH action (upon tagging?).

We should be able to keep a pretty clean and empty PHP file for those that are prime for this work.

**Comment by gravityrail** [comment]
Thanks for the feedback @kraftbj. 

I'll be the first to admit that this is not a perfect solution, however size on disk is far from my highest concern, though I would love it if WordPress core came up with a way of centralising autoloaded dependencies so that they're not baked into each plugin separately (and I think Crew is one of the few teams on the planet that could accomplish that goal)

What I am concerned about is:

- getting this done as fast as possible, while not shooting ourselves in the foot (e.g. maybe 3mb is a lot, but if we can optimize it away later I don't care)
- changing the fewest things in order to ship blocks outside of Jetpack (which also counts as "fast as possible")
- no magical renaming, post-processing, or other changes that would open the door for nasty bugs where the same block gets loaded twice (packages have the virtue of being loaded only once no matter what)
- allowing for some period of time where blocks ship both with Jetpack and independently
- allowing, perhaps, for some internal builds of Jetpack to include these blocks indefinitely
- using this as an opportunity to remove deprecated code and eliminate some of the weird confusing things that got introduced when blocks landed in Jetpack - extensions vs modules, variations, the whole lifecycle feels... cobbled together. This is a chance to rationalize it.

I am not saying that this approach is the best, though I haven't had a chance to examine others. But perhaps the list above helps clarify the choices I made here.

**Comment by kraftbj** [comment]
I think there are a couple of use cases: 

1. Being able to keep Simple and Atomic at the same block version.
2. The block directory.

For the first, this (or something similar) is a good approach. We can update the composer file on simple and Atomic at once and bring in the same version. Skip fusion for blocks.

For the second, ad hoc block plugins are limited to 50 KB of PHP. The 3 MB of PHP makes this approach a non-starter. 

I think this approach has its place and does solve problems we have outstanding, but for the block directory, we'd need to trim quite a bit.

**Comment by gravityrail** [comment]
50kb of PHP?

Challenge accepted.

**Comment by gravityrail** [comment]
I just checked, this has 244k of PHP. 50kb seems doable. Not sure where you got 3mb from?

**Comment by gravityrail** [comment]
Ohhh haha symlinks have 0 size :| you're right, it's a lot...

**Comment by gravityrail** [comment]
Even with symlinks disabled it's 264k, and only 12k of that is the "vendor/automattic" dirs. Where is your 3mb estimate coming from?

**Comment by jeherve** [comment]
@gravityrail This should give you more background on this requirement (and whether or not it will be subject to change), and how to check against it:
- p9dueE-1BH-p2#comment-2682
- https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/cli/class-block-plugin-checker.php?rev=10090#L807
- https://wordpress.org/plugins/developers/block-plugin-validator/

**Comment by kraftbj** [comment]
My 3 MB estimate was from installing composer deps, then moving the gif-block files to a separate repo and running it through the block validator: https://wordpress.org/plugins/developers/block-plugin-validator/

In looking more, I should have ran `composer install --no-dev` which brings down the weight quite a bit (25 KB).

I'm AFK for family reasons the next couple of days, but would be worth getting a fully functional and built version of it to pass through the validator.

**Pull request closed without merging**
