### PR TITLE
Fix/dedicated sync enable callables for dedicated sync requests

### PR DESCRIPTION
**Pull request by bisko**
#### Changes proposed in this Pull Request:

This PR enables sending of callables in non-admin contexts.

The reason for that is Dedicated Sync never runs in an admin context and we won't send callables properly if they are sent via Dedicated Sync.

Until now non-admin contexts would send only the "always send" callables, while the rest of them needed to be sent from an admin context, which would mean a user would have spawned the request.

With the introduction of Dedicated Sync, the sending of events doesn't happen in a user context, so Sync thinks that it doesn't need to send the callables, but it does. 

This was an oversight in previous releases and was discovered while enabling Dedicated Sync for general Jetpack self-hosted sites.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/a

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
**Before:**
- Setup a JN site and connect it
- Enable/Disable Jetpack modules and confirm by monitoring the corresponding audit logs that the following Sync actions were sent: 1) jetpack_deactivate_module and 2) jetpack_sync_callable
- Force enabled Dedicated Sync
- Repeat the above and confirm `jetpack_sync_callable` is not sent anymore

**After:**
- Activate this branch via Jetpack Beta
- Repeat the above and confirm both `jetpack_deactivate_module` and `jetpack_sync_callable` actions were sent

### CODE REVIEW

**Comment by fgiannar** [comment]
While reviewing this, I stumbled upon [this discussion ](https://github.com/Automattic/jetpack/pull/16827#pullrequestreview-475703026) and wonder if this could be an opportunity for us to remove the extra complexity of forcing Sync to send callables on the next request, given Dedicated Sync moves sync out of shutdown to its own dedicated request.

We don't necessarily have to do this in this PR, just mentioning it for awareness.

**Comment by coder-karen** [comment]
@bisko was the intention to get this in 11.2? I'll be cutting the beta in around 4hrs - if it does need to be in and there is anything I can do to help let me know :)

**Review by fgiannar — CHANGES_REQUESTED** [review]
I tried testing as follows but unfortunately it doesn't seen to be working for me:
- Setup a JN site and connect it
- Enable/Disable Jetpack modules and confirm by monitoring the corresponding audit logs that the following Sync actions were sent: 1) `jetpack_deactivate_module` and 2) `jetpack_sync_callable`
- Force enabled Dedicated Sync
- Repeated the above but only got: `jetpack_deactivate_module`

I'm still debugging but I can confirm that the `jetpack_sync_callable` action was fired [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/sync/src/modules/class-callables.php#L502) however it didn't make it to the queue.

**Review by fgiannar — APPROVED** [review]
LGTM!

**Review by coder-karen — APPROVED** [review]

**Pull request merged**
