### PR TITLE
Comments: service updates

### LINKED ISSUE #31367: Jetpack Comments: Adjust verbiage under Settings > Discussion to remove reference to Twitter
### Impacted plugin

Jetpack

### What

Twitter appears to no longer be supported as an option for Jetpack Comments, as the Twitter icon doesn't appear anymore

### How

The setting name under Jetpack > Settings > Discussion is:

**Let visitors use a WordPress.com, Twitter, or Facebook account to comment**

I guess we'd need to update this to **Let visitors use a WordPress.com or Facebook account to comment**.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #31367

## Proposed changes:

* Removing a service pending determination of app's permissions.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pdrWKz-UJ-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* None yet. Only staging this PR.

### CODE REVIEW

**Comment by kraftbj** [comment]
Marking as 12.2 since the primary change would be on the wp.com side. This would be effectively cleanup after that happens.

**Comment by jeherve** [comment]
Removing the 12.2 milestone for now.

**Comment by jeherve** [comment]
@kraftbj Maybe we could pick this up now?

**Review by zinigor — DISMISSED** [review]
This looks OK to me!

**Review by jeherve — APPROVED** [review]

**Pull request merged**
