### PR TITLE
Change "sharing_add_footer" priority to temporarily fix jQuery undefined console errors when using ShareDaddy with jQuery enqueued in the footer (#1223)

### PR DESCRIPTION
**Pull request by CFXd**
See https://github.com/Automattic/jetpack/issues/1223

### CODE REVIEW

**Comment by samhotchkiss** [comment]
works for me...

**Comment by CFXd** [comment]
:+1:

**Comment by jeherve** [comment]
fyi I had to revert this commit in d396079f89e402de4610dccd8ac7e488288b6a8f. It caused the sharing library not to be enqueued at all in my tests. As soon as the priority was higher than `20`, the file was dequeued.

**Comment by CFXd** [comment]
How can I resubmit the PR with priority 20? Should I create a new branch/PR from scratch?

**Comment by jeherve** [comment]
> How can I resubmit the PR with priority 20? 

`20` actually didn't work either in my tests. `19` did.

> Should I create a new branch/PR from scratch?

Yep, that'd be the best way.

**Comment by CFXd** [comment]
Done @ https://github.com/Automattic/jetpack/pull/1700

**Comment by CFXd** [comment]
Should have tested before I submitted, but priority 19 causes the undefined issue. 20 does not.

**Comment by samhotchkiss** [comment]
OK, I'll do some digging on this next week.

**Pull request merged**
