### PR TITLE
Podcast Player: Add API schema

### PR DESCRIPTION
**Pull request by marekhrabe**
#### Changes proposed in this Pull Request:

* adds API schema to our endpoint

#### Testing instructions:
* Check the API schema against the API output

#### Proposed changelog entry for your changes:
* none

### CODE REVIEW

**Comment by obenland** [comment]
I wonder if it made sense to use the schema to automatically validate endpoint args?

**Comment by marekhrabe** [comment]
> I wonder if it made sense to use the schema to automatically validate endpoint args?

I'm not sure I follow this.

**Review by jeherve — APPROVED** [review]

**Comment by obenland** [comment]
> I'm not sure I follow this.

Yeah, never mind. We only have the URL as a parameter.

**Comment by marekhrabe** [comment]
r205109-wpcom

**Pull request merged**
