### PR TITLE
Issue 3432 - Don't use site icon as fallback if it's less than default size

### LINKED ISSUE #3432: Don't use site icon as fallback if it's less than requested size
The site icon I've set is 360px square (https://s2.e15r.co/wp-content/uploads/sites/2/2016/01/erick-bio.jpg). When choosing an image to use for OG tags, and perhaps in other places, the site icon is considered as a fallback if a post has no images. In the case of OG tags, the requested size is 512px. Core returns the URL for the sub-512px image, and Jetpack passes it on as a 512px square, causing distortion. Hint: no one wants to see my face _that_ closely. ;)

https://github.com/Automattic/jetpack/blob/80df2a3638e72a84ba225231d12713385470f5be/functions.opengraph.php#L340

> What I expected

Jetpack wouldn't use an image that was less than 512px when it wanted one that was 512px. Or that it would, at least, check that the image's size met its request.

> What happened

Jetpack told Facebook that a 360px image was actually 512px. Fortunately my parents are probably the only ones who saw the posts.

> Steps to reproduce the issue

Set a site icon less than 512px and share a post to Facebook that contains no other images. Bask in the pixelation.

### PR DESCRIPTION
**Pull request by AjkP**
Fixes #3432 .

[Edited by @kraftbj]
This PR modified the OG image tag selection process to check for a 512 image and confirm the size is 512 before attaching.

### CODE REVIEW

**Comment by AjkP** [comment]
First pull request to jetpack. Do I need to do any kind of assigning to myself when I work on an issue? Also is there any IRC / slack room for answer to common questions?

**Comment by kraftbj** [comment]
@AjkP Welcome and thanks! We'll take a closer review of the PR, then reply back with any notes, suggestions, corrections needed, etc. 

We don't have a Slack/IRC room. I hang out in #wordpress on Freenode from time to time though. Cheers!

**Comment by eliorivero** [comment]
Hi, thanks for the PR!
This PR works fine for Site Icon. I tested assigning https://s.w.org/about/images/logos/wordpress-logo-32-blue.png as site icon (skipped cropping since otherwise image is inflated to 512) and it wasn't written as og:image, which is ok.

To make a more complete PR, we should tackle the Site Logo, which is doing the same thing than Site Icon before this PR. You assign a small image and it writes it down as og:image even if it's not the proper size.

@AjkP can you make the addition so this PR addresses the issue with Site Icon, which already does, and Site Logo as well?

**Comment by AjkP** [comment]
@eliorivero sorry for the overdue reply. Will take a look at it this weekend.

**Comment by AjkP** [comment]
Added validation for fall back images, to not show bigger images than the ones requested.

Updated the Unit Test with a new case and rearranged expected and actual.

**Comment by rcoll** [comment]
This tests fine for me on .org, but will need to be tested on WordPress.com before merging there.

**Pull request merged**
