### PR TITLE
Beta to Experimental -- AnchorFM Editor Integration 

### PR DESCRIPTION
**Pull request by krymson24**
Fixes 371-gh-Automattic/dotcom-manage

#### Changes proposed in this Pull Request:
Moves the AnchorFM extension from beta to experimental

#### Jetpack product discussion
371-gh-Automattic/dotcom-manage

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

- Make a testing post in the block editor and save it.
- Open the post for editing and add three GET params to the URL — `anchor_podcast`, `anchor_episode`, and `spotify_show_url`:
  - for convenience, you can use: `&anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_show_url=https://open.spotify.com/show/6HTZdaDHjqXKDE4acYffoD?si=EVfDYETjQCu7pasVG5D73Q`
 - Click on the editor body. Make sure the AnchorFM extension shows.

#### Proposed changelog entry for your changes:
Moves the AnchorFM extension from beta to experimental

### CODE REVIEW

**Comment by krymson24** [comment]
Per 371-gh-Automattic/dotcom-manage#issuecomment-746393643, adding this block/extension as "experimental" should remove it from Jetpack sites. However, when testing this locally, I'm still seeing this block render 🤔

**Comment by jeherve** [comment]
> Per 371-gh-Automattic/dotcom-manage#issuecomment-746393643, adding this block/extension as "experimental" should remove it from Jetpack sites. However, when testing this locally, I'm still seeing this block render 🤔

That's most likely because you have enabled Beta blocks on your local development environment.

Here are how the 3 block environments work:

- Production only includes production blocks. That's the default setup, when you haven't used any constant / filter.
- Environmental blocks include production blocks and experimental blocks. That environment can enabled by a constant or a filter. It is enabled on WordPress.com Simple sites and on Atomic.
- Beta blocks include production blocks, experimental blocks, and beta blocks. Like above, that environment can be enabled via a constant or filter. 

To double-check things, you can check the name of the js bundle that is loaded in the block editor.

I would recommend that you remove whatever constant or filter you were using to enable Beta blocks (`define( 'JETPACK_BETA_BLOCKS', true );` maybe?); the block should disappear. You can then do something like `add_filter( 'jetpack_blocks_variation', function() { return 'experimental'; } );` to see how things will look like for folks running Experimental blocks.

All that said, I'm not sure I would place the snippet playing with `jetpack_set_available_extensions` here in the Jetpack codebase. At some point, you'll want to remove that snippet to enable Anchor.fm, and you'll want this to happen regardless of the Jetpack plugin if I understood correctly.
I would consequently recommend placing the snippet in files that are not synchronized with the Jetpack codebase. It could be `wpcomsh` for Atomic, and `wp-content/mu-plugins/jetpack/jetpack.php` for WordPress.com Simple for example.

**Comment by krymson24** [comment]
Thanks for the context @jeherve ! Left this PR to just switch the block from `beta` to `experimental`

**Review by kraftbj — DISMISSED** [review]

**Review by jeherve — DISMISSED** [review]

**Comment by kwight** [comment]
@Automattic/explorers FYI this is about to go in – are we good to go?

**Comment by creativecoder** [comment]
> FYI this is about to go in – are we good to go?

@kwight Okay as far as I know. We'll be doing the same with the conversation/dialog blocks soon!

**Comment by krymson24** [comment]
@Automattic/serenity I think I need an approval here to merge.

**Comment by krymson24** [comment]
@jeherve apologies -- I think I need another approval here. The tests kept failing so I rebased.

**Review by jeherve — APPROVED** [review]

**Comment by krymson24** [comment]
Thanks for the help here @jeherve !

**Pull request merged**
