### PR TITLE
Remove legacy config pages & related code

### PR DESCRIPTION
**Pull request by brbrr**
Follow-up PR for cleaning up unused code after #10668

#### Changes proposed in this Pull Request:

* Remove `Jetpack::module_configuration_load()`, `Jetpack::module_configuration_head()`, `Jetpack::module_configuration_screen()`, `Jetpack::module_configuration_activation_screen()` and relevant code.
* Remove `jetpack_module_configuration_head_{module}`, `jetpack_module_configuration_load_{module}`, `display_activate_module_setting_{module}`, `jetpack_notices_update_settings`, `jetpack_module_configuration_screen_{module}` actions.
* Remove usage of `$_GET['configure']` and all relevant code.

#### Testing instructions:
Make sure that every module configuration link redirects to the desired location: (react) Jetpack Settings or wp-admin settings / other pages when applicable (for example for widgets):
* All Configure links in the legacy modules admin screen.
* Stats -> Configure link in header

#### Proposed changelog entry for your changes:
* Admin page: Remove legacy settings pages and related code

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍 

I would only recommend adding all the hooks that are now deprecated to `deprecated_hooks`, but that can be done in an additional PR.

**Comment by mdawaffe** [comment]
I've manually added the relevant changes to code-D26734.

**Comment by mdawaffe** [comment]
> I would only recommend adding all the hooks that are now deprecated to `deprecated_hooks`

I didn't know that was a thing :)

Most of the hooks are dynamic: they contain the module slug. Any advice?

**Comment by jeherve** [comment]
> they contain the module slug. Any advice?

That's a good question. I am not sure how we should handle, or if it should in fact. Maybe not that many third-parties are relying on those hooks today?

**Comment by georgestephanis** [comment]
> Maybe not that many third-parties are relying on those hooks today?

Probably.  We had a tendency to add theoretical hooks optimistic that someone would find them useful, but it was rare that anyone ever did.

**Comment by georgestephanis** [comment]
My only concern with this is if it breaks any no-js fallbacks, but we're probably okay with that.  If the user uses the legacy modules page, is it possible to do some of this stuff any more?

**Comment by brbrr** [comment]
@georgestephanis legacy settings pages are not easily accessible anymore (except stats settings), so there quite a small chance that anyone is still using them. You still can access them by passing the correct url-params though.

**Comment by mdawaffe** [comment]
> is it possible to do some of this stuff any more?

Do you mean "is it still possible to change the settings that you used to be able to change via the legacy pages", then yes: to the best of my knowledge all settings available on the legacy pages are available in the React UI as well.

**Pull request merged**
