### PR TITLE
Contact Form: add submitting state

### LINKED ISSUE #34283: Enhancement: add loading state to Contact Form on submitting
### Impacted plugin

Jetpack

### What

Add a loading indicator after user submitted the form

### How

_No response_

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/34283

## Proposed changes:

This PR adds a submitting state to the submit button of Contact Forms.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pf5801-87-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Spin up a test site with this branch
- Create a new post
- Add the _Contact Form_ block
- Open the preview
- Check you still see the error messages when the form is invalid
- Fix all the errors
- Submit the form and notice the spinner in the submit button

https://github.com/Automattic/jetpack/assets/1620183/e965d447-1e35-4c2c-ba32-9af0b9283d57

### CODE REVIEW

**Review by darssen — COMMENTED** [review]
Tested with Happy path and things looked good and as expected, but by chance I tested too with the Extra Widgets feature enabled in Jetpack-> Settings and some things didn't look good.

**To reproduce unexpected behavior**

- Enable the Extra Widgets feature as below 

image
- Try to submit the Contact form you will see the text for screen readers to the side of the Spinner.  

https://github.com/Automattic/jetpack/assets/13239096/b9868f71-f5e5-4eed-ad8d-1743ea06ad9f

**Comment by monsieur-z** [comment]
Thanks for the review @darssen! Looking at the spinner, it seems that `grunion.css` is not loaded at all. Could you confirm that?

I haven't been able to reproduce the issue (styles not loading), even with the extra widget enabled.

**Review by jeherve — COMMENTED** [review]
I spotted some issues when trying to submit a form while not logged in. We miss some data since we do not have the enqueued styles that would come along with the admin bar:

**No dashicons, no colors**

Screenshot 2023-12-01 at 10 11 45

**Submitting text is not hidden**

https://github.com/Automattic/jetpack/assets/426388/ae49b64f-24d7-49a4-847e-4c23bacea6f3

**Comment by monsieur-z** [comment]
Thanks for catching this @jeherve.

The dashicons are indeed not present when testing in a private window. I'll address that in a separate PR.

Regarding the "Submitting form" text (and most likely the missing red color), I was able to reproduce the issue in Firefox. Upon inspection, the browser had a stale stylesheet. Clearing the cache solved the issue. I'm not sure how we usually handle this, but I'm thinking specifying a version in `wp_register_style` would bust the cache.

If that's okay, I'll handle this separately as well since it's a different issue and to not block the merging of this PR.

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
In this case, this should be good to merge after a trunk update! 🚢

**Review by jeherve — APPROVED** [review]

**Comment by monsieur-z** [comment]
Following up on the caching issue, a version is already specified when we register the stylesheet: https://github.com/Automattic/jetpack/blob/7e4f988d83460a3e4e054d43ee7ef3fca84c1f74/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L389.

Since the version matches the Jetpack version, within a release period, the cache won't be busted from one PR to another unless you clear your browser cache. End users won't encounter this issue.

**Pull request merged**
