### PR TITLE
Upgrade @wordpress/components package to 9.2.3

### PR DESCRIPTION
**Pull request by scruffian**
This was raised in https://github.com/Automattic/jetpack/pull/14927.

#### Changes proposed in this Pull Request:

* Upgrades our version of the @wordpress/components package to 9.2.3
* Updates the components we use from this package to be aligned with the new package.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Update to existing features

#### Testing instructions:
* Try adding the following blocks and check you can still edit their media:
* Simple Payments
* Tiled Gallery
* Slideshow

#### Proposed changelog entry for your changes:

* Upgrade @wordpress/components to 9.2.3

### CODE REVIEW

**Comment by jeherve** [comment]
Related: #13668

**Review by jeherve — CHANGES_REQUESTED** [review]
Looks like this will need a rebase now.

**Review by jeherve — CHANGES_REQUESTED** [review]
I am afraid we can't do this just yet. `Button` only got merged with `IconButton` a few months ago in https://github.com/WordPress/gutenberg/pull/19193 That means that things look good on a site running WP 5.4 or the Gutenberg plugin, but in Jetpack we should also support folks running WP 5.3, where `icon` won't be available for `Button`:

image

**Comment by pento** [comment]
It looks like this is blocked on WordPress 5.5 released, which is [currently scheduled](https://wordpress.org/about/roadmap/) for August.

@scruffian: I'll leave it up to you whether you want to leave this PR open until then, or close it out.

**Comment by scruffian** [comment]
The main thing here was to upgrade the package which has already been done, so we can close this.

**Pull request closed without merging**
