### PR TITLE
Search: Fix regression preventing clicks from spawning overlay

### LINKED ISSUE #23091: Search: Instant Search cannot be opened via filter class anymore
### Impacted plugin

Jetpack

### Steps to Reproduce

Using latest version

Enable Jetpack search on a website and add the link to open the modal as documented in https://jetpack.com/support/search/install-search-on-your-site/
```
<a href="#" class="wp-button jetpack-search-filter__link" style="width: 50px;height:46px; border-color: #c8d7e1; border-style: solid; border-width: 1px 1px 2px;">
    <svg style="fill: #2e4453;" class="gridicon gridicons-search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g><path d="M21 19l-5.154-5.154C16.574 12.742 17 11.42 17 10c0-3.866-3.134-7-7-7s-7 3.134-7 7 3.134 7 7 7c1.42 0 2.742-.426 3.846-1.154L19 21l2-2zM5 10c0-2.757 2.243-5 5-5s5 2.243 5 5-2.243 5-5 5-5-2.243-5-5z"></path></g></svg>
</a>
```

### A clear and concise description of what you expected to happen.

When clicking a link with the `jetpack-search-filter__link` class, the modal should be revealed

### What actually happened

Nothing, but if you inspect the page you will see that is being triggered (both body and link attributes change, but instantly revert back to the current values).

If you look through the event listeners applied to the link, you will see there are 2. 
image
One on the link and one on the window. If you remove the event handler on the window itself, it will reveal and work as expected.

### Other information

After a brief chat with George Stephanis and Jeremy Herve, we concluded it's a bug in the current build as this can be seen on other sites we look after.

### Operating System

Linux

### OS Version

POP_OS 21.04

### Browser

Chrome/Chromium, Firefox

### Browser Version(s)

any

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #23091. E2E tests will be added in another PR to ensure this regression will not recur.

#### Changes proposed in this Pull Request:

Fixes a regression that prevents click events from spawning the search overlay.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Apply this change to your site with a Jetpack Search subscription.
* Add a `a.jetpack-search-filter__link` and a `button.jetpack-instant-search__open-overlay-button` to a page or a post.
* Open the post and click on the link or the button. 
* Ensure that the modal is spawned as expected.
* Click outside the modal; ensure that the modal closes as expected.
* Repeat the above steps to spawn the modal. 
* Press escape; ensure the modal closes as expected.

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
Thanks for the fix. It works for me and looks reasonable 👍 
PS: It's quite interesting it didn't affect the search button tho - probably is about the sequence of events.
I'll propose a follow up PR to add a E2E test.

**Comment by gin0115** [comment]
Cheers for this, gave me a bit of head-scratching to working out why earlier :)

**Comment by bluefuton** [comment]
@Automattic/jetpack-crew please could we have this one cherry-picked for inclusion in Jetpack 10.7?

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-10.7` in ba42d2faeeecbe5a054739fcee5ca8779109f953

Releasing a new version of the Search package in #23104

**Pull request merged**
