### PR TITLE
Business hours: Add unit tests and fixtures for the business hours block

### PR DESCRIPTION
**Pull request by andrewserong**
Adds test fixtures for the Business Hours block and unit tests for the block's Edit component. Also updates the Remove Hours button to include label/tooltip text.

#### Changes proposed in this Pull Request:

* Add block fixture parsing tests for the Business hours block (using the default hours, and using custom hours)
* Add unit tests for the block's Edit component
* Add label text to the Remove Hours button, so that it's more accessible (tooltip text makes it clearer that you're removing the hours, not the entire day) and cleaner to test (look for the button by its label text instead of by its class name)

image

#### Jetpack product discussion

See p1HpG7-b3G-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Change directory to `cd projects/plugins/jetpack` and run the following test making sure they all pass:
* `yarn jest extensions/blocks/business-hours/test/`
* In a browser, insert the Business Hours block, and add an additional set of hours to one of the days. Hover over the trashcan icon to remove hours and you should see tooltip text saying "Remove Hours".

#### Proposed changelog entry for your changes:

* Business Hours Block: Add tooltip text to the Remove Hours button.

### CODE REVIEW

**Comment by andrewserong** [comment]
Updated to iterate over each of the days when testing the open/closed toggle. I now just need to add in tests for adding and removing additional opening / closing hours.

**Review by jeherve — APPROVED** [review]
This tests well for me. I added a changelog entry.

**Comment by andrewserong** [comment]
I've merged in the PR, but I'll hold off on committing the wpcom diff until the new `Remove Hours` text is translated. For example here's how it currently looks in French:

image

**Comment by jeherve** [comment]
This may take up to a month, so I think it would be fine to deploy on WordPress.com already. Typically, strings are not translated in the first few days following a release in Jetpack either, as it takes some time for the translation process to be complete.

**Comment by andrewserong** [comment]
r222715-wpcom

**Pull request merged**
