### PR TITLE
Blocks: add AMP and CSS Classes methods to the new package

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* This PR starts adding methods to the new Blocks package we'll use for all Jetpack blocks from now on.

#### Jetpack product discussion

* Internal reference: p9dueE-1BH-p2
* Primary issue: #17099 

#### Does this pull request change what data or activity we track or use?

* N/A

#### Testing instructions:

* Install the AMP Plugin on your site.
* Connect Jetpack to WordPress.com, and try to add all the blocks added as labels to this PR.
* View them in AMP views as well.
* Ensure all blocks are displayed properly.
* Ensure that blocks that include a `view.js` file (such as the Map block) still load it on non-AMP views.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Review by fgiannar — APPROVED** [review]
Tested all blocks added as labels in this PR before and after applying the changes introduced in this PR  and can confirm the blocks are displayed properly with the following 2 exceptions:

- Google calendar block: This block is removed from AMP view due to missing `width`
- Opentable block: This block is removed from AMP view due to invalid `script`

However, the above are not related with the present PR so it can be approved. Just mentioning them here as a reference, please @jeherve let me know if I should create an issue for those.

**Comment by jeherve** [comment]
> Opentable block: This block is removed from AMP view due to invalid script

This should be addressed in #17085

> Google calendar block: This block is removed from AMP view due to missing width

Nothing in progress for this one, but it's tracked in #14395.

**Comment by kraftbj** [comment]
@jeherve How did you update the composer.lock so the branch was changed to `dev-master`?

**Comment by jeherve** [comment]
I don't know, I don't really remember doing anything specific. I believe I just `composer install`?

**Comment by kraftbj** [comment]
:y: It looked almost like it was ran standing on master? ¯\_(ツ)_/¯

**Comment by jeherve** [comment]
r214736-wpcom

**Pull request merged**
