### PR TITLE
Search: Add search plan onboarding notice

### PR DESCRIPTION
**Pull request by gibrown**
Adding banner to thank the end user for their purchase.

We redirect after Calypso thank you screen and link to: http://gibrown.wpsandbox.me/main/wp-admin/admin.php?page=jetpack&search-thank-you#/performance

Still TBD: handle dismissing the notification.

### CODE REVIEW

**Comment by keoshi** [comment]
@gibrown Pushed a few changes to use a `Card` component for the Search onboarding. A few notes:

- I've not added the full show/hide Card logic here.
- On `jetpack-notices` I'm calling the new `SearchOnboarding` component for ease of use. I'm guessing that's not where we want to call it.
- Also noticed the component shows up on any and all sections of the Jetpack app as long as the URL contains `?search-thank-you`.

#### Desktop:

image

#### Tablet:

image

#### Mobile: 

image

**Comment by gibrown** [comment]
I don't think there is any reason we need to store this on the server, maybe just clear the query param with something like:

```
	dismissCard = () => {
		const query = decode( window.location.search.substring( 1 ) );
		if ( 'search-thank-you' in query ) {
			delete query['search-thank-you'];
		}
		window.location.search = encode( query );
		analytics.tracks.recordJetpackClick( {
			target: 'search-onboarding',
			button: 'dismiss',
			page: this.props.path,
		} );
	};
```

**Comment by keoshi** [comment]
That's a valid point — it depends on whether we want to make it semi-persistent or a one-time thing — but I agree we can show it just once right after purchase.

**Comment by AnnaMag** [comment]
As per agreement to display the Thank you note in the purchase flow in Calypso, closing this PR (for now).

**Pull request closed without merging**
