### PR TITLE
Restore legacy publicize ui

### PR DESCRIPTION
**Pull request by gravityrail**
WIP experiment.

cc @jeffgolenski

### CODE REVIEW

**Comment by lezama** [comment]
@gravityrail We are seeing the same tests failing in https://github.com/Automattic/jetpack/pull/13230, it seems something deep in core master.

**Comment by jeffgolenski** [comment]
@gravityrail I'll give this a test once the checks pass and it shows up in the beta app! FYI, I'm AFK until wednesday though.

**Comment by gravityrail** [comment]
@jeffgolenski tests fixed, let me know when you've taken a look. I'm interested to know if we can give this old UI a coat of paint so it fits in with modern Jetpack

**Comment by gravityrail** [comment]
cc @oskosk who was also pinged on https://github.com/Automattic/jetpack/issues/12937 

Related: https://github.com/Automattic/jetpack/issues/12929

**Comment by jeffgolenski** [comment]
The functionality of the connections seems to work just fine (tested with linkedin). But we'll need to have a larger dicussion around overall UX / UI to bring this up to speed in 2019!

**Pull request closed without merging**
