### PR TITLE
Adds filters when getting current post id

### PR DESCRIPTION
**Pull request by thisislawatts**
See #1688

### CODE REVIEW

**Comment by georgestephanis** [comment]
We're actually looking at a grander system that will cache the forms in a cpt and generate a unique key that's passed through so it doesn't need to know the originating post.

I'm hoping to have it in shortly-ish.  This fix will be against code that will be changing heavily at that point.

**Comment by thisislawatts** [comment]
That sounds like a good way of handling things. Be interested to take a look at this once it's ready for review.

**Comment by samhotchkiss** [comment]
So @georgestephanis-- should we not accept this PR since it's going to be changing soon, or should we accept this as a stopgap fix for 3.4?

**Comment by georgestephanis** [comment]
I'm going to say no for the moment, this way seems somewhat clunky unfortunately, and I think it may be accomplishable through re-running the catcher script with the nested pages.

**Comment by thisislawatts** [comment]
Just wanted to catch up on this @georgestephanis, it looks like it's been pushed back to version 4.0? Is there anything I can do to help with this?

**Pull request closed without merging**
