### PR TITLE
CRM: Adding back correct comment style for White Label comments

### PR DESCRIPTION
**Pull request by coder-karen**
## Proposed changes:

* Code that is stripped out for White Label usage has a specific comment style that  we use to locate those relevant sections of code.
* Some of those comments were changed to regular `//` comments - that change originally happened in some files[ on the initial commit when moving CRM into the monorepo](https://github.com/Automattic/jetpack/pull/28314/commits/1da5384086be632b66922607090cca155fc92386) (before pushing the first commit).
* This PR changes those comments back to how they were, and adds a ruleset to phpcs.xml.dist to attempt to continue ignoring those comments in the future.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/zero-bs-crm/issues/3009

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* I don't believe testing instructions are needed here, other than reviewing the changes to make sure that comment changes look correct. How they should look: `##WLREMOVE` for the beginning of a section to be removed for WL releases, and `##/WLREMOVE` to mark the end of sections.

Noting that we'll likely need to manually override the PHP linting checks for this PR to be able to be merged.

### CODE REVIEW

**Review by kallehauge — COMMENTED** [review]
@coder-karen what if we approached this from a different angle and update the builder script (https://github.com/Automattic/jetpack-crm-app-customer/blob/trunk/includes/wp-buildr-main-process-funcs.php#L455) to look for `// WLREMOVE` and `// /WLREMOVE`?

The goal of the above approached would be to still be able to use the code standards that are otherwise being removed here

**Comment by cleacos** [comment]
The problem with that approach is that it'd be more complicated because those labels are used by our extensions too. We would need to do more checks to be sure that everything is okay.

**Review by cleacos — DISMISSED** [review]
I checked the code, and it seems okay. I searched and didn't find any wrong labels.

For me it is LGTM!

**Review by tbradsha — APPROVED** [review]
Looks good to me; right off I don't see any lingering wrong-format WLREMOVE references in the codebase.

How did this happen originally? Is there an associated PR/commit?

**Comment by coder-karen** [comment]
Thanks @tbradsha !

> How did this happen originally? Is there an associated PR/commit?

That change originally happened in some files[ on the initial commit when moving CRM into the monorepo](https://github.com/Automattic/jetpack/pull/28314/commits/1da5384086be632b66922607090cca155fc92386) (before pushing the first commit). So that was on the massive first commit locally - phpcsbf ran automatically.

**Pull request merged**
