### PR TITLE
admin-ui: Register Akismet menu for Jetpack-the-plugin too

### LINKED ISSUE #33550: Akismet reports "Sorry, you are not allowed to access this page" during setup with bundle plan on Jetpack 12.6+
### Impacted plugin

Jetpack

### Quick summary

@foleynotrose noticed an influx of tickets from users purchasing Jetpack bundles (e.g. Security, Complete) who are unable to activate Akismet - see pZbK5-7Ja-p2.

When attempting to reach the Akismet config page (/wp-admin/admin.php?page=akismet-key-config), they see the following:

Screenshot 2023-10-11 at 14 16 20

On further investigation, it looks like this behavior started with Jetpack v12.6, and Jetpack v12.5 works as expected.

### Steps to reproduce

1. Create a new Jetpack test site (with jurassic.ninja or similar).
2. Connect Jetpack and purchase a bundled plan, like Security or Complete.
3. Visit My Jetpack and click 'Activate' on the Akismet card.
4. When the page refreshes, click 'Manage' on the Akismet card.

Screenshot 2023-10-11 at 14 18 24

If you're on Jetpack v12.6+, you should see the "Sorry, you are not allowed to access this page." error.

### A clear and concise description of what you expected to happen.

After purchasing a Jetpack bundle, I should be able to visit the Akismet config page to set it up.

### What actually happened

After purchasing a Jetpack bundle while running JP v12.6.2, I am not able to visit the Akismet config page and see the message "Sorry, you are not allowed to access this page."

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

In #32911, we changed Jetpack to try to start using Admin_Menu to register a menu for Akismet instead of doing it itself, to avoid a bug where we'd get duplicate menu entries if a standalone plugin initialized Admin_Menu before Jetpack got loaded.

Unfortunately it wasn't noticed that Admin_Menu specifically avoids registering a menu for Akismet if Jetpack is present, so now Akismet isn't being registered at all.

Fix that by removing that check, allowing Admin_Menu to register Akismet for Jetpack too.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/33550#issuecomment-1757583709
Fixes #33550

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Install and connect Jetpack. Purchase a plan that bundles Akismet. Ensure the "Akismet Anti-Spam" menu is present, and that you can successfully visit `/wp-admin/admin.php?page=akismet-key-config`.
* Install and activate Jetpack Backup. Ensure that only one Anti-Spam menu is present.

### CODE REVIEW

**Review by sergeymitr — DISMISSED** [review]
Works great 👍

**Comment by anomiex** [comment]
We'll want to wait on merging this now until the revert in #33551 is itself reverted. Details in https://github.com/Automattic/jetpack/issues/33550#issuecomment-1757967011.

**Comment by anomiex** [comment]
> We'll want to wait on merging this now until the revert in #33551 is itself reverted. Details in [#33550 (comment)](https://github.com/Automattic/jetpack/issues/33550#issuecomment-1757967011).

Included that revert in this PR now.

**Comment by sergeymitr** [comment]
@anomiex looks like it needs a trunk merge, please take a look.

**Review by sergeymitr — APPROVED** [review]

**Pull request merged**
