### PR TITLE
Packages: add new Post Images package

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

This PR introduces a new Post Images package, to replace the existing `Jetpack_PostImages` class in Jetpack and on WordPress.com.

**To do**

- [ ] The tests will need some work. They cannot work as is, as wordbless will not allow us to test against methods that use get_posts() right now.
- [ ] It may be worth considering making that package a "post-media" package instead, and include the `Jetpack_Media_Meta_Extractor` and `Jetpack_Media_Summary` classes as well.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Do the tests pass?
* Check the different features that rely on the class: Related Posts images, images in Open Graph Meta tags, ...

### CODE REVIEW

**Comment by kraftbj** [comment]
I do like the idea of having a general "Post Media" package and include `Jetpack_Media_Meta_Extractor` and `Jetpack_Media_Summary`

I think it's fine to handle each class in separate PRs, but plan on a `Post Media` package from day one.

**Comment by pablinos** [comment]
> I think it's fine to handle each class in separate PRs, but plan on a Post Media package from day one.

Is there enough to have this as one package, and then create a Post Media package that has this as a dependency? Or do we think that in the majority of cases, we wouldn't want to use the post image functionality on its own?

**Comment by jeherve** [comment]
I'll let @kraftbj weigh in, but I like your idea of having one Post Images package, and later on a Post Media package with the Post Images package as dependency.

**Comment by kraftbj** [comment]
No objection on my side to have those be two separate packages.

**Comment by jeherve** [comment]
closing in favor of #23371.

**Pull request closed without merging**
