### PR TITLE
Autoupdates: log error code

### PR DESCRIPTION
**Pull request by roccotripaldi**
Base on a conversation with @dd32 , we determined it would be useful to include an error code in
our debugging script when we log failed plugin autoupdates.

@dd32 can you check that i'm handling the `$update_results` schema correctly?

### CODE REVIEW

**Comment by dd32** [comment]
To be quite honest, I'm not sure of what the format is without getting down into the nitty-gritty testing which I assume you've already done to come up with the changes here. At first glance, it looks right to me.

The main thing I can think of is https://core.trac.wordpress.org/ticket/27365 which might affect it.
I'll happily setup a test environment and make plugin autoupdates break in every which manner on Jetpack/master when this is merged to be absolute certain it's working as expected though.

**Comment by roccotripaldi** [comment]
> I'll happily setup a test environment and make plugin autoupdates break in every which manner

That would be awesome!
And yes i've done a lot of testing to grok the contents of `$update_results`. I never thought of forcing plugin updates to fail, and your comment gave me some ideas of how to do that. Thanks.

**Comment by dd32** [comment]
> I never thought of forcing plugin updates to fail
There's two main ways I'd do this FWIW. One is to cause the updates to fail, for example setting file ownership to root (a common issue in the wild AFAIK), the other is to simply edit `WP_Upgrader` and trigger the error condition even when the process is succeeding (ie. throw an extra `!` in conditionals).

There's two main error scenario's which can be triggered here too, one is the errors which happen during the update process, the other is the errors which happen during file system connections. I don't think you'd need to worry about FS errors, as they should be far and few between (and only affect people who have forced a non-direct update transport)

**Comment by roccotripaldi** [comment]
So after some extensive testing, i've determined that https://core.trac.wordpress.org/ticket/27365 is correct in it assertion that the `result` property of every item does not contain valuable information.

So this PR is not really going to help us until 27365 is merged. But it is not causing any errors, and it should theoretically give us better data in some future core release. :)

**Comment by roccotripaldi** [comment]
This is easy enough to recreate when the time comes

**Pull request closed without merging**
