### PR TITLE
JS Components: Use clicks to summon IconTooltip

### PR DESCRIPTION
**Pull request by jsnmoon**
Follow-up on #26408

#### Changes proposed in this Pull Request:

Modifies IconTooltip to summon the Popover upon clicks instead of hovers. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

See #26408.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

Storyboard:
* Apply this change to your local checkout and spin up Storyboard
`cd projects/js-packages/storybook && pnpm run storybook:dev`
* Ensure that the IconTooltip component works as described.

Search Pricing Table:
* Apply this change on a Jetpack site without a Search subscription.
* Navigate to `/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`.
* Ensure that clicking on the information icon opens a persistent popover.
* Ensure that any links within the popover is clickable.

### CODE REVIEW

**Review by dognose24 — DISMISSED** [review]
Works as described! 👍🏼 However, I found the title section would be blurred after clicking. I committed with a tooltip container to recover `pointer-events` assigned on the tooltip helper, which makes the whole Popover content not blurable.

https://user-images.githubusercontent.com/6869813/192430568-4530b988-8f97-4d79-ab10-758da60a6513.mov

**Review by kangzj — APPROVED** [review]
This works well for me 🚀 

I have a minor suggestion tho - I would prefer the clicking on the icon to close the tooltip when it's shown, which I think is more intuitive?

**Comment by kangzj** [comment]
🚢  `r253327-wpcom`

**Comment by dognose24** [comment]
> I have a minor suggestion tho - I would prefer the clicking on the icon to close the tooltip when it's shown, which I think is more intuitive?

Yes, @kangzj! I have been noticing this operation would not be what I expected. However, there is a conflict between the `onClose` event and the `onClick` event on the icon, which makes the effect inconsistent after clicking. The tooltip will sometimes be hidden for clicking on the icon when the tooltip is shown, but sometimes it will not be. I will follow up on this suggestion when I find a solution.

**Pull request merged**
