### PR TITLE
Block patterns: use category name Testimonials rather than Quotes

### PR DESCRIPTION
**Pull request by miksansegundo**
Related p1702625675735679-slack-CRWCHQGUB

## Proposed changes:

* Remove code related to `core_to_wpcom_categories_dictionary` because it's not being used anymore
* Revert change to use category name testimonials rather than quotes 

### Other information:

- [X] Have you written new tests for your changes, if applicable?
- [X] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [X] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sandbox a site
* Apply these changes to your sandbox
* Visit the Site editor on your site to confirm the category "Quotes" is now "Testimonials"

### CODE REVIEW

**Comment by taipeicoder** [comment]
@miksansegundo tested and none of the pattern categories loaded on my end. I think it's because this PR removes the function `update_core_patterns_with_wpcom_categories` but it's still being call in here https://github.com/Automattic/jetpack/blob/7efce89837a98577828be88b2ceae75498b76d5a/projects/packages/jetpack-mu-wpcom/src/features/block-patterns/class-wpcom-block-patterns-from-api.php#L138

**Comment by miksansegundo** [comment]
Thanks @taipeicoder I missed that. I'm testing again

**Review by taipeicoder — APPROVED** [review]
LGTM 👍
Screenshot 2024-01-02 at 3 43 06 PM

**Review by miksansegundo — COMMENTED** [review]
Working 🎉

**Pull request merged**
