### PR TITLE
Docker: Clean out vendor and composer.lock before installing package deps

### PR DESCRIPTION
**Pull request by kraftbj**
Before installing a package's deps for testing, clean out the vendor and the non-VCS'd composer.lock.

#### Changes proposed in this Pull Request:
*

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
* `yarn docker:phpunit:package connection` on master, make manual changes to composer.json
* Run again, see no change with master.
* Switch to this version and run. See that vendor and composre.lock are fixed.

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by dereksmart** [comment]
Just as long as we're aware that doing this will slow down every phpunit run for packages, even if composer.json didn't change. I could imagine this may be a bit annoying if you are working on a package test and need to re-run it multiple times. 

So I guess it's a question of what's more annoying: 
- Manually needing to remove these files when you update composer.json
- Slower test runs 

Will leave it up to the next person to decide.

**Comment by kraftbj** [comment]
@dereksmart What would you think about a `yarn docker:phpunit:package [package] --use-lock` with help text outputted when not using it that `--use-lock` is an option or something like that to provide a way to not clean out the files?

Since, as things are, the composer.lock will never get updated, I'd rather default toward cleaning it out (vs confusion when running it for the first time in awhile and having something unexpected happen, which is where this pain point came up for me), but I can appreciate the situation you describe.

**Comment by kraftbj** [comment]
Let's try this again. I added the ability to pass `-c` or `--clean-lock` to remove the package `vendor` folder and `composer.lock`.

I've tested this in a few different ways:
`yarn docker:phpunit:package`
`yarn docker:phpunit:package -c`
`yarn docker:phpunit:package status`
`yarn docker:phpunit:package status -c`
`yarn docker:phpunit:package -c status`

**Comment by leogermani** [comment]
Could we get an update on our docker documentation along with this PR :) ?

**Comment by kraftbj** [comment]
Added reference to the `-c` in the docker docs and copied them to the generic dev docs too. @leogermani

**Pull request merged**
