### PR TITLE
Search: fix search submenu visibility

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
The filter to change to visibility of Search submenu is loaded too late, and might not be executed at all, which leads to an issue that the Search submenu is shown regardless.

The PR moved the loading of compatibility file to the very beginning of the search package initialization.

Sorry the issue took few PRs to settle.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- [Create a JN site](https://jurassic.ninja/specialops/) with Jetpack Beta with branch `fix/search-menu-visibility`
image

- Ensure Search submenu is not shown
- Connect site and purchase a Search subscription
- Ensure Search submenu is shown

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Nice, this work for me!

**Review by samiff — APPROVED** [review]
Thanks for working on this @kangzj 

This worked for me, though I do note that it seems like if a site _ever_ had a Search plan, then it'd continue to see the Search submenu even after that Search plan has been removed:

https://github.com/Automattic/jetpack/blob/556b650d0eb693ff14ce3f20afedf56b2d427b61/projects/packages/search/src/class-plan.php#L149-L153

I only mention that because the Search page without a plan could be a tad confusing:

Screen Shot 2022-03-30 at 3 12 45 PM

Not sure if there are other changes already in the works to change this up.

**Comment by kangzj** [comment]
Hi @samiff good cactch! Yep the intention of this is to let the user find a way to re-purchase the search product. This isn't ideal at all and we have scheduled a better upsell page this in the next release: https://github.com/Automattic/jetpack/issues/23570

**Comment by kangzj** [comment]
🚢 r242834-wpcom

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-10.8` in b51aa7ebe131f94aa43ff5cc665ec93261db2f2f 

automattic/jetpack-search package version `v0.12.1` published: https://packagist.org/packages/automattic/jetpack-search#v0.12.1

**Pull request merged**
