### PR TITLE
Mesh oEmbed

### PR DESCRIPTION
**Pull request by johngodley**
Remove the Mesh shortcode file (which doesn't work), and add the oEmbed provider directly via `extra_oembed_providers`, similar to Cloudup.

### CODE REVIEW

**Comment by zinigor** [comment]
@johngodley can you please specify how the embed doesn't work in `master`? Also, for me it breaks embeds in the visual editor inside wp-admin.

**Comment by johngodley** [comment]
It doesn't work because it doesn't convert Mesh URLs into an embed. You can verify this by adding `https://me.sh/zahwisu` to a post and confirming that nothing is embedded.

The original file also contains additional code that is only required on WP.com (for email subscriptions).

This PR moves the oembed endpoint to the same place as the Cloudup embed. If you then add `https://me.sh/zahwisu` to a post it will be converted into a Mesh embed.

How is it breaking embeds in the visual editor? It's just an oEmbed endpoint so the only thing it should be able to do is silently fail (the oEmbed endpoint doesn't work), or show the results of the embed.

Note that I've simplified the endpoint so it uses a wildcard rather than a regex.

**Comment by zinigor** [comment]
OK, this is strange. Before you added a commit, the links were were *not* being converted into embeds, but now they do. So when I run Jetpack from `master` as well as from this branch, pasting the link results into an embedded me.sh gallery in the post editor. This is why I don't understand why you say that it doesn't work. Can you please test again using the latest version of Jetpack?

**Comment by richardmuscat** [comment]
Can't contribute much from a tech standpoint but, if we're unsure of what needs to be done we can punt this to 3.8 as doesn't seem like a top priority for 3.7 given our long list of stuff.

**Comment by zinigor** [comment]
Scratch what I said, after discussing this one with John I realized I was not testing it properly. The oembed works fine, and I will handle the file sync when merging from wpcom next time. Let's get this in!

**Pull request merged**
