### PR TITLE
Donations block: Filter the donation subscriptions based on public property

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes [#61908](https://github.com/Automattic/wp-calypso/issues/61908)

#### Changes proposed in this Pull Request:

* Filter the donation subscription by public false to keep the existing behaviour of donation subscriptions

#### Testing instructions:

* Apply the diffs on your sandbox: `arc patch D77469 && arc patch D77465 --nobranch && arc patch D77864 --nobranch`
* Create a new site (so that you don't have any existing donation subscription that are hidden)
* Atomic: You'll need to use your WoA dev site and merge locally the branch from https://github.com/Automattic/jetpack/pull/23714 and sync your WoA site with these changes
* Atomic: add `define( 'JETPACK__SANDBOX_DOMAIN', 'your-sandbox');` to your wp-config.php
* Use the Calypso link to create a new donation subscription in `/earn/payments-plans/` from this [PR](https://github.com/Automattic/wp-calypso/pull/62208)
* Go to wp-admin/post-new.php and create a new donation block
* Using Network inspector, check if the donation block DOESN'T use the subscription you've created in `/earn`

### CODE REVIEW

**Comment by dsas** [comment]
The donation block *does* use the payment plan I created earlier.

I'm using a simple site. It gets it with GET and then it's in the POST back along with two new plans. If I publish the plan and look at the post content, the plan ID is in the plan.

**Comment by dsas** [comment]
Doh, that was because I was accessing gutenberg via the calypso url, via the sandboxed wp-admin address it does work properly!

The payment plan I created earlier is in the GET but a new plan is created in the POST and is used in the publish post PUT.

**Comment by dsas** [comment]
Works for me on simple sites

**Comment by dsas** [comment]
This isn't working for me on an atomic site, I'm not sure if it's because I've done something wrong or if it's because there is an actual bug.

The url being requested is `https://deanbackend.wpcomstaging.com/wp-json/wpcom/v2/memberships/status?source=gutenberg&type=donation&_locale=user`

To test 
1. My sandbox has D77465-code applied
2. Get a WoA dev blog
3. Set it to use jetpack bleeding edge via jetpack beta
4. Locally, checkout add/public-subscription and merge in origin/add/membership-endpoint-updates
5. Run `pnpx build-extensions` from the extensions directory locally
6. Use the bogdan special PR for AWE to run atomic-sync
7. If I then inspect files in `~/wp-content/plugins/jetpack` on the WoA site, they have been updated to include is_editable
8. Go to /wp-admin/post-new.php and add a donations block

**Comment by dsas** [comment]
Ok, tried again and it is working for me on atomic - I'm pretty sure it was a sync issue, the built files didn't include is_editable, just the source files.

**Review by dsas — APPROVED** [review]

**Review by Copons — APPROVED** [review]

**Comment by BogdanUngureanu** [comment]
Deployed in WPCOM in r244105-wpcom

**Pull request merged**
