### PR TITLE
Jetpack: move VideoPress block to extended blocks folder

### PR DESCRIPTION
**Pull request by retrofox**
The current implementation of VideoPress is not a block by itself but it extends and also overwrites the core/video block.
Thus, as an initial step to work on the new VideoPress block, it makes sense to move the code from extensions/blocks/videopress to extensions/extended-block/core-video folder to pave the way for adding, in follow-up tasks, the new block.

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack: move VideoPress block to extended blocks folder

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

No

#### Testing instructions:

It doesn't change anything in terms of the feature implementation, so the testing instructions are limited to verifying that the current implementation of VideoPress still works without any changes.

[Jetapack videopress product page](https://jetpack.com/support/jetpack-videopress/add-video-block-editor/)

* Use a testing site with Jetpack with VideoPress feature supported. You may need to buy a plan/product
* Add a `core/video` block
* Upload a video
* Confirm you see the file uploading with the VideoPress feature
* Change the block properties using the toolbar and/or block inspector
* Try to test as much as possible all features confirming it works as expected.
* Test the feature in the block editor context as well as in the front-end

core editor context | frontend
------|------
image|image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202490094773346

### CODE REVIEW

**Review by jgcaruso — APPROVED** [review]
The `/video` block continues to work as expected. Attribute changing, "global" setting changes (public/private state), fallback after disabling videopress (existing blocks stay as VP blocks, new ones are the core block), adding video via upload and media library.

**Comment by retrofox** [comment]
> The `/video` block continues to work as expected. Attribute changing, "global" setting changes (public/private state), fallback after disabling videopress (existing blocks stay as VP blocks, new ones are the core block), adding video via upload and media library.

Thanks, @jgcaruso for your review. Let's hold on a couple of days before merging it. We'd like to get the big picture of the whole implementation. But again, thanks for your help

**Comment by coder-karen** [comment]
@retrofox just checking in on this one, is it still in a waiting period before being ready for review, based on the last comment?

**Comment by retrofox** [comment]
> @retrofox just checking in on this one, is it still in a waiting period before being ready for review, based on the last comment?

Hi @coder-karen. I'm sorry I missed you comment. Let's close it. We've changed completely the files structure of the VideoPress code.

**Pull request closed without merging**
