### PR TITLE
Carousel: prevent interaction on transition

### PR DESCRIPTION
**Pull request by ramonjd**
#### Changes proposed in this Pull Request

Hello!

If you're like me, and love clicking fast you'd have noticed that clicking at great pace on the next and previous buttons of a gallery carousel sometimes triggers the built-in double click zoom effect.

To prevent that from happening, this PR activates a Swiper JS parameter `preventInteractionOnTransition` **for non-touch devices**. Quoting the API docs:

> When enabled it won't allow to change slides by swiping or navigation/pagination buttons during transition

| Before  | After |
| ------------- | ------------- |
|  |  |

You're still permitting to click fast!

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions

Fire up a gallery in a desktop browser (a non-touch device).

⏱️ Proceed to click as fast as you can. Next, previous, go for it!

The image shouldn't zoom.

Try on a touch device. You should be able to swipe as expected.

Other events such as pinch and zoom and double tap (on the image) should also work as expected.

### CODE REVIEW

**Comment by andrewserong** [comment]
Oh, nice change @ramonjd, that's working well on desktop (tested Safari, FF, Chrome and Edge on Mac), no more unexpected zooming while rapidly clicking on the next or prev buttons 👍

On mobile, I noticed this introduces a subtle limiting to how quickly we can swipe left / right through the carousel. I'm not a fast clicker on desktop, but I'm definitely a fast swiper on my phone! 😄

### Before

Previously, I can immediately swipe to the next slide without any delay between transitions:

https://user-images.githubusercontent.com/14988353/127279845-7e456c6d-af80-43a8-856c-c1d310392ae4.MP4

### After

After, there's a subtle delay before moving to the next slide:

https://user-images.githubusercontent.com/14988353/127279901-afddbcab-23a5-4a31-8c4b-4327f02faba5.MP4

Would it be possible for us to add a check to conditionally set this setting to `true` only if we're not on a touch device?

In `calculatePadding` we have this existing line that checks for a touch device:

```
				var isTouch =
					'ontouchstart' in window || ( window.DocumentTouch && document instanceof DocumentTouch );
```

So we could either duplicate that (or move it to a function) and then set the property to:

```
preventInteractionOnTransition: isTouch ? false : true,
```

What do you think?

**Comment by ramonjd** [comment]
> Would it be possible for us to add a check to conditionally set this setting to true only if we're not on a touch device?

Very possible. Thanks for the suggestion. I'll add it in.

I did test in mobile, but I must be a slow swiper :)

**Comment by ramonjd** [comment]
> Would it be possible for us to add a check to conditionally set this setting to true only if we're not on a touch device?

Added in bed515e986782ebe3efb601250cc27dc6d4e48a6 

Cheers 🍺

**Review by andrewserong — APPROVED** [review]
Nice one, thanks @ramonjd!! The fast clicking issue in desktop (Safari, Chrome, FF, and Edge) is resolved, and I can still fast swipe on iOS Safari + Chrome 👍

LGTM!

**Review by samiff — APPROVED** [review]

**Comment by samiff** [comment]
cherry-picked to JP 10.0 release branch in c241c5333ad36e749c2d72c108424a10caba8de9

**Comment by samiff** [comment]
r230703-wpcom

**Pull request merged**
