### PR TITLE
My Jetpack: allow plugins to override a product class

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

* Adds a filter that allows plugins to override the class used by My Jetpack to represent a product

This will allow Search (and other plugins) to take over how their product behave in My Jetpack once the plugin is active.

#### Jetpack product discussion

p9dueE-55u-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Add this to your theme functions.php or to a plugin:
```PHP
class Mock_Boost_Child extends Automattic\Jetpack\My_Jetpack\Products\Boost {
	public static function get_name() {
		return 'Child Boost';
	}
}

add_filter( 'my_jetpack_products_classes', 'my_filter' );

function my_filter( $classes ) {
  $classes['boost'] = 'Mock_Boost_Child';
  return $classes;
}
```
* Visit My Jetpack and make sure the Boost card now says "Child Boost"
* Make sure all tests pass

### CODE REVIEW

**Comment by kangzj** [comment]
HI @leogermani thanks for working on this 👍 

IMHO, the module is already just for the Search module/plugin. And would it be convenient just to implement the logic there? If we just had the general logic for all hybrid plugins, then it makes more sense to allow plugins to override. Also if standalone plugins are not activated yet, the override wouldn't work at all. 

We don't have to actually merge #24385 to make the whole thing work (although that might be better because we could extract a process for all hybrids), we can just test whether `Automattic\Jetpack\Search\Module_Control` exists, if not, then Search is surely not active, otherwise call `Automattic\Jetpack\Search\Module_Control::is_active()`.

For activation, the class activate plugins accordingly, and then calls `Automattic\Jetpack\Search\Module_Control::activate()` to activate Search product.

Will spin up a PR to show what I'm thinking.

**Comment by leogermani** [comment]
Hey @jasperck 

When https://github.com/Automattic/jetpack/pull/24385 gets merged, I'll change My Jetpack and it will rely on the new Modules class. Once we do that, we might not need any customizations for Search and this will work for all Hybrid products.

If we don't get that on time, we can add Search specific actions in My Jetpack more or less the way you suggested. But in any case we'll need this PR.

Eventually we we'll need plugins to override things in My Jetpack, and we want to keep My Jetpack as agnostic as possible. Here are a couple of reasons why it's better to have specifics be handled by the plugin:

1) Plugin teams have full control over the code and its approval - If the team has the right to merge PRs for its plugin, they won't have to wait for Crew to approve changes
2) When you touch and modify code on My Jetpack, you are touching and modifying code in all plugins, because My Jetpack is shipped to all of them.

You are right the overriding the activation won't work because the plugin is activated in the middle of the process, but we have the filter for that.

However, the `is_active` check will work just fine.

So if you want to change the destination of the `Manage` button for example, you could also override the class. The more the things that are specific to what happens after the plugin is active live in the plugin code, the better.

**Comment by kangzj** [comment]
Hi @leogermani awesome agreed sounds great ❤️ 

Just let you know that, we do have a special thing to do after search module is activated, we need to enable the instant search experience which is the default experience. see code: 

https://github.com/Automattic/jetpack/pull/24425/files#diff-7a71c842fccd45da22b718860df19a9dc0afbb778bde25ef6432ddfe6a3c7b9fR261

**Comment by leogermani** [comment]
closing in favor of a brand new one: https://github.com/Automattic/jetpack/pull/25891

**Pull request closed without merging**
