### PR TITLE
Related Posts: decode ellipsis at the end of a long excerpt

### PR DESCRIPTION
**Pull request by jeherve**
screen shot 2014-11-08 at 5 00 59 pm

Reported here:
https://wordpress.org/support/topic/related-posts-hellip-typo-on-hover?replies=3

@xyu My patch works, but I wonder if there would be a better way of doing it, and if my patch could cause things to break, somehow?

### CODE REVIEW

**Comment by jeherve** [comment]
@xyu bd1241da924f791f90227bb74191cfc765f05e6f works nicely the ellipsis at the end of the excerpt, but the problem remains for other special characters in the excerpt:

screen shot 2015-01-13 at 3 02 53 pm

My Pull Request fixes the problem, but as you mentioned:

> Decoding like this may end up opening up some XSS vulnerabilities

Can you think of another solution?

**Comment by jeherve** [comment]
@xyu Do you think we could merge this in the next release?

**Comment by xyu** [comment]
I'm probably doing it wrong but...

I just made a PR for this change at: https://github.com/jeherve/jetpack/pull/1, basically we should escape on output now that we are calling `html_entity_decode()` on the server side.

**Comment by jeherve** [comment]
@xyu That looks good to me!

**Pull request merged**
