### PR TITLE
REST connection/data endpoint: Move to Connection package

### PR DESCRIPTION
**Pull request by fgiannar**
Moves `jetpack/v4/connection/data` endpoint from Jetpack-the-plugin to the Connection package.

#### Changes proposed in this Pull Request:

* Moves  `jetpack/v4/connection/data` endpoint to Connection
* Introduces the `jetpack_current_user_connection_data` filter that enables adding extra data (unrelated to Connection but related to Jetpack-the-plugin) to the returned response
* Optimizes `Manager::get_connected_user_data` by checking if the user is actually connected before making an XMLRPC call to WPCOM
* Fixes a few errors in `Test_REST_Endpoints` unit tests.

#### Jetpack product discussion

1199658893173824-as-1200636806056115/f

#### Does this pull request change what data or activity we track or use?

No

#### Without Jetpack-the-plugin

1. Spin up a JN site from this PR. Do not activate Jetpack, instead install the [Jetpack Connection UI Activator plugin](https://gist.github.com/sergeymitr/bc005e1b893e778c03e4f43debb91c30).
2. Go to "Tools -> Connection Manager".
3. After fully connecting make sure your WPCOM avatar and display name appear correctly in the Connection Info:

Screenshot 2021-07-22 at 5 34 10 PM

#### With Jetpack-the-plugin
4. Activate Jetpack
5. Make sure your WPCOM avatar and display name appear correctly in the Jetpack Dashboard (Account Connection section):
Screenshot 2021-07-23 at 4 11 52 PM

### CODE REVIEW

**Comment by kbrown9** [comment]
The team briefly discussed whether moving this endpoint could cause any backward compatibility issues with old versions of Jetpack. I looked into it, and here’s what I’ve found:

The `register_rest_route` [function](https://developer.wordpress.org/reference/functions/register_rest_route/) can accept an optional `$override` parameter. The function calls `WP_REST_Server::register_route`, and that where the value of `$override` [is important](https://developer.wordpress.org/reference/classes/wp_rest_server/register_route/):

```
if ( $override || empty( $this->endpoints[ $route ] ) ) {
    $this->endpoints[ $route ] = $route_args;
} else {
    $this->endpoints[ $route ] = array_merge( $this->endpoints[ $route ], $route_args );
}
```

So, we can end up with two sets of args in the `connection/data` route's array if the second (or later) endpoint registration does not have the `$override` parameter set to true.

When it’s time to dispatch the request, the `WP_REST_Server::match_request_to_handler` [method ](https://developer.wordpress.org/reference/classes/wp_rest_server/match_request_to_handler/)selects the first matching callback.

We discussed possibly using the `register_rest_route` function's `$override` parameter to ensure that the latest version of the endpoint from the Connection package is registered. Now that I’ve looked closer at the changes, I think that could cause problems. If an older version of Jetpack that does not include the `jetpack_current_user_connection_data` filter hook is active, some permission data won’t be included in the response.

I think we could also run into the same issue with missing permission data if the Connection package’s REST route is registered first while an older version of Jetpack is active. The Connection package’s callback would be used, but the Jetpack plugin won’t have anything hooked to the `jetpack_current_user_connection_data` filter.

I’m not sure what the permissions that Jetpack adds to the filter are used for, so I don’t know what the impact of missing permissions would be.

I don't have ideas for a solution for this yet.

**Comment by kbrown9** [comment]
> I think we could also run into the same issue with missing permission data if the Connection package’s REST route is registered first while an older version of Jetpack is active. The Connection package’s callback would be used, but the Jetpack plugin won’t have anything hooked to the jetpack_current_user_connection_data filter.

Following up on this part of my last comment - while this situation is possible, it seems unlikely. The Jetpack plugin hooks its endpoint registrations to the `rest_api_init` action very early. The `load-jetpack.php` file loads the `_inc/lib/class.core-rest-api-endpoints.php` file, which [sets up the hook](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/class.core-rest-api-endpoints.php#L27). The connection package endpoints hooks are typically set up later, during the `plugins_loaded` action. This causes Jetpack's REST route to be registered first if it exists.

I think Jetpack's REST route will be used when an old version of Jetpack is active. It looks like we didn't make any changes to the callback method, so I think it should be ok to allow Jetpack's route to be used instead of the connection package's route when an old version of Jetpack is active.

I feel like this is all a bit complex and could cause confusion in the future. A simpler option might be to check for a Jetpack version, and do a version compare to determine whether we should register the route in the Connection package. If a JP version < 10.0 is active, we would use Jetpack's route. Otherwise, we would register the Connection package's route.

**Comment by kbrown9** [comment]
I did some testing of this PR, and everything worked as expected. I think this will be ready to merge once we've decided on how to handle the situation where both an old version of Jetpack and the Connection package register the `jetpack/v4/connection/data` endpoint.

**Comment by fgiannar** [comment]
> I did some testing of this PR, and everything worked as expected. I think this will be ready to merge once we've decided on how to handle the situation where both an old version of Jetpack and the Connection package register the `jetpack/v4/connection/data` endpoint.

Hi @kbrown9 !

First of all, many thanks for taking the time to investigate this issue!

> I feel like this is all a bit complex and could cause confusion in the future. A simpler option might be to check for a Jetpack version, and do a version compare to determine whether we should register the route in the Connection package. If a JP version < 10.0 is active, we would use Jetpack's route. Otherwise, we would register the Connection package's route.

I agree we should go with the simpler option possible. I've implemented the suggested approach and added the corresponding unit tests.

**Review by kbrown9 — APPROVED** [review]
This tests well for me. I tested the following conditions, and the `connection/data` endpoint returned the expected data. The connection card on the Jetpack dashboard and the Connection Manager both displayed the user's connection info correctly.

* Backup with the new Connection package and Jetpack 9.9.1.
* Backup and Jetpack with the new Connection package.
* Backup with the new Connection package.
* Jetpack with the new Connection package.

**Pull request merged**
