### PR TITLE
Admin Page: new Performance tab.

### LINKED ISSUE #10550: Settings: create a new settings tab for performance
This issue is a placeholder to discuss creating a new tab in settings for Performance-related features like image and file CDN, lazy load, AMP (just a promotion), WPSC (just a promotion), and so forth. 

The tab would want to have a pre-amble at the top explaining our performance options and perhaps piloting an autopilot or turbo booster master switch.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10550

#### Changes proposed in this Pull Request:

This PR moves existing cards over to a new "Performance" section in Jetpack settings, and makes that "Performance" tab the new default tab you see when heading to Jetpack > Settings in your dashboard.

image

#### Testing instructions:

* Go to Jetpack > Settings
* Make sure all settings work, including the new Performance section.

#### Proposed changelog entry for your changes:

* Jetpack Dashboard: add a new "Performance" section

### CODE REVIEW

**Comment by keoshi** [comment]
This PR should be coordinated with https://github.com/Automattic/jetpack/pull/10940 — I'll make sure to at least have the copy ready to go for this new tab.

**Comment by keoshi** [comment]
Added the performance settings description in https://github.com/Automattic/jetpack/pull/10941/commits/a6ae3d62744fba44b3c1e137a37fece5fc195b4e

See: https://github.com/Automattic/jetpack/pull/10940

**Comment by keoshi** [comment]
Resolved the conflicts above.

**Review by zinigor — APPROVED** [review]
Read the code, tested in the admin both with usual tabs and in search mode, seems to be working fine!

**Review by jeffgolenski — APPROVED** [review]
This is brilliant. Thank you @jeherve @keoshi

**Comment by jeffgolenski** [comment]
This is great. Now we just need to push the same changes on the calypso side as well!

**Pull request merged**
