### PR TITLE
VideoPress: Add `poster` endpoint for updating and getting poster

### PR DESCRIPTION
**Pull request by renatoagds**
This one includes a new endpoint (`/:guid/poster`) that will accept `GET` and `POST` calls to update and retrieve poster image.

Related with #26153 

#### Changes proposed in this Pull Request:

* Add new route
* Include utilities for tokens
* Avoid override default `Authorization` for `Connection` method

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Open `/wp-json/wp/v2/media` in your browser. 
* Choose one video and get it `videopress_guid`.
* Open/Download [Postman](https://www.postman.com/)
* Create a new POST Request for `/wp-json/wpcom/v2/videopress/:videopress_guid/poster`
* Select `raw` and `JSON` as body.
* Set the body for: `{ "at_time": 1000, "is_millisec": true }`
* Run the request.
* It should return `code:200` and `data` with `generating: true` - ⚠️ do not open the returned poster url, for some reason it breaks the generation.
* Change the request type for `GET`.
* Run it until `generating` becomes `false`.
* Now, open the poster, it should be a new image from `1sec` frame.

### CODE REVIEW

**Comment by lhkowalski** [comment]
@renatoagds I was able to run it and use it to set the new poster, following the testing instructions. Having this available to any user that can `read` is the expected behavior, permission-wise?

**Comment by renatoagds** [comment]
> Having this available to any user that can read is the expected behavior, permission-wise?

@lhkowalski that's a good question, that I don't know the answer, that's the reason I ask for kernel folks help. @sergeymitr will join here to review it.

p1663675633957359-slack-C02NENKA4GN

**Review by sergeymitr — APPROVED** [review]
Looks great, tests well 👍

**Comment by renatoagds** [comment]
r253083-wpcom

**Pull request merged**
