### PR TITLE
Conversation/Dialogue: use `parent` block settings to limit Dialogue availability

### PR DESCRIPTION
**Pull request by retrofox**
This PR removes the custom template-lock system since we consider it could bring performance issues. Using the `parent` block setting property will be ok to provide a lock system for the Dialogue block for v1.
We wanted to make the Dialogue block available also for deeper nesting levels but finally decided to remove it, at least for this first implementation.

Fixes #

#### Changes proposed in this Pull Request:

* Conversation/Conversation: use `parent` block settings to limit Dialogue availability

#### Jetpack product discussion

p1613137937245000-slack-

#### Testing instructions:

* Create a new post
* Confirm the `Dialogue` is not available from the blocks picker

* Create a `Conversation` block
* Confirm the `Dialogue` block is properly rendered
* Confirm you can add/remove/edit the `Dialogue` blocks
* Confirm you can add other blocks into the `Conversation` block.

image

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
Confirmed dialogue blocks are only available inside a Conversation block, and that they work as expected. ✅

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to break the automatic addition of new dialogue blocks when you create a first dialogue block, then hit enter to create a second one.

**Comment by creativecoder** [comment]
> This seems to break the automatic addition of new dialogue blocks when you create a first dialogue block, then hit enter to create a second one.

@jeherve I'm not seeing this problem with this PR applied 🤔

Screen Recording 2021-02-12 at 12 07 42

**Review by creativecoder — APPROVED** [review]
This is working for me: dialogue block is available within a conversation block but not outside of it. And removing the filter to avoid potential performance issues is 💯 !

**Review by jeherve — COMMENTED** [review]
I still cannot seem to get this to work. This is on a site without the Gutenberg plugin; no js errors but I cannot seem to add more than one dialogue block:

https://user-images.githubusercontent.com/426388/107940755-0630db80-6f89-11eb-9948-b729907694e7.mov

**Comment by retrofox** [comment]
> I still cannot seem to get this to work. This is on a site without the Gutenberg plugin; no js errors but I cannot seem to add more than one dialogue block:
> 
>  Screen.Recording.2021-02-15.at.12.23.48.mov

Thanks. Looking again.

**Comment by retrofox** [comment]
> > I still cannot seem to get this to work. This is on a site without the Gutenberg plugin; no js errors but I cannot seem to add more than one dialogue block:
> > Screen.Recording.2021-02-15.at.12.23.48.mov
> 
> Thanks. Looking again.

I've tested again. Last core version, with Jetpack version (core version 5.6.1) and also switched to `core version 5.5`. It works as expected.

Screen Shot 2021-02-15 at 9 28 08 AM

I asked for help from @pablinos to try to detect this problem.

**Review by jeherve — APPROVED** [review]
This works for me now. I'm not sure what was happening before. 🚢

**Comment by retrofox** [comment]
r221065-wpcom

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in c24db4937c8467afdf805266199c614d0e24f74a

**Pull request merged**
