### PR TITLE
Check currently stored value of the `mfold` user setting before updating

### LINKED ISSUE #25332: User meta cache being purged on every wp-admin request
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Make sure some persistent cache storage is enabled in your test environment (eg.: memcache)
2. Have Gutenberg the plugin installed
3. Go to /wp-admin screen while having some plugin showing the SQL queries enabled (debug bar, query monitor)
4. Notice that there is a SQL query collecting all user meta during the screen load
5. Go to some other wp-admin screen and notice the SQL query for fetching all user meta is still present

### A clear and concise description of what you expected to happen.

All user meta should be properly cached, and the related SQL query should only happen once and stay cached till the user meta are not changed. Those should only be changed when necessary.

### What actually happened

Jetpack, via the [sync_sidebar_collapsed_state](https://github.com/Automattic/jetpack/blame/b82dce6b08932eae8b31eede5aa8b77b22edc36b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L435) function unnecessarily updates the user settings on every admin screen load, as it's not checking the currently stored value for the `mfold` setting.

WordPress updates the settings timestap (sets it to a value returned by the `time()` function ) along with each setting set, thus makes the value of the user meta different, which leads to database being updated, as well as user meta cache being purged.

### Browser

_No response_

### Other information

Related to https://github.com/Automattic/wp-calypso/issues/66063

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by david-binda**
The `set_user_setting` function always updates the settings update timestamp, making the stored value unique, which leads to DB writes and user meta cache being purged on every wp-admin screen.

In this changeset, a logic for checking the currently stored value is added, which allows the code to only call the `set_user_setting` function if the value needs to be updated, ultimatelly preventing unneccessary database writes, and user meta cache purging.

Fixes #25332

#### Changes proposed in this Pull Request:

*

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Have memcache or other persitant cache storage installed in your testing environment
* Have a debug bar, query monitor, or some other plugin allowing to inspect SQL queries for a request installed
* Have Gutenberg the plugin installed
* Go to the /wp-admin screen
* Check the SQL queries, a SQL query for collecting and updating all user meta should be present
* Reload the /wp-admin screen, the same SQL query should be still present
* Apply the patch repeat the 2 previous steps, the SQL query should not repeat itself

### CODE REVIEW

**Comment by david-binda** [comment]
I have looked into adding PHPUnit tests covering the `sync_sidebar_collapsed_state` method, however, I have run into an issue with the `set_user_setting` function, which checks for `headers_sent()`, and if it's return is true, it's returning early, making the tests to not ever pass, since the `headers_sent()` is always true.

So I'm afraid that this functionality will have to exists without tests.

**Comment by samiff** [comment]
> Check the SQL queries, a SQL query for collecting and updating all user meta should be present
> Reload the /wp-admin screen, the same SQL query should be still present

@david-binda I'm having some trouble following along with the testing steps on this one. Would a WoA site be a good test candidate for this? I wasn't able to see a difference in queries pre/post patching, and I'm not exactly sure what the db action I'm checking for looks like. Thanks!

**Comment by david-binda** [comment]
Thanks for looking into this @samiff , and sorry for not providing detailed info.

> Would a WoA site be a good test candidate for this?

I have noticed and tested the patch on WPCOM simple sites.

>  I wasn't able to see a difference in queries pre/post patching, and I'm not exactly sure what the db action I'm checking for looks like. Thanks!

The queries in question are coming from `Automattic\Jetpack\Dashboard_Customizations\WPcom_Admin_Menu->sync_sidebar_collapsed_state` and look like following:

```
SELECT umeta_id FROM wp_usermeta WHERE meta_key = 'wp_%d_user-settings-time' AND user_id = %d
UPDATE `wp_usermeta` SET `meta_value` = '%d' WHERE `user_id` = %d AND `meta_key` = 'wp_%d_user-settings-time'
```

Please, let me know if it helps. Some more details are in https://github.com/Automattic/wp-calypso/issues/66063

**Comment by samiff** [comment]
> I have noticed and tested the patch on WPCOM simple sites.

Thanks for the additional details. `class-wpcom-admin-menu.php` wouldn't even load on a WoA site like I was first trying. 

Was able to see the correct query this time around, and this looks good to go 👍

**Review by samiff — APPROVED** [review]

**Pull request merged**
