### PR TITLE
Move Whatsapp styles to Send-a-Message directory

### LINKED ISSUE #18940: WhatsApp Block: Styling and Alignment Inconsistencies
Lots of styling issues with the WhatsApp block. This might be related to the state the block in is now - being a child of "send a message" while somehow also being named as its own parent block. 

> “Chat on WhatsApp” doesn’t appear to be correctly styled on the published post:

image-5-15

> Once aligned to the left, it’s harder to select the button again for the controls to show up. You have to click on the lower part of the button to make the selection again.

> Alignment issues as mentioned elsewhere. This Block frequently collapses behind other Blocks that end up wrapping entirely around it and making it difficult to click again. Some Blocks collapse around it and some don’t. Behavior is inconsistent.

> When center aligned, the Block has additional space on the bottom compared to when it it Left or Right aligned.

Related:

> The Block is named “Send a Message” in the overall List View, but only “WhatsApp Button” in the Block browser (although it is still searchable by either term). It’s somewhat confusing.

If these are separate issues, happy to break this down into multiple distinct bug reports instead. 

**Additional Context**
p8oabR-Co-p2#comment-5013
p8oabR-Co-p2#comment-5050

### PR DESCRIPTION
**Pull request by stacimc**
https://github.com/Automattic/jetpack/pull/18487 moved the required plan check from the Send-a-Message block down to the WhatsApp block. In order to do this, it was necessary to change the block's entry in `jetpack/extensions/index.json` from `send-a-message/whatsapp-button` to `whatsapp-button`, so that it would match the slug used in registering the block on the backend here: https://github.com/Automattic/jetpack/blob/7a208dc8117f025d9846501ae49ed97a9a9aaa05/projects/plugins/jetpack/extensions/blocks/send-a-message/whatsapp-button/whatsapp-button.php#L24

This breaks the CSS, because the [code that loads in styles](https://github.com/Automattic/jetpack/blob/7a208dc8117f025d9846501ae49ed97a9a9aaa05/projects/plugins/jetpack/class.jetpack-gutenberg.php#L569) expects the path to the `view.scss` file to match the block name, so `send-a-message/whatsapp-button` in this case.

Essentially there are competing naming conventions here. This PR proposes a quick fix by moving the styles up to the parent block `Send-a-Message` directory, which does not have the same naming issue, and loads it from there.

Fixes https://github.com/Automattic/jetpack/issues/18940

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

On Jetpack, you will need to pull the branch and run `yarn run build` before testing.
On wpcom, test by applying the diff.

* Create a new post and add a WhatsApp button
* View the post on the frontend and verify that styles have loaded in
* Follow instructions from https://github.com/Automattic/jetpack/pull/18487 to verify that the upgrade nudges are still working.

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Comment by andrewserong** [comment]
This is testing well for me @stacimc both here and in the generated wpcom diff (D57726-code), but I actually wasn't able to recreate the reported issue in https://github.com/Automattic/jetpack/issues/18940, so I'm 100% sure that I was testing the problem correctly. Hopefully someone else can verify, too. Since it appears to be working correctly for me, though, I'll switch this over to Needs External Review.

**Review by jeherve — APPROVED** [review]
This works right now, I'll consequently merge this so as to fix the issue in the Jetpack release branch. However, I worry that this work-around may not be the best for the future. When we add more "send a message" options, this will not scale well. Do you think we could take a different approach?

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.5` in dae1dd8aeafa78cf8c26080415003d773fb6bd97

**Comment by stacimc** [comment]
> This works right now, I'll consequently merge this so as to fix the issue in the Jetpack release branch. However, I worry that this work-around may not be the best for the future. When we add more "send a message" options, this will not scale well. Do you think we could take a different approach?

@jeherve I completely agree. I'll open a ticket to resolve the underling block naming issue now that the immediate problem is taken care of.

**Comment by jeherve** [comment]
Thank you!

**Pull request merged**
