### PR TITLE
Shortcodes: fix content_width handling for various shortcodes

### LINKED ISSUE #27269: Shortcode [googleapps] width bug in t23
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On WP 6.1 with default Twenty Twenty-Three, go to a page and insert a Shortcode block
2. Enter a Google Apps shortcode like `[googleapps domain="drive" dir="file/d/137o4SVU9iyEdhtni-W4_mNHIRYx9GKMW/preview" width="650" height="480" /]`
3. Save and see the front end.

### A clear and concise description of what you expected to happen.

On the front end, it used to show an iframe embedded file, 650 pixels wide and 480 pixels high.

### What actually happened

The iframe embed has a width of 300 pixels.

### Browser

Google Chrome/Chromium

### Other information

Original WP.org thread https://wordpress.org/support/topic/shortcode-googleapps-width-bug-in-t23/

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by samiff**
Fixes #27269

#### Changes proposed in this Pull Request:

Instead of checking `isset( $content_width )` which may not always be numeric (e.g., could be bool false), check for `is_numeric( $content_width ) && $content_width > 0` since the content width may be assigned as the iframe width in this block.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

**Reproduce initial bug:**

- On a Jetpack connected site in `/wp-admin/admin.php?page=jetpack_modules` make sure you have `Shortcode Embeds` and `Custom CSS` activated.
- Activate the `Twenty Twenty-Three` theme.
- Edit a post and include the following in a shortcode block:

```
[googleapps domain="drive" dir="file/d/1gCZNONFnuELwj1iq74wJocnpCK1ve4c2/preview" width="650" height="480" /]
```

- Publish the post and inspect the iframe on the frontend. You will see the width attribute has been dropped:

Screenshot 2022-11-04 at 2 30 05 PM

**After patching with this PR:**

- Refresh the frontend preview and observe that the iframe has the width attribute as specified in the shortcode:

Screenshot 2022-11-04 at 2 31 39 PM

### CODE REVIEW

**Comment by RavanH** [comment]
Question: would this break shortcodes that use `width="100%"` for example?

**Comment by samiff** [comment]
> Question: would this break shortcodes that use `width="100%"` for example?

That behavior would remain unchanged with the change in this pull request; the check for `is_numeric( $attr['width'] )` would fail for `100%` so it'd be skipped.

**Review by anomiex — COMMENTED** [review]
I was not able to reproduce the bug following the instructions. The `$content_width` global is unset/null, not false as implied in some of the discussion. But the change itself looks sensible.

I note there's similar code in a few other places:

* https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/shortcodes/crowdsignal.php#L540-L546
* https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/shortcodes/facebook.php#L68-L70
* https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/shortcodes/googleapps.php#L163-L165
* https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/shortcodes/instagram.php#L182
* https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/shortcodes/vr.php#L86

There's also [this](https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/videopress/shortcode.php#L108) and [this](https://github.com/Automattic/jetpack/blob/817522a2959ac335bf444c80bd32fe88f20bd2da/projects/plugins/jetpack/modules/videopress/shortcode.php#L115), which should be ok since false will not be greater than the minimum width being checked there. Same for a few checks for `! empty( $content_width )`, false won't pass that.

**Comment by samiff** [comment]
> I was not able to reproduce the bug following the instructions. The `$content_width` global is unset/null, not false as implied in some of the discussion

Thanks for giving this a test Brad. I dug a little deeper into where the global `$content_width` was getting set to `false` and that seems to be an interaction between having our "Custom CSS" module activated:

https://github.com/Automattic/jetpack/blob/38c2f87dacfc6349a228f29d74a7492dbfad04e4/projects/plugins/jetpack/modules/custom-css/custom-css-4.7.php#L996-L1008

And this function:

https://github.com/Automattic/jetpack/blob/87ffd3e2d0ecf42fd86923f3870659a1e135c10e/projects/plugins/jetpack/class.jetpack.php#L5551-L5554

> I note there's similar code in a few other places:

Modified those bits in [cf60f67](https://github.com/Automattic/jetpack/pull/27276/commits/cf60f6727dee13d1a6b38960cfbc5b43b0b1a124)

**Review by anomiex — APPROVED** [review]
Good work tracking that down. LGTM.

**Comment by RavanH** [comment]
Thanks @samiff @anomiex for digging and fixing this!

**Pull request merged**
