### PR TITLE
Remove FAB: Remove obsolete floating action button from atomic sites.

### PR DESCRIPTION
**Pull request by renancarvalho**
## Summary of your changes 
Removes the FAB button from atomic sites.  
image

## Proposed changes:
Since the Help Center release, we are not using the FAB button anymore, [this issue](https://github.com/Automattic/wp-calypso/issues/72390) reports that FAB button is still visible in the MailPoet plugin on atomic. This PR fixes it by removing FAB render call.
This PR is not fixing the duplicated help center on the Masterbar, this will be part of another PR.

Partially Fixes #72390

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
Don't think so.

## Does this pull request change what data or activity we track or use?
Don't think so.

## Testing instructions:
Honestly I am not sure what's the best way to test it.

What I propose is:

**On Jetpack Repo.**
- Pull this branch 
- Build the plugins using `pnpm jetpack build plugins/jetpack`

**On Atomic site**

- Install the MailPoet plugin ([check issue](https://github.com/Automattic/wp-calypso/issues/72390))
- Connect via FTP into your atomic 
- Once connected to your atomic, navigate to `/srv/htdocs/wp-content/plugins/jetpack/modules` 
- Copy from your jetpack repo `/jetpack/projects/plugins/jetpack/modules/masterbar.php` into your atomic.

Open your atomic site again, you should **not** see the FAB button on the bottom right of the page
image

## Open to discussion

I believe we could remove the folder named `inline-help` inside `/jetpack/projects/plugins/jetpack/modules/masterbar` since it renders FAB content and it is obsolete, I did not remove it because I am unsure if other places are relying on it and we don't have it mapped. I am curious about your opinion and happy to follow up on that if necessary.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Maybe we can remove the whole `projects/plugins/jetpack/modules/masterbar/inline-help` directory now?

**Comment by renancarvalho** [comment]
> Maybe we can remove the whole `projects/plugins/jetpack/modules/masterbar/inline-help` directory now?
Hi @jeherve, thank you for checking this PR :) 
Yes, I wrote it at the end, I am just not sure if it is being used somewhere else, but I have also tested it removing the folder and worked fine as well. Do you think is safer to remove ? I can create another commit with this change.

**Review by jeherve — APPROVED** [review]

**Review by samiff — APPROVED** [review]
Tests well for me :shipit:

**Comment by samiff** [comment]
@renancarvalho Had to revert this one in #28648

Let me know if you need a hand looking at it 👍

**Pull request merged**
