### PR TITLE
Paypal Block: Fix issues with site editor

### LINKED ISSUE #19486: Site Editor Compatibility: Simple Payments (Pay with PayPal) block issues in editor and front end views
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some issues with the Simple Payments / Pay with Paypal block within the editor and front end of the site.

#### Steps to reproduce the issue

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Pay with PayPal button into the Footer template part
3. Observe that some of the styling is slightly off (the chevron in the currency field rendered beneath the field, font sizes are slightly off)
4. Go to upload or insert a product image
5. The image gets rendered outside of its container
6. Save the template part, and view the front end of the site
7. Observe that the product does not appear to be rendered on the site

#### What I expected
The UI to behave and look the same as when used in the post editor of a normal site running the Twenty Twenty theme.

#### What happened instead
* The editor UI didn't contain the product image as expected, and there were styling issues.
* The product did not get rendered on the front end of the site

##### Editor UI

image

##### Editor UI (block de-selected)

image

##### Front end of the site (note that the product does not appear to be rendered)

image

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/jetpack/issues/19486

#### Changes proposed in this Pull Request:

* Fix an issue that stops the paypal block from rendering in the front end when used within the site editor.
* Fix an issue where the product image would be huge in the editor
* Fix form rendering issues so the form renders consistently in the post and site editor

Before in site editor:

114128156-1472f680-993f-11eb-9d65-27b34cdfff14

After in site editor:

Screen Shot 2021-04-20 at 3 09 47 PM

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Activate TT1-blocks
* Open the site editor and insert a paypal block.
* Add a product image and confirm the size looks correct.
* Fill out the product details and preview the template on the front-end. Confirm the product is visible.
* Confirm the form renders correctly in the editor as per the screen grab above.
* Do the same in the post editor and confirm everything works correctly.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
When I tested this I still got the wrong sizing for the image:
Screen Shot 2021-04-21 at 4 20 41 PM

and also got a `Notice: Undefined index: productId in /var/www/html/wp-content/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php on line 67` error when trying to view on the frontend?

**Comment by apeatling** [comment]
Weird! Let me retest again and see if I can reproduce.

**Comment by apeatling** [comment]
Hold on I'm missing a bunch of commits. 🤦🏻

**Comment by apeatling** [comment]
@glendaviesnz Can you try deleting and re-adding a new paypal block? I can't reproduce the warning on the front end. Is the ID number at the end here undefined for you?

Screen Shot 2021-04-21 at 11 21 13 AM

**Comment by stacimc** [comment]
> Is the ID number at the end here undefined for you?
> 
> Screen Shot 2021-04-21 at 11 21 13 AM

I just tried this, after pulling the branch and rebuilding Jetpack to be safe. I do not see that id at all in the editor:
Screen Shot 2021-04-26 at 10 33 28 AM

* In the editor, the block looks correct after I initially add it. If I save the template and then refresh the page, the image does not show at all, and the title & description are now blank. (Price and email fields do persist).
* In the frontend, I do not see the block at all, and I get this console error:
```
Uncaught Error: Document is ready and element jetpack-simple-payments-_3_button does not exist
```

**Comment by glendaviesnz** [comment]
I just tested again and got the same result as @stacimc

**Comment by apeatling** [comment]
Thanks, I'll get back to this later in the week, trying to finish up the upgrade banner issue.

**Comment by apeatling** [comment]
@glendaviesnz @stacimc I've pushed an update that should fix this now, checked by syncing to dotcom and it worked in the post and site editor. 👍

**Comment by glendaviesnz** [comment]
This worked for me now on post and in site editor. The block added on the post editor retained the content between editor reloads and also displayed on the frontend.

For some reason the block shows as being invalid if the content of the post shows in the site editor:

Screen Shot 2021-04-30 at 9 41 10 AM

To replicate add a query block to FSE index that shows a post with a paypal block. Could be related to https://github.com/Automattic/wp-calypso/issues/52310

**Comment by apeatling** [comment]
@glendaviesnz I'm not seeing this, paypal block loading correctly within the query block when loaded from a post:

Screen Shot 2021-05-03 at 12 12 30 PM

**Comment by ramonjd** [comment]
This is looking good in Chrome and Safari
**Before**
Screen Shot 2021-05-04 at 2 34 15 pm
**After**
Screen Shot 2021-05-04 at 2 32 21 pm

Appears on the frontend as expected

Screen Shot 2021-05-04 at 2 32 16 pm

I can't see any block validation issues either. Could it be somehow a currency mismatch @glendaviesnz ? It looks like it was complaining about formatting? 🤷 

I noticed a teensy regression in Firefox. The select box looks to have some extra padding/lineheight/something

**Before**
Screen Shot 2021-05-04 at 2 48 05 pm

**After**
Screen Shot 2021-05-04 at 2 47 51 pm

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to move the amount field a bit off in non-FSE for me:

Screenshot 2021-05-06 at 12 57 04

I tested in Chrome.

**Comment by apeatling** [comment]
Thanks, fixed. 👍

**Comment by glendaviesnz** [comment]
@apeatling  I can't replicate that issue on a fresh site, so not sure what was going on there.

**Review by jeherve — DISMISSED** [review]

**Comment by apeatling** [comment]
Need to update a test here then I will merge.

**Comment by apeatling** [comment]
@jeherve Do you have any idea why these tests would be failing now? I'm seeing the error:

` TypeError: Cannot read property 'saveEntityRecord' of null` 

when running the simple payments tests, but nothing there has changed.

**Comment by jeherve** [comment]
@apeatling I think you would need to update the test to take the new prop into account. Something like this maybe?

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/simple-payments/test/edit.js b/projects/plugins/jetpack/extensions/blocks/simple-payments/test/edit.js
index a821ccae9b..55ab343e61 100644
--- a/projects/plugins/jetpack/extensions/blocks/simple-payments/test/edit.js
+++ b/projects/plugins/jetpack/extensions/blocks/simple-payments/test/edit.js
@@ -27,6 +27,7 @@ const props = {
 	postLinKText: 'Click here to buy',
 	setAttributes,
 	isSelected: true,
+	isPostEditor: true,
 };
 
 describe( 'Edit component', () => {

```

**Review by samiff — APPROVED** [review]
Tests well for me 👍

**Pull request merged**
