### PR TITLE
Full Sync :: Reduce Concurrency.

### PR DESCRIPTION
**Pull request by mdbitz**
When the Full Sync logic was migrated from queue based to immediate sending of data there was a send lock implemented with an expiration of 15 seconds. This expiration of the lock allows for concurrent sends when the original request is still being processed. These concurrent requests can build up causing the reduction of application processes available to handle new requests to the site.

Fixes #
https://wp.me/p9dueE-2kk

#### Changes proposed in this Pull Request:
* Reduce concurrent sending of data during a Full Sync.

#### Does this pull request change what data or activity we track or use?
NO

#### Testing instructions:

* Apply Patch
* on a WP.com sandbox run `wp jetpack-sync pull --blog-id=XXXXX --start`
* Verify the Full Sync starts and completes.

#### Proposed changelog entry for your changes:
* Sync Performance Update : Reduce concurrency of sync requests to minimize number of application processes that are waiting for sync processing to complete.

### CODE REVIEW

**Comment by mdbitz** [comment]
Need in depth testing of the change to the lock

**Comment by mdbitz** [comment]
I've run this through the paces and its ready for crew review/testing.

1) Standard Full Sync -> runs to completion
2) Full Sync w/ ping -> runs to completion
3) Multiple wp jetpack-sync pull from WP.com sandbox -> only singular processing no concurrent
4) Full Sync with uncached calls -> logging shows singular concurrent send, early returns from send until lock is cleared

Did some further cleanup so that we minimize the reading/setting of option only if Full Sync is in progress vs every shutdown call.

**Comment by mdbitz** [comment]
Always interesting when you find that tests weren't doing what they were supposed to be doing... cleanup needed on aisle 3.

**Comment by mdbitz** [comment]
Why are we still running legacy tests? And incremental sync wasn't modified so not sure why that is showing a failed test. 

- WP_Test_Jetpack_Sync_Lock. (this is interesting as all tests show prper clearing in stress runs)
- WP_Test_Jetpack_Sync_Sender::test_delays_next_send_if_exceeded_sync_wait_threshold -> ??
- WP_Test_Jetpack_Sync_Full::test_full_sync_continue_does_nothing_if_no_sync_started -> ?? 1 item in queue need to check if the function needs additional check as it doesn't account for not being started.

**Comment by mdbitz** [comment]
Something in how these tests are run is odd, would appreciate any insight on why failing

`yarn docker:phpunit:multisite --filter=WP_Test_Jetpack_Sync_Lock.` --> has no issue with the lock tests.
`yarn docker:phpunit:multisite` -- > failures

**Comment by anomiex** [comment]
> Something in how these tests are run is odd, would appreciate any insight on why failing
> 
> `yarn docker:phpunit:multisite --filter=WP_Test_Jetpack_Sync_Lock.` --> has no issue with the lock tests.
> `yarn docker:phpunit:multisite` -- > failures

I narrowed it down a bit for you, this fails
```
yarn docker:phpunit:multisite --filter='/WP_Test_Jetpack_Sync_Functions::test_get_main_network_site_wpcom_id_multisite|WP_Test_Jetpack_Sync_Lock/'
```
So it seems to be something about WP_Test_Jetpack_Sync_Functions::test_get_main_network_site_wpcom_id_multisite that breaks it.

**Comment by mdbitz** [comment]
> So it seems to be something about WP_Test_Jetpack_Sync_Functions::test_get_main_network_site_wpcom_id_multisite that breaks it.

Thanks Brad, it turns out that the option is being converted from a float to a string value. I've updated the patch to string cast to allow for the === to test properly. PHP and types, fun.

**Comment by anomiex** [comment]
Tracked it down a bit more: that test calls `wpmu_create_blog()`, which calls `wp_installing( true )`, which bypasses a lot of caching in the options code. So when it reads the value back from the DB instead of from cache, the DB returns it as a string rather than as the original type as the cache does.

**Review by bisko — APPROVED** [review]
LGTM!

Tested a full sync and it was working as expected.

**Comment by mdbitz** [comment]
Thank you Brad for the deep dive, I'll have to remember to check my options more carefully in the future.

As a note I ran testing of this increased expiration on VIP staging site and the Full SYnc went through with no concurrency.

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.3` in d81b93a00d24c6a2cb5f2e4710865d6aabef26c5

**Pull request merged**
