### PR TITLE
Publicize: Update the publicize meta fields earlier

### PR DESCRIPTION
**Pull request by enejb**
This PR brings wpcom changes in sync with the current file. 

#### Changes proposed in this Pull Request:

* We make sure that the post meta gets saved earlier so that any race conditions are not take into account.

#### Testing instructions:
Test publicize does it work as expected.

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Comment by jeherve** [comment]
> This PR brings wpcom changes in sync with the current file

Was this already merged on wpcom? could you paste the diff number here for reference, and maybe more background behind this change?

You will also need to rebase this PR to include the fixes we've made to Unit Tests for WP 5.0.

Thank you!

**Comment by jeherve** [comment]
@enejb could you take a look at this today, and either rebase and address the issues above, or remove the PR from the milestone?

Thank you!

**Comment by kraftbj** [comment]
Doing some housecleaning and see the corresponding wp.com code landed long ago. Let's sync this up.

**Comment by kraftbj** [comment]
r184610-wpcom

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
