### PR TITLE
Search: Add 'My Jetpack' and 'Settings' links to Search plugin line on plugins page

### LINKED ISSUE #25382: Feature Request: Add 'My Jetpack' and 'Settings' links to Search plugin line on plugins page
### Impacted plugin

Search

### What

I'd like two links added for Search plugin on plugins page to align with other standalone plugins

### How

- 'My Jetpack' links to `/wp-admin/admin.php?page=my-jetpack`.
- 'Settings' links to `/wp-admin/admin.php?page=jetpack-search`.

Example is Boost:

image

Note:

To avoid the issue where Jetpack might not be connected, we need to either hide Settings link or add Jeptack Search Dashboard regardless of whether Jetpack is connected.

### PR DESCRIPTION
**Pull request by annacmc**
This PR adds both a 'settings' and a 'My Jetpack' link to the plugins page for the Search plugin. It only displays 'my Jetpack' if there is an active connection, and only displays 'settings' if Search is active. 

Fixes #25382 

I am interested in specifically the following things:

* code placement: I am new to working in the plugin, and wondering if this is the best location for the code. I noticed that, for example, Boost handles this in their `class-admin.php` file. We don't have as much structure yet, but it doesn't seem worth restructuring into new classes for just the sake of this one link. 

* using `new Connection_Manager()` here, is this the best approach? Could I do it without creating a new instance and I've missed how? I feel like I could be missing a really obvious better solution. 

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* On a site with a Jetpack Search subscription and the Search plugin active, go to `/wp-admin/plugins.php` and check that the links alongside Jetpack Search are `My Jetpack` `Settings` and `Deactivate` 

image

* Try deactivating the Search plugin and ensure the only link displayed is `Activate`

* Try disconnecting Jetpack, with the Search plugin active, and check the links displayed are only `Settings` and `Deactivate`

### CODE REVIEW

**Comment by kangzj** [comment]
Hi @annacmc Thanks for the quick fix 👍 

> code placement: I am new to working in the plugin, and wondering if this is the best location for the code. I noticed that, for example, Boost handles this in their class-admin.php file. We don't have as much structure yet, but it doesn't seem worth restructuring into new classes for just the sake of this one link.

Good thinking. I'm fine for the approach taken here and we could refactor when the class gets bigger.

> using new Connection_Manager() here, is this the best approach? Could I do it without creating a new instance and I've missed how? I feel like I could be missing a really obvious better solution.

I think it's okay to get a new instance. If you look into the constructor, it's quite light actually and I guess it's okay to omit the `$plugin` parameter as well, which is already registered from the package.

There's another thing, I didn't add `automattic/jetpack-connection` dependency when first using it. Could you please add it by the way? You could run the following command in the search plugin directory:

`composer require automattic/jetpack-connection`

Thanks.

**Review by kangzj — CHANGES_REQUESTED** [review]
Hi @annacmc the patch adds the links for all plugins, which is not ideal. We should possibly add the filter for only our plugin, like [Boost does](https://github.com/Automattic/jetpack/blob/7f10325a9cfa7a45dbc987e7074d081e52e3e8b0/projects/plugins/boost/app/admin/class-admin.php#L63).

**Comment by annacmc** [comment]
> Hi @annacmc the patch adds the links for all plugins, which is not ideal. We should possibly add the filter for only our plugin, like [Boost does](https://github.com/Automattic/jetpack/blob/7f10325a9cfa7a45dbc987e7074d081e52e3e8b0/projects/plugins/boost/app/admin/class-admin.php#L63).

Oh geez, yeah - I did know this and had intended to fix it up. But then got carried away and forgot to add that part 🙈  thanks for catching it!

**Comment by annacmc** [comment]
Thanks so much @kangzj 🙏 it should be all addressed now, except for when you said:

> I guess it's okay to omit the $plugin parameter as well, which is already registered from the package.

I'm not quite sure which parameter you mean here?

**Review by kangzj — DISMISSED** [review]
This works well and looks good 👍 

---update---
The composer.lock file needs to be fixed and connection update to 1.43

**Comment by kangzj** [comment]
> I'm not quite sure which parameter you mean here? @annacmc 

I meant the slug parameter passed to constructor of `Connection_Manager` 😄

**Review by kangzj — APPROVED** [review]

**Pull request merged**
