### PR TITLE
Stats: improve pageview counts for widget views

### PR DESCRIPTION
**Pull request by lancewillett**
Janitorial naming fix, minor.

The stat name changed on the WP.com side, and this reflects that — it's more specific.

Previously #5478 improved after feedback from @jeherve

### CODE REVIEW

**Comment by lancewillett** [comment]
I've made a few fixes to the Jetpack widget files on WP.com to match this change — so both ends should have the same naming and stats bumps. For historical reasons some of the values use hyphens, some underscores (not ideal, but good to keep them the same as before for that reason).

**Comment by jeherve** [comment]
> I've made a few fixes to the Jetpack widget files on WP.com to match this change

For reference: r144925-wpcom

**Comment by lancewillett** [comment]
Good point — I thought about that and decided to only count the view on the "full" widget. What do you think is the best approach?

**Comment by jeherve** [comment]
I guess that depends what we usually use the stats for. I think we should count a view if the widget is displayed, even if it doesn’t display posts for some reason. It might have displayed posts at some point in the past, but the remote site stopped answering, maybe because the owner removed Jetpack.

**Comment by lancewillett** [comment]
OK, I'm open to putting the call into the `widget` method later so it's counted in all cases. I'm pretty sure 1-2 other widgets have similar logic, so I'll need to re-look at them all.

**Comment by jeherve** [comment]
It seems Goodreads, Google+ Badge, Gravatar Profile, and Top Posts use the same logic.

**Comment by lancewillett** [comment]
Updates pushed — and squashed commits.

**Comment by jeherve** [comment]
All looks good! 🚢

**Comment by lancewillett** [comment]
Synced these changes to WP.com in r144995-wpcom

**Pull request merged**
