### PR TITLE
Custom CSS: add CSS Grid Layout support.

### LINKED ISSUE #8394: Custom CSS: CSS Grid attributes and units removed on save
#### Steps to reproduce the issue
Try adding CSS Grid attributes and properties to the Custom CSS module. e.g.:
`grid-column-gap: 1rem`
`grid-row-gap: 1rem`
`grid-template-columns: 1fr 1fr`

#### What I expected
That style would be applied.

#### What happened instead
Adding CSS Grid properties and attributes to a Custom CSS field shows an error on save. 

image

### PR DESCRIPTION
**Pull request by danielwrobert**
Fixes #8394

#### Summary:

This PR adds all current properties for the CSS Grid Layout Module Level 1 specification to the Custom CSS whitelist.

#### Test Plan:

It does not appear that the Custom CSS module is used on self-hosted sites - this is mainly a PR for support requests on WPCOM.

### CODE REVIEW

**Comment by jeherve** [comment]
> It does not appear that the Custom CSS module is used on self-hosted sites

The module can still be used on self-hosted sites, so it's not a useless change. 👍

**Comment by jeherve** [comment]
Fixes #8394

**Comment by georgestephanis** [comment]
@danielwrobert Is this live on WPCOM currently?

**Comment by danielwrobert** [comment]
@georgestephanis No, not yet - I had it on my list to add today though.

**Pull request merged**
