### PR TITLE
jetpack: Work around another calypso-build oddity

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

Calypso-build sets webpack's `output.libraryTarget` to "window". When no
library name is supplied (which calypso-build doesn't do), this means
that everything exported by the module will be copied onto the `window`
object.

This could be bad, if we were exporting a bunch of stuff. But most of
our webpack entry points don't actually export anything, they're empty
ES modules.

Under Webpack 4, this worked out ok. All zero of the properties of the
empty ES modules got copied to `window`, so nothing really happened.

But Webpack 5 changed the behavior slightly: in addition to copying all
zero of the exports, it also flags the target object (`window`) as being
an ES module. This breaks other ES modules that do things like `import
window from 'global/window'`, as that'll start treating `window` as an
ES module (even though it lacks the correct structure) instead of as a
legacy object, leading to the breakage described in Automattic/wp-calypso#55696.

The fix is simple enough: Override calypso-build to set the library
target to the empty string, so it doesn't try to copy the zero
properties anywhere. The few entry points we have that were relying
on this behavior were all only exporting a single thing, so we can
explicitly set `library.name` and `library.export` to get the desired
behavior.

I also deleted one export that seemed clearly erroneous, since it's
unlikely it really intended to create `window.initialize()` and
internally it assigned the same function to
`global.jetpackSearchConfigureInit`.

#### Jetpack product discussion

https://github.com/Automattic/wp-calypso/issues/55696#issuecomment-915430357

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Try reproducing according to instructions at Automattic/wp-calypso#55696.
  * In my case, I managed to reproduce by [disabling the widget block editor](https://developer.wordpress.org/block-editor/how-to-guides/widgets/opting-out/#using-a-filter) then adding a Video widget, and also having Instant Search enabled.
* Make sure the blocks themselves and so on still work. Particularly you might want to look at the Instant Search customizer, the admin page, and the Widget Visibility thing, as those were the ones that had exports previously.

### CODE REVIEW

**Comment by simison** [comment]
> Calypso-build sets webpack's output.libraryTarget to "window". When no
library name is supplied (which calypso-build doesn't do), this means
that everything exported by the module will be copied onto the window
object.

Should this default get fixed in Calypso build? cc @griffbrad

**Comment by ebinnion** [comment]
@samiff – Pinging you here as release lead.

There is a case where legacy video embeds are broken for our users. Ideally, we should fix this in WPCOM asap. I'm not sure that it warrants a point release as we can prompt users to upgrade to the beta. I wanted you to be aware of the issue and fix though.

**Comment by sdixon194** [comment]
I found that this does indeed break the new Search Gutenberg editor:

```
Uncaught TypeError: y is undefined
    J https://continental-tick.jurassic.ninja/wp-content/plugins/jetpack-dev/_inc/build/instant-search/jp-search-configure-main.min.js?ver=10.2-alpha:14
    we https://continental-tick.jurassic.ninja/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84
```

But that was the only thing I found. All other legacy/block widgets seemed to work fine. 

I'm fine fixing this for simple sites and keeping an eye on incoming requests to see if a point release is needed in the near future, but not sure it's warranted at this time based on the requests.

**Comment by anomiex** [comment]
> I found that this does indeed break the new Search Gutenberg editor:

Did it? I get the same error with the current master.

Bisecting, it looks like it broke when `@wordpress/*` was updated in #21021.

**Comment by sdixon194** [comment]
> Did it? I get the same error with the current master.

Ah you're right, I was testing with Latest Stable. Seems unrelated to this post. I'll open up a separate issue for that one. 

This looks good to me then.

**Review by sdixon194 — APPROVED** [review]

**Comment by anomiex** [comment]
r231676-wpcom

**Comment by griffbrad** [comment]
@Automattic/team-calypso-platform looks like this default in calypso-build no longer makes sense in all cases with webpack 5:
https://github.com/Automattic/wp-calypso/blob/124efe5e1f1b709cdeb6e209a0dc5723b33fb183/packages/calypso-build/webpack.config.js#L50

**Comment by noahtallen** [comment]
> Work around another calypso-build oddity

I agree, my gut reaction to the title is that we should resolve any oddities we can at the source as well! Were there other examples of oddities we could fix?

**Comment by anomiex** [comment]
> I agree, my gut reaction to the title is that we should resolve any oddities we can at the source as well! Were there other examples of oddities we could fix?

Here's the list of other issues we've had to work around that I'm aware of at the moment.

* https://github.com/Automattic/wp-calypso/issues/53353
* https://github.com/Automattic/wp-calypso/issues/56111
* https://github.com/Automattic/wp-calypso/issues/56291

**Comment by anomiex** [comment]
Oh, and one more that I hadn't filed a bug for is the workaround at
https://github.com/Automattic/jetpack/blob/906f605624cad5fb6fa93f757456f94663babb2c/projects/plugins/jetpack/tools/webpack.config.extensions.js#L172-L175

**Comment by scinos** [comment]
Maybe we should reconsider the usefulness of `calypso-build`... or at least exporting a webpack config.

For the record, Calypso [doesn't use the webpack config](https://github.com/Automattic/wp-calypso/blob/trunk/client/webpack.config.js) provided by `calypso-build`, we only use some loaders. Some of which are basically an[ alias of an official loader](https://github.com/Automattic/wp-calypso/blob/714324a537c380b2d6135c95af9838b25247229b/packages/calypso-build/webpack/transpile.js) with some config options renamed.

**Comment by noahtallen** [comment]
> Maybe we should reconsider the usefulness of calypso-build

IMO, it would be useful if it allowed one team (like team calypso) to update all of our build tools, and then all the consumers would just have to update `calypso-build` without (for the most part) other modifications. I think we end up duplicating lots of work when everyone has to update all of the build tools like `sass` or `webpack` separately

**Comment by jsnajdr** [comment]
I have some recent experience creating a brand new webpack config for the Inline Help widget in Calypso (https://github.com/Automattic/wp-calypso/pull/55189).

When I tried to import and extend the `webpack.config.js` that's exported by the `calypso-build` package, I didn't succeed. I got lost in the details of which piece of the config I want to keep, which one I want to remove, which one I want to patch or replace with a slightly reconfigured version...

I ended up building a `webpack.config.js` from scratch, but reusing many pre-built parts from `calypso-build`, like `TranspileConfig`, `SassConfig` or `FileConfig`. That worked much better.

I think the second approach should be the future of `calypso-build` -- provide a library of IKEA-style blocks that can be used to quickly build a webpack config in a few lines. My webpack config still has 100+ lines, so there's a lot of room for improvement.

This case is also an instance of the "favor composition over inheritance" design principle.

**Comment by griffbrad** [comment]
I generally like @jsnajdr's approach for Inline Help as well. Ultimately, we should also keep in mind that `wp-scripts build` exists. Particularly early on, there were some real differences (e.g. support for style imports), but perhaps we could move toward using `wp-scripts` and providing some "IKEA-style blocks" that folks could use alongside it when needed.

**Comment by anomiex** [comment]
I've been considering whether the Jetpack monorepo should go more towards using calypso-build as a library of blocks instead of trying to start from the full config too. So far I haven't quite convinced myself to spend time on that, but if you're wanting to move in that direction anyway that could convince me. Especially if the library of blocks ends up being well-documented. I've also considered just forking the blocks we need.

I haven't looked too much into `wp-scripts` yet, other than seeing that it's also primarily documented as being "scripts to do everything for you" which might wind up with the same kinds of problems.

**Pull request merged**
