### PR TITLE
VideoPress: do not set constant if it is already set.

### LINKED ISSUE #4204: PHP Notice: Constant VIDEOPRESS_MIN_WIDTH already defined
Fresh install of WordPress & Jetpack, activated all the modules, got this notice:
```
PHP Notice: Constant VIDEOPRESS_MIN_WIDTH already defined in /nas/content/live/cloudsrvr/wp-content/plugins/jetpack/modules/videopress.php on line 20, referer: https://www.cloudsrvr.com/wp-admin/admin.php?page=jetpack_modules
```

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #4204

cc @dbtlr

### CODE REVIEW

**Comment by eliorivero** [comment]
@jeherve just made the update we spoke about, to define it only once in `utility-functions.php`.

**Comment by jeherve** [comment]
This works well in my tests. Merging!

**Comment by enejb** [comment]
Why not do use something like
`defined( 'VIDEOPRESS_MIN_WIDTH' ) or define( 'VIDEOPRESS_MIN_WIDTH', 60 );`
 instead of just `define( 'VIDEOPRESS_MIN_WIDTH', 60 )` ?

**Comment by jeherve** [comment]
@enejb That's how I started, in c617de0561731a1e8cb981f4c2b7f4eebcf13b8c, but as @eliorivero pointed out we don't actually need to `define` in both the VideoPress and the Shortcodes module. Both files require the utility functions file, so we can define the constant there.

I guess we could still add the check, just in case someone else decides to define that constant somewhere else. What do you think @eliorivero?

**Comment by eliorivero** [comment]
@enejb @jeherve yeah, I was about to reply that we can be more defensive. I'll update my commit.

**Comment by enejb** [comment]
Thanks 👍

**Comment by samhotchkiss** [comment]
#5457

**Pull request merged**
