### PR TITLE
Untangling: Show WP.com themes banner

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/dotcom-forge/issues/6475
Fixes https://github.com/Automattic/dotcom-forge/issues/6477

## Proposed changes:
This PR displays a banner on untangled Atomic sites before the theme browser that links to the WP.com Theme Showcase.

Screenshot 2024-04-09 at 16 18 04

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
- If you don't have an untangled Atomic site:
  - Create or pick a regular Atomic site
  - Go to wordpress.com/hosting-config and select your Atomic site
  - Change the admin interface to wp-admin
  - Go to `<SITE_DOMAIN>/_cli` and run this command: `wp option update wpcom_classic_early_release 1`
- Apply these changes to your untangled Atomic site:
  - Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/)
  - Go to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack-mu-wpcom-plugin`
  - Activate this branch
- Go to `/wp-admin/theme-install.php`
- Make sure the WP.com themes banner show up
- Make sure it looks good
- Make sure it links to the WP.com theme showcase
- Try different browser sizes and check the banner responsiveness
- Make sure the banner does not show up in other pages

### CODE REVIEW

**Review by dsas — DISMISSED** [review]
LGTM.

The only question I have is whether we should add any tracks events for seeing the banner and clicking on it.

**Comment by rcrdortiz** [comment]
> LGTM.
> 
> The only question I have is whether we should add any tracks events for seeing the banner and clicking on it.

I don't think we need an event for tracking when the banner is shown since it's shown on every page load of `theme-install.php`.

**Review by taipeicoder — DISMISSED** [review]
Works great! Only note is that the Wordpress.com logo looks a bit rough:

Screenshot 2024-04-10 at 9 42 22 AM

Any improvements we can do here? cc: @lucasmendes-design

**Comment by mmtr** [comment]
> whether we should add any tracks events for seeing the banner and clicking on it.

Added a `ref` param to the banner link, so we can check that param later in Calypso and track a specific `calypso_view_page` event with an additional property (I'll create a follow-up PR for this).

> Only note is that the Wordpress.com logo looks a bit rough

FWIW it looks like that in Figma, and the image is a scalable SVG so I'm not sure how can we improve it. @lucasmendes-design if you come up with a better SVG for the logo, let me know and I'll replace it. In the meantime, I guess we can use the current one.

**Review by dsas — APPROVED** [review]

**Comment by lucasmendes-design** [comment]
> if you come up with a better SVG for the logo, let me know and I'll replace 

Sure, I will share it today :)

**Comment by lucasmendes-design** [comment]
WordPress logo SVG
WPCOM logo SVG

**Comment by lucasmendes-design** [comment]
Whether you're in Dev Mode or not, you can click on the logo and find the Export section (select SVG). I hope it helps, but I'm not sure if you have only the free account. :( 

Screenshot 2024-04-10 at 14 25 30
).

**Comment by lucasmendes-design** [comment]
Banner update

Figma file: PZtnZ1nHhnBrsuXDoMJHPD-fi-722%3A63873 
Dev Link: PZtnZ1nHhnBrsuXDoMJHPD-fi-722_63873

V1
V1


V2 
v2

**Comment by mmtr** [comment]
> you can click on the logo and find the Export section (select SVG)

Yeah, that's what I've done to get the current WP.com logo. I think the one you provided is exactly the same one that I added to this PR: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/jetpack-mu-wpcom/src/features/wpcom-themes/images/wpcom-logo.svg

The problem that we're noticing is that the logo is a bit small and it's producing some artifacts/pixelation when displayed in that size:

Screenshot 2024-04-11 at 11 17 11

> Banner update

Awesome, thanks! I opened https://github.com/Automattic/jetpack/pull/36845 to update the image

**Comment by lucasmendes-design** [comment]
Strange, one sec let me double check. I can also share the PNG version.

**Comment by lucasmendes-design** [comment]
Maybe it's the GitHub upload. Here is a google drive link (PNG and SVG): 
https://drive.google.com/drive/folders/1nwfXRFhp8k3fhn4rtivc31G79FezggIT?usp=sharing 

This logo is a vector so this kind of problem shouldn't happen. 
image

**Comment by mmtr** [comment]
@lucasmendes-design the issue still persists even with the "bigger" SVG. The problem is that the logo has some small details so when it's rendered with a small size there are not enough pixels to show these small details. You can even see this problem on Figma with a 100% zoom (the most noticeable part for me is the middle peak of the W in the "WordPress.com" text).

Screenshot 2024-04-11 at 13 37 09


According to my tests, in order for that peak to be clearly visible, we need a logo with a ~200px width (right now it's 128px). Anyway, I think this is rather a subtle detail, it's probably fine to leave things as they are.

**Comment by lucasmendes-design** [comment]
On my Figma is perfect. I'll check with other designers if they have the same issue. 

image

**Comment by autumnfjeld** [comment]
Could we get this in production on atomic for both:
* wp-admin classic "normal"
* wp-admin classic early_release

Right now in production  I see that both Themes and Theme Showcase point to the Showcase

image


Is there any reason putting this in production now (e.g. themes.php with the banner) would have negative side effects?

OR maybe a better question is:  is this feature already scheduled as part of the next mu wpcom atomic release that is happening within a few days / week?

**Comment by mmtr** [comment]
> Right now in production I see that both Themes and Theme Showcase point to the Showcase

That's unexpected so it might be a bug. If "Appearance > Themes" links to the Calypso Theme Showcase, the "Appearance > Theme Showcase" menu should NOT be there. I'll take a deeper look.

> Is there any reason putting this in production now (e.g. themes.php with the banner) would have negative side effects?

The only reason is that this banner has been considered part of the WP.com themes on Atomic project, and everything in this project is currently behind the early release check. Once we're ready to launch the project (hopefully next week), we'll launch it to wp-admin classic "normal" sites.

**Comment by mmtr** [comment]
> That's unexpected so it might be a bug. If "Appearance > Themes" links to the Calypso Theme Showcase, the "Appearance > Theme Showcase" menu should NOT be there. I'll take a deeper look.

Found the issue, was caused by a regression introduced in https://github.com/Automattic/jetpack/pull/36851. Opened https://github.com/Automattic/jetpack/pull/36934 to fix it.

> this banner has been considered part of the WP.com themes on Atomic project, and everything in this project is currently behind the early release check. Once we're ready to launch the project (hopefully next week), we'll launch it to wp-admin classic "normal" sites.

Opened https://github.com/Automattic/jetpack/pull/36935 to release the banner to all users

**Pull request merged**
