### PR TITLE
Lint `.extra.dependencies.test-only` setting

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

The setting should refer to dev dependencies of the package. Verify that this is indeed the case.

Then clean up the two references to the removed idc package that were left behind when the dependencies on it were removed.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy?
* Add an `.extra.dependencies.test-only` somewhere referring to a slug that does not exist in the monorepo (e.g. revert one of the changes in this PR). Run the script, it should be reported properly.
* Add an `.extra.dependencies.test-only` somewhere referring to an existing non-dev composer dependency of the project. Run the script, it should be reported properly.
* Add an `.extra.dependencies.test-only` somewhere referring to an existing non-dev npm dependency of the project. Run the script, it should be reported properly.
* Add an `.extra.dependencies.test-only` in `packages/changelogger` referring to `js-packages/connection`. Run the script, it should be reported properly.
* Add an `.extra.dependencies.test-only` somewhere referring to a plugin slug. Run the script, it should be reported properly.

### CODE REVIEW

**Review by tbradsha — APPROVED** [review]
All scenarios pass as described.

A few notes as I was reviewing this:

1. macOS uses BSD `sed`, and this script (and most others in the monorepo) assumes GNU `sed`. I've now added GNU `sed` into my path before the built-in, but worth considering when using `sed`. In this particular case, the `\u` uppercase transformation is the part that breaks things in BSD `sed`.
2. Not sure if this is a bug or a feature, but the script expects a very clean repo, which happens in CI but not so much locally. I got various errors because it was checking untracked folders (e.g. the deleted `action-bar`, `heartbeat`, and `identity-crisis` packages, as well as various macOS `.DS_Store` folders).
3. I was a bit confused by the output, as it looked like it was giving me blank lines. In the end it's because we use the "debug" (`1;30`) color for output. I'll note that we have a CI exception built in that uses "blue" instead, but it doesn't even seem to output as blue in the CI.
image
image

**Comment by anomiex** [comment]
> macOS uses BSD `sed`, and this script (and most others in the monorepo) assumes GNU `sed`.

Scripts in `.github` are ok to assume GNU `sed`, since scripts there are intended to be run from Actions and Actions provides GNU `sed`.

For scripts elsewhere, particularly the ones directly in `tools/`, it depends a lot more on the intended audience. For the most part, though, those should work with Mac's version of `sed` as well as GNU `sed`.

> Not sure if this is a bug or a feature, but the script expects a very clean repo, which happens in CI but not so much locally.

Neither, I'd say. The intended use of the script is from CI, so I don't see it as a bug.

> I was a bit confused by the output, as it looked like it was giving me blank lines. In the end it's because we use the "debug" (1;30) color for output.

That should be a grey color, not black-on-black. Your terminal must not be following the usual convention of "bold" also meaning "bright".

If that's not something you specifically configured, we might want to look into changing the default debug coloring.

> I'll note that we have a CI exception built in that uses "blue" instead, but it doesn't even seem to output as blue in the CI.

I guess GitHub changed things at some point, it used to and I don't think we changed anything. 🤷

**Comment by tbradsha** [comment]
> For the most part, though, those should work with Mac's version

I've had mixed success here, but good to know at least that's the target.

> That should be a grey color, not black-on-black. Your terminal must not be following the usual convention of "bold" also meaning "bright".

Here are my settings, which differentiate between bold and bright, neither of which are black:
image

If grey is the target, I'd expect instead dim (e.g. `2;37`). 🤷

**Comment by anomiex** [comment]
This being unchecked is what's making the difference.
Screenshot

**Comment by tbradsha** [comment]
> This being unchecked is what's making the difference 

Yep, which is why I specified that my settings "differentiate between bold and bright". I could certainly change my end, but I'm not aware of a convention that expects them to be the same.

No need to change it; just mentioning it for awareness.

**Pull request merged**
