### PR TITLE
Launchpad task to add ten newsletter subscribers

### PR DESCRIPTION
**Pull request by daledupreez**
Related to https://github.com/Automattic/wp-calypso/issues/79613

## Proposed changes:

This PR includes two closely related changes:
* The PR adds a new `add_10_email_subscribers` task to the free and paid newsletter task lists, as per https://github.com/Automattic/wp-calypso/issues/79613, where we want users to add 10 email subscribers for their newsletter. There are some subtle notes to include:
   - We can only show this task when we're running on WordPress.com's main servers, as I don't think email subscriber information is directly available from Atomic sites -- it's possible we can get the information from users marked as "Followers", but I didn't want to hold the PR to dig in too long.
   - The site owner is included as an email follower by default, so we need to exclude them from the counts to avoid being confusing.
   - The logic for updating email subscribers is relatively convoluted, but we maintain a high-level cache for the email subscriber count, so I've _not_ implemented any logic that intercepts additions of email subscribers. This led me to the second major part of the PR below.
* The PR adds a new `wpcom_launchpad_is_repeated_task_complete()` task completion callback that's specific to repeating tasks, where the code identifies the task as complete (and marks it as complete) when the number of repetitions reaches or exceeds the target number of repetitions.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

The changes only affect the plugin we run on WordPress.com sites.

## Does this pull request change what data or activity we track or use?

No.

### Run the unit tests

* Check this branch out locally: `git checkout add/launchpad-task-add-ten-newsletter-subscribers`
* Run the unit tests:
```sh
cd projects/packages/jetpack-mu-wpcom
vendor/bin/phpunit
```

### Test on WordPress.com

* Identify or create a newsletter site - note the site slug
  - If you need to create a site, navigate to [https://wordpress.com/setup/newsletter]
* Apply these changes to your WordPress.com developer system as per [this comment](https://github.com/Automattic/jetpack/pull/32075#issuecomment-1651193557)
* Update your `0-sandbox.php` file to include the following -- you can also make this check more specific if you prefer.
```php
add_filter( 'wpcom_launchpad_intent_free_newsletter_enabled', '__return_true' );
add_filter( 'wpcom_launchpad_intent_paid_newsletter_enabled', '__return_true' );
```
* Ensure that traffic for `public-api.wordpress.com` is routed to your developer system
* Navigate to Customer Home
* Verify that the checklist for your newsletter includes the "Get your first 10 subscribers" task
* Use the network tab in your browser to verify that the `target_repetitions` and `repetition_count` values are 10 and 0, respectively
* Navigate to _Users_ -> _Subscribers_
* Click on the "Add subscribers" button in the top right corner
* Enter an email address to add a subscriber - you can use `+something` in a GMail email address to make it look unique so it's not the same as your existing email address
* Confirm the change, and wait a few seconds to allow the subscriber to be added - refresh the page to see whether the import has completed
* Once the page shows your subscriber as added, navigate to _My Home_
* Verify that the "Get your first 10 subscribers" task is still present
* Inspect the network tab and confirm that the launchpad API call has updated the `repetition_count` field for the task
* Navigate to _Users_ -> _Subscribers_
* Click on the "Add subscribers" button in the top right corner
* Enter 9 email addresses to add another 9 subscribers - as above, you can use `+something` in a GMail email address to make it look unique so it's not the same as your existing email address
* Submit the email addresses, and wait a few seconds to allow the subscribers to be added - refresh the page to see whether the import has completed
* Once the page shows 10 (or more) subscribers, navigate to _My Home_
* Verify that the "Get your first 10 subscribers" task is present and marked as complete

#### Initial task list
Screenshot 2023-07-26 at 10 21 13

#### Completed task
Screenshot 2023-07-26 at 10 35 27

### CODE REVIEW

**Comment by sixhours** [comment]
Gave this a whirl and it works well!

I noticed we don't stop counting the repeating task iterations after the goal has been reached; is that intentional? I found this a bit confusing, for example:
Screenshot 2023-07-27 at 3 50 04 PM

**Comment by daledupreez** [comment]
Thanks for testing, @sixhours!

> I noticed we don't stop counting the repeating task iterations after the goal has been reached; is that intentional?

Nope, not intentional at all! I've rebased the code and added a `min()` call in `Launchpad_Task_Lists->build_task()` to ensure that we always have this check. @valterlorran, that may be relevant for https://github.com/Automattic/jetpack/pull/32012, as you've added that guard in the task-specific callback.

**Comment by sixhours** [comment]
Tested again and this looks much better:

Screenshot 2023-07-31 at 10 57 47 AM

**Comment by valterlorran** [comment]
Funny, it was increasing correctly, but when I added more than ten subscribers, the number of subscribers turned to 0 on the customer home.
Screen Shot 2023-08-01 at 11 11 13

**Comment by daledupreez** [comment]
@valterlorran, can you recheck? That may be a timing-related issue around the email subscriber cache?

**Review by valterlorran — DISMISSED** [review]
LGTM!
Screen Shot 2023-08-01 at 13 31 23

**Review by valterlorran — APPROVED** [review]
LGTM!

**Pull request merged**
