### PR TITLE
Clean up partner scripts based on shellcheck.net results

### PR DESCRIPTION
**Pull request by gravityrail**
Small cleanups based on http://www.shellcheck.net/

### CODE REVIEW

**Comment by dereksmart** [comment]
Needs a rebase but good to merge after resolved

**Comment by dereksmart** [comment]
whoops

**Comment by jeherve** [comment]
Rebased. Will merge when Travis passes.

**Comment by jeherve** [comment]
Cherry-picked to `branch-5.0` in 3600827531f0ada641049b5855e43121dc1dcef7

**Pull request merged**
