### PR TITLE
Tiled gallery: remove Photon module dependency

### LINKED ISSUE #13470: Tiled gallery block: make the block available without Photon module
Tiled gallery block currently depends on the Photon module and PHP class, although it doesn't really use those.

Availability of Photon servers is not limited to Photon module being active for the site.

For Tiled gallery block to be available, people need to know to switch "image CDN" setting on which is very unintuitive:

image

Tiled gallery block should just always be available.

### PR DESCRIPTION
**Pull request by simison**
Make Tiled gallery block available without Photon module being active.

Requiring users to turn on "image optimizations" is confusing and arbitrary, and we don't depend on that technically either.

If there's an agency/partner that wants to hide the block, they shouldn't need to disable photon for doing that and there's a separate mechanism in Jetpack for hiding specific blocks.

It's not great to turn on Photon module for the whole page load either (that's what current tiled gallery does). All the other images on the page should be un-affected by Tiled gallery's dependency on Photon servers.

Resolves https://github.com/Automattic/jetpack/issues/13470

Similar question for Markdown block: https://github.com/Automattic/jetpack/pull/13473

#### Changes proposed in this Pull Request:
- Remove Photon class & module check in block registration

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Changing

#### Testing instructions:
- Have a Jetpack site (e.g. via https://jurassic.ninja/)
- Confirm that Tiled gallery block is available in block editor only when Photon module is active. You can activate/disable it via "Performance -> Speed up image load times" toggle in Jetpack settings:
- In this branch (Test e.g. via https://jurassic.ninja/create?jetpack-beta&branch=update/tiled-gallery-photon-dep&wp-debug-log)

image

image

#### Proposed changelog entry for your changes:
- Tiled gallery block is now available in block picker even if "image accelerator" feature is disabled.

### CODE REVIEW

**Review by mmtr — APPROVED** [review]
LGTM 👍

**Comment by jeherve** [comment]
See my comment in #13473. I guess the same applies here as well :)

**Comment by simison** [comment]
> See my comment in #13473. I guess the same applies here as well :)

Replied at https://github.com/Automattic/jetpack/pull/13473#issuecomment-532357176

**Comment by jeherve** [comment]
Works for me. Should we update the block description to mention that it relies on our CDN? This would avoid confusion, and folks wouldn't have to contact support when they disable the Image CDN but keep seeing it being used in their galleries (this was a common issue back when tiled galleries were available as a single module).

**Comment by simison** [comment]
Good idea! So you're suggesting to update both block description and docs?

**Comment by jeherve** [comment]
Yeah, I think it would make sense.

**Comment by simison** [comment]
Filed another PR for description to not let this being blocked, pending copy review; https://github.com/Automattic/jetpack/pull/13502

**Review by jeherve — APPROVED** [review]

**Pull request merged**
