### PR TITLE
Limited Global Styles: Port feature from ETK to `jetpack-mu-wpcom`

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/dotcom-forge/issues/8170

## Proposed changes:

Ports the Limited Global Styles feature [from ETK](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles) to `jetpack-mu-wpcom`.

Code has been just copied from ETK with some additional changes:
- Defined a `MU_WPCOM_GLOBAL_STYLES` constant to turn off the feature in the ETK plugin
- Changed tracks logic to use the tools available in Jetpack
- Changed fetching of the Explorer plan name to use the tools available in Jetpack
- Adapted webpack config and enqueueing logic
- Changed text domain of translations to `jetpack-mu-wpcom`
- Adapted `WPCOM_Global_Styles_Test` to use `\WorDBless\BaseTestCase`
- Fixed a few linting issues:
  - Added missing JSDocs
  - Removed a `?int` syntax because it's not compatible with PHP 7.0
  - Changed a capability check to use the `manage_options` cap instead of the `administrator` role

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
- Apply these changes.
- Sandbox your API.
- Test a Free site with GS.
- The Site Editor should show notices when GS are used.
- The Site Editor should show the `Try before you buy` modal.
- The onboarding flow should work without regressions.
- The Launch Banner should work without regressions.
- Event names should be the same as on production.

### CODE REVIEW

**Comment by rcrdortiz** [comment]
Works as expected on the Site Editor (I'll continue testing other places)

Screenshot 2024-07-17 at 09 51 22
Screenshot 2024-07-17 at 09 52 40
Screenshot 2024-07-17 at 09 52 16

**Comment by rcrdortiz** [comment]
Launch Banner works as expected:

Screenshot 2024-07-17 at 09 55 03
Screenshot 2024-07-17 at 09 54 50

**Comment by rcrdortiz** [comment]
Found a bug, it's not a regression since it also happens in production. When we have a GS paid variation selected on the Site Editor on the Free plan, the GS notice isn't shown until something re-triggers it. Here is a video with the actual issue.


https://github.com/user-attachments/assets/fe0e44ec-264c-459f-8d37-f1fb17384bac

**Comment by mmtr** [comment]
> When we have a GS paid variation selected on the Site Editor on the Free plan, the GS notice isn't shown until something re-triggers it.

Nice catch! Since the bug is in prod as well, let's create a separate issue and fix it afterwards.

**Comment by rcrdortiz** [comment]
Events working as expected, everything I've tried is working as expected.

**Review by rcrdortiz — DISMISSED** [review]
Changes work as expected, could not find any regressions. Tested the onboarding flow, Site Editor, and the Launch Banner.
Upgraded to an Explorer plan and checked that the notices and upsells are hidden.

**Review by rcrdortiz — DISMISSED** [review]

**Comment by rcrdortiz** [comment]
Could you have a look at the Phan changes we've made in this PR @anomiex?

**Review by rcrdortiz — APPROVED** [review]
Changes look good, all checks are passing.

**Comment by mmtr** [comment]
Thanks for addressing the Phan errors, @rcrdortiz! Everything looks good to me as well.

**Comment by anomiex** [comment]
Phan changes look reasonable. Suggested #38410 to clean up a little.

**Pull request merged**
