### PR TITLE
Widgets: fixes PHP's fatal class not found error on Simple Payments Widget

### LINKED ISSUE #9875: Activating JetPack gave me a fatal error on my multisite
#### Steps to reproduce the issue
I'm not really sure if this is easily reproducible. This happened on a multisite and the plugins were not network activated. I'll provide the steps I took: 
1. Install Jetpack and activate it
2. Set it up with the default settings
3. Install the[ Mark it Down WordPress](https://wordpress.org/plugins/mark-it-down-wp/) plugin and activate it (even though it only has less than 10 active installs and hasn't been updated in the last year). 
4. See a warning appear that Mark it Down is already included in Jetpack
5. Disable Jetpack
6. Go to Settings -> Writing -> Enable Markdown
7. Create a new post and use markdown
8. Go to plugins and deactivate Mark it Down. 
9. Enable Jetpack.

#### What I expected
I expected Jetpack to activate without throwing a fatal error on my whole multisite.

#### What happened instead
Instead I got a fatal error _Fatal error: Class 'Jetpack_Simple_Payments' not found in /.../.../.../wp-content/plugins/jetpack/modules/widgets/simple-payments.php on line 479_ and I'm unable to access any post/page on my multisite. The fatal error happens on the entire multiste: 
fatalerror

### PR DESCRIPTION
**Pull request by rodrigoi**
Fixes #9875

#### Changes proposed in this Pull Request:

* adds a existence check for the `Jetpack_Simple_Payments` class dependency on `Jetpack_Simple_Payments_Widget`.

#### Testing instructions:

* Get this branch on a Multisite Installation
* Activate the Jetpack Plugin on the main site.
* Deactivate the Jetpack Plugin on the main site.

Previously, the site failed with a WSOD with this error:

```
PHP Fatal error:  Uncaught Error: Class 'Jetpack_Simple_Payments' not found in /var/www/html/wp-content/plugins/jetpack/modules/widgets/simple-payments.php:483
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(286): register_widget_jetpack_simple_payments('')
#1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/wp-includes/widgets.php(1649): do_action('widgets_init')
#4 /var/www/html/wp-includes/class-wp-hook.php(286): wp_widgets_init('')
#5 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /var/www/html/wp-settings.php(450): do_action('init')
#8 /var/www/html/wp-config.php(83): require_once('/var/www/html/w...')
#9 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
#10 /var/www/html/wp-admin/admin.php(31): require_once('/var/www/html/w...')
#11 /var/www/html/wp-admin/cu in /var/www/html/wp-content/plugins/jetpack/modules/widgets/simple-payments.php on line 483
```

which should no longer happen.

#### Proposed changelog entry for your changes:

* fixed Fatal Error when disconnecting the main site on a multisite installation.

### CODE REVIEW

**Review by brbrr — APPROVED** [review]
Tested on JurassicNinja sites. Works great!

LGTM 🐑 🇮🇹

**Comment by iamgabrielma** [comment]
Adding myself here to notify 1275815-zen when this is live :)

**Comment by mdggjfgdog** [comment]
i have same issue last 2 weeks, currently Jetpack deactivated. i think it had my site slowing down for 2-3 months. Worpress not responding. Cannot log into AMP. I am amatuer. annoying.

**Comment by kraftbj** [comment]
@mdggjfgdog Can you submit a support request via https://jetpack.com/contact-support/ ? Anything from 2-3 months back would not be related to this as the widget is a new addition as of this month's release of Jetpack.

**Comment by mdggjfgdog** [comment]
thank you, i will do, i have had error messages last 2-3 weeks, gradually
getting worse, just was really slow before and seemed liberated, once i
de-activated i noticed the difference. i had Jetpack on auto update, but
site went down late Friday i think.
many thanks.
yours G J Flattery


*Fatal error*: Uncaught Error: Class 'Jetpack_Simple_Payments' not found in
/home/bootif5/public_html/wp-content/plugins/jetpack/modules/widgets/simple-payments.php:479
Stack trace: #0
/home/bootif5/public_html/wp-includes/class-wp-hook.php(286):
register_widget_jetpack_simple_payments('') #1
/home/bootif5/public_html/wp-includes/class-wp-hook.php(310):
WP_Hook->apply_filters(NULL, Array) #2
/home/bootif5/public_html/wp-includes/plugin.php(453):
WP_Hook->do_action(Array) #3
/home/bootif5/public_html/wp-includes/widgets.php(1649):
do_action('widgets_init') #4
/home/bootif5/public_html/wp-includes/class-wp-hook.php(286):
wp_widgets_init('') #5
/home/bootif5/public_html/wp-includes/class-wp-hook.php(310):
WP_Hook->apply_filters(NULL, Array) #6
/home/bootif5/public_html/wp-includes/plugin.php(453):
WP_Hook->do_action(Array) #7
/home/bootif5/public_html/wp-settings.php(450): do_action('init') #8
/home/bootif5/public_html/wp-config.php(91):
require_once('/home/bootif5/p...') #9
/home/bootif5/public_html/wp-load.php(37): require_o in
*/home/bootif5/public_html/wp-content/plugins/jetpack/modules/widgets/simple-payments.php*
 on line *479*


*Debug Info*

jQuery version: 1.12.4

CLIENT_ID: 139164804BLOG_TOKEN:
5dd&Ow)muHr2Txcd4P@dBmuDJ#wcR6hY.fksZa^FJiZcKifD9pl#x2FvmO1f#SLj7MASTER_USER:
1CERT: 0TIME_DIFF: 0VERSION: 6.3.2:1530712680OLD_VERSION:
6.3:1530674369PUBLIC: 1USER_ID: 1USER_TOKEN:
WmJKp@M42Uo!1NpxJ*KlFfc%N#w0GE3v.mv9XG7yvZ7ZDLT8^DaKqVWQt96iKz%rm.1PHP_VERSION:
7.2.1WORDPRESS_VERSION: 4.9.7JETPACK__VERSION:
6.3.2JETPACK__PLUGIN_DIR:
/home/bootif5/public_html/wp-content/plugins/jetpack/SITE_URL:
https://bootifulworld.netHOME_URL: https://bootifulworld.netPLAN:
JetpackPlanfree
Jetpack Sync Full Status: `Array(    [started] => Wed, 04 Jul 2018
13:58:00 +0000    [queue_finished] => Wed, 04 Jul 2018 13:58:00 +0000
  [send_started] => Wed, 04 Jul 2018 13:58:03 +0000    [finished] =>
Wed, 04 Jul 2018 13:58:03 +0000


    [sent] => Array        (            [constants] => 1
[functions] => 1            [options] => 1
[network_options] => 1        )
    [queue] => Array        (            [constants] => 1
[functions] => 1            [options] => 1
[network_options] => 1        )
    [config] => Array        (            [options] => 1
[functions] => 1            [constants] => 1            [users] =>
Array                (                    [0] => 0                )
            [network_options] => 1        )
    [total] => Array        (            [constants] => 1
[functions] => 1

[options] => 1

            [network_options] => 1        )
)`Sync Queue size: 0Sync Queue lag: 0 secondsFull Sync Queue size:
0Full Sync Queue lag: 0 secondsSync IDC URLs:
{"home":"https:\/\/bootifulworld.net","siteurl":"https:\/\/bootifulworld.net","WP_HOME":"","WP_SITEURL":""}Sync
error IDC option: falseSync IDC Optin:
HTTP_HOST: bootifulworld.netSERVER_PORT: 443HTTPS: onREMOTE_ADDR:
80.234.225.208PROTECT_TRUSTED_HEADER:
{"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
TEST RESULTS:

HTTP: PASSHTTPS: PASSIDENTITY_CRISIS: PASSSELF: FAIL

RAW TEST RESULTS:
HTTPArray(    [headers] => Requests_Utility_CaseInsensitiveDictionary
Object        (            [data:protected] => Array                (
                  [server] => nginx                    [date] => Sun,
15 Jul 2018 15:47:48 GMT                    [content-type] =>
text/plain;charset=utf-8                    [vary] => Array
            (                            [0] => Accept-Encoding
                    [1] => Cookie                        )
                    [expires] => Wed, 11 Jan 1984 05:00:00 GMT
           [cache-control] => no-cache, must-revalidate, max-age=60
                [x-hacker] => Jetpack Test
[content-encoding] => gzip                    [x-ac] => 3.dca _dca
           )
        )
    [body] => OK    [response] => Array        (            [code] =>
200            [message] => OK        )
    [cookies] => Array        (


)

    [filename] =>     [http_response] => WP_HTTP_Requests_Response
Object        (            [response:protected] => Requests_Response
Object                (                    [body] => OK
    [raw] => HTTP/1.1 200 OKServer: nginxDate: Sun, 15 Jul 2018
15:47:48 GMTContent-Type: text/plain;charset=utf-8Transfer-Encoding:
chunkedConnection: closeVary: Accept-EncodingVary: CookieExpires: Wed,
11 Jan 1984 05:00:00 GMTCache-Control: no-cache, must-revalidate,
max-age=60X-hacker: Jetpack TestContent-Encoding: gzipX-ac: 3.dca _dca
OK                    [headers] => Requests_Response_Headers Object
                    (                            [data:protected] =>
Array                                (
   [server] => Array                                        (
                                  [0] => nginx
               )
                                    [date] => Array
                    (                                            [0]
=> Sun, 15 Jul 2018 15:47:48 GMT
 )
                                    [content-type] => Array
                            (
  [0] => text/plain;charset=utf-8
  )
                                    [vary] => Array
                    (                                            [0]
=> Accept-Encoding                                            [1] =>
Cookie                                        )
                                    [expires] => Array
                       (
[0] => Wed, 11 Jan 1984 05:00:00 GMT
     )
                                    [cache-control] => Array
                             (
   [0] => no-cache, must-revalidate, max-age=60
                )
                                    [x-hacker] => Array
                        (
[0] => Jetpack Test                                        )
                                    [content-encoding] => Array
                                (

[0] => gzip

                                        )
                                    [x-ac] => Array
                    (                                            [0]
=> 3.dca _dca                                        )
                                )
                        )
                    [status_code] => 200
[protocol_version] => 1.1                    [success] => 1
        [redirects] => 0                    [url] =>
http://jetpack.wordpress.com/jetpack.test/1/
[history] => Array                        (                        )
                    [cookies] => Requests_Cookie_Jar Object
            (                            [cookies:protected] => Array
                              (                                )
                        )
                )
            [filename:protected] =>             [data] =>
[headers] =>             [status] =>         )
)

HTTPSArray(    [headers] => Requests_Utility_CaseInsensitiveDictionary
Object        (            [data:protected] => Array                (
                  [server] => nginx                    [date] => Sun,
15 Jul 2018 15:47:48 GMT                    [content-type] =>
text/plain;charset=utf-8                    [vary] => Array
            (                            [0] => Accept-Encoding
                    [1] => Cookie                        )
                    [expires] => Wed, 11 Jan 1984 05:00:00 GMT
           [cache-control] => no-cache, must-revalidate, max-age=60
                [x-hacker] => Jetpack Test
[content-encoding] => gzip                    [x-ac] => 3.dca _dca
               [strict-transport-security] => max-age=15552000
       )


	
	
	
	

 )

    [body] => OK    [response] => Array        (            [code] =>
200            [message] => OK        )
    [cookies] => Array        (        )
    [filename] =>     [http_response] => WP_HTTP_Requests_Response
Object        (            [response:protected] => Requests_Response
Object                (                    [body] => OK
    [raw] => HTTP/1.1 200 OKServer: nginxDate: Sun, 15 Jul 2018
15:47:48 GMTContent-Type: text/plain;charset=utf-8

Transfer-Encoding: chunkedConnection: closeVary: Accept-EncodingVary:
CookieExpires: Wed, 11 Jan 1984 05:00:00 GMTCache-Control: no-cache,
must-revalidate, max-age=60X-hacker: Jetpack TestContent-Encoding:
gzipX-ac: 3.dca _dcaStrict-Transport-Security: max-age=15552000
OK                    [headers] => Requests_Response_Headers Object
                    (                            [data:protected] =>
Array                                (
   [server] => Array                                        (
                                  [0] => nginx
               )
                                    [date] => Array
                    (                                            [0]
=> Sun, 15 Jul 2018 15:47:48 GMT
 )
                                    [content-type] => Array
                            (
  [0] => text/plain;charset=utf-8
  )
                                    [vary] => Array
                    (                                            [0]
=> Accept-Encoding                                            [1] =>
Cookie                                        )
                                    [expires] => Array
                       (
[0] => Wed, 11 Jan 1984 05:00:00 GMT
     )

[cache-control] => Array

                                        (
              [0] => no-cache, must-revalidate, max-age=60
                           )
                                    [x-hacker] => Array
                        (
[0] => Jetpack Test                                        )
                                    [content-encoding] => Array
                                (
      [0] => gzip                                        )
                                    [x-ac] => Array
                    (                                            [0]
=> 3.dca _dca                                        )
                                    [strict-transport-security] =>
Array                                        (
                   [0] => max-age=15552000
           )
                                )
                        )
                    [status_code] => 200
[protocol_version] => 1.1                    [success] => 1
        [redirects] => 0                    [url] =>
https://jetpack.wordpress.com/jetpack.test/1/

(

                        )
                    [cookies] => Requests_Cookie_Jar Object
            (                            [cookies:protected] => Array
                              (                                )
                        )
                )
            [filename:protected] =>             [data] =>
[headers] =>             [status] =>         )
)

IDENTITY_CRISISPASS
SELFArray(    [headers] => Requests_Utility_CaseInsensitiveDictionary Object

[data:protected] => Array

                (                    [server] => nginx
   [date] => Sun, 15 Jul 2018 15:47:57 GMT
[content-type] => text/plain;charset=utf-8
[expires] => Wed, 11 Jan 1984 05:00:00 GMT
[cache-control] => no-cache, must-revalidate, max-age=60
     [x-hacker] => Jetpack Test                    [x-ac] => 3.dca
_dca                    [strict-transport-security] =>
max-age=15552000                )
        )
    [body] => {"error":"Communication error","error_description":"We
were unable to make an XML-RPC request to your website. Please make
sure that XML-RPC is turned on and that Jetpack is installed,
activated and connected with your WordPress.com account. If the error
persists, try disconnecting and connecting Jetpack again."}
[response] => Array        (            [code] => 400
[message] => Bad Request        )
    [cookies] => Array        (        )
    [filename] =>     [http_response] => WP_HTTP_Requests_Response
Object        (            [response:protected] => Requests_Response
Object                (                    [body] =>
{"error":"Communication error","error_description":"We were unable to
make an XML-RPC request to your website. Please make sure that XML-RPC
is turned on and that Jetpack is installed, activated and connected
with your WordPress.com account. If the error persists, try
disconnecting and connecting Jetpack again."}                    [raw]
=> HTTP/1.1 400 Bad RequestServer: nginxDate: Sun, 15 Jul 2018
15:47:57 GMTContent-Type: text/plain;charset=utf-8Transfer-Encoding:
chunkedConnection: closeExpires: Wed, 11 Jan 1984 05:00:00
GMTCache-Control: no-cache, must-revalidate, max-age=60X-hacker:
Jetpack TestX-ac: 3.dca _dcaStrict-Transport-Security:
max-age=15552000
{"error":"Communication error","error_description":"We were unable to
make an XML-RPC request to your website. Please make sure that XML-RPC
is turned on and that Jetpack is installed, activated and connected
with your WordPress.com account. If the error persists, try
disconnecting and connecting Jetpack again."}
[headers] => Requests_Response_Headers Object                        (
                           [data:protected] => Array
             (                                    [server] => Array

[0] => nginx

                                        )
                                    [date] => Array
                    (                                            [0]
=> Sun, 15 Jul 2018 15:47:57 GMT
 )
                                    [content-type] => Array
                            (
  [0] => text/plain;charset=utf-8
  )
                                    [expires] => Array
                       (
[0] => Wed, 11 Jan 1984 05:00:00 GMT
     )

[cache-control] => Array

                                        (
              [0] => no-cache, must-revalidate, max-age=60
                           )
                                    [x-hacker] => Array
                        (
[0] => Jetpack Test                                        )
                                    [x-ac] => Array
                    (                                            [0]
=> 3.dca _dca                                        )
                                    [strict-transport-security] =>
Array                                        (
                   [0] => max-age=15552000
           )
                                )
                        )
                    [status_code] => 400
[protocol_version] => 1.1                    [success] =>
       [redirects] => 0                    [url] =>
https://jetpack.wordpress.com/jetpack.testsite/1/?url=https://bootifulworld.net/xmlrpc.php
                   [history] => Array                        (
               )
                    [cookies] => Requests_Cookie_Jar Object
            (                            [cookies:protected] => Array
                              (                                )
                        )
                )
            [filename:protected] =>             [data] =>
[headers] =>             [status] =>         )
)

**Review by vindl — APPROVED** [review]

**Review by Copons — APPROVED** [review]

**Comment by mdggjfgdog** [comment]
Merci`

**Comment by dougaitken** [comment]
Adding 1291753-zen for myself to loop back after this is merged

**Comment by mdggjfgdog** [comment]
nice: note am using wp multisite
Site going so fast without Jetpack, but i need it for Woo & WPMp and
integrations with WP & boldgrid.
Spread the Love.

**Comment by mdggjfgdog** [comment]
tried patch
new fatal error
Parse error: syntax error, unexpected 'if' (T_IF) in
/home/*******/public_html/wp-content/plugins/jetpack.deactivate/modules/widgets/simple-payments.php
on line 479

**Comment by mdggjfgdog** [comment]
Please ignore 2-3 months comments. I have had issues from my
WP/Boldgrid/Jetpack begining

But this is email i sent to Inmotion today.
*****
After 2 mins loading bootifulworld.net/whmcs/admin
https://bootifulworld.net/whmcs/admin/login.php?redirect=%2Fwhmcs%2Fadmin%
2Findex.php
https://bootifulworld.net/whmcs/admin/login.php?incorrect=1
what about viewing my front page .....https://bootifulworld.net/whmcs   er,
no returned to https://bootifulworld.net/#
i am locked out, some days good, some bad, but from memory it is healthy, i
have 2 errors that come up. Though both errors have been resolved, One is
about date-time-location.php

and i am unable to add sites to multi sites since installed in May
also i have an issue with images, and them disappearing., since starting
November 2017, and slow site since begining. NOV 2017
and still Jetpack, i applied their patch, and got another FATAL ERROR, so
deactived.   **************

Yes Gabriel, i tried patch last night, and another FATAL ERROR came up, i
will try again now.
I have contacted Jetpack Twice, with no reply.

Appreciate everyone`s help and values.
yours Gray of bootifulworld

On Sat, Jul 21, 2018 at 7:25 AM, Gabriel Maldonado <notifications@github.com

**Comment by mdggjfgdog** [comment]
I have tried patch again....

// Register Jetpack_Simple_Payments_Widget widget.

function register_widget_jetpack_simple_payments() {

+ if ( ! class_exists( 'Jetpack_Simple_Payments' ) ) {

+ return;

+ }

+

$jetpack_simple_payments = Jetpack_Simple_Payments::getInstance();

if ( ! $jetpack_simple_payments->is_enabled_jetpack_simple_payments() ) {

return;

Parse error: syntax error, unexpected 'if' (T_IF) in
/home/bootif5/public_html/wp-content/plugins/jetpack.deactivate/modules/widgets/simple-payments.php
on line 479


yours G

**Comment by Copons** [comment]
@mdggjfgdog It looks like you probably forgot to remove the `+` symbols when you manually pasted this fix.

Try replacing the entire `register_widget_jetpack_simple_payments` function with this instead:
```php
	function register_widget_jetpack_simple_payments() {
		if ( ! class_exists( 'Jetpack_Simple_Payments' ) ) {
			return;
		}
		$jetpack_simple_payments = Jetpack_Simple_Payments::getInstance();
		if ( ! $jetpack_simple_payments->is_enabled_jetpack_simple_payments() ) {
			return;
		}
		register_widget( 'Jetpack_Simple_Payments_Widget' );
	}
```

**Comment by mdggjfgdog** [comment]
Yes and i knew better..i have tried Copons as above, and got an error on the last line, so i have returned to previous patch and after trying to de-activate, got similar result - Parse error: syntax error, unexpected end of file in /home/*******/public_html/wp-content/plugins/jetpack.deactivate/modules/widgets/simple-payments.php on line 486

**Comment by Copons** [comment]
@mdggjfgdog I can't seem to reproduce it, and I'm inclined to think there are other typos in the file.

Would you mind replacing the entire content of your `modules/widgets/simple-payments.php` with the current content of the file in this repo?
(You can find it here: https://raw.githubusercontent.com/Automattic/jetpack/d3a69aac1463184e8353668eb2ccd9675781909e/modules/widgets/simple-payments.php)

**Comment by mdggjfgdog** [comment]
bravo !! so far so good, will check in the morning again. What was the
error?
may 1ooo data petals fall on your head !!

bootifulworld is many ££££ in the negative but would like to contract
someone, to tidy up, my efforts. I have learnt so much these last few
months, but early on i must have made some mistakes. I myself are on a
mission, which i know will be a success, but i need to be doing other
things, like stocking shop, creating identity and using the scanner etc,
and i have a large pile `of next jobs to do`. And paying for skilled help
will save me money. So I am offering £300 or $395, to help me resolve my
other issues. I value your time/skills at £50per hour.

Thanks to everyone, again

**Comment by mdggjfgdog** [comment]
Hi, Working but not working, whilst everything apart from whmcs is running
smooth. Site-Jetpack message - going off hourly (not exactly).

Your site is responding intermittently, or extremely slowly. This can
indicate an overloaded, under-powered, or misconfigured server. Your site
is probably loading for some users, but not for everyone.

so not same issue, and i am not getting any error messages any where else ?
can anyone give me a pointer in any direction
yours G J Flattery

**Comment by zinigor** [comment]
@mdggjfgdog thanks for contacting us! The fact that your site is running OK with the patch is great news! The fact that it's slow for some reason is not.
Have you tried contacting someone from your hosting provider? A slow site is impossible to debug without taking a look at what's "inside". Tech support should be able to get down to the root cause pretty quickly.

**Comment by mdggjfgdog** [comment]
Thanks Igor, yes i just have. This stream can be closed now. Thanks people

**Comment by 123dev** [comment]
The latest update Jetpack 6.3.3 broke it back :(

**Comment by dougaitken** [comment]
Hi @123dev, this is tagged with version 6.4 so the fix in this pull request wasn't included in 6.3.3

**Comment by 123dev** [comment]
Hi @dougaitken  thanks for the clarification.
Seeing how simple code change it is, it's puzzling that it's not already patched in the next minor release, considering that it breaks multisite deployments.
Shouldn't this be considered a hot fix rather than leave it for next major release?
Meanwhile each time there is an update we're caught missing this.

Thanks

**Comment by dougaitken** [comment]
@123dev Jetpack version 6.4. was released yesterday. This fix was specific to multisite installations. 

https://jetpack.com/2018/08/07/jetpack-6-4-release/

If you are on version 6.4 and seeing this error, please reach out to the team - http://jetpack.com/contact

**Pull request merged**
