### PR TITLE
Jetpack Sync : update should_initialize_sender_enqueue to honor filtered value vs overwriting.

### PR DESCRIPTION
**Pull request by mdbitz**
Currently when a new sync action is enqueued we add a filter that will always enable sending of data on shutdown except when cron is disabled. 

This PR ensures we don't setup the shutdown sender if it has been determined sending is disabled by previous filters.

#### Changes proposed in this Pull Request:
* Update should_initialize_sender_enqueue to use the $enabled property it is filtering.

#### Does this pull request change what data or activity we track or use?
* No

#### Testing instructions:

* checkout branch
* Create a Post
* Verify action is queued and sent (can put log statement in send_data or view kibana logs)
* Add this filter to your site
```add_filter( 'jetpack_sync_sender_should_load', '__return_false', 1, 0 );```
* Create a Post
* Verify action is in the queue
  `$listener = \Automattic\Jetpack\Sync\Listener::get_instance();`
 `$queue = $listener->get_sync_queue();`
 `$queue->size();`

#### Proposed changelog entry for your changes:
* Jetpack Sync : update should_initialize_sender_enqueue to honor filtered value vs overwriting.

### CODE REVIEW

**Comment by jeherve** [comment]
Is this ready for review?

**Comment by kbrown9** [comment]
This PR doesn't fix the fatal that's triggered when the update is done via "Dashboard -> Updates" tool. Should we keep this PR in the 9.0.2 milestone?

**Comment by jeherve** [comment]
Moving this to the 9.1 milestone as per discussion: p1602216931271000-slack-CBG1CP4EN

**Comment by mdbitz** [comment]
sorry I let this sit as it turned out to be a different issue with the update. However it is an update we should make will revise for 9.2

**Review by anomiex — APPROVED** [review]
Seems sane. Testing instructions didn't work for me though.

**Comment by mdbitz** [comment]
Sorry I messed up the testing instructions Instead of defining the constant we can use the filter itself.

`add_filter( 'jetpack_sync_sender_should_load', '__return_false', 1, 0 );` This will stop the items from being immediately sent and will remain in the queue.

**Pull request merged**
