### PR TITLE
Sharing: Use https when possible

### PR DESCRIPTION
**Pull request by kraftbj**
See #4665

While relative protocol should work fine, we can make things more secure by always using https.

### CODE REVIEW

**Comment by kraftbj** [comment]
cc: @aduth

**Comment by arcivanov** [comment]
@kraftbj I'm going to try and confirm in a second. Any idea why protocol-relative URLs might not be working?

**Comment by arcivanov** [comment]
This can be closed. Reason: PEBKAC.

**Comment by aduth** [comment]
TBH, even if the protocol-relative links work, we should force HTTPS anyways. From my point of view, this LGTM, though noting there are a handful of relative URLs in `sharing.js` remaining as well.

**Comment by arcivanov** [comment]
@aduth I agree with you, just wanted to mention that the root cause of the issue was my theme, not jetpack, per #4665

**Comment by jeherve** [comment]
LGTM! 🚢

**Pull request merged**
