### PR TITLE
Jetpack: update full-screen connection banner to Emerald design

### LINKED ISSUE #29051: Jetpack Plugin: Update style of post-activation connection screen.
### What's happening?

Install Jetpack → Click Plugins on the WPA side menu → In the Plugins table, under Jetpack, click Activate → 

1. The page style is old and should be updated to the newer RNA style
2. The page scroll is too long (lots of white space at the bottom)
3. 
Image

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #29051

## Proposed changes:

This PR removes the legacy full-screen connection banner. Instead, we re-use the existing connection screen component currently in use in the Jetpack dashboard.

**Visuals**

| **Before** | **After** |
| ---------- | --------- |
| image | image |
|   |  |

**To do**

- [x] Ensure that the connection is still tracked with the same parameters, to avoid breaking funnels.
- [x] Add a dismiss button so folks can choose not to connect.
    - [x] That dismiss button should be controlled by the same logic as before.
- [x] Ensure the screen looks good on all screen sizes.
- [x] ~Just like the previous screen, I am a bit worried about a11y, since it's an overlay that doesn't remove the existing elements on the page.~ I chose to wrap the component in a modal, to clearly delimitate the content that's popping up in a more accessible way.
- [ ] Ensure that none of the other banners are impacted.
    - [x] Regular connection banner appearing on all pages.
    - [x] connection screen in the Jetpack dashboard.
    - [ ] License-aware connection banner.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

See the conversation in #29051 to find out more.

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

This is a bit tricky to test, since the banner only appears once you first activate the plugin. One way to repeat test on the same site is to use the WP CLI to "reset" a site:
`wp transient set activated_jetpack true`
If you type this in after disconnecting your site from WordPress.com, you should see the full-screen banner:

- In the Plugins menu
- In the Dashboard menu

If you reload the page, that banner should be gone.

Make sure you check:

- In different browsers and devices.

*More testing instructions to follow*

### CODE REVIEW

**Comment by jeffgolenski** [comment]
@jeherve you're a genius. Good idea to use the built in core functionality! I'm all about it, I just have 2 requests, if possible

- [ ] Can you make the distance of Y the same as X for the dismiss icon?

Screen Shot 2023-03-21 at 11 54 14 AM


- [ ] Is there a way we can occupy less vertical space to get rid of that scroll bar in the modal at this screen size? Perhaps by bumping the image up? Feels like those two website screenshots on the right are unnecessarily creating a scroll bar. 

Thanks Jer!

**Comment by jeherve** [comment]
@jeffgolenski Thanks for the feedback! I've taken a stab at it in 71f64520b9fb0b26ab5731a374e9782d110e2b9f, but it doesn't work in all screen resolutions I'm afraid:

image

Screenshot 2023-03-24 at 17 27 29
Screenshot 2023-03-24 at 17 27 05

If you have the chance, I would appreciate if you could take a look at it, let me know how I could fix this!

Thanks!

**Comment by jeffgolenski** [comment]
@jeherve Apologies for the delay. I think what you have is totally fine. Excellent work. Let's get this one shipped!

**Review by dereksmart — APPROVED** [review]
This new screen looks great! Tested all the other banners and found no regressions. Code reads properly as if it will only load in the correct state (admin, specific page, not connected...)

**Comment by dereksmart** [comment]
I didn't test the "license-aware connection" one for regression. Not sure where that is.

**Pull request merged**
