### PR TITLE
Sharing: use the old module name to add the filter to Sharing group

### PR DESCRIPTION
**Pull request by jeherve**

### CODE REVIEW

**Comment by enejb** [comment]
Can you provide a bit more context here?

**Comment by jeherve** [comment]
See the codex for more info:
http://developer.jetpack.com/

Check the module list in the sidebar: it includes counts for each Jetpack module.

This list is built from an array of module names, and then gathers filters for each hook that uses one of the module names on the list.

You'll notice that one element has its own group there:
screen shot 2017-01-23 at 18 46 45

That's because it uses a module name that isn't part of the array of module names. Let me know if you need more info, I can point you to the code that builds the array on WordPress.com!

**Comment by georgestephanis** [comment]
Would it be better to change everything to `sharing` instead, and handle the conversion wpcom side?

Regardless, I agree consistency is better, whichever usage we converge on.

**Comment by jeherve** [comment]
@georgestephanis I'm fine either way. It's a quick change on WordPress.com, so it'd be easy there. It would be a much bigger commit here, but it'd essentially be a big Find and Replace, so I can do that, just say the word :)

We had originally picked `sharedaddy` for the docblocks since that's how the module is named in Jetpack. All module names in docblocks match the Jetpack module name right now.

**Comment by georgestephanis** [comment]
I'll defer to @samhotchkiss's preference on naming convention.

**Comment by jeherve** [comment]
Merging this for now, we can always go back and rename all documentation and code to use `sharing` instead of `sharedaddy` later.

**Pull request merged**
