### PR TITLE
Add Guided Tour component

### PR DESCRIPTION
**Pull request by eoigal**
Adds GuidedTour Componet to Jetpack Components so that it can be used on wp-admin dashboard and calypso.

## Proposed changes:

* Adds GuidedTour component to Jetpack components

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Run `cd projects/js-packages/storybook`
* Run `pnpm run storybook:dev`
* Select `GuidedTour` component from the sidebar
* Confirm that it works as expected

### CODE REVIEW

**Comment by arthur791004** [comment]
I found there is an `ActionPopover` component that used by the [Jetpack Protect Onboarding](https://github.com/Automattic/jetpack/pull/34649) and [VideoPress](https://github.com/Automattic/jetpack/pull/27714) as the screenshot below. I think we can extend it to support color scheme and back/skip. What do you think?

| Jetpack Protect | VideoPress |
| - | - |
|  |   |

**Comment by eoigal** [comment]
> I found there is an `ActionPopover` component that used by the [Jetpack Protect Onboarding](https://github.com/Automattic/jetpack/pull/34649) and [VideoPress](https://github.com/Automattic/jetpack/pull/27714) as the screenshot below. I think we can extend it to support color scheme and back/skip. What do you think?

Ah nice find! Yeah that looks like something we can repurpose rather than introduce a similar component. I'll look into it today.

My only concern is that this is under Protect. We can probably make it work but feels like it should be abstracted to somewhere more common.

**Comment by jeherve** [comment]
> My only concern is that this is under Protect. We can probably make it work but feels like it should be abstracted to somewhere more common.

Yeah, I think it would make sense to extract the existing component to a new component in `js-packages/components`, so it can be used by both Protect and other codebases.

**Comment by eoigal** [comment]
Looks like this PR will no longer be necessary. There is another PR https://github.com/Automattic/jetpack/pull/37533 that will render the guided tours using vanilla javascript.

**Pull request closed without merging**
