### PR TITLE
Footer: add a confirm() before resetting options

### PR DESCRIPTION
**Pull request by dereksmart**
This adds a confirmation before resetting options (dev mode only)

screen shot 2016-08-24 at 8 22 09 am

To Test: 
- Click `Reset Options`
- Verify you see the confirmation, and that confirming and denying works as expected.

### CODE REVIEW

**Comment by jeherve** [comment]
Since you're working on that, do you think you could also hide that link from non-admins?

**Comment by oskosk** [comment]
@jeherve fwiw, It's only showing on dev versions

**Comment by oskosk** [comment]
Works as expected. 🚢

**Comment by ebinnion** [comment]
@oskosk - what if a site is running our beta on a live site?

**Comment by jeherve** [comment]
> It's only showing on dev versions

Right, but a site running a development version of Jetpack could have editors, too.

**Comment by dereksmart** [comment]
@jeherve done in 18e02a9

**Pull request merged**
