### PR TITLE
Jetpack: add VideoPress beta block scaffolding 

### PR DESCRIPTION
**Pull request by retrofox**
This PR adds the scaffolding of the VideoPress (beta) block. The code lives into the `v6/` folder:

image

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack: add VideoPress beta block scaffolding 

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

This implementation defines the VideoPress block as a [beta extension](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/extensions#beta-extensions), meaning that it won't be available in production, hidden by default. To be able to enable the block, you need to:

* For the local environment, be sure that beta blocks are enabled by setting the global `JETPACK_BETA_BLOCKS` constant:
```php
define( 'JETPACK_BETA_BLOCKS', true );
```
* In the WordPress.com environment, Automatticians will be able to see beta extensions with no further configuration
* In a Jurassic Ninja site, you must go to Settings > Jetpack Constants, and enable the `JETPACK_BETA_BLOCKS` option there.
* Create/edit a post via the block editor
* Confirm the VideoPress block is available 
* Confirm it shows the `(beta)` label
* Save the post
* Confirm the block renders in the front-end (you should see a log in the console)

Screen Shot 2022-06-22 at 7 03 36 PM
Screen Shot 2022-06-22 at 7 03 14 PM

image

image

Screen Shot 2022-06-23 at 1 00 10 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202490094773323

### CODE REVIEW

**Comment by oskosk** [comment]
Looking great!. But let's move v6 out of `deprecated` like 
```
git mv projects/plugins/jetpack/extensions/blocks/videopress/deprecated/v6 projects/plugins/jetpack/extensions/blocks/videopress/v6
```

**Comment by retrofox** [comment]
> Looking great!. But let's move v6 out of `deprecated` like
> 
> ```
> git mv projects/plugins/jetpack/extensions/blocks/videopress/deprecated/v6 projects/plugins/jetpack/extensions/blocks/videopress/v6
> ```

done!

**Review by leogermani — APPROVED** [review]
Looks good and tests well for me.

I see the new block only if I enable beta blocks.

I confirm that the old block still works as usual

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D83123-code, and deploy it.

r248025-wpcom

**Pull request merged**
