### PR TITLE
CRM: Resolves 1907 - Hopscotch welcome tour fixes

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves Automattic/zero-bs-crm#1907 - Hopscotch welcome tour fixes

## Proposed changes:

Our welcome tour has been broken for some time; it only went through a few steps. I moved it a bit further in #31006 (it's tied to the learn menu in its current implementation), but this PR gets it through all the steps. It's easy enough to extend if we want, or we could remove it entirely at some point (the library has been deprecated for some time), but at least it goes through a few pages now and finishes gracefully.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Ensure the welcome tour clicks through all the way to "done" on an existing site as well as a new site:

image

### CODE REVIEW

**Review by cleacos — CHANGES_REQUESTED** [review]
It doesn't work as expected. The tour stops at step 7b, after Manage Extensions

**Comment by tbradsha** [comment]
Fixed in 6f8bbed; the tour state was different on new empty sites.

**Comment by tbradsha** [comment]
Rebased.

**Review by cleacos — CHANGES_REQUESTED** [review]
Now it stops on the step-10 (Setting page)

**Comment by tbradsha** [comment]
Fixed state check on Settings page in fe01c81. I clicked all the way through this time. ;^)

**Comment by cleacos** [comment]
Let's see if you did your job well :^D

**Comment by cleacos** [comment]
Could we auto-close this when we start the tour with zero contacts?

image

**Review by cleacos — DISMISSED** [review]
It works now for me. All good, except for the issue when you don't have any contact yet, that you see the pop-up interrupting the tour.

**Comment by cleacos** [comment]
Added the commit that prevents the First Use popup with zero contacts: https://github.com/Automattic/jetpack/pull/31178/commits/387b2c88f7adc01a7224628c799f8482c7842ee9

**Review by cleacos — APPROVED** [review]
LGTM!

**Pull request merged**
