### PR TITLE
Image Compare: fix issue with editing two blocks in a post

### LINKED ISSUE #16117: Image Compare: more than 1 block makes following blocks non editable
If you have more than one Image Compare block on a page, only the first block can be edited, not the following blocks as an error appears:

> This block has encountered an error and cannot be previewed.

#### Steps to reproduce

1. Create a new page or post
2. Add at least 2 Image Compare blocks
3. Publish the page, and reload it
4. Notice the 2nd (and following) Image Compare blocks cannot be edited

#### What I expected

To be able to edit all Image Compare blocks

#### What happened instead

Only the first Image Compare block can be edited

#### Screenshot / Video

Screen Shot 2020-06-09 at 11 23 19

It was originally reported in 3046104-zd

### PR DESCRIPTION
**Pull request by mkaz**
Due to the way React `useLayoutEffect` works, the `scanPage` function is called multiple times, with the component in various states of ready. The load and execution order of the scripts change based on different environments, for example due to `concat_js` behavior on WPCOM.

This ends up causing problems if one of the states is not rendered how the script expects. This PR adds a couple of additional checks to make sure it is in a valid state to avoid errors.

~Additionally, the initial `scanPage` call at the end is no longer needed and was removed.~
Updated: scanPage function is required for front-end rendering.

Fixes #16117

#### Changes proposed in this Pull Request:

* Add check for `this.wrapper` and bail if not defined.
* Add check for two images in element and bail if not found.
* ~Remove initial `scanPage` call, not needed since done in `useLayoutEffect`~

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

No, fixes issue with Image Compare block released in 8.6

#### Does this pull request change what data or activity we track or use?

No, no data or activity change.

#### Testing instruction

See instructions at #16117 confirm this change fixes that issue.

#### Proposed changelog entry for your changes:

* Fix issue with two Image Compare blocks in the same post.

### CODE REVIEW

**Comment by mkaz** [comment]
@jeherve I'm not sure what the screenshot shows, I do end up seeing what looks like two Image Compare blocks. I've tested out with various orientations and settings and not seeing an issue in editor or front-end.

Do you have steps to duplicate? Have you rebuilt and hard refresh browser?

image-compare-dual2

**Comment by jeherve** [comment]
Here is how I reproduce:

1. Apply D44763-code (freshly rebased)
2. In a new post on a sandboxed site, I add new Image Compare blocks, separated by a paragraph.
3. I publish my post.
4. I view it on the front end; it looks good.
5. I click to go back to the editor for that post.
6. The second block is now displayed as on the screenshot above.

**Comment by mkaz** [comment]
Can you try it again? I think it was related to the KSES issue, I'm not able to duplicate now that has been merged. Likewise, my testing previously was with it in place on my sandbox.

I think when the block validation broke, it had another strange side effect when rendering.

**Comment by mkaz** [comment]
r209225-wpcom

**Pull request merged**
