### PR TITLE
Build: First pass at minifying module JS

### PR DESCRIPTION
**Pull request by ebinnion**
As part of a front-end performance audit that @gravityrail and I are doing, this PR will start minifying all front-end assets that are loaded from the shortcodes module.

To test:

- Checkout branch
- `yarn build`
- Ensure that license is at top of the output for this command:
    - `more _inc/build/shortcodes/js/jmpress.min.js`
- Test the following shortcodes:
    - brightcove
    - gist
    - instagram
    - presentation
    - quiz
    - recipe
    - slideshow
- Ensure there are no JS errors on the frontend and that shortcodes are still functional
- In `wp-config.php`, add `define( 'SCRIPT_DEBUG`, true );` and check that non-minified files are now enqueued by checking the source

Note: I am removing `modules/shortcodes/js/jmpress.min.js` from source control since we'll now build it.

### CODE REVIEW

**Comment by ebinnion** [comment]
I've now scoped this changeset down to the shortcodes module for the time being. This will make the PR easier to review for the time being and allows us to verify this approach without investing time in changing all the files that enqueue JS multiple times.

**Comment by ebinnion** [comment]
Looks like there's an issue with sourcemap paths. I'll look into this tomorrow.

**Comment by oskosk** [comment]
I've just checked this branch and have these observations:

* On the frontend I still keep getting served `modules/shortcodes/js/jmpress.min.js?ver=0.4.5`
* You mention in the description that `modules/shortcodes/js/jmpress.min.js` is ignored now in this PR but `.gitignore` states that the whole `/modules/shortcodes/js` is to be ignored ).
* I ran the build and I never got a file `_inc/build/shortcodes/js/jmpress.min.js` built.
* After running `yarn build` again I realized by going into the `_inc/build` directory that the `jmpress.min.js` and `jmpress.min.js.map` are left in `_inc/build` and not in `_inc/build/js` but loading the fronted results in that I'm still served the original `min.js`  in `modules/shortcodes/js/`

**Comment by ebinnion** [comment]
I have fixed the issue that I noticed yesterday with sourcemaps. The issue was that we were piping to banner between sourcemaps init and sourcemaps write. As soon as I moved the pipe to banner to above sourcemaps init, all was well with the world.

**Comment by dereksmart** [comment]
> We don't want those in the plugin directory

Correct, we want to make sure any .map files are added to svnignore, as we're doing with the admin UI map files.

**Comment by ebinnion** [comment]
I've addressed feedback such that we are now:

- Conditionally enqueueing min or non-min JS based on `SCRIPT_DEBUG`
- Properly `.svnignore`ing map files

As a follow-up to this PR, I'll move other JS and CSS map files to the `_inc/build/maps` directory as well.

**Pull request merged**
