### PR TITLE
Story Block: Pause on long press

### PR DESCRIPTION
**Pull request by Tug**
Addresses https://github.com/Automattic/jetpack/issues/19949

#### Changes proposed in this Pull Request:
This PR implements a couple of navigation change for mobile users:
- [x] Pause on long press: This allows users to pause the video when pressing the screen with 1 finger, the story starts playing again when the user release their finger
- [x] Allow the next slide button to end the story on the last slide
- [x] Allow Enter to "launch" the story from the embed

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* Play a story with and without a video
* Put your finger on the screen to pause the slide, release to play it back
* Try going to the next slide by tapping on the (2/3rd) right side of the screen
* Try going to the previous slide by tapping on the (1/3rd) left side of the screen
* Make sure all the other controls work as expected: play/pause, mute/unmute, exit fullscreen

### CODE REVIEW

**Comment by samiff** [comment]
@Tug Wasn't sure if this one was ready for review, but I've moved it out of draft status.

* Allow Enter to "launch" the story from the embed ✅
* Allow the next slide button to end the story on the last slide ✅
* Make sure all the other controls work as expected: play/pause, mute/unmute, exit fullscreen ✅
* Pause on long press: This allows users to pause the video when pressing the screen with 1 finger, the story starts playing again when the user release their finger ❌

The pause on long press did not work for me. I'm testing on an iPhone 12 in Safari & Chrome. Should this be working currently? I feel the vibration feedback after a long press, but nothing happens.

**Comment by Tug** [comment]
Yes the PR isn't ready yet. Although the pause on long press part should have been working. I'm using the same device and browsers 🤔 I'll investigate further

**Comment by Tug** [comment]
@samiff @aforcier This is ready now 🙇

**Comment by samiff** [comment]
Currently testing on [this](https://maximum-scorpion.jurassic.ninja/2021/06/07/story-block-test/) JN site post.

The long press to pause worked for @sdixon194 on his Android, but on my iPhone 12 mini I'm not having any luck (Chrome or Safari). Not sure if there is a system setting or something else that would be interfering in some way. If I have time I'll try to swing back to this and do some logging.

**Comment by samiff** [comment]
@Tug are you testing with a physical iOS device or virtual? I did some quick logging on my end and I'm not seeing the onTouchStart/onTouchEnd events fire at all when I long press - just a small vibration feedback and nothing happens.

**Comment by Tug** [comment]
Thanks for testing again @samiff.
I'm testing on a physical device (iphone 12 pro).

> I did some quick logging on my end and I'm not seeing the onTouchStart/onTouchEnd events fire at all when I long press

Indeed, it seems there's a really strange bug for which I haven't figured out the cause yet.
On [the main page](http://ephemeral-dekervit-20210511.atomicsites.blog/) of my test site, I'm able tohave longpress working. However opening a story in its own page then I'm experiencing the same issue you have.

I have also noticed that in those cases onTouchStart/onTouchEnd events do not fire and that they do when I disable the shadow dom. I don't yet understand what the difference is between the main page and the post page. Will need to investigate deeper.

**Comment by Tug** [comment]
I believe to have found a working "hack" for this strange bug. Haven't been able to track down the root cause of the issue but I would be it's a limitation of webkit ios.

**Comment by Tug** [comment]
@samiff Would you have a chance to test the "hack" see if it fixes it for you?

**Review by samiff — APPROVED** [review]
Latest changes are now working on my iphone 👍

**Comment by Tug** [comment]
Awesome! Thank you @samiff !

**Comment by Tug** [comment]
r227776-wpcom

**Pull request merged**
