### PR TITLE
Update/add my jepack card loaded event

### PR DESCRIPTION
**Pull request by jboland88**
## Proposed changes:

* This diff adds a "loaded" event for the product cards on the My Jetpack page

## Jetpack product discussion

panfyZ-34C-p2#comment-8569

## Does this pull request change what data or activity we track or use?

Yes, this PR tracks an event when each product card loads on the My Jetpack page.

## Testing instructions:

* With this PR applied, navigate to My Jetpack
* Observe your network panel, you can filter requests by `t.gif`. 
* Make sure you see a `jetpack_myjetpack_product_card_loaded` event for each product card on the page

### CODE REVIEW

**Review by IanRamosC — DISMISSED** [review]
Looks good! :shipit: 
It seems like the PR needs a merge/rebase before merging it.

**Comment by jenhooks** [comment]
@jboland88 I _think_ the existing material in the [General Analytics Tracking section in our Privacy Center](https://jetpack.com/support/privacy/#analytics) already covers whatever was introduced in this change - can you give me a confidence check on that?

**Comment by jboland88** [comment]
@jenhooks - these changes seem to be generally covered by the general analytics tracking section, yes.
These events are firing when certain parts of the page (product cards) are loaded. Not sure how specific we need to be with the language in the privacy center - saying we track "Page Views" may cover that in a broad sense?

**Review by IanRamosC — APPROVED** [review]
:shipit:

**Pull request merged**
