### PR TITLE
Minimum Sync Config: Update required modules and options

### PR DESCRIPTION
**Pull request by fgiannar**
This PR updates the minimum required data settings for Sync while fixing a few existing logic errors.

#### Changes proposed in this Pull Request:
Fixes:
* `Sync\Data_Settings::add_filters_custom_settings_and_hooks`: Updated the check for enabled modules to also take into account the ones defined under `MUST_SYNC_DATA_SETTINGS`. This fixes an inconsistency, where if the corresponding module was not provided by the consumer plugin under `jetpack_sync_modules` it would be activated with the default settings otherwise with the minimum settings. Covered in the following unit test: `Data_Test_Data_Settings::data_test_1_2`
* `Sync\Data_Settings::add_required_settings`: No need to add a custom filter setting if the corresponding setting is already set and matches the default one.

`Data_Settings::MUST_SYNC_DATA_SETTINGS`: 
* Add `Options` and `Constants` to the list of required modules
* Update required `jetpack_sync_callable_whitelist`
* Add required `jetpack_sync_constants_whitelist`
* Add required `jetpack_sync_options_whitelist`

README:
* Detailed instructions on getting started with Sync and configuring what data to sync.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p9dueE-5lh-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Get a test site with any Jetpack plugin that uses Sync (Jetpack, Backup).
* Connect site, observe Sync activity - see the full sync and all added data being synced correctly.
* Change the settings to minimal using the Config object:

```php

    use Automattic\Jetpack\Sync\Data_Settings;

    // ....
    // Change the existing `ensure` call to this: 
    $config->ensure( 'sync', Data_Settings::MUST_SYNC_DATA_SETTINGS );
```

* Observe that data doesn't get synced and you can only see options, callables and constants getting synced.
* Try again with multiple plugins installed, see that the settings get combined, not overwritten.

### CODE REVIEW

**Comment by leogermani** [comment]
Thanks for working on this and documenting everything. It looks more consistent now.

Using the debug tool in out Debug helper plugin, I just found one thing that I wanted to confirm with you. This was the previous behavior and I was not sure if this should change:

If I do this:



Captura de tela de 2022-06-24 14-08-07

It works fine. I see only the required options + the one I added

But if I do this:

Captura de tela de 2022-06-24 14-08-35

Then ALL options are synced. Not only the required ones.

In other words, I always need to declare the modules I want to play with.

Note that I'm taking conclusions from what I see in the debug tool. So there's also the chance of this being a problem with the debug tool itself.

...

In any case, I don't think we need to change anything in the Protect plugin. Even though the required callables now cover everything we need, and we could just register an empty array there, I think it's a good practice to make all plugins be explicit about what they need.

What do you think?

**Comment by fgiannar** [comment]
@leogermani Many thanks for testing this, Leo!

> In other words, I always need to declare the modules I want to play with.

Yes, you are right, excellent catch! The set expectation used to be that not declaring a filter or passing a null value or an empty array would result in the default setting to be applied.

[The logic is now updated](https://github.com/Automattic/jetpack/pull/24831/commits/71e527ee76256643866a4b7fe71e60af4c6c2dc9), so that null will indeed result in the default setting, however an empty array means that we want the min sync config to be applied.

So for example, if we don't specify `jetpack_sync_modules` ALL Sync modules will be enabled.
If we pass an empty array for `jetpack_sync_modules`, it means that the consumer would like NO Sync modules to be enabled, therefore we will enable only the required ones.
I think this is a more intuitive approach but could definitely use your thoughts on this!

...

> In any case, I don't think we need to change anything in the Protect plugin. Even though the required callables now cover everything we need, and we could just register an empty array there, I think it's a good practice to make all plugins be explicit about what they need.

Yes, we don't need to change anything there! I also agree that it's a good practice to make all plugins be explicit about what they need.

**Comment by leogermani** [comment]
> @leogermani Many thanks for testing this, Leo!
> 
> > In other words, I always need to declare the modules I want to play with.
> 
> Yes, you are right, excellent catch! The set expectation used to be that not declaring a filter or passing a null value or an empty array would result in the default setting to be applied.
> 
> [The logic is now updated](https://github.com/Automattic/jetpack/pull/24831/commits/71e527ee76256643866a4b7fe71e60af4c6c2dc9), so that null will indeed result in the default setting, however an empty array means that we want the min sync config to be applied.
> 
> So for example, if we don't specify `jetpack_sync_modules` ALL Sync modules will be enabled. If we pass an empty array for `jetpack_sync_modules`, it means that the consumer would like NO Sync modules to be enabled, therefore we will enable only the required ones. I think this is a more intuitive approach but could definitely use your thoughts on this!

I think it looks great, I can help updating the examples in the doc and maybe adding a clarification about this.

Just one thing still looks confusing to me.

If we follow the same understanding for all things we can customize, there's still one thing that looks a bit inconsistent (or not, depending on what is our understanding here...)

Again with my previous example:

Captura de tela de 2022-06-24 14-08-35

In this case:

* I'm not declaring any modules, meaning we are going to sync ALL modules, not only the default ones.
* I am declaring a few options. Should it mean that it will only Sync the default options plus the ones I added? That's not what happens because when I don't declare the Options modules, we sync everything under options and not only the default ones.

I actually think this can be useful, to allow us to add options on the top of every whitelisted option (and not only the default ones), otherwise we would have to merge the arrays. We just need to clarify this in the docs... but I wanted to confirm with you first if that's intended/expected/acceptable

**Comment by fgiannar** [comment]
> In this case:

> I'm not declaring any modules, meaning we are going to sync ALL modules, not only the default ones.

This is correct.

> I am declaring a few options. Should it mean that it will only Sync the default options plus the ones I added? That's not what happens because when I don't declare the Options modules, we sync everything under options and not only the default ones.

The intended behaviour when you declare the `jetpack_sync_options_whitelist` _should be_ to sync exactly what is there plus the required ones, NOT all the default ones PLUS the ones you specified.
This behaviour should also be the same independently of whether or not you listed the `Options` modules in `jetpack_sync_modules`.
For me, it's like the consumer plugin saying I only care to sync `my_custom_option_a`. Then Sync should take that into account and make sure this custom options plus the required ones are synced.

> I actually think this can be useful, to allow us to add options on the top of every whitelisted option (and not only the default ones), otherwise we would have to merge the arrays. We just need to clarify this in the docs... but I wanted to confirm with you first if that's intended/expected/acceptable

Based on the above, I think it should still be required for consumer plugins to merge the array with the default ones if they want to add on top of those and not override them - which is what currently happens.

**Comment by leogermani** [comment]
> This behaviour should also be the same independently of whether or not you listed the Options modules in jetpack_sync_modules.
For me, it's like the consumer plugin saying I only care to sync my_custom_option_a. Then Sync should take that into account and make sure this custom options plus the required ones are synced.
> Based on the above, I think it should still be required for consumer plugins to merge the array with the default ones if they want to add on top of those and not override them - which is what currently happens.

@fgiannar  This is not what happens in my tests.

If I don't add Options to the `modules` array, ALL default (whitelisted) options are synced, even when I add one option to the `options` array. You're saying that only the required + my option should be synced, but I don't see this

**Comment by fgiannar** [comment]
> If I don't add Options to the modules array, ALL default (whitelisted) options are synced, even when I add one option to the options array. You're saying that only the required + my option should be synced, but I don't see this

@leogermani This is strange. Have you tested after the latest version of this branch? Here's what I'm seeing, using the Jetpack Debug plugin with the following config:

```
$config->ensure(
	'sync',
	array(
		'jetpack_sync_options_contentless' => array(),
		'jetpack_sync_options_whitelist'   => array(
			'active_plugins',
		),
	)
);
```
Screenshot 2022-06-27 at 23 38 51

And [here's the corresponding unit test](https://github.com/Automattic/jetpack/pull/24831/files#diff-6586440c4104603f2d272f9a16f3589ea96b6e76a23f28e0284390300a1ce896R544)

**Comment by leogermani** [comment]
oops, a `git pull` was missing :)

**Review by leogermani — APPROVED** [review]

**Pull request merged**
