### PR TITLE
Connection: fix connection screen for non-admins

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
- fix the bug with connection screen not being available for non-admins
- fix the bug with `/connection/authorize_url` endpoint not being available to non-admins
- only show connection screen if the site already has a connection owner

#### Jetpack product discussion
p1634233299011100-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Connect Jetpack, create a non-admin user (e.g. Editor) and log in using that user.
2. Go to Jetpack Dashboard, confirm that you see the "Connect your WP.com account" bar in the top of the page.
3. Click on the button. Confirm that the connection screen appeared, and the "Connect your WP.com account" bar disappeared.
4. Click "Connect your user account" on the connection screen, go through the connection process.
5. Confirm that you get connected successfully. _There's an odd bug where you get automatically redirected to Jetpack Dashboard from the Calypso Plans page, we'll need to look into it separately. If you encounter it, please confirm that you also see it._
6. Disconnect Jetpack, use admin account to connect it in site-only mode.
7. Go back to the non-admin Jetpack Dashboard. Confirm that you don't see the "Connect your WP.com account" button.
8. Manually switch to the `/wp-admin/admin.php?page=jetpack#/connect-user` page and confirm that you get immediately redirected to `?page=jetpack#/dashboard`.

### CODE REVIEW

**Comment by kraftbj** [comment]
@adimoldovan How would you test this situation? An example of what's broken before this PR:
* Setup a Jetpack site, connect it fully.
* Create a new user with the author role.
* As the author, visit the Jetpack dashboard. Click on the "Connect your WordPress.com" button.

Expected: Takes the author to the connection flow to link their account.

Actual before this PR: Nothing. It tries to hit the /connect-user route but redirects immediately it seems on the client side.

I looked at the e2e test, but I'm not confident in how to setup the test as a connected site with a secondary non-admin trying to connect.

At the same time, a simpler JS unit test may be sufficient enough, but I don't know that we have a JS unit test infra setup, but I may be ignorant with my PHP-bias.

**Review by leogermani — APPROVED** [review]
I've tested with the provided testing instructions and everything worked.

I also confirmed the flow for secondary admins are working properly and checked the other button we have down below in the page to connect the user account.

I didn't see the bug mentioned in the description, but I did experiment [this bug](https://github.com/Automattic/wp-calypso/issues/55969) again

I'll leave my approval for now but won't change the labels assuming other people still want to check it

**Review by jeherve — APPROVED** [review]
This seems to test well for me, and I could not reproduce the bug either. 🚢

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-10.2` in 27d7e5e86bdf725485087a099a0a109e0e6e5e33 (noting that I had to fix a merge conflict since #21038 has also been merged in the past few weeks).

@sergeymitr Could you check that my cherry-pick commit makes sense?

Thank you!

**Comment by sergeymitr** [comment]
Thanks @leogermani, @jeherve.
Tested it on `master`, works great.

**Comment by brbrr** [comment]
Hey @sergeymitr. I'm curious if you had time to look into adding a unit test for this bug.

**Comment by sergeymitr** [comment]
Hi @brbrr.
Thanks for the ping, totally slipped my mind.
Will do.

**Comment by brbrr** [comment]
Hi @sergeymitr

Just checking if you end up adding the tests :)

**Comment by sergeymitr** [comment]
Hi @brbrr 👋 
I looked into it at some point, ran into some issues with E2E, and had to put it off to work on some higher priority tasks.
Thanks for reminding me about it.

**Comment by brbrr** [comment]
I think the conclusion here is that we don't need E2E capabilities to make sure the bug is fixed, and a JS unit test should be enough.

**Pull request merged**
