### PR TITLE
Update wc-calypso-bridge to v2.8.1

### PR DESCRIPTION
**Pull request by Ferdev**
## Proposed changes:

This PR bumps the version of `wc-calypso-bridge` to `2.8.1`, which includes the following changes:

- https://github.com/Automattic/wc-calypso-bridge/pull/1527
- https://github.com/Automattic/wc-calypso-bridge/pull/1529
- https://github.com/Automattic/wc-calypso-bridge/pull/1530

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

The changes related to the wc-calypso-bridge were already tested in the linked PRs. Testing instructions can be found on the linked PRs above.

### CODE REVIEW

**Review by moon0326 — COMMENTED** [review]
I think you're missing composer.lock update.

**Comment by Ferdev** [comment]
Sorry about that, @moon0326! Totally missed that part, this was my first PR in this repo :man_facepalming: Should be fine now :+1: 

Thanks!

**Comment by moon0326** [comment]
> Sorry about that, @moon0326! Totally missed that part, this was my first PR in this repo 🤦‍♂️ Should be fine now 👍
> 
> Thanks!

No worries 😄 I forget about it from time to time too. LGTM! 🚀

**Review by moon0326 — APPROVED** [review]
LGTM 👍 🚀

**Comment by Ferdev** [comment]
awesome, thanks @moon0326! Is merging the PR enough to get this deployed, or is there anything else I should to for that?

**Pull request merged**
