### PR TITLE
avoid PHP warning when static.html doesn't exist

### PR DESCRIPTION
**Pull request by paulschreiber**
Fixes a PHP warning when `static.html` doesn't exist.

### CODE REVIEW

**Comment by kraftbj** [comment]
Thanks Paul. That file should be there on built branches (e.g. `master-stable`), but would throw this warning on unbuilt branches. If you're on `master` for testing/dev, `master-stable` is typically within a day of `master` and built.

**Comment by zinigor** [comment]
Yes, furthermore, if there is no `static.html` file, the new admin page will not load, so I'd say we better fail here rather than display an empty page.

**Comment by paulschreiber** [comment]
Failing silently is not an appropriate solution. We should show some sort of error message.

**Comment by zinigor** [comment]
@paulschreiber that's exactly what I'm talking about, thanks for creating this PR. I'm afraid the real issue here is that we need to make Jetpack be able to work directly from `master` or make it clear which branches you need to use in order to run it from git.

**Comment by jeherve** [comment]
> make it clear which branches you need to use in order to run it from git.

We had added this to the Readme:
https://github.com/Automattic/jetpack/blob/master/readme.md#installation-from--git-repo

Do you think we should add a notice within the plugin, in the `master` branch, with a warning to let folks know the branch won't work when it's not built?

**Comment by paulschreiber** [comment]
@zinigor Crashing and showing a backtrace does not count as "showing an error message."

**Comment by zinigor** [comment]
@paulschreiber yes, I agree, all I'm saying that there's still more work to do here. Sadly we can't use your code as it is right now.

**Comment by eliorivero** [comment]
Closing this as it's now outdated since we're using a different method to retrieve the static files and there are messages in the page now. I've also opened a #5073 where I reworded `page` to `static.html` to point the specific file missing.

**Pull request closed without merging**
