### PR TITLE
Newsletters: Fix: Prevent Emails on 'Post Only' Setting in Newsletter

### LINKED ISSUE #35998: Selecting Post Only option still sends email to some users
### Impacted plugin

Jetpack

### Quick summary

Markup 2024-02-27 at 13 38 55

I have a report from a WordPress.com customer where the Post Only option was selected in the Newsletter section of the Jetpack tab for a new post that was published, but two subscribers still got the post email notification. 
The site where the post was posted is on the WordPress.com Explorer plan.

The two subscribers who got the email were **not** WordPress.com users. 
The other subscribers who did not get the email were WordPress.com users. 
Is this feature supposed to suppress email notifications to all users, or just WordPress.com users?

### Steps to reproduce

I did not have time to try to reproduce but I wanted to go ahead and report in case others are experiencing the same thing.

### A clear and concise description of what you expected to happen.

I expected none of the subscribers to get the post notification email when the Post Only option was selected.

### What actually happened

Two subscribers who were not WordPress.com users got the email notification.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

7803673-zd-a8c

### PR DESCRIPTION
**Pull request by lezama**
Fixes #35998

This PR resolves the issue where emails were sent even when the "Post only" option was selected in the newsletter settings. The fix ensures the _jetpack_dont_email_post_to_subs meta` is updated correctly, aligning the email behavior with user selections.

## Proposed changes:

* Ensure `_jetpack_dont_email_post_to_subs` meta is synchronized before the `publish_post` action. (See discussion in D147226-code)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Write a Post
* Toggle the Post Only Newsletter setting
* Check the Network console and check the post is being saved

### CODE REVIEW

**Comment by lezama** [comment]
@simison it fills a little bit too clanky 😓 

https://github.com/Automattic/jetpack/assets/104869/a68702f1-468e-4be5-8d8a-b3f126f64d4d

**Comment by simison** [comment]
Yeah, not good. :-/ Let's explore alternatives.

Maybe at least saving the meta in the background if the post is draft?

**Comment by lezama** [comment]
@simison we have a solution p1715187596008499/1715024412.500929-slack-C45SNKV4Z, works great

**Comment by enejb** [comment]
This works as expected for me, nice work @lezama!

**Review by enejb — APPROVED** [review]
This works as expected for me.

**Pull request merged**
