### PR TITLE
Convert Facebook faux embeds to oEmbed

### PR DESCRIPTION
**Pull request by codebykat**
Facebook supports oEmbed now. This updates the embeds and removes our no-longer-needed faux embed code `facebook.js`.

See r127066-wpcom and r127071-wpcom.

Might be more updates coming as we're hoping to get this whitelisted in core for 4.4.

### CODE REVIEW

**Comment by kraftbj** [comment]
@codebykat Is there a core ticket for whitelisting FB? We're trying to get 3.8.1 into beta now-ish in anticipation of 4.4. I assume if whitelisted in Core, we can set a ver check for under 4.4, then remove totally once we no longer support 4.3.x.

**Comment by codebykat** [comment]
@kraftbj @pento is working on a core patch - looks like it will get into 4.4. I'll drop a link here once that's done. Looks like I will also need to update this code to support /notes/, /questions/ and /media/ (if we care about those things, but may as well) so no point in merging it just yet.

**Comment by kraftbj** [comment]
Sounds good. Whatever we end up doing, as long as we have a fallback for 4.2 and 4.3 (what'll be supported by JP until the next major release), we should be all good.

Whenever it's ready, just say so and change the `in progress` label to `Needs Review`.

**Comment by kraftbj** [comment]
https://core.trac.wordpress.org/ticket/34737

**Comment by dereksmart** [comment]
@codebykat is this ready to go?

**Comment by codebykat** [comment]
@dereksmart It is not! We ran into some issues with it and rolled it back on WPCOM. I need to circle back with @pento on the current status, but essentially there was a bug with ampersand parsing in core that breaks the oEmbeds. We'll need to add a version check for JP.

**Comment by codebykat** [comment]
Note also that the core ticket for the embeds includes an updated regex from the one that was originally deployed on WPCOM.

**Comment by dereksmart** [comment]
@codebykat thanks for the update, bumping to next version as we're aiming for beta tomorrow

**Comment by jeherve** [comment]
This will most likely fix #1113 as well.

**Comment by samhotchkiss** [comment]
Since this is getting implemented into WP core, let's just plan to remove it from Jetpack once WP 4.7 is our minimum

**Pull request closed without merging**
