### PR TITLE
Fix syncing footnotes meta for core footnotes block

### PR DESCRIPTION
**Pull request by simison**
Goes with D158364-code

Fixes missing footnotes in Newsletter emails:

Screenshot 2024-08-14 at 14 53 03

## Proposed changes:

* Add `footnotes` post meta to synced list

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Create a new post, add footnotes to a paragraph
* Publish post, or you can preview it from "pre publish" sidebar; note email doesn't have footnotes visible
* Apply D158364-code and this PR; edit footnotes
* Save draft and preview post again, or send it to yourself with bin script `bin/subscriptions/send.php SITE_ID post POST_ID YOUR_EMAIL`

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
You'll probably want to update the tests in `projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php` to match the changes in the package.

**Comment by simison** [comment]
@jeherve this is a post meta, not site option. :-) The test file would be `projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-meta.php` but I don't really see anything to add there, as meta fields don't seem to have validator functions?

**Review by darssen — COMMENTED** [review]
I tested the functionality and it worked fine.

Regarding the tests failing, it took me a long time to understand that [this](https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/blocks.php#L2571) filter in core was sanitizing the 'foo' string while a[dding the post meta in the test](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-meta.php).

**Comment by simison** [comment]
@darssen thanks! TBH it's still a bit of a mystery to me, as it looks like the only meta field we're running through tests is `foobar`? Although I might be reading the code wrong. Do you have any advice for adapting the tests?

https://github.com/Automattic/jetpack/blob/0029e591c038007cd247bfe04e0f6dc306edef9b/projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-meta.php#L16
https://github.com/Automattic/jetpack/blob/0029e591c038007cd247bfe04e0f6dc306edef9b/projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-meta.php#L26

**Review by lezama — DISMISSED** [review]

**Comment by simison** [comment]
I see the issue now too; I was looking at "sync E2E tests" which had output that didn't make much sense, but the PHP tests made it clear. 👍 I'll push a fix.

**Comment by darssen** [comment]
@simison the approach in https://github.com/Automattic/jetpack/pull/38878/commits/044e930c522c76a55c62a04053cfd689b707da17 is similar to what I was thinking of, but you would need to ensure updating the part that checks the synced meta [here](https://github.com/Automattic/jetpack/pull/38878/commits/044e930c522c76a55c62a04053cfd689b707da17#diff-9b5652f045153bea674b5fb16f5056fb3e3ce1a8085c1750f2c6ad4545f4c4daR214) 

You're probably aware of it (if running your local on docker), but you should be able to use something like below to make sure your test works locally
`jetpack docker phpunit -- --filter=WP_Test_Jetpack_Sync_Meta::test_sync_whitelisted_post_meta`

**Comment by simison** [comment]
@darssen thanks! Fixed, good for another look alongside D158364-code.

**Review by darssen — APPROVED** [review]
Still working fine for me. 
:ship:

**Pull request merged**
