### PR TITLE
Launchpad Checklist API: Add start writing checklist and tasks

### PR DESCRIPTION
**Pull request by jeyip**
Related  https://github.com/Automattic/wp-calypso/pull/76095

## Proposed changes:

* We've migrated most launchpad checklist definitions into a backend endpoint.
* The start-writing checklist, however, is an exception
* We add start-writing checklist task and task definitions into `jetpack-mu-wpcom`
### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Run `bin/jetpack-downloader test jetpack-mu-wpcom-plugin add/start-writing-checklist-and-tasks-to-launchpad-checklist-api` to build and sync this branch to your sandbox. 
2. Sandbox a test site. 
3. Start a new onboarding site by logging out, navigating to wordpress.com/setup/start-writing, and signing up for a new account
4. Go to `https://developer.wordpress.com/docs/api/console/`, select Rest API and wpcom/v2, and input the following: `/sites/YOURSITESLUG/launchpad/checklist?checklist_slug=start-writing`. Confirm you get back an appropriate checklist that matches the status of checklist items for the `start-writing` flow

### CODE REVIEW

**Review by DustyReagan — DISMISSED** [review]
LGTM!

**Review by paulopmt1 — DISMISSED** [review]
Thanks for that work! LGTM.

**Review by candy02058912 — APPROVED** [review]
Tested and it LGTM. I've updated the PR to pass the CI.

checklist endpoint test

**Comment by paulopmt1** [comment]
Thanks for your work @jeyip!

**Pull request merged**
