### PR TITLE
Sync: Utilize import for WP_Error

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes issue reported from WordCamp.org:
Uncaught Error: Class 'Automattic\Jetpack\Sync\WP_Error' not found in /.../wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-rest-sender.php:37

#### Changes proposed in this Pull Request:

* For the Rest_Sender class, add `use WP_Error` to resolve the fatal.
* Added `use WP_Error` to other files that previously used \WP_Error so all are they same now.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* None. It's a syntax error really.

### CODE REVIEW

**Review by mdbitz — APPROVED** [review]
👍 Thanks Kraft, Approved

**Review by mdbitz — APPROVED** [review]
:)

**Comment by samiff** [comment]
cherry-picked to the 10.0 release branch in 5fb904ca68ee68927d0b008ead79ae9317be2285

**Comment by samiff** [comment]
New sync package version released: https://packagist.org/packages/automattic/jetpack-sync#v1.24.1
Added to 10.0 release branch in https://github.com/Automattic/jetpack/commit/a632065f5617394514c07ef680a6658370bfa778

**Pull request merged**
