### PR TITLE
Donations Block: Fix the editor got stuck after inserting a pattern with the donations block

### LINKED ISSUE #93072: Reusable Synced Pattern: Donation Block in Pattern causes Post Editor to Freeze
### Quick summary

Inserting a Reusable Pattern which include a Donation Block can cause the post and page editor to freeze. 
Error message: "The "jetpack-sidebar" plugin has encountered an error and cannot be rendered."

### Steps to reproduce

Create a two new patterns using the Site Editor or a post or page editor. One pattern should include an image, text, and any other non-payment related blocks such as a button block. Name the pattern Test One (or similar).  
The other pattern should have similar blocks as pattern one and include a Donation Block. Set the Donation Block to accept payments. Name the pattern Test Donation (or similar).

- Go to Posts > Add New Post. 
- Click +  > Patterns > My Patterns. 
- Select the pattern called Test One. Notice it is inserted into the editor. 
- Select the pattern called Test Donation. Notice the editor freezes. 
- Depending on your browser you may get an error message similar to:  "This page is slowing down Firefox. To speed up your browser, stop this page." 
- Notice that items on the editor are not clickable, it's not possible to close the block inserter or click on list view.
- A red banner with the error message "The "jetpack-sidebar" plugin has encountered an error and cannot be rendered."
- Reload the post editor. Content added to the page is not saved. 
- Depending on the browser you may get an error message related to restoring blocks.

### What you expected to happen

Adding a Donation Block to a pattern, then inserting the pattern to a page or post should not cause any errors. 
Or if it is not possible to use a payment related block in a reusable pattern we should see a warning message stating that it's not doable. 

### What actually happened

Editing the patterns in the Site Editor is possible. 
However, inserting the pattern in a post or page editor is not. 

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

8473749-zd
Theme: Apostrophe 2

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/wp-calypso/issues/93072

## Proposed changes:

There seem to be an issue to call the `setAttributes` when the component mounts (the block will be removed, insert, and update attribute forever), so making changes as below to avoid this issue
* Use the `fallbackLinkUrl` from the server side so it can always get the link of the current post instead of the post of the synced pattern
* Update the currency only when the post is unlocked

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the Site Editor to create your pattern with the donations block (without connecting to stripe)
* Go to create a new post
* Insert the pattern you just created
* Make sure the pattern is inserted correctly and the browser won't get stuck
* Prepare to connect to stripe
  * Sandbox `public-api.wordpress.com` and `subscribe.wordpress.com`
  * Add the code below to /wp-content/mu-plugins/0-sandbox.php in your WP.com sandbox:
     ```
     define( 'USE_STORE_SANDBOX', true );
     define( 'USE_BILLING_SANDBOX', true );
     define( 'BILLINGDADDY_SANDBOX', rtrim( 'https://' . `hostname` ) );
     ```
* Refresh the post editor
* Connect to stripe
* Make sure you can see the donation form after the connection
* Edit the amount and make sure it works as expected
* Go to edit the original pattern, change the amount, and back
* Make sure the editor won't get stuck
* Go to https://developer.wordpress.com/docs/api/console/
* Request `/sites/:site/posts/:post_id`
* Make sure the content of the response contains the post link instead of the pattern link

### CODE REVIEW

**Comment by fushar** [comment]
I am (trying to) review this right now!

**Review by taipeicoder — APPROVED** [review]
Tested,

- Go to the Site Editor to create your pattern with the donations block (without connecting to stripe)
- Go to create a new post
- Insert the pattern you just created
 
✅ Make sure the pattern is inserted correctly and the browser won't get stuck

- Prepare to connect to stripe
- Sandbox public-api.wordpress.com and subscribe.wordpress.com
- Add the code below to /wp-content/mu-plugins/0-sandbox.php in your WP.com sandbox:
define( 'USE_STORE_SANDBOX', true );
define( 'USE_BILLING_SANDBOX', true );
define( 'BILLINGDADDY_SANDBOX', rtrim( 'https://' . `hostname` ) );
- Refresh the post editor
- Connect to stripe

✅ Make sure you can see the donation form after the connection
- Edit the amount and make sure it works as expected
- Go to edit the original pattern, change the amount, and back

✅ Make sure the editor won't get stuck

- Go to https://developer.wordpress.com/docs/api/console/
- Request /sites/:site/posts/:post_id

❓ Make sure the response contains the post link instead of the pattern link

I'm not noticing anything different pre/post patch 🤔 
Screenshot 2024-08-21 at 3 35 44 PM

**Comment by arthur791004** [comment]
> ❓ Make sure the response contains the post link instead of the pattern link

I'm sorry if I wasn't clear. I mean the content of the response will have the `a` element with the `jetpack-donations-fallback-link` class after you save your post with the connected donations block. With this patch, the link should point to the post instead of the pattern.

**Comment by taipeicoder** [comment]
> > ❓ Make sure the response contains the post link instead of the pattern link
> 
> I'm sorry if I wasn't clear. I mean the content of the response will have the `a` element with the `jetpack-donations-fallback-link` class after you save your post with the connected donations block. With this patch, the link should point to the post instead of the pattern.

Thanks for the clarification! In that case, then it also LGTM:
Screenshot 2024-08-21 at 4 59 05 PM

**Review by fushar — COMMENTED** [review]
I managed to test up to this point:

- Go to the Site Editor to create your pattern with the donations block (without connecting to stripe)
- Go to create a new post
- Insert the pattern you just created
- ✅ Make sure the pattern is inserted correctly and the browser won't get stuck

I verified that the my browser froze without the patch.

I got stuck in connecting the Stripe account... but seeing @taipeicoder already tested that, I think this is good.

**Pull request merged**
