### PR TITLE
WP.com block editor: Set cross-site auth cookies without overriding wp_set_auth_cookies

### PR DESCRIPTION
**Pull request by mmtr**
## Changes proposed in this Pull Request:

Refactors the work done in #14349 so cross-site auth cookies are generated with filters rather than running a code directly at the time when the file is being included, we avoid using `is_active` before `plugins_loaded`.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Refactor an existing feature as suggested by @zinigor in p1579526624044800-slack-dotcom-manage.

#### Testing instructions:
* To test on both a HTTP and HTTPS site:
* See testing instructions in #14349

#### Proposed changelog entry for your changes:
* N/A

### CODE REVIEW

**Comment by jeherve** [comment]
Unit Tests appear to be failing for this branch.

**Comment by mmtr** [comment]
> Unit Tests appear to be failing for this branch.

They're passing now after last commit.

**Review by gwwar — APPROVED** [review]
Thanks @mmtr this tests well for me on a Jurassic Ninja site. I'll defer to @zinigor for any thoughts on code execution order.

Screen Shot 2020-01-20 at 1 39 18 PM
Screen Shot 2020-01-20 at 1 40 49 PM

**Review by zinigor — APPROVED** [review]
This has turned out amazingly well, thanks for refactoring the old approach!

**Pull request merged**
