### PR TITLE
Conversation/Dialogue: new enhancements round

### PR DESCRIPTION
**Pull request by retrofox**
This PR implements a few enhancements to the `Conversation` and `Dialogue` blocks:

* **Conversation: use row style for example.** https://github.com/Automattic/jetpack/commit/196a22670c6622bad86a11965b06110a652c8b58
This is a quick fix for 425-gh-Automattic/dotcom-manage

The idea is simply to switch the block style to `row` in the example. We can iterate with a better solution soon.

* **Dialogue: remove focusing always the block content.** https://github.com/Automattic/jetpack/commit/f2627e0e450c1df31f312b705137ffbd1ec152e0

I've removed this improvement because I considered it not necessary. Basically, the idea was to make focus always on the block content when the block was selected, independently of the component/area where the event happened.
I think it's better to leave the choice to the user. If they want to make focus on the content, simply need to select it :-)

* **Dialogue: improve selector getting the previous block** https://github.com/Automattic/jetpack/commit/a8522a444e29512998e07575f93b192c031d7e01
The app tries to select the previous dialogue block to pick up the timestamp and the _next_ participant slug. I've added an additional condition which checks the `jetpack/dialogue` block name. 

* **Dialogue: update participant slug when removed** https://github.com/Automattic/jetpack/commit/0f9ebbbfbd672daf5f8582993fafbfe76a23d144
This commit updates the participant slug of the Dialogue block when its current one is removed from the `Conversation`. The new value will be the first participant slug of the participant's list.

before | after
-----|------
Screen Shot 2021-01-25 at 12 50 55 PM | Screen Shot 2021-01-25 at 12 51 48 PM

* Conversation: memoize bridge object https://github.com/Automattic/jetpack/commit/336bd15845ed587f8f21d7933f01dc6d84cd15fd
This commit memorize the object passed through the context from the `Conversation` Block to the `Dialogue` block.

Fixes #

#### Changes proposed in this Pull Request:

* Conversation/Dialogue: new enhancements round

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Take a look at the changes list below, and check it works as expected. Basically and beyond the visual changes, you should check the app doesn't break.

#### Proposed changelog entry for your changes:

n/a

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
Looks good 👍 I see the Row style in the block example:
Screen Shot 2021-01-25 at 11 10 25 AM
I was also able to remove a participant and see the name replaced. Adding and focusing Dialogue blocks works as expected.

**Review by jeherve — APPROVED** [review]
This tests well for me! 🚢

**Comment by jeherve** [comment]
I'll merge this for now so we can ship it in 9.4. I'll let you handle its WordPress.com counterpart.

**Comment by retrofox** [comment]
> I'll merge this for now so we can ship it in 9.4. I'll let you handle its WordPress.com counterpart.

👍 Shipping patch

**Comment by retrofox** [comment]
r219981-wpcom

**Pull request merged**
