### PR TITLE
Protect: Integrate Brute Force Protection

### PR DESCRIPTION
**Pull request by nateweller**
This is the primary project branch for integrating Brute Force Protection into the Jetpack Protect plugin.

## Proposed changes:

See the project milestone for a list of all PRs that have been reviewed and merged into this project branch: https://github.com/Automattic/jetpack/milestone/304?closed=1

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

peb6dq-oP-p2

## Does this pull request change what data or activity we track or use?

Yes. New tracks events are added - see https://github.com/Automattic/jetpack/pull/29548.

## Testing instructions:

* Review each merged PR from [the milestone](https://github.com/Automattic/jetpack/milestone/304?closed=1) and verify it has been approved by the appropriate team.
* Test the Brute Force Protection feature via the Protect plugin. See peb6dq-QV-p2 for detailed testing instructions.

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]
Rubber-stamp approval based on every contributing PR to this branch has already been reviewed. I'll manually test in about ~30 minutes.

**Comment by kraftbj** [comment]
Not blocking: This is weird. Installed Protect + BP, works fine. Add on Jetpack, which installs without prompting an user connection. Go to change the BP settings, which are not available:
2023-03-27 at 3 56 PM

Otherwise, the feature works well. Tried it with stable Jetpack to try to conflict it, but it worked well. 🚢

**Review by kraftbj — APPROVED** [review]
Approved after testing.

**Comment by nateweller** [comment]
Thanks @kraftbj! I will click the big green button :+1:

> Not blocking: This is weird. Installed Protect + BP, works fine. Add on Jetpack, which installs without prompting an user connection. Go to change the BP settings, which are not available

This PR includes a change where we remove the requirement for a user connection to use brute force protection, so this case would exist when they have the latest Jetpack Protect, and an outdated Jetpack version.

**Pull request merged**
