### PR TITLE
Contact Form: Allow changing required field string

### LINKED ISSUE #27657: JP Form Block - Make "field required" label editable, and update inspector sidebar text
We want to give users more flexibility about the "field required" label, like using a common " * " only, or translating the label.

If the field would be editable, similar to the normal field label, this would give users full control.

The required label will keep a different font-color (as currently the case) to signal the special purpose.

(Edge case: A user could delete the label, while the required functionality would be still active)

In the inspector sidebar, we will add a note below the toggle element to make users aware of this new edit functionality.

image

image

image

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27657

#### Changes proposed in this Pull Request:
* Allows changing required field string. More context on #27657

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a post and add a Form block
* Make form fields required and check if the "(required)" text can be changed
* Save the changes and check if they are applied to the live view

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Looking great João! 👍 

The only thing I noticed, if the user does delete the required label, it currently shows "required" in the published view, instead no label.

**Comment by jcheringer** [comment]
Thanks for giving it a spin, @digitalwaveride.
It should be working the way you mentioned now.

**Review by digitalwaveride — APPROVED** [review]
Great João!
Worked for me as expected!

image

**Review by sdixon194 — APPROVED** [review]
Nice, this works well for me 👍

**Pull request merged**
