### PR TITLE
Updated PHPCS: AMP, Tests, etc

### PR DESCRIPTION
**Pull request by kraftbj**
After #17406, updated the "requiredlist" files to match new PHPCS rules for packages and the debugger.

#### Changes proposed in this Pull Request:
* PHPCS

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
n/a

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by kraftbj** [comment]
After 9.1 branches off and #17406 merges, we need to update base branch to `master`, then this can be merged.

**Comment by anomiex** [comment]
> After 9.1 branches off and #17406 merges, we need to update base branch to `master`, then this can be merged.

Once #17406 merges and its branch is deleted, Github will automatically set the base branch to master (or whatever we're calling it by then).

**Review by anomiex — APPROVED** [review]
Looks sane to me.

**Review by anomiex — APPROVED** [review]

**Review by anomiex — APPROVED** [review]

**Comment by kraftbj** [comment]
r216014-wpcom

**Pull request merged**
