### PR TITLE
Layout: Support `start/end` prop in `Col` component

### PR DESCRIPTION
**Pull request by renatoagds**
For some of our layouts we need to start the column, not after the previous one, but some columns after, which makes it necessary to control where the column start or ends..

Example:

```es6
<Col lg={{ start: 6, end: 9 }}>
```

#### Changes proposed in this Pull Request:

* Move `Container` and `Col` styles to be based on SASS and share key values.
* Open a new option called `start/end` in `Col`.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

_First_

* Start Storybook.
* Navigate to `Components/Layout/Default` story.
* Check usage and do some tests.

_Second_

* Start `Protect | Backup | Social` plugins.
* Navigate to their admin pages and `My Jetpack` page.
* Everything should be the same.

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
> Move layout structure out of grid system to flexbox, since is not possible to create offset on grid only with CSS.

This doesn't sound very well at all. Still reviewing...

**Comment by renatoagds** [comment]
> I've just created a https://github.com/Automattic/jetpack/pull/24507 that implements offset by using grid.

@retrofox It's not working. If you take a look you're doing an offset of `6` and it just pushes the column `2` columns ahead and not `6`.

**Comment by retrofox** [comment]
> > I've just created a #24507 that implements offset by using grid.
> 
> @retrofox It's not working. If you take a look you're doing an offset of `6` in the second one, and it just pushes the column `2` columns ahead and not `6`. The same thing with the first one, you're doing an offset of `2` and it just pushes `1` column ahead.

ic. I though that what I wanted was an _absolute offset_, relative to the first column of the layout.

**Review by retrofox — APPROVED** [review]
LGTM. 🚀

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D81338-code, and deploy it.

r246430-wpcom

**Comment by pablinos** [comment]
> Most libraries (including Gutenberg - https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/grid/utils.js#L1-L13 ) implement it using Flexbox and not Grid

I don't know about the capabilities of the two layout systems, but that is much more likely to be historical. Gutenberg was developed with Flexbox, and moving to using Grid was tricky. It also wasn't as widely supported as it is now.

**Comment by retrofox** [comment]
> I don't know about the capabilities of the two layout systems, but that is much more likely to be historical. Gutenberg was developed with Flexbox, and moving to using Grid was tricky. It also wasn't as widely supported as it is now.

so you think that if they could start from scratch, probably they could choose the grid?

**Comment by pablinos** [comment]
> so you think that if they could start from scratch, probably they could choose the grid?

I don't know, but I remember having a discussion about whether we could use grid for layout in the editor, and at the time it wasn't supported, but there were instances where it would have been useful.

It's probably fine to have a mixture of flexbox and grid though. It's a shame that this moves towards sass and away from native CSS though. I suppose it highlights where CSS needs to catch up.

**Pull request merged**
