### PR TITLE
Fix export bug: missing data/columns (A sort of Revert of  #28678)

### LINKED ISSUE #29429: Export assigns data to wrong row when fields reordered
### Impacted plugin

Jetpack

### Quick summary

If you reorder the fields in a form, it messes up the export process, and data will be assigned to the wrong row in the CSV, and be missing from the correct row. This started in `8.0`

Possibly caused by #28678 and/or #28425, cc @CGastrell 

xref https://wordpress.slack.com/archives/C08M59V3P/p1677927125878589

### Steps to reproduce

1. Install Jetpack `11.7.1`
1. Create a contact form
1. Add two text fields; one named `text 1` and the other named `text 2`
1. Submit the form with values in both of those fields
1. Edit the form and swap the order of the two fields
1. Submit the form again
1. Export a CSV and open it. There'll be two entries for each field; e.g. `9_text1`, `9_text2`, `10_text2`, and `10_text1`, and  the data will be in the correct fields.
1. Update to Jetpack `11.8`
1. Export the CSV again and open it. There will only be a single `text1` field and a single `text2`, and there won't be any data in them.

In other situations, the data may show up, but in the wrong row. For a real-world example, check the shadow site for https://barcelona.wordcamp.org/2023/. Filter to the `llamada-a-ponentes` source, and look at the `Web` field for post ID `2604`. When exported, that value shows up in the row for a different entry.

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by CGastrell**
A bug was found when exporting form responses. The bug was introduced on #28678 and/or #28425 in the spirit of making column names look better by removing the order prefix. This led to wrong data merging upon the export process.

Fixes #29429

## Proposed changes:
This PR rolls back the rename/cleanup of field names (columns) to leave them as they were before the mentioned PRs. This doesn't mean we're completely reverting those changes, as all the other improvements remain.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Follow instructions on #29429

Exported data should now reflect the collected data more faithfully, even if that means that the same 2 fields are treated as different ones after inverting their order. This has always behaved that way and we plan to improve it on further iterations.

### CODE REVIEW

**Comment by oskosk** [comment]
Pushed [abe9896](https://github.com/Automattic/jetpack/pull/29448/commits/abe989654da789542ec639266b633a88b28075bc) with a rebase, [5623af5](https://github.com/Automattic/jetpack/pull/29448/commits/5623af5d7fb296cc38724babc6086d613ba282fd) with a changelog entry for Jetpack, and [2409443](https://github.com/Automattic/jetpack/pull/29448/commits/2409443b7b6093967bb959c7b602533b095f2f7f) with versions bump

**Comment by oskosk** [comment]
Tests need to be updated 

image

**Comment by oskosk** [comment]
Pushed 3d80139a5fee4d6f6ad442a955020b4add680eb3 with update to tests in package and module

**Review by oskosk — APPROVED** [review]
Tests well with instructions from https://github.com/Automattic/jetpack/issues/29429

CSV export looks like this

image

**Comment by sdixon194** [comment]
This has been cherry picked to the release branch and a special package v0.6.0.2 has been cut to be included in 11.9.1

**Pull request merged**
