### PR TITLE
Sync: blacklist `idx_page` post type

### PR DESCRIPTION
**Pull request by lezama**
Blacklist `idx_page` post type from being sync.

### CODE REVIEW

**Comment by enejb** [comment]
:shipit:

**Comment by enejb** [comment]
Plugin in questions: That use the post type. 
https://wordpress.org/plugins/idx-broker-platinum/
https://en-ca.wordpress.org/plugins/dsidxpress/

**Comment by lezama** [comment]
@zinigor can we put this one into 4.4?

**Comment by jeherve** [comment]
We'll also need to edit the changelog accordingly.

**Comment by zinigor** [comment]
Ported to `branch-4.4` in b1ada38.

**Pull request merged**
