### PR TITLE
AI Assistant: do not extend blocks with the AI Assistant feature

### PR DESCRIPTION
**Pull request by retrofox**
Fixes #

## Proposed changes:

* AI Assistant:; do not extend blocks with the AI Assistant feature

### Other information:

- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor
* Add a few paragraphs 
* Ensure AI Assistant is available
* Select more than one paragraph block
* Confirm the block sidebar doesn't show the `AI Assistant` panel

before | after
-------|-------
image| image

### CODE REVIEW

**Review by anomiex — APPROVED** [review]
Code is a bit ugly, but it works and you were wanting this in 12.2 post-deadline so cleaning it up in a followup seems ok to me.

**Comment by anomiex** [comment]
Cherry-picked in 80a4de9545a7ab0b56e40f4088973ead7566e30e

**Comment by retrofox** [comment]
> Code is a bit ugly, but it works and you were wanting this in 12.2 post-deadline so cleaning it up in a followup seems ok to me.

Why do you think it's ugly? the comment with the `@todo` part? Agree, but it's part of the development process.
Probably the feature it's going to be enabled soon, so maybe it's better to keep the comment.

**Comment by anomiex** [comment]
Yeah, exactly. We don't normally like to keep commented-out code around, sometimes the linter will even complain about it. But I know you're planning on revisiting it soon so I didn't think it was worth holding up the merge over, especially given the time constraints.

**Pull request merged**
