### PR TITLE
Create Video Widget problem

### PR DESCRIPTION
**Pull request by CraftYada**
Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

### CODE REVIEW

**Comment by CraftYada** [comment]
Video is hosted on vimeo for my actor website
https://www.chrisrogerstheactor.com/ 

It plays fine on tablet, but on desktop, there is not video, only audio. Any ideas? Thanx.

**Comment by zinigor** [comment]
Thank you for reporting the issue!

I can not reproduce the problem, though. Have tried browsing the site, played a couple of videos in the sidebar and on the Reels page, sound and video seem to be working fine. If it's not working for you, I'd suggest trying on a different device to see if the problem is your site, and not the device you're using.

Plus, we don't control what Vimeo uses to play videos, so it's better to contact Vimeo support if you can't see any video output.

And last, thank you for opening a PR, but if you need to report a problem in Jetpack, all you need is to create an issue. You don't even need to fork Jetpack for that.

Thanks, hope this helps!

**Comment by CraftYada** [comment]
Thanx for looking into this. i'm new to Github.

I'm glad it is playing correctly on your end. It didn't play for WPEngine
Customer Rep either. Maybe it is my setup?
MacOS X 10.12.6
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

Thanx.

**Comment by oskosk** [comment]
Could reproduce. The issue is being tracked in #8215

**Comment by oskosk** [comment]
@CraftYada this issue has been addressed and you'll be able to update to Jetpack 5.5.1 in a few hours.

**Comment by CraftYada** [comment]
My solution was to use the Text widget and post in vimeo url.

Thanx for your help. Have a great day.

**Pull request closed without merging**
