### PR TITLE
Filter post content in Open Graph meta tags

### PR DESCRIPTION
**Pull request by stacimc**
Fixes https://github.com/Automattic/wp-calypso/issues/46928

#### Changes proposed in this Pull Request:

* A short excerpt of post content is added to the `og:description` Open Graph meta tag. Unless an excerpt is supplied by the user, this will be a truncated section of the post body with some processing to remove shortcodes/tags/etc. This PR applies `the_content` filter to the excerpt in order to prevent premium content from being exposed through the meta tag.

#### Testing instructions:

Test setup:
* Create a new post and insert a Premium Content block at the top of the post.
* View the post on the frontend and open the inspector. Search for the `og:description` tag.

Test cases:
* When viewing the post in an incognito window, verify that the description tag includes only the LoggedOutView text from the Premium Content block
Screen Shot 2021-02-01 at 10 13 42 AM

* When viewing as an admin, the subscriber content is visible in the tag
Screen Shot 2021-02-01 at 10 14 07 AM

* When viewing as a subscriber, the subscriber content is visible in the tag (same as above)

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
The tests appear to be failing right now.

Overall, I believe we had opted not to filter that content with `the_content` until now to avoid having extra content prepended to the post content by other plugins (think ads or special content added to the beginning or end of all posts by a plugin).

**Comment by andrewserong** [comment]
@stacimc if we can't use `the_content` filter, I wonder if we could call [`do_blocks` directly](https://github.com/wordpress/wordpress/blob/eeb4d75c573b6cbc520bef9c71b4fa917f2d8a37/wp-includes/blocks.php#L752). Looks like that should call the block's render method, but we'd avoid accidentally calling other functions registered against the `the_content` filter?

**Comment by stacimc** [comment]
> Overall, I believe we had opted not to filter that content with the_content until now to avoid having extra content prepended to the post content by other plugins

Makes sense, +1!

> if we can't use the_content filter, I wonder if we could call do_blocks directly

I think that's exactly what we need, thanks.

**Review by andrewserong — APPROVED** [review]
This is working nicely for me now using the `do_blocks` call. Tested in the equivalent place in wpcom 👍

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Pull request merged**
