### PR TITLE
Provide smaller images in the Carousel when the full-size is very large

### PR DESCRIPTION
**Pull request by kraftbj**
See #3791.
Needs testing.

Original patch by Joseph Scott via https://github.com/Automattic/jetpack/issues/3791#issuecomment-219463561

### CODE REVIEW

**Comment by ChrisBegley** [comment]
This works great! I just tested it on my Retina 4K iMac which used to load in full sized images in Carousel. Now it's loading in just the right size based on how much room the image takes up on screen.

The `devicepx` script isn't loading in Retina versions for the entire gallery though. It only adds a Retina version for the 1st, 2nd, and very last image. Basically the 3 images you see on screen when you click on an image to open a gallery.

**Comment by josephscott** [comment]
Good catch @ChrisBegley - I'm able to reproduce this.  I'm not sure yet why devicepx isn't applying the `zoom=X` to the additional images, they don't have any of the triggers that would cause them to be skipped.  Need to run more tests.

**Comment by ChrisBegley** [comment]
Thanks. And in case it wasn't clear, that's an issue that's been around for a while. I don't think it's related to the change here.

**Comment by josephscott** [comment]
Good to know.

**Comment by josephscott** [comment]
If this an existing issue, which appears to be the case based on https://github.com/Automattic/jetpack/issues/975, then I think we shouldn't block on that for this change.  Lets go ahead and get this out to improve the situation with large images.

**Comment by kraftbj** [comment]
Agreed. Let's get this out and tackle 975 separately (though we should get to it sooner rather than later given it's been around for awhile :-/)

**Comment by samhotchkiss** [comment]
This looks good, however, I think it belongs in 4.1, as we are changing front-end output

**Comment by josephscott** [comment]
@samhotchkiss this is related to #3748 - different component, same problem.  Both of these together aim to stop having clients download giant images by default.

**Comment by jeherve** [comment]
This seems to work for me. Merging.

**Pull request merged**
