### PR TITLE
Add blogroll item block

### PR DESCRIPTION
**Pull request by heavyweight**
Add blogroll item block.
This will later be used in the blogroll to show the recommendations.

This PR only provides the scaffolding.  Block updates will be addressed in later PRs.

Fixes #
https://github.com/Automattic/wp-calypso/issues/80909

## Proposed changes:
* Add blogroll item block

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
- Apply this patch:
```
diff --git a/projects/plugins/jetpack/extensions/blocks/blogroll/edit.js b/projects/plugins/jetpack/extensions/blocks/blogroll/edit.js
index aa4901871c..5c0a55deed 100644
--- a/projects/plugins/jetpack/extensions/blocks/blogroll/edit.js
+++ b/projects/plugins/jetpack/extensions/blocks/blogroll/edit.js
@@ -1,4 +1,4 @@
-import { BlockIcon, InspectorControls, useBlockProps } from '@wordpress/block-editor';
+import { BlockIcon, InspectorControls, useBlockProps, InnerBlocks } from '@wordpress/block-editor';
 import {
 	Button,
 	CheckboxControl,
@@ -56,7 +56,10 @@ export function BlogRollEdit( { className, attributes, setAttributes, isSelected
 	 *
 	 * @returns {object} The UI displayed when user edits this block.
 	 */
-
+		// Default template is single WhatsApp block until we offer
+		// more services
+	const DEFAULT_TEMPLATE = [ [ 'jetpack/blogroll-item', {} ] ];
+	const ALLOWED_BLOCKS = [ 'jetpack/blogroll-item' ];
 	return (
 		<div { ...useBlockProps() } className={ className }>
 			{ showPlaceholder && (
@@ -92,6 +95,8 @@ export function BlogRollEdit( { className, attributes, setAttributes, isSelected
 				/>
 			) }
 
+			<InnerBlocks template={ DEFAULT_TEMPLATE } allowedBlocks={ ALLOWED_BLOCKS } />
+
 			<InspectorControls>
 				<PanelBody title={ __( 'Settings', 'jetpack' ) }>
 					<ToggleControl

```
- Add the blogroll block to a post
- Using the quick appender ensure that blogroll items can be added
Screenshot 2023-08-31 at 15 07 57

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
In blocks that are only meant to be used with a specific parent, we've opted to place them inside the directory of that parent block in the past. The WhatsApp block is a good example, in `projects/plugins/jetpack/extensions/blocks/send-a-message/whatsapp-button/`.

What would you think about doing something similar for this new block?

**Comment by heavyweight** [comment]
> In blocks that are only meant to be used with a specific parent, we've opted to place them inside the directory of that parent block in the past. The WhatsApp block is a good example, in `projects/plugins/jetpack/extensions/blocks/send-a-message/whatsapp-button/`.
> 
> What would you think about doing something similar for this new block?

Thanks for the feedback.

I wanted to do that but because of this part of [the readme](https://github.com/Automattic/jetpack/blob/695768a21b1341684a4da54fa4abc39093cd7ed8/projects/plugins/jetpack/extensions/README.md#L51-L50) changed my mind
```
If your block depends on another block, place them all in extensions folder:

.
└── blocks/
	├── block-name/
	└── sub-blockname/

```

I will revert according to the recommendation.

**Comment by jeherve** [comment]
> this part of [the readme](https://github.com/Automattic/jetpack/blob/695768a21b1341684a4da54fa4abc39093cd7ed8/projects/plugins/jetpack/extensions/README.md#L51-L50) changed my mind

That's a good point! Maybe we should update those docs to follow our current practices!

**Comment by heavyweight** [comment]
> > this part of [the readme](https://github.com/Automattic/jetpack/blob/695768a21b1341684a4da54fa4abc39093cd7ed8/projects/plugins/jetpack/extensions/README.md#L51-L50) changed my mind
> 
> That's a good point! Maybe we should update those docs to follow our current practices!

I can do it once I get back on this

**Comment by heavyweight** [comment]
@jeherve I just applied the feedback.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
