### PR TITLE
Upgraded node-sass in order to make Jetpack run under Node 6.

### PR DESCRIPTION
**Pull request by zinigor**
This PR should be used together with [the related dops-components PR](https://github.com/Automattic/dops-components/pull/26) that would enable us to use Node 6.

### CODE REVIEW

**Comment by richardmuscat** [comment]
Is this necessary for shipping 4.3?

**Comment by zinigor** [comment]
No, it's not necessary to ship 4.3.

**Comment by richardmuscat** [comment]
Moving to 4.3.1 then

**Comment by dereksmart** [comment]
I've rebased this branch, but I'm getting build errors.  

reproduce by: 
- `npm run distclean`
- checkout to this branch 
- `npm run build`

**Comment by eliorivero** [comment]
@zinigor after doing:

```
npm run distclean
npm run clean
npm run build
```
I get
```
Message:
    scss/molecules/_nav-horizontal.scss
Error: ".nav-horizontal" failed to @extend "%clear-fix".
       The selector "%clear-fix" was not found.
       Use "@extend %clear-fix !optional" if the extend should be able to fail.
        on line 6 of scss/molecules/_nav-horizontal.scss
>>      @extend %clear-fix;
```
that error belongs to a file in Jetpack `jetpack/scss/molecules/_nav-horizontal.scss`. The line
```scss
@extend %clearfix;
```
can be replaced by 
```
&:after {
	content: ".";
	display: block;
	height: 0;
	clear: both;
	visibility: hidden;
}
```
and the issue is gone.
However, there's another issue:
```
Module build failed: 
                &.tip-#{$side} .tip-arrow,
 ^
      Undefined variable: "$cross-side".
      in /Users/aldion/Sites/automattic/wp-content/plugins/jetpack/node_modules/@automattic/dops-components/client/components/popover/style.scss (line 66, column 3)
Details:
    details: Error: 
                &.tip-#{$side} .tip-arrow,
 ^
      Undefined variable: "$cross-side".
```
the error is in `jetpack/node_modules/@automattic/dops-components/client/components/popover/style.scss`, due to this conditional structure:
```scss
@mixin tip-arrow( $side ) {
		@if $side == "top" {
			$opposite-side: "bottom";
			$cross-side: "left";
			$cross-opposite-side: "right";
		} @else if $side == "bottom" {
			$opposite-side: "top";
			$cross-side: "left";
			$cross-opposite-side: "right";
		} @else if $side == "left" {
			$opposite-side: "right";
			$cross-side: "top";
			$cross-opposite-side: "bottom";
		} @else if $side == "right" {
			$opposite-side: "left";
			$cross-side: "top";
			$cross-opposite-side: "bottom";
		}
```
all branches are `if` and `else if` there's nothing for a case when it's not defined.

I've added 
```
 @else {
	$opposite-side: "";
	$cross-side: "";
	$cross-opposite-side: "";
}
```
just so it has a fallback.

I've added these two in a commit. Please check it and either accept it or reject it or edit it.

**Comment by zinigor** [comment]
Thanks Elio! I have added one small change to the dops-components PR, and now it works! Let's get it in and all switch to Node 6 before Calypso moves to Node 7 :)

**Comment by dereksmart** [comment]
Confirmed this is building fine with https://github.com/Automattic/dops-components/pull/62

Let's update the readme to reflect Node 6 is 👌  and merge!

**Comment by oskosk** [comment]
@zinigor I've added a commit to this PR updating `readme.md` mentions about Node versions.

**Pull request merged**
