### PR TITLE
Publicize: avoid notices as embeds are added to a post.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

﻿When one adds an embed to a post, it does not immediately get all its attributes, as the embed needs to be fully built first.
Until we have all the info, let's avoid notices.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* N/A

#### Testing instructions:

* Start from a site that's connected to WordPress.com, with the Publicize module on and a connected Twitter account.
* Go to Posts > Add New
* Add some content.
* Paste in a YouTube video.
* Watch some notices in your logs.
* Apply this branch.
* Repeat the operation.
* No more notices.

### CODE REVIEW

**Comment by sdixon194** [comment]
Just wanna make sure I'm testing this one correctly, but I wasn't able to reproduce the errors on a JN site running latest stable (publicize and twitter account connected). 

[Gif of my workflow here](https://d.pr/i/9zErHu).

**Comment by samiff** [comment]
@jeherve Could you clarify which "notices" we are looking for here (`Watch some notices in your logs.`)? The testing instructions mentioned pasting a YT video, but seems like the touched code deals with Twitter embeds?

**Comment by jeherve** [comment]
> Could you clarify which "notices" we are looking for here 

That would be your site's error logs. 

> The testing instructions mentioned pasting a YT video, but seems like the touched code deals with Twitter embeds?

Yes, the notices will happen from just about any embed block, as it takes a second for each embed block to get a provider name.

Here is a quick video of how I could reproduce on a fresh JN site:

https://videopress.com/v/clk74w5U

**Comment by sdixon194** [comment]
> Here is a quick video of how I could reproduce on a fresh JN site:

This helped, but boy was there a very specific set of steps I had to follow to reproduce 😅 

- Start a new post
- Add enough text to create multiple tweets
- Create a new line where I'd paste the Youtube video.
- Switch from Single Tweet to Twitter Thread
- Paste video on new line.
- See error

If I didn't do any one of those steps, I wouldn't get the error. Like if I switch to Twitter Thread before adding any content, no errors were logged. If I added a new line and then pasted an embed after switching to Twitter Thread, no errors were logged. It would also only do it the first time - subsequent embeds wouldn't log more errors. 

In any case, the fix works for me :D

**Review by sdixon194 — APPROVED** [review]

**Comment by jeherve** [comment]
r223254-wpcom

**Pull request merged**
