### PR TITLE
My Jetpack: Add Anti-Spam Product detail card

### PR DESCRIPTION
**Pull request by retrofox**
On this PR:

* Fill data into the Anti_Spam class
* Add mock data
* Create Anti-Spam stories

Fixes #

#### Changes proposed in this Pull Request:

* My Jetpack: Add Anti-Spam Product detail card

#### Does this pull request change what data or activity we track or use?

No
#### Testing instructions:

**Storybook**

* Run storybook

```bash
cd ./jetpack/projects/js-packages/storybook
```

```bash
> pnpm install & pnpm storybook:dev
```

`http://localhost:50240/?path=/story/packages-my-jetpack-product-detail-card--jetpack-anti-spam-card`

image

_Shame note: in case you get the `Cannot read properties of undefined (reading 'map')` error there, please change the product story again and again. It should show, at some moment, the proper visualization._

### CODE REVIEW

**Comment by oskosk** [comment]
Some test is failing. Can we add the route to the interstitial here in this PR too ?

**Comment by oskosk** [comment]
I see there's the icon over the title 
image

**Comment by retrofox** [comment]
> I see there's the icon over the title

Which is correct. What I need to do is removing the image.

**Comment by retrofox** [comment]
> I see there's the icon over the title image

Where are you seeing this image? I haven't added the Interstitial page for the AntiSpam product but only the card.

**Pull request merged**
