### PR TITLE
PHPBrew: Activate the hash variant in our 5.2 test environment

### PR DESCRIPTION
**Pull request by jblz**
While working on #9561, I'm getting an error in the 5.2 environment:
`Fatal error: Call to undefined function hash()`

According to the [PHP Docs](http://php.net/manual/en/hash.installation.php):

>  As of PHP 5.1.2, the Hash extension is bundled and compiled into PHP by default.
> It may be explicitly disabled by using the --disable-hash switch to configure.

So, it seems safe to assume it's available for unit testing purposes.

I'll add a check to the other PR that the function exists so on the off chance someone's host has disabled `hash` support, it won't cause a fatal.

#### Changes proposed in this Pull Request:

* Enable the `hash` variant in the PHPBrew-built 5.2 test environment
* Add a compat test to make sure the function is defined

#### Testing instructions:

* Automated tests pass in all envs

### CODE REVIEW

**Comment by jblz** [comment]
@zinigor @notnownikki -- do either of you have any insight as to why this isn't working? I'm pretty new to phpbrew, but it seems like we should just have to enable the `hash` variant from [their docs](https://github.com/phpbrew/phpbrew#variants).

Any insights greatly appreciated!

**Comment by notnownikki** [comment]
I think this is using a cached build of PHP.

On https://travis-ci.org/Automattic/jetpack/jobs/382512825#L578 it says the PHP build it is using was built on May 17th. Because a build can take sometimes longer than 15 minutes, we cache what phpbrew builds, so the hash variant isn't activated here.

This is the line that checks if a cached version exists: https://github.com/Automattic/jetpack/blob/1fe58c2bb391d56f42e6190f5b92553145eb7446/tests/install-php-phpunit.sh#L46

You can either disable that check for now, or force a rebuild with `rm -rf $HOME/.phpbrew` before this step starts.

Just remember when you re-enable the cache check for merge, you'll need to clear the caches at https://travis-ci.org/Automattic/jetpack/caches so that master builds and caches PHP with the new variant.

**Comment by jblz** [comment]
> I think this is using a cached build of PHP.

That would explain why that check completed so quickly!

Thanks much for the pointers, @notnownikki. Will give it a go.

**Comment by jblz** [comment]
So, turns out, sha224 is not available in PHP 5.2, so I'm going to go ahead and close this and just use `md5` in #9561. Fun exercise, though!

**Pull request closed without merging**
