### PR TITLE
My Jetpack: Requires/Push to connection only if needed

### LINKED ISSUE #27608: My Jetpack: correct Activate link behavior when disconnected
When Jetpack is disconnected, the activate links are active, but just return an error:

Image

This happens with VideoPress and with Social

Steps to reproduce:
1- Launch a JN with a Jetpack product
2- with jetpack disconnected, go to My Jetpack
3- Click on activate on VideoPress or Social

### LINKED ISSUE #27611: My Jetpack: When disconnected, don't request a Jetpack connection to add CRM
Whenever a user does not have Jetpack connected, we are asking them to connect to Jetpack before letting them add CRM from My Jetpack. CRM does not require a Jetpack connection, so we don't need to ask the user to connect before adding CRM.

This is what we currently do from My Jetpack:
ezgif com-gif-maker

### LINKED ISSUE #27612: My Jetpack: when disconnected, check the possibility of triggering the connection from the upgrade button
Check if we can trigger the connection dialog from here:
image

Instead of triggering the connection request like we do now:
ezgif com-gif-maker (1)

### LINKED ISSUE #27695: My Jetpack: Update price endpoint to not require user connected
Make sure that we switch between endpoints when requiring prices, based on user connection.

### PR DESCRIPTION
**Pull request by renatoagds**
Closes #27608
Closes #27612 
Closes #27611 
Closes #27695

#### Changes proposed in this Pull Request:

* Push user to `connection` page only when activating and only if needed.
* Update `ProductDetailCard` to use `useProductCheckoutWorkflow`.
* Update `get_products_from_wpcom` to use endpoint based on user connection.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Fully Disconnected with Jetpack plugin

⚠️ Make sure that you're fully or user disconnected.

* Navigate to `My Jetpack`.
* You should be able to:
- * Add (install) a new product that doesn't require purchase, and be redirect to it (CRM, Akismet for ex.)
- * Purchase a new product, being requested to connect first (Backup, Search for ex.).
- * Activate a module, being moved to `connect` screen first.

#### Fully/User Disconnected with Standalone plugin

⚠️ Make sure that you're fully or user disconnected.

* Navigate to `My Jetpack`.
* You should be able to:
- * Add (install) a new product that doesn't require purchase, and be redirect to it (CRM, Akismet for ex.)
- * Purchase a new product, being requested to connect first (Backup, Search for ex.).

### CODE REVIEW

**Comment by nunyvega** [comment]
I'm getting this error in the console when opening My Jetpack
Screenshot 2022-12-01 at 11 25 36

**Comment by nunyvega** [comment]
Not sure if it's related to the changes that we made in this project, but the **Add Security** button does not work on this screen:

Screenshot 2022-12-01 at 11 58 47

**Comment by nunyvega** [comment]
I see that VideoPress asks for a connection instead of showing the plan's price and a "Start for free" option. We can think about adding something like what Search has in a follow-up PR:

Screenshot 2022-12-01 at 12 05 28

**Comment by nunyvega** [comment]
All the others products and cases that I tested worked as expected. Reviewing the code now

**Review by nunyvega — COMMENTED** [review]
Code changes LGTM

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by sdixon194** [comment]
Cherry picked and released new versions of My Jetpack 2.5.0.1 to all current release branches - Jetpack, Social, and Backup.

**Pull request merged**
