### PR TITLE
Slideshow Block: Display full width and images as such

### LINKED ISSUE #12178: Slideshow block: Full width and wide width display shows scaled down images
_Jump to most recent technical analysis from June 2022: https://github.com/Automattic/jetpack/issues/12178#issuecomment-1157025213_

#### Steps to reproduce
1. Activate a twenty nineteen child theme
2. Create a page/post
3. Add new Slideshow Block and add one or more large images
4. Set display mode to full width
5. Publish and view page

#### What I expected

I expected the images to extend to the edge of the browser window.

#### What happened instead

The images are displayed as a scaled down version surrounded by grey space.  

Note: This happens with wide width display as well.

#### Screenshot / Video

Annotation on 2019-3-4

Screen Shot 2019-04-25 at 6 25 08 AM

Screen Shot 2019-04-25 at 6 19 46 AM

Screen Shot 2019-04-25 at 6 20 49 AM

#### Other

#1984153-zen

### PR DESCRIPTION
**Pull request by obenland**
Fixes #12178

#### Changes proposed in this Pull Request:

* Adds CSS rule for full width slideshows to fill the width of the screen.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Activate a theme with support for full-width slideshows (Twenty Twenty-One)
* Create a page/post
* Add new Slideshow Block and add one or more large images
* Set display mode to full width
* Publish and view page/post

Before | After
----|----
Screen Shot 2021-02-19 at 12 55 33 PM | Screen Shot 2021-02-19 at 12 56 08 PM

#### Proposed changelog entry for your changes:

* Fixed a bug where full-width slideshow blocks didn't display images actually in full width.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
While it does expand the images nicely, it does create issues with portrait images, now cropped to the point that they may not show the important part of a picture:

**Before**

image

**After**
image

**Comment by obenland** [comment]
Hm, I'd probably consider that more a feature than a bug. 

What would you expect happen instead? Have only images be full width where the width is larger than the height?

@eduardozulian Is there customer feedback around portrait images that you're aware of?

**Comment by jeherve** [comment]
> What would you expect happen instead? Have only images be full width where the width is larger than the height?

Yes, that would be my expectation, but it may just be me :)

**Comment by eduardozulian** [comment]
@obenland not that I can recall but anecdotally I think they were happier by only seeing the block respect the actual full-width setting.

If we treat it like we treat the cover block (or like we did with background images on custom headers) and set the expectations that this will affect how the image is delivered, it feels more like a feature than a bug indeed.

cc @jordesign and @davipontesblog in case you have any extra feedback on this.

**Comment by obenland** [comment]
@jeherve How would you feel about trying this for now and see if we'll get user feedback about portrait images?

**Comment by jeherve** [comment]
> How would you feel about trying this for now and see if we'll get user feedback about portrait images?

We could try that. I'll tag this for design review so somebody else can weigh in on this.

**Comment by keoshi** [comment]
Hi, all! 👋 I tend to agree with Jeremy on this one because the slideshow is such a self-contained block, meaning there's no subsequent action to take on each image (unlike the gallery block, for instance, that allows you to expand each item).

In other words, there's no way for me to see a complete vertical image unless I right-click and open it on a new tab. That seems like a non-starter to me. It's fine for the items to take however much space there is available to them, but I believe a better way to do this would be:

- Limiting the width on horizontal pictures.
- Limiting the height on vertical pictures.
- In sum: limiting the size of a picture by its largest axis to the block's boundaries.

Right now, it's impossible to me to show a vertical picture in all its context. Also, notice how the preview differs so much from what's displayed in the block editor; the latter seems the right approach to me.

Block editor | Preview
--|--
image | image

_However_, I can also imagine certain people preferring the behavior that this PR suggests, but that could be provided by a “Crop images”/“Expand images”/“Cover the block” option in the Slideshow block, since that's effectively what would be happening. We have a precedent in the Gallery block, for example, that we could use to offer this extra flexibility:

image

Lastly, I would argue that the goal of this block is largely different from the cover block. One is supposed to highlight the photos/images, the other uses a single image as an illustrative backdrop, not to mention it allows you to change the focal point, define the height to include more or less of the picture, among other options.

**Comment by donalirl** [comment]
I had a customer who could use this feature. I gave a CSS fix that they were very happy with. Ref: #31066278-hc

**Comment by yansern** [comment]
A block settings mockup of giving user a choice by letting them pick what they prefer.

**Comment by jeherve** [comment]
I'll close this PR for now because of the lack of activity on this. We can always reopen in the future if needed, but it will need a rebase, so it may be easier to start a new PR at this point.

**Pull request closed without merging**
