### PR TITLE
Admin Menu: Account for top-level item capabilities

### LINKED ISSUE #17977: Admin Menu: Settings menu title missing for single site users
While testing a user who is editor in a single site and doesn't have other sites I noticed that Settings title (that contains "Sharing", "Polls") is missing!

**Steps to reproduce**
1. Apply blog-sticker `nav-unification` to sandbox
2. Invite a contributor who doesn't have other sites
3. Load `https://horizon.wordpress.com/stats/day/[domain]?flags=nav-unification` as the contributor

### PR DESCRIPTION
**Pull request by obenland**
Fixes #17977.

#### Changes proposed in this Pull Request:

* Adds a second try for top-level menu items when they have submenu items available.
* Adds unit tests to make sure that a top-level item exists when there are submenu items that the user has caps for.
* Adds unit tests to make sure that top-level and the first submenu item have the same menu slug.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Run unit tests and make sure there are no failures for the admin menu tests: `$phpunit --testsuite core-api`.

#### Proposed changelog entry for your changes:

* None needed. Feature not in use yet.

### CODE REVIEW

**Comment by obenland** [comment]
@cpapazoglou Might be easiest to test this by applying the phab diff to your sandbox and testing the wp.com scenario you encountered.

**Review by cpapazoglou — APPROVED** [review]
I can confirm that the issue is resolved


and related tests are passing with flying colors!

**Review by jeherve — APPROVED** [review]
Approving after a rebase to fix unrelated test issues.

**Comment by obenland** [comment]
r217991-wpcom

**Pull request merged**
