### PR TITLE
External Media: Fix image not attaching or being recognized as "used" in a post

### PR DESCRIPTION
**Pull request by ebinnion**
See #16425 

This is very similar to an issue that @kraftbj recently fixed in #16287 

#### Changes proposed in this Pull Request:

* Do not process images with Photon when inserting from external services like Pexels or Google Photos
* Properly attach the photo to the post when copying

#### Jetpack product discussion

This came from a request from Galactica via Slack.

#### Does this pull request change what data or activity we track or use?

No 

#### Testing instructions:

- Connect site
- Add post and insert an image from Pexels or Google Photos
- Go to Media library and select new image
- Ensure that image is properly attached to post

#### Proposed changelog entry for your changes:

* Fixes issue where images from Pexels or Google Photos weren't attached to posts

### CODE REVIEW

**Comment by jeherve** [comment]
> Fixes an issue that was reported on WP Tavern

I updated your PR description since the bug was also tracked here on GitHub. One more issue we can close! 🎉

**Comment by ebinnion** [comment]
Thank you for the feedback. I've added a test to the PR 💯 

The test was a bit interesting since I needed to figure out how to preempt the network request when downloading a file. I'm glad to answer questions you have and/or add comments.

**Comment by ebinnion** [comment]
Thank you for the testing. I had confused "used in" with "attached to". My original commit fixed the logic for determining which posts an image was used in. 

I've just pushed another change which fixes the logic for attaching an image to a post. This required some minor changes to the frontend and backend.

**Comment by ebinnion** [comment]
@Automattic/ajax  - Could I get some help/advice on testing this with WordPress.com?

**Comment by jeherve** [comment]
r211629-wpcom

**Pull request merged**
