### PR TITLE
VideoPress: start to migrate block from Jetpack to VideoPress package

### PR DESCRIPTION
**Pull request by retrofox**
This PR starts the migration process of the VideoPress (beta) block of the Jetpack plugin to the VideoPress package.
* VideoPress package contains the code that defines the VideoPress block
* VideoPress package API exposes the `register_videopress_block()` method to delegate the block registering process.
* VideoPress plugin registers the VideoPress block
* Jetpack does not register the new VideoPress block. Follow-up PR is coming up for this
* VideoPress v6 is still working on the Jetpack plugin. Cleaning in a follow-up PR.

Fixes #

#### Changes proposed in this Pull Request:

* VideoPress: start to migrate block from Jetpack to VideoPress package

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Compile / update / etc Jetpack products dependencies. Probably, we'd like to run...

```
jetpack build --all
```

* In your WordPress testing site, go to the plugins admin page
* Activate VideoPress plugin
* Go to Block Editor
* Create/edit a site post
* Create a new VideoPress block
* Pay attention to the blocks there:
  * VideoPress block is the block registered by the package
  * VideoPress (beta) is the block registered by the Jetpack plugin
image

Upload a video using the `VideoPress` block. Confirm it works as expected.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202561463041784

### CODE REVIEW

**Review by leogermani — DISMISSED** [review]
working well. lets do further adjustments in following PRs

**Comment by bindlegirl** [comment]
@retrofox Tests are failing for this PR. Do these tests need updating?

**Review by dhasilva — DISMISSED** [review]

**Review by leogermani — DISMISSED** [review]
Tested and also made sure that nothing changes when using only the Jetpack plugin. the old block still works

Re-ran Boost tests that had failed and it passes now

**Review by oskosk — APPROVED** [review]
Tests great! :shipit:

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D85380-code, and deploy it.

r250764-wpcom

**Pull request merged**
