### PR TITLE
Fix issue templates

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

Fixes issue `body[1]: options must not include the reserved word, 'None'.` introduced in https://github.com/Automattic/jetpack/pull/20821

More info at: https://gh-community.github.io/issue-template-feedback/structured/#body0-options-must-not-include-the-reserved-word-none

> This is fixed by removing "None" as an option. If you want a contributor to be able to indicate that they like none of those types of pies, you can additionally remove the required validation:

Instead, I've simply changed "None" to "Other" for now.

#### Jetpack product discussion

Internal: p1630349786015800-slack-CDLH4C1UZ

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Proofread, then merge & test issue templates are visible.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]

**Review by anomiex — APPROVED** [review]
Cool. Where did you see that error message?

**Comment by samiff** [comment]
> Cool. Where did you see that error message?

Screen Shot 2021-08-30 at 1 52 16 PM

If we want to keep this as a required field, it seems like "None / Other" would work, just not "None" alone.

**Comment by anomiex** [comment]
Ah, I see. Like at https://github.com/Automattic/jetpack/blob/270ba589/.github/ISSUE_TEMPLATE/bug-report.yml.

I had worked out the same thing, but by copying the file to another repo and "bisecting" the contents until I found that that one line was responsible. Your way was much easier! 😀

**Comment by jeherve** [comment]
Thanks for catching that!

**Pull request merged**
