### PR TITLE
Form Block: Add a few keywords to the 'Newsletter Sign-up' variation

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Changes proposed in this Pull Request:

Adds a few relevant keywords to the 'Newsletter Sign-up' block.

From p1672677709091099-slack-C04H9D4F552

## Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

N/A

## Testing instructions:

1. Enter `/subsc` into the block editor.
2. Verify the 'Newsletter Sign-up' block appears in available options.

image

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
It works well for me.

I should note that this change does not impact our own Subscribe block:

Screenshot 2023-01-06 at 16 16 50

**Comment by danielbachhuber** [comment]
> I should note that this change does not impact our own Subscribe block:

@jeherve Oh, what's the difference between the two blocks? Which one should I use for signups to WordPress.com email notifications?

**Comment by jeherve** [comment]
> @jeherve Oh, what's the difference between the two blocks? Which one should I use for signups to WordPress.com email notifications?

The one you're changing is a variation on the generic form block, powered by the old Contact Form feature (née Grunion). It isn't plugged to any delivery system, it "just" emails you the sign-ups and saves them in the Feedback CPT.

The Subscribe block lives here:
https://github.com/Automattic/jetpack/blob/e88dcaf15cf2004fe1813566b05fa733f25ce2fd/projects/plugins/jetpack/extensions/blocks/subscriptions/index.js#L23

The block is built on top of the Email Subscriptions feature you're most likely looking for. When signing up thrrough that form on a WordPress.com simple site or a self-hosted site where the Subscriptions module is active, you then get emails for each new post published on the site.

Does that make sense?

**Comment by danielbachhuber** [comment]
> Does that make sense?

@jeherve Your explanation makes sense — and makes me realize the feature is very confusing 🙃

I guess I needed the Subscribe block (not obvious) which isn't present for me because the Subscription module isn't enabled (also not obvious):

image

**Comment by jeherve** [comment]
> the feature is very confusing 🙃

It definitely is. We added this variation in #16808 as part of a partnership project ( pbtFPC-GX-p2 ). It made sense for that use-case, and we had talked about extending this so it made sense with other products ( p93VbO-gZ-p2#comment-682 ). Until that is done, we had opted to remove that variation on WordPress.com Simple to avoid too much confusion:
https://github.com/Automattic/jetpack/blob/bb79a18e4ef5128c3b60a32177ba6d4098a6b02a/projects/plugins/jetpack/extensions/blocks/contact-form/variations.js#L52

> I guess I needed the Subscribe block (not obvious) which isn't present for me because the Subscription module isn't enabled (also not obvious)

Yup, it is not enabled by default anymore when you first connect your site to WordPress.com, since #11631.

**Comment by danielbachhuber** [comment]
@jeherve Fascinating!

Given this new information, do you think my pull request still makes sense?

**Comment by danielbachhuber** [comment]
@jeherve Also, on this topic, what do you think about showing this UI element when subscriptions are disabled, with a CTA to enable?

image

I had no idea subscriptions were disabled on my site. It seems like this UI should indicate such too:

image

**Comment by jeherve** [comment]
> what do you think about showing this UI element when subscriptions are disabled, with a CTA to enable?

Yeah, I think that would be a nice improvement. It's something we had discussed in #14621

It would require a bit of refactoring since the block and the panel are currently entangled and gated:
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/extensions/blocks/subscriptions/editor.js#L5-L9
https://github.com/Automattic/jetpack/blob/5463f2e0284ca8a634f75deee22db0c1bf1de984/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L36-L38

But it for sure would help a lot of folks, so it would be worth the time investment imo.

> I had no idea subscriptions were disabled on my site. It seems like this UI should indicate such too:

I'm less familiar with the Calypso UI strategies, so I'm not sure what the best behavior would be here. In some places in Calypso, we do not display the UI at all when a module is disabled. In other places, we display a toggle to enable the module from there. Maybe we should do that here too.

**Comment by danielbachhuber** [comment]
> Yeah, I think that would be a nice improvement.

Cool, sounds good https://github.com/Automattic/jetpack/issues/28288

> I'm less familiar with the Calypso UI strategies, so I'm not sure what the best behavior would be here. In some places in Calypso, we do not display the UI at all when a module is disabled. In other places, we display a toggle to enable the module from there. Maybe we should do that here too.

I passed along the suggestion and it ended up here: https://github.com/Automattic/dotcom-forge/issues/1466

**Pull request merged**
