### PR TITLE
Carousel: reimplement without jQuery

### LINKED ISSUE #11191: Carousel: error thrown in `originalDimensions` function
#### Steps to reproduce the issue

1. Activate recommended features in Jetpack.
2. Create new post and add a 1) Tiled Gallery and 2) a Gallery block in Gutenberg.
3. Upload these [two](https://unsplash.com/photos/-SFhuMwFClk) [images](https://unsplash.com/photos/hDqLoCCGOdU). Add a long caption to the last one.
4. Publish post and click one of the images to display the carousel.

#### What I expected

- The clicked image to be displayed correctly in the carousel.

#### What happened instead

- Carousel came up empty (both the image, caption, exif data).
- Site is halted and clicks on the carousel don't work because of a JS error.
- Console shows this JS error:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at a.fn.init.originalDimensions (jetpack-carousel.min.js?ver=20190102:4)
    at a.fn.init.e.fn.jp_carousel (jetpack-carousel.min.js?ver=20190102:4)
```

image

Which seems to originate from the `originalDimensions` function:

https://github.com/Automattic/jetpack/blob/6189a00b72db562d5002b38ae87afce47c717591/modules/carousel/jetpack-carousel.js#L1067

**Screenshots**

gallery-carousel

### LINKED ISSUE #20036: Jetpack Carousel: Lightbox breaks with lazyload
#### Steps to reproduce the issue

1. Go to https://www.insposa.co.uk/bridal-fashion/wedding-dresses/our-10-favourite-wedding-dresses-from-the-meadow-collection-by-katya-katya-london/
2. Click on an image inside the gallery block slightly further down the page
3. Lightbox won't work due to JavaScript error

#### What I expected
Lightbox to work

#### What happened instead
Lightbox breaks due to lazy load code changing the image HTML output to perform the lazy load. I'm imagining Jetpack adds the orig-size attribute too late or via JS. 

Ultimately, trying to open the lightbox leads to this JavaScript error:

`Uncaught TypeError: Cannot read property 'split' of undefined`

This error happens at:

`.data("orig-size").split(",")`

There should be a check for that attribute first and a fallback to get the image width if it doesn't exist.

### PR DESCRIPTION
**Pull request by sgomes**
Fixes #20036 
Fixes #11191  

Reimplement Carousel without `jQuery`, using only IE11-compatible vanilla ES5.

This is a big PR, but given the nature of the change, it would have been difficult to split it up into smaller chunks. Just like `jQuery`, it's pretty much an all-or-nothing affair.

Comparing the old and new code may be difficult, since the diffs are pretty much useless when just about every line of code has changed. As such, I'd recommend focusing on thorough testing instead.

I took an extremely slow and painful iterative approach, where I converted and tested one thing at a time through a lot of throwaway code, never allowing the carousel to be broken for more than a few minutes. I may have missed some bugs, but the result should be pretty close to the original in terms of functionality.

As for intentional changes, note that I removed a few sliding animations, since they tend to be slow, were difficult to implement in a performant way, and were only used for relatively minor things that don't benefit greatly from animation (such as displaying the status of a comment after submission). Fade animations were kept, but reimplemented in a more performant way.

#### Changes proposed in this Pull Request:
* Reimplement Carousel without `jQuery`

#### Jetpack product discussion
For a high-level, somewhat outdated plan, see p1HpG7-bfN-p2.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
This code touches all of the carousel, so it's difficult to provide any testing instructions. Please use the carousel as much as possible, trying all the different functionality, and see if anything breaks.

Things to watch out for:
- Does anything break if you take actions (like moving between slides, or opening and closing the carousel) too quickly?
- Does comment loading work correctly?
- Does comment posting work correctly?
- Does it still work in IE 11?
- Does it work in other browsers?

### CODE REVIEW

**Comment by sdixon194** [comment]
Should be good to merge #19986 and then rebase here 👍

**Comment by sgomes** [comment]
Rebased on `master` after #19986 merge. Thank you, @sdixon194! 👍

**Comment by sdixon194** [comment]
Wow! Nicely done, I think that slow and steady approach really worked 🎉 I found two tiny things:

**Mouse Changes to Pointer**

When opening a gallery, I notice the mouse changes to a pointer everywhere on the gallery, including comments/description. Before this branch, it would only appear on buttons, like the left and right arrows.

**Images Slightly Smaller**

Small thing, but noticed that images are displayed a bit smaller now. Might be intentional and not a big deal unless we were going for 100% parity with the previous way of using the carousel.

You can [see in this gif](https://d.pr/i/uXUgqh) when I flip between this branch and a tab with the current stable version.

**Just Noting**

In both stable and this branch, I notice the gallery doesn't load if I have uBlock enabled in Chrome. I think this was something introduced a little while ago. Not sure if it's a big deal, but figured it was worth jotting down.

Thanks for all your work with this!

**Comment by sgomes** [comment]
Thank you for the thorough review, @sdixon194 !

I think I've addressed all your concerns below, but please let me know if there's anything else 👍 

> **Mouse Changes to Pointer**
> 
> When opening a gallery, I notice the mouse changes to a pointer everywhere on the gallery, including comments/description. Before this branch, it would only appear on buttons, like the left and right arrows.

Great catch! Looks like this was an unnecessary CSS rule that wasn't being used before, but started taking an effect when I switched away from `jQuery` `data` to real DOM data attributes. Removed in 1bd6481acb92f8da14bc31e966de6b307fa1bcf7.

> **Images Slightly Smaller**
> 
> Small thing, but noticed that images are displayed a bit smaller now. Might be intentional and not a big deal unless we were going for 100% parity with the previous way of using the carousel.
> 
> You can [see in this gif](https://d.pr/i/uXUgqh) when I flip between this branch and a tab with the current stable version.

This appears to be because of the changes in #19986, as far as I can tell. Moving the photo info up leaves slightly less room  for the image, which causes it to become smaller in some screen configurations. I think it's an acceptable tradeoff, but we can go back and figure out a different way of doing things if you think it's undesirable.

> **Just Noting**
> 
> In both stable and this branch, I notice the gallery doesn't load if I have uBlock enabled in Chrome. I think this was something introduced a little while ago. Not sure if it's a big deal, but figured it was worth jotting down.

Looks like this was due to a bug introduced in #19863. Should be fixed with 5806eedac31a0e7b127903d5b6786fff82c80a00. Great catch!

**Comment by sgomes** [comment]
Rebased on `master` again to please one of the PR checks.

**Comment by sgomes** [comment]
FYI: @jeherve prepared an independent fix for the JS issue when loading in #20027. It doesn't just happen when `uBlock` is enabled, but rather when nothing happens to add `wpcom` as a global to the window before the carousel runs.

Once that's merged, I'll rebase this PR on top of it.

**Comment by jeherve** [comment]
> FYI: @jeherve prepared an independent fix for the JS issue when loading in #20027. It doesn't just happen when `uBlock` is enabled, but rather when nothing happens to add `wpcom` as a global to the window before the carousel runs.
> 
> Once that's merged, I'll rebase this PR on top of it.

Ah, excellent, thank you! I'm still having problems when trying to reliably reproduce the issue, but the fix seems safe.

Somewhat related: as we move away from jQuery in this PR, should we also take the opportunity to fix this issue?
https://github.com/Automattic/jetpack/issues/11191#issuecomment-819764521

**Comment by sgomes** [comment]
> Somewhat related: as we move away from jQuery in this PR, should we also take the opportunity to fix this issue?
> [#11191 (comment)](https://github.com/Automattic/jetpack/issues/11191#issuecomment-819764521)

Sure thing, I can make that code a bit more bullet-proof 👍

**Comment by sgomes** [comment]
@jeherve : 0ba3f6a3bb6142857343afc7b432f9e735da0460 should do the trick; it now checks a few other attributes on the element, which I think we can assume to be present.

If not, please let me know and I'll figure out something else!

**Comment by sgomes** [comment]
Rebased on top of `master`, now that #20027 was merged.

**Comment by sdixon194** [comment]
This still works well for me now, but I wasn't able to reproduce the `split` issue again, so having some trouble testing that. @jeherve did you have a test site that was still kicking that error we could test with?

**Comment by jeherve** [comment]
> did you have a test site that was still kicking that error we could test with?

I don't I'm afraid. The problem got fixed with 9.8.1 on my sites that had the issue.

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 🚢

**Comment by sgomes** [comment]
Thank you for your reviews, @sdixon194 and @jeherve! 🙇 

Woohoo, let's get this show on the road! 😁

**Comment by sgomes** [comment]
r227141-wpcom

**Pull request merged**
