### PR TITLE
Add fix shorthand GitHub action workflow to fix incorrect Automattic shorthand

### PR DESCRIPTION
**Pull request by arunsathiya**
#### Changes proposed in this Pull Request:

- This PR introduces a new GitHub Action workflow task.
- This task automatically fixes common incorrect shorthand of Automattic support interactions. This is not an exhaustive list -- we can add more incorrect formats as they are spotted. This workflow runs only on new comments on issues and PRs. It does not affect issues that are being edited, thus allowing the comment author to edit again if needed.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

- This workflow is inspired by @jeherve's work here to automatically add a priority label to new issues: https://github.com/Automattic/jetpack/pull/24841
- More discussion with Quality Squad here: pciE2j-18N-p2 

#### Does this pull request change what data or activity we track or use?

I am not aware of one.

#### Testing instructions:

- The PR will have to be merged first.
- And then, comment on any issue or a PR with an incorrect Happychat or Zendesk shorthand format. Examples: 123-HC, hc-123, zd-123, ZD-123, zd-woothemes-123, ZD-woothemes-123, 123-zd, 123-ZD. 
- Notice that the workflow task automatically fixes that to the correct format: 123-hc and 123-zen.

#### Live examples

Examples can be seen on my fork: https://github.com/arunsathiya/jetpack/issues/3#issuecomment-1173148450

### CODE REVIEW

**Comment by arunsathiya** [comment]
To make this available on Calypso as well, should I just add `fixShorthand` task to this line on the Calypso repo?

https://github.com/Automattic/wp-calypso/blob/10d61548ea987e10125d4ecb28c6d360dfee0dbd/.github/workflows/gardening.yml#L43

**Review by jeherve — COMMENTED** [review]
Instead of fixing comments, what if we edited our internal script so it supports all those incorrect formats out of the box?

**Comment by arunsathiya** [comment]
Hmm, that's an option I hadn't considered! I'll leave this PR open for a bit, to see whether this workflow will be useful in other ways.

**Comment by arunsathiya** [comment]
Agree that's a better idea, @jeherve, thanks! I'll close this PR in favor of that approach. Also started a discussion internally: pcLjiI-QJ-p2

**Pull request closed without merging**
