### PR TITLE
Instant Search: Add a check for gzipped bundle size limit

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
* Adds a `size-limit` test for Jetpack Search's main bundle. The current limit is set to 48KB.

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
None.

#### Testing instructions:
* Run `yarn test-search`, ensure that it runs the new bundle size checker.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
That seems like a lot of new dependencies for this. What's the advantage of this approach compared to the current implementation, where the bundle cannot be created when it gets too big?

**Comment by jsnmoon** [comment]
> That seems like a lot of new dependencies for this. What's the advantage of this approach compared to the current implementation, where the bundle cannot be created when it gets too big?

The main reason is that Webpack only measures the minified bundle size instead of the minified & gzipped bundle size. The secondary reason is that it's difficult to set granular file size limits for individual assets, which we may look into implementing in the future (e.g. 48 KB for the entry bundle and 12 KB for async loaded chunks, hypothetically).

Eventually, we'd like to integrate [size-limit-action](https://github.com/andresz1/size-limit-action) for PRs tagged with Instant Search. This will enable automated comments making it easier for developers to measure the performance impact of their changes:

image
> Note that we currently have the Running Time metric disabled.

I also believe this tooling may be useful for front-end portions of our Gutenberg scripts.

**Review by jeherve — APPROVED** [review]

**Review by jeherve — CHANGES_REQUESTED** [review]
This is going to need a rebase I'm afraid.

**Review by jeherve — DISMISSED** [review]

**Comment by jsnmoon** [comment]
Rebased again to fix Travis :)

**Review by jeherve — APPROVED** [review]
Let's merge it quick while Travis is friendly :)

Do you think you could commit the WordPress.com counterpart as well? Since it makes quite a few changes to `yarn.lock`, if we wait too long to commit to WordPress.com it may cause some difficulties when committing other diffs that modify the file.

Thank you!

**Comment by jsnmoon** [comment]
@jeherve Will do!

**Comment by jsnmoon** [comment]
Deployed in r215708-wpcom.

**Comment by jeherve** [comment]
Thank you!

**Pull request merged**
