### PR TITLE
IDC: Complete notice styles

### LINKED ISSUE #5494: IDC: Finish notice design
In #5484, I took a pass at styling the "Safe Mode" notice, but didn't quite finish before we decided to merge.

This issue will track things that we need to address:

- [x] Remove protocols from URLs in text
- [ ] Decide whether to include all of dops styles just because we want the `.dops-button` class
- [x] Link all URLs to site
- [x] Update wording to match mock below
- [x] Tidy up mobile styles

    screen shot 2016-11-02 at 12 09 34 pm

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #5494

This PR should finalize the design for the notice. Here are screenshots:

### Step one
screen shot 2016-11-03 at 3 24 27 pm

screen shot 2016-11-03 at 3 24 47 pm

### Step two

screen shot 2016-11-03 at 3 24 37 pm

screen shot 2016-11-03 at 3 24 53 pm

cc @jeffgolenski and @rickybanister for design review.

To test:

- Checkout this branch
- Put your site into an IDC (We have a test plugin to help with this if you're having an issue. Please ping)
- Click "Fix Jetpack's connection" and land on second step
- Reload page
- Click dismiss and verify notice is dismissed

### CODE REVIEW

**Comment by roccotripaldi** [comment]
This looks great Eric! Why do the URLs in the notices need to be actual links though? Could they just be bolded, or something similar, to make them stand out?

**Comment by ebinnion** [comment]
That's something we could consider. I'm not sure that I have a preference either way ¯\_(ツ)_/¯.

**Comment by rickybanister** [comment]
The links seem unstyled—that blue seems like it's coming from core, not from the Calypso styles, can you confirm @jeffgolenski

**Comment by ebinnion** [comment]
You were right @rickybanister 😄 

I just pushed a commit that handles those colors.

screen shot 2016-11-04 at 11 26 13 am

**Comment by rickybanister** [comment]
I'm always right! That looks great @ebinnion!

**Comment by dereksmart** [comment]
Looks great with the bottom aligned buttons :) 

:shipit:

**Comment by dereksmart** [comment]
making as design review complete since ricky gave it 👍

**Pull request merged**
