### PR TITLE
Fix out-of-bounds submenus on the admin menu

### LINKED ISSUE #71198: [Bug]: Submenus are shown outside of screen - Nav Unification
### Quick summary

When you're on a wp-admin page (ie wp-admin/site-health.php) and hovering over a menu item that is close to the bottom of the screen, it gets positioned outside of the screen

image

If you try to access a menu item of that menu, at some point, it causes an endless flickering

https://user-images.githubusercontent.com/2484390/207607018-9eb23dae-b775-47be-b0e5-98a313ed6c42.mp4

### Steps to reproduce

- Visit wp-admin/site-health.php
- Adjust your screen to a size of a 13-14" Macbook
- Hover over Settings
- The menu item is positioned outside of the screen
- Further more a flickering happens if you leave your cursor at a certain point

### What you expected to happen

- The menu item should be positioned correctly, inside the window and with no need to scroll down to see it

### What actually happened

- The menu item is positioned outside of the screen, and you need to scroll down to access it

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

_No response_

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

After some digging, I found out that due to Nav Unification, the native WordPress `#wp-admin-bar-menu-toggle` is not added to the admin bar.

https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L941 relies on `#wp-admin-bar-menu-toggle` to be present (and hidden) in order to calculate the `margin-top` of the submenu.

As discussed in slack with @mmtr , this is caused because https://github.com/Automattic/jetpack/blob/fc10b4ff5e8e9b3d566618124502d2166b6b1e99/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js is missing this calculation

Quoting @mmtr conversation from Slack

> Nav Unification completely overrides the menu behavior provided by Core by performing a custom logic that it’s in  `modules/masterbar/admin-menu` in Jetpack.

> That includes the JS logic that handles things like opening submenus, positioning them in the right place, etc.

> The issue you found is a Nav Unification issue that should be addressed in `admin-menu.js` . I know that `admin-menu.js` was partially inspired by the `common.js` file but that doesn’t necessarily mean it should have the same code.

> So if the issue doesn’t happen in Core because `common.js` handles it, we should incorporate that into `admin-menu.js` but adapting it to the Nav Unification specifics (such as using the DOM elements rendered by the Nav Unification menu) 

> I think the `wp-calypso` repo is preferable for this one, since that’s where most of the Nav Unification issues are reported (remember to add the Nav Unification level).
you can leave it unassigned then, and it would be prioritized by the folks triaging issues

I've added this issue as a Blocker Priority, as it blocks @Automattic/somewherewarm from releasing peapX7-Um-p2#comment-1029

cc @manospsyx @xristos3490 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by xristos3490**
### Specification

This PR aims to fix the positioning of the submenus in the admin menu. It does that by injecting the core's mobile toggler with ID `wp-admin-bar-menu-toggle` to enable the menu adjustment inside the core's `common.js` file.

More information at pdqkbG-2eG-p2

Fixes https://github.com/Automattic/wp-calypso/issues/71198

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Navigate to a wp-admin page with content outside the viewport, or resize your window.
* Notice the, e.g., the Settings submenu being rendered outside of the viewport.
* Apply this patch
* Ensure that the submenu is rendered inside the viewport.

Note that I didn't test this in Simple sites as I couldn't find the proper way of doing so. Please consider testing this patch in both Simple and AT sites.

## Does this pull request change what data or activity we track or use?

No.

### CODE REVIEW

**Comment by that-mike-bal** [comment]
Hey @jeherve  - anyway we can bump this review?

**Comment by jeherve** [comment]
@that-mike-bal If this is ready for review, I would recommend the following:

1. Update this PR with the latest version of `trunk`. Running `git merge origin/trunk` will do it. See the failing "PR is up to date" and "PHP tests" CI checks below; those will be fixed when updating the branch.
2. Add the "Needs Team Review" label and have someone on your team review the changes and approve them if they're happy wit the changes.
3. Add the "Needs review" label so someone from Crew can take a final look at the PR, test, review, and merge.

**Review by PanosSynetos — APPROVED** [review]
👌 Hey @xristos3490 - Tested on my atomic site and works as expected

## Before 

image


## After

image

**Comment by xristos3490** [comment]
Thanks for testing this @PanosSynetos! @jeherve Could you please take another look?

**Review by jeherve — APPROVED** [review]
This tests well for me on WoA. I cannot reproduce the issue on WordPress.com simple, but the patch doesn't seem to break anything. 🚢

**Comment by PanosSynetos** [comment]
Thank you @jeherve - Any ideas on when will this be merged and released?

**Comment by jeherve** [comment]
As soon as you get the "Ready to merge" label and the tests pass on your PR, you can merge it.

I've updated this branch so the tests can run again and pass, and I enabled auto-merge, so the PR will be automatically merged as soon as the tests complete. The changes will be deployed to WordPress.com Simple and WoA with the next Jetpack release. This should happen next Wednesday (releases happen every week).

**Comment by PanosSynetos** [comment]
Thanks for the info! Much appreciated!

**Pull request merged**
