### PR TITLE
Sharing: Merges changes from wpcom as of 17th of June, 2015

### PR DESCRIPTION
**Pull request by zinigor**
This is a merge of several changes from wpcom. cc @aduth

### CODE REVIEW

**Comment by dereksmart** [comment]
LGTM aside from what jeremy pointed out

**Comment by aduth** [comment]
Thanks for porting these over, @zinigor . The changes to `sharing-sources.php` look good to me, and were confirmed to be working in my Jetpack environment. I'm now noticing that non-official styles don't use the same behavior as the official button (affects both Jetpack and WordPress.com).

**Comment by aduth** [comment]
See the [`merge/sharedaddy-leftovers-consistency` branch](https://github.com/Automattic/jetpack/tree/merge/sharedaddy-leftovers-consistency) for an attempt at providing consistent behavior between the official and non-official buttons (specifically, 22521f4).

**Comment by zinigor** [comment]
Closing this in favor of #2269

**Pull request closed without merging**
