### PR TITLE
Fix/soft disconnection deprecation

### PR DESCRIPTION
**Pull request by leogermani**
Fixes issue in connection consumers that were checking `$plugin->is_enabled()`. (added in #23991)

The deprecation of soft disconnection made this method superfluous, but for BC reasons it was kept. But it was broken.

#### Changes proposed in this Pull Request:

* Fix plugin->is_enabled method

#### Jetpack product discussion

p1651023531345719-slack-C02AVAR9B

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Connect Jetpack
* Activate Boost and check it working as expected
* Activate woo-commerce payments and make sure it finds itself connected
* Test connecting, using and disconnecting different combinations of plugins (Jetpack and Boost, Jetpack and WCPayments, Bakcup and WCPayments, Backup and Boost, etc...)
* After deactivating a plugin (while other connected plugin is still active), check we have the right information on WPCOM
 * `jetpack_connected_active_plugins`
 * `jetpack_package_versions`

### CODE REVIEW

**Comment by kraftbj** [comment]
We merged the revert, so you'll want to revert the revert ( [7cee72a](https://github.com/Automattic/jetpack/commit/7cee72a180e75397a7eba58bf8b4b25cf2e6dcc6) ) in this branch.

**Review by coder-karen — COMMENTED** [review]
Everything appears to be working fine here (Boost, Woo Payments). However if I have WP_DEBUG_LOG enabled, I get a lot of deprecation notices at the top of the page making navigation impossible. Removing it, everything is fine. Is this something we'd be concerned about?

**Comment by kraftbj** [comment]
Yeah, we don't want to pollute log files. Is it coming from within Jetpack or one of the other plugins?

We may want to deprecate without notice while working with partners (WCPay for example) that need updates.... Then throw the notice in a few months after those mutual users would be upgraded, etc.

**Comment by coder-karen** [comment]
The notices (`Deprecated: Automattic\Jetpack\Connection\Plugin::is_enabled is deprecated since version 1.40.0-alpha with no alternative available. `) are triggered when activating WooCommerce Payments only (activating Boost is fine).

**Comment by coder-karen** [comment]
Following up here - as the Boost E2E tests are still failing we opted to use the revert PR in the Beta release.

p1651072216183279/1651068886.580209-slack-C01U2KGS2PQ

**Comment by leogermani** [comment]
The failing tests will need to be updated, there's a change in the assumption the test makes.

We used to require users to click and connect Boost even if Jetpack was already connected. This is not required anymore. If any Jetpack plugin is connected, all others will also be.

**Review by sergeymitr — APPROVED** [review]
👍

**Pull request merged**
