### PR TITLE
Fixed lack of space between button and link in MailChimp blank slate …

### LINKED ISSUE #14979: Mailchimp block: no space in the setup screen
When inserting Mailchimp block in Gutenberg 7.7 on WordPress.com simple site, using Varia theme, there's no space between the button and "recheck connection" link:

Screenshot 2020-03-13 at 16 29 12

### PR DESCRIPTION
**Pull request by davemart-in**
**Expected**
Adequate padding between the MailChimp blank slate button and the link below it.

**Actual**
There is a lack of padding, causing the button and link to feel too cramped.

| Before  | After |
| ------------- | ------------- |
| before  | after|

Fixes #14979

#### Changes proposed in this Pull Request:
* Moved the wrapper div from around the button to be around the link below it

#### Proposed changelog entry for your changes:
* Fixed lack of space between button and link in MailChimp block blank slate

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
It doesn't quite work on WP 5.3.2 I am afraid:

image

**Comment by davemart-in** [comment]
Thanks @jeherve. This is on my list to circle back to.

**Comment by jeherve** [comment]
@davemart-in Do you think you'll get the chance to look at it before the code freeze on Monday evening? It would be nice if we could push this in in time when folks update to WordPress 5.4.

Thank you!

**Comment by davemart-in** [comment]
Thanks for the ping! Yes, I'll work on this over the weekend. 👍

**Comment by davemart-in** [comment]
Okay @jeherve, after my latest updates, here's what I'm seeing in 5.3.2:



and here's latest WP:

latest

**Review by jeherve — APPROVED** [review]
This seems to work well for me now. Merging.

**Comment by jeherve** [comment]
r205033-wpcom

**Pull request merged**
