### PR TITLE
Add shortcode handler for embedding geogebra widgets

### PR DESCRIPTION
**Pull request by nbloomf**
Just like it says on the tin.

[GeoGebra](www.geogebra.org) is a tool for building interactive geometry demonstrations. It is mature, open source, and widely used in math education. This PR adds a shortcode for embedding GeoGebra applets uploaded to the project's [online library](tube.geogebra.org). It also hooks into ``pre_kses`` so that geogebra iframes in comments are converted to shortcodes.

#### Changes proposed in this Pull Request:

Add a new shortcode handler.

#### Testing instructions:

1. Make sure the Shortcodes module is enabled.
2. Create a new post with a shortcode of the following form: ``[geogebra id="vnRmvGCx"]`` (arbitrary example)
3. Save and view the post.
4. Try out the optional shortcode attributes: ``height``, ``width``, ``input-bar``, ``style-bar``, ``menu-bar``, ``tool-bar``, ``tool-help``, ``reset-icon``, ``right-click``, ``drag-labels``, and ``pan-zoom``. All but height and width expect to be "true" or "false".
5. Try using the shortcode without an ``id`` attribute. (This is an error)
6. Comment on a post with the following scary HTML: ``<iframe scrolling="no" src="https://www.geogebra.org/material/iframe/id/DpseMPzu/width/662/height/394/border/888888" width="662px" height="394px" style="border:0px;"> </iframe>``

You can get more iframes for testing at [https://tube.geogebra.org](https://tube.geogebra.org); open an applet page, click on the Share icon at the top of the page (it looks like a sideways V) and click on the "Embed" tab. Click "show more" to see the embed options.

### Changelog:

The ``geogebra`` shortcode has one required attribute, ``id``; this is the ID code of the applet to be embedded. It has several optional attributes as follows:

* ``height`` (integer): The height of the embedded applet.
* ``width`` (integer): The width of the embedded applet.
* ``input-bar`` (true/false): Show or don't show.
* ``style-bar`` (true/false): Show or don't show.
* ``menu-bar`` (true/false): Show or don't show.
* ``tool-bar`` (true/false): Show or don't show.
* ``tool-help`` (true/false): Show or don't show.
* ``reset-icon`` (true/false): Show or don't show.
* ``right-click`` (true/false): Allow or don't allow.
* ``drag-labels`` (true/false): Allow or don't allow.
* ``pan-zoom`` (true/false): Allow or don't allow.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Create **[unit tests](https://github.com/Automattic/jetpack/tree/master/tests)** if you can. If you're not familiar with Unit Testing, you can check [this tutorial](https://pippinsplugins.com/series/unit-tests-wordpress-plugins/).

### CODE REVIEW

**Comment by jeherve** [comment]
Thanks for the PR!

Before we review and test your code, I'd like to ask you if the GeoGebra service supports [the oEmbed protocol](http://oembed.com/)? If so, it would make things a lot easier and a lot more user friendly than the use of a shortcode. One would only have to paste a GeoGebra URL, and would then get a preview in their editor.

While Jetpack includes a large amount of shortcodes, when looking into adding new services, we favor integrations with services which already support the oEmbed protocol for their product.

I googled a bit, but only found [this open Trac ticket](https://dev.geogebra.org/trac/ticket/838#).

**Comment by nbloomf** [comment]
Thanks for having a look! And thanks for teaching me about oEmbed today. :)

I think the answer is no, but don't know for sure, so I put in a [question](https://help.geogebra.org/topic/oembed-protocol-on-geogebra-org) about this at the GeoGebra support forum.

**Comment by nbloomf** [comment]
I'm closing this PR- it has some serious vulnerabilities, and when GeoGebra implements oEmbed all these changes will be tossed out anyway.

**Comment by nbloomf** [comment]
Note to future self-

The ``geogebra_shortcode_handler`` function in this PR is vulnerable to XSS attacks such as the following.

``[geogebra id=QFbnH4dQ height='480/width/640" onload="alert(String.fromCharCode(88,83,83))" x="']``

**Pull request closed without merging**
