### PR TITLE
Module Info: add search terms for each module

### LINKED ISSUE #614: Module search needs additional keywords to search
## Did
Searched modules for "Statistics"

## Observed
Zero results.

## Expected
"WordPress.com Stats" modules to show up.

---

What might be good is to have additional hidden keywords that are searched.

### PR DESCRIPTION
**Pull request by jeherve**
Uses the `jetpack_search_terms_*` filters added by @dereksmart in #1969
Fixes #614

### CODE REVIEW

**Comment by georgestephanis** [comment]
This isn't the sort of implementation I'd like on this.  I'd prefer storing them in the module header, and we can autogenerate translation strings from there.

**Comment by jeherve** [comment]
@georgestephanis I updated the Pull Request based on your feedback.

**Comment by jeherve** [comment]
@jessefriedman Is "Search Terms" ok here, or should I rename the module headers?

**Comment by jessefriedman** [comment]
@jeherve I have no objects but it might be a tad more clear if we called them Additional Search Queries as they are supplementing the Search Queries

**Comment by jeherve** [comment]
@jessefriedman Done!

**Comment by dereksmart** [comment]
Rebased it, but this PR does not successfully search for these on the settings page, as it was before when using the filters

**Comment by dereksmart** [comment]
Punting for now, I can't get module search to pick up on `Advanced Search Queries` terms like for example `security` (protect)

**Comment by samhotchkiss** [comment]
@jessefriedman and @jeherve , can you take a look?

Thanks!

**Comment by jessefriedman** [comment]
While the Additional Search Queries look good the search functionality isn't working well yet. 

Searching for `cdn` produces 3 results but only 1 uses the term `cdn`
https://cloudup.com/iKpy4lznbiZ

`speed` is a search query for photon but typing in `speed` produces 0 results
https://cloudup.com/i9WNrsGyXXg

searching for `photon` brings up Tiled Galleries even though the term photon isn't used in its queries
https://cloudup.com/iKwqlGB-oMa

I'm not sure how the searching algorithm works but I'm guessing there is where the problem lies.

**Comment by jeherve** [comment]
Replaced by #2592

**Pull request closed without merging**
