### PR TITLE
Shortcodes: Add autohide parameter to the YouTube shortcode.

### PR DESCRIPTION
**Pull request by jeherve**
`autohide` accepts 3 parameters: `2` is the default, `0` and `1` are 2 other accepted values:
https://developers.google.com/youtube/player_parameters?hl=en#autohide

Suggested here:
https://wordpress.org/support/topic/youtube-shortcode-autohide-player-controls

### CODE REVIEW

**Comment by zinigor** [comment]
This doesn't work for me as well as it should. The default `autohide` parameter gets added fine, but if I want to use something else, it looks like it doesn't get through to `$qargs`. To reproduce checkout the branch and use the following shortcode for example:
```[youtube autohide=1 url=https://www.youtube.com/watch?v=3xF3aBCNWD4]```

Observe that the video still gets loaded with `autohide=2`.

**Comment by jeherve** [comment]
@zinigor The YouTube shortcode expects parameters to be inside the URL, like so:
`[youtube url=https://www.youtube.com/watch?v=3xF3aBCNWD4&autohide=1]`

See more examples here:
https://en.support.wordpress.com/videos/youtube/

**Comment by zinigor** [comment]
D'oh! Thank you, it works perfectly now that I test it properly.

**Comment by dereksmart** [comment]
:shipit:

**Pull request merged**
