### PR TITLE
Simple Payments Widget: Add Plan Check

### PR DESCRIPTION
**Pull request by rodrigoi**
Depends on:

- Simple Payments: adds plan support check for Jetpack and WordPress.com (#9650 and D14005-code)

#### Changes proposed in this Pull Request:

* Adds a plan support check to the SP Widget.

#### Testing instructions:

* Apply this branch on a Jetpack site with a Premium or Business Subscriptions.
* Using the Customizer, add a Simple Payment button as a widget to the site's sidebar.
* Navigate to site's frontend.

The Simple Payment button should display as a widget on the selected sidebar and location.

* Downgrade the site to the Free plan without deleting the SP Widget from the sidebar.
* Navigate to the Jetpack dashboard to refresh the site's settings.
* Navigate to site's frontend.

The site's sidebar should no longer show the Simple Payment.

### CODE REVIEW

**Comment by gwwar** [comment]
@rodrigoi Is this diff meant to work on it's own if I checkout this branch? I'm seeing 500's currently when switching to this branch

**Comment by Copons** [comment]
@gwwar Pretty sure this requires #9650

**Comment by gwwar** [comment]
Code makes sense 👍 but I'm not having much luck with getting the widget to disappear after downgrading. Maybe I'm not sandboxing properly? 

@Copons or @vindl would it be possible for y'all to test as well?

**Comment by rodrigoi** [comment]
Closed in favor of https://github.com/Automattic/jetpack/pull/9824 that targets the new feature branch.

**Pull request closed without merging**
