### PR TITLE
Update All Sites icon size for Simple Classic

### PR DESCRIPTION
**Pull request by lupus2k**
Fixes https://github.com/Automattic/dotcom-forge/issues/7483

## Proposed changes:
Update the `All Sites` icon size on Classic Interface.

| Before | After |
| --- | --- |
| sites-icon-before |sites-icon-after |

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
No

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Go to 'wp-admin' with a Classic Interface site (you can switch it in Settings)
* Check the All Sites icon size

### CODE REVIEW

**Comment by lucasmendes-design** [comment]
Hi there, I may be doing something wrong but the icons are different. What is the link I should visit? Horizon? 

image
image

**Comment by lupus2k** [comment]
> Hi there, I may be doing something wrong but the icons are different. What is the link I should visit? Horizon?
> 
> image image

Sorry, You have to run `bin/jetpack-downloader test jetpack-mu-wpcom-plugin update/all-sites-icon-size` in your sandox

**Review by miksansegundo — APPROVED** [review]
|Before|After|
|-|-|
|Screenshot 2567-06-14 at 20 54 04|Screenshot 2567-06-14 at 20 55 39|

It's easier to see the change on this recording:

https://github.com/Automattic/jetpack/assets/1881481/3f5b7577-cc91-4853-8da7-6dd0ede73f55

**Comment by miksansegundo** [comment]
@lucasmendes-design let us know if this new size looks good to you 🙂 on the recording. I believe you don't have a sandbox for testing it.

**Comment by lucasmendes-design** [comment]
> let us know if this new size looks good to you 🙂 on the recording. I believe you don't have a sandbox for testing it.

Yes, I haven't. Thanks for the recording :) 

LGTM 🫶🏽

**Pull request merged**
