### PR TITLE
Search: Fix search on private WordPress.com-on-Atomic sites

### LINKED ISSUE #24197: Search: Search fails on private WoA sites
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

This issue is geared toward a12s.

1. Spin up a WoA site with either a Jetpack plugin or a Search plugin on WordPress.com.
2. Purchase Jetpack Search for the site.
3. Navigate to `/?s=` and ensure that the search interface works as expected. It may take a minute or two for the indexing to finish.
4. Navigate to `https://wordpress.com/settings/general/` and change site visibility to `Private`.
5. Repeat step 3.

### A clear and concise description of what you expected to happen.

For the search results to populate.

### What actually happened

Screen Shot 2022-04-29 at 2 35 35 PM

Screen Shot 2022-04-29 at 2 36 52 PM

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #24197.

#### Changes proposed in this Pull Request:
Fixes search on private WordPress.com-on-Atomic (WoA) sites by signing the requests with a blog token instead of a user token.

Also changes the local API URL to the one provided by the search package instead of the one provided by the Jetpack plugin. 

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

Note: This PR is only testable by a12s.

1. Spin up a WoA site (either via Pro plan purchase + Jetpack Beta plugin install or via WoA developer blogs — p9o2xV-1r2).
2. Purchase Jetpack Search for the WoA site.
3. Navigate to `/?s=`. Ensure that the search interface works as expected.
4. Navigate to `https://wordpress.com/settings/general/` and change site visibility to Private.
5. Repeat the site search from step 3; ensure that the search API request fails in the network console.
6. Install the Jetpack Beta plugin (if you haven't in step 1) and change the plugin branch to this one.
7. Repeat step 5; ensure that the search API request succeeds.
8. Revert the site privacy back to Public and repeat step 5, just in case.

### CODE REVIEW

**Comment by jsnmoon** [comment]
I believe this regression was introduced in #21584. @kangzj, do we know why we changed to signing with user tokens here?

**Comment by kangzj** [comment]
@jsnmoon Yep I think so, this is a bug - I guess I didn't anticipate a local user doesn't necessary a WPCOM user in the previous PR.

**Comment by kangzj** [comment]
Hi @jsnmoon, could you please share more details about how to create a WoA site? I'm not sure how I set up one - should I  use the sandbox, a ephemeral site or sth else?

**Comment by jsnmoon** [comment]
> Hi @jsnmoon, could you please share more details about how to create a WoA site? I'm not sure how I set up one - should I use the sandbox, a ephemeral site or sth else?

The best way would be to spin up a regular WordPress.com site, purchase a Pro plan, and to install a plugin on it. I'll share the more internal a8c steps to do so privately.

**Review by kangzj — APPROVED** [review]
Thanks for fixing this. It works for me 👍

**Pull request merged**
