### PR TITLE
Gutenberg: Try out the Markdown block

### PR DESCRIPTION
**Pull request by tyxla**
This PR allows to test the latest version of the Markdown block that we have in Calypso, without the need to set up a bunch of environments for that. 

⚠️ This PR shouldn't be merged - it exists only for testing purposes.

#### Changes proposed in this Pull Request:

* Does several preparations to make testing easier:
  * ⚠️ Enables loading of custom Jetpack Gutenberg blocks
  * ⚠️ Un-`git ignore`-s the `_inc/blocks` directory to allow us to include custom blocks in the branch 
  * ⚠️ Adds a built Jetpack block preset based on the [existing block in Calypso](https://github.com/Automattic/wp-calypso/tree/master/client/gutenberg/extensions/markdown).

#### Testing instructions:

* Spin up a new Jurassic Ninja site with Jetpack and Gutenberg from this PR. You can use the following link to spin up a site: https://jurassic.ninja/create?jetpack-beta&branch=demo/try-markdown-gutenberg-block&shortlived&wp-debug-log&gutenberg
* Write a post, insert a Markdown block.
* Input some Markdown content, play with the Markdown and Preview tabs.
* Try to break it.

#### Proposed changelog entry for your changes:

* Introduced a new Markdown block for Gutenberg.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
I found an issue with the markdown preview. It looks like the styles don't match Gutenberg's. I also noticed the HTML doesn't match Gutenbergs, but there's an issue [here](https://github.com/WordPress/gutenberg/issues/9129) for that.

It looks like this currently:
https://cloudup.com/c-aaTn8KyJu

I created a demo on the JN site you set up for you to play with:
https://technological-horse.jurassic.ninja/wp-admin/post.php?post=8&action=edit

Note: I don't see this as a blocker for initial merge, but we do need to at the very least address it in a followup PR. I suspect the solution might require a little exploration.

**Comment by mapk** [comment]
Riffing off of @MichaelArestad's comparison above, I created a `columns` block in Gutenberg and put a nested markdown block on the left with the regular Gutenberg blocks on the right.

There were a few more differences I found.

1. Line-heights in the markdown were too tight.
2. Blockquotes didn't show the Gutenberg left-border.
3. Lists were not indented.
4. Preformatted code blocks had a grey background, but in Gutenberg they didn't.
5. The grey color background in for the `<code>` text was darker than the grey background in Gutenberg.

Here's a screenshot of them side-by-side.
https://cloudup.com/cm6JsEbcB22

I agree with @MichaelArestad that these can be iterated upon at a later time.

**Comment by MichaelArestad** [comment]
> I found a very minor issue with reference links.

Yeah. I think reference links could use whatever pattern Gutenberg uses for footnotes, though I'm not sure if those ever made it in.

**Comment by tyxla** [comment]
Thanks for the feedback, folks! 

I've taken a quick look, there seem to be several problems right now:
* We're using [this Markdown parser](https://github.com/markdown-it/markdown-it), so any bugs or differences (like the ones with reference links) might have to be pushed upstream, unless we decide to use another parser or fork this one (which doesn't sound like a good idea because of the maintenance costs it adds).
* It seems that the style problems come from the fact that all of those blocks (headings, paragraphs, lists) have their own classnames, and these classnames are used to style them. None of those elements have those classnames in the markdown preview 😕 I'm not sure how to tackle that yet, but will investigate next week.

**Comment by tyxla** [comment]
I'm planning to continue work on Markdown this week, but it'll happen in the Calypso repo. This PR is no longer necessary - y'all can spin up a JN site to test it with this URL: https://jurassic.ninja/create/?gutenberg&gutenpack&calypsobranch=master (thanks @oskosk ❤️ )

**Comment by oskosk** [comment]
`&calypsobranch=master` not needed actually. It's the default for when `gutenpack` is present.

**Comment by tyxla** [comment]
@mapk seems like reference links (footnotes) are subject to separate different implementations by plugins for Markdown. Since that seems to be additional extension work, I'm suggesting that we work on it after the v1 of the module.

**Comment by tyxla** [comment]
@MichaelArestad @mapk I've worked on reducing the visual differences between the core Gutenberg blocks/ elements and the Markdown preview in https://github.com/Automattic/wp-calypso/pull/27450 - I'd appreciate if you could have a look and let me know what you think.

**Comment by MichaelArestad** [comment]
> @mapk seems like reference links (footnotes) are subject to separate different implementations by plugins for Markdown. Since that seems to be additional extension work, I'm suggesting that we work on it after the v1 of the module.

Yeah. Let's not sweat footnotes until we have a large and active Markdown user base.

**Pull request closed without merging**
