### PR TITLE
Paid Newsletter: Detect subscription tier upgrade

### PR DESCRIPTION
**Pull request by pottedmeat**
Fixes 142-gh-Automattic/gold

## Proposed changes:

* Adds the ability to check for a paid subscriber at any tier level
* Exposes tier validation function
* Switches language between Subscribe/Upgrade depending on paid status

## Testing instructions:

- Apply D121198-code on your sandbox
- Patch your sandbox, answering "N" when it asks to checkout trunk:
```
bin/jetpack-downloader test jetpack add/detect-tier-upgrade
```
- Follow the instructions provided by [the bot below](#issuecomment-1716111091) or [create a new Jurassic Ninja site](https://jurassic.ninja/create?jetpack-beta&branches.jetpack=add/detect-subscription-upgrade&wp-debug-log) using this branch. 
- Connect Jetpack
- Make sure  to enable the newsletter options in the jetpack settings.
- Make sure to set `JETPACK__SANDBOX_DOMAIN` to your sandbox address (see `wp-admin/options-general.php?page=companion_settings` in JN)
- Enable global http in your sandbox
- Use store sandbox: PCYsg-IA-p2
- Sandbox `public-api.wordpress.com`, `subscribe.wordpress.com` and the test site (if testing on a simple site)
- From the Earn dashboard, connect Stripe if needed
- Create two "Paid newsletter tier" payment plans with one priced higher than the other
- image
- Create a new post with the lower-priced tier and publish it
- image
- Open a new incognito and visit the post page
- Text should read "Subscribe..."
- image
- Clicking the "Subscribe" button should launch a popup and show the plan picker
- Subscribe to the lowest tier with an email account not associated with the site owner
- Change access to the post to a higher tier
- Open a new incognito and visit the post page (don't reload, open it again, or delete the query string after `?`)
- Text should read "Upgrade..."
- 267157571-43a0319e-0473-4abb-987b-bf825a356ed8
- Clicking the "Upgrade" button should launch a popup and show the plan picker

### CODE REVIEW

**Comment by millerf** [comment]
@pottedmeat 

Following the instructions, I got this error:

```

Fatal error: Uncaught TypeError: Argument 3 passed to A8C\FSE\Earn\API\V1\Authentication\Auth_Endpoint::is_paid_subscriber() must be of the type int or null, string given, called in /home/wpcom/public_html/wp-content/lib/memberships/class.memberships-checkout-form.php on line 208 and defined in /home/wpcom/public_html/wp-content/mu-plugins/earn/api/v1/authentication/class-auth-endpoint.php:108 Stack trace: #0 /home/wpcom/public_html/wp-content/lib/memberships/class.memberships-checkout-form.php(208): A8C\FSE\Earn\API\V1\Authentication\Auth_Endpoint->is_paid_subscriber('newsletter', 'everybody', '') #1 /home/wpcom/public_html/wp-content/mu-plugins/subscribe-to-blogs.php(223): Memberships_Checkout_Form->render(142534287, '1336', 'newsletter', '', false, 'millerf81+bronz...', 'jetpack_subscri...', 'everybody', '') #2 /home/wpcom/public_html/wp-includes/class-wp-hook.php(310): subscriptions_blog('') #3 /home/wpcom/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) #4 /home/wpcom/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/wpcom/public_html/wp-includes/template-loader.php(13): do_action('template_redire...') #6 /home/wpcom/public_html/wp-blog-header.php(19): require_once('/home/wpcom/pub...') #7 /home/wpcom/public_html/index.php(49): require('/home/wpcom/pub...') #8 {main} thrown in /home/wpcom/public_html/wp-content/mu-plugins/earn/api/v1/authentication/class-auth-endpoint.php on line 108
```

When clicking on the `subscribe button` when not logged in.

Screenshot 2023-09-13 at 12 18 00

**Comment by millerf** [comment]
Issue was not really related to this diff. I fixed it in D121574-code

**Comment by millerf** [comment]
I tested it and it works for me.

There is 2 small changes I would like to make:

### Gate block
Screenshot 2023-09-13 at 16 02 15

When accessing this block after subscribing, the user is already "logged in":
- We should not display `Already a paid subscriber? Log in`. I requested change with Zap team in Slack: p1694613846242699-slack-C052XEUUBL4
- The "upgrade" button is a nice touch. However the email address is not displayed, and this is on WPCOM, and this is on WPCOM, not jetpack (https://github.com/Automattic/gold/issues/142#issuecomment-1709021091)
- I wonder if we should even display the email input. Maybe we should only display the "upgrade" button here, and add a button if the user wants to subscribe with a different email address (@crisbusquets )

👆Those 3 can be handled in a separated task

Finally, something that can be done in this one:
Screenshot 2023-09-13 at 16 26 10
Can we change the text to:
```
Choose a tier to upgrade to
```

**Comment by crisbusquets** [comment]
> I wonder if we should even display the email input. Maybe we should only display the "upgrade" button here, and add a button if the user wants to subscribe with a different email address (@crisbusquets )

I was thinking about this a few minutes ago while reviewing the paywall block. For now I would keep the input field so they can see which email they are upgrading the subscription with.

What do you think?

**Comment by millerf** [comment]
> What do you think?

It is fine as long as you are keeping track of that... 👍

**Comment by pottedmeat** [comment]
> However the email address is not displayed, and this is on WPCOM, not jetpack 

I'm not sure how this is happening. The code is pretty straightforward (fbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scyhtvaf%2Swrgcnpx%2Srkgrafvbaf%2Soybpxf%2Sfhofpevcgvbaf%2Sfhofpevcgvbaf.cuc%3Se%3Q6671012p%23570-og) and if I visit https://bestmemberships.wordpress.com/ I see my email address in the input.

**Comment by millerf** [comment]
>? I'm not sure how this is happening. The code is pretty straightforward (uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scyhtvaf%2Swrgcnpx%2Srkgrafvbaf%2Soybpxf%2Sfhofpevcgvbaf%2Sfhofpevcgvbaf.cuc%3Se%3Q6671012p%23570-og) and if I visit https://bestmemberships.wordpress.com/ I see my email address in the input.


The issue is once the subscribers pays or answers the login code, they are not actually logged in. We could use the email from the Token if it was provided... Or log the user on WPCOM...

**Pull request merged**
