### PR TITLE
My Jetpack: Change button used in ProductCard component

### PR DESCRIPTION
**Pull request by dhasilva**
#### Changes proposed in this Pull Request:
Changes which `Button` component is used by the `ProductCard` component, switching its import from `@wordpress/components` to `@automattic/jetpack-components`. The visual changes are more pronounced in the storybook, as it is not re-styled there. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Start `storybook`
* Navigate to `Packages > My Jetpack > Product Card`
* Check if the button is black instead of blue

Before | After
------|------
Screenshot_2022-07-20_14-41-35-before-story |  Screenshot_2022-07-20_14-41-35-after-story

Before | After
------|------
Screenshot_2022-07-20_14-26-05-before | Screenshot_2022-07-20_14-26-22-after

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202640362053502

### CODE REVIEW

**Review by retrofox — CHANGES_REQUESTED** [review]
It's almost done. There is a visual issue when defining the font-weight of te button text:


before | after
------|------
`font-weight: 400;` | `font-weight: 600;`
image | image

Fortunately, the `<Button />` component already supports the `weight` property. You can see how it works [using its story](https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-button--default&args=weight:regular).
Screen Shot 2022-07-20 at 4 44 59 PM

**Comment by retrofox** [comment]
I wonder why the screenshots you share here have the proper font weight.

**Comment by dhasilva** [comment]
> I wonder why the screenshots you share here have the proper font weight.

Had to take a very close look, but you are right, the "after" ones are with the wrong weight.

**Review by retrofox — APPROVED** [review]
LGTM !:shipit:

**Pull request merged**
