### PR TITLE
Fix/rdv regressions on treatment

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes several issues with the remove duplicate views experiment.

## Proposed changes:

* Fix the Admin menu upsell notice
* Fix the Stats and Promote with Blaze post menu items
* Fix the Tour overlay being displayed on Blaze and Stats pages

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Test on Simple and Atomic sites
* Go to WP-Admin > Posts
* Notice that the Promote with Blaze and Stats links are working (post list)
* Notice that Settings > Advertising is working (in-page WP-Admin screen)
* Notice that the upsell banner in WP-Admin menu is styled correctly
* Go to a Stats page from the posts lists
* Notice that there's no background overlay (from the tour component)

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
## Post List Stats

I think this is better than the current live experience for treatment, and for control + wp-admin. It's not better than the current live + control calypso experience. It's a bit confusing because the menu goes wrong.

Screenshot 2024-12-19 at 20 11 20

I'm concerned about blowing the scope by getting too embroiled in untangling jetpack stats. Is the best way forward to do what calypso control does and link to /stats/* from the Post List and menu ?

When testing:

#### Treatment
 * The Post List links to /wp-admin/admin.php?page=stats#!/stats/post/ID/BIGID?page=stats
 * It highlights the Jetpack menu which doesn't contain a Stats menu item
 * The Statistics menu item links to https://wordpress.com/stats/day/:siteSlug


#### Control (calypso)
 * The Post List links to https://wordpress.com/stats/post/ID/:siteSlug
 * It highlights the statistics menu
 * The Statistics menu item links to https://wordpress.com/stats/day/:siteSlug

#### Control (wp-admin)
 * The Post List links to /wp-admin/index.php?page=stats&view=post&post=ID
 * It doesn't highlight any of the menus
  * The Statistics menu item links to https://wordpress.com/stats/day/:siteSlug


#### Site set to classic
 * The Post List links to /wp-admin/admin.php?page=stats#!/stats/post/119/234759279?page=stats
 * The Jetpack → Stats menu is highlighted
 * There is no top-level Statistics menu

**Comment by mmtr** [comment]
> Is the best way forward to do what calypso control does and link to /stats/* from the Post List

I like this from a user perspective, but we would be essentially making this third wp-admin experience more and more divergent from the "Tangled – Classic view" and "Untangled" experiences, which is something we initially wanted to avoid (see paYJgx-5FI-p2).

**Comment by mmtr** [comment]
> Fix the Admin menu upsell notice

I still see wrong styles 🤔 

Screenshot 2024-12-20 at 14 11 04

**Comment by dsas** [comment]
> we would be essentially making this third wp-admin experience more and more divergent from the "Tangled – Classic view" and "Untangled" experiences, which is something we initially wanted to avoid 

Yep, and I think in general that's the right call.

For this specific case, I'd anticipate the menu being wrong for 90% of users will be raised pretty quickly as a high priority bug and an indicator of dotcom brokenness and code blue. I think we should make an exception.

**Comment by BogdanUngureanu** [comment]
@mmtr @dsas I've pushed a commit that should fix the upsell notice issue and a change that forces the stats page to highlight the Calypso Stats Admin menu :)

It's RfR again :)

**Review by dsas — COMMENTED** [review]
> a change that forces the stats page to highlight the Calypso Stats Admin menu :)

Ok, this seems to works. It's a little bit odd but I don't think it blocks merging, maybe it's something that will need resolving before starting the experiment though. The oddity is that the UTM section shows as a Premium upgrade in one screen and it doesn't in the other. I'm already on the Premium plan. When I click "Upgrade to Premium" nothing happens.

Via post list | Via Statistics menu
-------|------
image | image

**Comment by BogdanUngureanu** [comment]
@dsas that seems unrelated to our changes. :D

**Comment by dsas** [comment]
> @dsas that seems unrelated to our changes. :D

Well, we haven't broken it, no, but my concern is that we are bringing increased visibility to something already broken. I don't think it's a blocker right now, but maybe we'll need to find people to fix it in January.

**Comment by mmtr** [comment]
Another thing that looks different is the sidebar upsell, it seems that styles coming from Jetpack Stats override the sidebar upsell styles (note how the font is bolder):
Screenshot 2024-12-20 at 17 28 41

At this point, I'd revisit our decision of using Jetpack Stats during the experiment, and reconsider using Calypso Stats instead.

But we can re-evaluate that later.

**Review by mmtr — APPROVED** [review]

**Pull request merged**
