### PR TITLE
Docs: Partners: Add links within README; Add doc for automatic account creation

### PR DESCRIPTION
**Pull request by ebinnion**
#### Changes proposed in this Pull Request:

- Add links to README.md to other documents.
- Add document for automatic account creation
- Remove Dan as point of contact

#### Testing instructions:

- Read through doc and ensure it makes sense
- Click "View" button on `README.md` changeset below and ensure links works correctly

#### Proposed changelog entry for your changes:

- Add documentation for automatic account creation in partners API

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
Perfect. Just one comment but it's really just nitpicking.

**Comment by ebinnion** [comment]
Thank you for pointing that out! I've just pushed a fix.

**Review by jeherve — APPROVED** [review]
Looking good now. Merging when the tests will pass.

**Comment by kraftbj** [comment]
Due to Github's outage, Travis is backed up. Tests are finally running and will merge.

**Pull request merged**
