### PR TITLE
Build: Update gulp-clean-css to 4.2.0

### PR DESCRIPTION
**Pull request by mdawaffe**
#### Changes proposed in this Pull Request:
Updates the `gulp-clean-css` dependency from 2.4.0 to 4.2.0.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
N/A

##### In master, before applying this PR:
1. `yarn build`
2. `mkdir old`
3. `find . -path ./docker -prune -o -path ./old -prune -o -path ./new -prune -o -type f -name '*.min.css' -exec cp {} old \;`

##### Switch to this branch
1. `yarn build`
2. `mkdir new`
3. `find . -path ./docker -prune -o -path ./old -prune -o -path ./new -prune -o -type f -name '*.min.css' -exec cp {} new \;`
4. `diff -r old new` - Ensure no output (old and new CSS builds are the same).

#### Proposed changelog entry for your changes:
Update some build dependencies.

### CODE REVIEW

**Comment by mdawaffe** [comment]
Rebased after #13066.

**Comment by jeherve** [comment]
hm. Not sure if I am doing anything wrong, but here is what I get on my end:

```
diff -r old new                                                        jeherve@Jer
Only in old: admin-rtl.min.css
Only in old: admin-sharing-rtl.min.css
Only in old: admin-sharing.min.css
Only in old: admin.min.css
Only in old: codemirror-rtl.min.css
Only in old: codemirror.min.css
Only in old: comics-rtl.min.css
Only in old: comics.min.css
Only in old: css-editor-rtl.min.css
Only in old: css-editor.min.css
Only in old: cssparse-rtl.min.css
Only in old: cssparse.min.css
Only in old: cssparsed-rtl.min.css
Only in old: cssparsed.min.css
Only in old: dashboard-widget-rtl.min.css
Only in old: dashboard-widget.min.css
Only in old: editor-inline-editing-style-rtl.min.css
Only in old: editor-inline-editing-style.min.css
Only in old: editor-rtl.min.css
Only in old: editor-style-rtl.min.css
Only in old: editor-style.min.css
Only in old: editor-ui-rtl.min.css
Only in old: editor-ui.min.css
Only in old: editor.min.css
Only in old: jetpack-admin-jitm-rtl.min.css
Only in old: jetpack-admin-jitm.min.css
Only in old: jetpack-admin-rtl.min.css
Only in old: jetpack-admin.min.css
Only in old: jetpack-banners-rtl.min.css
Only in old: jetpack-banners.min.css
Only in old: jetpack-icons-rtl.min.css
Only in old: jetpack-icons.min.css
Only in old: jetpack-idc-admin-bar-rtl.min.css
Only in old: jetpack-idc-admin-bar.min.css
Only in old: jetpack-idc-rtl.min.css
Only in old: jetpack-idc.min.css
Only in old: jetpack-sso-login-rtl.min.css
Only in old: jetpack-sso-login.min.css
Only in old: post-by-email-rtl.min.css
Only in old: post-by-email.min.css
Only in old: protect-dashboard-widget-rtl.min.css
Only in old: protect-dashboard-widget.min.css
Only in old: recipes-print-rtl.min.css
Only in old: recipes-print.min.css
Only in old: recipes-rtl.min.css
Only in old: recipes.min.css
Only in old: site-logo-control-rtl.min.css
Only in old: site-logo-control.min.css
Only in old: slideshow-shortcode-rtl.min.css
Only in old: slideshow-shortcode.min.css
Only in old: social-logos.min.css
Only in old: style-gutenberg-rtl.min.css
Only in old: style-gutenberg.min.css
Only in old: style-rtl.min.css
Only in old: style.min.css
Only in old: swiper.min.css
Only in old: use-codemirror-rtl.min.css
Only in old: use-codemirror.min.css
Only in old: videopress-admin-rtl.min.css
Only in old: videopress-admin.min.css
Only in old: videopress-editor-style-rtl.min.css
Only in old: videopress-editor-style.min.css
Only in old: widget-conditions-rtl.min.css
Only in old: widget-conditions.min.css
```

Were those just leftovers on my local install?

**Review by jeherve — DISMISSED** [review]
Coming back to this, I think I just needed to adjust the second command to move the files. It's ok now. It will need a rebase though.

**Comment by mdawaffe** [comment]
> Coming back to this, I think I just needed to adjust the second command to move the files. It's ok now. It will need a rebase though.

Oops - sorry. I edited the command in the PR description.

**Comment by mdawaffe** [comment]
Rebased.

**Review by dereksmart — APPROVED** [review]
Looks good! No diff in builds, css looks clean on all pages I thought to look at, and no leftover stuff after building.

**Comment by kraftbj** [comment]
The tidycss change never made it over, so r205896-wpcom.

**Pull request merged**
