### PR TITLE
Admin Page: revamp non admin view when user is not linked and when it…

### LINKED ISSUE #3915: Admin: Non-admin view is extremely basic.
Currently non-admins see a very basic box/button combo, which is not very compelling.

screen shot 2016-05-23 at 6 13 08 pm

They should see a slimmed-down version of our pre-connection screen, targeted towards whatever features are available for them, e.g. SSO, Publicize, Stats, Calypso management.

### PR DESCRIPTION
**Pull request by eliorivero**
Closes #3915

#### Changes proposed in this Pull Request:

- [x] When user is not linked, page will be displayed like this https://github.com/Automattic/jetpack/issues/3915#issuecomment-230569070

- When user is linked, some elements are displayed in At a Glance and the setting tabs:

Dashboard
  - [x] At a Glance: Stats and Protect count
  - [x] Apps

Settings:
  - [x] General tab: Connection (link) setting
  - [x] Engagement tab: Publicize (not in React UI for v1)
  - [x] Writing tab: Post By Email
  - [x] Writing tab: After the Deadline

- [x] If user can't view Stats and Protect is not active, don't show At a Glance, only Apps

### CODE REVIEW

**Comment by dereksmart** [comment]
Noticed a few things:

- Seeing things greyed out as an admin in a couple of the tabs.
- The stats is showing for an editor and not respecting this option https://cloudup.com/cMAFxfGUlAc
- When protect is disabled, I see an inactive card there prompting me to activate, though I'm not able to. We should simply hide the card if it's not active.

**Comment by dereksmart** [comment]
@MichaelArestad any ideas on what we can show on the AAG landing page when the non-admin isn't shown anything?

**Comment by MichaelArestad** [comment]
@dereksmart They don't even get stats or anything?

**Comment by dereksmart** [comment]
@MichaelArestad Non-admins need to be explicitly allowed to see them.  These are the default settings for which roles can see stats for the site: 

screen shot 2016-07-07 at 11 28 34 am

**Comment by MichaelArestad** [comment]
Ah. Got it. @jeffgolenski ideas?

I'm thinking that if there are no stats to see, I would completely remove the At a Glance view and just show the Apps view maybe? Or just remove the dashboard view entirely?

**Comment by jeffgolenski** [comment]
@MichaelArestad Yeah, I think at that point perhaps just showing the apps landing page is the only real thing of value we can display for them.

**Comment by jeffgolenski** [comment]
@richardmuscat I see what you're saying

1) If non-admins have been given access to see stats (or other modules) we should definitely show them to the non-admin
2) If non-admins do not have access to see stats we should still show other relevant data to them

@eliorivero @dereksmart Are there ever going to be any instances where non-admins literally have 0% access to jetpack features / modules? In that instance, if ever, that's probably when we should just display the WordPress Apps landing page.

**Comment by dereksmart** [comment]
> Are there ever going to be any instances where non-admins literally have 0% access to jetpack features / modules?

Yes, except for the option to link/unlink.  This will always be available.

**Comment by MichaelArestad** [comment]
@eliorivero @dereksmart Is making At a Glance disappear in favor of the Apps view for users who can't see stats going to be difficult?

**Comment by eliorivero** [comment]
@MichaelArestad not too difficult. Once we get the role/s that is/are allowed to see Stats we can know if we should display AAG and Apps or only Apps.

**Comment by MichaelArestad** [comment]
@eliorivero Can it be done by tomorrow?

**Comment by eliorivero** [comment]
@MichaelArestad yes, it can be done by tomorrow.

**Comment by dereksmart** [comment]
This works as expected in my tests 👍

**Comment by oskosk** [comment]
LGTM!

**Pull request merged**
