### PR TITLE
Boost: Make Minify concat concat service independent of WordPress

### PR DESCRIPTION
**Pull request by dilirity**
> **Warning**
> Depends on another PR.
> Review and Merge after https://github.com/Automattic/jetpack/pull/30863.

## Proposed changes:

* Update the Minify concatenation service to work without WordPress.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-1xD-p2#comment-1185

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup this version of the plugin on your website;
* Turn on CSS or JS concatenation;
* In order to test that the code works without WordPress, you need to add a snippet at the top of your website's root `index.php`:

```php
if ( isset( $_SERVER['REQUEST_URI'] ) && '/_static/' === substr( $_SERVER['REQUEST_URI'], 0, 9 ) ) {
	// Page Optimize setup
	define( 'PAGE_OPTIMIZE_CACHE_DIR', false ); // Disable cache
	// paths so we can run service.php w/o WP
	define( 'PAGE_OPTIMIZE_CONCAT_BASE_DIR', __DIR__ );
	define( 'PAGE_OPTIMIZE_ABSPATH', PAGE_OPTIMIZE_CONCAT_BASE_DIR );

	require_once __DIR__ . '/wp-content/plugins/boost/serve-minified-content.php';
	exit;
}
```

* Update `require_once __DIR__ . '/wp-content/plugins/boost/serve-minified-content.php';` accordingly;
* Now open the home page and check to see that everything works as expected (styles and JS should be okay).

### CODE REVIEW

**Comment by haqadn** [comment]
Since we do have a good reason not to use wp functions, we should consistently use non-wp functions. This will give us predictable output and make debugging easier.

**Comment by thingalon** [comment]
image

Why not merge?

**Comment by dilirity** [comment]
> image
> 
> Why not merge?

It got reviewed before the parent branch in https://github.com/Automattic/jetpack/pull/30863. Since that was merged, this PR can be merged as well.

**Review by thingalon — APPROVED** [review]
👍

**Comment by thingalon** [comment]
Cherry picked to 1.9.0 in 9c915e73ef3fe345e814b9b190a50c8c0bf01135

**Pull request merged**
