### PR TITLE
Newsletter: visibility settings – remove notice

### PR DESCRIPTION
**Pull request by lezama**
Opened this PR for further discussion. Didn't even test.

Discussed with @crisbusquets that this notice makes little sense 🤔,
image

What do you all think?

Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by edanzer** [comment]
Is there any background conversation / context to check for this?

I'm assuming the idea is that, since the user has selected to send it to 'Anyone Subscribed', they know they're sending it to everyone, and showing the number of people is redundant? 

For my part, I tend to be very conservative about sending emails to readers/subscribers/customers. They can't be reversed. So for me, having a big notice that I'm about to send an email to, say, 1347 subscribers seems like something I'd want to see. It's a bit like a cautionary notice before publishing, since publishing in this case also equals hitting 'send' on emails.

**Comment by lezama** [comment]
> 1347 subscribers seems like something I'd want to see

I agree with this sentiment, it's good to see that number somewhere.
I don't like the copy too much, took me many milliseconds to parse that "*also*" refers to "on top of posting".

**Comment by crisbusquets** [comment]
> > 1347 subscribers seems like something I'd want to see
> 
> I agree with this sentiment, it's good to see that number somewhere. I don't like the copy too much, took me many milliseconds to parse that "_also_" refers to "on top of posting".

Yeah, maybe we can improve the copy to make it more clear?

Or maybe we can go back to this, and use the label to convey all the info:
- Anyone subscribed (2,019)
- Paid subscribers only (1,027)

I totally understand @edanzer's feedback, I do the same. I use Mailerlite, and the "audience selection" appears after you've prepared the email. And I think Substack doesn't even show a number.

**Comment by simison** [comment]
> I totally understand @edanzer's feedback, I do the same. I use Mailerlite, and the "audience selection" appears after you've prepared the email. And I think Substack doesn't even show a number.

They might've removed the number at some point as I remember seeing permanent "n subscribers" under each label, or then I'm mixing with Beehiiv or other services.

Anyway, I feel like it's an useful number to show, but our version is a bit too elaborate and reads less as notice rather than helpful info. @crisbusquets any thoughts between these solutions?

Screenshot 2023-08-04 at 12 22 43

Screenshot 2023-08-04 at 12 25 46

Screenshot 2023-08-04 at 12 25 02

**Comment by crisbusquets** [comment]
> > I totally understand @edanzer's feedback, I do the same. I use Mailerlite, and the "audience selection" appears after you've prepared the email. And I think Substack doesn't even show a number.
> 
> They might've removed the number at some point as I remember seeing permanent "n subscribers" under each label, or then I'm mixing with Beehiiv or other services.
> 
> Anyway, I feel like it's an useful number to show, but our version is a bit too elaborate and reads less as notice rather than helpful info. @crisbusquets any thoughts between these solutions?
> 
> Screenshot 2023-08-04 at 12 22 43 Screenshot 2023-08-04 at 12 25 46 Screenshot 2023-08-04 at 12 25 02

I think this is the right one:
1. It requires less vertical space
2. You can see the number of subscribers without having to click anything

I know we're discussing this in a P2, but what number will we show under `Everyone`? `Anyone subscribers` already include everyone that's subscribed.

I'm wondering if we should have this instead:
- Everyone
- Anyone subscribed (70)
- Paid subscribers only (30)

image

**Comment by lezama** [comment]
I would simplify copies:

Anyone subscribed => All subscribers

Paid subscribers only => Paid subscribers

**Comment by crisbusquets** [comment]
> I would simplify copies:
> 
> Anyone subscribed => All subscribers
> 
> Paid subscribers only => Paid subscribers

Works for me. This is what we had at some point (at least this is how it appears on the Newsletter LP screenshot).

**Comment by lezama** [comment]
no longer makes sense

**Pull request closed without merging**
