### PR TITLE
Jetpack Backup: Refactor component into multiple modules

### LINKED ISSUE #14065: Jetpack Backup: implement code style improvements
I'm creating this to keep track of the feedback on https://github.com/Automattic/jetpack/pull/14056 that needs to be addressed.

- [ ] Do not pass entire `backupPlanPrices` prop object to SingleProductBackupBody
- [ ] Make the appropriate propTypes required
- [ ] Do not define `backupOptions` or `upgradeTitles` on render
- [ ] Split `single-product-backup.jsx` into multiple files
- [ ] Rename `PlanPriceDisplay` to be more specific

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #14065 and prepares the Plans codebase for Jetpack Search.

#### Changes proposed in this Pull Request:
* Modularizes several components within `single-product-backup.jsx` into reusable components. 
* Use `useMemo` for generating `backupOptions` object.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No, this is a feature-complete refactor of the Plans page for Jetpack Backups.

#### Testing instructions:
1. Setup this branch of Jetpack on your site (or [use Docker](https://github.com/Automattic/jetpack/tree/master/docker#readme)).
2. Ensure that you have no Jetpack plan associated with your site. Navigate to `/wp-admin/admin.php?page=jetpack#/plans` and scroll down to the Solutions section. You should see something like the following:

> No Plans: 
>
> Screen Shot 2020-03-11 at 5 50 21 PM

> Personal Plan:
>
> Screen Shot 2020-03-11 at 5 50 30 PM

> Real-time Backup Plan:
>
> Screen Shot 2020-03-11 at 5 50 39 PM

> Professional Plan:
>
> Screen Shot 2020-03-11 at 5 50 45 PM

#### Proposed changelog entry for your changes:

* No changelog necessary.

### CODE REVIEW

**Review by gibrown — APPROVED** [review]
I don't see any problems/new-bugs with this change. Tough for me to fully eval the code changes.

There is a bug I found where the dev tools setting for the plan is not getting respected by the backups box:

Screen Shot 2020-03-16 at 10 04 06 AM

I suspect this bug existed before this change though.

**Review by roccotripaldi — APPROVED** [review]
This tests well. The code looks reasonable.
I also experienced the debug issue that @gibrown mentioned, but i don't see it as a merge blocker. We can address it in another PR.

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍

**Comment by tyxla** [comment]
A bit late to the party, but this looks great. Thanks a lot for working on it @jsnmoon 🙌

**Pull request merged**
