### PR TITLE
Switched dependency management, scripts and Travis to yarn.

### PR DESCRIPTION
**Pull request by zinigor**
Enables us to use `yarn` to manage dependencies and run scripts in Jetpack.

### CODE REVIEW

**Comment by oskosk** [comment]
One suggestion about the scripts directory name. Let's call it just `scripts` as they run with `npm` too as regular npm scripts.

**Comment by eliorivero** [comment]
Oscar and I were getting segmentation fault errors when building which turned out to be due to libsass. These steps allow to properly build:

1. fetch the latest changes in `jetpack` and `dops-components` repos. It's assumed you have one directory next to the other
2. start in `jetpack` directory
```
git checkout use/yarn
git rebase fix/node-six
cd ../dops-components
git checkout fix/undefined-cross-side
npm link
cd ../jetpack
npm link @automattic/dops-components
```
3. now you should be able to
```
yarn build
```

**Comment by dereksmart** [comment]
@zinigor @eliorivero I've updated the readme to provide instruction to install yarn.  I think this is good to merge after https://github.com/Automattic/jetpack/pull/4295 and https://github.com/Automattic/dops-components/pull/62 are merged

**Comment by eliorivero** [comment]
https://github.com/Automattic/dops-components/pull/62 is now merged

**Comment by dereksmart** [comment]
#4295 merged

**Comment by eliorivero** [comment]
I'm merging this so we can all start using yarn. That said, I think we could consolidate the yarn scripts we have into one. I'll open a new PR for that.

**Pull request merged**
