### PR TITLE
Site-Level User Profile: Show links back to WordPress.com on profile.php

### PR DESCRIPTION
**Pull request by okmttdhr**
Fixes https://github.com/Automattic/dotcom-forge/issues/8421

## Proposed changes:

This PR shows links back to WordPress.com for them to manage their WordPress.com profile. 

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Simple Classic & Default

* If you test Simple **Default** sites, set `wpcom_site_level_user_profile` option 1
* Go to `/wp-admin/profile.php`
* Observe "Contact Info > Email" is disabled and has a link to /me/account
	Screenshot 2024-07-31 at 15 27 03
* Observe "Account Management > New Password" has a link to /me/security
	Screenshot 2024-07-31 at 15 32 14

Atomic Classic

* Go to `/wp-admin/profile.php`
* Observe "Contact Info > Email" has a link to /me/account
	Screenshot 2024-07-31 at 15 25 50
* Observe "Account Management > New Password" has a link to /me/security
	Screenshot 2024-07-31 at 15 26 01

- [ ] For Atomic Default, we need to address this issue first: https://github.com/Automattic/dotcom-forge/issues/8511

### CODE REVIEW

**Comment by fushar** [comment]
Will review this first thing today.

**Comment by fushar** [comment]
I added a couple commits to use existing Core's `<p class="description"` rather than custom styles. This simplifies the code a lot. I also [updated](https://github.com/Automattic/jetpack/pull/38638/commits/d0bafe211548bce4875b9bdeadd943e1f9666f23) the JS from https://github.com/Automattic/jetpack/pull/38519 to use the same way, cc: @DustyReagan.

**Review by fushar — DISMISSED** [review]
Tested and it looks good in all cases:

### Contact Info

|Simple|Atomic|
|-|-|
|image|image|

### Account Management

|Simple|Atomic|
|-|-|
|image|image|

**Comment by fushar** [comment]
@okmttdhr, note that I removed the email description on Simple Classic:

image

while testing, I found that the wording is confusing: it says "If you change this" but the field itself can't be changed.

**Comment by okmttdhr** [comment]
> @okmttdhr, note that I removed the email description on Simple Classic:
> while testing, I found that the wording is confusing: it says "If you change this" but the field itself can't be changed.

Make sense :) Thank you for your work on this PR!

**Review by fushar — APPROVED** [review]
Retested and it still works fine.

**Pull request merged**
