### PR TITLE
Map block: reimplement frontend in vanilla JS

### PR DESCRIPTION
**Pull request by sgomes**
The Map block frontend currently reuses the editor component. This means that it loads an incredibly large amount of JS; between `@wordpress` packages, dependencies, and the mapbox script, we're talking upwards of 600KB compressed for potentially a single block.

A lot of the complexity in the editor component seems to come from the editing aspects, which means that it should be possible to reimplement the viewing (i.e. the frontend) code in a much leaner way.

This PR reimplements the frontend completely in vanilla JS, in less than 230KB compressed, the vast majority of which is the unavoidable mapbox script (at 200KB compressed).

## Proposed changes:
* Replace React-based `view.js` with a vanilla `view.js`
* Extract some common mapbox utilities to a new `mapbox-utils`
* Drop dependency on lodash, by adding a small `debounce` util to `extensions/shared/debounce.js`
* Update build-time checks to remove allowlist for the Map block

Note: added @Automattic/apex as a reviewer, since the team is currently planning/working on changes to the Map block.
Also added @Automattic/jetpack-crew as a reviewer, since the PR touches build files to remove an allowlist entry.

### Other information:

- N/A Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None; this should transparently reimplement the existing functionality, without adding or removing anything.

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
- Create a page with several map blocks, setting different options on each of them, and making sure at least one of them has multiple markers.
- Smoke-test the map blocks in the frontend, making sure that everything works correctly.

### CODE REVIEW

**Review by TimBroddin — APPROVED** [review]
I smoke tested this with several maps on my sandbox, and it looks perfect to me.

Nice job on reducing the code needed on the frontend!

**Comment by sgomes** [comment]
Thank you for the quick review, @TimBroddin! 🙂

**Comment by sgomes** [comment]
I changed the status on the PR, as this now needs a final review by @Automattic/jetpack-crew because of the changes to the block assets allowlist.

**Review by anomiex — APPROVED** [review]
Needs a trunk merge, but since there are no conflicts hopefully that won't remove the approval.

**Comment by sgomes** [comment]
That's odd, the PR doesn't seem to register that I've updated the branch with a trunk merge. It still shows as 302070a77a6dd436f9934fa0c89dcecbb83723a6 even though the branch is now at a53f9038a1c5249c37a6e76d978c280044632960.

Any clue what I might have done wrong, @anomiex?

Edit: I think this may be a GitHub issue, as I tried restarting the relevant job and it seems to be stuck waiting for a runner.

Edit 2: merged again after a new trunk commit, this time it seems to be working!

**Comment by sgomes** [comment]
Thank you for the review, btw, @anomiex ! 👍

**Pull request merged**
