### PR TITLE
Social: Remove media auto-conversion toggle UI

### PR DESCRIPTION
**Pull request by manzoorwanijk**
We are getting rid of media auto conversion UI because we want to enable it by defaul.

## Proposed changes:

* Remove the media auto-conversion toggle from Social and Jetpack settings

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to Social and Jetpack settings pages
* Confirm that you no longer see the auto conversion toggle

Nuked
image
image

### CODE REVIEW

**Comment by spsiddarthan** [comment]
Changes look good, but I have a feeling this can't be merged yet. More details on p1721824105249519/1721811464.913439-slack-C02JJ910CNL.

**Review by spsiddarthan — COMMENTED** [review]
This looks good! I couldn't test on Atomic to see that the toggle is gone, but it should work there as well. Please test there once if you haven't already

This is ready to merge, but is blocked by D156483-code which needs to be accepted before we can merge this

**Comment by manzoorwanijk** [comment]
Works on Atomic

image

**Comment by gmjuhasz** [comment]
@manzoorwanijk do we clean up the store and functions like `isAutoConversionEnabled` in another change?

**Comment by manzoorwanijk** [comment]
> @manzoorwanijk do we clean up the store and functions like `isAutoConversionEnabled` in another change?

Yes, we have sub-tasks for that. I didn't want to create a single massive PR.

**Review by gmjuhasz — APPROVED** [review]
This looks good!

**Pull request merged**
