### PR TITLE
Instant Search: Make display order match tab order on mobile.

### LINKED ISSUE #23367: Search: Tab order mismatch in search modal (mobile)
### Impacted plugin

Jetpack

### Steps to Reproduce

In the mobile view, the flex order of links in the search results is altered to place the thumbnail first. Because there are three links in each result, this results in a tab order mismatch between the visual sequence and the DOM order.

The visual order is thumbnail > title > breadcrumb title; the tab order is title > breadcrumb title > thumbnail.

The visual order must match the tab order.

Ideally, the thumbnail should be wrapped as a block-level link along with the post title, with an empty alt attribute. With that, the visible order does not matter, as it's a single object regardless. This would also help reduce the duplication of links and tedium of navigating the search results using a keyboard.

### Notes
_This issue was surfaced to team 51 by an a11y contractor working on a partner site._

### PR DESCRIPTION
**Pull request by a8ck3n**
We do this by removing the CSS order attribute on the image. This means the image will be shown below the title instead of above it. For now, we should consider accessibility before styling.

Fixes #23367.

#### Changes proposed in this Pull Request:

Just removing the custom ordering from the CSS. If we want to put the image first in our mobile results, we should explore a way to do this that is accessible.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Visit a site with Jetpack Search enabled.
2. Open the search overlay with `?s=&result_format=expanded`.
3. Resize the window until the mobile view kicks in.
4. Confirm the tab order is: title, permalink, image.

Composite

### CODE REVIEW

**Review by dognose24 — COMMENTED** [review]
LGTM! However, I am curious about if there was a specific reason to put the post image above the post title. By the way, I could be confused about which post owns the image between sibling posts.

截圖 2022-08-09 下午11 31 29

**Comment by a8ck3n** [comment]
> LGTM! However, I am curious about if there was a specific reason to put the post image above the post title. By the way, I could be confused about which post owns the image between sibling posts.

I don't believe it was anything beyond personal choice. I agree that it can be a bit unclear about which post an image belongs to though. I'd like to propose a few styles changes in a follow-up PR to make this clearer. For this PR though, the goal is just to fix the a11y issue where the tab order and the display order do not match.

@dognose24 — Any thoughts? Can you give me a thumbs-up to merge? 🙇

**Review by annacmc — DISMISSED** [review]
LGTM 👍 happy to approve and unblock you on this one & good idea to approach the image order/styling question in a different/followup PR, seems like a good thing to do as I also agree the post/image style could be improved upon 😄

**Comment by dognose24** [comment]
> I don't believe it was anything beyond personal choice. I agree that it can be a bit unclear about which post an image belongs to though. I'd like to propose a few styles changes in a follow-up PR to make this clearer. For this PR though, the goal is just to fix the a11y issue where the tab order and the display order do not match.

Yes! @a8ck3n The way you proposed in this PR seems to be the only solution to the accessibility for now. However, I would ask for more thoughts to avoid breaking the original intention of the image position by accident. That's why I did not give you the thumbs-up yet: you did nice work!

**Comment by a8ck3n** [comment]
I had to fix up the versions and rebase which caused my approval to be dismissed. No code changes though so I'd love another approval if you have a minute! — @annacmc and/or @dognose24 — Thanks!

**Comment by a8ck3n** [comment]
> However, I would ask for more thoughts to avoid breaking the original intention of the image position by accident.

Yeah, I understand. I can't see anything breaking as a result of the positioning change. I'm going to open a separate issue for some new styling changes though. Either some more spacing between results to make things clearer OR maybe we could alternate the background colour for each result on smaller screens where spacing is less effective.

**Review by annacmc — APPROVED** [review]
👍

**Pull request merged**
