### PR TITLE
Add tracks for impressions of jitms

### PR DESCRIPTION
**Pull request by withinboredom**
Records a jitm impression

#### Testing instructions:

* View a jitm, see the event in tracks.

#### Proposed changelog entry for your changes:

NA

### CODE REVIEW

**Comment by dereksmart** [comment]
Failing CI tests are not related to changes.

**Comment by zinigor** [comment]
I'm trying to rebase the changes on the latest master to fix Travis, and I end up with a clean working dir. @withinboredom have you applied these changes in a different PR by any chance?

**Comment by ebinnion** [comment]
I'm not seeing his changes in the master of `class.jetpack-jitm.php`, so I don't think that they've been merged in a separate PR.

**Comment by eliorivero** [comment]
I've rebased master onto this branch, let's see if it passes Travis this time.

**Pull request merged**
