### PR TITLE
Assistant: Fix product price without intro offer  

### PR DESCRIPTION
**Pull request by monsieur-z**
#### Changes proposed in this Pull Request:

This PR corrects the price shown in the Assistant product cards when no intro offer is available.

#### Jetpack product discussion

Context: p8oabR-QB-p2#comment-6247

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

- Update your currency to one that doesn't have an intro offer for Backup or Security, such as Turkish lira (TRY)
- Spin up a new JN site with this branch
- Complete the connection flow, getting Jetpack Free
- Visit `/wp-admin/admin.php?page=jetpack#/recommendations/product-suggestions`
- Check that for both Backup and Security, the prices matche what you see in the checkout page. Prices are shown by month in the former, and by year in the latter, so you'll have to divide/multiple by 12.

### CODE REVIEW

**Review by jboland88 — APPROVED** [review]
This LGTM and tests as described.
The prices I see on the product cards match the prices I see when I am viewing the products on the checkout page.

**Comment by sdixon194** [comment]
Hmm, something still seems off for me I think. This is what I see on the recommendations page:
Screen Shot on 2022-05-02 at 11:09:26

When I select backup, the original price is correct at 1,139.40 before the 1 year discount is applied (I'm not sure if that's supposed to be reflected on the recommendation page?)


Screen Shot on 2022-05-02 at 11:10:05


However if I choose security, it's the inverse - the original price is incorrect, but the discounted one year price is. 

Screen Shot on 2022-05-02 at 11:10:59

I'm not sure which one is supposed to be the right case, since neither plan shows a discount on the recommendation page.

**Comment by monsieur-z** [comment]
@sdixon194, from the first capture it looks like somehow no coupon was created. However a coupon is applied when you checkout Backup. Is it possible that this coupon was lingering in the cart?

Note that we don't show the stroke-through price in the Assistant if the only discount is the introductory offer.

Here's what I'm seeing on my side, which seems okay:
Screen Shot 2022-05-02 at 4 40 03 PM
screenshot
screenshot (1)

**Review by sdixon194 — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to release branch in 5ff19bf6e5f972291addd028784e51413b7b38e4

**Pull request merged**
