### PR TITLE
Adds a filter for hooking when wpcom color schemes are loaded

### PR DESCRIPTION
**Pull request by cpapazoglou**
Builds on https://github.com/Automattic/jetpack/pull/17828

#### Changes proposed in this Pull Request:

* Adds a filter for hooking when wpcom color schemes are loaded

#### Testing instructions:

* No change is expected at all follow testing instructions on https://github.com/Automattic/jetpack/pull/17828

### CODE REVIEW

**Comment by cpapazoglou** [comment]
@frontdevde I created this as a follow up of https://github.com/Automattic/jetpack/pull/17828. You may merge it in your branch if you see fit. Otherwise I will merge it after yours is merged.

**Comment by frontdevde** [comment]
> You may merge it in your branch if you see fit. Otherwise I will merge it after yours is merged.

Let's merge it after that one is merged. We could've merged https://github.com/Automattic/jetpack/pull/18010 into https://github.com/Automattic/jetpack/pull/17828 as well. But at this stage let's just get https://github.com/Automattic/jetpack/pull/17828 in and not risk anything blocking in Jetpack review by more stuff going in. Should be easy enough to merge after the fact.

**Review by frontdevde — DISMISSED** [review]
LGTM 👍

**Review by obenland — CHANGES_REQUESTED** [review]
I'm not sure this code has the effect you're looking for. To allow other plugins to hook into something you want to use `do_action( 'jetpack_color_schemes_loaded' );`

https://developer.wordpress.org/plugins/hooks/actions/
https://developer.wordpress.org/plugins/hooks/filters/

What would this action be used for?

**Comment by cpapazoglou** [comment]
We are closing this 554-gh-Automattic/wpcomsh#issuecomment-744419969

**Pull request closed without merging**
