### PR TITLE
Components / My Jetpack: update Spinner component

### LINKED ISSUE #23115: My Jetpack: update spinner component
In a later version of My Jetpack (and Jetpack products in general), we should update the spinner component to match the new Gutenberg styles:

https://wordpress.github.io/gutenberg/?path=/story/components-spinner--default

image

### PR DESCRIPTION
**Pull request by retrofox**
This PR stops using the Jetpack Spinner component by the core one. It updates the ActionButton of the `Components` pkg, and the Checkout button of My Jetpack.

Fixes https://github.com/Automattic/jetpack/issues/23115

#### Changes proposed in this Pull Request:

* Components / My Jetpack: update Spinner component

#### Testing instructions:

* Using Storybook
* Confirm you see the core Spinner in the following `JS PACKAGES / Components / Action Button` story

before | after
------|------
image | image

Confirm you see the `Checkout button` ok when it's loading.

https://user-images.githubusercontent.com/77539/156586873-288d46a0-2d95-4f68-b3f1-48b411e4ca83.mov

### CODE REVIEW

**Review by oskosk — APPROVED** [review]
LGTM

**Comment by keoshi** [comment]
So nice! Thanks for updating this so quickly.

**Comment by jeherve** [comment]
@retrofox Looks like this still needs committing to WordPress.com. Could you look into it?

Thanks!

**Comment by retrofox** [comment]
> @retrofox Looks like this still needs committing to WordPress.com. Could you look into it?

👍

**Comment by retrofox** [comment]
> Great news! One last step: head over to your WordPress.com diff, D75997-code, and commit it.

r243322-wpcom

**Pull request merged**
