### PR TITLE
Show an error when one is encountered while rendering a payment button

### PR DESCRIPTION
**Pull request by chrismccluskey**
Fixes 217-gh-automattic/gold

## Proposed changes:

* Adds a simple `render_button_error( $wp_error )` function which will either return a simple "Sorry! This product is not available for purchase at this time" message with an HTML comment showing the error code or a detailed error message if the reader can edit the post. 
* Changes early `return` statements to `return $this->render_button_error( new WP_Error( $code, $message ) )` so that an error is returned instead of nothing being returned.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Download this to your sandbox, or run locally in docker. Alternatively, use JN but be prepared to SSH in to make changes to files.
* Examine the `class-jetpack-memberships.php` file and add some code to trigger each error message. For example, you can `unset( $attributes['planId'] )` to trigger the first error, and change `$product = get_post( $plan_id )` to `$product = get_post( 100 + $plan_id )` to trigger the second error. Alternatively, if you know how to trigger these error messages without altering code, do that instead.
* View a page with a payment button (e.g., a page with a paid content block) in a private window. You should see a generic error message.
Screenshot 2023-11-29 at 1 25 49 PM
* Inspect the HTML element containing the generic error message. You should see `<!-- Jetpack Memberships Error: jetpack-memberships-rb-xxx -->` where `xxx` is a 3-6 character error code.
Screenshot 2023-11-29 at 1 25 58 PM
* View this page as a site admin or editor of the site. You should now see a more detailed error message.
Screenshot 2023-11-29 at 1 26 08 PM

### CODE REVIEW

**Review by chrisfromthelc — DISMISSED** [review]
I got some unexpected results when logged in as an admin.

You said "View a page with a payment button (e.g., a page with a paid content block)", but those are two different blocks in the editor, so I tried both.

When looking as non-logged-in with a private window:

Screenshot 2023-12-07 at 8 17 21 PM

When looking as a logged-in admin:

Screenshot 2023-12-07 at 8 13 35 PM

**Comment by millerf** [comment]
@chrisfromthelc Unless I am mistaken, what I see makes sense: when logged in as an admin, you will get the specific error (Jetpack memberships error), while the paid-content button is fully accessible and let you see the content.

Can you expand on what you see as an issue?

**Comment by chrisfromthelc** [comment]
> @chrisfromthelc Unless I am mistaken, what I see makes sense: when logged in as an admin, you will get the specific error (Jetpack memberships error), while the paid-content button is fully accessible and let you see the content.
> 
> Can you expand on what you see as an issue?

Seeing the potential content on the front end is fine, but if we're displaying an error state to the user in both cases, and to the admin for the payment button, we should probably also display some sort of error to the admin on the paid content block. The content could still show, just have a note above or below to indicate an issue like the button.

**Review by millerf — APPROVED** [review]
WFM. I'll let @chrisfromthelc approve as he requested changes

**Pull request merged**
