### PR TITLE
My Jetpack: Add Product Cards Section component

### LINKED ISSUE #22286: My Jetpack: Introduce a general <ProductCardsSection/> component
This component will eventually become the container for the [Product cards](https://github.com/Automattic/jetpack/issues/22287) offering complex feature activation/deactivation/management functionality.

* It should be able to incorporate the Cards layout as shown in p9dueE-47u-p2. Please check the codepen there.

image

### PR DESCRIPTION
**Pull request by renatoagds**
Closes #22286

#### Changes proposed in this Pull Request:

* Add `ProductCardsSection` component.
* Add one card component for each product that we have, to make easy each implementation without conflicts.
* Fix some points in `ProductCard` layout.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Goes into `storybook`.
* Run it
* Visit `My Jetpack / Product Cards Section` story.

or

* Activate `My Jetpack` module.
* Build `My Jetpack` module.
* Visit `My Jetpack` page.

#### Layout

Screen Shot 2022-01-21 at 18 11 14

### CODE REVIEW

**Comment by retrofox** [comment]
when the viewport narrows the button looks broken

Something we can polish in follow-up PRs, though.

**Comment by oskosk** [comment]
LOOKING AWESOME. Let's make all the name and description prop strings be wrapped in `__( ' ' )` from `@wordpress/i18n`

**Review by oskosk — APPROVED** [review]
Feedback can be addressed in future PRs.

**Comment by oskosk** [comment]
> LOOKING AWESOME. Let's make all the name and description prop strings be wrapped in __( ' ' ) from @wordpress/i18n

I'll do this on a follow-up pr

**Pull request merged**
