### PR TITLE
Sharing: remove Publicize section in WP Admin > Settings > Sharing

### PR DESCRIPTION
**Pull request by eliorivero**
This PR brings parity between the Publicize settings in WP Admin in wpcom and jp sites.

#### Changes proposed in this Pull Request:

* remove Publicize section in WP Admin > Settings > Sharing

captura de pantalla 2019-02-08 a la s 18 48 54

#### Testing instructions:

* Ensure Jetpack is connected and Publicize is active
* go to WP Admin > Settings > Sharing
* the Publicize section should look like the one above

#### Proposed changelog entry for your changes:

* The Publicize section in WP Admin > Settings > Sharing was removed. The section to configure sharing buttons is still available. Users can continue configuring Publicize connections in the dedicated page in WordPress.com.

### CODE REVIEW

**Comment by simison** [comment]
We're currently opening this page on a new tab from Gutenberg Publicize sidebar when adding new connection:

https://github.com/Automattic/wp-calypso/blob/7e1f7ba916739231ceeefbb4e70d15ee24b70550/client/gutenberg/extensions/publicize/settings-button.jsx#L32-L64

Let's make sure to upgrade sidebar to open Calypso instead of landing them to this intermediate page. We'll also need to make messaging clear in the sidebar so that folks know to expect to land on wp.com

cc @scruffian

**Comment by jeherve** [comment]
This will need a rebase I'm afraid.

**Comment by eliorivero** [comment]
@jeherve rebased, thank uu.

@simison thanks for your continued help! I've opened a companion PR https://github.com/Automattic/wp-calypso/pull/30705 that should now get the site fragment with the addition I've just added to this PR https://github.com/Automattic/jetpack/pull/11314/files#diff-d24019d250171c53680546ef0b1164e2R552

**Review by jeherve — DISMISSED** [review]
I tested this and it seems to work well.

However, since we don't load the Publicize UI at all anymore, this revealed an existing bug that I believe only appeared when both the Publicize and Likes modules were off, but the Sharing module was on; the Sharing module itself never loads the CSS that styles the wrapper around the sharing page (see #9952). To make sure the page is always styled, something like this should help:

```diff
diff --git a/modules/sharedaddy/sharing.php b/modules/sharedaddy/sharing.php
index 1049d82e6..57b353ecc 100644
--- a/modules/sharedaddy/sharing.php
+++ b/modules/sharedaddy/sharing.php
@@ -51,6 +51,11 @@ class Sharing_Admin {
 		wp_enqueue_style( 'social-logos' );
 		wp_enqueue_script( 'sharing-js-fe', WP_SHARING_PLUGIN_URL . 'sharing.js', array(), 4 );
 		add_thickbox();
+
+		// On Jetpack sites, make sure we include CSS to style the admin page.
+		if ( ! defined( 'IS_WPCOM' ) || ! IS_WPCOM ) {
+			Jetpack_Admin_Page::load_wrapper_styles();
+		}
 	}
 
 	public function admin_init() {
```
(I added the `IS_WPCOM` check so the changes can be merged back to WordPress.com, since `Jetpack_Admin_Page` does not exist on WordPress.com)

Do you want to add this to your PR, or should we merge this and fix that issue in another PR? Both work for me 👍

**Comment by eliorivero** [comment]
Thanks for pointing that @jeherve! Totally missed it. I've added those lines to the relevant file.
This now needs a new approval.

**Review by jeherve — APPROVED** [review]
Excellent! This should be good to go now!

Since the sharing file is a bit out of sync, you may have to apply the diff manually on WordPress.com to get this to work. :(

**Comment by eliorivero** [comment]
Cool. Patch created in D24320-code.

**Review by brbrr — APPROVED** [review]
Looks good :shipit:

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.0` in 4d63467bfd4dd201544436bd231a249ec5a6795a

**Pull request merged**
