### PR TITLE
Remove modal for paid features

### LINKED ISSUE #12116: Remove the modal for paid plan features
[Screenshot](https://cloudup.com/cKp1Bexwuyy)

This is a task in the master thread p1HpG7-6vh-p2

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #12116

#### Changes proposed in this Pull Request:

* removes all the code and options related to the modal for paid features

#### Testing instructions:

* Go to Jetpack settings, everything should work normally.
* There's nothing to test because everything was removed.

#### Proposed changelog entry for your changes:

* Not needed. Part of Module Prioritization

### CODE REVIEW

**Review by oskosk — COMMENTED** [review]
Seems like `_inc/client/scss/style.scss` still contains a reference to `/components/welcome-new-plan/style.scss` which is removed in this PR, thus the build is not working

**Review by jeherve — APPROVED** [review]
This looks ok. I spotted an error when clicking on the upgrade buttons in the Plans screen (`Uncaught TypeError: Cannot read property 'props' of undefined`, pointing to `clickHandler()` in the `TopButton` component, but that doesn't seem related to this PR.

👍 🚢

**Review by oskosk — APPROVED** [review]
LGTM! 

@jeherve Your observation is addressed by #12136

**Review by MichaelArestad — APPROVED** [review]
Makes me a little sad, but works as expected.

**Pull request merged**
