### PR TITLE
e2e tests: updates to the recommendation assistant tests

### LINKED ISSUE #32467: Jetpack E2E Test Failure: Recommendations (Jetpack Assistant)
### Impacted plugin

Jetpack

### Quick summary

The specs/post-connection/recommendations.test.js test has been failing for about a week now. [Example here](https://github.com/Automattic/jetpack/actions/runs/5859764017/attempts/1). 

> 1) specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) ====== page.waitForLoadState: Timeout 20000ms exceeded.

It seems it's waiting for some kind of recommendation assistant that either isn't appearing, or it's checking for the wrong element. 

### Steps to reproduce

Open any PR that touches jetpack-the-plugin, see the test fail.	

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #32467

## Proposed changes:

Making some changes to the tests so they start passing again.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Internal reference: p1691598965621699-slack-C03QNBQKG73

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

Do the tests pass?

### CODE REVIEW

**Comment by jeherve** [comment]
@adimoldovan Would you have a bit of time to look at this, by any chance? You can see the videos of the failures in that PR:
p1691660107128739-slack-C1Y1F7ZM1

I don't really understand why it started failing now. Something seems off with how the page loads (and then reloads), but I do not understand what exactly. Do you have any idea?

**Comment by adimoldovan** [comment]
> @adimoldovan Would you have a bit of time to look at this, by any chance? You can see the videos of the failures in that PR: p1691660107128739-slack-C1Y1F7ZM1
> 
> I don't really understand why it started failing now. Something seems off with how the page loads (and then reloads), but I do not understand what exactly. Do you have any idea?

Hi @jeherve, I checked this out, here's what I found:
- it seems the failure is happening in the `waitForNetworkIdle()`, after the page reload.
- I ran them locally on my machine and they passed. So probably increasing the timeout would make them pass in CI too. But why are they failing all of a sudden in such a consistent way? A performance degradation? I would check what requests are being made on that page reload and see if there's a problem there.
- I commented out all the `await recommendationsPage.waitForNetworkIdle()` with https://github.com/Automattic/jetpack/pull/32391/commits/568d60dd4aefb618fcecce517908d9d09986a435, and [they passed](https://github.com/Automattic/jetpack/actions/runs/5877482459/job/15939794874?pr=32391#step:11:77) (I re-ran the jobs a few times, and they passed consistently). I don't know why there's this explicit wait for network idles there and if it's really important to this test. The page.reload() has an implicit `waitForDomContentLoaded`. I'm also wondering if the page reload is important to the test.

**Comment by jeherve** [comment]
> But why are they failing all of a sudden in such a consistent way? A performance degradation? I would check what requests are being made on that page reload and see if there's a problem there.

That was my question as well. I couldn't find anything that changed in Jetpack itself, but the WordPress 6.3 release came out around that time, and I think that's what triggered the change.

>  So probably increasing the timeout would make them pass in CI too.

I tried that in 77a4b6a7204b8fc9a88064331e537d0e5170daaf, tests failed.

> I commented out all the await recommendationsPage.waitForNetworkIdle() with https://github.com/Automattic/jetpack/commit/568d60dd4aefb618fcecce517908d9d09986a435, and [they passed](https://github.com/Automattic/jetpack/actions/runs/5877482459/job/15939794874?pr=32391#step:11:77) (I re-ran the jobs a few times, and they passed consistently). I don't know why there's this explicit wait for network idles there and if it's really important to this test.

Should we merge this PR with this change, since this seems to work for now?

**Comment by adimoldovan** [comment]
> Should we merge this PR with this change, since this seems to work for now?

I think you should merge it like this, yes.

**Comment by anomiex** [comment]
Note playwright's eslint rules [discourage waiting for network idle](https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/no-networkidle.md) too, so removing it would be good.

**Review by anomiex — APPROVED** [review]

**Pull request merged**
