### PR TITLE
Added a loading container when stats are being loaded.

### LINKED ISSUE #9141: Dashboard stats flashing no stats on render.
introduced in #9108, this is now happening on first page loads of the Jetpack Dashboard: 

stats

### PR DESCRIPTION
**Pull request by zinigor**
Fixes #9141 

#### Changes proposed in this Pull Request:
* Adds a loading container instead of the stats block when stats are still being fetched.

#### Testing instructions:
* Refresh the Dashboard with stats visible.
* See that the empty stats block shows up until stats are loaded.
* Check this PR out.
* See that the stats block disappears when stats are loading.

This is still in progress, we need to display a spinner of some sort there.

screenshot from 2018-03-30 15-00-04

#### Proposed changelog entry for your changes:
* Fixed the flashing missing stats notice on load.

### CODE REVIEW

**Comment by dereksmart** [comment]
> we need to display a spinner of some sort there.

We were loading one that is already included in the component before.  Can we just reuse that?

**Comment by zinigor** [comment]
Good point Derek!

I have added the same spinner to the container and set its height to fit:
screenshot from 2018-03-30 16-05-00

**Comment by rickybanister** [comment]
I think we can make this a little bit slicker. 

If we only set the height of the card big enough to fit the spinner, there will be a pretty nasty jump of the content once stats do load. I think we might want to take an approach more like lazy loading images where we reserve the entire size of the stats box while it loads. That way if you scroll down past it as it's loading, things won't jump on you. 

WordPress.com seems to have gotten a lot faster lately, I could barely get a loading state for stats to show up on my junky home network. That made me wonder if we could dip our toe into server-side-rendering of the stats box's initial state some day?

That said, on .com we show all the UI controls and simply show the spinner in the middle of where the graphs appear. That would be better, could we just mirror that more directly?

**Comment by keoshi** [comment]
I like that, @zinigor! One question: isn't the stats block the same height in every device? Meaning its size doesn't change that much, except maybe for browser specifics?

If that's the case, I'd advocate for the loading container to have more or less the same final height, so the page doesn't jump once the stats are loaded. Is that fair? I even think we could do without the white container and have it be transparent.

**Comment by zinigor** [comment]
Let's close this in favour of much better #9213

**Pull request closed without merging**
