### PR TITLE
 Untangle: show existing homepage when live-previewing another block theme

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- https://github.com/Automattic/dotcom-forge/issues/5309

This PR prevents live preview feature from always previewing the Index / Blog Home / Front Page template, when the site is part of the nav redesign.

Without this PR (in production), even if the current "Your homepage displays" setting is set to a static page, previewing a block theme will always preview the target theme's "home" template (Index / Blog Home / Front Page).

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Enable this branch in Jetpack Beta Tester's WordPress.com Features. (Note that you must set define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true ); to your wp-config.php)
2. Go to Settings -> Reading.
3. Set the "Your homepage displays" to a static page.
4. Go to Appearance -> Themes.
5. Install and Live Preview a block theme.
6. Verify that you are seeing the same static page (but in the target theme).
7. Turn off your A8C proxy (to test existing production behavior).
8. Make sure to not include the site in the early release list (`/wp-admin/options.php`, ensure `wpcom_classic_early_release` is unset)
9. Refresh the page
10. Verify that you are now seeing the theme's home template (Index / Blog Home / Front Page) (production behavior).

Appendix

"Live Preview" means this button (appears after you install the theme):

image

### CODE REVIEW

**Review by DustyReagan — COMMENTED** [review]
This is working for me on the "Twenty Twenty-Four" theme. However, it is not working for me on the "Furniture Hub" or "Furnishop" themes. And it breaks the live preview of the "Bedrock" theme. I'm unsure why.

**Comment by fushar** [comment]
@DustyReagan Thanks for testing!

> However, it is not working for me on the "Furniture Hub" or "Furnishop" themes. And it breaks the live preview of the "Bedrock" theme.

I checked and they have a Front Page template. By [definition](https://developer.wordpress.org/themes/basics/template-hierarchy/#front-page-display):

> The front-page.php template file is used to render your site’s front page, whether the front page displays the blog posts index (mentioned above) or a static page.

So, this is expected. This will be the behavior in JN sites as well.

---

> And it breaks the live preview of the "Bedrock" theme. I'm unsure why.

Looks like it's related to the current p1709623282062709-slack-C02FMH4G8 🥲 it can be reproduced in production by:

- Activate Bedrock
- Set a static page as homepage
- Open Site Editor
- See blank page

I'll investigate it a bit more, but it definitely is not related to this PR.

**Comment by arthur791004** [comment]
Looks like the patterns of the previewing theme are not loaded 🤔

image

**Comment by fushar** [comment]
To close the loop, the issue is logged here: 

- https://github.com/WordPress/gutenberg/issues/59634

**Review by DustyReagan — APPROVED** [review]
Seeing as the "Bedrock" theme is a separate issue, and the behavior of the "Furniture Hub" and "Furnishop" themes is expected. This PR looks good to me! 👍

**Pull request merged**
