### PR TITLE
Connection: include to define wp_generate_password if necessary

### LINKED ISSUE #23835: Fatal error PHP 8.1
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install [Passwords Evolved](https://wordpress.org/plugins/passwords-evolved/) plugin
2. Install Jetpack 10.7 - Connect - Select Free plan
3. Upgrade to Jetpack 10.8
4. Navigate o a dashboard or front end page

### A clear and concise description of what you expected to happen.

Everything to be as normal, no errors

### What actually happened

Page displays "Fatal error occurred on this site" (or similar) message created by WordPress Fatal Error handler.

### Other information

`PHP Fatal error:  Uncaught InvalidArgumentException: Container doesn't have a value stored for the "password.generator" key. in /.../wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php:94
Stack trace:
#0 /.../wp-content/plugins/passwords-evolved/src/Plugin.php(79): PasswordsEvolved\DependencyInjection\Container->offsetGet()
#1 /.../wp-content/plugins/passwords-evolved/pluggable.php(59): PasswordsEvolved\Plugin->get_password_generator()
#2 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(132): wp_generate_password()
#3 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(37): Automattic\Jetpack\Connection\Client::build_signed_request()
#4 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(453): Automattic\Jetpack\Connection\Client::remote_request()
#5 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(51): Automattic\Jetpack\Connection\Client::wpcom_json_api_request_as_blog()
#6 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(67): Automattic\Jetpack\Search\Plan->get_plan_info_from_wpcom()
#7 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(71): Automattic\Jetpack\Search\Plan->get_plan_info()
#8 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(97): Automattic\Jetpack\Search\Plan->get_plan_info()
#9 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/initializers/class-initializer.php(208): Automattic\Jetpack\Search\Plan->supports_search()
#10 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/initializers/class-initializer.php(51): Automattic\Jetpack\Search\Initializer::is_search_supported()
#11 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(233): Automattic\Jetpack\Search\Initializer::init()
#12 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(169): Automattic\Jetpack\Config->enable_search()
#13 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(114): Automattic\Jetpack\Config->ensure_feature()
#14 /.../wp-includes/class-wp-hook.php(307): Automattic\Jetpack\Config->on_plugins_loaded()
#15 /.../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#16 /.../wp-includes/plugin.php(474): WP_Hook->do_action()
#17 /.../wp-settings.php(450): do_action()
#18 /../wp-config.php(118): require_once('/.../...')
#19 /.../wp-load.php(55): require_once('/.../...')
#20 /.../wp-admin/admin.php(34): require_once('/...')
#21 /.../wp-admin/index.php(10): require_once('/...')
#22 {main}
  thrown in /.../wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php on line 94`

Same happened with update to Jetpack 10.1, bit later fixed. See https://github.com/Automattic/jetpack/issues/21165

### Operating System

Linux

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #23835

#### Changes proposed in this Pull Request:

This may not be the right approach, but may be a workaround for the problem described in #23835.

I worry a bit about trying to include a core file from the package directly, ideally we wouldn't have to do that. I don't know if that could ever be an issue.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

I wasn't able to reproduce the original issue, but this may be worth trying:

1. Install and connect Jetpack.
2. Go to Plugins > Add New
3. Install the Passwords Evolved plugin.
4. Click to activate it.
5. Check your logs to ensure no Fatal happened.

### CODE REVIEW

**Comment by fgiannar** [comment]
Many thanks for trying to fix this, Jeremy and apologies for the delayed reply.

Looking at the [corresponding bug](https://github.com/Automattic/jetpack/issues/23835) I noticed that Kraft managed to resolve this the first time by [moving the external package tracker request to shutdown.](https://github.com/Automattic/jetpack/pull/21243)

The issue was indeed resolved but then came back because of another external request, introduced by the search package this time, aimed to fetch the [search plan info from WPCOM](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/class-plan.php#L44) and triggered [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/initializers/class-initializer.php#L51). 

Therefore I wonder if it would make sense to reach out to @Automattic/jetpack-search and discuss a similar approach.

**Comment by jeherve** [comment]
> introduced by the search package this time, aimed to fetch the [search plan info from WPCOM](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/class-plan.php?rgh-link-date=2022-06-23T07%3A32%3A01Z#L44) and triggered [here](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/initializers/class-initializer.php?rgh-link-date=2022-06-23T07%3A32%3A01Z#L51).

Nice!

I have to ask, how did you trace the problem back to this new call?

> I wonder if it would make sense to reach out to https://github.com/orgs/Automattic/teams/jetpack-search and discuss a similar approach.

Yeah, that seems like the best course of action here! 

Maybe we should also add a test to ensure that this doesn't happen again in the future.

**Comment by fgiannar** [comment]
>  have to ask, how did you trace the problem back to this new call?

Based on the corresponding fatal logs provided in #23835 (under Other Information).

> Maybe we should also add a test to ensure that this doesn't happen again in the future.

That would be great, however given this is so hard to reproduce I'm not sure how we could structure it. Even an e2e test with the Passwords Evolved plugin activated could prove flaky given we never managed to find a scenario where this is always reproducible. If any better ideas come to mind pls let me know and I'll be happy to work on this.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Pull request closed without merging**
