### PR TITLE
E2E tests: add simple payment test

### PR DESCRIPTION
**Pull request by brbrr**
#### Changes proposed in this Pull Request:

* Adds Simple Payment e2e test

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.
Internal ref: p9dueE-Ju-p2

#### Testing instructions:

* Check the Travis CI e2e job
* Try running these tests locally:
  - Follow these instructions to decrypt config file: [master/tests/e2e/README.md#test-configuration ](https://github.com/Automattic/jetpack/blob/master/tests/e2e/README.md#test-configuration ) 
  - You can use your local install or a JN site for this. 
  - The test expects `wordpress` to be your site's login/password, but you can override these by `WP_PASSWORD` & `WP_USERNAME` env variables.
  - run `WP_BASE_URL="YOUR_SITE_URL" yarn test-e2e`

The test itself should work for both already connected sites with a purchased plan, and for newly created, not connected sites. 

#### Proposed changelog entry for your changes:

* N/a

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I'm running into this error when I try to run the tests:

```
❯ WP_BASE_URL="http://jeherve.eu.ngrok.io/" yarn test-e2e                               jeherve@jer
yarn run v1.15.2
$ NODE_CONFIG_DIR='./tests/e2e/config' NODE_CONFIG_ENV=test JEST_PUPPETEER_CONFIG=tests/e2e/jest-puppeteer.config.js jest --config tests/e2e/jest.config.js
  console.error node_modules/config/lib/config.js:1638
    WARNING: NODE_ENV value of 'test' did not match any deployment config file names.

  console.error node_modules/config/lib/config.js:1639
    WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

  console.log tests/e2e/lib/setup.js:34
    Running tests against http://jeherve.eu.ngrok.io/

 FAIL  tests/e2e/specs/dummy.test.js
  ● Test suite failed to run

    Configuration property "storeSandboxCookieValue" is not defined

      21 | import MyPlanPage from '../pages/wpcom/my-plan';
      22 |
    > 23 | const cookie = config.get( 'storeSandboxCookieValue' );
         |                       ^
      24 | const cardCredentials = config.get( 'testCardCredentials' );
      25 | const siteUrl = new URL( process.env.WP_BASE_URL ).host;
      26 |

      at Config.Object.<anonymous>.Config.get (../../node_modules/config/lib/config.js:203:11)
      at Object.get (lib/flows/jetpack-connect.js:23:23)
      at Object.<anonymous> (lib/setup-env.js:8:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.643s
Ran all test suites.
```

Am I missing something?

**Comment by brbrr** [comment]
Ouch, sorry. I forgot about config decryption step. Here is a doc on how to do that: https://github.com/Automattic/jetpack/blob/master/tests/e2e/README.md#test-configuration
I also updated test instructions

**Comment by jeherve** [comment]
Tests and discussion in p1561123328107000-slack-jetpack-crew

**Review by jeherve — APPROVED** [review]
Merging following our discussion in Slack.

p1561127717124400-slack-jetpack-crew

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.5` in b21de65b83ff941aee584d0590b19224ed75d58a

**Pull request merged**
