### PR TITLE
Social | Add resharing for classic editor

### PR DESCRIPTION
**Pull request by manzoorwanijk**
We're getting requests about resharing in the classic editor. Previously we've de-prioritised any additional work on the classic editor, but WooCommerce is still transitioning away from it, and they are commercial customers. It's probably worth doing if it's low effort.

## Proposed changes:

* Add resharing for classic editor

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Enable classic editor using [classic editor plugin](https://wordpress.org/plugins/classic-editor/)
* Run `jetpack build plugins/social` or `jetpack build plugins/jetpack`
* Create a new post
* Click on "Edit" beside "Jetpack Social"
* Confirm that you don't see the "Share now" button for the posts which are not published yet.
* Publish the post
* Confirm that you now see the "Share now" button
* Use the Share now button
* Confirm that it works and behaves as expected.

Screenshot 2024-06-12 at 2 57 33 PM

### CODE REVIEW

**Review by spsiddarthan — COMMENTED** [review]
Resharing should be disabled on simple sites. With this change, it's enabled on simple sites. 

Screenshot 2024-06-14 at 2 35 22 PM


Screenshot 2024-06-14 at 2 34 54 PM

**Comment by manzoorwanijk** [comment]
> Resharing should be disabled on simple sites. With this change, it's enabled on simple sites.

Thank you for catching that. I have pushed a fix.

**Review by spsiddarthan — COMMENTED** [review]
Can confirm I don't see it on simple sites now, thanks for fixing that. 

With a single connection, things work fine on Jetpack/Atomic. With multiple connections present, it gets shared to all the connections despite having selected only one connection to share to. 

I understand the post meta has to be updated, perhaps I am doing it incorrectly. Recording below, just see the first 20 seconds.

Tagging @pablinos or @gmjuhasz  for a second review to get any front-end specific thoughts and also to ask if skipping sharing to one network isn't working correctly for them as well. 


https://github.com/Automattic/jetpack/assets/6594561/91835eb0-c1f6-4ba1-9a92-3c6e02edc921

**Review by spsiddarthan — APPROVED** [review]
Works well, we need to land the diff first though.

**Pull request merged**
