### PR TITLE
CRM: 3413 - escape output in listviews

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves Automattic/zero-bs-crm#3413 - escape output in listviews

## Proposed changes:

See issue for details.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

See issue for details. Make sure there are no regressions by enabling all columns in all listviews and confirming no output issues or errors in the JS console.

### CODE REVIEW

**Review by gogdzl — APPROVED** [review]
Works as advertised!

**Comment by cleacos** [comment]
I cannot replicate the issue or I'm not sure how to replicate it. In the trunk, if I save the Contact name with `<script>alert('asdf');</script>,` (or another field) it is saved escaped, and the list endpoint returns it already escaped, and I added the `Name` and `First Name` columns. The same for a Quote or a Transaction.

**Review by coder-karen — APPROVED** [review]
I was able to replicate the issue. 

@cleacos the steps I took: checkout the branch on a JN site. Create a contact, add all list view items. Then save the contact's first name as the suggested script directly in the database (using a database plugin). I then switched to trunk (in my case on the JN site I switched to the most recent release), and opened up the contacts page. Initially nothing - as before the contact's name is showing as the unrendered script. Then I clicked on the contact itself, then navigated back to the list view. In doing so, the script ran. Could replicate elsewhere too, eg transactions, quotes.
Then I went back to the branch, replicated the steps (clicking on the contact, then list view), and the script remained unrendered.

**Comment by cleacos** [comment]
> Then save the contact's first name as the suggested script directly in the database (using a database plugin)

Okay, if I save the JS script directly in the database, yes, I can replicate it, and if I apply this patch, it escapes the output, working as expected 👍 ... but it seems an odd security issue, having to replicate it by touching the database directly. I think even the importer service escapes the inputs anyway.

**Pull request merged**
