### PR TITLE
JITM: Add unit tests for JITM class

### PR DESCRIPTION
**Pull request by withinboredom**
#### Changes proposed in this Pull Request:

* Adds unit tests for the Just In Time Message class

#### Testing instructions:

* Unit tests should pass

#### Proposed changelog entry for your changes:
Increase code coverage of unit tests

### CODE REVIEW

**Comment by ebinnion** [comment]
The tests seem to make sense. The biggest feedback I have is that I would break the tests up.

For example, `test_prepare_jitm_edit_comments` test seems to actually be testing two separate things:

1. That the JITM notice displays on `edit-comments` if Akismet is not active
2. That the JITM notice does not display on `edit-comments` if Akismet is not active

While these are very similar, having separate tests might make it easier to grok and know what exactly is failing when a test fails. Same feedback for the other tests.

**Comment by withinboredom** [comment]
@ebinnion: I thought about this too, but decided to focus on the rules of a specific view v.s. breaking it up. IOW, if a unit test fails, it fails that JITM, not a specific rule of the JITM. That seemed to be the most intuitive to write. However, I see your point from the view of: "I just wrote code, why did this break?"

I agree that this makes more sense to break up into smaller tests, so I'll go ahead and do that.

**Comment by eliorivero** [comment]
I added a testsuite for JITM unit tests so now you can do
```
phpunit --testsuite jitm
```

I found one issue:
```
There was 1 failure:

1) WP_Test_Jetpack_JITM::test_jitm_dismiss
Failed asserting that false is true.

/jetpack/tests/php/test_class.jetpack-jitm.php:161
```

**Comment by zinigor** [comment]
IDK why, but I couldn't revert changes to yarn.lock properly.
I have fixed the failing test and added an example of how we can add explanation strings to make failures more obvious.

**Comment by eliorivero** [comment]
I've successfully reverted the `yarn.lock` and tested again and with Igor's fix the test now passes.
So let's 🐑

**Pull request merged**
