### PR TITLE
Fix ESLint runtime for packages and plugins

### PR DESCRIPTION
**Pull request by manzoorwanijk**
As discussed here (https://github.com/Automattic/jetpack/pull/23568#issuecomment-1082782170), VSCode's built in ESLint does not work in packages/plugins where it is not installed as a dependency. Thus we need to either install `eslint` in all the packages/plugins or install it at root `package.json`. Installing at root directory is a better option as mentioned [here](https://github.com/Automattic/jetpack/pull/23568#issuecomment-1083167455).

#### Changes proposed in this Pull Request:

* Add `eslint` as a dependency in root `package.json`
* Remove `eslint` from `plugins/jetpack/package.json`

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

1. Switch to master branch and run `npm install`
2. Reload VS Code (`Cmd + Shift + P` > `Developer: Reload Window`)
3. Open any js file inside `js-packages` e.g. `projects/js-packages/components/components/qr-code/index.jsx`
4. Mess up the formatting.  For example select some text and run `Outdent line` command (`Cmd + [`) a few times.
5. Open problems view (`Cmd + Shift + P` > `Problems: Focus on Problems View`)
6. Confirm that **_you DON'T see the problems_** reported by ESLint.
7. Repeat steps 4 and 5 for any js file inside `plugins/jetpack` e.g. `projects/plugins/jetpack/_inc/client/at-a-glance/activity.jsx`
8. Confirm that **_you SEE the problems_** reported by ESLint.
9. Now switch to this PR branch `git checkout fix-eslint-dependency` and run `npm install`
10. Repeat the above after step 2.
11. Confirm that **_you SEE the problems_** reported by ESLint in both the above cases.

| BEFORE | AFTER |
|--|--|
| Screenshot 2022-04-04 at 1 06 03 PM | Screenshot 2022-04-04 at 1 07 08 PM |

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
I fixed the description of the task: eslint works fine, it's vscode's built-in eslint that has the annoying requirement.

I note we now have a conflict for `node_modules/.bin/eslint` between eslint and our own tools/js-tools package. Pnpm surprisingly doesn't issue any diagnostic about that, but there's also no indication as to how it decides which to pick. We should probably remove the shim being provided by js-tools.

Also we could remove
https://github.com/Automattic/jetpack/blob/247cee70e162bd81d2c1c067728ccfb906230f88/package.json#L41-L47
since the dependency is now present throughout the monorepo. At least for now, we might have to bring it back when we update to pnpm 7 (thanks to an IMO somewhat misguided change in pnpm/pnpm#4469). But I can figure that out when the time comes.

**Comment by manzoorwanijk** [comment]
> We should probably remove the shim being provided by js-tools.

Does that mean we need to:

- Delete `tools/js-tools/eslint`
- Remove `bin.eslint` from `tools/js-tools/package.json`

Anything else?

Also, can we remove `eslint` as a dependency from these?

- `js-packages/eslint-config-target-es/package.json`
- `js-packages/eslint-changed/package.json`

**Comment by anomiex** [comment]
> Does that mean we need to:
> 
> * Delete `tools/js-tools/eslint`
> * Remove `bin.eslint` from `tools/js-tools/package.json`

Yes, both of those.

> * Remove `eslint` from `devDependencies` of `tools/js-tools/package.json`

We could probably do that too. At least until pnpm 7 as I mentioned earlier.

> Anything else?

I don't think so.

> Also, can we remove `eslint` as a dependency from these?
> 
> * `js-packages/eslint-config-target-es/package.json`
> * `js-packages/eslint-changed/package.json`

The dev dependency could probably be removed.

Removing the peer dep would be wrong and is what I mentioned could accidentally happen in https://github.com/Automattic/jetpack/pull/23568#issuecomment-1083167455. Which is why I don't really *like* this change and wish vscode would pick up our shim from js-tools instead of demanding the whole package be installed in the monorepo root.

**Review by anomiex — APPROVED** [review]

**Comment by vitozev** [comment]
r243208-wpcom

**Pull request merged**
