### PR TITLE
Boost: Add consolation log on critical CSS gen

### LINKED ISSUE #21370: Boost: Add consolation note regarding js errors during critical CSS gen.
When generating critical CSS. Often, the browser complains about blocked JS execution.

JS execution is not important and we can ignore that during critical CSS generation. However, the user might still find it frustrating and may think something is broken.

So, the idea is to put on a consolation note before the errors would start showing up. This can be something similar to the self xss warning facebook places on browser console.

Message we discussed about placing: "Generating Critical CSS will often leave errors in your console. Most of them are nothing to worry about - just the sounds of your browser complaining about our strict security settings. Check out the following page for more information: [link to a page on jetpack.com which explains which errors are fine to ignore]”

Related support topic: https://wordpress.org/support/topic/blocked-script-execution/

Discussion: p1634020657012900-slack-C0232B8CUHG

### PR DESCRIPTION
**Pull request by karthikax**
Fixes #21370 

#### Changes proposed in this Pull Request:

Add a console log with the following content right before the Critical CSS generation process:
```
Generating Critical CSS will often leave errors in your console. Most of them are nothing to worry about - just the sounds of your browser complaining about our strict security settings. Check out the following page for more information: {link}
```

#### Jetpack product discussion

p1634020657012900-slack-C0232B8CUHG

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Navigate to Boost dashboard
* Open developer tool in the browser
* Generate Critical CSS
* Verify that the following message is logged in the developer tool console right before any error is logged related to Blocked script execution. Eg:
consolation-note

### CODE REVIEW

**Comment by karthikax** [comment]
Asana task for the docs: 1200427382410585-as-1201682142764786/f

**Comment by thingalon** [comment]
@karthikax - what's the status of this? Is it ready for review, or been put off back into the backlog?

**Comment by karthikax** [comment]
@thingalon This is not ready for review yet. I have checked with the Obsidian team and Swish mentioned that it may take a few more weeks before they can take a look into this. I am moving the linked issue #21370 to backlog. I will update this PR once it is ready for review.

**Comment by thingalon** [comment]
Any word on getting a page ready to link users to? Can we draft one ourselves?

**Comment by karthikax** [comment]
I see Swish is AFK until 21st March. I checked earlier if I can add a draft and did not succeed. I will give it one more try.

**Comment by karthikax** [comment]
The [console error documentation](https://jetpack.com/support/performance/jetpack-boost/jetpack-boost-console-error/) page is now published. The same has been updated in the consolation log.

**Review by thingalon — APPROVED** [review]
🥳 🚀 🚢

**Pull request merged**
