### PR TITLE
Cover block: fix paid-block-media-placeholder interference with flex positioning

### PR DESCRIPTION
**Pull request by ciampo**
Related to #19488

#### Changes proposed in this Pull Request:

* Add a CSS rule to "remove" the `paid-block-media-placeholder` element from the flexbox layout in the cover block, when the cover block has a background set

#### Jetpack product discussion

Initial report: p1617898513140100-slack-CBTN58FTJ

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Apply D59965-code to your sandbox
2. Open the block editor on a site that is added to your sandbox
3. Add a cover block
    - [ ] Before adding an image or picking a background color, make sure that the cover block looks like the version currently in production Screenshot 2021-04-09 at 14 18 07
4. Pick a background color or select a background image/video from the gallery
5. Add a paragraph into the cover block and play with the cover block settings to change the position of its content
    - [ ] The content should align within the cover block as expected
6. With the cover block selected, drag a new image over the block
    - [ ] The cover block should react to the dragging, and turn into a drop target Screenshot 2021-04-09 at 14 23 52

#### Screen recordings:

**Before**

https://user-images.githubusercontent.com/1083581/114181127-6452bd00-9941-11eb-8797-3e544ffadc31.mp4

**After**

https://user-images.githubusercontent.com/1083581/114181138-67e64400-9941-11eb-87f8-7fbb7464e5b8.mp4

### CODE REVIEW

**Comment by retrofox** [comment]
I'm not able to reproduce the issue :-/

https://user-images.githubusercontent.com/77539/114193131-999ce200-9924-11eb-8714-e6c15840cec0.mov

**Comment by ciampo** [comment]
Maybe these instructions from the original issue (https://github.com/Automattic/wp-calypso/issues/51670) can help?


>### Steps to reproduce the behavior
>
>1. Make sure your site has a Personal plan
>2. Create a cover block and check if the content is center aligned
>
>---
>
>1. Create a new site on WP.com with a free plan.
>2. Add a cover block to a page.
>3. Change the background colour in the placeholder.
>4. Start typing and notice that the text defaults to right-align.

**Comment by retrofox** [comment]
> Maybe these instructions from the original issue (Automattic/wp-calypso#51670) can help?

let me trying again... thanks :-)

**Review by retrofox — APPROVED** [review]
Thanks for dealing with this issue. LGTM. Tested and it works as expected.

**Review by apeatling — APPROVED** [review]

**Comment by apeatling** [comment]
r224055-wpcom

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.6` in 41042282f0d7e399d63b65a2ccba1729718ec06b

**Pull request merged**
