### PR TITLE
Latest Instagram Posts: Delete cache after permanently deleting the connection

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request:

* Move the `get_instagram_connections` logic to the Instagram helper in order to be easily reused where needed.
* Check if the Instagram connection is valid before using the gallery cache; if it's not valid, delete the cache.
* If the block's connection is not valid, show a descriptive error message on the front end.

Screenshot 2020-06-24 at 14 48 35

To properly support multiple Instagram connections, we decided to stop permanently deleting a connection when disconnecting a block. This is still possible from Calypso (Marketing -> Connections).

Since the gallery is cached on the site, deleting a connection from Calypso won't also automatically delete the cache as well. For this reason, galleries are still visible for up to 1 hour after their connection has been deleted.

The solution proposed here is to check if the block's connection exists before attempting to retrieve the cached gallery.
If it doesn't exist, we delete the cached gallery and return an error.
In the front end, we display that error message to the site admins.
In the editor, we simply ignore the error and show the block's placeholder, prompting to create a new connection.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Insert a Latest Instagram Posts block, and connect it to an Instagram account.
* Save the post.
* Head to Calypso (Marketing -> Connection) and delete the Instagram connection.
* View the post in the front end: make sure it shows a "connection unavailable" error message (only for site admins)
* Reload the editor: make sure the block loads up in placeholder, prompting to create a new connection (or to select a different one, if possible).

#### Proposed changelog entry for your changes:

* Latest Instagram Posts Block: Stop showing cached galleries after the Instagram connection has been deleted.

### CODE REVIEW

**Review by glendaviesnz — APPROVED** [review]
This worked for me now.

**Review by jeherve — CHANGES_REQUESTED** [review]
It seems to work nicely when logged in, but I'm getting some notices when disconnected and viewing posts with a block while being logged out:

```
Notice: Undefined property: stdClass::$connections in wp-content/plugins/jetpack-dev/_inc/lib/class-jetpack-instagram-gallery-helper.php on line 36
Warning: Invalid argument supplied for foreach() in /wp-content/plugins/jetpack-dev/_inc/lib/class-jetpack-instagram-gallery-helper.php on line 36

```

**Comment by Copons** [comment]
> It seems to work nicely when logged in, but I'm getting some notices when disconnected and viewing posts with a block while being logged out:
> 
> ```
> Notice: Undefined property: stdClass::$connections in wp-content/plugins/jetpack-dev/_inc/lib/class-jetpack-instagram-gallery-helper.php on line 36
> Warning: Invalid argument supplied for foreach() in /wp-content/plugins/jetpack-dev/_inc/lib/class-jetpack-instagram-gallery-helper.php on line 36
> ```

Shoot, this made me realize that this doesn't work as nicely as we think! 😓 

The change here checks for the _current user_'s connections to confirm the cache, so if _anyone but the owner of the connection_ loads the gallery, the `/me/connections` would return empty for the gallery token, deleting its cache.

**Comment by Copons** [comment]
Replaced by #16331

**Pull request closed without merging**
