### PR TITLE
[paid-newsletters] visibility selector & wording changes

### LINKED ISSUE #28590: [Paid Newsletter] Access selector in the post-publish flow should not be a popup
The stock WordPress visibility selector in WordPress is not a "popup" - see close to the top in the "**Visibility: Public**" panel
 
The access selector for the paid newsletter displays in a popup. It should display the same way that the stock one does.

Zrzut ekranu 2023-01-26 o 15 01 20

### PR DESCRIPTION
**Pull request by millerf**
Fixes #28590 and #28592

## Proposed changes:
* Align newsletter UI menu with stock WordPress UI (see Visibility menu)
* Fix some wording
* Remove number of social followers if 0

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:
* Patch your sandbox
* Open a paid-newsletter-enabled blog (for example https://bestmemberships.wordpress.com/)
* Create a new post and watch the paid newsletter menu

You should see:
 

| Edition | Edition (menu opened) | Pre-publish |
| -- | -- | -- |
|  Screenshot 2023-02-13 at 17 25 40 | Screenshot 2023-02-13 at 17 26 03 | Screenshot 2023-02-13 at 17 26 14 |

### CODE REVIEW

**Comment by artpi** [comment]
I am adding the following here so the checks don't complain:

```
## Does this pull request change what data or activity we track or use?

No
```

**Comment by artpi** [comment]
Solves https://github.com/Automattic/wp-calypso/issues/73270

**Comment by artpi** [comment]
The screenshot does not fix 

> Remove number of social followers if 0

**Comment by millerf** [comment]
> The screenshot does not fix
> 
> > Remove number of social followers if 0

I think I fixed those afterwards, as I ended up fixing the 2 issues in the same PR. Let me retake those screenshots...

**Review by artpi — CHANGES_REQUESTED** [review]
1. The social subscriber is 0 in the screenshot even though the pr says it's going to fix that
2. this needs rebasing
3. I am getting a following error in the editor:

Zrzut ekranu 2023-02-13 o 15 50 07

**Comment by millerf** [comment]
@artpi 
- Bug fixed
- Rebased
- Screenshots updated

**Review by artpi — APPROVED** [review]
Works now!

**Review by jeherve — APPROVED** [review]

**Pull request merged**
