### PR TITLE
Donations Block: unify stripe nudge and refactor donations block to use it

### LINKED ISSUE #24176: Unify Stripe Nudge component and update Donations block to use the unified nudge
## Impacted plugin
Jetpack

## What
This task is a follow up for #24034
* Unify the different Stripe Nudges into a single one that is aware of the product store.
* Updated the donations block to use this Stripe Nudge and clean up residue from the previous implementation.

## How
No response

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes #24176

#### Changes proposed in this Pull Request:

* Unified the Stripe Nudge components into a single component.
* Updated the Donations block to use the single Strip Nudge component.
* Cleaned up the Donations block.
* Cleaned up the Premium content block.

#### Testing instructions:

* Make sure that your Stripe account is disconnected.
* Create or edit a Post
* Add a Donations, Payments, and Premium Content block.
* You should see the Stripe connect nudge in every block.

#### Testing video:

https://user-images.githubusercontent.com/1989914/165936272-677496ab-1195-42c8-816e-25d4c27fa5e2.mp4

### CODE REVIEW

**Review by BogdanUngureanu — DISMISSED** [review]
LGTM to me and tests well on Atomic and Simple.

**Comment by samiff** [comment]
@rcrdortiz Could you check on this behavior I'm seeing:

- With changes pulled down, create a new post.
- First add a Donations block - I'm not seeing the Stripe nudge on this.
- Then add a Payments button block - which after a second displays the Stripe nudge.
- Clicking back to the Donations block _now_ shows the Stripe nudge.


https://user-images.githubusercontent.com/15803018/165999383-2dac1e33-e2d6-43f9-9110-e14ee605e750.mov

**Comment by rcrdortiz** [comment]
> @rcrdortiz Could you check on this behavior I'm seeing:
> * With changes pulled down, create a new post.
> * First add a Donations block - I'm not seeing the Stripe nudge on this.
> * Then add a Payments button block - which after a second displays the Stripe nudge.
> * Clicking back to the Donations block now shows the Stripe nudge.

Nice catch @samiff, thanks! The Membership Products Store is only populated when we perform a call to getProducts. The connection URL and status weren't being updated by the donations block, and when you inserted one of the blocks that rely on the Membership Product Store for retrieving the subscriptions, the store was then populated and the Stripe Connect Nudge showed when the component redrew itself.

Regarding the Stripe Connect Nudge not being shown instantly, bear in mind that it relies on an API call in order to determine if the user has Stripe Connected or not and that would explain the delay you perceived.

Now the Donations Block updates the store after calling the API, both the Donations block and Membership Products Store call the same API but with different filters. The API response regarding the Stripe connection is the same in both cases so it's true that if the Donations response isn't connected then the Membership Products Store response will also not be connected and vice versa.

Making the Donations block also use the Membership Products Store for retrieving its subscriptions would further simplify the component and centralize the operation of obtaining payment plans. I'll create an issue to further investigate/execute the refactor.

And here you can see a video of how it is working for me after applying the latest changes:

https://user-images.githubusercontent.com/1989914/166099625-ac8ccf74-f3cc-432e-892c-88426c794a5a.mp4

**Review by samiff — APPROVED** [review]
Tested again and it works much better now 👍

**Comment by rcrdortiz** [comment]
Deployed r244806-wpcom

**Pull request merged**
