### PR TITLE
Unload masterbar and nav unification when nav redesign is enabled

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Fixes #

## Proposed changes:

* Updates the action bar module to not load masterbar and nav unification based off a filter which we can override from other areas such as wpcomsh/jetpack-mu. The default value for this filter checks both if the user is proxied and if they have the 'classic' interface setting enabled.

Before - "classic" view:
Screenshot 2024-02-13 at 11 27 33 AM

After - "classic" view:
image

NOTE - i forgot to take bigger captures to show the change to nav unification. You can see nav unification is removed in the above image by the comparative width of the sidebar, but you will see it more broadly in testing.  Also note the help center was gone in that image due to its incompatibility with the jetpack-beta-tester plugin, which has been [ fixed here](https://github.com/Automattic/wp-calypso/pull/87430).

Before AND after - "default" view:
Screenshot 2024-02-13 at 11 26 51 AM

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Load these changes of jetpack on a WoA site. A bot comment below will give more instructions on using the jetpack beta testing plugin.
* Go to hosting config and select "classic" view, make sure you are proxied.
* visit wp-admin, there should be no masterbar or nav unification customizations.
* disable the proxy - previous customizations should reappear.
* re-enable the proxy, go back to hosting config and toggle the "default" setting.
* back to wp-admin, verify there is no change from previous behvario.

### CODE REVIEW

**Review by ebinnion — CHANGES_REQUESTED** [review]
This largely seems to work. But, in functional testing, it does remove the help center proxied and unproxied, so we should fix that before merging.

**Comment by Addison-Stavlo** [comment]
>  it does remove the help center proxied and unproxied, so we should fix that before merging.

Thanks for testing! I just noticed this myself 🤔... investigating.

**Comment by Addison-Stavlo** [comment]
@ebinnion How weird!  The help center is showing for my test site that I am syncing the build to directly:

Screenshot 2024-02-13 at 12 39 43 PM

But its not showing up for the site that I run the jetpack beta tester plugin for:
Screenshot 2024-02-13 at 11 27 05 AM

**Comment by ebinnion** [comment]
Interesting. Because I also tested with the beta tester plugin. Maybe worth triggering a new build with a new commit? If that doesn't work, I'd probably ask the Jetpack team who would know best.

**Comment by Addison-Stavlo** [comment]
> Interesting. Because I also tested with the beta tester plugin.

Testing more, it seems to be an issue outside of this branch or with the tester plugin itself. Notice that the help center is there on the last stable release, but its gone as soon as we switch to the candidate (which this code isnt included for yet):

Screenshot 2024-02-13 at 12 47 39 PM

vs. 

Screenshot 2024-02-13 at 12 47 49 PM

And as we noted build/sync this branch directly preserves the help center while the beta tester on this branch doesn't.

So is there potentially an issue with the combination of the beta tester plugin and the help center? cc @Automattic/jetpack and  @alshakero if you might have run into this before or have ideas.

**Comment by ebinnion** [comment]
Omar is afk. cc @Automattic/vertex.

**Comment by Addison-Stavlo** [comment]
> Omar is afk. cc @Automattic/vertex.

Also opened a slack thread: p1707847387926519-slack-CDLH4C1UZ

**Comment by ebinnion** [comment]
In Slack, we came to the conclusion that the issue is a [not robust check for whether Jetpack is installed and active](https://github.com/Automattic/wp-calypso/blob/f41c3960a0e27a8b958fdb5ca114c4a0aa6de23b/apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php#L309-L311). @Addison-Stavlo  and I have talked about changing the check to look for the `JETPACK__VERSION` constant being defined.

**Review by DustyReagan — APPROVED** [review]
I tested it, and it works as described! Also, I see that the help center issue is not due to this PR.

**Review by ebinnion — APPROVED** [review]

**Comment by roo2** [comment]
@Addison-Stavlo hmm there are no longer links back to wordpress.com or the site switcher. So when you switch to a WoA site with this enabled, you get "stuck" in that site.

When this change was originally proposed, I think Matias was also assuming it would open in a new tab and so the user would always have the other tab to navigate through other sites on wordpress.com.

I think we should make sure the opening in a new tab is in before releasing beyond a12s, and make sure that navigating between sites still makes sense.

https://github.com/Automattic/jetpack/assets/22446385/d670caa6-5679-4818-b3e8-36da3abd3650

**Comment by lsl** [comment]
Screenshot(117)

Are we adding this? It's a link to /sites, shouldn't need nav unification to add this could even ship it as a plugin users can delete.

**Comment by lsl** [comment]
> I think we should make sure the opening in a new tab is in before releasing beyond a12s, and make sure that navigating between sites still makes sense.

Noted this concern here https://github.com/Automattic/dotcom-forge/issues/5565#issuecomment-1942982217

**Comment by ebinnion** [comment]
Yes, we'll be adding that link. Also, no to opening in a new tab.

p1707822206412999-slack-C06DN6QQVAQ

**Comment by lsl** [comment]
Added in https://github.com/Automattic/dotcom-forge/issues/5567

**Pull request merged**
