### PR TITLE
Premium content: Move view switcher to drop down

### LINKED ISSUE #22745: Premium Content Block: Toolbar button overlap on mobile
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Use smaller mobile viewport (or mobile device)
2. Go to the editor
3. Add the Premium Content block, and another block so there's  the up/down arrows in the block toolbar
4. Focus the Premium Content block
5. Look at the "Subscriber View" button in relation the three-dots more-settings button

### A clear and concise description of what you expected to happen.

The three-dots button should not overlap with the subscriber view button.

### What actually happened

The "subscriber view" button and the three-dots more settings button overlap.

### Other information

Screen Shot 2022-02-08 at 2 47 55 PM

We seem to be running out of horizontal space -- perhaps the subscriber/guest view selection should be moved to a drop down?

### Operating System

macOS

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by dsas**
Fixes #22745

#### Changes proposed in this Pull Request:

On small (<782px viewport) use a drop-down rather than two separate buttons to switch between guest and subscriber views. This takes up less space allowing mobile users to see the whole menu.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Use a premium or higher wpcom site
2. Create a new post
3. Resize your viewport to mobile size
4. Insert a premium content block
5. Use the new drop down menu to switch between subscriber and guest views
6. When you switch, the content being displayed should change to match
7. Make the viewport bigger
8. Note that the drop-down is replaced by two separate buttons
9. Make the viewport smaller again, without reloading. Note that the menu uses a dropdown on smaller screens and most importantly doesn't mysteriously disappear.

Before | After
-------|------
image| image
image | image

### CODE REVIEW

**Comment by Copons** [comment]
The toolbar dropdown control's paddings look a bit weird. 🤔 

Regardless, what do you think if we only collapsed to dropdown on smaller viewports?
Core Guten has a neat hook for that kind of things: https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-viewport-match/index.js

**Comment by rcrdortiz** [comment]
> Regardless, what do you think if we only collapsed to dropdown on smaller viewports?
That seems like a wonderful solution, +1.

**Comment by dsas** [comment]
Makes sense to me. I'll take a look this afternoon.

**Comment by dsas** [comment]
> what do you think if we only collapsed to dropdown on smaller viewports?

I've done this (though I need to tidy up the code a little). I chose the same viewpoint as when gutenberg changes from a floating menu to a fixed top one.

I experimented with triggering the change at a lower viewpoint depending upon the number of items in the menu, but it felt unnecessarily complex for little gain.

I've also came across a pre-existing bug where when starting with a small viewpoint a fixed menu works, if you then increase the size of the viewpoint it eventually switches to a floating menu but if you then decrease again it goes to a fixed menu without the view switcher or plan chooser toolbar items. I can't see why that's happening but I'll file that separately.

**Comment by dsas** [comment]
> I've also came across a pre-existing bug where when starting with a small viewpoint a fixed menu works, if you then increase the size of the viewpoint it eventually switches to a floating menu but if you then decrease again it goes to a fixed menu without the view switcher or plan chooser toolbar items. I can't see why that's happening but I'll file that separately.

https://github.com/Automattic/jetpack/issues/23337

**Comment by BogdanUngureanu** [comment]
Great job, Dean! I followed the instructions and it was working on most mobile resolutions. However, when switching to a lower resolution, the Settings menu (the three dot icon) still overlaps with the subscription dropdown:
Screenshot 2022-03-10 at 12 07 55

**Comment by dsas** [comment]
> However, when switching to a lower resolution, the Settings menu (the three dot icon) still overlaps with the subscription dropdown:

Any viewport lower than about 410px will start to do that (about 460px if not yet connected to stripe).

What's the lowest viewport width it's worth expending more effort supporting? 
 * At a glance I can't see any stats I have access to. 
 * Gutenberg only offers support for targeting browsers with a viewport that is are <480px, nothing more fine-grained for that.
 * Unless it's ok to start messing with core gutenberg controls we only have about 200px of width under our control at really low resolutions

Solutions:
 * Add more confusing icons instead of words
 * Dropping the word 'view' from the menu at low resolutions will probably get us down to about 380px in English but that's still 5px wider than the width you're testing at.
 * Drop the 'plan' icon on that menu - I don't get it anyway, it looks like a refresh or recycle symbol.

**Review by BogdanUngureanu — APPROVED** [review]
LGTM, great job Dean! 🎉

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Pull request merged**
