### PR TITLE
Dotcom Merge: All Shortcode files

### PR DESCRIPTION
**Pull request by dereksmart**
This will bring us up to date with wpcom's files for all shortcodes. 

cc @lancewillett

### CODE REVIEW

**Comment by lancewillett** [comment]
Side note: on WP.com I'd added shortcode and shortcode reversal unit tests. Do those get synced to Jetpack repo, or should they be added or mirrored somehow?

**Comment by dereksmart** [comment]
@lancewillett very nice! Currently there are no Unit Tests being synced at all, so they would likely need to be merged manually.  

Do you know if they are jetpack compatible as-is? aka nothing wpcom-specific?

**Comment by lancewillett** [comment]
I think they would be compatible code-wise, most of them use `WP_UnitTestCase` class and are named with Jetpack prefixes. I've only ever run them on my WP.com sandbox server, though. I think a merge would be good (sync both ways) ignoring anything that's only a shortcode on WP.com.

**Comment by zinigor** [comment]
Looks great, thank you!

**Pull request merged**
