### PR TITLE
JITM style enhancements 

### PR DESCRIPTION
**Pull request by jeffgolenski**
**Visual JITM adjustments**

Touching up a few style quirks that were found in a [previous PR](https://github.com/Automattic/jetpack/pull/7058).

- [x] JITMs need to properly clear and sit below "screen options" area (not next to it)
- [x] Alignment of `X` should align better with the down arrow of the "screen options" area and other dismiss buttons for wp-admin notices
- [x] Remove old JITM code (no longer needed)

**Before:**

**After:**

* dismissal `x` aligned on most screen sizes. wp-admin has different breakpoints than calypso so I didn't want to bloat our code just to be 100% on every screen size. It's 99% though. 
* border widened to match wp-admin notice borders. 
* JITM position is fixed to sit below "screen options" area. 
* Button width: `flex-basis` adjusted so the button text is on one line (90% of the time anyway—hard to do one-size-fits all and keep it so flexible)

screen shot 2017-05-30 at 4 54 02 pm

screen shot 2017-05-30 at 4 55 23 pm

**on smaller screens...**
screen shot 2017-05-30 at 5 06 24 pm

screen shot 2017-05-30 at 4 55 36 pm

**To test**

1) Install akismet, but keep it deactivated. Visit `/wp-admin/edit-comments.php` and verify that you see a JITM for Akismet. It should go away if dismissed or Akismet is activated. 
2) Install VaultPress, but keep it deactivated. After publishing a post, verify that you see a JITM for VaultPress. 
2) Install VaultPress, but keep it deactivated. `Visit 1/wp-admin/update-core.php` and verify that you see a JITM for VaultPress. 
3) Install Woo Comm and activate it. Visit `/wp-admin/admin.php?page=wc-settings` and verify that you see a JITM for Woo Services plugin.

### CODE REVIEW

**Comment by beaulebens** [comment]
This makes the notices look MUCH better for me, but it also accidentally introduces a big gap at the top of the main Jetpack UI:

screen shot 2017-05-30 at 3 41 56 pm

**Comment by jeffgolenski** [comment]
@beaulebens Good find!

@withinboredom Can you take a look as to why this JITM div is being loaded into the dashboard here? We want to ensure it's not being loaded where its not needed.

screen shot 2017-05-31 at 11 16 42 am

**Comment by eliorivero** [comment]
@withinboredom while I don't think we'll have JITMs in Jetpack settings and it could be quickly excluded with
```php
function prepare_jitms( $screen ) {
    if ( ! in_array( $screen->id, array( 'toplevel_page_jetpack', 'jetpack_page_stats', 'jetpack_page_akismet-key-config', 'admin_page_jetpack_modules' )  ) ) {
        add_action( 'admin_enqueue_scripts', array( $this, 'jitm_enqueue_files' ) );
        add_action( 'admin_notices', array( $this, 'ajax_message' ) );
        add_action( 'edit_form_top', array( $this, 'ajax_message' ) );
    }
}
```
I also think it would be much better to only enqueue the assets and write the `div.jetpack-jitm-message` in the screens where and when a JITM is going to be displayed. Right now the div and the style and script files are loaded in every WP Admin screen.

**Comment by withinboredom** [comment]
@eliorivero: we don't know what jitm will show or not until the api comes back. We decided to not delay the admin page from loading just to make an api request to see if there was a jitm. Instead, we moved it to an ajax call which can happen async. There may be a case for having JITMs show on the jetpack settings pages, but we can cross that bridge when we get there ;)

**Comment by jeffgolenski** [comment]
@withinboredom not to be _that_ guy here, but JITMS don't display in the jetpack dashboard area at all—and shouldn't. All the "notices" that will ever show up in the react dashboard or settings area will be our dops-component notices/nudges/banners (whatever we're calling them these days).

cc @rickybanister @MichaelArestad

**Comment by ebinnion** [comment]
@withinboredom Here's an example of how we don't know the IDC notice on the Jetpack page:

https://github.com/Automattic/jetpack/blob/master/class.jetpack-idc.php#L114

**Comment by withinboredom** [comment]
@jeffgolenski I wasn't saying this is/was a case, just saying that there may be one in the future :p which is why I didn't make it impossible and left it up to wpcom as to whether they show up there or not /shrug. One case I can think of is sync errors detected on the wpcom side, but undetected in the  client. Don't know if that's a thing, but just something I thought of...

**Comment by eliorivero** [comment]
Last night I was about to also comment that maybe the `div` could be added by JS, and pass the nonce, message path and query string through `wp_localize_script`. You could make the async call in every page, and when the response says that you have to show a JITM, load the style and script asynchronously, where the latter will render the `div` for the rest of elements.
In this way you can make a call in every dashboard screen, so you cover this
`we don't know what jitm will show or not until the api comes back`
but you also keep screens light by only loading the assets when they're necessary.

**Comment by withinboredom** [comment]
That's a good idea @eliorivero ... wish I'd thought about it weeks ago :D def something for 5.1, don't think it'll make it to 5.0 :(

**Comment by withinboredom** [comment]
Actually @jeffgolenski ... I think I have a solution that doesn't require this pr ... incoming in about 15-20 mins...

**Comment by jeffgolenski** [comment]
@withinboredom I still made other style changes in this PR that are necessary so this PR is still relevant. It needs to be merged in.

**Comment by eliorivero** [comment]
Cherry picked to 5.0 in 0ec46cef1b7763d883ff9b797553873e63347208

**Comment by withinboredom** [comment]
Oh boy ... I don't think both of those were supposed to be merged, where they @jeffgolenski ?

**Comment by withinboredom** [comment]
disregard, just saw your comment :D

**Pull request merged**
