### PR TITLE
Actions: Clarify that SVN is the expected ID

### PR DESCRIPTION
**Pull request by danielbachhuber**
Clarifies that the SVN changeset ID (not Git hash) is the expected ID:

image

From conversation in p1656428550703389/1656427306.796319-slack-C0347E545HR

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

N/A

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I'm okay with that, although I don't know if we need to be that specific. Now that we've moved to Git, I think a git sha would work just as well, as long as we can easily find the reference back.

The SVN changeset is good right now because our tampermonkey script supports that shorthand syntax, but maybe instead of asking folks to be specific here in the Jetpack repo, we should update the tampermonkey script to support more types of references, such as the git sha from WordPress.com? This way folks would be able to paste whatever they know best.

What do you think?

****

Internal reference: 125-gh-tampermonkey-highlighter

**Review by wojtekn — DISMISSED** [review]
@danielbachhuber looks good, it's much clearer now.

**Comment by danielbachhuber** [comment]
> I'm okay with that, although I don't know if we need to be that specific. Now that we've moved to Git, I think a git sha would work just as well, as long as we can easily find the reference back.
> 
> The SVN changeset is good right now because our tampermonkey script supports that shorthand syntax, but maybe instead of asking folks to be specific here in the Jetpack repo, we should update the tampermonkey script to support more types of references, such as the git sha from WordPress.com? This way folks would be able to paste whatever they know best.
> 
> What do you think?

@jeherve I think my preference would be to stick with SVN changeset IDs because:
1. SVN is the source of truth.
2. It's simpler to have one way of doing things, instead of two ways of doing things.
3. I'm not sure how one would disambiguate a WPCOM Git SHA vs. a SHA in this repo (although I suppose the former could be prefixed with `wpcom-`.

This isn't a strong opinion, however. I'm happy to go in either direction. Feel free to use the GitHub PR suggestion feature to suggest any changes you'd like to the language I proposed.

**Review by jeherve — APPROVED** [review]
> I think my preference would be to stick with SVN changeset IDs because:
>
> SVN is the source of truth.
> It's simpler to have one way of doing things, instead of two ways of doing things.
> I'm not sure how one would disambiguate a WPCOM Git SHA vs. a SHA in this repo (although I suppose the former could be prefixed with wpcom-.

That works for me, I do not have a strong opinion on this either; I'm happy to continue to use changesets.

I've update the changelog entry and escape the backticks inside the template literal, so this should be good to go now. 🚢

**Comment by wojtekn** [comment]
> SVN is the source of truth.
> It's simpler to have one way of doing things, instead of two ways of doing things.

I agree with those reasons. We could change that to GIT when SVN is gone completely and GIT becomes the source of truth.

**Review by wojtekn — APPROVED** [review]

**Comment by danielbachhuber** [comment]
Thanks @jeherve and @wojtekn !

**Pull request merged**
