### PR TITLE
Themes Promo Card: fix typo.

### PR DESCRIPTION
**Pull request by jeherve**
Fix typo in Themes Promo Card.

### CODE REVIEW

**Comment by jeherve** [comment]
Actually, looking at this some more, I am a bit confused:

screen shot 2018-03-13 at 15 42 04

The box says "Only with Jetpack Professional", but the sentence that follows talks about Jetpack Personal and plans that "Security essentials for every WordPress site starting from $3.50". That price matches Jetpack Personal.

@richardmuscat What should this all say?

**Comment by keoshi** [comment]
This card tries to accomplish too much right now. If the focus is on Unlimited Themes then let's eliminate all other plans mentions and simplify it.

I'd suggest something like:

> ### Introducing Premium Themes
>
> Jetpack Professional gives you unlimited access to over 200 Premium WordPress themes for use on your site!
>
> With Jetpack Professional you also get real-time backups with an unlimited archive, automated malware scanning, enhanced site-wide search, and priority support from our global team of experts.

cc @benhuberman since you might have better suggestions than mine! :)

**Comment by benhuberman** [comment]
I agree with you, @keoshi, that nixing the non-Professional references is the way to go. As for the remaining copy, I'd love for it to be more user-goal-oriented. What do you think of something like this edit:

> ### Introducing Premium Themes
> To create a beautiful site that looks and works exactly how you want it to, Jetpack Professional gives you unlimited access to over 200 premium WordPress themes.
> Jetpack Professional is about more than just finding the perfect design. It's also about total peace of mind: real-time backups, automatic malware scanning, and priority support from our global team of experts guarantee that your site will always be safe and secure.

I can make tweaks to the above if there's a different point/angle you think should be highlighted more prominently.

**Comment by keoshi** [comment]
That's absolutely perfect — thank you so much @benhuberman ! ⭐️ 

@jeherve Do you want to go ahead and make the changes, or shall I jump in?

**Comment by keoshi** [comment]
Updated the copy in the latest commit, now the card looks like this:

image

**Comment by jeffgolenski** [comment]
Changes looks great, @keoshi 

Just a small note. After speaking with some older folks at the past few meetups, several of them mentioned that they have been having difficultly reading the size of the text (here and descriptions in settings). I'm wondering if we can bump up the size of this text a couple of px and make it #000 so it's easier to read. 

Here's an example of what I'm doing for settings right now: https://github.com/Automattic/jetpack/issues/9695

**Comment by keoshi** [comment]
Here's the image, @jeffgolenski:

image

I have no idea what's going on with my sandbox, but now I see the clouds again. If you agree, I'll create another PR to remove the clouds and implement the cleaner look.

**Comment by keoshi** [comment]
> I have no idea what's going on with my sandbox, but now I see the clouds again. If you agree, I'll create another PR to remove the clouds and implement the cleaner look.

Never mind, I'm just running an older version. The changes in #9352 will be inherited in this component.

**Comment by jeffgolenski** [comment]
@keoshi I think the version without the clouds is a bit nicer and matches our now common illo card design pattern. Also, the illustration itself. Can we make that blue block that the person is holding our Jetpack green like our other illos?

After that I think we'll be good to go!

**Pull request merged**
