### PR TITLE
Fixes sidebar for Gutenberg in not fullscreen mode

### LINKED ISSUE #18117: Nav Unification: Sidebar width obscures block editor in not - full screen mode
#### Steps to reproduce

1. Enable `nav-unification` paYJgx-1af-p2
2. Starting at URL: `/wp-admin/post-new.php`
3. Turn off Full Screen mode as shown in the screenshot below

#### What I expected
- Editor to account for sidebar width

#### What happened instead (Made the sidebar transparent on purpose just for illustration)

**The problem**

### PR DESCRIPTION
**Pull request by cpapazoglou**
Fixes #18117

#### Changes proposed in this Pull Request:

* Adapt `interface-interface-skeleton` width to new sidebar width

#### Testing instructions:

* Apply D54395-code
* Go to `/wp-admin/post-new.php` in your sandbox 
* Use `CMD + OPTION + SHIFT + F` to exit full screen mode

Before | After
-------|------
image | 

#### Proposed changelog entry for your changes:

* Adapts `interface-interface-skeleton` width to new sidebar width

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
This doesn't seem to work for me as other, more specific CSS from Core overwrites this:

image

**Comment by cpapazoglou** [comment]
Thanks for testing and noticing this @jeherve, there are some states that didn't catch! That made me think so I searched for `left: 160px` in a `position: absolute` context. This revealed also the following cases 66f9807.

**Review by marekhrabe — APPROVED** [review]
The editor now seems properly aligned in both fullscreen and standard modes. I can no longer see the broken state from the issue.

**Review by jeherve — APPROVED** [review]

**Comment by cpapazoglou** [comment]
@jeherve can you help me out with the failing test? It seems unrelated...

**Review by jeherve — APPROVED** [review]
Re-approving after merging latest `master` to address unrelated test failures.

**Comment by cpapazoglou** [comment]
Thanks! I have totally forgotten to rebase...

**Comment by cpapazoglou** [comment]
Deployed r218480-wpcom

**Pull request merged**
