### PR TITLE
Conversation: remove unneeded `entry-content` CSS class

### PR DESCRIPTION
**Pull request by retrofox**
_This PR is part of the [follow-up tasks](https://github.com/Automattic/jetpack/issues/18123) after merging `conversation`/`dialogue` blocks._

This PR removes the `entry-content` class from the conversation block markup. We don't want to apply all styles defined for this class in the conversation block. ~In case we want to polish the styles, we can do it in the block itself.~
Also, it applies block properties using the `useBlockProps()` hook, and tweak a little bit some styles.

Fixes #

#### Changes proposed in this Pull Request:

* Conversation: remove unneeded `entry-content` CSS class.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Test editing a conversation block. You shouldn't see big changes there, no bugs either.

### CODE REVIEW

**Review by kraftbj — DISMISSED** [review]

**Comment by anomiex** [comment]
I do see some noticeable styling changes when comparing a block created before this PR with one created after:
Screenshot
In particular, it seems to have lost some margins that were indenting the block's contents slightly and adding whitespace in between the individual dialog blocks in the conversation. Is that intended?

Other than that, it seems to work. I verified that editing a post with an old block doesn't break despite the change to the saved content here.

> **Proposed changelog entry for your changes:**
> * Conversation: remove unneeded `entry-content` CSS class.

Is this really something a typical end user will care about (particularly if you decide to fix the styling changes screenshotted above)? And if so, will that changelog entry actually communicate to them what they'll care about?

**Comment by retrofox** [comment]
> I do see some noticeable styling changes when comparing a block created before this PR with one created after:

Yes, it's true and something that we're already aware. I added a reference in the PR description: _In case we want to polish the styles, we can do it in the block itself._ Definitely, it's something that we need to take care but adding the `entry-content` probably isn't the best solution.

> _Wouldn't this inherit styles defined by themes that are not intended for a block?_
> _Think of themes that set a border and a box-shadow to the entry-content class. I guess we don't want these styles in our block._

https://github.com/Automattic/jetpack/pull/17916#discussion_r544227973


> Other than that, it seems to work. I verified that editing a post with an old block doesn't break despite the change to the saved content here.

👍 Just in case, these blocks are still beta.

> > **Proposed changelog entry for your changes:**
> > 
> > * Conversation: remove unneeded `entry-content` CSS class.
> 
> Is this really something a typical end user will care about (particularly if you decide to fix the styling changes screenshotted above)?
Well... maybe not. Should I remove the comment from the PR description?

**Review by anomiex — DISMISSED** [review]
Ok, if you're aware of the style change and aren't concerned about it for this PR, I'm fine with it.

>  Well... maybe not. Should I remove the comment from the PR description?

Wouldn't hurt. The comment is there for when we're preparing a Jetpack release and putting together the changelog, and I'm hoping to get away with gently poking people to better follow [docs/writing-a-good-changelog-entry.md ](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md) to make that job a bit easier for us. What you have there is written well, but misses the check for whether it's needed at all. 🙂

**Comment by retrofox** [comment]
Let's hold on and research how we can implement the styles to the dialogue content in the same way the paragraph block does.

**Review by allilevine — APPROVED** [review]
Removes the unneeded `entry-content` CSS class while keeping the conversation block editing experience the same. ✅ Tested on Atomic, JN, Simple, and self-hosted.

Before | After
------- | -----
Screen Shot 2021-01-05 at 12 01 39 PM | Screen Shot 2021-01-05 at 12 08 24 PM

**Comment by retrofox** [comment]
r219015-wpcom

**Pull request merged**
