### PR TITLE
Deprecate soft disconnect

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

* Deprecates Soft Disconnect

#### Jetpack product discussion

p9dueE-4n9-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Nothing should change, because we are not really using Soft disconnection. This PR only removes and deprecates code that is not actively in use and updates the documentation.

Test connection, disconnection and reconnection flows.

### CODE REVIEW

**Comment by coder-karen** [comment]
@leogermani is this PR ready for review?

**Comment by leogermani** [comment]
> @leogermani is this PR ready for review?

Yes!

**Comment by sdixon194** [comment]
Looks like there's some conflicts here that need resolving.

**Comment by sdixon194** [comment]
Hmm the build is failing here and I'm not sure what's going on.

**Comment by samiff** [comment]
> Hmm the build is failing here and I'm not sure what's going on.

The next-version script is looking to parse `@since $$next-version$$` but there was one line with `@since since...`. Looks like it built okay now.

**Review by sergeymitr — COMMENTED** [review]
Approved 👍 
Noticed something worth discussing, but it can be addressed in a separate PR.

**Review by sdixon194 — APPROVED** [review]

**Pull request merged**
