### PR TITLE
WP.com block editor: auth cookie varies depending on site protocol

### LINKED ISSUE #14385: WordPress.com block editor: cannot log in with JP 8.1.1.
This is a regression introduced by #14349. cc @mmtr 

#### Steps to reproduce the issue

1. Start with a site with no SSL certificate, running the most recent version of `master`, including #14349 
2. Log out
3. Clear your cookies for that site.
4. Try to log back in; you'll see that auth cookies cannot be created, and you consequently cannot log in.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #14385

#### Changes proposed in this Pull Request:

* Ensure one can log in to their site regardless of the site protocol

#### Testing instructions:

* To test on both a HTTP and HTTPS site:
* See testing instructions in #14349 

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by mmtr** [comment]
Seems we need something else than the suggested code in https://github.com/Automattic/jetpack/issues/14385. I tested this locally and, although cookies are created now as `Lax` and non-secure, I'm still not able to log in.

Screenshot 2020-01-20 at 11 37 12

**Comment by jeherve** [comment]
> I tested this locally and, although cookies are created now as Lax and non-secure, I'm still not able to log in.

I had that experience as well when I cleared my cookies before to submit the form, and thus did not have the `wordpress_test_cookie` cookie set. Refreshing the log in page sets that cookie and solves the issue (for me at least)

**Comment by mmtr** [comment]
> Refreshing the log in page sets that cookie and solves the issue (for me at least)

Yeah, I just experienced the same. It did work on a 2nd attempt in an incognito session.

Let me double check login flows before approve.

**Review by mmtr — APPROVED** [review]
This tests well for me. Verified that I can login on both HTTP and HTTPS sites. Calypso still loads the iframed block editor on HTTPS sites while it redirects to WP Admin on HTTP sites, which is the expected flow 👍

**Comment by dereksmart** [comment]
Nice thank you. Also was able to log in https and non without issue

**Review by dereksmart — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.1` in 8dad05168ba1bc5c92744ae211db0db053873891

**Pull request merged**
