### PR TITLE
MU WPCOM: Port the wpcom block editor nux feature from the ETK

### PR DESCRIPTION
**Pull request by lsl**
Related https://github.com/Automattic/dotcom-forge/issues/8241, https://github.com/Automattic/wp-calypso/issues/92861

## Proposed changes:

> [!TIP]
> Changes are too large because I copied `wpcom-block-editor-nux`, `dotcom-fse/lib` and `@automattic/tour-kit` into `jetpack-mu-wpcom`
>
> It would be better to follow the Test Instructions below to check whether the functionalities work as expected or not

* Migrates wpcom-block-editor-nux to jetpack-mu-wpcom
* Resolved the `@automattic/tour-kit` dependency as follows:
  * The following packages are outdated so we have to release the new packages to resolve the peer dependencies issue
    * `@automattic/components`
    * `@automattic/tour-kit`
    * `@automattic/viewport-react`
  * However, I found we cannot introduce the `@automattic/components` to the `jetpack-mu-wpcom` because:
    * It requires `@automattic/calypso-analytics` package that uses the `EventEmitter` from the `events` package. I'm unsure whether to introduce the `events` package on the browser side.
    * It requires `i18n-calypso` package, and the issue is the same as above.
    * It requires `@emotion/*` packages that are used by the following components and I don't think it makes sense to introduce the whole `@emotion/*` packages for this purpose.
      * `LoadingPlaceholder`
      * `SiteThumbnail`
      * `UpsellMenuGroup`
  * Next, I found the `@automattic/tour-kit` is only used by the `wpcom-block-editor-nux`, so I decided to move the whole package to `jetpack-mu-wpcom` to get rid of those dependencies
  * Finally, just copied the following components to `jetpack-mu-wpcom` because I think they are not too complicated
      * `PaginationControl`
      * `ClipboardButton`
      * `FormInputCheckbox`
      * `FormLabel`
* Resolved the `recordTracksEvent` call
    * Replaced the `recordTracksEvent` with the `wpcomTrackEvent` as we did for other migrations
* Got rid of the type definition to remove the following dependencies
  * `@automattic/onboarding`
  * `starter-page-templates/store`
  * `wpcom-block-editor-nav-sidebar/src/store`

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Before getting started, you have to
* Apply changes to your sites
* Sandbox your API and ensure your siteSlug domain points to your sandbox for simple sites

### Welcome Tour

* Go to the Editor
* Make sure the Welcome Tour works as before
  

### Blogging prompts modal

* Go to /wp-admin/post-new.php?new_prompt=true
* Make sure you can see the blogging prompts modal
  

### Purchase notice (Payments block)

* Go to /wp-admin/post-new.php?notice=purchase-success
* Make sure you can see the purchase notice
  

### Draft post modal & First post published modal - Only for the "write" intent

* Create a new site
* Select the "Write & Publish" goal
* Select the "Choose a design" starting point
* Verify write your post modal show
  
* Publish the post
* Verify the first post published modal show (the "write" intent only)
  

### [Seller celebration modal](https://github.com/Automattic/wp-calypso/pull/61222) - Only for the "sell" intent

* Go to /setup?siteSlug=your_site
* Select the `Sell online`
* After the onboarding, go to create a new page
* Insert any payment blocks and save
  * Paid Content
  * Pay with PayPal
  * Payment Buttons
* Make sure you can see the seller celebration modal
  

### [Sharing modal](https://github.com/Automattic/wp-calypso/pull/76267) - Not for the `start-writing` or `design-first` intent

* Go to /wp-admin/post-new.php to create a new post on your **PUBILC** site
* Publish the post
* Make sure you can see the sharing modal
  

### [Video celebration modal](https://github.com/Automattic/wp-calypso/pull/67539) - Only for the "videopress" intent

* Start the flow at /setup/videopress
* When you land on the Site Editor, upload a video and save
* Make sure you can see the video celebration modal
  
* Note that the modal doesn't seem to work on atomic sites as it requests the `/sites/:site` endpoint to get the value of `options?.launchpad_checklist_tasks_statuses?.video_uploaded` from the response to check whether the video has been uploaded

### CODE REVIEW

**Review by okmttdhr — COMMENTED** [review]
Tested and ensured the following works well on an Atomic site 

- Welcome Tour ✅ 
- Blogging prompts modal ✅ 
- Purchase notice (Payments block) ✅ 
- Sharing modal ✅ 

Will test the following;

- [ ] Draft post modal & First post published modal
- [x] Seller celebration modal -> Tested and worked well ✅ 
- [x] Video celebration modal -> Tested and worked well ✅

**Comment by okmttdhr** [comment]
>* Go to /wp-admin/post-new.php?showDraftPostModal=true
>* Go to /start/setup-site?siteSlug=<your_site>
>* Select write intent and you'll redirect to the post editor
>* Verify write your post modal show. If it's not shown, go to /wp-admin/post.php?showDraftPostModal=true directly. It doesn't work if you go through the onboarding flow with the "write" intent now...
>  
>  * Note that if it's still not shown, open the "Welcome Guide" manually because we want to display it and hide the Welcome Guide the first time and then display the Welcome Guide after you refresh the page.

hmm, I could not display the modal even in production. 
I selected the intent, made sure I hid the Welcome Modal, and then visited both `/wp-admin/post-new.php?showDraftPostModal=true` and `/wp-admin/post.php?showDraftPostModal=true` but nothing appeared. 🤔

**Comment by arthur791004** [comment]
> hmm, I could not display the modal even in production.

Yes. It's buggy on production as the `showDraftPostModal` flag doesn't pass to the editor correctly.

> made sure I hid the Welcome Modal

Sorry for not being clear. I mean you have to open the Welcome Guide if it's not shown because they share the same toggle 😓

**Comment by okmttdhr** [comment]
>>hmm, I could not display the modal even in production.
>Yes. It's buggy on production as the showDraftPostModal flag doesn't pass to the editor correctly.

I'm not sure if I can approve this PR, but if it's unstable in production, I guess we can merge it?
It would be good to have a separate issue for this buggy modal (maybe in One Board?).

**Comment by arthur791004** [comment]
> It would be good to have a separate issue for this buggy modal (maybe in One Board?).

Yes. It will raise another PR to fix it!

**Comment by arthur791004** [comment]
> I'm not sure if I can approve this PR, but if it's unstable in production, I guess we can merge it?
It would be good to have a separate issue for this buggy modal (maybe in One Board?).

Sorry, I realized I was wrong. Referring to https://github.com/Automattic/wp-calypso/pull/57019, the modal is shown only when you land on the post editor through the “Choose a design” since it's unclear for users why they land on the post editor after selecting a design.

So, the correct steps are
1. Create a new site
2. Select the "Write & Publish" goal
3. Select the "Choose a design" starting point
4. You will see the modal when you land on the post editor

**Comment by okmttdhr** [comment]
Thanks for the update @arthur791004!

Here's my testing result:

1. Created a new site
2. Selected the "Write & Publish" goal
3. Selected the "Choose a design" starting point
4. Sandboxed the newly created site right before landing on the post editor
5. Landed on the post editor and confirmed wpcom-block-editor-nux was from jetpack-mu-wpcom
6. I could not observe the "Write your first post" modal 🙄 
7. Published the post
8. Observed the "First post published modal" ✅

**Comment by okmttdhr** [comment]
>I could not observe the "Write your first post" modal 🙄

The modal does not seem to display even in production (i.e., ETK), too. 😶‍🌫️

**Comment by arthur791004** [comment]
> I could not observe the "Write your first post" modal 🙄

hmmm...it's weird that I can see the modal by either ETK or jetpack-mu-wpcom 🤔

**Comment by fushar** [comment]
I can't also see any modal in production following the above steps 😂 

image

**Comment by arthur791004** [comment]
Am I missing to mention something 🤔

https://github.com/user-attachments/assets/0b56d9f7-a21b-4615-9d76-f14661bafd09

**Comment by fushar** [comment]
https://github.com/user-attachments/assets/50baae30-b61a-4de1-9dab-3b06b015e3ff

**Comment by okmttdhr** [comment]
https://github.com/user-attachments/assets/abc164f3-9fe2-4f0d-b012-aa42b03917fd

**Comment by arthur791004** [comment]
hmmm...weird 😂

**Comment by arthur791004** [comment]
Does session storage work on your side 🤔

**Comment by fushar** [comment]
We can do a quick huddle tomorrow to resolve this together once and for all.

**Comment by arthur791004** [comment]
I think the Welcome Guide in the Site Editor is turned off on your side, so you cannot see the “Write your first post modal” on the newly created site.

Could you go to the Site Editor on any of your sites to open the Welcome Guide and then follow the steps below to see whether the modal is shown? 🙏 
* Create a new site
* Select the "Write & Publish" goal
* Select the "Choose a design" starting point
* You will see the modal when you land on the post editor

**Comment by okmttdhr** [comment]
>Could you go to the Site Editor on any of your sites to open the Welcome Guide and then follow the steps below to see whether the modal is shown? 🙏

After opening the Welcome Modal and following the steps, I finally succeeded in testing the "Write your first post" modal! Thank you for your work covering all the scenarios.

**Review by okmttdhr — DISMISSED** [review]
I believe we're good to go 🙏 🚀

**Review by taipeicoder — APPROVED** [review]

**Pull request merged**
