### PR TITLE
Docker: Add psySH as default wp shell REPL

### PR DESCRIPTION
**Pull request by brbrr**
#### Changes proposed in this Pull Request:

* adds [psySH](https://psysh.org) REPL into WP image;
* use `psySH` as default REPL in `wp shell`

#### Testing instructions:

* Delete the old images `yarn docker:down`
* Rebuild your docker image: `yarn docker:build-image`
* launch the containers `yarn docker:up -d`
* get into `wp shell` by running `yarn docker:wp shell`
* Make sure you see some color output, and your favorite commands still work
* Try to run `wp shell` with build-in REPL: `yarn docker:wp shell --basic`

You should see something like this: 
1  docker 2019-06-10 18-18-17

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by jeherve** [comment]
That sounds fancy!

What kind of visual changes should I expect after this PR? I can't seem to spot any changes right now.

image

**Comment by brbrr** [comment]
Ouch, it seems like `psySH` not really hooked into your wp-cli. 

Did you rebuild the docker image? You should see `curl https://git.io/psysh -o psysh` in the output of `yarn docker:build-image`
 
Can you double check that `psySH` is installed in your docker image and available in PATH? Try 
```
$ yarn docker:sh
in-docker-shell> which psysh
```

**Comment by brbrr** [comment]
taking my words back - seems like it just not works :shrug:

**Comment by brbrr** [comment]
I think I fixed the problem with the latest commit. There were 2 problems: 
- incorrect URL used to fetch the binary
- It's impossible to create new files in `/var/www/html` via dockerfile, since the folder is being overwritten by`run` script`

**Review by jeherve — APPROVED** [review]
This works well for me now 👍

**Pull request merged**
