### PR TITLE
Search: add WP-Admin page for search and instant search toggling

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
* TBD

#### Jetpack product discussion
pcNPJE-7J#comment-161

#### Does this pull request change what data or activity we track or use?
probably yes

#### Testing instructions:
* TBD

### CODE REVIEW

**Comment by bluefuton** [comment]
@kangzj would the new endpoint discussed in pcNPJE-b8-p2 help simplify things here?

**Comment by kangzj** [comment]
> @kangzj would the new endpoint discussed in pcNPJE-b8-p2 help simplify things here?

Hi @bluefuton I think the settings are all dealt by Redux already by the frontend in the plugin - and all calls are local to the WP installation and then would be forwards by the backend to WPCOM.

The endpoint discussed would be particularly very useful to Calypso at the stage I guess. :-)

**Comment by bluefuton** [comment]
@kangzj I'll try another question :) I think ideally we'd get away from checking for specific plans in each UI (`is-business-plan` for example) because if anything changes about the plan or what's included in it, we'll have to alter it in multiple places. How can we push this responsibility up to the API?

**Comment by kangzj** [comment]
> @kangzj I'll try another question :) I think ideally we'd get away from checking for specific plans in each UI (`is-business-plan` for example) because if anything changes about the plan or what's included in it, we'll have to alter it in multiple places. How can we push this responsibility up to the API?

Agreed. That would definitely help simplify and centralize the logic of testing whether a feature exists for a site. A little concern is that it's a pretty fundamental thing, and we would create another set of very specialized APIs and would make confusion for other developers in the teams, as we'd have two ways of doing the same thing.

So just a thought, I guess if we are to do it, could we potentially consider for the future, and allow new modules and features to be added following a special pattern or into a configuration file etc, which would make it easier for the whole team to recognize its value.

-----

For the PR I'm working on, we'll still need to do things like `is-business-plan`, which is not ideal indeed. I'm more than happy to use the new API if the time allows :-D

**Comment by kangzj** [comment]
The PR is closed in favour of #20224 and the PRs following that.

**Pull request closed without merging**
