### PR TITLE
Drop Legacy Stats experience

### PR DESCRIPTION
**Pull request by myhro**
Fixes Automattic/red-team#48.

## Proposed changes:

* Remove UI and code of the Legacy Stats experience.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

### Odyssey Flag

- Disable the `enable_odyssey_stats` flag:

```
$ jetpack docker wp shell
> use Automattic\Jetpack\Stats_Admin\Main as Stats_Main;
> Stats_Main::update_new_stats_status( false );
= true
```

- (Optional) Confirm the flag was properly disabled:

```
> use Automattic\Jetpack\Stats\Options as Stats_Options;
> Stats_Options::get_option( 'enable_odyssey_stats' );
= false
```

### Stats Page

- Go to `/wp-admin/admin.php?page=stats`
- The Legacy Stats shouldn't appear in the page.
- There should be no `Fetch/XHR` requests in the `Network` tab of the browser developer tools.

### Settings Page

- Go to `/wp-admin/admin.php?page=jetpack#/traffic`
- There should be no `Enable a new Jetpack Stats experience` toggle in the `Jetpack Stats` section.

### Comparison

| Before | After |
| :-: | :-: |
| image | image |
| image | image |

### CODE REVIEW

**Comment by myhro** [comment]
@kangzj Hi. I kept the deprecation notice, allowing the user to switch to the new Stats, plus the upsell for other products at the bottom.

Is this what you had in mind? Or should we just redirect the user to the new Stats page without showing anything?

**Comment by kangzj** [comment]
Thanks for working on this! Could we please make sure the sparkline still works after the PR?

image

It should look something like the following,

 
image

Thanks 🙇

**Comment by myhro** [comment]
Thanks for catching that, Jasper. I missed it because of [this detail][1]:

> Checking this box will add the stats “Sparkline” to your admin bar when you’re viewing the front end of your site. If you’re in the wp-admin part of your site, this will not display.

Should be fixed now:

image

---

Can you please take a look again? I didn't rebase the PR to ease your review, but let me know if you prefer me to rebase/force-push first.

[1]: https://jetpack.com/blog/how-to-install-stats-and-analytics-on-your-wordpress-site-with-jetpack/

**Comment by myhro** [comment]
@kangzj Hi. This is a gentle ping to ensure this PR doesn't slip through the cracks.

**Review by kangzj — DISMISSED** [review]
Thanks for taking on this one. Everything works for me now! 🚀

**Comment by myhro** [comment]
Thanks for the review. I've rebased and fixed the previous conflicts. Will merge when CI checks turn green.

**Pull request merged**
