### PR TITLE
Remove JSON polyfill from postmessage

### PR DESCRIPTION
**Pull request by sgomes**
This polyfill hasn't been needed since IE 8 became widely adopted, sometime around the Early Cretaceous Period. Removing it saves more than a few bytes.

Related wpcom change: D54236-code

#### Changes proposed in this Pull Request:
* Remove JSON polyfill from `postmessage.js`

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* Go to any site that uses `postmessage`, e.g. `https://automattic.com`
* Ensure that there are no errors

#### Proposed changelog entry for your changes:
* Includes: removed JSON polyfill from `postmessage.js`

### CODE REVIEW

**Comment by sgomes** [comment]
Regarding the wpcom fusion error, it seems to be complaining about a malformed patch:

```
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 10
```

Since this seems to be a fusion issue, I went ahead and marked the check as a success.

**Comment by anomiex** [comment]
I wonder whether that was the correct form, versus using the top option with the "Force create Phab Diff" checkbox checked. 

OTOH, now instead of giving any error it instead observes that this brings the file in sync (after D54236-code was merged, I guess) so it's all good now.

**Review by anomiex — APPROVED** [review]

**Comment by kraftbj** [comment]
> after D54236-code was merged, I guess

Yup, Fusion doesn't expect a phab diff to be created first, so it can get a bit punchy, but the expected result post-merge is for it to realize that this is just bringing JP up to date.

**Comment by sgomes** [comment]
Thank you for the quick review + merge, @anomiex and @kraftbj! 🙇  

Sorry about the fusion confusion. I need to start looking for files in the Jetpack repo before making changes  in phab 😅

**Pull request merged**
