### PR TITLE
Adding support for post format for widget visibility

### PR DESCRIPTION
**Pull request by pkevan**

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Hey @pkevan , this has been sitting for a while :)  Looks like it needs some logic around what happens when people change from a theme that supports post formats to one that doesn't.

Are you interested in updating the PR?

**Comment by pkevan** [comment]
Gladly, any pointers around what to check might help me - as you say, it's been a while!

**Comment by samhotchkiss** [comment]
Sure-- we're going to try to get a lot of changes in to widget visibility for the next release (not the upcoming, but the one after), which will probably land some time in March.

One route that I would investigate is adding a conditional along the lines of "if post formats are not available but this widget has a post format set, show the box with a warning" to allow people to fix the issue.

What do you think?

**Comment by pkevan** [comment]
It probably makes sense just to delete the setting if the post format is no longer available or has been disabled

**Comment by samhotchkiss** [comment]
Except then you might wind up with people unexpectedly having a widget
somewhere.  Probably best not to surprise them :)

**Comment by pkevan** [comment]
Not that easy to achieve - since everything seem to happen on an ajax request so can't fire an error notice.

What is the expected behaviour with custom taxonomies, as this is the same problem which would happen there

**Comment by samhotchkiss** [comment]
I'll play around with this a little bit before 3.5

**Comment by zinigor** [comment]
I have just tested the changes using two different themes: Twenty Fourteen (supports formats) and Confit (does not support formats). There is a problem when you:
1. Select widget visibility based on formats in Twenty Fourteen.
2. Switch to Confit
3. Open Widget Visibility to find that the Post Format is selected, but the list is not loaded due to lack of format support. Also it looks like in the absence of formats the hide and show directives always work no matter what post is loaded.

By the way, since this PR has been sitting for a while, perhaps you can rebase it? If you need help with that, please let us know.

**Comment by samhotchkiss** [comment]
Closing for now-- if this gets updated per @zinigor's comments and rebased, we'll re-open and take a fresh look

**Pull request closed without merging**
