### PR TITLE
Protect : Validate userID with (int)

### PR DESCRIPTION
**Pull request by Umangvaghela**
#### Changes proposed in this Pull Request:

* Validate UserID.

#### Testing instructions:

*

### CODE REVIEW

**Comment by Umangvaghela** [comment]
@enejb 

Sir ,can you review this PR because last commit you did it in this file.

Thanks

**Comment by enejb** [comment]
Before we do this change @Umangvaghela can you explain what issue this is trying to solve, why is this change necessary? 

As far as I can tell the code is doing is not about validating user ID but setting it to an integer. Which is then used in urls. Which gets turned into strings anyways. So casting it to a integer is not that helpful. But maybe I am not understanding something.z
z
Thank you

**Comment by Umangvaghela** [comment]
@enejb 

WordPress always use absint($_GET['user_id']) to get user id. I want to cast user_id with (int) so user id converts in INT.And I do not see anywhere in Wordpress Core file to add $_GET['user_id'] without absint() function. 
Yes, these changes are necessary because we can't use USER_ID without convert in int. I think.
Thanks

**Comment by Umangvaghela** [comment]
@enejb 

Sir what you think on this PR it is usable or not.

Thanks

**Comment by enejb** [comment]
Hi @Umangvaghela

> Yes, these changes are necessary because we can't use USER_ID without convert in int.
This is not really true. Did you have a chance to test it? 

The reason why WordPress Core converts $_GET['user_id'] into int is because of security reasons. 

What issues would this solve? Currently not converting things to integers works as expected.
We are never saving or displaying the `$_GET['user_id']` on our end so we don't need to cast it since it won't work otherwise. Also we only convert 

But maybe I am missing something can you please explain. 

Thank you

**Pull request closed without merging**
