### PR TITLE
Site: Endpoint UI, make the request wpcom only and only return plan data

### PR DESCRIPTION
**Pull request by enejb**
Make the request agains the shadow site.

#### Testing instructions:
Does the plans page show up as expected?

### CODE REVIEW

**Comment by enejb** [comment]
Other improvements I think we can make is 

- [ ] only request the necessary fields. I think in this case it is just the plan field.
- [ ] Store the value of the api in a transient, but we need to make sure we are able to bust the cache. Since we don't want to introduce errors where we show the user the wrong plan after they just updated it.

**Comment by dereksmart** [comment]
@enejb what does this change do?  

Watching the network console, I'm seeing that the response times for both this and master are the same.  I also noticed that the response json is the same as well.  What does removing `'?force=wpcom'` do?

**Comment by enejb** [comment]
It grabs the data form the .com's shadow site instead of the going back to the Jetpack site to generate the data 

force=wpcom = jetpack Site -> wpcom -> data returns 
force=jetpack (default) jetapck Site -> wpcom -> jetpack site -> wpcom -> data retruns

How are you testing the change? And timing it?

**Comment by enejb** [comment]
This is what I am seeing
screen_shot_2017-02-10_at_12_12_23

**Comment by dereksmart** [comment]
@enejb 

`How are you testing the change? And timing it?`

I was watching the `/site` request/response in the Network console. 
screen shot 2017-02-13 at 9 35 01 am

**Comment by enejb** [comment]
I think what might be happening is that your are always retrieving the api from wordpress.com for your site. There is a setting in calypso that lets you toggle that.

When I did a test for force=jetpack vs force=wpcom
I notices about a second difference between the 2 requests. 

force=wpcom 
screen shot 2017-03-02 at 14 13 13

force=jetpack ( default and current setting for most sites )
screen shot 2017-03-02 at 14 17 55

**Pull request merged**
