### PR TITLE
Added Title attribute to the iframe for Archive.org book embed

### PR DESCRIPTION
**Pull request by rickcurran**
This commit adds a `Title` attribute to the iframe for Archive.org book embed to improve the Section 508 and WCAG 2.0 accessibility compliance.

The change here tackles the open issue #7370 "Shortcode Embeds: should include title attribute on iframe output to meet accessibility standards". There are multiple files which have iframes without a title attribute, but this changes tackles the first one I found in order to establish a correct format / methodology before updating the rest. 
This change adds a fixed text string which would be a translatable string within Jetpack's i8ln language strings. However, as this embed is generated from a shortcode it would also be an option to enable this string to be specified by the user as an additional attribute to the shortcode.

Fixes #

#### Changes proposed in this Pull Request:

A title attribute with a fixed i8ln string is added to the iframe that is rendered within this piece of code.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
This adds to an existing feature of Jetpack.

#### Testing instructions:
To test this please try adding an Archive.org book using the `archiveorg-book` shortcode. E.g. 

`[archiveorg-book id=inferno00dant_2 width=560 height=384]`

With the code in place the rendered iframe should now have a title attribute.

#### Proposed changelog entry for your changes:
This commit adds a `Title` attribute to the iframe for Archive.org book embed to improve the Section 508 and WCAG 2.0 accessibility compliance.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
LGTM!

**Review by jeherve — CHANGES_REQUESTED** [review]
Unit Tests are failing right now though:
```
WP_Test_Jetpack_Shortcodes_ArchiveOrg::test_shortcode_book
Failed asserting that '<div class='embed-archiveorg-book' style='text-align:center;'><iframe title='Archive.org Book' src='https://archive.org/stream/goodytwoshoes00newyiala?ui=embed#mode/1up' width='600' height='300' style='border:0;' webkitallowfullscreen='true' mozallowfullscreen='true' allowfullscreen></iframe></div>' contains "iframe src='https://archive.org/stream/goodytwoshoes00newyiala?ui=embed#mode/1up' width='600' height='300'".
/tmp/wordpress-latest/src/wp-content/plugins/jetpack/tests/php/modules/shortcodes/test-class.archiveorg.php:53
```

You'll need to update the test to match the new structure.

**Comment by rickcurran** [comment]
@jeherve Thanks! Can you give me some guidance about updating Unit Tests for this, it's not something I've done before so not sure what action to take here.

**Comment by jeherve** [comment]
In `tests/php/modules/shortcodes/test-class.archiveorg.php` you'll find a function  named `test_shortcode_book`. That function checks that when you add a specific shortcode to post content, that post includes a specific iFrame as a result. You'll want to update the expected markup in there since the iFrame that is now displayed now includes a title attribute as well.

To run the tests locally after making the changes, and thus checking that the tests now pass, you can run `yarn docker:phpunit --filter WP_Test_Jetpack_Shortcodes_ArchiveOrg`.

**Comment by rickcurran** [comment]
@jeherve Thanks, I've updated the unit test file to include the `title` attribute and committed that to the PR.

**Review by jeherve — APPROVED** [review]
I needed to rebase that branch, but it should be okay now. This should be good to merge!

**Comment by rickcurran** [comment]
Ok, great. If this is all ok then I can take a look at all the other iframes that need `title` attributes added to them, should I just do each of them as separate PRs?

**Comment by jeherve** [comment]
> If this is all ok then I can take a look at all the other iframes that need title attributes added to them, should I just do each of them as separate PRs?

Let's go at them one file at a time, if that's alright with you. It's easier to test and review that way, it ensures we won't miss anything by mistake.

**Pull request merged**
