### PR TITLE
Sync Health Delay and Error UIs in Site Health

### PR DESCRIPTION
**Pull request by mdbitz**
Jetpack Sync tests added for Sync Delays exceeding 5 minutes and when data loss was experienced.

#### Changes proposed in this Pull Request:
* Extends the Sync Health test so that it now displays a recommendation when the sync lag exceeds 5 minutes or when the health state has experienced data loss (lag > 15 && actions over 1000).

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.
Extends the existing Sync Site Health Test.

#### Testing instructions:

* Enable Jetpack and Sync Module
* Go to the SIte Health Admin Page `/wp-admin/site-health.php`
* Under Passed Tests you should not see any Jetpack Sync warnings in critical or recommended
* Update the Sync Health to Out of Sync  `Sync_Health::update_status( Sync_Health::STATUS_OUT_OF_SYNC )` dropped into the wp.config.php or the functions theme file or etc.
* Refresh the Site Health Admin Page
* Verify that under critical issues the Jetpack Sync info displays and aligns with the designs https://wp.me/p6TEKc-3uv

* Reset the Sync Health to In Sync `Sync_Health::update_status( Sync_Health::STATUS_IN_SYNC )`
* Point your Jetpack Connection to a bad address  `define( 'JETPACK__SANDBOX_DOMAIN', 'badbadbad23434.example.com' );`
* Update or Create a new Post.
* Verify sync health is not displayed in recommendations
* Wait 5-10 minutes.
* Refresh the Site Health Admin Page
* Verify that under recommended issues the Jetpack Sync delayed test displays and aligns with the designs https://wp.me/p6TEKc-3uv. Check that the X minutes updates as time goes on.

* Remove the Jetpack Connection sandbox
* refresh the admin a few times (clear the queue )
* Refresh the Site Health Admin Page
* Verify sync health is not displayed in recommendations

#### Proposed changelog entry for your changes:

* Enhance Jetpack Site Health Tests to display Sync health to users.

### CODE REVIEW

**Review by roccotripaldi — DISMISSED** [review]
I love it!

**Comment by mdbitz** [comment]
Currently re-basing, comparing against designs and then adding Full Sync Callback.

**Review by roccotripaldi — APPROVED** [review]
I have one small suggestion and we can fix it in an other PR. 
After someone clicks the full sync button, we need to indicate a loading state. I'll think on how we can achieve that.

**Comment by akirk** [comment]
@roccotripaldi, @mdbitz please don't write translatable strings like in https://github.com/Automattic/jetpack/pull/15199/files#diff-43ad69f84dbe6807242fdda0ebda84ffR563L:
```
'<p>%1$s</p><p><span class="dashicons fail"><span class="screen-reader-text">%2$s</span></span> %3$s<strong> %4$s <a id="full_sync_request_link" href="#">%5$s</a> %6$s</strong></p>',
__( 'The information synced by Jetpack ensures that Jetpack Search, Related Posts and other features are aligned with your site’s current content.', 'jetpack' ),
__( 'Error', 'jetpack' ),
__( 'Jetpack has detected an error while syncing your site', 'jetpack' ), /* translators: screen reader text indicating a test failed */
__( 'We recommend', 'jetpack' ),
__( 'full sync', 'jetpack' ),
__( 'to align Jetpack with your site data.', 'jetpack' )
```
This is string concat at its worst :( Please remember that translators don't see segments in sequence and are unaware about the placeholder-filled string. This should not have been approved.

**Comment by akirk** [comment]
There is another one:
```
'<p>%1$s</p><p><span class="dashicons dashicons-clock" style="color: orange;"><span class="screen-reader-text">%2$s</span></span> %3$s <strong>%4$s %5$d %6$s</strong></p>',
__( 'The information synced by Jetpack ensures that Jetpack Search, Related Posts and other features are aligned with your site’s current content.', 'jetpack' ),
__( 'Clock', 'jetpack' ),
__( 'Jetpack has identified a delay while syncing individual content updates. Certain features might be slower than usual, but this is only temporary while sync catches up with recent changes to your site.', 'jetpack' ), /* translators: screen reader text indicating a test failed */
__( 'We’re seeing a current delay of', 'jetpack' ),
intval( $sync_queue->lag() / MINUTE_IN_SECONDS ),
__( 'minutes.', 'jetpack' )
```
Could you please improve this with a follow-up? Thanks!

**Comment by kraftbj** [comment]
Opened 15379 to track updating the strings. Thanks @akirk.

**Pull request merged**
