### PR TITLE
Social Media Icons: update actions to filters.

### PR DESCRIPTION
**Pull request by jeherve**
As actions, it could only echo an additional icon before or after the whole widget.

Once this is fixed, site owners will be able to use the filters like in this example:

```php
/**
 * Add a link to a LinkedIn Company Page at the end of the Social Icons widget.
 *
 * @return string $html Social Icons widget HTML structure.
 */
function jeherve_linkedin_company_page_widget( $html ) {

	// LinkedIn Company information.
	$linkedin_company_name = 'Automattic';
	$linkedin_company_url  = 'https://www.linkedin.com/company/58194';

	// Build the icon.
	$linkedin_icon = '<li>
		<a
			title="' . esc_attr( $linkedin_company_name ) . '"
			href="' . esc_url( $linkedin_company_url ) . '"
			class="genericon genericon-linkedin"
			target="_blank"
		>
			<span class="screen-reader-text">
				' . esc_html( $linkedin_company_name ) . '
			</span>
		</a>
	</li>';

	// return the existing Widget HTML, and add the LinkedIn Icon.
	return $html . $linkedin_icon;

}
add_filter( 'jetpack_social_media_icons_widget_list_after', 'jeherve_linkedin_company_page_widget' );
```

### CODE REVIEW

**Comment by jeherve** [comment]
cc @macmanx2

**Comment by samhotchkiss** [comment]
I'd lean towards a different tack here, which would be to leave the current hooks, but then, when creating the social icons, create them as an array which we then filter, then implode.  This would make it much easier to insert new icons in the middle, change things for a specific icon, etc.

Thoughts?

**Comment by jeherve** [comment]
That would work for me.

**Comment by zinigor** [comment]
@samhotchkiss and @jeherve please take a look at my change. I decided to go the way Sam suggested and made the code a little more DRY in the process. This enables users to add any HTML into any place - on the ends of the list as well as in between, also change the order of icons.

**Comment by dereksmart** [comment]
@zinigor overall looks nice -- could you please provide an example usage that we can put on our support docs? 

My only real concern is there's no back compatibility for people who have set up the before/after icons with the after/before hooks.  It won't throw any errors, but still would be an unexpected result of upgrading to 3.8

**Comment by macmanx2** [comment]
I don't think we'll need to worry too much about folks using the old after/before hooks.

It was never published outside of here, and all the old hooks allowed for was changing the icon. Until this change goes through, there is still no way to provide a custom URL, so we really only have to worry about folks who saw the hooks in code or on GitHub and switched the icons on their existing links, which given the relevance of the icons seems unlikely.

I'm sure there are some who did that, there are always some, but I predict the user and support impact from such a change will be incredibly small.

**Comment by soulseekah** [comment]
@zinigor thank you! I was about to start writing a patch for this then found this pull request. Good stuff, I like :+1:

**Comment by zinigor** [comment]
Added changes from #2654 and rebased this PR, should be good to go now.

**Comment by dereksmart** [comment]
This shows all of the icons that link even if they're not being used.

**Comment by zinigor** [comment]
Here's an example of how you can use the newly added filter to add a new social network link:

```

add_filter( 'jetpack_social_media_icons_widget_array', function( $html_array ) {
	return
		$html_array +
		array(
			25 =>    // This key can be modified to change the order the new item will appear in the list
				'<a title="Automattic" '
				. 'href="https://www.linkedin.com/company/automattic" '
				. 'class="genericon genericon-linkedin" target="_blank">'
				. '<span class="screen-reader-text">Automattic Company Profile</span></a>'
		);
});
```

**Comment by jeherve** [comment]
Fixes #2657 and #2653

**Comment by dereksmart** [comment]
Looks good, tests well.  Thanks for the example filter.

**Comment by backpackingseries** [comment]
Hello,

Redirected here from WordPress [support forum](https://wordpress.org/support/topic/how-to-add-bloglovin-and-flipboard-to-jetpacks-social-icons-widget/#post-10405972) and posting a query for more eyes and possible help.

I want to add a Flipboard 'Follow us' icon (not a sharing button) to Jetpack Social Icon widget in WordPress.

The Flipboard icon is not part of Genericons font but, Flipboard itself offers a JS code to generate an icon.

`<a data-flip-widget="ico" href="https://flipboard.com/@Backpacking73vi?utm_campaign=tools&utm_medium=follow&action=follow">Flipboard</a><script src="https://cdn.flipboard.com/web/buttons/js/flbuttons.min.js" type="text/javascript"></script>`

Though I can use this code in a custom HTML widget to display the icon, but I want it to be part of the Jetpack's social icon widget, such that all social icons (Facebook, Instagram, Flipboard, etc.) are bunched together.

I am not a programmer. Can someone please help resolve this?

Thank you Kind regards,

PS: This is not a request for generating a Flipboard share button, which I have done successfully using the WordPress Dashboard -> Settings -> Sharing -> Add a New Service.

**Comment by zinigor** [comment]
Hello @backpackingseries ! 

We have recently deprecated the widget that this PR is about. Now we are using a different Social Icon Widget to which you can add any links that you want. The problem would be adding the icon to your link, because we don't have one for Flipboard. What I see instead is a link that has `icon-chain` as a class. 

```
<a href="https://flipboard.com/@Backpacking73vi?utm_campaign=tools&amp;utm_medium=follow&amp;action=follow" target="_self">
     <svg class="icon icon-chain" aria-hidden="true" role="img">
          <use href="#icon-chain" xlink:href="#icon-chain"></use>
      </svg>
</a>
```

If you have control over your site's theme and can add scripts or styles, you can probably add a style that would target this link with a selector like:

```
.jetpack-social-widget-item:last-child svg {
    display: none;

}

.jetpack-social-widget-item:last-child a {
    background: black;
}
```

That's assuming that your link to Flipboard is going to be last. The black background setting is just an example of how you can target the link and change the way it looks.

Hope that helps!

**Comment by backpackingseries** [comment]
Hello @zinigor,

Thank you for the help and suggesting a possible solution.

I just got off performance testing / tuning the site and had to remove few fonts that were slowing it down. I also realized that one of the plugin I use already loads Font awesome (that offers an icon for Flipboard) from the disk. However, I am not so sure whether I could tap into the local copy of the font (instead of enqueing it separately and incurring additional latency to fetch it) and will give it try along with the code above.

Though I have control over adding scripts and styles, my programming skills are limited. If it doesn't work, I will just hope for Jetpack (or Genericons) to add the Flipboard and Bloglovin icons to the social widget sometime soon!

Thanks very much once again.

Kind regards

**Pull request merged**
