### PR TITLE
Simple Payments Block: Add tests

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request:

* Adds block parsing and unit tests to the simple payments block

#### Jetpack product discussion
p1HpG7-b3G-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Running the unit tests:

cd projects/plugins/jetpack && yarn fixtures:test extensions/blocks/simple-payments/test/

We should also ensure that the block works as expected in the editor and frontend  on a site.

### CODE REVIEW

**Review by stacimc — DISMISSED** [review]
I think this looks good! Tests pass locally and manually testing the block tests well; the only console warnings I see are related to the ToolbarItems and present on master.

The only thing I could think to add if you think it would be useful would be checking for the attributes (title/price/etc) rendering in the un-selected component.

**Comment by anomiex** [comment]
Needs a master merge, a changelogger change file (run `composer install` and `vendor/bin/changelogger add` from `projects/plugins/jetpack`), and an update to `tools/eslint-excludelist.json`.

**Comment by glendaviesnz** [comment]
> The only thing I could think to add if you think it would be useful would be checking for the attributes (title/price/etc) rendering in the un-selected component.

Good idea, have added a test for this.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by glendaviesnz** [comment]
diff deployed rWP222593

**Pull request merged**
