### PR TITLE
Jetpack Recommendations: Show Recommendations tab for all users

### PR DESCRIPTION
**Pull request by robertf4**
#### Changes proposed in this Pull Request:

This updates the behavior for deciding whether the Recommendations show based on a conversation with @jessefriedman about the banner not being in this release.

Now:
1. The recommendations tab will show to all users. This was done because the tab alone is not intrusive.
2. The previous logic to hide the recommendations has been left so that it can be used to hide the recommendations banner in the future. This is because the banner is intrusive.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. On a new site, verify that the Recommendations tab shows on the dashboard.
2. On a site that had a completed setup wizard and upgraded, verify that the Recommendations tab shows on the dashboard.

#### Proposed changelog entry for your changes:

N/A

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
While the tab is displayed after completing the setup wizard, you can't access it anymore:

```
Unknown step setup_wizard_completed in RecommendationsComponent
Me @ react-dom.min.js:125
Ih.c.callback @ react-dom.min.js:138
Wg @ react-dom.min.js:67
oj @ react-dom.min.js:127
Aj @ react-dom.min.js:160
unstable_runWithPriority @ react.min.js:25
Da @ react-dom.min.js:60
ab @ react-dom.min.js:154
Te @ react-dom.min.js:146
Ja @ react-dom.min.js:224
md @ react-dom.min.js:173
(anonymous) @ react-dom.min.js:175
Rh @ react-dom.min.js:147
nd @ react-dom.min.js:175
I.render @ react-dom.min.js:238
(anonymous) @ admin.js?ver=9.4-alpha:80
(anonymous) @ admin.js?ver=9.4-alpha:80
n @ admin.js?ver=9.4-alpha:1
(anonymous) @ admin.js?ver=9.4-alpha:1
(anonymous) @ admin.js?ver=9.4-alpha:1
react-dom.min.js:161 Uncaught Unknown step setup_wizard_completed in RecommendationsComponent
Aj @ react-dom.min.js:161
unstable_runWithPriority @ react.min.js:25
Da @ react-dom.min.js:60
ab @ react-dom.min.js:154
Te @ react-dom.min.js:146
Ja @ react-dom.min.js:224
md @ react-dom.min.js:173
(anonymous) @ react-dom.min.js:175
Rh @ react-dom.min.js:147
nd @ react-dom.min.js:175
I.render @ react-dom.min.js:238
(anonymous) @ admin.js?ver=9.4-alpha:80
(anonymous) @ admin.js?ver=9.4-alpha:80
n @ admin.js?ver=9.4-alpha:1
(anonymous) @ admin.js?ver=9.4-alpha:1
(anonymous) @ admin.js?ver=9.4-alpha:1
```

image

**Comment by robertf4** [comment]
> While the tab is displayed after completing the setup wizard, you can't access it anymore:

@jeherve can you reset the site options and try that again? `setup_wizard_completed` was the old name of an option that I have renamed to `setup-wizard-completed`, but if that option was cached you will see that error.

**Review by jeherve — APPROVED** [review]
Cool, this tests well for me with a new site that wasn't running `master` before.

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in d7da834576329db8c655c26de826f9ad4403cd52

**Comment by jeherve** [comment]
I updated our packages to include the changes in a1a0dbfb473eb5cc1c6101df11d5f75e71ed7369

**Pull request merged**
