### PR TITLE
Plans: update links on single products

### LINKED ISSUE #15183: Single Products: needs better/consistent copy and design work
Problems both in Calypso now that there is more than one plan:

Screen Shot 2020-03-29 at 12 36 11 PM

and in wp-admin:

Screen Shot 2020-03-29 at 12 40 26 PM

Note that you can't purchase a monthly backups plan from the UI.

@robertbpugh I think we need new and consistent copy for the various products

### LINKED ISSUE #15244: Search: Track "Learn More" clicks in wp-admin Plans page
Ensure that the "Learn More" link in the Search card for the wp-admin Plans page is being tracked properly with analytics.

(This is already being done within the Backups card.)

Screen Shot 2020-04-01 at 3 01 35 PM

### PR DESCRIPTION
**Pull request by keoshi**
Fixes https://github.com/Automattic/jetpack/issues/15183
Fixes #15244

#### Changes proposed in this Pull Request:

* Moves “Which backup option is best for me?” link to the Backup card.
* Replaces regular link in Search for External Link component.
* Adds click tracking to the latter.

#### Before

image

#### After

Screen Shot 2020-04-02 at 3 07 51 PM

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:

* Fire up this PR.
* Go to `/wp-admin/admin.php?page=jetpack#/plans`
* Ensure:
  * All single product cards look good.
  * Both have links that redirect to their respective LPs.
  * Tracking works.

#### Proposed changelog entry for your changes:

* None.

### CODE REVIEW

**Comment by eeeeevon13** [comment]
@keoshi  the search card confused me a little, isn't there a monthly/yearly toggle up above? so scan has one method of switching monthy/yearly and backups has a different one. I'm worried about that inconsisency

**Comment by keoshi** [comment]
@eeeeevon13 We're waiting on https://github.com/Automattic/jetpack/pull/15193 to introduce a second monthly/yearly toggle at the bottom in the single products section. Then the search card will only show the option and pricing for the selected billing period.

**Review by jsnmoon — DISMISSED** [review]
Neat, works as expected. 

This will expectedly conflict a bit with https://github.com/Automattic/jetpack/pull/15193 since both PRs are making similar changes.

**Review by jeherve — DISMISSED** [review]
This seems to break tracking on the "learn more" links for me. When switching to this branch, I don't think tracking triggered when clicking on the links.

**Comment by jsnmoon** [comment]
✅ Updated from the latest master branch
✅ Fixes Learn More tracking bugs

Tracking can be verified by setting the following in the console:

```js
localStorage.setItem('debug', 'dops:analytics');
```

**Comment by jsnmoon** [comment]
✅ Updated from the latest master branch
✅ Fixes Learn More tracking bugs

Tracking can be verified by setting the following in the console:

```js
localStorage.setItem('debug', 'dops:analytics');
```

**Comment by jsnmoon** [comment]
✅ Updated from the latest master branch
✅ Fixes Learn More tracking bugs

Tracking can be verified by setting the following in the console:

```js
localStorage.setItem('debug', 'dops:analytics');
```

**Comment by jsnmoon** [comment]
✅ Updated from the latest master branch
✅ Fixes Learn More tracking bugs

Tracking can be verified by setting the following in the console:

```js
localStorage.setItem('debug', 'dops:analytics');
```

**Comment by keoshi** [comment]
Thanks for fixing @jsnmoon !

**Review by jeherve — COMMENTED** [review]
This tests well for me, but Travis wasn't triggered after the last rebase for some reason. Could you rebase one last time so we can merge?

Thank you!

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.4` in 1d9e8d7312a29766d622d10555f3cafae42b9f6f

**Pull request merged**
