### PR TITLE
Scan Package: Fix Build

### PR DESCRIPTION
**Pull request by nateweller**
Following up on https://github.com/Automattic/jetpack/pull/40262, this PR ensures the `js-packages/scan` project actually builds the `build` folder using `tsc`.

## Proposed changes:

* Restore the changes to `tsconfig.json` made in https://github.com/Automattic/jetpack/pull/39754/files#diff-1a0db43237e720fa764bf7d3052b6c672d5c26f7c7479154dca7c215f16270fa
* Remove babel deps and references since we are only using `tsc`.
* Adds `ts-jest-resolver` to `tools/js-tests`, to enable compatibility with the scan package's ".js" imports but ".ts" jetpack source.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/pull/40262

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Run `jetpack build js-packages/scan` and validate the `build` directory is generated.

### CODE REVIEW

**Comment by nateweller** [comment]
@anomiex What do you think about this alternate to https://github.com/Automattic/jetpack/pull/40262?

I had to extend `tsconfig.base.json` instead of `tsconfig.tsc.json` to get tests passing. Is that change appropriate for the use case of this package?

My ultimate hope and dream for the scan package is to have a reusable TS lib that exports types, functions, and translatable strings related to Jetpack Scan features. Initially for use across Jetpack and Jetpack Protect plugins, and then potentially sharing code with Calypso if/as possible and useful.

I know the inclusion of `@wordpress/i18n` complicates things. I appreciate any notes! Thanks 😄 

Edit: Could we use the declaration-only base to export types, and then have consumers (Jetpack, Jetpack Protect) be responsible for compiling the TS?

**Comment by anomiex** [comment]
> I had to extend `tsconfig.base.json` instead of `tsconfig.tsc.json` to get tests passing. Is that change appropriate for the use case of this package?

No, if you're using tsc to build then you should be using `tsconfig.tsc.json`. The tests will have to be fixed to work with that.

The reason for that is that `tsconfig.base.json` uses `"moduleResolution": "bundler"`, which is infectious: if a library package uses that, then anything using the library also needs to use that or else tsc blows up. `tsconfig.tsc.json` uses `"moduleResolution": "nodenext"`, which is what https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries recommends for interoperability.

If you can't figure the tests out on your own, feel free to push what you have and ask for help. 🙂

> Edit: Could we use the declaration-only base to export types, and then have consumers (Jetpack, Jetpack Protect) be responsible for compiling the TS?

You could, but there's not much point IMO. The intent of the declaration-only base is for when you want to use webpack instead of tsc to compile the TS to JS but also want to produce `.d.ts` files (using tsc or [fork-ts-checker-webpack-plugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin)). If the consumers have to compile the TS themselves, they don't need exported types because they get the types directly from the TS sources.

The consumers having to compile the TS themselves is effectively the case now, and if it's the way you want to go with this package then #40262 should be done to clean up. The down side is that it'll be harder to use in external consumers such as Calypso, because they would also have to be configured to compile the TS from this package themselves.

**Comment by nateweller** [comment]
Thanks again @anomiex, your expertise here is super valuable. I would vote we continue not shipping JS, and have re-opened a PR for that here: https://github.com/Automattic/jetpack/pull/40318

My thought is, we need the consumers/plugins to compile the translations. Otherwise, we could just build and ship JS right from the plugin if it was just types and utils.

P2'd this as well: peb6dq-3as-p2

**Comment by anomiex** [comment]
Translations are a whole other issue! 😀

For modern-ish plugins on dotorg, translation generally happens via translate.wordpress.org based on what JS is in the actual bundles. Whether that was compiled directly from TS into the bundle or was compiled to JS and then the JS was bundled doesn't make a difference.

For other stuff it all depends on their toolchain for doing translations. Which as far as I know there isn't much of a standard around, but I'd be surprised if compiling directly from a TS-package versus using already-compiled JS from a JS-package made much difference.

**Comment by nateweller** [comment]
@anomiex Thanks again for the guidance! I've updated this PR. Here's the outline:
- Use `tsc` to build the `scan` package, extending `jetpack-js-tools/tsconfig.tsc.json`.
- Add `ts-jest-resolver` to enable the JS Tests checks to follow the `.js` imports inside the scan package's `.ts` files.
- Remove babel deps.

This will allow us to write TS, export JS, and maintain compatibility with monorepo tooling. I've been using the `ai-client` package as a reference, aside from the related updated to the JS Tests/Jest resolver. I've tested stacking [this PR](https://github.com/Automattic/jetpack/pull/40076) on top of this setup, and the package integrates smoothly with the Jetpack Protect plugin 👍

**Review by anomiex — APPROVED** [review]
Looks reasonable to me, and I see CI is happy.

**Pull request merged**
