### PR TITLE
Search: fix translations for the new search customizer and lazy loaded payload

### LINKED ISSUE #20520: Jetpack Search: some interface strings are not being localized
#### Steps to reproduce the issue

1. On your test site with Instant Search enabled, set the site language to 'Français'.
2. Return to the front end of your site and perform a search.

#### What I expected
If the site language is French, all of the interface language in the Instant Search modal should also be in French.

#### What happened instead
The modal shows English strings for "Showing popular results", "Sort" and "clear". Interestingly the sort options themselves are correctly translated (e.g. "Pertinence") so some translations are working as expected.

For example: https://lapidoule.com/?s=bebe

Discovered via 4190269-zen.

**Screenshots**

Screen Shot 2021-08-02 at 15 03 22

### LINKED ISSUE #21349: Jetpack Search: Does not work when the site language is Arabic
### Quick summary

Jetpack search does not work when the site language is set to Arabic. 

### Steps to reproduce

1. Make sure JP search is eanbled from JP settings -> Performance -> Search
2. Change site language to Arabic (no need to change it for the user interface) from site settings -> general.
3. Add JP search widget in the sidebar and try to search.

### What you expected to happen

It should display results in popup

### What actually happened

Does nothing.

### Context

_No response_

### Operating System

_No response_

### Browser

_No response_

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

Ticket: 4357314-zd-woothemes

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #21349 and #20520

##### Background

> Trying it locally, I see this in my browser console:
> Uncaught (in promise) Error: Loading CSS chunk main-payload failed.
(https://REDACTED/wp-content/plugins/jetpack/_inc/build/instant-search/jp-search.chunk-main-payload.min.rtl.css?ver=f33ebf8feb95ae7fc64a)
> [...] @automattic/webpack-rtl-plugin expects the CSS asset's name to end in .css, while since #20926 it's ending in something like .css?ver=f33ebf8feb95ae7fc64a. So it never produces the .rtl.css file, which makes Instant Search fail to load for RTL languages. (@anomiex)

In #20926, we moved the `contentHash` from file name to [a GET parameter](https://github.com/Automattic/jetpack/pull/20926/files#diff-334181bb7a4c7626231d3a9e6d5aaa8d3a771d116848e2c26b1c9b596513e3d4R30) which breaks `rtl` languages like Arabic (#21349).

>At least wp i18n make-pot skips .min.js files by default, which we have to use to work around wpcom's broken minifier. [...] I don't know whether the official translation mechanism does the same. (@anomiex)

And also, when extracting string for translation, asset names ending with `.min.js` are all ignored (p1632856853438200-slack-jetpack-crew). Customburg (the search customizer) and lazy-loaded assets are all with `.min.js`, so strings in them are not translated at all.

##### Changes

The PR is basically a follow-up for #20926, which only proposed a solution to load translations but didn't make sure the translations would be generated. The PR proposes a Webpack plugin, which emits readable JS assets along with minimized assets. The plugin also removes the hash in the un-minimized asset filename, the reasons being that Jetpack the plugin could enqueue translations for a fixed filename rather than one changing all the time, which is essential for WPCOM as we deploy frequently with the hash changing all the time. The downside of doing this is Jetpack release will become about 800KB larger. The original plugin could be found [here](https://www.npmjs.com/package/@wordpress/readable-js-assets-webpack-plugin). Thanks for pointing the way @anomiex. 

Also, this PR reverted the change of moving the `contentHash` from file name to a GET parameter.

In the future, we could possibly automate the process by generating a list of assets for the PHP to automatically inline translations. Another item to investigate: if the RTL CSS build failed, why were no errors thrown?

#### Jetpack product discussion
pcNPJE-gU-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Run `pnpm build-production-search` 
- Check files in `_inc/build/instant-search`
- Ensure for `.min.js` files, there are un-minimized files for each minimized file.
- Ensure for `jp-search.chunk-main-payload.[hash].min.js`, the un-minimized version is `jp-search.chunk-main-payload.js`
- Ensure Search and Customburg work fine

- Run `cd path/to/jetpack/the/plugin && wp i18n make-pot ./ jetpack.pot`
- Ensure strings from `jp-search.chunk-main-payload.js`, `jp-search-main.bundle.js` and `jp-search-configure-main.js` are correctly extracted. Example:
```
#: _inc/build/instant-search/jp-search-configure-main.js:4542
msgid "Options"
msgstr ""
```
( You might want to [install wp for your mac](https://wpbeaches.com/installing-wordpress-wp-cli-macos/) as the docker instance doesn't have enough memory. )

- Download [the mocked French language file](https://github.com/Automattic/jetpack/files/7262897/jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json.zip)
- Unzip the file to `tools/docker/wordpress/wp-content/languages/plugins` and then switch your WP language to `French`
- Open the search overlay, and ensure you see `In French: Showing popular results` like the screenshot below.

image

### CODE REVIEW

**Review by jsnmoon — DISMISSED** [review]
This works as described and the code makes sense. Thanks for the quick follow-up to #21349!

Left some code quality comments, but this is ready for crew review. 👍

**Comment by jsnmoon** [comment]
> Thanks for sharing this Jason. I didn't write the docker command in there. If you try `jetpack docker wp i18n make-pot ....`, you should be able to see the OOM error. I tried to change the PHP memory limit in the docker instance, but it seems the VM is run out of memory but not due to the memory limit. Didn't try to change the memory for docker instance, so used the local `wp` command instead.

Ah, good point -- I'd forgotten about `jetpack docker wp`. I believe my advice might still be of some use, since my local `make-pot` command threw an OOM error for a mere 132MB memory usage :)

> What the plugin does mainly is not renaming assets, but actually produces readable versions of JS files. Renaming is some side effects, because it couldn't use the original names ( with .min ) I guess. Another thing is that the plugin is forked from Gutenberg, I guess we'd better keep the original names for easier reference.

Oh, shoot! You're right, I didn't realize that it was indeed unminifying the files. Feel free to disregard my comments there; I'll go ahead and mark them as resolved on my end.

**Comment by kangzj** [comment]
> Ah, good point -- I'd forgotten about jetpack docker wp. I believe my advice might still be of some use, since my local make-pot command threw an OOM error for a mere 132MB memory usage :)

It's useful for sure, thanks for sharing 👍

**Review by samiff — APPROVED** [review]
> The downside of doing this is Jetpack release will become about 800KB larger.

Following along with thoughts shared in https://github.com/Automattic/jetpack/issues/21343 I think this is okay until something else is worked out in the future.

This PR tested well for me 👍  Regarding the `cd path/to/jetpack/the/plugin && wp i18n make-pot ./ jetpack.pot` step, I did have to adjust the PHP memory limit in the wordpress container by:

- `jetpack docker sh` to access the wordpress container
- `php --ini` to find the config file, eg `/etc/php/7.4/cli/conf.d/20-jetpack-wordpress.ini`
- Set the `memory_limit` to -1 for testing this.
- If you are using Docker Desktop, there are some additional resource [settings](https://docs.docker.com/desktop/windows/#resources). But it should default to 2GB which should be enough.

The JS strings were being extracted correctly, and I was able to test with the mock file ok:

Markup on 2021-10-15 at 16:54:05

**Comment by kangzj** [comment]
> @kangzj
> Revert "Search: fix translations for the new search customizer and la… 

Please ignore this. Clicked the button by mistake.

Shipped 🚢 r233425-wpcom

**Comment by anomiex** [comment]
I just saw this question:

> Another item to investigate: if the RTL CSS build failed, why were no errors thrown?

That's easy enough to answer: The build didn't actually fail, it never happened in the first place. The plugin that builds the RTL CSS looks for assets named to end in ".css", and the problematic change made them be named to end in ".css?ver=somehash" instead so the plugin didn't see them.

**Pull request merged**
