### PR TITLE
WCAG: Remove title if alt is empty

### PR DESCRIPTION
**Pull request by davetgreen**
See issue #2679

### CODE REVIEW

**Comment by samhotchkiss** [comment]
I'll look deeper this week, but I'm not sure why we're checking if `$item->image_alt` is there to decide whether or not to use `$item->image_title`?

**Comment by samhotchkiss** [comment]
@davetgreen -- I had a discussion with @dereksmart about this.  We're concerned that this could have negative some negative repercussions, especially on SEO.  What about, if BOTH alt and title are empty, we hide it, if there's a title but no alt, set alt = title.

Thoughts?

**Comment by davetgreen** [comment]
@samhotchkiss @dereksmart If the links were to other web pages, I'd share the concerns about possible SEO issues, but as these links are to images I'm not so concerned. 

If users are *that* keen to get the images ranking in the search engines, they should be adding `alt` text to the images.

Personally I think we're better focusing on the accessibility issue, and leave the users to squeeze every last drop of SEO juice out of their image assets.

**Comment by dereksmart** [comment]
@davetgreen How about instead of removing the title in these cases, we add an `alt` tag with the same content as the title?

**Comment by dereksmart** [comment]
replaced by #2873

**Pull request closed without merging**
