### PR TITLE
Added properly translated module names and descriptions.

### PR DESCRIPTION
**Pull request by zinigor**
Previously the endpoint was returning untranslated module names and descriptions.

### CODE REVIEW

**Comment by dereksmart** [comment]
great 1-liner

**Comment by oskosk** [comment]
Works as expected! 🚢

**Comment by zinigor** [comment]
Not a 1-liner anymore, sorry :) Thanks to @eliorivero I have added a similar fix to the single module endpoint.

**Comment by dereksmart** [comment]
:shipit:

**Pull request merged**
