### PR TITLE
Paywall: Update email verification pending copy.

### PR DESCRIPTION
**Pull request by lezama**
## Proposed changes:

Screenshot 2023-09-01 at 17 34 57

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Review by simison — APPROVED** [review]
Tests well, good improvement.


Screenshot 2023-09-04 at 11 14 02
Screenshot 2023-09-04 at 11 14 11


I think we have 3 follow-ups:

- Bug: like button appearing in side paywall box
- Double confirm/thanks if subscribe block is on the page
- Lack of "resend" possibility

Screenshot 2023-09-04 at 11 14 43

**Comment by simison** [comment]
Checked that like&reblog buttons get outputted [here](https://github.com/Automattic/jetpack/blob/520d49466757068d4c414239cbaf5184b8083435/projects/plugins/jetpack/modules/likes.php#L457), and probably interacts with our content filter in unexpected ways, @lezama

**Comment by lezama** [comment]
hmm, I didn't get the like on my test site, will investigate

**Comment by simison** [comment]
You might need to enable likes/sharing module if it's not by default on Jetpack? Or "Jetpack social"

**Pull request merged**
