### PR TITLE
Search: avoid registering the widget when the module is not active

### LINKED ISSUE #21587: Search: Fatal Error when the Search module is inactive
#### Steps to reproduce the issue

1. On a site connected to WordPress.com, where you have a plan but where the Search module is inactive.
2. Go to Jetpack > Settings and enable Extra Sidebar Widgets
3. Go to Appearance > Widgets
4. You'll see this Fatal error:

```
PHP Fatal error:  Uncaught Error: Class 'Jetpack_Search' not found in /wp-content/plugins/jetpack-dev/modules/widgets/search.php:429
Stack trace:
#0 /wp-content/plugins/jetpack-dev/modules/widgets/search.php(302): Jetpack_Search_Widget->widget_instant(Array, Array)
#1 /wp-includes/widgets.php(1224): Jetpack_Search_Widget->widget(Array, Array)
#2 /wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(520): the_widget('Jetpack_Search_...', Array)
#3 /wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(490): WP_REST_Widget_Types_Controller->get_widget_preview('Jetpack_Search_...', Array)
#4 /wp-includes/rest-api/class-wp-rest-server.php(1140): WP_REST_Widget_Types_Controller->encode_form_data(Object(WP_REST_Request))
#5 /wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/widget-t...', Array, NULL)
#6 /wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#7 /wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/wp/v2/widget-t...')
#8 /wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#9 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#10 /wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#11 /wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#12 /wp-includes/class-wp.php(750): WP->parse_request('')
#13 /wp-includes/functions.php(1291): WP->main('')
#14 /wp-blog-header.php(16): wp()
#15 /home/gdjetpacktsting/public_html/sub/index.php(17): require('...')
#16 {main}
  thrown in /wp-content/plugins/jetpack-dev/modules/widgets/search.php on line 429

```

*****************

Reported here: p8oabR-K9-p2#comment-5572

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #21587

#### Changes proposed in this Pull Request:

The `Jetpack_Search` class will not be loaded if the Search module is not active. So let's not register the widget when the feature is not available.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* On a site connected to WordPress.com, where you have a plan but where the Search module is inactive.
* Go to Jetpack > Settings and enable Extra Sidebar Widgets
* Go to Appearance > Widgets
* You should not see any errors.
* Activate the Search feature.
* You should be able to use the Jetpack Search Widget.

### CODE REVIEW

**Comment by kangzj** [comment]
Hi @jeherve Thanks for the PR. The logic look fine - but when I tested on this branch and master, both worked. That is to say, when I disabled search module, on both branch the `Search (Jetpack)` became unavailable. When I looked further, it seemed the file `widgets/search.php` is not loaded when search module is disabled. But I haven't looked why yet. Any idea? Thanks.

**Comment by jeherve** [comment]
> when I disabled search module, on both branches the Search (Jetpack) widget became unavailable.

Hm, that is an odd one. I've only tested this using the test site in p8oabR-K9-p2#comment-5572 so I do not really have more details I'm afraid.

**Comment by samiff** [comment]
I was able to see the fatal Jeremy had mentioned with the search module deactivated:

```
[24-Nov-2021 18:37:59 UTC] PHP Fatal error:  Uncaught Error: Class 'Jetpack_Search' not found in /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/widgets/search.php:428
Stack trace:
#0 /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/widgets/search.php(301): Jetpack_Search_Widget->widget_instant()
#1 /var/www/html/wp-includes/widgets.php(1224): Jetpack_Search_Widget->widget()
#2 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(520): the_widget()
#3 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(490): WP_REST_Widget_Types_Controller->get_widget_preview()
#4 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1140): WP_REST_Widget_Types_Controller->encode_form_data()
#5 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request()
#6 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch()
#7 /var/www/html/wp-includes/rest-api.php(370): WP_REST_Server->serve_request()
#8 /var/www/html/wp-includes/class-wp-hook.php(303): rest_api_loaded()
#9 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#10 /var/www/html/wp-includes/plugin.php(518): WP_Hook->do_action()
#11 /var/www/html/wp-includes/class-wp.php(388): do_action_ref_array()
#12 /var/www/html/wp-includes/class-wp.php(750): WP->parse_request()
#13 /var/www/html/wp-includes/functions.php(1291): WP->main()
#14 /var/www/html/wp-blog-header.php(16): wp()
#15 /var/www/html/index.php(17): require('/var/www/html/w...')
#16 {main}
  thrown in /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/widgets/search.php on line 428
```

With this PR patched, the fatal is fixed.

> When I looked further, it seemed the file widgets/search.php is not loaded when search module is disabled.

If the search module is deactivated, then `jetpack/modules/search.php` (the module index file) won't load which is to be expected. However, with Extra Sidebar Widgets active, then the `jetpack/modules/widgets/search.php` file is being included, which has that `jetpack_search_widget_init()` call outside its main class.

https://github.com/Automattic/jetpack/blob/5e20900acf5cb7b50831158ccbea7d32bfa213aa/projects/plugins/jetpack/modules/widgets.php#L14-L33

I also did a check with all of the modules deactivated, but didn't see any other PHP errors when editing widgets, just some JS notices of block registration failures do to missing modules.

**Review by samiff — APPROVED** [review]

**Comment by samiff** [comment]
r235602-wpcom

**Comment by kangzj** [comment]
@samiff Thanks for looking into this, really appreciate that 👍

**Pull request merged**
