### PR TITLE
Blogging prompts: hide placeholder prompt by default

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request:

Changes the default setting for the showing placeholder prompt when starting a new post to false.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

We've received feedback from multiple places the the placeholder prompt is confusing, so we're turning it off by default while we figure out next steps.

p1670877978371049-slack-C025Q5RK2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Delete the `jetpack_blogging_prompts_enabled` option on your site, if present.
* Enable [experimental blocks](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/README.md#experimental-extensions) on your site.
* Set the home page to show a list of posts.
* You should not see a placeholder prompt by default when starting a new post.
* Go to Settings > Writing and turn on the placeholder prompts.
* Now you should still see a placeholder prompt when starting a new post.

### CODE REVIEW

**Review by roo2 — DISMISSED** [review]
LGTM. I tested that prompt will not be shown unless `jetpack_blogging_prompts_enabled` is enabled or `answer_prompt` url param is passed 👍

**Comment by sdixon194** [comment]
Looks like there's a merge conflict in `projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-options.php ` that we'll want to resolve first.

**Review by jeherve — COMMENTED** [review]
While I assume it's too early to mark those 2 functions as deprecated, maybe we can add a note in the docblock of both functions to quickly explain why it's not being used right now? I worry that things will stay that way and we'll eventually forget why we have those 2 functions here.

**Comment by creativecoder** [comment]
> While I assume it's too early to mark those 2 functions as deprecated, maybe we can add a note in the docblock of both functions to quickly explain why it's not being used right now? I worry that things will stay that way and we'll eventually forget why we have those 2 functions here.

We actually are using both functions separately in wpcom.

**Review by ebinnion — APPROVED** [review]
Code LGTM. Have not functionally tested. Approving based off of @roo2's previous review.

**Review by sdixon194 — APPROVED** [review]
Functionally tested things work for me 👍

**Pull request merged**
