### PR TITLE
One-click site verification and search console integration

### PR DESCRIPTION
**Pull request by gravityrail**
The primary purpose of this change is to simplify site verification by letting the user connect their Google account and automatically set the meta tag value and verify their site with Google in one step. It will also register with Search Console in order to set the `sitemap.xml` address.

This provides a foundation for further improvements, including:

* Automatically registering the site with Search Console
* Track indexing status of new posts
* Access to Speedy Indexing API

#### Changes proposed in this Pull Request:

* Add a button to verify site with Google
* If it's easy, add the site to Search Console at the same time

#### Testing instructions:

**Setup**
* Apply D17515-code
* Point Jetpack to Sandbox
* Set `public-api.wordpress.com` to your sandbox IP

**Testing**
* Go to Jetpack -> Settings -> Traffic
* Click "Verify with Google"
* You will be prompted to authorize the connection in a popup
* The UI should change to tell you that your site was verified (and added to Search Console?)

#### Proposed changelog entry for your changes:

Enable one-click site verification and sitemap.xml registration with Google

### CODE REVIEW

**Review by cbauerman — APPROVED** [review]
These changes look great! Everything works as described 👍

**Comment by jeherve** [comment]
I can't seem to be able to test this. I get the following error when trying to open the popup:

screenshot 2018-09-07 at 10 08 13

The phab diff appears to be properly installed on my sandbox, so I am not sure why this is happening. Any idea about what I should try next?

**Comment by cbauerman** [comment]
@jeherve sorry about that, our testing instructions were missing a keep piece of setup. In addition to D17515 you need to set `public-api.wordpress.com` to your sandbox IP.

**Comment by jeherve** [comment]
Thank you! This worked better.

I'd have a few remarks:
- Should the Google app be "WordPress.com" instead of just "WordPress"?
- Some of the notifications (like "Updating settings") happen through the usual Jetpack admin UI notifications at the top of the page, but the "Verifying" state is only displayed inside the button. I found it a bit confusing to have the status of the connection in 2 places.
- After the "verifying" status appeared in the button it reverted back to "click to verify". When I clicked "click to verify" again, it sticked.
- I got an error in my sandbox during the verification process. It may have been what caused the issue above. I posted the error on the Phab diff.
- When I refresh the page, "click to verify" appears again, just like if I had not verified anything yet.

Other than that, it worked quite nicely!

**Comment by cbauerman** [comment]
The Sandbox Error & the "Click to Verify" on refresh are fixed: both were typos/ missing args in D17515. The same fix may have also fixed the need to click the verify button twice, I have not been able to reproduce. As far the button text vs notification we will have a chat and see if we can do some work to clean that up. Thanks for the feedback!

**Comment by jeherve** [comment]
One small issue that I found with this is when you remove the site from the Google Search Console after it's been verified and marked as verified in your Jetpack admin settings. Our interface does not get updated to take the changes into account; it keeps telling you that your site is verified, when in fact it is not anymore since you removed the property in your Google Search console.

**Comment by jeherve** [comment]
Thank you, that helped!

I seem to be getting a different error on wpcom now when I try to reverify, but I may just have messed up something with my site at this point:
`Google Site Verification Error: Keyring_Error Object`
```
                                            [body] => {"error":{"errors":[{"domain":"global","reason":"forbidden","message":"You are not an owner of this site."}],"code":403,"message":"You are not an owner of this site."}}
                                            [raw] => HTTP/1.1 403 Forbidden
```

Should I try on brand new site?

**Comment by cbauerman** [comment]
@jeherve actually I would love to know what sites are in your search console. The error was from Google and I was not able to reproduce it, even with using multiple logins to verify.

**Comment by Tug** [comment]
@jeherve @cbauerman That error was fixed yesterday on the server patch as I investigated the issue Jeremy had. We now just make sure to clear the site keyring in that case insead of returning the error.

**Comment by jeherve** [comment]
I still get the error today with the updated version of the wpcom patch.

The property is there in my search console, just not verified:

screenshot 2018-09-12 at 11 23 50

In wp-admin, I only see the "Click to verify" prompt:

screenshot 2018-09-12 at 11 25 19

When clicking it, the button changes into a greyed out "Connect to Google" for a couple of seconds, there I get the 500 error on the `wp-json/jetpack/v4/verify-site/google` call and the "Click to verify" button reappears. The detailed error is the same as I posted yesterday, in the API response or my error logs in my wpcom sandbox:

```
{"code":"keyring-request-error","message":{"headers":[],"body":"{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"forbidden\",\"message\":\"You are not an owner of this site.\"}],\"code\":403,\"message\":\"You are not an owner of this site.\"}}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":"","http_response":{"data":"","headers":"","status":""}},"data":null}
```

**Comment by Tug** [comment]
Sorry to ask, but did you try reloading the page?

**Comment by jeherve** [comment]
Yeah, that does not seem to change anything.

**Comment by Tug** [comment]
After investigating, it seems your site was in a bad state, it seems we're unable to reproduce the error now!

**Review by cbauerman — APPROVED** [review]
Everything is looking good! LGTM 👍

**Pull request merged**
