### PR TITLE
Add/icons for all product cards on dashboard

### PR DESCRIPTION
**Pull request by CodeyGuyDylan**
## Proposed changes:

* Ensure every product card on the Dashboard has an icon when inactive. Currently several are missing

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

P2: pbNhbs-bHl-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

1. Checkout this branch via the Jetpack Beta plugin or your local dev environment
2. With a site connection but no user connection, go to `/wp-admin/admin.php?page=jetpack#/dashboard` and ensure that all cards relating to products have an icon
image
image
3. Connect your user account
4. Go back to `/wp-admin/admin.php?page=jetpack#/dashboard` and ensure all products that need a plan or a standalone plugin installed still have an icon
image
5. Try purchasing a few plans or installing a few plugins to activate products and make sure the cards look good still. Rule of thumb I used is if there is a CTA, we still show the icon
image
image

### CODE REVIEW

**Review by grzegorz-cp — APPROVED** [review]
👍

**Comment by CodeyGuyDylan** [comment]
@Automattic/jetpack-design might be interested in this 😄

**Review by keoshi — COMMENTED** [review]
Hey @CodeyGuyDylan — this looks great.

I wonder thought if the cards would look more balanced if we moved the icons next to the titles instead. Have you tried that?

That in turn could make the cards unbalanced between them, since some don't have icons: Brute force protection, Downtime monitoring, Image Accelerator, Akismet Anti-spam.

Would you like me to provide the missing icons so we can try this out, or should we keep this simple as is?

**Comment by CodeyGuyDylan** [comment]
> Hey @CodeyGuyDylan — this looks great.
> 
> I wonder thought if the cards would look more balanced if we moved the icons next to the titles instead. Have you tried that?
> 
> That in turn could make the cards unbalanced between them, since some don't have icons: Brute force protection, Downtime monitoring, Image Accelerator, Akismet Anti-spam.
> 
> Would you like me to provide the missing icons so we can try this out, or should we keep this simple as is?

Hmmmm if you think that would help the design a lot I am open to it. However our goal is to get this project done and into the next Jetpack release, and this was a very minor task in the project. Since we are deprecating the dashboard somewhat soon, do you think it'd be okay to look like this for now? cc: @robertsreberski 

Also I Akismet does have an icon as far as I can tell 🤔 But yes the rest are missing them. If you had icons for those I could add them pretty easy even if we don't do the design change 😄

**Comment by CodeyGuyDylan** [comment]
@keoshi I merged this instead of https://github.com/Automattic/jetpack/pull/39533 on accident 🤦🏻 

It was approved for what it is so I'll leave it be for now. If you'd like me to add the icons to the feature cards I can do that in a separate PR if that sounds good to you?

**Comment by keoshi** [comment]
As discussed on Slack just now, this is a great iterations. Let's go with it for now and reevaluate if needed.

**Comment by robertsreberski** [comment]
I agree we shouldn't spend too much effort on Dashboard now! The change looks like a good iteration.

> As discussed on Slack just now, this is a great iterations

@keoshi what actually was discussed on Slack? 😅

**Comment by keoshi** [comment]
Sorry for the lack of context, @robertsreberski. Dylan and I chatted briefly about spending time on the Dashboard vs spending time on things that actually move the needle. The Dashboard will be deprecated soon (we hope) so it doesn't make sense to invest a lot of time and energy into it at this stage, like you said.

**Comment by robertsreberski** [comment]
Awesome, thanks for the context @keoshi ✌️

**Pull request merged**
