### PR TITLE
Backup: Add next daily backup schedule time

### PR DESCRIPTION
**Pull request by Initsogar**
Resolves https://github.com/Automattic/jetpack-backup-team/issues/701

## Proposed changes:

* Setup react-query, moment and typescript packages on the backup package
* Add `/jetpack/v4/site/backup/schedule` endpoint that will fetch the daily schedule backup time for a site
* Add `useScheduledTimeQuery` hook to fetch schedule time
* Add `useNextBackupSchedule` hook to parse and return the next backup schedule time
* Add `NextScheduledBackup` component to render the next scheduled backup message and render it on Backups main component

https://github.com/user-attachments/assets/38add82e-348a-47ac-94b3-f721fd32c508

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

peaFOp-2Lz-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Spin up a Jurassic Ninja site using this branch: https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=add/jetpack-backup-schedule-time&wp-debug-log&nojetpack
* Navigate to the VaultPress Backup page.
* If you have a successful backup recently, you should see when the next scheduled backup will run under the latest backup section, similar to this:
  CleanShot 2024-10-25 at 22 12 10@2x
* Ensure that clicking on `Modify` record the `jetpack_backup_schedule_modify_click` Tracks event and it opens a new tab navigating to Jetpack Cloud settings page.

### CODE REVIEW

**Comment by mavegaf** [comment]
Run some tests and it works fine 👍

**Comment by Initsogar** [comment]
> Run some tests and it works fine 👍

@mavegaf thanks! I just merged trunk, removed two unnecessarily changelog items and submitted it for review. Made some additional tests and everything seems to be working as expected. Could you take a final look?

**Review by ilonagl — DISMISSED** [review]
It looks great! One suggestion: we can consider whether the word ‘between’ is necessary. Removing it could streamline the layout, bringing the line and modify link onto the same line, but this might not be essential. Just a thought!

**Review by mavegaf — DISMISSED** [review]

**Comment by Initsogar** [comment]
> It looks great! One suggestion: we can consider whether the word ‘between’ is necessary. Removing it could streamline the layout, bringing the line and modify link onto the same line, but this might not be essential. Just a thought!

@ilonagl Great suggestion! I just pushed the changes and looks better now :)

CleanShot 2024-11-11 at 11 51 27@2x

Could I get a final look? This change removed both approvals :D @ilonagl @mavegaf

**Review by ilonagl — APPROVED** [review]
It looks great! Amazing work as always, Rafael!

**Review by mavegaf — APPROVED** [review]

**Pull request merged**
