### PR TITLE
Fix remaining phpcs warnings in most of requirelist

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

The most interesting bit is the switching of abtest to use WorDBless so
it can pick up the WP_Error definition it needs instead of trying to
locally delcare it in its tests which results in a phpcs complaint about
the redefined class.

Also account for two files in the requirelist that had been moved.

Skipped packages/analyzer, there's too much going on there.

#### Jetpack product discussion

None.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Ideally nothing has changed. See if tests are still green.

#### Proposed changelog entry for your changes:

* Developer only, none needed.

### CODE REVIEW

**Comment by anomiex** [comment]
I'm tempted to swtich the requirelist to an "excludelist" so we can more easily exclude things like packages/analyzer and don't have to worry about tracking new files and renames of files that are supposed to be clean, but I'll leave that for a future PR.

**Comment by leogermani** [comment]
It reads well to me, but there are some e2e tests failing. I tried re-running and they failed again. Not sure if it's related to any changes on this PR

**Comment by anomiex** [comment]
I have zero visibility into it. All I know is that it currently fails with

> TimeoutError: waiting for selector "div[data-e2e-product-slug="jetpack_complete"]" failed: timeout 40000ms exceeded

I've seen similar timeout errors in past runs, although I want to say they failed waiting on `#adminmenumain` rather than that so :shrug:.

When I try to follow the instructions in tests/e2e/README.md to run the tests locally (`E2E_DEBUG=true npm run test-e2e tests/e2e/specs/connection.test.js`), it fails to even start with "Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT".

If I replace that path in tests/e2e/jest-puppeteer.config.js with `/usr/bin/chromium` the test runs and passes for me locally. So I have no idea.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r216875-wpcom

**Pull request merged**
