### PR TITLE
Social Previews | Update Twitter preview with multiple view type sections

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Completes 1203820933396971-as-1204281809108915/f and 1203820933396971-as-1204281809108923/f

## Proposed Changes

This PR updates the Twitter preview component to the latest design from Twitter

## Testing instructions:

* Checkout this PR branch
* Checkout https://github.com/Automattic/wp-calypso/pull/75544 in calypso
* In `wp-calypso/packages/social-previews/` directory, run `pnpm link --global` to expose the package to global `node_modules` for `pnpm`
* In `jetpack/projects/js-packages/publicize-components/` directory, run `pnpm link --global @automattic/social-previews`
* In `wp-calypso` root, run `yarn` and then `yarn workspace @automattic/social-previews run build`
* In Jetpack, run `jetpack build plugins/jetpack --no-pnpm-install`
* Start writing a new post with JT site via Jetpack
* Click Jetpack icon on the top of the sidebar
* Under "Social Previews", click on "Preview"
* Confirm that the preview of Twitter is as per the design
* Once you are done, run `pnpm unlink` in Jetpack

Single Tweet
Screenshot 2023-04-11 at 3 55 06 PM
Screenshot 2023-04-11 at 3 55 40 PM

Twitter Thread
Screenshot 2023-04-11 at 3 56 57 PM
Screenshot 2023-04-11 at 3 57 22 PM
Screenshot 2023-04-11 at 3 57 42 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1204281809108923

### CODE REVIEW

**Comment by gmjuhasz** [comment]
Hi @manzoorwanijk,

Thanks for working on this! I followed the testing description, I have some problems on my end:
- The preview panel looks weird for me, am I missing something here?
- Hashtags only convert to links for me if they are at the start of a message 

CleanShot 2023-04-14 at 10 42 49 png

EDIT: If I put a link in the middle it works for some reason:

CleanShot 2023-04-14 at 10 42 26 png

I'll take a look at the code now, just tested it first

**Comment by manzoorwanijk** [comment]
> * The preview panel looks weird for me, am I missing something here?

It looks like some build issue. Did you follow the steps in the correct sequence?

**Comment by gmjuhasz** [comment]
> It looks like some build issue. Did you follow the steps in the correct sequence?

Yeah it sure looks like it. 
I think I did, I also tried redoing it, but it ended up the same. 🤔 If it's a build issue it's weird that only that part is messed up, the preview itself looks fine

**Comment by manzoorwanijk** [comment]
> * Hashtags only convert to links for me if they are at the start of a message

Thank you for catching that. I have pushed a fix to the calypso PR.

**Review by gmjuhasz — APPROVED** [review]
As the other issue is on my end (p1681467716261349/1681456366.815559-slack-C04UC7YGPNY) , this LGTM!

**Pull request merged**
