### PR TITLE
Boost: Add premium upgrade flow

### PR DESCRIPTION
**Pull request by eAdnan007**
Fixes 44-gh-Automattic/boost-shield-api

Requires patch: D78422-code

#### Changes proposed in this Pull Request:
- [x] Clicking upgrade cta will take the user to the benefits page.
- [x] User can click "Upgrade Jetpack Boost" to go to wp.com checkout page and purchase the plan.
- [x] After plan is purchased, the user will reach the post-purchase landing page.
- [x] Enable and request cloud-css on purchase success.
- [x] Detect if the plugin is upgraded and show cloud CSS or critical CSS based on that.

#### Jetpack product discussion
pc9hqz-iD-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Apply D78422-code on your sandbox
* Load the boost settings page and follow the upgrade flow
* After the purchase is done, you should be able to see that Automatic critical CSS replaced the local critical CSS module

### CODE REVIEW

**Review by karthikax — COMMENTED** [review]
Amazing work. The flow is working end-to-end.

I am not sure if something is broken from my end. But after the successful purchase, the Cloud CSS module didn't get enabled by default. I have tested this twice and the module was in disabled state. Did not notice any error in the console. Could you confirm if this is working for you?

**Review by karthikax — DISMISSED** [review]
🎉

**Comment by eAdnan007** [comment]
r243680-wpcom

**Review by thingalon — APPROVED** [review]
Pretty excited about this!

**Pull request merged**
