### PR TITLE
[RNMobile] Remove mobile link from Account Connection card

### PR DESCRIPTION
**Pull request by SiobhyB**
As part of updates related to the Jetpack app's branding, we've decided to remove the mobile link from the Account Connection card found via _Jetpack_ → _Dashboard_. 

#### Changes proposed in this Pull Request:

* The `MobileMagicLink` component has been removed from the Account Connection card. 
* The code that was only used by [the `MobileMagicLink` component](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/_inc/client/components/mobile-magic-link) has also been deleted following [the discussion here](https://github.com/Automattic/jetpack/pull/26311#pullrequestreview-1117418936). The component was originally introduced in https://github.com/Automattic/jetpack/pull/12561 and that PR can be referred to to confirm the correct code has been deleted.
* The removal of the now unused code includes a changes to `js-packages/api`, which means that `api/package.json` had to be bumped from version `0.13.11` to `0.14`. This also included changes to various dependencies, as shown in https://github.com/Automattic/jetpack/pull/26311/commits/2375e4c2a7203f8938159b27ffd6ec2a0d4144dc.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pcdRpT-F0-p2

#### Does this pull request change what data or activity we track or use?

We'll no longer be tracking clicks on the mobile login link, as the `MobileMagicLink` component is no longer in use anywhere. 

#### Testing instructions:

* Navigate to _Jetpack_ → _Dashboard_ and verify that the link is no longer displayed in the Account Connection card.

| Before  | After |
| ------------- | ------------- |
|  |  |

### CODE REVIEW

**Review by dcalhoun — DISMISSED** [review]
🚀 LGTM. I verified the testing instructions passed locally. 

> * The code for the [actual `MobileMagicLink` component](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/_inc/client/components/mobile-magic-link) hasn't been deleted in case it's needed for future use, but I'm open to discussions around that decision.

This is always a judgement call. I understand both approaches. However, my opinion is that the code should be removed: 

* It should be easy to retrieve the deleted code via VCS, if needed. 
* If retained, the code would include WordPress app copy and install links. 
* If retained, the presence of the unused code may cause confusion for developers.

**Comment by SiobhyB** [comment]
> I understand both approaches. However, my opinion is that the code should be removed...

Thanks for sharing this perspective @dcalhoun. Thinking on this further with your points in mind, I can see how keeping unused code could contribute to a confusing, out-of-control codebase. I've gone ahead to remove the redundant code in https://github.com/Automattic/jetpack/pull/26311/commits/d7138e27d77081b15326e4eab6296f4c1748289c.

**Comment by SiobhyB** [comment]
Adding the `Needs Review` label for review from the Jetpack crew. For the crew: I don't have access to deploy to WordPress.com, so would be grateful if any reviewer could help with that too 🙇‍♀️

**Comment by kraftbj** [comment]
Refreshed the branch with `trunk` and will check it out here in a few. I'll take care of merging and deploying to WP.com too.

**Review by kraftbj — APPROVED** [review]
Tests fine. The Search e2e test appears to be an issue connecting the test site, not an issue in the actual PR.

**Comment by kraftbj** [comment]
r253208-wpcom

**Pull request merged**
