### PR TITLE
Subscribe: Transparent button border fix

### LINKED ISSUE #36244: Subscribe Block: Transparent border issue
The Subscribe button has a transparent border which looks bad on some themes.

Let's investigate why the transparent border is there and apply the fix if possible.

#### Pixl theme on hover

Image

vs

Image

#### Hello Elementor theme

Image

vs

Image

### PR DESCRIPTION
**Pull request by pkuliga**
Fixes https://github.com/Automattic/jetpack/issues/36244

## Proposed changes:

It fixes the issue with missing Subscribe button border by removing the `border-color: transparent;` style.

Didn't notice any regression after removing it. It was added here: https://github.com/Automattic/jetpack/pull/15107

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* activate Hello Elementor theme
* insert Subscribe block into the post
* open the post and make sure the button has a border visible

### CODE REVIEW

**Comment by simison** [comment]
Something is still off. Testing with TwentyTwenty Three theme, buttons now get border, although buttons block and forms block doesn't have border:

With PR, note border:

Screenshot 2024-03-15 at 15 21 29

Without PR, no border:

Screenshot 2024-03-15 at 15 19 41

Other blocks:

Screenshot 2024-03-15 at 15 21 26

In the block editor it looks worse with the PR (Without PR, no black border):

image

With many other themes look good, though.

**Comment by simison** [comment]
The fix does indeed help with Hello Elementor. With older version of the theme there was no issue, but I didn't grab a screenshot before updating the theme.

With PR: 
image

Without PR:
image

**Comment by pkuliga** [comment]
Nice catch! It's because we are adding by default `border-width: 1px` to the button for some reason.

Need to investigate it further.

**Comment by simison** [comment]
In the paywall we also do this, which might be both causing, and hiding, issues depending on theme:

```
{"borderRadius":50,"borderColor":"primary", ... }
```

https://github.com/Automattic/jetpack/blob/ac8361ace78dc0a03be09f2d14d5245734fd83ec/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L1151

E.g. Elementor:

image

**Pull request closed without merging**
