### PR TITLE
Connection: add new method to fetch a connected site's blog ID.

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This should avoid duplication of code in different parts of our codebase.

> **Note**
> I wasn't 100% sure where to place that new method in the Connection package. Let me know if you think it should be in another class.
>
> I also haven't added any test for that new method. I wasn't really sure what to test for. Let me know what you think.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Test the few blocks that rely on those endpoints (Instagram, Tweetstorm), and see that they still work.

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @jeherve, thanks for working on it, the code look a lot cleaner!

`Utils` class looks like a spillover of `Manager`, which is quite a bit bloated. However, `Manager` might be a more logical choice here, as site ID is an important piece of connection. Besides that, `Utils` looks like it's on its way to being deprecated. I'd leave it alone until we decide what to do with it.

**Comment by darssen** [comment]
Thanks @jeherve for working on this and @sergeymitr for jumping on it.

I did test the functionality in JN and simple site and the new function in connection package was being executed and things were working fine 

I will test once more when the suggested changes are done :)

**Comment by jeherve** [comment]
Thank you both! I just pushed e4ebed059fe00503c83144f8d60d78ad3bb28ee8 to move the method to the `Manager` class.

**Review by darssen — APPROVED** [review]
Tested the changes in JN and simple site for Instagram and Twitter blocks and the `get_site_id()` function in Manager was being used as expected.
LGTM!

**Pull request merged**
