### PR TITLE
Connection: Update ConnectionErrorNotice React component to use message property

### PR DESCRIPTION
**Pull request by chrisbliss18**
#### Changes proposed in this Pull Request:
Update the `ConnectionErrorNotice` React component to support and require a message property. The logic to generate the message is removed from the component and moved to the places where the component is utilized. This is part of a bigger project (1202697549597858-as) to provide consistent failed connection error reporting and an interface to reconnect (1202697549597858-as-1202697549597864). 

The changes will affect the following:
* Connection

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
* p9dueE-5w8-p2

#### Does this pull request change what data or activity we track or use?
* No

#### Testing instructions:
* Modify `projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx` to have the below changes:
```
diff --git a/projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx b/projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
index 6864b0d54d..a08566223a 100644
--- a/projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
+++ b/projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx
@@ -9,6 +9,7 @@ import {
 import { Notice } from '@wordpress/components';
 import { __ } from '@wordpress/i18n';
 import { Icon, warning, info } from '@wordpress/icons';
+import { ConnectionErrorNotice, useConnection } from '@automattic/jetpack-connection';
 import React, { useEffect } from 'react';
 import useAnalytics from '../../hooks/use-analytics';
 import useConnectionWatcher from '../../hooks/use-connection-watcher';
@@ -52,6 +53,10 @@ export default function MyJetpackScreen() {
                recordEvent( 'jetpack_myjetpack_page_view' );
        }, [ recordEvent ] );
 
+       const { connectionErrors } = useConnection( {} );
+       const connectionErrorList = Object.values( connectionErrors ).shift();
+       const connectionErrorMessage = connectionErrorList && connectionErrorList.length && connectionErrorList[ 0 ].error_message;
+
        // No render when site is not connected.
        const { isSiteConnected } = useMyJetpackConnection();
 
@@ -73,6 +78,11 @@ export default function MyJetpackScreen() {
                                                        { __( 'Manage your Jetpack products', 'jetpack-my-jetpack' ) }
                                                </Text>
                                        </Col>
+                                       { Boolean( connectionErrorMessage ) && (
+                                               <Col>
+                                                       <ConnectionErrorNotice message={ connectionErrorMessage } />
+                                               </Col>
+                                       ) }
                                        { message && (
                                                <Col>
                                                        <GlobalNotice message={ message } options={ options } clean={ clean } />
```
* Run `jetpack build packages/my-jetpack`.
* Enable the "Jetpack Debug Tools" plugin.
* Go to Jetpack Debug > Jetpack Debug.
* Enable "Broken token Utilities" and click "Save".
* Go to Jetpack Debug > Connection Errors
* Under "Create fake errors", select "With the blog token", select "Verified", and click the "Create error" button.
* Go to Jetpack > My Jetpack.
* You should see an error message as shown in the below screenshot:
jetpack-connection-error-example

### CODE REVIEW

**Comment by kraftbj** [comment]
@chrisbliss18 -- Can you resolve the conflict in the index.jsx file. For the rest, I'd suggest using `trunk`'s version of the lock and all of the json, then run `tools/fixup-project-versions.sh` and `pnpm install` to see if there's any changes needed there.

**Comment by chrisbliss18** [comment]
@kraftbj I merged the latest trunk, fixed the version issues, run `pnpm`, and pushed the updates.

> Can you resolve the conflict in the index.jsx file.

If you are referring to the `my-jetpack-screen/index.jsx` file changes in the testing instructions, I found that there was a JS error if no error needs to be displayed. I've updated the testing instructions example code to fix this issue.

If you are referring to `my-jetpack-screen/index.jsx` file, I'm not sure which conflict you are referring to.

Edit: As soon as I posted this, it's out of sync with trunk again. I'll start over with the trunk sync.

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by oskosk** [comment]
r253122-wpcom

**Pull request merged**
