### PR TITLE
Recommendations: do not show for Atomic sites.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

Atomic sites already get onboarded in Calypso.

#### Jetpack product discussion

* p8oabR-BT-p2#comment-4955

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:
* On an Atomic site, visit Jetpack > Dashboard
* You should not see the Recommendations tab.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Review by robertf4 — APPROVED** [review]
Looks good to me and tests well. 🚢

**Comment by sdixon194** [comment]
Also tests well for me 👍

**Review by sdixon194 — APPROVED** [review]

**Review by sergeymitr — APPROVED** [review]
Works well 🚢

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in cb51e78e51857eb7e8bf08e22d63b49f5923057e

**Pull request merged**
