### PR TITLE
Plugin visibility fix for taxonomy conditions

### LINKED ISSUE #2170: Widget Visibility for Custom Post Type for Pages and Custom Taxonomies Concurrently
A user got in touch wanting to add specific widget visibility rules. She wants it to follow both (a) a specific custom post type for pages and (b) two custom taxonomies. When all three rules are enabled, the widget only shows on the custom post type pages, not on the custom taxonomies.

Steps to Reproduce:
1. Enable a theme with custom post type/add a custom post type
2. Create a custom taxonomy or 2 for good measure.
3. Add a widget.
4. Create widget visibility rules for custom post type + taxonomy 1 + taxonomy 2

Expected result: The widget will appear only on the custom post type pages and custom taxonomies
Actual: The widget only appears on the custom post type pages, unless the above code is added

She was able to create a workaround by adding the following condition to modules/widget-visibility/widget-conditions.php in function filter_widget, line 492:

```
else if ( is_tax($rule['minor']) )
$condition_result = true;
```

(potentially similar issue: https://github.com/Automattic/jetpack/issues/1627)

### LINKED ISSUE #3020: Widget Visibility for "All taxonomy pages" and "All [custom tax] pages" not working
The widget visibility option for taxonomies is not working in two cases:
1. The  "Taxonomy" => "All taxonomy pages" entry.
2. The "Taxonomy" => "All [custom tax] pages" entry in custom taxonomies

Conditions for specific taxonomy terms work ok though.

Related to #2170.

### PR DESCRIPTION
**Pull request by anmar**
Fixes #3020 and maybe #2170

### CODE REVIEW

**Comment by dereksmart** [comment]
This doesn't seem to be working for me.  With this patch applied I'm not seeing my widget on any custom taxonomy.  Testing with jetpack-portfolio

**Comment by dereksmart** [comment]
punting until we can take a closer look

**Comment by eliorivero** [comment]
@dereksmart this is working fine for me testing it with `jetpack-portfolio-type` taxonomy. Tested visibility with all taxonomies, all taxonomy terms for a given taxonomy, and single taxonomy term.

**Comment by jeherve** [comment]
See #3210 for another pass at this.

**Comment by zinigor** [comment]
Thank you for the PR @anmar , but we will go with another one (#3288) that has the same changes plus some additional ones.

**Pull request closed without merging**
