### PR TITLE
Instant Search: remove date from search results

### PR DESCRIPTION
**Pull request by keoshi**
Fixes https://github.com/Automattic/jetpack/issues/14609

#### Changes proposed in this Pull Request:

* Remove date from minimal search results.

#### Before:

image

#### After:

image

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
1. Follow [these setup instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) to set up Jetpack Instant Search on your site.
2. Search your site to trigger the Jetpack Search overlay.
3. Ensure that the date is no longer displayed on search results.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by folletto** [comment]
I agree in concept... but for a proper review, can you include before-after screenshots, ideally of the full page?

**Comment by keoshi** [comment]
Updated above @folletto !

**Comment by folletto** [comment]
I don't have enough data to say how useful the date is, but definitely looks easier to scan without. 👍

**Comment by keoshi** [comment]
@folletto Thanks! The reasoning behind this is two-fold:

1. It takes valuable space, especially on mobile. We discussed having a different format for integrating the date on the same line as the content: `4 April, 2019 — Here's where the content comes in (...)` but we also think that:
2. The date might actually hurt the perception of how accurate our search results are. Jetpack Search is excellent, so the most relevant post might be 5 years old. If that's the most relevant post, it should come first and seeing the date (2015) might actually communicate that the algorithm isn't that good because people tend to prefer the newest results possible.

**Review by gibrown — APPROVED** [review]
WFM and LGTM. So much more space

**Pull request merged**
