### PR TITLE
Fix Paywall block unregister logic

### PR DESCRIPTION
**Pull request by fluiddot**
Fixes https://github.com/Automattic/jetpack/pull/33941/files#r1403640052.

## Proposed changes:

* Get block's name from `metadata` when invoking `unregisterBlockType`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

### Web version
* Create a page.
* Observe in the console that no errors are logged and no exceptions are encountered.
* **[UPDATE]** Observe that the Paywall block is not available (i.e. the block can't be added to the page).

### App version
* Open the app.
* Create a page.
* Observe that no exceptions/crashes are encountered.
* **[UPDATE]** Observe that the Paywall block is not available (i.e. the block can't be added to the page).

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
I was able to test this feature branch successfully on both web and mobile, and did not note any exceptions or console errors. 🚀

**Comment by fluiddot** [comment]
While testing the fix in the web version, I also noticed that before these changes, the Paywall block was available in Pages. As per this logic, this is unexpected as the Paywall block should be automatically unregistered. This fix will address it.

https://github.com/Automattic/jetpack/blob/8df317df876918638a758ed43dab4b8e2ac35b66/projects/plugins/jetpack/extensions/blocks/paywall/editor.js#L19-L22

**Comment by simison** [comment]
Correct, Paywall block should be available only to posts; no pages nor custom post types either. Thanks for catching! cc @lezama

**Comment by lezama** [comment]
Thanks!

**Pull request merged**
