### PR TITLE
Contact Form: refactor form to use forms package

### PR DESCRIPTION
**Pull request by monsieur-z**
## Proposed changes:

As part of the Contact Form module deprecation, this PR refactors the `Grunion_Contact_Form` class to reference the Forms package.

The refactored code uses object composition to call code from the Forms package. The refactored class holds an instance of `Contact_Form` and its methods call the composed object methods. The public properties are made private, and a setter and getter are defined to get and set the properties on the composed object instead. Static methods call their counterpart in `Contact_Form`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Project thread: pf5801-Aj-p2
Issue: https://github.com/Automattic/jetpack/issues/35653

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Let's do some regression testing.

- Spin up a test site with this branch
- Update the file `/projects/plugins/jetpack/modules/contact-form.php` so the condition on line 33 is falsy (or comment the block). This ensures we're loading the Contact Form module.
- Create a new post
- Check you can still add a Contact Form block and that nothing breaks
- Open the preview and verify you can see and use the form

### CODE REVIEW

**Review by chrisbliss18 — COMMENTED** [review]
I'm able to run all the testing instructions successfully until it comes to submitting a filled in contact form. I can successfully add the form and save the post. Loading the post shows the contact form as expected; however, after filling it out and submitting, I get an error page with the message: "There has been a critical error on this website." Looking in the logs, I find the following error:

```
PHP Fatal error:  Uncaught Error: Cannot access private property Grunion_Contact_Form::$last in /usr/local/src/jetpack-monorepo/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:1057
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): Grunion_Contact_Form_Plugin->process_form_submission()
#1 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/html/wp-includes/template-loader.php(13): do_action()
#4 /var/www/html/wp-blog-header.php(19): require_once('...')
#5 /var/www/html/index.php(17): require('...')
#6 {main}
```

Note that I did not change any of the contact form. I added the block and saved the post without making any changes to the form.

**Comment by monsieur-z** [comment]
Thanks @chrisbliss18. It seems that the rebase fixed the issue.

**Review by chrisbliss18 — DISMISSED** [review]
I was able to successfully run the testing steps after the latest change. I was able to submit the form successfully and confirmed that the form responses were saved as expected and had the correct values.

Thanks for the good work on this change. Approved! :)

**Review by chrisbliss18 — APPROVED** [review]
Changes are still good. Testing worked. Approved! :)

**Pull request merged**
