### PR TITLE
Fix/jetpack newsletter settings endpoint

### PR DESCRIPTION
**Pull request by enejb**
This PR fixes the settings endpoint response when the `subscription_options` are sent to the endpoint but they are not modified. 

This PR intends to fix the error that shows up when saving the newesletter settings in calypso. 

## Proposed changes:

* Ignore the saving and the false error when the options that current exists match the options in the table. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
Apply this patch. 
Go to wordpress.com/settings/newsletter/example.com and make a change to any option beside the welcome text box and notice that you don't see the error any more.

### CODE REVIEW

**Comment by kraftbj** [comment]
@simison Could someone on Zap give this a look?

**Comment by pkuliga** [comment]
Hi @enejb, is this ready for review?

Seems related to https://github.com/Automattic/jetpack/pull/37190

Do we need to merge both PRs to fix the issue?

**Comment by enejb** [comment]
@pkuliga I think merging https://github.com/Automattic/wp-calypso/pull/90605 would be enough. 

I do still think this should be merged because it currently doesn't work as expected since and the endpoint returns an error where it should just return success.

**Comment by pkuliga** [comment]
Hi @enejb! I tested saving newsletter settings on Simple, Atomic, and self-hosted (created by https://jurassic.ninja/) sites and couldn't repro this error. Settings were saving as expected.

Not sure what changed since I'm sure a couple of days ago the errors were triggered for me...

I tested against `trunk` and didn't apply any of your fixes...

Could you test it on your end and reply with repro steps so I could test it?

**Comment by enejb** [comment]
I am not able to reproduce the error any more. \o/ 

I do think this PR should be merged mostly so that we keep the consistency with other options where we don't save the setting if it matched the current saved data. This is currently not the case there.

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
