### PR TITLE
Search: add filtering support Woo brands plugin

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
The PR adds `product-brand` to taxonomy sync list, however this doesn't really have effects on syncing because all taxonomies are now synced. The change is to keep the list synced from WPCOM (`D86030-code`) and also make `Brands` available in Jetpack Search widget.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
p1660554618541599-jetpack-search-team-slack

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Open a site with Search plugin (and Search subscription), WooCommerce plugin and [WooCommerce Brands plugin](https://woocommerce.com/products/brands/)
- Open `/wp-admin/widgets.php` and add a Jetpack Search widget
- Ensure `Brands` is in the Taxonomy filter dropdown

image

### CODE REVIEW

**Review by annacmc — DISMISSED** [review]
nice one! lgtm 👍  curious what `product_brand` is for - is that for use with the other ` product brands with WooCommerce` competitor product, or maybe something else?
image

**Review by coder-karen — COMMENTED** [review]
Fixed up some lock file conflicts.

Is this to be tested with the Jetpack plugin installed and active too, using a legacy Search widget? That was how I was able to find the right widget - and it does work well in that case. Just wanted to double check.

**Comment by kangzj** [comment]
> curious what product_brand is for - is that for use with the other product brands with WooCommerce competitor product, or maybe something else? @annacmc 

I'm not sure. I think it could be typo, but like you said it could be from a competitor plugin, so I just kept it. Possibly @bluefuton knows more.

**Comment by kangzj** [comment]
> Is this to be tested with the Jetpack plugin installed and active too, using a legacy Search widget? That was how I was able to find the right widget - and it does work well in that case. Just wanted to double check. @coder-karen 

Hi @coder-karen, Thanks for your review 👍 

Yes it could be tested with only Jetpack plugin as well (or Search plugin, or both but would require a Search subscription) using the legacy Jetpack Search widget, we don't have a Gutenberg one yet.

Fixed up versions and could use another look please. Thanks in advance.

**Review by coder-karen — APPROVED** [review]

**Pull request merged**
