### PR TITLE
Paid blocks: Improve rendering of the upgrade nudge

### LINKED ISSUE #25102: Payment Button: Impossible to read upgrade banner
Example:

image

In context, in case it's theme related:

image

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/25102

#### Changes proposed in this Pull Request:

This PR adds a couple of enhancements to the paid blocks upgrade banner displayed on WP.com sites:

- Places the nudge inside the actual block edit component. Previously it was a sibling of that component, forcing us to hack CSS of the block toolbar so it doesn't overlap the nudge. Now that the nudge is part of the block edit markup, the toolbar is positioned correctly, effectively allowing us to remove the fixed height hack that was causing issues for cases when there is not enough width.

Before | After
--- | ---
Screen Shot 2022-08-29 at 11 56 52 | Screen Shot 2022-08-29 at 11 57 41

- Hides the nudge of nested paid blocks, and ensures that the the one of the parent block is the only one visible.

Before | After
--- | ---
Screen Shot 2022-08-25 at 12 53 48 | Screen Shot 2022-08-25 at 12 54 31

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Apply the diff created by Fusion to your WP.com sandbox.
- Sandbox a WP.com site.
- Go to https://wordpress.com/post.
- Select a Free site.
- Insert a Columns block with a 33 / 33 / 33 layout.
- Insert any paid block inside one of the columns.
- Make sure the upgrade nudge is displayed correctly with its height adapted to the content of the nudge.
- Insert a paid block in the root of the editor that contains another inner paid block. Some examples:
  - Payment buttons.
  - WhatApp button.
  - Premium content with a video in the subscriber content.
- Make sure that the upgrade nudger of the parent block is the only one that is visible.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Tested out the functionality here and everything works nicely 👍

**Review by lukaszwilczakwilnet — APPROVED** [review]
Works great.

**Comment by mmtr** [comment]
r251549-wpcom

**Comment by Addison-Stavlo** [comment]
👋  Hi all! We have been experiencing [an editor bug on dotcom ](https://github.com/Automattic/wp-calypso/issues/67929) with the position of the toolbar related to cover-block children that seems specific to free/personal plan simple sites.

After running a git bisect, it seems the wpcom commit for adding the changes in this PR introduced the regression.

**Comment by sdixon194** [comment]
Just noting that we are in the middle of defusioning blocks, so by the time we have a fix, we'll want to make sure it gets fixed on Jetpack's end as well, and not just patched on dotcom. Internal ref: p9dueE-5QR-p2

**Pull request merged**
