### PR TITLE
Contact form block - add example

### LINKED ISSUE #13648: Jetpack Contact Form block - fix gap between field name and required text
Breaking this one out of @simison's original mega-issue #13618 that lists out several visual regressions so we can tackle them one by one in separate PRs.

The gap between the field names and the "Required" text needs to be better balanced (justified) and the white backgrounds removed from the form field titles.

**Before/After:**
Screen Shot 2019-10-03 at 4 30 10 PM

### PR DESCRIPTION
**Pull request by MichaelArestad**
* props @gravityrail

Master issue: #13510

#### Changes proposed in this Pull Request:

* Added an example preview to the block in the Inspector.
* Also resolves the white form field title background and title/"required" text alignment issue, which Fixes #13648 

#### Before
image

#### After
image

Before/After of the field text alignment and bg color fixes:
Screen Shot 2019-10-03 at 4 30 10 PM

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Create a new post
* Click the + to open the Inserter in the **top bar**
* Hover over Form

#### Proposed changelog entry for your changes:

* None needed

### CODE REVIEW

**Comment by MichaelArestad** [comment]
This seems to now work (even though I can't get it to work). I'll take another shot at it in the morning and stub out all the fields to match the mockup.

**Comment by MichaelArestad** [comment]
There appears to be a display bug for blocks with innerblocks. There's a negative left/right margin set that makes the preview look not so great.

**Comment by MichaelArestad** [comment]
Added style overrides to core styles. Creating an issue in Gberg shortly and will link to it, but this will work in the meantime.

**Comment by MichaelArestad** [comment]
Gutenberg issue:
https://github.com/WordPress/gutenberg/issues/17760

**Comment by joanrho** [comment]
Looks great and works as expected!

**Review by jeherve — COMMENTED** [review]
The `@wordpress/block-editor` package used in this PR was only added to WordPress in version 5.2:
https://core.trac.wordpress.org/ticket/46429

Since Jetpack is currently compatible with WordPress 5.1, we can't use this just yet.

However, and as per the discussion in #13620, we should be able to update that requirement to WP 5.2 in the release after the next, once WordPress 5.3 is released for everyone. 

Should we wait to merge this until Jetpack 8.0 and our new compatibility change?

Another alternative would be to up our version requirement to WP 5.2 in this release already, but I am afraid this could be problematic for all the folks that still run WordPress 5.1.

**Comment by MichaelArestad** [comment]
@jeherve Ah! I had no idea. I was just trying to fix some warnings. I'll revert those changes.

**Comment by MichaelArestad** [comment]
@jeherve fixed

**Review by jeherve — APPROVED** [review]
This looks good to me. Merging!

**Pull request merged**
