### PR TITLE
Update contributors list

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request:

* Updates the list of contributors in the readme and plugin page. Adds:
  * bernhardreiter
  * brbrr
  * delawski
  * scottsweb
  * simison

#### Testing instructions:

* No testing required.

#### Proposed changelog entry for your changes:

* No changelog entry.

### CODE REVIEW

**Comment by jeherve** [comment]
@ockham What's your WordPress.org username? I am not sure if `ockham` is you, and `bernhardreiter` does not seem valid. 

Thank you!

**Comment by keoshi** [comment]
@jeherve Good catch, I grabbed it from Matticspace and didn't validate.

**Review by jeherve — APPROVED** [review]
This should be good to go. I removed Bernie for now, pending confirmation.

**Comment by simison** [comment]
Aww, thanks @keoshi <3

**Comment by keoshi** [comment]
My pleasure, @simison !

**Pull request merged**
