### PR TITLE
Adds additional plan slugs to active plan function

### PR DESCRIPTION
**Pull request by kraftbj**
There are some additional plan slugs that we need to add. Additionally, need to add these to any functions to automatically activate/deactivate modules.

### CODE REVIEW

**Comment by kraftbj** [comment]
While looking at it, it looks like the React side populates `this.props.plan` and needs to check for all variants. We can switch to use the `plan[class]` that this PHP provides to streamline the code and make this easier to add on to in the future.

**Comment by kraftbj** [comment]
Also want to update https://github.com/Automattic/jetpack/blob/9d5b9cadbc24999528be055d5d5725ffb4f77e4a/_inc/lib/admin-pages/class.jetpack-admin-page.php#L177

**Comment by rralian** [comment]
Nice work @kraftbj! This looks good and right to me. I think for testing we would want @seanosh to test this patch on the test pools for AT hosting. Then we can confirm it addresses this issue before we merge https://github.com/Automattic/automated-transfer/issues/115.

It's important that we get this merged by the 28th, which is the cutoff for the 4.8 beta. /cc @dereksmart

**Comment by dereksmart** [comment]
Cool, these will also need to be added to the plan constants for the admin UI so we're not showing prompts to upgrade to people who have these plans 

https://github.com/Automattic/dops-components/blob/master/client/lib/plans/constants.js

**Comment by rralian** [comment]
> Cool, these will also need to be added to the plan constants for the admin UI

@dereksmart looks to me like they're already added there (https://github.com/Automattic/dops-components/blame/master/client/lib/plans/constants.js#L7-L10) and it would already work correctly for `getPlanClass( $plan )`. What are the odds we could get a patch release for this PR? Waiting over a week for 4.8 may be a hard sell for support.

**Comment by kraftbj** [comment]
@dereksmart Can you check/add the react stuff needed to ensure that a site with one of these plans are not prompted to upgrade? Those constants are set, but the upgrade prompts I don't think care about them.

**Comment by rralian** [comment]
Can we put all necessary changes into one branch? I'd like to target master to hit 4.8, but I'd also like to rebase a fresh branch with these changes against latest stable so we can install on the AT servers rather than waiting for 4.8.

**Comment by dereksmart** [comment]
@rralian @kraftbj I've updated this to use the plan classes defined in dops-components rather than the raw slug.  This makes it much more DRY and will be very easy to add/update plan slugs in the future.  

Please test the /plans page, and also the upgrade banners throughout the settings for various wpcom-bundle plans.  

cc @eliorivero @zinigor would love your eyes on this one too.

**Comment by rralian** [comment]
That's much more pleasant, thanks. I want to test this in the AM on AT architecture (need systems to run the deploy), but the code looks good upon visual inspection.

**Comment by eliorivero** [comment]
Work fine, will merge 👍

**Pull request merged**
