### PR TITLE
Social | Simplify and clarify social network selection for post sharing

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Currently the messaging on the connection toggle section on post edit page is a bit confusing as highlighted here pdrWKz-1xe-p2

## Proposed changes:
* Update the connection related messaging to make the intent clear
* Simplify the logic used to render the messages

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pdrWKz-1xe-p2

## Testing instructions:

Follow these instructions for both Jepack and Jetpack Social individually as well as when both are installed

- For a site with some social connections added, create a new post
- Open the Jetpack or Social sidebar
- Confirm that the connection messages says, `"Enable the social media accounts where you want to share your post."` by default.
- Turn OFF Publicize (Share when publishing)
- Confirm that the message changes to `"Use this tool to share your post on all your social media accounts."`
- Turn ON Publicize again
- Confirm that enabling or disabling connections does not change the message
- Open an already published post
- Open the Jetpack or Social sidebar
- Confirm that the message always says, `"Enable the social media accounts where you want to re-share your post, then click on the "Share post" button below."`

## Screenshots
When the post is already published, we show the same message, whether any of the connections is enabled or not
Screenshot 2024-04-04 at 3 53 31 PM

For new posts, we show "Use this tool to share..." if publicize is not enabled
Screenshot 2024-04-04 at 4 07 01 PM

Otherwise show the enabled connections message
Screenshot 2024-04-04 at 4 07 22 PM

### CODE REVIEW

**Comment by gmjuhasz** [comment]
This looks good Manzoor, just one thought:

On a new post, all the connections are enabled by default, so instead of `Enable the social media accounts where you want to share your post.`, we could say something like `Use the social icons below to choose where to share your post.`


What do you think?

**Comment by manzoorwanijk** [comment]
> This looks good Manzoor, just one thought:
> 
> On a new post, all the connections are enabled by default, so instead of `Enable the social media accounts where you want to share your post.`, we could say something like `Use the social icons below to toggle where to share your post.`
> 
> What do you think?

Thank you for your input. I think `Enable the social media accounts where you want to share your post.` means that you should keep the connections enabled if you want to share to them.

**Comment by gmjuhasz** [comment]
> Thank you for your input. I think `Enable the social media accounts where you want to share your post.` means that you should keep the connections enabled if you want to share to them.

Yeah, that's true; I was just thinking of the fact that we tell them to enable the social media accounts where they want to share, but they do not have to enable them or do any action, as all are enabled by default, instead, they can toggle off a few if they want 🤔

**Comment by manzoorwanijk** [comment]
> Yeah, that's true; I was just thinking of the fact that we tell them to enable the social media accounts where they want to share, but they do not have to enable them or do any action, as all are enabled by default, instead, they can toggle off a few if they want 🤔

That makes sense.

How about the modified version of the suggestion from that p2 post?

`Click on the social icons below to control where you want to share your post.`

**Comment by gmjuhasz** [comment]
> `Click on the social icons below to control where you want to share your post.`

💯

**Comment by manzoorwanijk** [comment]
Done ✅

**Review by gmjuhasz — APPROVED** [review]
Works well, nice!

**Pull request merged**
