### PR TITLE
Update i18n-calypso

### PR DESCRIPTION
**Pull request by simison**
Update `i18n-calypso` dependency which in turn is mainly update of its dependencies. As you can see in the lockfile, it should get rid of some duplicate dependencies.

[See i18n-calypso changelog](https://github.com/Automattic/wp-calypso/blob/9ebe145354a7e7ab5540ce2ecd861c61ff7f963b/packages/i18n-calypso/CHANGELOG.md)

#### Changes proposed in this Pull Request:
* No functional changes.

#### Testing instructions:

- Confirm that everything with translations works in Jetpack dash normally.
- Confirm that `yarn build-languages` builds and updates `_inc/jetpack-strings.php` as well as languages json files.

#### Proposed changelog entry for your changes:

- N/A

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
Is there a reason we can't wait until the stable release? Renovatebot would then prompt us to update I think.

**Comment by jsnajdr** [comment]
Did the CLI changes break anything? Or is the update just considered more risky because of that?

**Comment by simison** [comment]
@jsnajdr CI is failing with:

```
/home/travis/build/Automattic/jetpack/node_modules/i18n-calypso/cli/index.js:74
	throw new Error( 'Error: You must enter the input file. Run `i18n-calypso -h` for examples.' );
	^
Error: Error: You must enter the input file. Run `i18n-calypso -h` for examples.
    at Object.<anonymous> (/home/travis/build/Automattic/jetpack/node_modules/i18n-calypso/cli/index.js:74:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

    at Module._compile (/home/travis/build/Automattic/jetpack/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/travis/build/Automattic/jetpack/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by simison** [comment]
Also fair to point out that Jetpack's way of using the CLI functions can be little bit outside intended way. ;-)

**Comment by simison** [comment]
>Is there a reason we can't wait until the stable release? Renovatebot would then prompt us to update I think.

I think we've just been little careful with versions but internally we could consider the package fairly stable. It's used in Calypso as-is after all.

**Comment by jsnajdr** [comment]
Oh, what Jetpack does is not run the CLI script as executable, but rather import it as a module in a Gulpfile and call the imported CLI-ish function.

In `gulpfile.babel.js`, changing the import from
```js
import i18n_calypso from 'i18n-calypso/cli';
```
to 
```js
import i18n_calypso from 'i18n-calypso/cli/i18n';
```
should fix it.

Or we can rearrange files in the `i18n-calypso` package so that the `i18n-calypso/cli` path exports the right thing and the actual bin script is `bin.js` instead of `index.js`. That'd be more clean.

**Comment by jsnajdr** [comment]
The `i18n-calypso-cli` package proposed in Automattic/wp-calypso#36669 should be very helpful here.

**Comment by simison** [comment]
https://www.npmjs.com/package/i18n-calypso-cli is now published so this PR can be reworked to use that. :tada:

Also `i18n-calypso` is now at stable v4.0.0 :tada:

**Review by zinigor — DISMISSED** [review]

**Review by zinigor — APPROVED** [review]

**Pull request merged**
