### PR TITLE
removing rocketeer flyby on jump start activation

### PR DESCRIPTION
**Pull request by jeffgolenski**
Once a user clicks "Jump Start" and it activates, an outdated version of our rocketeer flies by several times across the screen.

While this is a cool animation, it provides no real benefit to the user, as there is a success message as well. It's a lot of excess code that isn't needed.

FIXES: https://github.com/Automattic/jetpack/issues/3009

### CODE REVIEW

**Comment by dereksmart** [comment]
Goodbye sweet rocketeer, you will be missed.  

:shipit:

**Comment by dereksmart** [comment]
actually there's another reference to them in https://github.com/Automattic/jetpack/blob/master/_inc/jp.js#L310

**Comment by jeffgolenski** [comment]
@dereksmart Taken care of. Thanks for the find. 

Don't worry, we'll add something fun to 4.0 :-P

**Comment by samhotchkiss** [comment]
:( Farewell, Miguel!

**Comment by jeffgolenski** [comment]
@samhotchkiss Miguels are neither created nor destroyed. Merely transferred.

**Comment by dereksmart** [comment]
tested, good to go

**Pull request merged**
