### PR TITLE
Likes: Sync all public post types.

### PR DESCRIPTION
**Pull request by kraftbj**
When Likes are enabled, Custom Post Types will display the chrome for Likes, but will never load the like button since they aren't synced up to wpcom. Most users won't notice this since the Stats module takes care of syncing public CPTs.

This PR modifies Likes to sync public CPTs as well for those without Stats enabled.

cc: @xyu since it extends on the fix of #697

### CODE REVIEW

**Comment by xyu** [comment]
@kraftbj This looks good, only thing is during realtime syncing only posts matching both the post type and post status are synced so I could consider syncing all public post statuses as well which is what the stats module does.

https://github.com/Automattic/jetpack/blob/3726e9/modules/stats.php#L46-L52

**Comment by kraftbj** [comment]
@xyu Do you think there is logic to broadening the default to include all public CPTs/status by default or specify like this for stats/likes?

**Comment by xyu** [comment]
I believe the only reason we don't default to public CPTs and stati is fear of poorly configured sites. It's possible for people to add a public CPT but not have it displayed on the home page by default and assume it's "private" even through it is not.

I suppose for stats/likes we need the posts (post ids in particular) so that we can actually track views and likes so even if we get synced "private" content it's not so bad. Making this the default for all modules potentially means allowing pseudo-private content to be searched (e.g. related posts module) or otherwise leaked. Personally I don't think this is so bad as the content is not private anyway and someone could also expose these CPTs by simply walking through post ids on the site but I would rather have more of the Jetpack team discuss and make a change like this explicitly.

**Comment by kraftbj** [comment]
@xyu Sounds good and makes sense. I'll make the suggested change specific to this PR and open a new discussion regarding the default behavior. Thanks!

**Comment by dereksmart** [comment]
LGTM as well

**Comment by dereksmart** [comment]
note: users will need to re-index their posts in order for their old CPT's to show likes.  Will work automatically on new posts.

**Pull request merged**
