### PR TITLE
Updates wpcomsh to sync with version 3.22.13.

### PR DESCRIPTION
**Pull request by zinigor**
## Proposed changes:
* https://github.com/Automattic/wpcomsh/pull/1835
* https://github.com/Automattic/wpcomsh/pull/1893
* https://github.com/Automattic/wpcomsh/pull/1897
* https://github.com/Automattic/wpcomsh/pull/1900
* https://github.com/Automattic/wpcomsh/pull/1901
* https://github.com/Automattic/wpcomsh/pull/1902
* https://github.com/Automattic/wpcomsh/pull/1905

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Review by anomiex — DISMISSED** [review]
Looks to be a match for what's in the old wpcomsh repo.

**Review by anomiex — APPROVED** [review]

**Review by tbradsha — APPROVED** [review]
I can confirm the changes match what are in the `wpcomsh` repo. I'm not sure why the `create_function` polyfill was added, though, as it's not used.

**Comment by anomiex** [comment]
Automattic/wpcomsh#1894 doesn't give any more clue. It links to https://github.com/Automattic/wp-calypso/issues/91005 which just says "Polyfilling `create_function` in WPCOMSH should fix some sites" with no indication of what sites or why they can't fix their code. 🤷

**Comment by tbradsha** [comment]
Yep, I saw that. 🤷

**Pull request merged**
