### PR TITLE
Revert "Show social review prompt with both Social and Jetpack installed"

### PR DESCRIPTION
**Pull request by spsiddarthan**
Reverts Automattic/jetpack#29910

We are going to revert this PR to fix the initial state of the plugin p1681469685034749-slack-C02JJ910CNL and pick up 1198218726984184-as-1204393860935466 in the following sprints. The social plugin will have the review prompts working when it's active. The review prompts won't show up when both Social and Jetpack are active. 

This is the https://github.com/Automattic/jetpack/pull/27917 which originally added the review prompts. But this [line](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/social/src/class-jetpack-social.php#L295) sets the state for the Social plugin only if the Jetpack plugin is not active which leads to https://github.com/Automattic/jetpack/pull/29910 being created, I presume. That accidentally stomped over the plugin's initial state.

## Does this pull request change what data or activity we track or use?

* Yes, this PR reinstates 3 new analytics events around the new review prompt:

- jetpack_social_plugin_review_prompt_view (recorded when review prompt is rendered)
- jetpack_social_plugin_review_prompt_new_review_click (recorded when "Leave a review" is clicked)
- jetpack_social_plugin_review_prompt_dismiss_click (recorded when "Dismissed" is clicked)

## Testing instructions:

- When the prompt renders, the jetpack_social_plugin_review_prompt_view analytics event should fire. Search for this in your browser's network panel to confirm.
- Confirm that clicking on "Leave a Review" takes you to the reviews page for the Jetpack Social plugin
- Create another new post, but disable sharing. No prompt will show up since sharing was disabled. 
- Publish a post again, but disable the individual connections. Make sure the prompts don't show up. 
- Publish a post again with sharing enabled and notice that the prompt shows up. Dismiss the prompt
- Publish a post again with sharing enabled and notice that no prompt shows up.

### CODE REVIEW

**Comment by danielpost** [comment]
@spsiddarthan I created a new site to test this. Connected Social, added an account and published a new post. Instead of the prompt I got an empty panel (see screenshot). Any idea what might cause this?

Screenshot 2023-04-18 at 10 05 57@2x

**Comment by spsiddarthan** [comment]
>Any idea what might cause this?

I'll have to check that, Daniel! Will get back.

**Comment by pablinos** [comment]
> Instead of the prompt I got an empty panel (see screenshot). Any idea what might cause this?

If that was with Jetpack Social rather than Jetpack then I think that's the problem the original PR was trying to fix. Maybe we should fix it rather than reverting it.

**Comment by pablinos** [comment]
The empty [panel comes from here](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js#L209-L244). `showNotices` is false causing an empty panel to be rendered. I'm not sure why we don't get one in the pre-publish sidebar, but the problem doesn't seem related to this PR.

**Review by pablinos — APPROVED** [review]
This is working well for me. It reverts the changes, and the review prompt is still displayed when Social is active, but not Jetpack.

**Comment by spsiddarthan** [comment]
>If that was with Jetpack Social rather than Jetpack then I think that's the problem the original PR was trying to fix. 

Right, it is happening only in the Jetpack plugin.

>Maybe we should fix it rather than revert it.
Definitely, I tried my hand at it but it seems a like a bit of work. So, I decided to do that in the next sprint. 

I am merging this fix for now, so the social plugin's reviews work correctly.

**Pull request merged**
