### PR TITLE
Admin: fix orphans in Akismet and Update cards in AAG

### PR DESCRIPTION
**Pull request by eliorivero**
#### Changes proposed in this Pull Request:
- Reword text in Akismet and Update cards to avoid orphans

Before:

captura de pantalla 2016-08-15 a las 15 44 52

captura de pantalla 2016-08-15 a las 15 54 01

After:

captura de pantalla 2016-08-15 a las 16 09 39

captura de pantalla 2016-08-15 a las 15 57 43

#### Testing instructions:
- Go to Jetpack Admin > Dashboard

### CODE REVIEW

**Comment by zinigor** [comment]
I can't find any traces of previously translated texts, or do you mean something else by orphans?

**Comment by eliorivero** [comment]
@zinigor orphan is a typography term. It's a word left alone in a line. The images in the **Before:** show the `fix.` and `work!` words that are orphans.

**Comment by zinigor** [comment]
I see now! Although this PR looks fine, I hate to disappoint, but we can't foresee which fonts the user will have and what sentences are going to look like translated. But still, this is good to go.

**Comment by eliorivero** [comment]
@zinigor I'm aware of that, I'm just fixing what I can. When translating, users might typeset correctly or not according to their font face, but at least we have to do it right. Thanks for the review.

**Pull request merged**
