### PR TITLE
Custom CSS: Allow multiple `display` properties to be used

### LINKED ISSUE #4176: Custom CSS: Multiple `display` properties are stripped out of minified CSS
#### What I expected

This CSS should be preserved after being passed through CSSTidy:

```
.container {
 display: -webkit-flex;
 display: -ms-flexbox;
 display: -webkit-box;
 display: flex;
}
```

#### What happened instead

Instead the final result was:

```
.container {
 display: -webkit-flex;
}
```

### PR DESCRIPTION
**Pull request by iandunn**
Fixes #4176

### CODE REVIEW

**Comment by georgestephanis** [comment]
cc: @samhotchkiss ^^ for 4.1 plz

**Comment by kraftbj** [comment]
LGTM.

**Comment by marcustisater** [comment]
Wohooo. Thanks guys!

**Comment by marcustisater** [comment]
When can we see a 4.1 release ready to use for WordCamp.org?

**Comment by jeherve** [comment]
@marcustisater This patch is already running on WordCamp.org, as perhttps://github.com/Automattic/jetpack/issues/4176#issuecomment-227306132

**Pull request merged**
