### PR TITLE
Update babel-eslint → @babel/eslint-parser

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

[babel-eslint](https://www.npmjs.com/package/babel-eslint) has been renamed to [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser). Let's make that change.

That also requires some config changes to point @babel/eslint-parser at the babel config in each project, as the new package uses the actual babel config to know what lints to check for.

This also makes a few other fixes related to eslint:

* Add some missing built files to `.eslintignore`.
* Include `.cjs` files in linting.
* We're getting an error about "React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed." Fix that by only loading react rules when processing projects that use react.
* Move the eslint deps to a workspace, so as to not clutter the monorepo root with them.

#### Jetpack product discussion

None.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Is CI happy?
* Can you run eslint and eslint-changed like you could before? Note that you may need to do `jetpack clean all node_modules && pnpm install` after checking this out to fix the `eslint` symlink.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
This would seem to create issues with Testspace, as per the e2e checks. Not sure what's causing this?

**Comment by anomiex** [comment]
My best guess is their client (which I don't see source for) is somehow or other choking on the branch name. Some poking at it with [strace](https://en.wikipedia.org/wiki/Strace) and [ltrace](https://en.wikipedia.org/wiki/Ltrace] suggests that it's getting confused by the `@`.

**Comment by jeherve** [comment]
> My best guess is their client (which I don't see source for) is somehow or other choking on the branch name. Some poking at it with [strace](https://en.wikipedia.org/wiki/Strace) and [ltrace]([https://en.wikipedia.org/wiki/Ltrace]](https://en.wikipedia.org/wiki/Ltrace%5D) suggests that it's getting confused by the `@`.

@munderseth Hi! 

Is that something you could look into? It may be worth supporting more "exotic" characters in branch names, to avoid such issues.

Thank you!

**Comment by anomiex** [comment]
Looks like wpcom is failing to apply because people haven't taken care of D62346-code and D63200-code yet. Sigh.

**Comment by anomiex** [comment]
@munderseth The question is what is going on at https://github.com/Automattic/jetpack/pull/20085/checks?check_run_id=2906345972#step:18:10

I guessed that it might be choking on the `@` because ltrace was showing some string processing that had cut off strings including the branch name at that point. But I could be wrong. I also saw some hints of mojibake in there too.

**Comment by munderseth** [comment]
@anomiex we will double-check on our side.

**Comment by munderseth** [comment]
@anomiex, @jeherve we are able to reproduce this issue. This is a [bug](https://github.com/testspace-com/testspace.support/issues/16) on the Testspace client. 

How quickly does this need to be resolved .. roughly :smile:

**Comment by anomiex** [comment]
Well, I'd like to be done with this PR sooner rather than later. But the testspace failures don't actually block a merge, if @jeherve or someone is willing to ignore them. I don't think we're too likely to create more PRs using `@` very soon.

**Review by jeherve — APPROVED** [review]
This seems to test well. Let's give it a try. 👍

**Comment by anomiex** [comment]
r227937-wpcom

**Pull request merged**
