### PR TITLE
Packages: Release Status and My Jetpack (again)

### PR DESCRIPTION
**Pull request by sdixon194**
#### Changes proposed in this Pull Request:

Releasing these two packages again.

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

no
#### Testing instructions:

Proof
* Go to '..'
*

### CODE REVIEW

**Review by anomiex — APPROVED** [review]
Could fix up the message in the projects/plugins/jetpack/changelog/update-release-packages-again file, but the only thing it'll affect is that you'll have to delete the line for it when you update the changelog for the final 10.7 release.

**Review by anomiex — COMMENTED** [review]
Oh, wait, I was confused, this is the backport to the master branch. I'd delete that changelog entry file, and run the fixup-project-versions.sh to fix the lock file.

**Review by samiff — DISMISSED** [review]

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
> didn't work

Looked like GH was just being slow about scheduling the job to check the required reviewers, and you dismissed the review *just* before it finally did run.

**Comment by sdixon194** [comment]
Looks like it went now, thanks both 👍

**Pull request merged**
