### PR TITLE
Boost: track when someone moves from Boost Cache to WPSC

### PR DESCRIPTION
**Pull request by donnchawp**
Track sites that move from using Boost to perform caching to WPSC.

Fixes #

## Proposed changes:

* Add a hook on the action "jb_cache_moved_to_wpsc" that performs a tracks event.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pc9hqz-2QH-p2
pc9hqz-2V8-p2

## Does this pull request change what data or activity we track or use?

Yes, this PR allows us to track customers who go from using the Cache module of Boost to WP Super Cache.

## Testing instructions:
* Edit Page_Cache.php and add an error_log in track_move_to_wpsc() so you can see that functions being called.
* Disable WP Super Cache.
* Enable Boost, and the Cache module.
* Enable WP Super Cache and visit the settings page. Note the warning message about Boost.
* Disable the Boost Cache module. In the future this will delete advanced-cache.php
* Delete wp-content/advanced-cache.php. Do not disable Boost.
* Refresh the WPSC settings page.
* Note the error log showing the hooked function track_move_to_wpsc fired.

### CODE REVIEW

**Review by haqadn — COMMENTED** [review]
This shouldn't be able to work. The action hook is registered in `setup`. But, setup doesn't get called when a module isn't active. When WPSC is being activated, page cache would not be active.

So, I think we need to extract this out of the cache module.

**Review by pyronaur — DISMISSED** [review]
:shipit:

**Review by haqadn — DISMISSED** [review]
Check my comment above ^

**Comment by donnchawp** [comment]
@haqadn you're right. I was testing it by deleting the advanced-cache.php because disabling the Cache module doesn't currently delete it (until #37643 is merged), so I left it active.

**Comment by donnchawp** [comment]
The PR has been updated, the code moved into its own class. You'll have to do `composer dump-autoload` I guess.

I merged with trunk, so the notice shown in WPSC is updated and all you need to do is add error_log statements now to see what's happening.
I added an error_log() in app/lib/Super_Cache_Tracking.php in track_move_to_wpsc() and in super-cache/inc/boost.php, just above `do_action( 'jb_cache_moved_to_wpsc' );`.

**Review by dilirity — COMMENTED** [review]
Since we both worked on this, I'm not going to approve it.

Just leaving a comment that to mention that I think it's okay to merge 😅

**Comment by donnchawp** [comment]
Related: p1717702393232449-slack-C016BBAFHHS

**Review by dilirity — APPROVED** [review]

**Pull request merged**
