### PR TITLE
Contact Form: Remove the Connection button from the Form block toolbar

### LINKED ISSUE #27294: Form Block - Remove "connection feature" from toolbar
Image

Based on this request: p1666986265839269-slack-C01CSBEN0QZ

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27294

#### Changes proposed in this Pull Request:
* Remove the Connection button from the Form block toolbar
* More context on #27294

Before:
image

After
image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a Post/Page and add a Form block
* Check if the Connection button was removed from the From block toolbar

### CODE REVIEW

**Review by digitalwaveride — APPROVED** [review]
Looks good to me. 👍

**Review by CGastrell — APPROVED** [review]
LGTM!

**Comment by chrisbliss18** [comment]
Trying to run through the testing instructions with the latest trunk, I'm unable to recreate the "before" picture. Instead, I see the following:
form-block-settings

Is there something I'm not doing correctly in order to recreate the "before" image when running trunk?

**Review by anomiex — APPROVED** [review]
Appears to work as advertised.

**Pull request merged**
