### PR TITLE
Update Node to match latest LTS 12

### PR DESCRIPTION
**Pull request by kraftbj**
https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/

#### Changes proposed in this Pull Request:
* Bumps to latest LTS 12.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
* After applying patch, you may want to run `nvm install && nvm use` and `nvm alias default v12.21.0`

@anomiex and @jeherve Can y'all note on here when your chipsets/OSes have this update? `nvm` on Intel Macs has it.

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by kraftbj** [comment]
Also need to wait on https://www.npmjs.com/package/node

**Comment by jeherve** [comment]
> Can y'all note on here when your chipsets/OSes have this update?

It's available for Apple M1.

**Comment by anomiex** [comment]
I didn't see a bug or discussion in Debian yet, so I filed a bug with them to request the upgrade. I'll edit this comment with the link once their system finishes processing the email and creates the bug.

**Comment by anomiex** [comment]
Debian now has 12.21.0 in unstable: https://packages.debian.org/sid/nodejs

**Review by anomiex — COMMENTED** [review]
I see a few more references to 12.20.1:

* [projects/packages/jitm/package.json:30](https://github.com/Automattic/jetpack/blob/f1a4bb451232aa33d742ec255b7b0751ef379130/projects/packages/jitm/package.json#L30)
* [projects/packages/connection-ui/package.json:36](https://github.com/Automattic/jetpack/blob/f1a4bb451232aa33d742ec255b7b0751ef379130/projects/packages/connection-ui/package.json#L36)
* [projects/plugins/jetpack/package.json:212](https://github.com/Automattic/jetpack/blob/f1a4bb451232aa33d742ec255b7b0751ef379130/projects/plugins/jetpack/package.json#L212)
* [projects/plugins/jetpack/tests/e2e/package.json:46](https://github.com/Automattic/jetpack/blob/f1a4bb451232aa33d742ec255b7b0751ef379130/projects/plugins/jetpack/tests/e2e/package.json#L46)

**Comment by kraftbj** [comment]
Added the references and merged master into it. Still waiting for the npm package; I pinged the developer.

**Comment by kraftbj** [comment]
The maintainer missed my comment on the existing issue to bump version, so opening a new one in https://github.com/aredridel/node-bin-gen/issues/119

I'd like to get with devops to figure out why we're not using `nvm` and see about using that directly instead. I don't think we should be using an unofficial source.

**Comment by kraftbj** [comment]
Haven't tested but we should be ready on the wp.com side. Once tested I think we'd be able to land this.

**Comment by kraftbj** [comment]
Looks like all of our environments are ready for this change.

**Review by anomiex — APPROVED** [review]

**Comment by kraftbj** [comment]
r22225-wpcom

**Pull request merged**
