### PR TITLE
Super Cache: Boost banner with auto-install

### PR DESCRIPTION
**Pull request by thingalon**
Update: A previous iteration of this PR included an attempt to merge https://github.com/Automattic/jetpack/pull/26890 to add a new top level menu structure and a one-click auto-install for Jetpack Boost, but that turned into a quagmire with the main codebase not yet passing linting. So, I am breaking that up into multiple projects.

This PR brings a new dismissable one-click installation banner inviting users to try Jetpack Boost for further speed-ups:

image

Just click the button and it will auto-install and activate Jetpack Boost. Or, click the X to get rid of the notice.

#### Changes proposed in this Pull Request:
* Add a dismissable banner for boost to super cache.
* Automatically install Jetpack Boost with one click.

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Make sure you can dismiss the banner.
* Make sure that clicking the link auto-installs Boost properly.
* Make sure the banner does not show if you already have Boost.
* If you have Boost installed but not activated, make sure the banner instead shows an option to activate Boost.

### CODE REVIEW

**Comment by oskosk** [comment]
Pushed a few commits to try out some things in relation to the second part of p4Mypo-9b-p2 asuuming we can eventually show a specialized section for Super Cache.

* [Update left margin to 2rem in banner](https://github.com/Automattic/jetpack/pull/26702/commits/6fbe9cbce0535e072512de83f92357ce55013620)
* [Match .boost-banner top margin with .wpsc-callout's](https://github.com/Automattic/jetpack/pull/26702/commits/2207cdd4b273479788f2ed09692395c3fd4e1659)
* [Update to Jetpack Boost logo and update headline](https://github.com/Automattic/jetpack/pull/26702/commits/d360b867859d73cdc61c6f73a03faea61c949e58)

We can revert any of these if we want.

#### After

image

#### Before

image

**Comment by oskosk** [comment]
For some reason, admin_notices are rendered inside this banner introduced here.

image

In the image, this is the Jurassic Ninja notice, but I also saw it locally with a notice coming from Super Cache. Some warning.

**Comment by thingalon** [comment]
Thanks @oskosk for pointing this out:

> For some reason, admin_notices are rendered inside this banner introduced here.

That was fun. Took a little figuring out. The notices were being moved down by a script which shifts notices to just below the page's main heading -- looking for an h1 or h2 element. The banner was using an h2, confusing the admin scripts. 

Shifted to an h3 which has the same styling, and it's all good in ae32d30f7c

**Comment by mikestottuk** [comment]
Some comments from me after testing this out:-

- If I have Jetpack Boost downloaded, it still says "Install Boost" maybe it should say Activate in this case?
- What do we feel about  `p4Mypo-9b#comment-474` adding a top level menu in and red bubble?

I'm torn on it, I think it'll get us more clicks of the banner but it might come across as us highlighting a move just to show a banner...

**Comment by thingalon** [comment]
@mikemayhem3030 thanks for the feedback!

> If I have Jetpack Boost downloaded, it still says "Install Boost" maybe it should say Activate in this case?

🤔 You're right, it would be smoother that way. I'll take a look at that.

> What do we feel about  `p4Mypo-9b#comment-474` adding a top level menu in and red bubble?

Top level menu, definitely. I think Super Cache is a bit hidden away at the moment. However, not sure about a red bubble at the moment as nothing here is really an "alert". But I am open to a red bubble if we have something in the future the user's attention needs to be drawn to.

**Comment by mikestottuk** [comment]
> You're right, it would be smoother that way. I'll take a look at that.

I don't think it matters for this release, so I'll do a final review and then merge it (it will help if it's merged before I do the top level menu stuff)

**Review by mikestottuk — DISMISSED** [review]
LGTM and tests well. Hides itself after Boost is installed too which is a nice touch.

**Review by haqadn — APPROVED** [review]
LGTM!

**Pull request merged**
