### PR TITLE
Delete modules/blocks.php

### PR DESCRIPTION
**Pull request by simison**
Removes deprecated file.

### CODE REVIEW

**Comment by simison** [comment]
This will need to be removed from Fusion list as well.

**Review by roccotripaldi — APPROVED** [review]
Thanks :)

**Comment by roccotripaldi** [comment]
Fusion handled in D26072-code

**Review by jeherve — COMMENTED** [review]
We tend to keep those around for a bit, as removing files altogether sometimes cause fatals on sites with custom caching configurations.

**Comment by kraftbj** [comment]
I would say leave it. The problem comes into play on sites with opcaches that aren't automatically refreshing on file system changes. The php files in the modules folder are all loaded, so opcache is clinging onto that a blocks.php file exists. It is a require_once which then fatals since it isn't there anymore.

We have a number of these (debug.php, wpcc.php) and personally would rather us go through them all at once after doing more homework about ways to be more defensive against those caching setups.

I'm going to close this for that reason, but concur it should be removed from Fusion and wp.com.

**Comment by simison** [comment]
Nice, thanks folks! Today I learned about such issues with caches. :-)

**Pull request closed without merging**
