### PR TITLE
Use wp eval-file when generating module headings

### PR DESCRIPTION
**Pull request by gravityrail**
Extracted from #12213 

Note to reviewers: I'm happy with this going in 7.3 if you feel it's low risk. I made it 7.4 just to be conservative.

#### Changes proposed in this Pull Request:

In order to move module locations, we need to:

* make `get_module_path` filterable
* boot WP when generating module headings (rather than just globbing files) in case module code lives in another location

This should result in no user- or developer- visible changes. It's simply a foundational piece allowing us to move module locations in the future.

*Open question*: This probably requires that Jetpack is developed from within a WP instance (likely) and that it is active in the current WP instance (not as likely, but probable). Should we explicitly check and bail if those conditions aren't met?

#### Testing instructions:
* run `yarn build`
* everything should be built as usual

### CODE REVIEW

**Comment by kraftbj** [comment]
Thanks @gravityrail. I'm going to keep this on 7.4. 

There's some unit test failures; I haven't investigated them at all. Unless urgent, I'll likely not get to review this until after 7.3 ships on Tuesday.

**Comment by jeherve** [comment]
Noting that unit tests are not passing for this branch right now.

**Comment by roccotripaldi** [comment]
I was able to get the tests to pass by adding better error handling and ensure that we continue to run the build even if we encounter errors.

However, `php:module-headings` is not successful. At the moment, I don't think `wp` commands are available during the build.

**Comment by roccotripaldi** [comment]
For now, we can assume a normal module path whenever we build the module-heading translations.

Once we move modules, we will likely need to modify our heading translation process in a way that does not require booting wp during the build.

**Review by jeherve — APPROVED** [review]
As it stands, this PR does not do much on its own anymore; it only adds a new filter.

**Pull request merged**
