### PR TITLE
fix: Minor typos in docs/development-environment.md

### PR DESCRIPTION
**Pull request by jaswrks**
#### Changes proposed in this Pull Request:

* Fixes some minor typos in `docs/development-environment.md`

---

*I was just digging in a bit and thought I'd fix these while I was reading it myself.*

### CODE REVIEW

**Comment by oskosk** [comment]
Thank you!. If this is ready for review, please label as such

**Comment by jaswrks** [comment]
@oskosk It is ready, yes. Thank you.
Sorry, I don't have access to Labels in this repo.

**Comment by oskosk** [comment]
oh right. Sorry.

**Comment by oskosk** [comment]
It's merged now. Thank you again!

**Pull request merged**
