### PR TITLE
Use new GitHub secret to manage pushing to Project Boards

### PR DESCRIPTION
**Pull request by thingalon**
In #21800 I added a workflow to push new Issues to Project Boards based on their labels. Unfortunately when I deployed it, it didn't work. As far as I can tell from [reading the action logs](https://github.com/Automattic/jetpack/runs/4280792889?check_suite_focus=true#step:2:77), it's not getting a valid project-id back [when searching for one](https://github.com/monry/actions-add-issue-to-project/blob/main/action.yml#L64), so I believe it's a permissions issue.

So, this PR switches to a new secret I created called `PUSH_ISSUES_TO_PROJECTS` which contains a Personal Access Token I created with the correct permissions. I also added a comment documenting what permissions the PAT needs to support the script.

#### Changes proposed in this Pull Request:
* Switch issues-to-project action to use secret specifically set up for it.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
1. Read the code and make sure it seems ok
2. Merge and test.
3. Lament that GitHub actions are a pain. :)

### CODE REVIEW

**Comment by anomiex** [comment]
The `monry/actions-add-issue-to-project` action you're using seems to have claimed to succeed even though it didn't. It's also raising a Node deprecation warning. Perhaps you should see if one of the alternative actions available in GH's marketplace has better error handling?

It might be best if the new secret were named something like `PUSH_ISSUES_TO_PROJECT_TOKEN`, or maybe even something more descriptive of the token rather than the use it's being put to here.

Also, just to verify, is this new token something that can be documented at PCYsg-xsv-p2 with rotation information, or is it associated with your personal account?

**Comment by thingalon** [comment]
Thanks for the feedback!

> The monry/actions-add-issue-to-project action you're using seems to have claimed to succeed even though it didn't. It's also raising a Node deprecation warning. Perhaps you should see if one of the alternative actions available in GH's marketplace has better error handling?

I've switched to [another option from the marketplace](https://github.com/leonsteinhaeuser/project-beta-automations), which seems to have better error handling and doesn't generate warnings. :)

I've tested it [in the boost-hydra repos](https://github.com/Automattic/boost-hydra/blob/main/.github/workflows/issues-to-projects.yml), and it [works without warnings](https://github.com/Automattic/boost-hydra/runs/4318385057?check_suite_focus=true) and [produces errors when the permissions aren't right](https://github.com/Automattic/boost-hydra/runs/4318399809?check_suite_focus=true).

> It might be best if the new secret were named something like PUSH_ISSUES_TO_PROJECT_TOKEN, or maybe even something more descriptive of the token rather than the use it's being put to here.

Changed in 0ad8b47e03. 

> Also, just to verify, is this new token something that can be documented at PCYsg-xsv-p2 with rotation information, or is it associated with your personal account?

If you're happy to make these changes, I can add it to the above page with rotation information - though it is a PAT associated with my account, anyone with appropriate access should be able to generate an access token to replace it. I'm not sure I want to put a PAT with access to my gh account into the a8c secret store, though :)

**Review by anomiex — APPROVED** [review]
> If you're happy with these changes, I can add information about the secret to the above page with rotation information. It is a PAT for my GH account, but anyone with appropriate access should be able to generate replacement tokens. Though I'm not comfortable about putting a PAT for my personal GH account into the A8c secret store. :)

Probably the best thing would be to request devops (or someone else with access to the Matticbot account) to generate the proper token on that account.

**Comment by thingalon** [comment]
🥳 It works!

**Comment by thingalon** [comment]
I've [asked systems](https://systemsrequests.wordpress.com/) to set up a new Secret using the matticbot account to replace my PAT.

**Comment by thingalon** [comment]
I've put in a request to have the secret replaced with a matticbot one. pMz3w-edJ-p2

**Comment by thingalon** [comment]
All done and documented in the fieldguide :)

**Pull request merged**
