### PR TITLE
Forms: allow Crowdsignal to approve Forms package PRs.

### PR DESCRIPTION
**Pull request by kraftbj**
n/a -- This team has responsiblity for the Forms package.

## Proposed changes:

* Allow the `crowdsignal` team to be an approver for the Forms package

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* n/a

### CODE REVIEW

**Comment by anomiex** [comment]
The new team should probably be added here so they can update lock files elsewhere when needed
https://github.com/Automattic/jetpack/blob/005b692636ede8895d614038501bc603ce8666f8/.github/files/required-review.yaml#L18-L26
And the package should be excluded here now that some other team owns it
https://github.com/Automattic/jetpack/blob/005b692636ede8895d614038501bc603ce8666f8/.github/files/required-review.yaml#L33-L43

**Comment by kraftbj** [comment]
> The new team should probably be added here so they can update lock files elsewhere when needed

Going to hold off on this since there shouldn't be much need yet and trying to keep it scoped to just the forms package itself.

**Review by jeherve — APPROVED** [review]
Should be good now I think (short of the alphabetical order in the first list if I'm nitpicking :) )

**Review by anomiex — APPROVED** [review]
Should work.

**Comment by oskosk** [comment]
Thanks folks

**Pull request merged**
