### PR TITLE
Update/remove in place connection from Dashboard and Settings

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

* Disables the in-place authorization flow from the "Connect or user" buttons in Jetpack Dashboard and Settings pages

#### Jetpack product discussion

p1HpG7-bZE-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Perform a site-level connection
* Visit the Jetpack dashboard
* Check that the links to connect your user under the Stats, Protect and Monitor cards take you to Calypso
* Also check the button to connect the user down on the "Account Connection" card
* Visit Jetpack Settings page and make sure all buttons to connect your user take you to Calypso
* Log in with a secondary admin and make sure all links mentioned above also take you to Calypso

### CODE REVIEW

**Review by samiff — CHANGES_REQUESTED** [review]
Testing instructions work well for me!

Just a couple things:

1. Does the `<ConnectButton>` component still need the `connectInPlace` prop? If not, there are a few places to remove that.
2. On a successful user connection, I land on the Calypso plans page, is that the expected behavior?
3. Looks like there are two failing tests:

https://github.com/Automattic/jetpack/blob/b9a8a3b9398eabd382e4ac539bce4fda51225ba0/projects/plugins/jetpack/_inc/client/components/connect-button/test/component.js#L57

https://github.com/Automattic/jetpack/blob/b9a8a3b9398eabd382e4ac539bce4fda51225ba0/projects/plugins/jetpack/tests/e2e/lib/pages/wp-admin/in-place-authorize.js#L33

**Review by sergeymitr — COMMENTED** [review]
Everything works well 👍

**Comment by leogermani** [comment]
I'm putting this On hold until we finish this discussion: p9dueE-2SM-p2#comment-5122

**Comment by samiff** [comment]
@leogermani Were we still planning on this PR and #19871 ?

**Comment by leogermani** [comment]
> @leogermani Were we still planning on this PR and #19871 ?

No, thanks for the reminder. This will be addressed by the Streamline Connection Flow project -> p1HpG7-bZE-p2

**Pull request closed without merging**
