### PR TITLE
Admin menu: update with latest version of Jetpack logo

### LINKED ISSUE #29367: wp-admin: Jetpack icon is incorrect on the sidebar
I just noticed that the Jetpack graphic logo icon on the wp-admin sidebar is incorrect. Notice how the triangles are farther apart in the current graphic, different from the correct logo. 

For reference, I'm seeing this issue on a Jurassic Ninja site.

Please see attached comparison:
Image

Attached is the SVG of the correct Jetpack logo graphic.

Image

Below are the screenshot for the 3 states of which the logo appears on wp-admin:
Inactive / Hover / Active

Image
Image
Image

Let me know if you have any questions. Thanks so much.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #29367

## Proposed changes:

This involves a few changes:

1. Remove the Jetpack icon font we were using until today.
2. Remove the stylesheets that were enqueued to add that icon font.
    * That stylesheet also included some CSS for the Contact Form icon (see #17290). Now that we've switched to a dashicon for the Contact Form, it may no longer be necessary.
3. Add a new method to the Logo package, returning a base64-encoded SVG for the Jetpack icon.
4. Use that new method everywhere we need a Jetpack Logo in an admin menu.

image

image

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

This will require testing on different sites:

1. On a WoA site so you can test nav-unification (the admin menu displayed in Calypso).
2. On a self-hosted site using the Jetpack plugin.
3. On a self-hosted site using a standalone plugin.

In all 3 sites, the Jetpack icon should look good regardless of your admin color scheme (set under Users > My profile), and whether you're in the Jetpack menu (e.g. looking at Jetpack > Dashboard) or on another admin page. On the WoA site and the site running the Jetpack plugin, you should also check the Feedback menu icon.

### CODE REVIEW

**Comment by oskosk** [comment]
Apparently for WoA we're already using an svg ?

**Comment by oskosk** [comment]
It's looking like the version introduced here renders a bit bigger than sibling icons

image

I'm ok to go with this and then doublecheck tho.

**Review by oskosk — DISMISSED** [review]
LGTM

**Comment by jeherve** [comment]
> It's looking like the version introduced here renders a bit bigger than sibling icons

Ah, that's a good point, I hadn't noticed. I played with things a bit, but I'm not sure what I should aim for. When I make the logo smaller so it matches the "Dashboard" icon, then the "Media" icon is bigger. I'm no designer, so could definitely use some guidance on this.

Here is an example of things look like with this change:

```diff
diff --git a/projects/packages/logo/src/class-logo.php b/projects/packages/logo/src/class-logo.php
index 9cbf72a268..2689809879 100644
--- a/projects/packages/logo/src/class-logo.php
+++ b/projects/packages/logo/src/class-logo.php
@@ -112,7 +112,7 @@ class Logo {
 	public function get_base64_logo( $color = '#ffffff' ) {
 		$logo_text    = $this->get_jp_logo_parts( $color );
 		$base_logo    = sprintf(
-			'<svg xmlns="http://www.w3.org/2000/svg" x="20px" y="20px" viewBox="0 0 32 32">%1$s</svg>',
+			'<svg xmlns="http://www.w3.org/2000/svg" x="20px" y="20px" viewBox="-4 -5 41 41">%1$s</svg>',
 			$logo_text['logo']
 		);
 		$encoded_logo = base64_encode( $base_logo ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- The encoded version is used as data URI to use the logo in CSS.
```

Screenshot 2023-03-15 at 16 59 15
Screenshot 2023-03-15 at 16 59 34

**Comment by ballio2000** [comment]
Hello @jeherve! Thanks for the quick implementation of this, looking good! 

Regarding the sizing -- the smaller size above that matches the dashboard icon looks nice. The media icon is an outlier, the Jetpack logo would look visually too large compared to the other icons on the admin bar.

I did notice a small thing in the screenshots of the PR. In the hover state, I see that all the icon color also turns to blue, but not on the Jetpack icon above. Is it going to be blue when implemented?

**Comment by jeherve** [comment]
> Regarding the sizing -- the smaller size above that matches the dashboard icon looks nice. The media icon is an outlier, the Jetpack logo would look visually too large compared to the other icons on the admin bar.

Thank you. I pushed the size change in 849e0d599fd954fc799ef925aab8f798bb9b71c2

> I did notice a small thing in the screenshots of the PR. In the hover state, I see that all the icon color also turns to blue, but not on the Jetpack icon above. Is it going to be blue when implemented?

Here is a quick video of the implementation:

https://user-images.githubusercontent.com/426388/225388451-bb63d610-75c6-45ed-864c-add7368800d0.mov

You can also test it by yourself with Jurassic Ninja; the size change I just committed will not be part of the Beta for another 15 minutes until the build is complete, but you can already see the icon in action and its different states.

**Comment by ballio2000** [comment]
@jeherve, thanks for recording the screen capture; that looks good. I made a new JN site, and it still shows me the old version for some reason. Also, why is my wp-admin interface different from yours?

image

**Comment by jeherve** [comment]
> I made a new JN site, and it still shows me the old version for some reason. 

Did you create that site using the branch for this PR?

A quick way to go about creating a site using the branch from this PR would be to use Jetpack Live Branches:
https://github.com/Automattic/jetpack/blob/trunk/tools/jetpack-live-branches/README.md

Once you've installed the userscript, you'll see this at the bottom of all PRs:

image

> why is my wp-admin interface different from yours?

That would be because we use different color schemes. You can switch color schemes for your dashboard by going to Users > My Profile.

**Comment by oskosk** [comment]
@ballio2000 this is probably because you opted to launch a JN site with the Search plugin. BUT the default behavior of JN is to launch sites with whatever you ask for AND latest stable Jetpack. It may be that you're witnessing the logo of latest stable Jetpack taking precedence of Search's menu item registration.

**Comment by ballio2000** [comment]
@oskosk I just used the default button to create the JN site. Still not seeing the icon update with this new one. Thanks for working through it with me. :)

**Comment by jeherve** [comment]
> I just used the default button to create the JN site. Still not seeing the icon update with this new one. Thanks for working through it with me. :)

Any chance you could give one of us access to your site, so we can take a look?

Thank you!

**Review by keoshi — DISMISSED** [review]
Looks great in my testing!

image

**Comment by kraftbj** [comment]
Rebuilding to catch up with latest trunk, then I'll give this one a final review.

**Review by kraftbj — APPROVED** [review]
Let's do it.

**Pull request merged**
