### PR TITLE
Modify Jetpack_Client_Server to support unit testing, add some tests.

### PR DESCRIPTION
**Pull request by scotchfield**
Here's a proposal for modifying the Jetpack_Client_Server class so that it can be unit tested. Does this seem reasonable?

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Something seems off here, there aren't any unit tests as part of the PR any longer.

@dereksmart, are you noticing PRs missing commits?

**Comment by dereksmart** [comment]
@samhotchkiss what do you mean?  

There has been one instance of a missing commit after merging to master, but it was more than likely attributed to some irresponsible force-pushery

**Comment by scotchfield** [comment]
Not sure what happened, I haven't made any modifications here. Anything I can do?

**Comment by georgestephanis** [comment]
I'm seeing the test class -- what do you mean it's not showing?

**Comment by zinigor** [comment]
While I can see no problems with the code and I certainly think that the more tests the better, I have one comment. Redefining methods in the `Jetpack` class only to be able to mock them in tests seems kinda backwards to me. Being unable to mock static methods is a known problem with PHPUnit, and it is a part of the wider static method testability problem, so it's possible that the code needs some refactoring.

I would hate to see good code wasted, so I'd propose to merge this, but thoroughly explain in comments why we need those four wrappers. After that we should try to find a way to get rid of those. For example, one way to get rid of wrapping `init` is to assign a mock instance to `Jetpack::$instance` in the test case setup.

**Pull request merged**
