### PR TITLE
Fix for CSSTidy crashing because of missing old-style constructor

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes issue with crash when saving CSS due to removal of old-style PHP object constructors.

### CODE REVIEW

**Comment by lezama** [comment]
:shipit:

**Comment by gravityrail** [comment]
Merged to branch 4.2

**Comment by jeherve** [comment]
👍  @gravityrail Will we experience similar issues with the other constructors that were removed? https://github.com/Automattic/jetpack/pull/4268/files

**Comment by gravityrail** [comment]
@jeherve not as far as I can tell. The other constructors are all invoked using `new`

**Pull request merged**
