### PR TITLE
scssphp: Upgrade from 0.0.9 to 0.0.12

### PR DESCRIPTION
**Pull request by mreishus**
## Proposed changes:

* scssphp: Upgrade from 0.0.9 to 0.0.12
* See: https://leafo.net/scssphp/
* I wanted to do a pass on this file for PHP 8 compatibility, but before we do that, seems best to upgrade to the latest version of the abandoned library.

Previous upgrades at 58cac3f9bf6 , ff332d939 and initial commit is fd0e1b66753 

### Steps I took

* Downloaded the newest version of the library from https://leafo.net/scssphp/ and pasted over our file. 
* Ported 5d4d52ab2 / #23844 (phpcs: disable comment)
* Ported 299a659c2e1 / #24135 (isset() ? check)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Copy to sandbox
```
scp ./projects/plugins/jetpack/modules/custom-css/custom-css/preprocessors/scss.inc.php wpcom-sandbox:public_html/./wp-content/mu-plugins/jetpack-plugin/sun/modules/custom-css/custom-css/preprocessors/scss.inc.php
scp ./projects/plugins/jetpack/modules/custom-css/custom-css/preprocessors/scss.inc.php wpcom-sandbox:public_html/./wp-content/mu-plugins/jetpack-plugin/moon/modules/custom-css/custom-css/preprocessors/scss.inc.php
```
* Have a simple site with personal plan or better
* Go to customizer -> additional css
* Add this css
```
// Variables
$primary-bg-color: #f4f4f4;
$secondary-bg-color: #4CAF50;
$text-color: #333;

// Mixin for text styling
@mixin text-styling($size, $color: $text-color) {
  font-size: $size;
  color: $color;
}

// Global styles to check if SCSS is working
body {
  background-color: $primary-bg-color;
  @include text-styling(16px);
}

h1 {
  @include text-styling(36px, #ff0000);
}

// Nested Rules
.container {
  width: 100%;
  padding: 15px;
  background-color: $secondary-bg-color;
  @include text-styling(18px, white);

  .box {
    width: 50%;
    margin: 10px auto;
    padding: 10px;
    background-color: white;
    border: 1px solid $secondary-bg-color;

    h2 {
      @include text-styling(24px, $secondary-bg-color);
    }
  }
}
```
* Change preprocessor to SCSS
* Save
* The site should now have a gray background with large text

### CODE REVIEW

**Comment by mreishus** [comment]
@jeherve , do you know who might be good to review this?

**Review by jeherve — APPROVED** [review]
This looks good and tests well for me. An update is definitely needed, it generates quite a few deprecation notices on PHP 8+ :(

**Comment by mreishus** [comment]
Thanks. PR for rector updates here: #33868

**Comment by anomiex** [comment]
Looks like you got version 0.0.12 as "latest" from https://leafo.net/scssphp/ that's linked in the source? However, I note that that page also says you can get the latest version from https://github.com/leafo/scssphp/, which has version 0.8.4 available. And it also notes that it has been moved to https://github.com/scssphp/scssphp, which has version 1.11.1.

Which, for that matter, we might pull in via Composer from https://packagist.org/packages/scssphp/scssphp instead of copy-pasting it, as the 1.x series appears to still be maintaining compatibility with PHP 5.6.

**Pull request merged**
