### PR TITLE
Slideshow: Use gallery's images `size` if exists.

### PR DESCRIPTION
**Pull request by odie2**
Allow to display images in custom size as set in [gallery] tag - usable when using custom image size that was specially cropped and CSS is not enought to display in requested size.

### CODE REVIEW

**Comment by odie2** [comment]
But what `e280eca` is doing here? :/

**Comment by jeherve** [comment]
> But what e280eca is doing here? :/

Your version of master is probably a bit messed up.

It might be worth updating to the latest version of master first, and then creating a new branch where you'll cherry-pick 99d2f7411b6964042809859998da362552418c6c only.

**Comment by odie2** [comment]
@jeherve
I have completely no idea with creating multiple pull requests.
I used only to repositories on master branch only or single GitHub's pull requests.
I am choosing cherry-pick option and it doing something, but I see no changes.
I did only bigger mess in my fork...

So if you are able to "fix" it, please do it.

image

**Comment by jeherve** [comment]
Closing in favor of #2202

**Pull request closed without merging**
