### PR TITLE
Gathering Tweetstorms: Show a spinner while the thread is loading.

### PR DESCRIPTION
**Pull request by pento**
This PR shows a spinner over the "Unroll" button after it's clicked, while the twitter thread is loading.

#### Changes proposed in this Pull Request:
* Add a loading spinner to the twitter thread loader.

#### Jetpack product discussion
p58i-98G-p2#comment-46742

#### Does this pull request change what data or activity we track or use?
No changes.

#### Testing instructions:

* Embed a tweet in a post.
* Click the "Unroll" button.

#### Proposed changelog entry for your changes:
* None needed.

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
This tests well for me in Chrome, Firefox, Safari and Edge on Mac.

In IE11 on Windows 10 however the unroll button does not show.

MissingUnrollButton

**Comment by aaronrobertshaw** [comment]
I've reported the IE11 button missing as a separate issue: https://github.com/Automattic/jetpack/issues/16371

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.7` in 184c2035dc69b1a5d1142b1d8cf0f02a552c58b4

**Comment by jeherve** [comment]
r210093-wpcom

**Pull request merged**
