### PR TITLE
Add Mapkit to Maps block

### LINKED ISSUE #73641: Create token endpoint
Create a token endpoint to get a Mapkit JWT.

Documentation: https://developer.apple.com/documentation/mapkitjs/creating_and_using_tokens_with_mapkit_js

We should sign the token with the HTTP referrer domain, to avoid warnings in the console.

### LINKED ISSUE #73645: Change map.php / view.js to show Mapkit on WPCOM
- Show Mapkit on the frontend on WPCOM sites
- Make sure looks & behaves the same
- Fallback for black&white & terrain map styles: use default
- Make it pluggable, it should be "easy" to add other map providers

### PR DESCRIPTION
**Pull request by TimBroddin**
## Proposed changes:

This PR brings support to use Mapkit as a map provider in the Map block. This has been quite an endeavor, and this PR served as the feature branch, where all PR's listed below were merged. Now it needs a final review, before being released.

| PR | URL | Status |
|---|------|--------|
| Add util functions to convert from/between Mapbox zoom levels & Mapkit camera distance | https://github.com/Automattic/jetpack/pull/29092 | 🟢 |
| Endpoint for Mapkit JWT signing | D101694-code | 🟢 | 
| Add Mapkit secret key constants | D103086-code | 🟢 | 
| Maps block: render Apple Maps maps on WP.com frontend | https://github.com/Automattic/jetpack/pull/29089 | 🟢 |
| Add getMapProvider function | https://github.com/Automattic/jetpack/pull/29116 | 🟢 |
| Add support for Mapkit geocoding | https://github.com/Automattic/jetpack/pull/29120 | 🟢 |
| Introduce useMapkitSetup hook | https://github.com/Automattic/jetpack/pull/29144 | 🟢 | 
| Add Mapkit support in the editor | https://github.com/Automattic/jetpack/pull/29252 | 🟢  |
| Only load Mapkit library block once per page | https://github.com/Automattic/jetpack/pull/29301 | 🟢 |
| Don't show Mapbox token input when map provider is Mapkit | https://github.com/Automattic/jetpack/pull/29306 | 🟢 |
| Only show specific controls when mapprovider is mapbox | https://github.com/Automattic/jetpack/pull/29333 | 🟢 |
| Round zoom value in block properties | https://github.com/Automattic/jetpack/pull/29334 |  🟢 |
| Recenter map after closing a marker info window | https://github.com/Automattic/jetpack/pull/29338 | 🟢 |
| Catch Mapkit API request failures & show error | https://github.com/Automattic/jetpack/pull/29356 | 🟢 |
| Move logic to getMapProvider | https://github.com/Automattic/jetpack/pull/29382 | 🟢 |
| Geocode address parameters in Mapkit | https://github.com/Automattic/jetpack/pull/29394 | 🟢 |
| Default to the default mapCenter defined in settings.js| https://github.com/Automattic/jetpack/pull/29385 | 🟢   |

CleanShot 2023-04-20 at 12 56 19@2x

### Mapping provider

We'll only use Mapkit (Apple Maps) as a map provider on WPCOM Simple & Atomic sites. To determine which map provider is used, these steps are taken:

1. If the map style is terrain: use Mapbox
2. If a cookie called `map_provider` is set: use the value in the cookie (`mapbox` | `mapkit`)
3. If we still don't have a map provider:
    - On the post/page view: call `apply_filters( 'wpcom_map_block_map_provider', 'mapbox' );`. This will return whatever the filter returns on WPCOM, and fallback to the provided value mapbox on self-hosted JP sites.
    - In the editor: read the value of `window.map_block_map_provider`. This global variable is injected by [ETK](https://github.com/Automattic/wp-calypso/pull/75968). If it isn't present, fallback to Mapbox.

This approach will allow us to have the code already on WPCOM Simple & Atomic, and flip the switch later (by makeing a diff to WPCOM and a PR WPCOMSH).

### Functionality

The Mapkit integration offers the same functionality as Mapbox, except for:

- There's no option to show the map full-screen.
- There's no option to hide the street names.
- The `Black & White `style maps to Mapkit's `MutedStandard` style, which has some color.
- Mapkit doesn't offer the `Terrain` style, so when selecting that Mapbox will be used.

Other subtle differences:

- Mapkit's zoom & Mapbox's zoom levels don't map 100%. But it's pretty close.
- Mapkit uses its own geocoder when searching for addresses.

### Testing instructions

As can be seen in the overview above, (almost) all the changes have already been tested by Team Apex (and some by the Jetpack team) before being merged to this feature branch. 

The more eyes the better, so feel free to add a Map, add some points, see if everything behaves like it should, both when using Mapkit & Mapbox.

The easiest way to test is:

1. Run `bin/jetpack-downloader test jetpack add/map-block-mapkit` on your sandbox
2. Add this to `0-sandbox.php`:

```php
function wpcom_map_block_map_provider_mapkit() {
	return 'mapkit';
}

add_filter( 'wpcom_map_block_map_provider', 'wpcom_map_block_map_provider_mapkit', 20, 0 );
```
3. Thoroughly test the map block

Alternatively, you can test this on a self-hosted or JT site, by setting the cookie:

`document.cookie = 'map_provider=mapkit'`

When testing this on a JT or self-hosted site, make sure it's connected to Jetpack, otherwise the blog_id will be empty, and the call to fetch the API key will not work.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pdDOJh-1tR-p2
## Does this pull request change what data or activity we track or use?
No

Fixes https://github.com/Automattic/wp-calypso/issues/73645, fixes https://github.com/Automattic/wp-calypso/issues/73641

### CODE REVIEW

**Review by yansern — DISMISSED** [review]

**Comment by TimBroddin** [comment]
@jeherve does this require another review from the Jetpack crew? Or can I merge this in?

**Review by yansern — DISMISSED** [review]

**Comment by jeherve** [comment]
> @jeherve does this require another review from the Jetpack crew? Or can I merge this in?

That's up to you. If you're confident about your code, in all three platforms (Simple, WoA, self-hosted), you can merge right away. If you'd like an extra review, you can add a "Needs Review'" label, we'll be happy to take a look! I'm AFK today, but can take a look on Monday unless someone else from Crew beats me to it!

Either way, I would recommend adding the "Needs testing" label, so this can be properly tested during the monthly testing call.

**Comment by TimBroddin** [comment]
Thanks for the input! I'll do one final test on all three platforms.

**Comment by TimBroddin** [comment]
@jeherve one more question: since Mapkit will only be used on WP.com Simple & Atomic, does this also need to hit trunk before the code freeze? We'd like to flip the switch next Tuesday, so I guess it's best to get this in before tomorrow?

I tested on all self hosted, Atomic & Simple and found (and fixed) one issue where the Mapkit API token could not be retrieved when your Atomic site is private. Other than that, all seems fine. I added the `[Needs review]` label because Yan is AFK, and it would be comfortable to have one more glance on this, since Jetpack development still feels very new to me 🙏

**Comment by zinigor** [comment]
If you wish to do more work on this PR, you can also wait for the next weekly - if this code doesn't make it in `trunk` now, we'll still get it out next week whenever the weekly is deployed. It usually happens around Tuesday/Wednesday based on testing results.

**Comment by TimBroddin** [comment]
> If you wish to do more work on this PR, you can also wait for the next weekly - if this code doesn't make it in `trunk` now, we'll still get it out next week whenever the weekly is deployed. It usually happens around Tuesday/Wednesday based on testing results.

Since [a couple of small changes](https://github.com/Automattic/wp-calypso/pull/75968) are still needed, that might be the best way forward.

**Review by jeherve — DISMISSED** [review]
This tests well for me. I like the look of the tiles a lot better, personally, and the maps seem just as accurate, no complaints there. I left a few notes below, but I think this can be addressed in follow-up PRs.

*********

> In the editor: read the value of window.map_block_map_provider. This global variable is injected by https://github.com/Automattic/wp-calypso/pull/75968. If it isn't present, fallback to Mapbox.

Was there a specific reason to go with ETK here? Couldn't we have used jetpack-mu-wpcom instead, or even Jetpack directly, to keep everything in one place and easier to debug?

*********

> Other subtle differences:

The zooming behavior seems a bit different. When switching from an existing Mapbox map to Mapkit, the scroll to zoom setting doesn't seem respected. I have to apply the scroll to zoom toggle again and save my changes to be able to scroll to zoom on the frontend.

*********

I also noticed that when editing a post with an existing map on it, I cannot focus on the map block properly. Clicking on the block doesn't bring its sidebar like with any other block like the old Map block. I think it may prove confusing for some. Only when you click on the marker itself, then on the marker elements, can you access the map block options.

Sometimes I couldn't focus on the block at all, no matter where I clicked. I had to reload the editor to make things work.

*********

Since Mapkit includes an option to change the type of tile in the top right corner, I wonder if the styles should be worded differently in the block sidebar. Should they maybe say "Default styles" for example, instead of just Styles, since the site visitor can update them at any time?

*********

I noticed that the style previews appearing when you move your mouse hover each style in the block sidebar were the same for both providers.

**Comment by TimBroddin** [comment]
Hey @jeherve, could you reapprove please? I only changed the name of the global variable.

Currently looking into why the E2E tests still keep failing 🤔

**Review by jeherve — APPROVED** [review]
Approving again. One other thing I've noticed: when you change the zoom level then change the color of a marker, it also resets the zoom level on the map (but not on the map settings).

**Comment by jeherve** [comment]
> Currently looking into why the E2E tests still keep failing 🤔

I'll take a look as well. It would seem that #30297 fixed one test only.

**Comment by TimBroddin** [comment]
> Approving again. One other thing I've noticed: when you change the zoom level then change the color of a marker, it also resets the zoom level on the map (but not on the map settings).

Nice catch. I'm going to create issues for all things you've listed above, and will create follow-up PR's for them.

**Pull request merged**
