### PR TITLE
CRM: Resolves 2889 and 2972 - fixes overescaped HTML

### PR DESCRIPTION
**Pull request by tbradsha**
Fixes 2889 and 2972, which both dealt with over-escaped HTML.

When doing our XSS/security sweep, we accidentally escaped some strings that purposefully had HTML in them. In the first case (bulk-adding tags) I adjusted the string to use `wp_kses()`, simplified the logic so we weren't manually building a JS object, and reworded things a touch. 

In the other issue (a `<br>` in a settings description) I just removed the tag.

Note that I started doing extra linting in one function, but held off on the rest.

## Testing instructions

1. On an install that has some quotes but no quote tags, go here: `/wp-admin/admin.php?page=manage-quotes`
2. Select multiple quotes in the list view.
3. In the Bulk Actions dropdown, select "Add tags".

In `trunk`, one sees some HTML instead of a link to add tags:
image

In the `fix/crm/2889_and_2972_unescape_html` branch one sees this:
image

4. Go here: `/wp-admin/admin.php?page=zerobscrm-plugin-settings&tab=mail`

In `trunk` one sees a stray `<br/>`:
image

In `fix/crm/2889_and_2972_unescape_html` the tag is removed (and quotes are added to example email name):
image

## Does this pull request change what data or activity we track or use?
No

### CODE REVIEW

**Review by cleacos — CHANGES_REQUESTED** [review]
I tested it, and it works as expected. The issue is fixed. 

But the linter is complaining a bit.

**Comment by tbradsha** [comment]
> But the linter is complaining a bit.

It's complaining about lines surrounding the fix that I started to lint. I stopped making changes because I was told to only lint the lines directly being worked on.

Your wish is my command; the file should be fully linted now. ;^)

**Comment by tbradsha** [comment]
Since there are no more linting errors in `includes/ZeroBSCRM.List.Views.php`, I got another error until I removed the file from the exclude list: 35633c7

**Comment by cleacos** [comment]
> It's complaining about lines surrounding the fix that I started to lint. I stopped making changes because I was told to only lint the lines directly being worked on.

Yes, it only complains about the lines being modified and lines near in case of indentation issues. You didn't have to reformat the whole file. Thank you 🙂

**Review by cleacos — APPROVED** [review]
I tested it again. It works as expected. Also, I did a smoke test through the list views since the file was modified and had no issues...

LGTM!

**Pull request merged**
