### PR TITLE
Admin Page: Feature Settings Add better docs for feature settings-related components

### PR DESCRIPTION
**Pull request by oskosk**
#### Changes proposed in this Pull Request:
- Adds a `README.md` file, inline docs and cleans up deprecated methods
#### Testing instructions
1. Take a look at `components/module-settings/README.md` and check if it's fine.

### CODE REVIEW

**Comment by jeherve** [comment]
@oskosk Are you still working on this?

**Comment by oskosk** [comment]
@jeherve , I'm on it

**Comment by dereksmart** [comment]
@zinigor can you please review this and see if it's still relevant after the refactor to settings?

**Comment by zinigor** [comment]
It's going to be a little (or a lot) different after we integrate new settings, so right now this can be punted for a while.

**Comment by dereksmart** [comment]
Since new settings didn't go in, this is still relevant for now.  We just need to make sure to update this along with the UI cc @zinigor

**Pull request merged**
