### PR TITLE
Sync: Fix `enqueue_all_ids_as_action` logic

### PR DESCRIPTION
**Pull request by lezama**
Fix an error on the logic when `$max_items_to_enqueue` == `$items_per_page` / `self::ARRAY_CHUNK_SIZE`.

cc @enejb

### CODE REVIEW

**Comment by enejb** [comment]
I don't think this needs a change log since this is already just a fix to https://github.com/Automattic/jetpack/pull/5348

**Comment by enejb** [comment]
cc @gravityrail Does the above make sense to you?

**Comment by enejb** [comment]
This fixed the issue that I have.

**Comment by gravityrail** [comment]
LGTM!

**Pull request merged**
