### PR TITLE
Fix video block aspect-ratio in frontend

### LINKED ISSUE #17465: Video Block: video does not resize when inside a column block
### Steps to reproduce

1. Add a column block to the page.
2. Inside of this column block add a video block.

#### What I expected
I expected the video block to resize to the width of the column.

#### What happened instead
The video block is cutting off the video and displaying full height.

#### Browser / OS version
Firefox/Mac OS Catalina

#### Screenshot / Video
video_block

#### Context / Source
3021461-zen

### PR DESCRIPTION
**Pull request by cpapazoglou**
Fixes #17465

#### Changes proposed in this Pull Request:

* Provide the same set of classNames set in the editor to the save function so that block behaves the same in the frontend

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Apply D51151-code
* Go to your sandbox
* Edit a page / post
* Add a 30/30/30 columns block
* Add a video to 1 column
* **Save the post and visit the frontend**
* Video should get full width of the current column
* Height should be adjusted according to the aspect ratio of the original video

Repeat the above for the following themes:
- Varia
- Altofocus
- TwentyTwenty

Especially Altofocus and TwentyTwenty (as also other themes supporting `jetpack-responsive-videos`) handle the embeds height / width with javascript, thus resulting:
1) overriding the css styles
2) better adjusting cause we do not rely on just a bunch of set aspect ratios 
https://github.com/Automattic/jetpack/blob/324cd99629ef2e57a84f1a974085b892004a3434/extensions/blocks/videopress/constants.js#L1-L11

Before | After
-------|------
 | 

#### Proposed changelog entry for your changes:

* Fixes the video block aspect ratio in the frontend (for themes not supporting it)

### CODE REVIEW

**Comment by mreishus** [comment]
D51151-code is failing to apply, so I merged master into this branch to pull in the latest updates and force the patch regeneration.

**Review by mreishus — APPROVED** [review]
Tried the themes listed plus hever: Video filled the column width and height was appropriate for the video.  Also checked in calypso's preview -> phone feature and the videos looked good as well (didn't take screenshot of these).

**Comment by cpapazoglou** [comment]
> [D51151-code](https://href.li/?D51151-code) is failing to apply, so I merged master into this branch to pull in the latest updates and force the patch regeneration.

Thanks @mreishus ! Since the files that fail to apply the patch on  (usually) are the generated ones, I just `arc diff --update  D51151` after reset, up, patch.

@jeherve it seems that some checks fail:
- Travis CI - Pull Request 
- wpcom

are there any suggestions for them?

**Review by jeherve — APPROVED** [review]
This tests well for me. It should be good to merge once the tests pass. 

> it seems that some checks fail:
>
> Travis CI - Pull Request

I've restarted it.

> wpcom

This is a Fusion glitch, that sometimes fails to report back the status of the diff in Phabricator. I applied the status manually.

**Comment by cpapazoglou** [comment]
Deployed r215261-wpcom

**Pull request merged**
