### PR TITLE
RNA: Use `Button` at `ActionButton`

### PR DESCRIPTION
**Pull request by renatoagds**
This PR updates the `<ActionButton />` using the RNA `<Button />` component.

Part of https://github.com/Automattic/jetpack/issues/23708

#### Changes proposed in this Pull Request:

* JS Components: Use RNA button for ActionButton component

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

### `<ActionButton />`
* Use Storybook
* Go to ActionButton story
* Check how the component behaves when changing its props values via the Controls panel

https://user-images.githubusercontent.com/77539/163185479-34a6a067-2570-4b2b-a137-db14ba49ef92.mov

### CODE REVIEW

**Comment by oskosk** [comment]
Pushed 94d2c03437a617378278f9288cb4e3925e8b8087 importing the `React` type

**Comment by oskosk** [comment]
Pushed a73a5231d7a6d778057d85d30a6a52822aee8476 reverting https://github.com/Automattic/jetpack/commit/94d2c03437a617378278f9288cb4e3925e8b8087 cause everything broke. The file needs to be have tsx extension or we should just drop the type declaration in the function doc

**Comment by oskosk** [comment]
The changes here are breaking some e2e tests trying to target an element in this way `.jp-connection__connect-screen .jp-action-button--button`. 

`.jp-action-button--button` is being removed in this PR in favor of a css module way. 

For deciding how to continue, let's also consider these occurrences of the `.jp-action-button--button` class
```
tools/e2e-commons/pages/wp-admin/jetpack.js
13:		const connectButtonSelector = '.jp-connection__connect-screen .jp-action-button--button';
22:		const buttonSelector = '.jp-connection__connect-screen button.jp-action-button--button';

projects/plugins/boost/app/assets/src/js/pages/purchase-success/PurchaseSuccess.svelte
43:					className="jp-action-button--button jb-button jb-button--primary mt-3"

projects/plugins/jetpack/_inc/client/components/contextualized-connection/style.scss
54:	& .jp-action-button--button.is-primary,

projects/js-packages/connection/components/connect-screen/required-plan/style.scss
28:		.jp-action-button--button.components-button  {
50:		.jp-action-button--button.components-button {
```

**Review by dhasilva — COMMENTED** [review]
The `loading` states are different. Is that the intended UI?

Button | ActionButton
---------|---------
Screenshot_2022-09-12_19-26-01 | Screenshot_2022-09-12_19-26-14

**Comment by renatoagds** [comment]
@dhasilva This happens because `ActionButton` set `disabled` together with `isLoading`

**Review by dhasilva — DISMISSED** [review]
LGTM :rocket:

**Review by samiff — APPROVED** [review]

**Comment by renatoagds** [comment]
r252900-wpcom

**Pull request merged**
