### PR TITLE
WhatsApp Block: Add alignment controls

### LINKED ISSUE #16660: Whatsapp block lacks alignment options
#### Is your feature request related to a problem? Please describe.

The "Send a Message" block (Whatsapp block) does not support "alignment" in its toolbar.

#### Describe the solution you'd like

The "center", "left" and "right" options should be added there.
Screen Shot on 2020-07-31 at 11:52:13

#### Additional context
This block works essentially like a button. It should share as much as the button block UI interface as possible.

### PR DESCRIPTION
**Pull request by apeatling**
#### Changes proposed in this Pull Request:

* Add WhatsApp button alignment controls to provide better support for including this button in block patterns.

Fixes #16660

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Insert a WhatsApp Button block in a post or page
* Change the alignment
* Confirm this works in the editor and in the front end.

#### Proposed changelog entry for your changes:

* Add ability to change the alignment of the WhatsApp button.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
When I tested there is a `float: right` which overrides the the `justify-content: flex-end;` for right aligned which causes alignment to differ slightly in editor and front end if followed by  text:

Editor:
Screen Shot 2020-09-30 at 3 43 27 PM

Frontend:
Screen Shot 2020-09-30 at 3 43 40 PM

Could be fixed by adding a `float: none;` along with `justify-content: flex-end;` but not sure what the expected behaviour is with align right, ie.  is it the expectation that it will float next to following blocks?

**Comment by apeatling** [comment]
I'm not sure, but I'll stop the floats and then let's see what kind of feedback we get from users and the design team.

**Comment by apeatling** [comment]
This one is good for a review :+1:

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by jeherve** [comment]
r216550-wpcom

**Pull request merged**
