### PR TITLE
Feature/widget conditions extra hooks (second time lucky)

### PR DESCRIPTION
**Pull request by simonwheatley**
See previous Pull Request: https://github.com/Automattic/jetpack/pull/167 (I got too far your repo with my delay, and a new branch/PR was the quickest cleanest way to catch up)

Copy paste of #167 follows:

These hooks would allow us to add in more type conditions to Widget Visibility, save them, and process them on the front end.

Here's the addition of a "type" control:

Here's the code to add it:

``` php
/**
 * 
 * 
 * @package 
 **/
class Widget_Visibility_Types {

    /**
     * Singleton stuff.
     * 
     * @access @static
     * 
     * @return Widget_Visibility_Types object
     */
    static public function init() {
        static $instance = false;

        if ( ! $instance )
            $instance = new Widget_Visibility_Types;

        return $instance;

    }

    /**
     * Class constructor
     *
     * @return null
     */
    public function __construct() {
        add_action( 'widget_conditions_before_admin_form', array( $this, 'action_widget_conditions_before_admin_form' ), 10, 3 );
        add_filter( 'widget_conditions_condition_result', array( $this, 'filter_widget_conditions_condition_result' ), 10, 2 );
        add_filter( 'widget_conditions_update', array( $this, 'filter_widget_conditions_update' ), 10, 4 );
    }

    // HOOKS
    // =====

    /**
     * Hooks the Widget Conditions action widget_conditions_before_admin_form
     * Adds the additional type condition UI.
     *
     * @action widget_conditions_before_admin_form
     * 
     * @param array $instance
     * @param $return not used
     * @param $widget not used
     *
     * @return void
     * @author Simon Wheatley
     **/
    public function action_widget_conditions_before_admin_form( $instance, $return, $widget ) {
        $type = '';
        if ( isset( $instance['conditions']['type'] ) )
            $type = $instance['conditions']['type'];

        ?>
        <div class="condition">
            <div class="alignleft">
                <select class="conditions-rule-type" name="conditions[type]">
                    <option value="" <?php selected( "", $type ); ?>><?php echo esc_html_x( 'on any type (i.e. everywhere)', 'Used as the default option in a dropdown list', 'jetpack' ); ?></option>
                    <option value="is_front_page" <?php selected( "is_front_page", $type ); ?>><?php esc_html_e( 'on the front page only', 'jetpack' ); ?></option>
                    <option value="is_home" <?php selected( "is_home", $type ); ?>><?php esc_html_e( 'on the news page only', 'jetpack' ); ?></option>
                    <option value="is_archive" <?php selected( "is_archive", $type ); ?>><?php esc_html_e( 'on an archive page only', 'jetpack' ); ?></option>
                    <option value="is_singular" <?php selected( "is_singular", $type ); ?>><?php esc_html_e( 'on single posts (or pages, etc) only', 'jetpack' ); ?></option>
                </select>
            </div>
            <span class="condition-conjunction"><?php echo esc_html_x( 'and', 'Shown between widget visibility conditions.', 'jetpack' ); ?></span>
            <br class="clear" />
        </div><!-- .condition -->
        <?php
    }

    /**
     * Hooks the Widget Conditions filter widget_conditions_update
     * Save the type condition on the widget instance
     *
     * @filter widget_conditions_update
     * 
     * @param array $conditions The current widget conditions, to be returned
     * @param array $instance The current widget settings instance
     * @param array $new_instance The new widget settings as was
     * @param array $old_instance The old widget settings as were
     *
     * @return void
     * @author Simon Wheatley
     **/
    public function filter_widget_conditions_update( $conditions, $instance, $new_instance, $old_instance ) {

        $conditions['type'] = '';

        if ( isset( $_POST['conditions']['type'] ) ) {
            $conditions['type'] = $_POST['conditions']['type'];
            $conditions[ 'active' ] = true;
        }

        return $conditions;
    }

    /**
     * Hooks the Widget Conditions filter widget_conditions_before_admin_form
     * Checks the additional `type` condition allows widget display.
     *
     * @filter widget_conditions_condition_result
     * 
     * @param bool $condition_result Whether to show the widget
     * @param array $instance The widget settings for this instance
     *
     * @return void
     * @author Simon Wheatley
     **/
    public function filter_widget_conditions_condition_result( $condition_result, $instance ) {

        if ( $instance['conditions']['type'] ) {
            switch ( $instance['conditions']['type'] ) {
                case 'is_front_page':
                    $condition_result = is_front_page();
                break;
                case 'is_singular':
                    $condition_result = is_singular();
                break;
                case 'is_home':
                    $condition_result = is_home();
                break;
                case 'is_archive':
                    $condition_result = is_archive();
                break;
            }
        }

        return $condition_result;
    }

}


// Initiate the singleton
Widget_Visibility_Types::init();
```

### CODE REVIEW

**Comment by paulschreiber** [comment]
@jeherve This sounds great. Anything I can help with?

**Comment by jeherve** [comment]
@paulschreiber This is planned for our next Widget Visibility iteration, but we don't have an ETA yet.

Until then, do not hesitate to look at the conversation above, test things, and give us your opinion here!

Thanks!

**Comment by paulschreiber** [comment]
@jeherve Is he patch above good? Does it need work? Should I try another approach and submit a new PR?

**Comment by jeherve** [comment]
@paulschreiber I'll defer to @cfinke, who had some ideas earlier, and who could give us some insights.

**Comment by paulschreiber** [comment]
@cfinke?

**Comment by jeherve** [comment]
> It's a rewrite of how the conditions are implemented, allowing new major conditions to be added by plugins as well as allowing plugins to add/modify/remove minor conditions on any of the existing sets.

Now implemented in #3444. We'd consequently need to merge #3444 before to deal with this PR.

**Comment by jeherve** [comment]
#5781

**Comment by samhotchkiss** [comment]
@georgestephanis -- can you take a look at this?

**Comment by georgestephanis** [comment]
Yup.

**Comment by georgestephanis** [comment]
Honestly, I think this would have been merged a long time ago if https://github.com/Automattic/jetpack/pull/434/commits/9dec564769d6b0bd530a3b702ed61526372ca648 wasn't in the PR -- all that code style changes, while good, significantly complicates the PR.

I'm going to throw a new PR together instead that is without the style changes instead.

**Comment by paulschreiber** [comment]
What's the problem with the code style changes? We don't want another `goto fail`. This seems like a good opportunity to clean something up. Adding ?w=1 makes the diff very small. I'd go firther and change the `else if`s to `elseif`s.

**Comment by georgestephanis** [comment]
@paulschreiber I'm not saying that the code style improvements shouldn't be done, merely that a pull request aiming to do something else probably isn't the best place in which to implement broad style tweaks.

**Comment by paulschreiber** [comment]
Would a style-fixes only PR be approved? If so, I’m happy to run PHPBCF on the project. My worry is that would cause a lot of merge conflicts.

**Comment by georgestephanis** [comment]
Closing this out in favor of #6371 -- it's something we want, but implementation is still up in the air, and the underlying architecture has changed significantly in the interim.

**Pull request closed without merging**
