### PR TITLE
WIP Settings: Add the wpcom_admin_interface field to the reponse

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes #

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by arthur791004** [comment]
Hmmm...it's weird that the option cannot be updated on my site 🤔

**Comment by fushar** [comment]
> Hmmm...it's weird that the option cannot be updated on my site 🤔

I think this is related to: p1709294641757219/1709283860.021329-slack-CRWCHQGUB. Somehow that option is synced between wpcom <-> Atomic in a different way that the other options.

**Comment by arthur791004** [comment]
Yep. It's related to the persistent data, PfsEZG-X-p2. We made the `wpcom_admin_interface` a persistent data so we cannot use a normal way to update it.

**Comment by arthur791004** [comment]
Closing it as it's not planned. We can come back to this solution if needed.

**Pull request closed without merging**
