### PR TITLE
Config Package: Allow for enabling post_list package

### PR DESCRIPTION
**Pull request by allilevine**
Fixes https://github.com/Automattic/jetpack/issues/21102
Part of #20941

#### Changes proposed in this Pull Request:

* Allows for enabling the post_list package following these steps: https://github.com/Automattic/jetpack/tree/master/projects/packages/config
* The post_list package was added here: https://github.com/Automattic/jetpack/pull/20720

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* Follow[ the "Usage" instructions](https://github.com/Automattic/jetpack/tree/master/projects/packages/config#usage):
    * Require both the config and post_list packages:
        `cd projects/plugins/jetpack && composer require automattic/jetpack-post-list`
        `composer require automattic/jetpack-config` 
    * Install the monorepo:
        `pnpm install`
        `jetpack install -r && jetpack install --all`
    * Initialize the configuration package with the post_list slug:
        Create a file named 0-functions.php in the tools/docker/mu-plugins/ directory and add:
```
use Automattic/Jetpack/Config;

// Configuring Jetpack as early as plugins_loaded priority 1
// to make sure every action handler gets properly set.
add_action( 'plugins_loaded', 'configure_jetpack', 1 );

function configure_jetpack() {
    $config = new Config();
    $config->ensure( 'post_list' );
}
```

* Build and start the docker env:
        `jetpack build packages/post-list`
        `jetpack docker up`
* Go to http://localhost/wp-admin/edit.php (the post list) and check that the post thumbnails appear.

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
I'm trying to add the package to the Jetpack plugin, adding a new item into this [packages list](https://github.com/Automattic/jetpack/blob/c7adc871c064744a56a57583a5f210f46e60a5dc/projects/plugins/jetpack/class.jetpack.php#L828-L829), something like the following:

```php
foreach (
	array(
		'sync',
		'jitm',
		'post_list',
	)
	as $feature
) {
	$config->ensure( $feature );
}
```

However, for some reason, getting this notice:

```
[16-Sep-2021 10:09:04 UTC] PHP Notice:  Unable to load class Automattic\Jetpack\Post_List.
Please add the package that contains it using composer and make sure you are requiring the Jetpack autoloader
in /usr/local/src/jetpack-monorepo/projects/packages/config/src/class-config.php on line 129
```

`composer.json` and `composer.lock` are updated into the Jetpack plugin folder, too.

**Comment by allilevine** [comment]
> However, for some reason, getting this notice:
> 
> ```
> [16-Sep-2021 10:09:04 UTC] PHP Notice:  Unable to load class Automattic\Jetpack\Post_List.
> Please add the package that contains it using composer and make sure you are requiring the Jetpack autoloader
> in /usr/local/src/jetpack-monorepo/projects/packages/config/src/class-config.php on line 129
> ```
> 
> `composer.json` and `composer.lock` are updated into the Jetpack plugin folder, too.

@retrofox Thanks for catching that! I needed to load the class as `Automattic\Jetpack\Post_List\Post_List`. I've updated the PR and the testing instructions.

**Review by retrofox — DISMISSED** [review]
LGTM.
I've tested adding the package to the Jetpack plugins adding the item into the configure method:

```php
public function configure() {
	$config = new Config();

	foreach (
		array(
			'sync',
			'jitm',
			'post_list', // <- new post list added to Jetpack plugin.
		)
		as $feature
	) {
		$config->ensure( $feature );
	}
```

The package is properly loaded and it shows the image thumbnail.



Just a couple of notes:

> Go to http://localhost/wp-admin/edit.php?post-list=true and check that the post thumbnails appear.

It seems we removed the `post-list` flag from the query string, meaning the feature will be available simply on the `http://localhost/wp-admin/edit.php` page. Is it correct?

Have we removed the no-thumb image when no thumbnail for the posts?

**Comment by allilevine** [comment]
> It seems we removed the `post-list` flag from the query string, meaning the feature will be available simply on the `http://localhost/wp-admin/edit.php` page. Is it correct?

That's correct! I removed the flag from the testing instructions.

> Have we removed the no-thumb image when no thumbnail for the posts?

Looks like it's not showing up anymore. To be addressed here: https://github.com/Automattic/jetpack/issues/20889

**Comment by retrofox** [comment]
Although we are able to merge it, I'd like to know the opinion of Jetpack folks

**Comment by retrofox** [comment]
> Although we are able to merge it, I'd like to know the opinion of Jetpack folks

@kraftbj @jeherve

**Review by jeherve — APPROVED** [review]

**Comment by pablinos** [comment]
> > It seems we removed the post-list flag from the query string, meaning the feature will be available simply on the http://localhost/wp-admin/edit.php page. Is it correct?
> That's correct! I removed the flag from the testing instructions.

Yes, the idea is that the decision of whether to load the package or not should be made by the plugin or wherever it's being used. If we didn't want to load it then we would not include the `post-list` slug in the packages passed to the `ensure` method.

**Pull request merged**
