### PR TITLE
Carousel: Add filter to disable stats collection

### LINKED ISSUE #3356: Stats + Carousel: Record individual image hits
On WordPress.com, page hits are recorded for each image viewed full-screen in the Carousel. In Jetpack, we do not collect that.

Enhancement: Collect these stats :)

Requested in 2509419-t

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #3356 

Adds a filter to allow site owners to disable Jetpack collection stats for carousel views.

### CODE REVIEW

**Comment by jeherve** [comment]
Should we shortcut the whole stats code earlier, maybe, before all the other checks?

**Comment by kraftbj** [comment]
Yeah, i started it thinking there could be more to the filter, but didn't do it. :) I can make the change pending the conversation on 3356 re default state.

**Comment by kraftbj** [comment]
@jeherve Reworked it to default false per @jonathansadowski's opinion and moved it to kill early.

**Comment by jeherve** [comment]
Looks good to me! 👍  🚢

**Pull request merged**
