### PR TITLE
Block fixtures: trim block fixture HTML when generating fixtures

### PR DESCRIPTION
**Pull request by ramonjd**
#### Changes proposed in this Pull Request:

When a new line exists at the end of a html fixture file, the parser interprets this as an empty block. 😱 

The result is an empty block object in the parsed JSON (`*.parsed.json` files).

```
   {
        "blockName": null,
        "attrs": {},
        "innerBlocks": [],
        "innerHTML": "\n",
        "innerContent": [
            "\n"
        ]
    }
```

Trimming the output string of the HTML prevents this from occurring.

#### Jetpack product discussion
None. Unit-test framework-related.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

Check out this branch.

Find existing test fixtures, e.g., 
https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/rating-star/test/fixtures/jetpack__rating-star.html

Delete the files `test/fixtures/*.json` and `test/fixtures/*.serialized.html`

Screen Shot 2021-03-16 at 11 26 34 pm

Regenerate the fixtures, e.g., `yarn fixtures:generate extensions/blocks/rating-star/test`

Check the file contents of `jetpack__rating-star.parsed.json`

There should be no empty block object:

```
    {
        "blockName": null,
        "attrs": {},
        "innerBlocks": [],
        "innerHTML": "\n",
        "innerContent": [
            "\n"
        ]
    }
```

Check that all the tests pass: `yarn fixtures:test extensions/blocks`

### CODE REVIEW

**Review by glendaviesnz — DISMISSED** [review]
LGTM

**Comment by aaronrobertshaw** [comment]
Nice. Thanks for taking care of this one 👍

**Review by jeherve — CHANGES_REQUESTED** [review]
Tests are failing at the moment I'm afraid.

**Comment by ramonjd** [comment]
> Tests are failing at the moment I'm afraid.

Ah yes, it makes sense that we'll have to regenerate all the affected fixtures, that is, those with the hanging, empty block object. 🤦 

Thank you!

**Comment by ramonjd** [comment]
Merged in master branch with the latest fixtures.

**Review by jeherve — APPROVED** [review]

**Comment by ramonjd** [comment]
r223265-wpcom

For some reason the fixtures for Eventbrite, Instagram, Map and Related posts weren't pulled in by D58791-code. I added them manually.

The remaining fixture files will be moved to WPCOM when the following PRs are deployed (to WPCOM). 

Mailchimp https://github.com/Automattic/jetpack/pull/19169 
Subscriptions https://github.com/Automattic/jetpack/pull/18993 
Button https://github.com/Automattic/jetpack/pull/19002

**Pull request merged**
