### PR TITLE
Subscribe Block: Improves "Subscribed" state in WPCOM

### PR DESCRIPTION
**Pull request by lezama**
Fixes #

## Proposed changes:

* Improves subscribe button behavior introduced in https://github.com/Automattic/jetpack/pull/33897
* See p1699026721433949-slack-C05PV073SG3

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* On a simple site check the subscribe button while logged in / logged out.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
This tests much better for me now, thanks! Approving after functional testing, but can leave for someone else to look at the code.

**Review by n3f — APPROVED** [review]
LGTM 👍 

I was able to view the "✔️ subscribed" button after being subscribed and "logged in".

**Comment by ice9js** [comment]
Cherry-picked to 12.8 in 33871aab64d74d55d316d9c297be5904db03f788.

**Comment by simison** [comment]
@ice9js why to cherry pick this for 12.8 if the [original feature update](https://github.com/Automattic/jetpack/pull/33897) we made is for 12.9? 🤔

**Comment by ice9js** [comment]
I was going through any remaining PR's with the `cherry-pick` label and `12.8` milestone which is the regular procedure for us. Is this being in 12.8 an issue?

**Comment by ice9js** [comment]
The PR you just mentioned is part of the release too, by the way. https://github.com/Automattic/jetpack-production/compare/12.8-a.11...12.8

**Comment by lezama** [comment]
Could we add https://github.com/Automattic/jetpack/pull/33973 once it gets merged 🙏? Added "Needs Cherry Pick" label.

**Comment by ice9js** [comment]
Unfortunately at this point 12.8 is out. Unless it's a critical issue/fix, I'm afraid it'll have to wait until 12.9. The code freeze for that will be on December 4th, with the release going out on the 5th.

**Comment by simison** [comment]
> The PR you just mentioned is part of the release too, by the way. https://github.com/Automattic/jetpack-production/compare/12.8-a.11...12.8

Weird, I thought [the PR](https://github.com/Automattic/jetpack/pull/33897) was merged well after the code-freeze for 12.8 and it also had "milestone" 12.9 marked, and bot's github comment was along those lines too.

There's nothing urgent here but the UX in that PR was such that you might get some feedback. https://github.com/Automattic/jetpack/pull/33973 improves on this.

**Pull request merged**
