### PR TITLE
Properly address slashes in custom CSS.

### LINKED ISSUE #3727: Custom CSS: problem stripping / replacing quotes
Steps to reproduce the issue:

1. Add the following CSS to the custom CSS editor:
```css
@import url("fineprint.css") print;
@import url("bluish.css") projection, tv;
@import 'custom.css';
@import url("chrome://communicator/skin/");
@import "common.css" screen, projection;
@import url('landscape.css') screen and (orientation:landscape);
```

2. Save your changes.
3. The following is saved in the editor:

```css
@import  '"fineprint.css' print;
@import  '"bluish.css' projection, tv;
@import  "'custom.css'";
@import  '"chrome://communicator/skin/';
@import  "common.css" screen, projection;
@import  ''landscape.css' screen and (orientation:landscape);
```

Reported here:
https://wordpress.org/support/topic/saving-stylesheet-via-css-stylesheet-editor-double-quotation-is-increased?replies=1&view=all

### PR DESCRIPTION
**Pull request by cfinke**
Fixes #3727.

In c2811e253175d8c371739c3e56e7e0d043e471e3, we (I) removed a call to `stripslashes()` that seemed to be interfering with icon fonts.  This caused problems, because other modifications to the CSS expected it to have all slashes removed -- $_POST['safecss'] will be slashed, as WordPress guarantees that, so if we don't run `stripslashes()`, then the CSS will be passed to CSSTidy with slashes in it, causing all sorts of mayhem.

However, if we just run `stripslashes()` and do nothing else, then slashes that are supposed to be in the CSS (like for icon fonts, or quotes inside of quotes) will be stripped by various core WP functions that are expecting slashed data. We pass the CSS to three core functions; `wp_insert_post()` and `wp_update_post()` expect slashed data, but `_wp_put_post_revision()` does not, so we have to account for that. (I am basing whether each expects slashed data on how they modify data that I am passing in, not on any documented slashing requirement.)

### CODE REVIEW

**Comment by cfinke** [comment]
This patch is committed and deployed on WordPress.com; I feel confident that it's ok to merge here too, but I'll wait for someone on the Jetpack team to review it.

**Comment by cfinke** [comment]
@samhotchkiss I think your bot is preventing me from removing the "Test on WP.com" label. It's live on WP.com and I've added the "Tested on WP.com" label.

**Comment by iandunn** [comment]
This is running on WordCamp.org too, so seems to be good so far. I'll leave a comment if I notice any issues.

**Comment by jeherve** [comment]
@cfinke Do we need to port r135498-wpcom as well, to avoid turning `\3434` into `\\3434`?

**Comment by iandunn** [comment]
> @cfinke Do we need to port r135498-wpcom as well, to avoid turning \3434 into \\3434?

[We ran into that slashing issue on WordCamp.org](https://wordpress.slack.com/archives/meta-wordcamp/p1464618424000597) too, and merging r135498-wpcom seems to have fixed it.

**Comment by jeherve** [comment]
@iandunn Thanks a lot for the feedback! I updated this PR to include r135498-wpcom too.

**Comment by eliorivero** [comment]
LGTM slashes are fine, they're not stripped and they're not added again.
I've rebased this branch because it had a conflict with new files created by gulp
```
css/dashboard-widget.css
css/dashboard-widget.css.map
css/dashboard-widget.min.css
css/jetpack-admin-jitm.css
css/jetpack-admin-jitm.css.map
css/jetpack-admin-jitm.min.css
```

**Comment by jeherve** [comment]
Seems to work in my tests as well. 👍

**Pull request merged**
