### PR TITLE
Instant Search: add polyfill for CustomEvent (IE11)

### LINKED ISSUE #18079: Instant Search: changing sort does not work on IE11
#### Steps to reproduce the issue

1. Using IE11, go to a site with Instant Search enabled and open the search overlay.
2. Click on any sort option other than the default option.

#### What I expected
When I choose a different sort option, the sort order should change and only the current sort should be highlighted.

#### What happened instead
When I chose a different sort option, it was highlighted, and the default sort also remained highlighted. The actual sort order of the results did not change.

Verified with Browserstack and IE virtual machine.

**Screenshots**

Screen Shot 2020-12-14 at 16 13 31

### PR DESCRIPTION
**Pull request by bluefuton**
Searching, filtering and sorting on Instant Search is currently not working in IE11 because we're creating a `new Event` as part of our query string handling. This PR adds a polyfill that fixes the problem.

Fixes https://github.com/Automattic/jetpack/issues/18079.

Screen Shot 2020-12-15 at 12 11 55

#### Changes proposed in this Pull Request:

Add a simple polyfill for `CustomEvent`. This fixes search, filter and sort behaviour on IE11.

Background on the solution:
* [Suggested fix](https://stackoverflow.com/a/26596324): "Adding CustomEvent to IE and using that instead works."
* [Polyfill on MDN](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)
* There is a [package for the polyfill](https://www.npmjs.com/package/custom-event-polyfill), but I chose not to use it because it has less concise code.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Login to Browserstack and spin up a IE11 VM.
* Navigate to your Instant Search test site and make sure you can search, filter and sort results as expected.

Screen Shot 2020-12-15 at 14 18 39

#### Proposed changelog entry for your changes:

* Instant Search: improve compatibility with IE11.

### CODE REVIEW

**Comment by bluefuton** [comment]
@jsnmoon notes that his upcoming Redux changes will remove the dependency on `Event`/`CustomEvent`.

**Review by jsnmoon — DISMISSED** [review]
Works as described 👍

**Comment by bluefuton** [comment]
Keen to get this one into the January release if possible 🚀

**Review by anomiex — DISMISSED** [review]
Code looks sane. I don't have IE11 handy to test with, so I'll trust jsnmoon's review that it works.

**Comment by bluefuton** [comment]
Shipped to wpcom in D54669.

**Comment by bluefuton** [comment]
@anomiex would you mind giving it the 👍 again please? I force-pushed to try and trigger a rebuild on the wpcom patch and now merging is blocked because your review was dismissed 🤦

**Comment by anomiex** [comment]
The JS linting test is failing now, it wants a doc comment on the added function.

**Comment by jsnmoon** [comment]
> The JS linting test is failing now, it wants a doc comment on the added function. (@anomiex)

I was under the impression that the ESLint check was optional? Also, the test was throwing a warning, not an error; should we expect all ESLint warnings to be blockers in the future?

Nonetheless, this has been fixed.

**Comment by anomiex** [comment]
The ESLint check was always required, but it formerly only failed for errors. That's also why we had GitHub complaining about "warnings in unchanged files" on every patch, the ESLint check was still issuing the 1574-ish warnings even though it didn't fail the check.

We've improved it to work more like the PHPCS checks:

* We have [a list of files known to have existing warnings](https://github.com/Automattic/jetpack/blob/ba636a62/bin/eslint-excludelist.json). These are checked for any new errors or warnings being introduced, and only those are reported by the check and both errors and warnings will make it fail.
* Any file not in that list must continue to have no errors or warnings, and again both errors and warnings will make it fail.

So, going forward, any new warnings are CI blockers. Preexisting warnings shouldn't block.

**Review by anomiex — APPROVED** [review]

**Comment by jsnmoon** [comment]
@anomiex: Got it, thanks for the explanation!

**Pull request merged**
