### PR TITLE
Extensions: drop i18n wrapper

### LINKED ISSUE #11656: Cleanup: Drop the Gutenpack i18n wrapper
Once blocks have been moved to Jetpack (https://github.com/Automattic/jetpack/pull/11633), our custom i18n wrapper can be removed.

In calypso, the file is: https://github.com/Automattic/wp-calypso/blob/c909b11ab962b061a263a91c48eb5b6baab54b87/packages/jetpack-blocks/src/utils/i18n.js

Does `jetpack` textdomain need to be added to these functions?

### PR DESCRIPTION
**Pull request by sirreal**
Closes: #11656 

#### Changes proposed in this Pull Request:

- Drop the now-obsolete i18n helper in `extensions/utils`
- Change `__, _n, _x, _nx()` imports to import directly from `@wordpress/i18n`
- Add `jetpack` textdomain as last argument to all those functions

#### Testing instructions:

- Verify that blocks still work
- (Not sure if we currently expect translations to work? They might live in a different place than they will once this is merged and used for string extraction.)

#### Proposed changelog entry for your changes:

Blocks: Drop i18n wrapper, use `@wordpress/i18n` directly.

### CODE REVIEW

**Comment by simison** [comment]
Do we now need to add `jetpack` textdomain in translation functions?

**Comment by sirreal** [comment]
> Do we now need to add `jetpack` textdomain in translation functions?

Yes, I believe so.

**Comment by ockham** [comment]
This could do the trick

```js
/** @format */

function addTextdomain( j, root, name ) {
  	return root
		.find( j.CallExpression, { callee: { type: 'Identifier', name } } )
		.forEach( path => {
			j( path ).replaceWith( () => {
				path.node.arguments = path.node.arguments.concat( j.stringLiteral( 'jetpack' ) );
              	return path.node;
			} );
		} )
		.toSource( { quote: 'single' } );
}

export default function transformer( file, api ) {
	const j = api.jscodeshift;
	var ret = file.source;
	ret = addTextdomain( j, j( ret ), '__' ); 
 	ret = addTextdomain( j, j( ret ), '_n' );
   	ret = addTextdomain( j, j( ret ), '_x' );
   	ret = addTextdomain( j, j( ret ), '_nx' );

	return ret;
}
```

**Comment by simison** [comment]
Rebased after `vr` block folder had been removed.

**Review by simison — APPROVED** [review]
Builds well and blocks work.

Since there have been issues with i18n and blocks in `master`, we might need to verify separately that translations work before 7.3 ships.

I'm seeing some translations for business hours block tho (_maanantai_ = _monday_): 

image

**Comment by ockham** [comment]
I'll try and produce a WP.com phab diff.

**Comment by ockham** [comment]
> I'll try and produce a WP.com phab diff.

D26251-code

**Review by scruffian — APPROVED** [review]
I tested this and it worked as expected. I tried switching branches and everything continued to work. Code looks good too.

**Review by jeherve — APPROVED** [review]
It works well for me 👍

**Comment by ockham** [comment]
Thanks everyone for reviewing!

**Pull request merged**
