### PR TITLE
General: Basic updates to prepare for WP 5.8

### PR DESCRIPTION
**Pull request by kraftbj**
- Bump minimum supported/tested version to 5.7/5.8
- Remove Instagram oembed removal. Ref #19736

See #19654

#### Changes proposed in this Pull Request:
* Bump versions.
* Remove Instagram code
* More coming.

#### Jetpack product discussion

See 19654

#### Does this pull request change what data or activity we track or use?

n/a

#### Testing instructions:

* Running WP 5.7 or 5.8, test an Instagram embed.
*

### CODE REVIEW

**Comment by kraftbj** [comment]
Unit test failure to be fixed by #20045.

**Review by sdixon194 — CHANGES_REQUESTED** [review]
Looks like I'm getting:

> Deprecated: Jetpack::validate_sync_error_idc_option is deprecated since version jetpack-9.8! Use \Automattic\Jetpack\Identity_Crisis::validate_sync_error_idc_option instead. in /srv/users/user35ae9581/apps/user35ae9581/public/wp-includes/functions.php on line 4861

I think maybe from `class-jetpack-redux-state-helper.php` on line 79? 🤔

**Comment by kraftbj** [comment]
Where are you seeing that @sdixon194? I'm not sure how this PR would be causing that.

**Comment by sdixon194** [comment]
> Where are you seeing that @sdixon194? I'm not sure how this PR would be causing that.

Yeah that's why I'm confused too. I see the php error on any Jetpack dashboard - both locally and a JN site.

Screen Shot on 2021-06-09 at 15:58:04

Doing some more digging, it seems like it's also happening on `Bleeding edge`, so likely unrelated to this PR. It also doesn't happen on my regularly hosted test sites, just JN and locally 🤔

**Comment by kraftbj** [comment]
Well, this PR should be able to land once you can re-test it and we can slide the fix in here. LIkely caused by #19126.

**Review by sdixon194 — APPROVED** [review]

**Comment by kraftbj** [comment]
r227047-wpcom

**Pull request merged**
