### PR TITLE
Social | Update connections modal UI

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Proposed changes:

* Update the connections modal UI as per the design

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Ensure that feature flag is ON - `define( 'JETPACK_SOCIAL_USE_ADMIN_UI_V1', true );`
- Test the following for both Jetpack and Social plugin
    - Goto settings page
    - Open "Add new connection" modal
    - Confirm that the UI looks as per the design - p1HpG7-swB-p2
    - Add some connections
    - Confirm that you see "Connected" in green for active connection services
    - Add more than one connection to a service
    - Confirm that you see "N connections"

Screenshot 2024-05-16 at 5 56 06 PM
Screenshot 2024-05-16 at 5 56 14 PM
Screenshot 2024-05-16 at 5 56 52 PM
Screenshot 2024-05-16 at 5 57 06 PM

### CODE REVIEW

**Review by spsiddarthan — COMMENTED** [review]
This works well. I haven't tested this on WPCOM for sanity, but otherwise it looks great. 

Should we test it on Atomic as well and see how it behaves?

**Review by gmjuhasz — COMMENTED** [review]
The styling of the connection names is messed up, it has the underline everytime, I think it was working yesterday when we looked at it?

**Comment by manzoorwanijk** [comment]
Optimistic updates

https://github.com/Automattic/jetpack/assets/18226415/b3337d3c-9d1d-4bac-a3af-148d9f45731f

**Comment by manzoorwanijk** [comment]
Reduced opacity for disabled items

https://github.com/Automattic/jetpack/assets/18226415/f1fb9956-db46-4df0-aac8-085fd29101ec

**Review by pablinos — COMMENTED** [review]
This is looking good. I think having the connection faded while the API request completes to (un)globalize it, is a good improvement on what we have in Calypso/Cloud currently.

I've noticed the Connect/Connect More button is broken for Mastodon. It changes the title of the modal to 'Connecting a new Mastodon Account' but doesn't expand the section. When the section is expanded, it doesn't have the form for adding the username. I'm pretty sure that was working, so I think this is probably a regression.

CleanShot 2024-05-18 at 21 38 40@2x

**Comment by manzoorwanijk** [comment]
> I've noticed the Connect/Connect More button is broken for Mastodon. It changes the title of the modal to 'Connecting a new Mastodon Account' but doesn't expand the section. When the section is expanded, it doesn't have the form for adding the username. I'm pretty sure that was working, so I think this is probably a regression.

Good catch. Thanks

**Review by gmjuhasz — COMMENTED** [review]
@manzoorwanijk I think other than Mastodon this works well, there is just one minor issue I found, the last info popup in the modal is cut off at the end of the modal.

CleanShot 2024-05-20 at 09 30 01 png

**Comment by manzoorwanijk** [comment]
> one minor issue I found, the last info popup in the modal is cut off at the end of the modal.

@gmjuhasz Nice catch. It's now fixed in https://github.com/Automattic/jetpack/pull/37420/commits/a0ff59a0d80a4829f0b031466bf695e02fc62b98

image
image

**Comment by manzoorwanijk** [comment]
Hide inline connect button for mastodon on panel open

https://github.com/Automattic/jetpack/assets/18226415/d8f3e4e2-755d-4ab0-94cf-84402578dd41

**Comment by manzoorwanijk** [comment]
Consistent font-size

Screenshot 2024-05-20 at 5 51 51 PM

**Comment by manzoorwanijk** [comment]
Increased font-size for confirmation modal text

Screenshot 2024-05-20 at 6 03 12 PM

**Review by gmjuhasz — APPROVED** [review]
This now works well for me and looks good too. I'm not sure @pablinos want's to take a look or not, I thinks its good

**Pull request merged**
