### PR TITLE
Fixes gulp language extract task async problem.

### PR DESCRIPTION
**Pull request by zinigor**
Fixes a problem with the language extracting task where it wouldn't properly signal an end.

#### Changes proposed in this Pull Request:

* Added a `return` statement to the `gulp` task so that Gulp knows when the task is over. It looks like this one broke sometime ago, but nobody noticed because it's not regularly run.
* Removed gulp tasks that merged POT files into one and converted it into a PHP file.
* Changed the jetpack-strings file generation back to "direct to PHP" mode to avoid unnecessary conversions.

#### Testing instructions:

* Make sure `yarn gulp languages:extract` runs properly, doesn't fail.
* Additionally `yarn build-languages` and `yarn build-production` should work too, no failures expected.

#### Proposed changelog entry
Not needed.

### CODE REVIEW

**Review by kraftbj — DISMISSED** [review]
Fixed the issue for me.

**Comment by aldavigdis** [comment]
I ran this manually on my local machine and it works perfectly.

**Review by aldavigdis — DISMISSED** [review]
👍

**Review by kraftbj — APPROVED** [review]
On node 10, works great.

**Comment by aldavigdis** [comment]
`yarn build-production` works as well as `gulp languages:extract`

**Review by jeherve — APPROVED** [review]
This should be good to go. I can see that the block strings are now gone from `_inc/jetpack-strings.php`, since they are not needed anymore.

**Pull request merged**
