### PR TITLE
Social Media Icons Widget: add new parameters

### LINKED ISSUE #7601: Social Media Icons: open link in a new tab
**Changes proposed**

Including an option for opening the social media networks in a new tab instead of redirecting visitors to the social media's site in the same one.

Requested on: 617940-t

### PR DESCRIPTION
**Pull request by bradleymoore111**
Fixes #7601 

Recreation of the previous pull request #7917, that I accidentally broke.

- Added icon size and icon color options to the links.
- Added the option to open social links in a new tab rather than the main window.

**Edit**: Added "Fixes #...." &mdash; @oskosk

### CODE REVIEW

**Comment by oskosk** [comment]
As mentioned by @jeherve in #7917:

"Noting that this might become moot if #7454 is merged. It might be best to add those features to the new version of the widget instead."

**Comment by zinigor** [comment]
Sorry, we had no time to test this in order to get it into 5.8, we'll try to get it in 5.9.

**Comment by bradleymoore111** [comment]
Hey that's OK, I'll make sure it's compatible and all after the release (though it's small enough that that shouldn't be a problem).

**Comment by dereksmart** [comment]
@bradleymoore111 turns out that this version of the widget is going to be deprecated by a version that already supports opening in a new tab in the upcoming release.  Would you mind testing that one out? #8498 

If that satisfies, can you please close this PR? Thanks!

**Comment by bradleymoore111** [comment]
Hm, so ignoring the broken new_tab variable (I assume they'll fix it) in #8498, it fixes the opening in new tab, but a large reason I submitted this was also to be able to change color/more control over the size of the icons. Either way though, it's a better direction, and this pull request is now in reference to a deprecated widget.

I'll close this request, but I may re-open a new one for the newer widget to support more sizing options/color. Otherwise, thanks fro the response!

**Comment by dereksmart** [comment]
Thanks @bradleymoore111!

**Comment by andpiazza** [comment]
How do we change the order of the social share icons, example:
show in this order
- instagram
- facebook
- linkedin
- google+
- twitter

**Comment by zinigor** [comment]
@andpiazza you should be able to use the new version of the widget and post the links in the order of your choice. Here's [the help article](https://en.support.wordpress.com/widgets/social-media-icons-widget/) for WordPress.com that has the same widget, which should help you do what you want.

**Pull request closed without merging**
