### PR TITLE
Forms: Fix previews on Forms package

### LINKED ISSUE #29291: Fix Forms previews on Forms package
This task is complementary to #29178.
We decided to split up the task to save some time since #29178 needed to be cherry-picked for the release.

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #29291

## Proposed changes:

* Fixes Forms previews on the Forms package

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No
## Testing instructions:

* Enable the Forms package by adding the following filter to the constructor of the `class.jetpack.php` inside the Jetpack plugin

```
add_filter( 'jetpack_contact_form_use_package', '__return_true' ); 
```

* Create a post and add a Form block
* Check all the available block previews (Block Library, Block Style Variations, and Patterns Modal) work as expected

### CODE REVIEW

**Comment by CGastrell** [comment]
Not entirely sure where I should be looking, but I checked:

- Block library (on mouse over): previews looked good
- Exploring patterns: previews looked good
- Variations: no previews there, so I guess it's ok?

Let me know if I should be looking in any other place or that should suffice

**Comment by jcheringer** [comment]
> Not entirely sure where I should be looking, but I checked:
> 
> * Block library (on mouse over): previews looked good
> * Exploring patterns: previews looked good
> * Variations: no previews there, so I guess it's ok?
> 
> Let me know if I should be looking in any other place or that should suffice

Thanks for taking a look @CGastrell!
What do you mean by `Variations: no previews there, so I guess it's ok?`?
You should be able to see the preview by hovering the mouse over the variation buttons:

image

**Comment by CGastrell** [comment]
> > Not entirely sure where I should be looking, but I checked:
> > 
> > * Block library (on mouse over): previews looked good
> > * Exploring patterns: previews looked good
> > * Variations: no previews there, so I guess it's ok?
> > 
> > Let me know if I should be looking in any other place or that should suffice
> 
> Thanks for taking a look @CGastrell! What do you mean by `Variations: no previews there, so I guess it's ok?`? You should be able to see the preview by hovering the mouse over the variation buttons:
> 

Oh, I get it now! Those are the styles, I was hovering the variations here and not seeing anything:
image

So I'd say it's working good. One thing though, and we can completely throw this in a follow up PR: when the variations picker is rendered we already have the Styles available, making them render a preview of the variations picker :D 

https://user-images.githubusercontent.com/157240/224411032-3b1a409c-7442-40ba-bb99-9dfcf7c70281.mov

Let me know what you prefer, as in: maybe it's a single line of code change, or follow up on another PR

**Review by CGastrell — APPROVED** [review]
I left a comment for your consideration, otherwise this LGTM :shipit:

**Comment by jcheringer** [comment]
I'm not sure what's happening.
I could reproduce what you're saying once but then I couldn't anymore.
Tried removing the block and adding a new one, refreshing the page. 🤷‍♂️ 

image

@CGastrell

**Pull request merged**
