### PR TITLE
Add badge to admin menus endpoint

### PR DESCRIPTION
**Pull request by david-szabo97**
Related https://github.com/Automattic/wp-calypso/issues/54464

#### Changes proposed in this Pull Request:

* Add badge to the JetPack admin menus endpoint. We use this to ensure we have a beta badge for the Site Editor menu.

#### Testing instructions:

* Apply diff
* Sandbox public-api
* Open the Calypso admin of one of your sites with site editor enabled
* Open inspector and find this request: https://public-api.wordpress.com/wpcom/v2/sites/_YOUR_SITE_ID_/admin-menu/?_envelope=1
* Confirm response contains the site editor with a badge property. (badge = "beta")

### CODE REVIEW

**Comment by david-szabo97** [comment]
We already had a diff for this change: D64231-code some comments can be found there.

**Review by mattwiebe — APPROVED** [review]
I gave it a 👍 before, and I'll give it a 👍 again.

**Review by samiff — APPROVED** [review]
Looks good 👍 

Screen Shot 2021-07-28 at 3 48 46 PM

**Comment by samiff** [comment]
cherry-picked to 10.0 release branch in 7b08a18948ee57f60cbc23c46b06db14cb02a365

**Comment by david-szabo97** [comment]
r229480-wpcom

**Pull request merged**
