### PR TITLE
Email preview: improve error state visually

### PR DESCRIPTION
**Pull request by simison**
As I was debugging some backend errors, I noticed the error state wasn't great looking, so this is just a quick update to it.

## Proposed changes:
* Adds better looking error state and ability to re-fetch the preview.
* Adds tracks for Errors

### Before

Screenshot 2024-09-20 at 14 12 15

### After

Screenshot 2024-10-01 at 13 31 23

After 2nd fetch:

Screenshot 2024-10-01 at 13 31 40

Linking to https://jetpack.com/support/

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Trigger error from backend e.g. by returning empty string, see D161896-code for the right file.
* Open the preview modal, see error.
* Remove the backend change, and re-fetch in modal.
* Refetching works.

### CODE REVIEW

**Comment by simison** [comment]
FYI @crisbusquets for design; hopefully this view never shows up though. ;-)

Could remove the icon to simplify the view a bit, now it's;

- Icon
- H3
- Button "primary" variation

**Comment by crisbusquets** [comment]
> FYI @crisbusquets for design; hopefully this view never shows up though. ;-)
> 
> Could remove the icon to simplify the view a bit, now it's;
> 
> * Icon
> * H3
> * Button "primary" variation

Works for me. I'd rather have this design than an red/error warning floating in the middle of the screen.

Would the "Try again" CTA solve the issue? I'm asking because ideally we should provide users with a solution, and I'm not sure if reloading will do that.

**Comment by simison** [comment]
I have to confirm but I think the error would get triggered just by spotty internet connection, in which case it can help. Otherwise it'll just reload the error so not super helpful. We could add copy about contacting support?

**Comment by crisbusquets** [comment]
> We could add copy about contacting support?

Can we:
1. First show the CTA to reload
2. Show the link to contact support if reloading it one time doesn't work

I'm not convinced about showing the contact support link right away. What do you think?

**Comment by simison** [comment]
> Can we:
>
> - First show the CTA to reload
> - Show the link to contact support if reloading it one time doesn't work

Sounds good, thanks @crisbusquets. I updated the logic to this and updated screenshots in the PR description.

**Review by lezama — APPROVED** [review]
❤️

**Pull request merged**
