### PR TITLE
Likes: replace postmessage.js with native code

### PR DESCRIPTION
**Pull request by sgomes**
This PR replaces the usage of `postmessage.js` with the native `postMessage` functionality built into the browser.

`postmessage.js` is no longer required, since all of the supported browsers have native support for `window.postMessage` at this point. Removing this library allows us to save ~16KB (~4KB over the wire) on every context where `postmessage.js` was loaded, which due to browser privacy mitigations often don't share a cache.

Note: This PR will need to be coordinated with further changes on the wpcom side of things, which I'll add to the automatically generated Fusion diff.

#### Changes proposed in this Pull Request:
* Replace all usage of `postmessage.js` with native `postMessage`
* Removing all existing enqueuing of `postmessage.js`
* Remove `postmessage.js` from `_inc`

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
Ensure that likes and comment likes continue working correctly, based on the modified Fusion diff at D69669-code.

### CODE REVIEW

**Comment by sgomes** [comment]
The corresponding D69669-code, which includes both these changes and the corresponding wpcom-specific ones, is now ready for review.

**Review by jeherve — COMMENTED** [review]
I cannot seem to get this to work, but I'm not sure why. Here is [an example of a post where Likes usually work, but not with this branch](https://jeherve.com/testing-things-but-with-a-custom-publicize-message/).

**Comment by sgomes** [comment]
> I cannot seem to get this to work, but I'm not sure why. Here is [an example of a post where Likes usually work, but not with this branch](https://jeherve.com/testing-things-but-with-a-custom-publicize-message/).

Thank you, @jeherve! I'll investigate and see if I can reproduce your issue.

**Comment by sgomes** [comment]
> Thank you, @jeherve! I'll investigate and see if I can reproduce your issue.

@jeherve I'm having trouble getting things to work even without the patch:

image

It seems to remain loading indefinitely. I've tried two separate WordPress.com accounts and neither seems to work.

**Comment by jeherve** [comment]
> I'm having trouble getting things to work on that site even without the patch:

It seems to work well for me when I switch to `master`, as you can see [here](https://jeherve.com/testing-things-but-with-a-custom-publicize-message/).

**Comment by sgomes** [comment]
> > I'm having trouble getting things to work on that site even without the patch:
> 
> It seems to work well for me when I switch to `master`, as you can see [here](https://jeherve.com/testing-things-but-with-a-custom-publicize-message/).

Thanks @jeherve. That's the same URL, so I assume you simply switched branches?

If so, it appears I'm still getting my branch's `queuehandler.js`, so there may be an issue with the cachebusting or some other type of inconsistency.

**Comment by jeherve** [comment]
> That's the same URL, so I assume you simply switched branches?

Yup, correct.

> If so, it appears I'm still getting my branch's queuehandler.js, so there may be an issue with the cachebusting or some other type of inconsistency.

Indeed. I've just flushed the cache, so this shouldn't be an issue anymore.

**Comment by sgomes** [comment]
> Indeed. I've just flushed the cache, so this shouldn't be an issue anymore.

Perfect, thank you @jeherve !

I can confirm it works correctly now. I'll use local overrides to test things and see if I can piece together what fails with the patch, and will let you know when I have a fix 👍

**Comment by sgomes** [comment]
I've tracked down the issue. The new messages aren't immediately compatible with the old ones, which means that all systems would need to be upgraded simultaneously for there to be no breakage. In this case, things are failing because the corresponding wpcom services haven't been updated yet.

I will attempt to make `queuehandler.js` compatible with both types of messages to provide for a seamless upgrade path.

**Comment by sgomes** [comment]
Both this PR and the corresponding wpcom change have been updated to work with the old message format, so this is ready for review once again 👍

**Comment by sgomes** [comment]
Rebased, to clear the PR check.

**Comment by sgomes** [comment]
Rebased, to remove annoying `[not verified]` tags on commit messages.

**Comment by samiff** [comment]
Tested this out using the instructions in the diff and the Like button worked as expected.

@sgomes This is my first time reading about `window.postMessage` and was just curious about the couple of blocks in the diff with `window.addEventListener( 'message'` and no origin/source checking. Would there be any security implications for that?

**Comment by sgomes** [comment]
Thank you for taking a look, @samiff! 👍

> Would there be any security implications for that?

I'm not a security expert, but it is my understanding that there are indeed possible security or privacy concerns whenever a message is emitted with a `*`, or when a message is listened to and its origin isn't checked. This of course depends on the content of the message being emitted and how sensitive it is.

In any case, my approach with these changes is to keep the exact same behaviour as before; `postmessage.js` uses `window.postMessage` under the hood (which is partly why it's a waste to keep using it and pulling in more JS than needed), so assuming I translated everything correctly there shouldn't be any *new* security implications.

I'm happy to change things to enhance security (without breaking functionality) if someone's available to coach me through it, though!

**Comment by samiff** [comment]
> my approach with these changes is to keep the exact same behaviour as before; `postmessage.js` uses `window.postMessage` under the hood

That makes sense, I think this PR is good to ship on its own 👍

**Review by samiff — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you for the review and approval, @samiff! 🙏

**Pull request merged**
