### PR TITLE
Responsive videos: do not load when embed blocks are in use

### LINKED ISSUE #11097: Responsive videos: Removing support for Gutenberg themes causes issues in older posts
With #10678, themes that support Gutenberg's responsive embeds will no longer use Jetpack's responsive video behaviour. This makes sense -- I can see how having two competing responsive embed approaches would make a bit of a mess! -- but it causes some issues in this in-between time, when sites with existing content switch to a Gutenberg supporting theme, or, like on WP.com, existing themes get Gutenberg support added: videos in older posts stop behaving responsively. 

#### Steps to reproduce the issue

1. Start with a theme that supports both `responsive-embeds` and `jetpack-responsive-videos` (every theme in https://github.com/Automattic/themes should fit this criteria)
2. Create a post, and add a YouTube video and/or Vimeo video to a Classic Block.
3. Publish post.
4. View on mobile.

#### What I expected
I expected the videos to maintain their aspect ratio.

#### What happened instead

YouTube videos get cut off on the sides, and Vimeo videos get scaled down to fill the available width, but there's extra vertical space around them.

Originally reported here: https://github.com/Automattic/themes/issues/478

I'm going to keep investigating this from the theme side for the ones on WP.com, but I wanted to bring it up here, too, in case there's a way to keep the two responsive behaviours from clashing, but still apply Jetpack's solution to videos embedded in the classic editor or block.

**Screenshots**
Youtube video added to a Classic block, using the Lodestar theme:

Vimeo video added to a Classic block, using the Lodestar theme:

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #11097 

#### Changes proposed in this Pull Request:

This is a different approach than #10880. Instead of shortcircuiting Jetpack responsive videos as soon as we detect that the theme supports core responsive embeds, we hook into each block as it is being rendered. We check if the block is an embed block, and if so we remove the wrapper div that had been added by Jetpack Responsive videos, thus stopping it from affecting the display of videos.
If however all we find are classic blocks (even with videos inside) or shortcodes, we carry on and use Jetpack responsive videos.

#### Testing instructions:

* Start by enabling a theme that supports core Responsive embeds, like Twenty Nineteen.
* In a new post, paste a YouTube video; it will be automatically converted into an embed block with the video. Set that embed to a full width one.
* Publish your post.
* On the frontend, you should not see any `jetpack-video-wrapper` div around the embed. The video should take the full width of your browser.
* Edit that post. Delete that embed block, and instead insert a classic block. Inside that classic block, paste the same video URL.
* Save your changes.
* On the frontend, you should now see the `jetpack-video-wrapper` div around the embed.

#### Proposed changelog entry for your changes:

* Responsive videos: do not apply for videos that benefit from WordPress' own Responsive Embeds solution.

### CODE REVIEW

**Review by brbrr — COMMENTED** [review]
This PR fixes the problem, but it seems that `responsive-videos.min.js` is still enqueued even when it is not needed.

**Comment by jeherve** [comment]
@brbrr I have now updated this PR to take a different approach. I've updated the testing instructions accordingly.

**Review by brbrr — APPROVED** [review]
LGTM! Thank you :shipit:

**Comment by jeherve** [comment]
@laurelfulford Do you think you could give this a try, see if that solution would work for you?

Thank you!

**Comment by laurelfulford** [comment]
@jeherve Gah, sorry I missed the ping from earlier this week to test! 

Looks like things are already moving ahead, but I wanted to confirm I did check this out, and the fix looks great! Thank you for diving into this!

**Pull request merged**
