### PR TITLE
Comments: Remove comment author URL shortcutting

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to remove a condition which is used to shortcut the return of the Jetpack Comments author avatar if the comment author URL does not contain either a Facebook or Twitter domain. It's assumed that this condition was added to prevent an unnecessary meta lookup, since the comment object is already known, but the meta may not have been retrieved. However, we'd like to consider ignoring author URLs for Facebook URLs containing an app-scoped user ID, since these are not useful in the sense of being the comment author's canonical website. If we were to remove tracking of the `comment_author_URL` without removing this check, the commenter avatar would also not be shown. With these changes, the comment author avatar should still display while the `comment_author_url` field is empty.

__Testing instructions:__

Verify that Jetpack Comments author avatars display as expected, for comments originating from a guest, a logged in user, or from a connected social media account.

### CODE REVIEW

**Comment by dereksmart** [comment]
With this patch applied, my avatar (when logged in) is replaced by a WordPress logo

screen shot 2016-02-22 at 12 00 32 pm

It gives me the photonized $foreign_avatar:  `http://i2.wp.com/s2.wp.com/wp-content/mu-plugins/highlander-comments/images/wplogo.png`

**Comment by aduth** [comment]
>With this patch applied, my avatar (when logged in) is replaced by a WordPress logo

Could you Slack me a link to where you're seeing this, and what you're expecting to see?

I would have expected that if a foreign (Facebook, Twitter) avatar is not assigned in the comment meta, it should return the default avatar (same return value as previous).

I'd be curious to see what value is assigned to the `hc_avatar` meta key for that comment.

**Comment by aduth** [comment]
@dereksmart : Per our conversation, it appears the comments module expects this function to shortcut early with the original avatar if it is not a Twitter or Facebook avatar. Therefore, I've reimplemented a condition in 0fe3a89 to still perform the URL check, but against the avatar stored in the comment meta.

**Comment by jeherve** [comment]
It seems to work well in my tests, regardless of how I comment (WordPress.com, WordPress.com without a Gravatar, Twitter, Twitter without a profile picture, Facebook, Google+, Standard Gravatar Guest commenter, and admin).

**Pull request merged**
