### PR TITLE
AMP: Fix invalid `@media only` block styles

### LINKED ISSUE #19922: AMP: Slideshow block includes invalid CSS in AMP
The slideshow block is including `@media only email` in AMP, which doesn't validate:

image

image

The relevant `@media` queries should be stripped out for AMP.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/19922

#### Changes proposed in this Pull Request:
Removes the `@media only <FALLBACK_CONTEXT>` styles used in some blocks when rendered in other contexts than the web (e.g. emails or notifications) since they are breaking the AMP validation. They have been replaced with a regular CSS selector targeting the `is-<FALLBACK_CONTEXT>` class, which is now added to posts rendered on fallback contexts (see D62038-code).

Before | After
--- | ---
Screen Shot 2021-05-28 at 15 32 20 | Screen Shot 2021-05-28 at 15 38 05

#### Jetpack product discussion
N/A.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Go to Posts > Add new.
- Insert these blocks: Slideshow, Tiled Gallery, Pay with PayPal.
- Publish the post.
- Copy the published post URL and add `?amp#development=amp` at the end.
- Visit the above URL.
- Inspect the browser JS console.
- Make sure the AMP validation is successful.
- Make sure there are no regressions when the post is rendered on a fallback context (see D62038-code).

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This looks good to me. 🚢

**Comment by mmtr** [comment]
Changes here depend on D62038-code, so please do not merge this PR until the previous has landed.

**Comment by mmtr** [comment]
Deployed to WP.com in r226502-wpcom.

**Comment by samiff** [comment]
Cherry-picked to `jetpack/branch-9.8` in 383db2a1f60f4cb3c5289de949a6bbfc83b590fd

**Pull request merged**
