### PR TITLE
Convert some Jetpack synced files from subdirectory rtl to core style…

### PR DESCRIPTION
**Pull request by georgestephanis**
… rtl.

Summary:
All of the deleted files and directories were moved in r157038-wpcom
This will let Jetpack have the same generated rtl css paths as wpcom, instead of having to either use the wrong path or use rtl conditionals for wpcom rtl stylesheets that Jetpack's build tools can't update as the source css changes.
Test Plan:
Load up http://stephanis.info/?concat_css=no in a sandbox with a rtl language or rtl somehow otherwise enabled and make sure that the following stylesheet is loaded:
https://georgestephanis.wordpress.com/wp-content/mu-plugins/shortcodes/recipes/css/recipes-rtl.css
For enabling rtl, I just did this:

```
add_action( 'init', function(){
	global $wp_locale;
	$wp_locale->text_direction = 'rtl';
	global $wp_styles;
	if ( ! is_a( $wp_styles, 'WP_Styles' ) ) {
		$wp_styles = new WP_Styles();
	}
	$wp_styles->text_direction = 'rtl';
});
```

Reviewers: yoavf
Reviewed By: yoavf
Subscribers: yoavf
Differential Revision: D5814

This commit merges r157268-wpcom downstream to Jetpack.

### CODE REVIEW

**Comment by georgestephanis** [comment]
@zinigor Should be fixed -- build tools should now generate the rtl variants.

**Comment by eliorivero** [comment]
I applied this branch to my sandbox, set the language to 
captura de pantalla 2017-08-03 a las 19 52 28
Applied D5814 in my sandbox.
When I load this https://eliorivero.wpsandbox.me/blog/2017/05/24/delicious-recipe/?concat_css=no
it's trying to load https://eliorivero.wpsandbox.me/wp-content/plugins/jetpack/modules/shortcodes/css/recipes.min-rtl.css?ver=20130919 but the file is missing.

**Comment by georgestephanis** [comment]
Ah, got it.  That sounds oddly familiar -- I think something's not properly handling the order of minification/rtl in the path.  Checking.

**Comment by georgestephanis** [comment]
So what's happening is that this code in class.jetpack.php:

https://github.com/Automattic/jetpack/blob/039567d86/class.jetpack.php#L5854-L5893

is rewriting the url from `blah.css` to `blah.min.css` before the stylesheet is registered.

This is happening so the same synced code can run on wpcom and jetpack, with this extraneous code handling the minification.

Unfortunately, nothing is setting the 

`wp_style_add_data( 'handle', 'suffix', '.min' );` so that core knows to do `recipes-rtl.min.css` instead of `recipes.min-rtl.css`

I'm checking into the best way to add that now so it doesn't fire on wpcom as well.

**Comment by georgestephanis** [comment]
Should be addressed now.  Tested and seems to behave properly both with and without min'd files.

**Comment by eliorivero** [comment]
Works fine! 🐑

**Pull request merged**
