### PR TITLE
Repo Gardening: switch to GitHub's action toolkit for debug

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:
﻿
We were using our own debug functionality until now, but GitHub offers a debug functionality as part of its action toolkit:
https://github.com/actions/toolkit/tree/main/packages/core#logging

Since we already use that dependency in the action, let's use it for logging as well.

It allows us to enable and disable logging via a secret, as explained here:
https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#step-debug-logs

#### Jetpack product discussion

* No

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Set a new GitHub secret [here](https://github.com/Automattic/jetpack/settings/secrets/actions): `ACTIONS_STEP_DEBUG`, set to `true`.
* Make a change to this PR (update this description to fix this ~tpyo~typo for example).
* Notice the purple debug lines in [the action that ran](https://github.com/Automattic/jetpack/runs/3531450584).

Screenshot 2021-09-07 at 10 14 35

### CODE REVIEW

**Review by anomiex — APPROVED** [review]
> Set a new GitHub secret [here](https://github.com/Automattic/jetpack/settings/secrets/actions): `ACTIONS_STEP_DEBUG`, set to `true`.

Personally I'm not very fond of GitHub's built-in debug function because of the need for this step, which also enables a flood of other debug messages. But I won't block on it. PR itself looks good to do what it intends.

**Comment by jeherve** [comment]
> Personally I'm not very fond of GitHub's built-in debug function because of the need for this step, which also enables a flood of other debug messages. But I won't block on it. PR itself looks good to do what it intends.

Happy to wait for a third opinion on this, I'm okay not making the change if you'd rather not.

**Comment by samiff** [comment]
> enables a flood of other debug messages

@anomiex Is there an example to look at? Is it just more verbose or is there a lot of unrelated noise that would make reading through the logs harder?

**Comment by jeherve** [comment]
> @anomiex Is there an example to look at? Is it just more verbose or is there a lot of unrelated noise that would make reading through the logs harder?

You can check the action that ran for this PR:
https://github.com/Automattic/jetpack/runs/3531450584

You'll notice debug steps for when the action runs, but also for other setup steps.

**Comment by samiff** [comment]
> You can check the action that ran for this PR:
> https://github.com/Automattic/jetpack/runs/3531450584
> 
> You'll notice debug steps for when the action runs, but also for other setup steps.

Got it, I'm not a fan of the extra lines and `##[debug]` prefixing everything.

**Comment by jeherve** [comment]
👍 Closing this now.

**Pull request closed without merging**
