### PR TITLE
Sync: Add data validation on the server side tests.

### PR DESCRIPTION
**Pull request by enejb**
We don't have any test that show that the data is what we expect it to be. 

Thoughts? @lezama, @gravityrail 

- [ ] Did you create a **new action or filter**? [Add inline documentation](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters) to help others understand how to use the action or the filter.
- [ ] Create **[unit tests](https://github.com/Automattic/jetpack/tree/master/tests)** if you can. If you're not familiar with Unit Testing, you can check [this tutorial](https://pippinsplugins.com/series/unit-tests-wordpress-plugins/).

### CODE REVIEW

**Comment by gravityrail** [comment]
A few thoughts:

1. It seems like this overlaps with #4530, which also checks if there was a WP_Error response. However that PR takes a simpler approach because it assumes there will be at most one error - that the server will stop processing after a single error. This is important because we don't ever want to process sync actions out-of-order if we can avoid it, so we should always stop processing and return after a single error rather than continue processing items. That also means it's less code and doesn't change the response format from WPCOM.

2. While I like the idea of `class.jetpack-sync-data-validator.php`, it seems that this code could easily be part of the replicator (or replicastore, but that would introduce duplication) rather than having an entire duplicate class. This would help avoid issues of keeping those two implementations in sync when really the responsibilities of validating input and issuing commands on the replicastore could easily be put in the same file. It'll then be clearer exactly what expectations the replicastore has on data types.

**Comment by gravityrail** [comment]
I do however think that we need a separate input validator and cleaner for synced options, as the data format for options varies per option name. Something like `Jetpack_Sync_Option_Validator` that would be part of WPCOM.

**Comment by jeherve** [comment]
@enejb Is this still a valid PR, or was it replaced by another one?

**Comment by enejb** [comment]
Sorry this is really old I will close it.

**Pull request closed without merging**
