### PR TITLE
AIOWP Helper: Add `target_blog_id` eventprop to Tracks events

### PR DESCRIPTION
**Pull request by sixhours**
## Proposed changes:

* Add a `target_blog_id` eventprop to the Tracks events fired when an AIOWP migration is started and finished.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pa1C6h-3hm-p2#comment-13537 

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

1. Create a new Business site, mark it as a WoA Dev site, and take it Atomic.
2. Rsync the wpcomsh changes on this branch to your WoA site: `jetpack rsync wpcomsh yourtestsite.wordpress.com@sftp.wp.com:htdocs/wp-content/mu-plugins`
3. On your WoA test site, install the AIOWPM plugin: https://wordpress.com/plugins/all-in-one-wp-migration/
4. Activate the plugin and go to All in One WP Migration -> Export
5. Create and download an export file
6. Go to All in One WP Migration -> Import
7. Start the import from the file you created
8. Check Tracks Live for the migration start and end events (may take a few minutes to get there): `wpcom_site_migration_start` and `wpcom_site_migration_done`
9. Ensure the events have a `target_blog_id` eventprop set to your test site's blog ID

Screenshot 2024-07-30 at 2 24 44 PM

### CODE REVIEW

**Comment by andres-blanco** [comment]
I think the name of the events in the description is wrong, from the change in code it looks like it should be `wpcom_site_migration_start` and `wpcom_site_migration_done`. I've also checked for those events, but are not appearing, maybe I need to wait longer. Will check in a while.

**Review by andres-blanco — DISMISSED** [review]
The prop `target_blog_id` is added to the `wpcom_site_migration_(start|done)` events and it's populated with the results of `_wpcom_get_current_blog_id()`.

image
image

Btw, for the events in my site, `target_blog_id` is equal to `blogid` I figure that `_wpcom_get_current_blog_id()` is more robust than what is used for populating `blogid`?

**Comment by sixhours** [comment]
> Btw, for the events in my site, target_blog_id is equal to blogid I figure that _wpcom_get_current_blog_id() is more robust than what is used for populating blogid?

Yep yep! The `target_blog_id` is going to be the same as the `blog_id` in this case, and it's necessary to use the wpcomsh-specific function because on Atomic sites `get_current_blog_id()` will be equal to `1`.

**Comment by sixhours** [comment]
> I think the name of the events in the description is wrong, from the change in code it looks like it should be wpcom_site_migration_start and wpcom_site_migration_done.

And yep, that's my bad. 🙃 Fixed in the testing instructions, thank you!!

**Review by andres-blanco — APPROVED** [review]

**Pull request merged**
