### PR TITLE
Add the export modal for the new Jetpack Forms dashboard

### PR DESCRIPTION
**Pull request by ice9js**
## Proposed changes:

This PR adds an export modal for the new Jetpack Forms dashboard. The modal should work similarly to the existing one on the legacy view.

In addition to the modal, I've also updated the export handler itself so it's now also compatible with post status and search filters. This way, the export should always contain the same results you're seeing in the dashboard unless you make a specific selection.

_Note: The selection mechanism is a little buggy. I've moved it to the state layer but I saw @jcheringer also made some changes in #29766. Let's merge that one first, and then I'll fix any remaining issues here._

Screenshot 2023-03-29 at 13 42 00

Screenshot 2023-03-29 at 13 42 28

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pcsBup-Pl-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Go to `admin.php?page=jetpack-forms`.
- There should be an 'Export' button in the upper right corner above the table.
- Clicking the button should display the export modal.
- Clicking 'Download' under the CSV section should trigger a download for the CSV file.
- The Google Drive section should have an export button when you're already connected to google drive, otherwise a connect button will be shown.
- Triggering the google drive export should open a new tab with the newly created export document.
- In both cases, the export should contain the same responses you're currently seeing inside the inbox.
- If you change the selection, only the selected elements should be exported.

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Thanks so much Kuba! 
 
Export worked as expected 🥳!!!
Also tried with active search filter, search results were exported as expected! 👍 


Just a few little things from the design side:

- the modal is missing an "x" icon, 
- and it would need a little bit more padding, see below the current modal in production vs this version:
- "You need to connect..." is missing a space before the sentence.
- The Google Sheets button can be shortened to "Export"

image

**Review by digitalwaveride — APPROVED** [review]
image


Looking good now! 🚀 
Thanks a ton Kuba!

**Comment by digitalwaveride** [comment]
Aaaannd just as I gave the thumbs up, I tested the responsive views... the modal is missing some padding on small width views: 
image

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
As commented above, padding on responsive views missing.

**Review by digitalwaveride — DISMISSED** [review]
Paddings fixed on mobile views! 
Thank you, Sir! 🙏 
🚀

**Review by jcheringer — APPROVED** [review]
Works for me!

**Pull request merged**
