### PR TITLE
Boost: Add speed score popout

### LINKED ISSUE #36052: [Boost] Re-add score increase popout
Jetpack Boost used to have a nice stream of reviews, which has tapered off since we released Boost 3.0.0. Ref: p1708932630630129/1708726302.002779-slack-C01264051NE

This coincides with when we removed the score increase/decrease pop-outs, because we found the decrease pop-out triggered in a heap of situations it shouldn't, leading users to get upset and confused.

We should start by re-adding the "Your score got better" version of the dialog with a reminder for users to review the plugin. :)

### PR DESCRIPTION
**Pull request by dilirity**
Fixes #36052

## Proposed changes:

* Add the speed score changed prompt back into Boost;
* Update boost speed score modules list to include page cache.

It got removed in https://github.com/Automattic/jetpack/pull/35333 awhile back.
In https://github.com/Automattic/jetpack/pull/35327 we've updated the noBoost scores to no longer be returned if there are no active modules for the latest speed score request, which should fix the issue that warranted a removal of the prompt in the first place.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Request speed scores and make sure that the prompt behaves accordingly.

### CODE REVIEW

**Comment by haqadn** [comment]
It doesn't look like the no-boost score is behaving as expected. Something might not be right with #35327. Also, it doesn't account fot `page_cache`. Can you take a look?

**Comment by dilirity** [comment]
> It doesn't look like the no-boost score is behaving as expected. Something might not be right with #35327.

Can you elaborate on that?

> Also, it doesn't account fot `page_cache`.

I'm not sure what you mean by this. How should it account for page cache?

**Comment by dilirity** [comment]
https://github.com/Automattic/jetpack/blob/927a8403a12098e1a21bafd59feffc5d54c069ae/projects/packages/boost-speed-score/src/class-speed-score-request.php#L113-L120

This list is outdated and doesn't include the page_cache feature.

Further testing is also needed, to make sure noBoost isn't sent when all modules are disabled.

**Comment by haqadn** [comment]
I have re-tested this and I got a speed score has fallen on the first load. So, we do need to fix the logic behind when noBoost score is sent.

**Review by haqadn — DISMISSED** [review]
The issue I raised is OOS of this PR. So, this one is good to merge.

**Comment by haqadn** [comment]
I have added a PR to fix the issue: https://github.com/Automattic/jetpack/pull/36534

**Comment by thingalon** [comment]
> I have re-tested this and I got a speed score has fallen on the first load. So, we do need to fix the logic behind when noBoost score is sent.

I'd be ok with only implementing the score increased dialog for now :) We can always re-add the decrease notice later. I'm not sure momentary dips should prompt people to reach out to support, and I'd be inclined to suggest you leave it out and revisit it as an upgrade to the performance history chart.

**Comment by dilirity** [comment]
@haqadn this got lost in the wind. Merged with trunk and had to re-add the changes.

Do you think we should only release the speed increase version?

**Review by haqadn — APPROVED** [review]
Looks good and works as expected 👍🏼 

I somewhat agree with what Mark suggested, that the momentary dips probably shouldn't trigger a contact support prompt. But, it's already there and is probably good for working on as a separate thing.

I don't think we should remove it completely though. I think we should work on detecting an actual drop more accurately.

**Pull request merged**
