### PR TITLE
VideoPress overhaul: new upgrade handling and video management.

### PR DESCRIPTION
**Pull request by zinigor**
This PR replaces and continues where #2438 left off. It will change how Jetpack works with WordPress.com in terms of VideoPress upgrades and video management. As a side effect it aims to fix the following issues: #2340, #2337, #1953, #1952, #1551.

### CODE REVIEW

**Comment by dereksmart** [comment]
@zinigor punt this?

**Comment by zinigor** [comment]
Yes, this has not had any attention in the 3.8 cycle.

**Comment by kraftbj** [comment]
@zinigor Is this PR/branch still valid with all of the VideoPress work being done?

**Comment by zinigor** [comment]
No, I don't think that's relevant anymore. I'll close this, thanks for digging it out!

**Pull request closed without merging**
