### PR TITLE
Support of tier type

### PR DESCRIPTION
**Pull request by millerf**
Fixes https://github.com/Automattic/gold/issues/192

## Proposed changes:

* Support "tier" type for NL

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply D126468-code on your sandbox
* Using https://github.com/Automattic/wp-calypso/pull/83433, create a tier plan on any site (JN, wpcom simple)
* Make sure the new plans were created with type `tier`  in wpsh
```
$only_tiers = true;
print_r(Memberships_Product::get_product_list(<your blog id>, null, null. $only_tiers);
```
* if you have an existing tier, edit it and make sure the type is modified
* create a paid-newsletter post with this new plan
* make sure you can subscribe as before
* optional: make sure you can subscribe also with previously created tiers
* Repeat with WPCOM simple if you tested with JN
* Repeat with JN if you tested with WPCOM simple

### CODE REVIEW

**Review by chrismccluskey — DISMISSED** [review]
This LGTM and seemed to work during testing. However, the test instructions don't seem to include testing this actual patch. When I downloaded this branch to sandbox, on top of the wpcom PR, I ran into some unexpected bugs. I think this may just need a trunk merge.

**Review by n3f — COMMENTED** [review]
I'm currently getting hung up at "create a paid-newsletter post with this new plan".  When I go to add/edit a post the memberships/status API call is failing.  I'm not sure why.

### Curl command
```sh
curl 'https://influential-goat.jurassic.ninja/wp-json/wpcom/v2/memberships/status?source=gutenberg&type=all&is_editable=true&_locale=user' \
  -H 'authority: influential-goat.jurassic.ninja' \
  -H 'accept: application/json, */*;q=0.1' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'cookie: wordpress_logged_in_fd238f836f07bfae098e22292d5c0003=demo%7C1699559781%7CFlQDeBhPlxZzEaFXV8YtH1bZmyJNVfYJPCq7jPVgSbP%7Cabeef650cf0a9466821dd776c7b11c432b0b3c3bf8a5439194713bdea2e40cef; tk_ai=jetpack%3AprZv1IARAHF6tJWXo5O8tmnp; wp-settings-time-1=1698358699' \
  -H 'pragma: no-cache' \
  -H 'referer: https://influential-goat.jurassic.ninja/wp-admin/post-new.php' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'x-wp-api-fetch-from-editor: true' \
  -H 'x-wp-nonce: 8b9ee0cee9' \
  --compressed
```

In my `/tmp/php-errors` I see: 

```txt
PHP Warning:  Declaration of Jetpack_Sync_WPCOM_Shadow_Replicastore::get_table_checksum_instance($table, $salt = NULL, $perform_text_conversion = false) should be compatible with Automattic\Jetpack\Sync\Replicastore::get_table_checksum_instance($table, $salt = NULL, $perform_text_conversion = false, $additional_columns = NULL) in /home/wpcom/public_html/wp-content/mu-plugins/jetpack/sync/class.jetpack-sync-shadow-replicastore.php on line 8407`, but I'm not sure if this is any symptom other than the code loading (seems to happen for every request) including `wpsh`. 
```

After rebasing the PR and rsync-ing all the code I still see the same thing.

### WPCOM

On WPCOM it's worse as the editor isn't even loading...

image

This is definitely caused by that PHP Warning as the JSON the editor is loading has been corrupted by that warning.  I wonder if there's a site setting I have enabled that's causing this error.  I don't see this problem on jetpack trunk though.

**Comment by millerf** [comment]
> I'm currently getting hung up at "create a paid-newsletter post with this new plan". When I go to add/edit a post the memberships/status API call is failing. I'm not sure why.
> 
> ### Curl command
> ```shell
> curl 'https://influential-goat.jurassic.ninja/wp-json/wpcom/v2/memberships/status?source=gutenberg&type=all&is_editable=true&_locale=user' \
>   -H 'authority: influential-goat.jurassic.ninja' \
>   -H 'accept: application/json, */*;q=0.1' \
>   -H 'accept-language: en-US,en;q=0.9' \
>   -H 'cache-control: no-cache' \
>   -H 'cookie: wordpress_logged_in_fd238f836f07bfae098e22292d5c0003=demo%7C1699559781%7CFlQDeBhPlxZzEaFXV8YtH1bZmyJNVfYJPCq7jPVgSbP%7Cabeef650cf0a9466821dd776c7b11c432b0b3c3bf8a5439194713bdea2e40cef; tk_ai=jetpack%3AprZv1IARAHF6tJWXo5O8tmnp; wp-settings-time-1=1698358699' \
>   -H 'pragma: no-cache' \
>   -H 'referer: https://influential-goat.jurassic.ninja/wp-admin/post-new.php' \
>   -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'sec-ch-ua-platform: "macOS"' \
>   -H 'sec-fetch-dest: empty' \
>   -H 'sec-fetch-mode: cors' \
>   -H 'sec-fetch-site: same-origin' \
>   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
>   -H 'x-wp-api-fetch-from-editor: true' \
>   -H 'x-wp-nonce: 8b9ee0cee9' \
>   --compressed
> ```
> 
> In my `/tmp/php-errors` I see:
> 
> ```
> PHP Warning:  Declaration of Jetpack_Sync_WPCOM_Shadow_Replicastore::get_table_checksum_instance($table, $salt = NULL, $perform_text_conversion = false) should be compatible with Automattic\Jetpack\Sync\Replicastore::get_table_checksum_instance($table, $salt = NULL, $perform_text_conversion = false, $additional_columns = NULL) in /home/wpcom/public_html/wp-content/mu-plugins/jetpack/sync/class.jetpack-sync-shadow-replicastore.php on line 8407`, but I'm not sure if this is any symptom other than the code loading (seems to happen for every request) including `wpsh`. 
> ```
> 
> After rebasing the PR and rsync-ing all the code I still see the same thing.
> 
> ### WPCOM
> On WPCOM it's worse as the editor isn't even loading...
> 
> image
> 
> This is definitely caused by that PHP Warning as the JSON the editor is loading has been corrupted by that warning. I wonder if there's a site setting I have enabled that's causing this error. I don't see this problem on jetpack trunk though.

Is your sandbox up-to-date? Did you sync this PR on WPCOM (with `jetpack-downloader`)?

**Comment by millerf** [comment]
> This is definitely caused by that PHP Warning as the JSON the editor is loading has been corrupted by that warning. I wonder if there's a site setting I have enabled that's causing this error. I don't see this problem on jetpack trunk though.

It is a known issue unrelated to this PR ... I can't paste the link, Tampermonkey is acting up

**Comment by pottedmeat** [comment]
NOTE: When I edited plans, I had to restart wpsh because the previous result was cached.

**Comment by pottedmeat** [comment]
image

**Comment by millerf** [comment]
> image

Yes, that is not related to us...

**Review by n3f — APPROVED** [review]
WFM 👍

**Review by pottedmeat — APPROVED** [review]
Code looks good and tested successfully.

**Comment by millerf** [comment]
> image

Fixed in https://github.com/Automattic/jetpack/pull/33863

**Pull request merged**
