### PR TITLE
General: update requirements to match upcoming WP 6.0 release

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* Update required WordPress version to WP 6.0 -1 (5.9)
* Update tested up to version to WP 6.0

#### Jetpack product discussion

* See #24082

#### Does this pull request change what data or activity we track or use?

* N/A

#### Testing instructions:

* Is CI happy?
* Are the numbers correct?

### CODE REVIEW

**Comment by kraftbj** [comment]
Adding the `Needs Cherry-Pick` for the 10.9.x 6.0 compact. Do not cherry-pick before 10.9 stable ships.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
At the end of my day, but need to address the WP.com side of things. Looks like the conditional check we added for WP 6.0 is throwing on WP.com.

My first guess is WP.com is reporting as 6.0-alpha without having yet the commit we're handling here.

**Comment by jeherve** [comment]
> My first guess is WP.com is reporting as 6.0-alpha without having yet the commit we're handling here.

Yup, that's it.

Internal references:
- p94tqY-rU-p2
- rWPGIT5cce3fb0b3979fcea5c1c7655f21201efd0a9769

Should we wait a bit with ours, or should I skip the test on WordPress.com for now?

**Comment by jeherve** [comment]
> Should we wait a bit with ours, or should I skip the test on WordPress.com for now?

I marked the tests as skipped in 1437593cdc9763a9fe459b24d3c98a9a6029ecc0

**Review by kraftbj — DISMISSED** [review]

**Comment by kraftbj** [comment]
Let's hold to merge this until Tuesday when we also bump the Composer version. We'll need to change the required test to `trunk` instead of `master`. This isn't urgent IMO so we can align it with the already existing infra bump.

**Comment by jeherve** [comment]
I'll need to rebase this once #24224 gets merged.

**Comment by kraftbj** [comment]
I'll work on landing 24224 right now so we can have this ready to merge at the same time as the #23908 to avoid folks having to bump their PRs too many times.

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
r244861-wpcom

**Comment by kraftbj** [comment]
Noting the `id` to `ID` changes made in this PR are no longer necessary; however, I think we should leave it. 

Perk is older versions of Jetpack won't face any oddities due to the original issue.  https://core.trac.wordpress.org/changeset/53362

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-10.9` in a0b9931ea77b188234c90fd174708fd011c5984e

**Pull request merged**
