### PR TITLE
Renovate: Update various packages

### PR DESCRIPTION
**Pull request by kraftbj**
Looking to update a number of packages at once to avoid a lot of little WP.com commits. Picked up the update that passed tests.

#### Changes proposed in this Pull Request:
* n/a

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* n/a

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by mdawaffe** [comment]
There's some package duplication. For example, `eslint-plugin-react` looks like it only needs `7.14.3` but is also installing `7.14.2`. (`yarn` is weird about dependencies sometimes: I don't know why.)

Is that just a dev issue, or does it increase the size of the JS files we ship with Jetpack?

**Comment by kraftbj** [comment]
The duplication comes from dependencies require specific versions.

````
=> Found "eslint-plugin-react@7.14.3"
info Has been hoisted to "eslint-plugin-react"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "876KB"
info Disk size with unique dependencies: "2.48MB"
info Disk size with transitive dependencies: "3.79MB"
info Number of shared dependencies: 21
=> Found "@wordpress/eslint-plugin#eslint-plugin-react@7.14.2"
info This module exists because "@wordpress#eslint-plugin" depends on it.
info Disk size without dependencies: "872KB"
info Disk size with unique dependencies: "2.48MB"
info Disk size with transitive dependencies: "3.78MB"
info Number of shared dependencies: 21
````

For the devDeps, that just impacts what's happening when building. For regular dependencies, since we only ship the final built things, it shouldn't matter, but I think that's the state of the world of js packages.

**Review by mdawaffe — APPROVED** [review]
`@wordpress/eslint-plugin` uses caret notation for `eslint-plugin-react`, so yarn should be able to deduplicate them. I don't know why it doesn't.

I agree that devdeps mostly don't matter. If there's nothing similar in deps, we're fine.

**Comment by kraftbj** [comment]
It's weird to me since the version of `@wordpress/eslint-plugin` we're using is carot'd to 7.12.x per https://github.com/WordPress/gutenberg/blob/41a5b4cf054ac13ff434fedbc9c0bd508dcfeeaa/packages/eslint-plugin/package.json

In any case, thanks for the check.

**Pull request merged**
