### PR TITLE
Jetpack Plugin Visual Refresh: About page

### LINKED ISSUE #29834: Jetpack Plugin Visual Refresh: About page
`/wp-admin/admin.php?page=jetpack_about`. It's. not react. 

No words were used to describe the changes. Just a screenshot. 
p1HpG7-lx8-p2#about-page

Image

### PR DESCRIPTION
**Pull request by bindlegirl**
- Updated CSS styles for About us page

Fixes #29834

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to  About us and see if it matches expected look
* Check CSS and see if changes make sense

### CODE REVIEW

**Comment by sergeymitr** [comment]
Looks great!
One tiny thing I noticed: the "our WordPress.org profile" link in the bottom doesn't change the text underline thickness as other links do.
Once you fix this, feel free to merge into the feature branch.

**Comment by bindlegirl** [comment]
Thanks for checking it Sergey! Good catch, I missed that one.

**Comment by jeffgolenski** [comment]
@bindlegirl Outstanding work!!! I know this branch has been merged, but I'm wondering if we could just make a couple more adjustments in a new PR? Nothing major, you did such a precise job! If they're already being handled elsewhere, feel free to ignore. 

1. Can you make the "Back to the Jetpack Dashboard" link black?
2. Can all the links be black, and underlined, throughout all the content? Plugin titles should be black, but not underlined 
3. Can we include external link icons in all links in the content area that take the user out of wp-admin? (4 in the main content area, and all "more details" links in the plugin cards) I omitted this in my designs, I apologize. The external icon is present in the new main nav that Sergey just built!
4. The buttons should be the updated Emerald style secondary buttons (I'm assuming these are in another PR?)

THANK YOU!

**Comment by bindlegirl** [comment]
@jeffgolenski I also found a couple of things to fix (focus colors on buttons for one), so I'll definitely be revisiting this page 😄 

Just a couple of clarifications

>Can all the links be black, and underlined, throughout all the content? Plugin titles should be black, but not underlined

Not sure I understand which links you mean. All links are black and underlined and plugins are black but not underlined. Just making sure we see the same thing:

Screenshot 2023-04-21 at 20 36 38

>Can we include external link icons in all links in the content area that take the user out of wp-admin? (4 in the main content area, and all "more details" links in the plugin cards) 

Just to clarify, the More details links are not taking users out of wp-admin so they don't need the icon?

**Comment by jeffgolenski** [comment]
> Not sure I understand which links you mean. All links are black and underlined and plugins are black but not underlined. Just making sure we see the same thing:

@bindlegirl Ah, I'm seeing something different. I tested the page in the `feature/jetpack-visual-refresh` branch tho, since `refresh/about-us` was merged. Here's what I'm seeing:




Screen Shot 2023-04-24 at 11 44 35 AM


> Just to clarify, the More details links are not taking users out of wp-admin so they don't need the icon?

Yes, you're right! My mistake. Ignore that request. Thank you!

**Comment by bindlegirl** [comment]
@jeffgolenski That looks like the old/unchanged About page. Do you need to run build after checking out the branch?

**Comment by sergeymitr** [comment]
The feature branch used to have a conflict with `trunk` which prevented it from being updated in Jetpack Beta.
I merged `trunk` into it, so everything is fine now, but you might need to update it in Jetpack Beta.

Also, the About page changes didn't kick in for me until I cleared the cache via Ctrl+Shift+R, so that might also be the cause.

**Comment by jeffgolenski** [comment]
@bindlegirl @sergeymitr Thank you both for working with me to diagnose the issue. All good now. My only ask is that we update the "Back to Jetpack Dashboard" link to be `gray 70` (3C434A). Everything else is perfect! 

about-page-review

**Pull request merged**
