### PR TITLE
Update blocks to v16

### PR DESCRIPTION
**Pull request by sirreal**
Includes some 7.2 fixes for the `jetpack-blocks` package. Released from https://github.com/Automattic/wp-calypso/pull/31793/commits/b2d8841596197b48a4ce9fa89279a0b1ae92ba6e

### CODE REVIEW

**Review by jeherve — APPROVED** [review]

**Comment by sirreal** [comment]
Bumped to 16.0.1 which includes changes from #11755

**Review by jeherve — APPROVED** [review]

**Comment by simison** [comment]
Does this need to be rebased with master because of https://github.com/Automattic/jetpack/pull/11741?

I see some white space changes in package.json here.

**Comment by sirreal** [comment]
😩 Fixed whitespace change. I'm lost without prettier.

**Review by simison — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
still green. :)

**Pull request merged**
