### PR TITLE
Media Summary: Get the excerpt by post

### LINKED ISSUE #8420: PHP 7.2: Warning: count(): Parameter must be an array or an object that implements Countable in...
**I myself can not replicate this issue.** 
The error and steps are based on what I collect from various sources: 

### Steps to reproduce the issue

1. Activate Jetpack on PHP 7.x. 
2. Check log there is an error. 

```
'Warning: count():
Parameter must be an array or an object that implements Countable in
wp-includes/post-template.php on line 284'.
```
3. Using PHP 5.6.x, no issue. 

### What I expected

No warning at all in both PHP 5.6.x and PHP 7.x. 

### What happened instead

The error above with PHP 7.x. 

### More info

* 863780-zen
* https://core.trac.wordpress.org/ticket/42814
* https://wordpress.org/support/topic/jetpack-errors-on-install-with-publicise/

### LINKED ISSUE #9209: Filter 'get_the_excerpt' is called with a missing argument
I experienced a fatal error on a site from [class.media-summary.php's usage of the `get_the_excerpt` filter](https://github.com/Automattic/jetpack/blob/d6846b492329cc6436ee9db93d8a44b32476e2f7/_inc/lib/class.media-summary.php#L314). The `'get_the_excerpt'` filter is being applied with only one argument, not matching [how core uses that filter](https://github.com/WordPress/WordPress/blob/921e131eae45801b8fdb1ecfceb5d7839fdfd509/wp-includes/post-template.php#L402-L411).

Since Jetpack isn't using a core filter as it is intended, it's relatively easy for themes and plugins to encounter a conflict with Jetpack, causing a site to encounter this fatal error.

Relates to #8510, which would render this moot, but is currently on hold.

### PR DESCRIPTION
**Pull request by kraftbj**
WP 4.5 allows `get_the_excerpt` to be returned specific to a post.

Fixes #8420 
Fixes #9209

Originally, `get_the_excerpt` only returned the global $post from within the loop, so we used the filter, which ended up tripping us up in 8420. WP 4.5 added the ability to use `get_the_excerpt` for a specific post, which allows us to skip the filter bit completely.

### CODE REVIEW

**Comment by kraftbj** [comment]
Holding this PR as `In Progress` pending the discussion in https://core.trac.wordpress.org/ticket/42814#comment:17 and following comments. This PR addresses part of the issue of 8420—Jetpack doing this in an unexpected-to-Core way—but an underlying Core issue would still result in the same notice.

**Comment by zinigor** [comment]
This makes lots of sense to me, except it will disable excerpts for posts that do not have one - right now we disregard the excerpt and just get a new one from post content. Perhaps there were other concerns as well. @justinshreve as an original author, can you remember why you initially chose to use the filter instead of just getting an excerpt?

**Comment by justinshreve** [comment]
@zinigor I'm not sure now, sorry!

**Comment by mboynes** [comment]
Also relevant: https://core.trac.wordpress.org/ticket/36934

**Comment by kraftbj** [comment]
> This makes lots of sense to me, except it will disable excerpts for posts that do not have one - right now we disregard the excerpt and just get a new one from post content

@zinigor I looked closer and I think this is something that is, all in all, a Core problem. `get_the_excerpt` has `wp_trim_excerpt` attached to it, except it doesn't expect to be called outside the loop either.

I'm going to re-take a look at the Core tickets since they stalled out. It makes sense to me for this to be ultimately fixed there, but we likely just need to ship something for 7.2 compat in the meantime.

**Comment by zinigor** [comment]
This seems to be already implemented by #9348, yet still not handled very well in Core when outside of the loop.
Let's close this one and see what changes in the next several Core releases.

**Comment by kraftbj** [comment]
I'm reopening since https://core.trac.wordpress.org/changeset/44941 landed.

**Comment by jeherve** [comment]
I'll close this PR for now because of the lack of activity on this. We can always reopen in the future if needed, but it will need a rebase, so it may be easier to start a new PR at this point.

**Pull request closed without merging**
