### PR TITLE
Memberships: instruct WP Super cache to not cache membership posts

### PR DESCRIPTION
**Pull request by simison**
Follow up to https://github.com/Automattic/jetpack/pull/35372#discussion_r1473017981

## Proposed changes:

* Adds a method to bust cache with WP Super Cache plugin ([FAQ](https://jetpack.com/support/wp-super-cache/wp-super-cache-faq/))
    * Jetpack Boost Cache [is handled with this same constant](https://github.com/Automattic/jetpack/issues/35497#issuecomment-1931721738).
* Requests plugins not to cache when the page has either a paywall, or the subscribe block and:
   * User is a subscriber
   * User is logged in, even if they aren't subscribed and thus don't have the JWT auth token cookie set.
When user is subscribed 

Later on need to look also what other [common cache plugins](https://wordpress.org/plugins/search/cache/) require.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* See https://github.com/Automattic/jetpack/pull/35372

### CODE REVIEW

**Review by millerf — CHANGES_REQUESTED** [review]
As said [here](https://github.com/Automattic/jetpack/pull/35372#discussion_r1473081920), this is not the right approach.

The issue is not only about when to cache, but when to also access said cache.

**Comment by simison** [comment]
@millerf sure, no problem — could you advice how to proceed alternatively?

**Comment by simison** [comment]
Later on we can add more sophisticated support for WP Super cache to cache each types of responses separately (free, subscribers only, paid members only). Instructions: https://jetpack.com/support/wp-super-cache/developer-documentation-for-wp-super-cache/#the-cookies-used-to-identify-visitors

**Comment by millerf** [comment]
> @millerf sure, no problem — could you advice how to proceed alternatively?

Yes, it is written in the same comment: https://github.com/Automattic/jetpack/pull/35372#discussion_r1473081920

```
If there is a strong case to support SC, I am happy to create a project for it.
```

**Comment by simison** [comment]
@millerf I meant code-wise, can you unpack _"The issue is not only about when to cache, but when to also access said cache."_ a bit more to me, and how would you prefer implementation look like instead?

I.e. what exactly should I change with this PR's implementation?

For these couple lines, I don't think we'd need a project, and we're happy to chime in with a bit of code here. To support more full set of caching plugins, sure, a project might make sense.

**Comment by simison** [comment]
Updated the PR to cover also Subscribe block, similar to https://github.com/Automattic/jetpack/pull/35510 which ended up not needed.

**Comment by millerf** [comment]
@simison Sorry, I have been stuck into a stream of calls.

Let me explain the issue with your approach: you are preventing the paywalled data to be put in the cache, and that is great. However, you code will more than likely never be reached. 

Let's write down a "normal" use case of a user accessing the paywalled data (more or less the test instructions recommended here: https://github.com/a8cteam51/public/issues/360 )

(brand new browser window - user does not have the token but has an account with a subscription for paid-content )
- User gets access to `mywsite.com/paywalled-content` and receives the public version
-> Super Cache caches the data
- User logs in, page gets reloaded with the same URL
-> Super cache servers the cached public data, not the paid content

I hope that makes my previous sentence clearer:
```
The issue is not only about when to cache, but when to also access said cache.
```

One way to approach this is to disable the whole cache (serving cache and caching) when the token is available. That requires some investigation to know how SC is initiated and if/how it can be bypassed altogether. The documentation references the plugins is bypassed when a user is logged in, but investigation is needed to know if it checks for `wp_*` cookie, or something else. Maybe it check for `wordpress_*`, and therefore renaming the JP premium cookie with this prefix would be enough.

Please close this PR and I'll spin up a couple of tasks to investigate the right approach and implement it.

**Comment by millerf** [comment]
Closed in favor of https://github.com/Automattic/jetpack/pull/35598

**Comment by simison** [comment]
Excellent, thanks for elaborating — much appreciated.

> Please close this PR and I'll spin up a couple of tasks to investigate the right approach and implement it.

Nice! I enjoy when folks just jump to coding too so thanks for doing that. :-)

While all cache plugins are important due to sensitivity of the data that could be leaked through cached pages (other user's emails, or paywalled content), WP Super Cache and Jetpack Boost are important because they're in-house products so we need to make sure we are compatible with those out-of-the-box, similarly to our WP.com internal caching mechanisms.

**Comment by millerf** [comment]
> WP Super Cache and Jetpack Boost are important because they're in-house

Yes, I do agree. I figured it out when I started to work on it :)

> Nice! I enjoy when folks just jump to coding too so thanks for doing that. :-)

Please note that I offered to create a task for this here: https://github.com/Automattic/jetpack/pull/35372/files#r1473081920
Those random and non-tested PRs are just a loss of time for everyone, unfortunately.

**Pull request closed without merging**
