### PR TITLE
Top Posts: add an option to choose what Post Types to display

### PR DESCRIPTION
**Pull request by jeherve**
This is only a first pass, trying to support CPTs as well.
I've also removed the code that excluded attachment pages,
since people would now be able to exclude them in the widget options.

Unfortunately, that patch doesn't work at the moment. I've been trying to understand why, but I must be missing something. I must not be saving the form properly. I would appreciate a second set of eyes on this.

Original trac ticket:
http://plugins.trac.wordpress.org/ticket/1797

### CODE REVIEW

**Comment by omriamos** [comment]
Hi,

Any updates with this?
I keep seeing my static homepage (and some other pages) at the top of the list, and it's annoying...  I want to 'top posts' to show only posts and not pages...

thanks

**Comment by jeherve** [comment]
@omriamos The Top Posts & Pages Widget now includes an option to choose whether you want posts, pages, or both to be displayed in the widget. We've added that option to the widget's settings last year, in Jetpack 3.6.

You can find out more about the widget here:
https://jetpack.com/support/extra-sidebar-widgets/top-posts-pages-widget/

**Comment by omriamos** [comment]
Oh.... So I was actually talking about something else.
I'm talking about jetpack's Site Stats widget on the wordpress Dashboard, that shows recent statistics, top searches and top posts (and.... pages).

**Comment by jeherve** [comment]
@omriamos That is indeed something else. That Stats widget is meant to return a list of the most popular pages on your site, regardless of their post type. We don't plan on changing that, though.

**Pull request closed without merging**
