### PR TITLE
Starter Plugin: Configure Sync to only sync minimum required data

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

* In our starter plugin, configure sync to the minimal amount of data that needs to be synced

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Enable only Jetpack Starter Plugin
* Enable Jetpack Debug helper plugin
* Connect
* Go to Jetpack Debug > Sync Data Settings Tester
* Confirm you see a small list of thing and 4 items under jetpack_sync_callable_whitelist

### CODE REVIEW

**Comment by kbrown9** [comment]
What's the best way to test the Starter plugin? I'm running the bleeding edge version of the Jetpack Beta Tester plugin, and I don't see the Starter plugin in the settings.

The code changes look correct to me, but I'd still like to test them.

**Comment by kbrown9** [comment]
What's the best way to test the Starter plugin? I'm running the bleeding edge version of the Jetpack Beta Tester plugin, and I don't see the Starter plugin in the settings.

The code changes look correct to me, but I'd still like to test them.

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by oskosk** [comment]
@kbrown9 right now the plugin should be listed on the Jetpack Beta plugin. But it's probable that this branch is not available for the plugin yet. Just pushed a rebase to re-trigger builds. Should show afterwards.

image

**Review by oskosk — APPROVED** [review]

**Pull request merged**
