### PR TITLE
Stats: fix encoding issue

### PR DESCRIPTION
**Pull request by jeherve**
As per https://twitter.com/BarisUnver/status/585162275486621698

cc @barisunver Could you give us more details about this encoding issue, where it appeared, and how we can reproduce and test?

Thanks!

P.S.: if you want to start playing with Git and submit patches, you can follow our guide [here](https://github.com/Automattic/jetpack/blob/master/CONTRIBUTING.md)!

### CODE REVIEW

**Comment by barisunver** [comment]
Hey @jeherve,

It's the Turkish characters for me but it's a problem of (probably) all non-Latin characters because I see [more people encountering the encoding problem](https://www.google.com.tr/search?q=jetpack+stats+encoding).

It basically shows weird characters instead of Turkish (or all non-Latin) characters. Here's an example from the dashboard widget:

image

It's clearly an encoding problem that happens while getting content with AJAX. As you can see, the characters in the button is crippled as well, meaning that **all** AJAX content is affected, not just the ones that are fetched from WP.com servers. I searched for "ajax utf-8 problem" and applied one of the solutions and, yay, it worked this time!

I never understood the reason of this problem because it literally popped out of nowhere over a year ago. It's a strong possibility that a change in my server caused it but it looks like a common problem (not *very* common, but common nonetheless).

Anyways, thanks for making the commit for me! Remember that it only affects the Stats page and not the dashboard widget - you'll need another patch for that. I would, but I couldn't do it - I'm very bad at JavaScript.

Cheers!

**Comment by jeherve** [comment]
Thanks for the extra details. For reference, this is linked to ticked ID 1975657.

**Comment by zinigor** [comment]
I can not reproduce that issue using either Russian or Turkish languages, the stats widget always get served with a proper `charset=UTF-8` header. Which leads me to think that the problem is best be solved by explicitly specifying the response header when we output the widget HTML code.

**Comment by samhotchkiss** [comment]
Punting to 3.5.1

**Comment by dereksmart** [comment]
@barisunver, following the forums where other people had this problem, some said that this fixed it for them.  Can you try it and let us know if it works? 

http://codex.wordpress.org/%D0%A7%D0%90%D0%92%D0%9E/%D0%9F%D1%80%D0

**Comment by dereksmart** [comment]
punting until we hear back.  There may be an .htaccess fix for this (see link in comment above)

**Comment by samhotchkiss** [comment]
Closing this for now.  @barisunver, if you're still having this issue with Jetpack 3.6, please let us know and we can re-open.

**Pull request closed without merging**
