### PR TITLE
My Jetpack: do not enable Licensing UI if My Jetpack is disabled

### LINKED ISSUE #25666: Licensing: dashboard should not link to My Jetpack on Multisite
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Start with a site that's part of a Multisite network.
2. Connect your site to WordPress.com.
3. Go to https://cloud.jetpack.com/pricing and purchase a plan; do not attach it to any site yet.
4. Go back to your site's WP-Admin
5. Go to Jetpack > Dashboard > My Plan
6. Click on the link to activate a product

You will be redirected to My Jetpack (and get a permissions error), even though My Jetpack does not support Multisite (see #23069):
https://github.com/Automattic/jetpack/blob/3571cd046bcbf03b898df0e1b8c073f10416e183/projects/packages/my-jetpack/src/class-initializer.php#L222

### A clear and concise description of what you expected to happen.

Since My Jetpack is not available, I would expect to stay in the Jetpack dashboard.

### What actually happened

_No response_

### Browser

_No response_

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #25666

#### Changes proposed in this Pull Request:

This is true for Multisite environments, for example. If My Jetpack isn't available, the licensing UI in My Jetpack should not be available either.

> **Note**
> Beyond this PR, this brings the question of whether the licensing UI should be shown on multisite environments in the Jetpack dashboard.
> This question is somewhat related to this discussion: p1659447314971209-slack-CS8UYNPEE
> @Automattic/jetpack-origin Would you have an opinion on this?

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

1. Start with a site that's part of a Multisite network.
2. Connect your site to WordPress.com.
3. Go to https://cloud.jetpack.com/pricing and purchase a plan; do not attach it to any site yet.
4. Go back to your site's WP-Admin
5. Go to Jetpack > Dashboard > My Plan
6. Click on the link to activate a product
7. You should not be redirected to a My Jetpack page

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
@Automattic/jetpack-genesis would be the right team to take this call.

**Review by kraftbj — DISMISSED** [review]
Looks good to me. Waiting for Genesis to sign off.

**Comment by rcanepa** [comment]
> Beyond this PR, this brings the question of whether the licensing UI should be shown on multisite environments in the Jetpack dashboard.

I think we should enable the licensing UI since Search, Anti-spam, and VideoPress are compatible with multisite networks.

What would happen if a user activates a license from `/wp-admin/admin.php?page=my-jetpack#/add-license` and My Jetpack is not available? Would the user still be redirected to My Jetpack?

I tried to replicate the issue, but I couldn't. What Jetpack product was bought when this happened? I tried with VideoPress, however, I wasn't redirected to My Jetpack after activating it.

**Comment by jeherve** [comment]
> What would happen if a user activates a license from `/wp-admin/admin.php?page=my-jetpack#/add-license` and My Jetpack is not available? Would the user still be redirected to My Jetpack?

You're redirected to the My Jetpack page, but since it isn't registered all you get is an error page:

https://user-images.githubusercontent.com/426388/185857148-f0ee3a3b-ff88-4f6c-93c6-6f4748e41bd2.mov

> What Jetpack product was bought when this happened? I tried with VideoPress, however, I wasn't redirected to My Jetpack after activating it.

The product you bought doesn't matter here, since the issue is with the My Jetpack page not being available.

**Comment by rcanepa** [comment]
> You're redirected to the My Jetpack page, but since it isn't registered all you get is an error page:

Thanks for the recording. I understand the issue now.

**Review by rcanepa — DISMISSED** [review]
LGTM as well. 

I don't see any problem with these changes, and the issue is fixed.

**Comment by bindlegirl** [comment]
I updated the package version so the tests can pass.

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
