### PR TITLE
JS Components: Add RNA ConnectButton story

### PR DESCRIPTION
**Pull request by retrofox**
Simple PR that adds a story to the `<ConnectButton />` component.

* Depends on https://github.com/Automattic/jetpack/pull/23921
* Part of Part of https://github.com/Automattic/jetpack/issues/23708

#### Changes proposed in this Pull Request:

* JS Components: Add RNA ConnectButton story

#### Testing instructions:

* Use Storybook
* Confirm you see the ConnectButton component there
image

### CODE REVIEW

**Review by renatoagds — COMMENTED** [review]
The description says that the PR is only to add storybook for connected button. But looking at the changes you're doing more things, that I'm not understanding fully. Can you update to match everything that you're doing here? 

If this depends on other PR, point this PR to the other PR branch, this way Github will show only what is being added here and will update to master as soon that branch get merged.

**Comment by retrofox** [comment]
> The description says that the PR is only to add storybook for connected button. But looking at the changes you're doing more things, that I'm not understanding fully.

The PR is still `in progress`.

Can you update to match everything that you're doing here?

sure thing, once it's ready for review.

> If this depends on other PR, point this PR to the other PR branch, this way Github will show only what is being added here and will update to master as soon that branch get merged.

I think adding a comment in the PR description should work, too.

image

**Comment by renatoagds** [comment]
> The PR is still in progress.

Ok, so let's move it to draft mode? And remove the request for review. This will avoid notification since it's not ready yet.

**Comment by retrofox** [comment]
> > The PR is still in progress.
> 
> Ok, so let's move it to draft mode? And remove the reviewers. This will avoid notification since it's not ready yet.

I can do that. I though the `In Progress` label was enough. Sorry about the notifications.

**Pull request closed without merging**
