### PR TITLE
Update some REST API endpoints documentation

### PR DESCRIPTION
**Pull request by oskosk**
Fixes erroneous references about some endpoints in `rest-api.md`.
#### Changes proposed in this Pull Request:
- Updates `rest-api.md` changing the endpoints URLs that were renamed by previous PRs
#### Testing instructions:
- 
#### Why

The PR which introduced this docs,was merged before the API changes were taken in account in the API reference.

### CODE REVIEW

**Comment by eliorivero** [comment]
@oskosk as of now this is good to go. Is there anything else you want to add? Otherwise you can just merge this.

**Comment by samhotchkiss** [comment]
I agree with @jeherve 

Jeremy, if Osk doesn't respond in the next day, would you mind just making that change?  Feel free to merge once you have.

**Comment by eliorivero** [comment]
I'm updating this...

**Comment by eliorivero** [comment]
File moved and link updated. Merging!

**Pull request merged**
