### PR TITLE
Admin Page: Modularize Redux init into separate helper class

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
Refactors the Redux initialization code into a staticized helper class.

This is in preparation for a new Jetpack Search wp-admin dashboard, which will re-use the existing Admin Page Redux code -- see #19810 as a working example. At the very least, this change improves code readability and fixes several linting errors.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* (These changes should not affect functionality.)
* Apply these changes to your Jetpack site. Ensure that the Admin Pages (both the Dashboard and the Settings pages) all work as expected.
* Additionally, check the browser console and ensure that the `window.Initial_State` object has been properly populated.

### CODE REVIEW

**Comment by jsnmoon** [comment]
I went ahead and requested a Crew review because I didn't know who else to ask. If you have a reviewer recommendation, please feel free to add them to the PR!

**Review by jeherve — DISMISSED** [review]
This looks good to me, and seems to test well. 🚢

**Comment by jsnmoon** [comment]
Just merged the latest master to pull in changes from #19633. This likely necessitates another review, unfortunately 😅  

I verified the correctness of the `Jetpack_Redux_State_Helper` class by ensuring that the `Initial_State` value of this branch matches the `Initial_State` value of the master branch.

**Review by sergeymitr — APPROVED** [review]
Great refactoring, thanks for doing this! 🚢

**Pull request merged**
