### PR TITLE
Jetpack Visual Refresh: header and navigation

### LINKED ISSUE #29838: Jetpack Plugin Visual Refresh: Header and nav
The header and nav components should look consistent to My Jetpack. 

There wasn't a specific section or call-out for this, it just intuitive to break it into it's own issue in case someone wants to take it separately. 

p1HpG7-lx8-p2

Image

### PR DESCRIPTION
**Pull request by sergeymitr**
Fixes #29838

## Proposed changes:
* Update Jetpack header and navigation design

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p1HpG7-lx8-p2

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
Visit the pages and confirm the header and top navigation look in accordance with the design (see #29838).

Some of the most important pages in both Desktop and Mobile modes:

- [ ] Jetpack Dashboard
- [ ] Settings
- [ ] Modules
- [ ] License Activation
- [ ] Jetpack Dashboard under a non-admin user
- [ ] Jetpack Dashboard for non-connected secondary admin user

### CODE REVIEW

**Review by bindlegirl — DISMISSED** [review]
Looks great!

**Comment by bindlegirl** [comment]
Just one thing I noticed on WoA dev site:

Screenshot 2023-04-14 at 13 16 31

I'm guessing the breakpoints are different because it happens only at a certain screen size.

**Comment by sergeymitr** [comment]
Hi @bindlegirl.
I fixed the WoA problem, can you please give it another look.

**Review by bindlegirl — APPROVED** [review]
@sergeymitr Thanks for fixing that! Looks good

**Pull request merged**
