### PR TITLE
Contact Form: Sync `feedback` CPT

### PR DESCRIPTION
**Pull request by lezama**
Sync 'feedback' CPT when "Contact Form" is active.

### CODE REVIEW

**Comment by georgestephanis** [comment]
@lezama @beaulebens -- just for future reference, is there a write-up somewhere of why we need feedbacks synced?  Is it for parity in the wpcom dashboard experience with wpcom sites?

**Comment by lezama** [comment]
> Is it for parity in the wpcom dashboard experience with wpcom sites?

Exactly

**Comment by georgestephanis** [comment]
Can we perhaps only sync if  they also have Manage opted in to?  I hesitate to silently start syncing up all new private contact form responses.

**Comment by georgestephanis** [comment]
Reverted after discussion with @beaulebens in Slack, let's try this again for 3.5.

**Pull request merged**
