### PR TITLE
[Boost] Switch to standard Jetpack build pipeline

### PR DESCRIPTION
**Pull request by thingalon**
Fixes 35017 and 35016

Shift Boost over to using the standard webpack-based build pipeline, in line with the rest of Jetpack. Moves the remaining svelte-build stuff for the Image Guide UI out to its own package to avoid complicating Boost's own compilation.

## Proposed changes:
* Shift Boost over to using the standard webpack-based build pipeline
* Move the remaining svelte-build stuff for the Image Guide UI out to its own package

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Make sure it builds and the basic features still work.

### CODE REVIEW

**Comment by thingalon** [comment]
~The failing E2E test is one plaguing all of our PRs and shouldn't be a blocker to this getting reviewed and merged. I'm chasing down the E2e error in a separate PR.~

All green now!

**Review by pyronaur — APPROVED** [review]
Looks good, although I'm not sure why is image guide UI needed in our webpack if it's a separate package.

**Review by haqadn — COMMENTED** [review]
Wow this is fast!

This build of image guide breaks the ISA hydra though. This is because the library was previously being built as umd `ImageGuideLibrary`. Maybe we can address this separately?

**Comment by thingalon** [comment]
> This build of image guide breaks the ISA hydra though. This is because the library was previously being built as umd `ImageGuideLibrary`. Maybe we can address this separately?

I'll take care of it today :)

**Comment by thingalon** [comment]
> This build of image guide breaks the ISA hydra though. This is because the library was previously being built as umd `ImageGuideLibrary`. Maybe we can address this separately?

I've tried and tried and can't seem to replicate this issue in the latest trunk boost cloud. Can you give me steps to replicate?

**Comment by haqadn** [comment]
> I've tried and tried and can't seem to replicate this issue in the latest trunk boost cloud. Can you give me steps to replicate?

I copied the contents of the package after building from monorepo and replaced the package content(in `node_modules/@automattic/jetpack-image-guide`) on hydra with it, so hydra would use the in-progress version. @thingalon

**Pull request merged**
