### PR TITLE
Subscriber Login: Remove the premium content cookie specified for the blog on logging out

### PR DESCRIPTION
**Pull request by pkuliga**
Part of https://github.com/Automattic/jetpack/issues/34884

## Proposed changes:

In some cases user is not logged out after clicking "Log out", this change fixes it by removing also the premium content cookie specified for the blog.

Tested it on simple and self-hosted sites.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Make sure the logging out works as expected for subscribed and not subscribed users.

### CODE REVIEW

**Comment by simison** [comment]
Added Gold to reviewers as a FYI and in case they'd had feedback

**Comment by millerf** [comment]
These changes have no impact whatsoever to Monetize.

How does that button differ from [the login button that already exists](https://github.com/Automattic/jetpack/tree/7bd0423394866ab1d7a4a5c74bcc6e6dfc542593/projects/plugins/jetpack/extensions/blocks/premium-content/login-button)? Why didn't you extend it to add the logout feature?

**Comment by simison** [comment]
@millerf we don't really want to hijack the core login block experience and flows, especially on Jetpack sites.

With member login block we have more flexibility with the UX.

**Comment by millerf** [comment]
@simison What do you mean? How does your block flow differ from the one in premium content?

**Comment by simison** [comment]
@millerf ah I glossed over the link, and thought you referred to core login block! We'll review :-)

**Comment by millerf** [comment]
> @millerf ah I glossed over the link, and thought you referred to core login block! We'll review :-)

I know. If feels like using the term "login" here is quite confusing.

**Comment by millerf** [comment]
@simison Let's remove the duplication of buttons.

I am still unsure what are the features of your button, but I would like them to be merged with the actual "login" button from the Premium content.
There is already enough complexity, we should prevent duplicating features as well. If I am not misunderstanding, your new button does exactly what the other one does, right?

CC @jeherve

**Comment by simison** [comment]
> I would like them to be merged with the actual "login" button from the Premium content.

Yup, agreed. We've been busy with other project meanwhile but we'll get back to the login block soonish, too.

**Comment by millerf** [comment]
> We've been busy with other project meanwhile but we'll get back to the login block soonish, too.

No worries and no rush. Thanks for taking care of it.

**Review by simison — APPROVED** [review]
This PR fell through a bit but let's get it in, and we'll continue iterating on login blocks and eventually merging them.

**Pull request merged**
