### PR TITLE
jetpack-mu-wpcom: Sync newspack blocks on build, not install

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

If you do it on install, everyone everywhere in the monorepo has to have this downloaded and installed even if they're not working on mu-wpcom at all.

Instead, save the syncing for the actual build. And also, as a (hopefully temporary) hack, build the package when plugins/wpcomsh is going to be tested too.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy?
* No relevant change to the build artifact?

### CODE REVIEW

**Comment by arthur791004** [comment]
What do you think about just keeping the synced files in the repo directly?

**Comment by anomiex** [comment]
The main risk there would be that they might get out of sync with the versions in newspack. It'd be more straightforward though.

**Comment by arthur791004** [comment]
But currently we use the fixed version instead of pulling the latest one as I think it's risky 😅 And it would be better to manually upgrade the version and test whether everything still works well.

**Comment by anomiex** [comment]
Ok, I'll abandon this in favor of you doing that.

**Pull request closed without merging**
