### PR TITLE
Nav Redesign i3: Hotfix the order of the admin menu items for WP 6.6

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/dotcom-forge/issues/8220

## Proposed changes:

* Hotfix the order of the admin menu items for WP 6.6

| Before | After |
| - | - |
| image | image |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your simple sites with the classic interface
* Go to /wp-admin
* Make sure the order of the admin menu items on the right side is correct

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
On Classic Simple's frontend, the search bar should still be the rightmost one (CMIIW). Can we check and fix?

|Actual (this PR)|Expected (like in Atomic)|
|-|-|
|image|image|

**Comment by okmttdhr** [comment]
>On Classic Simple's frontend, the search bar should still be the rightmost one (CMIIW).

I agree that the search bar should be at the rightmost, aligning with Atomic Classic and Core 👍

**Comment by arthur791004** [comment]
I changed the implementation to keep the search at the rightmost. Do you have any concerns about using flex here?

The reason is the core also changes the priority of the hook as follows:
```diff
-  add_action( 'admin_bar_menu', 'wp_admin_bar_search_menu', 4 );
+  add_action( 'admin_bar_menu', 'wp_admin_bar_search_menu', 9999 );
```

See https://core.trac.wordpress.org/attachment/ticket/60685/60685.9999.diff

**Review by fushar — COMMENTED** [review]
The profile menu is now in a weird position on Simple Classic's site frontend on mobile device 🙈 

image

**Comment by arthur791004** [comment]
hmmm... I'll take a look later 🙃

**Comment by arthur791004** [comment]
> The profile menu is now in a weird position on Simple Classic's site frontend on mobile device 🙈

I think this is the current behavior and it happens only on the super smaller viewport 😅

**Comment by fushar** [comment]
> I think this is the current behavior and it happens only on the super smaller viewport 😅

Sorry! You're right! I had assumed that some icons would be hidden on such viewport.

**Review by fushar — APPROVED** [review]
Tested on all cases (Simple/Atomic, wp-admin/frontend) and all work as expected. Thanks!

**Pull request merged**
