### PR TITLE
Don't fire clean_post_cache on the same post multiple times

### PR DESCRIPTION
**Pull request by wturrell**
Attempt to reduce SQL queries.  I don't fully understand the flow here so have tried to keep this as simple as possible.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Makes sense, code looks good

**Comment by dereksmart** [comment]
@enejb or @lezama could you take a look?  Not clear to me if there was a reason for clearing cache every time in the loop.   

If it makes sense to you, feel free to merge

**Comment by dereksmart** [comment]
this kind of seems like it's there for a reason - to clear the cache for each post.  This change would only clear it for one post.  

@georgestephanis can you confirm?

**Comment by enejb** [comment]
I also don't know why we do it in the first place.

**Comment by dereksmart** [comment]
Punting until someone can provide some definitive answers

**Comment by samhotchkiss** [comment]
@dereksmart - this only runs once per post.  I can't see any reason to run it more than once.  I've tested this without any obvious issues, I'm going to go ahead and merge.

**Pull request merged**
