### PR TITLE
use wordbless to test the assets package

### PR DESCRIPTION
**Pull request by leogermani**
This PR replaces other dependencies in the Assets package with WroDBless for testing purposes. It simplifies what's needed to test the package and also improves the testability.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Run the tests for the package
* Look at the changes and see if we are still testing everything we want

### CODE REVIEW

**Comment by jeherve** [comment]
I've removed the "fixes ..." from the PR description, since there are still other packages that rely on `brain/monkey`. Other than that it seems perfect. You rock!

**Review by jeherve — APPROVED** [review]

**Comment by kraftbj** [comment]
Restarting the e2e test that failed. I hesitate to do this over #17443, though, unless there are other benefits to using WorDBless within the Assets package.

**Comment by leogermani** [comment]
Putting this on hold until we finish the discussion on https://github.com/Automattic/jetpack/pull/17443

**Comment by jeherve** [comment]
Closing this since we merged #17443.

**Pull request closed without merging**
