### PR TITLE
OpenTable Block: CSS Class to counter button padding

### LINKED ISSUE #15267: OpenTable block: Button style has built in padding
OpenTable's block button style has padding around it, which makes it impossible to properly align with text.

#### Steps to reproduce the issue

1. Add a paragraph of text, and OpenTable block below. Use the button block style.
2. Notice how the button does not align with text.
3. Preview the page. Inspect with developer tools and notice the button has built in padding around.

#### What I expected
To be able to align button with text.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes #15267

#### Changes proposed in this Pull Request:
* The OpenTable button is within an iframe and has default padding. A new optional CSS class has been added to apply a negative margin to the container matching the default padding.

_Note: When this is merged, [documentation](https://wordpress.com/support/wordpress-editor/blocks/opentable-block/#advanced) will need to be updated. Docs need info about the "load in iframe" setting as well._

#### Testing instructions:
1. Edit a post using the block editor
2. Add a paragraph block of text for visual alignment check
3. Add an OpenTable block using the button style
4. You should see that there is padding within the OpenTable block indenting it
5. Select the OpenTable block and expand it's Advanced settings panel
6. Toggle on the new "Remove button padding" setting
6. Block should appear visually aligned now
7. Save post and check alignment on frontend

OpenTableCSS

**Before:**

OpenTableBlock-before

**After:**

OpenTableBlock-after

#### Proposed changelog entry for your changes:

* Bug Fix (#15267): Add optional CSS class to counter OpenTable block button's padding.

### CODE REVIEW

**Comment by Copons** [comment]
This does fix the issues, although it may be a bit brittle, in the off chance OpenTable changed the button padding.
Since we are changing the margin of a nested element, [we should be fine with however themes decide to position blocks](https://github.com/Automattic/jetpack/issues/15267#issuecomment-613220799).

Although, I do question the value of having a secret class.
Yes, I guess we can instruct our designer to use it in page templates if needed, but why not make it useful to everybody?

I agree with @creativecoder when he [suggested](https://github.com/Automattic/jetpack/issues/15267#issuecomment-618597976) to add a button margin toggle.
We might even tuck it away in the `InspectorAdvancedControls` panel (where there is already another "dangerous" control), if we don't want to clutter the main sidebar.

**Comment by glendaviesnz** [comment]
I tend to agree with @Copons on thinking about it, rather than a hidden class, maybe a toggle under the `load widget in iframe` on in Advanced tab, is a better approach, still means it isn't always visible and confusing to basic user, but easier for a more advanced user to stumble across it than finding a reference in the docs.

**Comment by scruffian** [comment]
+1 to that :)

**Comment by aaronrobertshaw** [comment]
I've added a new toggle setting under the block's Advanced panel and updated the PR testing instructions. Let me know if I've missed anything.

**Comment by scruffian** [comment]
Looks good. I added a commit which only shows the toggle if the button style is selected. What do you think?

**Comment by aaronrobertshaw** [comment]
Thanks @scruffian, good call on the conditional display of the toggle.

**Comment by Copons** [comment]
This works great! ✨ 

One thing felt a bit weird to me: should we change from "padding" to "margins"?
Like, regardless of what we are technically doing, this option either "removes _block_ padding", or "removes _button_ margins".
I think this is an especially valid point considering we are targeting advanced users, who would probably know the difference.
What do y'all think about changing the label into `Remove button margins`?

**Comment by scruffian** [comment]
Based on @Copons's feedback I have updated `padding` to `margin`...

**Comment by glendaviesnz** [comment]
Sorry @kraftbj  - in trying to sort the manual sync of the diff I inadvertently  failed the test again ... we have D42789-code manually synced now - is there some way that we are able to toggle that wpcom sync failure in these cases, or is that something jetpack crew needs to do? Thanks :-)

**Comment by glendaviesnz** [comment]
> is there some way that we are able to toggle that wpcom sync failure in these cases, or is that something jetpack crew needs to do? Thanks :-)

Ignore, @pento kindly showed us how :-)

**Pull request merged**
