### PR TITLE
IDC: First pass at automatically putting a site in staging mode

### PR DESCRIPTION
**Pull request by ebinnion**
Identity crises in Jetpack are painful for all. 

This PR is a first pass at automatically putting a site into staging mode if the site is attempting to update the shadow site on WordPress.com in such a way that could cause an identity crisis.

On the WordPress.com side, for sites that have opted in, we check if the new home and siteurl options that are sent from the Jetpack site match what we have on the WPCOM side. If so, then we allow sync. If not, we return an error.

This PR, when it gets the error back, puts the site into staging mode and shows some very basic UI like this:

screen shot 2016-10-06 at 5 27 30 pm

It doesn't currently allow for any actions. But, a user can take their site out of staging mode by opting out the IDC mitigation (after which, we'll cleanup the flag we set) or by filtering `jetpack_is_staging_site`.

This is a rough early design for the notice. For now, we're trying to help out VIPs, who are experiencing IDC issues when cloning a site to a local development server and the `home` and `siteurl` values overriding those on the shadow site 😞 cc @simonwheatley @joshbetz @rickybanister for thoughts on this early flow.

To test:

- Checkout `update/sync-auto-staging-notice-first` branch
- In `wp-config.php`, `define( 'JETPACK_SYNC_IDC_OPTIN', true );`
- Ensure your site is connected to WPCOM
- Go to `General > Settings`
- Change home and siteurl options
- Wait a minute or so, and then go to `Jetpack > Dashboard`
- Verify you see a notice like the above
- Ensure that SSO module is turned on
- Verify that you get a message that you can't use SSO because of an IDC (you're in IDC because your local options don't match WPCOM because we didn't update 😉 );;
- Log back in with username and pass
- Opt out of IDC mitigation by removing the filter or constant
- Wait a minute, then reload admin. Then go to `Jetpack > Dashboard`. You should not see a notice
- Log out
- You should be able to SSO now. The IDC is cleared since we updated the value.

### CODE REVIEW

**Comment by simonwheatley** [comment]
I'm gradually putting the pieces together to test this for real with some sites. 

How does this approach cope if the production site is running updated Jetpack, but the site where the data is copied to (the staging site) is running an outdated Jetpack. We had this happen recently, where a dev got hold of the most recent database and loaded it up with an outdated set of our MU plugins (which includes Jetpack).

Separately, we're finding the term "staging site" is loaded and also quite specific. Can we rephrase to something like "The Jetpack connection for this site has been suspended, so it does not interfere with the active Jetpack connection at example.com. [More information](http://some/information/)".

**Comment by ebinnion** [comment]
> How does this approach cope if the production site is running updated Jetpack, but the site where the data is copied to (the staging site) is running an outdated Jetpack.

It doesn't currently. That's an interesting situation to handle, because we really should show some UI if we're going to block a site from syncing. For VIPs, we could probably also disable on the WPCOM side if:

1) The site has a VIP flag
2) The site has not opted in to the IDC mitigation with the filter and we assume that means it's on an outdated version of Jetpack
3) The dev site has at least Jetpack 4.2 (although we may be able to do something similar in old sync as well.

> Separately, we're finding the term "staging site" is loaded and also quite specific. Can we rephrase to something like "The Jetpack connection for this site has been suspended, so it does not interfere with the active Jetpack connection at example.com. More information".

I dig it. cc @rickybanister for thoughts.

**Comment by kraftbj** [comment]
I dig dropping using "staging" in documentation/UI. I'm open to a better term to use in code (for constants/function names, etc too), but don't find that as pressing.

**Comment by dereksmart** [comment]
This seems like a solid first pass by assuming that the first site that connected is a production site (and tests well as such), but we'll need to take into account the site that started out as a staging site (as we discussed in slack).  

We'll also want to make sure we're checking for both home && siteurl options, not just home, and of course we'll need to incorporate some sort of UI.  

However, as discussed, we'll be handling these goals in future PR's :)

**Comment by simonwheatley** [comment]
I've checked this out, and it catches an identity crisis for me as long as the usurping site has an up to date Jetpack:

1. Load this branch
2. Copy the database from production to staging
3. Search and replace the URLs, but don't replace the `jetpack_options` or `jetpack_private_options` options
4. Log in via username and password
5. See the Jetpack notice in the Jetpack admin

Thoughts:

* I'd love the notice to be more obnoxiously noticeable /cc @rickybanister 
* I think the notice should appear EVERYWHERE in the admin area
* The notice is the same for editors and administrators, should it be?

When I try to use SSO in the usurping site, I get logged in to the original site:

1. Load this branch
2. Copy the database from production to staging
3. Search and replace the URLs, but don't replace the `jetpack_options` or `jetpack_private_options` options
4. Hit the big "Log in with WordPress.com" button (`https://usurping-site.com/wp-login.php?action=jetpack-sso&rememberme=0`)
5. End up logged in to the original site

Thoughts:

* It really wasn't obvious what just happened, and because the site is cloned (which is how the problem arises) it would be easy for a user to start making destructive changes at this point and really cause some trouble. 😞

**Comment by simonwheatley** [comment]
> It really wasn't obvious what just happened, and because the site is cloned (which is how the problem arises) it would be easy for a user to start making destructive changes at this point and really cause some trouble. 😞

To (attempt to) clarify: Because I started trying to SSO into the usurping site, and I ended up in the original site, and because the usurping site is a clone of the original site, it is really easy for me to not notice the cues that the site has switched on me at the point that I land in the admin area of the "wrong" site. If the original site is a production site, and I think I'm in a development/staging site, then I might start doing things like adding test posts, deleting things, etc, etc, all of which would *actually* happen to the original/production site when I *think* I'm acting on the usurping site. 

Does that make sense?

**Comment by ebinnion** [comment]
Patch for forcing VIP sites to use IDC mitigation. D3056

**Pull request merged**
