### PR TITLE
renovate: Use configured version of PHP when running composer

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

In the absence of configuration or certain dependencies, renovate
currently defaults to running composer with PHP 7.4. Or, more
specifically, it defaults to whatever is the 'latest' tag on the
`renovate/php` docker package.

We do everything else with PHP 8.0, so configure renovate to use that
too.

**:warning: If we merge this, WooCommerce will probably stop working in the Jetpack Development Environment with errors like the one [here](https://href.li?https://github.com/woocommerce/woocommerce/issues/33611#issuecomment-1170280202).**

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

None, but see https://github.com/Automattic/jetpack/pull/25106#issuecomment-1185611334

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Check that it's not too close to the scheduled renovate run.
* Go to [the dependency dashboard](https://href.li?https://github.com/Automattic/jetpack/issues/23363) and check the box for "Lock file maintenance".
* Go to [the action page](https://github.com/Automattic/jetpack/actions/workflows/renovate.yml) and trigger a dry run, specifying this branch.
* Wait for the triggered run to finish.
* Go to [the dependency dashboard](https://href.li?https://github.com/Automattic/jetpack/issues/23363) and uncheck the box for "Lock file maintenance".
* Check the logs for indications that it's using PHP 8.0 rather than 7.4
  * :heavy_check_mark: [Using a docker image `docker.io/renovate/php:8.0.21`](https://github.com/Automattic/jetpack/runs/7363125518?check_suite_focus=true#step:5:29956)
  * :heavy_check_mark: [Updating symfony/string to 6.0.x, not 5.x (PHP 7.4) or 6.1.x (PHP 8.1)](https://github.com/Automattic/jetpack/runs/7363125518?check_suite_focus=true#step:5:29963)

### CODE REVIEW

**Comment by anomiex** [comment]
> **:warning: If we merge this, WooCommerce will probably stop working in the Jetpack Development Environment with errors like the one [here](https://href.li?https://github.com/woocommerce/woocommerce/issues/33611#issuecomment-1170280202).**

Another alternative would be to run both renovate and the "Lock files are up to date" CI check with 7.4, to avoid the need for PRs like #25106 in the future. To do that we should add a `LOCKFILE_PHP_VERSION=7.4` into `.github/versions.sh` and use it in both places. 

The down side there would be that people might have difficulty properly updating the lock files if they have 8.0 installed locally. On Linux it's easy to have multiple versions installed using https://deb.sury.org/, but what about Macs?

**Comment by samiff** [comment]
> The down side there would be that people might have difficulty properly updating the lock files if they have 8.0 installed locally. On Linux it's easy to have multiple versions installed using https://deb.sury.org/, but what about Macs?

I use Homebrew on Mac and it's pretty easy to switch the PHP versions. Are there any Composer pre-update hooks or anything like that we can use to check what version of PHP someone is using before the lock file gets updated?

**Comment by anomiex** [comment]
Composer does have [various hooks](https://getcomposer.org/doc/articles/scripts.md#event-names), but using them properly might take a little thought. Our `tools/composer-update-monorepo.sh`, for example, runs the update in a way that only applies to the monorepo packages so it should be safe. It'd be annoying if people had to jump through some hoop to get that to use php 7.4 when it shouldn't matter.

**Comment by anomiex** [comment]
Current plan is to go ahead with this on July 26, unless feedback at pdWQjU-3c-p2 gives us reason to go with [the alternative](https://github.com/Automattic/jetpack/pull/25112#issuecomment-1185816266).

**Review by samiff — APPROVED** [review]

**Pull request merged**
