### PR TITLE
Jetpack Blocks: update to a new version of the blocks.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

- https://github.com/Automattic/wp-calypso/releases/tag/%40automattic%2Fjetpack-blocks%4012.2.0
- https://www.npmjs.com/package/@automattic/jetpack-blocks
- Built from https://github.com/Automattic/wp-calypso/pull/30509

#### Testing instructions:

* Run `yarn build`
* Go to Posts > Add New
* Do you see Jetpack Blocks?
* Do you see the plugin sidebar with the Publicize info and the shortlink?

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

**Review by eliorivero — APPROVED** [review]

**Comment by mdawaffe** [comment]
> the shortlink

I'm not sure what I should be looking for here, but everything else looks good.

**Comment by jeherve** [comment]
> I'm not sure what I should be looking for here

Sorry. A screenshot should help:

screenshot 2019-02-14 at 22 27 06

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.0` in e95d6b1eb7ec3bf0d3bfae99eb40382a03178acf

**Comment by mdawaffe** [comment]
> screenshot

I had completely forgotten about that button :) Everything WFM.

**Pull request merged**
