### PR TITLE
Search: Better handling of Unlimited API requests.

### PR DESCRIPTION
**Pull request by a8ck3n**
Follow-up PR addressing "0/Unlimited" display in usage meters.

#### Changes proposed in this Pull Request:

Better handles the case where the API returns a huge request limit. Was showing "0/Unlimited". Now shows the request count from the last month if available (245/Unlimited) or just "Unlimited" if no request count was provided.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Visit new Search dashboard.
2. Check that limits are shown correctly under the "Search requests" meter.
3. Use Dev Tools to update the values.
4. `count === 0` --> "Unlimited"
5. `count !==0` --> "count/Unlimited"
6. Normal request limit from API --> "count/limit"

Screenshot:

SnapUnlimited

### CODE REVIEW

**Review by jsnmoon — APPROVED** [review]
Looks great! Might be nice to space out the value in the interface (e.g. `235 / 500` and `235 / Unlimited`), but it's not important to push out before release.

🚢 🚢 🚢

**Comment by dognose24** [comment]
I found that the `DonutMeter` fill percentage seems weird. Should the fill be 0% for the [unlimited requests](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/dashboard/components/donut-meter-container/index.jsx#L57)? cc @a8ck3n 

截圖 2022-10-14 下午1 02 33

**Comment by jsnmoon** [comment]
> I found that the `DonutMeter` fill percentage seems weird. Should the fill be 0% for the [unlimited requests](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/search/src/dashboard/components/donut-meter-container/index.jsx#L57)?

I think this is a matter of opinion. Showing 577 as a 0% meter doesn't make much sense either, for example. Happy to go with either option, honestly.

**Comment by a8ck3n** [comment]
Agreed that it's a little weird but I'm fine with either an empty meter or a green meter. As long as it's not red!

**Pull request merged**
