### PR TITLE
Fix comments on password protected posts

### LINKED ISSUE #35716: Verbum Comments: Comment lost when submitted on a password-protected page or post in Chrome
### Impacted plugin

Jetpack

### Quick summary

Under some circumstances, submitting comments does not work.

### Steps to reproduce

In Chrome:

1.  On a WordPress.com Atomic site, activate a classic theme like Twenty Twenty-One
2. Create a password-protected page or post with comments open and unmoderated
3. Submit a comment

### A clear and concise description of what you expected to happen.

Expected to see the comment appear on the page or post

### What actually happened

Comment disappears
Test_Post_–_Jupiter_Woo_Testing

Screencast: 

https://github.com/Automattic/jetpack/assets/7662449/7b87a880-a948-41de-b1b1-6abbe3bb51c1

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

The bug occurs in Chrome 121.0.6167.184
Works OK in Firefox 122.0.1
Have not tested other browsers

Was **not** able to replicate in a block theme or a Simple site.

User follow-up ticket in: 7746553-zd-a8c

### PR DESCRIPTION
**Pull request by heavyweight**
Commenting on password-protected posts on atomic sites is not working.

On atomic sites, comments are posted via iframe.
The iframe points to https://jetpack.wordpress.com/jetpack-comment...
When the comment is submitted there is an inline js that submits the form. This js form submission happens from https://jetpack.wordpress.com/jetpack-comment/ and posts to the comment post endpoint of the atomic site. If the cookie wp-postpass_... is missing from this then we get `comment_on_password_protected` error.

This PR sets same-site none on the cookie to ensure that it is sent out. This way the comments will continue to work on password-protected posts atomic sites.

Fixes https://github.com/Automattic/jetpack/issues/35716

## Proposed changes:

* In case we have `wp-postpass` set the same-site to none

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sync this PR with atomic site
* Create password protected post
* In a private tab open the password protected post
* Unlock the post with the password
* Check if `wp-postpass_` and `verbum-wp-postpass` are set
* Post a comment
* There should be no errors and the comment should be posted

### CODE REVIEW

**Review by escapemanuele — DISMISSED** [review]
I see that the cookies are set and that the comment has been posted ✌️

**Comment by heavyweight** [comment]
Drafting it since I found an issue.

If I have one site with more protected posts, if the password is the same then it will be the same cookie.
In case there is another protected post with a different password, then the cookie will change.
But in our case `verbum-wp-postpass` will still be there and that cookie won't be modified.

**Review by agrullon95 — COMMENTED** [review]
@heavyweight - Lets fix the security issues if possible.
Besides that, everything is working well on my atomic site.
I was able to comment on a password protected post.

**Review by agrullon95 — APPROVED** [review]
Tested again with jetpack beta plugin. I was able to post a comment on my atomic site with admin user and non admin users on password protected post.

**Pull request merged**
