### PR TITLE
Contact Form: add filter to allow customizing email headers.

### PR DESCRIPTION
**Pull request by jeherve**
See #631

#### Changes proposed in this Pull Request:

Allowing one to customize the email headers used for the emails sent out for each contact form would allow cc'ing or bcc'ing specific addresses, for example.

#### Jetpack product discussion

* No

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Add a new form to one of your posts.
* Add the following snippet to your site using a functionality plugin:
```php
add_filter(
	'jetpack_contact_form_email_headers',
	function ( $headers, $comment_author, $reply_to_addr, $to ) {
		$headers .= 'Bcc: ' . $reply_to_addr . "\r\n";
		return $headers;
	},
	10,
	4
);
```
* Submit a form using the form you've just published.
* An email should be sent to the email address you specified in the address you specified in the snippet above.

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
I see we already have a bunch of filters in `::process_submission()` like 'contact_form_to', 'contact_form_subject', and 'contact_form_message'. I wonder if it would make more sense to put the new filter in there instead.

That would also allow for the 'grunion_after_message_sent' action to see the modified headers.

**Comment by jeherve** [comment]
> I see we already have a bunch of filters in `::process_submission()` like 'contact_form_to', 'contact_form_subject', and 'contact_form_message'. I wonder if it would make more sense to put the new filter in there instead.
> 
> That would also allow for the 'grunion_after_message_sent' action to see the modified headers.

That's a good point. I've changed things around a bit, hopefully to make the filter more useful.

**Review by anomiex — APPROVED** [review]
Looks straightforward. Haven't tested it myself.

**Comment by jeherve** [comment]
r231218-wpcom

**Pull request merged**
