### PR TITLE
Manage: Add Themes and Menus to module info

### PR DESCRIPTION
**Pull request by ockham**
/cc @zinigor

### CODE REVIEW

**Comment by kraftbj** [comment]
What's the timeline/plan for adding more on-wp.com functionality to /designs/ for JP sites. It looks like, atm, everything is redirecting me to my site's wp-admin.

screen shot 2015-08-18 at 10 20 06

If that'll be the case when 3.7 is released, I think we shouldn't advertise that too much yet.

**Comment by ockham** [comment]
> What's the timeline/plan for adding more native wp.com functionality to /designs/ for JP sites. It looks like, atm, all links are redirecting me to my site's wp-admin with regard to themes.

JP site handling within `/design` is only enabled in the development environment; we're going to enable it on wpcalypso and horizon tomorrow, and in staging and production on 9-2, to be in sync with the JP beta and release. (There's also a JP version check, so you need at least the 3.7 Beta or 3.7-dev for things to work).

> If that'll be the case when 3.7 is released, I think we shouldn't advertise that too much yet.

Hm. Why not? Between the Beta and release, only people using the Beta will see it, and they're the ones that will be able to alreaddy use it, too (albeit only via horizon, admittedly). From 9-2, everyone running JP 3.7 will be able to use `design/` for JP sites. 

But if you prefer, I can only add the paragraph about 'Menus' for now, and the one about 'Themes' once 3.7 final is released.

**Comment by zinigor** [comment]
If we're adding the paragraph in 3.7, we need to add it for beta as well because we'll need the time to translate it in time for 3.7. So it means that from the beta testers point of view we'll have broken links until 2nd of September, right?

**Comment by ockham** [comment]
> So it means that from the beta testers point of view we'll have broken links until 2nd of September, right?

The link will work (it already does) -- tester only won't be able to manage their Jetpack sites' themes from that location, as opposed to what the paragraph promises.

**Comment by zinigor** [comment]
@ockham I see, thanks for explaining. Then I believe it's OK to merge it in and release it as part of the beta.

**Comment by kraftbj** [comment]
:+1: Sounds good to me. I just wanted to make sure we weren't highlighting something that just sent folks back to their /wp-admin/. Since it'll do amazing beautiful hotness when 3.7 ships, then rock on.

**Pull request merged**
