### PR TITLE
Contact Info Block: Fix styling issues for FSE compatibility

### PR DESCRIPTION
**Pull request by andrewserong**
Related to: 256-gh-Automattic/view-design

This change updates the CSS for the editor view of the Contact Info block to create consistency between the post editor and the new FSE site editor. The existing editor CSS depends on `forms.css` being present to provide the border-radius, and the gap between each form field occurs by default because the elements were set to `inline-block`. This change makes the gap explicit using a margin, and sets the input fields to be displayed as blocks. It also explicitly prevents the form field from being manually resized.

#### Screenshots

Using the site editor with Twenty Twenty One Blocks theme:

| Before | After |
| --- | --- |
| image | image |

#### Reference screenshot from the post editor

This is how the block looks in the normal post editor (this is the view we're trying to match):

image

#### Changes proposed in this Pull Request:

* Update Contact Info editor styling to deliberately set the border radius for the input fields
* Force the resize controls for the textarea element to not be displayed
* Set the vertical margin between input fields

#### Jetpack product discussion

256-gh-Automattic/view-design

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Apply this change using an FSE-compatible theme and from the site editor (e.g. wp-admin/admin.php?page=gutenberg-edit-site) test the Contact Info block
* From the standard post editor, compare and ensure the editor UI looks basically the same
* Try with a couple of other themes and non-FSE themes to ensure this doesn't introduce regressions / degrade the editing experience

### CODE REVIEW

**Review by glendaviesnz — APPROVED** [review]
Works as advertised for me.

Shame about the lack of padding on the left, but that is existing and may be a deliberate design decision so I guess we shouldn't mess with that

**Comment by andrewserong** [comment]
Thanks @glendaviesnz, yes I took a look at adding a negative left margin so that the white of the input field would be slightly offset to keep the text in the same horizontal position between the edit state and the rendered state, but then that conflicted with the border in the site editor to show that the block is selected. I figured we could look at improving the design in a follow-up potentially, so I've been mostly aiming for parity between the post editor and site editor.

Happy to revisit here, though, if you (or anyone else!) think it's worth pursuing now.

**Comment by glendaviesnz** [comment]
> Happy to revisit here, though, if you (or anyone else!) think it's worth pursuing now.

No, sounds like a follow up job to me.

**Review by jeherve — APPROVED** [review]
This looks good to me. 🚢

**Comment by andrewserong** [comment]
r224100-wpcom

**Pull request merged**
