### PR TITLE
Tiled Gallery Block: avoid validation errors in editor on WordPress.com

### LINKED ISSUE #16514: Gutenberg: Tiled Gallery on Layout Grid invalid content
#### Steps to reproduce the issue

1. Create a new page on a WordPress.com (tested on Free and Premium).
2. Add a `Layout Grid` block (any layout).
3. Add a Tiled Gallery block in one of the rows. 
4. Add images (I added from Media Library)
5. Publish page.

#### What I expected
I expected the Tiled Gallery is saved correctly.

#### What happened instead
The block crashes after publishing the page with the following error: `This block contains unexpected or invalid content.`

Screenshot 2020-07-17 at 17 42 02

### PR DESCRIPTION
**Pull request by carlosenamdev**
Fixes #16514

#### Changes proposed in this Pull Request:

* Fix validations errors for tilled galleries on wordpress.com ( more info on this [issue](https://github.com/Automattic/jetpack/issues/16514) )

#### Testing instructions:
1. Make sure you have a blog on WordPress.com
2. Create a post/page on the blog.
3. Add a Tiled Gallery to the post content.
4. Save the post and then refresh the page.
5. Make sure there are no block validation errors in the console

#### Proposed changelog entry for your changes:

* Fix for validation errors for Tiled Galleries

### CODE REVIEW

**Comment by jeherve** [comment]
Internal reference: D46819-code

**Review by jeherve — CHANGES_REQUESTED** [review]
This works when updating blocks that were created prior the last update, but will still generate errors for galleries that were created after the last update. In those cases, I am afraid we'll need another set of deprecations.

**Comment by carlosenamdev** [comment]
> This works when updating blocks that were created prior the last update, but will still generate errors for galleries that were created after the last update. In those cases, I am afraid we'll need another set of deprecations.

Hi Jeremy, thanks for the test results!, could you please elaborate on the deprecations?, do you mean to create a new deprecated version without the changes on this PR?

**Comment by carlosenamdev** [comment]
@jeherve I pushed a new commit where I add a new deprecated version ( `V3` ) and a new fix for the tiled galleries inside Grid Layouts. Could you please test this new commit?

**Review by jeherve — CHANGES_REQUESTED** [review]
No luck I'm afraid. I still run into validation errors:

`Block validation: Expected attribute `style` of value `flex-basis:50.00000%`, saw `flex-basis:50%;`.`

**Comment by carlosenamdev** [comment]
@jeherve Thanks for noticing that!, I just pushed a new commti to handle percentages with whole numbers, could you please test this new chnage?

**Comment by brbrr** [comment]
I have tried on a few different WPCOM blogs, and unfortunately, I still can see validation errors:

1. Block validation: Expected attribute `style` of value `flex-basis:52.68275271884437%`, saw `flex-basis:52.682752718844%;`.
2. Block validation: Expected attributes: `[ ["class", "tiled-gallery__col", true] ]`, instead saw `[ ["class", "tiled-gallery__col", true], ["style", "flex-basis:52.682752718844%;", true] ]`

**Comment by carlosenamdev** [comment]
> I have tried on a few different WPCOM blogs, and unfortunately, I still can see validation errors:
> 
> 1. Block validation: Expected attribute `style` of value `flex-basis:52.68275271884437%`, saw `flex-basis:52.682752718844%;`.
> 2. Block validation: Expected attributes: `[ ["class", "tiled-gallery__col", true] ]`, instead saw `[ ["class", "tiled-gallery__col", true], ["style", "flex-basis:52.682752718844%;", true] ]`
> 
> UPD: It does work with blocks created _after_ applying this patch. When editing blocks created with _older_ version of this block, validation warnings are still present.

Hi @brbrr Thanks for testing!, could you please paste a copy of the logs here?

@jeherve Could you please test using my last commit?

**Comment by carlosenamdev** [comment]
Hi @brbrr, just passing through to check on this

**Comment by jeherve** [comment]
We still have validation issues I'm afraid:

image

**Comment by carlosenamdev** [comment]
@jeremy, the error you are showing in the image seems caused by caused by rolling back to the old script version and not delete the tiled gallery generated by the new script version. Could you please delete that tiled gallery, then go back to the old scrip version, create the tiled gallery, then build the new script version and check the results?

**Comment by kraftbj** [comment]
Rebased to ensure we're testing everything fresh and will give it a go once the beta builds.

**Review by kraftbj — APPROVED** [review]
The upgrade from a previous version worked well with no validation errors for me.

**Review by kraftbj — CHANGES_REQUESTED** [review]
I mis-tested before. I'm getting a validation error on a new block within the layout grid. It no longer hard fatals, though.

Testing with a TG outside of the layout grid validates without an error.

**Pull request closed without merging**
