### PR TITLE
Unit tests: Update tests to pass on WP.com

### PR DESCRIPTION
**Pull request by obenland**
It turns out Jetpack unit tests don't run in TC, so I never noticed them failing. See D53660-code

#### Changes proposed in this Pull Request:

* Decode API responses as arrays.
* Store new requests in their own variable (and not overwrite the passed request object).
* Update unit tests to process array responses.
* Update unit tests to compute admin urls to account for http vs https.
* Add unit tests for `delete_connection`.
* Add unit test for a `get_connection_details` request that fails.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Open the editor and insert an image, cover, or gallery block.
* Click the "Select Media" button and choose either of the new libraries.
* Go through the steps to insert an image and make sure it still works.

##### Unit tests
Run `phpunit --testsuite core-api` and make sure that admin menu and external media tests are passing.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Comment by obenland** [comment]
I noticed that with the switch to an array response, the error handling in `get_connection_details` won't work anymore. 
And that made me notice that there are no tests for that. And also no tests for `delete_connection`.
And that made me notice that I have no idea what an error response would look like or how to trigger one.

I'll take another look at this.

**Comment by obenland** [comment]
This should be ready for review again. `get_connection_details` and `delete_connection` consume wp.com's v1 `/meta/external-media/connection/*` endpoint, which always returns WP_Errors on failure.

I added tests for that and also a success test for `delete_connection`.

Finally, I noticed that on internal requests we're trying to set parameters from an empty object because we're overwriting the `$request` variable. Apparently we don't really need any of these other parameters? For now I just made sure the new request is stored in its own variable.

**Review by cpapazoglou — APPROVED** [review]
Related tests are passing now with 🪰ing colors!

Regarding the Google Photos integration, my attempt resulted in 


Request URL: `/wp-json/wpcom/v2/external-media/list/google_photos?number=20&path=recent&filter%5B0%5D=mediaType%3Dphoto&filter%5B1%5D=dateRange%3D0000-00-00%3A0000-00-00&_locale=user`

Message: `cURL error 28: Connection timed out after 10000 milliseconds`
Status: 400
Code: `http_request_failed`

Tried disconnecting (in order to reconnect) to no vail, don't know if it is related though as I am getting the same error on master too.

**Review by jeherve — APPROVED** [review]

**Comment by obenland** [comment]
0a3114b  resolved merge conflicts after merging #17955.

**Comment by obenland** [comment]
On the wpcom side it looks like API requests are not (always) properly mocked, which makes some of the tests fail as they hit live data. Is there more information about the decision to pull `jetpack-unit` tests from automatically running for phab diffs?

**Comment by jeherve** [comment]
> Is there more information about the decision to pull jetpack-unit tests from automatically running for phab diffs?

@fgiannar may know more about this.

**Review by jeherve — APPROVED** [review]

**Comment by obenland** [comment]
@jeherve `test dashboard, extensions and search` Could you give me a hint on what that is and how I can get it to pass? It currently seems to prevent me from merging the PR

image

**Review by jeherve — APPROVED** [review]
I think it only needed one last rebase.

**Comment by obenland** [comment]
r218366-wpcom

**Comment by fgiannar** [comment]
> > Is there more information about the decision to pull jetpack-unit tests from automatically running for phab diffs?
> 
> @fgiannar may know more about this.

@obenland Hi Konstantin,

Unfortunately I'm not aware of this decision. I was actually under the impression those tests do run automatically for phab diffs. I'll try to look into it and let you know if I find anything related.

**Pull request merged**
