### PR TITLE
RNMobile: Ensure `playsInline` attribute conforms when falling back to core Video block

### LINKED ISSUE #6671: VideoPress v5: Plays inline setting not saving for Atomic sites w/o VideoPress
**Describe the bug**

The plays inline setting is not working in the Video block for Atomic sites w/o VideoPress enabled. As part of his report [here](https://github.com/Automattic/jetpack/pull/35637#pullrequestreview-1894091744), @fluiddot suggested the following workaround as a solution:

```patch
diff --git forkSrcPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js forkDstPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
index 2c6b81eae8cd005e7b83036f217a93dc3438d54f..6bdff0d8fc893f8a0710b9406fbb9b0ab4b139a9 100644
--- forkSrcPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
+++ forkDstPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
@@ -42,7 +42,15 @@ const VideoPressSave = CoreVideoSave => props => {
 		 * @see https://github.com/WordPress/gutenberg/blob/c5f9bd88125282a0c35f887cc8d835f065893112/packages/editor/src/hooks/generated-class-name.js#L42
 		 * @see https://github.com/Automattic/wp-calypso/pull/30546#issuecomment-463637946
 		 */
-		return CoreVideoSave( props );
+
+		// Rename `playsinline` to `playsInline` to conform the block schema of core Video block.
+		const { playsinline: videoPressPlayinline, ...restAttributes } = props.attributes;
+		const coreVideoAttributes = { ...restAttributes, playsInline: playsinline };
+
+		return CoreVideoSave( {
+			...props,
+			attributes: coreVideoAttributes,
+		} );
 	}
 
 	const url = getVideoPressUrl( guid, {
```

**To Reproduce**

1. Set up an Atomic site and disable VideoPress (this can be done via the Jetpack admin panel).  
2. In the app, navigate to the site's post editor.
3. Add a video block and upload any video to it.
4. Open the block's settings panel and toggle the "plays inline" setting on.
5. Save your changes and exit the post.
6. Navigate to the post editor containing the video on the web. 
7. Notice that "plays inline" is not toggled on when viewing the settings on the web.

**Expected behavior**

The setting should persist across platforms.

**Additional context**

It's worth highlighting that this isn't a recent regression. Prior to VideoPress v5 being implemented, the setting was broken in the app for all site types (ref: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1721). It's now only broken for Atomic sites w/o VideoPress enabled.

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/6671

## Description:

The core Video and VideoPress v5 blocks use different capitalisation for the "plays inline" setting:

* **Video:** `playsInline`  
* **VideoPress v5:** `playsinline`

Due to various technical limitations that arise from working with the app, the native implementation of VideoPress v5 in https://github.com/Automattic/jetpack/pull/35637 assigns the `playsinline` attribute when the block is added to Atomic sites, even those without VideoPress enabled. As described in https://github.com/wordpress-mobile/gutenberg-mobile/issues/6671, this leads to the setting not working as expected for Atomic sites w/o Jetpack when changed within the app.

## Proposed changes:

* https://github.com/Automattic/jetpack/pull/35981/commits/ee6267f492432a60ae30fbfb7a981fd252a57478: Rename the attribute from `playsinline` to `playsInline` when falling back to the core Video block. This will ensure the correctly capitalised setting is always used with the core block.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No, it does not.

## Testing instructions:

1. Set up an Atomic site and disable VideoPress (this can be done via the Jetpack admin panel).  
2. In the app, navigate to the site's post editor.
3. Add a video block and upload any video to it.
4. Open the block's settings panel and toggle the "plays inline" setting on.
5. Save your changes and exit the post.
6. Navigate to the post editor containing the video on the web. 
7. Verify that "plays inline" is toggled on when viewing the settings on the web.
8. Toggle the setting back off on the web to verify the changes also work on the web.

### CODE REVIEW

**Comment by SiobhyB** [comment]
@Automattic/jetpack-crew, as we're proposing a change to web file here, I'd be grateful for your review. 🙇‍♀️

**Review by jeherve — APPROVED** [review]

**Comment by bindlegirl** [comment]
I tried testing this and had slightly unexpected results. Not sure if I'm testing it right, though.
I accessed the post in the app and toggled the "inline" setting on, saved the post, and exited the editor.
When I opened that post on the web, the inline toggle was on, but whenever I tried leaving the post (without making any changes to it), it warned me about unsaved changes. The unsaved change appeared to be turning the inline toggle off.

Can you reproduce this behavior?

**Review by fluiddot — COMMENTED** [review]
@SiobhyB I confirmed that with this change https://github.com/wordpress-mobile/gutenberg-mobile/issues/6671 can't be reproduced. However, I noticed that blocks created previous to this change result in a block validation error.

Screenshot 2024-02-28 at 14 26 24

I presume that we shouldn't change the block's markup without adding a deprecation to the block.

Regarding the web version, I couldn't reproduce this case but this seems expected as the VideoPress v5 is not registered if VideoPress is disabled. Apart from this, seems there are no regressions in the web. In any case, I'd defer the approval of that part to the Jetpack crew.

**Comment by jeherve** [comment]
> However, I noticed that blocks created previous to this change result in a block validation error.
> 
> I presume that we shouldn't change the block's markup without adding a deprecation to the block.

Ah, interesting, I was testing for that but didn't run into the error. We should definitely add deprecation handling then 👍

**Comment by SiobhyB** [comment]
> However, I noticed that blocks created previous to this change result in a block validation error.
> I presume that we shouldn't change the block's markup without adding a deprecation to the block.

@fluiddot, were those blocks created based on the changes in https://github.com/Automattic/jetpack/pull/35637? If so, those changes aren't yet shipped to users, so I'm wondering if there would be a case where users would actually run into what you've described. 🤔

**Comment by fluiddot** [comment]
> @fluiddot, were those blocks created based on the changes in #35637? [...]

Yes, the blocks I tested were created based on the changes in #35637. 

> [...] If so, those changes aren't yet shipped to users, so I'm wondering if there would be a case where users would actually run into what you've described. 🤔

Good point. If this change will be released along with #35637, then what I mentioned shouldn't be an issue. Tomorrow we are releasing a new Gutenberg Mobile version (which will include #35637), so if we merge this today we'll be on time to have both. That said, I'll proceed with approving the PR, thanks 🙇 !

**Comment by SiobhyB** [comment]
@bindlegirl, thank you for testing!

> I tried testing this and had slightly unexpected results. Not sure if I'm testing it right, though.
I accessed the post in the app and toggled the "inline" setting on, saved the post, and exited the editor.
> When I opened that post on the web, the inline toggle was on, but whenever I tried leaving the post (without making any changes to it), it warned me about unsaved changes. The unsaved change appeared to be turning the inline toggle off.

Were you testing the app locally (with these changes applied) or with a production build? I tested with these changes checked out in both the app and web, but wasn't able to reproduce what you're describing: 

https://github.com/Automattic/jetpack/assets/2998162/d63f88dc-f561-4a0f-81fc-e01a47ab1818

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Comment by SiobhyB** [comment]
I'll go ahead to merge based on the above and then incorporate this into Gutenberg Mobile for tomorrow's release. 

@bindlegirl let me know if you're able to consistently reproduce the issue you were running into with the local changes from the app (or when this is released in 24.4). I'll also be keeping an eye out for reports when the change is released to users. 🙇‍♀️

**Comment by bindlegirl** [comment]
@SiobhyB This is what I see when testing on web (the inline toggle is set to off when reopening the post):

https://github.com/Automattic/jetpack/assets/1242807/ed1eb04d-0786-4001-a627-8e756c70f594

As far as I can tell, saving in app, and opening in web editor works as expected. It could be a problem with my testing environment if you are unable to reproduce it. Or with my testing procedure. 🙂

**Comment by SiobhyB** [comment]
@bindlegirl, ah I see, thank you for elaborating! My testing was focused on the app, if I check now I can confirm I can reproduce what you're seeing on Atomic sites that have VideoPress enabled on the web.

I'll create a separate PR to revert these changes.

**Comment by SiobhyB** [comment]
I've got the revert PR up in https://github.com/Automattic/jetpack/pull/36030.

@bindlegirl, thank you for spotting! I was eager to get a potential fix into the app's next release, which is why I kind of rushed merging, but should have looked more carefully into your first comment. Thank you again for following up!

We'll have to come up with another solution for the app bug but the setting has always been broken on mobile, so this isn't a regression for us. We can wait to address in another release.

**Comment by fluiddot** [comment]
Good catch @bindlegirl! I checked the block's attributes in the case shared https://github.com/Automattic/jetpack/pull/35981#issuecomment-1969386975, and noticed that the block has both `playsInline` and `playsinline` attributes. In this PR, we considered that Plays inline setting would always be controlled by `playsinline` attribute of VideoPress v5. However, since it can have both, we should take this into account and determine which one should be used. Here's a proposal for addressing it:

```patch
diff --git forkSrcPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js forkDstPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
index a731b3ea65c298e0ecf9a99014436e16dcd89fb8..65e9c17e614ac1ae04eb8eef9fcb1529ab57f8bb 100644
--- forkSrcPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
+++ forkDstPrefix/projects/plugins/jetpack/extensions/blocks/videopress/save.js
@@ -42,9 +42,18 @@ const VideoPressSave = CoreVideoSave => props => {
 		 * @see https://github.com/WordPress/gutenberg/blob/c5f9bd88125282a0c35f887cc8d835f065893112/packages/editor/src/hooks/generated-class-name.js#L42
 		 * @see https://github.com/Automattic/wp-calypso/pull/30546#issuecomment-463637946
 		 */
-		// Rename `playsinline` to `playsInline` to conform the block schema of core Video block.
-		const { playsinline: videoPressPlayinline, ...restAttributes } = props.attributes;
-		const coreVideoAttributes = { ...restAttributes, playsInline: playsinline };
+		// Due to different naming for the Plays inline setting between this block and core Video block, and potentially
+		// having both defined in block's attributes. We need to determine which value should be used and ensure we use
+		// the `playsInline` attribute defined by the core Video block, as it's the block that ultimately will be rendered.
+		const {
+			playsinline: videoPressPlayinline,
+			playsInline: corePlayinline,
+			...restAttributes
+		} = props.attributes;
+		const coreVideoAttributes = {
+			...restAttributes,
+			playsInline: corePlayinline || videoPressPlayinline,
+		};
 
 		return CoreVideoSave( {
 			...props,
```

cc @SiobhyB

**Comment by SiobhyB** [comment]
@fluiddot, the solution you proposed seems promising! I would be happy to help review if anyone picks up a PR. I'm working on the release today ahead of my support rotation and, as this isn't regression, won't prioritise working on it myself.

**Pull request merged**
