### PR TITLE
External Media: Enable for Cover block

### PR DESCRIPTION
**Pull request by obenland**
Enables External Media feature for the Cover block.

#### Changes proposed in this Pull Request:

* Adds `core/cover` to the list of blocks External Media is available to.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* In the Editor, insert a Cover block and chose an External Media provider to insert a background image.
* Replace the image with a different one.

#### Proposed changelog entry for your changes:

* Makes External Media available to the Cover block.

### CODE REVIEW

**Comment by obenland** [comment]
@marekhrabe @retrofox Do you remember why we initially decided to not make External Media available to the Cover block?

**Comment by retrofox** [comment]
> @marekhrabe @retrofox Do you remember why we initially decided to not make External Media available to the Cover block?

Was no valid reason, AFAIK. I presume it was just a way to extend the media button progressively to other blocks. Add it to cover makes total sense to me.

**Review by retrofox — APPROVED** [review]
LGTM

image

**Comment by obenland** [comment]
r215148-wpcom

**Pull request merged**
