### PR TITLE
[WIP] Carousel: Use CSS Grid for fixed info footer, add icons

### PR DESCRIPTION
**Pull request by ramonjd**
This PR builds off the work in #20139, however is based off of #20107, so that we can build on top of the Swiper.JS refactor.

#### Changes proposed in this Pull Request:

* Add an apparent fixed footer to the Jetpack Carousel, with info and comment buttons
* Hide the extra info area beneath the footer by default, to prevent vertical scrolling
* When the info or comment button is clicked, reveal extra info below the fixed footer and scroll to it

#### Screenshot of WIP

carousel-footer-with-swiper-sml

#### To-dos

* [x] Should we hide the extra footer area when navigating back / forward through slides?
* [ ] Add smooth scrolling to scrolling up / down (note Safari iOS doesn't support this via scrollTo natively)
* [ ] Add a timeout before toggling the show class off so that we can smooth scroll up before the extra info content is hidden
* [x] Tweak the tap targets of the buttons so that they are larger — currently (with my thumbs at least) it's difficult to tap the buttons on mobile (iPhone 8)
* [ ] Tweak styling and positioning of buttons to better match designs
* [ ] Tweak styling, width and positioning of columns, info, captions, etc beneath the new footer
* [x] Update styling to ensure it works in Light mode as well as the default Dark colour scheme
* [x] Should we add in the description to the footer (as per the designs) or leave it off for the time being?
* [x] Should we add in a number indicator in the bottom left (e.g. 1/5)?
* [x] Invert the fill / background colours of the icon buttons when they're hovered.
* [x] Conditionally hide the info and comment icons based on the site's Jetpack settings for showing Exif metadata / comments:

image

#### Jetpack product discussion

Designs: p9Jlb4-2cI-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Add an image gallery to a post on your test site
* With Jetpack active, and the Jetpack Carousel module activated, view the post on the front end of your site
* Click an image in the gallery to open up the carousel, and try out the info and comment buttons in the footer
* Go to the Jetpack settings and update the carousel to use the white colour scheme and check that the styling is correct (note: styling support for light theme hasn't been added yet) `/wp-admin/admin.php?page=jetpack#/writing`

image

### CODE REVIEW

**Comment by ramonjd** [comment]
puppy-love

The footer is working really well!

Main thing I see now is to work out why image translates and widths are not working. I think it's maybe why the image disappears when resizing the window.

When resizing my browser, some of the swiper.js calculations are coming out at `-3.69099e+08px`

**Comment by andrewserong** [comment]
I've added a few small CSS changes to clear up some duplicate CSS, add back in hiding prev/next buttons on mobile, and restore the padding for the footer that we had on the other PR. We might want to add a max width or more indented padding on desktop for the `.jp-carousel-info-extra` class on wider viewports so that the comments / info area isn't _too_ wide.

I also noticed that the Swiper next button doesn't appear to be visible on desktop (the element's there, but possibly one of the layers above it is hiding it?) Happy to keep digging tomorrow!

**Comment by sgomes** [comment]
I want to add a note that this PR will break compatibility with older browsers that don't support grid, such as IE 11. This would be fine for Jetpack 10.0, but no earlier than that.

And if we're going ahead with this change, then we should seriously rethink all of the existing CSS, as there would be no point for all the prefixed properties that are still in there.

**Comment by andrewserong** [comment]
Great points, thanks for the heads-up @sgomes (and for taking a look over our work)! I haven’t tested this PR in IE11 yet, but since we’re using a fairly simple layout, I wonder if it’ll hold up if we add in the -ms-grid prefixed version that it supports… it might be possible for us to get it working to maintain support? I can look into that tomorrow.

Agreed, though, once we can drop IE11, it’d be great to do a pass and clean things up. I’d be keen to look at replacing the light mode with CSS variables too, to streamline things.

**Comment by sgomes** [comment]
> Great points, thanks for the heads-up @sgomes (and for taking a look over our work)! I haven’t tested this PR in IE11 yet, but since we’re using a fairly simple layout, I wonder if it’ll hold up if we add in the -ms-grid prefixed version that it supports… it might be possible for us to get it working to maintain support? I can look into that tomorrow.

Yes, that's certainly possible! In my experience, it can be somewhat hard to achieve, however, depending on what features you're making use of. The CSS grid spec changed quite a bit between the time it was being tested in IE 11 and when it was eventually finished, and not everything is a great match 😕

> Agreed, though, once we can drop IE11, it’d be great to do a pass and clean things up. I’d be keen to look at replacing the light mode with CSS variables too, to streamline things.

Yes, that sounds great! 🙂

And while we're at it, the JS could use a pass as well! I just recently finished reimplementing it in ES5 without `jQuery`, but once IE 11 is out of the picture then we could make things a bit smaller and easier to read by switching to ES2015+ 😄

**Comment by apeatling** [comment]
For the slide indicator, let's use the dots if there are 5 or less images, and the numbers if there are more than 5. I think that matches the designs.

**Comment by apeatling** [comment]
If we can get the image caption as a single line at the bottom, as per the designs, that would be ideal. Tapping or clicking would expand to show it all. A fallback would be putting it in the meta when then (i) is hit.

**Comment by apeatling** [comment]
One other nice to have: When the image is zoomed hide the buttons, slide indicator, and close button.  When zoomed back to original size, show them again.

**Comment by apeatling** [comment]
For the last two with issues, I think it would be fine to get this merged and then follow up in separate PRs.

**Comment by ramonjd** [comment]
> Main thing I see now is to work out why image translates and widths are not working. I think it's maybe why the image disappears when resizing the window.

This seems to be fixed by giving the `.swiper-container` a width. 🗡️ 

squisht

**Comment by andrewserong** [comment]
Added conditionals to hide the icons based on whether or not the relevant features are switched on in `/wp-admin/admin.php?page=jetpack#/writing`.

With just exif switched on (comments disabled):
image

With just comments switched on (exif disabled):
image

With both disabled (just shows pagination):
image

**Comment by ramonjd** [comment]
> For the slide indicator, let's use the dots if there are 5 or less images, and the numbers if there are more than 5. I think that matches the designs.

✅ 

> If we can get the image caption as a single line at the bottom, as per the designs, that would be ideal. Tapping or clicking would expand to show it all. A fallback would be putting it in the meta when then (i) is hit.

✅ Although I used the title instead since most images will have a default value. The caption seems to never load, although the description does.

**Comment by andrewserong** [comment]
Update: we've now completed most of the work that we intended to do on the fixed footer, separately from the main feature PR (#20107). Now that the fixed footer is _mostly_ working as we would like it to, we'll merge this PR into that parent PR, and we can continue the discussion over there. Here is what the footer currently looks like:


https://user-images.githubusercontent.com/14988353/123210560-82be6280-d505-11eb-899f-c20a76c91478.mp4

As for IE11 support, I didn't have much luck using the `-ms-grid` prefixed approach, however in IE11 the buttons will display below the swiper by default anyway, so in terms of the buttons/footer I don't think it's a deal breaker, as the existing carousel has scroll on IE11, too. The bigger issue is that the current version of Swiper doesn't appear to work on IE11, so we'll need to explore a fallback over on #20107 (discussion raised in: p1624501255365700-slack-CS0SC36SX)

**Pull request merged**
