### PR TITLE
lacking valid underscores from mixcloud url

### PR DESCRIPTION
**Pull request by verybigelephants**
example https://www.mixcloud.com/radiofm/balaz-a-hubinak_fm-27102017/

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

### CODE REVIEW

**Comment by verybigelephants** [comment]
example https://www.mixcloud.com/radiofm/balaz-a-hubinak_fm-27102017/

**Comment by jeherve** [comment]
Thanks for the contribution!

Could you edit the pull request description to add more details about how we can test this change and make sure existing embeds are not broken?

Thank you!

**Comment by verybigelephants** [comment]
i actually don't even know what repository i am fixing it in so i don't know how could you test it. 
i have just googled "regexp mixcloud id from url" or something like that and it showed me this file, from which i took the code and used in my project. there i saw there was a bug and it didn't parse the underscores correctly. so i fixed it in my project and thought i would contribute back. you don't have to use it if you don't want to, i'm not exactly sure how to test it in your software :(

**Comment by jeherve** [comment]
Thanks for the extra details! We'll try to reproduce an issue and test your patch against it!

**Comment by alisterscott** [comment]
The URL mentioned works when I directly embed this in the editor.  The shortcode doesn't seem to be working at the moment, I've raised that separately as #9006 

Closing this issue as there doesn't seem to be necessary any more.

**Pull request closed without merging**
