### PR TITLE
Admin Menu: Follow-up tasks from initial commit

### LINKED ISSUE #17973: Admin Menu: Jetpack Scan should not be a feature of simple sites
#### Steps to reproduce

1. Create a WordPress.com simple site
2. Visit WordPress.com
3. Browse to Jetpack -> **Scan**
4. Get a 404

#### What I expected

Scanning and security are part of WordPress.com by default, we do not need this menu item.

#### What happened instead

A 404.

#### Browser / OS version

Chrome 87 / OSX 10.15.7

#### Screenshot / Video

Screenshot 2020-12-04 at 09 45 24

#### Context / Source

 #manual-testing

### PR DESCRIPTION
**Pull request by obenland**
This PR tries to fix as many of the things @jeherve pointed out in the original PR as possible.
See https://github.com/Automattic/jetpack/pull/17629#pullrequestreview-544243248

Fixes #17973

#### Changes proposed in this Pull Request:

* Updates version numbers to reflect the version this will ship in.
* Removes Scan & Backup submenu items to let Jetpack Scan handle them.
* Accounts for missing grofiles plugin on WoA sites. Falls back to `profile.php` again.
* Adds conditions for menu items that are wpcom-only.

#### Jetpack product discussion

https://github.com/Automattic/jetpack/pull/17629#pullrequestreview-544243248

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* On your Jetpack test site, make sure you have the Masterbar module active
* Check that the Jetpack menu item doesn't contain "Scan" and "Backup" menu items anymore.
* Check that the Settings > Domains and Settings > Hosting Configuration menu items don't show up on Jetpack sites. They should still be visible for simple and atomic sites.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Review by getdave — CHANGES_REQUESTED** [review]
I tested this on a _Simple_ site by applying D54069-code and enabling the experiment.

I found the following:

## Check that the Jetpack menu item doesn't contain "Scan" and "Backup" menu items anymore.

This seemed to work well.

| Calypso          | WPAdmin | 
|--------------|------------|
| Screen Shot 2020-12-15 at 12 13 22         | Screen Shot 2020-12-15 at 12 12 31            | 

## Check that the Settings > Domains and Settings > Hosting Configuration menu items don't show up anymore.

This didn't work. I still saw those menu items.

| Calypso          | WPAdmin | 
|--------------|------------|
| Screen Shot 2020-12-15 at 12 14 29 | Screen Shot 2020-12-15 at 12 14 54 |

**Comment by obenland** [comment]
> Check that the Settings > Domains and Settings > Hosting Configuration menu items don't show up anymore.

That implied the context of Jetpack sites, my bad. I updated the description to be more detailed. Your test results are correct, they _should_ still show up on simple sites.

**Review by cpapazoglou — APPROVED** [review]
**Regarding "Backup", "Scan"**
On a Jetpack connected site I can confirm that I can no longer see "Backup", "Scan". I can see though an external link "Backup & Scan" leading to `https://jetpack.com/redirect/?source=calypso-backups&site=[domain]` which I suppose is what we want?



On a Simple site, I can no longer see "Backup", "Scan" as you mentioned. **BUT "Backup" should be shown! Only "Scan" is invalid!** This the backup screen for simple sites 



**Regarding "Domains", "Hosting Configuration"**
- Works as expected in Simple, Atomic, and Jetpack sites

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by obenland** [comment]
r218438-wpcom

**Comment by cpapazoglou** [comment]
👋  @obenland ! Did you have a chance to make sure that "Backup" is shown on simple sites per my [comment above](https://github.com/Automattic/jetpack/pull/18041#pullrequestreview-553931348)?

> On a Simple site, I can no longer see "Backup", "Scan" as you mentioned. BUT "Backup" should be shown! Only "Scan" is invalid! This the backup screen for simple sites

**Pull request merged**
