### PR TITLE
Jetpack: Improve UX when rendering the VideoPress player

### PR DESCRIPTION
**Pull request by retrofox**
The goal of this PR is improves the UX when the video player is rendered in the editor canvas, tackling two stations:

### The initial render of the block
Currently, when the block renders the height is unknown producing a height zero element. Once the block gets the video preview, it renders the sandbox (iFrame) to finally shows the player in its ready-to-use state.
This PR, gets the width and height of the video, provided by the preview object, to compute the video ratio to finally store it into a new block attribute.
With this ratio value, it is possible to set the block height either when the preview is not available. It's named like `temporaryHeight` that, as its name explains, it's used only when the preview is not ready. The result is shown below, comparing this implementation with the current one. Pay attention to the caption and the `<hr />`, observing the block height. It doesn't change with this suggestion.

https://user-images.githubusercontent.com/77539/177217288-4fba7e9b-9a8a-42b0-b132-8be1258761ff.mov

https://user-images.githubusercontent.com/77539/177217281-6abf27fa-bf3d-4895-b25d-fcb9558c2227.mov

### Fallback image
Taking advantage of the preview provided by the VideoPress infrastructure, the block stores the video thumbnail image in a new attribute.
This attribute is used to render the static image behind the Sandbox, providing a fallback image shown when the video preview is not ready, something that happens pretty often (editing video props, for instance).
The first video of the follow ones, shows how the block renders the fallback image when the user changes the video properties, producing a fetch to get the fresh preview.

https://user-images.githubusercontent.com/77539/177217143-856ff343-e9fe-4dec-b2b3-a151b7e90038.mov

The next one, shows how it doesn't show the video when the player attributes change (current implementation)

https://user-images.githubusercontent.com/77539/177217991-f636a192-6061-467e-a69c-1e82ec6d22b9.mov

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack: Improve UX when rendering the VideoPress player:
  - Set a temporary height when the block is first rendered
  - Add an image fallback when the video preview is loading

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Go to block editor
* Confirm the enhancements mentioned above, in the PR description.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202514379845525
  - 0-as-1202514379845507

### CODE REVIEW

**Review by leogermani — COMMENTED** [review]
I can't really reproduce the zero-height player. It always keep the video height even before loading or when tweaking attributes (before applying this branch). But otherwise it works...

One thing I noticed is that the overlay that allows me to click on the block without interacting with the video is gone... now I can't select the block easily

**Comment by retrofox** [comment]
> One thing I noticed is that the overlay that allows me to click on the block without interacting with the video is gone... now I can't select the block easily

Nice one. Addressed here https://github.com/Automattic/jetpack/pull/24891/commits/9ca2ccf2aa38c3977895bad71a277320a0cd48bd

> I can't really reproduce the zero-height player. It always keep the video height even before loading or when tweaking attributes (before applying this branch).

Because we've been working on the preview process, too. It catches the HTML representation to be used next time asap while it requests a fresh one. It's nice to don't detect the flickrs meaning the process works.
Being said this, we should be able to detect it at the very initial uploading of the video, when the HTML cache is not available.


https://user-images.githubusercontent.com/77539/177619216-a4a43239-f689-4959-82a0-04ec5e50061c.mov



> But otherwise it works...

👍

**Comment by retrofox** [comment]
> I can't really reproduce the zero-height player. It always keep the video height even before loading or when tweaking attributes (before applying this branch).

Sorry, this is compared with the current implementation. Compared with VPBlock, there is not a big difference. However, sometimes the fallack image is shown when the video preview is not ready.

**Review by leogermani — APPROVED** [review]

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D83402-code, and deploy it.

r248620-wpcom

**Pull request merged**
