### PR TITLE
Update/videopress match feature check criteria

### PR DESCRIPTION
**Pull request by jgcaruso**
Fixes # 1272-gh-Automattic/greenhouse

#### Changes proposed in this Pull Request:

* Updated the criteria for showing upsells in the Jetpack -> Dashboard for VideoPress to match what is used in Performance -> Media

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Add a Jetpack Premium plan to your test site
* Visit Jetpack -> Dashboard
* You should not see the VideoPress upsell for a paid plan
* Remove the plan and add a plan that doesn't include VideoPress (ex a Security plan with a recent purchase date)
* Visit Jetpack -> Dashboard again, you SHOULD see the upsell
* Try again with no plan, you SHOULD see the upsell
*

### CODE REVIEW

**Review by thedebian — DISMISSED** [review]
Worked well, I saw VideoPress was still considered as included with a Security (1TB) and a Security Daily plan, so I guess the tests instruction are not up-to-date, the upsell was showing up fine on a Jetpack Search plan for instance.
👍 :shipit:

**Comment by bindlegirl** [comment]
@jgcaruso Do you think this PR can get reviewed by the team before the Jetpack beta branch is cut? Or we can push this change to the next version?

**Comment by jgcaruso** [comment]
> @jgcaruso Do you think this PR can get reviewed by the team before the Jetpack beta branch is cut? Or we can push this change to the next version?

Thanks for the nudge on this, looks like it slipped through the cracks. I'll get my team to re-review this morning.

**Review by roundhill — APPROVED** [review]
Code looks fine, but my local Jetpack is giving me fits -- @Automattic/jetpack-crew can you please verify functional changes when you review?

**Review by sdixon194 — APPROVED** [review]
Works for me functionally!

**Pull request merged**
