### PR TITLE
Build: Remove explicit Babel dependencies

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request:

Per #11949, Jetpack relies on `@automattic/calypso-build` for all its Babel transforms. There are no more direct mentions of any other individual Babel plugins or presets in Jetpack's codebase, so it's safe to remove those dependencies from `package.json`

#### Testing instructions:

```
yarn distclean && yarn
yarn build-extensions
```

Verify that blocks still build and work.

#### Proposed changelog entry for your changes:

N/A

### CODE REVIEW

**Comment by kraftbj** [comment]
A lot of warnings: `warning "@automattic/calypso-build > @babel/plugin-proposal-class-properties@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".` and a lot of errors for me. Tried with node 11 and node 10.

**Comment by simison** [comment]
>A lot of warnings

Yeah, this depends on merging this and publishing a new version: https://github.com/Automattic/wp-calypso/pull/32201

**Comment by ockham** [comment]
> > A lot of warnings
> 
> Yeah, this depends on merging this and publishing a new version: [Automattic/wp-calypso#32201](https://github.com/Automattic/wp-calypso/pull/32201)

Done, and updated this PR to use that new version. Should be ready for another look.

**Comment by simison** [comment]
Still seeing these:
```
warning " > babel-loader@8.0.5" has unmet peer dependency "@babel/core@^7.0.0".
warning " > @babel/register@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@wordpress/jest-preset-default > babel-jest@24.7.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "@wordpress/jest-preset-default > babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
```

I don't think we can remove the babel/core dependency considering Jest will need it?

**Comment by ockham** [comment]
> Still seeing these:
> 
> ```
> warning " > babel-loader@8.0.5" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > @babel/register@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@wordpress/jest-preset-default > babel-jest@24.7.1" has unmet peer dependency "@babel/core@^7.0.0".
> warning "@wordpress/jest-preset-default > babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
> ```
> I don't think we can remove the babel/core dependency considering Jest stuff will need it?

Ah, true dat. I added it back and rebased :+1:

**Review by simison — DISMISSED** [review]
🚀

**Comment by ockham** [comment]
Rebased. Needs another :heavy_check_mark:  please :grimacing:

**Review by simison — APPROVED** [review]

**Comment by simison** [comment]
There was some "Fusion issue" concern: https://github.com/Automattic/jetpack/pull/12035#issuecomment-483861114

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
The Fusion issue there was a modified phab that passed didn't return a passing status report for the GitHub issue, so nothing with the actual change itself.

**Pull request merged**
