### PR TITLE
Jetpack Sync: Remove 'admin_action_update' hook from Sync Plugins module

### PR DESCRIPTION
**Pull request by fgiannar**
The `admin_action_update` hook is no longer fired when making plugin edits in the `plugin-editor` screen, and as of WP 4.9 we added the `wp_ajax_edit-theme-plugin-file` listener (which covers detecting plugin edits in the `plugin-editor` screen) via https://github.com/Automattic/jetpack/pull/8459 anyways.
This PR removes the `admin_action_update` hook from the Plugins module and its corresponding action.

## Proposed changes:

* `Automattic\Jetpack\Sync\Modules\Plugins`: Remove `admin_action_update` hook and `check_plugin_edit` method.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p9dueE-8ca-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Code Review: Any WP version we support (6.4 or higher) where the `admin_action_update` hook is fired in `plugin-editor` screen (when making plugin edits) while `wp_ajax_edit-theme-plugin-file` is not? 
* Edit a plugin file in the Plugin Editor and confirm the corresponding action is synced.

### CODE REVIEW

**Comment by fgiannar** [comment]
@enejb Added you as a reviewer mostly for a confirmation on the first part of the review since you implemented https://github.com/Automattic/jetpack/pull/8459:

> Code Review: Any WP version we support (6.4 or higher) where the admin_action_update hook is fired in plugin-editor screen (when making plugin edits) while wp_ajax_edit-theme-plugin-file is not?

Many thanks!

**Review by darssen — DISMISSED** [review]
Thanks for keeping the codebase tidy Foteini!

I have inspected the code and tested in my local that the sync action is still being processed. 

As for confirming below, I'll leave it for @enejb as suggested.
> Code Review: Any WP version we support (6.4 or higher) where the admin_action_update hook is fired in plugin-editor screen (when making plugin edits) while wp_ajax_edit-theme-plugin-file is not?

**Comment by enejb** [comment]
The change seems safe to make. 

We implemented this sync feature at the time so that a user would be able to see if someone edited a plugin in the activity log. 
If in the end you are able to see the plugin edit in the activity log then I think this is safe to do. 

Thanks for all the clean up!

**Review by darssen — DISMISSED** [review]
LGTM!

**Review by darssen — APPROVED** [review]
:ship:

**Pull request merged**
