### PR TITLE
Remove toolbar 'edit' control from the Contact Form block

### LINKED ISSUE #26867: Jetpack: Contact Form - Remove toolbar control
This control toolbar shows an edit button (with the pencil icon) that only offers a redundant location for the form controls

We should remove this and favor the controls located in the Inspector

Image

### PR DESCRIPTION
**Pull request by ice9js**
Fixes #26867

#### Changes proposed in this Pull Request:

This patch removes the 'Edit' dropdown from the Contact Form block's toolbar, which was just a duplicate of the settings already contained in the sidebar - which is the expected place for such settings in Gutenberg anyway.  
This helps un-clutter the block UI.

Before:
Screenshot 2022-10-18 at 18 51 01

After:
Screenshot 2022-10-18 at 18 50 44

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

- Checkout the branch and start/edit a post or a page in the block editor.
- Insert a Contact Form block.
- Make sure the Contact Form block is focused (clicking on the block once will focus the Contact Form block, subsequent clicks may focus child blocks).
- There should be no 'Edit' option in the block toolbar.

### CODE REVIEW

**Review by jcheringer — APPROVED** [review]
Works for me!

**Comment by CGastrell** [comment]
LGTM! We need to change pics here: https://jetpack.com/blog/wordpress-contact-form/

**Comment by oskosk** [comment]
Rebased in https://github.com/Automattic/jetpack/pull/26911/commits/c5a1a4c12db57c3419ecb6c079ca9178e6669756

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by oskosk** [comment]
Updated https://wordpress.com/support/wordpress-editor/blocks/form-block/ removing the section "Control toolbar" which was just there to reference this control we just removed

Also 
* https://es.support.wordpress.com/editor-wordpress/bloques/bloque-formulario/

**Comment by oskosk** [comment]
🤦  There are a lot of languages to update

image

**Pull request merged**
