### PR TITLE
WPCOM Simple Site: Remove add license link in the Search upsell page

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed changes:

This PR removes the link to admin.php?page=my-jetpack#/add-license in the Search upsell page for WPCOM Simple sites, due to My Jetpack not being available.

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply the changes in your sandbox.
* Head to Jetpack > Search and ensure that the link is no longer present.

### CODE REVIEW

**Review by fushar — APPROVED** [review]
Works as intended 👍

**Review by candy02058912 — APPROVED** [review]
Good catch!
Tested ✅ 
jetpack search

**Comment by taipeicoder** [comment]
@anomiex there are a couple of phpcs checks that are failing in this PR. I tried fixing them by changing the code to use nullable types. However, this causes the phpcs in the pre-commit hook to fail with the error:
Screenshot 2024-04-01 at 3 16 32 PM

Do you have any suggestions as to how to address this?

**Comment by arthur791004** [comment]
Referring to https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated, it seems dropping parameter type is the only possible way to avoid the deprecation notice while keeping the code compatible with PHP 7.0 and later even if it's highly discouraged...

Here is the related [ticket](https://core.trac.wordpress.org/ticket/60786) on WordPress Core

**Comment by arthur791004** [comment]
> Do you have any suggestions as to how to address this?

It will be disabled by https://github.com/Automattic/jetpack/pull/36673

**Comment by anomiex** [comment]
Now that https://github.com/Automattic/jetpack/pull/36673 is merged, a trunk merge here should fix things for you. See that PR for details on what exactly was going on.

**Review by DustyReagan — APPROVED** [review]

**Review by lupus2k — APPROVED** [review]
LGTM!

**Pull request merged**
