### PR TITLE
Infinite Scroll: Update posts_per_page setting

### PR DESCRIPTION
**Pull request by fgiannar**
#### Changes proposed in this Pull Request:

p3btAN-1io-p2

#### Jetpack product discussion
p3btAN-1io-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
p3btAN-1io-p2

#### Proposed changelog entry for your changes:

* n/a :: Minor enhancement in Infinite Scroll module

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
The tests appear to be failing at the moment:

```
There were 3 failures:
1) WP_Test_The_Neverending_Home_Page::test_max_posts_per_page_in_request with data set "posts_per_page_over_allowed_limit" (5001, 0)
Failed asserting that 10 is identical to 0.
/tmp/wordpress-master/src/wp-content/plugins/jetpack/tests/php/modules/infinite-scroll/test_class.infinite-scroll.php:32
2) WP_Test_The_Neverending_Home_Page::test_max_posts_per_page_in_request with data set "posts_per_page_not_numeric" ('not-numeric', 0)
Failed asserting that 10 is identical to 0.
/tmp/wordpress-master/src/wp-content/plugins/jetpack/tests/php/modules/infinite-scroll/test_class.infinite-scroll.php:32
3) WP_Test_The_Neverending_Home_Page::test_max_posts_per_page_in_request with data set "posts_per_page_negative" (-10, 0)
Failed asserting that 10 is identical to 0.
```

**Comment by fgiannar** [comment]
So it seems that when the corresponding unit tests I added run on their own, they pass:

`yarn docker:phpunit --filter=WP_Test_The_Neverending_Home_Page`

When they run with the rest they fail.

I investigated this and it looks that the Photon unit tests affect them.

`yarn docker:phpunit --filter='/WP_Test_Jetpack_Photon|WP_Test_The_Neverending_Home_Page/'`

and in particular [this line](https://github.com/Automattic/jetpack/blob/master/tests/php/test_class.jetpack_photon.php#L1221) which results in:
`self::wp_query()->get( 'posts_per_page' )` returning `10` [here](https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L256).

I would expect globals, such as `$wp_the_query` to reset to a default state after each test is run. Not sure why this happens here.

@brbrr Any suggestions or best practices for this case? Many thanks!

**Comment by fgiannar** [comment]
@jeherve I ended up [resetting](https://github.com/Automattic/jetpack/pull/17538/commits/7eee833e29f3d4d6452d2582f38ecf8b1884646e) the global `$wp_the_query` in the `tearDown` method of the corresponding Photon unit tests to fix this.
I wanted to make sure that this won't affect any other unit tests in the future, but ideally I'd prefer this to happen centrally (as it [already does](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#globals) with eg `$wp_query`).
There are some unit tests still failing but unrelated to this PR.

**Comment by brbrr** [comment]
Hi @fgiannar 

I guess, best practice would be to design tests to be isolated from one another. I don't know how PHPUnit works internally, but here is what I found.

PHPUnit runs tests in a single process, which might affect globals pollution. Setting `processIsolation="true"` in config might help here, but it might affect tests performance. 

Also, there is `beStrictAboutChangesToGlobalState` which might be helpful when identifying tests that pollute the global state.  

Docs: https://phpunit.readthedocs.io/en/9.3/configuration.html#the-processisolation-attribute

>  I ended up resetting the global $wp_the_query in the tearDown

I think this is the best approach here.

**Comment by fgiannar** [comment]
Hi @brbrr 

Thanks for all the valuable info.

> I think this is the best approach here.

Also thanks for confirming.

Globals such as `$wp_query` are reset [after every test](https://core.trac.wordpress.org/browser/trunk/tests/phpunit/includes/testcase.php?rev=29251#L54). 
This is not the case for `$wp_the_query` not sure why but I think it should also be handled centrally.
Since this is core functionality at least making sure that the corresponding tests clean up after themselves seemed to make sense.

Again thanks for sharing your thoughts!

**Review by jeherve — APPROVED** [review]

**Comment by fgiannar** [comment]
Seems that some unrelated flanky tests are causing the build to fail.
I have rebased couple of times but no luck so far.
@jeherve Any suggestions?

**Review by leogermani — APPROVED** [review]
re-approving after tests fixed

**Comment by fgiannar** [comment]
r215757-wpcom

**Pull request merged**
