### PR TITLE
Update/plugin api endpoint

### PR DESCRIPTION
**Pull request by enejb**
Adds the icons and whether the plugin is in the .org repo or not.

#### Changes proposed in this Pull Request:
* Adds the icons and whether the plugin is in the .org repo or not.
* Sync .org data to the jetpack shadow site.

#### Testing instructions:
* Do the tests pass?
* is the data available on the api.

### CODE REVIEW

**Comment by lezama** [comment]
@enejb  do we still need this one?

**Comment by lezama** [comment]
@enejb \o/

**Comment by enejb** [comment]
I am toren about this PR since we are just adding data from .org to the shadow site. Which is not great but we could use it to solve a bunch of issues.

**Comment by oskosk** [comment]
@enejb I've restarted the test-runs on this one. Is this PR still valid? 

I'm removing the needs review label until you reply. (I'm on review mode) Feel free to relabel. Thanks!

**Comment by brbrr** [comment]
Hey @enejb 
Is this PR is still valid? It needs rebasing.

**Comment by enejb** [comment]
I am going to close this PR untill we want to take this appraoch of adding that sort of data to the api.

**Pull request closed without merging**
