### PR TITLE
RNA Pricing card component: Fix case where prices before and after match

### PR DESCRIPTION
**Pull request by fgiannar**
RNA Pricing card component: Fix case where prices before and after match

#### Changes proposed in this Pull Request:

* Updates the `PricingCard` RNA component to display the price only once when price before matches price after.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
* Go to the Storybook folder `cd projects/js-packages/storybook`
* Run `pnpm install && pnpm run storybook:dev`
* Storybook should open in your browser.
* Go to Playground → Pricing Card and set the prices (`priceBefore` and `priceAfter`) to match.
* Verify that only one price gets displayed.

#### Screenshot
Screenshot 2021-11-16 at 2 43 20 PM

### CODE REVIEW

**Comment by fgiannar** [comment]
@keoshi Could you pls take a quick look as well? AFAIK this case was not in the designs, however just hiding the strike-through price should be enough I guess?

Many thanks!

**Review by keoshi — APPROVED** [review]
This looks excellent and is exactly how it should work! Ship it.

**Review by sergeymitr — APPROVED** [review]
:shipit:

**Comment by anomiex** [comment]
r235230-wpcom

**Pull request merged**
