### PR TITLE
Tiled gallery: fix 'from' transforms

### LINKED ISSUE #20264: Tiled Gallery: Transform From Gallery Doesn't Work
Similar to: https://github.com/Automattic/jetpack/issues/14536

- Add a gallery block and some images
- Transform the block into a tiled gallery block
- See the blank images.
- Save draft or refresh
- The block is now totally blank.

Clicking on the block, the blank images seem to fix themselves, but upon saving and refreshing, the block is blank again.

Surfaced again during internal testing p8oabR-GM-p2#comment-5385

### PR DESCRIPTION
**Pull request by glendaviesnz**
Fixes #20264

#### Changes proposed in this Pull Request:
* Adds a default columnWidths attributes so saved content is created when transforming from other galleries

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Check out PR to local dev env
* Add a Jetpack slideshow gallery and then transform it to a  Jetpack tiled gallery and make sure the image elements are saved in the post content
* Save the post and reload and make sure images still show in the tiled gallery
* Repeat for the core gallery and a single core image block

Before:
tiled-before

After:
after-tiled

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Thanks @glendaviesnz — this is testing well for me to resolve the issue where the images aren't being saved into the post content. After selecting to transform from a Slideshow, core gallery, or core image block, once I hit save and reload, the transformed block is now preserved 👍

The issue from #20264 where the block is stuck in what looks like a loading state until it's clicked or otherwise interacted with still appears to be at play. I can't _quite_ work out why, though — from looking at the `gallery-image/edit.js` file, it _appears_ as though we have the appropriate `url` value to be added as the `src` for the image element (I tried adding some logs to see what's going on). However in its state before we interact with it, the block lacks some of the image element properties. After interacting with the block, they get added back in.

Here's what's in the code view of the post before interacting with the block:

```
<!-- wp:jetpack/tiled-gallery {"columnWidths":[["100.00000"]],"ids":["434","433","432"]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col" style="flex-basis:100.00000%"><figure class="tiled-gallery__item"><img alt="" data-id="434" data-url="http://localhost:4759/wp-content/uploads/2021/07/trees-02-1024x576.jpg" data-amp-layout="responsive"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-id="433" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1-1024x681.jpg" data-amp-layout="responsive"/></figure><figure class="tiled-gallery__item"><img alt="" data-id="432" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1-1024x683.jpg" data-amp-layout="responsive"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

And here's what's in the code view of the post after interacting with the block:

```
<!-- wp:jetpack/tiled-gallery {"columnWidths":[["100.00000"]],"ids":[434,433,432]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col" style="flex-basis:100.00000%"><figure class="tiled-gallery__item"><img alt="" data-height="1080" data-id="434" data-link="http://localhost:4759/?attachment_id=434" data-url="http://localhost:4759/wp-content/uploads/2021/07/trees-02.jpg" data-width="1920" src="http://localhost:4759/wp-content/uploads/2021/07/trees-02.jpg" data-amp-layout="responsive"/></figure><figure class="tiled-gallery__item"><img alt="" data-height="1064" data-id="433" data-link="http://localhost:4759/?attachment_id=433" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1.jpg" data-width="1600" src="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1.jpg" data-amp-layout="responsive"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="1000" data-id="432" data-link="http://localhost:4759/?attachment_id=432" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1.jpg" data-width="1500" src="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1.jpg" data-amp-layout="responsive"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

I wonder if we somehow need to trigger the component to be re-rendered?

Overall, though, I don't think that should block getting this fix in, as this resolves the main problem of losing content after the transform, and the content is preserved after save. But I was a bit stumped trying to debug why the `img` elements didn't appear to update with the correct `src` prop 🤔

I'm giving this the ✅ so we can get the initial fix in in the short-term. Let's see if other folks have ideas about the loading state.

**Comment by glendaviesnz** [comment]
@andrewserong the issue with the first rendering should be fixed now [by this change](https://github.com/Automattic/jetpack/pull/20583/commits/5acce004fdf70236d31e46affb0d37568abc09c6#diff-9d9e38e0f9e8af6b764c8b3fdd83aa56a7f2709012db7a79cd2d359f515652e8R36) if you want to give it a retest.

**Comment by andrewserong** [comment]
Thanks @glendaviesnz! This now gets the images loading immediately after transforming the block from Gallery -> Tiled Galleries 👍

There's now another minor issue, but it's less critical than the loading state was. After the transformation is run, but before clicking on it, the first `tiled-gallery__col` class container only has a single image in it (with the other two in the next column), but after clicking on the tiled gallery, the markup is updated, and the first column has two images in it, with the second column having a single image.

| After transform, before clicking on gallery | After transform, after clicking on gallery |
| --- | --- |
| image | image |

## Markup before clicking on the Tiled Gallery

```
<!-- wp:jetpack/tiled-gallery {"columnWidths":[["100.00000"]],"ids":["434","433","432"]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col" style="flex-basis:100.00000%"><figure class="tiled-gallery__item"><img alt="" data-id="434" data-link="http://localhost:4759/?attachment_id=434" data-url="http://localhost:4759/wp-content/uploads/2021/07/trees-02-1024x576.jpg" src="http://localhost:4759/wp-content/uploads/2021/07/trees-02-1024x576.jpg" data-amp-layout="responsive"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-id="433" data-link="http://localhost:4759/?attachment_id=433" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1-1024x681.jpg" src="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1-1024x681.jpg" data-amp-layout="responsive"/></figure><figure class="tiled-gallery__item"><img alt="" data-id="432" data-link="http://localhost:4759/?attachment_id=432" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1-1024x683.jpg" src="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1-1024x683.jpg" data-amp-layout="responsive"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

## Markup after clicking on the Tiled Gallery

```
<!-- wp:jetpack/tiled-gallery {"columnWidths":[["100.00000"]],"ids":[434,433,432]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col" style="flex-basis:100.00000%"><figure class="tiled-gallery__item"><img alt="" data-height="1080" data-id="434" data-link="http://localhost:4759/?attachment_id=434" data-url="http://localhost:4759/wp-content/uploads/2021/07/trees-02-1024x576.jpg" data-width="1920" src="http://localhost:4759/wp-content/uploads/2021/07/trees-02-1024x576.jpg" data-amp-layout="responsive"/></figure><figure class="tiled-gallery__item"><img alt="" data-height="1064" data-id="433" data-link="http://localhost:4759/?attachment_id=433" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1-1024x681.jpg" data-width="1600" src="http://localhost:4759/wp-content/uploads/2021/07/desert-01-1-1024x681.jpg" data-amp-layout="responsive"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="1000" data-id="432" data-link="http://localhost:4759/?attachment_id=432" data-url="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1-1024x683.jpg" data-width="1500" src="http://localhost:4759/wp-content/uploads/2021/07/desert-02-1-1024x683.jpg" data-amp-layout="responsive"/></figure></div></div></div></div>
```

The difference in markup is pretty subtle, so here's a slightly clearer picture of it from diff checker:

image

I imagine this might be caused by the images (before click) not yet having widths and heights, so the calculations for the Mosaic result in a different layout after click, when the images now have widths and heights to be calculated? I'm not quite sure how we'd fix that 🤔, but would a workaround be to set the style for the block to "Tiled columns" instead to avoid the calculation entirely?

**Comment by glendaviesnz** [comment]
> but would a workaround be to set the style for the block to "Tiled columns" instead to avoid the calculation entirely

I tried setting a default of tiled columns, but it still resizes when you click on the block. Because the gallery has no sizes to pass through, and there is a resize/mutation observer in the tiled gallery that is recalculating things on interaction I think there would be a bit of rework needed to sort this. I think we should leave that as a follow up if it is thought to be critical.

**Review by andrewserong — APPROVED** [review]
> I think we should leave that as a follow up if it is thought to be critical.

Agreed, thanks for digging into this @glendaviesnz! This PR as-is already improves things considerably and fixes the main bug. LGTM! 😀

**Review by jeherve — COMMENTED** [review]
I can't get this to work for some reason.

When I transform a classic gallery into a tiled gallery, the transform originally seems to work in the editor (no errors, no js errors, the images appear in the new tiled gallery). However, when I preview my changes the gallery is nowhere to be found. And when I update the post, and then refresh the editor, the tiled gallery block is empty:

image

However when I view the HTML for the block, I get this:

```
<!-- wp:jetpack/tiled-gallery {"columnWidths":[["100.00000"]],"ids":[16246,16247,16248,16249,16250]} /-->
```

Any idea why this is happening?

**Comment by glendaviesnz** [comment]
> When I transform a classic gallery into a tiled gallery

Can you give me some more details about the steps you took to transform a 'classic' gallery? Do you mean a gallery added via the Classic block? I tried adding a gallery to a Classic block, and then converting it to blocks, and then to a tiled gallery and it worked as expected when saved and reloaded.

**Comment by jeherve** [comment]
> I tried adding a gallery to a Classic block, and then converting it to blocks, and then to a tiled gallery and it worked as expected when saved and reloaded.

This was one of the ways that I tried indeed. The other was adding a core Gallery block, and then transforming it into a tiled gallery.

**Comment by glendaviesnz** [comment]
> This was one of the ways that I tried indeed. The other was adding a core Gallery block, and then transforming it into a tiled gallery.

That is strange, I wonder what is different about your setup? I just tried again locally and the transform is working as expected with this PR checked out:
transform

**Comment by jeherve** [comment]
If that helps, I'l send you a link to the site where I tested this!

**Comment by glendaviesnz** [comment]
> If that helps, I'l send you a link to the site where I tested this!

If you can give me admin or author access to that site I will take a look and see if I can work out what is going on.

**Comment by jeherve** [comment]
I sent you the admin credentials via Slack. Let me know if it helps!

**Comment by glendaviesnz** [comment]
@jeherve on your test site, I switched the Jetpack beta plugin to this branch, and after I did that the gallery transform works as expected for me:

tiled-test

**Comment by glendaviesnz** [comment]
> @jeherve on your test site, I switched the Jetpack beta plugin to this branch, and after I did that the gallery transform works as expected for me (not easy to see in the following, but the final step after updating the post was a browser refresh):
> 
> tiled-test

**Review by jeherve — APPROVED** [review]
And now it works just fine  ¯\_(ツ)_/¯ This should be good to merge then! :)

**Comment by glendaviesnz** [comment]
rWP230501

**Comment by glendaviesnz** [comment]
Looks like this fix turned out to be the wrong approach - doesn't work for galleries with 4 or more images. Alternative approach at https://github.com/Automattic/jetpack/pull/20928

**Pull request merged**
