### PR TITLE
Social | Fix publicize crashing when activated from the editor

### PR DESCRIPTION
**Pull request by manzoorwanijk**
When Jetpack is active and the publicize module is off, if you try to activate publicize from the editor, it crashes.

Image

The reason for the issue is lack of some script data (initial state) that sets things up when social is activated.

## Proposed changes:

* Pass the bare minimum scipt-data to the editor when Social is turned OFF

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Turn OFF publicize from Jetpack settings > Sharing
- Goto Editor
- Open Jetpack sidebar
- Expand "Share this post" panel
- Click on "Activate Jetpack Social"
- Confirm that the module is activated and there is no error
- Goto Social settings page
- Confirm that the information and settings on the page are correct

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
> Confirm that the module is activated and there is no error

The module was activated, but if I then click on "Connect an account", I do not get any available networks in the modal:
Screenshot 2024-11-28 at 10 12 11

**Comment by manzoorwanijk** [comment]
> The module was activated, but if I then click on "Connect an account", I do not get any available networks in the modal:

Yeah, that's what we have for now and that has always been like that. It's because we cannot fetch the supported networks from WPCOM unless publicize is activated.

I will create a follow up task to create a REST endpoint to fetch the networks list when the module is activated.

**Comment by manzoorwanijk** [comment]
I have added it to our board https://github.com/Automattic/jetpack-reach/issues/704

**Comment by pablinos** [comment]
> I will create a follow up task to create a REST endpoint to fetch the networks list when the module is activated.

I think if we're doing that then we should do what we were discussing and get the initial state after the module is activated. 

@jeherve - @manzoorwanijk and I were discussing that this feature creates a few headaches where the module needs to be in a strange half-activated state to render the nudge and button. What do you think about swapping it to a link out to the settings screen to enable the feature? We could merge this for now of course, to stop the error, but creating extra endpoints etc seems like too much effort right now.

**Comment by jeherve** [comment]
> What do you think about swapping it to a link out to the settings screen to enable the feature?

It's not perfect, but that may indeed be the best UX we can hope for. 👍

**Comment by manzoorwanijk** [comment]
Closing in favour of #40390

**Pull request closed without merging**
