### PR TITLE
AMP: do not load sharing resources when not necessary

### LINKED ISSUE #22366: Don't load social-logos.eot font file on AMP pages if Sharing is not enabled.
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Ensure sharing is not enabled.
2. Activate the AMP plugin: https://en-gb.wordpress.org/plugins/amp/
3. View the AMP version of any page.

### A clear and concise description of what you expected to happen.

Since Sharing is not enabled, no resources related to Sharing should be loaded.

### What actually happened

The page source code shows that the social-logos.eot file is being loaded.

### Other information

Reported in https://wordpress.org/support/topic/how-to-remove-preloading-of-social-logos-eot-from-all-pages-2/

### Operating System

macOS

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #22366

#### Changes proposed in this Pull Request:

* The Social Logos stylesheet is a dependency of the `sharedaddy-amp` stylesheet, used by the AMP plugin. That stylesheet is not always necessary though, especially when using Legacy Mode in the AMP plugin, where CSS is directly included in the page (see `amp_reader_sharing_css`).

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start a new site with both the AMP plugin and this branch.
* Go to Jetpack and connect the plugin to WordPress.com
* Once connected, go to `wp-admin/admin.php?page=jetpack_modules` and disable all modules, including sharing.
* Go to AMP > Settings.
* Switch between different template modes, and for each mode:
    * On the frontend, load a single post's view.
    * Click on the "AMP" button in the admin bar to load the AMP view.
    * You should never see the `social-logos.eot` file loaded on the page.
* Go back to `wp-admin/admin.php?page=jetpack_modules` and enable the Sharing feature.
* Re-do the above:
    * The sharing buttons should look good in every template mode.`

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Seems to do the trick!

**Comment by jeherve** [comment]
r238613-wpcom

**Comment by earcos** [comment]
Hi. This is still happening on Jetpack 10.7+ (10.8-a1 as well) on WordPress.com in AMP pages.

The plugin is preloading `social-logos.eot` and adding the font on the theme's CSS.

Even though social sharing buttons are disabled in Jetpack.

Thanks a lot.

**Comment by jeherve** [comment]
@earcos Thanks for the report. Could you tell me more about your site, its AMP Settings, and its theme, so I can try to reproduce the problem on my end?

**Comment by kervis** [comment]
> @earcos Thanks for the report. Could you tell me more about your site, its AMP Settings, and its theme, so I can try to reproduce the problem on my end?

same problem with generate press, amp plugin, and amp for generatepress plugin in github

**Pull request merged**
