### PR TITLE
Fix contact widget error message style

### LINKED ISSUE #13361: Contact Info Widget: improve styles for error messages displayed for map
> When omitting an API key, the feedback/error is teeny tiny and could be easily missed:
> A little extra padding would certainly help. I am thinking perhaps a stronger border too – to separate the white on white problem.

image

cc @scottsweb

### PR DESCRIPTION
**Pull request by rakmob42**
#### Changes proposed in this Pull Request:

* Fixes: https://github.com/Automattic/jetpack/issues/13361

#### Testing instructions:

* Go to widget > add `Contact Info & Map widget` 
* Save without an API key
* It returns an error but this fix makes it a little more visible (and hard to miss). 

Screen Shot on 2019-10-05 at 07:19:57

#### Proposed changelog entry for your changes:

* Fixes for error messages in "Contact Info & Map" widget.

### CODE REVIEW

**Comment by jeherve** [comment]
See comment here:
> Where does the red colour you have chosen come from? Is it a colour used in core already? It looks quite different to the Delete below it for example.

**Comment by codestor4** [comment]
Update: Replied to @scottsweb in the issue - https://github.com/Automattic/jetpack/issues/13361#issuecomment-538922411

**Comment by codestor4** [comment]
The latest commit has the changes suggested by Scott (i.e. correct color code/css-class for the error message).

Screen Shot 2020-03-07 at 15 12 37

**Comment by codestor4** [comment]
@jeherve @kraftbj This should be good to go in 8.4

**Review by jeherve — APPROVED** [review]
This looks good to me. It should be good to go once the tests pass. Thank you!

**Pull request merged**
