### PR TITLE
External Media: Update Google Photos connect

### PR DESCRIPTION
**Pull request by obenland**
Clarifies the Google Photos context as requested in their [UX guidelines](https://developers.google.com/photos/library/guides/ux-guidelines).

#### Changes proposed in this Pull Request:

* Update body and button text in the Google Photos connect modal.

#### Jetpack product discussion

See p4hfux-5P7-p2#comment-8601

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Go to the Editor and insert an image block.
* Click Select image
* Click Google Photos
* The changes should be visible in the modal that opened.

### CODE REVIEW

**Review by retrofox — APPROVED** [review]
I think the paragraphs don't look very well since they should be only one line per paragraph or two lines balanced in length.

This PR | Suggestion
-----|-----
image | image

Anyway, LGTM. 🚀 !

**Comment by obenland** [comment]
I also just wondered if that information about how to remove the connection is even needed, given that customers can disconnect right from within the modal.

**Comment by retrofox** [comment]
> I also just wondered if that information about how to remove the connection is even needed, given that customers can disconnect right from within the modal.

🤷

**Review by mreishus — APPROVED** [review]
LGTM. I prefer the 'how to disconnect' blurb being there, as it assures someone connecting that it's possible to disconnect in the future, where they might not know that.

**Review by jeherve — APPROVED** [review]

**Comment by obenland** [comment]
Deployed in r232366-wpcom

**Pull request merged**
