### PR TITLE
CRM: Fix version and add old changelogs

### PR DESCRIPTION
**Pull request by tbradsha**
While updating the CRM sites to PHP 8.2 I tested the API Connector and noticed it was retrieving the CRM version as 6.4.2  instead of 6.4.3 because a version bump was missed in the last release. This PR fixes it.

Also, while retiring some old sites I noticed some historical data that was missing from the current changelog. I merged the two changelog files and backfilled the old changelog entries. I fixed a few minor typos in the process.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Make sure each entry has a consistent header entry and date format.

### CODE REVIEW

**Comment by cleacos** [comment]
> I noticed some historical data that was missing from the current changelog. I merged the two changelog files and backfilled the old changelog entries

If I recall well, we decided to keep the old changelog in one file and the new one in another one. But I remember why we did it.

**Review by cleacos — APPROVED** [review]
Other than my comment above... I don't recall why we did it. I think is fine to merge both.

LGTM!

**Comment by tbradsha** [comment]
> I don't recall why we did it.
* The v4-v5 logs were probably not added to the new file because it was a different format. This PR standardizes it.
* The pre-v4 logs were removed in v4, likely because it was in `readme.txt` and was just getting too long. Now that we have a separate changelog file, there's no reason to not have it all. This PR adds a standardized version of the old entries.

**Comment by cleacos** [comment]
> probably not added to the new file because it was a different format

That is 👍

**Pull request merged**
