### PR TITLE
Instant Search: don't include highlight markup in alt text

### LINKED ISSUE #20188: Instant Search: image alt text can include HTML
#### Steps to reproduce the issue

1. Go to https://bazaarica.com/?lang=en&s=Bioxcin%20Quantum%20Hair%20Loss

#### What I expected
A sensible `alt` text is available for images.

#### What happened instead
There are some missing images in the results, and the `alt` text contains HTML:

Screen Shot 2021-06-28 at 09 58 50

The ideal solution here would be to use the correct image alt text (as described in https://github.com/Automattic/jetpack/issues/19273) but an interim solution could be to add the existing content as `image.alt` to the API response and ensure HTML is stripped from it.

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes #20188.

#### Changes proposed in this Pull Request:
Ensure HTML is stripped from alt text where images are displayed in Instant Search results.

Currently we generally use the post title as the alt text (until we can get the correct alt text into the index - see https://github.com/Automattic/jetpack/issues/19273). If the title matches a search keyword, it will contain a `<mark>` element. We do not want this element to appear in the image alt.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. On a site with Instant Search installed, select the 'Expanded' result format in the Customizer.
2. Add a test post with a featured image.
3. Search for the post by title - e.g. if the post is called "Hello World", search for "hello".
4. Inspect the image in the search result and ensure there are no `<mark>` tags in the output.
5. Repeat the same check with the 'Product' result format. You can use `&result_format=product` to check this.

Screen Shot 2021-06-28 at 12 44 16

Before:
Screen Shot 2021-06-28 at 12 43 49

After:

Screen Shot 2021-06-28 at 12 43 55

### CODE REVIEW

**Comment by bluefuton** [comment]
DOMParser browser support (includes IE11): https://developer.mozilla.org/en-US/docs/Web/API/DOMParse

**Comment by kangzj** [comment]
@bluefuton could we use the default title which has no highlights, which I guess is for this purpose? But not 100% sure `title.default` would always be pure text tho.

image

**Comment by bluefuton** [comment]
> could we use the default title which has no highlights, which I guess is for this purpose

Sometimes the obvious solution is just staring you in the face :) Thanks @kangzj! We'll use that.

**Review by kangzj — APPROVED** [review]
Look good to me. Good job 👍

**Review by jeherve — APPROVED** [review]

**Comment by bluefuton** [comment]
🚢 in r227912-wpcom.

**Pull request merged**
