### PR TITLE
storybook: Try storybook-addon-turbo-build

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

The main change here (according to its documentation) is that it will
use esbuild instead of terser for minification. Since we don't need
things like preserving of translator comments in the storybook, that's
probably ok. Let's see how it performs.

#### Jetpack product discussion

PT: p9dueE-4dJ-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Is the build faster? (since it touches pnpm-lock, it'll build everything so we can probably tell)
* Check the built storybook artifact. Does it still work?

### CODE REVIEW

**Comment by anomiex** [comment]
Storybook build itself seemed decently sped up. Overall build time didn't really change though, if anything it got slightly slower.

It looks like the stuff building in parallel with Storybook was slowed down, probably because esbuild incorporates more parallelism in its own operation. Those slowdowns delayed the start of the Jetpack build, so even though Jetpack sped up a little (due to fewer competing builds) it wasn't enough to overcome the later start.

**Comment by anomiex** [comment]
The lower level of optimization seems worthwhile. Let's go with that.

**Review by brbrr — APPROVED** [review]
It is faster!

**Comment by anomiex** [comment]
r239953-wpcom

**Pull request merged**
