### PR TITLE
VideoPress package: Avoid conflict with old versions of Jetpack plugin

### LINKED ISSUE #25686: VideoPress: fix Fatal error when VideoPress and Jetpack plugins are both active
* Active both Jetpack and VideoPress plugins
* Connect Jetpack

Image

```
Fatal error: Cannot redeclare videopress_is_valid_guid() (previously declared in /srv/users/user9338b8e0/apps/user9338b8e0/public/wp-content/plugins/jetpack-videopress-dev/jetpack_vendor/automattic/jetpack-videopress/src/utility-functions.php:24) in /srv/users/user9338b8e0/apps/user9338b8e0/public/wp-content/plugins/jetpack/modules/videopress/utility-functions.php on line 24
```

Image

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #25686

#### Changes proposed in this Pull Request:

* Avoid conflict between the package ad old versions of Jetpack plugin

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

NA

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Launch a new JN site
* Use VideoPress plugin on this branch
* set Jetpack plugin on latests stable (11.2)
* test the usage of VideoPress
* set Jetpack plugin to any version after 11.2-a.7 and confirm it works fine
* test other versions
* Note: version 11.2-a.5 is known to be broken

### CODE REVIEW

**Comment by retrofox** [comment]
Since the errors is about redeclaration a function...

```
Fatal error: Cannot redeclare videopress_is_valid_guid()
(previously declared in /srv/users/userc438270a/apps/userc438270a/public/wp-content/plugins/jetpack-videopress-dev/jetpack_vendor/automattic/jetpack-videopress/src/utility-functions.php:24)
in /srv/users/userc438270a/apps/userc438270a/public/wp-content/plugins/jetpack/modules/videopress/utility-functions.php on line 24
```

... isn't safer to check whether the function is already defined?

**Review by retrofox — DISMISSED** [review]
LGTM 🚀 

- [x] Launch a new JN site
- [x] Use VideoPress plugin on bleeding edge
image

- [x] set Jetpack plugin on latests stable (11.2)
image

- [x] test the usage of VideoPress
image

- [x] set Jetpack plugin to any version after 11.2-a.7 and confirm it works fine
image

- [x] test other versions
- [x] Note: version 11.2-a.5 is known to be broken
image

**Review by retrofox — COMMENTED** [review]
Let me check again..

**Comment by leogermani** [comment]
> ... isn't safer to check whether the function is already defined?

the problem is that the package initializaton runs before the plugin inlcudes the file. So even if I check if functions exists, it wont exist and it will include

the problem is that the package initializaton runs before the plugin inlcudes the file. So even if I check if functions exists, it wont exist and it will include

I could delay the include in the package, to make sure that Jetpack initialization is over, but I think that's less secure, because we dont know exactly when the functions are needed... also, it is included from more than one place in the plugin. This is why version a.5 is broken. See your fix -> https://github.com/Automattic/jetpack/pull/25660

And we can't go back in time and add the check in previous versions of the plugin...

**Review by retrofox — CHANGES_REQUESTED** [review]
Maybe I'm missing something?

image

* Create JN site
* Connect site with Jetpack
* Go to Jetpack beta plugins
* Activate VideoPress standalone plugin / bleeding-edge version

**Comment by leogermani** [comment]
> Maybe I'm missing something?

You need to put videopress plugin on this branch

**Review by retrofox — APPROVED** [review]
Confirmed it works as expected using the proper branch for the VideoPress plugin.

image

Sorry about the delay. LGTM! 🚀

**Pull request merged**
