### PR TITLE
Jetpack: VPBlock - limit the attempts to get the video preview

### PR DESCRIPTION
**Pull request by retrofox**
This PR handles the attempts to get the video preview. Although it shouldn't happen since getting the preview is always expected beyond it could take time and a few attempts, we need to ensure to do not request the preview forever.
This PR limits the attempts to 10. Statistically, the attempts are never more than 3 in my personal experience.

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack: VPBlock - limit the attempts to get the video preview

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Go to the block editor
* Add a new VideoPress block
* Set the video by using an invalid URL (BTW, this is a known issue that will be tackled in another PR). For instance:

```
https://video.wordpress.com/v/retrofox
```
* Confirm it isn't possible to get the preview
* Confirm it gets the attempts limit (10)
* Confirm you see a basic error message.

Screen Shot 2022-07-06 at 1 23 14 PM

image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202514379845507

### CODE REVIEW

**Review by leogermani — DISMISSED** [review]
Works well,

as a minor suggestion, we could have the maximum number of attempts as a constant and use it in all the places in the code

**Comment by retrofox** [comment]
> Works well,
> 
> as a minor suggestion, we could have the maximum number of attempts as a constant and use it in all the places in the code

yes...

**Comment by retrofox** [comment]
> Works well,
> 
> as a minor suggestion, we could have the maximum number of attempts as a constant and use it in all the places in the code

addressed https://github.com/Automattic/jetpack/pull/24897/commits/c22f13a82d20cfbf83b9db9776392c8a3908f544

**Review by leogermani — DISMISSED** [review]

**Review by oskosk — APPROVED** [review]

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D83432-code, and deploy it.

r248632-wpcom

**Pull request merged**
