### PR TITLE
Update illustration colors to use Color Studio v2

### PR DESCRIPTION
**Pull request by crunnells**
Part of our Hack week project to update the illustrations to use the new [Color Studio v2](https://color-studio.blog/) that dropped last week. 

#### Changes proposed in this Pull Request:

* Updates existing illustrations with new colors.

**Old Illustrations (Free Plan)**
L8xVpZA8Rg-3000x3000

**New Illustrations (Free Plan)**
Screenshot_2019-07-29 Jetpack ‹ Hollow Macaroni — WordPress

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Not a new feature, just updating assets. More info here: p6TEKc-2SC-p2

#### Testing instructions:
* Activate and Connect Jetpack
* Go to My Plan
* Note that the illustrations have changed from drab to fab (tm)

#### Proposed changelog entry for your changes:

* Update illustration colors

### CODE REVIEW

**Comment by olesyabrk** [comment]
so awesome to see it come together! --away with the grays --drab to fab ✨

**Comment by crunnells** [comment]
@jeherve Any chance we can squeeze this one into the next release?

**Comment by jeherve** [comment]
@crunnells Sorry, I missed your comment, and I just shipped the Beta. It's going to have to be in the next release now, if that's okay with you.

**Review by jeherve — DISMISSED** [review]
I like it. It looks better than before! I think this should be good to merge.

Worth noting that this also impacts other screens that rely on the SVG, like the main connection screen.

Also worth noting that we do have a few layout issues in IE11 right now, but they were not introduced with this PR:

screenshot 2019-07-31 at 18 26 39
screenshot 2019-07-31 at 18 25 09

**Comment by jeherve** [comment]
I logged the IE11 layout issues in #13161

**Comment by crunnells** [comment]
@jeherve Thanks for the review and IE11 reports! I'll look into those.

**Review by mdawaffe — APPROVED** [review]
Boom - purty!

**Pull request merged**
