### PR TITLE
Add query_vars to visibility widget option

### PR DESCRIPTION
**Pull request by zinigor**
Add additional option input to the visibility widget. Use case: I'd like this promo text widget to be hidden if the lang query_var is set. (Replay of #1363 by @drrobotnik )

### CODE REVIEW

**Comment by zinigor** [comment]
Master issue: #5781

**Comment by zinigor** [comment]
I have added some changes, namely:
* added docblocks for filters and actions;
* brought back a condition that allowed skipping additional checks if one of them was true;
* namespaced filter and action names, renamed some;
* changed the logic that hid the minor rule to avoid dangling strings.

Here's a gist to help you test filters and actions:
'''
// Widget visibility testing

add_action( 'jetpack_widget_visibility_additional_fields', function( $rule ) {
?>
	I can do whatever I want here.
<?php

} );

add_action( 'jetpack_widget_visibility_condition_major', function( $rule ) {
?>
	<option value="foo">Foo</option>
<?php
} );

add_filter( 'jetpack_widget_visibility_minor_visible', function( $rule ) {
	return false;
} );

add_filter( 'jetpack_widget_visibility_conditions_defaults', function( $rule ) {
	error_log( print_r( $rule, true ) );
	return $rule;
} );

add_filter( 'jetpack_widget_visibility_condition_result', function( $rule ) {

	// All widgets visible!
	return true;
} );
```

**Review by briancolinger — COMMENTED** [review]
This works on my test site.
Using the gist provided, I can see the "I can do whatever I want here." message show up when I click the Visibility button on a widget.

**Review by samhotchkiss — DISMISSED** [review]

**Comment by zinigor** [comment]
I have rebased this one, but I'm afraid we have more work to do here. After the refactoring of how rules are displayed in the admin side, this requires additional fixes to make custom rules usable.

**Comment by paulschreiber** [comment]
@zinigor Any plans to finish this? This has been around in one form or another since 2014. #434 #3779

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Pull request closed without merging**
