### PR TITLE
Update/identify broken facebook accounts

### PR DESCRIPTION
**Pull request by enejb**
Fixes Facebook removing the ability to publicize to personal profiles. 

#### Changes proposed in this Pull Request:
* Remve the ability for the user to select the facebook's personal profile account. To publicize to.
* Show a notice so that the user know to disconnect the connection and set up a new one. 

UI When showing the Personal Facebook Connection on the settings screen.
screen shot 2018-07-20 at 3 43 47 pm

UI when showing the Page Facebook Connection on the settings screen
screen shot 2018-07-19 at 3 07 58 pm

UI on the new post screen showing the Broken personal Facebook connection. 
screen shot 2018-07-20 at 1 18 49 pm
screen shot 2018-07-20 at 3 42 43 pm

UI on the new post screen showing the Page Facebook connection. 

screen shot 2018-07-19 at 3 46 53 pm
screen shot 2018-07-19 at 3 46 49 pm

#### Testing instructions:

Go to the WP-admin > Settings > Sharing
Does the UI make sense. 
1. Connect your personal Facebook account. 
Notice all the error messages. 
Notice that when you publish that the post doesn't go to facebook anymore.

2. Disconnect your personal account and connect a page account. 
Notice that everything works as expected/ as before.

### CODE REVIEW

**Comment by benhuberman** [comment]
@enejb  Re: the wording here, I think we can make a few small changes for clarity and consistent naming.

UI When showing the Personal Facebook Connection on the settings screen:
> Facebook Profiles no longer support automatic sharing via Publicize.

Or, if we want to be a bit more explanatory (which I think would definitely be better in this case):
> Due to changes on Facebook's platform, you can no longer share posts to your connected Facebook Profile.

Also: it might be worth adding a link to the related support page?

UI on the new post screen showing the Broken personal Facebook connection:
> Facebook no longer supports Publicize connections to Facebook Profiles. 

And if we wanted to give an alternative in this context, before the CTA button (which might encourage some people to actually update sharing settings?):
> Facebook no longer supports Publicize connections to Facebook Profiles, but you can still connect Facebook Pages.

**Comment by enejb** [comment]
@benhuberman It is a lot more effort to show the different messages in the 2 different contexts. 

Do you think it would be fine to just go with. 
> Facebook Profiles no longer support automatic sharing via Publicize.

For both messages?

**Comment by joanrho** [comment]
@enejb just tested. I think we need to give some sort of "next steps" guidance for users on this step:

screen shot 2018-07-20 at 1 52 38 pm

What @benhuberman suggests in his comment sounds like a good option. How about something like this?

>Facebook no longer supports Publicize connections to Facebook Profiles, but you can still connect Facebook Pages. Please select a Facebook Page to publish updates to.

**Comment by benhuberman** [comment]
@enejb  -- I think showing the same message in both contexts is fine, but I'll also +1 @joanrho's comment above; it would be better if we include some minimal information about what users can do next.

**Comment by enejb** [comment]
Screenshots updated. 
@benhuberman and @joanrho Does it work for you? 
@mdawaffe Any changes to the code?

**Comment by mdawaffe** [comment]
Untested, but code looks good to me :)

**Comment by zinigor** [comment]
Ported to `branch-6.3` in 8dd3f88b3.

**Pull request merged**
