### PR TITLE
Bump version to 5.6-alpha.

### PR DESCRIPTION
**Pull request by zinigor**
And run `yarn upgrade` to resolve new dependency versions.

### CODE REVIEW

**Comment by zinigor** [comment]
Thanks for rebasing, can you please remove `yarn-error.log` from the change? Thank you!

**Comment by jeherve** [comment]
oops sorry. Done.

**Comment by ebinnion** [comment]
Restarted travis tests after a failure

**Comment by zinigor** [comment]
Force pushed a rebased version, should clear up conflicts and fix Travis.

**Pull request merged**
