### PR TITLE
Admin Page: Add confirm message when changing routes, informing about unsaved options

### LINKED ISSUE #4982: Admin Page: no warnings when leaving settings without saving
When making changes to settings and you don’t click ‘Save Settings’ and move to another tab/page, there’s no “unsaved changes” warning.

nav

It might help to display a warning that if you continue to navigate away your changes will be lost to stop any confusion about what someone has done.

### PR DESCRIPTION
**Pull request by oskosk**
Fixes #4982 .

#### Changes proposed in this Pull Request:

Adds a mechanism for warning the user that some module settings have not been saved when trying to change tabs or routes.

#### Testing instructions:

1. Get to the **Site Stats** under the  **Engagement** tab 
1. update one of the options, without saving.
1. Switch to the **Security** tab
1. Expect to be prompted

### CODE REVIEW

**Comment by eliorivero** [comment]
Works fine, but the text

> There are some unsaved options in the Carousel settings

could use some tweaking, for example:

> There are unsaved options in Carousel settings that will be lost if you navigate away. Proceed?

**Comment by eliorivero** [comment]
@oskosk a bug I noticed: if you for example have Carousel dirty, and browse away anyway, if you later get Spelling and Grammar dirty, the message will still display Carousel as the dirty module.

**Comment by oskosk** [comment]
@eliorivero I think you tested on an old local copy of this branch

**Comment by eliorivero** [comment]
Ok the latest change doesn't mention the module anymore. In any case, the text should still describe what is going to happen like:
> There are unsaved options in the module settings that will be lost if you leave this tab. Proceed?

**Comment by oskosk** [comment]
Updated message text to `There are unsaved settings in this tab that will be lost if you leave it. Proceed?`. Thanks!

**Pull request merged**
