### PR TITLE
Boost: Update image guide handling of missing images

### PR DESCRIPTION
**Pull request by dilirity**
## Proposed changes:

* Update image guide package to throw an error when an image is missing;
* Update Boost to work with package update.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup Boost with Image Size Analysis;
* Request a report;
* There should be no problems with the process.

### CODE REVIEW

**Comment by thingalon** [comment]
Needs a fresh merge from trunk; I'm getting: 
```
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
```

Which I believe was fixed in @donnchawp's branch here: https://github.com/Automattic/jetpack/pull/31504

**Comment by dilirity** [comment]
This needs an update. The changes introduced with #31504, skip missing images before they can be reported.

**Comment by dilirity** [comment]
Moved tiny images check outside `getMeasurableImages`. This will allow us to decide which images we want to work with at a later point.

**Review by thingalon — APPROVED** [review]
✅ Nice, seems to work, and I'm happy with how we're handling this. Broken images are not yet shown appropriately in the UI but I see them in the DB and understand that the UI update will be a separate PR.

**Pull request merged**
