### PR TITLE
Contact Form: Escape `@` in email addresses to avoid transport errors

### PR DESCRIPTION
**Pull request by iandunn**
`@` symbols in email addresses should be escaped, according to RFC 5322. Most MTAs won't complain if it's not, but some will refuse to send the message. Most reports have been from sites hosted on SiteGround, but a few others may be affected.

This is a work in progress. I think it fixes 90% of the issue, but it needs some cleaning up and testing.

See #7276

#### Testing instructions:

* Follow the reproduction steps in #7276 to see the bug happen
* Apply the patch and go through the steps again, it should be fixed :)

#### Proposed changelog entry for your changes:

* Fix bug that caused contact form submissions to not be sent on a handful of hosts.

### CODE REVIEW

**Comment by dereksmart** [comment]
@iandunn our code freeze is on Tuesday.  Do you think you'll have time to take this to 100% by then?

**Comment by iandunn** [comment]
@dereksmart: I'm taking a long vacation the next few weeks to avoid burnout, and am swamped this week trying to get things wrapped up before I leave, so I don't think I'll be able to finish it.

If it's not a high priority for this release, though, I can finish it when I get back so that it's ready for the next one.

**Comment by dereksmart** [comment]
@iandunn no worries, enjoy your AFK!

**Comment by splitinfinities** [comment]
Hey all, wanted to share how we at Flywheel have solved the problem for now. This is a plugin we activate on a case-by-case basis to mitigate the issue. Hopefully this can provide some direction on this PR. 

The core issue are with headers under the format `"William M. Riley" <example@gmail.com>`. the content sent with quotes is escaped - the RFC calls this segment the `display-name`. We target that name block, then remove those quotes, basically. We went down a rabbit hole, because there are 3 or 4 partially superseding RFC's that contradict each other. Reference #7350 for more technical details on that part. But, this is how we solved it. To come to the solution, I researched how other plugins (Caldera forms, ninja forms, contact form 7, ACF, 5 or 6 others) were formatting the email, and they didn't have the quotes. 

Here's the code we're using on a case-by-case basis like I mentioned above: 
```php
<?php
/*
 * Plugin Name: Mail Header Compatibility by Flywheel
 * Plugin UI: https://getFlywheel.com
 * Description: Allows emails with malformed headers to be sent.
 * Author: Flywheel
 * Version: 0.1.0
 * Author URI: https://getFlywheel.com
 */

if ( defined( 'FW_MAIL_HEADER_COMPATIBILITY' ) && FW_MAIL_HEADER_COMPATIBILITY ) {
	include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

	if ( is_plugin_active('jetpack/jetpack.php') ) {
		add_filter( 'wp_mail', 'flywheel_demangle_mail_headers' );

		/**
		 * Reformats mail headers to remove quoted strings.
		 *
		 * @param array $args A compacted array of wp_mail() arguments, including the "to" email,
		 *                    subject, message, headers, and attachments values.
		 * @return array The sanitized arguments for wp_mail().
		 */
		function flywheel_demangle_mail_headers( $args ) {
			$headers = explode( "\n", trim( $args['headers'] ) );

			foreach ( $headers as $index => $header_row ) {
				list( $header, $value ) = explode( ':', $header_row, 2 );

				if ( $header == 'From' || $header == 'Reply-To' ) {
					$value = str_replace( '"', '', $value );
				}

				$headers[$index] = implode( ':', array( $header, $value ) );
			}

			$args['headers'] = implode( "\n", $headers );

			if ( $args['to'] ) {
				foreach ( $args['to'] as $index => $to ) {
					$args['to'][$index] = str_replace( '"', '', $to );
				}
			}

			return $args;
		}
	}
}
```

Let me know how I can help, really happy to a rubber duck or write any code you'd need.

**Comment by apmarshall** [comment]
Checking in for an update on this. I know this is impacting my clients using Siteground, and it looks like from the support forums that it's impacting plenty of others. Have been waiting to move on my own cause I assumed this would go through soon, but should we be implementing our own alternative fixes instead? Thanks for all your work!

**Comment by dereksmart** [comment]
We're going with another approach to fix this that doesn't include escaping at all #7733

**Pull request closed without merging**
