### PR TITLE
Search: allow hiding content

### PR DESCRIPTION
**Pull request by trakos**
## Proposed changes:

This change allows customizing which fields are highlighted in search results. Some users don't want to show parts of the content that match the query by default, especially if some of the content is behind a paywall/membership.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p1724318175328299-slack-C02ME06LF

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

Add a snippet limiting highlighted fields:

```
function jp_filter_query( $options ) {
    $options['highlightFields'] = array( 'title' );
    return $options;
}
add_filter( 'jetpack_instant_search_options', 'jp_filter_query' );
```

search results should no longer show content, only title. It should be tested with all three search result formats (minimal, standard, product).

You can also test this with an excerpt field, but only if you apply D159359-code at the same time.

### CODE REVIEW

**Review by kangzj — DISMISSED** [review]
Works well and looks good! 🚀

**Review by kangzj — DISMISSED** [review]

**Review by gibrown — DISMISSED** [review]
This looks great. Also took a look at the wpcom change and that makes sense as well.

**Comment by trakos** [comment]
Thank you for the reviews!

I had to rebase due to the changes in Jetpack repo - pdWQjU-Qj-p2. I've enabled the auto-merge now.

**Review by kangzj — APPROVED** [review]
🚀

**Pull request merged**
