### PR TITLE
tools: Update tools/check-development-environment.sh

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

I got tired of some unclarities in the existing script.

* Have it output help directly instead of linking to
  docs/development-environment-cli-support.md
* Link to docs/development-environment.md where detailed instructions
  are available.
* Indicate which checks are optional.
* Add some extra checks for standard shell commands.
* More and better version checking.
* Drop the checks for "repo is up to date", that's outside the scope of
  getting an environment set up.
* Drop the checks that amount to "you ran `jetpack docker up`", those
  are outside the scope too.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Try it out!
* Run it in an environment lacking basic tools, or with outdated versions of stuff. Does it give appropriate messages?
* Run it on a Mac using /bin/bash. If it errors out, let me know what happens so I can make it get as far as saying "You need to update bash" then exit gracefully.

### CODE REVIEW

**Comment by kraftbj** [comment]
It tells me I don't have `nvm` available when I do.
2021-07-19 at 10 25 AM

`/bin/bash` on macOS worked fine:
2021-07-19 at 10 25 AM

Trying it on a non-development system worked well. It exited nicely early when `jq` was not found, but after installing via `apt-get` on Ubuntu 18, it didn't handle that nicely
```
Shell tools
===========

* Usable version of bash                   ... ok (version 4.4.20(1)-release)
* Standard tools are available             ... yes
* If sed accepts -E                        ... yes
* Usable version of jq                     ... unknown

  jq version from /usr/bin/jq could not be determined. Output was:

    jq-1.5-1-a5b5cbe
```

**Comment by anomiex** [comment]
> It tells me I don't have nvm available when I do.

Weird. What do you get as output for the following:

* `which nvm`
* `command -v nvm`
* `bash -c 'echo $BASH_VERSION; which nvm'`
* `bash -c 'echo $BASH_VERSION; command -v nvm'`

> `/bin/bash` on macOS worked fine:

The part I'm most interested in is what it did after that screenshot. Did the rest of the script run like usual, or did it die on some error about syntax Bash 3 doesn't support? If the latter, I'll want to add an early exit like for the missing jq.

> It exited nicely early when jq was not found, but after installing via apt-get on Ubuntu 18, it didn't handle that nicely

Ah, weird version format. Fix incoming.

**Comment by kraftbj** [comment]
> The part I'm most interested in is what it did after that screenshot. Did the rest of the script run like usual, or did it die on some error about syntax Bash 3 doesn't support? If the latter, I'll want to add an early exit like for the missing jq.

Ran like usual, no errors.

**Comment by kraftbj** [comment]
2021-07-19 at 3 08 PM

`which nvm` outputs what looks to be bash code of nvm or something like it?
2021-07-19 at 3 09 PM

**Comment by anomiex** [comment]
... Apparently nvm doesn't install an actual binary, instead it defines itself as a function in bash via `~/.bashrc`. I guess I can copy what the old version of the script did to try to detect it.

**Comment by kraftbj** [comment]
Still fails to realize `nvm` is there. For me, it's in `/usr/local/opt/nvm/nvm.sh` and is called from there from `.zshrc` from being installed via `brew`.

Since this is running in bash, for me, it isn't picking up the `.zshrc` location, so running `nvm` within the script isn't working either. Hmm.

**Comment by anomiex** [comment]
Did the original script detect nvm for you? I can't see how it would have.

**Comment by kraftbj** [comment]
It also fails.

I think it's fine to merge this and worry about `nvm` in a follow-up.

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
