### PR TITLE
Use class selector for the admin menu icon

### PR DESCRIPTION
**Pull request by swissspidy**
Hi there,

I'm currently working on [Admin Menu Manager](https://github.com/wearerequired/admin-menu-manager) where the user can modify the admin menu using drag & drop. He can also move sub items to the top level and vice-versa. For the former I copy the parent item's classes so the new item gets the same icon.

For example, I can move "Settings" from the Jetpack menu to the top level, and it also gets the `toplevel_page_jetpack` class that _should_ get the same styling. However, this doesn't work because of the ID selector. This small change would fix that without affecting the menu item's appearance or anything else.

Note: Other Jetpack modules, like Contact Form, work like a charm, because they also use class selectors.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
@swissspidy -- looks like changes in master have made this unmerge-able-- would you mind rebasing?

**Comment by swissspidy** [comment]
@samhotchkiss Just did some command line hackery and hope it's working now... Can you have a look again? Thanks!

**Comment by samhotchkiss** [comment]
Looks good to me-- @jeffgolenski, can you give this a once over?

**Comment by jeffgolenski** [comment]
@samhotchkiss It's looking good to me. simple style change.

**Comment by rase-** [comment]
LGTM as well

**Comment by jeffgolenski** [comment]
After reviewing the merge, I'm going to have to get into the files to mod some things. 

Within the Jetpack admin menu, this occurs: https://cloudup.com/cKZtJrql0XK

cc @samhotchkiss @rase- 

@swissspidy I'll make sure to alter it so we're not associating the styles with IDs, but rather a specific class. I'll let you know when I finish that.

**Comment by samhotchkiss** [comment]
JETPACK ALL THE THINGS.

@jeffgolenski, just go ahead and submit a new PR when you're finished

**Comment by jeffgolenski** [comment]
Issue fixed in: https://github.com/Automattic/jetpack/pull/1972

**Pull request merged**
