### PR TITLE
JSON API: Add clear transient endpoint

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request:

* Part of a fix for https://github.com/Automattic/wp-calypso/issues/50312
* Adds an endpoint to clear a transient on a Jetpack site, so that we can clear `jetpack_connected_user_data_$user_id` when a user makes an account change (e.g. to color scheme or language) on WP.com

#### Jetpack product discussion

p1618495635435200/1618329458.321800-slack-CKZHG0QCR
p3hLNG-18q-p2

#### Does this pull request change what data or activity we track or use?

Nope.

#### Testing instructions:

* Apply D60445-code and sandbox the API.
* Checkout this branch on a Jetpack-connected site.
* Check that you have a `jetpack_connected_user_data_1` transient on your Jetpack site, e.g. by running `wp transient get jetpack_connected_user_data_1` in wp-cli. You should see an array.
* [Ping the new endpoint](https://developer.wordpress.com/docs/api/console/) with `name: "jetpack_connected_user_data_1"` in the JSON body of the request.
Click the correct path in the dropdown:
Screen Shot 2021-04-20 at 6 13 58 PM
Fill in the transient name:
Screen Shot 2021-04-20 at 6 14 24 PM

* Check that the transient has been deleted on the Jetpack site: `Transient with key "jetpack_connected_user_data_1" is not set.`

### CODE REVIEW

**Comment by retrofox** [comment]
There is an inconsistency between this PR and the D60445-code. Going to add a comment there.

**Comment by retrofox** [comment]
> There is an inconsistency between this PR and the D60445-code. Going to add a comment there.

After updating the patch, I see the proper response.

image

**Comment by jeherve** [comment]
Related discussion: p1619007262095000-slack-CKZHG0QCR

**Comment by jeherve** [comment]
Marking this as on hold, pending decision in p3hLNG-18q-p2

**Comment by allilevine** [comment]
Closing in favor of https://github.com/Automattic/jetpack/pull/19632

**Pull request closed without merging**
