### PR TITLE
Retool twitter:image for overlarge images.

### PR DESCRIPTION
**Pull request by georgestephanis**
Also worth mentioning, I'm dropped some of the escaping on these variables on the code I'd added, as it's escaped later when output.  Prior history on this (thanks @kraftbj for digging up the citation) here: https://github.com/Automattic/jetpack/pull/2516

This PR is to address cases where there's large images -- over 4100px wide or tall -- that are currently just skipped instead of resized.  Let's use and reward sites that provide high quality assets, not just skip them!

#### Changes proposed in this Pull Request:

* Add code to gracefully handle, instead of skip large images when generating summary tags for twitter cards.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Have a post with an 8,000 pixel wide image.
* See if it populates into the Twitter cards.

### CODE REVIEW

**Comment by samiff** [comment]
Hey @georgestephanis 👋 

Could you add a changelog entry for this and then add the `[Status] Needs Review` label if it's ready for a look, thanks!

---

Please add missing changelog entries for the following projects: `projects/plugins/jetpack`

Use [the Jetpack CLI tool](https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#first-time) to generate changelog entries by running the following command: `jetpack changelog add`.  
Guidelines: [/docs/writing-a-good-changelog-entry.md](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md)

**Comment by georgestephanis** [comment]
I'm off on my weekend right now.  Will try to remember to take a look first thing on Monday.

**Review by jeherve — COMMENTED** [review]
I played with this branch a bit, and thought to simplify the logic a bit thanks to `Jetpack_PostImages::fit_image_url)`:

```diff
diff --git a/projects/plugins/jetpack/class.jetpack-post-images.php b/projects/plugins/jetpack/class.jetpack-post-images.php
index 7b9ecc3d10..3fd6fe67af 100644
--- a/projects/plugins/jetpack/class.jetpack-post-images.php
+++ b/projects/plugins/jetpack/class.jetpack-post-images.php
@@ -757,6 +757,18 @@ class Jetpack_PostImages {
 			return jetpack_photon_url( $src, array( 'resize' => "$width,$height" ) );
 		}
 
+		/*
+		 * If we cannot dynamically resize,
+		 * see if WordPress has any smaller fallback image sizes we can use.
+		 */
+		$image_id = attachment_url_to_postid( $src );
+		if ( $image_id ) {
+			$large_image = wp_get_attachment_image_url( $image_id, 'large' );
+			if ( false !== $large_image ) {
+				return $large_image;
+			}
+		}
+
 		// Arg... no way to resize image using WordPress.com infrastructure!
 		return $src;
 	}
diff --git a/projects/plugins/jetpack/class.jetpack-twitter-cards.php b/projects/plugins/jetpack/class.jetpack-twitter-cards.php
index d8f1f8fda6..1b4ba6fab0 100644
--- a/projects/plugins/jetpack/class.jetpack-twitter-cards.php
+++ b/projects/plugins/jetpack/class.jetpack-twitter-cards.php
@@ -104,11 +104,14 @@ class Jetpack_Twitter_Cards {
 					'height' => 144,
 				)
 			);
-			if ( ! empty( $post_image ) && is_array( $post_image ) ) {
+			if (
+				! empty( $post_image )
+				&& is_array( $post_image )
+				&& isset( $post_image['src_width'], $post_image['src_height'] )
+			) {
 				// 4096 is the maximum size for an image per https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary .
 				if (
-					isset( $post_image['src_width'], $post_image['src_height'] )
-					&& (int) $post_image['src_width'] <= 4096
+					(int) $post_image['src_width'] <= 4096
 					&& (int) $post_image['src_height'] <= 4096
 				) {
 					// 300x157 is the minimum size for a summary_large_image per https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image .
@@ -118,24 +121,14 @@ class Jetpack_Twitter_Cards {
 					} else {
 						$og_tags['twitter:image'] = esc_url( add_query_arg( 'w', 144, $post_image['src'] ) );
 					}
-				} elseif ( isset( $post_image['src_width'], $post_image['src_height'] ) ) {
+				} else {
 					// Elseif we have an image, but it's TOO BIG (larger than 4096px on either dimension).
-					if ( Jetpack::is_module_active( 'photon' ) ) {
-						$card_type                = 'summary_large_image';
-						$og_tags['twitter:image'] = jetpack_photon_url(
-							$post_image['src'],
-							array(
-								'fit' => '4096,4096',
-							)
-						);
-					} else {
-						// See if WordPress has any smaller fallback image sizes we can use?
-						$image_id = attachment_url_to_postid( $post_image['src'] );
-						if ( $image_id ) {
-							$card_type                = 'summary_large_image';
-							$og_tags['twitter:image'] = wp_get_attachment_image_url( $image_id, 'large' );
-						}
-					}
+					$card_type                = 'summary_large_image';
+					$og_tags['twitter:image'] = Jetpack_PostImages::fit_image_url(
+						$post_image['src'],
+						4096,
+						4096
+					);
 				}
 			}
 
```

However, when testing I am regularly running into the same problem: when dealing with such large images, often large in dimensions and large in size, Photon fails to download such an image. At this point, even though the Twitter Card does refer to the big image (passed through Photon), Twitter will not see it because Photon isn't able to fetch and resize it.

I was thinking that we may want to fetch the `full` image instead, since for very large images above a certain threshold (2560px by default), a new `full`, scaled down image is generated from the original image and the original image is then stored as an `original_image` sized image. Would that be acceptable? Sites willing to risk fetching such large images could then disable the threshold to get the "real" full images, with the `big_image_size_threshold` filter.

@georgestephanis Would that be an acceptable work-around?

**Comment by georgestephanis** [comment]
@jeherve That sounds like a reasonable workaround to me.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Pull request closed without merging**
