### PR TITLE
tools/version-packages.sh: Check for missed upgrades

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

If a package isn't upgraded in a run of tools/version-packages.sh, then
something is wrong (e.g. p9dueE-4bx-p2). So check for that and error out
if it happens.

#### Jetpack product discussion

p1641996471074300-slack-C01U2KGS2PQ

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Edit `projects/plugins/jetpack/composer.json` to do minor or major bumps of some package versions, then run `tools/version-packages.sh projects/plugins/jetpack/`. It should print relevant errors and exit with a non-zero status.
* If you don't bump any versions, it should complete successfully.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
> Edit projects/plugins/jetpack/composer.json to do minor or major bumps of some package versions, then run tools/version-packages.sh projects/plugins/jetpack/. It should print relevant errors and exit with a non-zero status.

I'm not sure if I'm missing something here. I updated `automattic/jetpack-blocks` (currently at `1.4.x-dev`) to a previous minor (`1.3.0`), and it seems it let me do that with no errors:

image

**Comment by jeherve** [comment]
Ah, right. But wouldn't we want to avoid accidental downgrades as well?

**Comment by anomiex** [comment]
How would that accidentally happen in the first place?

**Review by samiff — APPROVED** [review]
This tests like it should prevent the issue mentioned internally [here](p9dueE-4bx-p2#comment-7087) (i.e. release branch cut/processed before package available on Packagist).

- Say for example that during generating the changelog for a Jetpack release, a new version of `automattic/jetpack-search` is released `0.6.0`. Simulate this by changing Jetpack's composer.json to `0.6.x-dev` for the search package.
- Then when cutting the release branch, package versions would be fetched, simulated by running `tools/version-packages.sh projects/plugins/jetpack/` which  for me produces the error:

```
automattic/jetpack-search was not upgraded (^0.5.0 <= 0.6.x-dev)
Error running script! Exited with status code 1.
```

**Pull request merged**
