### PR TITLE
Update size & colors indeterminate progress bar

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
The PR is a follow up for #26370, and adjusts the color and size of stripes per design. 
- Changes light color to `#F6F7F7` and dark color to `#EDEDEE`
- Adjusts the length of the stripes to `68px` which is `24px * sqrt(2) * 2` the double of longest side of isosceles right triangle. 

~~The colors used in #26370 are from the properties in sidebar of the objects in Figma, which doesn't match the real colors. Any idea? @madebynoam @ederrengifo Thanks.~~

Colors in Figma for future reference:

> in Figma, the top-most element can in some instances dictate the color its children should use and this is one of those cases since there’s an union (imagine merging a bunch of different shapes into one)
that’s why child elements can have a color that doesn’t correspond to the actual color, which is coming from the union element that “groups” them together @keoshi 

image

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Run storybook `cd projects/js-packages/storybook && npm run storybook:dev`
* Navigate to `http://localhost:50240/?path=/story/js-packages-components-indeterminate-progress-bar--default`
* Ensure it looks okay

### CODE REVIEW

**Review by dognose24 — DISMISSED** [review]
LGTM! 👍🏼  However, the `linear-gradient` stop positions that apply `33%` and `71%` would have more equal dark and light areas. But it is okay and would not be a block. 😄 
bar2

**Comment by kangzj** [comment]
@dognose24 Thanks for the feed and your attention to details. addressed in 6b6c87f. Thanks!

**Review by dognose24 — DISMISSED** [review]
LGTM! 👍🏼 🚀

**Review by jsnmoon — DISMISSED** [review]

**Review by jsnmoon — APPROVED** [review]

**Comment by kangzj** [comment]
`r253323-wpcom`

**Pull request merged**
