### PR TITLE
Mailchimp Block: UI Review Updates

### PR DESCRIPTION
**Pull request by jeffersonrabb**
#### Changes proposed in this Pull Request:

Along with https://github.com/Automattic/wp-calypso/pull/30685 this PR contains a series of UI and design improvements that were listed in https://github.com/Automattic/wp-calypso/issues/30667. For a full list of changes see: https://github.com/Automattic/wp-calypso/pull/30685

#### Testing instructions:

Complete testing instructions in https://github.com/Automattic/wp-calypso/pull/30685

### CODE REVIEW

**Comment by jeherve** [comment]
This now needs a rebase, since we've reorganized how blocks are loaded in #11312.

**Comment by jeffersonrabb** [comment]
> This now needs a rebase

Done. I'm really going to miss conflict resolution in `modules/blocks.php`

**Review by jeherve — CHANGES_REQUESTED** [review]
This looks good. I have 2 remarks about things that could be improved I think:

-------

When I update the email placeholder, the value in the inspector controls is not updated:

image

The value that seems to matter in the end is the one in the inspector controls.

-----

The subscribe button does not support multi-line text. I think we should implement this, like we did for the Contact Form and the subscription form in #11223 

image

----

**Comment by jeffersonrabb** [comment]
> When I update the email placeholder, the value in the inspector controls is not updated:

@thomasguillot what do you think of this? The email input is really just a placeholder to show what the block will look like, but it sounds like @jeherve assumed (quite reasonably) that it was the UI for changing the placeholder. How do you think this should be addressed?

**Comment by jeffersonrabb** [comment]
> The subscribe button does not support multi-line text. I think we should implement this, like we did for the Contact Form and the subscription form in #11223

This is done in https://github.com/Automattic/jetpack/pull/11317/commits/7bc5ea0c91b3e673b7ea47cac2912799fa52ea49

**Comment by thomasguillot** [comment]
> > When I update the email placeholder, the value in the inspector controls is not updated:
> 
> How do you think this should be addressed?

@jeffersonrabb could we add a `disabled` to the email input?

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb could we add a `disabled` to the email input?

Good idea, will open a new PR trying this out. This is going to be a `wp-calyspo` fix, though, so it shouldn't hold up this PR, cc: @jeherve.

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb could we add a `disabled` to the email input?

This is done and merged in https://github.com/Automattic/wp-calypso/pull/30751.

**Review by jeherve — APPROVED** [review]
This is looking good. Merge when ready!

**Pull request merged**
