### PR TITLE
Instant Search: Add focus styles.

### PR DESCRIPTION
**Pull request by a8ck3n**
#### Changes proposed in this Pull Request:

Add focus styles to the various overlay elements (excluding the search input field). Covers the Close box, the sort options, the "Load more" button, the "Clear filters" button, the checkboxes, and the hidden close button.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Visit a site with a Jetpack Search plan.
2. Open the Overlay by appending `?s=&category=uncategorized` to your site address.
3. Confirm the buttons look correct in both Light & Dark themes.
4. Toggle the light/dark themes from `/wp-admin/admin.php?page=jetpack-search-configure`.

https://user-images.githubusercontent.com/40267301/183593894-6616af60-c783-48be-976c-b4c96ccb28fe.mp4

### CODE REVIEW

**Comment by a8ck3n** [comment]
This branch is a replacement for #25414 (now closed) as the approach has changed slightly.

**Comment by dognose24** [comment]
I would recommend refactoring on-focus styles to mixin for reuse, which could also benefit the changes on this [PR](https://github.com/Automattic/jetpack/pull/25260).

`projects/packages/search/src/instant-search/lib/styles/_mixins.scss`
```
@mixin focus-outline() {
	outline: 1px auto Highlight;
	outline: 1px auto -webkit-focus-ring-color !important; /* this won't work without !important */
	outline-offset: inherit;
}

**Review by dognose24 — COMMENTED** [review]
I would recommend refactoring on-focus styles to mixin for reuse, which could also benefit the changes on this [PR](https://github.com/Automattic/jetpack/pull/25260).

`projects/packages/search/src/instant-search/lib/styles/_mixins.scss`
```
@mixin focus-outline() {
	outline: 1px auto Highlight;
	outline: 1px auto -webkit-focus-ring-color !important; /* this won't work without !important */
	outline-offset: inherit;
}

**Comment by a8ck3n** [comment]
> I would recommend refactoring on-focus styles to mixin for reuse, which could also benefit the changes on this [PR](https://github.com/Automattic/jetpack/pull/25260).

Good call. I'll have a look at this next. Thanks @dognose24!

**Review by dognose24 — APPROVED** [review]
It works as described to me! 🚀

**Pull request merged**
