### PR TITLE
Jetpack Plans: introduce new package

### PR DESCRIPTION
**Pull request by mkm119**
This PR creates a new package with functionality to fetch Plans data from WPCOM. We have restored an existing branch and rebased it. Old PR link - https://github.com/Automattic/jetpack/pull/22650

For now, it copies the classes from the Jetpack plugin. Usage in the Jetpack plugin will be replaced in subsequent PRs as this must be synced with changes in WPCOM as well.

We need this to move the work on the standalone Publicize plugin.

#### Changes proposed in this Pull Request:

* Create new Plans package

#### Jetpack product discussion

https://github.com/Automattic/jetpack/pull/23488#discussion_r829364181
p1647598368441399/1647597121.990859-slack-CBG1CP4EN

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Nothing for now, the package is not used
* Let's see if the tests pass

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
You'd want to bring in the changes from recent PRs, like #23189

**Review by pablinos — DISMISSED** [review]
There's something up with the changelog in the Jetpack plugin, and I'm not sure we're making changes to Jetpack the plugin. Do you think we should start using this in the same PR so there's not duplicate code? Git would be able to see that this is a code move too, and keep the history of the file.

**Comment by mkm119** [comment]
> There's something up with the changelog in the Jetpack plugin, and I'm not sure we're making changes to Jetpack the plugin. Do you think we should start using this in the same PR so there's not duplicate code? Git would be able to see that this is a code move too, and keep the history of the file.

Are you suggesting removing the files from Jetpack plugin folder and updating the references in this PR itself? @pablinos

**Comment by pablinos** [comment]
> Are you suggesting removing the files from Jetpack plugin folder and updating the references in this PR itself?

Yes, that's right. I suppose it depends on how much bigger it makes the PR, but I think moving the files would probably be preferrable to copying and then deleting in a separate PR. @jeherve might have some thoughts on that.

**Comment by jeherve** [comment]
I'm happy with both, personally; we can split this into 2 PRs if you'd like, but if we do it may help if you have some comments here on GitHub to highlight where you've diverted from the original files in Jetpack; that should make reviewing easier, by helping the reviewer quickly spot the changes you've made on top of copying the files.

**Comment by mkm119** [comment]
I think it might be better to split it into two PRs as we need to make reference changes across some 30 files which will increase the PR size. For this one, we should just focus on [publishing](https://github.com/Automattic/jetpack/pull/23503) the package first.

**Comment by pablinos** [comment]
> I think it might be better to split it into two PRs

Fair enough, we probably don't need the Jetpack plugin changelog then.

> you've diverted from the original files in Jetpack

Have we diverted from the original files or is this just a copy and paste? If we end up with two divergent copies of the code, then we'll want to follow up with updating references in the Jetpack plugin as quickly as possible.

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
r242972-wpcom

**Pull request merged**
