### PR TITLE
Fix content clickable when having HTML attributes with "<" in the value

### PR DESCRIPTION
**Pull request by renatho**
Related to https://github.com/Automattic/sensei-pro/issues/2574

## Proposed changes:

* It fixes the regex that splits the content to add the anchor tag in the URLs.

This regex was introduced years ago: https://github.com/Automattic/wpcomsh/pull/375/files#diff-617829ac2bd62b94e204d12538c81a709caa5671cc2471c1051b2b8e272e6b50R982. Notice that it tries to split the pieces starting with "<" and ending with ">" to handle them in chunks.

But with the previous regex, if we have "<" inside the tag (an attribute), it doesn't get the chunks properly. If I'm not missing anything, we don't need to skip the "<" from inside the tags because "<" wouldn't never be there. `<this<isnotexpected>`.

So removing that char from the excluding portion of the regex, fixes the issue.

To be more clear, see the following examples:

The current regex:

```
php > print_r( preg_split( '/(<[^<>]+>)/i', '<li data-test="<test&gt;"></li>', -1, PREG_SPLIT_DELIM_CAPTURE ) );
Array
(
    [0] => <li data-test="
    [1] => <test&gt;">
    [2] =>
    [3] => </li>
    [4] =>
)
```

The new regex:

```
php > print_r( preg_split( '/(<[^>]+>)/i', '<li data-test="<test&gt;"></li>', -1, PREG_SPLIT_DELIM_CAPTURE ) );
Array
(
    [0] =>
    [1] => <li data-test="<test&gt;">
    [2] =>
    [3] => </li>
    [4] =>
)
```

Notice that we could also have issues with the `>` inside the attributes, but this doesn't happen because of this: https://github.com/WordPress/gutenberg/pull/9963.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Install Sensei Interactive Blocks https://github.com/Automattic/sensei-pro/releases/tag/version%2Fsensei-interactive-blocks-1.4.5.
* Add the block Tasklist to a post.
* Add a task to the list.
* In the task, add an inline link.
* Check it in the frontend, and make sure it works properly (you don't see pieces of HTML rendered in the page).

Known issue: https://github.com/Automattic/sensei-pro/issues/2609

### CODE REVIEW

**Review by m1r0 — DISMISSED** [review]
Makes sense and it works as described. 👍

**Comment by renatho** [comment]
Thank you for the review, @m1r0!

Hi @westi! 👋 I know the original code was introduced a long long time ago, but could you just take a quick look to see if we're not missing anything critical that you could remember?

**Comment by azaozz** [comment]
> with the previous regex, if we have "<" inside the tag (an attribute), it doesn't get the chunks properly
> ...
> Notice that we could also have issues with the `>` inside the attributes, but this doesn't happen because

Think this restriction was (mostly) a security hardening. In theory both `<` and `>` seem allowed in [attribute values](https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#syntax-attributes), but not sure there is a good use case for using literal characters instead of entities. 

If I remember right this code is more restrictive to "err on the side of safety", and to keep that functionality simple. If the `<` and `>` characters must be supported perhaps the [WP HTML API](https://developer.wordpress.org/news/2023/09/28/the-html-api-process-your-tags-not-your-pain/) can be used to split the tags, or even to handle most of this. That may actually be faster/better than the old code.

**Comment by renatho** [comment]
@azaozz, thank you for checking!

I agree that a refactor to use the WP HTML API would probably be better here. But since it would impact all WPCOM sites, I think it would need to be a cautious work, checking possible issues, performance, and so on.

Since we don't have a critical issue related to the brackets, I would go ahead with this current solution, and I could also create an issue for a refactor to use the WP HTML API. Does it make sense to you?

**Comment by azaozz** [comment]
@renatho Sure, sounds good. I cannot remember if there was a specific (security hardening) reason to exclude HTML tags that may have extra `<` and/or `>` in attribute values, perhaps not. Also seems this fixes the current issue but may leave another edge case, for example:
`<li data-test="<test&gt;" data-test-2="some > something">[url to convert]</li>`

Would also be pretty good if some unit tests are added for this, would definitely help in similar situations in the future.

**Comment by renatho** [comment]
It seems the issue with the test coverage is something also happening in other PRs, so considering it was already reviewed and I just wrote a test, I'm going ahead and merging this.

The test was added here: https://github.com/Automattic/jetpack/pull/39931/commits/753bbe025b408772b10c2701a2ac67c72d118ea5

Thank you for your approval @m1r0! And thank you for checking and for your suggestions @azaozz!

> perhaps the [WP HTML API](https://developer.wordpress.org/news/2023/09/28/the-html-api-process-your-tags-not-your-pain/) can be used to split the tags, or even to handle most of this

Issue to refactor the whole approach created here: https://github.com/Automattic/jetpack/issues/40134

**Pull request merged**
