### PR TITLE
SSO: Add JS and CSS tooltips

### PR DESCRIPTION
**Pull request by renancarvalho**
Fixes #

## Proposed changes:

* Improve the tooltips by using JS and CSS instead of relying on HTML title attribute.

How it is now:

https://github.com/Automattic/jetpack/assets/2653810/0021e3bd-3284-4afa-ae0d-1f9312a0b5a3

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sync this branch into your atomic site
* Navigate to `/wp-admin/users.php`
* Make sure you have a pending invite to be able to see the pending invite exclamation mark
image

* Hove over the tooltip on the table header
 
image

### CODE REVIEW

**Comment by crisbusquets** [comment]
From what I see on the video, it works for me. The tooltip has enough contrast and it's easy to read.
Related to the accessibility concerns, does it have Aria labels ([source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role))? I can't see it myself (the JN site I created isn't working as expected).

**Comment by agrullon95** [comment]
The new tooltip looks great and is functioning well!

One thing I noticed when using the Mac Voiceover tool is that the `SSO Status` column values (`Connected`, `Pending Invite`, and `Send Invite`) are reading out `Jetpack SSO allows a seamless and secure experience on WordPress.com. Join millions of WordPress users who trust us to keep their accounts safe.` before it reads out the column value.


https://github.com/Automattic/jetpack/assets/10482592/b44d3af8-1b3b-46b3-bb8c-ae7ec3b68531

**Comment by escapemanuele** [comment]
Great catch @agrullon95!

**Comment by renancarvalho** [comment]
> The new tooltip looks great and is functioning well!
> 
> One thing I noticed when using the Mac Voiceover tool is that the `SSO Status` column values (`Connected`, `Pending Invite`, and `Send Invite`) are reading out `Jetpack SSO allows a seamless and secure experience on WordPress.com. Join millions of WordPress users who trust us to keep their accounts safe.` before it reads out the column value.
> 
>  CleanShot.2024-03-06.at.15.16.29.mp4

Great @agrullon95, I made a research and spans are not selectable by tab navigation by default, I have added `tabindex=0` to make them selectable and now users can understand via voice over the link and the tooltip. I think it makes sense now.


https://github.com/Automattic/jetpack/assets/2653810/196bbe0a-bbec-4bf8-9199-261e0f39c1cc

**Comment by agrullon95** [comment]
@renancarvalho - Tabbing is working much better for the actions such as `Send Invite`.

The only thing that seems slightly off is navigating with `Control + Option` and going through each row column. It usually reads out the column header name and then the column value (`Name, Anthony`, `Role, Subscriber` - something like this), but for the SSO Status column, it doesn't seem to follow this behavior. 


https://github.com/Automattic/jetpack/assets/10482592/62cf2037-17b5-4cfd-aa43-5e34542179d4



Do you know anyone who can confirm what the expected accessibility behavior should be for tables?

**Review by heavyweight — APPROVED** [review]

**Pull request merged**
