### PR TITLE
Publicize: Include Verbiage Enhancements

### LINKED ISSUE #9737: Publicize settings: verbiage enhancements
**Currently:**
screen shot 2018-06-12 at 3 04 15 pm

**Proposed:**

**Inactive:**
screen shot 2018-06-12 at 3 10 11 pm

**Active:**
screen shot 2018-06-12 at 3 10 01 pm

Title: change to "Social Media Automation" to match marketing

Description:

> Save time on marketing by connecting your favorite social media networks to your website. When you publish a post, it'll automatically be shared on all your connected accounts.

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #9737

#### Changes proposed in this Pull Request:

Include the wording enhancements mentioned in the original issue in the Publicize settings page. 

#### Testing instructions:

Compare the two at the `wp-admin/admin.php?page=jetpack#/sharing` route

**Current:**

fadsadfsfsdafdsa

**Proposed:**

sfgdfsdggssgdf

Edit: I think I need some help with the whitespaces again :sweat_smile: 

#### Proposed changelog entry for your changes:

Include verbiage enhancements for the Publicize settings

### CODE REVIEW

**Comment by jeherve** [comment]
> I think I need some help with the whitespaces again 😅

I took care of that for you. 👍

**Review by jeherve — APPROVED** [review]
This looks good on my end. 👍

**Review by keoshi — APPROVED** [review]
Looking good! Thanks again, @torres126 🙌

**Comment by torres126** [comment]
Thanks! :)

**Pull request merged**
