### PR TITLE
Add `replace` field to built plugin composer.json

### PR DESCRIPTION
**Pull request by LeoColomb**
Ref: https://github.com/Automattic/jetpack/issues/18695

### CODE REVIEW

**Comment by jeherve** [comment]
Do you think you could add some instructions to test this out? 
Thanks!

**Comment by LeoColomb** [comment]
@jeherve How so? Scripts here are tested somewhere?

**Comment by LeoColomb** [comment]
@jeherve @anomiex What do you expect to be tested? Where I can add those tests?

**Comment by jeffbyrnes** [comment]
@jeherve testing this involves making these changes to your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/LeoColomb/jetpack"
        }
    ],
    "require": {
        "automattic/jetpack": "dev-fix/composer",
    }
}
```

then running `composer update` & seeing if Jetpack >= 9.4.0 installs well & doesn’t throw the error reported in #18695.

@LeoColomb by the way, if you change “Ref: #18695” to “Fixes #18695”, it will auto-close the issue when this merges.

**Comment by jeffbyrnes** [comment]
Hmm, doesn’t _quite_ work as simply as my previous comment suggests… open to a little guidance!

**Comment by LeoColomb** [comment]
@jeffbyrnes Not sure to really follow your points.

> testing this involves making these changes to your `composer.json`:

These change seems unrelative to this PR. Are you sure you're commenting the good one?

> if you change “Ref: #18695” to “Fixes #18695”

Thanks, this is deliberate. This PR is just a workaround not a full fix.

**Comment by jeffbyrnes** [comment]
@jeherve was asking how to test this, and I was attempting to work that out myself by updating my `composer.json` to use the code in this PR. Turns out it’s not so simple, probably b/c of how Jetpack is built.

And understood about this only being a workaround! Looking forward to how this all pans out.

**Comment by jeherve** [comment]
> What do you expect to be tested? Where I can add those tests?

Is there an existing setup I could rely on with an installation of WordPress using Composer, and relying on Jetpack, where I get the Fatal error, but the Fatal disappears when Jetpack's `composer.json` is updated from using `require` to using `replace`?
I suppose it would also be interesting to see how this impacts non-Automattic packages that are required today; should those follow the same rules (it may not be necessary)?
It would also be interesting to limit this to plugins; we should not have to play with the `composer.json` file of the packages themselves, also created via the script you modified.

**Comment by anomiex** [comment]
Why are none of the GitHub Action checks running? A few can't run, but all the required ones should be able to.

> It would also be interesting to limit this to plugins; we should not have to play with the composer.json file of the packages themselves, also created via the script you modified.

If this messes with composer.json for packages, it will in fact break them.

**Comment by LeoColomb** [comment]
> It would also be interesting to limit this to plugins.

Indeed, fixed.

> Is there an existing setup I could rely on with an installation of WordPress using Composer

Well, mine, using Roots Bedrock (https://github.com/roots/bedrock).
I can create a repo with it and run an install via GitHub Actions, if that is something you're looking for.

> I suppose it would also be interesting to see how this impacts non-Automattic packages that are required today; should those follow the same rules (it may not be necessary)?

They should follow the same rules, indeed, and this is the case here. Only PHP extensions which are not actually committed to build branches are excluded.

> Why are none of the GitHub Action checks running?

Don't know why, this time all fine.

**Comment by anomiex** [comment]
> > Why are none of the GitHub Action checks running?
>
> Don't know why, this time all fine.

Looks like it may have been a GitHub issue, I later saw another PR where nothing ran.

**Comment by anomiex** [comment]
I note that the Automattic/jetpack-production composer.json generated with this PR claims that it replaces automattic/jetpack-autoloader, but it doesn't actually do so (that package is not included in the vendor directory).

**Comment by LeoColomb** [comment]
@anomiex It is, I'm afraid 😉 

https://github.com/Automattic/jetpack-production/tree/master/vendor/composer

**Comment by anomiex** [comment]
That's not the autoloader package itself, that's the files created by the autoloader package when it runs as a composer plugin.

**Comment by LeoColomb** [comment]
@anomiex Alright. Then wat do you expect? Why should this package excluded from `.replace` and installed independently on the main composer install? 
I honestly do not expect Jetpack installation via composer to alter my main autoloader behavior.

**Comment by anomiex** [comment]
I'd expect that a composer.json requiring both automattic/jetpack and automattic/jetpack-autoloader would have the autoloader plugin functioning.

But I'm starting to think the whole "replace" thing is going the wrong way, or else Jetpack itself needs something extra so a requiring composer install can autoload the included stuff correctly. If I have a composer.json that requires only automattic/jetpack-constants and do this
```
php -r 'require "vendor/autoload.php"; var_dump( Automattic\Jetpack\Constants::is_defined( "PHP_VERSION" ) );'
```
it works. But if I then add automattic/jetpack (pointed to a version with the "replace" thing) to composer, that code snippet doesn't work anymore.

**Comment by LeoColomb** [comment]
> But if I then add automattic/jetpack (pointed to a version with the "replace" thing) to composer, that code snippet doesn't work anymore.

That is 100% expected. Including `vendor` files into GitHub releases delegates (auto-)loading to Jetpack plugin load, which happens when WordPress actually require its `plugin.php`.  
`.replace` avoid duplication/conflict in autoloading, and in that case you won't have any classes from the `Automattic` namespace at the root composer install.

**Comment by LeoColomb** [comment]
> think the whole "replace" thing is going the wrong way

@anomiex By the way, I agree with that, but this is the only reasonable options if you don't want to change the way Jetpack is published.
That's also why I explained previously that I consider this PR as a workaround to answer initial issue.

Ideal way is:
1. Never commit `vendor` files into built branches/repositories (as [stated by composer manual](https://getcomposer.org/doc/01-basic-usage.md#installing-without-composer-lock))
2. Publish `vendor`-free GitHub releases
3. Deploy plugins with `vendor` to wp.org by running composer installation _just before_ deployment script. For example:
    * https://github.com/korben-info/wp-algolia/blob/4ef82aae3619d82e5182c2f933f41e5f5799ed16/.github/workflows/deploy.yml
    * https://github.com/stayallive/wp-sentry/blob/de94dcc3ab71b8c04704f61159831e151a542fca/.github/workflows/wordpress.yml#L22-L34

**Comment by anomiex** [comment]
The jetpack-production repo is intended to match what's published on wp.org. My own preference would be to remove it from packagist since it doesn't really work like a normal composer package and it's not really intended to be one.

**Comment by LeoColomb** [comment]
> My own preference would be to remove it from packagist

You mean we should re-open https://github.com/Automattic/jetpack/issues/2150? 😉

**Comment by jeffbyrnes** [comment]
Actually, I think it’d be fine to remove it from Packagist, b/c you can install it via [WPackagist](https://wpackagist.org) instead. I just swapped {{wpackagist/jetpack}} in place of {{automattic/jetpack}}, and things installed just fine!

This comes standard with Bedrock (which is why #2150 was opened), but otherwise, can be accommodated by adding this to the `repositories` stanza of your `composer.json`:

```json
{
  "type": "composer",
  "url": "https://wpackagist.org",
  "only": ["wpackagist-plugin/*", "wpackagist-theme/*"]
},
```

**Comment by LeoColomb** [comment]
@jeffbyrnes Please, no. Moving from a workaround to another is still not a good solution.
Doing this will make Jetpack moving away of PHP community standard, and I don't see any value moving from official to unofficial source, but a regression.

**Comment by anomiex** [comment]
Since when is it a standard to install WordPress plugins via composer? Jetpack isn't a library, or a development tool, or a plugin to such things.

**Comment by LeoColomb** [comment]
@anomiex Ha ha, reversing my words is not very fair!
Composer is standard to manage PHP dependencies, Jetpack can definitely be seen as a WordPress-blog dependency. The other way is not true, you are right.

And this is a possible since Composer supports installing plugins via `composer/installers` (https://github.com/composer/installers/blob/1b94b414035400a8be5c694048a0e711a86b1080/src/Composer/Installers/WordPressInstaller.php, 9yo).

**Comment by jeffbyrnes** [comment]
@LeoColomb it’s a rather common workaround, since most plugins aren’t published to Packagist. You can see I’m [installing quite a few that way](https://github.com/abundanthomesma/abundanthousingma.org/blob/d37226281a961c516768dad6ed0e9d123f33bd97/site/composer.json#L103-L118).

I’m still using Composer to do it.

**Comment by LeoColomb** [comment]
Ok, I give up.

**Comment by jeffbyrnes** [comment]
I’m sorry I didn’t think of trying out WPackagist before! Would have saved us all a lot of time & energy 😆

**Pull request closed without merging**
