### PR TITLE
Pre-Connection JITMs: Fix connection button links

### PR DESCRIPTION
**Pull request by grassfedfarmboi**
# Fixes

Currently, the "Set Up Jetpack" buttons on the Pre-Connection JITMs simply take the user to the `jetpack/#setup` page and do not pass on any query vars, making it impossible to track these connections or to properly redirect the user afterwards. This patch fixes these links such that the user is automatically connected after clicking and then redirected to the page they were on after success.

#### Changes proposed in this Pull Request:

* Adds a method `Pre_Connection_JITM::build_setup_url()` that uses `Jetpack::build_connect_url()` to create the link for the buttons.
* Adds a `from` parameter to each JITM for source tracking purposes.
* Adds a check in `jetpack-jitm.js` to look for an existing `redirect` query var instead of blindly appending a new one.

#### Jetpack product discussion

* pbtFPC-nZ-p2

#### Does this pull request change what data or activity we track or use?
Adds a `from` parameter to each Pre-Connection JITM button link for source tracking for general analytics purposes.

#### Testing instructions:
* Add the following to your `debug.php` to allow Pre-Connection JITMs to display: `add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );` 
* I also recommend disabling the JITM cache: `add_filter( 'jetpack_just_in_time_msg_cache', '__return_false', 1000 );`
* Ensure the Jetpack plugin is Activated, but not connected.
* Visit `wp-admin/upload.php` and ensure the JITM appears and that the link has proper `from` and `redirect` query vars.
* Click the button and ensure Jetpack automatically connects successfully, returning the user back to `wp-admin/upload.php` afterward.
* Deactivate the Jetpack plugin to reset the connection, and repeat this process for:
  * `wp-admin/widgets.php` and
  * `wp-admin/edit.php` (Note: This JITM will not display until there are at least 5 posts.)

#### Proposed changelog entry for your changes:
* Fixes Pre-Connection JITM links to include a "from" parameter and the correct "redirect" parameter.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
We had taken that approach when we first worked on this project, but then reverted to simpler links in #15994 to avoid skipping the in-place connect flow.

This would go back on that. Is that something we want?

**Comment by grassfedfarmboi** [comment]
I think fixing the links to have proper parameters is more important right now (and refactoring in a way to allow us to accomplish both seemed out of scope), but I am double checking with @jessefriedman to confirm.

**Comment by grassfedfarmboi** [comment]
OK, we seem to have uncovered a problem with connection source tracking in general that we'll have to address, but for now, yes, we want to go ahead and merge this version. 👍

**Comment by jeherve** [comment]
> we seem to have uncovered a problem with connection source tracking in general that we'll have to address

For reference: #17344 

Let's see if we can fix that core issue instead; it would solve the tracking issue for everyone.

**Comment by grassfedfarmboi** [comment]
That's definitely the plan, but @jessefriedman still wants this patch deployed in the meantime.

**Comment by jeherve** [comment]
Is this still needed, now that we've merged #17350?

**Comment by jeherve** [comment]
Closing this one for now. Feel free to reopen if needed.

**Pull request closed without merging**
