### PR TITLE
Donations: Update plans when currency changes

### PR DESCRIPTION
**Pull request by blackjackkent**
#### Changes proposed in this Pull Request:

* This pull request fixes behavior in the donation block wherein the selected plan was not being updated when the user changed the currency in the edit view.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Set up a test site:
    * Create a JN site running this branch.
    * Go to `/wp-admin/options-general.php?page=companion_settings`.
        * Activate `JETPACK_BETA_BLOCKS`.
        * Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. `mysandbox.wordpress.com` to avoid issues with the SSL certificate).
    * Sandbox the API, the store and subscribe.wordpress.com (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
    * Set up Jetpack and purchase a Premium or Professional plan.
* Go to Posts > New and insert a new Donations block.
* Set up the Stripe connection (you will be able to see a link above the form letting you to skip and instantly create a test account).
* Go back to the editor
* With the developer console open, change the currency of the block several times.
* Verify that a network call is made to `memberships/status` when the value is changed. A second call to `memberships/products` can be made if the previous call does not return any plan for the selected currency.
* Publish the post and visit it.
* Select an interval, choose an amount and click on the donate button.
* Make sure the dialog displays the amount in the currency you previously selected.
* Complete the payment and make sure the process finishes successfully.

#### Proposed changelog entry for your changes:

N/A

### CODE REVIEW

**Comment by blackjackkent** [comment]
Thanks for the comments, @mmtr -- I spent some time looking over this today. 

A couple things - 

> I think the logic above is a bit over-engineered, and can be simplified as below, that way plans will be updated whenever there are changes in products

I might need to look further into this in a future PR, but the changes you describe here (specifically, removing the early-return statements in each hook) cause the block to go into some sort of infinite loop state. Seems like there might be some deeper issue with the dependency array here.

> We likely need to add a new useEffect or update the existing ones here so the plan IDs are updated when the products prop changes.

From what I can tell, the `useEffect` hooks inside `tabs.js` actually are receiving the correctly updated plan IDs. However, the view-side HTML comment isn't being updated with the values. (You can see, for instance, that even when the block loads in initially with AUD preselected for the currency, the code editor view shows the block attributes with USD plan IDs.) I'm delving in to get my head around where the code-editor view is generated to see what might be mixed up here.

**Comment by blackjackkent** [comment]
It also appears that even if the Code Editor data display is wrong, the donation block is being saved correctly (i.e. when the currency changes and then the post is saved, it is displaying with the correct currency on the front-end). So I'm not sure where the disconnect is happening between the Code Editor view and everything else. 🤔

**Comment by mmtr** [comment]
Hey @blackjackkent, I just pushed c34fb0e for you with changes that make sure the plan IDs are updated when the fetched products change but also preventing the infinite loop you noted above. Let me know if something it's not clear there! Normally I would have let you to handle it, but we're close to the Jetpack code freeze, and this is the last thing we need before publishing the internal CfT.

Also fixed an unrelated bug in 25db31d that was causing the `type` query param to be incorrectly set to the initial call to `memberships/status`, forcing the block to always make a second call to `memberships/products` even when plans were already created.

This tests now well for me, so I think we're good here. I noted sometimes the call to `memberships/products` fails, but I'm sure it's caused by being sandboxed (request takes a bit longer and times out). It does not happen when testing in WP.com.

Screen Shot 2020-08-18 at 11 56 00

> the donation block is being saved correctly (i.e. when the currency changes and then the post is saved, it is displaying with the correct currency on the front-end

This is because currency and amounts are stored in a separate attribute, but the plan IDs attributes were still pointing to the previous plan. Those plan IDs are important because we use them for generating the URL that the donate buttons will open when clicking on them:

https://github.com/Automattic/jetpack/blob/c47a4483b202ba1f9ad044bf183908944b34b715/extensions/blocks/donations/donations.php#L62-L63

If we leave them with the previous values, the URL will point to the plans of the previous currency (and therefore, received donations will be in that previous currency).

**Comment by mmtr** [comment]
Code synced to WP.com in r212290-wpcom.

**Pull request merged**
