### PR TITLE
My Jetpack: Add Extras interstitial page

### PR DESCRIPTION
**Pull request by retrofox**
It depends on https://github.com/Automattic/jetpack/pull/23035

This is a suggestion of adding an Extras interstitial page. Basically, we copied what the Jetpack plugin shows.
Fixes #

#### Changes proposed in this Pull Request:

* My Jetpack: Add Extras interstitial page

#### Testing instructions:

* Go to add extras interstitial page `https://your-testing-site/wp-admin/admin.php?page=my-jetpack#/add-extras`
* Check you see the Extras interstitial page :smart:
* Click on the `Add Jetpack Extras` will lead to the Jetpack dashboard

image

### CODE REVIEW

**Comment by keoshi** [comment]
Very nicely done by reusing the content from the initial connection prompt!

Would only change the illustration to something like this to make sure we standardize across all interstitial views.

jetpack-extras-illustration-01

**Review by keoshi — APPROVED** [review]
LGTM!

**Review by oskosk — APPROVED** [review]
Excellent thank you!

**Comment by sdixon194** [comment]
Cherry picked to jetpack release branch in 40ddca4b0a2c8e30b6d2563f713e497fdbebc13c

Package updated in jetpack, boost, and backup release branches.

**Pull request merged**
