### PR TITLE
CSS Tidy: Add mask, scroll, and object-fit properties

### LINKED ISSUE #14993: CSS Tidy: improve modern CSS support for properties such as mask and scroll
In https://github.com/Automattic/jetpack/pull/2123 we added `flexbox` support. Let's continue supporting properties that users ask for from time to time.

**New properties for `mask`**:

mask-image
mask-mode
mask-repeat
mask-position
mask-clip
mask-origin
mask-size
mask-composite

​https://developer.mozilla.org/en-US/docs/Web/CSS/mask

Context — The property is used for certain styles in Gutenberg, like the image block style that lets you make an image appear rounded. Whitelisting the property would help users make modifications to the styles. Reported by WordPress.com HEs in 8202-wpcom

**New properties for `scroll`:**

(There are quite a few!)

scroll-behavior
scroll-margin
scroll-margin-block
scroll-margin-block-end
scroll-margin-block-start
scroll-margin-bottom
scroll-margin-inline
scroll-margin-inline-end
scroll-margin-inline-start
scroll-margin-left
scroll-margin-right
scroll-margin-top
scroll-padding
scroll-padding-block
scroll-padding-block-end
scroll-padding-block-start
scroll-padding-bottom
scroll-padding-inline
scroll-padding-inline-end
scroll-padding-inline-start
scroll-padding-left
scroll-padding-right
scroll-padding-top
scroll-snap-align
scroll-snap-stop

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

Context — This property allows page jumps to scroll smoothly, as some themes like Pique out of the box, via CSS rather than a more complicated JavaScript solution. Requested by WordPress.com HEs at 8188-wpcom

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #14993

#### Changes proposed in this Pull Request:

Add `mask`, `scroll`, and `object-fit` properties to CSS support.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

It's an enhancement of the current supported CSS elements.

#### Testing instructions:

* Go to "My Sites → Design → Customize → Additional CSS"
* Create a CSS statement using one or more of the `mask` or `scroll` or `object-fit` properties as mentioned in https://github.com/Automattic/jetpack/issues/14993#issue-580901337

#### Proposed changelog entry for your changes:

* Add support for more CSS 3.0 properties: `mask` , `scroll`, and `object-fit`

### CODE REVIEW

**Comment by jeherve** [comment]
@lancewillett Adding you as a reviewer since you've worked on this recently.

Thank you!

**Comment by lancewillett** [comment]
Even though my HACK week developer time is now over, I'll try to look soon. Should be a quick one.

**Review by lancewillett — CHANGES_REQUESTED** [review]
@nielslange Could you please also add `object-fit` and `object-position`?

**Comment by lancewillett** [comment]
@jeherve Does it mess up the sync if I change Phabricator diff summary text?

**Comment by nielslange** [comment]
@lancewillett In https://github.com/Automattic/jetpack/pull/15044/commits/3f2897ec6c3260010628a0b5d92d292ea3cf33b7 you can find the updated version as requested by you in https://github.com/Automattic/jetpack/pull/15044#pullrequestreview-378189673

**Comment by jeherve** [comment]
> Does it mess up the sync if I change Phabricator diff summary text?

It doesn't, no worries!

**Review by lancewillett — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]
This looks good to me, should be good to merge once the tests pass (I had to rebase to fix a bad test).

**Comment by lancewillett** [comment]
WP.com change landed in r204590-wpcom

**Comment by lancewillett** [comment]
I love that GitHub to Phabricator push. Wow! That is a time saver.

**Pull request merged**
