### PR TITLE
Unit Tests: switch to PHP 7.4 Production

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* Now that PHP 7.4 has shipped, we should be able to use the final stable version in Unit Tests.

#### Testing instructions:

* Not much to test here, just see if the tests pass.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by kraftbj** [comment]
Couple of tests are failing in 7.4, but sounds like issues with the tests themselves.

```
There were 2 errors:

1) WP_Test_Jetpack_Photon::test_photon_cdn_in_rest_response_with_view_context

PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertArrayHasKey() must be a array or ArrayAccess

/tmp/wordpress-master/src/wp-content/plugins/jetpack/tests/php/test_class.jetpack_photon.php:1040

2) WP_Test_Jetpack_Photon::test_photon_cdn_in_rest_response_with_edit_context

PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertArrayHasKey() must be a array or ArrayAccess

/tmp/wordpress-master/src/wp-content/plugins/jetpack/tests/php/test_class.jetpack_photon.php:1065
```

**Comment by kraftbj** [comment]
I updated https://github.com/Automattic/jetpack/pull/13773 to give us a playground to work on this test.

**Comment by jeherve** [comment]
It turns out PHP 7.4 is not yet ready for Ubuntu Trusty (14.04) on Travis. Work is in progress here:
https://github.com/php-build/php-build/pull/599

Putting this PR on hold for now.

**Comment by kraftbj** [comment]
Alternatively, we can explore not using Trusty. An initial test led to a lot more failures, so we can examine that on it's own and not within the context of this PR if php-build's work beats us to it.

**Comment by kraftbj** [comment]
Still fiddling with it. When I dump the value, it is there, but obviously is sometimes a class instead of an array. I added some json encoding/decoding to standardize everything as an array, but still instances of Core not returning what we'd expect.

This isn't an unit test failure as much as an integration test failure, but still not sure what's happening yet.

**Pull request closed without merging**
