### PR TITLE
Jetpack API package

### PR DESCRIPTION
**Pull request by gravityrail**
Moves shared internal API functions to the `@automattic/jetpack-api` package.

This is part of work on Jetpack RNA p2-p9dueE-2sp.

#### Changes proposed in this Pull Request:

* Move rest-api class into a shared js-package

#### Jetpack product discussion
p2-p9dueE-2sp

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Build, connect Jetpack and confirm that everything in the dashboard loads correctly.
* Follow instructions below to run tests for the new package

```sh
cd projects/js-packages/api
pnpm run test
```

Right now there are minimal tests, just there to act as a guide as we add and modify API methods.

### CODE REVIEW

**Comment by gravityrail** [comment]
There's a weird unrelated test failure:

```
[3] NODE_ENV=production pnpm run build-search exited with code 0
  [build-production-client] [18:46:18] 'react:master' errored after 1.62 min
  [build-production-client] [18:46:18] Error in plugin "webpack"
  [build-production-client] Message:
  [build-production-client]     TypeError: Cannot set property 'Headers' of undefined
````

See here: https://github.com/Automattic/jetpack/pull/20531/checks?check_run_id=3234044347#step:11:7145

**Review by sergeymitr — APPROVED** [review]

**Review by jeherve — CHANGES_REQUESTED** [review]
You'll need to fix the linting and changelog issues before we can merge this, I am afraid.

More generally, I wonder if this may prove a bit confusing to have the different endpoints listed in the new JS package, while we use them in the Jetpack dashboard and in other places. What would you think about only having the actual REST API tools in the JS package, and set up the different calls to endpoints directly where we use them?

This also makes me wonder if we shouldn't take that opportunity to move towards `@wordpress/api-fetch` for such tools. What do you think?

**Comment by gravityrail** [comment]
@jeherve I fixed those couple of issues. FWIW, they were _somewhat_ spurious:

> Warning: Good job! "projects/plugins/jetpack/_inc/client/rest-api/index.js" no longer has any lint errors,
and should be removed from the exclude list.

This probably shouldn't be a warning. Info is fine - something like this should not be a blocker to merging IMO.

The other was a changelog entry that had a "Type" of "changed", which is not on your list. Fair enough I suppose... but the pre-commit checks (that already look for changelog entries) should also check if they're valid.

This is ready for another look.

**Comment by gravityrail** [comment]
> More generally, I wonder if this may prove a bit confusing to have the different endpoints listed in the new JS package, while we use them in the Jetpack dashboard and in other places. What would you think about only having the actual REST API tools in the JS package, and set up the different calls to endpoints directly where we use them?

Personally I was more confused by the duplication than having a centralised file that has methods ppl might not use. It's possible that people might want to define these JS endpoints where the PHP endpoints are defined, but that can be done in subsequent PRs and I don't see that decision as a blocker for this work.

> This also makes me wonder if we shouldn't take that opportunity to move towards @wordpress/api-fetch for such tools. What do you think?

Doesn't seem related to this PR, and I prefer not to introduce dependencies unless we have to, including dependencies on `@wordpress/*` libraries, since that will then preclude using this in other contexts where those libraries aren't available.

**Review by kraftbj — DISMISSED** [review]
I concur that moving to `api-fetch` is worth looking into, but I don't think it needs to be a blocker for this PR. I'm approving this based on the testing instructions. I don't have suitable context to evaluate the philosophical question at hand. We can still discuss that and separate the tools from the endpoints later.

**Review by kraftbj — DISMISSED** [review]

**Comment by jeherve** [comment]
> This probably shouldn't be a warning. Info is fine - something like this should not be a blocker to merging IMO.

I'd prefer to leave this a blocking check, personally. This is the easiest way for us to ensure the list remains up to date.

> The other was a changelog entry that had a "Type" of "changed", which is not on your list. Fair enough I suppose... but the pre-commit checks (that already look for changelog entries) should also check if they're valid.

Yes, the pre-push check is a bit more limited than the full-fledged check. It only looks for a changelog file, but does not check its validity like the check does. That's definitely something we could aim to improve in the pre-push check in the future!

> that can be done in subsequent PRs and I don't see that decision as a blocker for this work.

**Review by jeherve — APPROVED** [review]
This should be good to merge now. 🚢

**Comment by gravityrail** [comment]
Committed to WPCOM in r229879-wpcom

**Pull request merged**
