### PR TITLE
Scan: Don't show prompt to set up if not on correct plan

### LINKED ISSUE #6008: Admin: Set Up button showing in Security Scanning when user has Personal plan
#### Steps to reproduce the issue
- make sure the site is in a Personal plan
- make sure VaultPress plugin is deactivated
- go to Jetpack > Settings > Security

#### What I didn't expect
The Set Up button to be displayed since Security Scanning is not included in the Personal plan.

#### What happened instead
The Set Up button is displayed
captura de pantalla 2016-12-29 a las 12 59 49

Props @jenhooks for reporting this.

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #6008

The Scan feature requires minimum Premium plan.  Make sure to show prompt to upgrade in the scan cards.  

While on a Personal plan, Make sure the `Upgrade` buttons shows for all scan cards: 
- /security tab
- /search page
- /dashboard card

### CODE REVIEW

**Comment by jeherve** [comment]
This works well when VaultPress is not installed:

screen shot 2017-01-12 at 19 33 54

However as soon as I install and configure VaultPress using the Registration key that was emailed to me, the cards switch to "Active":

screen shot 2017-01-12 at 19 08 58
screen shot 2017-01-12 at 19 08 47

It seems the check for `if ( active && installed ) {` comes a bit too late and overwrites the "Upgrade" button

**Comment by dereksmart** [comment]
thanks @jeherve, 

pushed 416b1b4e61a8759a73ce9d05b4479b92a8416d6b which will make sure the ProStatus button will not show active if not on the correct plan 

also pushed ef4ead70dea4c488a74f405b176df0fb3d6ee369 that will make sure the Dashboard content will reflect the correct text/data, relying on the data received from the vaultPress API (in case they purchased VaultPress separately.)

**Comment by jeherve** [comment]
It seems to work well now; I tested with a personal and a premium plan, and all cards are displayed properly.

I did not, however, check with a separate VaultPress plan.

**Comment by zinigor** [comment]
Ported to `branch-4.5` in b86f4da.

**Pull request merged**
