### PR TITLE
PHPCS Changed: The Next Generation

### PR DESCRIPTION
**Pull request by kraftbj**
Third (or fifth?) time is the charm.

DO NOT MERGE UNTIL AFTER https://github.com/Automattic/jetpack/pull/13975 LANDS AND THE BETA BUILDER HAS BEEN UPDATED.

#### Changes proposed in this Pull Request:
* PHPCS processing on changed lines only.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* On this branch, make changes to a whitelisted file and a non-whitelisted file ( anything in the packages folder for a whitelist or `uninstall.php` for non-whitelist. ( ` // This is a fine change.` or ` // This will throw an error`
* Attempt to commit (`yarn install` must have been run before at some point)
* Confirm that the precommit hook prevents it.

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by jeherve** [comment]
Noting that @lezama ran into another issue with `phpcs-changed` here:
https://travis-ci.org/Automattic/jetpack/jobs/608753079?utm_medium=notification&utm_source=github_status

```
PHP Warning:  Unsupported declare 'strict_types' in /tmp/wordpress-master/src/wp-content/plugins/jetpack/vendor/sirbrillig/phpcs-changed/PhpcsChanged/Cli.php on line 2
Warning: Unsupported declare 'strict_types' in /tmp/wordpress-master/src/wp-content/plugins/jetpack/vendor/sirbrillig/phpcs-changed/PhpcsChanged/Cli.php on line 2
PHP Parse error:  syntax error, unexpected '{', expecting identifier (T_STRING) in /tmp/wordpress-master/src/wp-content/plugins/jetpack/vendor/sirbrillig/phpcs-changed/PhpcsChanged/Cli.php on line 13
Parse error: syntax error, unexpected '{', expecting identifier (T_STRING) in /tmp/wordpress-master/src/wp-content/plugins/jetpack/vendor/sirbrillig/phpcs-changed/PhpcsChanged/Cli.php on line 13
The command "./tests/run-travis.sh" exited with 1.
cache.2
store build cache
```

**Comment by kraftbj** [comment]
@jeherve That's because of PHP 5.6. That is handled in the tests/setup-travis.sh changes in this PR (remove that dependency for under PHP 7.1).

**Comment by kraftbj** [comment]
#13975 has been merged, so this PR is regular review. We should specifically try this with JN since the beta builder would have built that branch as well as manually via `tools/build-jetpack.sh -d -b retry/phpcs-changed Automattic/jetpack /tmp/jetpack`

**Review by jeherve — APPROVED** [review]
This seems to work, again :)

**Comment by kraftbj** [comment]
Here goes nothing.

**Pull request merged**
