### PR TITLE
WAF: Generate ip rules when running the update rules cron

### LINKED ISSUE #27209: Upgrade to 11.5 broke WAF
### Impacted plugin

Protect

### Steps to Reproduce

My site is set to auto update Jetpack. Today it did so at 9:58am, and immediately my site went down.

The error log was full of 
 PHP Fatal error:  require(): Failed opening required '/home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/allow-ip.php' (include_path='.:') in /home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/rules/rules.php on line 2', referer: https://lezwatchtv.com/

I went into that file and found these:

//if ( require('/home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/allow-ip.php') ) { return; }
//if ( require('/home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/block-ip.php') ) { return $waf->block('block', -1, 'ip block list'); }

So I commented them out and the site came back.

### A clear and concise description of what you expected to happen.

An upgrade shouldn't break things.

### What actually happened

Upgrade caused a white screen of death.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Comment out the top lines:

//if ( require('/home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/allow-ip.php') ) { return; }
//if ( require('/home/wp_w9hpj2/lezwatchtv.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/../rules/block-ip.php') ) { return $waf->block('block', -1, 'ip block list'); }

### PR DESCRIPTION
**Pull request by miguelxpn**
Fixes #27209

#### Changes proposed in this Pull Request:

* Regenerate the ip rules when running the cron that updates the waf rules

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Spin up a JN site with a Scan subscription.
* Turn on the WAF module
* SSH into the site and remove all the rules
* Run the cron via `wp cron event run jetpack_waf_rules_update_cron`
* Verify that both sets of rules were generated and that the site still works after the cron runs

### CODE REVIEW

**Comment by anomiex** [comment]
What about the code path via line 334?

Or maybe to better future-proof this, we should just move the call to `generate_ip_rules` inside `generate_rules` instead of relying on every caller to do it.

**Comment by miguelxpn** [comment]
> What about the code path via line 334?
> 
> Or maybe to better future-proof this, we should just move the call to `generate_ip_rules` inside `generate_rules` instead of relying on every caller to do it.

Good catch. Yeah I agree, that's part of what we'll do in a more elaborated patch. We also are going to add some better file handling around all file operations.

**Review by samiff — APPROVED** [review]
Reproduced fatal pre-patch, and verified that this patch resolves the immediate issue 👍

**Comment by coder-karen** [comment]
Cherry-picked to release branch in d7fbae8c8bd52ca26c15dd7c0dd0956de977c2d0

**Pull request merged**
