### PR TITLE
Sharing: Add X button

### LINKED ISSUE #32178: Sharing / Social: update Twitter logo
### What

Update the logo for Twitter to the new logo

Feature request from user: 6586135-zd-woothemes

### Why

Twitter has recently updated its logo: https://techcrunch.com/2023/07/24/twitter-has-officially-changed-its-logo-to-x/

### How

_No response_

---

_Just adding a couple places where this appears; feel free to update with more (-cuemarie)_:

- [ ] Social Icons block
- [ ] Sharing Buttons

### LINKED ISSUE #33315: Enhancement: Change Twitter share button to X.
### Impacted plugin

Social

### What

Need to change twitter function to X.

### How

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #32178
Fixes #33315

## Proposed changes:

This PR does 2 things:

1. It adds a new button for the X service.
2. It changes the default sharing buttons added on sites that enable the module for the first time from Twitter and Facebook to Facebook and X.

**Notes**

- It **does not** replace the existing Twitter button, for the reasons we discussed in #33118. This is less forceful on site owners.
- The new Share_X class extends the existing Twitter class so we can rely on that for now.
- At some point in the future, we may be able to merge the 2, once the Twitter brand is more deprecated than it is today.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

No discussion on this, but some previous related PRs:

- https://github.com/Automattic/social-logos/pull/126
- #33118

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

1. Go to Jetpack > Settings > Social and enable sharing buttons.
2. Go to Settings > Sharing and add a Twitter and an X sharing button.
3. They should both look good in wp-admin and on the frontend.
4. Clicking the button should work too.

> **Note**
> Matching Calypso PR: https://github.com/Automattic/wp-calypso/pull/81835

### CODE REVIEW

**Review by zinigor — DISMISSED** [review]
I don't know if I'm testing this wrong, but the actual sharing doesn't work for me. When I click the X sharing button, a new window opens that just takes me to the same page. Can it be due to the fact that the URL parameter still says `twitter` instead of `X`?

**Comment by jeherve** [comment]
Ah, that's my bad. I had only tested on a site where the old Twitter button was also active. This obviously won't always be the case, so we cannot just extend the Twitter class. I've just pushed 4a8fc54c8ea3682bd468869aa56ee115509e16ca
 to take care of this issue. It does duplicate a few things, but I think this is fine for now; at some point in the future we will eventually get rid of the Twitter class.

**Review by sdixon194 — APPROVED** [review]
Looks good to me and works! No official button is available yet right? Approving this PR so we can merge and test in the beta, and if there's an option for an official button later we can add it to a followup.

**Comment by jeherve** [comment]
> No official button is available yet right? 

Correct. Maybe one will be added at some point in the future.

**Comment by jeherve** [comment]
@sdixon194 Following-up to your remark about official buttons, I just opened #33474 to improve the button when using the Official style.

Thank you!

**Pull request merged**
