### PR TITLE
Connection: do not display Connect Bar when in Offline mode, and make SEO userless

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:
﻿
This PR is a follow-up of #18837 and #19300.

It introduces the following changes:

**The connect bar main message should be translatable.**

**The SEO module now works in userless mode.**

**The Protect card should still be a bit readable when in offline mode.**

In bc422ac3f771e80a36ef47ef73d7681878411979, we wrapped the foldable card into a SettingsGroup component that already handles the display of the group when in offline mode. We consequently do not need to handle it again in the foldable card.

**Before**

Screenshot 2021-03-26 at 18 06 09

**After**

Screenshot 2021-03-26 at 18 06 57

**Let's not show the connect bar when in offline mode, since folks will not be able to connect their site to WordPress.com anyway.

**Before**

Screenshot 2021-03-26 at 18 24 02

**After**

Screenshot 2021-03-26 at 18 24 14

**Note**: a potential alternative would be to add the Offline check within the connect bar component itself. 

#### Jetpack product discussion

p1HpG7-ba8-p2

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start with a brand new JN site running `master`.
* In the Jetpack constants page, enable Offline mode.
* If you then visit Jetpack > Settings, you should see the Userless card appear under some of the features, even though your site cannot be connected to WordPress.com.
* Switch to this branch.
* The userless connect bar prompt should disappear.
* In the Jetpack constants page, disable Offline mode and enable `JETPACK_NO_USER_TEST_MODE`.
* Disconnect from Jetpack, reconnect in userless mode.
* Go to "Settings -> Traffic -> Search engine optimization" and confirm that the module works in Userless mode (switch on/off and settings are available).

### CODE REVIEW

**Review by sergeymitr — APPROVED** [review]
Works well, thanks for fixing this! 👍

**Comment by sergeymitr** [comment]
There's a conflict with newly merged #18810, I'm working on resolving it.

**Comment by sergeymitr** [comment]
Hi @jeherve.
Since the code freeze is coming, I decided not to wait for this branch to merge, and implemented the "Userless SEO" changes right here, hope you don't mind.

Please review my changes, including the merge of `master` branch, in case I missed something.

**Review by jeherve — COMMENTED** [review]
This looks good to me, thanks for the addition. I cannot approve my own PR though, so I'll leave this to somebody else. :)

**Review by fgiannar — APPROVED** [review]
Thanks for working on this @jeherve and @sergeymitr!
The code looks good!
Tested using the provided instructions and worked as expected 🥇

**Pull request merged**
