### PR TITLE
JS Components: Add ThemeProvider to AdminPage component

### PR DESCRIPTION
**Pull request by nunyvega**
#### Changes proposed in this Pull Request:

* Add ThemeProvider to the AdminPage component.
* Remove it whenever it's wrapping an AdminPage render. 

#### Jetpack product discussion

p1658244302220609-slack-jetpack-agora

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

*  Create Jurassic Ninja site with JP Backup, Social and Protect.
*  Check the Social and Protect admin pages and confirm that they look like before.
*  Complete a restore using Jetpack Backup and confirm that the Review message looks like it's expected.

Before:
Screen Shot 2022-07-19 at 18 59 32

After:
Screen Shot 2022-07-19 at 18 56 41

### CODE REVIEW

**Comment by oskosk** [comment]
May need rebase after merging https://github.com/Automattic/jetpack/pull/25263  ? (or something)

**Comment by retrofox** [comment]
I think we should take a look at all places where the `<AdminPage />` component is used. I found the following ones doing a quick search:


* https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/starter-plugin/src/js/components/admin-page/index.jsx/#L22
* https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/social/src/js/components/admin-page/index.jsx/#L39
* https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/protect/src/js/components/admin-page/index.jsx/#L172
* https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/protect/src/js/components/admin-page/index.jsx/#L118
* https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/protect/src/js/components/admin-page/index.jsx/#L76
* https://github.com/Automattic/jetpack/blob/trunk/projects/packages/wordads/src/dashboard/components/dashboard/index.jsx/#L67
* https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/_inc/components/product-interstitial/index.jsx/#L89
* https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/_inc/components/connection-screen/index.jsx/#L49
* https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/_inc/components/add-license-screen/index.jsx/#L36
* https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/_inc/components/add-license-screen/index.jsx/#L36

**Comment by nunyvega** [comment]
Good call @retrofox , I'll check those

**Comment by nunyvega** [comment]
Rebased, checking now the different places where the AdminPage component is used:
- [ ] Starter plugin
- [ ] Social
- [ ] Protect
- [ ] WordAds dashboard
- [ ] My Jetpack Product interstitial
- [ ] My Jetpack Connection screen
- [ ] My Jetpack add license screen

**Comment by nunyvega** [comment]
Closing this PR as it does not follow how ThemeProvider should be applied. 
ThemeProvider is intended to be the main wrapper of the app, and not to be included inside another component.
More details in p1658244302220609-slack-jetpack-agora

**Pull request closed without merging**
