### PR TITLE
General: remove deprecated methods.

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This PR removes deprecated methods and files that were marked as deprecated before Jetpack 10.0 was released, back in August 2021.

Some remain, when they are still in use on WordPress.com Simple.

This PR ends up removing a significant part of the Compat package, since those classes and methods do not appear to be used in active W.org plugins at the moment (as per a search on wpdirectory.net). Only the `GP_Locale` and `GP_Locales` classes remain; maybe those should be moved somewhere else at this point, in their own package?

This PR also removes a compatibility layer that was added for the Crowdsignal plugin. That layer does not seem necessary anymore, since:
https://github.com/Automattic/crowdsignal-plugin/commit/941fc5758152ebf860a14d1cd0058245e8aed86b

Noting that as part of this change, I also landed D140596-code to ensure tests will continue to work on WordPress.com after this change is merged.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Ensure you can continue to connect the Jetpack plugin to WordPress.com.
* Ensure that usage of `GP_Locale` or `GP_Locales` in the Jetpack plugin continues to work as expected. Places to test: [notifications](https://github.com/Automattic/jetpack/blob/fb71cf18d6624fe1dabfe356d347e040114d9585/projects/plugins/jetpack/modules/notes.php#L172-L178), [Facebook's official sharing button](https://github.com/Automattic/jetpack/blob/932a9cc02857be81f78086afbdd2c9f5f5d50ab3/projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php#L1865-L1868), [Instant Search](https://github.com/Automattic/jetpack/blob/1366be26137abfc9ced38a71aaa26ec7624f0fa0/projects/packages/search/src/class-helper.php#L706-L712).

### CODE REVIEW

**Comment by jeherve** [comment]
@fgiannar @darssen Since this is removing some old Sync-related classes, I wanted to rope you in for a review since you may have an opinion on that.
Thank you!

**Review by monsieur-z — DISMISSED** [review]
I haven't noticed any issues with the connection or sharing. You may ask another review from someone more knowledgeable in that part of the code.

**Review by fgiannar — APPROVED** [review]
Tested using the provided instructions and everything works as expected 👍 
The only issue I noticed, but confirmed is unrelated to this PR, is that when I change the site locale after connecting Jetpack on a brand new JN site, the Jetpack menu and dashboards are not translated:
Screenshot 2024-03-25 at 08 59 40

I also made sure to test with the current branch for the Jetpack plugin and the oldest version of Jetpack Backup to confirm nothing breaks just in case.
Apologies for the delayed review, Jeremy! This one slipped through the cracks..

**Review by zinigor — APPROVED** [review]
That's some glorious cleanup! Let's get it in for the testing week.

**Pull request merged**
