### PR TITLE
Newsletters: Add Jetpack Newsletter Plugin Icon + Email Preview option.

### PR DESCRIPTION
**Pull request by lezama**
Improves https://github.com/Automattic/jetpack/issues/38370

## Proposed changes:

Screenshot 2024-08-02 at 3 44 33 PM

Screenshot 2024-08-02 at 3 44 54 PM

### Other information:

Needs D157276-code

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Check instructions in D157276-code

### CODE REVIEW

**Comment by crisbusquets** [comment]
Hi @lezama !

I tested it using a Jurassic Ninja site, and I can see the "plugin" when I write a post:

Screenshot 2024-08-03 at 10 34 11


The CTAs only seem to have rounded corners in one side. They all should be the same (the default)
Screenshot 2024-08-03 at 10 38 10

The preview doesn't work, but I'm not sure if it's part of another PR. The error I see has to do with this:
`{"code":"rest_cannot_send_email_preview","message":"Please connect your user account to WordPress.com","data":{"status":401}}`

But I'm already connected to WordPress.com. If this is an error we expect would be quite common, we should add an alert in the plugin, right between the copy and the CTAs.
Screenshot 2024-08-03 at 10 41 17

I see that the "plugin" also appears in Pages. Is it possible to remove it there? You'll never send a "Page" as a newsletter 🤔

**Comment by lezama** [comment]
thanks for the review @crisbusquets!

> The CTAs only seem to have rounded corners in one side. They all should be the same (the default)

Great catch! fixed.

> The preview doesn't work, but I'm not sure if it's part of another PR. The error I see has to do with this:

You need to set `JETPACK__SANDBOX_DOMAIN` to point to your sandbox with D157276-code applied, I will merge the wpcom side so it is easier to test!

> But I'm already connected to WordPress.com. If this is an error we expect would be quite common, we should add an alert in the plugin, right between the copy and the CTAs.

We could! maybe change the icon if there's a problem?

> I see that the "plugin" also appears in Pages. Is it possible to remove it there? You'll never send a "Page" as a newsletter 🤔

good point, fixed.

I added a feature flag, now you need to add `?showNewsletterMenu` to the editor url to test this PR.

I think we could merge and improve on follow up PRs.

**Comment by crisbusquets** [comment]
Thanks @lezama! 

>  I will merge the wpcom side so it is easier to test!

I'll wait for it 😅

**Comment by lezama** [comment]
I just deployed the wpcom side!

**Comment by lezama** [comment]
@crisbusquets deployed the wpcom side!

**Review by simison — APPROVED** [review]
Code looks good, let's merge behind feature flag and continue polishing 👍

**Pull request merged**
