### PR TITLE
Drop Mailchimp shortcode support

### PR DESCRIPTION
**Pull request by sirreal**
Mailchimp has not been released and the shortcode was never in use. It
will soon be released as a Gutenberg block.

Remove the shortcode support so it never needs to be maintained.

At the time, I've naively removed the relevant shortcode file. There's likely more work involved.

The shortcode was added in 1d4dffbac4

CC: @jeherve 

## Testing
- Is support for the `[jetpack-email-subscribe]` shortcode removed?
- Are all the relevant related assets removed.
- Does the Mailchimp block continue to work correctly?

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
You'll need to remove the CSS file from here as well:
https://github.com/Automattic/jetpack/blob/661d73f2f4da09d8520274fa3b641b97fc30db90/class.jetpack.php#L68
https://github.com/Automattic/jetpack/blob/f836eb1f648cb7a8a67573cd208c796c0429a5c0/tools/builder/frontend-css.js#L35

I would also recommend that we keep the PHP file around, but with a deprecated message like so:
https://github.com/Automattic/jetpack/blob/07257a1360bfd26cf0eb33ef99f7ac74b34e048c/modules/debug.php#L3

**Comment by sirreal** [comment]
> I would also recommend that we keep the PHP file around, but with a deprecated message like so:

To be clear, are you suggesting keeping `modules/shortcodes/email-subscribe.php` around but deprecated? How would that be different? Would the shortcode remain available? Would the supporting css and js need to be left?

I want to understand what the motivation for leaving it would be. The shortcode was never released or publicly usable, it seems to me that the win is eliminating the code and ensuring it never needs to be maintained. If we leave it, even as deprecated code, it seems like a burden.

Trying to understand where the suggestion is coming from 🙂

**Comment by jeherve** [comment]
Sorry, I should have been clearer.

> are you suggesting keeping `modules/shortcodes/email-subscribe.php` around but deprecated?

Yes, exactly.

> Would the shortcode remain available? Would the supporting css and js need to be left?

No.

I am mostly suggesting this because in the past we've sometimes had issues when deleting PHP files and releasing a new version of Jetpack without that file. In some caching configurations, this was causing fatals. Leaving the file around (even though it's empty) works around that problem.

**Comment by sirreal** [comment]
> I am mostly suggesting this because in the past we've sometimes had issues when deleting PHP files and releasing a new version of Jetpack without that file.

Makes perfect sense, thanks for the explanation! I've restored the file as you suggested.

**Review by jeherve — APPROVED** [review]
This looks good. Merge when ready.

**Pull request merged**
