### PR TITLE
Remove port from IP address if it's there

### PR DESCRIPTION
**Pull request by samhotchkiss**

### CODE REVIEW

**Comment by rcoll** [comment]
Love it. 🚢

**Comment by da2x** [comment]
REVERT! This breaks IPv6 support!

`$_SERVER['REMOTE_ADDR']` will never return a port suffix anyway. What was this ever meant to fix?

**Comment by jeherve** [comment]
@da2x Thanks for the report!

> $_SERVER['REMOTE_ADDR'] will never return a INET address-styled colon-separated port suffix anyway.

It unfortunately does in some server configurations.

**Comment by da2x** [comment]
> It unfortunately does in some server configurations.

Ha. People. They do the craziest thing when passing variables to PHP.

Anyway, you can keep this fix in place, but it will require additional checks. Count for how many colons there are in the string. More than one? Then you’ve got an IPv6 address as there will always be at least two. If there is only one colon and also four dots in the string? Assume it’s an InetSocketAddress notation representing a IP-port pair and proceed with splitting the host from port by splitting at the colon.

Should also remove any leading `[` and trailing `]:port`, but again: this shouldn’t happen unless the environment is broken.

**Pull request merged**
