### PR TITLE
Search: updated default photon image size

### PR DESCRIPTION
**Pull request by kangzj**
Requested in p4Kr4c-42v-p2#comment-17418 

#### Changes proposed in this Pull Request:
Requested by special project team who requested larger image in search results.
* Updated default photon image size from 300x300 to 600x600.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
1. Go to a test site with Instant Search enabled. The test site should be on WordPress.com or Jetpack with Site Accelerator, so that Photon is used for image resizing.
2. Change your search result type to ‘Expanded’ in Customizer.
3. Using your browser developer tools, inspect the images in the search results and make sure they are resized to max dimensions of 600x600.

### CODE REVIEW

**Review by jsnmoon — APPROVED** [review]
👍 Works as described!

The Changelogger test is currently failing for this PR; fixed by adding the generated file from `projects/plugins/jetpack/vendor/bin/changelogger add`.

**Review by bluefuton — APPROVED** [review]
Tests out well! ✅

**Comment by bluefuton** [comment]
Shipped to wpcom in r222954-wpcom. 🚀

**Comment by bluefuton** [comment]
🎉 🚢

**Pull request merged**
