### PR TITLE
Launchpad: Remove unnecessary require

### PR DESCRIPTION
**Pull request by sixhours**
Related to [#75504](https://github.com/Automattic/wp-calypso/issues/75504)

## Proposed changes:

* Removes a duplicated `require` of the Launchpad code; this code is already required in the features index: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php#L80
## Does this pull request change what data or activity we track or use?

No.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
https://github.com/Automattic/wp-calypso/issues/75504

## Testing instructions:

* Apply this patch to your sandbox and sandbox `public-api.wordpress.com`
* Visit `/start` and create a new site with the "Write & Publish" intent.
* The Launchpad step should still work, with no errors from the API.
* Your sandbox should not throw any PHP errors as a result of removing this require.

### CODE REVIEW

**Comment by sixhours** [comment]
Good to note, I wasn't able to get the CLI tool to add a changelog entry (I think because the jetpack-mu-wpcom package is new) so I've added one manually.

**Comment by sixhours** [comment]
@Automattic/jetpack-crew not sure if you're the right group to ping, but I couldn't generate a changelog entry with the CLI tool, so I added one manually. Now my changelog validity is failing and the suggested fixer script just hangs. Any advice? 🙏

**Comment by samiff** [comment]
Hi @sixhours 👋  

> I wasn't able to get the CLI tool to add a changelog entry

What wasn't working with that exactly, and were you trying with `jetpack changelog add packages/jetpack-mu-wpcom` ? 

> my changelog validity is failing and the suggested fixer script just hangs

Using `tools/fixup-project-versions.sh` ran okay on my end. Without any error output, hard to say what could have been happening on your end. You might check `tools/check-development-environment.sh` to see if anything looks off there.

**Review by samiff — DISMISSED** [review]

**Comment by sixhours** [comment]
@samiff Sorry I should have added more detail 😅 

When I run `jetpack changelog add` and follow the prompts, it says it added a changelog file successfully, but there's nothing new when I `git status`:

Screen Shot 2023-05-23 at 1 56 38 PM

Screen Shot 2023-05-23 at 2 02 51 PM

The linter suggested running `tools/project-version.sh -f -u 2.2.2-alpha packages/jetpack-mu-wpcom`, which just hangs and doesn't seem to do anything. But now I think it may be because I'm missing `pnpm` because I'm seeing an error to that effect when I try to run `tools/fixup-project-versions.sh`: 

Screen Shot 2023-05-23 at 2 01 04 PM

I'll try to get pnpm installed and try again.

**Review by samiff — APPROVED** [review]
Looks like you were able to get that fixed up 👍

**Pull request merged**
