### PR TITLE
Instant Search: Simplify modal animation

### LINKED ISSUE #19836: Instant Search: remove or reduce modal animation
#### Is your feature request related to a problem? Please describe.
@pablohoneyhoney reports in https://github.com/Automattic/jetpack/pull/19251#issuecomment-838645044:

> 
> It would be neat if we enhance the animation that happens currently with the Search modal (sliding up from the bottom) to be simpler as a quick fade or even remove it all together. The animation itself delays the action (it’s fairly slow), and it doesn’t look good either. There are other particular cases like this P2 on a non P2020 5dIxE-p2 with an open field where the Search behavior (when you start typing) and the look (styles on the close ad clear UI) aren’t ideal. While this case is running on an older theme, Lighthouse is considering the open field as a resting search UI that would likely create a similar fractured flow.

#### Describe the solution you'd like
The modal animation should be a quick fade or even removed all together.

#### Additional context
@pablohoneyhoney started a Slack conversation about this in p1620744989134600-slack-jetpack-search-team. @p3ob7o  added: "I agree on the animation, it’s quite jarring. I’d love a quick fade as Pablo suggested."

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes https://github.com/Automattic/jetpack/issues/19836.

#### Changes proposed in this Pull Request:

* Drop animation from modal opening and use a simple opacity transition instead for a snappier feel.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
On a test site with a Jetpack Search plan, start a search to open the modal. Verify that there's a short transition but no slide animation. When closing the modal, verify that there is no transition or animation.

cc @pablohoneyhoney @evilluendas

### CODE REVIEW

**Comment by kangzj** [comment]
This looks fantastic.

One tiny thing I noticed is the text would disappear a little bit later than the overlay. I think it'll be better if they disappear together.

image

**Comment by kangzj** [comment]
And also the tricky `scrollOverlayToTop` doesn't seem to be necessary anymore.

https://github.com/Automattic/jetpack/blob/e76b6ebd438259b44ee2ead459aa4fb3b4410192/projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx#L170

**Comment by bluefuton** [comment]
> One tiny thing I noticed is the text would disappear a little bit later than the overlay. I think it'll be better if they disappear together.

That's curious - I don't think we have any kind of transition on the overlay contents. Do you have a screencast to demonstrate? & is it across all browsers?

**Comment by kangzj** [comment]
> > One tiny thing I noticed is the text would disappear a little bit later than the overlay. I think it'll be better if they disappear together.
> 
> That's curious - I don't think we have any kind of transition on the overlay contents. Do you have a screencast to demonstrate? & is it across all browsers?

It is across all browsers.  I attached a gif but ended up not moving, attached again - seems moving this time.
Screen Capture on 2021-06-04 at 15-55-55

**Review by jsnmoon — DISMISSED** [review]
Looks good and works for me; I'm not able to reproduce the text animation bug either.

Could we remove all `scrollOverlayToTop` related code with this PR? It should no longer be necessary now that we're not using a slide-in animation. Open to doing this in a follow-up PR.

**Comment by evilluendas** [comment]
Hey @bluefuton, thanks a lot for this change! I think it makes it feel much faster than the full animation, it's a great improvement 👏 

I've been playing with it a bit and I think I'd make it even faster, `0.1s` instead of `0.2s` so it's even subtler. The modal is such a big and visually heavy component that any transition is very noticeable, so even that .1 of difference can end up feeling slow. What do you think?

**Comment by bluefuton** [comment]
Thanks for the feedback @evilluendas! I will drop it to 0.1s as you suggested 👍

**Comment by bluefuton** [comment]
Todo:
- [ ] remove `scrollToTop` code and re-test
- [ ] investigate Jasper's report of text disappearing too late

**Comment by bluefuton** [comment]
@kangzj reports that he can no longer reproduce the 'text disappearing before the modal' effect noted above. 👍

**Review by kangzj — APPROVED** [review]
LGTM 👍

**Review by evilluendas — APPROVED** [review]

**Comment by lezama** [comment]
@jeherve is this good to go?

**Comment by pablohoneyhoney** [comment]
Looking forward to get this iteration out.

**Review by jsnmoon — APPROVED** [review]

**Comment by jsnmoon** [comment]
Deployed in r227578-wpcom.

**Comment by bluefuton** [comment]
Thanks for 🚢 @jsnmoon!

**Pull request merged**
