### PR TITLE
Sync: Check that jetpack_json_wrap exists

### LINKED ISSUE #9477: 6.1 Upgrade: Fatal when upgrading via WP-CLI
As reported in the forums and I saw when upgrading myself. The upgrade goes through and is successful. The function is new ( https://github.com/Automattic/jetpack/blob/master/functions.global.php#L167 ).

My guess is something to do with calling a new function during the upgrade process?

```
Enabling Maintenance mode...
Downloading update from https://downloads.wordpress.org/plugin/jetpack.6.1.zip...
Unpacking the update...
Installing the latest version...
Removing the old version of the plugin...
Plugin updated successfully.
Disabling Maintenance mode...
+---------+-------------+-------------+---------+
| name | old_version | new_version | status |
+---------+-------------+-------------+---------+
| jetpack | 6.0 | 6.1 | Updated |
+---------+-------------+-------------+---------+
Success: Updated 1 of 1 plugins.
PHP Fatal error: Uncaught Error: Call to undefined function jetpack_json_wrap() in /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php:27
Stack trace:
#0 /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php(17): Jetpack_Sync_JSON_Deflate_Array_Codec->json_serialize(Array)
#1 /jetpack/sync/class.jetpack-sync-sender.php(177): Jetpack_Sync_JSON_Deflate_Array_Codec->encode(Array)
#2 /jetpack/sync/class.jetpack-sync-sender.php(219): Jetpack_Sync_Sender->get_items_to_send(Object(Jetpack_Sync_Queue_Buffer), true)
#3 /jetpack/sync/class.jetpack-sync-sender.php(124): Jetpack_Sync_Sender->do_sync_for_queue(Object(Jetpack_Sync_Queue))
#4 /jetpack/sync/class.jetpack-sync-sender.php(88): Jetpack_Sync_Sender->do_sync_and_set_delays(Object(Jetpack_Sync_Queue))
#5 / in /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php on line 27
```

### PR DESCRIPTION
**Pull request by enejb**
Fixes #9477 

#### Changes proposed in this Pull Request:

* use the previous version of the function if the current once doesn't exits.

#### Testing instructions:
*
Downgrade Jetpack to 6.0 use the cli command to update to the this version of Jetpack

### CODE REVIEW

**Comment by lezama** [comment]
should we require `functions.global.php` earlier instead? https://github.com/Automattic/jetpack/issues/9477#issuecomment-386990305

**Comment by zinigor** [comment]
We can both move the require statement higher, and additionally `require_once` it here just to make sure. Do we know why the code gets run before functions are required?

**Comment by enejb** [comment]
@zinigor what is going on is that the new file gets loaded but we are still using the old class.jetpack.php file. 

I would rather not require loading the sync files unless they are really needed. 

I think the above solution should work as expected.

**Comment by lezama** [comment]
> what is going on is that the new file gets loaded but we are still using the old class.jetpack.php file

I am not sure about this, how could it be possible?

**Comment by enejb** [comment]
We don't do any type of syncing and then on shutdown we tried to sync stuff but at that point we have all the new files. which now mean the new codec. 
How do you explain the fatal in the first place?

**Comment by lezama** [comment]
> How do you explain the fatal in the first place?

I don't explain it yet 😓 but I don't think it is possible to load some old and new files at the same time, it would fatal on a lot of installs.

maybe this has something to do? https://github.com/Automattic/jetpack/blame/master/functions.global.php#L15

**Pull request merged**
