### PR TITLE
Site Management Panel: Update Dev tools to match Overview tabs

### PR DESCRIPTION
**Pull request by eoigal**
Fixes https://github.com/Automattic/dotcom-forge/issues/7604

## Proposed changes:

* Updated 'Hosting Overview' button to just 'Overview'
* Updates dev tools links to match corresponding overview tabs on WPCOM 
* Added Staging Site link to correspond to Staging site tab
* Changed the order of the dev tool links to match the tabs

Current Dev Tools -> Site management overview tabs
- Hosting Config -> Server Settings
- Github Deployments -> Deployments
- Server Logs -> **Removed**
- Monitoring -> Monitoring
- PHP Logs -> Logs

Added
- Staging Site

## Before

Screenshot 2024-06-05 at 12 15 35

## After

Screenshot 2024-06-05 at 12 16 44

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Follow https://github.com/Automattic/jetpack/pull/37712#issuecomment-2149515951 to apply changes to your sites
* Go to /wp-admin/index.php
* Make sure you can see the “Site management panel” widget on the WP Dashboard
* Make sure all links work as expected

### CODE REVIEW

**Review by davemart-in — APPROVED** [review]
LGTM

**Comment by fushar** [comment]
Now that we have updated `Dev Tools` => `Hosting Settings` (https://github.com/Automattic/dotcom-forge/issues/7590), should we update the terminologies here, too?

- `or easily access your development tools` -> `or easily access your hosting settings` ?
- `DEV TOOLS:` -> I think we can just remove this line

What do you think?

**Review by fushar — COMMENTED** [review]
Now that we have updated `Dev Tools` => `Hosting Settings` (https://github.com/Automattic/dotcom-forge/issues/7590), should we update the terminologies here, too?

- `or easily access your development tools` -> `or easily access your hosting settings` ?
- `DEV TOOLS:` -> I think we can just remove this line

What do you think?

**Comment by davemart-in** [comment]
@fushar let's wait until we hear back from Daniel on this one: https://github.com/Automattic/dotcom-forge/issues/7590#issuecomment-2150313427 

I want to make sure we're 100% going a different direction before we make any more related changes.

**Pull request merged**
