### PR TITLE
Subscribe Widget: Set the placeholder ID based on widget ID.

### LINKED ISSUE #3166: Subscriptions Widget: 2nd instance of the widget fails to hide placeholder
The subscriptions widget [includes code](https://github.com/Automattic/jetpack/blob/3.8.1/modules/subscriptions.php#L882) to hide the label above the e-mail address input field (the same placeholder text is used in both places).

When two or more instances of the widget appear on the same page, the additional ones will not have their placeholders hidden.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #3166

There are some other elements that are IDs, which make the HTML with multiple subscribe widgets invalid which should be investigated too, but not needed for 3166.

### CODE REVIEW

**Comment by eliorivero** [comment]
@kraftbj I'm concerned that if someone targeted `#jetpack-subscribe-label` in their CSS rule, their style will be gone.
What do you think of a different approach replacing this line
```js
var label = d.getElementById( 'jetpack-subscribe-label' );
```
with
```js
var label = d.querySelector( 'label[for=subscribe-field-<?php echo $widget_id; ?>]' );
```
works back to IE 8.

**Comment by zinigor** [comment]
Although I think that having multiple elements on the page with the same id is wrong, I see what @eliorivero means here. And I would go with the approach that he proposes not to break existing stuff.

**Comment by samhotchkiss** [comment]
I agree with @eliorivero and @zinigor...

**Comment by kraftbj** [comment]
Reverted original, added @eliorivero's code, and rebased. I didn't test it specifically.

**Comment by zinigor** [comment]
Read, tested, added a minor change in the comments.

**Pull request merged**
