### PR TITLE
Translate Widget: display default title by default.

### PR DESCRIPTION
**Pull request by jeherve**
Until now, no title was displayed if you hadn't set a custom title.

#### Proposed changelog entry for your changes:

Translate Widget: display default title if no custom title was set.

### CODE REVIEW

**Comment by eliorivero** [comment]
This is not good. What if I don't want to set a title?

Also, I now noticed that this change you previously introduced
https://github.com/Automattic/jetpack/commit/2381fef792e558efd64377e5d7cd6401452a00ff#diff-5820ce995ecad3a08ccadc0b9b18e534R69
causes a `Notice: Undefined index: title in /.../wp-content/plugins/jetpack/modules/widgets/google-translate.php on line 69` in the Customizer.

**Comment by jeherve** [comment]
@eliorivero I couldn't reproduce that problem you were having when trying to clear the title. That seems to work for me too.

However, I could definitely reproduce that PHP notice. I believe db798b66dda79b4e766938e20c9ebd81ce03fca8 should take care of this.

**Comment by eliorivero** [comment]
Works fine! 🐑

**Comment by dereksmart** [comment]
4.5 in fbd4bdf 40fc60b

**Pull request merged**
