### PR TITLE
Admin Menu: change switch the site link URL to /sites

### LINKED ISSUE #66632: Sites Management Page: Browse Sites in wp-admin should link to SMP
`Browse Sites` in wp-admin view redirects to the empty page showing only the site switcher. The current context/page is not preserved after switching. We should point this to the SMP instead to surface the new and improved view for site selection.

Screenshot 2022-08-16 at 17 51 57

Done is:
- Browse Sites in wp-admin points to `wordpress.com/sites`(the URL we'll use once SMP is launched)

### PR DESCRIPTION
**Pull request by sejas**
Closes https://github.com/Automattic/wp-calypso/issues/66632

#### Changes proposed in this Pull Request:

* Change `< Browse Sites` link to `/sites` instead of `/home`

Screenshot 2022-08-16 at 17 51 57

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

**Jetpack Site**

* This change doesn't affect jetpack sites, because the `Browse Sites` button doesn't exist on those sites.

**Atomic Site**

* On an atomic dev site
* Install and activate [Jetpack beta](https://jetpack.com/download-jetpack-beta/)
* Go to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack`
* Click on `Search for a Feature Branch` and enter this branch name `update/switch-site-link-to-smp`
* Follow the tests described on **Observe the link has changed**

**Simple Site**

* Apply this diff D86095-code in your sandbox
* Sandbox a simple site
* go to `/wp-admin` on your simple site
* Follow the tests described on **Observe the link has changed**

**Observe the link has changed**

* After applying the steps described above.
* Go to `/wp-admin`
* Click on `Browse Site` on the admin menu
* Observe you have been redirected to `https://wordpress.com/sites` instead of `https://wordpress.com/home`

### CODE REVIEW

**Comment by zaguiini** [comment]
I tried testing this on a WoA site:

image

But it always redirects to `/home`:

image

Not sure what I'm doing wrong here 😢  It worked for simple sites ✅ 

>Change `< My Sites` link to `/sites` instead of `/home`

I think you meant "< Browse Sites" here, right?

**Review by vykes-mac — COMMENTED** [review]
Having the same issue mentioned by @zaguiini with jetpack connected sites. works for simple sites but still points to` /home` for jetpack sites.

**Comment by zaguiini** [comment]
I'm still getting `/home` on Jetpack sites, @sejas 😢 Maybe it did not update the changes?

EDIT: That's it.

image

I wonder how can I trigger a rebase?

**Comment by sejas** [comment]
I've added the change for atomic sites on https://github.com/Automattic/jetpack/pull/25689/commits/79693edc621a28d4ddca953e2e2a93e1cdd02e26

> I wonder how can I trigger a rebase?

@zaguiini I think the easiest way to test it on atomic is using atomic dev and applying the changes manually through ssh or sftp
https://github.com/Automattic/jetpack/pull/25689/files

**Review by zaguiini — DISMISSED** [review]
After your last push to this branch I saw the notice to update it:

image

And now this is working as expected. Great job 👍 

WoA:

image

Simple site:

image

**Comment by sejas** [comment]
@zaguiini @vykes-mac, now you can use [jetpack beta](https://jetpack.com/download-jetpack-beta/) on your atomic dev.
 I had to remove the folder/symlink jetpack in order to make the changes on this branch effective:
Screenshot 2022-08-22 at 18 45 44

**Review by vykes-mac — DISMISSED** [review]

**Review by sdixon194 — APPROVED** [review]

**Comment by sejas** [comment]
r251218-wpcom

**Pull request merged**
