### PR TITLE
Product views: update icons to use VaultPress & Akismet icons

### LINKED ISSUE #29045: Jetpack Admin Product views: update product icons in bundle pricing views
### What's happening?

All cards that show Backup + Anti-spam should use the newer (VaultPress and Akismet) logo icons:

Image

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #29045

## Proposed changes:

Let's move from the generic cloud and bug icons to VaultPress and Akismet icons.

image

image

- [ ] This may be the opportunity to change "Jetpack Backup" into "Jetpack VaultPress backup" on that screen. I think that's the name we go with these days?
- [ ] Still need to build a new "combined" icon as well:

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Start with a free site, connected to WordPress.com
* Go to `wp-admin/admin.php?page=jetpack#/product/akismet`
* Go to `wp-admin/admin.php?page=jetpack#/product/backup`
* Check that the icons look good.

### CODE REVIEW

**Comment by jeherve** [comment]
closing in favor of #29598.

**Comment by bluefuton** [comment]
@jeherve I'm happy if we reopen this one - I hadn't planned to include the icon changes in https://github.com/Automattic/jetpack/pull/29598 🙂

**Comment by bluefuton** [comment]
> Still need to build a new "combined" icon as well

@jeherve what's the usual process for merging these SVGs into one?

**Comment by jeherve** [comment]
> what's the usual process for merging these SVGs into one?

I don't know, some Figma magic? :) I [pinged Jetpack Design on the original issue](https://github.com/Automattic/jetpack/issues/29045#issuecomment-1437330555) for help.

**Comment by bluefuton** [comment]
I believe this is resolved and we're now using the correct icons - see https://github.com/Automattic/jetpack/issues/29045#issuecomment-1487637161.

**Pull request closed without merging**
