### PR TITLE
Remove the upgrade nudge for the Premium Block

### LINKED ISSUE #30349: Upgrade the Premium Content Nudge once D108873-code is merged
Since the block will be for free users. We no longer need a nudge for this block

preview-Screenshot_2023-04-27_at_14 56 59

Relates to: https://github.com/Automattic/gold/issues/11
Releates to: https://github.com/Automattic/wp-calypso/issues/76384

### PR DESCRIPTION
**Pull request by romarioraffington**
Relates to https://github.com/Automattic/gold/issues/11
Fixes https://github.com/Automattic/jetpack/issues/30349

## Proposed changes:

Removes the upgrade nudge for the Premium block

| Before  | After |
| ------------- | ------------- |
| Screenshot 2023-05-01 at 4 44 22 PM  | Screenshot 2023-05-01 at 4 43 54 PM  | 

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Add the Premium block to a site with a free plan
* Verify that the upgrade nudge is no longer present
* Open the post in an incognito window
* Checkout to ensure the block works as expected

### CODE REVIEW

**Review by n3f — DISMISSED** [review]
LGTM

**Review by jeherve — APPROVED** [review]

**Comment by romarioraffington** [comment]
Thanks for updating the the PR with [c68d4c5](https://github.com/Automattic/jetpack/pull/30398/commits/c68d4c5df5673df575973a929c44a78bf1e678a6) @jeherve . We want to make all earn products free for our users. I suspect we need to update the same files ( maybe in another PR ) for simple-payments, recurring payments and the donation block

**Comment by jeherve** [comment]
> We want to make all earn products free for our users. I suspect we need to update the same files ( maybe in another PR ) for simple-payments, recurring, payments and the donation block

Yeah, it would be best to do it in another PR I think. 👍

**Comment by romarioraffington** [comment]
> Yeah, it would be best to do it in another PR I think. 👍

Sounds good. PR: https://github.com/Automattic/jetpack/pull/30432

**Pull request merged**
