### PR TITLE
Upgrade Nudges: Fix in the full site editor

### LINKED ISSUE #19539: Site Editor Compatibility: Upgrade nudges don't redirect back to site editor
In the new site editor in Gutenberg (`/wp-admin/admin.php?page=gutenberg-edit-site`), the Upgrade nudges do not redirect back to the site-editor as a user might expect.

#### Steps to reproduce the issue

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. Insert a Payments block (or any other block requiring a plan upgrade) in the footer. You should see the Upgrade banner above the block.
3. Click the Upgrade CTA to go to the checkout screen
4. Complete checkout to upgrade to a premium plan

#### What I expected
After successful upgrade , I would expect to be redirected back to the site-editor, and my changes should have been saved (ie the Payments block should still be in the footer, now without an upgrade nudge)

#### What happened instead
After upgrading I was redirected to the `https://wordpress.com/edit/stacifakefsesite.wordpress.com?plan_upgraded=1` URL with the screen showing all of my available sites to edit. When I re-entered the site editor, my changes had not been saved (the Payments block was no longer in the footer).

**Screenshots**

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/jetpack/issues/19539

#### Changes proposed in this Pull Request:

* Make sure plan upgrade nudges work and redirect back to the correct location in the site editor.

Screen Shot 2021-04-28 at 10 56 23 AM

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Sync this branch to your sandbox on a site with a free plan.
* Open the site editor and insert a premium block.
* Make some edits to different template parts, insert a few other blocks. Make a note of the changes you made.
* Select the premium block, and hit the "Upgrade" button.
* Confirm that the "Save" button changes to a saving state, before you are redirected to a checkout page.
* Complete the checkout and confirm you are returned to the site editor in the same state.
* Confirm that all of your changes before you were redirected to checkout are still present.
* Open the post editor and confirm that the upgrade flow still works correctly here.

Note: In the site editor you will not get a notice that you have successfully purchased a plan on redirect. The site editor does not currently support the top notices. Support will be added via https://github.com/WordPress/gutenberg/pull/31303

### CODE REVIEW

**Review by stacimc — DISMISSED** [review]
This looks good to me! I tested:

- [x] Premium block is autosaved before redirecting
- [x] Changes to other template parts are also saved before redirecting
- [x] Upgrade flow redirects back to the correct template within the site-editor, for example back to the 404 page
- [x] Save button visually reflects that the post is being saved
- [x] Upgrade flow still works correctly from the block editor (redirect & autosave)

I agree about the missing notification that the plan has been added for future work.

**Review by andrewserong — DISMISSED** [review]
This is testing nicely for me, too! (Tested from wordpress.com/site-editor as well as from wp-admin, and the dirty entities were saved before redirecting, and after upgrading I was redirected to the site editor).

In the back of my mind, I'm wondering if the return URL for the site editor might change when FSE eventually lands in core? At the moment we return to `admin.php` with the query param of `page` set to `gutenberg-edit-site`. Hopefully when we get closer to that stage, we'll be able to safely migrate the redirect over to its eventual permalink? I don't think there's anything for us to do right now though, so just a thought 🙂

**Review by jeherve — DISMISSED** [review]
This seems to test well for me on WordPress.com. 🚢

**Comment by apeatling** [comment]
> Hopefully when we get closer to that stage, we'll be able to safely migrate the redirect over to its eventual permalink? I don't think there's anything for us to do right now though, so just a thought 🙂

Yes agreed, changing the URL is very simple, we just need to remember to do it.

**Comment by apeatling** [comment]
Rebased

**Review by stacimc — APPROVED** [review]

**Comment by apeatling** [comment]
@jeherve Thanks, I'll need another approval here after the rebase. :+1:

**Review by sdixon194 — APPROVED** [review]

**Pull request merged**
