### PR TITLE
CSS Editor: add support for `align-items` and `justify-content` CSS3 properties.

### PR DESCRIPTION
**Pull request by lancewillett**
See #1534.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Looks good to me...

**Comment by dereksmart** [comment]
Tested, tried and true. :shipit:

**Comment by jeherve** [comment]
@lancewillett Will that also help for the other related CSS properties mentioned in #1534?

**Comment by samhotchkiss** [comment]
Yes, this fixes #1534

**Pull request merged**
