### PR TITLE
Social Media Icons Widget: add new parameters

### PR DESCRIPTION
**Pull request by bradleymoore111**
Added icon size and icon color to the links.
Added capability to open social links in a new tab rather than the main window.

### CODE REVIEW

**Comment by jeherve** [comment]
Fixes #7601

**Comment by jeherve** [comment]
Noting that this might become moot if #7454 is merged. It might be best to add those features to the new version of the widget instead.

**Comment by bradleymoore111** [comment]
I accidentally broke the pull request. Gonna create a new one, will retag and all.

**Comment by oskosk** [comment]
Alright, thank you! For the next time. Rebasing a branch is usually a sequence of these commands

```

$ git remote add upstream https://github.com/Automattic/jetpack.git #you need to do this only once
$ git checkout social-icons-features
$ git rebase upstream/master
```

That should do it as there were no conflicts. In this case of this PR, there were no conflicts, but tests were failing for old test-setup code present in this branch of your fork...

**Comment by bradleymoore111** [comment]
Ah, noted. I thought I did something similar to that, but I must have made a mistake. Thanks!

**Pull request closed without merging**
