### PR TITLE
Social Menu: Syncing changes from WordPress.com to Jetpack

### PR DESCRIPTION
**Pull request by coder-karen**
#### Changes proposed in this Pull Request:

* This PR is the first part in de-fusioning Social Menus: https://github.com/Automattic/jetpack/issues/25234
* In this PR, changes that exist in the WordPress.com versions of the files are added to the Jetpack file versions.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* To test, add the Twenty Twenty theme to a Jetpack-connected site and in the `functions.php` file (or via a code snippets plugin) add the following: `add_theme_support( 'jetpack-social-menu', 'svg' );`. This is to make sure we test the `icon-functions.php` file as well.
* Make sure to add a social menu via `wp-admin/nav-menus.php`.
* The icons should display as expected without any errors.

~As a general note, I haven't had any luck in getting `has_nav_menu('jetpack-social-menu'))` to return true, even if a jetpack-social-menu is set. These calls existed before (in `icon-functions.php` and `social-menu.php`) - so not related to this PR.  Everything appears to work fine, but that makes me a little uneasy about the existing code.~ (solved below)

### CODE REVIEW

**Review by samiff — APPROVED** [review]
> I haven't had any luck in getting has_nav_menu('jetpack-social-menu') to return true, even if a jetpack-social-menu is set.

After adding the theme support, the `! has_nav_menu( 'jetpack-social-menu' )` line seems to be working well for me, unless you meant something else? The PR changes seem to make sense 👍

**Comment by coder-karen** [comment]
Thanks @samiff 

> After adding the theme support, the ! has_nav_menu( 'jetpack-social-menu' ) line seems to be working well for me

For me in testing that line always seems to return true. Removing the 'not' operator to test whether `has_nav_menu( 'jetpack-social-menu' )` returns true didn't seem to work for me (adding in an error log for example, assuming the menu had been added). I suspect `! has_nav_menu( 'jetpack-social-menu' )` shouldn't be returning true for me though - I must be doing something wrong in adding theme support. Out of curiosity how did you add that?

While I can add the social menus on a Jetpack site, in comparison to a WordPress.com site (testing with a legacy theme that has this enabled), there are nav classes missing that should be there (eg. I expect I should be seeing `<nav class="jetpack-social-navigation jetpack-social-navigation-svg"...`).

**Comment by samiff** [comment]
> For me in testing that line always seems to return true.

On local dev, I'm using Twenty Twenty and have added the `add_theme_support`. When I turn on the "Social Menu" location for a menu, then I'm able to see the `! has_nav_menu` skipped. And when I unset the "Social Menu" location, then I hit that `! has_nav_menu` portion.

> in comparison to a WordPress.com site (testing with a legacy theme that has this enabled), there are nav classes missing that should be there

I didn't have a look at a wpcom site, is that the case even without any of your defusion changes? 

Edit: left this on hold in case you want another look at it.

**Comment by coder-karen** [comment]
@samiff Thanks for following up - I figured it out and it seems I was picking the wrong Social Menu (as Twenty Twenty includes one by default), so after picking the correct one (with SVG support), as well as outputting the menu with `<?php if ( function_exists( 'jetpack_social_menu' ) ) jetpack_social_menu(); ?>` added to the footer, I could test properly.

That also solved the second issue as well - the HTML output is now what I'd expect to see. Whew, thanks for bearing with me here. All good to go now.

**Pull request merged**
