### PR TITLE
My Jetpack: Fix button to add bundle in product interstitial component

### LINKED ISSUE #28983: My Jetpack: Add Security button in product interstitial is not working
Clicking on `Add Security` does not work. The `onClick` prop is absent.

Image

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #28983

This was observed in https://github.com/Automattic/jetpack/pull/27615/#issuecomment-1333582689 which we didn't tackle before merging. cc @renatoagds 

## Proposed changes:

* Fixes the button to add a bundle in the product interstitial page by adding an `onClick` prop

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1676485057759749-slack-C02TQF5VAJD

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Go to the product interstitial page for `Scan` (`wp-admin/admin.php?page=my-jetpack#/add-scan`)
* Click on `Add Jetpack Scan`
* Check that you are redirected to the checkout page of the `Jetpack Scan Daily` plan
* Remove the plan from the cart and go back to the previous page
* Click on `Add Security`

* Check that you are redirected to the checkout page of the `Jetpack Security (10GB)` plan
 * Go to the product interstitial page for `Anti-Spam` (`wp-admin/admin.php?page=my-jetpack#/add-anti-spam`)
* Click on `Add Jetpack Anti-Spam`
* Check that you are redirected to the Akismet connectioni page
*  Go back to the product interstitial page for `Anti-Spam` (`wp-admin/admin.php?page=my-jetpack#/add-anti-spam`)
* Click on `Add Security` 
  image
* Check that you are redirected to the checkout page of the `Jetpack Security (10GB)` plan

### CODE REVIEW

**Comment by lhkowalski** [comment]
Confirmed that the button now leads to the checkout page with the right product:

Screen Shot 2023-02-15 at 17 26 04

**Review by lhkowalski — DISMISSED** [review]
Code change looks good. As a follow up, we may want to fix the spinner on the button.

**Comment by dhasilva** [comment]
Working with Scan, but not working with Akismet for now.

**Comment by oskosk** [comment]
Pushed three commits:

589ef81ca1e256fa7dc8043d1cae36a5558faae3 Addresses a problem that was there unrelated to this issue, but shooting an annyoing warning in the console
Screenshot 2023-02-15 at 18 20 57

0a4da064aadb3d118d6daa984aeb182d3831c713 updating a bit of code pushed in 217224890f80b14026c62d9e91a098c7ac3a6620

3c46e4001d3fe84aa01ef181f6d127cea1692149 which is the definitive fix for this issue.

**Review by nunyvega — APPROVED** [review]
Tests well also in anti-spam 🚢

**Pull request merged**
