### PR TITLE
Settings UI: Add VideoPress settings card

### PR DESCRIPTION
**Pull request by dereksmart**
Adds a settings card in /writing in the media section to allow toggling of VideoPress.  

Will only show if on premium or business plan.  Otherwise, you should see a banner CTA.  

screen shot 2017-03-14 at 5 26 36 pm

screen shot 2017-03-14 at 5 26 14 pm

### CODE REVIEW

**Comment by rickybanister** [comment]
Looks good—the only thing I notice is that the left-hand border of the upgrade banner does not match the plan icon color.

**Comment by dereksmart** [comment]
@rickybanister good eye -- @zinigor can you check that out when you go ham on the banners tomorrow?

**Comment by richardmuscat** [comment]
quick Q for @dereksmart or @MichaelArestad -- shouldn't videopress be turned on by default if you're on a plan that supports it?

additionally, can we make it say "Fast, ad-free video hosting" instead of "Powerful, simple..."

**Comment by dereksmart** [comment]
@richardmuscat When we last talked about this, it would be handled (activated) from the Calypso side after purchasing a plan during the `set up` step.

**Comment by eliorivero** [comment]
Looks good. My only concern is that the video banner shows up when the app is loading and then changes to VideoPress toggle. Maybe it can be done so that it doesn't show anything while it's loading, and once the plan data has been fetch, show either the banner or the toggle?

**Comment by dereksmart** [comment]
> the video banner shows up when the app is loading and then changes to VideoPress toggle

This happens for all banners currently.  I think that is part of the clean up @zinigor is handling tomorrow

**Comment by dereksmart** [comment]
@richardmuscat updated the copy 

screen shot 2017-03-14 at 6 10 45 pm

**Comment by zinigor** [comment]
Looks good, I'll merge this to be able to work on this for the banner update PR.

**Pull request merged**
