### PR TITLE
Boost: Dismiss the admin notice when the plugin is deactivated

### PR DESCRIPTION
**Pull request by pyronaur**
#### Changes proposed in this Pull Request:

Fixes e2e test error introduced in #25980

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Apply the patch, change the theme, make sure the regeneration notice appears and dismiss it.

### CODE REVIEW

**Review by thingalon — DISMISSED** [review]
🚢

**Comment by oskosk** [comment]
Pushed a14c2b3ed66988fcfafd217ee00aa869349c848c with changelog

**Comment by oskosk** [comment]
Folks from Jetpack Quality are checking the e2e runs here cause they fail up here, but don't fail locally

**Comment by adimoldovan** [comment]
The e2e test failures look legit to me. 

- `Critical CSS Admin message should show when the theme is changed`
The action required notice is not displayed after the theme is activated, as expected. (It is displayed if the page is reloaded - but I guess this is not an expected step).

- `User can access the Critical advanced recommendations and go back to settings page`
This test fails because the first one fails. I recommend also fixing this. Tests should not depend on one another.

**Review by thingalon — APPROVED** [review]
Ok, let's get the fix out.

**Pull request merged**
