### PR TITLE
actions: Test upgrading of built plugins

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

After several problems with plugin upgrades failing since #23039, we
need a more robust CI test for plugin upgrades failing.

For each plugin built, this will test upgrading via the web UI and
wp-cli, from the latest stable (if any) and from the built version to a
hypothetical future version.

#### Jetpack product discussion

p9dueE-4Bm-p2
Related to p9dueE-4zF-p2 

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Are the existing Build jobs happy?
* Is the new job happy too?
* Submit a PR based on this one that reverts #23253 or #23246 or #23207. Does the new job fail on it with a reasonable message?
  * :heavy_check_mark: https://github.com/Automattic/jetpack/actions/runs/1947464089
* Submit a PR based on this one that doesn't build any plugins. Make sure the workflow works right.
  * :heavy_check_mark: https://github.com/Automattic/jetpack/actions/runs/1947473452

### CODE REVIEW

**Comment by anomiex** [comment]
Todo yet:

* [ ] Add master→PR upgrades as well
* [ ] Connect Jetpack before the upgrades to better catch things like Sync syncing post-upgrade.

**Comment by anomiex** [comment]
I had no luck figuring out the connection. The partner provision script used in the E2E tests failed with "transport error - HTTP status code was not 200 (400)", probably because I didn't have a real URL to pass it. Tried using the E2E tunneling script, but the tunnel didn't seem to work (at least not when I tried starting it from inside a local docker instance).

@adimoldovan Any ideas? Or should we leave that part aside for now?

**Comment by adimoldovan** [comment]
> I had no luck figuring out the connection. The partner provision script used in the E2E tests failed with "transport error - HTTP status code was not 200 (400)", probably because I didn't have a real URL to pass it. Tried using the E2E tunneling script, but the tunnel didn't seem to work (at least not when I tried starting it from inside a local docker instance).
> 
> @adimoldovan Any ideas? Or should we leave that part aside for now?

I played a bit with the script myself and I had the same results without a valid URL. Adding the tunnel would complicate the setup quite a bit.
I think it makes sense to leave this part for now, and address it in a follow-up.

**Comment by adimoldovan** [comment]
I think it would be nice to have it as a job in the tests workflow, but it would probably complicate things too much.

**Comment by anomiex** [comment]
> I think it would be nice to have it as a job in the tests workflow, but it would probably complicate things too much.

It would be nice, but as far as I know there's no way to really have cross-workflow dependencies. So we'd either have to use `workflow_run` (which then won't show up in the checks list, the workflow would have to set a check via the API), or `workflow_dispatch` (same), or have a polling loop inside the job waiting for the artifact to be created (uses extra API calls).

**Review by adimoldovan — APPROVED** [review]
This looks good to me and the tests are successful.

**Pull request merged**
