### PR TITLE
Add `featured_image_email_enabled` option to the site settings endpoint

### PR DESCRIPTION
**Pull request by ivan-ottinger**
#### Changes proposed in this Pull Request:

The proposed changes add `featured_image_email_enabled` option to the site settings endpoint. The new option is necessary in order to save the state whether the Featured image should or shouldn't be displayed in the _New Post_ email template.

Project thread: pdDOJh-Nu-p2

This PR doesn't introduce any visible / functional changes. Instead, this PR is a prerequisite for the upcoming changes that will utilize the newly-added site option/setting:

- https://github.com/Automattic/wp-calypso/pull/68745 (in development, not ready for review yet)
- D88807-code (in development, not ready for review yet)

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

Project thread: pdDOJh-Nu-p2

#### Does this pull request change what data or activity we track or use?

No, it does not.

#### Testing instructions:

The PR doesn't introduce any visible/functional changes. We can review the code and make sure the are no regressions.

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
Discussing the failed tests in p1665390129292649-slack-CBG1CP4EN.

**Review by TimBroddin — DISMISSED** [review]
This looks ok to me!

**Comment by ivan-ottinger** [comment]
Alright, I have merged https://github.com/Automattic/jetpack/pull/26747 but now there are these two conflicts above. I will fix them on Monday.

**Review by samiff — APPROVED** [review]

**Comment by ivan-ottinger** [comment]
I have deployed the patch to WPCOM now. Changeset ID: r254584-wpcom.

**Pull request merged**
