### PR TITLE
Boost: Remove global state from Pagination component

### PR DESCRIPTION
**Pull request by dilirity**
## Proposed changes:

* Moves global state to parent component in favor of props;
* Update next/previous buttons to use a separate component.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-286-p2

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Make sure ISA Pagination is working as expected.
CleanShot 2023-09-18 at 16 56 59

### CODE REVIEW

**Review by pyronaur — DISMISSED** [review]
Clicking left and right arrows no longer works because the connection to `current` reactivity is now lost.

**Comment by pyronaur** [comment]
To fix that, I think `<button>` needs to become a `<Link>` instead and link to the relevant page.

**Comment by dilirity** [comment]
@pyronaur great catch - thanks!

I've updated the buttons to use the Link component.

~~I've also updated their behavior - they'll hide when necessary, instead of always showing. I kind of felt it didn't make sense to show them and disable them, as they are very tiny.~~

**Review by pyronaur — DISMISSED** [review]
Looks like this might work. Although you could use `slot` instead of `if right` check, removing a condition - would make the component a bit simpler imho.

But it's fine if you prefer to keep it this way.

**Comment by dilirity** [comment]
Thanks for the suggestion @pyronaur! I've updated the pagination arrow component to use slots in 02584d3.

**Review by pyronaur — COMMENTED** [review]
Looks good! :shipit:

**Review by pyronaur — APPROVED** [review]

**Pull request merged**
