### PR TITLE
Moving logo readme file to the package root

### PR DESCRIPTION
**Pull request by aldavigdis**
Just a simple fix to move the readme file for the logo package from `./src` to the package root.

### CODE REVIEW

**Review by tyxla — CHANGES_REQUESTED** [review]
This seems to be removing the file instead of moving it?

**Comment by aldavigdis** [comment]
Just noticed. I'm sorry.

**Review by tyxla — APPROVED** [review]
LGTM, thank you 🚢

**Comment by aldavigdis** [comment]
Just rebased fixed the error. Sorry about the silliness.

**Comment by tyxla** [comment]
Yeah, feel free to ship after this gets approval from @Automattic/jetpack-crew

**Review by brbrr — APPROVED** [review]
Looks good

**Pull request merged**
