### PR TITLE
Add workaround for subscriptions widget form submission failure in AMP pages

### LINKED ISSUE #11595: Subscriptions Widget Broken Under AMP with Native Template Mode
When using AMP 1.0.2 and Jetpack 7.1.1 under WordPress 5.1.1, the Subscribe button in the Subscriptions widget does not function while under AMP's Native template mode.

To reproduce the issue, simply add the "Blog Subscriptions (Jetpack)" widget to your site, make sure that AMP is running under the Native template mode, and attempt to subscribe. You will notice that clicking the Subscribe button does nothing, and the following errors appear in the Console:

`Response must contain the AMP-Access-Control-Allow-Source-Origin header: template-impl.js:227:8`

`Jf template-impl.js:227`
`<anonymous> viewport-impl.js:1126`
`assert log.js:349`
`y log.js:762`
`Wg action-impl.js:716`

`Form submission failed: Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header​​​: log.js:187:6`

`Ha log.js:187`
`Da log.js:242`
`error log.js:257`
`xc amp-form.js:885 `

The Subscribe button works perfectly under the Paired and Classic template modes, only the Native mode is affected.

Reported at https://wordpress.org/support/topic/jetpack-subscribe-button-stopped-working/

(Apologies if this should have gone under #9730 I didn't see it listed there and am not 100% sure on the protocol.)

### PR DESCRIPTION
**Pull request by westonruter**
It was [discovered](https://wordpress.org/support/topic/amp-jetpack-subscribe-button-stopped-working/) that the subscription widget form submission fails on AMP pages. At issue is AMP form submissions appear to not include a field for the named button that sent the form. This field is used to initiate the subscription flow:

https://github.com/Automattic/jetpack/blob/e3986c699471dbb1dab42bdeac2041b8c979514c/modules/subscriptions.php#L84

Because this field is not included in the submission, the result is what appears to be a reload of the page.

For more information about the issue, see https://github.com/ampproject/amphtml/issues/21498 which I've reported as an apparent bug in the `amp-form` component.

See also this workaround plugin: https://gist.github.com/westonruter/3b61ffcfbc1b528b1135ac7cc065eaa2

Note: This workaround plugin also shows how the subscription widget UX could be greatly improved on AMP pages by not requiring a full page reload to submit the form. The form can instead be submitted via Ajax and the success/error message can instead be shown right in the existing form. The `AMP_Jetpack_Subscriptions_Form_Response_Container_Injector` in this plugin is a hack to inject the `div[submit-error]` and `div[submit-success]` elements into the `form`; this wouldn't be needed if the widget itself output the required elements. Also, the success/error messages could be refactored into a common helper method for use in Ajax responses as well as full page responses.

See #9730.
Fixes #11595.

#### Changes proposed in this Pull Request:

* Add a hidden `jetpack_subscriptions_widget` field to the subscriptions form in AMP pages to ensure the subscription flow is initiated.

#### Testing instructions:

* Active the AMP plugin and enable Paired mode.
* Add a Subscriptions widget to the sidebar.
* Navigate to an AMP page that has the subscriptions widget on it.
* Attempt to subscribe.

#### Proposed changelog entry for your changes:

* Fix subscriptions widget form submissions on AMP pages.

### CODE REVIEW

**Comment by jeherve** [comment]
I can't seem to get this to appear for some reason.

Should this work on any page of the site in Paired mode, as long as I am on the AMP view?

**Comment by westonruter** [comment]
> I can't seem to get this to appear for some reason.

You can't get the widget to appear? It doesn't render in dev mode.

**Comment by jeherve** [comment]
The widget does appear, but I can’t seem to get the invisible additional field to appear

**Comment by westonruter** [comment]
And you're looking at an AMP page? 

In any case, the issue in AMP is actively being fixed: https://github.com/ampproject/amphtml/pull/21518

So I'm sure it will be rolled out before this workaround in Jetpack, so I don't think this PR is necessary.

A separate PR to improve the UX of submitting the form would be nice.

**Comment by westonruter** [comment]
And fix has been merged into AMP: https://github.com/ampproject/amphtml/pull/21518

Should be rolled out to every AMP page in 1-2 weeks.

**Pull request closed without merging**
