### PR TITLE
Build: update to a node version matching Calypso

### LINKED ISSUE #14270: Build: update Node version
Calypso has been upgraded to the new LTS, moving from version 10 (Dubnium) to 12 (Erbium).

Let's aim to do the same for Jetpack, so when one develops in both environments they don't have to constantly switch from one version to the other with nvm.

Internal reference: p4TIVU-9jL-p2

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #14270

#### Changes proposed in this Pull Request:

* Update to a node version matching Calypso, so switching between one and the other doesn't require changing node version every time.

#### Testing instructions:

For the JP dashboard, the blocks, Instant Search:

* Does it build?
* Does it work well?
* Do the tests pass?

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by zinigor** [comment]
There's a problem with this one: the beta builder doesn't support Node 12 yet, and judging by pMz3w-aTS-p2, the problem is not likely to be resolved soon. Let's remove this from the milestone and get back to it in January?

**Comment by kraftbj** [comment]
Now they we don't build on the beta builder anymore, time to revisit?

**Comment by jeherve** [comment]
> Now that we don't build on the beta builder anymore, time to revisit?

@zinigor Would we be okay merging this?

**Review by zinigor — APPROVED** [review]
Since we're not using our custom builder anymore, let's merge this!

**Comment by jeherve** [comment]
r213518-wpcom

**Pull request merged**
