### PR TITLE
Debugger: Set default theme to Twenty Sixteen

### PR DESCRIPTION
**Pull request by kraftbj**
Hold for 4.4 release (scheduled for December 8).

### CODE REVIEW

**Comment by kraftbj** [comment]
Sidenote: I'd like a better way to automate this process or make it harder to forget. I'm trying to think through ideas... unit test that somehow checks for the latest theme and compares...

**Comment by jeherve** [comment]
Looks good to me!

**Comment by lezama** [comment]
:+1:

**Comment by kraftbj** [comment]
For me to play with between now and then, `WP_DEFAULT_THEME` is a constant in WP that has the slug of the default. Probably could figure out something here.

```
if ( WP_DEFAULT_THEME = 'twentyfifteen' ) $theme = "Twenty Fifteen";
``` etc

**Comment by zinigor** [comment]
Thanks for a good suggestion, @kraftbj ! I have implemented the dynamic name using `wp_get_theme`. It would be better to do it with `WP_Theme::get_core_default_theme`, but it's not yet available in all WP versions we support.

**Pull request merged**
