### PR TITLE
(wip) Extensions: organize blocks adding new categories

### LINKED ISSUE #14598: (3P) Update block categorization in CoBlocks
As a writer, I'd like blocks to be categorized appropriately, so they are easier for me to find.

#### Acceptance Criteria:
- [ ] Blocks make use of four new categories: Blog, Earn, Marketing, and Social.
- [ ] Blocks are part of the assigned category.
- [ ] Blocks are not within a "collection" category (meaning "Jetpack" or "Coblocks").

#### Resources:
* [Spreadsheet with Blocks and their new categories](https://docs.google.com/spreadsheets/d/1Oua0oDUhGJJtabatoBS3XBzZ6K3oUiB5-kSdWl00M-I/edit#gid=0).

#### Implementation Notes

- [ ] Confirm it's ok to register the same Category twice without causing an error. This is in case Core creates a new Category with the same as ours. (Also can we check for cat exists before creating?).

#### How to Demo:
* In the block selector, identify two or three blocks that found their new home in a core-registered or custom category.
* Show how blocks not make use of "collection" categories anymore.

More discussion: p58i-8yl-p2.

### PR DESCRIPTION
**Pull request by retrofox**
Fixes #14598

#### Changes proposed in this Pull Request:

This PR reorganizes the block categories, adding/removing them.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Basically it changes the category for all blocks, but it doesn't affect the functionality of the blocks.

#### Testing instructions:

* Apply these changes
* Add/edit a post/page

You should be able to blocks organized by categories, according to the table described above.

image

### CODE REVIEW

**Comment by ockham** [comment]
Please consider registering a new Jetpack _collection_ to hold these blocks -- see https://github.com/WordPress/gutenberg/pull/17609 :slightly_smiling_face:

**Comment by retrofox** [comment]
> Please consider registering a new Jetpack _collection_ to hold these blocks -- see [WordPress/gutenberg#17609](https://github.com/WordPress/gutenberg/pull/17609) 🙂

👍 Thanks for the advice and reference.

**Comment by simison** [comment]
Let's rather rebase and update https://github.com/Automattic/jetpack/pull/14454

**Comment by kraftbj** [comment]
Related: #14598 for using block collections (shipping in WP 5.4, coming out soon).

**Comment by kraftbj** [comment]
Noting for the Jetpack collection, that is WordPress 5.4+, which is about to hit RC1. If we'll want to decide how we want to fallback for WP 5.3 (keep them all in a Jetpack category, use the new ones and lose the "Jetpack" category).

**Pull request closed without merging**
