### PR TITLE
Nav Unification: Support absolute URLs in upsell nudges

### PR DESCRIPTION
**Pull request by mmtr**
Helps fixing https://github.com/Automattic/wp-calypso/issues/57498.

#### Changes proposed in this Pull Request:
The Nav Unification logic was previously assuming that all the upsell nudges links were pointing to Calypso and that the `wordpress.com` domain was missing.

However, there are some upsell nudges that point to WP Admin where the appropriate domain is already part of the URL.

On this PR, we check that the upsell nudge link doesn't include a domain (and thus should point to Calypso) before completing it with `wordpress.com`.

#### Jetpack product discussion
N/A.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Install Jetpack Beta on an WoA dev site and switch to the branch of this PR.
- In your WP.com sandbox, re-enable the Crowdsignal JITM:
  - Revert D69407-code.
  - Adjust the dates set with `within_date_range` to include the current date.
  - If the plan is not newer than 30 days, comment out the `with_plan_newer_than` line.
- Allow incoming HTTP connections in your sandbox: `sudo global-http enable`.
- Connect your WoA dev site to your WP.com sandbox by adding this code to the `wp-config.php` file: `define( 'JETPACK__SANDBOX_DOMAIN', '<YOUR_SANDBOX_DOMAIN>.wordpress.com' )`.
- Activate the Crowdsignal plugin on your WoA Atomic site.
- Go to a WP Admin page.
- The Crowdsignal JITM should show up in the sidebar.
- Make sure the CTA button points to the correct WP Admin page.
- Make sure that other JITMs still point to Calypso correctly.

### CODE REVIEW

**Review by dsas — APPROVED** [review]
Works well for me

**Review by jeherve — APPROVED** [review]

**Comment by mmtr** [comment]
Seems the changelogger validity failures are unrelated to this PR:

```
Error: Version mismatch, expected 10.4-a.10 but found 10.4-a.9!
You might use `tools/project-version.sh -f -u 10.4-a.10 plugins/jetpack` or `tools/fixup-project-versions.sh` to fix this.
---
Checking version in composer.json, if any
Ok, no version found to check
Checking version in package.json, if any
---
Error: Version mismatch, expected 10.4.0-a.10 but found 10.4.0-a.9!
You might use `tools/project-version.sh -f -u 10.4-a.10 plugins/jetpack` or `tools/fixup-project-versions.sh` to fix this.
---
Checking branch-alias version, if any
Ok, no version found to check
Checking autoloader-suffix version, if any
---
Error: Version mismatch, expected f11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_4_a_10 but found f11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_4_a_9!
You might use `tools/project-version.sh -f -u 10.4-a.10 plugins/jetpack` or `tools/fixup-project-versions.sh` to fix this.
---
Checking version constant JETPACK__VERSION in jetpack.php
---
Error: Version mismatch, expected 10.4-a.10 but found 10.4-a.9!
You might use `tools/project-version.sh -f -u 10.4-a.10 plugins/jetpack` or `tools/fixup-project-versions.sh` to fix this.
```

@jeherve Is there any way to get rid of them? Tried merging with latest `origin/master` but no luck.

**Comment by jeherve** [comment]
@mmtr Sorry, we just happen to be in the middle of pushing a new release! If you merge master once again, you should be all good.

**Comment by mmtr** [comment]
Deployed to WP.com in r235503-wpcom.

**Pull request merged**
