### PR TITLE
Jetpack Search: Add Marketplace meta fields and taxonomies to allowed list

### PR DESCRIPTION
**Pull request by gcsecsey**
Related to https://github.com/Automattic/wp-calypso/issues/63903

#### Changes proposed in this Pull Request:

* Update the allow list to include Marketplace related custom meta fields and taxonomies
 
#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pdh6GB-Ax-p2#comment-2104

#### Does this pull request change what data or activity we track or use?

Yes, additional data will be synced from some sites.

#### Testing instructions:

* Based on pdh6GB-Ax-p2#comment-2503, changes can be tested only after deployment by running a full sync

### CODE REVIEW

**Review by zinigor — DISMISSED** [review]
This looks like what @gibrown  has mentioned in the other discussion we've had, looks good to me!

**Comment by cpapazoglou** [comment]
@zinigor could we cherry pick this in the current release?

**Comment by cpapazoglou** [comment]
Can we also add `_wc_general_product_dependency_theme` and `_wc_general_product_dependency_plugin` meta fields?

**Comment by BogdanUngureanu** [comment]
Hey! Is there a reason why we haven't added these fields on the WooCommerce side? I've noticed that there are some filters that might allow that (I think it's called jetpack_sync_post_meta_whitelist).

I might be wrong though, but if that's the case, I think having Marketplace specific fields shouldn't be present in the generic implementation (Jetpack Search).

**Comment by gcsecsey** [comment]
> Hey! Is there a reason why we haven't added these fields on the WooCommerce side? I've noticed that there are some filters that might allow that (I think it's called jetpack_sync_post_meta_whitelist).

@BogdanUngureanu We'd primarily need the meta fields to be indeed, and it may not be sufficient to add them to the `jetpack_sync_post_meta_whitelist`. I've created the PRs based on these two comments: pdh6GB-Ax-p2#comment-2503 pdh6GB-Ax-p2#comment-2504

> I might be wrong though, but if that's the case, I think having Marketplace specific fields shouldn't be present in the generic implementation (Jetpack Search).

I agree that we should try to avoid adding these to the general implementation if possible. Is there perhaps an easy way to test whether updating the allowlist solves the issue for these fields?

**Comment by BogdanUngureanu** [comment]
I haven't worked at all on the WooCommerce.com/Jetpack sync projects at all, so you have more experience than me, haha. 

I was planning to install the WooCommerce environment locally and to try to connect it to wp.com as a normal Jetpack site, so that it'll create a shadow site. But, at this point, it's just an idea I'm having, so I'm not sure it's possible or not, or if there any side effects to it.

**Comment by gibrown** [comment]
@BogdanUngureanu adding them on the wc.com site won't be enough because we also have to make sure the fields get indexed. This sync code gets deployed both in Jetpack and on wp.com where we use it to control what we index.

**Comment by zinigor** [comment]
> I was planning to install the WooCommerce environment locally and to try to connect it to wp.com as a normal Jetpack site, so that it'll create a shadow site. But, at this point, it's just an idea I'm having, so I'm not sure it's possible or not, or if there any side effects to it.

Just to expand on what @gibrown said before I would like to add that when we figure out the needed fields, it's possible to make it work before the actual Jetpack release that's going to happen on the second week of September.

To do this we will have to:

- deploy the corresponding change to WordPress.com
- deploy an alpha version of Jetpack to WooCommerce.com containing this change.

**Comment by cpapazoglou** [comment]
@zinigor a rebase here would be enough for merging?

**Comment by epeicher** [comment]
I have rebased with trunk and fixed the merge conflict updating the version to [1.38.1-alpha](https://github.com/Automattic/jetpack/pull/25376/files#diff-8cbe6de8fca27651a9743f3cfb6ad21f466db46d01fb42f0637e13216e0e1373R15).
I have cross-checked that the [added fields](https://github.com/Automattic/jetpack/pull/25376/commits/7e103824b2bcf7df65589c1b3f107a4513e737df) exist in WC.com and I have accepted the related diff D85227-code so this PR could be progressed, sending a re-request to @zinigor 🙂

**Review by zinigor — APPROVED** [review]
While it's unfortunate that the spacing had to change, the addition looks good to me!

**Comment by cpapazoglou** [comment]
> deploy an alpha version of Jetpack to WooCommerce.com containing this change.

@zinigor is this something you can handle? WP.com diff is deployed D85227-code

**Pull request merged**
