### PR TITLE
Site Migrations: Add tracks events for AIOWPM start, end, and error events; include blog ID in Tracks events

### PR DESCRIPTION
**Pull request by zinigor**
Related to https://github.com/Automattic/dotcom-forge/issues/7645

## Proposed Changes

* Add Tracks events for the AIOWPM plugin in the site migrations helper functions.
* Ensure we include the blog ID when we're recording tracks events via Jetpack.
* These Tracks events will give us some sense of how many migrations are started, finished, and have errors from the AIOWPM plugin.

Example output:

Screenshot 2024-06-18 at 3 32 21 PM

## Does this pull request change what data or activity we track or use?

Yes, it adds the site's blog ID to any Tracks events recorded by `wpcomsh_record_tracks_event`. We need to know if this is allowed according to our TOS.

## Testing instructions:

1. Create a new Business site, mark it as a WoA Dev site, and take it Atomic.
2. Activate this branch on your WoA test site via the Jetpack Beta plugin
3. Rsync the wpcomsh changes to your WoA site: `jetpack rsync wpcomsh yourtestsite.wordpress.com@sftp.wp.com:htdocs/wp-content/mu-plugins`
4. On your WoA test site, install the AIOWPM plugin: https://wordpress.com/plugins/all-in-one-wp-migration/
5. Activate the plugin and go to All in One WP Migration -> Export
6. Create and download an export file
7. Go to All in One WP Migration -> Import
8. Start the import from the file you created
9. Check Tracks Live for the migration start and end events (may take a few minutes to get there): `wpcom_aiowpm_import_start` and `wpcom_aiowpm_import_end`

### CODE REVIEW

**Comment by sixhours** [comment]
Ping TOS folks to get their take p1718814626568589-slack-C029FV6KT

**Comment by sixhours** [comment]
TOS suggested I check with legal, so I'm doing so here p2y3YZ-8Bs-p2

**Comment by sixhours** [comment]
Legal has signed off on blog IDs being added based on the fact that we're tracking existing users who have a relationship with us: p2y3YZ-8Bs-p2#comment-19107

So I think this is good for a review.

**Comment by markbiek** [comment]
I'm having some issues testing this. But I suspect it's a problem setting up the test site and not with the actual PR. I'll try and revisit it on Mon.

**Review by markbiek — DISMISSED** [review]
I've tried testing this several times now and I never see the events firing. I've followed the testing instructions exactly and verified the changes are on my WoA site so I'm not sure what's happening.

**Review by daledupreez — COMMENTED** [review]
@markbiek, I just tested the changes successfully, so I think we should be OK to ship this.

**Comment by markbiek** [comment]
> @markbiek, I just tested the changes successfully, so I think we should be OK to ship this.

Awesome. I can take care of the rebase and getting it deployed.

**Comment by daledupreez** [comment]
Ugh. Looks like we need another merge/rebase, @markbiek.

**Comment by markbiek** [comment]
> Ugh. Looks like we need another merge/rebase, @markbiek.

On it! Jetpack changes so fast 🙃

**Review by daledupreez — APPROVED** [review]
Approving after all the rebase/version fixes.

**Pull request merged**
