### PR TITLE
Userless Connection: connection flow

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
- Modify connection screen appearance
- Redirect "userless" users to the "Plans" page after they choose to proceed without connecting to WP.com
- `ConnectUserBar` React component
- New module setting: `requires_user_connection`, and new reducers to pull this data
- New property for the `SettingsGroup` component: `disableInUserlessMode`, which checks if the site is working in userless mode, and makes the `SettingsGroup` inactive
- Adjusting the modules that require user connection accordingly

#### Jetpack product discussion
p1HpG7-b0a-p2
p9dueE-2vd-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
__Free plan__
1. Define the `JETPACK_NO_USER_TEST_MODE`, disconnect Jetpack.
2. Initiate the connection using the In-Place flow.
3. Instead of clicking "Approve", scroll down to the "Or start using Jetpack now" section. Confirm that it looks like this:
Screen Shot 2021-02-17 at 7 06 31 PM
4. Click "Continue without user account". You should be taken to the "Pricing" page: `https://cloud.jetpack.com/pricing/`.

5. Scroll down and click "Start for free". You should be redirected back to Jetpack Dashboard.

__Connecting user via In-Place Flow__
6. Go to "Jetpack -> Settings -> Security -> Downtime monitoring". Underneath it you should see the "Connect my user account" button:
Screen Shot 2021-02-17 at 7 10 35 PM
7. Click "Connect my user account" button, the connection widget should unfold under the same "Downtime monitoring" card:
Screen Shot 2021-02-17 at 7 13 50 PM
8. Click "Approve". After the authorization has completed, the connection widget should get replaced with the "Configure your notification settings" link in the same place (under "Downtime monitoring"). This should happen **without** page reloading.

__Purchasing a plan__
_You need to disconnect from the Automattic Proxy to use the production build of Jetpack Cloud. This flow does not fully work with the Jetpack Cloud Stage, which is served to you when you connect through the proxy._

Your WP.com account may be in 3 different states in regard to this account, please repeats testing instructions in this section in each state:
- Not logged into WP.com
- Logged into WP.com, not connected to Jetpack Cloud app (go to the [Connected Apps](https://wordpress.com/me/security/connected-applications) section and disconnect all "Jetpack.com" apps if there are any).
- Logged into WP.com, connected to Jetpack Cloud app (go to https://cloud.jetpack.com/ and approve the connection).

1. Disconnect Jetpack, and click "Set up Jetpack" again.
2. Click "Continue without user account". You should be taken to the "Pricing" page: `https://cloud.jetpack.com/pricing/`
3. Choose a plan and click on the Purchase button. You should be redirected to the Calypso flow to connect your user account to WP.com. If you are not logged into WP.com, the flow will include authentication process.
4. After you click "Approve" you should get redirected to Checkout.
5. _This step may only be completed once, no need to repeat it for every WP.com account state_. Complete the checkout and confirm that the product is purchased successfully.

#### Proposed changelog entry for your changes:
* Using Jetpack without connecting to WP.com account.

### CODE REVIEW

**Comment by leogermani** [comment]
Great work Sergey, here's what I've found so far:

1. for the features that require a user, I see the "connect your account" but I can still activate it before connecting

2. I had no luck testing the purchase flow, I fell into two situations

1st, in a window logged in with my a11n account, The flow took me to this screen:

Captura de Tela 2021-02-18 às 16 19 47

2nd, in an incognito window, I logged in with a non a11n account and was taken to this error:

```
Deprecated: Jetpack::is_user_connected is deprecated since version jetpack-9.5! Use Automattic\Jetpack\Connection\Manager\is_user_connected instead. in /srv/users/usercbd092c2/apps/usercbd092c2/public/wp-includes/functions.php on line 4859

Warning: Cannot modify header information - ...
```

**Comment by leogermani** [comment]
I'd like to ping @keoshi , @coder-karen to help review it looking at what we started discussing here p1HpG7-b0a-p2#comment-44208 concerning the "See all jetpack features" link.

Also, @keoshi , to get a final version on the copy for the authorize screen, where we still have "activate essential Wordpress features..." (first topic on this comment -> p1HpG7-b0a-p2#comment-44204)

**Comment by sergeymitr** [comment]
Thanks @leogermani.

> for the features that require a user, I see the "connect your account" but I can still activate it before connecting

Fixed.

> 1st, in a window logged in with my a11n account, The flow took me to this screen:

Please check if your a11n account is "connected to Jetpack Cloud" in the WP.com settings: https://wordpress.com/me/security/connected-applications
If you're connected, the flow will not work, we need to fix that. In that case please disconnect it and try again.

> 2nd, in an incognito window, I logged in with a non a11n account and was taken to this error:

Fixed by #18876, please test again.

**Comment by leogermani** [comment]
Two more comments while I'm not able to fully test:

* reduce the iframe height so the "continue without a user" is not so far down below
* Make sure we are tracking clicks to the new buttons the same way we are tracking all the others events

**Comment by coder-karen** [comment]
> concerning the "See all jetpack features" link.

The draft support doc still links to all features that require and those that don't require a WP.com connection, but the first part of the doc could do with an explanation of why the WP.com connection is important. @keoshi took over the doc after the features were added so I'd defer to him there.

I did want to add one extra comment as I review the suggested wording in the connection flow - after clicking 'activate' under Jetpack on the plugins page, under 'Or start using Jetpack now' could the wording perhaps change from ‘Some features will not be available, but….’ to ‘Some features will not be available until you connect your user account to unlock them’?

**Comment by keoshi** [comment]
First off, apologies for the delay here but I was AFK most of last week.

I've tested this flow successfully and it's really exciting to see this come to life. The UX feels really good IMO and while there are a few design tweaks we can make (more on that below), this feels solid. I also agree with @coder-karen's suggestion on the copy, that's much better.

> "See all jetpack features" link

I'll circle back to that doc this week and complete it with the intro on dotcom. While these two documents overlap a little bit, this new one will be much more targeted, so what if we should change the copy to `Why the connection is important?` or something similar. Pinging @coder-karen for your thoughts.

> final version on the copy for the authorize screen

I wonder if we could pair the copy change on the link to `Why the connection is important?` (see above) and use the current title `Unlock {selected_feature} and more amazing features` — would that solve the problem in your opinion?

We have a tight space to speak about the extra benefits, so focusing on the connection itself might not be the best option. Instead, we could offset those details to our support page.

Another note is that the list below this title should be “dynamic” in the sense that it should exclude the benefit that's currently selected. See how we're duplicating Downtime Monitor in both the title and the first bullet here (this is design's fault, we made that mistake):

image


### Design tweaks

- The gray box in the in-place connect flow has an extra border, can we remove it so it sits flush with the existing card?
- Would it be possible to vertically center the iframe on the space that is reserved for it, so that it's equally spaced from the top and bottom?

Last but not least, kudos for the great work happening here! 🙌

**Comment by sergeymitr** [comment]
Hi @keoshi.

Thanks for taking a look!

> The gray box in the in-place connect flow has an extra border, can we remove it so it sits flush with the existing card?

Fixed.

> Would it be possible to vertically center the iframe on the space that is reserved for it, so that it's equally spaced from the top and bottom?

That needs to be adjusted on the WP.com side. I added necessary changes to this PR so we could identify this iframe on the WP.com side and adjust the styling there.

**Comment by sergeymitr** [comment]
Hi @leogermani.

Thanks for the review!

> reduce the iframe height so the "continue without a user" is not so far down below

Fixed.

> Make sure we are tracking clicks to the new buttons the same way we are tracking all the others events

I added a `jetpack_wpa_click` event with `target=connection-bar-click`. Please confirm that the event is being tracked when you click on the "Connect my user account" button.

**Comment by leogermani** [comment]
Hi Sergey,

Excellent job! Thank you so much for working at this.

I've tested all the scenarios you asked for and also some additional ones, such as going user-less and then clicking in one of the Upgrade buttons we have, for example, under Backups.

Everything worked just fine, with the user being added to the blog correctly.

All the comments I have are concerned to layout.

## Top banner

Captura de Tela 2021-03-03 às 17 01 18

I think we should remove this current banner that says "Link to WordPress.com". The original design has that progression bar showing that not all the features are available. If you want to push that to a next PR that's fine, but I think we could remove this anyway.

## Downtime Monitor at the "At a glance" page

The downtime monitor card is not showing the message to connect the user in that At a Glance page

## Layout of the Connection bar

I'm seeing a layout a bit different here. I'm using Firefox. The border is missing:

Captura de Tela 2021-03-03 às 17 07 00

Also, there should be a  WordPress.com logo on the left

## Layout of the connect user box

It looks it needs a vertical alignment

Captura de Tela 2021-03-03 às 17 03 44
Captura de Tela 2021-03-03 às 17 32 09

Also, let's change this text to "Unlock all Jetpack features by connecting to WordPress.com" as for [this comment](p1HpG7-b0a-p2#comment-44204)

Thanks!

**Comment by keoshi** [comment]
Those are great catches, @leogermani — agree with everything you pointed out above. And again, let me know if I can help with anything.

**Comment by sergeymitr** [comment]
Hi @leogermani.

Thanks for the review!

> Top banner

I removed the banner in userless mode, left it in place for non-connected secondary users.
You're right, we should address the new banner in a separate PR.

> Layout of the connect user box

We can't style insides of the iframe from Jetpack, because we don't know the size of the actual iframed page. Instead, we're now passing the iframe height into WP.com so we could center the content in there.
So I'll address this in a WP.com diff.

> Also, let's change this text to "Unlock all Jetpack features by connecting to WordPress.com" as for this comment

This will also require changes on the WP.com side - we'll need to use the `postMessage` API to ping Jetpack when iframe is loaded and it's time to switch the title from "Activate essential WordPress..." to "Unlock all Jetpack features...".
So let's address this in a separate PR to get this one merged.

> Layout of the Connection bar

I added the border, good catch.
Let's leave the WP.com logo for the next PR too, I don't want to stall this PR any longer.

@keoshi, can you please send me the WordPress.com logo for the connection bar? I wasn't able to save it from the Figma prototype with good quality.
Screen Shot 2021-03-04 at 2 16 07 PM

> Downtime Monitor at the "At a glance" page

Fixed now, good catch.

**Comment by kbrown9** [comment]
I did a bit of testing on this and noticed a few things:

## Enabling a Module When a User has Connected From the Module Card

Sorry in advance if this has already been discussed. I wonder if it would be a better user experience if the module were to be automatically enabled during the authorization. Currently, the user sees a module card, chooses to authorize (most likely because they want that feature), and they're returned to the settings screen with the module still deactivated.

## The Subscriptions Card Doesn't Show the Connection Bar

This is what I see when the Subscriptions module is disabled. Notice that there's no connection bar.

Screen%20Shot%20on%202021-03-05%20at%2010-48-44

And this is what I see when the Subscriptions module is enabled:

Screen%20Shot%20on%202021-03-05%20at%2010-49-55

**Comment by leogermani** [comment]
@kbrown9 automatic module activation for user-less connection is being handled in this PR https://github.com/Automattic/jetpack/pull/18927

It depends on this one so will be moved to Needs Review as soon as this one goes through but you are welcome to have a look at it if you can. I'm gonna update it with the latest changes made here

**Comment by sergeymitr** [comment]
Hi @kbrown9, @leogermani, thanks for the review.
If the module is disabled, it never gets to display the connection bar: https://github.com/Automattic/jetpack/pull/18837/files#diff-15f52e6f46e57664ff6322651cd10ec800acd7471daa1a7f0dba4e44840df606L70

@leogermani,
We will activate this module as soon as the blog connection gets established in the PR #18927, correct?

**Comment by kbrown9** [comment]
> If the module is disabled, it never gets to display the connection bar: https://github.com/Automattic/jetpack/pull/18837/files#diff-15f52e6f46e57664ff6322651cd10ec800acd7471daa1a7f0dba4e44840df606L70

Hmm, how will the user enable the Subscriptions module? I had to go to the `jetpack_modules` page, enable the Subscriptions module, go back to the Settings page, and connect.

On my site, all of the other cards show the connection bar even though the modules are disabled. 

Monitor on the `jetpack_modules` page:

Screen%20Shot%20on%202021-03-05%20at%2012-02-44

The Monitor card on the Settings page:

Screen%20Shot%20on%202021-03-05%20at%2012-03-09

**Comment by leogermani** [comment]
> We will activate this module as soon as the blog connection gets established in the PR #18927, correct?

The default modules will, yes. But Subscriptions [is not a default module](https://github.com/Automattic/jetpack/blob/update%2Fconnection-package-xmlrpc-independence/projects/plugins/jetpack/modules/subscriptions.php#L9).

> If the module is disabled, it never gets to display the connection bar

Hmm I didn't catch that. But it doesn't look like this is right. I should be asked to connect so I can activate the module...

**Comment by sergeymitr** [comment]
Hi @kbrown9, @leogermani.
I fixed the Subscription module issue, please re-review.

**Review by leogermani — APPROVED** [review]
Tested it again and it looks good. I think it's a good idea to merge it early in the release cycle so it gets well tested. Approving it!

Let's work on the layout adjustments on the WPCOM side now.

**Review by kbrown9 — APPROVED** [review]
I tested , and the subscriptions module now displays the connection bar.

**Comment by sergeymitr** [comment]
Nice!
@kbrown9, @leogermani, huge thanks for the review!

**Comment by sergeymitr** [comment]
Hi @jeherve.
Thanks for pointing this out, we probably don't need that border in "userful" mode.
I addressed that in #19155.

**Pull request merged**
