### PR TITLE
Merge/divergence custom css

### PR DESCRIPTION
**Pull request by dereksmart**

### CODE REVIEW

**Comment by zinigor** [comment]
Looks good! You may want to consider merging #2711 because this PR has related commits.

**Comment by dereksmart** [comment]
@sirbrillig Would you mind taking a look at this and #2711? Not sure if these endpoints are ready for Jetpack prime time yet

**Comment by sirbrillig** [comment]
@dereksmart The additional custom-css functions are only being used by my endpoint, so I guess the question is if the endpoint should be merged or not.

> Not sure if these endpoints are ready for Jetpack prime time yet

Neither am I! This is my first Jetpack endpoint (although I've made tons of wpcom endpoints). :-) What's the criteria to determine if it's ready for "prime time"?

**Comment by dereksmart** [comment]
I suppose if it's functional and throws no errors :) 

Just double-checking with ya because someone mentioned that they heard it may still be in development.  

We've been talking about adding in Unit tests for the REST endpoints in Jetpack, but that's not required rn

**Pull request merged**
