### PR TITLE
Add/prevent batcache when accessing paywalled content

### PR DESCRIPTION
**Pull request by millerf**
## Proposed changes:

* Send no-cache headers so batcache is disabled when user access a paywalled content

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

### Works only on Atomic (can't see batcache on simple)
* Deploy on your sandbox
* Sandbox your preferred site
* Create a paywalled content
* Access gated content and notice a batcache hit
* Access paywall and notice no cache header

### CODE REVIEW

**Review by chrismccluskey — APPROVED** [review]
Tested this and I see the `Cache-Control: no-cache` header both as an editor and as a subscriber. LGTM!

**Comment by simison** [comment]
@chrismccluskey @millerf would it make sense to disable the cache for this view, too?

image

**Comment by millerf** [comment]
> @chrismccluskey @millerf would it make sense to disable the cache for this view, too?
> 
> image

Why?

**Comment by millerf** [comment]
> @chrismccluskey @millerf would it make sense to disable the cache for this view, too?
> 

What makes you think this page is cached?

Screenshot 2023-12-04 at 11 53 57

**Pull request merged**
