### PR TITLE
Backup: minor styling fixes

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
* adjusted margins for the connection screen
* brought back the "Where are my backups stored" on the Backup's "no plan" page
* made the "Connection" card match the styling of the "Heartbeat" card

#### Jetpack product discussion
p1HpG7-cGL-p2#comment-48286

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
0. Rebuild the Backup plugin if testing locally (`jetpack build plugins/backup`).
1. Disconnect Jetpack and go to the "Backup" page (connection screen). Confirm that the margins on the left screen are correct.
2. Connect with no plan. Confirm that the "Where are my backups stored" card shows up.
3. Confirm that the styling of the "Connection" card matches the "Heartbeat" card.
4. Confirm that the "Heartbeat" card does not have the "Activity" link.
5. Purchase a backup plan, confirm that you now see the "Activity" link in the "Heartbeat" card.

### CODE REVIEW

**Review by fgiannar — CHANGES_REQUESTED** [review]
Hi Sergey,

Thanks for working on this! I have the following comments:
1. On the Set Up screen ( aka before establishing a user-level connection ) the "Heartbeat" and "Where are my backups stored?" cards are now visible. This is an issue, because the "Heartbeat" section includes a link to Calypso Green (Activity Log) that will not work before a user level connection is setup. 
Screenshot 2021-08-10 at 1 25 46 PM
2. You'll notice a small flickering when refreshing the "Setup" screen that is not reproducible on the master branch.

**Comment by sergeymitr** [comment]
Hi @fgiannar, thanks for the review!
I make the "activity" only show up if a backup plan is available.
However, I wasn't able to see the flickering. Comparing to `master`, the rendering process looks pretty much the same. Could you please record a video, may be I'm missing something?

**Comment by sergeymitr** [comment]
> 2. You'll notice a small flickering when refreshing the "Setup" screen that is not reproducible on the master branch. 
I see that now.
Should be fixed, please double check.

**Review by fgiannar — APPROVED** [review]
This tests well for me now, Sergey! 👍

**Pull request merged**
