### PR TITLE
Sync json-api-site-base.php with wpcom

### PR DESCRIPTION
**Pull request by sdixon194**
#### Changes proposed in this Pull Request:

Syncs wpcom changes to jetpack file for json-api-site-base.php

Jetpack changes will then need to be pushed back to wpcom

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

No
#### Testing instructions:

* Proof? Can these new methods be safely added to Jetpack?

### CODE REVIEW

**Comment by anomiex** [comment]
Lots of CI failures, removing Needs Review status.

**Comment by sdixon194** [comment]
Yeah this is going to need significantly more work to get going.

**Comment by coder-karen** [comment]
I've not looked at json-api-site-base.php but looked at several others in this PR - #23059 - most likely taken too much in one bite in my PR. Mentioning it here anyway since we're looking at similar files.

**Comment by sdixon194** [comment]
> most likely taken too much in one bite in my PR. Mentioning it here anyway since we're looking at similar files.

Yeah I'm curious how difficult it will be to deploy the wpcom files if these aren't merged, but worth a shot. I'll mark this as on hold until that PR gets merged and then we can look at it again.

**Comment by coder-karen** [comment]
@sdixon194 PR #23059 is merged now.

Separately, I'm thinking of taking a look at `class.json-api-post-base.php` and `class.json-api-post-jetpack.php` next in a separate PR. After that if they still remain I could look at the final three files listed here - #21967 - so excluding the file you've looked at in this PR. I just want to check in though to make sure that doesn't conflict with anything you are doing.

**Comment by sdixon194** [comment]
> I just want to check in though to make sure that doesn't conflict with anything you are doing

You should be good to go @coder-karen, that's not conficting with anything I'm working on. I'm thinking of closing out this PR as well and trying a different approach.

**Comment by sdixon194** [comment]
Gonna just close this out for now. After fixing up some endpoint diffs for wpcom, getting the PHPCS stuff out of the way first actually seems easier than trying to untangle the knot that is unsynced jetpack files first.

**Pull request closed without merging**
