### PR TITLE
JS Components: Convert ProductOffer component to TypeScript

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Changes proposed in this Pull Request:
* This PR converts `ProductOffer` component to TypeScript.
* It also converts the `ProductOffer` stories to TS

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Checkout the PR
* Run `cd projects/js-packages/storybook && pnpm run storybook:dev`
* Confirm that all the stories of `ProductOffer` component work as expected
* Check the consumers of `ProductOffer` and related components and confirm that they work as expected
* Check for any regression

https://user-images.githubusercontent.com/18226415/181243146-c92042a2-e053-4364-9a6e-79d216e0be82.mov

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202276314263990

### CODE REVIEW

**Comment by dhasilva** [comment]
Some actions are not shown in storybook anymore, probably the same issue as https://github.com/Automattic/jetpack/pull/25295#issuecomment-1200859975.

Before | After
------|------
Screenshot_2022-08-01_12-06-14 | Screenshot_2022-08-01_12-08-37

**Comment by manzoorwanijk** [comment]
> Some actions are not shown in storybook anymore

Thank you @dhasilva for pointing that out. In my opinion, it's good that implicit controls are not shown. It shows only the controls we have added to the story and I think that is better than having any unknown controls that have not been added to the story because that can be confusing for a beginner as to where those controls come from. If we want those extra controls to be there, we can add them separately if needed.

**Review by dhasilva — APPROVED** [review]
:rocket:

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by sdixon194** [comment]
Deployed in r250012-wpcom because it was blocking another diff.

**Pull request merged**
