### PR TITLE
Hoist packages required for Gutenberg Mobile

### PR DESCRIPTION
**Pull request by jhnstn**
Fixes Gutenberg Mobile build issues.

Gutenberg Mobile CI tests began failing after a recent change to [how packages are hoisted by pnpm](https://github.com/Automattic/jetpack/commit/ef3305b95be354cb1e1a27327309483d354a4852). Here is an example https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/17267/workflows/db9a684d-a584-4d50-ae19-295a9d6120c0/jobs/94164

This PR hoists the minimal number of packages currently required for the Jetpack integration into Gutenberg Mobile

#### Changes proposed in this Pull Request:

* Hoists a few additional packages in the `.npmrc` config

#### Jetpack product discussion

none

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* Go to '..'
* Jetpack should function as expected.

For Gutenberg Mobile developers:
- Remove `gutenberg-mobile/jetpack/node_modules` to make sure there are no lingering packages from prior intalls.
- Update the Jetpack submodule to a5457b13be59f207a7defe3237084f137c5decd7
- Run `npm install` from `gutenberg-mobile`
- Verify bundling the app succeeds (I've been using the command that has been failing on CI:  `npm run test:e2e:bundle:ios`

### CODE REVIEW

**Comment by anomiex** [comment]
I'd really rather we figure out what is going on in your build environment that it can't find these normally. Most of these are direct dependencies of Jetpack, there's no reason they shouldn't be findable.

**Comment by kraftbj** [comment]
@anomiex Is that a rejection of this PR or an "accept-but-it-should-be-temporary" comment?

**Comment by anomiex** [comment]
Not sure yet. Needs more poking.

I poked at it a little locally. I can reproduce the failure from https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/17326/workflows/516c96f2-2b3c-4d04-a56d-852203eda556/jobs/94405?invite=true&invite=true#step-109-33 by running the following script in a fresh Ubuntu 20.04 docker (`docker run --rm -it ubuntu:20.04`).
```bash
#!/bin/bash

set -eo pipefail

export CI=true

export DEBIAN_FRONTEND=noninteractive
printf "\e[1m=== Installing various base packages ===\e[0m\n"
apt-get -q update
apt-get -qy install curl git gpg jq unzip vim

printf "\e[1m=== Installing Node 14 ===\e[0m\n"
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get -qy install nodejs

printf "\e[1m=== Fetch ===\e[0m\n"
cd /tmp
git clone --branch=fix/jetpack-ci-build --depth=1 --recurse-submodules --shallow-submodules https://github.com/wordpress-mobile/gutenberg-mobile.git
cd gutenberg-mobile

printf "\e[1m=== npm install ===\e[0m\n"
npm ci --no-audit

printf "\e[1m=== Build? ===\e[0m\n"
npm run test:e2e:bundle:android
```

I also found [some issues](https://github.com/facebook/metro/issues?q=is%3Aissue+is%3Aopen+symlink) in the repo for metro suggesting that it doesn't follow symlinks, some with possible workarounds.

I also just came across some existing code at https://github.com/wordpress-mobile/gutenberg-mobile/blob/528d17a497818c839bee9ea7a79b2523b3e8c4d8/metro.config.js#L26-L40 that looks like it could use updating after the change in the Jetpack monorepo, as it's specifically looking at a dir that's not populated anymore.

**Comment by anomiex** [comment]
<details>
<summary>Try this rewrite of your `metro.config.js`:</summary>

```js
const path = require( 'path' );
const fs = require( 'fs' );
const metroResolver = require( 'metro-resolver' );

const gutenbergMetroConfig = require( './gutenberg/packages/react-native-editor/metro.config.js' );
const extraNodeModules = {};
const gutenbergMetroConfigCopy = {
	...gutenbergMetroConfig,
	resolver: {
		...gutenbergMetroConfig.resolver,
		sourceExts: [ 'js', 'jsx', 'json', 'scss', 'sass', 'ts', 'tsx' ],
		extraNodeModules,
	}
};

gutenbergMetroConfigCopy.resolver.resolveRequest = (context, moduleName, platform) => {
	const bits = moduleName.split( '/' );
	if ( bits[0] !== '' && bits[0][0] !== '.' ) {
		const name = bits[0][0] === '@' ? bits[0] + '/' + bits[1] : bits[0];

		if ( extraNodeModules[ name ] === undefined ) {
			// Try to find the package in the Gutenberg submodule.
			const dir = path.join(
				process.cwd(),
				`gutenberg/node_modules/${ name }`
			);
			if ( fs.existsSync( dir ) ) {
				extraNodeModules[ name ] = fs.realpathSync( dir );
			}
		}

		if ( extraNodeModules[ name ] === undefined ) {
			// Try to find the package in the Jetpack submodule.
			const dir = path.join(
				process.cwd(),
				`jetpack/projects/plugins/jetpack/node_modules/${ name }`
			);
			if ( fs.existsSync( dir ) ) {
				extraNodeModules[ name ] = fs.realpathSync( dir );
			}
		}

		if ( extraNodeModules[ name ] === undefined ) {
			// Try to find within Jetpack's pnpm store, relative to the origin file.
			const filePath = require.resolve( name, { paths: [
				path.dirname( context.originModulePath ),
			] } );
			if ( filePath && filePath.indexOf( '/.pnpm/' ) >= 0 ) {
				const idx = filePath.lastIndexOf( '/node_modules/' );
				if ( idx >= 0 ) {
					extraNodeModules[ name ] = filePath.substring( 0, idx + 14 ) + name;
				}
			}
		}

		if ( extraNodeModules[ name ] === undefined ) {
			// Record failure of all of the above to save trying again.
			extraNodeModules[ name ] = null;
		}
	}

	// Call the default resolver.
	if ( context.resolveRequest !== gutenbergMetroConfigCopy.resolver.resolveRequest ) {
		// metro 0.68+
		return context.resolveRequest( context, moduleName, platform );
	} else {
		// metro < 0.68
		return metroResolver.resolve(
			{
				...context,
				resolveRequest: null,
			},
			moduleName,
			platform
		);
	}
};

module.exports = gutenbergMetroConfigCopy;
```

</details>

It moves the logic for looking up the extra modules into a `.resolver.resolveRequest` function so we have access to the requesting file's path, simplifies the symlink handling, and uses Node's `require.resolve()` logic to find pnpm deps relative to the requesting file to handle things like how `/tmp/gutenberg-mobile/jetpack/node_modules/.pnpm/photon@4.0.0/node_modules/photon/dist/cjs/index.js` needs to find crc32 via a symlink at `/tmp/gutenberg-mobile/jetpack/node_modules/.pnpm/photon@4.0.0/node_modules/crc32` rather than looking in `/tmp/gutenberg-mobile/jetpack/projects/plugins/jetpack/node_modules/` or any path above there.

**Comment by jhnstn** [comment]
Thanks for digging into this @anomiex !  TIL Metro has issues with symlinks. 
Closing this in favor of updating the metro config

**Pull request closed without merging**
