### PR TITLE
Bypass custom link check for galleries created in classic block

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request:

* Checks for existence of `.attr( 'data-permalink' )` before running check for custom image links in carousel. The recent modification to allow for custom links to bypass the carousel in the gallery block refactor broke the carousel for galleries created with the classic editor/block.

Fixes: #18694

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

- Apply this PR to local install
- Add a gallery via the classic editor or classic block and check that images open in lightbox
- Also add a gallery block and check the same
-  Run Gallery refactor PR locally as well as this PR and check that images with custom links forward to the link instead of opening in lightbox, but other images still open in lightbox

#### Proposed changelog entry for your changes:
* No changelog entry needed

### CODE REVIEW

**Review by apeatling — DISMISSED** [review]
Followed testing instructions and everything worked as expected. 👍

**Comment by glendaviesnz** [comment]
Are you happy for us to merge this @jeherve?  We just need to make sure this gets into 9.5 so the fix gets out to Atomic sites. Do you know roughly when 9.5 would be pushed to Atomic?

**Comment by jeherve** [comment]
> Do you know roughly when 9.5 would be pushed to Atomic?

It will ship to Atomic on March 2.

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to break the behaviour of galleries that have the link setting set to "Media File":
Screenshot 2021-02-04 at 12 16 53

When I pick that setting, the Carousel view is not triggered anymore.

Somewhat related, the previous change also caused this bug:
#18694 

It may be interesting to try to fix both issues at once?

**Comment by glendaviesnz** [comment]
> This seems to break the behaviour of galleries that have the link setting set to "Media File":
> When I pick that setting, the Carousel view is not triggered anymore.
> Somewhat related, the previous change also caused this bug:
> #18694 
> It may be interesting to try to fix both issues at once?

This patch was intended to fix #18694 which was reported on WPCOM and the patch was pushed to simple sites with D56102-code which fixed the issue there.

I just retested this on a local install and with both Attachment and Media setting the carousel loads:

carousel

I wonder if there is another local setting with affects the image data. It appears that gallery images added via the classic block don't have the `data-permalink` attribute set which is how I was filtering these out of the custom link check, but maybe you have a different setting on your install that causes this to be set?

**Comment by glendaviesnz** [comment]
@jeherve I have refactored this to specifically target only gallery items that are individual Image blocks so it should now only affect the new refactored core gallery and should fix both #18694 and the Media link issue you noted.

**Review by aaronrobertshaw — APPROVED** [review]
This is testing well for me. 👍 

- Works as advertised without the Gutenberg refactored gallery PR
- With both PR branches
    - classic block gallery images open in a lightbox
    - gallery block images open in a lightbox when link to destination is none, media file or attachment
    - gallery block images honour custom links without error

**Review by jeherve — APPROVED** [review]
This tests well for me, and fixes the issue, thank you!

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in 33b10e25b11184d89b5c56617a22ac3fcf8362f4. I'll let you handle the matching WordPress.com diff.

**Comment by JoshuaGoode** [comment]
Encountered this today on an Atomic site.  They are not a Gutenberg user and all posts have been created in the editor and rely heavily on the gallery.

1,000+ posts are now linking to attachment pages instead of a carousel; however, due to their site settings, normal visitors can't access them.

**Comment by JoshuaGoode** [comment]
Is there a safe way to code snippet this and provide it to a user until an update is available on Atomic?

**Comment by JoshuaGoode** [comment]
Rather than trying to add the fix, I was able to use this to force the galleries to `none` and  restore the carousel until things are fixed up.

```
function force_gallery_link_to_none($out, $pairs, $atts)
{
    $atts = shortcode_atts( array( 
    'link' => 'none' 
    ), $atts );
    $out['link'] = $atts['link'];
    return $out;
}
add_filter('shortcode_atts_gallery', 'force_gallery_link_to_none', 10, 3);
```

**Pull request merged**
