### PR TITLE
Widget Visibility: support custom post type archive pages #80

### PR DESCRIPTION
**Pull request by ivankristianto**
Fix for #80 and #750 

cc @jeherve and @kraftbj please kindly review this PR

### CODE REVIEW

**Comment by ivankristianto** [comment]
Any plan to merge this PR?

**Comment by kraftbj** [comment]
Hi @ivankristianto, it's still on the roadmap. Thanks for your patience!

**Comment by samhotchkiss** [comment]
This needs a review for UX and some deeper testing, as this syncs up with WordPress.com

It's probably not going to happen for 3.6, but let's try to make an effort to get this wrangled for 3.7

**Comment by samhotchkiss** [comment]
This isn't going to make 3.7.  @jessefriedman, can you take some ownership of this for 3.8?

**Comment by dereksmart** [comment]
@ivankristianto can we get a rebase?

**Comment by jessefriedman** [comment]
@dereksmart rebasing now with branch: fix/widget-visibility-and-cpts

**Comment by dereksmart** [comment]
@jessefriedman sounds good. please Close this when you're done.

**Comment by s-a-s-k-i-a** [comment]
Any news on this?

**Comment by kraftbj** [comment]
@jessefriedman is https://github.com/automattic/jetpack/tree/fix/widget-visibility-and-cpts ready to be PR'd?

**Comment by jessefriedman** [comment]
@kraftbj no, unfortunately I ran into the problem with the rebase, fixing it

**Pull request closed without merging**
