### PR TITLE
adds a notification task to notify KitKat for high and blocker bugs

### PR DESCRIPTION
**Pull request by cometgrrl**
## Proposed changes:

- This is WIP to add notifications to #kitkat-daily for high and blocker bugs.
- I have mostly copied from notify-editorial, and I'm sure I've made some mistakes. 😎
- I have not added the channel id as a secret (yet)
- ifNotClosed might need to be updated (or a new function added) to handle issues, as the existing function is geared towards PRs.
- This is my first time working with GitHub actions. I'm unsure if this will fire a notification when any label is added to a bug with the specified labels or only when the specified labels are added. For example, if a bug is labeled [Prio] High, and the notification is sent, and later, someone adds another label such as "Atomic", will this trigger another notification? I ask because notify-editorial has a check on "hasBeenRequested". If this is the case, I can add a check for the presence of the "needs triage" label, so that we don't send the notification if that label is not present. We will then need to ensure that new bugs start with that label and that we remove it consistently during triage.
- Also, I do not know how to test this, so advice would be greatly appreciated!

### Other information:

Since this is for GitHub Actions, there should be no impact on e2e tests or WP.com.

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No.

### CODE REVIEW

**Comment by jeherve** [comment]
I pushed a few commits that should help with this, I hope you don't mind!

> I do not know how to test this, so advice would be greatly appreciated!

Testing actions can be a bit tricky indeed. I usually test on a fork of this repo. You can see one of my tests here for example:

p1676307249843629-slack-CN2FSK7L4

> I have not added the channel id as a secret (yet)

I took care of it for you.

> ifNotClosed might need to be updated (or a new function added) to handle issues, as the existing function is geared towards PRs.

Yes indeed, it's not compatible with issues right now. I don't think that's an issue in this task though; I don't think we add priority labels on closed issues too often.

>  I'm unsure if this will fire a notification when any label is added to a bug with the specified labels or only when the specified labels are added. For example, if a bug is labeled [Prio] High, and the notification is sent, and later, someone adds another label such as "Atomic", will this trigger another notification? I ask because notify-editorial has a check on "hasBeenRequested". 

We do indeed need a way to ensure notifications do not keep being sent for the same issue. I thought about using the existing Needs triage label as you mentioned, but I'm afraid it may not work perfectly, since the label is not always there in the first place. I ended up creating a new "[Status] Escalated to Kitkat" that will be added to issues when you've been notified. 
Let me know what you think about it.

**Comment by cometgrrl** [comment]
> I pushed a few commits that should help with this, I hope you don't mind!

Thank you for the help!

> We do indeed need a way to ensure notifications do not keep being sent for the same issue. I thought about using the existing Needs triage label as you mentioned, but I'm afraid it may not work perfectly, since the label is not always there in the first place. I ended up creating a new "[Status] Escalated to Kitkat" that will be added to issues when you've been notified.

This would work. Will it get confusing as [status] labels pile up on an issue? I personally expect an issue to have a single status, but perhaps that's not a reasonable expectation in this case.

Since the `needs triage` label doesn't always get applied (and I've seen several cases where it didn't get removed after triage), perhaps we need to rethink that label. I've also seen some issues labeled as `triaged`, which also seems to be applied inconsistently. This, perhaps, should be a separate conversation.

I might make some small edits to the slack message, as I think we'd prefer to use :bug_police: instead of ⚠️.

**Comment by jeherve** [comment]
> Will it get confusing as [status] labels pile up on an issue? I personally expect an issue to have a single status, but perhaps that's not a reasonable expectation in this case.

Yes, it's not a perfect solution. I usually prefer single [Status], [Type], and [Pri] labels on issues, but in cases like that I'm afraid there is no better solution than a label to clearly mark an issue as already escalated.

> Since the needs triage label doesn't always get applied (and I've seen several cases where it didn't get removed after triage), perhaps we need to rethink that label. I've also seen some issues labeled as triaged, which also seems to be applied inconsistently. This, perhaps, should be a separate conversation.

Yeah, I'm not sure what's best; the 2 labels make sense when they're used consistently. Maybe we would be able to improve how they're used by automating some of the 2 labels' additions and removals. That may be something to discuss on p2 though. :)

**Review by dpasque — DISMISSED** [review]
Not sure if y'all need/want other review, but FWIW I also took a peek and the changes LGTM! 
🎉

**Comment by cometgrrl** [comment]
@jeherve I tweaked the notification text to make it shorter and changed the emoji. Those should be the only changes. 

Unless you see any other issues/bugs, hopefully this is good to go?

**Review by jeherve — APPROVED** [review]

**Pull request merged**
