### PR TITLE
Admin Color Schemes: generate wp-admin color schemes from Calypso counterparts

### PR DESCRIPTION
**Pull request by frontdevde**
## Changes proposed in this Pull Request

This PR adds 9 new wp-admin color schemes based on existing Calypso color schemes.

In Jetpack these will be available to select in the wp-admin user profile when the `WordPress.com toolbar` option in the `Writing` settings section is active.

Context for this addition is that for Simple and WoA sites we need to have all Calypso color schemes available in wp-admin for the Nav unification project. For details please see https://github.com/Automattic/wp-calypso/issues/45675

All color scheme options with this change:

Screenshot 2020-11-26 at 11 15 15

## Testing instructions

**For Jetpack:**
- In the Jetpack settings ensure that in the `Writing` section the `WordPress.com toolbar` option is active
- Navigate to your user profile in `/wp-admin/profile.php`
- Check if all Calypso color schemes are present
- Compare new color schemes to their Calypso counterparts

**For WoA:**
- Use Jetpack Beta and activate `try/admin-color-schemes` branch

**For Simple:**
Tricky because we hide the wp-admin profile settings. Needs another Diff applied.
- Apply D52880 (diff for this PR) to your sandbox
- Apply D52376 (does the sync) to your sandbox
- Change color scheme settings in Calypso /me/account to Sakura
- Go to wp-admin and reload. ~~It should display in Sakura colors~~ 
Edit: color don't display anymore as the build moved from TC to Compass on svn ci (see slack-C4GAP2RHD/p1607525905317500). Double check if the path for the color scheme is as expected for simple.

## Todos / development task list

Known tasks:
- [x] Add admin theme file override for main nav background color to be different from sidebar
- [x] Add admin theme file override for current menu item icon color on hover (shouldn't change)
- [x] Add admin theme file override for selected submenu menu item color on hover (shouldn't change)
- [x] ~~Use rtl css if site is RTL~~ Remove RTL from build

 - [x] List of color schemes to port over:
   - [x] Aquatic (i.e. former Calypso Ocean) - Scaffolding
   - [x] Aquatic (i.e. former Calypso Ocean) - Refined
   - [x] Classic Blue - Scaffolding
   - [x] Classic Blue - Refined
   - [x] Classic Bright - Scaffolding
   - [x] Classic Bright - Refined
   - [x] Classic Dark - Scaffolding
   - [x] Classic Dark - Refined
   - [x] Contrast  - Scaffolding
   - [x] Contrast  - Refined
   - [x] Nightfall - Scaffolding
   - [x] Nightfall - Refined
   - [x] Powder Snow - Scaffolding
   - [x] Powder Snow - Refined
   - [x] Sakura - Scaffolding
   - [x] Sakura - Refined
   - [x] Sunset - Scaffolding
   - [x] Sunset - Refined

### CODE REVIEW

**Comment by frontdevde** [comment]
Handover notes:

- Calypso color schemes are all implemented. So far mainly tested with a Jetpack site, needs further testing within Nav Unification context.

- The build is generating RTL stylesheets but they are not being used yet.  Instead of just loading the default file in all cases `plugins_url( 'colors/classic-blue/colors.css', __FILE__ )` we might want to check for `is_rtl()` and load the RTL file instead.

- The [Jetpack team expressed interest](https://github.com/Automattic/wp-calypso/issues/47045#issuecomment-730327280) in having the admin color schemes available as a feature for all users, not just Simple and WoA. The issue I'm seeing is that right now the admin color schemes are only showing once the `WordPress.com toolbar` has been enabled. The location made sense for what we're trying to do with Nav Unification, I'm not sure that's still the case if Jetpack would like to have this as a feature for all their users.

**Comment by obenland** [comment]
> The Jetpack team expressed interest in having the admin color schemes available as a feature for all users

@jeherve Where would be a good place for this to live? I assume you'd just want this to work out of the box?

**Comment by jeherve** [comment]
> Where would be a good place for this to live?

I think it would be fine as part of the masterbar, with the rest of the changes you've been making. If folks are interested in the colors, they can enable the module.

**Comment by cpapazoglou** [comment]
- I agree that we shouldn't create `rtl` .css files.
- Regarding the place for the code, I am not sure that masterbar module is the correct place. It doesn't seem to be currently exposed / enabled to wpcom where we also need them. @obenland I guess the same applies to https://github.com/Automattic/jetpack/pull/17629 also. Do you have a plan in mind or am I missing something?

**Comment by jeherve** [comment]
> I am not sure that masterbar module is the correct place. It doesn't seem to be currently copied / enabled to wpcom where we also need color-schemes.

Noting that files don't need to be in the same location in both environments. Individual files can be kept in sync, but required differently. In Jetpack, we require the different parts of the Masterbar here, that file only getting loaded when the Masterbar module is active:
https://github.com/Automattic/jetpack/blob/80b4cca9ad6280b1f9efdae73e7898fa35574e64/modules%2Fmasterbar.php#L18-L19

On WordPress.com, we could choose to have a different loader file, pointing to the same file.

**Comment by obenland** [comment]
@jeherve @cpapazoglou I reclaimed D53264-code to sync the admin-color-scheme class to dotcom. Once that's accepted and merged, the changes in this PR can be synced.

**Comment by cpapazoglou** [comment]
@jeherve we have used a `.scss` building to `.css` process here https://github.com/Automattic/jetpack/pull/17828/files#diff-3779894f3734e15106366de177129f7cee7e6745e3ea14dfd9f0d0d205612ba6

I am afraid that we have to use plain `.css` so that this files can be synced to wpcom? Or can we just remove the gitignore rule https://github.com/Automattic/jetpack/pull/17828/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947 and make sure we commit the builded `.css` files?

**Comment by jeherve** [comment]
> @jeherve we have used a `.scss` building to `.css` process here [#17828 (files)](https://github.com/Automattic/jetpack/pull/17828/files#diff-3779894f3734e15106366de177129f7cee7e6745e3ea14dfd9f0d0d205612ba6)
> 
> I am afraid that we have to use plain `.css` so that this files can be synced to wpcom? Or can we just remove the gitignore rule [#17828 (files)](https://github.com/Automattic/jetpack/pull/17828/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) and make sure we commit the builded `.css` files?

If possible, it would be best if we didn't commit the .css file. Instead, maybe we can follow the same process we built for the Jetpack block or for Instant Search: a TeamCity test that watches for changes to the `.scss` files, builds the `.css` file, and then updates the diff with the new `.css` file.

To do this, we'd have to do a few things:
- Add the `modules/masterbar/admin-color-schemes/` directory to the Fusion list so all files in there are synced with WordPress.com, including the `.scss` files
- Update the gulp task so it builds to `_inc` instead of within `modules/masterbar`. This would ensure the css gets built in a place we can refer to in both environments, and would avoid us having to add to .gitignore.
- Add a new task to `package.json` that points to the gulp task.
- Reach out to devops to ask them to create a new TeamCity test that watches changes to specific files and run the `package.json` task you created earlier. Here is an example: p3topS-Hw-p2

**Comment by obenland** [comment]
@frontdevde I edited Jeremy's comment to be a check list and checked-off the first item.

**Comment by frontdevde** [comment]
@obenland Thanks, I just saw that and checked off the next two :)

**Comment by frontdevde** [comment]
> Reach out to devops to ask them to create a new TeamCity test that watches changes to specific files and run the package.json task you created earlier. Here is an example: p3topS-Hw-p2

Reached out in p3topS-PV-p2

**Review by cpapazoglou — APPROVED** [review]
Tested by installing the jetpack beta plugin in an Atomic site and loading this branch.


Tried all the color-schemes and they look great! We just need to apply https://github.com/Automattic/jetpack/issues/17972 after we deploy to wpcom!

LGTM! Let's just wait for reviewing in wpcom simple sites too!

**Review by marekhrabe — APPROVED** [review]
This took a fair bit of effort but I've managed to use it on all platforms without an issue.

Jetpack on my local site ✅ 
Jetpack install via Jetpack beta ✅ 
Simple ✅ 
Atomic ✅

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Pull request merged**
