### PR TITLE
Jetpack plugin structure: Revert esc_html which will break links in deprecated Identity crisis package

### PR DESCRIPTION
**Pull request by darssen**
Fixes https://github.com/Automattic/vulcan/issues/339
Fallback from #37395 
## Proposed changes:

* As explained by this [comment](https://github.com/Automattic/jetpack/pull/37395#discussion_r1601972676) some of the escaped messages included links that get broken by using `esc_html`.
* Reverted the changes for the ones that had links in them and added the `phpcs:ignore` for now.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No
## Testing instructions:

Not much to test.

### CODE REVIEW

**Comment by darssen** [comment]
@anomiex Thanks for the comment [here](https://github.com/Automattic/jetpack/pull/37395#discussion_r1601972676).
Do you think that for the remaining ones that we cannot use `esc_html` it is a good idea to add an extra `wp_kses` with the `href` tag or just add a comment explaining that it has been already sanitized prior to the filter?

**Comment by bindlegirl** [comment]
This code hasn't been in use for years but we only added deprecation notices recently (3 months ago). Personally, I would just remove the code. 

@sergeymitr what do you think? Should we clean this now that the IDC is being moved to the connection package?

**Comment by sergeymitr** [comment]
I can't think of a scenario where removing it would cause issues.
So yeah, I believe removing it is what we need.

**Comment by darssen** [comment]
Thanks @sergeymitr, @bindlegirl . Closing this one in favor of https://github.com/Automattic/jetpack/pull/37421

**Comment by anomiex** [comment]
> @anomiex Thanks for the comment [here](https://github.com/Automattic/jetpack/pull/37395#discussion_r1601972676). Do you think that for the remaining ones that we cannot use `esc_html` it is a good idea to add an extra `wp_kses` with the `href` tag or just add a comment explaining that it has been already sanitized prior to the filter?

I think the wporg plugin team would want the extra `wp_kses`, based on what they said in the email. In that case we might remove the `wp_kses` calls inside the functions in favor of the new later one at output time.

For the code here, the later `wp_kses` could even be seen as beneficial, since it will then also apply to whatever is done by the various filters I see in there. OTOH, it would also mean that the filters couldn't be used to add in any other HTML besides `<a>` tags. Depends on just what the intention is for the filters I suppose.

But in this case, removing the code as suggested later sounds better to me. 🙂

**Comment by darssen** [comment]
> > @anomiex Thanks for the comment [here](https://github.com/Automattic/jetpack/pull/37395#discussion_r1601972676). Do you think that for the remaining ones that we cannot use `esc_html` it is a good idea to add an extra `wp_kses` with the `href` tag or just add a comment explaining that it has been already sanitized prior to the filter?
> 
> I think the wporg plugin team would want the extra `wp_kses`, based on what they said in the email. In that case we might remove the `wp_kses` calls inside the functions in favor of the new later one at output time.
> 
> For the code here, the later `wp_kses` could even be seen as beneficial, since it will then also apply to whatever is done by the various filters I see in there. OTOH, it would also mean that the filters couldn't be used to add in any other HTML besides `<a>` tags. Depends on just what the intention is for the filters I suppose.
> 
> But in this case, removing the code as suggested later sounds better to me. 🙂

I did as suggested and removed the deprecated code, but many thanks for always going the extra mile and explaining things in detail.

**Pull request closed without merging**
