### PR TITLE
Enable ajax tracking for guest users

### PR DESCRIPTION
**Pull request by malithsen**
Jetpack-tracking package is being explored for the tracking needs of WooCommerce Platform Checkout. One of the limitations we've noticed in using jetpack-tracking is that `record_ajax_event` does not capture ajax events if the user is not logged in. This change uses `wp_ajax_nopriv_jetpack_tracks` action so that ajax calls from guest users also call `ajax_tracks` function. 

#### Changes proposed in this Pull Request:

* Capture ajax events from guest users to track guest user events

#### Relevant P2 thread
pdpOw2-mz-p2#comment-270

#### Does this pull request change what data or activity we track or use?

Yes

**Concerns**
I am not sure whether guest user tracking is intentionally omitted, but because this is already possible from other tracking methods (Tracking pixel, `record_user_event` in PHP) in this package, I am guessing that's not the case. 

#### Testing instructions:

* Make sure tracking scripts are [enabled](https://github.com/Automattic/jetpack/tree/master/projects/packages/tracking#1-enqueue-script) in the test site
* Add a break point inside [ajax-tracks ](https://github.com/Automattic/jetpack-tracking/blob/master/src/class-tracking.php#L73)
* Log out from the site and visit the site frontend 
* In browser's dev tools make an [ajax tracking request](https://github.com/Automattic/jetpack/tree/master/projects/packages/tracking#4-making-your-own-ajax-calls)
* Ensure that the above ajax requests hits the break point

### CODE REVIEW

**Comment by malithsen** [comment]
Hi @leogermani This is my first Jetpack PR. I added you as a reviewer as I noticed you have reviewed a PR in Jetpack-tracking in the past. Please let me know if I should assign it to someone else instead.

**Review by jeherve — COMMENTED** [review]
> Ensure that the above ajax requests hits the break point

This works for me, but I cannot seem to get the request to actually appear in the Tracks UI in MC. Does this work for you?

> GitHub Actions
> / Changelogger validity
> projects/packages/tracking/composer.json#L53
> Version mismatch, expected 1.15.x-dev but found 1.14.x-dev!
> You might use `tools/project-version.sh -f -u 1.15.0-alpha packages/tracking` or `tools/fixup-project-versions.sh` to fix this.

You'll want to run this script to fix this issue. 

> I am not sure whether guest user tracking is intentionally omitted

That's a good question. I've commented in pdpOw2-mz-p2#comment-286 with a somewhat related question.

**Comment by malithsen** [comment]
> This works for me, but I cannot seem to get the request to actually appear in the Tracks UI in MC. Does this work for you?

Hmm, I can get to it via the [live view](https://mc.a8c.com/tracks/live/?eventname=woocommerceanalytics_order_checkout_start&user=&useragent=) But for some reason, it doesn't show up when I search on the [events page](https://mc.a8c.com/tracks/events/?_status=all&_name=woocommerceanalytics_order_checkout_start) 🤔

**Comment by malithsen** [comment]
> This works for me, but I cannot seem to get the request to actually appear in the Tracks UI in MC. Does this work for you?

Hmm, I can get to it via the Live View, but it doesn't show up when searching on the Events page 🤔

**Comment by malithsen** [comment]
Closing this as per pdpOw2-mz-p2#comment-372

**Pull request closed without merging**
