### PR TITLE
Add json-api-full-management to Heartbeat

### PR DESCRIPTION
**Pull request by enejb**
Currently we are not tracking the JSON api full managment via the Jetpack heart beat API. 
This pull request tries to provide us with better stats.

### CODE REVIEW

**Comment by georgestephanis** [comment]
I'm wondering if we should do this as three values -- on, off, and unset.

**Comment by enejb** [comment]
@georgestephanis: I think maybe what would be more interesting if we would record `off - private`, because the site is private or off because it is in development mode. ( Although in that case it should not be sending data to .com. )

Right now we don't display the opt in notification for private sites. 
See https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2476

I think the goal of the data point would be to know how many sites are able to manage their site from .com. Having an off state allows to get a ratio check if the numbers add up.

**Comment by samhotchkiss** [comment]
This looks good to me, @georgestephanis, are you okay for this to be merged?  Don't want to step on your toes

**Comment by samhotchkiss** [comment]
@enejb - can you rebase so that I can merge?

Thanks!

**Comment by enejb** [comment]
A stat for managa full api has been added by @georgestephanis in https://github.com/Automattic/jetpack/commit/3dfc86d95d1a13b7e842ed0f64941535894e2d30
This PR is not useful any more.

**Comment by georgestephanis** [comment]
Yup, apologies, when I committed that I forgot this was an open PR.  Please feel free to add in the private option.

**Pull request closed without merging**
