### PR TITLE
Add a Plans comparison table

### PR DESCRIPTION
**Pull request by mattwiebe**
We will now show plans comparison tables directly in the plugin so users can begin making an informed decision about an upgrade right in their dashboard.

This builds on work already done in #8834 and #8860 to bring in the required data from the WP.com REST API

(Testing directions forthcoming when ready for review.)

#### Proposed changelog entry for your changes:

View plan features in your dashboard

### CODE REVIEW

**Comment by mattwiebe** [comment]
Remaining tasks

- [ ] use real data
- [ ] small screens
- [ ] handle current plan
- [ ] my plans tab?
- [ ] what to do with current stuff on the plans page?

**Comment by jeffgolenski** [comment]
**Design Review:**

Currently, on the plans page within the plugin I'm seeing this:

jetpack-plans-before

The plans page within the plugin is rather lengthy and I think there's some things we can do to really make it more concise and provide some better UX. 

**Quick wins:**
- Let's change the button verbiage "Start with [plan name]" to "Upgrade to [plan name]. If they're seeing this page, they're already users in some regard, so they aren't starting anything. 
- Feature verbiage: The feature titles are a little vague and inconsistent with recent changes that we've made to the pricing grid and comparison chart pages on jetpack.com. Let's work to make those as consistent and meaningful as possible. ie. "Revenue" what on earth does that mean to an end user? Nothing. It should be "Ad program."
- Add links to each feature title. I think we'd be hard-pressed to find many folks willing to upgrade their plans by just looking at these lists alone. Let's turn the feature titles into links so folks can learn more and then upgrade. If we create informational dead-ends for folks, they're less likely to upgrade. See https://jetpack.com/pricing/

screen shot 2018-02-26 at 5 30 52 pm


- Can we get rid of the unnecessary gimmick-y stuff that just adds clutter? Such as the crossed out pricing? The crossed out pricing for the personal plan ("~~$420~~ $39 per year") is way higher than the business plan (~~$348~~ $299 per year) which is just downright confusing. Let's just be straight-up with our pricing, like on Jetpack.com/pricing
- Also, can we consider trying out the monthly prices rather than the yearly? I know some testing has been done in the past, but I forget which proved to be more successful, but I know for the pro plan $29/month looks far more attractive and less intimidating than $299/year.
- Let's 

**Bigger changes:** 

Aside from the above changes to make to the current I whipped up this sketch to explore a better UX for our "my plan" page within the dash, that isn't quite so long as what we currently have:

jetpack-plans-sketch

**1) My plan**

The my plan block would quickly display which plan the user currently has (free as well), and offer a "manage plan" button

**2) Checklist**

As part of ongoing NUX work by @joanrho we're building out a Jetpack checklist to better help folks understand the value of Jetpack—more specifically the tools included with their plan. I think as a start, we should offer a small text block here that says something like:

"Jetpack offers a lot of tools. View your personalized checklist to make sure you're getting the more out of it!" [View Checklist]  (verbiage TBD cc @nicoleckohler )

**3) Plans columns**

Here the plans columns will come into play with the changes listed above. But let's remove the 3 different "see all features" buttons. They're redundant and add clutter

screen shot 2018-02-26 at 5 49 15 pm

**4) A single "see all features block"**

Let's add another quick block here where we take the 3 buttons and make them into one button that take the user to view the full feature comparison chart (https://jetpack.com/features/comparison/) so they can quickly see everything jetpack has to offer.  verbiage TBD


As always, I'm happy to help implement this stuff this week so we can get this out!

cc @rickybanister @MichaelArestad

**Comment by joanrho** [comment]
@jeffgolenski @mattwiebe Please see p6TEKc-1Qa for a related plans grid update discussion. Perhaps we can do the same thing in both places?

**Comment by nicoleckohler** [comment]
@jeffgolenski 

> Jetpack offers a lot of tools. View your personalized checklist to make sure you're getting the more out of it!

Let's consider de-emphasizing the number of tools (don't want to make it overwhelming!) and make it simple & helpful:

> Make sure you're getting the most out of Jetpack -- view your personalized checklist here.

or

> Are you making the most of your Jetpack plan? View your personalized checklist to see which features you haven't tried yet.

Something along those lines :)

**Comment by richardmuscat** [comment]
@mattwiebe this is looking great for our v1 and thanks @jeffgolenski for the feedback.

There's only a couple things from me:

- [ ] Under Personal, we should be saying "Off-site Backups" not "Real-time"
- [ ] "See all features" links should perhaps go to https://jetpack.com/pricing ?

Everything else LGTM and we can iterate for the next release. cc @bubel

**Comment by rickybanister** [comment]
In @jeffgolenski's screenshots there is no sectionNav link to 'Plans'—has the navigation been sorted out?

**Comment by mattwiebe** [comment]
> there is no sectionNav link to 'Plans'—has the navigation been sorted out?

Yes. I was running the `wcomsh` plugin for Atomic sites on my sandbox that hides it.

**Comment by nicoleckohler** [comment]
> "See all features" links should perhaps go to https://jetpack.com/pricing ?

Why would this not go to https://jetpack.com/**features**/ ?

**Comment by withinboredom** [comment]
> Can we just delete it? The tables are already providing more info about each of the features, and as Jeff said, the content on this page is very lengthy.

Seems like it would make more sense to do that in a separate PR.

**Comment by jeffgolenski** [comment]
Thanks for the feedback, @nicoleckohler @richardmuscat  and @mattwiebe + @withinboredom for conquering this.

Just to clarify one thing:

> "See all features" links should perhaps go to https://jetpack.com/pricing ?
> Why would this not go to https://jetpack.com/**features**/ ?

The "see all features" button should go to the full feature comparison chart. Not the pricing grid on the site (that's redundant) or the features page/product tour page (because that product tour page describes the feature sets and doesn't list all the features). I want to explicitly take them to the list of **all** the features. They can click each link to dig down into the landing pages and learn about each feature. 

I know the idea is to make jetpack seem simple and all that stuff, but I'm hypothesizing that will the full comparison chart, folks can see *how many* features they get with higher paid plans. Keep in mind, that if a customer is seeing this, they're already a jetpack user. Statistically, they're probably a free user and have *some* understanding of what jetpack is or does. So this entire area is designed to be an upsell for them. The comparison chart is the only tool to have that visually compares free and paid plans. That's what we want them to see.

**Comment by nicoleckohler** [comment]
@jeffgolenski you're making total sense - I actually missed your suggestion to link to the plans comparison page above, so that's my bad. :)

**Comment by jeffgolenski** [comment]
@nicoleckohler :hug:

**Comment by mattwiebe** [comment]
> Under Personal, we should be saying "Off-site Backups" not "Real-time"

Done. These are strings in the endpoint, so it can be tweaked independently of the plugin proper.

>  "See all features" links should perhaps go to https://jetpack.com/pricing

Above convo says leave it on `/features/comparison`

**Comment by jeffgolenski** [comment]
Moved the further proposed enhancements into this issue: https://github.com/Automattic/jetpack/issues/8941

**Comment by oskosk** [comment]
Cherry-picked into `branch-5.9` in 6293e6d56320f3246279cbcedc7c3298d633bd06

**Pull request merged**
