### PR TITLE
Allow PHP 7 to `composer install` inside of `plugins/jetpack` again

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes this error:

```
  Problem 1
    - symfony/deprecation-contracts is locked to version v3.0.2 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.0.2 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement.
  Problem 2
    - symfony/service-contracts is locked to version v3.0.2 and an update of this package was not requested.
    - symfony/service-contracts v3.0.2 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement.
  Problem 3
    - symfony/string is locked to version v6.0.10 and an update of this package was not requested.
    - symfony/string v6.0.10 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement.
  Problem 4
    - symfony/deprecation-contracts v3.0.2 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement.
    - symfony/console v5.4.10 requires symfony/deprecation-contracts ^2.1|^3 -> satisfiable by symfony/deprecation-contracts[v3.0.2].
    - symfony/console is locked to version v5.4.10 and an update of this package was not requested
```

Looks like this was introduced in #25047

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@Automattic/jetpack-crew What would be the best way to test for ensuring `composer install` works on PHP 7 for every pull request?

**Comment by anomiex** [comment]
> @Automattic/jetpack-crew What would be the best way to test for ensuring `composer install` works on PHP 7 for every pull request?

Probably by configuring the existing "Linting / Lock files are up to date" CI check to run with PHP 7.4 instead of 8.0.

On the other hand, to what extent to we really want to keep supporting PHP 7.4? If it weren't for renovate's "Lock file mainetnance" defaulting to that, we'd probably have long since wound up with most comopser.lock files requiring 8.0. Perhaps we should change the renovate config instead.

But then there's the fact that keeping to PHP 7.4 has the side effect of keeping `psr/container` at 1.x instead of 2.x. WooCommerce breaks if the Jetpack autoloader picks up a 2.x version of that package from somewhere (see also #17221 and woocommerce/woocommerce#33611), which comes up every once in a while when someone tries to test WooCommerce along with a development copy of Jetpack that has dev dependencies installed.

**Comment by danielbachhuber** [comment]
@anomiex Would it make sense to land this pull request while we're waiting on the results of the broader discussion?

**Review by anomiex — APPROVED** [review]
Let's go ahead with this now. But next week we may convert everything to 8.0: pdWQjU-3c-p2

**Pull request merged**
