### PR TITLE
Google Analytics: remove the module and switch to `is_active` flag

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:

- [x] Remove the GA module from Jetpack.
- [x] Only show the UI in "Jetpack -> Settings -> Traffic" for WoA sites.
- [x] Only activate tracking if it's enabled.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pfwV0U-4g-p2
https://github.com/Automattic/vulcan/issues/366

## Does this pull request change what data or activity we track or use?
No.

### Self-Hosted Site
1. Connect Jetpack. If reusing a site, delete the option: `jetpack docker wp option delete jetpack_wga`
2. Go to "Jetpack -> Settings -> Traffic", confirm that the "Google Analytics" card does not show up.
3. Go to Calypso "Tools -> Marketing -> Traffic" page, confirm the "Google" card does not show up.
4. Install and activate the GA Legacy plugin (use the ` jetpack-legacy-google-analytics.zip` file): https://github.com/Automattic/jetpack-legacy-google-analytics/releases/tag/v1.0.0
5. Go back to "Plugins", find the plugin "Jetpack Legacy Google Analytics", and click on its "Settings" link.
6. The Calypso "Tools -> Marketing -> Traffic" page will load. Find the "Google" card, and click "Connect your site to Google Analytics" to purchase the required plan.
7. After checkout, go back to that Calypso page. Confirm the GA card now shows up, and GA is disabled.
10. Activate it by clicking "Add Google". When the form unfolds, enter a measurement ID (e.g. `G-12345`).
12. Click "Save settings". Check the Jetpack option and confirm it got saved: `wp option get jetpack_wga`.
13. Reload the page, confirm the measurement ID persists.
14. Load the website frontend, confirm the measurement ID is in the source code.
15. Deactivate Google Analytics in Calypso. Confirm the tracking code and the measurement ID are no longer added to the source code.

### WoA Sites
1. Use a WoA site, checkout the branch via Jetpack Beta.
2. Go to "Jetpack -> Dashboard -> Settings -> Traffic" (`/wp-admin/admin.php?page=jetpack#/traffic`, confirm the Google Analytics card shows up. Check the "Configure..." link, confirm it leads to proper page in Calypso (the one on step 3).
3. Go to "Tools -> Marketing -> Traffic", confirm the "Google" Card shows up. Deactivate if active.
4. Check the frontend, confirm Google Analytics code doesn't show up (search source code by "Google Analytics").
5. Activate GA, enter a sample tracking code, click "Save".
6. Check the frontend again, confirm the code shows up now.

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
Works well for me on self-hosted and WoA!

I did test on Simple and my Simple site won't load with a fatal error though:

```
Fatal error: Uncaught Error: Failed opening required '/home/wpcom/public_html/wp-content/mu-plugins/jetpack-plugin/sun/modules/google-analytics.php' (include_path='.') in /home/wpcom/public_html/wp-content/mu-plugins/analytics.php:17 
```

So it looks like we need to change the path in `wpcom/wp-content/mu-plugins/analytics.php` to the mu-wpcom-plugin path instead, before this PR is merged.

**Comment by sergeymitr** [comment]
Good catch @coder-karen, I'll look into it.

**Comment by sergeymitr** [comment]
Hi @coder-karen
I fixed the Simple sites issues, can you please give it another look.

**Review by coder-karen — APPROVED** [review]
All works well for me, and Simple site loads 👍

**Pull request merged**
