### PR TITLE
RNA: export the Connection store

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
- remove the `withConnectionStatus` HOC
- export the package store ID
- modify the Connection UI package to get rid of its own connection status object, and pull the required data from the RNA Connection package store
- modify Jetpack to put the connection status from its initial state into RNA Connection package
- remove connection status handling from Jetpack Backup's state and make it rely on RNA Connection

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
_The testing is long and tedious. No functional changes, but we need to make sure all the connection flows still work properly._

_If you're testing locally, make sure you rebuild `plugins/jetpack`, `plugins/backup`, and `packages/connection-ui`.

0. Read the corresponding section in the [README.md](https://github.com/Automattic/jetpack/tree/try/rna-connection-store-export/projects/js-packages/connection#fetching-connection-status-and-other-data-from-the-store). Does everything make sense and free of typos?

##### Jetpack
1. Go to Jetpack Dashboard, disconnect if connected. Confirm that you see the connection screen.
2. Open the "Network Monitor" and reload the connection screen. Confirm that the API request to `/wp-json/jetpack/v4/connection` does NOT get sent. The RNA Connection package receives the connection status from Jetpack's initial state, so that request is excessive.
3. Connect Jetpack, confirm everything's all right.
4. Disconnect Jetpack, connect in site-only mode, go to Jetpack Dashboard. Open the "Network Monitor", click "Connect your WP.com account", confirm the `/v4/connection` API request does NOT get send, and the connection screen shows up.
5. Connect the user, confirm it goes well.
6. Log in as a separate non-admin user, connect to WP.com, confirm it works as usual.

##### Jetpack Backup
1. Disconnect if connected. You should see the connection screen.
2. Open the "Network Monitor" and reload the connection screen. Confirm that the API request to `/wp-json/jetpack/v4/connection` DOES get sent. The backup plugin no longer stores connection status in its store, and RNA Connection package loads it via the API.
3. Connect to WP.com, confirm that it works fine.
4. After you're back in Jetpack Backup, confirm that the connection status card shows up correctly (you're connected, your name and avatar are there).
5. Disconnect, confirm that you're back to the connection screen.

##### Connection Manager (connection screen with a required plan)
_If testing using JN, you're going to need [this plugin](https://gist.github.com/sergeymitr/bc005e1b893e778c03e4f43debb91c30) installed and activated._

1. Go to "Tools -> Connection Manager". You should see the new Backup connection screen. Click on "Get Jetpack Backup".
2. Go through the connection flow, confirm it works well.
3. After you're back to the Connection Manager, confirm that the connection status card shows up correctly (you're connected, your name and avatar are there).

### CODE REVIEW

**Review by fgiannar — COMMENTED** [review]
Great work here, Sergey!

I tested on a JN site using the provided instructions plus some error states and everything worked as expected :)

I only have a question: Are we planning to move `registerSite` to the state? This way for example `isRegistering` would be provided from the store and not be an internal state. That would solve the [issue](https://github.com/Automattic/jetpack/pull/21521#issuecomment-953527942) with the `ConnectScreenRequiredPlan` component having two `ConnectButton`.

**Comment by sergeymitr** [comment]
Hi @fgiannar, thanks for taking a look!
That's a good idea. We could move both `isRegistering` and `isUserConnecting` in there, for everybody to use.
Will do that now.

**Comment by sergeymitr** [comment]
Hi @fgiannar.
I adjusted the package to add `siteIsRegistering` and `userIsConnecting` into the package-wide state.
Please take another look when you can.

**Comment by leogermani** [comment]
> Hi @fgiannar. I adjusted the package to add `siteIsRegistering` and `userIsConnecting` into the package-wide state. Please take another look when you can.

I think she meant to move the whole `registerSite` action to the store. Don't you think it makes sense for it to be an action in the store?

**Comment by sergeymitr** [comment]
Thanks @leogermani, didn't realize it at first. I'll look into it a bit more.

**Review by leogermani — APPROVED** [review]
I've tested with the provided instructions and everything works fine.

I also have been looking at this in depth for the last couple of days and discussed this with Sergey. There are still some changes and improvements we want to make to the store but we agreed it's best to do them in separate PRs.

**Comment by sergeymitr** [comment]
r234902-wpcom

**Pull request merged**
