### PR TITLE
Social Media Widget: add a Google+ option.

### PR DESCRIPTION
**Pull request by jeherve**
I think Google+ would deserve its place in the core list of social networks.

As suggested here:
https://wordpress.org/support/topic/social-media-widget-genericons-no-google?replies=1&view=all

### CODE REVIEW

**Comment by dereksmart** [comment]
It works if you've created a custom username, however if you only have a numeric ID (mine is 106016569422981142354), then it won't work because the url structure is different. (doesn't have the + in it)

**Comment by jeherve** [comment]
Didn't think of that, good catch. I wonder if we should add instructions, maybe in the form of a small interrogation mark next to each service, explaining where to get the username. We could then explain the expected format for each service (for Google+, it'd be `+username` or `userid`. What do you think?

**Comment by samhotchkiss** [comment]
What if we just checked?  if( is_integer( $id ) ) { structure1 } else { structure2 }

**Comment by dereksmart** [comment]
There's always the edge-case of someone who has chosen their username to be all numbers

**Comment by jeherve** [comment]
I've committed your suggestion, @samhotchkiss, but realized that it's also an issue for the link title:

screen shot 2015-08-14 at 2 05 33 pm

I'm not sure what the best course of action is here. Now that we have the `jetpack_social_media_icons_widget_list_after` action, should we leave it to site owners to decide how to handle this?

**Comment by dereksmart** [comment]
we could break the mold and make them paste the whole URL

**Comment by jeherve** [comment]
The whole URL would still create problems for the Title value, though.

**Comment by dereksmart** [comment]
yes, it would take a refactor to a couple parts of the widget.  Not ideal obviously, but an option.

**Comment by samhotchkiss** [comment]
Punting to 3.8 because edge cases

**Comment by jeherve** [comment]
Replaced by #2654

**Comment by SamRohn** [comment]
another vote for adding G+ icon, and a Flickr icon would be nice for those of us who do not use instagram...

re: numerical value in link title tag, YouTube icon link title tag already shows numerical value instead of username, how about making the title tag the WP site name value instead of the service user name ?

**Pull request closed without merging**
