### PR TITLE
use twitter:image instead of twitter:image:src

### PR DESCRIPTION
**Pull request by niallkennedy**
Set a Twitter card image URL using `twitter:image` instead of the `twitter:image:src` structured property.

### CODE REVIEW

**Comment by kraftbj** [comment]
I can't find reference to twitter:image:src anymore on their official docs, but not seeing a reference that they deprecated it. For my own edification, do you have that handy?

**Comment by kraftbj** [comment]
:y: from me on the change. @dereksmart I marked it as 3.6 since it is a small change, but it doesn't seem src is breaking (from my own site), so no complaints from me to push to 3.7 if we're too close to code freeze.

**Comment by niallkennedy** [comment]
`twitter:image` should be used for maximum compatibility. no deprecation announcement.

**Comment by samhotchkiss** [comment]
If @niallkennedy says we should use `twitter:image`, then we probably should :)

LGTM

**Comment by kraftbj** [comment]
Oh yeah, wasn't a push back at all. Just curious since I didn't see it mentioned.

**Pull request merged**
