### PR TITLE
Settings UI - Non admin: refresh view after unlink. Don't show features if site disconnected

### LINKED ISSUE #5145: Admin Page Stats: do not show link to WordPress.com when user isn't linked
#### Steps to reproduce the issue
1. Start with a Jetpack site with 2 admin users.
2. Log in with the first user, connect Jetpack to WordPress.com.
3. Log out.
4. Log back in with the second user, go to the Jetpack dashboard.
5. You'll see the message inviting you to link your account to WordPress.com. You'll also see the stats graph, with 2 buttons: 'Old Stats', and the button to view the stats on WordPress.com.

Since that account isn't linked to WordPress.com, that second button is confusing, as it won't work.

I'd suggest removing the second button until the user is linked to WordPress.com.

### LINKED ISSUE #6464: Settings UI: when site is not connected and user can't do it, main content shows
#### Steps to reproduce the issue
1. disconnect the Jetpack site
2. log in as a user with role other than admin

#### What I expected
Nothing to be displayed

#### What happened instead
captura de pantalla 2017-02-21 a las 15 58 05

### LINKED ISSUE #6465: Settings UI: when site is connected and non admin unlinked, main content shows
#### Steps to reproduce the issue
1. in a connected Jetpack site, log in as a non admin user

#### What I expected
Some notice prompting me to connect.

#### What happened instead
The notice is displayed, but content is displayed as well. In this example the user role was editor.

captura de pantalla 2017-02-21 a las 16 03 32

### LINKED ISSUE #6466: Settings UI: clicking "Unlink me from..." link doesn't refresh view
#### Steps to reproduce the issue
1. connect the Jetpack site
2. login as a non admin user and link the user if necessary
3. in At a Glance, in the Connections section, click "Unlink me from WordPress.com"

#### What I expected
The view to be refreshed and show the linking UI.

#### What happened instead
The view wasn't updated in its entirety. Only the card showing the user link is updated. As soon as you click a different tab like Apps or Plans, the view is updated.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6464
Fixes #6466 props @oskosk 

#### Changes proposed in this Pull Request:

* remove usage of `window.Initial_State`.
* if non admin users unlink their accounts, the view is refreshed.
* if site is not connected and user can't do it, show notice prompting user to ask an admin to connect and don't show link button.

captura de pantalla 2017-02-23 a las 18 49 07

#### Testing instructions:

* Disconnect site and log with non admin: it should display a notice prompting to ask admin to connect the site.
* Disconnect site, the view should be refreshed

### CODE REVIEW

**Comment by dereksmart** [comment]
> Previously, the unlinked admin could view stats

This is very much intentional, and I would be hesitant (opposed) to require a connection to view the site stats within the wp-admin.  This is the same for the rest of the content that we currently show (and showed before) in the prior UI and also in the wp-admin main dashboard widget.

**Comment by eliorivero** [comment]
Ok

**Comment by eliorivero** [comment]
What Derek mentioned has been restored now.

**Comment by oskosk** [comment]
@eliorivero @dereksmart  I think the cause of your headache yesterday is the following

1. With a non-admin linked user, after disconnecting, the NondAdminView does not update to reflect the unlinked state. The thing is that 

`<NonAdminView />` is getting `isLinked={ true }` **always** among its props passed by its parent (`<Main />` )

screen shot 2017-02-22 at 9 02 27 am

Even when its parent `<Main />` is getting a `isLinked={ false }` from redux state after unlinking the user.

screen shot 2017-02-22 at 9 02 35 am

The problem here is that we used the lifecycle method `shouldComponentUpdate()` in `<Main />`.
And this method only returns `true` on some particular conditions. Changing the link state for a user is not among those conditions.

screen shot 2017-02-22 at 9 02 44 am

What this causes is that even when `<Main />` knows by its props that the user is now not linked, it doesn't re-render (because `shouldComponentUpdate()` returns `false` ) and thus, its children don't get the new props because they're not re-rendered. 

Something like this could work:

image


I've just added a commit, including this condition to the `shouldComponentUpdate()` and it works like this now.

unlinkme

**Comment by eliorivero** [comment]
Gracias @oskosk for checking and fixing this! 👍

**Comment by dereksmart** [comment]
When I enabled stats to be visible by Editors, I expected to be able to see them, but I'm only seeing a connect page 

screen shot 2017-02-22 at 10 18 45 am

screen shot 2017-02-22 at 10 19 53 am

**Comment by dereksmart** [comment]
If we're showing a dedicated connect/link page for non-admins, shouldn't we be removing the features from the promotional stuff that includes things they can't activate/deactivate, or may not have access to?

**Comment by eliorivero** [comment]
Updated this PR to do only 2 things: don't show features when site is disconnected (and display a warning prompting user to ask admin to connected) and refresh the view after non admin unlink.

**Comment by dereksmart** [comment]
Tested, and works as expected, considering the latest changes: 
> don't show features when site is disconnected (and display a warning prompting user to ask admin to connected) and refresh the view after non admin unlink.

Code looks good.  🐑

**Pull request merged**
