### PR TITLE
Sync: Fix Trying to get property of non-object in sync/class.jetpack-sync-module-posts.php

### LINKED ISSUE #7156: Sync: PHP notice on module-posts
```
PHP Notice: Trying to get property of non-object in /../wp-content/plugins/jetpack/sync/class.jetpack-sync-module-posts.php on line 126
```

Reported here:
https://wordpress.org/support/topic/property-of-non-object-in-class-jetpack-sync-module-posts-php/

### LINKED ISSUE #8137: Undefined index in class.jetpack-sync-functions.php
First reported in a forum thread: https://wordpress.org/support/topic/notice-undefined-index-48/

> Only in the administration area – Intermittent error:
> Notice: Undefined index: scheme in /xxxxxx/plugins/jetpack/sync/class.jetpack-sync-functions.php on line 210

> apache.error.log :
>PHP Notice: Undefined index: scheme in /xxx/plugins/jetpack/sync/class.jetpack-sync-functions.php on line 210\n', referer: https://xxxx/wp-admin/post.php?post=xxxxx&action=edit
> PHP Notice: Undefined index: scheme in /xxx/plugins/jetpack/sync/class.jetpack-sync-functions.php on line 210\n', referer: https://xxx/wp-admin/post-new.php

### PR DESCRIPTION
**Pull request by Umangvaghela**
Fixes #8137
Fixes #7156

#### Changes proposed in this Pull Request:

*  In this file directly call $post->post_type so it given error. If We update the code so we overcome the problem.

#### Testing instructions:

*

### CODE REVIEW

**Comment by Umangvaghela** [comment]
@jeherve, @oskosk 

Greetings !!!

Hello sir,

Can you review this PR and told me just it is fine and required or not.

Thanks

**Comment by jeherve** [comment]
@Umangvaghela Any reason why you closed this PR?

**Comment by Umangvaghela** [comment]
@jeherve 

Sir, nobody can review this PR that's why I close the PR.

**Comment by jeherve** [comment]
> nobody can review this PR that's why I close the PR.
 
As you can see the PR uses the label "[Status] Needs Review". That means that it is on our roadmap of things to look at. We will look at it and review it at some point in the future, and update this PR when we do so.

Until then, you can leave the PR as it is, you don't need to do anything with it.

Thank you for your patience.

**Pull request merged**
