### PR TITLE
Jetpack: Use Blog ID in links to WPCOM instead of site slug

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:
Make links and redirects to WPCOM in Jetpack plugin use blog ID instead of slug for multi-URL support.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pf5801-93-p2

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:

To test the blog, you'll need two domains pointing to the same site. One way to do that is to setup two proxying tunnels to the same local environment.

**Connect Jetpack with a free plan on URL A, and load it via URL B.**

If your site falls into IDC due to concurrency issues with IDC secret validation (fix pending), remove `jetpack_sync_error_idc` option.

**The Dashboard**
1. Go to Jetpack Dashboard, scroll to the "Comprehensive Site Security" and click "Learn More".
2. The `jetpack.com` page should have `site=[blog_id]` in GET-parameters.
3. Click "Secure your site" and confirm that you are taken to the checkout page with "Jetpack Security" plan added in the cart. The checkout page URL should contain URL A. Do not purchase the plan yet.
4. Click "Upgrade" on the same banner. You should see the "Security" upsell page.
5. Click "Add Security" button and confirm you're taken to the Checkout with URL A in the page URL.
6. Go back to the Jetpack Dashboard and click on the "Plans" tab in the top navigation. Confirm it takes you to `https://cloud.jetpack.com/pricing/[your-blog-id]`.
7. Switch to the "My Plan" tab, click on the external links, confirm that they work and URL A (or blog ID) is used in the URL instead of blog slug.
8. Scroll down to "We’re here to help" and click "Upgrade". Confirm you're taken to Checkout and "Jetpack Security" is in the cart. Confirm the URL A slug is present in the page URL.
9. Go to the "Recommendations" tab and click on the "View Security Products" button. Confirm the checkout buttons use blog ID's and lead to proper checkout page for URL A.

**The Settings**
_Some "Upgrade" buttons will not work for URL B because they work through "My Jetpack" upsell page. We will address that in a separate PR._

1. Go to "Jetpack Settings -> Performance -> Search" and click "Upgrade", then any of the "Get..." buttons. Confirm you're taken to the proper Checkout page.
2. Go to "Traffic -> Google Analytics" and click "Upgrade". Confirm you're taken to the proper Checkout page.
3. Go to "Monitize" tab and check "Upgrade" buttons for "Ads" and "Collect PayPal payments", confirm they take you to proper Checkout page with "Creator" product added.
4. Same "Monitize" tab, check the "Accept donations and tips" and "Collect payments" cards for the "Enable..." links in the bottom. Confirm they lead to proper Calypso pages.
5. Go to "Share" tab, activate "Jetpack Social connections" and "Sharing buttons". Click "Connect..." and "Configure..." links in the bottom of the cards. Confirm they take you to proper Calypso pages.

**Checkout**
1. Load the site using URL B (not cache site main URL).
2. Visit a random checkout link that doesn't go through "My Jetpack" (no `my-jetpack` in the URL).
3. Purchase a product, confirm it went well and you got redirected back to the proper post-checkout page on URL A (cache site main URL).

### CODE REVIEW

**Comment by bindlegirl** [comment]
Most of the stuff I checked so far looks good (stuff that doesn't will most likely work when I check My Jetpack PR). I did run into trouble with "Manage all subscribers" link in Jetpack Newsletter Settings. Should that get updated as well?

**Comment by sergeymitr** [comment]
Hi @bindlegirl, thanks for taking a look!
Good find, fixed now. Can you please give it another run when you get a chance?

**Comment by bindlegirl** [comment]
Subscribers menu link still has the same problem. This part may need checking https://github.com/Automattic/jetpack/blob/0f70c4ed3ac8d90761ef59d34a726d6419a5604c/projects/plugins/jetpack/modules/subscriptions.php#L1129

Will the wpcom masterbar modul need some updates to display the correct site too?

Also, the Get Stats button needs an updated link (or is that a My Jetpack part?)

**Comment by sergeymitr** [comment]
I updated the "Subscribers" and Masterbar links, thanks for pointing that out!
The "Manage Purchases" link was already broken though, so adjusting it didn't fix it. I'll address it in a separate PR if you don't mind, don't want it stalling this one.

**Review by bindlegirl — APPROVED** [review]
Rechecked and it's looking good now. We can address the Wordpress.com toolbar in a separate PR

**Pull request merged**
