### PR TITLE
Jetpack: Update WAF settings UI to allow toggling of automatic and manual rules independently

### PR DESCRIPTION
**Pull request by nateweller**
#### Changes proposed in this Pull Request:

* Updates the Jetpack Firewall settings UI to use the new automatic/manual rules toggling pattern.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

peb6dq-hs-p2

1201069996155224-as-1203286905507161

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Go to `/wp-admin/admin.php?page=jetpack#/settings`
* Validate that the module can still be enabled and disabled by the primary firewall toggle.
* Validate that automatic rules can not be toggled when the site does not have a scan plan.
* Validate that automatic rules can be toggled on and off.

#### Screenshots

Screen Shot 2022-12-06 at 2 28 55 PM

### CODE REVIEW

**Comment by dkmyta** [comment]
It seems that when the Firewall module is activated, but no other settings are toggled, we are still blocking requests if we have an appropriate plan (for example `?test=<script>`) - is that expected?

**Comment by dkmyta** [comment]
One minor nitpick - when you do not have a plan, the Automatic rules toggle is disabled, however, the accompanying text still has `cursor: pointer` hover effect making it seems as though it's clickable.

**Comment by nateweller** [comment]
> It seems that when the Firewall module is activated, but no other settings are toggled, we are still blocking requests if we have an appropriate plan (for example `?test=<script>`) - is that expected?

@dkmyta This should not be the case! Was this on a fresh JN site, or an existing site that already had the firewall module enabled? May be an issue with the backwards compatibility of these changes. Thanks for catching this :+1:

**Comment by dkmyta** [comment]
>Was this on a fresh JN site, or an existing site that already had the firewall module enabled? May be an issue with the backwards compatibility of these changes.

This was on an existing site on which I had recently tested some other related WAF PRs. I had thought that I had set everything back to default in advance but there certainly could have been some settings still in place so I'd say you are on the right track with it being an issue with backward compatibility.

**Comment by nateweller** [comment]
@dkmyta I've refactored my approach to backwards compat, so this should work much better now!

Testing instructions for backwards compatibility:
- To simulate a site that hasn't had this update applied, first run `jetpack docker wp option delete jetpack_waf_automatic_rules`.
- Set up your site with `trunk` so that the WAF module is enabled, Scan plan, and automatic rules don't exist.
- Verify a request is blocked.
- Update to this branch.
- Verify a request is still blocked.
- Verify the automatic rules toggled is enabled by default.
- Turn off manual rules.
- Verify the request is no longer blocked.
- Verify the `jetpack_waf_automatic_rules` value is `1`. You can run this with `jetpack docker wp option get jetpack_waf_automatic_rules`.

And then the original PR testing instructions on a JN site running this branch from the get go :+1:

**Comment by dkmyta** [comment]
Works great and addresses all prior issues! 

However, I uncovered a new issue in testing that we will certainly want to address both here and in Protect - when a user upgrades, toggles automatic rules on, then downgrades, automatic rules remain toggled on even though the ability to toggle it is effectively disabled. In this situation, as long as the Firewall module remains enabled the automatic rules continue to run.

**Comment by nateweller** [comment]
> However, I uncovered a new issue in testing that we will certainly want to address both here and in Protect - when a user upgrades, toggles automatic rules on, then downgrades, automatic rules remain toggled on even though the ability to toggle it is effectively disabled. In this situation, as long as the Firewall module remains enabled the automatic rules continue to run.

Really good point... as soon as `hasRequiredPlan` is `false`, the toggle will appear as off and disabled but the rules will not update until the next cron is run. We might want to add a call to `/update-rules` on plan cancellation/downgrade as well, similar to how we do on purchase.

**Comment by nateweller** [comment]
After some team discussion, we're going to pursue making sure the automatic rules are still available and toggle-able even after the plan expires or is cancelled. I'll have to make a couple updates to the package and the plugin to handle this, moving this back to in progress :+1:

**Comment by nateweller** [comment]
Will pick this one back up after https://github.com/Automattic/jetpack/pull/28049 and https://github.com/Automattic/jetpack/pull/28027 are in trunk :+1:

**Comment by nateweller** [comment]
Blocking PRs merged, pulled the latest from the project branch, and fixed some lingering issues.

Ready for re-review!

**Comment by dkmyta** [comment]
It would appear that automatic rules are still being enabled and included by default. On a fresh install with a Scan plan, when I activate the WAF module via Jetpack settings, I can see the `rules` directory is properly generated in the `/wp-content/jetpack-waf` folder but immediately includes the `require` for the `automatic-rules.php` file. In the UI, the initial toggling of the WAF module renders the correct display - the module is on, but all settings with the exception of the share data, show as disabled, however, automatic rules are running and upon refreshing the page, the automatic rule setting is toggled on.

I believe we now have a separate task dedicated to handling situations where the `rules` directory is manually deleted but I'd also like to note here that when we remove the `rules` directory generated by activating Protect, it will produce the same `Failed to empty rules.php file.` fatal error we've seen previously in Jetpack (this time without proper error handling) if/when we activate Jetpack.

**Comment by nateweller** [comment]
@dkmyta Thanks for catching these issues! I've fixed both the auto-enabling of automatic rules, and addressed the "failed to empty rules.php" issue as well.

**Review by dkmyta — APPROVED** [review]
Works perfectly!

**Pull request merged**
