### PR TITLE
Settings - Newsletter, Sharing: Disabling options for sites missing user connection

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Fixes https://github.com/Automattic/jetpack-marketing/issues/1023

## Proposed changes:

* make sure that visually disabled elements receive HTML `disabled` property
* replace `unavailableInSiteConnectionMode` with `hasConnectedOwner` to enable options if the site has any connected user (also other than the current user)
* fix `save` button label when the button is disabled and not saving

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Create a JN instance from this branch
* Connect Jetpck but not the user
* Go to `/wp-admin/admin.php?page=jetpack#/newsletter` and you should see disabled controls that you can't toggle (not only CSS disabled)
* Do the same for the first option of `Sharing` settings section
* Create another user and connect that user
* Go back to the main user, and verify that you can change and save options in the Newsletter tab
* Verify that Sharing is also interactive

After the change, before connecting a user:
SCR-20241004-obap
SCR-20241004-njxe
After connecting a user:
SCR-20241004-nkxf

### CODE REVIEW

**Review by elliottprogrammer — DISMISSED** [review]
Tested, works good as described.
Just a note that screenshots would have been helpful to accompany the testing instructions.  Because as per instruction, "and you shouldn't see disabled controls.", there were a lot of other disabled controls on the screen and it was difficult to discern at first, which control you are referring to that should not be disabled.
Other than that, code changes look all good! 😃
LGTM! 👍

**Review by CodeyGuyDylan — DISMISSED** [review]
These changes look great! Jetpack Social has a similar issue
image
Where the toggle on that is clickable. Would you want to handle that as well in this PR or would you like to handle that separately?

Other than that question, the code changes look good and it tests well, so I'll approve this and you can decide whether to fix social here or separately

**Comment by grzegorz-cp** [comment]
I can tackle Social here as well, and I'll add screenshots. Based on the discussion (pbNhbs-bMC-p2), I will change this to disable the controls in a visually disabled state.

**Comment by grzegorz-cp** [comment]
I updated everything to the latest specs, and both the newsletter and sharing settings are ready for testing.

**Review by IanRamosC — APPROVED** [review]
Looks good and test well. I tested it based on the latest specs and it works as expected.

**Pull request merged**
