### PR TITLE
Pay with PayPal: Use post GUID as `postLinkUrl` attribute

### LINKED ISSUE #20724: Pay with PayPal Block: Editor gets dirty after post publishing
#### Steps to reproduce the issue

1. Make sure permalinks using a non-plain format (wp-admin > settings > permalinks)
2. Create a post with "Pay with PayPal" block. 
3. Switch to the code editor, note the `href` attribute, which looks like this: `href="https://thoughtful-dingo.jurassic.ninja/?p=64"`
3. Publish the post.
4. Note that post-publish panel is not shown after the publish.
5. Note that the editor has unsaved changes (try to navigate away from the editor, alert will be shown)
6. Switch to the code editor, discover that URL has changed: `href="https://thoughtful-dingo.jurassic.ninja/2021/08/13/64/"`

Apparently, block content gets updated _after_ post is published, basically to update post URL from draft, to actual URL. This leads to few issues:
- Editor become dirty, meaning a user would need to save/update before safely leaving the editor
- Due to the changes in a block, post-publish panel not displayed. 

**Screenshots**

https://user-images.githubusercontent.com/5654161/129692630-9cd188dc-3664-4e7b-9a7b-dbdcb0b89581.mp4

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/20724

#### Changes proposed in this Pull Request:

Updates the `postLinkUrl` attribute of the Pay with PayPal block so it uses the immutable post GUID (which also works as the post URL) to prevent the editor from becoming dirty after publishing a post.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- [Spin up a JN site running the branch of this PR](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack=fix/pay-with-paypal-post-url).
- Set up Jetpack with a Security plan.
- Go to Posts > Add new.
- Insert a Pay with PayPal block.
- Publish the post.
- Make sure it doesn't become dirty (there shouldn't be any unsaved change).
- Switch to the code editor.
- Note the href attribute.
- Make sure it matches the permalink plain format (`<DOMAIN>?p=<POST_ID>`).

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
This isn't working for me on a wpcom site.

 1. Open the Gutenberg post editor for a fresh new post (/wp-admin/post-new.php)
 2. Add a paypal block, fill in email, price and title
 3. Switch to code view
 4. See the href is `https://deanpremiumtest.wordpress.com/?p=10991099undefined`
 5. Publish, see the post address  is `https://deanpremiumtest.wordpress.com/2022/09/06/1099/`
 6. Switch back to visual view, then back to code editor
 7. See href is updated to https://deanpremiumtest.wordpress.com/2022/09/06/1099/
 8. Post is still marked dirty

I wondered if not using the code editor made a difference - it didn't. I also wondered if adding a post title before publishing made a difference - it didn't.

**Comment by dsas** [comment]
Here's a video where I de-selected the block too in case that made a difference:

https://user-images.githubusercontent.com/93301/188727153-0364c615-ac9b-4675-b614-3ce6449c8c96.mp4

**Comment by rcrdortiz** [comment]
This also isn't working for me a newly created JN site:
Captura de Pantalla 2022-09-07 a las 7 57 59

**Comment by mmtr** [comment]
I changed the approach to use the post GUID instead which is always immutable and it also works as the post URL, so this should be ready for review again.

**Comment by rcrdortiz** [comment]
It's working as expected for me now.

**Review by rcrdortiz — APPROVED** [review]

**Comment by BogdanUngureanu** [comment]
LGTM! The only thing I've noticed is that when you switch between visual and code editor, the block resets 😓 It's not a regression though, since it's happening on trunk too.

https://user-images.githubusercontent.com/995955/189149563-5d17fc91-07b2-4d89-889d-75e423542ea6.mov

**Comment by lukaszwilczakwilnet** [comment]
Screenshot 2022-09-09 at 09 26 31
It works now as expected.

**Review by Copons — APPROVED** [review]

**Comment by Copons** [comment]
Approved this, it should be good to go after the rebase, and you shouldn't need another ✅, but ping me again in case. 🙂

**Comment by mmtr** [comment]
r252331-wpcom

**Pull request merged**
