### PR TITLE
Shortcopy: modify jumpstarted features

### LINKED ISSUE #11556: Shortcopy: update list of modules included in Jumpstart
We are reducing the number of modules included in Jumpstart (Recommended Features) to the minimum Security and Performance essentials:

**BEFORE:**
- Carousel
- Contact Form
- Gravatar Hovercards
- Sharing
- Subscriptions
- Lazy-images
- Monitor
- Photon
- Related-posts
- SSO
- Tiled-gallery

**AFTER:**
- Static File Hosting
- Image Hosting (Photon)
- Lazy Loading Images (Lazy-images)
- XML Sitemaps
- Downtime Monitoring (Monitor)
- SSO

ref: p1HpG7-6qm-p2

### PR DESCRIPTION
**Pull request by eliorivero**
This PR updates the modules that will be activated when the user chooses to Jumpstart the site. This is part of the shift towards security and performance.

Fixes #11556

#### Changes proposed in this Pull Request:

* Update modules that will be jumpstarted

#### Testing instructions:

* Create a new site
* Setup Jetpack
* go back and choose to Jumpstart the features
* verify that the features were activated

#### Proposed changelog entry for your changes:

* not needed. Part of Shortcopy.

### CODE REVIEW

**Comment by oskosk** [comment]
We probalby need to rebuild module headers after these changes

**Review by keoshi — DISMISSED** [review]
This worked beautifully for me, activating the following modules: Asset CDN, Image CDN, Lazy Images, Monitor, Secure Sign On, and Sitemaps.

🛳

**Comment by oskosk** [comment]
@eliorivero I just pushed a commit with the changes after running `npx gulp php:module-headings`.

**Comment by oskosk** [comment]
Also I already deployed  D25531-code to sync the code

**Review by oskosk — CHANGES_REQUESTED** [review]
When testing this PR, I noticed that some of the modules that are being removed from Jumpstart here were activated anyways...

After jumpstarting 

* Contact Form was activated
* Gravatar Hovercards was activated Sharing was activated
* Subscriptions was activated

Althought the thing is that they were activated on connection, not by me clicking the Jumpstart button.

Should we remove `Auto Activate: Yes` from them ?

**Comment by dereksmart** [comment]
@oskosk that pretty much means that they were useless in Jumpstart before. This iteration we're not touching auto activated, so let's leave them as that.

**Review by oskosk — APPROVED** [review]
LGTM works as expected if the modules are deactivated by hand before jumpstarting!

**Pull request merged**
