### PR TITLE
Try/actions conditionals2

### PR DESCRIPTION
**Pull request by kbrown9**
Fixes #

#### Changes proposed in this Pull Request:

*

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Go to '..'
*

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by dereksmart — DISMISSED** [review]
test

**Review by dereksmart — DISMISSED** [review]
test

**Review by dereksmart — DISMISSED** [review]
approval

**Review by dereksmart — DISMISSED** [review]
Let's see what happens

**Review by dereksmart — DISMISSED** [review]
all good

**Review by dereksmart — DISMISSED** [review]
gud

**Review by dereksmart — DISMISSED** [review]
hi again

**Review by dereksmart — APPROVED** [review]
Approve final

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]
changes

**Review by dereksmart — DISMISSED** [review]
changes

**Review by dereksmart — CHANGES_REQUESTED** [review]
request

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]

**Review by dereksmart — DISMISSED** [review]
request changes

**Review by jeherve — APPROVED** [review]
approving now?

**Review by jeherve — DISMISSED** [review]
requesting changes now

**Review by dereksmart — CHANGES_REQUESTED** [review]
Request change

**Comment by dereksmart** [comment]
We're done testing this :)

**Pull request closed without merging**
