### PR TITLE
Gardening: avoid duplicated runs of the action

### LINKED ISSUE #19099: Actions: avoid duplicate Gardening comments
When creating a new PR, you often end up triggering [the Gardening task that check the PR description twice](https://github.com/Automattic/jetpack/blob/12a6d0d94eed577940707653ecd3b74f898c028c/.github/actions/repo-gardening/src/index.js#L33-L37):
- Once when the `pull_request` is opened.
- Once when the `pull_request` is labeled (even though you most likely added the labels as you created the PR).

As a result, the 2 actions run concurrently, and 2 comments are created because when each task checks for an existing comment, they do not find one yet.
See the example below, triggered when I created a Pull Request (I had added some labels before I submitted my pull request):

- Pull request opened: `Tue, 09 Mar 2021 13:29:02 GMT main: Received event = 'pull_request', action = 'opened'` -- https://github.com/Automattic/jetpack/runs/2066899454?check_suite_focus=true
- Pull request labeled: `Tue, 09 Mar 2021 13:29:02 GMT
main: Received event = 'pull_request', action = 'labeled'` -- https://github.com/Automattic/jetpack/runs/2066899578?check_suite_focus=true

We need the task to be triggered when we open PRs, and we also need it to be triggered when we label PRs, so we can't get rid of one of the triggers.

But somehow, we should be able to either:
1. Check for existing runs of the same action and wait until they complete.
2. Cancel duplicate runs. I don't think this would be a good option here as we don't want to accidentally cancel a run that's checking something else in the Gardening action:
https://github.com/Automattic/jetpack/blob/12a6d0d94eed577940707653ecd3b74f898c028c/.github/actions/repo-gardening/src/index.js#L19-L37

I'm not quite sure how to go about that yet. I wonder if I would be able to rely on https://github.com/actions/toolkit/pull/149.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #19099

#### Changes proposed in this Pull Request:

Such runs can end up conflicting with each other, as outlined in the issue above.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Examine actions for this PR, which will be created with some labels already.

### CODE REVIEW

**Comment by jeherve** [comment]
The following runs were created for this PR:
- Opening the PR: https://github.com/Automattic/jetpack/actions/runs/646976512 -- completed. The comment was added and the label and assignment was added to #19099.

- Labeling the PR: https://github.com/Automattic/jetpack/actions/runs/646976523
- Labeling the PR: https://github.com/Automattic/jetpack/actions/runs/646976525
- Labeling the PR: https://github.com/Automattic/jetpack/actions/runs/646976526
- Labeling the PR: https://github.com/Automattic/jetpack/actions/runs/646976531

All those were cancelled because it took more than a minute for the run to complete (since it was waiting for run 1 to finish). I'll allow more time for the action to complete, so those can complete too.

**Comment by jeherve** [comment]
> I'll allow more time for the action to complete, so those can complete too.

Did that in ec1a6616eeb463bb38e4dab612534ffee082f3d8. I gave it 10 minutes; I'm not sure if this was too generous, but that seemed safe.

This last action completed successfully:
https://github.com/Automattic/jetpack/actions/runs/646994385

**Review by anomiex — APPROVED** [review]
Looks ok to me. I've been considering increasing the time limit here anyway since the build seems to have gotten to more than just a few seconds.

On the other hand, you might consider doing what I did in the "Push to mirror repos" job in build.yml: instead of setting a time limit on the whole job, set a time limit on each step except the turnstyle step.

**Comment by jeherve** [comment]
> On the other hand, you might consider doing what I did in the "Push to mirror repos" job in build.yml: instead of setting a time limit on the whole job, set a time limit on each step except the turnstyle step.

That makes sense. I think I'll leave it with just one `timeout-minutes` for now, since it seems to do the trick and may be easier to quickly parse for folks who are looking at the action for the first time.

**Pull request merged**
