### PR TITLE
Add P2 organization identifier to site SAL

### PR DESCRIPTION
**Pull request by unDemian**
Summary: Fixes 1542-gh-p2 by adding P2 `organization_id` to sites' details.

Test Plan:
Sites' info should contain P2 organization_id if requested

```
## cURL
curl "https://[private link].2/me/sites?http_envelope=1&site_visibility=all&include_domain_only=true&site_activity=active&fields=ID,name,organization_id" \
     -H 'Authority: [private link]' \
     -H 'Accept: */*'
```

Reviewers: aerych, #lighthouse_team, migueluy

Reviewed By: #lighthouse_team, migueluy

Subscribers: migueluy

Tags: #touches_jetpack_files

Differential Revision: D53881-code

This commit syncs r217904-wpcom.

### CODE REVIEW

**Comment by kraftbj** [comment]
I fixed the valid PHPCS issue (no docblock for the new method), but there's a glitch in our new action for checking for changed PHP files. We're getting that fixed up and can merge this soon thereafter. I'll keep an eye on it and get it in.

**Comment by unDemian** [comment]
Thank you

**Review by jeherve — DISMISSED** [review]
We may have to add a method to `sal/class.json-api-site-jetpack.php` as well.

**Comment by kraftbj** [comment]
@unDemian Sorry for the mess. We've fixed the CI issue and brought that into this branch for the sake of the tests.

There were a couple PHPCS violations that I fixed and merged to WP.com, so everything should pass.

Only thing is the question from @jeherve regarding if there is a need to implement this method in the Jetpack class. When p2s are self-hosted, will there be a need to grab an ID that isn't 0? Or is that something for further down the road?

If this isn't a concern, please merge this PR. If that's something to implement, please do and mark for review when you're ready.

Thanks!

**Review by kraftbj — APPROVED** [review]

**Comment by unDemian** [comment]
> We may have to add a method to sal/class.json-api-site-jetpack.php as well.

@lezama ^ I don't know why I removed that 🙂

**Comment by unDemian** [comment]
> @unDemian Sorry for the mess. We've fixed the CI issue and brought that into this branch for the sake of the tests.

No worries, thanks for the help.

**Comment by kraftbj** [comment]
@unDemian Did you mean to close this?

**Comment by unDemian** [comment]
> @unDemian Did you mean to close this?

Not really 🙂

**Comment by unDemian** [comment]
> If this isn't a concern, please merge this PR. If that's something to implement, please do and mark for review when you're ready.

I'll merge this as Jetpack support for `organization_id` is not a concern at the moment, we will revisit. Thanks for all your help

**Pull request merged**
