### PR TITLE
Admin: Update search module card to better match Calypso

### LINKED ISSUE #8733: Search settings panel missing clear "Add Search Widget" action
At wp-admin I didn't realise _"Jetpack Search widget to your sidebar."_-text was a link:

image

In Calypso there is a much nicer action button, we should bring that over to wp-admin as well:
image

Both link to **Widgets page** at wp-admin; even the wp.com one. We could link to **Customizer** instead. Now when I click this at Calypso, I have to jump to wp-admin whereas if it would open Customizer, I would stay at Calypso.

Kinda related to: #8712 _Search: Clarify search widget name_

### PR DESCRIPTION
**Pull request by Viper007Bond**
Fixes #8733

#### Changes proposed in this Pull Request:

Updates the search module card to better match Calypso.

**Before:**

firefox_2018-02-13_20-46-28

**After:**

firefox_2018-02-13_19-41-19

### CODE REVIEW

**Comment by oskosk** [comment]
Looks good. Note that Calypso card looks like this actually

image

**Comment by Viper007Bond** [comment]
Good catch on the missing extra description text. I'l add it.

And I tweaked the very bottom text to distinguish from the regular search widget.

**Comment by Viper007Bond** [comment]
firefox_2018-02-14_19-00-31

**Comment by rickybanister** [comment]
Looks good. I like the calypso clickable card text better, but understand it might be confused with the regular search widget.

Can we make them both say `Add Jetpack search widget` without the quotes or parens? I think it will be obvious once they get to the customizer which widget it is. 

@oskosk do you think we can make that same change to calypso to keep them in sync?

**Pull request merged**
