### PR TITLE
Related Posts: Add unit tests

### PR DESCRIPTION
**Pull request by stacimc**
#### Changes proposed in this Pull Request:

* Pulls settings out of the block into a Controls component for simplification/separate testing
* Adds tests

#### Jetpack product discussion

p1HpG7-b3G-p2

#### Testing instructions:

* Run tests from the projects/plugins/jetpack folder with:
```
yarn jest extensions/blocks/related-posts/test/edit.js
yarn jest extensions/blocks/related-posts/test/controls.js
yarn jest extensions/blocks/related-posts/test/validate.js
```
* Manually test the Related Posts block, especially focusing on updating attributes in the Inspector controls and block toolbar.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
✅ Tests look good
✅ Fired up site in Jurassic tube and played around with the block in the editor. Attributes/block toolbar options work as expected

Mar-10-2021 10-11-21

Unrelated to this PR, only documenting here:

When there are not enough related posts to render the block on the site, the module js throws an [error here](https://github.com/Automattic/jetpack/blob/1b1419ed8dbbc0626408f61143ef6a5b585247a6/projects/plugins/jetpack/modules/related-posts/related-posts.js#L42)

Screen Shot 2021-03-10 at 10 22 25 am

Checking for the element `relatedPosts && relatedPosts.hasAttribute( 'data-exclude' )` should take care of it.

**Review by jeherve — DISMISSED** [review]
This tests well for me. 🚢

**Comment by stacimc** [comment]
Rebased because of failing PHP tests.

**Review by jeherve — APPROVED** [review]

**Comment by stacimc** [comment]
Deployed: r222854

**Pull request merged**
