### PR TITLE
Social Menu & Social Media Icons: Add Threads support

### LINKED ISSUE #31768: Social Menu & Social Media Icons: Add Threads Support
### Impacted plugin

Social

### What

As title

### How

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #31768

## Proposed changes:

Update the icon font, the social icons widget, the social menu, the social-logos package to include the new Threads icon.

Related PR: https://github.com/Automattic/social-logos/pull/122

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* * Go to `yoursite.com/wp-content/plugins/jetpack/_inc/social-logos/social-logos.html`
* Check the new logos
* Go to Jetpack > Settings and enable extra sidebar widgets.
* Switch to an old theme, like Twenty Ten.
* Go to Plugins > Add New and install the Classic Widgets plugin.
* In a functionality plugin, add the following:
```php
// Add social menu support
add_action( 'after_setup_theme', function () {
	add_theme_support( 'jetpack-social-menu', 'svg' );
} );
```
* Edit your theme and add the following, in `footer.php` for example
```php
<?php jetpack_social_menu(); ?>
```
* Go to Appearance > Customize > Menus
* Create a new menu with some links, e.g. `https://www.facebook.com/jetpackme` and `https://www.threads.net/@tconrad`
* Assign that menu to the Social Menu location
* Go to Appearance > Widgets menu
* Drag the Social Icons widget to one of the active widget areas, and add some links again.
* Check how things look like on the frontend, for both your social menu and the Social Icons Widget you created.

### CODE REVIEW

**Comment by sdixon194** [comment]
This does work for me when adding the widgets, but visiting https://firm-mole.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.html doesn't show the logo. I'm not sure if that means something else will be broken that I didn't think to test.

**Comment by jeherve** [comment]
> but visiting [firm-mole.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.html](https://firm-mole.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.html) doesn't show the logo

You would have to go to https://firm-mole.jurassic.ninja/wp-content/plugins/jetpack-dev/_inc/social-logos/social-logos.html (the dev version) to see it.

**Comment by sdixon194** [comment]
_shakes off sabbatical dust_

**Review by sdixon194 — APPROVED** [review]

**Comment by roo2** [comment]
I suspect this broke the social icons on wpcom for a bit when released p1689640150536069-slack-CBG1CP4EN https://github.com/Automattic/wp-calypso/issues/79502

**Comment by jeherve** [comment]
Sorry about that! #31932 should fix things.

**Pull request merged**
