### PR TITLE
VideoPress: Fix video caption saving

### LINKED ISSUE #26441: VideoPress: changes on caption field inside video details are not being saved
The video caption is not being saved on the backend, despite being updated on the local store.

How to reproduce:

* Go to the video details page for some video
* Edit the value from `Caption` field:

videopress-admin-details-with-caption-changed

* Save the changes
* Open the video details page again
* Force a refresh of the page
* The old value will be back on the field:

videopress-admin-details-with-caption-old-value

* No errors are shown on the UI; same for the browser console

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #26441.

#### Changes proposed in this Pull Request:

* Allow the `caption` as a possible field on the video meta update payload
* Set the attachment `post_excerpt` field with the submited `caption` value, as per pe4Cmx-fL-p2#comment-153
* Set the caption on the attachment meta information, as we do for the other fields on all non-wpcom sites

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Test on a site with VideoPress installed
* Go to `Media > Library` and upload a new video
* Go to `Jetpack > VideoPress` to see your VideoPress library
* Click the `Edit video details` button on the video that you just uploaded
* Fill the Caption field with some value and click `Save changes`
* Click the `Edit video details` button again
* The Caption field must be filled with the same text that you typed before
* Do a hard refresh on the page and check the Caption field value again: it must have the same typed value

### CODE REVIEW

**Comment by lhkowalski** [comment]
I moving this back to draft so I can check this `wpcom` check failing.

**Comment by kraftbj** [comment]
The WP.com failure was an unrelated issue.

**Review by nunyvega — APPROVED** [review]
The changes look good!

It also works as expected:


https://user-images.githubusercontent.com/16329583/192472750-fd06915e-1818-4e01-bceb-2ec36218d6c6.mov

🚢

**Comment by lhkowalski** [comment]
> The WP.com failure was an unrelated issue.

This is good to know!

**Comment by lhkowalski** [comment]
Added a DO NOT MERGE (yet), just in case.

**Comment by kraftbj** [comment]
Removing the `Ready to Merge` label so not cross signals if we're ready to merge or are holding this one.

**Comment by retrofox** [comment]
r253527-wpcom

**Pull request merged**
