### PR TITLE
Adding aldavigdis and gititon to readme markdown file

### PR DESCRIPTION
**Pull request by aldavigdis**
Documentation change. Adds yours truly and @gititon to the credits in the readme.

### CODE REVIEW

**Comment by jeherve** [comment]
You can add yourselves to the contributor list in the `readme.txt` file as well, if you have WordPress.org usernames!

**Comment by aldavigdis** [comment]
Okay @jeherve — I'll update the PR tonight and let you know. Poseidon was also discussing of others were missing from the list too, such as members of Luna.

**Comment by jeherve** [comment]
Feel free to add all of them at once, to both lists! As long as their usernames for both WordPress.org and GitHub are valid it's all good.

**Comment by aldavigdis** [comment]
That's the plan :)

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
