### PR TITLE
Jetpack code analyzer

### PR DESCRIPTION
**Pull request by gravityrail**
In order to track potential breakage, this tool parses all the PHP in Jetpack and produces a list of every public function, class, method, and property (TODO: constants, etc), along with their file path and line number.

By generating this for two separate codebases (e.g. Jetpack 7.5 and Jetpack 7.4) we can ascertain which of these have changed between the two versions. 

Then we can scan an external codebase that depends on Jetpack and find any dependencies on changed/moved methods, classes, files, functions, etc.

Then we can put some compatibility code into Jetpack or the other repo, then re-run the script and hopefully eliminate the warning / error.

To run:

```sh
cd packages/analyze
composer install # only necessary once
composer run example # this might break unless you change some paths
```

For more information, [see the README](https://github.com/Automattic/jetpack/blob/06b5f602ed8e301e955ebf63a8bc4ecf4002e63d/packages/analyzer/README.md).

### Testing

This runs independently of the rest of the Jetpack codebase, so it should be safe to merge from a UX point of view. Since it's not even required by the root composer.json file, it won't be included in the production build.

- `cd packages/analyze`
- `composer install`
- uncompress the Jetpack 7.4 zip file somewhere, e.g. to ~/Downloads/jetpack-7.4
- check out some code that might depend on Jetpack
- adjust the example script, or run your own PHP script which looks a bit like this (adjust the paths at the top):

```php
<?php
require '/path/to/jetpack-master/packages/analyze/vendor/autoload.php';

$jetpack_75_path = '/path/to/jetpack-master';
$jetpack_74_path = '~/Downloads/jetpack-7.4';
$external_repo_path = '/path/to/some-repo';
$jetpack_exclude = array( '.git', 'vendor', 'tests', 'docker', 'bin', 'scss', 'images', 'docs', 'languages', 'node_modules' );

echo "Scan master declarations\n";
$jetpack_75_declarations = new Automattic\Jetpack\Analyzer\Declarations();
$jetpack_75_declarations->scan( $jetpack_75_path, $jetpack_exclude );

echo "Scan 7.4 declarations\n";
$jetpack_74_declarations = new Automattic\Jetpack\Analyzer\Declarations();
$jetpack_74_declarations->scan( $jetpack_74_path, $jetpack_exclude );

echo "Find differences\n";
$differences = new Automattic\Jetpack\Analyzer\Differences();
$differences->find( $jetpack_75_declarations, $jetpack_74_declarations );

echo "Find invocations\n";
$invocations = new Automattic\Jetpack\Analyzer\Invocations();
$invocations->scan( $external_repo_path );

echo "Generate warnings\n";
$warnings = new Automattic\Jetpack\Analyzer\Warnings();
$warnings->generate( $invocations, $differences );
$warnings->print();
```

Run this using `php /path/to/test.php`. If all goes well, it should include the autoloader and scan the code, producing output like this:

```csv
Total: 6081
Missing: 698
method_missing,class.cli-commands.php,38,"Class static method \Jetpack_Sync_Settings::update_settings($new_settings) is missing"
method_missing,class.cli-commands.php,56,"Class static method \Jetpack_Sync_Actions::initialize_listener() is missing"
method_missing,class.cli-commands.php,57,"Class static method \Jetpack_Sync_Modules::get_module($module_name) is missing"
method_missing,class.cli-commands.php,58,"Class static method \Jetpack_Sync_Actions::initialize_sender() is missing"
property_missing,class.cli-commands.php,75,"Class static property \Jetpack_Sync_Actions::$sender is missing"
method_missing,class.cli-commands.php,97,"Class static method \Jetpack_Sync_Settings::reset_data() is missing"
```

You may then go into your external source or Jetpack master to make compatibility fixes to each of the file locations in question, then re-run the script to make sure your compatibility issue was eliminated.

### Remaining work

This is a very preliminary release which has only been tested on a small amount of code. While care was taken to make it efficient, there are probably many issues scaling it to large, complex codebases. It also lacks several features:

- Add annotations to selectively ignore compatibility errors that are fixed (but the fix not detected, e.g. moved method to subclass) or safe to ignore.
- Just list missing file paths (could also be done w/ a shell script) so we can at least add stubs
- Attempt to resolve instances to classes so we can detect invocations of instance methods and properties
- Detect changes in args (number, default values) to methods and functions
- Many more types of invocation (e.g. instance methods and props), more language features for declarations (`const`, `define()`, etc) and more warnings (params changed, return value changed)

#### Instance method support

It's very hard to detect usage of an instance method or prop in external code e.g.

```php
$x = new Foo();
$x->run();
```

In order to know that `run` was being called on $x, we have to track what kind of value is assigned to $x, which requires executing (not just parsing) the code. This is a typical dynamic language problem but it's a tough one. Perhaps it's enough just to know that affected classes are being instantiated and that we need to investigate how their methods/vars are being invoked.

#### Methods moved to subclass

I don't believe PHP_Parser resolves subclass methods as part of the current class, since we're only dealing with syntax, not an actual class hierarchy.

### CODE REVIEW

**Comment by zinigor** [comment]
I have added some corner cases, but I don't really fully understand why the expression objects that I had to single out in case of the "new" statements were special in this way. 

I was testing with the client-example plugin that I was using for the Jetpack Connection example, as well as with wpcomsh.

**Review by dereksmart — APPROVED** [review]
❤

**Review by zinigor — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.5` in cbff357e931437ccb5d893fddf621df7ea911e74

**Comment by tyxla** [comment]
This is amazing work! ❤️

**Pull request merged**
