### PR TITLE
Fix Super Cache / Jetpack Compatibility

### LINKED ISSUE #7868: Disable "Require Two-Step" checkbox when option is filtered
When the `jetpack_sso_require_two_step` option is filtered and therefore not dependent on the options table, we should disable the toggle.

https://github.com/Automattic/jetpack/blob/6219689790419c7266a9f94664c3522c1586c4b6/_inc/client/security/sso.jsx#L84-L96

### PR DESCRIPTION
**Pull request by thingalon**
Fixes https://github.com/Automattic/jpop-issues/issues/7868

A fatal error can occur when running Jetpack 11.5 and Super Cache side-by-side, if Super Cache has its "Jetpack Mobile Theme" plugin enabled. This was caused by a change to how the device-detection stuff in Jetpack 11.5 was autoloaded.

Things I'm uncertain of:
- Does adding device-detection as a dependency of Super Cache require anything in the repository setup to ensure the vendor stuff will get added to the next deployed version?

#### Changes proposed in this Pull Request:
* Add Jetpack's device detection as a dependency of Super Cache, so that it can rely on its own copy
* Ensure that the User_Agent class is automatically loaded if not run in an auto-load environment in device-detection.

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Install Jetpack 11.5 and Super Cache side-by-side
* Enable Jetpack mobile Theme under the "Plugins" tab of Super Cache
* Load your home page in a private browser window
* Ensure that it no longer crashes :)

### CODE REVIEW

**Review by oskosk — DISMISSED** [review]

**Comment by thingalon** [comment]
Ok, it looks like there is some kind of setup step I don't know how to configure -- @Automattic/ground-control can I please have some help?

I added `device-detection` to the composer file, so that Super Cache can rely on its own copy at runtime instead of loading it from a neighboring copy of Jetpack (which seems fraught). But based on the failing action it looks like the vendor directory isn't included in the build (?): https://github.com/Automattic/jetpack/actions/runs/3374114013/jobs/5599477259

I'm not sure how to fix this properly :) I'd love some help.

**Comment by kraftbj** [comment]
I added the inclusion of the vendor dirs in 17ffda8b57098a3fe1ae4aff8effb11243618c6f

**Comment by oskosk** [comment]
Thanks @kraftbj

**Comment by thingalon** [comment]
Thank you @kraftbj! 😁 

Now I just need a 👍 from someone with reviewer access to device-detection and I think we can merge this to bring trunk in-line with what's already released in svn.

**Review by sdixon194 — APPROVED** [review]

**Pull request merged**
