### PR TITLE
Boost: Use Blog ID in links to WPCOM instead of site slug

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:
Adjust checkout links in Boost plugin to use blog ID instead of slug for multi-URL support.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pf5801-93-p2

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
To test the blog, you'll need two domains pointing to the same site. One way to do that is to setup two proxying tunnels to the same local environment.

**Connect Jetpack with a free plan on URL A, and load it via URL B.**

**To also fully test the Calypso changes, please test the changes separately on site-only connected site.**

If your site falls into IDC due to concurrency issues with IDC secret validation (fix pending), remove `jetpack_sync_error_idc` option.

1. Using URL B (not the main cache site URL), go to "Jetpack -> Boost" and click "Get Boost".
2. Confirm you were taken to checkout, and the page URL contains URL A (main cache site URL).
3. Don't finish the checkout, go back and choose the free plan. You should see the Boost dashboard.
4. Scroll down to the "Upgrade" link and click it. You should see the upgrade upsell card, click "Upgrade Jetpack Boost".
5. Confirm you were taken to checkout, and the page URL contains URL A (main cache site URL). 
6. Finish the checkout. Confirm that you're back in the Boost Dashboard and the plan was upgraded.

### CODE REVIEW

**Comment by sergeymitr** [comment]
Code needs to be adjusted for the recent Boost changed, back to "In Progress".

**Comment by sergeymitr** [comment]
Created a Calypso PR to fix the "Upgrade" issue for site-only connected sites: https://github.com/Automattic/wp-calypso/pull/86920
This PR is now blocked until I sort that out.

**Comment by sergeymitr** [comment]
@bindlegirl I might've reproduced the checkout issue you discovered before, and pinged the Boost team: p1706406531225549-slack-C016BBAFHHS
We'll see if they're able to reproduce it.

**Comment by sergeymitr** [comment]
@bindlegirl I tested the Boost flows a bit more and couldn't find any more issues besides the one I mentioned above, which is also present in the latest stable of the plugin.
Please give it another look when you get a few minutes, ignoring that "Getting Started" problem.

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
