### PR TITLE
Masterbar: Improve plugin compatibility

### PR DESCRIPTION
**Pull request by obenland**
See #17594

#### Changes proposed in this Pull Request:

* Adds a late callback to `custom_menu_order` in an attempt to not have the menu order altered.
* Loads admin include files to closer resemble the admin environment for plugins hooking into `admin_menu`.
* Accounts for `div` and `none` menu icons by passing on the default icon (has unit tests).
* Improves link generation for custom top level menu items (has unit tests).

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

To run unit tests:
* Follow [setup guidelines](https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#unit-testing) if you don't have unit tests set up yet.
* Run `phpunit --filter WP_Test_WPCOM_REST_API_V2_Endpoint_Admin_Menu`

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Comment by obenland** [comment]
Currently blocked on the wpcom side by D51740-code

**Review by cpapazoglou — DISMISSED** [review]
These changes LGTM! Let's merge them when unblocked.

**Comment by obenland** [comment]
Test file name updates on the dotcom side were part of D51740-code.

**Comment by obenland** [comment]
@kraftbj This one should probably go into 9.1 if that is still possible, it fixes a regression for plugins that hook into `admin_menu` and use admin APIs without an `is_admin()` check.

**Review by kraftbj — APPROVED** [review]
Looks good to me. I'll leave the merge and corresponding wp.com commits to y'all. Once that's done, we'll get it into the 9.1 branch.

**Comment by obenland** [comment]
r216092-wpcom

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.1` in 34390c704b3f42145f64ed47efb44f6cdbb2efc6

**Pull request merged**
