### PR TITLE
E2E: Fix failing search tests by adjusting E2E build workflow

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
Adds `packages/search` production build step before running E2E tests. And as `composer` ignores the built search assets ( because they are in `.gitignore` ), we added a step to manually copy them over. @samiff suggests that newer version of `composer` might have addressed the issue, we could possibly remove the copying process in the future.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Ensure that the post-connection E2E tests pass.
- Ensure that the changes look reasonable

### CODE REVIEW

**Comment by jsnmoon** [comment]
Hi @Automattic/jetpack-crew, this PR adds a search package build invocation to the E2E setup workflow. With this addition, however, I'm running into the following error during the search package's Composer installation step (emphasis mine):

> Root composer.json requires **automattic/jetpack-connection ^1.34**, it is satisfiable by automattic/jetpack-connection[**dev-master, v1.34.0, 1.34.x-dev (alias of dev-master)**] from composer repo (https://repo.packagist.org) but automattic/jetpack-connection[**dev-8a589b5bfc4334bd1bf2c11ba1ad782f7d7b88ed**] from path repo (../*) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

This error repeats for assets, constants, tracking, options, status, and changelogger packages as well. What's the best way to resolve this?

**Comment by anomiex** [comment]
The immediate fix is https://github.com/Automattic/jetpack/blob/ccc9c35167c9ebc7fa2f42d93fc4434ad8f4dad2/.github/workflows/build.yml#L11-L12 which tells Composer that the local git checkout should be considered as "dev-master".

Although if you're getting to the point of building everything, I start to wonder if it'd make more sense to wait for the Build workflow and download its artifact instead. Probably a question for @adimoldovan, particularly with his recent looking into combining the various E2E workflows we have now.

**Comment by adimoldovan** [comment]
> I start to wonder if it'd make more sense to wait for the Build workflow and download its artifact instead.
Last time I checked the Build workflow was taking over 15 minutes, while the build in the e2e workflow takes around 5. I'm not sure how much time will the search package build add, but it probably still makes sense to keep the build step in the e2e flow.

**Comment by kangzj** [comment]
I added the env variable, and the search package builds fine now. But weird enough, the search package assets are still missing i.e. 404ed, so the search E2E tests still fail.

https://github.com/Automattic/jetpack/pull/22311/files#diff-194218c48b9a0cdd03974145733804c2d992ca818529fe2fa69a501d8b5b1cc3R57

@samiff @adimoldovan Any idea? Thanks

**Comment by anomiex** [comment]
> I did some experiments, which indicates that the `jetpack-search` and other packages inside Jetpack the plugin are real folders instead of symbol links.

With `jetpack build plugins/jetpack --production`, it sets composer to "mirror" rather than "symlink". Unfortunately when composer does that, it pays attention to `.gitignore` and so doesn't mirror any built files.

We get around this in the actual Build job by [copying the stuff that will be pushed to the mirror repos elsewhere](https://github.com/Automattic/jetpack/blob/92c4834a2aacf1f3789f8152bb2308b07d8f0235/.github/files/build-all-projects.sh#L178-L188) and [munging Jetpack's composer.json to point to that in preference to the monorepo](https://github.com/Automattic/jetpack/blob/92c4834a2aacf1f3789f8152bb2308b07d8f0235/.github/files/build-all-projects.sh#L61-L78).

**Comment by bluefuton** [comment]
@kangzj could we add the command(s) to run the E2E tests to the 'Testing instructions' please?

**Comment by kangzj** [comment]
Hi @bluefuton, the PR is to fix the E2E flow on Github, so I guess just ensure the E2E tests pass on Github actions is fine?

E2E test instructions: 
* `cd projects/plugins/jetpack/tests/e2e`
* `pnpm install`
* `pnpx jetpack build packages/search`
* `pnpx jetpack build plugins/jetpack`
* `pnpm env-start`
* `pnpm tunnel-on`
* Ensure test pass: `pnpm test-e2e -- ./specs/post-connection/search-configure.test.js`
* Ensure all E2E tests pass on GitHub

**Comment by bluefuton** [comment]
> the PR is to fix the E2E flow on Github, so I guess just ensure the E2E tests pass on Github actions is fine?

Thanks! That wasn't immediately clear from the issue title/description. Looking good now:

Screen Shot 2022-01-14 at 10 51 34

**Comment by kangzj** [comment]
@bluefuton I guess you are right. Updated the test instructions 😄

**Review by adimoldovan — DISMISSED** [review]

**Review by anomiex — DISMISSED** [review]
Seems ok to me. Let's try to remember to check if lines 63–64 are still needed when we eventually update to composer 2.2.

**Comment by kangzj** [comment]
Thanks @adimoldovan @anomiex for the speedy review. Needed to rebase, would you mind to appove it again. thanks.

>  Let's try to remember to check if lines 63–64 are still needed when we eventually update to composer 2.2. @anomiex 

I'll write that down. Thanks.

**Review by anomiex — APPROVED** [review]
Next time try doing a [master merge instead of a rebase](https://github.com/Automattic/jetpack/blob/master/docs/git-workflow.md#keeping-your-branch-up-to-date). If there are no merge conflicts it preserves approvals.

**Comment by kangzj** [comment]
> Next time try doing a [master merge instead of a rebase](https://github.com/Automattic/jetpack/blob/master/docs/git-workflow.md#keeping-your-branch-up-to-date). If there are no merge conflicts it preserves approvals.

Will do thanks 😊

**Pull request merged**
