### PR TITLE
VideoPress: Add settings to the React interface

### PR DESCRIPTION
**Pull request by rcoll**
#### Changes proposed in this Pull Request:

Bring VideoPress settings over to the React interface. Fixes some issues with https://github.com/Automattic/jetpack/pull/5233

### CODE REVIEW

**Comment by rcoll** [comment]
https://github.com/Automattic/jetpack/issues/5457

**Comment by rcoll** [comment]
No Jetpack plan active (could use better verbiage):
screen shot 2016-11-03 at 2 36 50 pm

With personal/premium/business plan active:
screen shot 2016-11-03 at 2 36 17 pm

/cc @dbtlr How does this look? Do you want to do away with these options as well?

**Comment by rcoll** [comment]
Also, @dbtlr, I changed where the options are stored. They are now in their own options named "videopress_default_quality" (1 for HD, 0 for SD) and "videopress_free_formats" (1 checked / 0 unchecked). Happy to put them wherever you need them, if it's even necessary.

**Comment by rcoll** [comment]
New screenshots, all options removed.

No Jetpack plan:
screen shot 2016-11-03 at 8 20 00 pm

With Jetpack plan:
screen shot 2016-11-03 at 8 19 28 pm

A couple more commits coming tomorrow to tidy up and then we should be good.

**Comment by dbtlr** [comment]
The screens look great! thanks @rcoll !

**Pull request closed without merging**
