### PR TITLE
Jetpack DNA: Move Jetpack Sync Settings from Legacy to psr-4

### PR DESCRIPTION
**Pull request by gititon**
This PR moves the Jetpack Sync Settings from legacy to PSR-4.

No new tests should be needed because this is a refactor, so existing tests should catch any regressions.

### CODE REVIEW

**Comment by gravityrail** [comment]
Please check in with VIP and Atomic folks about whether they are directly calling `Jetpack_Sync_Settings` from any of their scripts.

**Comment by roccotripaldi** [comment]
> Please check in with VIP and Atomic folks about whether they are directly calling Jetpack_Sync_Settings from any of their scripts.

Good call @gravityrail - i think we need to do a quick spin through open grok to make sure Atomic and VIP don't invoke any of the classes that we've change so far. I'll start a master issue for that.

**Comment by roccotripaldi** [comment]
let's fix the conflicts

**Review by dereksmart — APPROVED** [review]
Tested a bit

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.5` in 5f3718c28851b02f3d75ba81f4a0f9f6a03d4111

**Pull request merged**
