### PR TITLE
a4a: display warning modal when deactivating the plugin

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This PR adds a modal displayed when one wants to deactivate the plugin. It warns folks of the lost functionality when deactivating the plugin.

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

- pfunGA-sQ-p2#comment-1126
- 129-gh-automattic-for-agencies-dev

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Activate the a4a plugin.
* Go to the Plugins menu
* Click on "Deactivate"
    * See the modal that opens.

### CODE REVIEW

**Review by madebynoam — COMMENTED** [review]
The modal looks good. Just noting that when I click Disconnect it removes the plugin instead of disabling and leaving it installed.

**Comment by jeherve** [comment]
> Just noting that when I click Disconnect it removes the plugin instead of disabling and leaving it installed.

This is specific to sites running the Jetpack Beta Tester plugin. It won't happen on a site running the regular plugin. 👍

**Comment by madebynoam** [comment]
> > Just noting that when I click Disconnect it removes the plugin instead of disabling and leaving it installed.
> 
> This is specific to sites running the Jetpack Beta Tester plugin. It won't happen on a site running the regular plugin. 👍

Thanks!

**Comment by jeffgolenski** [comment]
Just tested on a live branch! Just a couple of questions at this point @jeherve @rcanepa just so I know what to expect at this stage!

The connection flow still has a Jetpack branded screen.

image


When I connect the A4A plugin, my new site successfully shows up in my A4A dashboard (NICE)

CleanShot 2024-03-26 at 11 44 33

However, when I deactivate (disconnect) the site on the wp-admin side, the site remains within my A4A sites dashboard afterwards. Is that expected?

**Comment by jeherve** [comment]
>  just so I know what to expect at this stage!
> The connection flow still has a Jetpack branded screen.

Yes, that's expected. The design hasn't been implemented yet.

> when I deactivate (disconnect) the site on the wp-admin side, the site remains within my A4A sites dashboard afterwards. Is that expected?

I'll let @rcanepa speak to that.

**Comment by rcanepa** [comment]
> when I deactivate (disconnect) the site on the wp-admin side, the site remains within my A4A sites dashboard afterwards. Is that expected?

@jeffgolenski , can you verify that other Jetpack plugins are not active? I tested it myself and couldn't replicate the issue. Did you try with a JN site?

**Comment by jeherve** [comment]
Since folks are happy with the modal (what's being added here), I think we could merge this PR now. We can iterate on other things in follow-up PRs. It needs an approval though.

**Review by rcanepa — APPROVED** [review]
LGTM.

I wasn't able to replicate Jeff's error report. And I'm pretty confident it should not be a problem because we have not modified how the Jetpack Connection works.

**Pull request merged**
