### PR TITLE
Bump height of the connect-in-place iframe to fit error messages

### PR DESCRIPTION
**Pull request by delawski**
Bump height of the connect-in-place iframe to fit error messages.

Fixes no known issue. See D32584-code for screenshots.

#### Changes proposed in this Pull Request:
* Bump height of the connect-in-place iframe to fit error messages.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* p1HpG7-7nj-p2

#### Testing instructions:
- Run this branch
- Confirm that the iframe height is big enough to fit the content in each stage of the connection and in case of an error.

#### Proposed changelog entry for your changes:
None.

### CODE REVIEW

**Review by tyxla — APPROVED** [review]
This is looking good to me. Should we also get design review on it?

**Comment by keoshi** [comment]
Code looks good, but I couldn't test on JN because there's a file conflict.

**Comment by delawski** [comment]
The conflict is resolved now.

**Comment by keoshi** [comment]
Thanks, @delawski ! Will take a look shortly.

**Review by keoshi — APPROVED** [review]
Looks good to me!

**Comment by lezama** [comment]
🚢 IT

**Pull request merged**
