### PR TITLE
Stats: Add stats-admin package

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
The `stats` package contains the essential functionalities (Loading the pixel and some endpoints) for Stats so that Stats could easily be integrated with Jetpack the plugin, the Search plugin and etc.

Recently we are refreshing the Jetpack Stats experience, mostly the Stats Dashboard. The PR introduces another package `stats-admin`, which would handle everything happening from the WP-Admin side. We create it as a separate package because the admin part isn't always needed by plugins and would otherwise bloat size of the plugin.

The package adds route that forwards requests to WPCOM and loads assets from `https://widgets.wp.com/calypso-stats/`.

Calypso Stats: https://github.com/Automattic/wp-calypso/pull/69231

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
pejTkB-1h-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Apply `D92140-code` to your sandbox
* Add `x.x.x.x widgets.wp.com` to your hosts file <- please change it to your sandbox IP
* Checkout and build current branch `add/stats-admin-package` on your local test site
* Open `/wp-admin/admin.php?page=stats&calypso_stats=1` on you local test site
* Ensure Jetpack Stats looks reasonable and **_mostly_** works
* Ensure legacy Stats still works
* Switch WordPress language to French (other languages fine, but make sure Calypso supports it)
* Open `/wp-admin/admin.php?page=stats&calypso_stats=1` on you local test site
* Ensure the page is translated

image

### CODE REVIEW

**Review by jsnmoon — CHANGES_REQUESTED** [review]
I'm getting the following fatal error upon navigating to `/wp-admin/admin.php?page=stats&calypso_stats=1` on a fresh Jurassic Ninja site:

```
Fatal error: Uncaught Error: Undefined class constant 'VERSON' in /public/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-stats-admin/src/class-dashboard.php:199

Stack trace:
#0 /public/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-stats-admin/src/class-dashboard.php(136): Automattic\Jetpack\Stats_Admin\Dashboard->get_cdn_asset_cache_buster()
#1 /public/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Stats_Admin\Dashboard->load_admin_scripts('jetpack_page_st...')
#2 /public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /public/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'jetpack_page_st...')
#5 /srv/users/userf3f898a1/apps/us in /public/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-stats-admin/src/class-dashboard.php on line 199
```

**Comment by kangzj** [comment]
Fixed two references which I apparently missed when refactoring and also rebased.

**Review by jsnmoon — APPROVED** [review]
Let's split PRs of this magnitude into multiple PRs next time around (e.g., one for scaffolding, another for REST endpoints, and another for the dashboard class).

Nonetheless, these changes look reasonable and ready to ship. Great work!

**Comment by kangzj** [comment]
> Let's split PRs of this magnitude into multiple PRs next time around (e.g., one for scaffolding, another for REST endpoints, and another for the dashboard class).

@jsnmoon  Yep good point. I'll do that next time. Thanks for the quick review.

**Pull request merged**
