### PR TITLE
Social | Social post UI: Update connection toggle and media notice

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Proposed changes:

* Make the social post Instagram notice same as the one in sidebar
* Social post modal: Hide toggle if connection or media is not valid
* Move social post connection toggle to the top and update the label

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Enable the editor preview feature - `define( 'JETPACK_SOCIAL_HAS_EDITOR_PREVIEW', true );`
* Goto post editor
* Open Jetpack or Social sidebar
* Under "Share this post" section, click on "Create custom posts"
* Confirm that the connection toggle is at the top before the preview
* Confirm that no media notice for  Instagram is same as the one in sidebar
* Confirm that the toggle is hidden when there is a validation notice for Instagram.
* Confirm that the toggle label says, "Connection enabled"

Screenshot 2024-08-09 at 3 21 10 PM

Screenshot 2024-08-09 at 3 22 19 PM

### CODE REVIEW

**Review by gmjuhasz — COMMENTED** [review]
Looks good codewise, but I think we could cut from both the top and bottom margin a bit, it takes up a lot of space, what do you think?
CleanShot 2024-08-09 at 12 31 42 png

On the design it also looked slimmer
CleanShot 2024-08-09 at 12 32 49 png

**Comment by manzoorwanijk** [comment]
> I think we could cut from both the top and bottom margin a bit, it takes up a lot of space, what do you think?

How about now?

image

**Comment by gmjuhasz** [comment]
@manzoorwanijk What do you think of decreasing that bottom gap to 1rem or 1.5rem from 2? To me 2 looks a bit too much, but I'm not sure

**Comment by manzoorwanijk** [comment]
> What do you think of decreasing that bottom gap to 1rem or 1.5rem from 2? To me 2 looks a bit too much, but I'm not sure

I am also not sure. Let me change it to 1rem

**Review by gmjuhasz — APPROVED** [review]
I think I like it more like this

**Pull request merged**
