### PR TITLE
Check for dev mode, return early if true

### LINKED ISSUE #2288: Multisite: Jetpack_Network::do_subsiteregister should return early in dev mode
There's no point in trying to connect a new site to WordPress.com if `JETPACK_DEV_DEBUG` is enabled, and the blocking HTTP request slows down the site creation process.

`restore_current_blog()` should be called before returning, to avoid regressing #2280 / #2287.

### PR DESCRIPTION
**Pull request by chaselivingston**
Fixes #2288

### CODE REVIEW

**Comment by kraftbj** [comment]
Right above it, there's another early `return` without the `restore_current_blog()`. Should that be added there too?

**Comment by chaselivingston** [comment]
Good question. Thoughts @iandunn?

**Comment by iandunn** [comment]
Er, actually, I think I was just wrong when I said it needed the `restore_current_blog()`; If the `return` is done before `switch_to_blog()` is called, then it's not needed.

I don't remember why I thought it was needed, maybe I just didn't look closely enough? I don't see `switch_to_blog()` being called higher up the stack, so I think it's safe to just `return` without calling `restore_current_blog()`.

**Comment by chaselivingston** [comment]
Updated to remove that unnecessary call.

**Comment by dereksmart** [comment]
:+1:

**Pull request merged**
