### PR TITLE
Added default module activation for pre-existing settings.

### PR DESCRIPTION
**Pull request by zinigor**
Fixes a problem where if you had previously enabled modules, Jetpack wouldn't enable default ones when activated, but only if Jetpack wasn't previously active on this installation and wasn't uninstalled.

#### Changes proposed in this Pull Request:

* Added default modules to a list of activated modules with pre-existing settings.

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

[p9dueE-5pN](view-source:p9dueE-5pN-p2)

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Install both Jetpack and Jetpack Social on your testing site. Jetpack Social is a good testing candidate because it uses the `jetpack_active_modules` option.
* Only activate Jetpack Social.
* Make sure the social accounts feature is enabled.
* Make sure that the `jetpack_active_modules` option contains `publicize` and nothing else.
```
$ wp option get jetpack_active_modules
array (
  0 => 'publicize',
)
```
If it has something else - delete the option and start again.
```
$ wp option delete jetpack_active_modules
Success: Deleted 'jetpack_active_modules' option.
```
* Make sure that the `jetpack_active_modules_initialized` is not defined
```
$ wp option delete jetpack_active_modules_initialized
Success: Deleted 'jetpack_active_modules_initialized' option.
```
* Activate Jetpack.
* See that the active module list has not changed.
* Use this PR and repeat the same steps.
* See that the active modules include the default modules as well.

### CODE REVIEW

**Comment by anomiex** [comment]
Observed this behavior in testing:

* Enable Jetpack.
* Disable some default modules.
* Disconnect and reconnect Jetpack.
* Deactivated modules are now reactivated.

Not sure that's behavior we want.

Same happens if you deactivate and reactivate Jetpack without a disconnection (e.g. because a standalone plugin is also installed).

**Comment by zinigor** [comment]
Thanks for the review @anomiex ! I have updated the PR to not activate default modules if Jetpack was previously set up, and updated the testing instructions accordingly.

**Comment by anomiex** [comment]
Still has a failure condition:

* Install Jetpack Social and establish a Jetpack connection
* Install Jetpack
* Deactivate some modules
* Deactivate and reactivate Jetpack

The `active_modules_initialized` option gets set in two places: when the Jetpack connection is established or when Jetpack is activated without any existing `active_modules`. Neither of those happens in this situation. Probably the thing to do is to set `active_modules_initialized` in the code path being changed here.

**Comment by zinigor** [comment]
Great catch, thank you @anomiex ! I have added one change to fix that.

**Review by anomiex — APPROVED** [review]

**Pull request merged**
