### PR TITLE
Add wpcom marketplate upsell to plugins on WoA sites

### PR DESCRIPTION
**Pull request by dsas**
Fixes https://github.com/Automattic/dotcom-forge/issues/6001

## Proposed changes:

Add a prominent upsell banner from /wp-admin/plugin-install.php to the wpcom plugin marketplace

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Create a woa dev site and take it atomic
2. Use instructions in comment below to apply to the atomic site
3. Go to /wp-admin/plugin-install.php
4. See the banner
5. Click the link in the banner - you should go to the plugin marketplace

### CODE REVIEW

**Comment by rcrdortiz** [comment]
Since the banner isn't shared across Simple and Atomic, I think having this feature live on wpcomsh would make more sense.

**Comment by rcrdortiz** [comment]
### When the popular tab is selected the banner is missing some separation with the tab bar.

Screenshot 2024-04-30 at 08 45 23

**Comment by rcrdortiz** [comment]
### Maybe we could remove the banner when we search for something (or at least hide it if there are results). It seems a bit out of context to have the banner show up before my search results. The same applies to the `Favorites` tab.


https://github.com/Automattic/jetpack/assets/1989914/a81dd880-2dd4-4efe-b71c-09b972fed0b6

**Comment by xavier-lc** [comment]
Between 960 and 1200 pixels (page width) the banner looks a bit cluttered, with the logos a bit too close to the text.

image

**Review by xavier-lc — DISMISSED** [review]
Still a bit bloated between 1120 and 1200 px, but it can be easily fixed. I'm approving 🥇

image

**Comment by rcrdortiz** [comment]
Everything is working fine except for https://github.com/Automattic/jetpack/pull/37113/commits/98577cc4f9f15ee012a272fbd6017c4f634ac9e7. I can still see the banner when I have search results. I cleared my cache and all, I'm not getting any JS errors.

**Comment by dsas** [comment]
Moved this to wpcomsh: https://github.com/Automattic/wpcomsh/pull/1839

**Pull request closed without merging**
