### PR TITLE
Docker Image: Update Ubuntu version to 21.04

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request:
While trying to install the Jurassic Tube scripts on an M1 Mac, I was
seeing segmentation fault errors from the `curl` commands. After some
investigation, it l[ooks to be a problem with `libcrypto`](https://github.com/docker/for-mac/issues/5846#issuecomment-881244406) and upgrading
the base image to ubuntu:21.04 fixes the issue.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Run `jetpack docker build-image`
* Check everything still functions ok
* If on an M1 Mac, run `jetpack docker exec curl https://jurassic.tube/jtuber-v0.4.sh` and check that the script is returned with this change.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
The update went just fine for me on an M1. I'll let @anomiex chime in to see how it goes on his system, but I think we should be good to go!

**Comment by anomiex** [comment]
Works as far as it goes, but I note 21.04 is already end-of-life. 21.10 was released in October, so we might want to try that instead.

Also a new LTS (22.04) is scheduled for release on April 21, which we'll probably want to look at once it has come out. Too bad Ubuntu doesn't seem inclined to address this in 20.04.

**Comment by kraftbj** [comment]
Might as well try the jump to 21.10. I'm going to bump it to 21.10 and see if it builds for me fine. I'm not on a M1, though, so can't test for the original bug.

**Comment by kraftbj** [comment]
21.10 worked fine for me, so pushing up that for others to test.

**Review by jeherve — APPROVED** [review]
Still works for me on M1.

**Pull request merged**
