### PR TITLE
Correction to string "Simple Payments"

### LINKED ISSUE #10114: Simple Payments: Make the product name consistent
During our i18n test on WordPress.com logged-out homepage, some of Team Global members found that the word "Simple Payments" is translated inconsistently.

As I was looking into a way to re-send the strings that include this product name, I also found that some variations of it:

- Simple Payments (correct)
- Simple Payment (singular)
- simple payments (lowercase)
- simple payment (lowercase singular)

From the translation perspective, it would be the best if they are always spelled "Simple Payments" so that the phrase matches existing glossaries.

Inconsistent strings within the plugin:
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/ja/default?filters%5Bterm%5D=simple+payment+&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

All "simple payment" matches in WordPress.com (low priority "↓" ones don't need to be fixed):
https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bterm%5D=Simple+Payment&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

### PR DESCRIPTION
**Pull request by rakmob42**
#### Changes proposed in this Pull Request:

* Fixes #10114

Note: This is my first PR in this repo so please let me know about my mistakes and how I can improve them. From what I understand, this should be pretty straight forward as it involves string correction.

### CODE REVIEW

**Comment by codestor4** [comment]
>  If you think 'Testing instructions' or 'Proposed changelog entry' are not needed for your PR - please explain why you think so.

I think so because the original issue explains it very well and this patch should fix all strings in here:

> Inconsistent strings within the plugin:
> https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/ja/default?filters%5Bterm%5D=simple+payment+&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Review by jeherve — APPROVED** [review]
Works for me. 🚢

**Comment by jeherve** [comment]
Nice first contribution :)

Quick note for your next PRs: don't forget the testing instructions. :)

**Comment by kraftbj** [comment]
I believe this should be syncing back to WP.com, but looks like SImple Payments may not be in the build script. I'll check that out shortly.

**Comment by kraftbj** [comment]
Added to Fusion and brought downstream changes up in D18702-code

**Pull request merged**
