### PR TITLE
Likes: Flip likers popup when it overflows the edge of the viewport.

### LINKED ISSUE #86312: Like block: Likers popover overflows on mobile screens when the reblog button is present
Image

### PR DESCRIPTION
**Pull request by yansern**
Fixes https://github.com/Automattic/wp-calypso/issues/86312

## Proposed changes:

* When the likers popup overflow the edge of the viewport, flip it around so it stays within the viewport.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

**Preparation**
* Add `define( 'JETPACK_BLOCKS_VARIATION', 'beta' );` to `wp-config.php`.
* Test your site on jurassic.
* Go to the post editor, add a Likes block.
  * Recommended: Right align the Like block (you can do it with Row block) so that it is closer to the edge (didn't help for me I manually pushed the element but it really depends on your template.)
* Publish the post.

**Test**
* Resize your browser viewport until the likers popup will overflow when opened.
  * Ensure the popup flips the other way around.
* With the likers popup opened, resize the browser window.  
  * The likers popup should reposition itself on resize.
* With the likers popup closed, resize the browser window.
  * Nothing should happen.
* Also test with RTL.

https://github.com/Automattic/jetpack/assets/1287077/21c72ca3-926f-4741-8ef4-ab957cd904cc

### CODE REVIEW

**Comment by JuanLucha** [comment]
I can see two things here:
a) When the avatars are not there, weird popup appearance:
Screenshot 2024-01-16 at 13 51 32
Inspecting:
Screenshot 2024-01-16 at 13 53 23

b) When resizing the popup appears again:
https://github.com/Automattic/jetpack/assets/3832570/a0981448-b8b0-4f03-962d-8ac0832eeeb3

**Comment by yansern** [comment]
> a) When the avatars are not there, weird popup appearance:

I think this is an isolated issue, check if you have gravatar sandboxed or if the gravatar image urls are working.

> b) When resizing the popup appears again:

Oh thanks, I missed out the removal of event listener. Working on it.

**Comment by yansern** [comment]
Alright I have added the event removal handler and updated the test description.

**Comment by JuanLucha** [comment]
Nice! Thanks for the changes, @yansern !
I can see resizing the window doesn't make the popup to appear again 👍 
I can also see that clicking the "x likes" label when there is no space for the popup to appear to the right, it re-position to fit 👍 
Before:
Screenshot 2024-01-16 at 16 54 11

After:
Screenshot 2024-01-16 at 16 51 26


About the avatars, there is a problem there for sure, but in trunk the behavior is the same. I consider that problem something we need to work on right away but outside the scope of this patch.

Great work!

**Review by JuanLucha — APPROVED** [review]

**Pull request merged**
