### PR TITLE
PHPCS - Carousel audit

### PR DESCRIPTION
**Pull request by sdixon194**
Brings carousel php files up to phpcs standards in order to remove them from phpcs ignore.

Changes so far are incomplete, but want to merge the mostly doc comment and small changes before breaking things with the bigger ones.

#### Changes proposed in this Pull Request:

* as above

#### Jetpack product discussion

n/a
#### Does this pull request change what data or activity we track or use?

n/a
#### Testing instructions:

* check out this branch
* enable the carousel
* make sure everything still works as expected

### CODE REVIEW

**Comment by sdixon194** [comment]
gotta figure out changelogger stuff

**Comment by jeherve** [comment]
> gotta figure out changelogger stuff

This should help:
p1HpG7-bqa-p2

**Comment by jeherve** [comment]
I'll close this PR for now because of the lack of activity on this. We can always reopen in the future if needed, but it will need a rebase, so it may be easier to start a new PR at this point.

**Comment by coder-karen** [comment]
Ah, it looks like this is the same as what I was working on here: https://github.com/Automattic/jetpack/pull/22770

**Pull request closed without merging**
