### PR TITLE
My Plan: Add Offer Reset project new plans (Jetpack Security, Jetpack Complete)

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request:

* Configure constants for the new plans that are part of the Offer Reset project: Jetpack Security Daily, Jetpack Security Real-Time, and Jetpack Complete.
* Enable these plans in the My Plan page.
* Add a SVG icon for each of them.

#### Jetpack product discussion

* Ticket: 1169247016322522-as-1187323761633593

#### Does this pull request change what data or activity we track or use?

* No. It doesn't.

#### Testing instructions:

Notes: 

* Since we haven't configure yet these plans in our backend, it isn't possible to test this unless you have access to the code (*). It might be possible to see the new products by modifying the state of the app (I haven't tried it yet).
* Please, don't forget to review the copy associated with each plan (the icon too).

(*) If you want to edit the code to test each plan, you can modify the `/jetpack/_inc/client/my-plan/index.jsx` and add to the start of the `MyPlan` component the following:
```
export function MyPlan( props ) {
    // Set the slug of the plan you want to check
	if ( props.sitePlan ) {
		props.sitePlan.product_slug = 'jetpack_security_daily';
	}
    // the rest of the code goes here...
```

Instructions:

* Run this PR (locally or with the Beta Tester plugin).
* Buy one of the new plans.
* Visit the My Plan page.
* Check that you see your new plan in the My Plan section.

##### Jetpack Security Daily
Jetpack Security Daily

##### Jetpack Security Real-Time
Jetpack Security Real-Time

##### Jetpack Complete
Jetpack Complete

#### Proposed changelog entry for your changes:

* Configure Jetpack Security Daily, Jetpack Security Real-Time, and Jetpack Complete as part of the Offer Reset project.

### CODE REVIEW

**Comment by monsieur-z** [comment]
I wasn't able to test the PR locally, but code and copy look good. We've released the icons in the `components` package in Calypso (see[ this component](https://github.com/Automattic/wp-calypso/tree/master/packages/components/src/product-icon)). I'm not familiar with the Jetpack codebase but I'm wondering if they could easily be reused here.

**Comment by rcanepa** [comment]
> I wasn't able to test the PR locally, but code and copy look good. We've released the icons in the `components` package in Calypso (see[ this component](https://github.com/Automattic/wp-calypso/tree/master/packages/components/src/product-icon)). I'm not familiar with the Jetpack codebase but I'm wondering if they could easily be reused here.

Good point. I'll investigate that.

**Comment by rcanepa** [comment]
> This looks good to me.
> 
> > Since we haven't configure yet these plans in our backend, it isn't possible to test this unless you have access to the code (*). It might be possible to see the new products by modifying the state of the app (I haven't tried it yet).
> 
> Perhaps for a follow-up PR, but this would be a good opportunity to add those new plans to our debug tools here:
> 
> https://github.com/Automattic/jetpack/blob/master/_inc/client/components/dev-card/index.jsx
> 
> For reference, those debug tools can be accessed here:
> image

TIL. I wasn't aware of these debug tools. I'm adding the new plans right now.

**Comment by rcanepa** [comment]
👋 @jeherve, I added the new Offer Reset plans to the dev tools.

Kapture 2020-08-10 at 13 08 18

**Pull request merged**
