### PR TITLE
Videopress: disable uploading for Free WoA

### PR DESCRIPTION
**Pull request by retrofox**
This PR disables uploading video files for WoA sites with a Free plan.

#### Changes proposed in this Pull Request:

* videopress: disable uploading video files for WoA with Free plan.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Test with a WoA site with a Free plan
* Go to edit a post
* Add a video block
* check the uploading buttons are disabled 

before | after
----|-----
image | image

### CODE REVIEW

**Comment by allilevine** [comment]
This is strange, this worked as expected for me on a free WoA site:

Screen Shot 2021-06-08 at 2 39 33 PM

But when I checked out the branch on my WoA developer blog with free plan, it didn't disable the buttons:

Screen Shot 2021-06-08 at 2 47 14 PM

The developer blog was previously on a Business plan, would that change the behavior here?

**Comment by retrofox** [comment]
> The developer blog was previously on a Business plan, would that change the behavior here?

Yes, you need to refresh the site options. What's your testing blog?

**Comment by pablinos** [comment]
I thought I could replicate this, but it turns out that as I made the site 'free' it stopped the Jetpack beta plugin from loading and so the code in this branch. Could it be a similar issue for you @allilevine?

**Comment by retrofox** [comment]
> I thought I could replicate this, but it turns out that as I made the site 'free' it stopped the Jetpack beta plugin from loading and so the code in this branch. Could it be a similar issue for you @allilevine?

If the Jetpack beta plugin is not there, you are testing the last stable release. So yes, it could be the problem.

**Review by allilevine — APPROVED** [review]
I'm not sure what changed, but the buttons are disabled now. ✅ 
Screen Shot 2021-06-10 at 8 56 20 AM

> I thought I could replicate this, but it turns out that as I made the site 'free' it stopped the Jetpack beta plugin from loading and so the code in this branch. Could it be a similar issue for you @allilevine?

I think I reinstalled Jetpack beta via the cli when I started testing. But definitely something to check next time!
Screen Shot 2021-06-10 at 8 54 27 AM

**Review by jeherve — APPROVED** [review]

**Comment by retrofox** [comment]
r227088-wpcom

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM in r227813-wpcom.

**Pull request merged**
