### PR TITLE
OpenTable: Don't allow duplicate restaurants in the restaurant picker

### LINKED ISSUE #14343: OpenTable block: avoid offering restaurant that's already in use
#### Steps to reproduce the issue

1. Start from a site with Beta blocks enabled.
2. Add the OpenTable block, and search for a restaurant.
3. Once you find it, click on it to add it the list of restaurants to embed.
4. Search for the same restaurant again (or the same city, for example), and you'll see the same restaurant pop up in the list of suggested restaurants, although you've already added it. 

image

I think it would be nice if we did not suggest the same restaurant twice.

### PR DESCRIPTION
**Pull request by scruffian**
Fixes #14343

#### Changes proposed in this Pull Request:

* Don't allow duplicate restaurants in the restaurant picker

#### Testing instructions:
* Add an OpenTable block to a post
* Add a restaurant to the picker
* Try searching for the same restaurant
* Check that it doesn't show up in the suggestions list

#### Proposed changelog entry for your changes:

* no changelog entry needed

### CODE REVIEW

**Comment by pablinos** [comment]
Looks good. Should we filter it out if the suggestions too?

**Comment by pablinos** [comment]
Ignore me! I’ve just seen that’s exactly what it’s doing.

Does it prevent someone typing in the same ID?

**Review by jeherve — APPROVED** [review]
This seems to work well for me. 👍

**Comment by jeherve** [comment]
r201710-wpcom

**Pull request merged**
