### PR TITLE
Add support for products on My Plan page and update layout to match mocks

### PR DESCRIPTION
**Pull request by delawski**
This PR adds a support for products to the My Plan page and adjusts the page header area layout to match the new designs.

**Please note that this PR doesn't add the action buttons like "Manage Plan" or "Manage Purchase". They need to be added in a follow-up PR.**

**Before**
Screenshot 2019-11-25 at 18 25 20

**After**
Screenshot 2019-11-25 at 18 24 12

Fixes n/a

#### Changes proposed in this Pull Request:

* Migrate `MyPlanCard` from Calypso
* Refactor `MyPlanHeader` so that it supports both plans and products
* Update `MyPlanHeader` layout to match the latest mock-ups

#### Testing instructions:

* Go to /wp-admin/admin.php?page=jetpack#/my-plan
* Check if each plan information is displayed there (free and paid plans)
* Check if both Jetpack Backup information is displayed there along with the plan information. 

#### Proposed changelog entry for your changes:

* Add `MyPlanCard` card
* Refactor `MyPlanHeader` so that it supports both plans and products

### CODE REVIEW

**Review by robertf4 — APPROVED** [review]
Excellent work @delawski! I like the code and everything tested well for me so I think this is good to 🚢

**Review by tyxla — APPROVED** [review]
LGTM, let's ship this :ship:

**Comment by enejb** [comment]
I tested this as well and it worked as expected :shipit:

**Comment by enejb** [comment]
Just wanted to note that calypso uses a different Free plan icon. 

I don't think this should hold this PR but we should address this in the future.

**Comment by delawski** [comment]
I was confused about the icons in Jetpack. There is a `PlanIcon` component that renders yet different icons than what we have here, on My Plan page, and in Calypso. I think this needs some attention and improvements in the future.

**Pull request merged**
