### PR TITLE
Removed unused references to unused fonts

### LINKED ISSUE #4508: Font stack / Dashboard Widget: remove Proxima Nova since it is not enqueued anywhere.
On WordPress 4.4, 4.5 and 4.6-beta, the "Please Connect Jetpack" dashboard widget uses Proxima Nova, a commercial font family. As very few users have that font installed as a .ttf on their computers, the box defaults to Arial.

The font family should not be declared, as it is inherited from `admin.css`.

Before:

before

After:

after

By changing `/jetpack/css/dashboard-widget.css` at line 13:

`font-family: "proxima-nova", "Open Sans", Helvetica, Arial, sans-serif;`

with:

`font-family: inherit;`

or completely removing it, the problem would be solved.

### PR DESCRIPTION
**Pull request by MichaelArestad**
Fixes #4508

#### Changes proposed in this Pull Request:
* removes all references to unused font families in favor of the native fonts already in place

### CODE REVIEW

**Comment by wolffe** [comment]
Why keep Helvetica? The widget would inherit the backend fonts, using the new native fonts.

**Comment by MichaelArestad** [comment]
@wolffe Good point. Changing. Thanks for pointing this out! 😄

**Comment by MichaelArestad** [comment]
Ready for review.

**Comment by oskosk** [comment]
LGTM !

**Pull request merged**
