### PR TITLE
Protect: Use Google Recaptcha instead of the math fallback

### LINKED ISSUE #2762: Protect: use Google Recaptcha instead of the math fallback
Jetpack already ships with Google Recaptcha, and that library is used with the Email sharing button whenever the Recaptcha keys are defined in `wp-config.php`.

It would be nice if we could use that library instead of the math fallback.

Suggested here:
https://wordpress.org/support/topic/protect-module-needs-option-to-turn-off-human-verification?replies=5&view=all#post-7478870

### PR DESCRIPTION
**Pull request by osiux**
If RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY are defined, use recaptcha as fallback instead of math problem captcha.

Looks like this:
selection_004
selection_003

Fixes #2762

### CODE REVIEW

**Comment by osiux** [comment]
Right now it has the same issue described on #2775, should we fix them together or first fix that one?

**Comment by kraftbj** [comment]
> Right now it has the same issue described on #2775, should we fix them together or first fix that one?
Let's keep them separate.

Noting the failed tests are unrelated to this PR. WP deprecated a function in trunk. PR incoming.

**Comment by dereksmart** [comment]
@osiux can you please rebase your branch against `master`?  We've fixed the failing Travis errors

**Comment by osiux** [comment]
@dereksmart done :)

Also I've seen that #2781 works fine, so once that's merged I'm going to update this one too.

**Comment by dereksmart** [comment]
@osiux just a heads up that #2781 has been merged

**Comment by osiux** [comment]
@dereksmart updated!

**Comment by samhotchkiss** [comment]
I'm going to punt this to our next release because I haven't had a chance to properly think through and review, and with internal updates to the API, users should be seeing the math fallback MUCH less often, making this a bit of a moot point.  But I'll dig a little deeper down the road...

**Comment by osiux** [comment]
Sounds good, I rebased the code just in case.

**Comment by samhotchkiss** [comment]
Hey @osiux -- after some thought, I think that we'll pass on integrating this into the main Jetpack plugin because it hits such a small subset of users-- users who are both having trouble connecting to the API (which, with recent improvements, is very rare) and who have recaptcha creds.

However, I'd be totally open to accepting a PR adding the necessary hooks to allow this to be an add-on plugin

**Comment by osiux** [comment]
Hey @samhotchkiss! No problem, sounds good to me, I'll see what can be done as soon as I have some free time :)

**Pull request closed without merging**
