### PR TITLE
Editor: remove deprecated isPressed prop in WP 6.5.

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

The isPressed prop is deprecated in WP 6.5, and replaced by the native aria-pressed attribute.

https://github.com/WordPress/gutenberg/pull/54740

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* #33615 

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Check how the different buttons impacted by this PR behave when pressed.

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
I note that this change causes the button to no longer display as "pressed" in WordPress 6.4.

**Comment by jeherve** [comment]
> I note that this change causes the button to no longer display as "pressed" in WordPress 6.4.

I think that would be okay to be like this for a few months on self-hosted sites, until WP 6.6 comes along, but I'm happy to be overruled on this.

**Comment by anomiex** [comment]
> I think that would be okay to be like this for a few months on self-hosted sites, until WP 6.6 comes along, but I'm happy to be overruled on this.

Just for clarity, I claim no power to make that decision. I pointed it out so whoever is a decision-maker about this would have the data. 🙂

**Review by fgiannar — APPROVED** [review]
LGTM 🚢 

> I think that would be okay to be like this for a few months on self-hosted sites, until WP 6.6 comes along, but I'm happy to be overruled on this.

I agree it's fine, therefore approving :)

**Pull request merged**
