### PR TITLE
Storybook: Try adding support for `@storybook/test-runner`

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Storybook has a `@storybook/test-runner` package, which can be used to make sure the stories at least work (and can be used for integration testing too if such tests are written). This tries adding that package and running it in CI.

To not have to build all the deps before we can run the test, let's set `jetpack:src` in storybook's webpack config like we do in our own. Hopefully that also means we can remove the `extra.dependencies.build` from composer.json too, which may speed up the builds a little by not having to have storybook wait until the end.

To make the output from that a bit more friendly, let's also make storybook development builds not minify.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1708449385672469/1708444782.597729-slack-CDLH4C1UZ
Announcement: pdWQjU-Ip-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Is CI running the storybook test thing?
* Does the output from all the failing tests look sensible?

### CODE REVIEW

**Review by pyronaur — DISMISSED** [review]
tenor

**Review by zinigor — DISMISSED** [review]
Changes look good, and I even tested this locally, the runner works great. The only problem is the failing tests, which I guess we can take care of in the following PRs.

**Comment by anomiex** [comment]
Note we shouldn't merge this until either the tests pass or we figure out the right setting ([this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) I think?) to not email on every PR about the Tests workflow failing because of this.

**Comment by anomiex** [comment]
Looks like that worked.

Also I drafted an announcement for it: pdWQjU-Ip-p2

**Comment by pyronaur** [comment]
Looks good to go. P2 post looks good as well. Only blocking thing right now is a merge conflict.

**Comment by anomiex** [comment]
PHP tests: PHP 8.2 WP trunk fail is unrelated, see p1709562619872529/1709562558.619689-slack-C034JEXD1RD for details.

**Review by samiff — APPROVED** [review]

**Pull request merged**
