### PR TITLE
Carousel: update prev/next nav button colors

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

Sometimes the carousel is showing blue prev/next nav buttons (regardless of black/white carousel color scheme):

Screen Shot 2021-09-02 at 1 53 25 PM

Edit: Seems like the root issue has to do with CSS file load order, see: https://github.com/Automattic/jetpack/pull/20940#issuecomment-912148708

#### Jetpack product discussion

Internal, asked in testing: p8oabR-IS-p2#comment-5467

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* After applying changes, you should see the carousel nav buttons be based off the carousel color scheme rather than being blue all the time.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@samiff I wasn't able to replicate the blue foreward/next on a local jetpack env, I see the following on master with black and white options:

Screen Shot 2021-09-03 at 9 13 51 AM
Screen Shot 2021-09-03 at 9 14 41 AM

**Comment by samiff** [comment]
> I wasn't able to replicate the blue foreward/next on a local jetpack env, I see the following on master with black and white options:

Hmm strange, looks like the color var is set here:

https://github.com/Automattic/jetpack/blob/af2d6905f184372d150f24afef95f7c548291660/projects/plugins/jetpack/modules/carousel/swiper-bundle.css#L200-L207

The nav button elements would need the `.swiper-button-black` or `.swiper-button-white` classes to pick that up (added in this PR), that's why `--swiper-navigation-color` is grayed out in my screenshot and it's falling back to the `--swiper-theme-color` color.

Maybe something is caching on your end, try in a private/guest window perhaps?

**Comment by glendaviesnz** [comment]
Strange, I get the same result with or without this PR applied and in an incognito window, will get someone else in the team to take a look as well.

**Comment by glendaviesnz** [comment]
We are unable to replicate this issue on a local or JN site.  You shouldn't be seeing those large prev/next buttons at all, you should instead see the smaller custom buttons below:

Screen Shot 2021-09-03 at 9 13 51 AM

so it will be best to work out why the custom buttons are not displaying in some contexts, rather that setting the colour of the default swiper buttons.

**Comment by glendaviesnz** [comment]
ok, so looks like the issue is:

When run locally and on WPcom there are two css files loaded `swiper-bundle.css` is loaded first which is the default swiper styles  which includes the large blue prev/next buttons. Then `jetpack-carousel.css` is loaded after this which has the overrides for the custom prev/next buttons.

When run on a JN site there is only a single `jetpack.css` file which is pulling in `jetpack-carousel.css` first and then `swiper-bundle.css` so the overrides are not being applied. 

So we just need to work out how to change the concatenation order of these two files into `jetpack.css` to ensure that `swiper-bundle.css` is always includes before  `jetpack-carousel.css`

**Comment by glendaviesnz** [comment]
@samiff I pushed a change which looked like it should fix it - and it does seem to fix the colour issue, but still showing the wrong size icon, will take another look at it later this afternoon

**Comment by glendaviesnz** [comment]
Despite changing the order the files are listed in `projects/plugins/jetpack/class.jetpack.php` and `projects/plugins/jetpack/tools/builder/frontend-css.js` the concat css file seems to still have them with the `jetpack-carousel` css file first. @samiff Do you know how we can ensure that `swiper-bundle.css` always gets pulled into the jetpack.css concat file ahead of `jetpack-carousel.css`?

**Comment by samiff** [comment]
@glendaviesnz Nice sleuthing on this 🕵️  With the change you've made, on my local dev I'm able to see the `swiper-bundle.css` at the top of `jetpack.css`, and the navigation buttons look great! I'm also able to see the same on a JN site with this branch pulled down via the JP Beta plugin. Where were you testing that it wasn't working for you still?

I also tested putting the file order back, rebuilding (`jetpack build plugins/jetpack`), and was able to see the incorrect blue arrows again, so that seems like the lever we are looking for here.

**Review by glendaviesnz — APPROVED** [review]
@samiff this is testing correctly for me now on a JN site, not sure why it wasn't on Friday. Correct button styling shows with the bundled single jetpack.css file:

carousel

**Review by jeherve — APPROVED** [review]

**Comment by samiff** [comment]
r231311-wpcom

**Comment by sdixon194** [comment]
Cherry picked to release branch in 5d4670eed94492b8a6f65d925ccb298be1dbb35b.

**Pull request merged**
