### PR TITLE
Inline Docs: 4.1->4.1.0

### PR DESCRIPTION
**Pull request by kraftbj**
Updates the version number on a number of inline docs, trims some whitespace that snuck in, and addresses lack of full docs in https://github.com/Automattic/jetpack/pull/4073/files#r65800739

cc: @jeherve

### CODE REVIEW

**Comment by jeherve** [comment]
LGTM!

**Comment by dereksmart** [comment]
:shipit:

**Comment by kraftbj** [comment]
Since Sync and SSO will likely ship in separate releases, holding this PR until final confirmation.

**Comment by jeherve** [comment]
@kraftbj Looks like Sync will ship in 4.2. Want to take this in, and update all related filters? I tried to triage all related issues and PRs and assign them the right milestone (4.2) and the right label, so you should be able to track a lot of those down here on GitHub.

**Comment by kraftbj** [comment]
Rebased to remove touching the sync files. Since they're going in later, a separate PR to update all of those should be fine. Remilestoning to 4.1.

**Pull request merged**
