### PR TITLE
Upgrade ESLint to 5.12.0

### PR DESCRIPTION
**Pull request by jsnajdr**
ESLint upgrade to latest version. Needed mainly to move Babel upgrade in #10810 forward. Old ESLint uses old version of the `babel-eslint` package that's not compatible with Babel 7.

There is plenty of new ESLint errors reported now, as the rules got upgraded:
- instantiating functions inside `connect` -- leads to unnecessary rerenders
- JSX a11y warnings
- warnings about legacy React lifecycle methods
- duplicate ES module imports
- legacy string refs in React

I'll leave it up to the Jetpack team to decide whether they want to fix the issues or disable the offending rules.

### CODE REVIEW

**Comment by jeherve** [comment]
Related:

#10822

And further changes:
#10823
#10825
#10827

**Comment by jsnajdr** [comment]
OK all these PR seems to do the same thing. That's a good sign 😄 What are the next steps (cc @brbrr). Can I help with something?

**Comment by brbrr** [comment]
I'll be happy to take it over :)

**Comment by brbrr** [comment]
I went through all the ESLint errors and tried to fix all of them. Unfortunately, some of the errors are trickier than other errors, so I disabled some rules with the intention to tackle these errors later with a more incremental approach: https://github.com/Automattic/jetpack/issues/11142

Most rule fixes are grouped by commits for ease of review (you might not want to review the all the changes at once)

**Comment by kraftbj** [comment]
@brbrr I took a look and everything made sense to me. Would you be game for a rebase and we can get it across the line ASAP after the rebase.

**Comment by brbrr** [comment]
Rebased! Let's push it through :)

**Review by kraftbj — APPROVED** [review]
Code changes make sense to me. Built fine and the dashboard works as expected with changing settings, etc.

**Pull request merged**
