### PR TITLE
Sharing: Bump character limit to 280 in Twitter sharing source

### LINKED ISSUE #8325: Sharing: increase twitter title character limit to 280
Twitter has recently bumped up character limit to 280, however the change has not been reflected in Twitter sharing source: 
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L716

PR incoming.

### PR DESCRIPTION
**Pull request by rinatkhaziev**
Fixes #8325

Bump character limit to 280 when sharing a post via Twitter.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
Thanks for the quick turnaround

**Comment by lancewillett** [comment]
OK to merge this one?

**Comment by jeherve** [comment]
Yes, we will merge it and it will be included in the next release.

**Comment by oskosk** [comment]
Cherry-picked to `branch-5.6` in c38a53808eaf8529eef38362e544039994e2724e

**Pull request merged**
