### PR TITLE
Testing: Enable WP_Test_Jetpack_PHP_Lint for all PHP versions

### LINKED ISSUE #9862: Linting: Do a compatibility check for all the supported PHP versions
Inspired by: https://github.com/Automattic/jetpack/issues/9858

To prevent issues like these we need to do an automated check to prevent any sort of syntax errors across all the supported PHP versions

### PR DESCRIPTION
**Pull request by brbrr**
Fixes: #9862

#### Changes proposed in this Pull Request:

* Enable WP_Test_Jetpack_PHP_Lint for all PHP versions

#### Testing instructions:

Make sure that `WP_Test_Jetpack_PHP_Lint` is running for every PHP version. This branch includes syntax errors for PHP 5.2, so that job will be failing until fixed

### CODE REVIEW

**Comment by abidhahmed** [comment]
`Parse error: syntax error, unexpected '[', expecting ')' in ./tests/php/modules/geo-location/test_class.jetpack-geo-location.php on line 40`

Looks like we need to refactor the test code as that's the only one failing at the moment.

**Review by abidhahmed — COMMENTED** [review]
Looks good, only thing failing is the test code.

**Comment by oskosk** [comment]
This is great. Should we fix the code problems here or on other PRs? What do you think @brbrr @abidhahmed ?

**Comment by abidhahmed** [comment]
I vote to fix it here! 🍦

**Comment by brbrr** [comment]
@oskosk should I rebase and maybe merge this or #9869 is a better candidate for enabling linting test?

**Comment by brbrr** [comment]
I rebased this branch with master to include some recent compatibility fixes

**Comment by brbrr** [comment]
Closing in favor #10026

**Pull request closed without merging**
