### PR TITLE
Compat: update GlotPress locales

### PR DESCRIPTION
**Pull request by myhro**
Part of #2707.

## Proposed changes:

The process of updating the GlotPress locales isn't so straightforward as just [copying the file][locales.php] over the monorepo's local copy. Their formatting differ throughout the file.

In order to make clear what is being changed, I took care of ensuring the indentation/formatting is preserved and the vertical alignment (e.g. on variables attribution) is kept consistent. This resulted in a meaningful diff, although GitHub might not show it by default because of the still large number of lines changed.

Even if we don't implement [all the suggestions][suggestions] made in the aforementioned issue, my understanding is that it's still valuable to keep the `GP_Locales` copy in sync with the GlotPress version.

Pinging @jeherve as the suggestion author.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

[locales.php]: https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/locales/locales.php
[suggestions]: https://github.com/Automattic/jetpack/issues/2707#issuecomment-2036701663

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This looks good to me. Thanks for working on that!

**Comment by jeherve** [comment]
Marking as ready to merge for now, but we'll have to come back and run the tests again in a few hours. GitHub is currently experiencing issues with [Pages, Actions, Codespaces, API Requests, Issues and Pull Requests](https://www.githubstatus.com/incidents/5ly0psff2s5d)
[Subscribe](https://www.githubstatus.com/#subscribe-modal-5ly0psff2s5d), and it's causing all tests to fail.

**Comment by anomiex** [comment]
Looks like CI is flagging two issues that will need to be addressed:

* https://github.com/Automattic/jetpack/pull/36748/files#annotation_20119971958 (note it appears you'll have to expand the diff on `projects/packages/compat/lib/locales.php` to see the issue at the link)
* https://github.com/Automattic/jetpack/pull/36748/files#annotation_20119353430

**Comment by myhro** [comment]
Thank you both for reviewing the PR.

I've fixed the CI check failures and also sent a small patch upstream. This will ensure the issue won't appear again anytime the locales are re-imported: https://github.com/GlotPress/GlotPress/pull/1827

**Review by jeherve — APPROVED** [review]

**Pull request merged**
