### PR TITLE
Search: don't translate product name in wp-admin menu

### LINKED ISSUE #20906: Instant Search: 'Search' product name should not be translated in menus
### Impacted plugin

Jetpack

### Steps to Reproduce

1. With your interface language set to something other than English, go to wp-admin on a site with Instant Search enabled.
2. Have a look at the menu under 'Jetpack'.

(This also applies to the equivalent Calypso and Jetpack Cloud menus.)

### A clear and concise description of what you expected to happen.

"Search" is a Jetpack product name and should not be translated.

### What actually happened

'Search' is translated in the menu, meaning it is called "Recherche" in French.

### Other information

Screen Shot 2021-09-01 at 14 39 56

On Jetpack.com it is not translated:

Screen Shot 2021-09-01 at 15 16 43

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request:
Fixes #20906.

Search was appearing as 'Recherche' in the wp-admin when the interface language is French.

Generally we do not translate the product name - see https://jetpack.com/upgrade/search/ for example.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* On a site with Jetpack Search enabled, go to wp-admin.
* Make sure your interface language is set to a non-English language.
* Make sure the Jetpack menu contains an item 'Search'.

Screen Shot 2021-09-02 at 16 21 59

### CODE REVIEW

**Comment by bluefuton** [comment]
Interestingly I notice we do translate product names in Calypso ("Scan" for example), so perhaps it's the case that we translate a full product name "Jetpack Search" but leave "Search" translated?

**Comment by jeherve** [comment]
I'd be curious to have Team Global's take on this. I am not sure what the best course of action is here, and maybe that's also an indicator that a submenu named just "Search" may be misunderstood by English speakers as well, they may expect something different when clicking on it.

**Comment by bluefuton** [comment]
Thanks @jeherve 👍 I'll P2 about it and get some input from Team Global.

**Comment by bluefuton** [comment]
Asked for feedback in pxLjZ-6Bs-p2.

**Comment by bluefuton** [comment]
Discussion in pxLjZ-6Bs-p2 confirms that we'll stick with the translated string in the menu, but add a translator context to make it clear where the string will appear.

**Pull request closed without merging**
