### PR TITLE
Shortcode: Update Mixcloud oEmbed url and fix up typos

### PR DESCRIPTION
**Pull request by matclayton**
1. Update to use Mixcloud's new oEmbed url, as Wordpress didn't follow 301's
2. Fix up a few typos in the company name

Fixes #

#### Changes proposed in this Pull Request:

* We're doing some URL hygiene work and need to move this endpoint around, this change reflects that, and the new endpoint is operational already.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Review by ben-xo — DISMISSED** [review]
Looks good to me. Will be surprised if any tests fail

**Review by jeherve — APPROVED** [review]
This tests well for me, it should be good to merge!

I should note that Mixcloud embeds are also enabled in WordPress Core itself, so if you haven't done so yet, it may be worth updating the URL there as well:
- https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-oembed.php#L80
- https://make.wordpress.org/core/handbook/contribute/fixing-bugs/

**Comment by matclayton** [comment]
Thanks @jeherve thats my next job :) Much appreciate the review, merge and all the great work!

**Comment by matclayton** [comment]
Matching trac for Wordpress core embeds https://core.trac.wordpress.org/ticket/57376

**Pull request merged**
