### PR TITLE
Jetpack: improve QR Post code site/Jetpack logo

### PR DESCRIPTION
**Pull request by retrofox**
This PR tweaks the QR post code logo either for the site logo, or for the Jetpack logo when the site doesn't have it.

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack: improve QR Post code site/Jetpack logo

#### Testing instructions:

* Edit a post via Block editor
* Take a look at the QR Post code 
* Confirm the following visual changes

Without site logo

before | after
------|------
image | image

With site logo

before | after
------|------
image | image

### CODE REVIEW

**Comment by retrofox** [comment]
> I was thinking that we could end up doing the opposite, and completely get rid of the `JetpackLogo` set in the extensions. Couldn't we use the one from Jetpack Components instead, and make any improvements to that component?

We were using that logo, then used the shared one, but agree with you we should try to go back to use the jetpack-components one.
I switched to this one because I introduced some changes in the API that I wasn't sure about it.

My opinion is we should use this one, and then iterate in another PR to switch to the jetpack-components in case we agree about the changes proposed here. Clearly, in a follow up task.

**Comment by kraftbj** [comment]
> My opinion is we should use this one, and then iterate in another PR to switch to the jetpack-components in case we agree about the changes proposed here. Clearly, in a follow up task.

No objection to that.

**Review by kraftbj — APPROVED** [review]

**Review by dereksmart — APPROVED** [review]

**Comment by retrofox** [comment]
> Great news! One last step: head over to your WordPress.com diff, D76879-code, and commit it.
> Once you've done so, come back to this PR and add a comment with your changeset ID.

r241909-wpcom

**Comment by retrofox** [comment]
> I was thinking that we could end up doing the opposite, and completely get rid of the `JetpackLogo` set in the extensions. Couldn't we use the one from Jetpack Components instead, and make any improvements to that component?

Ideally, we may start to work on a new `@automattic/jetpack-icons` pkg?

**Comment by jeherve** [comment]
> we may start to work on a new @automattic/jetpack-icons pkg?

I don't know what's best here. We already have `@automattic/social-logos` ([ref](https://github.com/Automattic/social-logos)), I don't know if we need a new icons package. Maybe just a new icons components within Jetpack Components would be enough for now?

**Comment by retrofox** [comment]
I dived into the components pgk but just realized that maybe the structure is not the best considering that I think:

* It should be 100% core friendly.
* The API should be pretty simular to the core, too.

For instance, to use an icon with core, you should do something like:

```es6
import { Icon, create } from '@wordpress/icons';

function MyComponent() {
  return (
    <Icon icon={ create } size={ 48 } />
  );
}
```

```es6
import { Icon } from '@wordpress/icons';
import { jetpack } from '@automattic/icons';

function MyComponent() {
  return (
    <Icon icon={ jetpack } size={ 48 } />
  );
}
```

The question is how to expose the icons using the current jetpack-components pkg. :-/

**Pull request merged**
