### PR TITLE
Remove unused gulp tasks

### PR DESCRIPTION
**Pull request by brbrr**
While going through some of the renovate PRs I noticed that there some of the tasks are unused or useless/redundant

Removed tasks:
- `gulp eslint` - not used
- `gulp php:lint` - not needed since we have `yarn php:lint`
- `gulp php:unit` - not needed since we have `yarn docker:phpunit`
- `gulp php` - parallelized `php:unit` & `php:lint`
- `gulp check:DIR` - not needed, since we already running 5.2 compatibilty  
- `checkstrings` - parallelized `check:DIR`

Also removed dependencies that no longer needed.

#### Changes proposed in this Pull Request:

* remove unused gulp tasks

#### Testing instructions:

* make sure these tasks aren't used in dev/release process 

#### Proposed changelog entry for your changes:

none needed

### CODE REVIEW

**Comment by oskosk** [comment]
wow

**Review by oskosk — DISMISSED** [review]
LGTM! 

One note: I'd think that the one who added these tasks as dependencies to others may have had the intention of running this lint checks while in the process of building. Not quite sure though.

**Comment by brbrr** [comment]
It seems like `php` task was added in https://github.com/Automattic/jetpack/pull/3800, which was initial react UI PR.

**Review by oskosk — APPROVED** [review]
LGTM!

**Pull request merged**
