### PR TITLE
My Jetpack: reduxify purchases data

### PR DESCRIPTION
**Pull request by retrofox**
This PR _reduxses_ the purchases data. Currently, the data is stored at the component level.

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

* Easier once https://github.com/Automattic/jetpack/pull/22356 merges
* Test with a site with some purchases / plans
* Go to My Jetpack dashboard.
* Confirm you see the plans list in the Plans Section
* Check the redux implementation, filtering by `my-jetpack`

* Check the client hits the `/purchases` endpoint

#### Tests

```cli
> jetpack test packages/my-jetpack js
```

### CODE REVIEW

**Comment by retrofox** [comment]
Going to add tests in a follow up PR

**Comment by retrofox** [comment]
> Going to add tests in a follow up PR

Actually, added basic tests here https://github.com/Automattic/jetpack/pull/22368/commits/57a8788407757f47de6bec972ef2e0cd3113d753

**Review by oskosk — APPROVED** [review]
Tests well!

**Comment by oskosk** [comment]
Will push commit with rebase

**Comment by oskosk** [comment]
Pushed 15a21abc04fe783bad75fab1258205905a3feda6 with the rebase. Will be back for merging

**Comment by oskosk** [comment]
Had to merge master with 49240a399c263cc9f1b1922371aab8dc88e0ddef again as  the release of Jetpack backup in 9b2397dbdb29da077e75e67830446a266e50fb2f forced this branch out of date again.

**Comment by oskosk** [comment]
Pushed 3e398e93b9ac2c78c101d8e7b39e2fe2736ec350 to take in account the difference with 22368

**Pull request merged**
