### PR TITLE
VideoPress: WebVTT file content generation from video description chapters

### LINKED ISSUE #26172: VideoPress: detect chapters from video description
Create a helper function to detect and extract the Video chapters text from the block description:

Image

Given the whole text description, the function should be able to pick the text of the chapters:

**block description =>**

```
This is the introduction of the text...
and now, the chapters

00:00 Intro
00:06 Presentation
10:02: End

I hope you enjoy the video. Thanks for watching...
```

**=> chapters chapters text**
```
00:00 Intro
00:06 Presentation
10:02: End
````

### LINKED ISSUE #26189: VideoPress: generates .vtt format from chapters text
https://www.w3.org/wiki/VTT_Concepts#Chapter_Tracks

### PR DESCRIPTION
**Pull request by dhasilva**
Closes #26172 (moved from VideoPress package to Jetpack plugin)
Closes #26189

#### Changes proposed in this Pull Request:

* Moves the files from #26181 to Jetpack plugin
* Adds helper functions to generate the contents of a webVTT file of video chapters

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Run `jetpack test plugins/jetpack js`
* Check that `extensions/blocks/videopress/video-chapters/utils/test/extract-video-chapters.ts` passes
* Check that `extensions/blocks/videopress/video-chapters/utils/test/generate-chapters-file-content.ts` passes

Note: Some unrelated tests are not passing.

### CODE REVIEW

**Review by retrofox — DISMISSED** [review]
LGTM.
Something to keep in mind it these functions picks individual chapter line. Given the following text:

```txt
This is the introduction of the text...
and now, the chapters

00:00 Intro
00:06 Presentation
10:02: End

I hope you enjoy the video. Thanks for watching...
10:02: End

10:02: End

Hola

createHTMLDocument is ....

10:02: End
`;
```

the parser returns:

image

**Comment by retrofox** [comment]
```
[test-extensions]  PASS  extensions/blocks/videopress/video-chapters/utils/test/extract-video-chapters.ts
```

```
[test-extensions]  PASS  extensions/blocks/videopress/video-chapters/utils/test/generate-chapters-file-content.ts
```

**Review by retrofox — COMMENTED** [review]
some tests are failing in wpcom

**Comment by dhasilva** [comment]
> 



> LGTM. Something to keep in mind it these functions picks individual chapter line. Given the following text:
> 
> ```
> This is the introduction of the text...
> and now, the chapters
> 
> 00:00 Intro
> 00:06 Presentation
> 10:02: End
> 
> I hope you enjoy the video. Thanks for watching...
> 10:02: End
> 
> 10:02: End
> 
> Hola
> 
> createHTMLDocument is ....
> 
> 10:02: End
> `;
> ```

That is by design. Take a look at [this video](https://www.youtube.com/watch?v=TQUy8ENesGY) description that youtube parsed correctly:
Screenshot_2022-09-14_10-47-13

If the parser only gets uninterrupted blocks of timestamps, it would not parse this description.

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by retrofox** [comment]
r252534-wpcom

**Pull request merged**
