### PR TITLE
Boost: Cleanup dangling files and rules to remove files from production release

### PR DESCRIPTION
**Pull request by davidlonjon**
#### Changes proposed in this Pull Request:

* Remove the `.wordpress-org` folder and files. From what I can see in this monorepo, tt seems that WordPress.org files might be handled another way. As a result I am removing these files from the repo as they might not be needed anymore. I guess we could ultimately remove also the https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/.github/workflows/wp-org-deploy.yml ? I am not completely sure about this cleanup here as I don't fully understand the new release process.
 * Remove the `.distignore` file as it was used to ignore files during a release in the legacy repository and by the github action above.
 * Remove the `.dockerignore`. The whole Docker setup specific to Jetpack Boost will be cleanup in a follow up PR but I thought I'll remove this file now so I don't have to add it in the 'gitattributes` file.
 * Add rules to ignore more files and folders for production release. I tried to follow the standard from the similar file in the Jetpack plugin folder.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

* At the next release make sure that the https://github.com/Automattic/jetpack-boost-production repo does not contain any of the files which have been deleted in this patch or the ones added to the `.gitattributes` file.

### CODE REVIEW

**Comment by davidlonjon** [comment]
@jeherve , @kraftbj ,

Re 
image

in https://github.com/Automattic/jetpack/pull/20617/files, do I need to fix it in this PR by running the `tools/project-version.sh -u 1.2.1-alpha plugins/boost` command and then commit in this PR the resulting changes done to `projects/plugins/boost/composer.json`, `projects/plugins/boost/jetpack-boost.php` and `projects/plugins/boost/package.json`. I am not sure to fully understand why this is happening?

**Comment by jeherve** [comment]
> do I need to fix it in this PR by running the `tools/project-version.sh -u 1.2.1-alpha plugins/boost` command and then commit in this PR the resulting changes done to `projects/plugins/boost/composer.json`, `projects/plugins/boost/jetpack-boost.php` and `projects/plugins/boost/package.json`. I am not sure to fully understand why this is happening?

This is happening because @thingalon recently released a new (Beta) version of the Boost plugin. We usually follow such a release by an update of the version numbers in the monorepo to effectively start a new release cycle. 

I've done that in https://github.com/Automattic/jetpack/pull/20619 to get us started. Once this is merged, we should be able to move forward.

**Comment by kraftbj** [comment]
20619 was merged. Brought it into this branch.

We don't have an automated deployment to w.org step (our philosophy is for the critical step of putting it into the delivery repo, we like to have a couple eyes on it to make sure everything is snazzy), so we don't keep w.org assets in this repo at this time, so should be fine to remove from here.

**Review by thingalon — APPROVED** [review]
My only point of confusion was removing the `.wordpress-org` directory,  but from the above comments it looks like that is managed elsewhere 👍

**Review by jeherve — APPROVED** [review]
One last master update to try to unblock all the stuck tests caused by yesterday's GitHub outage. :)

**Comment by thingalon** [comment]
Cherry-picked to `boost/branch-1.2.0` in 28927561d.

**Pull request merged**
