### PR TITLE
Settings UI: link to a release post in the welcome notice

### PR DESCRIPTION
**Pull request by eliorivero**
I'd prefer if we get this https://github.com/Automattic/jetpack/issues/7375 in, but just in case, here's this PR that addresses this issue in the UI.
If we get that one in, let's close this one and add a PR that entirely deletes this notice instead.

❗️❗️ Before merging this, let's add the proper link to the release post ❗️❗️ 

#### Changes proposed in this Pull Request:

* underline links in notice text, following Notices section example at https://wpcalypso.wordpress.com/devdocs/design
* display a link to the release post
captura de pantalla 2017-07-25 a las 13 43 16

#### Testing instructions:

* update version and make sure the link is shown

### CODE REVIEW

**Comment by beaulebens** [comment]
Can we use that "split" notice style where the action/CTA/link is highlighted slightly, and right-aligned?

@MichaelArestad @rickybanister

**Comment by rickybanister** [comment]
@beaulebens sometimes that's weird when used next to the dismiss X. Folks do it, but I like avoiding it. 

On WordPress.com links within notices are underlined, seems like that's the regression here. 

Also the 'warm welcome' will replace this soonish.

**Comment by eliorivero** [comment]
Updated style (and screenshot) so the links in notice texts are underlined following Calypso.

**Comment by beaulebens** [comment]
Good point with the dismiss, and the underline being what's missing here to make the link obvious. Looks fine to me now, thanks @eliorivero 🚢

**Comment by dereksmart** [comment]
PR for full-screen welcome notice is here #7531

**Comment by eliorivero** [comment]
Closing this since #7531 was merged.

**Pull request closed without merging**
