### PR TITLE
Payments Block: Remove notice from canvas

### LINKED ISSUE #46884: Payments Block: issues with Banners and Block Preview
The Premium Payments Block features two banners, one to note that it's premium another to provide a link to learn more about the block.

Here's what the block looks like when first inserted into the editor.

image

Three issues pop up here.

- The block toolbar covers up the premium banner upon first view.
- The learn more banner is difficult to read. (Styles not specific enough? The active theme is Mayland.)
- The learn more banner appears even when the block is unselected.

Here's a screenshot of the unselected block in the Editor.

image

The learn more banner creates an additional issue when used in a block pattern. Here's a screenshot of the the payments block in a test block pattern.

image

The banner displays in the pattern inserter and will continue to appear in block patterns when the block is unselected.

image

Both banners can appear together in block patterns and cause a pattern to appear strange when the block is selected.

image

### PR DESCRIPTION
**Pull request by apeatling**
Remove the notice in the canvas that often appears unreadable that links to fee structure for payments. Instead add this to the sidebar for the block and make it persistent. This also helps better support block patterns that will use this block.

**Before**

Screen Shot 2020-11-02 at 12 52 36 PM

**After**

Screen Shot 2020-11-02 at 12 51 09 PM

Partially fixes https://github.com/Automattic/wp-calypso/issues/46884

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Check out this branch locally.
* Sync this branch to your WordPress.com sandbox.
* Sandbox a WordPress.com site
* On this site insert a payments button
* Confirm that you do not see the message in the canvas as appears in the before picture above.
* Confirm that you see the message in the sidebar when the payments block is selected.

#### Proposed changelog entry for your changes:

* Fixed an issue with the Payments block and an unreadable notice.

### CODE REVIEW

**Review by glendaviesnz — DISMISSED** [review]
LGTM

**Review by jeherve — DISMISSED** [review]

**Comment by apeatling** [comment]
@jeherve Thanks. :+1: The failing test, it looks unrelated, what do you think?

**Comment by jeherve** [comment]
> The failing e2e test, it looks unrelated, what do you think?

Yep, it should be fine. The PHP 8 linting action was problematic here though. I've rebased, that should take care of things.

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
r219426-wpcom

**Pull request merged**
