### PR TITLE
Add an i18n framework from Calypso.

### PR DESCRIPTION
**Pull request by dereksmart**
**_Copy of @zinigor's branch from jetpack-react_**

This PR adds Calypso as npm dependency and borrows some of Calypso's functionality in order to provide i18n capabilities to client-side code.

- [x] Add Calypso as dependency.
- [x] Create a build script that will import strings from JS into a PHP file in order to translate them.
- [x] Add a mechanism that will export strings from PHP to JS in order enable the i18n mixin to use them.

To test:

- run `npm build` to generate necessary files in dependencies.
- use the plugin as usual, it should work properly.
- try to `import { translate as __ } from 'lib/mixins/i18n'` in your module.
- try to use `__( 'Translatable string' )` instead of `Translatable string` in your code.
- try to switch your WordPress to a different language and see if [already translated strings](https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/es/default) appear properly translated. 
- bonus points if you try to use placeholders and plural versions of strings, you can read more about that in [the mixin docs](https://github.com/Automattic/wp-calypso/tree/master/client/lib/mixins/i18n).
- extra bonus points if you use `__` for your module and run `npm build` again. You should see the newly generated `jetpack-strings` file with your newly added strings.

### CODE REVIEW

**Comment by jeherve** [comment]
Are we going to be loading one new json file for each language in Jetpack? With so many new files, that seems like it could greatly increase chances of a failed plugin update on sites with limited resources.

**Comment by zinigor** [comment]
Yes, it's going to be pretty heavy, so my plan is to only include things that are needed on the client in the JSON file. It's going to be not more than what we had with .po and .mo files. After that I had an idea of compiling JSON files using existing translation packs, but I haven't yet looked into it, so I don't know if it's possible.

**Comment by jeherve** [comment]
I assume you've considered that option, but wouldn't it be possible to host them on WordPress.com, like we do for notifications?

**Comment by dereksmart** [comment]
after building fresh, the app fails to load and I get `Uncaught TypeError: Cannot set property 'localeSlug' of undefined`

**Comment by dereksmart** [comment]
after poking around, the problem is that there is no `languages/json/jetpack-en_US.json` file lol

**Comment by beaulebens** [comment]
I verified that I can build and run this, and it appears to work. I also added some calls to `translate` (as `__`) in a component, and translated the string "Learn More" successfully.

I also re-ran `npm run build-i18n` after adding the calls to `__` and verified that my strings were added into `_inc/jetpack-strings.php`.

**Comment by beaulebens** [comment]
Also confirmed that plurals are working.

**Comment by ntwb** [comment]
This is pretty awesome, that said you might want to update `/trunk` on w.org so translators have a little more time to update strings before you release Jetpack 4.1

https://plugins.trac.wordpress.org/browser/jetpack/trunk

**Comment by zinigor** [comment]
@ntwb Yes, thank you for the reminder. We plan to get these strings into `/trunk` as soon as the beta hits, which will be several weeks before the actual release.

**Pull request merged**
