### PR TITLE
Verification Tools: Update example text (#8485)

### PR DESCRIPTION
**Pull request by UP-Nguyen**
Update example text (#8485)

Fixes #

#### Changes proposed in this Pull Request:
Update example text (#8485)
*

#### Testing instructions:

*

### CODE REVIEW

**Comment by UP-Nguyen** [comment]
Hello!

Sorry, this was my first time using Github to contribute to an open-source project. Aren't the two files essentially the same?

**Comment by UP-Nguyen** [comment]
Should I just delete the uploaded one?

**Comment by UP-Nguyen** [comment]
Because on #8522 it shows the changes, what they are supposed to do, etc

**Comment by jeherve** [comment]
Ok. Let's close this in favor of #8522 then. 👍

**Pull request closed without merging**
