### PR TITLE
Post Images: allow passing size when searching for images in HTML.

### PR DESCRIPTION
**Pull request by jeherve**
#### Testing instructions:

1. Insert an image in a post. It should be a big image. It can be hosted somewhere else.
2. Publish the post.
3. Visit that post a few times while logged out.
4. Add the Top Posts widget to your site and configure it to show images list.
5. The post should use the image from the post, and not a fallback image.

#### Proposed changelog entry for your changes:
* Post Images: allow passing size when searching for images in HTML.

### CODE REVIEW

**Comment by oskosk** [comment]
I couldn't find any difference when testing this PR in contrast to the behavior shown in master. I'm gonna have to punt to 5.8. I may be confused about what ` fallback image` means here.

**Comment by jeherve** [comment]
> I may be confused about what fallback image means here.

fallback image can be the post author's Gravatar image for example, or your site's icon /  logo. We should use the image inserted in the post instead.

**Comment by oskosk** [comment]
It's just the even when trying `master` I got to see the image I chose in the widget and couldn't get to see anything else

**Comment by jeherve** [comment]
> I got to see the image I chose in the widget and couldn't get to see anything else

Try adding an image that is not set as featured image, not attached to the post, not in a gallery, but only added to the body of the post.

**Comment by oskosk** [comment]
Sorry @jeherve . I've tested this numerous times with fresh sites... Here's a screenshot from a fresh site, **without** the changes introduced in this PR.


image

Here are the widget settings.



The steps I've followed:
1. Created a Fresh blank site.
2. Created a new post titled "Hello". Added [this image](http://bute-park.com/wp-content/uploads/2013/11/ButePark_1962a.jpg) via the "Add media" "Insert from URL" popup in the post editor view.
3. Visited  the post in incognito several times
4. Connected Jetpack latest stable version
4. Added the Top Posts widgets with the settings shown above.
5. Visited the home page and made the screenshot

I never get to experience an image different than this one

This is the body of the post:

image

**Comment by oskosk** [comment]
Tested with a small image >40x40 and <200x200 and it does the trick!

**Pull request merged**
