### PR TITLE
Adding Gutenberg support to Publicize

### LINKED ISSUE #9039: Publicize: Gutenberg integration missing
This issue is being created to consolidate discussion around integrating Publicize module with Gutenberg. I'll be working to address this issue.

#### Steps to reproduce the issue
Publish a post from Gutenberg with Jetpack setup and social accounts connected with Publicize.

#### What I expected
Here's the classic editor behavior that's missing with Gutenberg:
publicize-classic

#### What happened instead
Publicize correctly publishes the post to all connected social accounts with Gutenberg, **but** there is no form provided in editor to know that Publicize is active and to edit post text.

#### Potential designs
@MichaelArestad  proposes adding Publicize integration in one (or both?) of the following locations:

1. Gutenberg pre-publish view:
gutenberg publish
2. Gutenberg sidebar view (potentially with other Jetpack options down the road):
33017789-f93c2054-cdf3-11e7-89d0-17eaecc70b9c

#### Proposal
I would propose taking a swing at number 1 above (add Publicize to the pre-publish view in Gutenberg) as a first iteration. At a minimum this affects the Publicize's [ui.php](../blob/master/modules/publicize/ui.php). Gutenberg will also need hooks in place to enable this. Paging @gziolo on the best approach for this (and if there are any existing examples of this yet). 

#### Enhancements
This may be a good chance to look at enhancing Publicize while we'll be touching it. 

One concept I would like to explore is to report back the Publicize results after publishing a post. The post-publish view in Gutenberg could be a good place to list out which connections were shared to and provide links to the associated posts. This serves a couple purposes:
1. Immediate feedback to the user that Publicize is working correctly
2. Convenient for the user to open linked social posts so they can view/edit them.
Post-publish view where the reporting could be added:
gutenberg post-publish

### PR DESCRIPTION
**Pull request by c-shultz**
This Pull Request contains the changes from #9144 but on a branch local to this repo.

==== Original description follows ===

Fixes #9039 (No Publicize form in Gutenberg)
Dependencies:
- PR #9466 for Jetpack connection data access
- [Gutenberg PR #5795](https://github.com/WordPress/gutenberg/pull/5795) for Gutenberg extensibility

#### Summary
Bringing Jetpack's Publicize feature to the Gutenberg editor! ---
image

Without this PR, Publicize invisibly shares all new Gutenberg posts to all connected social accounts.

#### Front-End Design Note
The design is based heavily on @MichaelArestad's [post-publish design concept](https://automattic.invisionapp.com/share/2EGBADFXKAD#/screens/284765844_Start). The desired long-term direction for Publicize is to incorporate it in the post-publish panel (after the user publishes the post), but on this PR, as a first iteration, it is being placed in the pre-publish panel.

#### Architecture Notes
This PR touches a lot of files and there's several early commits that were taking the design in a different direction. In an effort to make review easier, I'll try to distill the list changes into the most important new content and describe how that's hooked into existing content:

  - This PR implements the Publicize form as React-based UI, with components implemented in newly created `modules\publicize\assets\gutenberg_client` directory
  - Publicize form is hooked into Gutenberg via [Slot-Fill](https://github.com/WordPress/gutenberg/tree/master/components/slot-fill#usage)
     - The Publicize `Fill` UI is created on this PR ([in `publicize-gutenberg-plugin.jsx`](https://github.com/Automattic/jetpack/pull/9144/files#diff-3264bcd048332c7a45fcfdb928d6c526)) and the pre-publish `Slot` is created in [Gutenberg PR #5795](https://github.com/WordPress/gutenberg/pull/5795)
   -  Newly created `jetpack\modules\publicize\class-jetpack-publicize-gutenberg.php` does the setup for the new UI.
       - Registers new UI JS to be loaded with Gutenberg editor
       - Registers REST field on the `post` endpoint to pass in Publicize `title` and `connections` form options when saving post:
image 
       - Registers new Ajax endpoint `wp_ajax_get_publicize_connections` to expose connection list so client can refresh connections
   - Depends on `try/publicize-decouple-ui` (PR #9466) to expose connection data access methods

## Testing instructions:

1. Checkout this branch and merge dependended on branch:
    `git checkout add/gutenberg-publicize && git merge try/publicize-decouple-ui --no-commit`
2. Checkout [Gutenberg PR #5795](https://github.com/WordPress/gutenberg/pull/5795) and build to enable pre-publish extensibility
3. Activate Gutenberg and Jetpack
4. Create new post
5. Click "Publish" to get Publicize form in pre-publish sidebar
6. Try stuff:
    - Add connections
    - Open settings
    - Edit message
    - Check/uncheck connections
    - Refresh connections
    - Publish post
    - Check social accounts for post and message
    - Try changing previously published/shared post to draft and re-sharing (Publicize should be disabled)
    - Try Publicize in classic editor to make sure nothing changed

### CODE REVIEW

**Comment by brbrr** [comment]
@c-shultz please rebase your PR and make sure it passes in CI

**Comment by c-shultz** [comment]
@brbrr, I don't have the extra time to support this PR right now, as I'm focused on efforts on my new team.

**Comment by jeherve** [comment]
@simison Should this remain opened now that the work moved to https://github.com/Automattic/wp-calypso/pull/26389 ?

**Comment by simison** [comment]
Yeah, I think this can be closed. There might be something that we'd still want to port but it'll remain here safe if we need to.

This PR as is won't be merged anyway so no point keeping it open.

cc @tyxla

**Pull request closed without merging**
