### PR TITLE
CRM: Adding back and unminifying font-awesome.css

### PR DESCRIPTION
**Pull request by coder-karen**
## Proposed changes:

* During the process of moving CRM over to the monorepo, the font-awesome.min.css file has been removed. The [new build script](https://github.com/Automattic/jetpack/pull/28578) will remove min.css files before rebuilding from CSS files, so instead of working around that one approach is to unminify the file. Another is to refer to a CDN instead of adding font-awesome files. This PR unminifies the file.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/pull/28578#issuecomment-1420559609 

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Once https://github.com/Automattic/jetpack/pull/28578 is merged, then this can be tested by creating a new Jurassic Ninja site with the [Beta plugin](https://github.com/Automattic/jetpack-beta) installed and active, and under Jetpack CRM on the Beta testing dashboard add this feature branch.
* To test a build using a [local development installation](https://github.com/Automattic/jetpack/blob/trunk/docs/development-environment.md), run `jetpack build plugins/crm`, or `jetpack build --production plugins/crm` to test the build as if it were running in production.
* Previously console errors were showing while navigating CRM dashboard pages when this file was missing - these should be gone now (and the file properly minified in a production build).

### CODE REVIEW

**Comment by cleacos** [comment]
Thank you, Karen for fixing it. 

My local installation is asking for the minified file... `/css/font-awesome.min.css`

image

The old repo has only the `/css/font-awesome.min.css` file.

**Comment by cleacos** [comment]
Okay, I missed running the script... forget the previous comment

**Comment by coder-karen** [comment]
Sorry @cleacos , I've updated the PR description testing section with the scripts to run to test this out locally too.

**Comment by cleacos** [comment]
Critical error running a Jurassic Ninja site... I cannot access the site, and I see this error:

image

I launched the site with Jetpack + Jetpack Beta + this branch

**Comment by cleacos** [comment]
After running the script, in my local dev, the same, it doesn't exist `font-awesome.min.css` (404 not found), it's not in the`css` folder. Running it in both modes, `jetpack build plugins/crm` or `jetpack build --production plugins/crm`. I rebased the branch to trunk, just in case it doesn't have the last changes.

Also, I got these other console errors:

image

**Comment by cleacos** [comment]
I think that for the JN site, I didn't include Jetpack CRM itself. But launching a new JN site, with Jetpack Beta, and then selecting this branch, the site works, 
image

But I still see the same errors in JN as in my local dev:

image

**Review by cleacos — CHANGES_REQUESTED** [review]
.

**Comment by coder-karen** [comment]
Ok that's odd, it is working for me both locally and JN. However using the Live Branches script did not work (if you use that TamperMonkey script). Having CRM pre-installed seems to be necessary.

It also looks like 'jpcrm_js_bind_daterangepicker' needs to be added to the exports in ZeroBSCRM.admin.global.js so I'll add a PR for that.

**Comment by cleacos** [comment]
> However using the Live Branches script did not work (if you use that TamperMonkey script). Having CRM pre-installed seems to be necessary.

The second time, I went directly to https://jurassic.ninja/specialops/, I selected Jetpack, Jetpack Beta, Jetpack CRM (WPORG version) with data generation. 

The first time I didn't select Jetpack CRM, so I got that error.

( I didn't use the script TamperMonkey, in both tries, I used the JN setup directly )

**Comment by coder-karen** [comment]
So it turns out the build issues here were primarily because this PR was created before the Webpack PR was merged, and the trunk merge wasn't reflecting in the beta testing plugin (it showed the last update as being 22hrs ago and the CRM version as 5.5.2-alpha, whereas it should be 5.5.4-alpha). Adding the CRM plugin before hand shouldn't be needed. I've rebased instead of merging and that helps (building using Jurassic Ninja and the branch, or the Live Branches script, works for me now).

I also still saw the font-awesome error, because it wasn't minifying this file. The reason was that the build script is looking for SASS files in the SASS folder to minify, so I've converted it from css to scss. Everything looks ok from my end, hopefully all works for you now too.

**Comment by cleacos** [comment]
Testing it again...

**Review by cleacos — APPROVED** [review]
Now it works as expected. The font-awesome issue is fixed. I tested it via a JN site using this branch, and also in my dev-env.

LGTM!

**Pull request merged**
