### PR TITLE
Add jsx highlighting to .js files

### PR DESCRIPTION
**Pull request by sirreal**
cc: @simison 

Details in https://github.com/Automattic/wp-calypso/pull/28459, although apparently has stopped working in the interim.

### CODE REVIEW

**Comment by sirreal** [comment]
I think this method of getting JSX highlighting in .js has broken.

Following along at https://github.com/github/linguist/pull/3677

**Comment by simison** [comment]
Also interesting: https://github.com/github/linguist/issues/4359#issuecomment-461033744

**Comment by simison** [comment]
The file would need to be added to svnignore

**Comment by sirreal** [comment]
This seems to have stopped working. Closing.

**Pull request closed without merging**
