### PR TITLE
Admin Page: Proposal - Add lazy images settings

### LINKED ISSUE #8193: UI for Lazy Images
Lazy Images doesn't currently have a UI, and can only be enabled via the Jetpack Modules page.

There was a prototype UI baked into the old PWA branch: #7963

### PR DESCRIPTION
**Pull request by oskosk**
Fixes #8193.

This PR adds a Lazy image card to Writing Settings

The label here is being taken from the module headings, so any text changes, should take place there.

**Screenshots**

image

image

#### Changes proposed in this Pull Request:

* Shows a toggle in the Media Settings page enabling the activation of the Lazy Images module

#### Testing instructions:

* Check this branch
* Build the admin page
* Visit Jetpack/Settings/Media
* Confirm that you a see a toggle for Lazy Images

### CODE REVIEW

**Comment by oskosk** [comment]
@ebinnion @gravityrail would you say this is desirable ?

**Comment by ebinnion** [comment]
I would prefer that we not have UI for lazy image until the next release. While I don't have any concerns about lazy images at the moment, I'm apprehensive about releasing a new module with UI just before Christmas vacation. Also, I believe have plans for a release in January.

**Comment by oskosk** [comment]
@ebinnion alright! Moving this to just be labeled as proposal.

**Comment by oskosk** [comment]
Closing as the feedback in #8193 seem to be more pretentious than the changes introduced here.

**Pull request closed without merging**
