### PR TITLE
filter og:title and og:description so they get smart punctuation

### LINKED ISSUE #2377: Open Graph title/description tags lack smart punctuation
Open Graph title/description tags lack smart punctuation.

Actual:

    <meta property="og:title" content="It&#039;s 2015 -- You&#039;d Think We&#039;d Have Figured Out How To Measure Web Traffic By Now" />

Expected:

    <meta property="og:title" content="It’s 2015 — You’d Think We’d Have Figured Out How To Measure Web Traffic By Now" />

### PR DESCRIPTION
**Pull request by paulschreiber**
Fixes #2377.

### CODE REVIEW

**Comment by zinigor** [comment]
Read the changes, tested, they seem to be working fine. One thing - even though the changes are welcome, I can't seem to reproduce the original problem when using Jetpack from `master`. Perhaps there was something else that has caused HTML entities in OG tags?

**Comment by paulschreiber** [comment]
@zinigor Are you seeing smart punctuation or just entities? WP will encode standard quotes, too.

**Comment by zinigor** [comment]
@paulschreiber I am seeing punctuation both in the `og:title` and in the page head title. When creating a post I used different characters like `“”`, `«»`, `‘`, etc.

**Comment by paulschreiber** [comment]
Can you paste an example in here?

**Comment by zinigor** [comment]
@paulschreiber here's the title I entered for the post:
`Two dashes -- long dash — foot ' inch " quotes “” apostrophe ‘`

*Running master*
Here's what I see in the `<head>`:
```<title>Two dashes &#8212; long dash — foot &#8216; inch &#8221; quotes “” apostrophe ‘ | Local Version Really</title>```
Here's what I see in the OG tags:
```<meta property="og:title" content="Two dashes -- long dash — foot &#039; inch &quot; quotes “” apostrophe ‘" />```

*Running paulschreiber:fix/filter-og-tags*
Here's what I see in the `<head>`:
```<title>Two dashes &#8212; long dash — foot &#8216; inch &#8221; quotes “” apostrophe ‘ | Local Version Really</title>```
Here's what I see in the OG tags:
```<meta property="og:title" content="Two dashes &#8212; long dash — foot &#8216; inch &#8221; quotes “” apostrophe ‘" />```

So it looks like the PR is working fine, I was getting the same results before because I was using UTF-8 symbols instead of smart punctuation.

Looks good to me!

**Comment by paulschreiber** [comment]
Great! Can we merge this in?

**Comment by kraftbj** [comment]
@paulschreiber Wanted to give you a head's up of #2723. The filters here are bringing in more than we want so will need to adjust.

**Pull request merged**
