### PR TITLE
Connection: fix redirect to user connection after Jetpack site registration action

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
Fixing a bug introduced in #24531

Upon replacing `wp_redirect()` with `wp_safe_redirect()`, it no longer accepts the `https://jetpack.wordpress.com` URL as a safe redirect.
The `register` and `reconnect` actions are no longer able to redirect users to the Calypso user connection flow, and forward them to the WP-admin Dashboard instead, leaving Jetpack connected in site-only mode.

#### Known Issues the PR Fixes
These two connection flows leave the site in site-only connected mode and don't go any further:

- Jetpack connection flow auto-initiated by the WooCommerce Setup Wizard
- Jetpack connection banner shown on the "Plugins" page after the Jetpack plugin is activated

There may be other functionality affected, but not yet discovered.

#### Jetpack product discussion
1657900505121469-slack-C01U2KGS2PQ
1191179647901802-as-1202648366228088

#### Does this pull request change what data or activity we track or use?
No.

##### Plugins page full-screen banner
1. Disconnect Jetpack, go to "Plugins" and deactivate it.
2. Activate it again, you should see the full-screen "Set Up Jetpack" banner.
3. Go through the connection flow, confirm you see the Calypso "Approve" page, and that both site and user connection are established.

##### WooCoommerce setup wizard
_For some reason the fix doesn't work when Jetpack Beta is used to checkout the branch. Please test on your local copy._
1. Install Jetpack and WooCommerce, activate both. Confirm Jetpack is not connected.
2. Go to "WooCommerce" and follow the wizard to do the basic setup.
3. After the last step ("Theme"), you should get redirected to the Calypso "Approve" page.
4. Confirm that connection flow completes successfully, and Jetpack is fully connected.

### CODE REVIEW

**Comment by coder-karen** [comment]
Thanks @sergeymitr !

This is what I observed from testing:

Testing with 11.0:
- Jetpack plugin active but not connected: In the Woo setup flow, right after selecting a theme I automatically see the Jetpack connection prompt.
- Jetpack plugin installed but not active: No connection prompt ever appears.

Testing with 10.9: Same behaviour as in 11.0

Testing with 11.1.2 - Jetpack plugin active but not connected - after the theme selection I'm redirected back to wp-admin. Jetpack has been connected with a site-only connection behind the scenes.

Testing with this PR :
- Jetpack plugin active but not connected: At no point in the onboarding flow do I see a connection prompt (and checking later I see Jetpack has not been connected behind the scenes at all). However I do get to complete the onboarding flow.

I'm guessing it's the 11.0 flow that we'd want to replicate here?

**Review by anomiex — COMMENTED** [review]
Do we need the same fix in this code too? https://github.com/Automattic/jetpack/blob/6e9bd779f2afcfdd4a75dc3af0ef621bac977291/projects/plugins/jetpack/class.jetpack.php#L4038-L4051

**Comment by AnnaMag** [comment]
I double what @coder-karen shared above re testing.

`I'm guessing it's the 11.0 flow that we'd want to replicate here?`
Yes!

**Comment by sergeymitr** [comment]
Hi @coder-karen.

> At no point in the onboarding flow do I see a connection prompt

I've tried to get down to this issue and couldn't. The fact that even site registration doesn't happen means that WooCommerce simply doesn't try to connect the site.
It looks like Jetpack Beta is the reason, although I wasn't able to figure out why.
Please retest the PR on your local machine, without Jetpack Beta, it should work fine that way.

**Comment by coder-karen** [comment]
Hi @sergeymitr ,

I have the same issues on my local development environment, testing just the PR, no Beta plugin installed. In the Woo onboarding flow, after selecting a theme, I'm not redirected to a Jetpack connection screen but instead back to the main onboarding flow landing page in order to continue setup. 

In case there is an issue with my local development environment I'll see if we can get some more testers here.

**Comment by bindlegirl** [comment]
I tested this on a JN site but before activating Jetpack I manually copied over the `class.jetpack.php` file from this PR.
Woo connection flow worked as expected. I got redirected to make a connection after selecting a theme. 

I got stuck with installing Woo on my local dev site, so I have to get back to that option when I figure out what's wrong.

**Comment by coder-karen** [comment]
> I manually copied over the class.jetpack.php file from this PR.

Good thinking! That worked for me too. Strange that the other environments seem touchy though, I wonder what causes that, or if it's anything that's worth worrying about / digging into for any reason.

> I got stuck with installing Woo on my local dev site,

I did too - ended up downloading it from WP.org, unzipping, and copying the `woocommerce` folder over to my local installation's plugin folder, which worked. But perhaps it wasn't the ideal way to do things, given the results I got.

**Review by coder-karen — APPROVED** [review]
It looks like we're in a good place to have this PR merged, so we can get this in the beta release as well.

**Pull request merged**
