### PR TITLE
Untangle: introduce use_untangled_interface() toggle

### PR DESCRIPTION
**Pull request by fushar**
## Proposed changes:

Currently, we're using the "if the current admin interface style is classic" check as a flag on whether we should show the untangled menus: both the structure (where should a menu lives) and the content (for a menu, if the classic view is set, show the wp-admin version).

However, now we want to be able to release the new structure for all users. Therefore the above conditions will need to be independent. This PR splits the check into one of the following independent checks:

- `use_wp_admin_interface()` -- whether the admin interface style is set to classic
- `use_untangled_interface()` -- whether we should show the new menus IA; the "untangled" ones matching Core's structure as similar as possible.

I categorized the merged PRs are as follows:

Should use `use_wp_admin_interface()` check:

- https://github.com/Automattic/jetpack/pull/35145
- https://github.com/Automattic/jetpack/pull/35210

Should use `use_untangled_interface()` check:

- https://github.com/Automattic/jetpack/pull/35154
- https://github.com/Automattic/jetpack/pull/35212
- https://github.com/Automattic/jetpack/pull/35217
- https://github.com/Automattic/jetpack/pull/35439

Let me know if I mis-categorized anything.

While I'm modifying the changes, I also improved the comments a little bit.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Re-test the above linked PRs.

### CODE REVIEW

**Comment by fushar** [comment]
As advised by @lsl (pfsHM7-68-p2#comment-162), we can revisit this after we merge all features for the Atomic-classic style. Marking this as draft for now.

**Comment by arthur791004** [comment]
The changes look good to me 👍

> https://github.com/Automattic/jetpack/pull/35145

This seems to match Core's structure as well. WDYT?

**Comment by fushar** [comment]
> > https://github.com/Automattic/jetpack/pull/35145

> This seems to match Core's structure as well. WDYT?

Sorry, could you elaborate what you mean here?

**Comment by arthur791004** [comment]
Sorry, I mean “Untangle: Themes to core & add Theme Showcase submenu (https://github.com/Automattic/jetpack/pull/35145) ” is to match the Appearance of the Core, so would it be better to use `use_untangled_interface` instead of `use_wp_admin_interface`? (I'm unsure of that)

**Comment by fushar** [comment]
I see. But the menu structure already matches Core (even now without any untangling). When we release the new nav, the submenus for Appearance are already correct (already contains Appearance -> Themes, etc).

Then we use the `use_wp_admin_interface()` flag to make `Appearance -> Themes` go to wp-admin version.

So I think it is already correct.

**Comment by fushar** [comment]
Not relevant anymore.

**Pull request closed without merging**
