### PR TITLE
Protect: Introduce Jetpack Protect plugin initial skeleton

### PR DESCRIPTION
**Pull request by oskosk**
This PR may overlap with #23558. I tested that one and it threw fatals. Turned off Jetpack as I assumed that was the issue, but then didn't check much of the structure. Will check how different the generated structure is after #23434 got merged

### Disconnected view
image

### Connected view

image

#### Changes proposed in this Pull Request:

* Adds plugin initial structure based on the new Jetpack generator introduced in #23434

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* Launch a [JN site with this branch and plugin](https://jurassic.ninja/create/?jetpack-beta&nojetpack&branches.jetpack-protect=add/security-plugn-named-jetpack-protect)
* *[](https://user-images.githubusercontent.com/746152/157232961-d07a5a23-4d00-4dcb-aae1-356adba2a132.png) (This link launches without the main Jetpack plugin).
* Visit the Jetpack Protect menu
* Connect the site. 
* Expect to se the My Jetpack menu item

### CODE REVIEW

**Comment by oskosk** [comment]
Even though I generated this with the new geenrator. Something did not build right on the launched JN. The plugin was there and installed, but showing the wrong build message

image

**Comment by dereksmart** [comment]
> I tested that one and it threw fatals.
I hadn't added this to the description yet, but you needed to `composer install` in plugins/protect

**Review by dereksmart — APPROVED** [review]
Tests well

**Comment by oskosk** [comment]
> Or that some of the brute protect features were conflicting with JP active because there was no protection in place for conflicts yet.
@dereksmart Oh yes, indeed. I meant this. The conflict with Jetpack. Fatals were gone when I deactivated Jetpack. 

I only started this one because we merged Leo's generator PR and I saw yours was failing (Checks) for a few reasons.

**Pull request merged**
