### PR TITLE
Update to React 18

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Update to React 18.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p9dueE-6wd-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Test everything you can think of that uses React (e.g. Jetpack's dashboard and settings, Jetpack's blocks in the editor, the My Jetpack page, pages for most of the standalone plugins) with WordPress 6.0 (no Gutenberg plugin), WordPress 6.1 (same), WordPress with the latest Gutenberg plugin, wpcom Simple, and wpcom Atomic.

### CODE REVIEW

**Comment by anomiex** [comment]
Note Boost's Critical CSS feature is currently broken in trunk, that's not an effect of this PR. p1675393194601369/1675373367.797419-slack-CBG1CP4EN

**Comment by samiff** [comment]
I did some clicking around on a JN site but wasn't able to notice any issues.

**Comment by sdixon194** [comment]
Checked everything I could - Jurassic Ninja, WoA, Simple site, all standalone plugin pages, dashboards and block editors. Didn't notice any issues. 

Looks like there are some merge conflicts. I say we go ahead and merge this so we can get as close to a full cycle of testing as possible.

**Comment by anomiex** [comment]
I was planning on waiting for Wednesday in case something blows up with the release tomorrow in code that's touched here. But if others think that won't complicate backporting fixes, I'm fine with going ahead now. There's not that much non-test code being touched (mainly just the replacing of `react-dom`'s `render` with `@wordpress/element`).

**Comment by sdixon194** [comment]
> I was planning on waiting for Wednesday

Gotcha, that makes sense to me. Let's wait until Wednesday and merge it after 11.8 just to be safe.

**Review by sdixon194 — DISMISSED** [review]

**Review by samiff — APPROVED** [review]

**Comment by renatoagds** [comment]
Nice work here folks! 👏🏽

**Pull request merged**
