### PR TITLE
WooCommerce Analytics: require package in the Jetpack plugin

### LINKED ISSUE #35631: Woo Analytics: require the package in the Jetpack plugin and remove the code from the module.
Epic: #35511

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #35631

## Proposed changes:

> [!IMPORTANT]
> Do not merge this PR until #35754, #35756, and #35857 get merged.

Let's require the WooCommerce Analytics package in the Jetpack plugin, and mark the existing codebase in the Jetpack plugin as deprecated.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* Epic: #35511

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* This will require using the WooCommerce plugin on your site, and having created some test products.
* Connect the site to your WordPress.com account.
* Go to Jetpack > Settings > Modules and confirm that the WooCommerce Analytics module is enabled.
* Go to the frontend of the site, and confirm that https://stats.wp.com/s-xxxx.js is enabled, xxxx being the year and week number.
* Load Chrome, and install https://github.com/Automattic/tracks-chrome-extension
* Try checking Tracks events generated on Woo pages. You can follow the instructions in #35139 or #34065 for some examples.

### CODE REVIEW

**Comment by jeherve** [comment]
@senadir @opr Do you think you could give this PR a try, and see that existing WooCommerce Analytics functionality still works? It does seem to work on my end, but I think you're a lot more familiar with the feature than I am. 

Thank you!

**Review by opr — DISMISSED** [review]
Hi @jeherve - seems like the package is loading ok, but the stats file loaded for me is `s-202409.js` which does not fit the year/month (but it does fit year/week, is that what it's using?).

Also, this one is for @senadir not you but it seems that when using the cart _block_, the values below are incorrectly reported on all events:

```
cart_page_contains_cart_block: 0
cart_page_contains_cart_shortcode: 1
```

Nadir can you replicate/see the cause? 

Requesting changes so we can update the PR description or look into the stats JS file, thanks!

**Comment by jeherve** [comment]
> it does fit year/week, is that what it's using?

Yes sorry, that's what I should have written.

https://github.com/Automattic/jetpack/blob/fa0dba982629678671cc218ab6ac6b8600369c16/projects/packages/woocommerce-analytics/src/class-woocommerce-analytics.php#L98

I've updated the PR description accordingly.

**Review by chrisbliss18 — APPROVED** [review]
The changes look good. I ran the tests using both `trunk` and this branch. Track events generated as expected throughout the browsing, adding to cart, and checking out flow on each branch.

I approve. Thanks for the work on this Jeremy.

**Pull request merged**
