### PR TITLE
E2E tests: Introduce steps in tests

### PR DESCRIPTION
**Pull request by brbrr**
#### Changes proposed in this Pull Request:

* Introduce `step`s to split up the tests in more meaningful pieces.
* use `reporter.startStep` & `reporter.endStep` to capture steps in Allure reports
* rename `connection.test.js` to `re-connection.test.js` for clarity

#### Testing instructions:
* Make sure tests are green
* check https://jetpack-e2e-dashboard.herokuapp.com/pr-15553 and make sure suites does have steps in test details

#### Proposed changelog entry for your changes:

* n/a

### CODE REVIEW

**Comment by brbrr** [comment]
something strange happened. I not sure that I pushed that merge, and your rebase did not picked up the last commit :shrug:

committed it once again. should good now now

**Comment by leogermani** [comment]
* Travis is green
* I'm not sure what the "steps" are supposed to be in Allure. This is what I see:

Captura de tela de 2020-04-28 16-02-58

**Comment by brbrr** [comment]
Should have stated it clearly in the PR description. 

Steps are basically the breakdown of `steps` during the specific test run. You can see them on in the right tab under "Test body"

Your screenshot revealed a messed up steps for Eventbrite block :) Going to fix that

**Comment by leogermani** [comment]
Travis is green.

Steps look fine and now I can see they are related to the test on the left column.

Only tests under "Jetpack pre-connection" don't have any steps. Is this expected?

**Comment by brbrr** [comment]
> Only tests under "Jetpack pre-connection" don't have any steps. Is this expected?

I don't know :) I decided not to split them up into steps since they are quite simple.

**Pull request merged**
