### PR TITLE
Add a new PR template for extensions

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:

* This should give users a choice of template when creating a PR - one for core patches and one for extensions

#### Jetpack product discussion

We noticed recently that some blocks don't work in p2. We'd like to add a checklist for block PRs which includes a check that the block works in p2, to help us to test better in the future.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* I'm not sure how to test this, but I am assuming it works the same way as issue templates
* The docs are here: https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

#### Proposed changelog entry for your changes:

* Added a new PR template for extensions

### CODE REVIEW

**Comment by jeherve** [comment]
Maybe this would be better implemented within our existing regression checklists?
https://github.com/Automattic/jetpack/tree/master/docs/testing/regression-checklist

**Comment by scruffian** [comment]
Maybe, but my experience is that its easy to ignore those kind of checklists because they aren't right in front of you. The Gutenberg repo has checklists like this in the PR template and I find it a useful reminder to check the various things it prompts for...

**Comment by jeherve** [comment]
> its easy to ignore those kind of checklists because they aren't right in front of you.

The checklists get added as a new comment on each PR, so I think it should be as visible as the PR template, maybe even more since you get the comment even if you delete that section when creating your PR.

Here is an example of the regression checklist on a PR:
https://github.com/Automattic/jetpack/pull/16606#pullrequestreview-456362156

**Comment by scruffian** [comment]
Oh I didn't realise that. Looks great. I'll update the patch!

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/jetpack/pull/16642

**Pull request closed without merging**
