### PR TITLE
Videopress/branch 1.0.1 test

### PR DESCRIPTION
**Pull request by retrofox**
Fixes #

#### Changes proposed in this Pull Request:

*

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by oskosk** [comment]
This branch name apparently triggered one to be created in the mirror repo for the Standalone plugin. 

https://github.com/Automattic/jetpack-videopress-plugin/tree/videopress/branch-1.0.1-test

cc @sdixon194 @zinigor

**Comment by sdixon194** [comment]
> This branch name apparently triggered one to be created in the mirror repo for the Standalone plugin.

Yeah, the `<plugin-name>/branch-*` format is what the action looks for. Was there something you needed from this PR, or can that branch on the mirror repo just be deleted?

**Comment by oskosk** [comment]
It can be deleted @sdixon194

**Comment by oskosk** [comment]
Closing this one as no longer neded

**Comment by oskosk** [comment]
Also deleted the branch in the mirror repo

**Comment by sdixon194** [comment]
> Also deleted the branch in the mirror repo

Thanks Osk!

**Pull request closed without merging**
