### PR TITLE
Loading Holiday Snow in Footer Instead of Head

### LINKED ISSUE #5930: Holiday Snow Loads In Head - Slows Down Page Load
I love the time of year when WordPress sites start snowing. ❄️ 

But it seems a bit silly to load that feature in the head. It works just as well in the footer. And it'll load your page tincy bit faster.

I checked my site in [Google Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/) and it increases the page speed of my site by 1 point if I load the script in the footer. Going from 57->58.

And Google does flag that specific script as an issue.

pagespeed_insights

### PR DESCRIPTION
**Pull request by BFTrick**
Fixes #5930

### CODE REVIEW

**Comment by eliorivero** [comment]
Thanks @BFTrick!

**Comment by dereksmart** [comment]
merged to branch-4.5 82d2af4

happy holidays @BFTrick !

**Comment by BFTrick** [comment]
@dereksmart Thanks!

Any eta on 4.5?

**Comment by dereksmart** [comment]
@BFTrick looking to be around mid-January (holidays and such), so I'd go ahead and apply this to your sites manually since the snow is going to stop before then :)

**Pull request merged**
