### PR TITLE
URL-encode tag markup in SVG data: URLs

### LINKED ISSUE #18714: Podcast Player Block: Issues with AMP + other iframes in the Customizer
Disclaimer: This seems like an issue related to the Podcast block, but this might not be the correct spot (I'm not sure, for example, that the MediaElement.js isn't the cause). Please let me know if I should file this somewhere else!

#### Steps to reproduce the issue

1. Set up a test site using a default theme. 
2. Install Jetpack and the [official AMP plugin](https://en-ca.wordpress.org/plugins/amp/); set AMP to Standard mode under WP Admin > AMP. 
3. Add the podcast block, and another block that inserts an iframe to a page or post (a Custom HTML block with a regular iframe will work, or an embed like YouTube).
4. When viewing that post, open the Customizer by clicking the button in the admin toolbar, so the Customizer previews this page. 

#### What I expected
A regular preview of the page. 

#### What happened instead
The preview starts with an exploded version of the Podcast Player CSS. When I inspect it, it looks like a partial SVG element is inserted right after the body tag, replacing the opening `<style>` tag. 

**Screenshots**
With the Twenty Twenty One theme:

image

Scrolling down will eventually reach the normal page preview...

image

... but the podcast player is not styled correctly, because its styles are messed up:

image

What I see when I inspect the Customizer preview's iframe -- after the closing `<body>` tag, there is an opening `<g>` tag (like it's midway through an `<svg>` tag). The [audio player styles in Jetpack include SVGs](https://github.com/Automattic/jetpack/blob/763703ec4974dc1017c2d1a5648d1fa0e3e1ffd0/projects/plugins/jetpack/extensions/shared/components/audio-player/style.scss#L136), so it could just be something else is cutting off the styles, and this just happens to be where it is:

image

### PR DESCRIPTION
**Pull request by westonruter**
This re-adds URL-encoding of `<` and `>` characters in the SVG data: URLs used in the podcast player CSS. Originally they were URL-encoded and other data: URL SVGs are still URL encoded, but two instances got unencoded in  #18501 via 763703e.

Fixes #18714

#### Changes proposed in this Pull Request:

* Re-encode SVG data: URLs to fix rendering of stylesheets inline on the page in a `style` element to prevent `</style>` from prematurely closing a stylesheet.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* See repro steps on #18714.

#### Proposed changelog entry for your changes:

* Fix AMP compatibility with Podcast Player block in the Customizer preview.

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
Thanks for catching this! 🙌 I was able to reproduce the issue and applying this change fixed it. 

I'm not seeing the podcast player controls at all in preview and published posts, with AMP activated and standard template mode enabled. I was able to reproduce that on the master branch though, so I don't think it's related to this change.
Screen Shot 2021-03-02 at 3 46 21 PM

**Comment by westonruter** [comment]
> I'm not seeing the podcast player controls at all in preview and published posts, with AMP activated and standard template mode enabled. I was able to reproduce that on the master branch though, so I don't think it's related to this change.

Right, it's expected that the player controls aren't yet showing up on the AMP version. Adding full AMP compatibility is filed as #15771 and there's a stale PR to implement: #15306.

**Review by anomiex — APPROVED** [review]
Looks sane, confirmed the only change is percent-encoding `<` and `>` in the URLs.

**Comment by jeherve** [comment]
r222132-wpcom

**Pull request merged**
