### PR TITLE
ConnectScreen: make button full width on small screens

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes 1164141197617539-as-1201305007019293

#### Changes proposed in this Pull Request:
This PR makes the call-to-action button in the connection screen take the full available with, on small viewports. The `ConnectScreen` component lives in the `connection` JS package, and is used at the moment by both the Jetpack and the Backup plugins.

#### Does this pull request change what data or activity we track or use?
No.

##### Prerequisites

- Download this PR.
- Build the `connection` JS package.
- Build the `jetpack` and `backup` plugins.
- Launch your local testing site and makes sure it doesn't have any Jetpack plugin installed.
- Make sure you're not connected to any WordPress account.

##### Jetpack Plugin
- Activate the Jetpack plugin.
- Visit the `Jetpack` section.
- You should see the connection screen. Verify that the CTA takes the full width on small devices (width <= 782px).

_Before_
Screen Shot 2021-11-09 at 10 36 07 AM
_After_
Screen Shot 2021-11-09 at 11 35 51 AM

- Check that the width of the CTA hasn't changed for wider viewports.

Screen Shot 2021-11-09 at 11 36 04 AM

##### Backup Plugin
- Deactivate the Jetpack plugin.
- Activate the Backup plugin.
- Visit the `Jetpack` section.
- You should see the connection screen. Check the CTA.

_After_
Screen Shot 2021-11-09 at 11 40 55 AM

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @monsieur-z.
I bumped the package versions, hope you don't mind.

**Review by jeherve — CHANGES_REQUESTED** [review]
I think my changes from #21711 invalidate your changes a bit.

**Comment by monsieur-z** [comment]
I see your changes were later removed in #21803 @jeherve, so I guess it revalidates the PR :)

**Comment by leogermani** [comment]
We are still discussing how to better handle these CSS changes, whether it should be treated by the Button itself or by the ConnectionScreen, but we won't block this change for now, we can refactor it later if we find a better approach.

I'll just mark it as needing review from Design and then we can approve it.

**Comment by monsieur-z** [comment]
> I'll just mark it as needing review from Design and then we can approve it.

Just looping @Luchadores, since this is part of the mobile sweep in WP admin.

**Review by keoshi — APPROVED** [review]
Agreed with @leogermani that we should discuss how to approach this from a broader perspective in the future, but the changes in this PR look good and are an improvement! Thanks, @monsieur-z 🚀

**Review by jeherve — APPROVED** [review]

**Comment by monsieur-z** [comment]
Committed to WordPress.com: https://code.a8c.com/rWP235855

**Comment by jeherve** [comment]
r235855-wpcom

**Pull request merged**
