### PR TITLE
Admin Bar: Make it consistent between Calypso and WP Admin regardless of the value of Admin Interface Style

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/dotcom-forge/issues/8314
Fixes https://github.com/Automattic/dotcom-forge/issues/8311

## Proposed changes:

* We want to make the admin bar consistent everywhere, so this PR adds the flag `WPCOM_ADMIN_BAR_UNIFICATION` to determine whether to display the consistent admin bar. If the flag is true, we should not initialize the custom Masterbar and avoid the CSS concat for the color schemes due to the loading CSS priority.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your site, either atomic or simple
* Apply D155493-code to your simple site
* Check the admin bar on both WP Admin and Calypso
* Change the value of the Admin Interface Style
* The admin bar should be always the same

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
If `WPCOM_ADMIN_BAR_UNIFICATION` is always true, why do we need the flag? 🤔

**Comment by arthur791004** [comment]
> If WPCOM_ADMIN_BAR_UNIFICATION is always true, why do we need the flag? 🤔

We need the flag for the simple sites to disable the custom admin bar as the feature is composed of jetpack-mu-wpcom & wpcom.

Also, the value is always true on the sites with the mu-wpcom plugin but the master bar is a standalone package. We cannot ensure it's always loaded with mu-wpcom plugin. Maybe it's always true but I'd prefer to clean up the codebase in the follow-up PRs.

**Comment by mmtr** [comment]
Not sure if I'm missing anything, but I'm getting this weird bar on my Simple site:

Screenshot 2024-07-17 at 10 33 07

These are the steps I followed in my sandbox:

```
arc patch D155493
bin/jetpack-downloader test jetpack feat/unify-masterbar
bin/jetpack-downloader test jetpack-mu-wpcom-plugin feat/unify-masterbar
```

The `bin/jetpack-downloader` commands asked me if I wanted to checkout `trunk` which I declined.

**Comment by arthur791004** [comment]
> Not sure if I'm missing anything, but I'm getting this weird bar on my Simple site:

I found this issue on the frontend page and just addressed it. The flag, `WPCOM_ADMIN_BAR_UNIFICATION`, didn't work well because it's defined after the plugins are loaded... But I'm unsure why it worked well on wp-admin when I was testing 😓

Could you check it again by applying the latest D155493?

**Comment by arthur791004** [comment]
Ooops... there is still an issue related to the Write button

**Comment by mmtr** [comment]
Looks much better now! I think there is an issue with mobile viewports, since the avatar is now missing:

Before | After
--- | ---
Screenshot 2024-07-17 at 11 22 14 | Screenshot 2024-07-17 at 11 22 02

**Comment by mmtr** [comment]
All these menus link to `/wp-admin` pages, despite my site using the default interface. I don't think this is expected, becase the same menus in Calypso link to Calypso pages.

Screenshot 2024-07-17 at 11 24 40

Similarly, I think the "Edit profile" and "Logout" menus when hovering the avatar should link to Calypso pages.

**Comment by mmtr** [comment]
When visiting the frontend of a P2 site, the masterbar now has a "My Sites" menu which I don't know if it's expected:

Screenshot 2024-07-17 at 11 37 30

**Comment by arthur791004** [comment]
hmmm... Let me think about how to replace links 🤔

**Review by fushar — COMMENTED** [review]
@arthur791004 This is looking really nice, thanks! I tested and I found the same issues as @mmtr above. Other than that, I think this is good to go.

> When visiting the frontend of a P2 site, the masterbar now has a "My Sites" menu which I don't know if it's expected

No, I don't think this is expected. We should hide it.

> All these menus link to /wp-admin pages, despite my site using the default interface. I don't think this is expected, because the same menus in Calypso link to Calypso pages.

Hmmmm.... good point. 🥲

**Comment by arthur791004** [comment]
> When visiting the frontend of a P2 site, the masterbar now has a "My Sites" menu which I don't know if it's expected:

The menu is added by the `wp_admin_bar_my_sites_menu` and it's for super admin. So, I think it's fine.

**Comment by arthur791004** [comment]
There are 2 ways to replace the URL, and I'll continue on it tomorrow
* Get the node by id -> replace the URL -> remove the node and add it back
* Create another WPCOM_Admin_Bar class extends the `WP_Admin_Bar` and override the `add_node` function to replace the URL

**Review by lupus2k — COMMENTED** [review]
It works great on Atomic:

### Mobile
| Before | After |
| --- | --- |
| image | image |

### Desktop
#### Before
image

#### After
https://github.com/user-attachments/assets/324cb325-4cbe-4b89-be20-38be27b8916d

**Comment by lupus2k** [comment]
On Simple + Classic interface it keeps showing the old bar on `wp-admin` pages:

| Default + wp-admin | Classic + wp-admin |
| --- | --- |
| image | image |

On the other hand, the Mobile view on Calypso doesn't show like in wp-admin:
image

**Review by lupus2k — APPROVED** [review]
Atomic verified [here](https://github.com/Automattic/jetpack/pull/38362#pullrequestreview-2183126672)

### Simple
#### Classic + Calypso
image
image

#### Default + Calypso
image
image

**Pull request merged**
