### PR TITLE
Monitor: Don't query last down time 

### LINKED ISSUE #5208: Admin Page: Monitor data requires the user to be linked with WordPress.com
#### Steps to reproduce the issue

1. Activate Jetpack, connect it to WordPress.com.
2. Activate Monitor.
3. Go to Jetpack > Dashboard: the Monitor card is displayed properly:

screen shot 2016-09-27 at 11 42 30

4. Go to Users > Add New, and create a new admin.
5. Log out.
6. Log back in with the new admin.
7. Go to Jetpack > Dashboard.
8. The Monitor card won't load:

screen shot 2016-09-27 at 11 43 07

The `wp-json/jetpack/v4/module/monitor/data` call returns a 500 error:

screen shot 2016-09-27 at 11 43 59

The response is `Jetpack: [missing_token] `

### PR DESCRIPTION
**Pull request by dereksmart**
We haven't been showing the "Last Downtime" data for Monitor since 0be8681b9fcfc602429b79b51177a8057da9c8c4

This removes the WP-API call (and subsequent xmlrpc request to dotcom).  It will have two positive effects: 

1. Faster admin page load 
2. Not as many random instances with the xmlrpc request failing with a 500 error.  I've see this come up a bit with our support.  

To test: 
- Make sure that we're not making any calls to `/wp-json/jetpack/v4/module/monitor` when viewing the Dashboard
- Make sure activating/deactivating Monitor still works

Will also fix #5208

### CODE REVIEW

**Comment by jeherve** [comment]
Fixes #5208

**Comment by dereksmart** [comment]
Changelog suggestion: `Performance enhancements to the At a Glance Dashboard.`

**Comment by eliorivero** [comment]
This LGTM, and my only concern is if we should remove the `QueryLastDownTime` component, the `fetchLastDownTime` action, the `getLastDownTime` reducer and the `getLastDownTime` method that calls the REST API to avoid including it in the build so it doesn't increase the size. They are no longer used in the code.

**Comment by dereksmart** [comment]
I optimistically left them in there in case we start returning more accurate data from the Monitor Data endpoint one day... 

FWIW since `QueryLastDownTime` isn't used anywhere in the client code, it's not built out to `build/admin.js`.  The action/reducers however do, and it looks like it adds around ~35ish unused LOC in the non-minified build file, so kind of negligible but I can remove it anyway if you insist ;)

**Comment by dereksmart** [comment]
@eliorivero Last commit removes all traces of last downtime from the client.  Do you think we should leave the REST endpoint intact?

**Comment by eliorivero** [comment]
We can leave the REST API code in case we ever use it again in the future. It's not actually an special endpoint: @zinigor updated the module endpoints in such way that all of them can be called with a `/data` suffix which is eventually handled with a `case 'monitor':` in this case so I think it's not worth it to remove it.
Works fine so I'm merging 💯

**Comment by samhotchkiss** [comment]
#5461

**Pull request merged**
