### PR TITLE
Debugger: Add package

### PR DESCRIPTION
**Pull request by kraftbj**
## Changes proposed in this Pull Request:

* Moved the Debugger Library to a Debugger Package.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* Ensure the `wp jetpack status` command outputs as expected.
* Ensure the Site Health section (tests and data) report as expected.
* Ensure the jetpack.com debugger for SAs report local connection status as expected.

#### Proposed changelog entry for your changes:
* Debugger: Move functionality into an independent package.

### CODE REVIEW

**Comment by dereksmart** [comment]
However this ends up shaping out, I think it makes sense if only the Test "Engine" is what is packaged, and the "Tests" themselves are extendable and done so in their respective consuming codebases.  

For example if someone is only trying to consume the Connection package, and wants to include connection tests only.

**Comment by kraftbj** [comment]
@dereksmart That makes sense and wouldn't take much to do. Do you think the same should be applied to the debug data too?

**Comment by dereksmart** [comment]
Yeah I think so! Unless it was a trick question 😅

**Comment by mdbitz** [comment]
@roccotripaldi in our chats I remember you mentioning some feedback on this approach. Do you mind reviewing, commenting as time allows?

Thanks

**Comment by kraftbj** [comment]
Will come back to this in a new PR.

**Pull request closed without merging**
