### PR TITLE
VideoPress: extend the media endpoint with the jetpack_videopress_guid field

### PR DESCRIPTION
**Pull request by retrofox**
This PR moves the `jetpack_videopress_guid` REST custom field to VideoPress package from the Jetpack plugin.
Having this functionality in the VideoPress package will guarantee the `jetpack_videopress_guid` field will be present in media endpoint responses when either Jetpack or VideoPress plugin is active.

#### Changes proposed in this Pull Request:

* VideoPress: Introduce `WPCOM_REST_API_V2_Attachment_VideoPress_Field` for registering the `jetpack_videopress_guid` field
*Jetpack: Remove the corresponding file from the Jetpack plugin

#### Jetpack product discussion

pe4Cmx-fL-p2#comment-128

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Test with a site with some VideoPress videos and the Jetpack plugin active and connected
* Hit the `wp/v2/media` endpoint 
* Confirm you see the `jetpack_videopress_guid` in the request-response body only for VideoPress posts.
* Deactivate the Jetpack plugin and activate the VideoPress plugin
* Git the media endpoint again and confirm the above

Screen Shot 2022-09-05 at 17 55 50

### CODE REVIEW

**Review by fgiannar — DISMISSED** [review]
Thanks for working on this @retrofox !

Before fully reviewing this, I'd like to understand the current approach a bit better :)

With the current implementation it seems the corresponding `WPCOM_REST_API_V2_Attachment_VideoPress_Field` which lives in the Jetpack plugin and does exactly the same thing is left intact.
This means that we have duplicate code that we'll need to maintain. Do you think it would make sense to move the `WPCOM_REST_API_V2_Attachment_VideoPress_Field` class to the videopress package?
This way we'll only have a single place where this functionality exists.
The downside of this approach, also taking into account that this file is synced to WPCOM, is that we'll probably need to drop the parent `WPCOM_REST_API_V2_Field_Controller`, which I think we can afford for now in favour of being more explicit in the classes that extend it.

In general the approach could be similar to Leo's [here](https://github.com/Automattic/jetpack/pull/25042). What do you think?

**Comment by retrofox** [comment]
@fgiannar nice work! qq:

Screen Shot 2022-09-07 at 20 10 32


`jetpack_videopress_guid` and `jetpack_videopress` are present even when the attachment is not videopress type. Is it ok?

**Comment by chrisbliss18** [comment]
I was able to successfully run the testing steps. The `jetpack_videopress_guid` entry was present after disabling Jetpack and enabling VideoPress.

**Comment by fgiannar** [comment]
@chrisbliss18 Thanks for testing this, Chris!

> jetpack_videopress_guid and jetpack_videopress are present even when the attachment is not videopress type. Is it ok?

@retrofox  I believe so yes, as this is the case without the PR applied as well. Furthermore, this PR only touches the `jetpack_videopress_guid` field, therefore it's consistent with `jetpack_videopress` custom field being present as well.

Of note, the `jetpack_videopress` custom field migration to the VideoPress package will be addressed in a separate PR.

**Review by fgiannar — APPROVED** [review]
Approving on behalf of @retrofox who can't :)

**Comment by fgiannar** [comment]
SVN changeset ID: r252190-wpcom

**Pull request merged**
