### PR TITLE
Fix build for plugins/boost when using TypeScript inside js-packages

### LINKED ISSUE #23961: Build for plugins/boost fails if we create TypeScript components in js-packages/components
### Description

We added TypeScript support in #23522 but Boost plugin fails to handle TypeScript components imported from `js-packages`

### Impacted plugin

Boost

### Steps to Reproduce

1. Create a TypeScript component (with types defined) inside `projects/js-packages/components/components`
2. Export the component via `projects/js-packages/components/index.jsx`
OR
    - Simply rename `index.jsx` in `projects/js-packages/components/components/number-format` to `index.ts`
    - Add param and return type to function i.e. `const numberFormat = ( number: number ): string => {`
3. Run `jetpack build plugins/boost -v`
4. You should see the build fail with an error like `Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`

### A clear and concise description of what you expected to happen.

Build should be successful.

### What actually happened

Build fails because 

#### Reason
The reason for the build failure is that `@rollup/plugin-typescript` by default only handles files inside the project directory, thus files from outside are excluded. Since the TypeScript component comes from `js-packages/components`, the rollup plugin doesn't handle it, resulting in build failure.

#### Possible solution
- Create a separate `tsconfig.json` file for rollup and name it something like `rollup-tsconfig.json`.
- Make it extend the existing `tsconfig.json`.
- Add `js-packages` path to `includes` inside `rollup-tsconfig.json`.
- Pass `rollup-tsconfig.json` path to `@rollup/plugin-typescript` in `rollup.config.js`.

The solution [doesn't break the package boundary](https://github.com/Automattic/jetpack/pull/23889#discussion_r850436961) in existing `tsconfig.json`.

```jsonc
// rollup-tsconfig.json

{
	"extends": "./tsconfig.json",
	"include": [
		"app/assets/src/js/**/*",
		"../../js-packages/components/**/*"
	],
}
```

```js
// rollup.config.js

import tsconfig from './rollup-tsconfig.json';

export default {
	...,
	plugins: [
		...,
		typescript( {
			sourceMap: ! production,
			inlineSources: ! production,
			include: tsconfig.include,
			tsconfig: 'rollup-tsconfig.json', // Pass the custom tsconfig
		} ),
		...,
	],
	...,
};
```

### Operating System

macOS

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the failing build for `plugins/boost` when using TypeScript inside `js-packages`. Please see the related issue for details

Fixes #23961 

#### Changes proposed in this Pull Request:

* Adds a custom tsconfig.json file for rollup named `rollup-tsconfig.json`.
* Passes the new `rollup-tsconfig.json` path to `@rollup/plugin-typescript` in `rollup.config.js`.
* Converts `numberFormat` in `js-packages/components` to TypeScript as a proof for the fix

#### Jetpack product discussion
https://github.com/Automattic/jetpack/pull/23889#discussion_r850436961

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Checkout the PR branch
* Run `jetpack build plugins/boost `
* Confirm that build is successful

#### Additional/Optional steps

* Convert any other component inside `js-packages/components` to TypeScript
* Run `jetpack build plugins/boost `
* Confirm that build is successful

### CODE REVIEW

**Review by haqadn — APPROVED** [review]
👍🏼

**Review by haqadn — APPROVED** [review]
👍🏼 👍🏼

**Review by karthikax — APPROVED** [review]

**Comment by coder-karen** [comment]
Tested this out and the main testing steps work well. I'm not familiar with converting components to TypeScript though so will leave this for someone else in Crew to jump in and take a look as well.

**Comment by manzoorwanijk** [comment]
> Tested this out and the main testing steps work well. I'm not familiar with converting components to TypeScript though so will leave this for someone else in Crew to jump in and take a look as well.

Thank you @coder-karen. Those Additional steps are totally optional.

**Review by dereksmart — APPROVED** [review]
Boost and Jetpack built fine. The stuff using numberFormat in Jetpack still looks good.

**Comment by manzoorwanijk** [comment]
r243791-wpcom

**Pull request merged**
