### PR TITLE
Widget Visibility: Rewrite the way that the major/minor rules lists are generated.

### PR DESCRIPTION
**Pull request by cfinke**
Widget Visibility: Rewrite the way that the major/minor rules lists are generated to save bandwidth and memory.

In situations where a site has hundreds of widgets each with multiple visibility rules, the widget admin pagesize can grow out of control, causing out-of-memory errors and issues with loading the customizer.

This commit rewrites the way that the admin UI is generated, moving from hardcoding everything server-side to providing a single set of all the possible visibility options that are then dynamically generated client-side when they're needed.

This also has the happy side-effect of eliminating the need for the AJAX calls when changing the major rule type. It also fixes some inconsistencies with how the "Include children" checkbox was processed -- in some circumstances, the "Include children" option was being applied to the wrong set of conditions.

### CODE REVIEW

**Comment by dereksmart** [comment]
Failing some jshint stuff, can you take a look? https://travis-ci.org/Automattic/jetpack/jobs/111335805

**Comment by jeherve** [comment]
Sorry we didn't get around to it until now. It looks like it will need a rebase now.

**Comment by jeherve** [comment]
#5781

**Comment by zinigor** [comment]
Rebase in progress...

**Comment by zinigor** [comment]
Closing in favour of #6333. Hopefully it won't get closed in favour of 9222.

**Pull request closed without merging**
