### PR TITLE
Add pre-publish panel to promote Yoast

### PR DESCRIPTION
**Pull request by robertsreberski**
## Proposed changes:

* Add pre-publish panel to yoast-promo package
* Initialize and activate yoast-promo package in jetpack plugin
* Address feedback from https://github.com/Automattic/jetpack/pull/29603

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Checkout this branch `add/yoast-promo-prepublish-panel`
* Run your docker env
* Go to "Posts > Add new"
* Click on "Publish" and you should see the below ad (focused on Yoast free version) in the pre-publish panel:
CleanShot 2023-03-22 at 16 56 56@2x

* Ensure CTA link is `https://yoa.st/yoast-jetpack-boost?domain=<your_site>`

* Go to "/wp-admin/plugins.php" and install (and activate) Yoast plugin
* Go to "Posts > Add new"
* Click on "Publish" and you should see the below ad (focused on Yoast premium version) in the pre-publish panel:
CleanShot 2023-03-22 at 17 00 59@2x

* Ensure CTA link is `https://yoa.st/yoast-upgrade-jetpack-boost?domain=<your_site>`
* Click on "x" button - the ad should be dismissed and should not appear again after page reload (the setting is stored in local storage)
* Remove `jetpack-yoast-promo-dismissed` local storage item, the ad should appear again
* A12s - reach out to me to install Yoast Premium plugin
* Go to "Posts > Add new"
* The ad should not be displayed anymore

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
I think we're in a good place for getting this merged. 👍 I've made a few changes, feel free to take a look at them. If you're happy with them, you can merge this PR! 🚢

**Comment by robertsreberski** [comment]
@jeherve thank you for your help on this PR! the changes look good to me, and I will apply your feedback in the other PR (https://github.com/Automattic/jetpack/pull/29643) as well

**Comment by jeherve** [comment]
There is one thing we could iterate on, I think: it's a bit annoying to have the 2 failing `wp/v2/plugins` requests as soon as you load the editor. I wonder if it would be worth addressing it in a follow-up PR.

**Comment by robertsreberski** [comment]
I'll take a look at it!

**Pull request merged**
