### PR TITLE
Contact Form Block: Fix issues with FSE

### LINKED ISSUE #19462: Site Editor Compatibility: Contact Form Block styling issues
In the new site editor in Gutenberg (`/wp-admin/admin.php?page=gutenberg-edit-site`), there are some styling issues with the Contact Form block when rendered on the front end of the site.

#### Steps to reproduce the issue

Related to: 256-gh-Automattic/view-design

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Contact Form block into the Footer template part.
3. Save the template part, and load the front end of the site
4. Observe that the Contact Form block does not provide much in the way of default styles for the form field elements, but expects them to be provided by the theme.

#### What I expected

I expected the form to be rendered similarly to how it appears in the TwentyTwenty One theme, with comfortable padding in the text fields

#### What happened instead

* Since tt1-blocks theme does not provide styling for the input field elements, they are left unstyled by the block.
* The Button block does not appear to be styled either, however if you add a Buttons block elsewhere in the template part, then the styles for the Button block are loaded. Perhaps we can trigger the Button block styles to be enqueued if the Contact Form block is added?

#### Possible solution(s)

With themes moving in the direction of not providing CSS styles directly for blocks, should we update the Contact Form block to provide better default styling?

**Screenshots**

| FSE running tt1-blocks theme | Post editor in Twenty Twenty One theme |
| --- | --- |
| image | image |
| image | image |

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/jetpack/issues/19462

#### Changes proposed in this Pull Request:

* Fix CSS issues with using the contact form box in the site editor. This PR adds some new base styles for the form the front end. Primarily the padding that was missing.
* Fixes an issue where a textarea would not be 100% in the editor
* Fixes an issue with custom widths of contact form fields

Note: this will not match TwentyTwentyOne theme form styles. These are not present in the blocks version. Future block themes will include some more base form styles. This PR will simply add some base styles so the form is more presentable in the front end.

Before (missing padding etc)

113967711-e7f2a800-9874-11eb-8273-0f17e493adaf

After (Includes padding matching editor and correct button styles)

Screen Shot 2021-04-14 at 12 52 16 PM

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Enable TT1 blocks theme.
* Insert a contact form block in the site editor.
* Confirm that the contact form fields display as expected in the editor.
* Confirm that the contact form fields display as expected in the front end.
* Switch to a regular WP theme and insert a contact form block in a post.
* Confirm that in this post the contact form fields work expected in editor and front end.

### CODE REVIEW

**Comment by ramonjd** [comment]
This is looking good. 

✅ Fields and labels are consistent in the editor and frontend across editors
✅ Contact forms look and behave as expected on non-FSE sites

The only think I'm seeing is that in the frontend, the contact form button created in the site editor has a different border radius and color to the single post version. Is that right?

### Contact form in the site editor
a2-fe-fse-site


### Contact form in a single post
a2-fe-fse-post

**Comment by apeatling** [comment]
@ramonjd This is an issue with the editor vs front end styles in the TT1 theme. If you set the border radius using the sidebar in option in the editor then it will display correctly on the front end.

**Comment by ramonjd** [comment]
> This is an issue with the editor vs front end styles in the TT1 theme. If you set the border radius using the sidebar in option in the editor then it will display correctly on the front end.

Ah, thanks for the clarification. This LGTM then 👍

**Review by ramonjd — DISMISSED** [review]
👍

**Comment by apeatling** [comment]
@jeherve I've added a changelog file to this PR, any idea why it keeps saying there isn't one?

**Comment by jeherve** [comment]
> I've added a changelog file to this PR, any idea why it keeps saying there isn't one?

The changelog file you had created wasn't in the `projects/plugins/jetpack` directory. I took care of that in c6ae089f4c1875ca8a0c071ec16b7d5f9777d13c

**Review by jeherve — APPROVED** [review]

**Comment by scruffian** [comment]
This problem with this approach is that it overrides styles set but the theme. I would prefer that the block inherits these kind of settings from the theme, unless there is a reason we want this form to look different to the other forms on the site.

**Pull request merged**
