### PR TITLE
Add upgrade prompt for Jetpack Search

### LINKED ISSUE #8468: Search: Admin: Prompt users to get professional for search functionality
Currently, we do not show UI to turn on search in the react admin if the site does not have a professional plan.

Instead of hiding search, perhaps we should tell users about the benefits of search and suggest they upgrade?

We hide the search setting here:

https://github.com/Automattic/jetpack/blob/master/_inc/client/traffic/search.jsx

Where we return null if the site does not have a professional plan.

Reported in #8372

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes #8468 

Adds a prompt for non-Professional sites to upgrade to get Jetpack Search.

jetpack search prompt

### CODE REVIEW

**Comment by gibrown** [comment]
I think we should link to https://jetpack.com/features/design/search/ as a landing page to show search features here.

**Comment by MichaelArestad** [comment]
@gravityrail I suggest changing the copy to something like 

"Upgrade to Business to get faster, more relevant search results on your site"

Maybe @nicoleckohler has a better suggestion.

Visually, it looks good.

@gibrown Are you suggesting we add a help link or direct them to a landing page before the upgrade page?

**Comment by nicoleckohler** [comment]
@gravityrail @MichaelArestad Can we make the upgrade prompts [match these](https://github.com/Automattic/wp-calypso/pull/20099) (as in, make this two lines)?

If so:

> **Enable Jetpack Search by upgrading to to Jetpack Professional**
> Get faster, more relevant sitewide search results.

I also considered ending that with "powered by Elasticsearch" but up to y'all

**Comment by MichaelArestad** [comment]
@nicoleckohler I'm hesitant to call it Jetpack Search as a thing. Maybe "Jetpack's enhanced search" or something like that?

**Comment by gibrown** [comment]
@MichaelArestad isn't "Jetpack Search" the same as calling things "Jetpack Stats" and "Jetpack Related Posts"?

> Are you suggesting we add a help link or direct them to a landing page before the upgrade page?

It feels like the user should have some way to learn more about the feature. The current link seem to take the user to the generic plans page which I see as:

screen shot 2018-01-08 at 4 10 18 pm

Search isn't on it yet (which makes sense), but none of the features on it have an easy way to get to the landing pages for those features and really dig into the details for them. Personally if Search is what triggered me to upgrade, then I'd want to know more about what that means.

We could add an extra link in the text, or it feels like that link should not just say upgrade, but "learn more" ? "Explore Jetpack Pro"?

**Comment by MichaelArestad** [comment]
> @MichaelArestad isn't "Jetpack Search" the same as calling things "Jetpack Stats" and "Jetpack Related Posts"?

Yes it is. We don't refer to either like that in settings or in the promotional materials. We just refer to them as "stats" (sentence case) and "related posts" or "related content."  For the most part, our features are no longer treated as individual products and more as a piece of Jetpack.

> It feels like the user should have some way to learn more about the feature.

> Search isn't on it yet (which makes sense), but none of the features on it have an easy way to get to the landing pages for those features and really dig into the details for them. Personally if Search is what triggered me to upgrade, then I'd want to know more about what that means.

> We could add an extra link in the text, or it feels like that link should not just say upgrade, but "learn more" ? "Explore Jetpack Pro"?

Makes sense. I defer to Growth on this one as they have tried a few things like this. CC @richardmuscat @jeffgolenski

**Comment by richardmuscat** [comment]
@MichaelArestad / @gibrown -- yup. let's just call it search or enhanced search.

**Comment by gravityrail** [comment]
I might be inclined to call it "sitewide search" or "site search" or "content search". Just something that implies it is used by end-users to search your pages and posts, not "search engine optimisation" or a wp-admin search product.

**Comment by gibrown** [comment]
Ya, seems like just removing the "with Jetpack Search" clause would take care of this case.

**Comment by gravityrail** [comment]
@gibrown @richardmuscat done - just removed that part of the phrase, so it now says "Faster, more relevant and more powerful sitewide search."

**Pull request merged**
