### PR TITLE
Social: Update/cut component tooltip

### PR DESCRIPTION
**Pull request by gmjuhasz**
Duplicate of #29224
Fixes # 1203876111187910-as-1203884651474282

## Proposed changes:

* Updated the CSS rules in the ContextualUpgradeTrigger component and changed the text copy.
 
### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

1203876111187910-as-1203884651474282

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Boot up a new JN site on this branch with Social and Protect plugins. Boot up a trunk site on this branch with Social and Protect plugins
* Make sure you have the free plans on both and compare the behaviour of the upgrade box by hovering over them. You will also see the information icon in this branch. Hover over it to see the upgrade copy.  

Before

Screenshot 2023-03-01 at 19 02 00

After

Screenshot 2023-03-01 at 18 15 01

* Testing the component in another plugin: Install Jetpack Protect on your JN site and make sure the upgrade copy looks the same. 

Before and After:

Screenshot 2023-03-01 at 18 59 40
is is to ensure that our changes to the `ContextualUpgradeTrigger` component didn't break anything.

### CODE REVIEW

**Review by spsiddarthan — APPROVED** [review]
LGTM, we can land this!

**Comment by nateweller** [comment]
@gmjuhasz I noticed this PR breaks the layout of `ContextualUpgradeTrigger` instances that don't use the tooltip, or perhaps just instances with less text in the description:

Screenshot 2023-03-25 at 8 00 58 PM

Would it be possible to apply these changes without making `.description` display `inline`?

**Comment by nateweller** [comment]
It also appears that the current implementation doesn't render correctly in Firefox:

Screenshot 2023-03-30 at 11 25 06 AM

**Comment by gmjuhasz** [comment]
Hey @nateweller,

First of all sorry about missing this, also I was AFK already yesterday so I just saw this. I saw that you already created a fix for it, thank you! 🙏 I did check with Protect before and seemed fine with me, but yeah that `inline` should have been definitely conditional

**Pull request merged**
