### PR TITLE
js-packages: Fix textdomains

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

We have a bunch of packages that, for historical reasons, use "jetpack" rather than a unique text domain. Fix them now.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Check the Composer-package and plugin artifacts. There should be no relevant changes, thanks to use of `@automattic/babel-plugin-replace-textdomain` when bundling.
  * The only change I noticed was that the move of a few translator comments from outside a `sprintf` to inside is reflected in the bundles.

### CODE REVIEW

**Review by zinigor — DISMISSED** [review]
I don't see anything wrong with this at first glance, but should we wait until we branch 14.1 just to make sure we don't introduce a lot of fuzzy strings right before the release?

**Comment by anomiex** [comment]
It shouldn't introduce fuzzy strings since the textdomains in the JS all get rewritten in the plugins anyway.

**Review by zinigor — APPROVED** [review]
Good to know that we won't introduce fuzzies with this! I'm pretty sure though that Thomas will branch off 14.1 before you'll be able to merge it :)

**Comment by anomiex** [comment]
I probably could have gotten in just under the wire, but I'll wait anyway since it's happening now. 🙂

**Pull request merged**
