### PR TITLE
Nova Menu CPT: Improved control over output markup

### PR DESCRIPTION
**Pull request by webmandesign**
Allowing filtering element's opening and closing markup and item's class.

### CODE REVIEW

**Comment by kraftbj** [comment]
Marking for 4.3 so we can decide to merge or not to keep this PR from growing (more) mold.

**Comment by rcoll** [comment]
I've rebased and tested this on 4.3 with the Confit theme and it looks good to go - the filters work as expected. If there is still interest in this, it should be safe to merge 👍

**Comment by rcoll** [comment]
One comment - the filter names are a bit generic. Perhaps we could prefix them with "nova_" or something like that.

**Comment by webmandesign** [comment]
> One comment - the filter names are a bit generic. Perhaps we could prefix them with "nova_" or something like that.

Agree. If we can decide on using ` jetpack_` or `nova_` or `jetpack_nova_` ;) I can adapt the PR. Let me know what you think. I personally would go with `jetpack_nova_` but not sure what is your naming convention here, guys.

**Comment by jeherve** [comment]
> if we can decide on using jetpack_ or nova_ or jetpack_nova_ ;) I can adapt the PR. Let me know what you think.

`jetpack_nova_` will work 👍

**Comment by webmandesign** [comment]
OK guys, `jetpack_nova_` prefix was added to the filters.

**Pull request merged**
