### PR TITLE
Retry changelog filename with suffixes if exists

### PR DESCRIPTION
**Pull request by gravityrail**
If you run `tools/check-intra-monorepo-deps.sh -u`, and it has a filename collision when it auto-generates the changelog entry, then the script bails. This can leave the repo in a bad state, e.g. by failing to commit some auto-generated changelogs even if you retry.

This change attempts up to five numeric suffixes of the changelog filename before bailing.

#### Changes proposed in this Pull Request:
* Retry dependency-update changelog filenames with suffixes so that script is more robust

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Fork this branch
* Generate a changelog entry using `jetpack changelogger add ${packagename}` for a package with an outdated internal dependency. Use the default filename (which is the branch name)
* Run `tools/check-intra-monorepo-deps.sh -u`
* It should not have a filename conflict, but rather should automatically commit the changelog entry to `${branchname}-1`

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]

**Review by kraftbj — APPROVED** [review]

**Review by kraftbj — APPROVED** [review]

**Review by jeherve — COMMENTED** [review]
Tests appear to be failing for this branch:

```
There was 1 error:
  Script ./vendor/phpunit/phpunit/phpunit --colors=always handling the phpunit event returned with error code 2
  
  Script @composer phpunit handling the test-php event returned with error code 2
  1) Test_Constants::test_jetpack_constants_get_constant_null_when_not_set
  Mockery\Exception\InvalidCountException: Method apply_filters('jetpack_constant_default_value', NULL, 'UNDEFINED') from Mockery_0 should be called
   exactly 1 times but called 0 times.
  
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery/CountValidator/Exact.php:38
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery/Expectation.php:310
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:119
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery/Container.php:301
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery/Container.php:286
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/mockery/mockery/library/Mockery.php:210
  /home/runner/work/jetpack/jetpack/projects/packages/constants/vendor/brain/monkey/inc/api.php:38
  /home/runner/work/jetpack/jetpack/projects/packages/constants/tests/php/test-constants.php:35
  
  --
  
  There was 1 failure:
  
  1) Test_Constants::test_jetpack_constants_get_constant_use_filter_value
  Failed asserting that null matches expected 'test value'.
  
  /home/runner/work/jetpack/jetpack/projects/packages/constants/tests/php/test-constants.php:153
```

Not sure why this is coming up now.

**Comment by gravityrail** [comment]
@jeherve I fixed that test. Seems like something changed in BrainMonkey or PHPUnit and the old style of testing stoped working, but Filters\expectApplied does work, so I switched to that.

**Comment by anomiex** [comment]
Are you overthinking this? Changelogger already has a `--filename-auto-suffix` option for use in non-interactive mode, which should be the case when it's being run from `tools/check-intra-monorepo-deps.sh -u`. Instead of rearranging a bunch of code in changelogger to add auto-suffixing in interactive mode too (which I'm not convinced is a good idea, it may be too easy for someone to manually add multiple change entries instead of realizing they already have one), why not just add that option to the invocation in `tools/check-intra-monorepo-deps.sh -u`?

**Comment by gravityrail** [comment]
@anomiex :
> Changelogger already has a --filename-auto-suffix option for use in non-interactive mode

Yes, this patch actually consolidates filename suffixing for both, using the same implementation inside the validator.

If this turns out to be overkill or causes extra files to be created we can easily change the defaults. In my experience this change definitely helps and hasn't caused me issues yet - certainly, I've had more issues with filename conflicts causing the scripts to bail than I have with extra unnecessary files being created.

**Review by anomiex — CHANGES_REQUESTED** [review]
I intentionally didn't add automatic suffixing in interactive mode in #19789 because I think the user should have to positively choose to create a second change file for their PR. It shouldn't just happen by default.

I haven't heard anyone actually complain about that behavior yet. You're not even complaining about it in the description of this PR, the problem you describe does not involve interactive mode.

So absent any request or any real reason to change the behavior of interactive mode, let's not.

**Comment by gravityrail** [comment]
I was about to close this actually, after reviewing your suggestion... I am
making a separate patch which just allows passing the auto suffix param in
via the top level script for people who want it. Thanks for the feedback! I
was hitting this when I made cross cutting changes to packages, which I
expect will begin to happen more frequently.

**Comment by gravityrail** [comment]
Closing in favor of #20752

**Pull request closed without merging**
