### PR TITLE
Settings: add descriptions to settings sections

### LINKED ISSUE #10688: Settings: Add headers to each section to explain each section's theme
The entire settings sections don’t have headers that explain why users should care about something like ‘Writing enhancements’. Let's add headers that help explain the theme of the settings below.

ref: p6TEKc-2m8-p2 (RB / item 5.13)

### PR DESCRIPTION
**Pull request by keoshi**
Fixes #10688

#### Changes proposed in this Pull Request:

* Adds descriptions to all settings sections headers explaining the theme of the options below.
* Cleans up dependencies paths on `settings/index.jsx`.

image

#### Testing instructions:

* Fire up this PR.
* Go to Jetpack settings.
* Read the descriptions on each section.

#### Proposed changelog entry for your changes:

* Settings: add descriptions to settings sections

### CODE REVIEW

**Comment by keoshi** [comment]
Note for @joanrho and @jeffgolenski: we went over the copy on p2JRYi-3Qv-p2, and since the final suggestions were so short I eliminated the redundant title (e.g. `Writing Tools` under the already selected `Writing` tab) and the paragraph, and used a big font size for the entire description instead.

**Review by jeherve — DISMISSED** [review]
Looking good, and works well in my tests. 👍

**Comment by keoshi** [comment]
@jeffgolenski Added to to this test site, would appreciate it if you could take a look at the descriptions in the settings here: https://used-longhorn-58.jurassic.ninja/wp-admin/admin.php?page=jetpack#/settings

Thank you in advance!!

**Review by jeffgolenski — DISMISSED** [review]
@keoshi Works well for me. Can we make the test flush with the left side of the cards below it? example: https://cloudup.com/cLLjdQXwe6n

**Comment by keoshi** [comment]
Yeah, I actually gave it a bit of padding to follow the tab navigation's, but I can make that adjustment.

untitled 2

**Review by jeherve — APPROVED** [review]
Looking good. Merging!

**Pull request merged**
