### PR TITLE
JITM: wrap CTA below text on small viewports

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes 1164141197617539-as-1201305007019335

#### Changes proposed in this Pull Request:
This PR fixes the layout of JITM banners on screens narrower than 480px, by wrapping the CTA under the text.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* Start with a site that's connected to WordPress.com.
* Go to a wp-admin page with a JITM message, like the main wp-admin page or Jetpack > Dashboard.
* Check how the message looks like on desktop and on mobile devices.

_Before_
image

_After_
image

### CODE REVIEW

**Comment by sdixon194** [comment]
This is blocked, awaiting the JITM package being able to build its own CSS per p1637253835484300/1636490736.172600-slack-CBG1CP4EN

**Review by jeherve — APPROVED** [review]
This looks good to me. 👍

**Review by keoshi — COMMENTED** [review]
Looks good to me as well, though it sparks two questions:

- Should the buttons be full-width?
- In case there are two of them should we have them side-by-side, so that the entire JITM takes less room vertically?

I don't have the answers but would like to know your thoughts on this.

**Comment by monsieur-z** [comment]
> Should the buttons be full-width?
> In case there are two of them should we have them side-by-side, so that the entire JITM takes less room vertically?

I'm happy to take care of those in a separate PR. In this one, I'm just sticking to 1164141197617539-as-1201305007019335. Would it make sense to integrate such banners in Emerald/Jetpack RNA? I don't know what's the process for that, if there's already a backlog, etc. But it seems that the banner could be more consistent with the rest of the platform indeed.

**Comment by keoshi** [comment]
That makes total sense and it wasn't my intention to delay this PR, Kevin. Approving right now!

**Review by keoshi — APPROVED** [review]
LGTM, let's ship it! 🚀

**Comment by keoshi** [comment]
Hah, absolutely not @monsieur-z ! We're on the same wave length, no worries, but appreciate you reaching out again.

🤗

**Pull request merged**
