### PR TITLE
Subscriptions Widget: ensure titles are displayed nicely in 2020

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

On WordPress.com (and only on wpcom), Subscription widget titles are wrapped in label tags.
This is problematic with the Twenty Twenty theme, since that theme has custom label styles that overwrite the default widget title style. Let's fix that.

**Before**

image

**After**

image

This was originally reported by @kathrynwp here:
https://core.trac.wordpress.org/ticket/49137

#### Testing instructions:

* Nothing should change if you use the widget with the Twenty Twenty theme on a Jetpack site; the look of the widget title should match the other titles before and after this patch was applied.
* On WordPress.com (see D42586-code), you should see the changes in the screenshot above.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by leogermani** [comment]
I can confirm the title style was corrected after applying the patch:

Captura de tela de 2020-04-28 17-39-21

But since we're here, I must say this text input looks quite odd to me. It's too short in height.

The same with the block:

Captura de tela de 2020-04-28 17-40-40

What do you think?  Is this the expected design?

**Comment by leogermani** [comment]
Just checked with another theme and I can see a proper sized text input. Maybe we should fix it too?

Captura de tela de 2020-04-28 17-45-50

**Comment by jeherve** [comment]
@leogermani Yeah, that's a good point! Done in 70dc2b9c75e95eaf79758ea257d56fef25259a2a

**Comment by jeherve** [comment]
r206748-wpcom

**Pull request merged**
