### PR TITLE
Boost: Add E2E tests integration into the Github actions workflow.

### PR DESCRIPTION
**Pull request by davidlonjon**
As discussed in https://github.com/Automattic/jetpack/pull/20764 which is now merged, this PR introduces the integration of the Boost e2e tests into the Github actions workflow.

This is still the first round of my integration attempt. Hopefully not too far off.

#### Changes proposed in this Pull Request:

This PR does:

- Add a new e2e workflow especially to run Boost e2e tests. Eventually, this might get integrated into the Jetpack e2e tests Github actions workflow.
- Add a new `slack` command into the Boost e2e package.json file to allow doing Slack notifications in the Github workflow.
- Rename the Jetpack e2e and atomic Github actions workflow name to differentiate more clearly with the Boost one
- Fix some tests naming conventions (This change does not really belong in this PR but used to test the triggering of the workflow)
- remove irrelevant comment in a JS file (This change does not really belong in this PR but used to test the triggering of the workflow)

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
N/A

#### Testing instructions:
* Make sure that the Jetpack Boost e2e tests Github workflow complete successfully.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Review by adimoldovan — DISMISSED** [review]
Looks good to me!

**Comment by adimoldovan** [comment]
@jeherve I believe your approval is required for the "Changes requested" state to get updated.

**Comment by davidlonjon** [comment]
Hi @jeherve, would you mind taking a look at this one again when you'll have the time. It is probably good to go as @adimoldovan gave the green tick but it needs to be unlocked by your green tick too.

**Comment by davidlonjon** [comment]
@adimoldovan, I had to push one more update with d2d0a29 as some tests were failing due to a [timeout](https://github.com/Automattic/jetpack/actions/runs/1437805238) on `waitForResponse` calls which seems a little odd as locally I never experienced these timeouts and the response of the remote call should not take too long. In this commit, I am just increasing the timeout. It seems to do the trick for now. Eventually, we are going to [revisit these tests anyway.](https://jetpackboostp2.wordpress.com/).

**Review by adimoldovan — APPROVED** [review]

**Comment by davidlonjon** [comment]
Thank you @adimoldovan :)

**Pull request merged**
