### PR TITLE
Settings UI: place Protect settings into foldable card

### LINKED ISSUE #6504: Move brute force protection into a foldable card
This is similar to https://github.com/Automattic/jetpack/issues/6503

#### Current
image

#### Proposal
Card title: Prevent brute force login attacks
Primary setting: `Block suspicious-looking login activity from unknown IP addresses`

Only the child settings should be in the expanded view.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6504

#### Changes proposed in this Pull Request:

* the options for Protect have been placed into a foldable card

#### Connected

captura de pantalla 2017-03-07 a las 19 03 45

captura de pantalla 2017-03-07 a las 19 03 28

##### Inactive

captura de pantalla 2017-03-07 a las 19 06 46

#### Dev Mode

captura de pantalla 2017-03-07 a las 18 25 49

captura de pantalla 2017-03-07 a las 18 45 16

#### Testing instructions:

❗️ Do `yarn distclean` && `yarn build` before testing❗️

* go to Security tab and make sure Protect looks and works fine.

### CODE REVIEW

**Comment by dereksmart** [comment]
> Toggling the module toggles the foldable card. Event propagation must be stopped.

Why not just set `clickableHeader={false}`?

> Clicking the chevron leads to a blank page

This was fixed in https://github.com/Automattic/dops-components/pull/97 -- just need to update yarn.lock

**Comment by dereksmart** [comment]
I would like to see this in, as I could use the same styles for the foldable card settings I am working on in #6550

**Comment by eliorivero** [comment]
Ah right, yeah, we should prevent clicks in header. Thanks for pointing about the fixed chevron, will rebase feature branch in this one.

**Comment by MichaelArestad** [comment]
Because the toggle + label are in the subheader, they are not displayed on smaller screens. What are our options here?

**Comment by dereksmart** [comment]
> What are our options here?

put them in the header.

**Comment by eliorivero** [comment]
Updated:

- uses header instead of subheader, so it solves the issue of the text disappearing in mobile screen sizes
- rebased feature so chevron behavior is fixed

**Comment by MichaelArestad** [comment]
:shipit:

**Pull request merged**
