### PR TITLE
Instant Search: improve product layout

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request:

* Improve the product layout for Instant Search. This layout is not currently available to end users.

There's still design work to do here, but this PR adds some absolute basics for the product layout:
* reduce title font size
* handle missing titles
* add a link to the product image

Screen Shot 2020-12-11 at 15 23 07

#### Does this pull request change what data or activity we track or use?

No. 

#### Testing instructions:

On a test site with Instant Search enabled, add a query string `?result_format=product` and perform a search.

#### Proposed changelog entry for your changes:

Not required at this stage.

### CODE REVIEW

**Comment by jsnmoon** [comment]
Will we encounter any compatibility problems by using CSS grid? [IE11](https://caniuse.com/css-grid) doesn't support the latest grid specifications, for example; do we need to support IE11?

**Review by jsnmoon — DISMISSED** [review]
Changes work as expected! Left a separate comment noting browser compatibility issues.

In the future, I think it'd be nice if the product image served as a link as well.

**Comment by bluefuton** [comment]
> In the future, I think it'd be nice if the product image served as a link as well.

Done! ✅

**Comment by bluefuton** [comment]
> Will we encounter any compatibility problems by using CSS grid? IE11 doesn't support the latest grid specifications, for example; do we need to support IE11?

Unfortunately, I think so, because it's still supported by Core: https://make.wordpress.org/core/handbook/best-practices/browser-support/

Looks like IE11 implements the old CSS grid spec and we can get around some things with vendor prefixes/slightly different repeat syntax, but it's missing some of the shiny stuff I've used here like `grid-auto-flow`. Perhaps back to the flexbox solution, then...

**Review by jsnmoon — APPROVED** [review]
Good start 👍

**Review by leogermani — APPROVED** [review]
Tests well for me!

**Comment by kraftbj** [comment]
r218917-wpcom

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
