### PR TITLE
Block Editor: Respect the send_auth_cookies filter

### LINKED ISSUE #19516: Block Editor: Respect the `send_auth_cookies` filter
#### Steps to reproduce the issue

1. Add a filter on `send_auth_cookies` to `__return_false`
2. Attempt to login

#### What I expected
Login should fail, as no cookies will be sent to the client.

#### What happened instead
Jetpack sets the authentication cookies instead, with the cross-site attributes set.

https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L431-L450

Two thoughts come to mind:
 - The filters that set the cookies should check the `send_auth_cookies` filter
 - The existing `__return_false` filter on `send_auth_cookies` should be removed, and instead it should only be set to false if Jetpack has indeed sent the cookies.

I'm unsure if just running the filter / storing the result at the point in time of `enable_cross_site_auth_cookies()` being run would be proper, I'm leaning towards no.

#### Temporary hotfix
```
add_filter( 'jetpack_disable_cross_site_auth_cookies', function( $disable ) {
	return ! apply_filters( 'send_auth_cookies', true );
} );
```

#### Possible solution

* Remove the existing `send_auth_cookies` filter
* Do not set the cookies on the `set_*_cookies` filters, instead temporarily store them internally
* Late on the `send_auth_cookies` filter, if the filter value is truthful, then send the cookies & return false on the filter.

### PR DESCRIPTION
**Pull request by pablinos**
Fixes #19516 by implementing the suggestion of storing the auth cookies
and only sending them if the `send_auth_cookies` filter is true.

This also removes the need for the copy of `wp_clear_auth_cookie`

#### Changes proposed in this Pull Request:

This implements a slightly different approach for setting the cross site auth cookies. As the actions are called the arguments to `jetpack_shim_setcookie` are pushed into an array. When the `send_auth_cookies` filter runs we only call `jetpack_shim_setcookie` with the stored arguments if there are some available and the filtered value is `true`

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:
As described is #19516 
* Add a filter to `send_auth_cookies` of `__return_false`
* Log into the site without this change and it will succeed, which it shouldn't
* With this PR you shouldn't be able to login.

### CODE REVIEW

**Comment by pablinos** [comment]
I'm struggling to get the 'Tests / PHP tests: PHP 7.4 WP master (pull_request)' check to pass (any help there would be appreciated!), but hopefully, that shouldn't stop this from being reviewed.

**Review by jeherve — APPROVED** [review]
This tests well for me. @pablinos Any chance that someone from Explorers who's familiar with the WordPress.com block editor could take a look as well?

**Review by allilevine — APPROVED** [review]
I'm not familiar with this code but I tested with the filter and I was able to log in without this change, but not able to log in with this change. ✅

**Comment by pablinos** [comment]
We have done a lot of work on the logic related to loading the block editor, but I don't think we've touched this authorisation code. We've all checked that it's working, but is there anyone else we should get to look at it? Someone working on the third party cookies perhaps?

**Comment by jeherve** [comment]
@mmtr Would you have the chance to take a look, since you worked on #14349?

Thank you!

**Comment by mmtr** [comment]
I followed the testing instructions from https://github.com/Automattic/jetpack/pull/14349 and noted there is an issue during login when the site is not connected to WP.com yet.

These are the exact steps I followed:
- Created a JN site running this branch: https://jurassic.ninja/create/?jetpack-beta&branch=fix/19516-respect-send-auth-cookies-filter
- Cleared the cookies and reload.
- I'm redirected to the login page.


From that point, I'm unable to login. I also noted there is a PHP warning:

Screen Shot 2021-04-30 at 11 16 00

**Comment by pablinos** [comment]
Thanks for looking at it @mmtr. It's odd as that function was accidentally marked private, so I don't know why it was working. Even more curious is that I used your JN link, cleared my cookies, which logged me out, and then I was able to log in again.

I've pushed a change to make that method public. Would you mind giving it another test when you get a chance please?

**Review by mmtr — APPROVED** [review]
Thanks @pablinos, this tests well now for me! I didn't find any regression when the block editor is accessed from Calypso. Also verified that any existing `send_auth_cookies` filter is taken now into consideration.

**Pull request merged**
