### PR TITLE
Masterbar: Introduce new package

### LINKED ISSUE #36916: Introduce a Masterbar package

### PR DESCRIPTION
**Pull request by fgiannar**
Introduce Masterbar package.
Under the context of deprecating the Masterbar feature in the Jetpack plugin and moving it to the `mu-wpcom-plugin`

## Proposed changes:

* Creates a new `masterbar` package

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pfwV0U-3U-p2

## Testing instructions:

Code Review: The package was generated via `jetpack generate` and is not in use currently.

### CODE REVIEW

**Review by darssen — COMMENTED** [review]
Changes look good. Are you planning on adding the mirror-repo as suggested in https://github.com/Automattic/jetpack/blob/trunk/projects/packages/README.md#deploying-packages ?

**Comment by fgiannar** [comment]
> Changes look good. Are you planning on adding the mirror-repo as suggested in https://github.com/Automattic/jetpack/blob/trunk/projects/packages/README.md#deploying-packages ?

Thanks Juanma! I created it https://github.com/Automattic/jetpack-masterbar however I haven't made the branch related updates mentioned in the instructions you linked, since no branch is created in the repo yet cc @Automattic/jetpack-garage

**Comment by fgiannar** [comment]
I've manually added a README in the mirror repo and added a new branch protection rule as well. Adding @Automattic/jetpack-garage as reviewers to ensure everything is fine with the mirror repo setup.

**Comment by zinigor** [comment]
Everything looks OK to me, I would just suggest one thing. Recently @anomiex has introduced a new rule to allow project to not have baselines at all:

https://github.com/Automattic/jetpack/pull/36857

If you foresee the code to have some Phan ignores, then I'd leave the file in, but if not, it's not necessary to have it in here.

**Comment by fgiannar** [comment]
Thanks @zinigor !

> If you foresee the code to have some Phan ignores, then I'd leave the file in, but if not, it's not necessary to have it in here.

Done with https://github.com/Automattic/jetpack/pull/37277/commits/e34185390a99bc8f42455a7847eaa82dbf299bfa

**Review by zinigor — APPROVED** [review]
Let's go!

**Pull request merged**
