### PR TITLE
Button styles: ensure connection button can accomodate longer text

### LINKED ISSUE #21710: Connection: layout issue with user connection button on localized versions
#### Steps to reproduce:

1. Create a brand new site.
2. Go to Settings > General and switch the language to French
3. Go to Tableau de Bord > Mises à jour and update translations
4. Go to the Jetpack menu, and start the connection process, but do not connect your user.
5. Load the Jetpack menu again, and click on the button to start the user connection process.
Screenshot 2021-11-11 at 13 17 11

The main connect button's string is a bit long, but the button doesn't expand to match the text.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #21710

#### Changes proposed in this Pull Request:

* The button didn't previously accomodate long text, which can be an issue in some languages.

**Before**

Screenshot 2021-11-11 at 13 17 11

**After**

image

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

1. Create a brand new site.
2. Go to Settings > General and switch the language to French
3. Go to Tableau de Bord > Mises à jour and update translations
4. Go to the Jetpack menu, and start the connection process, but do not connect your user.
5. Load the Jetpack menu again, and click on the button to start the user connection process.
6. Ensure the connection button looks good.

### CODE REVIEW

**Comment by sdixon194** [comment]
This works, but seems to change the loading spinner width:

Screen Shot on 2021-11-11 at 15:07:12

This is what it looks like without this branch:

Screen Shot on 2021-11-11 at 15:08:14

Not sure if this was an intended part of the update?

**Comment by jeherve** [comment]
> seems to change the loading spinner width

Ah yes, that's something I had missed. I just pushed f0eb976c544c2925c9a680464d1d2b4c022a1e56 to change that.

**Review by sdixon194 — APPROVED** [review]
This looks good to me now!

**Comment by jeherve** [comment]
r235131-wpcom

**Pull request merged**
