### PR TITLE
Blocks: use custom SVGs instead of trying to rely on core's icons

### LINKED ISSUE #32704: Embed Blocks: some block names have a strange unicode square character in front.
### Quick summary

Some embed services such as Instagram have a square character in front of the name, like so: `" Instagram"`

image

### Steps to reproduce

1. start a post.
2. open the block inserter sidebar.
3. open F12.
4. using accessibility inspector, look for the Instagram block.

### What you expected to happen

Instagram block name is "Instagram".

### What actually happened

Instagram block name is " Instagram"

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #32704

## Proposed changes:

Using proper SVGs should avoid those accessibility issues.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

1. Go to Posts > Add New
2. Search for Instagram and Facebook blocks, ensure the icons look good:

Screenshot 2023-08-28 at 12 11 24
Screenshot 2023-08-28 at 12 11 20

Alternatively, you can try this:

1. start a post.
2. open the block inserter sidebar.
3. open F12. (I'm not sure how to do this on my Mac, so I wasn't able to follow those instructions).
4. using accessibility inspector, look for the Instagram block. **You should not see a unicode character before the block name.

### CODE REVIEW

**Comment by jeherve** [comment]
@worldomonation Do you think you could give this a try? I wasn't sure how to do the "F12" key on my keyboard to get to the screen you were looking at in #32704.

Thank you!

**Comment by worldomonation** [comment]
@jeherve Sorry for being late with testing results!

Checked accessibility options for Instagram and Facebook blocks. The accessible names look good:
image

**Comment by worldomonation** [comment]
FYI the F12/Developer Tools can be accessed via Right click > Inspect on an element as well.

image

**Review by worldomonation — APPROVED** [review]

**Comment by jeherve** [comment]
> the F12/Developer Tools can be accessed via Right click > Inspect on an element as well.

Ah, thank you! I didn't know those could be accessed with F12. TIL!

**Pull request merged**
