### PR TITLE
Social Menu / Social Icons Widget: add Mastodon

### LINKED ISSUE #10338: Social Menu & Social Media Icons: Add Mastodon Support
Please add support for [Mastodon](https://joinmastodon.org/), a distributed, decentralized, federated micro-blogging platform popular among people abandoning Twitter and Free software/Free culture enthusiasts ([many nodes exist](https://the-federation.info/mastodon))

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10338

#### Changes proposed in this Pull Request:

This is a first implementation, that we can revisit once #28172 is merged.

For now, it detects some of the most popular instances of Mastodon (pulled from https://instances.social/ plus a few others that I know are popular in the WordPress community) and uses the Mastodon icon there.

It's not perfect since we cannot possibly detect all instances of Mastodon, but that's a start.

Screenshot 2023-01-04 at 19 08 11

Screenshot 2023-01-04 at 19 08 07

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

List of sample links to use:

```
https://mastodon.online/@kraft
https://facebook.com/jetpackme
https://religious.social/@kraft/
https://mastodon.jetpack.com/@jetpack
https://www.amazon.fr/Lucky-Duck-Games-Jetpack-Fran%C3%A7aise/dp/B07SVDFMCD/
https://www.google.it/maps
https://telegram.me/jeherve
https://profiles.wordpress.org/jeherve/
```

* Start by switching to an old theme, like Twenty Ten.
* Go to Plugins > Add New and install the Classic Widgets plugin.
* In a functionality plugin, add the following:
```php
// Add social menu support
add_action( 'after_setup_theme', function () {
	add_theme_support( 'jetpack-social-menu', 'svg' );
} );
// Add an extra instance to the list.
add_filter(
	'jetpack_mastodon_instance_list',
	function ( $mastodon_instance_list ) {
		$mastodon_instance_list[] = 'religious.social';
		return $mastodon_instance_list;
	}
);
```
* Go to Appearance > Customize > Menus
* Create a new menu with custom links from the example list above.
* Assign that menu to the Social Menu location
* Go to Appearance > Widgets menu
* Drag the Social Icons widget to one of the active widget areas, and add some links again.
* Check how things look like on the frontend.

### CODE REVIEW

**Comment by kraftbj** [comment]
@jeherve What would you think about a filter at the end of that function so others could `add_filter( 'to-be-named', function( $array ) { $array['server.com'] = 'mastodon'; return $array; } );`?

**Comment by jeherve** [comment]
> @jeherve What would you think about a filter at the end of that function so others could `add_filter( 'to-be-named', function( $array ) { $array['server.com'] = 'mastodon'; return $array; } );`?

Sure thing. I just pushed 20aa5efea21476c94e30c160f1f5a0376271ba13, I don't know if that's what you had in mind. I made it a global function so one can only use one function to modify that list over Jetpack.

With that change, one should be able to do this:

```php
// Add a new Mastodon instance to the list.
add_filter(
	'jetpack_mastodon_instance_list',
	function ( $mastodon_instance_list ) {
		$mastodon_instance_list[] = 'religious.social';
		return $mastodon_instance_list;
	}
);
```

**Comment by kraftbj** [comment]
That's perfect. After I left the comment, I second-guessed if it should be a general filter for the social networks or mastodon-specific. I like the way you put it together. Going to test and review now.

**Comment by jeherve** [comment]
> I second-guessed if it should be a general filter for the social networks or mastodon-specific.

I thought about that as well. I think general filters for each one of the features could be useful, but in this specific case (adding Mastodon to both lists), I think a Mastodon-specific filter may make more sense, since site owners hoping to change that will most likely look for a filter with the word `mastodon` on it.

Actually, thinking of that, I think I need to categorize the filter so it shows in the right categories on the Codex site. Done in 1f11d710bff64bcc8f6c153bee054b189a1c0b0a

**Comment by sergeymitr** [comment]
Hi @jeherve.
#28172 is merged now, do you think we should replace the function `jetpack_mastodon_get_instance_list()` with regular expressions?

**Comment by jeherve** [comment]
> do you think we should replace the function `jetpack_mastodon_get_instance_list()` with regular expressions?

I do not think we can as is, since only the social menu supports regex for now. I should update the Social icons widget to support regex first. I'll do that now.

**Comment by jeherve** [comment]
Ok, it should be ready for another review now.

Since this makes changes to the way the Social Icons widget works, I've updated the testing instructions accordingly.

**Review by kraftbj — APPROVED** [review]
It took me a little work to test, but works as advertised.

**Pull request merged**
