### PR TITLE
[AI] Add/sanitize openai input

### PR DESCRIPTION
**Pull request by millerf**
Fixes @fgiannar [comment](https://github.com/Automattic/jetpack/pull/28309#issuecomment-1387300514)

## Does this pull request change what data or activity we track or use?

No

## Proposed changes:

* Sanitize endpoints inputs

## Testing instructions

- Deploy to your WPCOM sandbox.
- Make sure the AI blocks are still working

Screenshot 2023-01-26 at 11 16 36

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I believe we should be able to also rely on a `sanitize_callback` key in our argument definition  to sanitize the request's parameter. It may be worth giving it a try.

**Comment by millerf** [comment]
> sanitize_callback

Thanks for such a  quick feedback. Let me check...

**Comment by artpi** [comment]
I changed the description because @millerf  continually edits it in a way that does not match the bot expectations.

**Review by artpi — APPROVED** [review]
Code looks good, works

**Review by samiff — APPROVED** [review]

**Pull request merged**
