### PR TITLE
 Remove scssc 0.0.12, replace with ScssPhp 1.1.11 via composer

### PR DESCRIPTION
**Pull request by mreishus**
## Proposed changes:

*  Remove scssc 0.0.12, replace with ScssPhp 1.1.11
  * :heavy_check_mark:  Is this the right composer file to edit?
  * :heavy_check_mark:  Will this work on WPCOM? The autoloading works fine on my local jetpack docker, but I know traditionally WPCOM hasn't had a good autoloading setup.
    * It's working for me now, after 6442da739080ae6a5d674f25a293d77e339c701e

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* You might have to turn this on in jetpack settings

* Use an older theme like twentytwentyone
* Go to customizer -> additional css
* Add this css
```
// Variables
$primary-bg-color: #f4f4f4;
$secondary-bg-color: #4CAF50;
$text-color: #333;

// Mixin for text styling
@mixin text-styling($size, $color: $text-color) {
  font-size: $size;
  color: $color;
}

// Global styles to check if SCSS is working
body {
  background-color: $primary-bg-color;
  @include text-styling(16px);
}

h1 {
  @include text-styling(36px, #ff0000);
}

// Nested Rules
.container {
  width: 100%;
  padding: 15px;
  background-color: $secondary-bg-color;
  @include text-styling(18px, white);

  .box {
    width: 50%;
    margin: 10px auto;
    padding: 10px;
    background-color: white;
    border: 1px solid $secondary-bg-color;

    h2 {
      @include text-styling(24px, $secondary-bg-color);
    }
  }
}
```
* Change preprocessor to SCSS
* Save
* The site should now have a gray background with large text

### CODE REVIEW

**Comment by anomiex** [comment]
> Is this the right composer file to edit?

Yes

> Will this work on WPCOM?

I think this won't work anywhere yet, since the package files aren't flagged for being included in the plugin zip. You'll need to add an entry like these:
https://github.com/Automattic/jetpack/blob/fc6209a4a69711218be9ee9932503743558868a8/projects/plugins/jetpack/.gitattributes#L18-L19

Once that's done, wpcom should work too. We'll have to make sure to test that, of course, following [the bot's instructions](https://github.com/Automattic/jetpack/pull/33928#issuecomment-1789681241).

**Comment by mreishus** [comment]
I don't think this works on wpcom. After `bin/jetpack-downloader test jetpack update/scss` I don't have any of the vendor files, and trying to compile scss crashes.

**Comment by mreishus** [comment]
Ok, nice, it is working on wpcom

**Review by anomiex — APPROVED** [review]
LGTM

**Pull request merged**
