### PR TITLE
Donation block: Payment modal not displayed on iOS devices

### LINKED ISSUE #776: Jetpack Stats: Custom Post Types with 'exclude_from_search' set to true do not show titles
Automattic/jetpack#100

### LINKED ISSUE #55279: Donations block: Stripe checkout is unresponsive when viewed using iOS 14
### Steps to Reproduce

1. Use iOS device with iOS 14 (for example, iPhone)
2. Open a page with Donations block
3. Type or choose the amount. Click "Donate"

### What I expected to happen

In mobile, I expect to see black/dark green overlay and a pop-up window for Stripe payment and checkout.

Please check the GIF recording (from Browserstack) here:
https://cldup.com/HqGemSuDBI.gif

Please note, the device information:
iOS 13. Browser Safari

### What actually happened

Black overlay with no pop-up window for Stripe payment and checkout.

Please check the GIF recording (from Browserstack) here:
https://cldup.com/atrg5JgOMq.gif

Please note, the device information:
iOS 14. Browser Safari

### Context

Customer report, and I able to replicate it. This issue does not happen on Android, so I feel this issue is restricted on iOS 14.

### Operating System

macOS

### OS Version

iOS 14.x

### Browser

Safari

### Browser Version

_No response_

### Is this specific to applied theme? If so, what is the theme name?

_No response_

### Simple, Atomic or both?

Atomic

### Console and/or error logs

No console error.

### Level of impact

Normal

### Reproducibility

Consistent

### Workaround

If users needs a fix quickly, can consider to:

* install a plugin, https://wordpress.org/plugins/search/donation/
* add PayPal donate button, https://wordpress.com/support/paypal/#donate-button

### Other information

Slack discussion:
p1628487486262400-slack-C03TY6J1A

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes https://github.com/Automattic/wp-calypso/issues/55279

#### Changes proposed in this Pull Request:

* Removed a CSS style that was causing the modal to no be shown properly on iOS devices.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable? Not applicable
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

##### Atomic sites testing
* Go to an Atomic site and use Jetpack beta to use this branch.
* Make sure your proxy is disabled.
* Navigate to a site with a donations block. (You can use [this site/post ](https://atomic20220811pool.wpcomstaging.com/2022/08/16/foooing/)for example)
* The modal should be displayed correctly.
* Repeat these steps on iOS devices, desktop, and as many width combinations as possible.

##### Simple sites testing
* You should also test that it works properly on simple sites. Use the steps above (excluding going to an Atomic site)

##### Test evidence

https://user-images.githubusercontent.com/1989914/185604214-1bc693fd-6c00-4a86-bd9c-d9a6e2a03766.mp4

### CODE REVIEW

**Comment by dsas** [comment]
I get a slightly weird display glitch when using the simulator. If it matters I'm using a Jurassic Ninja site using this branch via the jetpack beta plugin.

image

As soon as I scroll the dialog part of the page, the glitch disappears

https://user-images.githubusercontent.com/93301/185613337-564ebfa2-fe58-4089-ad7e-5cc42f8a305e.mp4

Testing on Firefox, Chrome desktop and Chrome mobile all worked.

**Comment by BogdanUngureanu** [comment]
LGTM on desktop and using Chrome with a mobile resolution. I don't have an iPhone to test it there too.

**Comment by rcrdortiz** [comment]
> I get a slightly weird display glitch when using the simulator. If it matters I'm using a Jurassic Ninja site using this branch via the jetpack beta plugin.
> 
> image
> 
> As soon as I scroll the dialog part of the page, the glitch disappears
> 
>  trim_D28RYT.mp4 
> Testing on Firefox, Chrome desktop and Chrome mobile all worked.

I can't reproduce the glitch you're mentioning on Jurassic sites: https://successive-world.jurassic.ninja/2022/08/19/hello-world/

I'll clean cache and try again.

Can't reproduce after clearing cache either.

**Comment by dsas** [comment]
I can't reproduce on https://successive-world.jurassic.ninja/2022/08/19/hello-world/ I can reproduce on https://only-manatee.jurassic.ninja/2022/08/19/6/ 🙃, as we spoke about though, it's a move forward so doesn't need to be a blocker.

**Review by mmtr — APPROVED** [review]
I don't reproduce the glitch either. Tested on an actual iPhone and can confirm that the issue noted in https://github.com/Automattic/wp-calypso/issues/55279 goes away after removing the `position: absolute` declaration. I didn't notice any regression on WP.com sites, so I think this is ready to go.

**Comment by mmtr** [comment]
r251008-wpcom

**Pull request merged**
