### PR TITLE
Forms: add field id setting

### PR DESCRIPTION
**Pull request by CGastrell**
This PR adds a new text control to the field block's inspector, allowing to change the name/ID for the input.

## Proposed changes:
Add the name/ID setting on the inspector's Advance section for form input blocks
image

This is replacing our per-input implementation where it would be referred as "Unique CSS ID".

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
Insert a form on a post. Select any input and check the inspector's Advanced section, you should be able to change the input's name/ID.
It should be restricted to alphanumeric, dash and underscore (this restriction can be bypassed using the code editor).
Look at the published post, see that the input has the name/ID set for it.

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Can we move the Name ID field into the "Advanced" section, as the functionality is not really "self-explanatory", very technically, and for most users not really relevant?

The feature feels on a similar level like "customizing css classes", and would be a good fit under "advanced".

image

**Comment by CGastrell** [comment]
> Can we move the Name ID field into the "Advanced" section, as the functionality is not really "self-explanatory", very technically, and for most users not really relevant?
> 
> The feature feels on a similar level like "customizing css classes", and would be a good fit under "advanced".
> 
It not only feels similar, it's the exact same thing. The reason to put it up more prominently is that it's relevant mostly for inputs, where you not only control the CSS/styling, but actual form functionality.

If we aim to put it in the "Advanced" section, then it's already there and we only need to instruct users on where to find it.

**Comment by digitalwaveride** [comment]
Perfect, let's put it into the advanced section! There is little chance to understand what this field ID is about with out any documentation. Let's keep it in the advanced section, and let's include in the description below the ID field a "learn more" link, that points to the documentation.

**Comment by digitalwaveride** [comment]
Great! I like it Christian!

Just wondering if we should simplify the instructions, and link out to the documentation ... which we obviously still would need to create ;) ... something like this?

image

**Comment by CGastrell** [comment]
> Great! I like it Christian!
> 
> Just wondering if we should simplify the instructions, and link out to the documentation ... which we obviously still would need to create ;) ... something like this?
> 

Let's make it an issue (lacks documentation, link on settings) and let it for next iterations (either us or whoever takes over)

**Review by digitalwaveride — APPROVED** [review]
👍  Let's do this.

> Let's make it an issue (lacks documentation, link on settings) and let it for next iterations (either us or whoever takes over)

Create [issue](https://github.com/orgs/Automattic/projects/491/views/1?pane=issue&itemId=27447778) draft here.

**Comment by tbradsha** [comment]
I'll note that "name" and "ID" have separate meanings/purposes for inputs, so it's a bit confusing to combine them. It looks like it's technically the ID attribute on the backend.

@mikestottuk @StefMattana might be looking into verifying this didn't break anything on the CRM side. I think not, but worth a check and update to the docs:
https://kb.jetpackcrm.com/knowledge-base/jetpack-contact-forms/

**Comment by StefMattana** [comment]
@tbradsha I added an ID value in a contact form Name field here: https://steftest.mystagingwebsite.com/2025/01/23/test-form-id-with-crm/
I sent a message with a fake email address, I received the form in the Feedback section in WP Admin, and it created a CRM contact with no problems. 

I guess it doesn't conflict as you anticipated, but let me know if I need to test it further.

**Comment by tbradsha** [comment]
@StefMattana Thanks for testing! Note that the JPCRM doc linked above still mentions "Unique CSS ID" instead of "Name/ID".

**Comment by StefMattana** [comment]
Updated!

**Pull request merged**
