### PR TITLE
Contact Form: Update Form child blocks names

### LINKED ISSUE #27092: Optimize the Naming for Form Child-blocks
In order to [increase the visibility and discoverability of the form child blocks](pcsBup-fK-p2), we brought these form-specific blocks into their own Forms category. 
As they are now searchable via the inserter and library, not just when the form block is selected, we need to make sure that block names also work as a stand-alone search result. Names need to be descriptive regarding their functionality and make clear that all these blocks are “input fields” and not “publishing elements”.
Examples of such block names in question are “Text”, “Email,” or “Message”.|

pcsBup-jU-p2

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #27092

#### Changes proposed in this Pull Request:
* Update Form child blocks names to be more meaningful, as they'll now appear as standalone blocks

New names can be found here: pcsBup-jU-p2

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Create a Page/Post and open the Block Library
* Under the Forms section, you should see the Form child blocks with updated names.

### CODE REVIEW

**Review by CGastrell — DISMISSED** [review]
LGTM!

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Thank you João for updating the names!

Discovered an issue with the default naming of the labels though. We can't use 1:1 the block name as the default label name, as we are now using these more descriptive names. 
We would need to go through all blocks, and define specific labels.

image

**Comment by jcheringer** [comment]
> Thank you João for updating the names!
> 
> Discovered an issue with the default naming of the labels though. We can't use 1:1 the block name as the default label name, as we are now using these more descriptive names. We would need to go through all blocks, and define specific labels.
>

Nice catch! I didn't realize we were using the block name as the label.
I'll handle that

**Comment by digitalwaveride** [comment]
Thanks João for updating the labels!

Found one though that slipped through ;) 

image

If you add the multi-line text field as "standalone".

For this case, how about just showing a placeholder no default label?

image

**Review by digitalwaveride — APPROVED** [review]
João, thanks for the label updates! 👍

**Review by fgiannar — APPROVED** [review]
LGTM 👍

**Pull request merged**
