### PR TITLE
Docker: Enable support for non-Intel platforms (M1)

### PR DESCRIPTION
**Pull request by kraftbj**
Follow-up to #19234

#### Changes proposed in this Pull Request:

* Specify the platform directly for the db container.

This is needed because the mysql image on Docker Hub is not yet built for the ARM platform that the M1 uses. Once the mysql image has been updated to supply an ARM version, we should remove this to be more performant.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* I go nuclear when testing Docker things so `jetpack docker clean`
* `jetpack docker up`

Did it create the Docker env successfully?

This worked successfully for me on an Intel-based Mac, so requesting a review from both @jeherve and @anomiex as our token M1 and non-Mac folks :).

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This looks okay to me.

**Comment by anomiex** [comment]
Didn't work for me.
```
$ yarn docker:clean
yarn run v1.22.10
$ yarn docker:compose down --rmi all -v && rm -rf tools/docker/wordpress/* tools/docker/wordpress/.htaccess tools/docker/wordpress-develop/* tools/docker/logs/* tools/docker/data/mysql/*
$ yarn docker:env && yarn docker:compose-volumes && yarn docker:compose-extras && docker-compose -f tools/docker/docker-compose.yml -f tools/docker/compose-volumes.built.yml -f tools/docker/compose-extras.yml down --rmi all -v
$ node -e "require('fs').createWriteStream( 'tools/docker/.env', { flags: 'a' } );"
$ [ -f tools/docker/compose-volumes.yml ] || cp tools/docker/compose-volumes.yml.sample tools/docker/compose-volumes.yml; bash ./tools/compose-volumes.sh tools/docker/compose-volumes.yml > tools/docker/compose-volumes.built.yml
$ [ -f tools/docker/compose-extras.yml ] || cp tools/docker/compose-extras.yml.sample tools/docker/compose-extras.yml
ERROR: The Compose file './tools/docker/docker-compose.yml' is invalid because:
Unsupported config option for services.db: 'platform'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kraftbj** [comment]
@anomiex What version of docker engine and docker compose are you on? The error makes it sound like you're on an old version ( https://docs.docker.com/compose/compose-file/compose-file-v2/#platform ) but that would surprise me since we declare the file to be v3.3—unless Docker doesn't care as long as it can understand what's there.

**Comment by anomiex** [comment]
Docker version 20.10.5+dfsg1, build 55c4c88
docker-compose version 1.25.0, build unknown

Also possibly relevant: https://github.com/docker/cli/issues/1050

**Comment by kraftbj** [comment]
Ah, interesting. I presumed 3.x would always be more advanced than 2.x, but sounds like they're on independent processes. I'll look to see if we really need 3.x or not, etc.

**Comment by jeherve** [comment]
As an alternative, we could explore the option to update to MySQL 8, since there seem to be images available:
https://hub.docker.com/_/mysql?tab=tags&page=1&ordering=last_updated

Related conversation here:
p1624979052023100-slack-CBG1CP4EN

**Comment by bisko** [comment]
Within the relevant conversation, it seems that even the MySQL 8 images do not support arm/v8 (M1). 

For now it seems an alternative might be to move towards migrating to MariaDB images as they have native ports and should be drop-in replacement for MySQL in most cases.

**Comment by bisko** [comment]
Closing in favor of #20226.

It's almost the same content, but uses an updated branch name to reflect the migration to MariaDB.

**Pull request closed without merging**
