### PR TITLE
CRM: Add business telephone to invoices

### PR DESCRIPTION
**Pull request by gogdzl**
This PR adds the business telephone number to the invoices.

## Proposed changes:

Add the business telephone number to the invoices.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/zero-bs-crm/issues/2757

## Testing instructions:

* Configure a telephone number in the business settings (`wp-admin/admin.php?page=zerobscrm-plugin-settings&tab=bizinfo`)
* Create an invoice (`wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=invoice`)
* Test all three rendering options for this invoice (located in the invoice edit page - e.g. `wp-admin/admin.php?page=zbs-add-edit&action=edit&zbstype=invoice&zbsid=4`)
image
* In `trunk` the telephone is not shown in invoices.
image
* In `fix/crm-business-telephone-not-shown` the telephone is shown in invoices.
image

## NOTE
After implementing this new feature we stumbled across the field `Extra Invoice Info:` in the invoice settings page that could achieve the same thing.
In `trunk`:
image

image

Should we even go ahead merging this PR?
With this PR some people that didn't want their number to be public in the first place will have it displayed in their invoices. By not merging and putting that information about the extra invoice info in the KB we are giving them a choice of what will be displayed without adding any more settings (e.g. `Display phone number in invoices [ ]`).

### CODE REVIEW

**Review by coder-karen — APPROVED** [review]
This looks good to me.

> Should we even go ahead merging this PR?

If they didn't want their phone number to be public, then would they have any need to add it to Business Info Settings page?

**Comment by cleacos** [comment]
Maybe we could make it optional so that the users can set it in their Invoicing Settings.

**Comment by tbradsha** [comment]
I'd say that since no one has requested it, there's no need to add it at this point. I'd just close this PR without a merge, because:

* "Extra Invoice Info" field works well enough for now as a workaround should someone need it
* Merging this would result in a change in the current behaviour
* Adding a setting means more dev and code complexity

**Comment by gogdzl** [comment]
I'm choosing to close this without a merge because of the feedback received.
Thanks, everyone.

**Pull request closed without merging**
