### PR TITLE
require-lib: Update order to return out most likely valid option

### PR DESCRIPTION
**Pull request by kraftbj**
#### Changes proposed in this Pull Request:
* `JETPACK__PLUGIN_DIR . "vendor/automattic/jetpack-compat/lib/$slug.php",` is the least likely location for a file, but we're checking first. We can save file system checks by putting it in the end of the line.
* Move loader for the debugger library to the first location to improve load.
* Did not update the libraries that are shared with WP.com at this time.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* n/a

#### Proposed changelog entry for your changes:
* None needed.

### CODE REVIEW

**Comment by kraftbj** [comment]
I couldn't find an instance of needing the `JETPACK__PLUGIN_DIR . "vendor/automattic/jetpack-compat/lib/$slug.php",` within Jetpack.

Did we add that for dependent plugins that are running when Jetpack is present (partner stuff)?

Looking at WooCommerce Services (referenced in #12907) is [already calling the package directly](https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-jetpack.php#L105).

I'm wondering if we can just strike it.

**Comment by kraftbj** [comment]
This file was not synced with WP.com after 12907, so handling it via D29962-code .

**Comment by kbrown9** [comment]
> I couldn't find an instance of needing the `JETPACK__PLUGIN_DIR . "vendor/automattic/jetpack-compat/lib/$slug.php",` within Jetpack.
> 
> Did we add that for dependent plugins that are running when Jetpack is present (partner stuff)?

> 
> I'm wondering if we can just strike it.

We recently stopped using `jetpack_require_lib()` in the [compat package](https://github.com/Automattic/jetpack/pull/15046). `JETPACK__PLUGIN_DIR . "vendor/automattic/jetpack-compat/lib/$slug.php"` may have been in `jetpack_require_lib()` because the compat package needed it.

**Comment by kraftbj** [comment]
@kbrown9 Genius! I bet that's it. Can you think of any reason we'd need to leave that in require-lib then?

**Comment by kbrown9** [comment]
> @kbrown9 Genius! I bet that's it. Can you think of any reason we'd need to leave that in require-lib then?

No, I can't think of any reason it needs to stay in `require_lib()`. I guess it's possible that a dependent plugin could use `require_lib()` to load those `tracks/client` functions. If that's the case, an error would be generated if we remove that path. ,However, I don't know why a dependent plugin would go to that trouble when Jetpack makes those functions available using the compat package.

**Comment by kraftbj** [comment]
D41918-code isn't a perfect match for this PR, so needs to be manually updated if there are changes in this PR. It would bring us back in sync with wp.com on it.

**Comment by kraftbj** [comment]
We have a few instances of `tracks/client` that I missed earlier, so need to update those before landing this.

**Review by sergeymitr — APPROVED** [review]
👍

**Comment by kraftbj** [comment]
r205901-wpcom

**Pull request merged**
