### PR TITLE
Enable side loading of video types

### PR DESCRIPTION
**Pull request by dbtlr**
Currently, we block out side loading based on the result from the `file_is_displayable_image` function, which uses the builtin image processing checks to look for BMP, JPEG, GIF, or PNG file types. Instead of doing this, we should use a direct mime type check, which will allow us to check for many different types of uploads.

@georgestephanis previously made the suggestion to use the core function `wp_check_filetype` to do the mime checking, however this works based on the files extension, not by doing a real mime check, so it doesn't work with the way file downloads are processed inside of Jetpack (which is by creating tmpfiles with random file names. While we could cheat this by renaming that file to one that included the extension of the media download URL given, that requires the url have a proper extension to work.

It is more exact to instead check the mime type using the PHP builtin function `mime_content_type` which uses the OS itself to do the checking.

### CODE REVIEW

**Comment by dbtlr** [comment]
Note: I've tested this already against the WPCOM sandbox and it does indeed allow for not only the sideloading of videos, but they also are correctly processed by VideoPress in the backend.

**Comment by georgestephanis** [comment]
I'd almost rather leave the `file_is_displayable_image()` call in the new function as a fallback in case the mime type doesn't match.  I mean, sure, let it short circuit if it's in the array (which we should probably attach a filter to maybe?) but if it's not, the core method has some fallbacks I'd prefer not to lose in case of messed up mime types.

**Comment by georgestephanis** [comment]
Fixes #3164

**Comment by dbtlr** [comment]
That makes complete sense @georgestephanis.

One thing I'll need some guidance on is, what is the best way to use a filter to generate the image array. Should I simply run that array through a filter, that can then modify it, or should I instead have it be 100% defined by a filter?

I'm guessing the first of those is the answer, but I'm still pretty new to how these things are set up in WP. :)

**Comment by dbtlr** [comment]
The CI failures seem to be unrelated to my changes ... I notice a few other builds are having the same errors. I'm guessing it is a error with the CI server itself.

**Comment by georgestephanis** [comment]
> Should I simply run that array through a filter, that can then modify it, or should I instead have it be 100% defined by a filter?

Just run the existing array through a filter.  That way anyone else can add/remove items more conditionally.

Or maybe include a `pre_restapi_is_file_supported_for_sideloading` filter that passes in `null` and the `$file` and on return of anything non-null, short-circuits the rest of the function and returns that.

Or both.  Either way, maybe this is a YAGNI that we're overthinking and shouldn't bother extending yet.

**Comment by georgestephanis** [comment]
(edit: bah, didn't mean to close the request, sorry about that.)

**Comment by dbtlr** [comment]
Bad merge of master into the branch ... This PR is old anyway, going to move this changeset into v2/videopress where it belongs.

**Pull request closed without merging**
