### PR TITLE
Consent Form Block: Added field to Success page, Email and Feedback View

### LINKED ISSUE #26875: Consent Form Block: consent not being added to the success page, email and feedback view
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable Contact Form module in Jetpack settings `/wp-admin/admin.php?page=jetpack_modules`
2. Create a form using Jetpack form Blocks
3. Add a Consent form block

Screenshot 2022-10-17 at 15 25 22

5. Add an Email address in the form settings to send to

Screenshot 2022-10-17 at 15 26 14

7. Set the form setting field `On Submission = Show a summary of submitted fields`
8. Submit the form on the site with the consent field selected

### A clear and concise description of what you expected to happen.

1. I expect that all of the fields are present on the success page.
2. I expect that all of the fields are present in the feedback view.
3. I expect that all of the fields are present in the after-submit email.

### What actually happened

1. The consent field is missing from the success page.
2. The consent field is missing from the feedback view, the field is only visible if you "edit" the feedback.
3. The consent field is missing from the after-submit email.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Other information

The consent field type is being added as a "standard" field type [here](https://github.com/Automattic/jetpack/blob/1f6e6d28b530635f658480b58f45533ec0fff9ce/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L3145). But it's not properly added to all the other places where it's accessed/used/saved as per warning from the function [comment](https://github.com/Automattic/jetpack/blob/1f6e6d28b530635f658480b58f45533ec0fff9ce/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L3070).

That causes an issue later when the [compiled form data](https://github.com/Automattic/jetpack/blob/1f6e6d28b530635f658480b58f45533ec0fff9ce/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L2830) is created. The consent field is not picked up.

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by Ninodevo**
Fixes [#26875](https://github.com/Automattic/jetpack/issues/26875). The initial feature was added in this [PR](https://github.com/Automattic/jetpack/pull/16808).

#### Changes proposed in this Pull Request:

- The consent form block field is removed from the "standard" field type and is added to the "extra" field type. The "extra" field type automatically handles the Success Page, Email, and Feedback Views so the field is properly shown. The field is also visible in the CSV export.
- The `email_marketing_consent` field setup is moved to the `get_field_ids` function. The field is set on the first Consent field type. 

#### Jetpack product discussion
This issue was discussed in slack with Jetpack developers before implementation. p1665394433939419-slack-jetpack-developers

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

1. Enable Contact Form module in Jetpack settings `/wp-admin/admin.php?page=jetpack_modules`
2. Create a form using Jetpack form Blocks
3. Add a Consent form block - the type of the Consent block is irrelevant

Screenshot 2022-10-17 at 15 25 22

5. Add an Email address in the form settings to send to

Screenshot 2022-10-17 at 15 26 14

7. Set the form setting field `On Submission = Show a summary of submitted fields`
8. Submit the form on the site with the consent field selected

#### Sucessful Results

1. Consent field is visible on the success page

Screenshot 2022-10-17 at 16 13 29

3. Consent field is visible on the Feedback View

Screenshot 2022-10-17 at 16 19 13

5. Consent field is visible in the after-submit email

Screenshot 2022-10-17 at 16 17 04

### CODE REVIEW

**Review by samiff — APPROVED** [review]
Tested with a checkbox consent field and both states worked well for me 👍

**Comment by Ninodevo** [comment]
Thank you for the review @samiff. Can I also add you for the WP.com diff D90037 as a reviewer? I've tested it and works as expected. 
I can't find your username there to add you.

**Comment by samiff** [comment]
Approved the diff 👍

**Comment by Ninodevo** [comment]
Just noting that the grunion-contact-form was defused in diff D90043 and that this diff D90037 is not needed anymore. I closed the diff.

**Pull request merged**
