### PR TITLE
Dialogue: fix copy/paste block into block content

### PR DESCRIPTION
**Pull request by retrofox**
This PR fixes a bug when copy blocks and paste them into the dialogue content.
Fixes #

#### Changes proposed in this Pull Request:

* Dialogue: fix copy/paste block into block content.

#### Jetpack product discussion

p7DVsv-atS-p2#comment-34461

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create/Edit a post
* Create a random block
* Create Conversation/Dialogue blocks

Canvas | Outline
-----|----
image | image

* Copy the random block...
* ...and paste it into the Dialogue content

**before**
* The Dialogue block keeps empty
* There is an error in the dev console.

Canvas | Dev Console
------|------
image | image

**after**
* There are no errors in the dev console
* the blocks are pasted and now are children of the Conversation block

Canvas | Outline | Dev console
----|-----|-----
image | image | image

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by creativecoder — APPROVED** [review]
Tested according to testing instructions. I wasn't seeing the console error, but using current version of block I wasn't able to paste the copied blocks. But with the change in this PR, it worked.

I also saw what looks like this same part of the code causing issues with copying and pasting in a previous version of the block, so feeling a bit 😌  to see a fix for this issue.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in fa4ef7e23b8e20f8e78e024de142da27fc02e691

**Comment by retrofox** [comment]
r221112-wpcom

**Pull request merged**
