### PR TITLE
E2E tests: save video for all tabs

### PR DESCRIPTION
**Pull request by adimoldovan**
#### Changes proposed in this Pull Request:

For tests that use multiple browser tabs we're not saving the video for all the opened pages. This should fix that.

#### Jetpack product discussion
pd5faL-1q-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Run Mailchimp test and make if fail -> there should be 2 video files saved in the output folder

### CODE REVIEW

**Review by brbrr — COMMENTED** [review]
> Run Mailchimp test and make if fail -> there should be 2 video files saved in the output folder

I checked the second video, and for some reason, it includes only 1 retry attempt. The Mailchimp does retries the connection multiple times, and apparently, it happens in different tabs. I'm not sure we can do anything about it here, but worth to mention anyway

**Comment by adimoldovan** [comment]
> it includes only 1 retry attempt

That is strange. All tabs that are opened when the test ends should be saved.
But I don't understand why it would retry in another tab. Nothing in the code looks like the 2nd retry would happen in another tab.

**Comment by brbrr** [comment]
Yeah, agreed. The test uses the same instance of a page for all the retries. Maybe the fact that one of the page methods throwing on timeout causes to tab to get closed/reset?

**Comment by adimoldovan** [comment]
> Do you want to merge it, and then figure out the Mailchimp thing or do you want to address it in this PR?

That depends on the problem, which I don't really understand. If it's a playwright-env or video-saving logic issue I would address it in this PR. If it's something specific to Mailchimp test I would close it. I will give it some more time to test and to reproduce and understand the problem.

**Comment by adimoldovan** [comment]
@brbrr I checked this again and couldn't find any issue. Here's an example where all 5 attempts are recorded: [report](https://automattic.github.io/jetpack-e2e-reports/20934/report/#suites/fdcc91b27974c84847e605cee75e54b0/fcc5615c67194bbc/?attachment=2cc21337d27a710).
I suggest we merge this and if this comes back again we'll deal with it then. Anyway, most probably the problem is not in the video saving logic, so not really the scope of this PR.

**Review by brbrr — APPROVED** [review]
Make sense

**Pull request merged**
