### PR TITLE
Update PHP 7.4 to 8.0 in our tools

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

* Updates PHP version constant in `.github/versions.sh` from `7.4` to `8.0`. This constant value is used in various monorepo tools. [Active support](https://www.php.net/supported-versions.php) for 7.4 is elapsed.
* Removes `php${PHP_VERSION}-json` from the Dockerfile. _"As of PHP 8.0.0, the JSON extension is a core PHP extension, so it is always enabled."_ [source](https://www.php.net/manual/en/json.installation.php)

#### Jetpack product discussion

Internal: p9dueE-3Vv-p2#comment-6799

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

- Make sure your Jetpack Docker container is stopped.
- Pull down changes in this PR.
- Run `jetpack docker build-image`. Check to see if there are any errors reported during the build process.
- Next run `jetpack docker up` to start your Jetpack container.
- Once the Jetpack container is up run `jetpack docker sh`. When you see the Docker instance shell run `php -v` to see the updated PHP version in use, 8.0.z (it would have been 7.4.z previously).

After this PR is merged, we can also check that the `Build Docker` workflow published an updated image https://hub.docker.com/r/automattic/jetpack-wordpress-dev

### CODE REVIEW

**Comment by samiff** [comment]
@anomiex Few questions:

1. Does `MAX_PHP_VERSION` in `versions.sh` need updating at all?
2. Is the `.github/php-version` file necessary still? Looks like the `versions.sh` PHP value may have replaced that.
3. Once merged, are we wanting to have everyone build their local Jetpack image again, or is that not necessary?

**Comment by anomiex** [comment]
>     1. Does `MAX_PHP_VERSION` in `versions.sh` need updating at all?

Looks like the only use of it is in the check-development-environment.sh script. We probably should wait to increment it until we have PHP 8.1 fully working.

>     2. Is the `.github/php-version` file necessary still? Looks like the `versions.sh` PHP value may have replaced that.

Nope. I guess I forgot to delete that in #20031. Also `.github/pnpm-version`.

>     3. Once merged, are we wanting to have everyone build their local Jetpack image again, or is that not necessary?

That shouldn't be necessary. People might want to do a `docker image pull automattic/jetpack-wordpress-dev` though, after the image build action completes post-merge.

**Comment by anomiex** [comment]
As for CI, a few notes:

* To merge this, we'll have to adjust the GitHub settings to make "PHP tests: PHP 7.4 WP master" and "PHP tests: PHP 7.4 WP previous" not required, and make the new "PHP tests: PHP 8.0 WP master" and "PHP tests: PHP 8.0 WP previous" required.
* The Code Coverage job is failing at the moment because WordPress 5.8.2 still has the "we require an old monkey-patched version of PHPUnit" thing going on even though they backported the fix for that from 5.9. Sigh. I think updating the no-longer-needed hack at https://github.com/Automattic/jetpack/blob/190266a268e7ac18a45665104705da3c377d5129/.github/files/setup-wordpress-env.sh#L38-L42 may be the best workaround for now.
   ```bash
   # 5.8.x still requires a monkey-patched obsolete version of phpunit.
   # If that's latest, run the coverage test with the upcoming 5.9 instead.
   # @todo: Remove this once WordPress 5.9 is "latest".
   if [[ "$LATEST" == 5.8.* && "$TEST_SCRIPT" == "test-coverage" ]]; then
       LATEST=master
   fi
   ```
* Post-merge, we'll want to manually bump the `pr-update-to` tag to help signal to people that they need to do a master merge. That'll look something like `git pull && git tag -f pr-update-to && git push -f origin pr-update-to` IIRC.

**Comment by samiff** [comment]
> we'll have to adjust the GitHub settings to make "PHP tests: PHP 7.4 WP master" and "PHP tests: PHP 7.4 WP previous" not required, and make the new "PHP tests: PHP 8.0 WP master" and "PHP tests: PHP 8.0 WP previous" required.

Done.

Modified `setup-wordpress-env.sh` in https://github.com/Automattic/jetpack/pull/22046/commits/bc27d341c94732fe1ab4d32b39a2767e39e5d76a but seems like the code coverage check failed again, but for something different this time:

```sh
1) WP_Test_Jetpack_Sync_Full::test_full_sync_can_sync_individual_comments
  Failed asserting that an array contains 73.
  /tmp/wordpress-latest/src/wp-content/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-full.php:1272
```

Didn't try rerunning yet.

**Review by anomiex — APPROVED** [review]
Let's hope the Code Coverage test failure is just flakiness.

**Comment by samiff** [comment]
Internal: r236272-wpcom

**Pull request merged**
