### PR TITLE
SSO Invite Users: Improve error handling when inviting users

### PR DESCRIPTION
**Pull request by agrullon95**
Fixes #

## Proposed changes:

When an error occurs with the invite user API, the errors are not handled correctly and are throwing a critical error on /wp-admin.
These changes will handle API response errors gracefully when inviting users and will display a error notice instead of a critical error screen.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sync to WoA
* Add `define('JETPACK__SANDBOX_DOMAIN', 'SANDBOX_HOST_NAME') ;` to your atomic site wp-config.php
* Test error scenarios when inviting users by modifying the backend. You can force throw `new WP_ERROR('random_text', 'some message');` on WPCOM.
* Try to break this ( critical error on frontend)

### CODE REVIEW

**Review by renancarvalho — DISMISSED** [review]
Hi @agrullon95 thanks for working on this one. Tested and works fine!
I have just added some better error handling on revoke action as well to keep it more consistent.

If the revoke fails, it should show this generic message.
image

**Comment by heavyweight** [comment]
Sorry @renancarvalho your review got dismissed
Can you recheck again please?

**Review by heavyweight — APPROVED** [review]
Tested and looks good to me.
Lets wait for one more review for safety..

**Review by renancarvalho — APPROVED** [review]

**Review by escapemanuele — APPROVED** [review]
LGTM 👍

**Pull request merged**
