### PR TITLE
Migrate Modifying DAL to be able to query the contact table excluding IDs which have already been sent.

### PR DESCRIPTION
**Pull request by sdixon194**
Migrated from Jetpack CRM repo https://github.com/Automattic/zero-bs-crm/pull/1270

## Proposed changes:

This adds some support for filters to the MySQL query for MC2 release. 

Currently MC2.0 grabs all contacts and all the data matching an audience (limit 50,000) these filters should allow us to retrieve less data (i.e. id, email, dnd) and also hopefully join with the mailstats table, and select contacts which haven't been sent the email (so the list it returns will get smaller, rather than the full list and grabbing all the stats array too).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a
## Does this pull request change what data or activity we track or use?

no
## Testing instructions:

TBD

### CODE REVIEW

**Comment by sdixon194** [comment]
cc @coder-karen this PR is pretty old since it's from the time of the migration - I'm assuming I can just close it out but wanted to double check.

**Comment by kallehauge** [comment]
> this PR is pretty old since it's from the time of the migration - I'm assuming I can just close it out but wanted to double check.

Yeah, it was even old at the time of migration so I'd definitely consider it stale at the very least. Closing it, thanks @sdixon194 !

**Comment by kallehauge** [comment]
> this PR is pretty old since it's from the time of the migration - I'm assuming I can just close it out but wanted to double check.

Yeah, it was even old at the time of migration so I'd definitely consider it stale at the very least. Closing it, thanks @sdixon194 !

**Comment by coder-karen** [comment]
Thanks both!

**Pull request closed without merging**
