### PR TITLE
Mailchimp block - improve loading state

### PR DESCRIPTION
**Pull request by lukaszwilczakwilnet**
Fixes # https://github.com/Automattic/jetpack/issues/19390

#### Changes proposed in this Pull Request:
Center spinner inside block during loading

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
Create new post
Add new Mailchimp block
Verify if spinner is centered

Screenshot 2022-06-10 at 14 00 48

### CODE REVIEW

**Comment by rcrdortiz** [comment]
Maybe we could add the name next to the logo while we load. Once the spinner is removed the UI looks like this:
Captura de Pantalla 2022-06-10 a las 15 14 41
I think it makes sense to add the title next to the icon while loading as well. If I remember correctly you can achieve it with the label property 
```
<Placeholder icon={ icon } label={ __( 'Payments', 'jetpack' ) } notices={ notices }>
	<div class="class that centers content">
            <Spinner />
        </div>
</Placeholder>
```

**Review by dsas — DISMISSED** [review]
Works for me 👍

**Review by jeherve — DISMISSED** [review]

**Comment by lukaszwilczakwilnet** [comment]
> Maybe we could add the name next to the logo while we load since just centering the spinner doesn't improve the UX by too much. Once the spinner is removed the UI looks like this: Captura de Pantalla 2022-06-10 a las 15 14 41 I think it makes sense to add the title next to the icon while loading as well. If I remember correctly you can achieve it with the label property
> 
> ```
> <Placeholder icon={ icon } label={ __( 'Payments', 'jetpack' ) } notices={ notices }>
> 	<div class="class that centers content">
>             <Spinner />
>         </div>
> </Placeholder>
> ```

Done, i've added label. Looks much better.

**Review by Copons — APPROVED** [review]
Screenshot 2022-06-13 at 16 40 27

LGTM! 🚢

**Comment by Copons** [comment]
r247323-wpcom

**Pull request merged**
