### PR TITLE
Make Widget Visibility extensible

### PR DESCRIPTION
**Pull request by georgestephanis**
Implements @cfinke's suggestions originally in https://github.com/Automattic/jetpack/pull/434#issuecomment-39266425

Fixes #434 

Related: #6333, #3444

### CODE REVIEW

**Comment by georgestephanis** [comment]
There's been so many changes to the core of the module that nothing outdated will work and will really need to be rewritten from scratch with the goal of implementation.  Let's do it sometime, but this isn't the fix.

**Comment by paulschreiber** [comment]
@georgestephanis What ticket is tracking this work now?

**Comment by georgestephanis** [comment]
I'm honestly unsure, this was closed because it wasn't the best solution.

**Comment by paulschreiber** [comment]
Should I file a new ticket?

**Comment by jeherve** [comment]
@paulschreiber If you have ideas on another way to implement this, feel free to open a new issue and share your ideas!

**Pull request closed without merging**
