### PR TITLE
Site Settings: Add new site option for WooCommerce themes headstart flag

### PR DESCRIPTION
**Pull request by sixhours**
Related to https://github.com/Automattic/wp-calypso/issues/85793

## Proposed changes:

* When a WooCommerce theme is initially bundled with a site, we need to know if we should run Headstart for the theme. We've introduced a new site option `woocommerce_should_run_headstart_for_theme` for this purpose. This diff adds the option to the site settings endpoint and sanitizes it (the value must be `yes` or empty).
* We only want to run Headstart for product categories _once_, so we'll be checking this value in wpcomsh Automattic/wpcomsh#1665 If we have already run Headstart, the site option gets deleted. This should prevent product categories from being added every time a new WC theme is activated/Headstart is run.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* TBD

### CODE REVIEW

**Comment by daledupreez** [comment]
@sixhours, I don't know that we need this option available via the REST API. For our use case, we're only going to be fetching the value via local `get_option()` calls, and I think we want to avoid making this modifiable via REST API calls.

**Comment by sixhours** [comment]
> @sixhours, I don't know that we need this option available via the REST API. For our use case, we're only going to be fetching the value via local get_option() calls, and I think we want to avoid making this modifiable via REST API calls.

Ahhh, I was going by what @andres-blanco mentioned in this comment:

https://github.com/Automattic/wp-calypso/issues/85793#issuecomment-1908664667

But I have little familiarity with how the bundled themes work behind the scenes so maybe we don't need to add the option to the API for that. I'll double-check with Andy and close this if it's unnecessary.

**Comment by sixhours** [comment]
I don't think we need to add this option to the API after all, but leaving it open 'til we're sure.

**Comment by sixhours** [comment]
Closing this as we don't need it.

**Pull request closed without merging**
