### PR TITLE
Sync: Add a passing test that shows how to prevent shortcodes from expanding

### PR DESCRIPTION
**Pull request by enejb**
part of #869

#### Changes proposed in this Pull Request:
Add a filter that lets us not expand some shortcode because we can expand them later at a different time from .com. 

#### Testing instructions:
* Do the unit tests pass? 
* Do the data that comes in to the .com shadow site reflect what we want to see? 

Adds a filter that can be used to filter out some type of shortcodes
that can be expanded on the .com side in a more relevant context.

### CODE REVIEW

**Comment by zinigor** [comment]
It looks like the slideshow shortcode is not accounted for somewhere in the test.

**Comment by enejb** [comment]
The test are passing here now as well. 

This will help with subscription emails and work more in line how .com does things.

**Comment by cejayassoc** [comment]
Where/What variable can I edit to add my own shortcode to the "skip" list, and can it include a "wildcard"?  For some reason, Divi has decided to add the version number to it's builder shortcode.  Here's what I need removed:
[et_pb_gallery _builder_version="3.0.76" ... ]
[et_pb_post_nav _builder_version="3.0.76" ...]

**Comment by jeherve** [comment]
cc @enejb Could you take a look at the above?

**Comment by enejb** [comment]
@cejayassoc We don't sync the whole filtered content any more. We used to now we send the content that has the shortcodes. Can you tell me what problem you are trying to solve and I can hopefully find a solution.

**Comment by cejayassoc** [comment]
@enejb  Here's what our e-mail messages are looking like (We are using the Divi theme by Elegant Themes and the Divi Builder keeps inserting shortcode...we are open to work-arounds):
 
e-mail_with_code

This is the actual post in the screenshot above: http://animalimagery.us/other/cady-the-capuchin-monkey/

**Comment by enejb** [comment]
Thanks for the info. I should be able to add the shortcodes to the list of shortcodes that should be replaced by nothing. So that they don't show up in emails like yours. 

There is unfortunately no way to that the emails can be formatted the same way as they are on your page.

**Comment by enejb** [comment]
@cejayassoc The changes was deployed so you should be able to send out posts with the ^ shortcodes and they will be ignored.

**Comment by cejayassoc** [comment]
I am impressed beyond belief, I didn't think anyone would ever get around to it ;) Thanks so much!!

**Pull request merged**
