### PR TITLE
Fix/carousel form padding

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request:

* Tidies up comment form padding and widths on smaller screens

Before:
Screen Shot 2021-06-25 at 8 46 10 AM

After:
Screen Shot 2021-06-25 at 8 45 05 AM

* Also constrains the width of the info area for better layout on larger screens

Before:
Screen Shot 2021-06-25 at 9 12 05 AM

After:
Screen Shot 2021-06-25 at 9 11 35 AM

### CODE REVIEW

**Review by apeatling — CHANGES_REQUESTED** [review]
Padding and widths look great, just needs some space above the button at smaller widths. Same amount of space as between the top of the input label and the bottom of the previous input.

IMG_1376

**Comment by ramonjd** [comment]
I've resolved the button padding issue [mentioned above](https://github.com/Automattic/jetpack/pull/20177#pullrequestreview-692235213).

form_submission

Also took the opportunity to show the error message and spinner in more prominent locations. They were hidden on smaller screens.

**Review by ramonjd — APPROVED** [review]
The padding changes look good to me. 

I'm not reviewing my own changes by the way :)

Screen Shot 2021-06-25 at 11 53 38 am

Screen Shot 2021-06-25 at 11 54 00 am

**Review by glendaviesnz — COMMENTED** [review]
Your changes test well for me @ramonjd

**Pull request merged**
