### PR TITLE
 Lazy Images: Make it a part of Jumpstart

### PR DESCRIPTION
**Pull request by Dec0y-jb**
Hello, I have added "Jumpstart" to Feature section of Header. This is in reference to Issue #9567.

### CODE REVIEW

**Comment by Dec0y-jb** [comment]
Sorry about that. I was creating a pull request for a different issue and merged these by mistake.

**Comment by ebinnion** [comment]
Hi @Dec0y-jb – I'd suggest removing the commits. To do that, I typically use `git reset --hard HEAD^` which will remove the last commit and its message.

**Comment by Dec0y-jb** [comment]
OK, I will go ahead and remove the commits.

**Comment by Dec0y-jb** [comment]
@ebinnion - I tried removing these changes manually because I don't have the clone I was working from. Will that suffice? Or should I try and revert all the changes when I get back to my laptop later?

**Comment by jeherve** [comment]
Replaced by #9613

**Pull request closed without merging**
