### PR TITLE
Update newspack blocks 3.5.0 → 4.0.1

### LINKED ISSUE #69306: [Block] Blog Posts Block missing first post when added to FSE Templates
### Quick summary

Using the `Blog Posts Block` instead of a `Query Loop Block` on templates seems to not work well. The most recently published post doesn't display on the live site. 

(And because of the lack of previews, as reported here: https://github.com/Automattic/wp-calypso/issues/69101 , this is hard to notice while working in the editor)

### Steps to reproduce

1. Activate an FSE theme like `Zoologist`
2. Set the homepage to display latest posts
3. Open the Site Editor to edit the homepage
4. There will be a Query Loop block in place. Below that, add the Blog Posts block to the template. 
5. Save this change and view the live site

### What you expected to happen

The same posts in the same order should appear in either the Query Loop Block or the Blog Posts block.

### What actually happened

The Blog Posts block does not include the most recently published post.

**Example: AT site, Zoologist Theme**

Markup on 2022-10-20 at 15:43:19

### Context

Currently testing for this user: 5646515-zd-woothemes

This issue has also been reported as theme specific, here: https://github.com/Automattic/themes/issues/6161 but it seems it's not just impacting that theme. 

I replicated the issue on an AT test site using **Byrne** and **Zoologist**.

**Byrne**

Markup on 2022-10-20 at 15:38:34

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

Firefox

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to replace the Blog Posts block with the Query Loop block. While this is easy for us to implement, it may be difficult for users who prefer the Blog Posts block, as the QL block is more complex to add and set up.

### LINKED ISSUE #73171: [Block] Post Carousel - missing first post when added to FSE Templates
### Quick summary

When adding the Post Carousel inside the Index template the carousel starts displaying from the second most recent published post. The new post is skipped. 

Current workaround: Move the Carousel block out of the template and inside the page content. 

### Steps to reproduce

1- Insert the Carousel Post block on the Index template on your FSE theme.
2- Set either the homepage or another page as the Post Page. 
3- Check the post page live.

### What you expected to happen

To view the carousel starts with the most recent published post

### What actually happened

Carousel skips first post. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported on 5925571-zd-woothemes

### PR DESCRIPTION
**Pull request by dsas**
Fixes https://github.com/Automattic/wp-calypso/issues/69306
Fixes https://github.com/Automattic/wp-calypso/issues/73171

## Proposed changes:

Upgrading newspack blocks to 4.0.1
 * Mainly build and dependency changes
 * Also includes a fix to make the carousel and list posts blocks stop excluding the first post in the loop when used outside of a single posts/pages.

Improve the newspack sync system:
 * Fix issue with undefined constant
 * Updated readme with new instructions
 * Removed hardcoded version number in the npm command list, now users will get an error message unless they supply what to sync

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Create a simple site with a block theme
2. Update your sandbox as described in the comment below
3. Sandbox your site
4. Edit the template to replace any query block with a Blog Posts block
5. Look at the front-end of the site, it this block should include the configured number of posts starting with the most recent post.
6. Replace the Blog Posts block with a Post Carousel block
7. Repeat step 3.
8. Transfer your site to atomic
9. Use the instructions below to configure your atomic site to have this PR (use jetpack beta tester to change the `WordPress.com Features` branch.
10. Repeat steps 4-7

### CODE REVIEW

**Comment by dsas** [comment]
This works on simple, but it doesn't work on atomic. 

It looks like atomic uses the version of newspack blocks bundled in ETK still 😕 When I deactivated ETK the blocks disappeared from the front-end and the editor says "Your site doesn’t include support for the "a8c/posts-carousel" block. You can leave this block intact or remove it entirely."

As far as I understand [newspack blocks were removed from ETK](https://github.com/Automattic/wp-calypso/pull/93238).

**Comment by arthur791004** [comment]
> When I deactivated ETK the blocks disappeared from the front-end and the editor says "Your site doesn’t include support for the "a8c/posts-carousel" block. You can leave this block intact or remove it entirely."

It works on my side. What's the ETK version on your atomic site?

**Comment by arthur791004** [comment]
> When I deactivated ETK the blocks disappeared from the front-end and the editor says "Your site doesn’t include support for the "a8c/posts-carousel" block. You can leave this block intact or remove it entirely."

It works on my side no matter whether the ETK plugin is active or not 🤔

**Comment by arthur791004** [comment]
Tested, and now I can see all posts on my homepage!

**Comment by dsas** [comment]
> This works on simple, but it doesn't work on atomic.

My problem was that I updated `WordPress.com Site Helper` with jetpack beta and not `WordPress.com Features`. As wpcomsh depends upon wpcom-features I thought that was sufficient.

**Review by arthur791004 — APPROVED** [review]

**Pull request merged**
