### PR TITLE
Embeds: Add support for Instagram Reel permalinks

### LINKED ISSUE #17662: Instagram Block:  Improve URL handling for "Reels"
Instagram Reels use a slightly different URL from standard Instagram videos, and does not work in the Instagram block.

For example, this URL does not work:  https://www.instagram.com/reel/CG7PQkGhA8J/
Whereas this URL does seem to work:  https://www.instagram.com/p/CG7PQkGhA8J/

#### Steps to reproduce the issue

1. Go to Gutenberg and add Instagram block
2. Add URL from an Instagram reel (https://www.instagram.com/reel/CG7PQkGhA8J/) and attempt to embed
3. Error message in block:  Sorry, this content could not be embedded.
4. Edit the URL to change reel to p and try again
5. Video is embedded as expected

See screencast of the issue here:  https://d.pr/v/9ZP5tN

Also worth noting that Instagram does not allow Reels to be viewed as on other sites, so the resulting (successful) embed displays the video frame, but with a "play on Instagram" player button.  An argument can be made that due to this we should block Reels from being embedded, and show more specific error message like "Instagram Reels cannot be embedded" instead.

### PR DESCRIPTION
**Pull request by pierlon**
Fixes #17662 

#### Changes proposed in this Pull Request:

Adds support for Instagram Reel permalinks to be used as embedded content.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

1. Create a new post and add an Instagram block
2. Enter the URL https://instagram.com/reel/COWmlFLB_7P/
3. See that the Instagram Reel embed is now in the post

Before | After
---|---
image | image

### CODE REVIEW

**Comment by kraftbj** [comment]
Howdy! Thanks for your contribution! Trying it first hand, it worked well once I disabled the Facebook blocking I have setup in my browser :).

It looks like the lining and the PHPunit testing failed on this PR though. I can look at it later this week, but feel free to take a gander to help speed things up.

Please note that I added a changelog file to the PR, so you'll want to pull from the remote before making any changes.

Thanks again!

**Comment by pierlon** [comment]
Thanks for the quick review @kraftbj! The lint and PHP test errors should be resolved in 2bcf8b177796364f17d0f540f7273a7afd85caf8.

**Comment by pierlon** [comment]
There was a newline (`\n`) in the mocked body response that was preventing the JSON from being parsed. That's been resolved in https://github.com/Automattic/jetpack/pull/19735/commits/7f7869123b33930c24b04e631b28c9b699ec1b96.

**Review by jeherve — APPROVED** [review]
This tests well for me now. It should be good to merge once the tests pass!

**Comment by jeherve** [comment]
Internal reference: r225352-wpcom

**Comment by pierlon** [comment]
@jeherve Anything I need to do to get this PR merged?

**Comment by jeherve** [comment]
No, you should be all set! Once the tests pass, the PR will be merged 👍

**Pull request merged**
