### PR TITLE
Check for presence of `id` option when building WPCOM connection link

### PR DESCRIPTION
**Pull request by kraftbj**
This is an attempt at #2218. This doesn't truly fix the issue—only hide it to reduce the support load.

Even with this, we should add logging of some type, namely for beta testers and try to lock this down more.

This requires extra testing. I'll update to Needs Review when ready! :)

### CODE REVIEW

**Comment by kraftbj** [comment]
@dereksmart This what you were thinking for this?

**Comment by dereksmart** [comment]
Yeah basically. but since registration could also fail if some of <a href="https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2870-L2878">these other options</a> are still in the DB (will have to check exatcly which ones), we might want to check for more than just `blog_token`.

**Comment by dereksmart** [comment]
I'm thinking now that we should just delete_options rather than calling the whole `disconnect()` method.

**Comment by kraftbj** [comment]
I'm down with deleting options. However resulted in this state is messy and wp.com can handle it if not disconnected from wp.com first. What about if `jetpack_private_options` exists, delete it?

**Comment by dereksmart** [comment]
@kraftbj pulling a 180 on you here, as I think the best solution for the specific `invalid_client_id` problem is the one that @felixarntz suggested in #2218 to check for absence of `id` as well as `blog_token` when building the registration link.  

I was mistaken when I initially looked into this.  The actual problem that is causing this specific error message is the missing `id`, not necessarily the presence of a `blog_token`.   

So, I've updated the PR to reflect this, and I think it should do the trick.

**Pull request merged**
