### PR TITLE
load polldaddy scripts asynchronously

### PR DESCRIPTION
**Pull request by rodruiz**
#### Changes proposed in this Pull Request:

* Load polldaddy scripts asynchronously to improve load time.

#### Testing instructions:

* To check polldaddy scripts are loading asynchronously.

### CODE REVIEW

**Comment by rodruiz** [comment]
Hi @jeherve,
how long does it takes to test and merge this?
Thanks

**Comment by jeherve** [comment]
We haven't had the chance to look at your PR yet as there were other higher-priority PRs that needed our attention, but we'll get to yours soon!

**Comment by rodruiz** [comment]
Sounds good. Thanks.

**Comment by oskosk** [comment]
Can you add testing instructions, like from scratch to test this? steps to  add a poll and such. Something that helps us reach a state where we can compare old to new behaviour clearly.

**Comment by rodruiz** [comment]
Hi @oskosk,
1- you can add a poll using a shortcode: [polldaddy poll="THE-POLL-ID"].
2- new behavior: load scripts asynchronously. Improve page load time.
3- old behavior: load scripts synchronously. Slow load time.

Thanks.

**Comment by oskosk** [comment]
Thank you!

**Pull request merged**
