### PR TITLE
Internal release: add was_hosting_trial flag to indicate if site ever had a hosting free trial

### PR DESCRIPTION
**Pull request by mpkelly**
## Proposed changes:

* add a flag to site endpoint responses, `was_hosting_trial`. This flag is used internally by the Hosting Free Trial project. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Test instructions added to internal issue.

### CODE REVIEW

**Review by vykes-mac — COMMENTED** [review]
@mpkelly when I use `v1.1` if the api i see the `was_hosting_trial` flag, however when I use v1.2 the flag is not present. The `was_migration_trial` and `was_ecommerce_trial` shows for both `v1.1` and `v1.2`, I'm assuming it should be the same for `was_hosting_trial`.

**Comment by mpkelly** [comment]
> @mpkelly when I use `v1.1` if the api i see the `was_hosting_trial` flag, however when I use v1.2 the flag is not present. The `was_migration_trial` and `was_ecommerce_trial` shows for both `v1.1` and `v1.2`, I'm assuming it should be the same for `was_hosting_trial`.

@vykes-mac, thanks for finding that. I will fix it.

**Comment by mpkelly** [comment]
I can see it in the 1.2 API. I was missing an entry in the `$site_format` so I added that. Can I get a re-review, @vykes-mac. 

Screenshot 2566-10-10 at 12 03 10

**Review by vykes-mac — APPROVED** [review]
This looks good @mpkelly

**Pull request merged**
