### PR TITLE
Carousel: GPL-2.0 or later please

### PR DESCRIPTION
**Pull request by nextgenthemes**
Could you please change the license. I like to take some code but into a GPL-3.0 plugin.

### CODE REVIEW

**Comment by jeherve** [comment]
cc @pesieminski for review.

**Comment by jeherve** [comment]
@nextgenthemes Just curious, what will you use Carousel for? I'm always curious of the other cool projects and tools built on top of Jetpack :)

**Comment by nextgenthemes** [comment]
Would be great if you do this to all Jetpack. Quoting wp.org.

> We strongly recommend using the same license as WordPress — “GPLv2 or later.”

I am working on a minimalistic opinionated carousel based on Bootstrap 4.0. Just took some lines from this. It taught me how to do things, saved me some time. So I would not call that "on top of Jetpack" but I  learned how this can be done and still have some unchanged lines and one unchanged function from this.

**Comment by samhotchkiss** [comment]
If we make this change, we should probably make it across the board.

I'm not an expert in the intricacies of licensing, so I'll leave this up to @pesieminski to decide on.

**Comment by pesieminski** [comment]
The license on Jetpack overall is GPLv2: https://github.com/woocommerce/woocommerce-gateway-simplify-commerce/pull/5

Assuming the components are derivatives of Jetpack main?

If so, we can change the license on any component to a compatible license. GPLv2 would be an option, but "GPLv2 or later" would not be compatible.

**Comment by dereksmart** [comment]
@nextgenthemes feel free to re-open with a compatible version as @pesieminski described.  Thanks!

**Comment by nextgenthemes** [comment]
@dereksmart @pesieminski I do not get what you mean and why you linked to a woo-commerce thing, something that is GPLv3. How does this relate exactly? I want to used this code in a plugin and license that under GPLv3. Therefore I need this to be either v3 or "v2 or later" and I do not understand why "GPLv2 or later would not be compatible." with what exactly?

**Comment by pesieminski** [comment]
@nextgenthemes sorry, I think I just pasted the wrong link, I was working on two things at once. 

I meant this one: https://github.com/Automattic/jetpack/blob/master/LICENSE.txt

This shows the license on Jetpack as v2 - if a piece of code is licensed under GPLv2, it's not able to be used in a project that is licensed under GPLv3 or "GPLv2 or later", so would not work with your GPLv3 project.

I *think* that this may not be correct though, and Jetpack + components should be licensed as "GPLv2 or later" which would solve your problem. I'll check and see, for sure and we can change the license file to be more clear.


image

**Comment by nextgenthemes** [comment]
@pesieminski OK you 

> if a piece of code is licensed under GPLv2, it's not able to be used in a project that is licensed under GPLv3 or "GPLv2 or later", so would not work with your GPLv3 project.

Yeah and that is the exact reason I opened this issue. No offense but you brought nothing but confusion here and looks like @dereksmart was just looking for a reason do close.

And Jetpack is actually mainly licensed with "or later". The main file says GPL2+ and I just found only 2 other components that are v2 only.

**Comment by nextgenthemes** [comment]
You based your wrong info on the fact that there is a GPL 2.0 license file ...

**Comment by pesieminski** [comment]
Correct. License.txt says "GPL v 2.0" in the top banner, and did not include the "2 or later" declaration in the text. That's where I looked first and what was confusing. Plus, I am a lawyer...so easily confused. 

Anyway, submitted PR to clarify. We can also change/clarify the individual modules. They should all be 2+ and clearly say that.

Thanks for pointing it out.

**Pull request closed without merging**
