### PR TITLE
VideoPress: Disable local library item expansion when video is already uploaded (mobile)

### LINKED ISSUE #28951: VideoPress: "Upload to VideoPress" button is shown on disabled local video row on mobile
pe4Cmx-Qm-p2#comment-397

It is necessary to remove or disable the button.

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #28951

## Proposed changes:

* Prevents expansion of the row when `showActions` is false, as the button is the only information there for local videos

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the Media Library and upload some videos
* Connect Jetpack
* Go to the VideoPress dashboard and change the viewport to simulate a small screen (or test is on a smartphone)
* Using the local videos library, upload a video
* Check that after the video is uploaded, the row cannot be expanded anymore
* Change the VideoPress library to show rows instead of cards
* Check that the rows work as normal without regressions

### CODE REVIEW

**Review by renatoagds — DISMISSED** [review]
Tested and works as expected.

**Comment by lhkowalski** [comment]
Tested on a JN site. Started with 2 local videos, one of them unreadable. The unreadable is shown on a not-expandable row, as expected:

Screen Shot 2023-02-14 at 18 50 13

Then I uploaded one local video. The local version got greyed out and the row became not-expandable as well, but the "Upload to VideoPress" stayed visible and became active again as soon as the upload finished and the video started the "processing" status, what is not expected:

Screen Shot 2023-02-14 at 18 57 53

The button goes away after a refresh on the page. I checked `trunk` and the same behavior happens there as well, the button is back to active after the upload.

I also checked if the rows on the VideoPress library section were working as expected after the upload, and they do:

Screen Shot 2023-02-14 at 19 13 04

One thing that I noticed is that longer file names are truncated (as expected) but the information/error icon goes away with the rest of the name, so the video is greyed out but we can't say why:

Screen Shot 2023-02-14 at 18 59 14

This is also not related to this specific change, and we can deal with it on a future follow-up.

**Review by renatoagds — COMMENTED** [review]
Removing approval based on @lhkowalski comment

**Review by lhkowalski — CHANGES_REQUESTED** [review]
If the row is not collapsed, the upload button will show again after the upload. If the row is collapsed, then the fix works as expected.

We may need to trigger a row collapse to hide the button when it's clicked, or make sure the row is collapsed when the upload finishes.

**Comment by lhkowalski** [comment]
Tested the new changes that @renatoagds and the button went away. I am seeing an extra spacing where the button should be, but this can be fixed on a follow-up since it does not break things

Screen Shot 2023-02-15 at 08 57 18

In the image above, the first two items were files that I just uploaded, the third one was upload before. The extra spacing goes away on a page refresh.

**Review by lhkowalski — DISMISSED** [review]
We are good, the button is gone and the row can't be expanded. Left a comment about some spacing on the recent uploads, but I think it's minor and can be fixed on a follow-up in the future.

**Review by lhkowalski — APPROVED** [review]
Tested again and the tab closed as expected, and the extra spacing is gone 🚀

**Pull request merged**
