### PR TITLE
AI Crawler Control: introduce new feature & package

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This PR does a few things:

- It introduces a new Composer package, that can be required in different plugins.
- It requires that package in the Jetpack plugin.
- It introduces a module and its interface in the Jetpack plugin and the Jetpack dashboard.

The package does 2 things:

1. It adds lines to the site's `robots.txt` to encourage AI user agents to not crawl the site.
2. It creates a `/ai.txt` file, as proposed by [Spawning.ai](https://spawning.ai/ai-txt). It marks a full list of file extensions as not indexable by AI agents.

**To do**

- [ ] Create the mirror repo once we can confirm that this project goes forward, and if we're happy with the name.
- [x] Rely on the new `AI_Agents` class in `Automattic\Jetpack\Jetpack_Mu_Wpcom\Blog_Privacy`. Before we do so, we'll need to decide whether `ChatGPT-User` needs to be included on that list. @dereksmart Do you know?
- [ ] Adjust wording in the feature title and description.
- [ ] Create the support doc.
- [ ] Decide if we want to ship this feature as is, or if we want to offer full granularity on the list of excluded file extensions, just like the [Spawning.ai generator](https://spawning.ai/ai-txt) does. If so, how should such an interface look like in the Jetpack dashboard?
- [ ] Decide if the feature should live in another category in the Jetpack Settings (I added it to Jetpack > Settings > Traffic so far).
- [ ] Should we add a warning or workaround to ensure `/ai.txt` works on sites using plain permalinks.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* p1HpG7-rr7-p2

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Go to Jetpack > Settings > Traffic
* Enable the feature
    * *Note: the support doc doesn't exist yet, so the links to support won't work just yet.*
* Go to `yoursite.com/robots.txt` and notice the added lines about AI Agents.
* Go to `yoursite.com/ai.txt` and see the contents added by the package.

### CODE REVIEW

**Comment by dereksmart** [comment]
> Before we do so, we'll need to decide whether ChatGPT-User needs to be included on that list. @dereksmart Do you know?

The bot is not used for crawling or training purposes which is why I originally excluded it from this list. It is used to pull content from a site via a custom [GPT](https://chat.openai.com/gpts), formerly known as "[plugin](https://platform.openai.com/docs/plugins/)"- most commonly used for web browsing functionality. So for example: if this rule was applied on jetpack.com, and you asked one of these GPTs about the Jetpack plugin, it would not be able to pull content from jetpack.com to answer the question. 

image

**Comment by jeherve** [comment]
Thanks for the extra details! With that in mind, do you think I should remove it from my list too?

**Comment by dereksmart** [comment]
> Thanks for the extra details! With that in mind, do you think I should remove it from my list too?

Assuming the intent is to prevent the site content from being used in AI training, then it's not needed. You would want to exclude this bot if the intent is to "prevent the site's content from being discoverable at all". 

One cool thing about uses of this bot is that it will directly attribute the source when used in a plugin/GPT.

**Comment by jeherve** [comment]
Closing this for now, following the discussion here:
p1HpG7-rr7-p2#comment-70596

**Pull request closed without merging**
