### PR TITLE
Dialogue: allow line-breaks in front-end

### PR DESCRIPTION
**Pull request by retrofox**
_This PR is part of the [follow-up tasks](https://github.com/Automattic/jetpack/issues/18123) after merging `conversation`/`dialogue` blocks._

Fixes #

#### Changes proposed in this Pull Request:

* Dialogue: allow line-breaks in front-end

#### Testing instructions:

* Create a dialogue block
* Add text. Create a line-break (CMD + ENTER in Mac)

image

* Save
* Confirm that the line-break is rendered properly in the front-end

before  | after
------|------
image | image

#### Proposed changelog entry for your changes:

* Dialogue: allow line-breaks in front-end

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Marked it approved from the Crew POV. Please feel free to merge. I didn't tag it as such since it still has the Team Review status.

**Comment by retrofox** [comment]
<3

**Comment by retrofox** [comment]
> Marked it approved from the Crew POV. Please feel free to merge. I didn't tag it as such since it still has the Team Review status.

we can go ahead and merge it. The changes introduced isn't a big deal. Thanks 👍

**Comment by retrofox** [comment]
r218725-wpcom

**Comment by anomiex** [comment]
> **Proposed changelog entry for your changes:**
> * Dialogue: allow line-breaks in front-end

Thanks for the great changelog entry! Since Dialog and Conversation are first being added in 9.3, though, I think we can skip mentioning this fix.

(I'm trying to gently help people to better follow [docs/writing-a-good-changelog-entry.md](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md) to make it easier for us to prepare the changelog for releases 🙂)

**Pull request merged**
