### PR TITLE
update: VSCode debug instructions

### LINKED ISSUE #26983: Docs: Update VSCode debugger instructions
### Proposal

In newer versions of VSCode `workspaceRoot` has been renamed to `workspaceFolder`, so the instructions on how to setup VSCode debugger are not working.

Update the docs to mention that change.

### PR DESCRIPTION
**Pull request by kozer**
Fixes #26983

#### Changes proposed in this Pull Request:

* In newer versions of VSCode `workspaceRoot` has been renamed to `workspaceFolder`, so the instructions on how to set up VSCode debugger are not working.

Update the debugger instructions to reflect that.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Make sure you have an updated VSCode editor (as it is right now, the newest version is 1.72.2)
2. Follow the new isntructions
3. Make sure that the debugger stops correctly at a breakpoint

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
It looks like "workspaceFolder" was [introduced in vscode 1.17](https://code.visualstudio.com/updates/v1_17#_workspacefolder-in-launchjson-and-tasksjson), which was released in September **2017**. Should we just remove the example using workspaceRoot instead of having two large example blocks?

**Comment by kozer** [comment]
> It looks like "workspaceFolder" was [introduced in vscode 1.17](https://code.visualstudio.com/updates/v1_17#_workspacefolder-in-launchjson-and-tasksjson), which was released in September **2017**. Should we just remove the example using workspaceRoot instead of having two large example blocks?

Not sure about that. Maybe move it first and keep the other one as a mention just in case, without the code snippet?

**Comment by zaguiini** [comment]
How about we remove the old snippet and add a paragraph stating that the property was renamed? I do agree that it's been a while since the renaming happened, so probably not many people will come across the old property name.

**Comment by sejas** [comment]
I agree, `workspaceRoot` is deprecated, we can remove the old example.
> `${workspaceRoot} was deprecated in favor of ${workspaceFolder}`
https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

**Review by sejas — APPROVED** [review]
Looks good !!
Thanks for this change.

**Review by wojtekn — APPROVED** [review]

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
> @kozer added [Status] Needs Team Review and removed [Status] Needs Review labels [3 hours ago](https://github.com/Automattic/jetpack/pull/26984#event-7652715770)

FYI, this was probably not what you wanted to do. The "Needs Review" label is what brings the PR to the attention of Crew for the required approval, taking it off would remove it from our dashboards. "Needs Team Review" is for when you want some other team to review something before asking for Crew review.

**Comment by kozer** [comment]
Sorry about that! Still learning! Thanks for letting me know!

**Pull request merged**
