### PR TITLE
Story Block: Fix edit button used in block's toolbar

### PR DESCRIPTION
**Pull request by Tug**
This PR fixes an issue with the story block toolbar edit button that was reported in  https://github.com/Automattic/jetpack/pull/19628#issuecomment-830472184
More precisely, the `render` props of the `MediaUpload` component used in the story block's toolbar is being ignored and replaced with a button having the label "Select Media".

result

#### Changes proposed in this Pull Request:
This PR attempts to fix this issue by looking at the element rendered in MediaUpload. If it's a simple button containing only text then we can replace it with our own label, otherwise we try to reuse the rendered element. In this case we check if the element's `children` props is simply a `string`. There are other approaches we could take: for instance we could whitelist `EditButton` intances. I'm open to other ideas.
Most recent work on this component: https://github.com/Automattic/jetpack/pull/19644

#### Does this pull request change what data or activity we track or use?
no

## Testing instructions:

* Edit a post containing a story block using an account connected to WPCOM (so you have external media sources available such as Google Photos or Vexel)
* Select the story block
* Notice the pencil icon is used in the block toolbar to edit the media used for the story
* Try inserting one image, then multiple media
* Make sure the "pencil" button and the "Select Media" one are still working and and display the menu with different sources on click. Make sure selecting media from any sources work as expected

 Screenshot 2021-05-13 at 15 24 44

### Make sure there is no regressions:
* Set and unset the post featured image on a site connected to and disconnected from WordPress.com

* Image block: make sure the block edit button displays "Replace"

* Gallery block: makes sure the default button for adding media displays "Select Images"

* Gallery block: makes sure that for each image, the button to modify it displays "Select Image"

* Slideshow block: the button for adding media should display "Select Images"

### CODE REVIEW

**Comment by aforcier** [comment]
I gave this a try and it looks to have a few issues:

1. When there is only one slide in the story, a 'Replace image' text button appears next to the pencil icon:

Screen Shot 2021-05-11 at 10 35 54 AM

2. When clicking the pencil button (regardless of number of slides), the media already in the story are not pre-selected in the media library view, as they are when clicking the 'Select media' text button under the story

3. Also in the above case, at least on my (Jetpack) site the media selection seems to be in 'feature image' mode - the title is "Featured image," only one media item can be selected, and the confirmation button says "Set featured image" instead of "Select":

Screen Shot 2021-05-11 at 10 38 15 AM

I guess maybe the workaround is also setting it in 'feature image' mode in some way?

**Comment by Tug** [comment]
@aforcier Updated the PR, this should be fixed now

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Review by aforcier — APPROVED** [review]
Tests well for me now, on both Jetpack and WPcom 👍

**Comment by Tug** [comment]
Deployed to WPCOM with changeset ID 225846

**Pull request merged**
