### PR TITLE
Add default values for jetpack forms' CSS veriables

### PR DESCRIPTION
**Pull request by ice9js**
## Proposed changes:

This patch fixes the issue of layout shifts that occur on form elements after the page has loaded due to the delay before JS can run.

This is done by providing sensible defaults for our CSS variables as suggested by @jcheringer in #29140. Because the root cause was the delay before JS could run, not slow loading of the CSS itself, that PR is now obsolete.

This PR also removes the obnoxious blur effect on load which is no longer necessary for the same reason as described above.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

-

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Create a post with a contact form or forms.
- Test for either style variation: default, outlined and animated.
- Publish the post.
- When you view the public post, the contact form blocks should no longer be blurred while they're loading.
- While the page is loading, the form inputs and labels should also 'not shift violently'.

### CODE REVIEW

**Review by jcheringer — APPROVED** [review]
LGTM!

**Review by sdixon194 — APPROVED** [review]

**Comment by jcheringer** [comment]
@samiff, it'd be great if we could include this PR in the current (11.9) release.
Would it be possible?

**Comment by samiff** [comment]
> @samiff, it'd be great if we could include this PR in the current (11.9) release.

Will do 👍

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-11.9` in 1ef18ef2940633f20330c9b54a7a86e9586011c9

Released `automattic/jetpack-forms` v0.6.0.1: https://packagist.org/packages/automattic/jetpack-forms#v0.6.0.1

New package version consumed in `jetpack/branch-11.9` via cf6c5d6ff8a2a9829da6e0f28aa6e585efdde6fa

**Pull request merged**
