### PR TITLE
Untangle: Prevent Tools menu override for the wp-admin interface

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/dotcom-forge/issues/5283

## Proposed changes:

This PR disables the Tools menu re-registration for the wp-admin interface. 

| Before | After | 
| --- | --- |
| Screenshot 2024-01-24 at 2 24 13 PM | Screenshot 2024-01-24 at 2 25 13 PM|

Note: There is an issue where the styles are not aligned with core. This is due to the Calypso component `Card` ([src](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/card/style.scss#L5)) overriding the styles. We can address this in a later PR.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Head to Settings → Hosting Configuration.
- Scroll to the Admin interface style section, and select Classic style.
- Refresh the page if needed.
- Ensure that the Tools menu is updated as shown above.

### CODE REVIEW

**Review by okmttdhr — DISMISSED** [review]
Tested and looks good to me 🚀

**Comment by taipeicoder** [comment]
> Tested and looks good to me 🚀

Thanks for the review @okmttdhr. Looking at other PRs, I think we are supposed to modify `class-atomic-admin-menu.php' if possible, since the file will only be loaded for Atomic sites. Could you review again?

**Review by okmttdhr — DISMISSED** [review]
Tested and confirmed;

- The Tools menu is disabled on Atomic with the wp-admin interface
Screenshot 2024-01-24 at 17 03 29

- The Tools menu is enabled on Atomic without the wp-admin interface
Screenshot 2024-01-24 at 17 03 37

**Comment by taipeicoder** [comment]
Updated the code so that the other menu items in Tools are not affected. So this PR is just about bringing back the Available Tools to the Tools menu.

**Review by fushar — APPROVED** [review]
Nicely done 👍 

|Before|After|Vanilla WP|
|-|-|-|
|image|image|image|

> Note: There is an issue where the styles are not aligned with core. This is due to the Calypso component Card ([src](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/card/style.scss#L5)) overriding the styles. We can address this in a later PR.

☝️ I don't see any styling issues.

**Comment by taipeicoder** [comment]
> Nicely done 👍
> 
> Before	After	Vanilla WP
> image	image	image
> > Note: There is an issue where the styles are not aligned with core. This is due to the Calypso component Card ([src](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/card/style.scss#L5)) overriding the styles. We can address this in a later PR.
> 
> ☝️ I don't see any styling issues.

Interesting, I can't reproduce it on my end anymore either...

**Pull request merged**
