### PR TITLE
Increase timeout of license activation request from 10 to 30 seconds

### PR DESCRIPTION
**Pull request by rcanepa**
Asana card: 1201096622142517-as-1201400491645539

#### Changes proposed in this Pull Request:

* Increase the timeout of the request that triggers the activation of a product via license key. This is particularly important for Jetpack Complete, which activation requires some extra work that is not always completed in under 10 seconds (you can read more about this in [here](p1637846404079400-slack-C82FZ5T4G) and [here](1201096622142517-as-1201400491645539)).

**Note**: this is a workaround until we find a proper solution on the WPCOM that decreases the activation time for Jetpack Complete (which might not happen before the 10.4 gets released).

#### Jetpack product discussion

* Project Thread: p1HpG7-cSg-p2.
* This is a known issue described in p1HpG7-dIr-p2.

#### Does this pull request change what data or activity we track or use?

* Not at all.

#### Testing instructions:

* Spin up a site using this Jetpack branch.
* Connect Jetpack to your A8C WordPress.com account.
* Enable the A8c Proxy.
* Go to https://cloud.jetpack.com/pricing.
* Select Jetpack Complete.
* Complete checkout.
* On the "Thank you for purchase!" page, just stop there.. (Don't enter a site URL in the input box).
* On your site, visit `/wp-admin/admin.php?page=jetpack#/license/activation`.
* Open the Network section of the JS Console.
* Enter the license key associated with your Jetpack Complete purchase (you can get it from SA).
* Activate the product.
* Once the activation finishes, do not refresh the page.
* Verify how long did the `attach_licenses` request take to complete. If it took more than 10 seconds, that means that the timeout was effectively increased.
* Click on Jetpack > Dashboard (sidebar).
* Click on the My Plan tab.
* Verify that you see Jetpack Complete in the My Plan section.
* Verify that you see `Instant search and filtering` card just below that.
* Go to Jetpack > Settings (sidebar).
* Click on the Performace tab.
* Verify that Search and Instant Search Experience are enabled.

Screen Shot 2021-11-30 at 10 42 29

### CODE REVIEW

**Comment by rcanepa** [comment]
@jeherve, is this a reasonable change if we don't manage to fix the issue on the WPCOM side before the release of 10.4?

**Review by vitozev — APPROVED** [review]
IMPO, it's an acceptable solution as it will increase the timeout of the `jetpack.attachLicense` call only and won't have any side effects.

However, it should be considered as temporary solution and we'll have to identify the root cause of the issue. I'll keep looking into that in the following days.

**Comment by sdixon194** [comment]
@rcanepa This works for me (needs a merge with master) - we have a week for the Beta though. If you suspect there might be a solution from the wpcom side prior to release, we could hold off on cherry picking if this might get reverted later. Otherwise, we can go ahead with it.

**Comment by rcanepa** [comment]
> @rcanepa This works for me (needs a merge with master) - we have a week for the Beta though. If you suspect there might be a solution from the wpcom side prior to release, we could hold off on cherry picking if this might get reverted later. Otherwise, we can go ahead with it.

I'll wait until Monday (one day before the release), and if we haven't found a solution on the WPCOM side, I'll merge the PR to include it in version 10.4. How does it sound?

**Comment by sdixon194** [comment]
> I'll wait until Monday (one day before the release), and if we haven't found a solution on the WPCOM side, I'll merge the PR to include it in version 10.4. How does it sound?

Works for me! Just give a ping if something changes.

**Comment by rcanepa** [comment]
> Works for me! Just give a ping if something changes.

Hey @sdixon194 👋 
We will need more time to find out what's going on with Jetpack Complete activation process, so we will have to merge this change (I already updated the PR).

**Review by sdixon194 — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to release branch in c1a11c43e358a6038f1872489c9da90f0f36c792

**Pull request merged**
