### PR TITLE
Pinterest: soft-remove block in favor of the core Pinterest embed

### LINKED ISSUE #22223: Pinterest Block: deprecate the block as the embed has now been added to Core
WordPress 5.9 will ship with its own Pinterest embed:

- https://core.trac.wordpress.org/ticket/53448

We may consider deprecating our block for folks running WP 5.9+

cc @pento who worked on the core implementation as well as the Jetpack block.

***********

Primary issue: #21322

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #22223

## Proposed changes:

We cannot remove the block entirely; doing so we break existing Jetpack Pinterest embeds since they only display a link at that point.

Instead, we will:

- Keep the Jetpack block around
- Disable inserting new Jetpack Pinterest blocks
- Disable block transforms to Jetpack Pinterest blocks
- Disable editing existing Jetpack Pinterest blocks

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

**Pinterest test URLs**

```
https://www.pinterest.com/pin/307722587052205242/
https://hu.pinterest.com/pin/307722587052205242/
https://hu.pinterest.com/saltandlavender/
https://www.pinterest.com/saltandlavender/
https://www.pinterest.com/saltandlavender/dinner-recipes/
```

* Start with a site that runs Jetpack stable or `trunk`.
* Go to Posts > Add New
* Look for the Jetpack Pinterest block (colored green)
* Add a block, publish your post.
* Apply this branch.
* Edit the post
    * The existing Pinterest block should remain, but without a pencil "edit" icon.
 * Open the block inserter, search for "Pinterest"
    * Only one block should be available, the Core one.

### CODE REVIEW

**Review by monsieur-z — DISMISSED** [review]
Works as expected! 🚀

**Comment by monsieur-z** [comment]
I just noticed some JS tests are failing because they reference the deleted file.

**Comment by jeherve** [comment]
> I just noticed some JS tests are failing because they reference the deleted file.

I missed that one, sorry about that! Should be good now.

**Review by monsieur-z — APPROVED** [review]
Tests are passing now!

**Pull request merged**
