### PR TITLE
Enhance/Changing plans landing raster img to svg

### PR DESCRIPTION
**Pull request by jeffgolenski**
Fixes: https://github.com/Automattic/jetpack/issues/5947

We've switched all the images on the apps landing page, and need to follow through with that on the plans page. svg designed + added to match apps landing page. a11y added to svg and tested on mobile.

Before:
screen shot 2016-12-15 at 11 46 36 am

After:
screen shot 2016-12-30 at 1 55 45 pm

### CODE REVIEW

**Comment by dereksmart** [comment]
Changes look good except it's throwing a couple console warnings about the svg atts: 

screen shot 2017-01-02 at 1 54 37 pm

**Comment by jeffgolenski** [comment]
@dereksmart Those are both valid atts. https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

You think that has something to do with the react syntax though?

**Comment by dereksmart** [comment]
> You think that has something to do with the react syntax though?

Yep, `In React, all DOM properties and attributes (including event handlers) should be camelCased.` [#](https://facebook.github.io/react/docs/dom-elements.html)

Mind updating it?

**Comment by jeffgolenski** [comment]
@dereksmart sure thing derek. Good catch. inlined SVG code is kind of a pain in react. Let me know if you notice anything else!

**Comment by dereksmart** [comment]
Thanks Jeff, LGTM

**Comment by jeherve** [comment]
@dereksmart This should probably be cherry-picked to `branch-4.5`.

**Pull request merged**
