### PR TITLE
Backup: Transition from showing Plan and Connection status to relying on My Jetpack

### PR DESCRIPTION
**Pull request by oskosk**
Removes Plan and Connection status secions to favour the ones shown by My Jetpack 

#### Changes proposed in this Pull Request:

* Removes usage of MyPlan
* Removes MyPlan component file
* Removes usage of connection Status card and related code from the `useConection` hoook

#### After
image

image

image

#### Before

image

#### Testing instructions:
* Checkout this branch or [launch a Jurassic Ninja site this branch for the Backup plugin](https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=update/backup-for-my-jetpack&wp-debug-log&my-jetpack&no-jetpack)
* Go to the Backup menu item under Jetpack.
* Connect the site . No need for purchasing
* Back into the Backup page, confirm all looks good

### CODE REVIEW

**Comment by oskosk** [comment]
@nunyvega @jwebbdev it would be great if you two could keep an eye on this Pull Request frequently for when end up launching My Jetpack. I'll be updating it, keeping it up to date, etc.

**Comment by oskosk** [comment]
@keoshi can you validate this transition please?

**Review by keoshi — APPROVED** [review]
This is great and greatly reduces the complexity of the Backup page. Thank you for doing this, @oskosk !

**Review by nunyvega — APPROVED** [review]
I tested it and works as expected. 
It also looks better, great change 🥇

**Pull request merged**
