### PR TITLE
Build: Remove the extensions directly before building them fresh

### LINKED ISSUE #12019: Clean out old files on `yarn build-extensions`
`yarn build-extensions` doesn't wipe out `_inc/blocks` folder first (you'd have to manually run `yarn clean-extensions`) so you end up with old files around:

image

This could bring trouble when;
- Testing and file exists when it shouldn't
- When manually syncing to sandbox
- Possibly even when doing a release?

`yarn build-production` includes distclean, which cleans blocks.

### PR DESCRIPTION
**Pull request by kraftbj**
This helps to prevent abandoned files from sticking around between builds.
Fixes #12019

#### Changes proposed in this Pull Request:
* See above.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:
* Before patch, build Jetpack and add a random file to `_inc/blocks. Run `yarn build` and see the new file still there.
* After patch, repeat and confirm the random file is no longer present.

#### Proposed changelog entry for your changes:
* Build Tools: Improve our build tools to help prevent things from falling through the cracks.

### CODE REVIEW

**Comment by simison** [comment]
Context; I think the hope was that people would use just `yarn build` which already runs `yarn clean` which runs `clean-extensions`.

Since we didn't get Gulp-watching work with blocks-Webpack, folks are now running just `yarn build-extensions --watch` directly and here we are. :-)

So with this, we'll wipe out built extensions twice on `yarn build`. It's a fast process so prolly ok, if this fixes an issue. 👍 

Hope we can get rid of all the code driving `yarn build:watch` in future and just rely on Webpack's internals and have one canonical `yarn build --watch`.

**Review by simison — DISMISSED** [review]

**Comment by simison** [comment]
Hmm, actually you could move `yarn clean-client` directly to `build-client` and remove the `client` task. That way extensions cleaner would run always just once?

**Comment by sirreal** [comment]
Is `build-extensions` used for the automated WPCOM build? We don't want to remove the built files there.

I don't think we want to include "stale" built files in Jetpack release, but has this been a problem?

**Comment by ockham** [comment]
> Hmm, actually you could move `yarn clean-client` directly to `build-client` and remove the `client` task. That way extensions cleaner would run always just once?

Yeah, symmetry is a good guiding principle here :+1:

**Comment by kraftbj** [comment]
> I don't think we want to include "stale" built files in Jetpack release, but has this been a problem?

Not specifically in blocks, afaik, but we've had it happen before with other files. As a defensive measure, I would like to ensure it is harder to ship something unintentionally.

**Comment by kraftbj** [comment]
Updated per @simison's suggestions. The WP.com side test is failing because, as @sirreal pointed out, this would end up cleaning out files on the WP.com side. I think this is, all in all, good since that would be an unexpected delta between sets of Jetpack blocks. The hold up is the script on the WP.com side does not have a mech in place to `svn rm` the deleted files.

**Comment by kraftbj** [comment]
Marking as blocked since there are issues with removing built files on the wp.com side. See more at the thread at:
C8A2EUTB9/p1558624532441200-slack-jetpack-gutenberg

**Pull request closed without merging**
