### PR TITLE
Pocket Casts: Add Pocket Casts as oEmbed provider.

### PR DESCRIPTION
**Pull request by yansern**
#### Changes proposed in this Pull Request:

* This PR adds Pocket Casts to trusted list of oEmbed providers.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
p1659418592115089/1659075657.456929-slack-C0371DL0ZQS
1060-gh-Automattic/wpcomsh

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

**Frontend:**
- Open Block Editor.
- Paste the following beta Pocket Casts link:
  - `https://pcast.pocketcasts.net/drtlaf9s?random_string_to_bust_cache`
  - The oEmbed content should show up.
- Paste the following production Pocket Casts link:
  - `https://pca.st/ydy2e635?random_string_to_bust_cache`
  - The oEmbed content should show up.

**Unit test:**

Setup:
- Run `jetpack docker update-core-unit-tests`
- Due to WP 6.0.1 incompatibility, additionally run this (reference: p1660080203861559-slack-CBG1CP4EN and p1660080203861559-slack-CBG1CP4EN):
   - `jetpack docker sh`
   - `cd /tmp/wordpress-develop/tests/phpunit/includes`
   - `svn up -r r53748`
   - `exit`

Test:
- Run `jetpack docker phpunit -- --filter=WP_Test_Jetpack_Shortcodes_PocketCasts`

If the unit test is not successful, run `jetpack docker tail` and paste what you see.

image

### CODE REVIEW

**Review by mashikag — DISMISSED** [review]
LGTM! 🚀

**Review by jeherve — DISMISSED** [review]
This looks good. Could you add some tests to cover this, so we ensure this keeps working in the future? You can add them in `projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.others.php` alongside the other tests.

Thank you!

**Comment by yansern** [comment]
Hi @jeherve, I've added some unit tests although it is unconventional in the sense that PocketCasts actually do not have shortcodes (unlike other unit tests in the folder where they are mostly testing shortcode conversions). So what I'm testing is the output of the embed content ensuring it contains certain strings.

For more context, the intention of this PR is to add PocketCasts as trusted oEmbed provider for Atomic & self-hosted Jetpack sites to fix issues where kses is stripping off the sandbox html attribute (context: p1659075657456929-slack-C0371DL0ZQS) and thus crippling the functionality of the embed block.

Adding to Jetpack is also a temporary solution until WP 6.1.0 is released ([on Oct 25](https://make.wordpress.org/core/2022/06/23/wordpress-6-1-planning-roundup/)) where PocketCasts will be officially added [as a trusted oEmbed in Core](https://core.trac.wordpress.org/changeset/53744).

**Comment by kraftbj** [comment]
Thanks for the added context. I'm changing up this a bit to only load when Core isn't providing the oEmbed and adding notes to remove when 6.1 is the minimum version. I'm leaving the unit tests as they are since they'll also help confirm that Core is handling it when on WP trunk.

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
