### PR TITLE
AI Assistant: Group options under `Write with AI`

### LINKED ISSUE #31039: AI Assistant: Add all options except from translation and tone under Write with AI
Add all options to create/modify text except for tone and translations under Write with AI

Image

### PR DESCRIPTION
**Pull request by renatoagds**
Closes #31039 

## Proposed changes:

* Move options under `Write with AI`.
* Improve UX and texts into `Write with AI`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

N/A

## Testing instructions:

* Insert `AI Assistant`.
* You should see only `Write with AI` option.
* It should not appear if has content in the block and the options should be context based.

### Demo

https://github.com/Automattic/jetpack/assets/1663717/bee05af0-7fcb-4f19-ab83-cad30759f95a

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
The menu looks very nice. How the options get organized feels more comfortable IMO.

image

The sections (divided by lines) are not a typical pattern. At least I haven't seen it often except in the block options menu.

**Comment by renatoagds** [comment]
We discussed at the slack about the group and lines and will go with it: p1685473425881249/1685456086.688509-slack-C054LN8RNVA

**Review by retrofox — APPROVED** [review]
LGTM

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by kraftbj** [comment]
[monthly/branch-2023-05-29 729104cf8f]

**Pull request merged**
