### PR TITLE
ci: Fix coverage munger with no coverage

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

If the PR has no PHP and/or JS coverage data, the `process-coverage.sh` script should do the right thing instead of failing.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1731442301581969/1731441986.548139-slack-CDLH4C1UZ

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Make a PR based on this one with changes only in packages/jetpack-mu-wpcom or only in js-packages/eslint-changed. Coverage artifacts should still be generated correctly.
  * [x] https://github.com/Automattic/jetpack/actions/runs/11805582535/job/32888384027?pr=40151
  * [x] https://github.com/Automattic/jetpack/actions/runs/11805591885/job/32888425001?pr=40152

### CODE REVIEW

**Comment by tbradsha** [comment]
The output doesn't seem to match what I'd expect (I wasn't expecting any groups or composer install and expected a `No ___ coverage files found!` message):

image

**Comment by anomiex** [comment]
Where'd you look to get that screenshot? On this PR it runs the tests for everything because the process-coverage script is modified. PRs like #40151 or #40152 are what you'd want to look at.

**Comment by tbradsha** [comment]
I created a test PR based on your branch: #40153

Here's the run: https://github.com/Automattic/jetpack/actions/runs/11805633978/job/32888559879

I just tried changing my PR's base to your branch to see if that works.

That said, even in your PRs are you intending to have content in all the output groups? Nothing is echoed inside the `Creating PHP coverage summary`, `Creating JS coverage summary`, and `Combining coverage summaries` groups.

**Review by tbradsha — APPROVED** [review]
Ignoring my PR (which is tainted by its base), your runs look like the code indicates. But the groups are mostly empty when it does something, which makes it look like there's something wrong. Not a blocker.

**Comment by anomiex** [comment]
Yeah, the commands run don't seem to output anything on successful operation. 🤷

**Pull request merged**
