### PR TITLE
Use minified version of videopress-token-bridge

### PR DESCRIPTION
**Pull request by thedebian**
Fixes Automattic/greenhouse#1260

#### Changes proposed in this Pull Request:

This PR allows videopress-token-bridge to be minified instead of including the normal version.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* On a Jetpack plan with VideoPress enabled
* Update projects/packages/assets/src/class-assets.php get_file_url_for_environment by setting $path to $min_path around line 147
* Go to /wp-admin/upload.php and upload a video or use an existing one uploaded to VideoPress
* Edit the video and set it to private
* Create a new post and include the private video
* :white_check_mark: The video should work
* Save and preview
* :white_check_mark: The video should work
* Publish the post
* Go to the post page
* :white_check_mark: The video should work
* Test your post in incognito mode
* :white_check_mark: The private video message should appear
* Go back to /wp-admin/upload.php and make the video public
* Go to your post page
* :white_check_mark: The video should work
* Test your post in incognito mode
* :white_check_mark: The video should work
* CTRL+U on your post page
* Search for token-bridge
* :white_check_mark: The ".min.js" file should be included (in _inc)

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Review by jgcaruso — DISMISSED** [review]
Tests well for me as well.

One thing I noticed when doing a look around to see if there were any other examples of this is the 2 instances of `videopress-token-bridge.min.js` that are in here have 2 different variables being passed for `version`. One is an int, the other is `JETPACK__VERSION`. I think we should make these the same so that 2 different scripts don't get requested and downloaded. Not sure which one is more correct, but `JETPACK__VERSION` seems the easiest to use since it doesn't require manual updating on our end when there are code changes.

This is seen when in the editor.

Screen Shot 2022-08-02 at 3 58 05 PM

**Comment by thedebian** [comment]
> One thing I noticed when doing a look around to see if there were any other examples of this is the 2 instances of `videopress-token-bridge.min.js` that are in here have 2 different variables being passed for `version`. One is an int, the other is `JETPACK__VERSION`. I think we should make these the same so that 2 different scripts don't get requested and downloaded. Not sure which one is more correct, but `JETPACK__VERSION` seems the easiest to use since it doesn't require manual updating on our end when there are code changes.

Nice catch, I updated the PR, it should be good to go after review now :)

**Review by jeherve — COMMENTED** [review]
> I think we should make these the same so that 2 different scripts don't get requested and downloaded. Not sure which one is more correct, but JETPACK__VERSION seems the easiest to use since it doesn't require manual updating on our end when there are code changes.

That's a good idea, and the change looks good. I wonder if we should take this opportunity to get rid of `VERSION` entirely right now, and use `JETPACK__VERSION` for all other assets in that file?

**Comment by thedebian** [comment]
Here is the complementary test procedure:

* Go to /wp-admin
* CMD+U
* Look for videopress-admin-css
* :white_check_mark: The href should use the Jetpack version
* Go to /wp-admin/upload.php
* CMD+U
* Look for videopress-plupload
* :white_check_mark: The src should use the Jetpack version
* Look for videopress-uploader
* :white_check_mark: The src should use the Jetpack version
* Look for media-video-widget-extensions
* :white_check_mark: The src should use the Jetpack version
* Create or edit a post with the block editor
* CMD+U
* Look for videopress-editor-ui
* :white_check_mark: The href should use the Jetpack version
* Look for videopress-editor-view
* :white_check_mark: The src should use the Jetpack version

**Review by pgk — APPROVED** [review]
lgtm tested well!

**Review by jeherve — APPROVED** [review]

**Comment by thedebian** [comment]
r250519-wpcom

**Comment by leogermani** [comment]
Hi @thedebian ,

This happened at the very same time we are moving this script to the videopress package. See https://github.com/Automattic/jetpack/pull/25412

In the process, we are temporarily not using the minified version again, but I've already created an issue for us to address this: 1202184803119163-as-1202764755494536

**Comment by leogermani** [comment]
@thedebian closing the loop. This was addressed here: https://github.com/Automattic/jetpack/pull/25683

**Pull request merged**
