### PR TITLE
Backup: Update references from Jetpack Backup to Jetpack VaultPress Backup

### PR DESCRIPTION
**Pull request by Initsogar**
#### Changes proposed in this Pull Request:

* Update Backup plugin file to rename `Jetpack Backup` -> `Jetpack VaultPress Backup`
* Update Backup package UI references from `Jetpack Backup` -> `Jetpack VaultPress Backup`
* Update Backup menu title from `Backup` -> `VaultPress Backup`

#### Screenshots
| Content | Screenshot |
| --- | --- |
| Plugins list page | image |
| Footer | image |
| Pricing card | image |
| Admin Jetpack Submenu | image |
| Page title | image |  

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

* p1HpG7-j2p-p2#comment-58598
* 1202586245449203-as-1203367050452965/f

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Launch a [JN site with Backup standalone and this branch](https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=update/vaultpress-backup-rename&wp-debug-log&nojetpack).
* Navigate to `Jetpack` admin menu option.
* You should see:
  * The **pricing card** product name updated from `Jetpack Backup` -> `Jetpack VaultPress Backup`.
  * The **admin Jetpack submenu** from `Backup` -> `VaultPress Backup`.
  * The **page title** in your browser from `Jetpack Backup` -> `Jetpack VaultPress Backup`.
 * Click on `Get Jetpack VaultPress Backup` and purchase a `Jetpack VaultPress Backup` plan.
  * You should see the **footer** changed from `Jetpack Backup` to `Jetpack VaultPress Backup`. 
* Navigate to `Plugins`.
* You should see `Jetpack VaultPress Backup` plugin active instead of `Jetpack Backup` in the **plugins listing page**.

### CODE REVIEW

**Review by jwebbdev — DISMISSED** [review]
Looks good

**Comment by Initsogar** [comment]
Just made a few text adjustments (CTA and Footer) after reviewing changes proposed in 1TSbd5DtFkvvloCXtap3Yk-fi-2899%3A1360&t=D0cPhSksyMMyHyf7-0. We will address assets/images changes in a new PR once they are confirmed. Discussion ongoing on p1HpG7-jcD-p2.

@jwebbdev could you do a final review?

**Comment by jwebbdev** [comment]
The "Subscription Needed" screen that's available when a site is connected, but without a subscription has 'Backup' by itself.

Screen Shot 2022-11-18 at 5 11 55 PM

The footer text of `An Automattic Airline` hits kind of odd without a mention of Jetpack.

Screen Shot 2022-11-18 at 5 12 09 PM

All the proposed changes in the PR are in place, so if we want to get them in and continue from there (I know we have some icons still to come in a future PR as well) that seems reasonable.

**Review by jwebbdev — APPROVED** [review]
Left comments, but I think what's in there is fine to merge, and we can keep moving forward if we want to include more changes.

**Pull request merged**
