### PR TITLE
Implement a form responses inbox

### PR DESCRIPTION
**Pull request by ice9js**
#### Changes proposed in this Pull Request:

This is a development branch including the changes necessary to implement the new responses inbox. It's not meant to be merged - it'll be split into multiple smaller PRs -  and only to serve as a single place where changes can easily be tested while the work is moving along.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pcsBup-hX-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

- View the new form responses page at `/wp-admin/admin.php?page=jetpack#/forms`.

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Super nice Kuba!!! 😍😍😍  
Great start!

Here are a few notes - not necessarily need to be addressed in this PR, just posting these here to keep them documented... more finetuning notes coming soon... 

## Enhancements

- [ ] Left Table: Full row should be clickable to switch content in the right column (clickable area between the lines - besides the source link and checkbox of course)
- [x] Left Table: The background color of the “selected row” needs to have the same background color as the right column area.
- [ ] Left Table: Row should have a “hover” state
- [ ] Source column should show only the URL part behind “last /“ - on hover, it shows the full URL
- [ ] Empty state - the empty table area is “too short” - would be a bit better to have some "empty space" that gives a hint of the page structure of that view. (in the end, we will replace that view anyways with a landing page)
- [x] “Form Responses” headline styling => “font-weight: 700” (compare with “My Jetpack” view)
- [x] Message Input field does not support “paragraph” formatting in the data field. Everything is compressed into one line.


## Bugs

- [x] Right Column: Data field of the “Radio button” blocks are shown twice!
- [ ] Check icon inside checkbox is “off”.
- [x] Message data field seems to have issues when [ ] is used in the text. 
- [x] Tried to customize the contact form, added an additional block (name block), changed the label, and got for this new input field a data duplication in the right column


## Not implemented, yet

- [x] Gravatar image seems not to be supported yet.
- [ ] Bulk Actions don’t work, yet?
- [x] Footer
- [ ] Responsive behaviour
- [ ] Filter feature
- [ ] Export feature


## Nice to have:

- [ ] Keyboard support for arrow keys to browse the table

**Comment by oskosk** [comment]
There's a problem with this approach. This React-based UI (this admin dashboard) is not present in WordPress.com sites. Only on sites carrying the Jetpack plugin.

**Comment by ice9js** [comment]
>There's a problem with this approach. This React-based UI (this admin dashboard) is not present in WordPress.com sites. Only on sites carrying the Jetpack plugin.

I see. The view is pretty self-contained though so it's still easy to move around if need be.
One of the things I noticed is how the Jetpack search page has its UI implemented as a whole separate package in `projects/packages/search`. Would you suggest we do a similar thing for forms and move it over there when we circle back around to it? And how would that work for the backend - should it be moved too or left alone?

**Comment by ice9js** [comment]
Closing the PR as the work has been split up and already made it through to Jetpack in a bunch of other PRs.

**Pull request closed without merging**
