### PR TITLE
A4A Client plugin: tweak readme

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

Let's make some final changes to the readme:

- Apply changes mentioned in pfunGA-1Ka-p2#comment-3125
- Add mention of our ToS

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* pfunGA-1Ka-p2#comment-3125

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Check wording for typos.

### CODE REVIEW

**Comment by jeffgolenski** [comment]
Hey @jeherve!

When I follow the JN test instructions and spin up a new JN site via this PR, I'm met with this text when I click "View details" witin the A4A Client plugin on `/wp-admin/plugins.php` - any ideas on how to see the real content and imagery? 

CleanShot 2024-06-11 at 11 52 20

**Comment by jeherve** [comment]
Since the plugin is not available on the directory yet, you won't be able to see the changes in wp-admin.

A good way to preview the changes would be to copy the contents of the readme from here:
https://raw.githubusercontent.com/Automattic/jetpack/daf6609bc55893cc0ff782841b4464d9cd82b705/projects/plugins/automattic-for-agencies-client/readme.txt

To this page, where you can preview plugin readmes:
https://wpreadme.com/

**Comment by jeffgolenski** [comment]
@jeherve TIL! What a great tool! Just a couple of adjustments which I missed in the google doc. 

1. The opening paragraph has 2 redundant links. Remove the first link.

Currently:
`[Automattic for Agencies](https://automattic.com/for/agencies/) is a new agency program that combines the best of Woo, WordPress.com, Jetpack, and Pressable under one roof. [Learn more about Automattic for Agencies](https://automattic.com/for-agencies/).`

Should be
`Automattic for Agencies is a new agency program that combines the best of Woo, WordPress.com, Jetpack, and Pressable under one roof. [Learn more about Automattic for Agencies](https://automattic.com/for-agencies/).`

2. Add periods to the list items

Currently: 
- With plugin updates across the sites you manage in just a few clicks
- Downtime monitoring so you’ll instantly know if a client’s site needs attention
- And more to come.

Should be: 
- With plugin updates across the sites you manage in just a few clicks.
- Downtime monitoring so you’ll instantly know if a client’s site needs attention.
- And more to come.

3. "To remove a site from Automattic for Agencies" should become a list:

Currently:
`To remove a site from Automattic for Agencies, simply navigate to Plugins > Installed Plugins, within wp-admin for the site you want to remove. Find the Automattic for Agencies plugin and click “Deactivate.” You’ll be prompted to confirm. Once deactivated, your site will be removed from Automattic for Agencies.`

Should be:
- To remove a site from Automattic for Agencies, simply navigate to Plugins > Installed Plugins, within wp-admin of the site you want to remove.
- Find the Automattic for Agencies plugin and click “Deactivate.”
- You’ll be prompted to confirm. Once deactivated, your site will be removed from Automattic for Agencies.`

cc @rcanepa for a second pair of eyes as well. Thanks Jer!

**Comment by jeherve** [comment]
👍 Done in 2b408d2e2f84bdc700d24ec6c2d8e7919da57d84

**Review by jeffgolenski — APPROVED** [review]
Send it! (After Renzo gets a chance to look at it for review)

**Review by rcanepa — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
