### PR TITLE
Fix URL parsing issues / cache contamination

### PR DESCRIPTION
**Pull request by thingalon**
When a requested URL has a `//` after the hostname, GET parameters may be ignored, causing cache contamination across URLs.

This PR fixes the places where partial URLs are parsed using `parse_url`, ensuring they are read properly.

Fixes p3btAN-1Sl-p2

#### Changes proposed in this Pull Request:
* Use `$_SERVER['QUERY_STRING']` when checking if GET params exist, and
* Introduce a new wrapper for `parse_url` which deals with partial URLs that may have double-slashes in them.

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Turn on wp-super-cache, and clear your cache.
* Run `curl http://your-domain.com//?s=1223`
* Visit `http://your-domain.com/` as a non-logged in user, and observe that the search results page is served.
* Turn on the "Tracking Parameters" feature in the Advanced tab.
* Run `curl 'http://your-domain.com//?s=1&mtm_cid=123'`. Observe the cache time in the footer.
* Run `curl 'http://your-domain.com//?s=1&mtm_cid=12'`. Observe the cache time in the footer, and ensure it is unchanged (i.e.: cached version changed, as the tracking param is ignored).

### CODE REVIEW

**Comment by thingalon** [comment]
Note: There are linting issues in this file, as we have not fully fixed all linting issues in the WPSC codebase yet (I want to do that after getting tests on their feet). The new wpsc_is_https method takes an existing check, and turns it into something that can be used from multiple places. We'll tidy up the lint warnings from that code in a future PR.

**Comment by kraftbj** [comment]
Merged with `trunk` to pick up an upstream change to the infra that was needed for approving the PR. The changes that I looked at match what is in the file and the rest read well, but didn't test yet. 

Did you go with the partial URL reconstruction function route to avoid too many changes to the existing code at this time?

**Review by kraftbj — APPROVED** [review]
Functional testing worked for me.

**Comment by thingalon** [comment]
> Did you go with the partial URL reconstruction function route to avoid too many changes to the existing code at this time?

Yes, I did. For the code that deals with stripping tracking GET params out of the URL. That would require a lot more refactoring otherwise, which I'm reluctant to do for a Friday security fix before the tests are in place.

Though for the check whether there are get params at all, i went with your suggested `QUERY_STRING` approach, since IMHO it's cleaner.

**Pull request merged**
