### PR TITLE
API: Publicly Include if Site is WP.com Atomic 

### PR DESCRIPTION
**Pull request by Aurorum**
Part of Automattic/wp-calypso#52979 

#### Changes proposed in this Pull Request:

* It'd be really helpful as part of Automattic/wp-calypso#52979  to be able to check if a site is an Atomic one through the API without being part of that site. Currently, it's possible to see if the site is connected through Jetpack (see below) but also returns true for Atomic sites.

Screenshot 2021-05-23 at 12 35 59

As a result, something like this, which is seeking to distinguish self-hosted and WP.com sites, would mark an Atomic site as a self-hosted one rather a WP.com one.

https://github.com/Automattic/wp-calypso/blob/6e07aa3b8d51654e84c530749ebce26f4a34f6a5/client/me/help/help-contact-form/index.jsx#L324-L329

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

I'd really appreciate some help with this because I'm struggling to test this; looking at previous examples, it seems that testing changes to this endpoint requires creating a WP.com diff, which I'm unable to do. It seems that a `is_wpcom_atomic()` function is already used though, so I'm hoping this won't be too difficult to implement. 

https://github.com/Automattic/jetpack/blob/83b3f239b03e3d0a55d8fe6fd47ff823a2721b6b/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L600-L602

The issue is that it's part of `options`, and that is hidden for users without access to the site which is understandable because it contains other sensitive details. Instead, I'm hoping for this information to be available. 

The endpoint involved is `v1.1/sites/example.com`. Any advice would be greatly appreciated.

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]
Thanks for specifying "WP.com Atomic" vs simply "Atomic". It's been easy to forget there are non-WP.com sites on the Atomic platform.

**Comment by kraftbj** [comment]
Marked as needs review since I don't have time at the moment to handle the WP.com-diff side of things.

**Comment by jeherve** [comment]
Wouldn't it be enough to rely on the existing `is_wpcom_atomic` option?
https://github.com/Automattic/jetpack/blob/f5a516818c75162d94b0004a8cff553d68aa0a05/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L142

**Review by jeherve — CHANGES_REQUESTED** [review]
For internal reference, matching WordPress.com diff: D61769-code

I believe we would also need to update the `is_wpcom_atomic` method in `projects/plugins/jetpack/sal/class.json-api-site-base.php`, and have it detect Atomic status there. It could be something like this for example:

```diff
diff --git a/projects/plugins/jetpack/sal/class.json-api-site-base.php b/projects/plugins/jetpack/sal/class.json-api-site-base.php
index d73a07d5a1..d605eb08b7 100644
--- a/projects/plugins/jetpack/sal/class.json-api-site-base.php
+++ b/projects/plugins/jetpack/sal/class.json-api-site-base.php
@@ -167,8 +167,13 @@ abstract class SAL_Site {
 		return 0; // WPForTeams\Constants\NO_ORG_ID not loaded.
 	}
 
+	/**
+	 * Detect whether a site is a WordPress.com on Atomic site.
+	 *
+	 * @return bool
+	 */
 	public function is_wpcom_atomic() {
-		return false;
+		return jetpack_is_atomic_site();
 	}
 
 	public function is_wpcom_store() {
```

**Comment by jeherve** [comment]
Internal reference: p1621858815214200-slack-CBG1CP4EN

**Comment by Aurorum** [comment]
Many thanks, I've made that change now! :)

**Comment by jeherve** [comment]
> The issue is that it's part of options, and that is hidden for users without access to the site which is understandable because it contains other sensitive details. Instead, I'm hoping for this information to be available.

As I'm looking through this again, I wonder if it would be an option to use the existing option (available when doing authenticated requests) instead of adding a new one? Since the requests are done in Calypso, they should already be authenticated with the user, so the option should be available if the user is a member of a site. 
If they are not a member of that site they won't see the option, but in that case they shouldn't be asking for support for that site in the first place, I suppose.

**Comment by Aurorum** [comment]
Yes, you're right. In principle with what I'm developing, the only situation where this could be useful is if an Atomic site owner has lost access to their account and has created a new one in order to seek help. 

Although, I have no clue what the statistics are on that, it's probably safe to say that it's a very low number. Regardless, I personally think it'd be preferable to have a flawless experience where there's no risk of misinforming volunteers in the Forums regardless of the potential scenario. My fear is that if there's even one scenario where the information could be wrong, volunteers might need to feel like every submission through the Help form needs to be manually checked.

**Comment by jeherve** [comment]
> the only situation where this could be useful is if an Atomic site owner has lost access to their account and has created a new one in order to seek help.

I'm honestly not sure this is worth supporting. If one loses access to their account, we already have a process to help folks get help regain access to their account; I think it would be best to focus on this.

**Comment by Aurorum** [comment]
This change would allow the focus on the existing Account Recovery procedure! Perhaps I should try explaining the flow, then let me know what you think. 

**Scenario:**

1. A user with an Atomic site loses access to their account *or* logs into the wrong account.
2. In their confusion, they create a new account and seek help. We know that they should follow the Account Recovery process, but in practise, many people don't; there are [3000 threads](https://wordpress.com/forums/topic-tag/account-recovery/) related to Account Recovery and [1600 threads](https://wordpress.com/forums/topic-tag/other-user/) related to the user signing into the wrong account.

**Without this PR:**

1. The user enters their URL into the Help form. 
2. They are told that their (WordPress.com) site is not hosted on WordPress.com.

Screenshot 2021-05-22 at 10 38 04

3. In their confusion, they submit their thread to the Forums. The end of their message says "My site is not hosted with WordPress.com but it is connected with Jetpack".
4. Reading that, a volunteer essentially tells them there's nothing WordPress.com can do.
5. The user is stuck. If they're lucky, someone will realise that their blog actually is a WordPress.com one and redirect them to the Account Recovery procedure, since those issues can't be dealt with in the forum.

**With this PR:**

1. The user enters their URL into the Help form.
2. They are told that it'd be better to follow the Account Recovery procedure, and so they do so.

Screenshot 2021-05-20 at 19 29 57

Assuming that's clear, and you're still not keen on implementing this, please let me know! But it is worth stressing, there is no alternative, so it would be consciously implementing a broken flow.

**Comment by jeherve** [comment]
@Aurorum Thanks for all the details! This makes a lot more sense now. I can see how useful this would be. I'll discuss it with the team and we'll see if we can get this merged.

**Comment by jeherve** [comment]
Internal reference: r226535-wpcom

**Review by jeherve — APPROVED** [review]
Let's go ahead with this!

**Pull request merged**
