### PR TITLE
Fix support for allowed HTML tags in Subscribe block submit button

### LINKED ISSUE #25104: Subscribe Block showing HTML text formatting tags in CTA Button text in the live site
### Quick summary

CTA Button in Subscribe Block displays HTML Text Formatting tags in the live site when the texts are italicized or bold but  not on in the editor. This happens across many themes.

Markup on 2022-07-11 at 1:00:32 PM

### Steps to reproduce

1. Edit a Page/Post
2. Add Subscribe Block
3. Change the text in the CTA button to Italic or bold
4. Update and Preview the post/page

### What you expected to happen

The text in the CTA button should have been italicized or bold without the HTML tags <em> </em> and <strong> </strong> being visible in the live site and preview.

### What actually happened

The texts in CTA button are showing with  the HTML tags <em> </em> and <strong> </strong> added in the live site and preview.

### Context

User reported in 5362876-zen and shared they did not see the HTML tags before in the live site.

- [ ] 5362876-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

This has happened across all themes I tested : Dicot, Twenty Twenty Two, Twenty Twenty One, Twenty Twenty, Marl, Twenty Sixteen

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/jetpack/issues/25104

#### Changes proposed in this Pull Request:

* The previous fix made to the submit button was leaving all the HTML tags escaped, so it broke the HTML tags that are allowed to use for the submit button: `em`, `strong`, `s`, and `br`. This PR fixes support for allowed HTML tags in Subscribe block submit button. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Open a New Post editor
2. Add Subscribe block
3. Use one or more double-quotes in the button, use allowed HTML tags including line break, use `>` and `<` characters
4. Save the post
5. Open post in the frontend
6. All double-quotes should be displayed, line break should be preserved, `>` and `<` characters should be displayed, as well as custom HTML tags: `em`, `strong`, `s`, and `br`.

Editor:

Screen Shot 2022-07-18 at 11 13 36

Frontend:

Screen Shot 2022-07-18 at 11 13 45

### CODE REVIEW

**Comment by wojtekn** [comment]
I've checked it on the WPCOM sandbox, works well there too.

**Review by danielbachhuber — APPROVED** [review]
👍 Works well in my testing

**Review by coder-karen — APPROVED** [review]
Based on the testing instructions I noticed something - if I removed one of the line breaks (copying the exact same HTML as in the PR description), the quotes are stripped. If I have two line breaks, they aren't. 

This is the backend:
Screenshot 2022-07-19 at 10 54 43
This is the frontend:
Screenshot 2022-07-19 at 10 56 50

It works well if I have the two line breaks like in the description - the quotes don't get stripped out in that case.

I think this is better behaviour than there had been previously though - I tried testing in 11.0 and the same code breaks the styling of the subscribe block. So it seems like this is ok / expected? I'll add an approve here anyway but haven't changed any labels just in case.

**Comment by wojtekn** [comment]
@coder-karen thanks for testing it. I've checked it, and I think this would be expected. When you remove one line break from the text we used for testing, the `<` and `>` characters form the text that looks like an HTML tag. Then `wp_kses` removes it:

179723399-9655bd5d-290e-4929-af79-76993dfd3ccc

**Comment by coder-karen** [comment]
Thanks for clarifying! Should be good to go then :)

**Comment by wojtekn** [comment]
r249249-wpcom

**Pull request merged**
