### PR TITLE
Sync: Prevent an PHP warning

### PR DESCRIPTION
**Pull request by kraftbj**
Since the `$importer` variable contains an object, it can't be used as an array key. Let's use an is_string check before attempting to compare against known importers.

```
Warning: Illegal offset type in isset or empty in /home/wpcom/public_html/wp-content/mu-plugins/jetpack-plugin/vendor/automattic/jetpack-sync/src/modules/class-import.php on line 117
```

#### Changes proposed in this Pull Request:
* Avoid using an object as an array key.

#### Jetpack product discussion
Originally proposed in D55368-code

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
* On WP.com side, see D55368-code
*

#### Proposed changelog entry for your changes:
* Sync: prevent a warning in PHP.

### CODE REVIEW

**Comment by kraftbj** [comment]
I see tests are failing. May need to do something different to meet both the original code's intent and resolve the warning.

**Comment by david-binda** [comment]
> I see tests are failing. May need to do something different to meet both the original code's intent and resolve the warning.

Thanks! Reviewing the unit tests and digging into the issue again, it feels like it's caused by a custom importer which passes `$this` to the `import_end` action:

```
do_action( 'import_end', $this );
```

while the Jetpack's callback expects (likely correctly) the param to be a type of `string`. So I guess, that the proper fix would be on the custom importer's side of things ( see D55517-code for more details ).

I believe that this PR can be closed, then.

**Comment by david-binda** [comment]
Thinking about the issue more, we could also harden the code in here by checking the type of the `$importer` variable, before attempting to use it as an array key. As shown in revisited D55368-code

**Comment by mdbitz** [comment]
Thanks @david-binda I agree a is_string check is appropriate in this case. I'll make sure I get this updated before end of week, been a little head down on a few tasks.

**Review by david-binda — APPROVED** [review]
Thanks for working on this @mdbitz !

I have tested the patch on WPCOM via updated D55368-code, and it works great.

That said, :shipit:

**Review by mdbitz — APPROVED** [review]
Kraft approved :)

**Pull request merged**
