### PR TITLE
Lazy Images: Add placeholder support

### PR DESCRIPTION
**Pull request by ebinnion**
#### Changes proposed in this Pull Request:

Add placeholder support for loading lazy images.

#### Testing instructions:

In short, add images in various places and ensure that a grey placeholder initially loads, followed by the image being loaded. This process should have minimal jank.

If you're on a fast connection, you may want to consider slowing the connection down a bit so that you can actually see the placeholders. You can do this in Chrome:

https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions

Some specific places to test:

- On a WooCommerce site with Storefront
    - Home page
    - Shop page
    - Individual product page
    - Cart page after updating quantity
- Blog listing
- Individual posts/pages

#### Proposed changelog entry for your changes:
Adds placeholder support for Lazy Images

### After

after_placeholders_kareless_shop mov

### Before

before_placeholders_kareless_shop mov

### CODE REVIEW

**Comment by jeherve** [comment]
@ebinnion Is this ready to test and review, or do you still have work to do with that PR?

**Comment by ebinnion** [comment]
It's not yet ready to go. There's an issue with the implementation as-is where the placeholder size is determined based on the image's containing element. We'll need to add a wrapper around the image to fix the issue.

**Comment by ebinnion** [comment]
@jeffgolenski To make placeholders work properly, we're going to have to add a wrapper around each image. This makes me a bit nervous since it could break queries where an image is selected using a child selector.

For example:

```css
.header > img {}
```

If we wrap the image in something like `<div class="jetpack-lazy-images__placeholder-wrapper">...</div>`, then we the CSS would need to change to something like:

```css
.header > .jetpack-lazy-images__placeholder-wrapper > img {}
```

So, in cases like this, we could break styles on images. With that in mind, I think we should still add wrappers for lazy images images placeholders, but consider adding a toggle or some UI that allows users to turn placeholders off. What are your thoughts?

**Comment by jeffgolenski** [comment]
@ebinnion Yeah absolutely. I agree with you. In the off-chance they do break, there should be an option that at least allows them to prevent that.

**Comment by ebinnion** [comment]
> Could you tell me a little more about how adding that wrapper around the images and how it has the potential to break things?

My concern is primarily when there is CSS that uses something like `.something > img` in a selector. That would no longer work since we've just placed a div, or some other wrapper, in between `.something` and `img`.

My hunch is that the breakage from that would be fairly minimal, but I imagine it would still cause some issues and users would think it was a Jetpack issue.

**Pull request closed without merging**
