### PR TITLE
Try/improve placeholder buttons

### PR DESCRIPTION
**Pull request by jasmussen**
Improves #39933

## Proposed changes:

* Makes the Generate with AI button secondary
* Makes it the same height as other buttons.

### Other information:

Note, I was not able to fully get my env. to compile, I kept getting this message:

Screenshot 2024-10-31 at 12 36 10

Additionally, this is just one button, since multiple buttons are being touched, a PR such as this would need to touch additional buttons. Therefore this is more of a draft, progress on the issue. 

Let me know if this was helpful.

### CODE REVIEW

**Comment by jasmussen** [comment]
Added another bit of code that changes how the buttons stack in the medium placeholder breakpoint, fixes the style, and the height. 

Again, I cannot test this unfortunately, but the code should work, if you're able to review, feel free to bring this home. At this point, I think this PR fixes #39933.

**Review by jeherve — COMMENTED** [review]
Ah, I missed that you were working on this, and was pushing my own PR, #39985. :)

Your PR gets us some of the way there:

Screenshot 2024-10-31 at 13 49 00
Screenshot 2024-10-31 at 13 48 54

Do you think I should bring some of the things from your PR into mine?

**Review by jeherve — COMMENTED** [review]
Ah, I missed that you were working on this, and was pushing my own PR, #39985. :)

Your PR gets us some of the way there:

Screenshot 2024-10-31 at 13 49 00
Screenshot 2024-10-31 at 13 48 54

Do you think I should bring some of the things from your PR into mine?

**Comment by jasmussen** [comment]
Thanks for testing. It seems like you got this much better handled in #39985! I'm happy to close this one in favor of that.

**Pull request closed without merging**
