### PR TITLE
Site Settings API: Add `subscription_options` to site settings endpoint

### LINKED ISSUE #71414: Reading Settings: Expose `subscription_options` site option in the settings API
"Welcome email text" and "Comment follow email text" settings in the new Reading settings page alter the `subscriprion_options` site option.

This option is not being exposed via the `site/%s/settings` API yet. Hence, we need to first make it available to be then able to read and update it via UI in Calypso.

For completeness, the `subscriprion_options` site option consists of two arrays in the following form:

|  key | value type |
| ------------- | ------------- |
| invitation | string |
| comment_follow | string |

Both values need to be sanitized and allow `<a />` tags - as they are used in the default text values.

This task is a blocking dependency for the following two tasks:

* https://github.com/Automattic/wp-calypso/issues/70414
* https://github.com/Automattic/wp-calypso/issues/70415

### PR DESCRIPTION
**Pull request by ivan-ottinger**
#### Changes proposed in this Pull Request:

The proposed changes expose `subscription_options` site option to the site settings API at `site/%s/settings` (`GET`) and also allows this setting to be updated (`POST`).

Closes https://github.com/Automattic/wp-calypso/issues/71414

Having `subscription_options` site option available is required to be able to interact with it via Calypso UI, more specifically through the new Reading settings page we are building. This PR will unblock the following two tasks:

* https://github.com/Automattic/wp-calypso/issues/70414
* https://github.com/Automattic/wp-calypso/issues/70415

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

* project thread: pdDOJh-17o-p2
* p1671626436207709-slack-C02TCEHP3HA

#### Does this pull request change what data or activity we track or use?

No, it does not.

#### Testing instructions:

1. Use the [script below](https://github.com/Automattic/jetpack/pull/28036#issuecomment-1361259623) to sync the changes to your sandbox.
2. Sandbox `public-api.wordpress.com`.
3. When testing with Atomic and Jetpack-connected sites, the build changes need to be synced to those sites as well. More info: PCYsg-eg0-p2 and pb5gDS-1rQ-p2
4. Use the Developer Console to test the `GET` request (`/sites/$site/settings`):

Markup on 2023-01-03 at 10:26:36

5. Use cURL to test `POST` requests:

As a first step, you can copy the raw cURL request by doing a POST request using the Developer Console:

Markup on 2023-01-03 at 10:37:30

and then paste it into terminal with desired option values to be set, e.g.:

Markup on 2023-01-03 at 10:52:00

Once the request is sent, the API should respond as follows:

Markup on 2023-01-03 at 10:53:11

and the new option values should be saved.

The `POST` should let through values that only include plain text, line breaks and anchor tags. The accepted keys are `invitation` and `comment_follow`. Example of a correct option in JSON format:

```json
"subscription_options": {
	"invitation": "text 1",
	"comment_follow": "text 2"
},
```

If needed, values can be also changed through textfields in the WP Admin UI at `wp-admin/options-reading.php`.

ℹ️ Please note that if the `subscription_options` hasn't been touched through admin yet (`wp-admin/options-reading.php`) e.g. when the site is new, the option will be empty. On the WP Admin side, the default values are extracted from `Subscription_Mailer::get_default_settings()` - which we don't have access to here. Related discussion: p1671718726381529/1671717628.207919-slack-C02TCEHP3HA. → This issue will be resolved separately: https://github.com/Automattic/wp-calypso/issues/71711.

### CODE REVIEW

**Comment by mashikag** [comment]
The code looks good to me. The input sanitization looks appropriate to me too. 👍

I tested the changes and all is working as expected. 👍

**Review by mashikag — DISMISSED** [review]

**Comment by mashikag** [comment]
FYI I resolved conflicts that were caused by [my other PR](https://github.com/Automattic/jetpack/pull/28042) since @ivan-ottinger is on holidays. 🙂

**Review by mashikag — DISMISSED** [review]

**Review by mashikag — DISMISSED** [review]

**Review by mashikag — DISMISSED** [review]

**Comment by ivan-ottinger** [comment]
> FYI I resolved conflicts that were caused by https://github.com/Automattic/jetpack/pull/28042 since @ivan-ottinger is on holidays. 🙂

Thank you, Maciej! 🙇🏼‍♂️

**Comment by ivan-ottinger** [comment]
There were additional conflicts that needed to be resolved as the trunk had changed in the meantime. I have resolved the conflicts and the PR is now ready for review again.

**Review by sergeymitr — APPROVED** [review]
Tests well 👍

**Pull request merged**
