### PR TITLE
Update/cleanup sync subscriptions

### PR DESCRIPTION
**Pull request by enejb**
Removing code that we do not need any more. 

#### Changes proposed in this Pull Request:
We determine if subscriptions should go out or not based on what the jetpack_publish_post action.

#### Testing instructions:

* Test should pass.

### CODE REVIEW

**Comment by ebinnion** [comment]
After I rebased against master to pick up the changes in #5880, this PR worked fine. 👍

**Comment by jeherve** [comment]
Should this also be tested when using hooks to force subscription emails not to be sent?
https://jetpack.com/2016/02/10/hook-month-control-subscriptions/

**Comment by enejb** [comment]
@jeherve Please do test it more. 

But I am pretty confident it should still work as expected. Since since 4.4 we do not use this part any more to determine if an email should go out or not. It was left in place in case the new way wasn't going to work better but now that we know it does we can remove it.

**Comment by ebinnion** [comment]
I did functionally test that when I posted on manofhustle.com that the subscription did not go out and that the post was publicized (which means it did get successfully synced).

Besides that, there are some tests around [jetpack_published_post action](https://github.com/Automattic/jetpack/blob/3926e7b4327df3037f15315bbd215d4b2710f51e/tests/php/sync/test_class.jetpack-sync-posts.php#L855-L949), which is what is now sent to trigger a subscription going out.

So, I think we're good. 🚢

**Pull request merged**
