### PR TITLE
Conversation/Dialogue: improve transforms

### PR DESCRIPTION
**Pull request by retrofox**
This PR adds a couple of transforms to the `Conversation` and the `Dialogue` blocks.

#### Changes proposed in this Pull Request:

* Conversation/Dialogue: improve transforms #18737

### `Conversation` transform: **From** `Paragraph` blocks

* Start to edit a post
* Generates some paragraphs
* Selects them
* Confirm the `Conversation` transform is ready to use

* Confirm the paragraph blocks are converted to a Conversation/Dialogue blocks composition when the transform is done.

**before** | **after**
-----------|----------
image | image

### `Dialogue` transform: **To** `Paragraph` blocks

* Creates a `Dialogue` block
* Confirm the `Paragraph` transform option is available
Screen Shot 2021-02-07 at 8 11 23 PM
* Confirm the `Dialogue` block is converted to a `Paragraph` block.
* Also, if the Dialogue has defined a speaker, confirm it's added into the paragraph content.

**before (Dialogue)** | **after** (Paragraph)
-------|-------
image | image

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by creativecoder — APPROVED** [review]
Nice, this works well for me! I tested the following:

- Transform a single paragraph block to conversation with a single dialogue block
- Transform multiple paragraph blocks to conversation with multiple dialogue blocks
- Transform one or more paragraphs to dialogue blocks inside a conversation
- Transform one or more dialogue blocks to paragraphs within a conversation (with or without a speaker assigned)

---

If we can, I think it would be a good idea to prevent transforming from a paragraph to a conversation from within a conversation (no nested conversations). But that can be done separately from this PR

image

**Review by jeherve — APPROVED** [review]

**Comment by retrofox** [comment]
I found an issue with the function we use to create the blocks. Created a [PR here](https://github.com/Automattic/jetpack/pull/18828), and going to update this one according to those changes. Sorry.

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.4` in 7604c6b4678c8ff717693dc47227ff0462d09d42

**Comment by retrofox** [comment]
r221110-wpcom

**Pull request merged**
