### PR TITLE
Protect: Hide WAF screen on unsupported platforms

### PR DESCRIPTION
**Pull request by nateweller**
This PR disables the WAF screen from being rendered and included in navigation when the `DISABLE_JETPACK_WAF` constant is set. This is primarily to prevent the settings from being accessible on Atomic sites.

#### Changes proposed in this Pull Request:

* Extracts `DISABLE_JETPACK_WAF` killswitch logic into `Waf_Runner` so that is can be used outside of the package.
* Passes the killswitch value into the Protect app via a `isSupported` initial state variable.
* Does not render the Firewall tab in the navigation when `! isSupported`.
* Redirects away from the `/firewall` page to `/` when `! isSupported`.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

1201069996155224-as-1203527484103970

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Validate the firewall tab is accessible, and firewall page operates normally.
* Add the `DISABLE_JETPACK_WAF` constant to your environment.
* Validate the firewall tab is no longer rendered or accessible.
* Remove the constant.
* Validate the firewall tab is accessible, and firewall page operates normally.

### CODE REVIEW

**Comment by dkmyta** [comment]
Quick note while testing on Pressable - it appears that `DISABLE_JETPACK_WAF` is not defined until Jetpack is enabled, so in a situation where only Protect is activated, we continue to be able to access the Firewall page.

Otherwise, works beautifully!

**Comment by nateweller** [comment]
The failing plugin upgrades test has been tricky...

```
PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\Jetpack\Waf\Waf_Runner::is_supported_environment() in /var/www/html/wp-content/plugins/jetpack-protect/jetpack_vendor/automattic/jetpack-waf/src/class-waf-standalone-bootstrap.php:131
  Stack trace:
  #0 /var/www/html/wp-content/plugins/jetpack-protect/jetpack_vendor/automattic/jetpack-waf/src/class-waf-runner.php(386): Automattic\Jetpack\Waf\Waf_Standalone_Bootstrap->generate()
  #1 /var/www/html/wp-content/plugins/jetpack-protect/jetpack_vendor/automattic/jetpack-waf/src/class-waf-initializer.php(78): Automattic\Jetpack\Waf\Waf_Runner::update_waf()
  #2 /var/www/html/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Waf\Waf_Initializer::update_waf_after_plugin_upgrade()
  #3 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
```

I've entirely removed the code that triggers `is_supported_environment()` during upgrade in this PR, but it is still running. I believe this is because the upgrader hook runs using the old versions code. But if so, then how is a reference to `is_supported_environment()` present in the old version, if it is added in this PR?

Is the prior version of the plugin running the old upgrade handler code, but with the new `Waf_Standalone_Bootstrap` class that now references `Waf_Runner::is_supported_environment()`?

**Review by dkmyta — DISMISSED** [review]
Tests defining `DISABLE_JETPACK_WAF` killswitch on a JN instance and via the `is_atomic_platform` check on a Pressable instance worked perfectly!

**Review by coder-karen — COMMENTED** [review]
What is the expected behaviour on an Atomic or Pressable site without the Protect plugin installed? Just applying the PR I see the Firewall tab everywhere, so may be misunderstanding how to test / the expected behaviour.

**Comment by nateweller** [comment]
> What is the expected behaviour on an Atomic or Pressable site without the Protect plugin installed? Just applying the PR I see the Firewall tab everywhere, so may be misunderstanding how to test / the expected behaviour.

@coder-karen Thank you for reviewing this! I believe this was a bug - I've applied a fix: https://github.com/Automattic/jetpack/pull/27939/commits/1beed726ef4e4a4a4af9bd04060f32d36bdf2ec4

The WAF module was not being removed properly, because I was only registering the hook to remove the module on environments that supported the module 🙈

The expected behavior is that the Firewall settings should not be displayed in Jetpack > Settings when on Atomic or Pressable. I've re-tested with these changes and we should be good to go now :+1:

**Review by coder-karen — APPROVED** [review]
Looks good now, thanks! 👍

**Pull request merged**
