### PR TITLE
Podcast Player: connect with AudioPlayer via global state

### PR DESCRIPTION
**Pull request by retrofox**
~Let's hold on until https://github.com/Automattic/jetpack/pull/18151 merge. This branch has been branched off from there.~

Currently (master branch) the `<PodcastPlayer />` component is linked to the `<AudioPlayer />` through a local state defined in the first one. For instance, every time that the current time position changes, the `<AudioPlayer />` component [runs the onTimeChange callback](https://github.com/Automattic/jetpack/blob/fd0a916aba87b291b491a5e6f4d44d9f88c4cf42/projects/plugins/jetpack/extensions/shared/components/audio-player/index.jsx#L133). The `<PodcastPlayer />` [binds a function to this callback](https://github.com/Automattic/jetpack/blob/fd0a916aba87b291b491a5e6f4d44d9f88c4cf42/projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js#L271) by passing to the `onTimeChange` property, here. The method [updates the local state of the currentTime](https://github.com/Automattic/jetpack/blob/fd0a916aba87b291b491a5e6f4d44d9f88c4cf42/projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js#L166), and finally this state is passed to the `<AudioPlayer />` component via the `currentTime` property, [here](https://github.com/Automattic/jetpack/blob/fd0a916aba87b291b491a5e6f4d44d9f88c4cf42/projects/plugins/jetpack/extensions/blocks/podcast-player/components/podcast-player.js#L270).

This PR introduced a global state to connect both components, but globally using the `jetpack/media-source` state.

Fixes https://github.com/Automattic/jetpack/issues/18343

#### Changes proposed in this Pull Request:

* Podcast Player: connect with AudioPlayer via global state

#### Does this pull request change what data or activity we track or use?

No

####  Via UI
* Add a podcast block to the block editor. 
* Once the podcast player is ready to play, open the redux tool and check how the actions are triggered when you interact with the player: it sets the state to `is-playing`, `is-paused`. Also, it changes the current time position while it's playing, as well as when the position is changed by dragging the progress bar and/or the forward and back buttons.
image

### Via distpacther 

* pick up the current player:

```
wp.data.select( 'jetpack/media-source' ).getDefaultMediaSource()
```

You should get something like this:
image

#### Actions

* play:
`wp.data.dispatch( 'jetpack/media-source' ).playMediaSource( 'jetpack-podcast-player-block-0' );`
* pause:
* `wp.data.dispatch( 'jetpack/media-source' ).pauseMediaSource( 'jetpack-podcast-player-block-0' );`
* toggle:
`wp.data.dispatch( 'jetpack/media-source' ).toggleMediaSource( 'jetpack-podcast-player-block-0' );`
* set current time:
* `wp.data.dispatch( 'jetpack/media-source' ).setMediaSourceCurrentTime( 'jetpack-podcast-player-block-0', 100 )`

#### Selectors
* Get default media source:
`wp.data.select( 'jetpack/media-source' ).getDefaultMediaSource()`

* Get  player state:
`wp.data.select( 'jetpack/media-source' ).getMediaPlayerState( 'jetpack-podcast-player-block-0' )`

* Get current time:
`wp.data.select( 'jetpack/media-source' ).getMediaSourceCurrentTime( 'jetpack-podcast-player-block-0' )`

#### Run Unit Tests

```
cd ./projects/plugins/jetpack
yarn
yarn test-extensions
```

### Demo video
https://cloudup.com/c9aGV-NY0rv

Test with two or more podcast players. You should see each player registered in the state tree:
image
Confirm when you remove the block, it unregisters the media source register.

#### Proposed changelog entry for your changes:

*
n/a

### CODE REVIEW

**Comment by mreishus** [comment]
https://github.com/Automattic/jetpack/pull/18369

**Comment by mreishus** [comment]
The track title and link are stored in the redux store, but they aren't updated when you change tracks.


I don't have an opinion on this, but I noticed that `currentTrack` is in state, while everything else is in redux. Would it make sense to move `currentTrack` into redux or is it better to keep it in state? (Emphasizing that I don't know the correct answer here)

**Comment by mreishus** [comment]
Other than that, I tried everything I could think of and it's working great. Multiple players, deleting/moving them, skipping around, time seek buttons, etc.  Couldn't find any errors, and redux store data reflects the current state of the players etc. :+1:

There are some minor formatting / linting errors, github shows them in the "files changed" tab with warning messages.

**Comment by retrofox** [comment]
> The track title and link are stored in the redux store, but they aren't updated when you change tracks.

Yeah... well I was waiting for the single version of the podcast player, but it's something that we can address on this PR. Thanks for your review 🙇‍♂️

**Comment by allilevine** [comment]
> Via dispatcher

I updated the "set current time" testing step to use `setMediaSourceCurrentTime()`

> Run unit tests

All passing ✅ 
Screen Shot 2021-01-15 at 3 27 53 PM

**Comment by retrofox** [comment]
> > The track title and link are stored in the redux store, but they aren't updated when you change tracks.
> 
> Yeah... well I was waiting for the single version of the podcast player, but it's something that we can address on this PR. 

Addressed here 670ff3905e373caf36aea27bd64c1a8afe0b8651

**Review by mreishus — APPROVED** [review]
I'm now seeing the track names update when I change tracks.



Tested out several ways of using the player and couldn't find anything that was broken, or any decoupled state.  LGTM :+1:

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to test well. I think there is only one thing left to address:

```
Good job! "projects/plugins/jetpack/extensions/blocks/podcast-player/view.js" no longer has any lint errors,
and should be removed from the exclude list.
```
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/tools/eslint-excludelist.json#L147

**Comment by retrofox** [comment]
> This seems to test well. I think there is only one thing left to address:
> 
> ```
> Good job! "projects/plugins/jetpack/extensions/blocks/podcast-player/view.js" no longer has any lint errors,
> and should be removed from the exclude list.
> ```
> 
> https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/tools/eslint-excludelist.json#L147

addressed here https://github.com/Automattic/jetpack/pull/18349/commits/5f9c537d388db876e593d88e5b5b5b8d24e7a556

**Review by jeherve — APPROVED** [review]

**Comment by retrofox** [comment]
Thanks, folks 🙇‍♂️ r219580-wpcom

**Pull request merged**
