### PR TITLE
Fix subscribers messaging in post publish panel

### LINKED ISSUE #25317: Republishing a post falsely shows the post has been sent to subscribers
### Quick summary

If a user has an already published post that they switch back to a draft and then republish, the Jetpack notifications show that the post is being sent to their subscribers again, which is not actually happening.  

### Steps to reproduce

1. First, ensure that the test site has a least one subscriber
2. Publish a post
3. Switch the post to a draft and make an edit to the text
4. Publish the post again
5. View the "Subscribers" Message that appears in the pre-publish check screen and then again after the post is republished

**Prepublish Check**
Markup on 2022-07-23 at 10:45:11
 
**After Publish Confirmation**
Markup on 2022-07-23 at 11:56:55

**GIF**
62db65d365800735995851

### What you expected to happen

As this post is being republished, and the post ID is not changing, no notification emails will be sent to the site followers.  As such, I would expect that the notifications through Jetpack would tell the user that this is an already existing post and no notifications will be sent. 

### What actually happened

The messaging from Jetpack was the same as if the post was a new post and indicated that "This post has been sent to 2 readers" when in fact that was not true. 

### Context

Customer Report 5411263-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/jetpack/issues/25317

#### Changes proposed in this Pull Request:

I propose to fix subscribers messaging in the post publish panel by saving the meta field when the post is changed back to draft after it was already published. Then, we disable subscribers' notification information in the Publish panel for posts already marked as published.

As the fix relies on the meta field that is saved when a post is saved as "draft" from "published", it will fix issues for all posts that are:

* currently "published" and will be changed to "draft" in the future
* are currently "draft", have never been "published" and will be changed to "published" and then "draft" in the future

Posts that were already "published" in the past, and have been changed to "draft" before this fix, will still show the message until they are "published" and become "draft" again.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

##### Preconditions (Jetpack):
* Jetpack is in online mode 
* ensure that the test site has at least one subscriber

##### Preconditions (Simple sites)

* download both diffs (D87321-code and D87352-code),upload them to the sandbox, and apply
* bring the PR to the WPCOM sandbox using a new process too:
```bin/jetpack-downloader test jetpack fix/subscribers-messaging-in-publish-panel```
* sandbox simple site and api
* ensure that the test site has a least one subscriber

##### Testing steps

1. Go to a WP Admin -> Posts
2. Open a form to add a new post
3. Fill it with any title and content
4. Click on "Publish"
5. Confirm that the "Subscribers" block is displayed in the Publish panel
6. Click "Switch to draft" and then approve with "OK"
7. Click on "Publish"
8. Confirm that the "Subscribers" block is not displayed anymore

### CODE REVIEW

**Comment by wojtekn** [comment]
I moved it back to "In Progress" as I still need to check this issue for Simple sites.

**Review by sejas — COMMENTED** [review]
@wojtekn 

I couldn't validate it on simple sites.
I've applied these diffs: D87321, and D87352. But those changes doesn't include the functions that update the post_meta `maybe_set_first_published_status` and `register_post_meta`. 

Do I need to do something more to test simple sites?

It seems the diff for this file is missing: https://github.com/Automattic/jetpack/pull/26085/files#diff-776cd74bed19fb81f284b9dbfd8258e57d5fb0a5db07c0e1db94e47dbb0d6182

**Comment by wojtekn** [comment]
@sejas I think another code was merged to trunk and deployed in the meantime, so we couldn't apply the patch on the sandbox anymore.

I've just merged the trunk to this PR. The diff was regenerated; I applied the new one to my sandbox, retested it for simple sites, and it worked fine.

**Review by vykes-mac — COMMENTED** [review]
Works as expected. Good work!

**Review by sejas — DISMISSED** [review]
Working good !
- Tested on atomic sites
- Tested on simple sites
- I didn't see the subscribers messaging box on jetpack sites.

**Comment by wojtekn** [comment]
@Automattic/jetpack-crew I would appreciate a review for this one.

**Review by coder-karen — CHANGES_REQUESTED** [review]
The PR tests well on simple and Jetpack-connected sites in terms of the subscriber messaging. I did spot a side effect though, on both simple and JP-connected sites (and in both the WordPress.com editor and the wp-admin post editor). If I have Sharing enabled on my site, and if I deselect 'Share when publishing' under 'Share this post' when a post is in the pre-publish state, then there is an error message on the screen:

`Publishing failed. meta.jetpack_post_was_ever_published is not of type string.`.

In another instance I saw `Publishing failed. Sorry, you are not allowed to edit the jetpack_post_was_ever_published custom field.`. (in that case there were no subscribers). 

In both instances despite the editor showing the post appearing to be unpublished, it did publish.

**Comment by wojtekn** [comment]
@coder-karen thanks for giving it a test and finding those failing cases!

I reproduced and fixed both. I modified the WPCOM part and used the meta code that is similar to the Jetpack implementation. The initial implementation was too hacky, and it was causing problems when the editor tried to save the meta value on its own. Then I added an auth callback on the Jetpack side to allow saving the meta field to users who can publish posts.

It seems working fine in those cases, I've also checked other cases e.g., users who do not have publishing permissions and those are working fine too.

**Review by coder-karen — APPROVED** [review]
Works well for me too now - on WoA, simple and Jetpack-connected sites.

**Comment by wojtekn** [comment]
r252523-wpcom and r252522-wpcom

**Pull request merged**
