### PR TITLE
VideoPress: Fix VideoPress Attachment Deletions on wp.com

### PR DESCRIPTION
**Pull request by roundhill**
Fixes issue where deleting a VideoPress video would not actually delete the VideoPress entry on wp.com. Uses the `pre_delete_attachment` filter to attempt deletion of VideoPress video on wp.com.

There's a big change here in that the attachment will not get deleted unless wp.com successfully deleted the VideoPress video (unless the API returns a `404` which means it was already deleted or not found). This is to prevent any dangling data. One thing I'd like advice on here is how we can tell the user there was an error so they can take appropriate action. At a minimum it'd be great if we could add to the activity log so that happiness can help troubleshoot.

#### Changes proposed in this Pull Request:
* Updates VideoPress attachment deletions to use the wp.com api to actually delete the video from our servers.

#### Jetpack product discussion
pxWta-Zz-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Select a video in the media library and copy it's `guid`.
* Delete the video.
* Check that the video is not found at https://videopress.com/v/{guid}
* Repeat the above steps for videos in the Calypso media library.

**Also test that attachment poster image is deleted:**
* Right click on a video thumbnail and copy the url for the poster image:
Screen Shot 2021-08-31 at 2 19 39 PM
* Delete the video
* Try to access the thumbnail url, it should also be deleted.

### CODE REVIEW

**Review by jgcaruso — CHANGES_REQUESTED** [review]
Tested perfectly for the happy path, but when I tried to make things break it got into some funny situations.

I wonder if we check for specific errors, like `404` and allow the function to return `null`. This could help if the video was deleted on wpcom but the request timed out (or jetpack lost connection). The next time the user tries to delete the video we'd block them because its an error, but really if the video is gone from the server we can allow it to be removed from their site's media library.

**Review by jgcaruso — DISMISSED** [review]
`404` check works as expected!

Other than the latest doc block warning, everything looks good!

**Review by jeherve — COMMENTED** [review]
This seems to test well for me. I was wondering if we should take that opportunity to also delete the poster image or images that were created for that video?

**Comment by roundhill** [comment]
> This seems to test well for me. I was wondering if we should take that opportunity to also delete the poster image or images that were created for that video?

That's a good call - I assumed all of the thumbnails were stored on wp.com but I see some in the local media library.

**Comment by roundhill** [comment]
> That's a good call - I assumed all of the thumbnails were stored on wp.com but I see some in the local media library.

Ok the attachment poster image is also delete now as well: 5d5713e. Updated the testing instructions on how to test for that.

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 👍

**Pull request merged**
