### PR TITLE
Allow caching script in Facebook embeds and Facebook Page Plugin widget

### PR DESCRIPTION
**Pull request by kienstra**
#### Changes proposed in this Pull Request
* In place of `jQuery.getScript()`, use vanilla JS to get a script. This should allow the browser to cache it. 
* It looks like [jQuery.getScript()](https://api.jquery.com/jQuery.getScript/#caching-requests) doesn't cache the script by default. But maybe there's a reason it shouldn't be cached.
* Also, this removes the `jQuery` dependency from this script. 
* This should help the [Facebook Page Plugin widget](https://github.com/Automattic/jetpack/blob/4a46d48e326df63a40109828cc201202ba66e1f1/modules/widgets/facebook-likebox.php#L13) and [Facebook embeds](https://github.com/Automattic/jetpack/blob/4a46d48e326df63a40109828cc201202ba66e1f1/modules/shortcodes/facebook.php#L19-L34), as they [all use the script](https://github.com/Automattic/jetpack/blob/4a46d48e326df63a40109828cc201202ba66e1f1/modules/shortcodes/facebook.php#L84).

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Not a new feature, only a performance enhancement to a given feature. No intended change in functionality.

#### Testing instructions:

* In the Customizer, add a 'Facebook Page Plugin' widget
* Enter a 'Facebook Page URL,' like https://www.facebook.com/cureintl/
* Click 'Publish,' and view the front-end
* Expected: the widget still looks and works as expected
* Also test Facebook embeds, using a 'Facebook' or 'Embed' block

#### Proposed changelog entry for your changes:

* Facebook embed and Facebook Page Plugin performance enhancement

### CODE REVIEW

**Comment by kienstra** [comment]
Hi @dero, could you please review this? Thanks, and have a great day.

**Comment by dero** [comment]
@kienstra This looks good!

**Review by dero — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks, Dero!

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
r204382-wpcom

**Pull request merged**
