### PR TITLE
New shell command for easier access to the database.

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
Introducing the new command: `yarn docker:mysql`.
It reads the environment variables and initializes a mysql client session.
Logging into your mysql has never been easier!

Introducing the new command: `yarn docker:run-extras`.
It runs the file `docker/bin/run-extras.sh`.
The whole purpose of a separate file is to run commands that can be run during both:
1. The container initialization (run by `docker/bin/run.sh`)
2. The active container (run by `yarn docker:run-extras`).

This will let us modify the container without the need for everybody to rebuild it.

#### Jetpack product discussion
`p1596825139021600-slack-jetpack-crew`

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Use the docker environment.
2. Run `yarn docker:run-extras` to run the extras
3. Run `yarn docker:compose exec wordpress cat /root/.my.cnf` to confirm that the MySQL config file was created.
3. Run `yarn docker:db`, and confirm that you actually are inside your database.
4. Run `yarn docker:compose rm -sf wordpress` to remove your docker container.
**Danger: this will remove your container with any custom changes you made to it that are not in the `docker-compose` files.** _Although you shouldn't have made any custom changed to your docker containers in the first place 😉._
5. Run `yarn docker:up -d` to restart the container. The `jetpack_wordpress` container is supposed to be rebuilt.
6. Run `yarn docker:db` to confirm that you can once again access the MySQL client.

#### Proposed changelog entry for your changes:
New shell command `yarn docker:db` for easier access to the database

### CODE REVIEW

**Review by leogermani — DISMISSED** [review]
LGTM

Leaving as Needs Review to get a second opinion on whether the new dependencies are fine.

We should also not forget and try to understand what's going on with `yarn docker:wp db cli`. It should work...

**Review by jeherve — COMMENTED** [review]
While this can be useful, this adds quite a few new dependencies that are going to slow down build times quite a bit. I'm not sure if this is worth it.

Maybe we could look into why `yarn docker:wp db cli` hangs from time to time, and try to fix that instead?

**Comment by sergeymitr** [comment]
@jeherve 

> Maybe we could look into why yarn docker:wp db cli hangs from time to time, and try to fix that instead?

I'll try to dig into it, but wouldn't put too much hope into this.
Most likely it's Docker acting up, since it works for some people and doesn't work for others.

**Comment by kraftbj** [comment]
I would suggest let's dig deeper into the docker:wp cli failure before adding another shell access. Unrelated but related, we can add phpMyAdmin as an alternative for those who prefer a GUI/backup without hurting build times.

**Review by jeherve — COMMENTED** [review]
This doesn't quite work for me, it gives me this error:

`ERROR 2005 (HY000): Unknown MySQL server host 'db:3306' (2)`

For reference:

```
jetpack  add/docker-mysql-access
❯ yarn docker:db                                                       jeherve@jer
yarn run v1.21.1
$ yarn docker:compose exec wordpress bash -c "mysql --defaults-group-suffix=docker"
$ yarn docker:env && yarn docker:compose-extras && docker-compose -f docker/docker-compose.yml -f docker/compose-extras.yml exec wordpress bash -c 'mysql --defaults-group-suffix=docker'
$ node -e "require('fs').createWriteStream( 'docker/.env', { flags: 'a' } );"
$ [ -f docker/compose-extras.yml ] || cp docker/compose-extras.yml.sample docker/compose-extras.yml
ERROR 2005 (HY000): Unknown MySQL server host 'db:3306' (2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

jetpack  add/docker-mysql-access
❯ docker ps                                                            jeherve@jer
CONTAINER ID        IMAGE                                     COMMAND                  CREATED              STATUS              PORTS                                      NAMES
00b3028cc0ef        wernight/ngrok                            "/entrypoint.sh"         About a minute ago   Up About a minute   0.0.0.0:4040->4040/tcp                     jetpack_ngrok
80d174fc44ea        automattic/jetpack-wordpress-dev:latest   "/usr/local/bin/run"     About a minute ago   Up About a minute   0.0.0.0:80->80/tcp                         jetpack_wordpress
025161eaa62a        mysql:5.7                                 "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp, 33060/tcp                        jetpack_mysql
413fccd22a1c        djfarrelly/maildev                        "bin/maildev --web 8…"   About a minute ago   Up About a minute   0.0.0.0:25->25/tcp, 0.0.0.0:1080->80/tcp   maildev
d2981e18692e        atmoz/sftp                                "/entrypoint"            About a minute ago   Up About a minute   0.0.0.0:1022->22/tcp                       jetpack_sftp
```

**Comment by kraftbj** [comment]
Since it adds to run.sh, you may need to yarn docker:up first.

**Comment by jeherve** [comment]
I'm still seeing the issue unfortunately :(

**Review by jeherve — APPROVED** [review]
It works now! 🚢

**Review by kraftbj — APPROVED** [review]

**Pull request merged**
