### PR TITLE
Remove/account creation links

### PR DESCRIPTION
**Pull request by johnHackworth**
fixes https://github.com/Automattic/jetpack/issues/8943

This PR removes the wpcom account creation link from below the connection buttons:

image

How to test it
==========
1. Go to your jetpack menu in an unconnected site: You should see the top & bottom connect buttons, but the old "no account?" link shouldn't be after them anymore

### CODE REVIEW

**Comment by oskosk** [comment]
@johnHackworth looks like you started this PR with a sort of old state of `master` as there are a bunch of conflicts from files that haven't been touched for about two weeks.

**Comment by gravityrail** [comment]
Just pushed a fix for those failing tests

**Comment by johnHackworth** [comment]
thank you dan!

**Comment by johnHackworth** [comment]
@oskosk @dereksmart @zinigor  do you think I can merge this?

**Pull request merged**
