### PR TITLE
Add wp_suspend_cache_addition on full sync

### PR DESCRIPTION
**Pull request by enejb**
Add wp_suspend_cache_addition on full sync. 

cc: @lezama @kovshenin

### CODE REVIEW

**Comment by gravityrail** [comment]
LGTM!

**Comment by enejb** [comment]
I did the following in test:
```	
function test_full_sync_memory() {
		// make some stuff
		foreach( range( 0, 1000 ) as $number ) {
			$post_id = $this->factory->post->create();
			$this->factory->user->create();
			$this->factory->comment->create_post_comments( $post_id, 2 );
		}

		$this->full_sync->start();
		Jetpack_Sync_Actions::do_cron_sync();
	}
```

With the following debug code. ( in sync/class.jetpack-sync-module-full-sync.php )
```
$before = memory_get_usage();
// Suspend cache addition prevent the cache from being overloaded by large sites.
wp_suspend_cache_addition( true );
$items_enqueued = $module->enqueue_full_sync_actions( $module_config );
wp_suspend_cache_addition( false );

$after = memory_get_usage();
$calc = ( $after - $before );
error_log( print_r( 'memory usage for '.$module_name.':'. $calc ,1 ));
``` 

and  sync/class.jetpack-sync-actions.php
```
$before = memory_get_usage();
wp_suspend_cache_addition( true );
$result = self::$sender->do_sync();
wp_suspend_cache_addition( false );
$after = memory_get_usage();
$calc = $after - $before;

error_log( print_r( 'MEMORY ON DO CRON SYNC:' . $calc,1 ));
```

which produced the followin result before `wp_suspend_cache_addition()` calls were added
```
memory usage for constants:208
memory usage for functions:208
memory usage for options:208
memory usage for network_options:0
memory usage for terms:16608
memory usage for themes:208
memory usage for users:16416
memory usage for posts:16496
memory usage for comments:16496
memory usage for updates:4304
memory usage for attachments:0
memory usage for meta:0
memory usage for plugins:0
memory usage for protect:0
memory usage for full-sync:0
MEMORY ON DO CRON SYNC:40278232
```
and after
```
memory usage for constants:208
memory usage for functions:208
memory usage for options:208
memory usage for network_options:0
memory usage for terms:16608
memory usage for themes:208
memory usage for users:16416
memory usage for posts:16496
memory usage for comments:16496
memory usage for updates:4304
memory usage for attachments:0
memory usage for meta:0
memory usage for plugins:0
memory usage for protect:0
memory usage for full-sync:0
MEMORY ON DO CRON SYNC:36487784
```

notice the reduction on memory o do cron sync.

**Comment by enejb** [comment]
From my testing I saw that we don't add grow memory usage when we add items to the queue but when we run `Jetpack_Sync_Actions::do_cron_sync();`. The main culprit here is when we expand the the post_id, user_ids, comment_id into items and then add to the in memory cache. 


To prevent that we add `wp_suspend_cache_addition( true );` and `wp_suspend_cache_addition( false );` after to avoid adding to in memory cache.

**Comment by enejb** [comment]
Retesting:
Using the following phpunit test with ranges of 100, 1000, 10000.
```
	function test_full_sync_memory() {
		// make some stuff
		remove_all_actions(  'jetpack_sync_remote_action' );
		foreach( range( 0, 10000 ) as $number ) {
			$post_id = $this->factory->post->create();
			$this->factory->user->create();
			$this->factory->comment->create_post_comments( $post_id, 2 );
		}
		$before = memory_get_usage();
		$this->full_sync->start();

		Jetpack_Sync_Actions::do_cron_sync();

		$after = memory_get_usage();
		$calc = $after - $before;
		error_log( print_r( 'MEMORY ON DO CRON SYNC:' . $calc,1 ));
	}
```

The results with `wp_suspend_cache_addition` (this PR) 
100 iterations
MEMORY ON DO CRON SYNC: `647024`
Time: 4.74 seconds, Memory: 42.00MB

1000 iterations
MEMORY ON DO CRON SYNC: `696176`
Time: 27.72 seconds, Memory: 78.00MB

10,000 iterations
MEMORY ON DO CRON SYNC: `889496`
Time: 5.94 minutes, Memory: 208.00MB

Without: ( current master )
100 iterations
MEMORY ON DO CRON SYNC: `1036032`
Time: 4.65 seconds, Memory: 42.00MB

1000 iterations
MEMORY ON DO CRON SYNC: `4486624`
Time: 29.97 seconds, Memory: 82.00MB

10,000 iterations
MEMORY ON DO CRON SYNC: `1212776`
Time: 5.87 minutes, Memory: 208.00MB

**Comment by enejb** [comment]
update the test to 
```
function test_full_sync_memory() {

	// make some stuff
	remove_all_actions(  'jetpack_sync_remote_action' );
	foreach( range( 0, 1000 ) as $number ) {
		$post_id = $this->factory->post->create();
		$this->factory->user->create();
		$this->factory->comment->create_post_comments( $post_id, 2 );
	}

	wp_cache_flush();

	$before = memory_get_usage();
	$this->full_sync->start();

	Jetpack_Sync_Actions::do_cron_sync();

	$after = memory_get_usage();
	$calc = $after - $before;
	error_log( print_r( 'MEMORY ON DO CRON SYNC:' . $calc,1 ));
}
```


MEMORY ON DO CRON SYNC:671952 - Time: 4.85 seconds, Memory: 42.00MB 
MEMORY ON DO CRON SYNC:721104 - Time: 33.43 seconds, Memory: 68.00MB
MEMORY ON DO CRON SYNC:651888 - Time: 6.44 minutes, Memory: 178.00MB

without 
MEMORY ON DO CRON SYNC:2114312 - Time: 4.87 seconds, Memory: 42.00MB
MEMORY ON DO CRON SYNC:14818056 - Time: 30.38 seconds, Memory: 80.00MB
MEMORY ON DO CRON SYNC:17131672 - Time: 6.09 minutes, Memory: 178.00MB

test were performed on PHP7

**Comment by enejb** [comment]
Merged to 4.2 in https://github.com/Automattic/jetpack/commit/d736464e56fa84b68f3bf6aceed0686124f4ee36

**Comment by lezama** [comment]
thanks Enej!

**Pull request merged**
