### PR TITLE
Conversation: Handle closely speaker-name changes propagation

### PR DESCRIPTION
**Pull request by retrofox**
~This PR fixes a bug when the user selects multiple blocks. It changes the speakers of some Dialogue blocks because the app detects that the block is selected, and consequently updates the speaker.~

This PR handles the propagation of the speaker-name changes among all Dialogue sibling blocks closely.
It checks if whether the participant label and the current block label are different before applying the changes, also checks if there is a multi-blocks-selection, and finally it removes the debouncing when setting attributes.

Fixes #

#### Changes proposed in this Pull Request:

* Conversation: Handle closely speaker-name changes propagation

#### Jetpack product discussion

p7DVsv-atS-p2#comment-34479

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create Conversation/Dialogue composition
* Defines some speakers for them

**before**
In the following video, the speaker changes from `James` to `Jimmy` just because of the multi-selection.

https://user-images.githubusercontent.com/77539/108001635-b9222900-6fcb-11eb-83be-346ec966a130.mov

**after**
It's possible to select all blocks, move them and also apply a multiple speaker edition 

https://user-images.githubusercontent.com/77539/108001540-7a8c6e80-6fcb-11eb-9ccc-d228d7d20869.mov

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by creativecoder — CHANGES_REQUESTED** [review]
Unfortunately this change doesn't seem to fix the issue for me

conversation-multiple-select

**Comment by retrofox** [comment]
> Unfortunately this change doesn't seem to fix the issue for me

Oh, right it's true. I think it's better than before, though. We need to figure out a better solution for this, but in the meanwhile, I think we could apply these changes.

**Comment by allilevine** [comment]
This sometimes works and sometimes doesn't for me. 🤔 

The issue re-occurs here:
changingspeakers

But not here:
changingparticipants2

**Comment by retrofox** [comment]
> This sometimes works and sometimes doesn't for me. 🤔
> 
> The issue re-occurs here:

> But not here:

I'm not able to reproduce the error. Tested with the Gutenberg version of WordPress 5.5, and also activating core `Version 10.1.0 `. :-(

**Comment by retrofox** [comment]
> > This sometimes works and sometimes doesn't for me. 🤔
> > The issue re-occurs here:
> 
> > But not here:
> 
> I'm not able to reproduce the error. Tested with the Gutenberg version of WordPress 5.5, and also activating core `Version 10.1.0 `. :-(

I can reproduce it in firefox. Nice catch, Allison. 👍

**Comment by retrofox** [comment]
> I can reproduce it in firefox. Nice catch, Allison. 👍

fixed here https://github.com/Automattic/jetpack/pull/18835/commits/7aad68757e192797638c7a3ee8065de3f015407b

**Review by allilevine — APPROVED** [review]
The speakers no longer change when multi-selected, in both Firefox and Chrome. ✨

**Review by jeherve — APPROVED** [review]
Tests well for me. 🚢

**Comment by retrofox** [comment]
r222110-wpcom

**Comment by jeherve** [comment]
@retrofox It looks like r222110-wpcom is missing some of the changes from this PR (the function rename form `refreshAutocompleter` to `freshAutocompleter`. Do you think you could take a look?

Thank you!

**Comment by retrofox** [comment]
> @retrofox It looks like r222110-wpcom is missing some of the changes from this PR (the function rename form `refreshAutocompleter` to `freshAutocompleter`. Do you think you could take a look?

Yes, give me some hours :-)

**Comment by retrofox** [comment]
> Do you think you could take a look?

D59867-code

**Comment by retrofox** [comment]
r223914-wpcom

**Pull request merged**
