### PR TITLE
Command Palette: Add GH deployments is available.

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes:
- https://github.com/Automattic/wp-calypso/issues/88345

## Proposed changes:

* Added if GitHub deployments are available.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply these changes to your sandbox.
* Add the `wpcom-github-deployments` sticker to your blog.
* Open the browser's console and type `commandPaletteConfig`.
* You should see that the new property is included and set to true if you have the blog sticker.

### CODE REVIEW

**Comment by rcrdortiz** [comment]
The sticker isn't getting propagated to my Atomic site, could any of you give it a shot?

Just by adding the sticker from wpcom it should get propagated to APD, but it's not working for me.

**Review by dsas — COMMENTED** [review]
It looks like it should work but for some reason it isn't.

I had an already existing atomic site, and on my sandbox ran `wp blog-stickers add --sticker=wpcom-github-deployments --blog_id=229411837 --who=deansas` The blog sticker is showing up in RC but `commandPaletteConfig.isGHDeployAvailable` is false in wp-admin 🤔 Pretty sure it must be something I'm doing wrong, or something not related to this issue.

**Comment by dsas** [comment]
The sticker is not in the allowlist: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qoybt%2Qfgvpxref.cuc%3Se%3Qosr72390%23129-og

I think we should be using `wpcomsh_should_show_wpcom_github_deployments_menu` on Atomic. It'll use the REST API which uses the sticker.

**Comment by rcrdortiz** [comment]
> The sticker is not in the allowlist: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qoybt%2Qfgvpxref.cuc%3Se%3Qosr72390%23129-og
> 
> I think we should be using `wpcomsh_should_show_wpcom_github_deployments_menu` on Atomic. It'll use the REST API which uses the sticker.

That seemed to do the trick, thanks!

**Review by dsas — DISMISSED** [review]
WfM now.

In my completely unscientific tests the network request time of /wp-admin increased by 0.069 seconds. I think that's ok for a temporary measure 🤔 If it is a problem then we'll have to update the APD allowlist and backfill, or allow redirecting to the Calypso page and explaining on there.

**Comment by rcrdortiz** [comment]
> WfM now.
> 
> In my completely unscientific tests the network request time of /wp-admin increased by 0.069 seconds. I think that's ok for a temporary measure 🤔 If it is a problem then we'll have to update the APD allowlist and backfill, or allow redirecting to the Calypso page and explaining on there.

The time increase isn't a problem, 0.07 seconds is negligible. Also, bear in mind that once the GitHub deployments feature is released, these sticker checks will be removed since the feature will be available to all our users.

**Review by dsas — APPROVED** [review]

**Pull request merged**
