### PR TITLE
JS Components: Convert layout (Col, Container) components to TypeScript

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Changes proposed in this Pull Request:
* This PR converts `Col` and `Container` components to TypeScript.
* It also converts the Layout stories to TS

To see the actual changes please check d9f3a3110802beeba0c799f18b62118745d3be61 and 347861324db4e74545db4992a3beb498954c9eca

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Checkout the PR
* Run `cd projects/js-packages/storybook && pnpm run storybook:dev`
* Confirm that all the Layout stories work as expected
* Check the consumers of `Col` and `Container` and related components and confirm that they work as expected
* Check for any regression

Screenshot 2022-07-29 at 12 46 46 PM

Screenshot 2022-07-29 at 12 45 46 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202276314264006

### CODE REVIEW

**Comment by dhasilva** [comment]
There are some undefined values in the CSS:
Before | After
---------|---------
Screenshot_2022-08-01_16-00-21 | Screenshot_2022-08-01_16-00-01

**Comment by manzoorwanijk** [comment]
> There are some undefined values in the CSS:

Nice catch @dhasilva. Thanks! Pushed a fix with default values that got removed while refactoring.

**Review by dhasilva — APPROVED** [review]
Looks good.

Screenshot_2022-08-02_10-24-00

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by chrisbliss18** [comment]
I tried testing this PR on WordPress.com, and I was unable to apply the patch. It seems to be a version issue in `projects/js-packages/components/package.json`:

```
error: while searching for:
{
	"name": "@automattic/jetpack-components",
	"version": "0.17.1",
	"description": "Jetpack Components Package",
	"author": "Automattic",
	"license": "GPL-2.0-or-later",
```

**Comment by sdixon194** [comment]
I'd give it a go again now @chrisbliss18, I just updated the diff manually. I'm not sure why that was conflicting.

**Comment by manzoorwanijk** [comment]
deployed via r250023-wpcom

**Pull request merged**
