### PR TITLE
VideoPress Block: Fix video display at any aspect ratio to not show black bars

### PR DESCRIPTION
**Pull request by roundhill**
Fixes https://github.com/Automattic/wp-calypso/issues/54351

There's been a number of fixes put in the VideoPress block to fix issues with certain aspect ratios causing black bars at the top/bottom/sides of the video. The block uses the VideoPress iframe embed to display the video, and the iframe embed was not configured to resize within its parent container. Instead it expects a width and height to be provided to it in the same way that you would embed a YouTube video with a fixed height and width. 

To get around this we've added support for a new url argument to be passed to the VideoPress oembed url that will have the `videopress-iframe.js` always resize the video to its parent container. This way we get nice looking embeds in gutenberg as well as on the front end:

Screen Shot 2021-08-06 at 4 05 35 PM

#### Changes proposed in this Pull Request:
* The `has-aspect-ratio` classes will no longer be added since they are no longer needed (I've left the code for this just in case we need to roll back to it)
* `resizeToParent` VideoPress url argument will always be added to get the resizing working nicely.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Insert some videos into a post (both from media library and a new upload directly to editor), they should not have any large black bars on any side (Note: Some browsers have a 1px bar sometimes - we are looking into this).
* Try inserting videos into a `Columns` block, they also should not have large black bars at the sides.
* Publish the post and the videos should look the same as in the editor.

### CODE REVIEW

**Comment by roundhill** [comment]
> The only case where it is not respected is in the editor when the video is first added, but I think this was the case prior to this PR as well. The video is added with bars, and until a change is made that causes a new URL to be retrieved, it doesn't render correctly.

As discussed in Slack this may not be an issue in production, it appears the first transcode job finishes before the embed is requested, so it gets the proper width/height set for the processing screen and the video when it first loads.

**Review by jeherve — COMMENTED** [review]
I'm noticing bars on an old post, but I'm not sure if that's expected.

Here is how it looks in the frontend:

image

And in the editor:

image

Here is the post content:

<details>
```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"33.33%"} -->
<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:paragraph -->
<p>On the right, you'll see an instructional video. Enjoy!</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"66.66%"} -->
<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:video {"guid":"K9lV8j11","id":13505,"src":"https://videos.files.wordpress.com/K9lV8j11/screenshot-2020-08-13-at-11.52.21_hd.mp4","videoPressClassNames":"wp-block-embed is-type-video is-provider-videopress","className":""} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/K9lV8j11?resizeToParent=true&amp;preloadContent=metadata
</div></figure>
<!-- /wp:video -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:heading -->
<h2>And below, the same video bu t aligned center and using the videopress embed block variation</h2>
<!-- /wp:heading -->

<!-- wp:embed {"url":"https://videopress.com/v/K9lV8j11","type":"video","providerNameSlug":"videopress","responsive":true,"align":"center","className":""} -->
<figure class="wp-block-embed aligncenter is-type-video is-provider-videopress wp-block-embed-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/K9lV8j11
</div></figure>
<!-- /wp:embed -->
```
</details>

**Comment by roundhill** [comment]
> I'm noticing bars on an old post, but I'm not sure if that's expected.

@jeherve I should have mentioned that this won't fix existing videos unless you make a change to the video block so that the embed url changes (like change the rating). If you insert a new video, you shouldn't see the bars.

**Review by jeherve — APPROVED** [review]
Following the discussion above, this looks good to me! 🚢

**Comment by roundhill** [comment]
r230275-wpcom

**Pull request merged**
