### PR TITLE
Mobile Theme: Update verbiage for feature

### LINKED ISSUE #7036: Settings: Clearer label on mobile theme option
Right now, we have a label for the mobile theme that looks like this:

screen shot 2017-04-22 at 2 06 42 pm

A few people have remarked that the main label is not very descriptive, so we should probably reword it to something like:

"Enable optimized mobile theme"

or

"Use an optimized theme for mobile devices"

or

"Use a mobile-specific theme for smart phones"

cc @rickybanister / @richardmuscat for wording suggestions.

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #7036 

screen shot 2017-06-28 at 9 27 39 am

### CODE REVIEW

**Comment by dereksmart** [comment]
Calypso PR is here https://github.com/Automattic/wp-calypso/pull/15610

**Comment by kraftbj** [comment]
For a code review, 👍 from me. It picks up a text change for Comment Likes as well. If we're keeping the PR clean that should be out, but I'm fine with getting it in here.

**Comment by dereksmart** [comment]
Yeah it was just a result of the `module-heading` gulp script.

**Comment by rickybanister** [comment]
Excellent @dereksmart ship it.

**Comment by jeffgolenski** [comment]
👍

**Pull request merged**
