### PR TITLE
Revert gating to simple payments

### PR DESCRIPTION
**Pull request by millerf**
Fixes https://github.com/Automattic/gold/issues/52
Fixes https://github.com/Automattic/gold/issues/51

## Proposed changes:

* This PR reverts changes in https://github.com/Automattic/jetpack/pull/30432 related to Simple Payments
* It mainly straightforward as it looks like the block was only gated with `plan_check`. Please correct me if I am wrong.

### Other information:

- [X] Have you written new tests for your changes, if applicable?

## Jetpack product discussion

https://href.li/?https://wp.me/peKye1-7f#comment-43

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:
* TBD

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
Looks like we may have to revert the others as well for now:
pbNhbs-6QK-p2#comment-15819

Should we do it all in this PR to make the revert (and the follow-up cherry-pick) easier?

**Comment by millerf** [comment]
> Looks like we may have to revert the others as well for now:

I don't quite see the issue, as it has been available on Premium for a while: pbNhbs-6QK-p2#comment-15833 ...
Let's see what the decision ends up being. 

> Should we do it all in this PR to make the revert (and the follow-up cherry-pick) easier?

Yes, good approach!

**Comment by millerf** [comment]
> > Looks like we may have to revert the others as well for now:
> 
> I don't quite see the issue, as it has been available on Premium for a while: pbNhbs-6QK-p2#comment-15833 ... Let's see what the decision ends up being.
> 
> > Should we do it all in this PR to make the revert (and the follow-up cherry-pick) easier?
> 
> Yes, good approach!


@jeherve What do you think about:
- Leaving this as is it and merge it
- Creating a new PR reverting this one and https://github.com/Automattic/jetpack/pull/30432

I think it would make things simplier.

I am also working on https://github.com/Automattic/jetpack/pull/31103 to gate newsletters

**Comment by anomiex** [comment]
FYI, you might want to remove [this line from Jetpack's changelog](https://github.com/Automattic/jetpack/blob/9d8bbbe7086b30e20b022bd15df4825565af20a5/projects/plugins/jetpack/CHANGELOG.md?plain=1#L8) too, and double check for any other mentions in there.

**Comment by millerf** [comment]
> FYI, you might want to remove [this line from Jetpack's changelog](https://github.com/Automattic/jetpack/blob/9d8bbbe7086b30e20b022bd15df4825565af20a5/projects/plugins/jetpack/CHANGELOG.md?plain=1#L8) too, and double check for any other mentions in there.

The revert was cancelled ( pbNhbs-6QK-p2#comment-15861 ) go ahead with this PR.

**Comment by millerf** [comment]
> FYI, you might want to remove [this line from Jetpack's changelog](https://github.com/Automattic/jetpack/blob/9d8bbbe7086b30e20b022bd15df4825565af20a5/projects/plugins/jetpack/CHANGELOG.md?plain=1#L8) too, and double check for any other mentions in there.

It is actually still valid. Only one of the payment buttons was reverted...

**Review by jeherve — APPROVED** [review]

**Comment by anomiex** [comment]
It's not clear to me what exactly is going on here, the title and summary seem to not touch on https://github.com/Automattic/gold/issues/51 at all. But whatever. Next time please don't leave things until Friday of beta week, like we asked at the beginning of the month. Cherry-picked as 6925c138ca.

**Comment by millerf** [comment]
> It's not clear to me what exactly is going on here, the title and summary seem to not touch on https://github.com/Automattic/gold/issues/51 at all.

It started as a fix for https://github.com/Automattic/gold/issues/50, and I ended up throwing a fix for https://github.com/Automattic/gold/issues/51 at the very end, [which is basically a one-liner](https://github.com/Automattic/jetpack/pull/31067/files#diff-fa8258a2965aec2786974a5bd6052492c8f3a2b4679e88d41b42ed0f9122af25R90).

> Next time please don't leave things until Friday of beta week

Believe me, we tried to. But last week has been really hectic. 

Thanks for cherry-picking it @anomiex

**Pull request merged**
