### PR TITLE
Fix media links for tiled gallery

### LINKED ISSUE #16940: Square or Circular tiled gallery thumbnails link to square image when the original is rectangular
The following problem can be viewed when Jetpack Carousel is not used, in fact, no lightbox overlays at all. [The conversaton originally started on JP Support forum.](https://wordpress.org/support/topic/square-tile-galleries-show-square-images-2/)

#### Steps to reproduce the issue

1. Insert a tiled gallery block
2. Add vertical and horizontal images
3. Set the type to Square or Circular
4. Set the Link to the Media file
5. View the post and the square tiled gallery
6. Click on an image thumbnail to see a square image being presented rather than a vertical or horizontal rectangular one

#### What I expected
I would expect to see the original image linked with the proper aspect ratio.

Apparently, the link settings for the gallery need to be set to Media File, not to the Attachment Page. In the post, the link is indeed set to the Media file.

The post that started this all is below. But, that being a staging site, the content may disappear:
https://www.testbed.biz/tiled-gallery-samples/

You may notice another problem on that page too, but that's a different story!

### LINKED ISSUE #25015: Tiled Gallery in Reusable block: Link To Media File not showing full image
### Steps to Reproduce

1. Create a tiled gallery, using horizontal and/or vertical images
2. In the Block settings, set **Link To** to **Media File**

### A clear and concise description of what you expected to happen.

Media file should show in full.

### What happens

On Simple, Atomic with Gutenberg on/off, the image shows in full if Tiled Gallery is a regular block, but not if it is in a Reusable block.

troubleshooting

Ticket: 4278458-zd-woothemes

~Also filed in Jetpack, https://github.com/Automattic/jetpack/issues/20980~ Similar issue as in https://github.com/Automattic/jetpack/issues/16940 where the image doesn't show in full, regardless of whether it's in a Reusable block or not.

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes #25015
Fixes #16940

#### Changes proposed in this Pull Request:

* This PR updates the editor code for the Tiled Gallery block to _always_ link to the original media URL for the image when the "Link To" setting is set to "Media File".
  - Prior to this change, the Square Tiles and Circles layouts would link to the URL for the _currently displayed_ image, which would be a Photon-resized image for those formats
  - This maintains the existing behaviour for the Tiled Mosaic and Tiled Columns layouts
  - The PR also includes a block deprecation so we won't see block validation errors - we should smoothly switch to the new code

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

This is a bugfix, so no major discussion needed.

#### Does this pull request change what data or activity we track or use?

No changes to tracking.

#### Testing instructions:

* Set up a standalone site running WordPress 6.0 (so we have Gutenberg in core), and ensure the Jetpack and Jetpack Beta plugins are installed. (The site should _not_ be a WordPress.com Atomic site -- an ephemeral development site should be fine.)
* Ensure that the site is connected to Jetpack.
* Create a new post
* In the new post, add a Tiled Gallery block, and insert multiple non-square images
* Modify the style to be "Square Tiles" or "Circles", and set the "Link To" dropdown to be "Media File"
* View the markup using the code editor -- you should see the Photon-ised URL for the wrapping `<a>` tag around each image -- it will start with `i[0-2].wp.com` and should include an escaped `resize` URL parameter
* Duplicate the Tiled Gallery, and convert the new duplicate block to a reusable block
* Save and publish the post
* In a new tab, navigate to the post on your site
* Verify that clicking on the images in both galleries links to a square image that has a Photonised URL of the form `i[0-2].wp.com`
* In wp-admin, navigate to _Jetpack_ -> _Jetpack Beta_ and click on "Manage" for the Jetpack plugin
* In the "Feature Branch" field, enter `fix/tiled-gallery-media-links` and click on "Activate" to enable this branch
* Navigate to _Posts_ -> _All Posts_ and click on "Edit" for your post from above
* Ensure you force refresh the editor page to get the updated Javascript
* Verify that you don't see a warning about invalid block content
* Inspect the code for the standard block, and verify that the `href` values for the `<a>` tags around the images reference links on the site itself (i.e. `yoursite.tld/wp-content/uploads/*`), and the links don't include a `resize` URL parameter
* Publish the updates to the post
* Refresh the tab that was viewing the post on the site
* Verify that clicking on the images in the standard and reusable Tiled Galleries opens the full-sized image on the site.

Note that for WordPress.com sites, we don't use Photon directly, so I don't believe this specific replacement should impact those cases. However, we should also test the change on both Simple and Atomic sites via D86002-code and the Jetpack Beta plugin respectively. We should see no change in behaviour on those platforms.

### CODE REVIEW

**Review by mpkelly — DISMISSED** [review]
Looks fine and tested successfully using an Ephemeral Site. 

I think we could add a dedicated close button and keyboard shortcut to close fullscreen images, but that would be a different PR.

**Review by coder-karen — DISMISSED** [review]
Also works well on a Jetpack self-hosted (JN) site. 👍 

@bindlegirl heads up about this from the PR description, due to the block validation errors that will come up:

> This may push us to flag the compatibility impact more explicitly.

**Review by jeherve — DISMISSED** [review]
> NOTE: the upgrade will cause block validation issues for existing Tiled Gallery blocks

I would recommend creating a deprecation to handle that scenario, just like we've done for other blocks and for that specific block in the past whenever the saved markup changed:
https://github.com/Automattic/jetpack/tree/7d97ced29dbbf6bd5c7a5d85bb5d752d9245f1c7/projects/plugins/jetpack/extensions/blocks/tiled-gallery/deprecated

Until now we've always avoided validation issues in our blocks whenever possible.

**Comment by daledupreez** [comment]
Thanks for the pointers on block deprecation, @jeherve! That was definitely a TIL moment for me.

I've now implemented the deprecation in 5d26c9e7eb9c71492b031a3e666bd45f8c2da6bd, and we'll do another round of testing for this.

**Review by mpkelly — APPROVED** [review]
I completed the Test Plan successfully.

The existing Reusable Tiled Gallery still has links like `https://i1.wp.com/...` but it opens at full size. When I created a second Reusable Tiled Gallery by duplicating the standard black, it had a URL relative to the site (same-origin).

**Review by coder-karen — APPROVED** [review]

**Comment by daledupreez** [comment]
@jeherve, just a quick ping as I can't merge this PR until you've cleared your request for changes.

**Comment by daledupreez** [comment]
Thanks, @jeherve! 💖

**Comment by daledupreez** [comment]
I am not going to be online long enough to get this deployed to WordPress.com today, as I want to be around if any issues come up, especially relating to the block deprecation. I'll aim to tackle that on Monday morning.

**Comment by daledupreez** [comment]
Deployed to WordPress.com in r251471-wpcom.

**Pull request merged**
