### PR TITLE
Update minimum pnpm version to 7.5.0

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

It turns out pnpm 7.1.3 subtly changed the data written to the lock
file, which is why renovate PRs kept adding `dev: true` and `dev: false`
to the lock file which later PRs would remove.

Also, lets save 100 file changes in future pnpm version updates by
removing `.engines.pnpm` from all the projects' `package.json` files.
It's not needed, pnpm checks against the monorepo root anyway so that's
sufficient to enforce minimum versions. And `.engines` is stripped from
`package.json` before it's pushed to mirror repos, so it makes no
difference there either.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

no

#### Testing instructions:

* Is CI happy?
* Verify that the version restriction in the monorepo root package.json is applied appropriately in the various projects.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]

**Comment by anomiex** [comment]
Needs re-review after trunk merge and version bumps.

**Comment by coder-karen** [comment]
I'm not fully understanding how to test this out - when I run something like `jetpack test js-packages/config js` it leads to a pnpm error while this PR is checked out ( `Error: Command failed with exit code 1: pnpm install`). To properly test this would I need to update pnpm locally? 🤔

**Review by kraftbj — APPROVED** [review]

**Comment by anomiex** [comment]
> To properly test this would I need to update pnpm locally? :thinking:

Yes, you would.

**Comment by anomiex** [comment]
r248737-wpcom

**Pull request merged**
