### PR TITLE
Let's not just use `file_get_contents()` for better compat.

### PR DESCRIPTION
**Pull request by georgestephanis**

### CODE REVIEW

**Comment by jeherve** [comment]
This might cause some issues in some cases, as mentioned here:
https://github.com/Automattic/jetpack/pull/3742#discussion_r61246242

> We could use `wp_remote_get()` if the `$image_url` is prefixed by `http://` or `https://` however would need to use `file_get_contents()` for all other protocols and image paths anyway (ie. `/home/.../image.jpg` or `custom-file-wrapper://path/image.jpg`)

**Comment by georgestephanis** [comment]
Ah, thanks, I hadn't seen that.

Also other possible place -- https://github.com/Automattic/jetpack/blob/d9f57d6df1a0e1eb20cedd4c1505599bf7d6beaa/modules/likes.php#L504

**Comment by eliorivero** [comment]
Works fine with URLs, images are recognized, even with no extensions. Non images return false, which is correct too.
Loading through filesystem isn't working though.

I tested with something like 
```php
add_action( 'wp_footer', function() {
	$ton = new Tonesque( 'http://example.tld/wp-content/uploads/2029/08/image.jpg' );
	var_dump( $ton->grab_color() );
} );
```
and it works, you get the array with `r`, `g` and `b` keys, but replacing the URL with a path `/Users/someuser/Sites/someserver/wp-content/uploads/2029/08/image.jpg` doesn't

**Comment by lezama** [comment]
Personal opinion: I think we should add another method `imagecreatefromfile` instead of complicating things in `imagecreatefromurl`

**Comment by rcoll** [comment]
It appears that in PHP7, list() must be fed an integer-keyed array. I received the following when loading up Tonesque with a local file path:

`Notice:  Undefined offset: 0 in /home/jetpack-single.ftlwp.com/wp-content/plugins/jetpack/_inc/lib/tonesque.php on line 69
Notice:  Undefined offset: 1 in /home/jetpack-single.ftlwp.com/wp-content/plugins/jetpack/_inc/lib/tonesque.php on line 69
Warning:  imagecreatefromstring(): Empty string or invalid image in /home/jetpack-single.ftlwp.com/wp-content/plugins/jetpack/_inc/lib/tonesque.php on line 76
`

I just pushed a commit that should resolve this. Otherwise, everything LGTM and tests good.

**Comment by eliorivero** [comment]
LGTM! 🐑 Tested again with Ryu theme and this code and it works fine now
```php
add_action( 'wp_footer', function() {
    $ton = new Tonesque( 'http://example.tld/wp-content/uploads/2029/08/image.jpg' );
    var_dump( $ton->grab_color() );

    $ton = new Tonesque( '/Users/joedoe/Sites/joeserver/wp-content/uploads/2029/08/image.jpg );
    var_dump( $ton->grab_color() );
} );
```

**Pull request merged**
