### PR TITLE
Starter Plugin: Serve via Beta Plugin

### PR DESCRIPTION
**Pull request by kraftbj**
- Enable beta plugin to offer the Starter plugin

#### Changes proposed in this Pull Request:

* This plugin won't be served via w.org, so removing that and adding a slug for the beta plugin instead.
* A mirror repo has already been created.

#### Jetpack product discussion

To assist in testing changes to it. See https://github.com/Automattic/jetpack/pull/23759#issuecomment-1088193975

#### Does this pull request change what data or activity we track or use?

no

#### Testing instructions:

* Does this generate a manifest for the beta server?

### CODE REVIEW

**Comment by kraftbj** [comment]
I'm not a huge fan of having the wp slug in there when this isn't in the repo, but since it is meant to be a starter/skeleton plugin, I suppose it is better to have it than not?

**Comment by anomiex** [comment]
Will the CLI code that generates a plugin based on this need updating to delete the beta-plugin-slug that was added?

**Comment by kraftbj** [comment]
> Will the CLI code that generates a plugin based on this need updating to delete the beta-plugin-slug that was added?

That's a good question. I think early in dev when the plugin isn't actually published, it's probably fine to leave it, but remove it whenever it actually does land in the w.org repo?

**Comment by kraftbj** [comment]
2022-04-06 at 3 06 PM

**Comment by anomiex** [comment]
I was more referring to whether "beta-plugin-slug" would still be "jetpack-starter-plugin", but it looks like the CLI code does a global search-and-replace on "jetpack-starter-plugin" so it works out ok.

On the other hand, I note that the generated plugin winds up with "release-branch-prefix" still set to "starter-plugin" instead of the new plugin's name. 😀 That should probably be fixed at some point.

**Comment by anomiex** [comment]
BTW, looks like there's nothing special about specifying "beta-plugin-slug" rather than "wp-plugin-slug". The only difference is that some things only look for the latter. Mostly release stuff, and some i18n stuff uses "wp-plugin-slug" (but not "beta-plugin-slug") as a fallback if "textdomain" isn't set.

**Comment by anomiex** [comment]
> [IMAGE: 2022-04-06 at 3 06 PM](https://user-images.githubusercontent.com/88897/162061683-0a256332-283c-4a0f-931e-00ad07bade01.png)

Of note is that I had to fix some configuration on the jpbeta site to get that to work. The first time around [it was ignored](https://github.com/Automattic/jetpack/runs/5857547755?check_suite_focus=true#step:7:78).

**Comment by kraftbj** [comment]
> > [IMAGE: 2022-04-06 at 3 06 PM](https://user-images.githubusercontent.com/88897/162061683-0a256332-283c-4a0f-931e-00ad07bade01.png)
> 
> Of note is that I had to fix some configuration on the jpbeta site to get that to work. The first time around [it was ignored](https://github.com/Automattic/jetpack/runs/5857547755?check_suite_focus=true#step:7:78).

I thought there was a step I needed to do over there, but when it worked, I figured maybe not anymore ;-) Thanks.

**Comment by anomiex** [comment]
> I thought there was a step I needed to do over there, but when it worked, I figured maybe not anymore ;-) Thanks.

It looked like someone tried, but they kind of screwed it up.

**Review by anomiex — APPROVED** [review]
Anyway, let's go ahead and do it. We can always follow up on the beta-plugin-slug versus wp-plugin-slug thing later.

**Comment by kraftbj** [comment]
r243282-wpcom

**Comment by oskosk** [comment]
Thanks for this, I totally missed this PR yesterday

**Pull request merged**
