### PR TITLE
Explore new set of default modules

### PR DESCRIPTION
**Pull request by dereksmart**
This introduces a new set of default modules to play with. 

Context p1HpG7-6qm-p2

#### Testing instructions:

Since these only kick in for new sites, Jurassic.ninja is kinda the only way. 

https://jurassic.ninja/create?jetpack-beta&branch=update/default-modules&wp-debug-log

#### Proposed changelog entry for your changes:

N/A for now

### CODE REVIEW

**Comment by beaulebens** [comment]
I'm going to leave a raw list of notes here of things I noticed when trying this out, which don't "fit the narrative", or which seems to pose an issue of some sort;

**Pre Set Up**
- Connection banner says "You’re almost done. Set up Jetpack to boost your site performance and unlock powerful customization, marketing, and security tools."
- On the pre-connection page, I think we should hide the Mobile Apps promo until they're set up. There's only one thing we want them to do at that point, and that's set up/connect Jetpack.

**Set Up**
- Something weird going on here.
Screen Shot 2019-03-20 at 2 31 49 PM
- Plans grid was not focused on the security and performance offerings (although does mainly speak about those features).
Screen Shot 2019-03-20 at 2 33 13 PM
- I picked Premium (via credits) to see what the experience was like with a paid plan
- We talk about "powering up" your site -- might be better to just be more direct and saying we're activating and configuring their paid features.
- End of flow takes me back to wp-admin

**After Set Up**
- I landed on My Plan within Jetpack, with the Jump start panel. Jump start didn't really stand out that much, and might be better off being highlighted somehow better?
- Spacing between Jump start and the top box "Welcome to Jetpack Premium" was different to other spacing.
Screen Shot 2019-03-20 at 2 36 07 PM
- When I clicked around and got back to the Jetpack dashboard/At A Glance, I still got this JITM
Screen Shot 2019-03-20 at 2 36 47 PM
- Eventually I clicked the Jump start prompt to activate recommended features, without knowing what they were -- I think we should probably list/show/somehow explain right there what they're activating (and that it's all performance and security related).
- Once I'd hit Jump start, I then got the dialog/overlay for the Premium Plan. We might want to reorganize that (and the Personal/Professional ones) to prioritize performance/security features.
Screen Shot 2019-03-20 at 2 38 18 PM
- I activated everything in that list and clicked "Got It" at the bottom. I'm now dropped on the dashboard with no stats, and no real idea on what to do next. It says it's security-scanning me, and that I'll be backed up soon.
- "Plans" view in the plugin lists things other than security and performance.
- "Plans" view in the plugin has a big "Introducing Premium Themes" banner/display at the top, which feels much less relevant now

**Settings***
- Incorrect capitalization, and extra spacing at the bottom of the card for "Plugin autoupdates"
Screen Shot 2019-03-20 at 2 42 58 PM
- Maybe move "Sitemaps", "Site verification", and "Stats" from Traffic to Performance? Or we might need a third settings section that catches some of the not-quite-perfect-fit pieces that we still want to ship.
- There's no (obvious) way, other than digging to find the module list or using search (some of these don't show in search either) to interact with some features. Off the top of my head; Beautiful Math, Contact Form, Custom CSS, Extra Sidebar Widgets, Shortcode embeds, Tiled Galleries, WP.me Shortlinks, Widget visibility.

**Comment by beaulebens** [comment]
Also note that I got 2 emails, neither of which mentioned security or performance. I think I got the Ads one only because I enabled ads, since they showed up in the overlay/dialog when I purchased Premium;

Screen Shot 2019-03-20 at 3 07 43 PM
Screen Shot 2019-03-20 at 3 07 30 PM

(I connected using an existing WP.com/testing account, so I didn't get an email about that).

**Comment by beaulebens** [comment]
As a follow up to the above, I got another email -- this one focused on traffic generation, probably wants to be updated to talk about performance/security:

Screen Shot 2019-03-22 at 4 24 31 PM
Screen Shot 2019-03-22 at 4 24 41 PM
Screen Shot 2019-03-22 at 4 24 52 PM

**Comment by beaulebens** [comment]
And another email talking about all the other features:

Screen Shot 2019-03-24 at 5 38 29 PM
Screen Shot 2019-03-24 at 5 38 36 PM
Screen Shot 2019-03-24 at 5 38 43 PM

**Comment by eliorivero** [comment]
I've rebased master to include the latest changes I introduced to auto activation as part of the module prioritization project (like widgets, widget-visibility and others) so changed files went from 16 to 11. I think this is good to go in the context of module prioritization.

**Review by eliorivero — APPROVED** [review]
🐑

**Pull request merged**
