### PR TITLE
Instant Search: display price information on product results

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request:

* Request additional fields for Woo price when viewing product results.
* Display price and sale price when viewing product results.

The PR does not aim to implement final styling for product prices. We will also have to undertake further testing later with different types of product (subscriptions, free products, and so on).

Screen Shot 2021-02-10 at 16 01 16

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

On an Instant Search-enabled site with WooCommerce installed, search for a product and add`result_format=product` to the query string. Check that the product price is displayed.

Screen Shot 2021-01-08 at 16 03 32

On a product with a sale price, ensure that the regular price is displayed (struck through) along with the sale price.

#### Proposed changelog entry for your changes:

Not required yet. The product result format has not yet been released to end users.

### CODE REVIEW

**Comment by jeffgolenski** [comment]
❤️

**Review by jsnmoon — APPROVED** [review]
Excellent! Works as described.

Requires re-indexing your test site, so please ask anyone in @Automattic/jetpack-search if you require assistance with this. Specific instructions: P9xfpQ-Na-p2.

**Comment by jsnmoon** [comment]
I'm unable to merge this due to the `Required review` pre-commit check, so passing this along for Crew approval 👍

**Comment by bluefuton** [comment]
🚢 Shipped to wpcom in r220954-wpcom.

**Pull request merged**
