### PR TITLE
Recommendations: Add Jetpack Product Suggestions step

### PR DESCRIPTION
**Pull request by kallehauge**
### Changes proposed in this Pull Request:

* [API] Add support for new `/jetpack/v4/recommendations/product-suggestions` endpoint.
* [Plugin] Change the `illustrationPath` attribute of `<PromptLayout>` to be optional, so we can use the same layout component for full width content.
* [Plugin] Add a new `<MoneyBackGuarantee>` component.
* [Plugin] Add a new Query Data component to fetch Product Suggestions (`<QueryRecommendationsProductSuggestions>`). 
* [Plugin] Add a new Product Suggestions step in the Jetpack Assistant (done by adding it to the Recommendations routing system and two new components: `<ProductSuggestions>` and `<ProductSuggestion>`).
* [Plugin] Add a new hidden "landing page" like step to the Jetpack Assistant (`<ProductPurchased>`) that will only be displayed if a user is directly forwarded to it (used as return URL from the checkout)  

### Jetpack product discussion

* PT: pbNhbs-Yp-p2
* Design: p6TEKc-5bW-p2
* Task: 1161179020265237-as-1200537408139848
* API: D66016-code

### Does this pull request change what data or activity we track or use?

This Pull Request adds the following Analytics Tracking Events:

* `jetpack_recommendations_product_suggestion_click`: When a user selects one of the suggested products.
* `jetpack_recommendations_product_suggestion_learn_more_click`: When a user clicks one of the "Learn More" links located at the suggested products.
* `jetpack_recommendations_product_suggestion_purchased`: When a user has gone through checkout and been returned to the Jetpack Assistant.
* `jetpack_recommendations_product_suggestions_decide_later_click`: When a user skips the Purchase Product step.

### Testing instructions:

**Initial setup and how to find the Product Suggestion step**

1. Get a local version of the repository running.
2. Create a successful Jetpack connection (you can do this by connection the website with a Jetpack Free plan).
3. Go to `/wp-admin/admin.php?page=jetpack#/recommendations`.
4. On the second step of the Recommendations wizard you should see the Product Suggestions step.

**Things to test**

* Click on the Product `Learn More` links. These should open in a new tab.
* When you press the `Decide later` link you should be taken to either the `WooCommerce` step or `Monitor` step depending on your website.
* When you click the `Continue with [Product Name]` button you should be redirected to checkout where the product is pre-selected.
* When you are finished in the checkout you should be redirected to the new landing page which should display 3 bullets if you purchased Jetpack Backup Daily or 5 bullets if you selected Jetpack Security Daily.
* When you've purchased a product on the product suggestions step, you should no longer see any upsell/upgrade suggestions on the final summary screen with all the features.

### Screenshots

**Product Suggestion step: Desktop**

Screenshot 2021-08-24 at 23 51 57

**Product Suggestion step: Tablet**

Screenshot 2021-08-25 at 00 24 40

**Product Suggestion step: Phone**

Screenshot 2021-08-30 at 17 29 03

**Product Purchased step: Desktop**

Screenshot 2021-08-25 at 01 56 05

**Product Purchased step: Tablet**

Screenshot 2021-08-25 at 01 56 26

**Product Purchased step: Phone**

Screenshot 2021-08-25 at 01 57 26

**Product Purchased step: Jetpack Backup Daily example**

Screenshot 2021-08-25 at 14 36 11

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This looks good overall, nice work.

**********

I'll let Design weigh in on this, but maybe it would make sense to center things on mobile?

image

***********

In some cases (not sure what caused it), I would get a blank screen when the suggestions loaded, and a js error:

```
react-dom.min.js?ver=16.13.1:125 TypeError: o.map is not a function
    at admin.js?ver=10.1-alpha:formatted:42613
```
-- https://github.com/Automattic/jetpack/blob/86ea3570d5cea0d9a83a90e7e9bfd9e0dbeb4aec/projects/plugins/jetpack/_inc/client/recommendations/prompts/product-suggestions/index.jsx#L54

***********

I saw no benefits mentioned when upgrading to a Backup daily plan. Oddly enough, `purchasedProductSlug` was set to `false`:

Screenshot 2021-08-27 at 13 52 49

**Comment by kallehauge** [comment]
> I'll let Design weigh in on this, but maybe it would make sense to center things on mobile?

CC: @Automattic/jetpack-design (just to make sure Jeremy's comment isn't lost 😄  🔔  )

**Comment by kallehauge** [comment]
Thank you very much for the review @jeherve and your help with versioning numbers! 🙇 

---

> In some cases (not sure what caused it), I would get a blank screen when the suggestions loaded, and a js error:
> 
> ```
> react-dom.min.js?ver=16.13.1:125 TypeError: o.map is not a function
>     at admin.js?ver=10.1-alpha:formatted:42613
> ```

I have not been able to product the error by just using the Assistant but I'm assuming you experienced one of two scenarios:

1. You received an errors response from the Product Suggestions API endpoint which - from the previous code - was still a successful response and not an array which `.map` relies on.
2. The reducer gave us the default state instead of an array. 

Both basically means the same from a _"what can we do to avoid it"_ perspective: The error and response handling might not have been the best. So I've added an `isArray` condition as part of a better loading experience of <ProductSuggestions> which should eliminate us trying to iterate over suggestions before we're really, really ready.

Reference: 

* [New `isProductSuggestionsAvailable` logic that also add additional defensive code to avoid people directly accessing the product suggestions step if they're not supposed to](https://github.com/Automattic/jetpack/pull/20814/commits/1d66bd34817ab67e1111abdd164d6984819c3c5c).
* [The specific `isArray` logic from the commit mentioned above](https://github.com/Automattic/jetpack/pull/20814/commits/1d66bd34817ab67e1111abdd164d6984819c3c5c#diff-ed22086dc13e06f1bc3a8dfcf40218bca96473e32bad2f71348dc32af948078eR224).

---

> I saw no benefits mentioned when upgrading to a Backup daily plan. Oddly enough, `purchasedProductSlug` was set to `false`:

[The only reason `purchasedProductSlug` would be `false` is if we have to resort to the default value of `getDataByKey`](https://github.com/Automattic/jetpack/blob/abb10c155832ef50b4a46e92b4c7065c861cc894/projects/plugins/jetpack/_inc/client/state/recommendations/reducer.js#L162) and it looks like we faced one of the oldies here, where we try to store data while also redirecting the user to a new page (external in this case) and not just update the `state` like the rest of the steps do.
_(I'm still relatively new to React and worked from an assumptions about combining `onClick` and `useCallback` would help us with this scenario but that is what happens when you work from assumptions and not validation 😅 )._

[I've reworked the logic so we `preventDefault` and trigger the redirect at the end of the callback with `window.location.href` instead and could no longer reproduce the issue myself](https://github.com/Automattic/jetpack/pull/20814/commits/abb10c155832ef50b4a46e92b4c7065c861cc894)

**Comment by Luchadores** [comment]
Looks good to me 🙌 And liked promised, here is the screenshot for the mobile change regarding the pricing position.
image

Thank you! 🚀

**Comment by kallehauge** [comment]
> Looks good to me 🙌 And liked promised, here is the screenshot for the mobile change regarding the pricing position.

Awesome work! I have implemented the change and updated the screenshot in the PR description. 

Related:

* p1630330099088000-slack-C0D96691V

**Review by sdixon194 — APPROVED** [review]
This works well for me! Let's do it 👍

**Comment by anomiex** [comment]
r231018-wpcom

**Pull request merged**
