### PR TITLE
Change from old php4 style constructor.

### LINKED ISSUE #2323: Deprecate PHP4 Style Constructors
A recent update of WordPress core shows the PHP 4 compatible method of defining a widget using WP_Widget::WP_Widget( ... ) is being deprecated.  There are several Jetpack widget modules containing these backwards compatible calls:

modules/subscription.php - Line 567
modules/widgets/gallery.php - Line 26
modules/widgets/rsslinks-widget.php - Line 13

My local log is flooding with these errors, so I have locally converted them from $this->WP_Widget( ... ) to parent::__construct( ... ). 

If the intent is to remain PHP 4 compatible, then each of these calls could be wrapped in a PHP version check, otherwise, I suggest updating these to call the constructor directly.  Thanks!

### PR DESCRIPTION
**Pull request by georgestephanis**
Fixes #2323

### CODE REVIEW

**Comment by kraftbj** [comment]
@georgestephanis anything left outstanding on this or ready for review/merging?

**Comment by kraftbj** [comment]
Marking for review so we can get it into master for those on master and trunk.

**Comment by georgestephanis** [comment]
@dereksmart: This needs to hit, at the very least at the 3.6.1 point release whenever that lands.  It'd be nice to have it hit for 3.6, but at this point I'm not holding my breath.

**Comment by danielbachhuber** [comment]
FWIW, this issue is currently bricking everyone's VIP Quickstart instances, which are set to auto-update trunk on cron

cc @joshbetz @nickdaugherty

**Comment by joshbetz** [comment]
> FWIW, this issue is currently bricking everyone's VIP Quickstart instances, which are set to auto-update trunk on cron

Jetpack shouldn't update on cron, but we still obviously need to get this fixed.

**Comment by danielbachhuber** [comment]
> Jetpack shouldn't update on cron

Er, I meant WordPress trunk

**Comment by georgestephanis** [comment]
Well, now that 3.6 is shipped, let's just get #2324 merged in.  I'll do it now.

@danielbachhuber Are you running Jetpack Trunk in that, or the release version?

**Comment by danielbachhuber** [comment]
> Well, now that 3.6 is shipped, let's just get #2324 merged in. I'll do it now.

Thanks!

> Are you running Jetpack Trunk in that, or the release version?

I'm running trunk — I have a cron entry to auto-update.

**Pull request merged**
