### PR TITLE
Shortcodes: do not overwrite Core's Instagram oEmbed in new editor

### LINKED ISSUE #9331: removal of instagram providor breaks proxy requests
This is easiest to see inside Gutenberg. 

Essentially, the removal of the instagram providor in `jetpack/modules/shortcodes/instagram.php` is causing the instagram matcher to not be present in `WP_Embed:get_providor` during oembed proxy REST requests such as `/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fwww.instagram.com
%2Fp%2FBbba7EYljLv%2F`

To reproduce, make sure the instagram shortcode is active in Jetpack ( Not sure how to do that, maybe it's a default?) and try to embed an instagram post into Gutenebrg. 

see the related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/3499

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #9331

#### Changes proposed in this Pull Request:

When using the block editor, let's rely on core's Instagram embed method. We don't really need to overwrite it to use our own there.

#### Testing instructions:

* Go to the old Jetpack > Modules list and make sure that the Shortcode embeds module is active.
* Create multiple posts:
    - using the new block editor, and pasting the following URL on its own line: `https://www.instagram.com/p/BnMO9vRleEx/`
    - using the new block editor, and pasting the following URL on its own line inside a classic block: `https://www.instagram.com/p/BnMO9vRleEx/`
    - using the new block editor, and pasting the following on its own line in a classic block: `[instagram url=https://www.instagram.com/p/BnMO9vRleEx/]`
* Make sure the embeds work well (no errors on the page or in the browser console) in the editor and on the frontend.

#### Proposed changelog entry for your changes:

* Instagram: make sure Instagram embeds work well in the new block editor.

### CODE REVIEW

**Comment by dereksmart** [comment]
I'm still getting a 404 on the /oembed url in the editor view with this patch applied.

**Comment by oskosk** [comment]
I cannot reproduce the original issue. Tested with WordPress 5 and with WordPress 4.9.9 running the Gutenberg plugin. Shortcodes module was definitely active.

**Comment by jeherve** [comment]
Related discussion: 9GBOq-p2

**Review by brbrr — APPROVED** [review]
Works well, and renders as expected on the frontend. FWIW - rendered direct link embed in classic editor block falling back to URL after post save/update. This does not affect frontend rendering.

**Comment by jeherve** [comment]
> rendered direct link embed in classic editor block falling back to URL after post save/update.

Yes, I believe this is to be expected. The same happens with galleries as well.

**Comment by amgmbs** [comment]
I've just installed Jetpack on a website yesterday and it broke the instagram oembeds. When I deactivate Jetpack, the embeds are fine, when I enable it we see the Instagram frame without any photo or video.

We do not use Gutenberg (our authors believe it's buggy with old posts but this is a different story)

**Comment by ockham** [comment]
Closing in favor of #17356.

**Pull request closed without merging**
