### PR TITLE
Fix blogroll block unhelpful error when user not connected

### PR DESCRIPTION
**Pull request by CodeyGuyDylan**
## Proposed changes:

* Create a new shared block component that is specific for connection nudges
* Replace the specific connection banner for Jetpack AI with the shared block
* Add new shared block to blogroll to show connection nudge when user is not connected instead of error

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

P2: pbNhbs-bHl-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

1. Checkout this branch via the Jetpack Beta plugin or your local dev environment
2. With a site that is site-connected but not user connected, create a new blog post
3. Try to add the Blogroll block to the post
4. You should be met with a connection nudge instead of an unhelpful red error
image
5. Try to add the AI block as well and ensure the connection nudges look the same (there are slight differences as I didn't want to affect the AI nudge)
image
6. Click the CTA on the blogroll connection nudge and connect your user account. Go back to the blog post and ensure the blogroll block works as expected
image

Bonus!

If you'd like, you can try connecting a one user to your site and edit the blog post with a different one. Any connected user account should allow the block to be used.

### CODE REVIEW

**Review by grzegorz-cp — DISMISSED** [review]
It looks good and works as described for the main connected account.

I created a new Author account for a JN blog, but it caused an error in the Blogroll block - `Whoops, we have encountered an error. Please try again later.`. AI block worked fine for both users.

**Comment by CodeyGuyDylan** [comment]
> It looks good and works as described for the main connected account.
> 
> I created a new Author account for a JN blog, but it caused an error in the Blogroll block - `Whoops, we have encountered an error. Please try again later.`. AI block worked fine for both users.

Let me take a look at this, I meant for it to work for all cases

**Comment by CodeyGuyDylan** [comment]
Ah ok, this block actually requires a user connection for the user that is trying to use the block. Not just a connected user on the site. That makes sense since it is supposed to show personalized recommendations. I'll get that updated

**Comment by CodeyGuyDylan** [comment]
It looks like the payment buttons are the same, I will update those as well

**Review by grzegorz-cp — APPROVED** [review]
Thanks for making the changes 👍

**Pull request merged**
