### PR TITLE
Search: Fix Customizer and styling bugs introduced in 9.6

### LINKED ISSUE #19420: Instant Search: dark mode ordering options are not visible in IE11
> Dark mode ordering options do not have good colors and make text unreadable.

jetpack-beta-search-dark-mode-order-colors

Original report: p8oabR-DS-p2#comment-5202

### LINKED ISSUE #19421: Instant Search: issues saving in the Customizer in IE11
> Customizer “is not saving” when doing Jetpack Search changes, but they reflect on the front-end.

When attempting to save changes in the Customizer, JS errors happen, and the changes aren't marked as saved even though they were:

customizer-save-issue

Original report: p8oabR-DS-p2#comment-5203

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #19420, fixes #19421.

#### Changes proposed in this Pull Request:
* Fixes a bug preventing sort select in the product layout from being legible in the dark theme for IE11.
* Fixes a bug that misaligns the sort select in the product layout.
* Fixes a Customizer bug that prevents IE11 users from saving their changes within the Customizer.
* Fixes a Customizer bug that summons the search modal scrolled halfway down the page.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your site with a Jetpack Search subscription.
* In IE11, enable the product layout in the Jetpack Search section. Ensure that the preview summons the Jetpack Search modal upon (1) opening the Jetpack Search section and (2) changing the search layout, if necessary.
* Summon the search modal in IE11. Ensure that the sort select is legible.

### CODE REVIEW

**Comment by kangzj** [comment]
Hi @jsnmoon, thanks for the fixes 👍 

> Fixes a visual bug preventing sort select in the product layout from being legible in the dark theme for IE11.

> Fixes a visual bug that misaligns the sort select in the product layout.

Tested working.

> Fixes a Customizer bug that prevents IE11 users from saving their changes within the Customizer.

I'm able to save settings in customizer, but there's a script error complaining about [line 20 in customize-controls.js](https://github.com/Automattic/jetpack/blob/ba06c5ec4928a7bb66b07faf3037fdcbc04e1e76/projects/plugins/jetpack/modules/search/customize-controls/customize-controls.js#L20)

Markup on 2021-04-06 at 16:31:44

Really hope we could drop IE11 in the near future, eh?

**Review by kangzj — APPROVED** [review]
Thanks Jason, It works perfectly on IE11 (and regressed on Firefox).

**Review by sdixon194 — APPROVED** [review]
Wew, testing this was fun. Works for me! Also pushed a merge so it would pass the PR up to date check.

**Comment by jsnmoon** [comment]
> Wew, testing this was fun. Works for me! Also pushed a merge so it would pass the PR up to date check.

Thanks for the review, @sdixon194! :)

**Comment by jsnmoon** [comment]
Deployed in r223930-wpcom.

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.6` in 9f3184065bc16ba6a54af4fa56ddfd2ca51c67a9

**Pull request merged**
