### PR TITLE
Change `Inbox` menu name to `My Mailboxes`

### PR DESCRIPTION
**Pull request by olaseni**
Change menu name from `Inbox` to `My Mailboxes`. Rename relevant symbols, as well as route

## Proposed changes:

* Rename the `Inbox` menu name to `My Mailboxes`
* Rename all functions, comments and tests referring to the previous name
* Update tests as well

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Follow the directives specified [here](https://github.com/Automattic/jetpack/pull/32992#issuecomment-1715267300) to test in both Simple and Atomic sites.
* Go to your Calypso dashboard
* Confirm that the previous `Inbox` menu is now named `My Mailboxes` and pointing to `/mailboxes`.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This looks good, but I assume we should wait to merge this until https://github.com/Automattic/wp-calypso/pull/81666 is merged?

**Comment by olaseni** [comment]
> This looks good, but I assume we should wait to merge this until [Automattic/wp-calypso#81666](https://github.com/Automattic/wp-calypso/pull/81666) is merged?

Yes please. Thanks  @jeherve for looking out.

We additionally need the route added by Systems as well. I have added a `[DO NOT MERGE]` label for now.

**Review by wongasy — APPROVED** [review]
LGTM! 

I was able to test both atomic and simple sites following these https://github.com/Automattic/jetpack/pull/32992#issuecomment-1715267300.

**Atomic site:**

atomic-mailboxes

atomic-mailboxes-link

**Simple site:**

simple-mailboxes

simple-mailboxes-link

**Comment by olaseni** [comment]
> We additionally need the route added by Systems as well. I have added a `[DO NOT MERGE]` label for now.

Both requirements are met. I'll remove the `[DO NOT MERGE]` label

**Comment by olaseni** [comment]
@jeherve can I go ahead and merge?

**Comment by jeherve** [comment]
Yup, that's good to merge if the other pieces are ready!

**Pull request merged**
