### PR TITLE
Adds a Linter to check for URLs that should be added using Redirect

### PR DESCRIPTION
**Pull request by leogermani**
After we deployed the "Redirect Everything" project on https://github.com/Automattic/jetpack/pull/15140, we want to make sure that future links are added using our Redirect service.

This PR adds a new sniffer to phpcs that will look for strings containing URLs to some automattic domains and throw a warning if they are  not being added using the redirect function.

### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* It adds a sniffer to our phpcs rules

### Testing instructions:

This is going to be easier if you try it on a single file. So choose a PHP file to work with and run `phpcs` against it:

```
yarn php:lint myfile.php
```
See the `$blacklist` variable

Now test it with different situations:

```PHP
use Automattic\Jetpack\Redirect;
// ...

$x = 'https://wordpress.com/any'; // should throw warning

$x = Redirect::get_url( 'https://wordpress.com/any' ); // should NOT throw warning

$var = array(
	'whatever',
	__( 'anything', 'jetpack' ),
	'https://subdomain.vaultpress.com', // should throw warning
);

?>
	<a href="http://akismet.com">Link</a> <!-- should throw warning -->
<?php

if ( true ) {
	foreach ( $var as $v ) {
		echo esc_url( 'http://super.videopress.com' ); // should throw warning
		echo esc_url( Redirect::get_url( 'http://super.videopress.com' ) ); // should NOT throw warning
	}

	$multi_line = Redirect::get_url(
		'https://support.jetpack.com', // should NOT throw warning
		array( 'site' => 'example.org )
	);
}
```
#### Feedback wanted

* Is `bin` folder a good place for it?
* Run it in random files to have a feel of how many false positives it triggers

Note: I couldn't figure out an easy way to run only this sniffer in the whole code. In theory, you can call `vendor/bin/phpcs` passing the `--sniffs` parameter, but it didn't work for me. If you know how to do this, please share

(what I did was temporarily delete all rules from `.phpcs.xml.dist` (except `PHPCompatibilityWP`) and then run `yarn php:compatibility`)

### CODE REVIEW

**Comment by kraftbj** [comment]
This may be a bit too noisy.

For example, `public $service_url = 'https://public-api.wordpress.com/rest/v1.1/';` throws an error ( https://github.com/Automattic/jetpack/blob/8.4/modules/widgets/wordpress-post-widget/class.jetpack-display-posts-widget-base.php#L24 ).

In top-posts.php: `'gravatar_default'    => apply_filters( 'jetpack_static_url', set_url_scheme( 'https://en.wordpress.com/i/logo/white-gray-80.png' ) ),`

Also: 
```	
$link = esc_url( Redirect::get_url( 'jetpack-support-getting-more-views-and-traffic' ) );
			if ( defined( 'IS_WPCOM' ) && IS_WPCOM ) {
				$link = 'https://en.support.wordpress.com/getting-more-site-traffic/';
			}
```
Though, that one might be a legit case of needing to use the redirect class.

Another one from social-media-icons.php:
`'wordpress'  => array( 'WordPress.org', 'https://profiles.wordpress.org/%s/' ),`
listing services for social media icons.

4 of the 5 times it errored would be a false positive IMO, which is a bit too high for me without more thought.

I, likewise, deleted all of the rules except for phpcompatibility, then ran `vendor/bin/phpcs modules`, then started reviewing from the bottom up.

**Comment by leogermani** [comment]
> 4 of the 5 times it errored would be a false positive IMO, which is a bit too high for me without more thought.

Yep... agree... I'm just thinking how we could improve this... First thing that comes to my mind is to create a whitelist based on the errors we got now...

**Comment by leogermani** [comment]
I had a close look at the sniffer output in the whole code.

It was throwing **697 warnings** (see https://gist.github.com/leogermani/e971dd67916949c038af8b7eb998aa68) containing a total of **451 unique URLs** (see https://gist.github.com/leogermani/7f5852aa6a7a76f899f44b5ae6aff126)

I've made some changes, whitelisting a few domains and file extensions.

The total warning **dropped from 697 to 449**. See https://gist.github.com/leogermani/52e23074bacd397ed2e7f87b5e1285ec

## Black list or White list?

We had a discussion on the ESLint issue (#15555) on whether we should look only for a8c domains or if we should look for all domains.

I ran a test to see what the results would be if we were searching for any URL.

We would have:

**1521 warnings** - see https://gist.github.com/leogermani/adfb17e7c6bc2c9ba06b3b91b33a56f1
**860 unique URLs** - see https://gist.github.com/leogermani/c7783954bc750b79e36674039ff5d260

This is still under discussion, if anyone want to have a look at the sniffer outputs linked above.

**Comment by kraftbj** [comment]
I still think this is too noisy. Looking at the first twenty results:

```
1
/home/leo/develop/jetpack/class.json-api-endpoints.php Line 407
'https://videos.files.wordpress.com/'
https://videos.files.wordpress.com/
```
This is the `needle` in a `strpos` function call. It must be what it is.


```2
/home/leo/develop/jetpack/class.json-api-endpoints.php Line 866
			<td class="type api-index-item-title">https://public-api.wordpress.com/rest/v
https://public-api.wordpress.com/rest/v
```

This is an outputted URL as part of a self-documenting function of the API. If it was a link, maybe need the redirect, but as display text, no.

```
3
/home/leo/develop/jetpack/_inc/class.jetpack-provision.php Line 46
'Can not provision a plan while in safe mode. See: https://jetpack.com/support/safe-mode/'
https://jetpack.com/support/safe-mode/
```

This is text inside a WP_Error. I could see the argument of having it within a Redirect call. I'm not sure it should be though.

```
4
/home/leo/develop/jetpack/_inc/lib/class-jetpack-mapbox-helper.php Line 60
'https://public-api.wordpress.com/wpcom/v2/sites/'
https://public-api.wordpress.com/wpcom/v2/sites/
```
This is the request URL for an API call -- and an incomplete URL at that. The whole line is `		$request_url = 'https://public-api.wordpress.com/wpcom/v2/sites/' . $site_id . '/mapbox';`.

```
5
/home/leo/develop/jetpack/_inc/lib/components.php Line 98
"https://wordpress.com/checkout/${site_slug}/${plan_path_slug}"
https://wordpress.com/checkout/${site_slug}/${plan_path_slug}
```

This is for the upgrade nudge. At first look, probably a good use of the Redirect package.

```
6
/home/leo/develop/jetpack/_inc/lib/admin-pages/class-jetpack-about-page.php Line 198
'For even more of our WordPress plugins, please <a href="https://profiles.wordpress.org/automattic/#content-plugins" target="_blank" rel="noopener noreferrer" class="jptracks" data-jptracks-name="jetpack_about_wporg_profile">take a look at our WordPress.org profile</a>.'
https://profiles.wordpress.org/automattic/#content-plugins
```

This is a link to our plugins on WordPress.org. I don't know why we would need to change where this link is landing. With the redirect package, we can track it (maybe we can already through Tracks, but haven't looked if we load in on that page). To me, not sure about it but could be valid.

```
7
/home/leo/develop/jetpack/_inc/lib/admin-pages/class-jetpack-about-page.php Line 535
'https://public-api.wordpress.com/wpcom/v2/jetpack-about'
https://public-api.wordpress.com/wpcom/v2/jetpack-about
```
API URL; should not be Redirect.

```
8
/home/leo/develop/jetpack/_inc/lib/class.media-summary.php Line 95
'https://videos.files.wordpress.com/%1$s/%2$s'
https://videos.files.wordpress.com/%1$s/%2$s
```

This is going to be used as part of returning a media summary item for a post (e.g. a post with a VideoPress embed could potentially return this value as the best media item for this post). Should not be redirected as this would be user/customer content.

```
9
/home/leo/develop/jetpack/_inc/lib/plugins.php Line 99
"https://downloads.wordpress.org/plugin/$plugin_slug.latest-stable.zip"
https://downloads.wordpress.org/plugin/$plugin_slug.latest-stable.zip
```
This is used by Jetpack to generate the link when installing a plugin. Should not be redirected.

```
10
/home/leo/develop/jetpack/_inc/lib/class.jetpack-keyring-service-helper.php Line 107
'https://public-api.wordpress.com/connect/?jetpack=publicize'
https://public-api.wordpress.com/connect/?jetpack=publicize
```

Incomplete URL. More query args are added onto to it which are needed.

```
11
/home/leo/develop/jetpack/class.jetpack.php Line 5883
'https://s-ssl.wordpress.com/'
https://s-ssl.wordpress.com/
```
Part of a `preg_replace` call. Should not be Redirect'd.

```
12
/home/leo/develop/jetpack/class.jetpack.php Line 6188
'https://jetpack.com/is-idc-allowed/'
https://jetpack.com/is-idc-allowed/
```

This is part of a remote get call to jetpack.com to see if the IDC resolution process is on (originally a kill switch in case the function actually broke horribly in production). Should not be redirected.

```
13
/home/leo/develop/jetpack/class.jetpack.php Line 7001
'https://akismet.com/?utm_source=jetpack&utm_medium=link&utm_campaign=Jetpack%20Dashboard%20Widget%20Footer%20Link'
https://akismet.com/?utm_source=jetpack&utm_medium=link&utm_campaign=Jetpack%20Dashboard%20Widget%20Footer%20Link
```

Seems like a good candidate.

```
14
/home/leo/develop/jetpack/class.jetpack.php Line 7194
'https://wpcalypso.wordpress.com/'
https://wpcalypso.wordpress.com/

15
/home/leo/develop/jetpack/class.jetpack.php Line 7196
'https://horizon.wordpress.com/'
https://horizon.wordpress.com/

16
/home/leo/develop/jetpack/class.jetpack.php Line 7198
'https://wordpress.com/'
https://wordpress.com/
```

These three are part of a check to determine the Calypso env. Should not be Redirected.

```
17
/home/leo/develop/jetpack/json-endpoints/class.wpcom-json-api-list-media-v1-2-endpoint.php Line 44
'https://public-api.wordpress.com/rest/v1.2/sites/82974409/media'
https://public-api.wordpress.com/rest/v1.2/sites/82974409/media

18
/home/leo/develop/jetpack/json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php Line 15
'https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/posts/7'
https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/posts/7

19
/home/leo/develop/jetpack/json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php Line 30
'https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/posts/slug:blogging-and-stuff'
https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/posts/slug:blogging-and-stuff

20
/home/leo/develop/jetpack/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php Line 19
"<code>curl \<br />--form 'media[]=@/path/to/file.jpg' \<br />-H 'Authorization: BEARER your-token' \<br />'https://public-api.wordpress.com/rest/v1/sites/123/media/new'</code>"
https://public-api.wordpress.com/rest/v1/sites/123/media/new
```

Part of REST API docs for example requests. Should not be Redirected.

By my path, of the first 20 hits, 15 can not use the Redirect library for technical reasons. Ignoring that I'm not certain the other 5 should be, that's still a 75% error rate for the sniff. That's too high.

We can likely exclude "public-api.wordpress.com", which would cut down on a lot of false flags.

The sniff should likely check to see if the URL is within a function like `strpos`, `preg_replace`, etc and related functions since if it is included there, it isn't meant to be transversed as a hyperlink.

**Comment by leogermani** [comment]
We have been discussing that the approach here still needs more thought. Markin as In Progress for now

**Comment by jeherve** [comment]
I'll close this PR for now because of the lack of activity on this. We can always reopen in the future if needed, but it will need a rebase, so it may be easier to start a new PR at this point.

**Pull request closed without merging**
