### PR TITLE
Social: Fix the check for Social Image Generator for the media picker

### PR DESCRIPTION
**Pull request by pablinos**
The check for Social Image Generator was checking the current post config twice, rather than the config for the post and the feature availability, and so the media picker was never being disabled.

## Proposed changes:

This swaps the `isSocialImageGeneratorEnabled` prop for `isSocialImageGeneratorAvailable` so we check for the feature availability

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* With a site with the advanced plan, enable SIG in the sidebar
* With this change the media picker should be disabled with a notice. Without it, nothing will happen with the media picker.

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
What happens if a user already had a media added and then enabled SIG?

Screenshot 2023-05-24 at 12 17 36 PM

The remove (X) icon on the media is not clickable.

**Comment by pablinos** [comment]
> What happens if a user already had a media added and then enabled SIG?

I think that's fine. We're ignoring that image in those circumstances, which is why it gets greyed out.

**Review by manzoorwanijk — DISMISSED** [review]
Works as expected

**Review by spsiddarthan — DISMISSED** [review]
This works well for me! Tested it both on Social and Jetpack.

**Review by spsiddarthan — APPROVED** [review]

**Pull request merged**
