### PR TITLE
Jetpack AI: Add machinery to generate audio transcriptions

### LINKED ISSUE #35548: Voice to Content: handle the audio recording “done” event to create the transcript
Steps:

- get a JWT token for the request
- upload the audio for transcription
   - the API is being created by #32829, make sure the request is created on the way the API expects it
- use a “loading” string/messaging to inform the user that some processing is going on
- when the transcription returns, save it on the application state and trigger the post-processing action (may use an event, for example “transcription-ready”)

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #35548.

## Proposed changes:

* Created a `transcribeAudio` helper function on the `ai-client` package to call the transcription endpoint
* Created an `useAudioTranscription` hook on the `ai-client` package to abstract details from the helper function and simpler usage on React
* Created a simple, throwaway component on the current Voice-To-Content block implementation to test/demo the hook usage

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor
* Open the browser console to watch the debug messages (make sure to enable it with `localStorage.setItem( 'debug', '*' )`
* Insert a "Voice-to-Content" block
* You will notice a button to pick an audio file for transcription:

Screenshot 2024-02-15 at 14 41 53

* Click it and choose a short audio file (tip: download an OpenAI demo file at https://cdn.openai.com/whisper/draft-20220913a/micro-machines.wav)
* Once you choose the file, you will see some debug messages on the console, related to fetching a JWT token as well as requesting the transcription:

Screenshot 2024-02-14 at 16 02 46

* When the transcription is done, you will see the content of it on the console as well:

Screenshot 2024-02-15 at 14 41 44

* Remember this flow is just a way to **test it**, the important thing is the internal flow to get a token and request the transcription, as well as handling the events from it
* We will need to adjust the hook usage once #35547 is ready
* **Known issue:** the backend is refusing `mp3` files because the is `audio/mpeg`, and this type is not on the list of allowed types (it's allowing `audio/mp3` instead); D138285-code will fix it
   * Tip: use a `mp3` file to test the error handling, to see an error message on the console:

Screenshot 2024-02-15 at 14 53 22

### CODE REVIEW

**Review by CGastrell — DISMISSED** [review]
Code looks good, flow worked both successfully and failing (uploaded m4a file). Would love to see us keeping track on things so we keep feeding our dashboards, but we can follow up on the matter. :shipit:

**Review by CGastrell — DISMISSED** [review]
Change looks good, just a follow up question: is this new api-fetch mod something we should also be using from other places on our code (ai-client)?

:shipit:

**Comment by lhkowalski** [comment]
> is this new api-fetch mod something we should also be using from other places on our code (ai-client)?

@CGastrell Yes. In fact, we already updated all the places that use it. Not doing it would break the build step, after the merge of #35453. 

There is a ticket to solve the typing on Gutenberg code base, that would be the definitive solution: https://github.com/WordPress/gutenberg/issues/59087.

**Review by CGastrell — APPROVED** [review]
Correcto! :shipit:

**Pull request merged**
