### PR TITLE
VideoPress Block: Add setting for playing video inline

### PR DESCRIPTION
**Pull request by roundhill**
We added support to the VideoPress player to support the `playsinline` attribute which will prevent a video from automatically playing full screen when on mobile. This PR adds a user-facing UI for that attribute to be set.

Screen Shot 2021-03-29 at 2 01 09 PM

#### Changes proposed in this Pull Request:
* Adds a new toggle to the VideoPress block settings (disabled by default) that will allow a user to set if the video should be played inline in the browser.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Before applying PR, add a VideoPress block to a post with a video and save it.
* Apply the PR and rebuild Jetpack. Load up the post you saved to ensure the block still loads properly. The `Plays Inline` setting should be untoggled.
* Add another new post and add a video block. Turn on the `Plays Inline` toggle, and publish the post. 
* Inspect the video, and you should see the `playsinline` attribute applied to the `video` tag.
* Bring up the url on a mobile device (I tested on iPhone 12). Pressing play should play the video inline on the page, not taking you full screen.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
While the PR adds the attribute well, I have some questions:

1. I don't see a difference in behaviour in Chrome on my Android device. Is that expected?
2. "Play Inline" doesn't really tell us much about what the toggle will change in our video? Could we add some help text, like it's done for the Autoplay toggle?

**Comment by roundhill** [comment]
> * I don't see a difference in behaviour in Chrome on my Android device. Is that expected?

Chrome doesn't go full-screen by default, so yeah that's expected. I think this is mainly for iOS.

> * "Play Inline" doesn't really tell us much about what the toggle will change in our video? Could we add some help text, like it's done for the Autoplay toggle?

Nice idea but it kinda sticks out like a sore thumb:

Screen Shot 2021-03-31 at 8 56 07 AM

It'd be nice if the `ToggleControl` could do a hover tooltip but I didn't see a way to add that?

**Comment by jeherve** [comment]
> Nice idea but it kinda sticks out like a sore thumb:

I didn't find this too disturbing since it only appears when the toggle is on, and since that's already how the Autoplay toggle works:

image

Maybe that's just me though  ¯\_(ツ)_/¯

I'll let someone else weigh in on this. :)

**Comment by jeherve** [comment]
Internal reference: r223581-wpcom

**Review by jeherve — APPROVED** [review]
Since this is already committed to WordPress.com, let's keep the codebases in sync. We can see if we get feedback from post authors about what the new setting means.

**Pull request merged**
