### PR TITLE
Newsletter: change default reply-to option from "no reply" to "comments"

### PR DESCRIPTION
**Pull request by simison**
Addresses https://github.com/Automattic/jetpack/issues/39655

## Proposed changes:

* Changes  default from "no-reply" to "comment"
* Changes order of options in settings from "no reply, comment, author" to "comment, author, no reply". 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Create a new site; it should default to "reply as comments" for newsletters
* Try changing the settings for reply-to

### CODE REVIEW

**Comment by crisbusquets** [comment]
@simison I tried to use a JN site to test this, but I can't connect Jetpack. It's stuck here:
Screenshot 2024-10-07 at 11 58 26

**Comment by simison** [comment]
@crisbusquets oh I'm still in progress with the code — I'll ping you when it's ready for test.

**Review by lezama — APPROVED** [review]
looking good!

**Comment by lezama** [comment]
Screenshot 2024-10-07 at 10 15 57 PM

**Comment by simison** [comment]
Tested on a brand new site as well

Screenshot 2024-10-08 at 13 21 07

**Pull request merged**
