### PR TITLE
JS Components: Fix multiline visual issue in Alert component

### PR DESCRIPTION
**Pull request by retrofox**
To fix this visual issue, this PR wrappers the icon with a div element, and tweaks/updates the styles on it.

Fixes #

#### Changes proposed in this Pull Request:

* JS Components: Fix multiline visual issue in Alert component

#### Testing instructions:

* Use storybook
* Go to Alert story: http://localhost:50240/?path=/docs/js-packages-components-alert--default
* Play with the Alert component: add long content to create multi-lines in the message

before | after
------|------
Screen Shot 2022-06-20 at 1 43 41 PM |  image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202469108953672

### CODE REVIEW

**Comment by leogermani** [comment]
Question: Would it look better if the icon was vertical aligned at the top?

**Comment by retrofox** [comment]
> Question: Would it look better if the icon was vertical aligned at the top?

Yeah. That's probably true. Also, we may like to add a Ivón size prop?

**Comment by leogermani** [comment]
I'm not sure a icon size prop is needed... I wouldn't say so... but let's align it to the top

**Review by oskosk — APPROVED** [review]

**Comment by retrofox** [comment]
> One last step: head over to your WordPress.com diff, D82876-code, and deploy it.

r248177-wpcom

**Pull request merged**
