### PR TITLE
PHPCS: Only Report on Changed Lines in pre-commit Hook (2nd attempt)

### PR DESCRIPTION
**Pull request by mdawaffe**
A new and "improved" version of #11515.

##### Method

1. Run PHPCS on all staged (whole) files.
2. Print a summary for the lint results of those (whole) files.
3. Cache the results of that PHPCS run.
4. Filter that cached data to remove any information about unchanged or deleted lines. We are left only with information about new or changed lines.
5. Run PHPCS again, but this time we feed it that filtered cached data. Instead of rescanning all the files, it just generates reports straight from the cache.

##### No more autofixer in the pre-commit hook

This PR also removes the autofixer. (It's pretty straightforward to add back if we want it). There are pros and cons to using the autofixer.
* Pros: Less work for the developer! 🎉
* Cons: As written, it yields commits that contain both lint fixes and functional changes. This means the commit history's "story" becomes less clear, and makes more work for reviewing developers 😫

If we're linting whole files, the burden of cleaning up the file is enough that the autofixer's benefits outweigh its disadvantages.

If we're able to lint only changed lines, though, the burden of cleaning up those changed lines is reduced, so the autofixer is less beneficial. I feel it's better to just block the commit, tell the developer how to unblock, and let them figure out if they want to run PHPCBF on the whole file, the changed lines, or to just manually fix things.

##### Improvements over the first attempt

* Unlike in #11515, the pre-commit hook in this PR always looks at the staged version of the files. It can never get mixed up between the working tree and the staged index. (The new `bin/sniff-diff.php` script is much more flexible, but the pre-commit hook's job is to only look at staged files.)
* As pointed out in p1HpG7-6kp%23comment-30895-p2, changing one line can sometimes introduce an error on another line. The error can be as simple as a misalignment in whitespace, or something more complicated like a now unused variable (or worse, a now uninitialized variable). To notice this, this PR runs PHPCS a third time on the old version of the files and compares total error count of each old file to the total error count of the corresponding new file.

##### Whitelist

This PR does not get rid of the PHPCS whitelist. Before we can get rid of the whitelist, we should at least run the autofixer on everything (yay syncing those changes to WP.com!).

I've added 3rd-party/ to the whitelist, though, to make it easier to test some things.

##### 3rd-party/vaultpress.php
This file has just a few errors, so testing things is pretty straightforward.

1. `vendor/bin/phpcs 3rd-party/vaultpress.php`
2. See several errors. Note that one of them is on line 20.
3. Edit 3rd-party/vaultpress.php. Change line 20, but don't fix the PHPCS error:
```diff
--- a/3rd-party/vaultpress.php
+++ b/3rd-party/vaultpress.php
@@ -17,7 +17,7 @@ function jetpack_vaultpress_rewind_enabled_notice() {
 	?>
 	<div class="notice notice-success vp-deactivated">
 		<h2 style="margin-bottom: 0.25em;"><?php _e( 'Jetpack is now handling your backups.', 'jetpack' ); ?></h2>
-		<p><?php _e( 'VaultPress is no longer needed and has been deactivated.', 'jetpack' ); ?></p>
+		<p><?php _e( '!!!VaultPress is no longer needed and has been deactivated.', 'jetpack' ); ?></p>
 	</div>
 	<style>#vp-notice{display:none;}</style>
 	<?php
```
4. `git add 3rd-party/vaultpress.php`
5. `git commit`
6. See the commit blocked, but only by the one error!
7. Fix the error:
```diff
--- a/3rd-party/vaultpress.php
+++ b/3rd-party/vaultpress.php
@@ -17,7 +17,7 @@ function jetpack_vaultpress_rewind_enabled_notice() {
 	?>
 	<div class="notice notice-success vp-deactivated">
 		<h2 style="margin-bottom: 0.25em;"><?php _e( 'Jetpack is now handling your backups.', 'jetpack' ); ?></h2>
-		<p><?php _e( '!!!VaultPress is no longer needed and has been deactivated.', 'jetpack' ); ?></p>
+		<p><?php esc_html_e( '!!!VaultPress is no longer needed and has been deactivated.', 'jetpack' ); ?></p>
 	</div>
 	<style>#vp-notice{display:none;}</style>
 	<?php

```
8. `git add 3rd-party/vaultpress.php`
9. `git commit`
10. See the pre-commit pass, even though you didn't fix all the other errors in the file.
11. (Cancel the commit by exiting the editor without saving the commit message file.)
12. (`git reset HEAD 3rd-party/vaultpress.php; git checkout -- 3rd-party/vaultpress.php`)

#### TODO
* [ ] Does any of this work on Windows?
* [x] Do one more PHPCS pass to see if the total number of errors in a file increased (even if the number of errors on the changed lines decreased).

#### Proposed changelog entry for your changes:
None required.

### CODE REVIEW

**Comment by kraftbj** [comment]
For the sake of discussion - PHPCBF, as you stated, is less than ideal if we're only checking changed lines. Would there be benefit in activating this PR's methodology immediately for all files, then still having a whitelist of "fully PHPCS compliant" files that would autofix, with the idea being if a file is on the whitelist, any PHPCBF issues would be part of the changes? Or something like that?

**Comment by mdawaffe** [comment]
We can probably also get fancy and only apply the PHPCBF fixes (automatically or otherwise) to the already changed lines of the pending commit.

**Comment by kraftbj** [comment]
> Run PHPCBF on all files that don't sync to WP.com. (Maybe get clever here and try not to stomp on open PRs).
> Turn on this per-line linting for all files.

I'm down with this. Even with conflicts with open PRs, we don't have _that_ many open PRs and I'm open to rebasing them as they come.

**Comment by sirbrillig** [comment]
If it's helpful, [phpcs-changed](https://github.com/sirbrillig/phpcs-changed) allows running phpcs only on changed lines.

**Comment by kraftbj** [comment]
Closing this as #13771 has landed.

@sirbrillig -- I'm loving phpcs-changed. I ended up going with v1 since OS X (pre-Catalina) ships with a version of PHP that isn't compatible with 2.x and didn't want to put up any roadblocks for developers to get on board and use it (yet). Thanks for your work with it!

**Comment by sirbrillig** [comment]
> OS X (pre-Catalina) ships with a version of PHP that isn't compatible with 2.x and didn't want to put up any roadblocks for developers to get on board and use it (yet).

That's a very good point that I hadn't considered when developing it! 🤔 I can't recall why I set the minimum version to 7.2. It seems like 7.1 would be all that's needed for the code I wrote (nullable types, `void` type). I can try to do some testing and if 7.1 works I'll release a new version with the downgraded dependency.

**Pull request closed without merging**
