### PR TITLE
Writing prompts: add a block

### PR DESCRIPTION
**Pull request by creativecoder**
## Proposed changes:

- Adds a writing prompts block to the editor for answering a prompt

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pe7F0s-uo-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

TBD

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
I realize you've already done a lot, but I was wondering if you'd be willing to break this down into 2 PRs: one to introduce the basic skeleton of the new block (generated with `jetpack docker wp jetpack scaffold`), and a follow-up that would expand on it and add the guts of it? I think it would potentially make things easier to review.

**Comment by creativecoder** [comment]
> ... I was wondering if you'd be willing to break this down into 2 PRs ...

@jeherve I can see the benefits of that. Since the blogging-prompts extension is already in experimental build (in production for WP.com sites) I think I'd need to create a new, temporary beta extension, do the PRs for that extension to create a new block, and then move it all into the existing blogging-prompts extension when we're happy with it.

I've currently been focused on resolving the underlying API issues, but will start on the above early next week.

**Comment by jeherve** [comment]
> I think I'd need to create a new, temporary beta extension, do the PRs for that extension to create a new block, and then move it all into the existing blogging-prompts extension when we're happy with it.

I don't want to cause you too much extra work though. 

Another alternative, if you'd prefer, could be to have a feature branch and we'd review PRs merged into that feature branch?

**Comment by creativecoder** [comment]
Here's the first PR with just a basic block to break this work out: https://github.com/Automattic/jetpack/pull/29013

**Comment by creativecoder** [comment]
Next step for this is in https://github.com/Automattic/jetpack/pull/29182

**Comment by creativecoder** [comment]
And here's the final piece: https://github.com/Automattic/jetpack/pull/29189

I'll go ahead and close this one.

**Pull request closed without merging**
