### PR TITLE
actions: Set concurrency for gardening workflow

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

This might help reduce our API call usage from turnstyle, by cancelling
extraneous jobs in cases where we get multiple "pull_request labeled"
events in quick succession or something like that.

#### Jetpack product discussion

Just generic discussion about hitting the GH API rate limits.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Try triggering multiple events in quick succession, e.g. changing labels multiple times. See whether some of the resulting Gardening jobs get cancelled.

### CODE REVIEW

**Comment by anomiex** [comment]
Heh, it tested itself as soon as I submitted it, since the submit itself triggered three "pull_request labeled" events. https://github.com/Automattic/jetpack/actions/runs/947023834 and https://github.com/Automattic/jetpack/actions/runs/947023844 got cancelled, since https://github.com/Automattic/jetpack/actions/runs/947023876 got created.

**Review by jeherve — DISMISSED** [review]
This does seem to work so I'm approving, but I do have a question about this. I may be missing something here, but how does a cancelled job runs again later on?

Let's say I create a PR. As I submit the PR, the Gardening workflow needs to do a few things:
- Assign the issue my PR closes to me, via the `assignIssues` task that listens to `pull_request` `opened`.
- Add the right labels via the `addLabels` task, also happening on `pull_request` `opened`.
- Check the PR's description via the `checkDescription` task, also happening on `pull_request` `opened`.
- Notify Design, happening on `pull_request_target` `labeled`.
- Notify Editrorial, happening on `pull_request_target` `labeled`.
- Add an OSS label, happening `pull_request_target` `opened`.

Your PR seems to show that this still works (`checkDescription` happens, but also `addLabels`, even though they both listen to the same event), but I'm not sure I understand why.

**Comment by anomiex** [comment]
The cancelled job doesn't run again later on. But you're looking at it in the wrong way, so I see why you're confused.

* I create the PR.
  * That fires a "pull_request opened" event, which queues workflow run A.
    * When that workflow run runs, it'll do the assignIssues, addLabels, and checkDescription tasks.
  * That also fires a "pull_request_target opened" event, which queues workflow run B.
    * When that workflow run runs, it'll do the flagOss task.
* Then, because I specified three labels while creating the PR, it starts adding them to the new PR. And apparently it does them one at a time. So, the first one...
  * That fires a "pull_request labeled" event, which queues workflow run C.
    * When that workflow run runs, it'll do the addLabels and checkDescription tasks.
  * That also fires a "pull_request_target labeled" event, which queues workflow run D.
    * When that workflow run runs, it'll do the notifyDesign and notifyEditorial tasks.
* ... and then the second one ...
  * That fires a "pull_request labeled" event, which queues workflow run E.
    * When that workflow run runs, it'll do the addLabels and checkDescription tasks.
  * That also fires a "pull_request_target labeled" event, which queues workflow run F.
    * When that workflow run runs, it'll do the notifyDesign and notifyEditorial tasks.
* ... and then the third.
  * That fires a "pull_request labeled" event, which queues workflow run G.
    * When that workflow run runs, it'll do the addLabels and checkDescription tasks.
  * That also fires a "pull_request_target labeled" event, which queues workflow run H.
    * When that workflow run runs, it'll do the notifyDesign and notifyEditorial tasks.

Note that runs C, E, and G will all do exactly the same thing. And the same for D, F, and H. We really only need to run one copy of each. That's what this change does.

* C, E, and G get a concurrency group of "gardening-pull_request-labeled-$REF". GitHub will immediately cancel any existing runs in that group when a new run is queued for the group, so only G should get to the point of running.
* Similarly, D, F, and H get a group of "gardening-pull_request_target-labeled-$REF", so only H should wind up running. Or will once this is merged, since pull_request_target runs against the target rather than the PR.
* A gets "gardening-pull_request-opened-$REF"
* B gets "gardening-pull_request_target-opened-$REF"

A run on a merge to master would get group "gardening-push--master". I should probably adjust that so two merges to master in quick succession don't wind up skipping the gardening for one of them. New commit coming momentarily.

When I push that new commit, it'll queue a workflow run for "gardening-pull_request-synchronize-$REF". If I then quickly fix a typo and push another commit, it would make a second run for "gardening-pull_request-labeled-$REF" and cancel the first. This second run wouldn't do exactly the same thing (the first runs against the first commit and the second against the second), but that shouldn't matter.

**Review by kraftbj — APPROVED** [review]
Cool. Nice work.

**Comment by jeherve** [comment]
Thanks for the explanation, it all makes sense now!

**Pull request merged**
