### PR TITLE
Enhancement/consistent-ui-design-changes

### PR DESCRIPTION
**Pull request by jeffgolenski**
Fixes this: https://github.com/Automattic/jetpack/issues/1809
And a few small tweaks within the stats dashboard widget area.

BEFORE:
screen shot 2015-03-31 at 2 22 30 pm

AFTER:
screen shot 2015-03-31 at 4 07 14 pm

### CODE REVIEW

**Comment by jeffgolenski** [comment]
Current: https://cloudup.com/i4d0tA1NUrO

**Comment by jeffgolenski** [comment]
Current: 
screen shot 2015-04-14 at 2 15 56 pm

**Comment by samhotchkiss** [comment]
Looks good to me

**Comment by dereksmart** [comment]
Tested and looks good in all shapes and sizes! 

:shipit:

**Comment by jeffgolenski** [comment]
@dereksmart I can always count on Inspector Smart!

**Pull request merged**
