### PR TITLE
Simple Payments: Only fire init hooks if enabled

### PR DESCRIPTION
**Pull request by kraftbj**
There exists a `jetpack_disable_simple_payments` filter, but it does not prevent the init hooks from firing, thus the CPT and shortcode are still registered.

#### Changes proposed in this Pull Request:

* Check if Simple Payments are enabled before use.

This is likely incomplete. It looks like right now we still want the shortcode enabled so we can display an warning to an admin when it is disabled. May want to juggle things around a bit.

#### Jetpack product discussion

None at this time.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Add `add_filter( 'jetpack_disable_simple_payments', '__return_true' );` to a connected Jetpack site with a higher plan.
* Check the list of CPTs on the site to see if `jp_pay_order` is included or not.

### CODE REVIEW

**Comment by samiff** [comment]
@kraftbj Just noticing this in the 10.8 milestone, is this PR ready for review or is it still in progress?

**Comment by coder-karen** [comment]
@kraftbj it looks like this is still in progress?

**Comment by kraftbj** [comment]
@coder-karen Ah, I totally forgot about this one. I moved it out of the milestone, but will put it back if I'm solid with it before I leave today. Otherwise, we'll leave it for 11.0.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Pull request closed without merging**
