### PR TITLE
E2E: Fix connection tests

### PR DESCRIPTION
**Pull request by dereksmart**
The connection E2E is failing because of changes made to the default flow in p1HpG7-jYo-p2, which is landing by default on the complete page. 

## Proposed changes:

- New "Page" object for Complete. 
- Updates the "free" flow to hit the "free" button on Complete page
- Updates the "free" flow to redirect back to the main Jetpack dashboard (changed behavior)
- Update the other "product" flows to first hit the "view all products" link on the complete page.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Flow changed as part of p1HpG7-jYo-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

Green tests. 
See tests passing on https://github.com/Automattic/jetpack/pull/29287, where it changes the Jetpack plugin to trigger the full connection tests.

### CODE REVIEW

**Review by fgiannar — APPROVED** [review]
LGTM 🚢

**Comment by elliottprogrammer** [comment]
@dereksmart, it's been decided ( pbNhbs-5JE-p2#comment-14031 ) we're going to revert the Jetpack plugin post-connection (post-authorization) redirect page back to the Jetpack plans page (showing all Jetpack products), instead of redirecting to the "Offer Jetpack Complete Immediately" post-connection/authorization page (PT: p1HpG7-jYo-p2 ) and we have this PR ( https://github.com/Automattic/wp-calypso/pull/74558 ) that's ready to ship that accomplishes this, but shipping the revert PR will cause this e2e test in this PR to break again, I believe.

I guess what I'm wondering is: If we need to ship the revert PR ( https://github.com/Automattic/wp-calypso/pull/74558 ) asap (which will cause this test to break, I think), can we still go ahead and ship it for now? Then I'm assuming we'll create/ship a Jetpack PR that reverts/un-does the code change in _this_ e2e test PR. So in the mean time, until the next Jetpack release, do we need to, or can we, disable this test? Or how does it work? I'm just not sure how to handle a Jetpack e2e test that is dependent on a Calypso PR. Just wondering if you might know or could provide any assistance or insight. 😉

I've also pinged you about this same issue, on the revert PR, here: https://github.com/Automattic/wp-calypso/pull/74558#issuecomment-1474102638 . but I haven't heard any response, so I'm duplicating the comment here just for more exposure in case you missed it. Apologies for the duplication.

**Comment by dereksmart** [comment]
Yeah totally fine to come back and fix/update the tests after deploying.
E2E tests are non-blocking

**Comment by elliottprogrammer** [comment]
> Yeah totally fine to come back and fix/update the tests after deploying. E2E tests are non-blocking

Ok awesome, thanks very much @dereksmart !  TIL! 🙏 👍

**Pull request merged**
