### PR TITLE
Carousel: update bail wording to use module instead of plugin.

### PR DESCRIPTION
**Pull request by jeherve**
@see #1277

### CODE REVIEW

**Comment by dereksmart** [comment]
Good call, dunno how I missed that

**Comment by jeherve** [comment]
Thinking about it some more, "The carousel module has been disabled" isn't correct either, since the module is actually still enabled. 

Carousel **feature**, maybe? What do you think?

I think the message is also not that helpful, as it doesn't tell you how to get it fixed, and what that means to you as a site owner. It'd be nice to add a link to a support page that would explain how to continue debugging.

**Comment by dereksmart** [comment]
simplified: 

> another plugin or a theme is overriding Jetpack's [gallery] shortcode.

**Comment by dereksmart** [comment]
looks good :+1:

**Pull request merged**
