### PR TITLE
Site Breadcrumbs: add from Dotcom

### LINKED ISSUE #1563: Add Site Breadcrumbs
A growing number of our themes on Dotcom use a basic shared breadcrumb navigation function that would be nice to have in Jetpack for our users.

### PR DESCRIPTION
**Pull request by michaeldcain**
Fixes #1563.

### CODE REVIEW

**Comment by jeherve** [comment]
@michaeldcain That looks interesting! Could you draft a support doc about this on jetpack.me, so I can give it a try?

**Comment by michaeldcain** [comment]
Can do.

**Comment by michaeldcain** [comment]
@jeherve should I go ahead and publish it since it's in the beta?

**Comment by jeherve** [comment]
@michaeldcain Thanks! You can leave it as a draft, I'll publish it when we release 3.4.

**Pull request merged**
