### PR TITLE
VideoPress: Update VideoPress to use the placeholder component from js-packages

### PR DESCRIPTION
**Pull request by kozer**
## Proposed changes:

Replace `Placeholder` component with `LoadingPlaceholder` from js packages

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Test videopress to check that in places where placeholder is used, there are no discrepancies using the new loading placeholder package

### CODE REVIEW

**Review by danielbachhuber — COMMENTED** [review]
> Test videopress to check that in places where placeholder is used, there are no discrepancies using the new loading placeholder package

Where do I go to test this?

Also, can you edit the pull request title to be more descriptive?

**Comment by kozer** [comment]
> > Test videopress to check that in places where placeholder is used, there are no discrepancies using the new loading placeholder package
> 
> Where do I go to test this?
> 
> Also, can you edit the pull request title to be more descriptive?

I'm not sure tbh. @jeherve said that he would add people in the loop who have worked on this before. It was a question I had as well, in the original pr I opened.

**Review by jeherve — DISMISSED** [review]
> he would add people in the loop who have worked on this before. It was a question I had as well, in the original pr I opened.

I added Agora to this PR, they should be able to help with that.

Before they can review, could you fix the failing test here, by running `tools/fixup-project-versions.sh`?

Thanks!

**Comment by dhasilva** [comment]
Added a commit bumping the version and merging trunk. There were some changes in recent PRs causing conflicts.

**Review by dhasilva — APPROVED** [review]
Working nicely here. Thanks for the PR! :+1: 



https://user-images.githubusercontent.com/8486249/224153435-e942bcf2-3978-4c79-a505-0feebb8cee68.mp4

**Review by danielbachhuber — COMMENTED** [review]
Great work on this PR, @kozer 👍

**Comment by kozer** [comment]
> Working nicely here. Thanks for the PR! +1
> 
> 

Thank you!
One question though! Is it's ok to be merged, or do I have to wait for more team members to review that? (As I see, you added the sticker "Needs team review", and this is why I'm asking!)

**Comment by jeherve** [comment]
> One question though! Is it's ok to be merged, or do I have to wait for more team members to review that? (As I see, you added the sticker "Needs team review", and this is why I'm asking!)

It should be ok to merge, since you've got an approval! 👍

**Pull request merged**
