### PR TITLE
Add template lock to premium-content buttons

### PR DESCRIPTION
**Pull request by dsas**
#### Changes proposed in this Pull Request:

Currently users can add extra payment blocks to premium-content buttons,
If the button has the same planId as the existing one, then there's no
point adding it - it'll unlock the same content, and have the same
payment terms. If the button has a different planId as the existing one,
then it won't unlock the content it looks to be associated with.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

 1. Create a post with the premium content block 
 2. Select the premium content buttons
 3. It shouldn't be possible to add more child blocks
 4. It shouldn't be possible to remove the existing child blocks

### CODE REVIEW

**Comment by Copons** [comment]
Thanks for opening this @dsas!

The change makes sense to me, but looking at the comment, I can't help but wonder if the template was left unlocked intentionally.

@mmtr, you added that in https://github.com/Automattic/wp-calypso/pull/43684. Do you have any recollection of it?
E.g. why did we leave the Premium Content Buttons container block unlocked, allowing users to insert more payment buttons?

**Comment by rcrdortiz** [comment]
Tests well for me.

**Review by rcrdortiz — APPROVED** [review]

**Comment by mmtr** [comment]
> The change makes sense to me, but looking at the comment, I can't help but wonder if the template was left unlocked intentionally.
> 
> @mmtr, you added that in [Automattic/wp-calypso#43684](https://github.com/Automattic/wp-calypso/pull/43684). Do you have any recollection of it? E.g. why did we leave the Premium Content Buttons container block unlocked, allowing users to insert more payment buttons?

Sorry for the late reply, I missed your ping!

I added that intentionally in order to support a scenario where a user want to sell other products/plans.

Something like:

```
// Non-subscriber view

This video is exclusive for <COURSE_PLAN_NAME> subscribers. You can also buy a book with the content of this course!

[payment-button]Subscribe to <COURSE_PLAN_NAME>[payment-button]
[login-button]Login[login-button]
[payment-button]Purchase <BOOK_PRODUCT_NAME>[payment-button]
```

AFAICR, that scenario wasn't required by the project, and it wasn't considered in order to fix a bug – I just added it because I thought it could be useful. I don't have any problems in locking the template if we're certain that users don't use the non-subscriber view for selling other subscriptions.

**Comment by mmtr** [comment]
> I just added it because I thought it could be useful

Actually, after taking a further look to https://github.com/Automattic/wp-calypso/pull/43684, the template was added before that. So I think I just kept it supported in that PR because I didn't want to change the behavior.

**Comment by mmtr** [comment]
Found more context behind that decision: https://github.com/Automattic/wp-calypso/pull/42715#issuecomment-640508662

**Comment by dsas** [comment]
> The https://github.com/Automattic/jetpack/pull/23486 surfaced this issue, but if we decide to https://github.com/Automattic/jetpack/pull/23486#issuecomment-1084773415, this change might not be worth the migration pain. 🤔

+1

**Pull request closed without merging**
