### PR TITLE
Remove getIconColor from Paywall block icon paths

### PR DESCRIPTION
**Pull request by derekblank**
Resolves an issue where the Paywall block appears as Jetpack green in the mobile editor. Removes color properties from the Paywall block SVG itself in favor of setting this color for the web editor in the [block's settings](
https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/paywall/index.js#L35C1-L35C1). If these code changes have been done correctly, there should be no modification to the Paywall icon appearance in the Jetpack web editor. On mobile, the icon should not appear as Jetpack green within the editor. 

Fixes `gutenberg-mobile#6099`
* https://github.com/wordpress-mobile/gutenberg-mobile/issues/6099

## Proposed changes:

For the Paywall block SVG icon:
* Remove `fill="none"` on the parent SVG element
* Remove the use of `fill={ getIconColor() }` from the child Path elements

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* https://github.com/Automattic/jetpack/pull/32553

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

0. Enable Jetpack beta features so that beta blocks are available
1. Add a Paywall block 
2. Verify that the correct Paywall block icon appears as Jetpack green
3. Open the same post on mobile app with these local changes
4. Verify that the Paywall icon is not green

### CODE REVIEW

**Review by simison — DISMISSED** [review]
I agree it would be better for these icons to be normal UI colour outside colour picker where it seems in Jetpack they should be green.

In https://github.com/Automattic/jetpack/pull/32544 I just simply copied what other Jetpack blocks were doing but also found the function for the fill colour condotionally odd:

Screenshot 2023-08-23 at 10 32 34


Testing this PR, icons are still green in the editor, so I don't know what `getIconColor` really does. 🤷 

Screenshot 2023-08-23 at 10 25 37

Screenshot 2023-08-23 at 10 55 00


cc @jeherve @monsieur-z for any advice and seeing if the `getIconColor()` could be removed for all blocks?

**Comment by derekblank** [comment]
> I agree it would be better for these icons to be normal UI colour outside colour picker where it seems in Jetpack they should be green.
> 
> In #32544 I just simply copied what other Jetpack blocks were doing but also found the function for the fill colour condotionally odd.

@simison That makes sense -- the fill color conditions did seem odd for the Paywall block. I posted a much deeper description of how the fill colors affect the mobile editor here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/6099#issuecomment-1689456936 

> Testing this PR, icons are still green in the editor, so I don't know what this really does. 🤷

That's great to hear! This is the behavior I was expecting -- the icon should remain green for the web editor (meaning this PR introduced no unintended changes).  In the mobile editor, however, the icons for Jetpack blocks are not always displayed as green.

**Comment by simison** [comment]
@derekblank can you add a changelog file (just type `jetpack changelog add` and follow instructions), and we can then merge. That'll fix lint failure. I'd like to rebase with https://github.com/Automattic/jetpack/pull/32615 afterwards since we touch similar code lines. 

Let me also know if I can do that for you! :-)

E2E failure is unrelated.

**Comment by derekblank** [comment]
@simison Changelog added ~(I think). The script was successful, and I pushed the branch. Would I expect to see a changelog entry in this PR, though?~ **Edit:** nevermind, I didn't see that it actually created a changelog entry that I needed to push. 🙃 

Thanks for the review. 👍 Just noting that I have this PR currently set to merge into our Jetpack mobile [feat/register-paywall-block](https://github.com/Automattic/jetpack/tree/feat/register-paywall-block) branch, but if the team would eventually remove `getIconColor()` from all block icons (referenced https://github.com/Automattic/jetpack/pull/32638#pullrequestreview-1590947933), perhaps it would be better to set this to merge straight to `trunk` instead. Wdyt? And yes please, I think it's a good idea if you handled the rebase with #32615 afterwards to keep things clear.

**Comment by simison** [comment]
Looks good now. 👍 

Yes please merge this change directly to `trunk` to get changes in sooner and in smaller chunks, so that we avoid more complicated rebases and everything is simpler.

**Comment by simison** [comment]
Just noting that similar changes were already made in https://github.com/Automattic/jetpack/pull/32568 by @monsieur-z  where block settings like icon are copied to `block.json` files. Those files aren't in use yet I think, but eventually they will.

**Comment by derekblank** [comment]
> Looks good now. 👍
> 
> Yes please merge this change directly to `trunk` to get changes in sooner and in smaller chunks, so that we avoid more complicated rebases and everything is simpler.

Sounds good. Changing the base branch invalidated your first review, and requires another re-review.

**Review by simison — DISMISSED** [review]

**Comment by simison** [comment]
Oh I see the `native` etc files now in this PR, you probably meant to have only the commit changing the SVG and rebase the native mobile branch after merging to `trunk`?

**Comment by derekblank** [comment]
> Oh I see the native etc files now in this PR, you probably meant to have only the commit changing the SVG and rebase the native mobile branch after merging to trunk?

Yes, good point. I branched this off of [feat/register-paywall-block](https://github.com/Automattic/jetpack/tree/feat/register-paywall-block), which I'm not sure we should merge yet. Let me see if I can update this PR to only branch off `trunk` and then cherry-pick https://github.com/Automattic/jetpack/pull/32638/commits/a6b652cd244a81487067062e28d59025407dc0c3 and the changelog on top of it. 🤔

**Comment by simison** [comment]
This should also work, and you'd flag first 5 unwanted commits with `d`:

```sh
git rebase -i HEAD~7
git push origin fix/paywall-icon --force-with-lease
```

image

Those commits should be safe in the original branch.

**Comment by derekblank** [comment]
> This should also work, and you'd flag first 5 unwanted commits with `d`:

Yep, brilliant -- that did it, thanks! Just waiting on CI and another re-review.

**Review by simison — APPROVED** [review]

**Review by dcalhoun — COMMENTED** [review]
Thank you for addressing this! 🎉

**Pull request merged**
