### PR TITLE
JS Components: Add Dialog component

### LINKED ISSUE #23754: RNA: Introduce Dialog component
image

* Implement the component
* Add doc and stories

p6TEKc-68A-p2

- [x] https://github.com/Automattic/jetpack/issues/23831
- [x] https://github.com/Automattic/jetpack/issues/23843

### PR DESCRIPTION
**Pull request by retrofox**
This is the last PR that introduces the `<Dialog />` component to the jetpack-components packages. More detail about implementation https://github.com/Automattic/jetpack/issues/23754.

Fixes https://github.com/Automattic/jetpack/issues/23754

#### Changes proposed in this Pull Request:

* JS Components: Add Dialog component

#### Testing instructions:

* Use Storybook
* Go to Dialog story
* Take a look at both stories
* Confirm the box-model is consistent with the design

image

Screen Shot 2022-04-07 at 2 49 57 PM

https://user-images.githubusercontent.com/77539/162266031-96136676-2aff-4b05-b30b-16e5447a2c54.mov

### CODE REVIEW

**Review by keoshi — DISMISSED** [review]
Looks great to me!

Only spotted two tiny details but neither should hold back merging this:

- As illustrated in your screenshot, I'm also getting a `65px` padding on the Backup card. Just 1px more than the expected 64px so I'm wondering if the outer layout has anything to do with it.
- The list items on the Security card have `=` symbols on them.

image

**Comment by retrofox** [comment]
> Looks great to me!

nice

> Only spotted two tiny details but neither should hold back merging this:
> 
> * As illustrated in your screenshot, I'm also getting a `65px` padding on the Backup card. Just 1px more than the expected 64px so I'm wondering if the outer layout has anything to do with it.

Yes, because it's the padding + border. Let me try to compute it to define 24px.

> * The list items on the Security card have `=` symbols on them.

That's mock data. Let me update it anyway.

**Comment by retrofox** [comment]
let's address the size issue in another PR, since it belongs to the ProductOffer component

**Review by keoshi — APPROVED** [review]
LGTM!

**Review by renatoagds — APPROVED** [review]
LGTM

**Comment by retrofox** [comment]
r243528-wpcom

**Pull request merged**
