### PR TITLE
Stats: Update dashboard widget content sections balanced with long titles

### LINKED ISSUE #30089: Stats widget: Truncate long post / page titles in the Highlights section
I noticed that depending on the time frame selected in the widget settings, when there's no search terms, the post titles push right into that area, which looks bad and feels very unbalanced. 

Can we truncate long post titles and add an ellipsis. I think 34 characters max feel comfortable. We should also created more fixed max-widths with these cols. 

Examples: 

Image

It's better if search terms are available, but still a little unbalanced. 

Image

cc @ederrengifo @jsnmoon

### PR DESCRIPTION
**Pull request by dognose24**
Fixes #30089 

## Proposed changes:

|Before|After|
|-|-|
|截圖 2023-04-15 上午1 18 13|截圖 2023-04-15 上午1 22 12|

* Update the `Top Posts` and `Top Searches` sections structure with 50% width each to accommodate long post titles with ellipsis effects.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

The updated styling is in line with p1HpG7-l7H-p2.

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Apply these changes to your site with the Jetpack plugin.
* Navigate to `/wp-admin/` and ensure that the Jetpack Stats widget renders a balanced layout for long post titles.

### CODE REVIEW

**Review by jsnmoon — DISMISSED** [review]
Looks good!

**Comment by jeffgolenski** [comment]
Looking good @dognose24!

Screen Shot 2023-04-14 at 4 23 30 PM


I have a small side request. The light gray that's used for "Sorry, nothing to report." and "X views" is a bit too light. I've got some a11y concerns. Could we change that to `gray 60` from our color library? (#50575E)

Thank you!

**Review by jsnmoon — APPROVED** [review]
@jeffgolenski: I pushed a commit replacing that gray (`#999`) with `gray-60`. I also set the page view counter text (also `#999`) to `gray-40` for improved readability.

image

**Comment by dognose24** [comment]
@jeffgolenski @jsnmoon Thanks for the design feedback and prompt update for this PR! The colors look more clear to me.

**Comment by jeffgolenski** [comment]
Beautiful. Thank you both!

**Pull request merged**
