### PR TITLE
[Boost] update changelog for 1.5.1 release

### PR DESCRIPTION
**Pull request by thingalon**
Prepare changelogs for a minor bugfix release of Boost; 1.5.1

#### Changes proposed in this Pull Request:
* Update changelogs for 1.5.1 release
* Update version to 1.5.2-alpha for future dev.

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Review changelogs.

### CODE REVIEW

**Review by haqadn — DISMISSED** [review]
🚢 🚢 🚢

**Review by haqadn — APPROVED** [review]
Still good 👍🏼

**Review by jeherve — APPROVED** [review]

**Review by karthikax — APPROVED** [review]
👍

**Comment by thingalon** [comment]
Pushed D83360 in rWPGIT4b127c809af8bf2d4a1629067ab9a57a5e5561e3

**Pull request merged**
