### PR TITLE
Autoupdates: debug failed autoupdates

### PR DESCRIPTION
**Pull request by roccotripaldi**
Send a remote post to wordpress.com to debug failed autoupdates.

The request body includes a list of failed plugins, and the blog id.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Hey @roccotripaldi -- this is flagged as in progress, but looks complete.  Are you still working on it, or is it ready for review?  If the latter, can you give us steps to test?

**Comment by roccotripaldi** [comment]
@samhotchkiss This is waiting on a server-side merge.

**Comment by zinigor** [comment]
Read the changes, everything looks fine!

**Comment by dereksmart** [comment]
:+1:

**Pull request merged**
