### PR TITLE
Slideshow block: Ensure max-width is defined when within the Stack block

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes https://github.com/Automattic/vulcan/issues/610

## Proposed changes:

* The issue: When a Slideshow block is added to a Stack block, it's max-width balloons, thanks to it's parent (the Stack block) having a display of flex set. This is a known issue with the Swiper library - see the link in the linked issue. This affects Slideshow blocks added in both templates and regular post / page editors, plus the block display on the front-end.
* This PR defines a max-width for the Slideshow block, when it is placed within a Stack block. 
* It also ensures the max-width considers any parent padding. Since this requires calculation and can't be done via pure CSS, a new `utils.js` file has been created with a JS helper function to help calculate and apply width changes based on padding. 
* I've tested putting the Slideshow block inside various other blocks, and the issue only occurs within the Stack block (the Row block with orientation set to vertical becomes a Stack block). It's possible that another parent-style block could also define itself as a flex container, however I've been unable to find an example. So until we can, I think the current approach would fit - if we find another flex parent block then we may need to change the logic so in JS we check for a flex parent and apply styles that way.
* A simpler solution would be great here - this seems overly complex, so I'm open to any other ideas as well.

A similar issue was fixed here, though was tested with Row / Column blocks: https://github.com/Automattic/jetpack/pull/40041

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/vulcan/issues/610
https://github.com/Automattic/jetpack/issues/22834
p1733937332404909-slack-C05PV073SG3

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

**To replicate the issue:**

On either self-hosted, WoA or Simple:

* Add a block-based theme (some that were mentioned in testing include Attar, Marl, Twenty Twenty Two, Blank Canvas).
* Open the site editor and open the 'index' template. Add a stack block, and then add the Slideshow block to that (with several images). You can move blocks around via the block overview section if needed.
* You should see part of the slideshow block but without any images - it's width extending well beyond the width of the screen.
* Open the site on the front-end to the homepage or the page that displays posts (the index page), and what you see should be similar.
* In the post / page editor for a post / page, add a Slideshow block within a Stack block - what you see should be similar again.
* Note there are other issues with the Slideshow block display (see below) - this largely depends on the theme and where you place the Slideshow, but for the purposes of this PR you may be better adding the Stack block within another such as the header, footer, or main content area.

**To test the fix**

On any platform:

* Apply this PR if on self-hosted locally, or via the Beta tester plugin on Jurassic Ninja or WoA, or using the generated commands in the comment below for a sandboxed Simple site.
* Follow the same steps as above.
* The slideshow block should be visible in those cases.
* Slideshows added to posts / pages outside of Stack blocks should continue to display as before.
* Test adding multiple slideshows to a post / page - for example a regular slideshow, a slideshow within a stack block, a slideshow within a stack block within a group block. Try adjusting image size as well (medium, large, etc). Everything should work as expected..

**Testing discrepancies:**
* Some template sections won't show the slideshow on the front-end, but they won't show other blocks either (not specific to slideshows).
* If you stack a stack block within a group block, you may also notice display issues. This should be fixable by modifying the group block / blocks layout options from the block sidebar. It may not be depending on how things are nested, but at this stage I'd think this would start becoming an edge case.
* You may also notice other unrelated Slideshow issues when adding blocks, such as this issue related to images appearing 'stuck' to the mouse: https://github.com/Automattic/jetpack/issues/37407

Screenshots:

Block overview section:
Screenshot 2024-11-28 at 16 09 38

Template / post editor before:

Screenshot 2024-11-28 at 16 13 42

Front-end before: 
Screenshot 2024-11-28 at 16 15 40

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
In testing with twenty twenty four, I still see some issues: the images are displayed but the width is still off. Here is an example:
https://extreme-rhinoceros.jurassic.ninja/

Does this work well with Twenty Twenty Four for you?

**Comment by coder-karen** [comment]
Thanks for taking a look @jeherve. Yes I can see the same issues in Twenty Twenty Four as well, and other themes, if the Stack block is placed within a Group block. This is one of the 'testing discrepancies', and should be fixable by modifying the 'layout' for the Group block itself to not use content width (your Group block would be set to 'Inner blocks use content width', I am guessing).

I've noted this as more of an edge case, though I can see it's common to group blocks in templates, using the Group block. But, how common would it be to then add a Stack block within a Group block, and then add the Slideshow block to that?
The other reason I think it should be an edge case, is because you could then stack another Group block within a Group block, then another Stack block, etc. Accounting for each case could be difficult. Do you think we should at least account for Stack blocks within Group blocks (one each deep)?

**Comment by jeherve** [comment]
> I can see it's common to group blocks in templates, using the Group block. But, how common would it be to then add a Stack block within a Group block, and then add the Slideshow block to that?

Yeah, I find myself using group blocks more and more, often a combination of groups, stacks, and rows to create grids like the old multi-column widget areas in classic themes.

image

I don't know how often folks would want to add a slideshow block to such an area, but I could see this being useful to showcase pictures of the building for a business for example.

That said, your PR is already an improvement over the current situation. Maybe we can ship that and iterate in future PRs?

**Comment by coder-karen** [comment]
Ah so it could be more common than I thought, good to know though.

I'd be comfortable shipping this and iterating in the future, yes - I know it took a good bit of time to get to what I've added, so I'm aware it could be quite time consuming to try and factor in deeper nesting (unless a simpler approach could work in all cases).

**Pull request merged**
