### PR TITLE
Search: Use checkboxes for filter ui and currently applied filters

### PR DESCRIPTION
**Pull request by gibrown**
The current filters selected UI means that the selected set of filters are not in the same context of where they were clicked. Example:

screen shot 2018-01-16 at 1 51 11 pm

By using checkboxes we can make it a little clearer what has been selected.

screen shot 2018-01-16 at 3 35 15 pm

@MichaelArestad any feedback on this direction?

### CODE REVIEW

**Comment by gibrown** [comment]
Some open issues:
- Clicking in the checkbox does nothing. Haven't been able to get that to work as a link yet.
- Should the count be right justified somehow? Would look a lot better IMO if the numbers were lined up
- There are probably some corner cases when there is only one post, or when combined with default post type filtering
- Needs testing in a bunch more themes

**Comment by gibrown** [comment]
You can play with it on http://gibrown.wpsandbox.me/main/?s=post&post_type=post&day

**Comment by MichaelArestad** [comment]
@gibrown Looks like the test site is back to dots instead of checkboxes.

> Should the count be right justified somehow? Would look a lot better IMO if the numbers were lined up

I don't think so. I think those aren't as important as the "category" itself and might be distracting or way off to the right on wide sidebar areas.

**Comment by gibrown** [comment]
We should remove the lists or change the list style rather than inheriting whatever the theme is doing:

screen shot 2018-01-18 at 9 33 00 am

**Comment by MichaelArestad** [comment]
@gibrown Yep. I think a `list-style: none` on those `ul` elements will do it (target a class for slightly higher specificity).

**Comment by ebinnion** [comment]
Closing in favor of #8619

**Pull request closed without merging**
