### PR TITLE
Likes block: allow hiding avatars

### PR DESCRIPTION
**Pull request by simison**
Related to https://github.com/Automattic/jetpack/pull/40276

Depends on D165404-code 

## Proposed changes:

* Add ability to hide avatars in Likes block

This is backawards compatible as old blocks won't have setting, and in Gutenberg "default" value means no attribute is stored in block markup. Hence no deprecation transforms needed.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply diff
* Add block to a page
* Disable avatar setting
* Avatars should be gone in editor and the site

### CODE REVIEW

**Comment by georgestephanis** [comment]
This is also contingent on the upstream phab diff D165404 merging to wpcom.

**Comment by coder-karen** [comment]
I feel I'm missing a step testing-wise for Jetpack self-hosted sites.  I've got a sandboxed JN site, applied the diff, also added widgets.wp.com to my hosts file.

I can 'like' the post / page via the like block and see no avatar (yet it shows as liked). However the toggle state in the editor won't change, though the initial toggle click (followed by pressing save) does allow me to see my avatar when clicking like on the front-end now.

**Comment by simison** [comment]
> However the toggle state in the editor won't change

I'm having the same issue, and I don't get what's missing. 🤔  My local Jetpack isn't working now so having a bit hard time to develop, but I'll get this going and can ping when it's no longer in progress.

**Comment by simison** [comment]
@coder-karen good for another look now!

Attribute handling wasn't great in this block so I did it like it's done with our other blocks.

**Comment by coder-karen** [comment]
Yes it works now, thanks!

I tested on Simple and self-hosted, I did notice on both that I had issues liking or unliking if avatars were disabled (`cannot read properties of undefined (reading 'querySelector')`). It worked fine if Avatars were enabled.

Also if I have like buttons added to the post /page via the Jetpack sharing settings, that will show avatars when the like block doesn't. I'm guessing that's expected at the moment?

**Comment by simison** [comment]
@georgestephanis [above](https://github.com/Automattic/jetpack/pull/40282#issuecomment-2494315734) might be something to look into at D165404-code as the actual liking action happens in the iframe AFAIK.

**Comment by georgestephanis** [comment]
Okay, merged the phab diff to wpcom, it /should/ work now without the errors.

**Comment by coder-karen** [comment]
I still seem to get the same results as in my last comment, but checking the last comment in the diff it seems like that would be expected (unable to like or unlike when avatars are disabled)?

**Pull request merged**
