### PR TITLE
Content Options: Respect Block Settings for Featured Images

### LINKED ISSUE #399: Homepage Posts Block: Featured images conflict with Content Options
A user reported that the featured images added to a blog post block, within a blog post, are not displayed unless the theme option **My Site -> Design -> Customize -> Content Options -> Featured Images -> Display on single posts** is enabled [screenshot](https://d.pr/i/sKvIEX)

#### Steps to reproduce
1. Start with a site that includes at least one blog post with a featured image
2. Create a new blog post and add a blog post block to the post 
3. Enable the post block to display featured images
4. When the post is published, the featured images will not appear unless the setting to display featured images on single posts is enabled 

#### What I expected

The blog posts block settings should be independent from the theme settings

#### What happened instead

The content options settings override the blog posts block settings

#### Context / Source

#userreport 

This has been tested across several themes that include the Content Options settings in the Customize tool including Twenty Seventeen, Twenty Sixteen, and Shoreditch 

The issue doesnt persist to an install of the core version of Twenty Sixteen and seems to be .com only.

### LINKED ISSUE #851: Post Carousel block doesn't display the featured images
**Describe the bug**
We have a case in 4257832-zen for a couple of post carousels that are not displaying the featured images of the posts on the frontend, despite showing up in the editor.

**To Reproduce**
1. Create a new page and add a Post Carousel block
2. I used the featured tag to have the posts that had a featured image attached 
3. Check the results in the editor vs frontend.

The user's site has the Canard theme, but it's the same with TwentyTwenty-One.

I used this as a workaround for Canard:

```
.wp-block-newspack-blocks-carousel .post-thumbnail img {
    opacity: 1 !important;
    position: absolute !important;
    top: 0 !important;
}

/* Temp fix for the post carousel images for firefox | xxxxx-zen rg */
.wp-block-newspack-blocks-carousel .swiper-slide {
    height: 75vh !important;
}

```

**Screenshots**

Frontend VS Editor

image

**Expected behavior**

To have the images appear on the carousel

### LINKED ISSUE #1943: Apostrophe 2: Featured image display issue on Blog Posts block
This theme has an option in the Customizer to hide the featured images on pages. This causes an issue if you add the Blog Posts block to a page and choose to display the featured images in the block, the images won't display on the page because of the setting in the Customizer.

## Steps to replicate

* Make sure the featured image setting is off in the Customizer
* Add a Blog Posts block to a page, choose to display featured images
* View published page

img

## Result

* Featured images do not display on the page within the block

Images display in admin:

img

Images hidden on page:

img

## Expected

* Featured images should display on the page within the block

* User report: 20553869-hc

### LINKED ISSUE #3255: Colinear: Option to Hide Featured Images on Single Posts Also Hides Featured Images in Blog Posts Block Added to Posts
## Steps to replicate

1. Activate Colinear, and set up a few posts with featured images.
2. Add a blog posts block to one of your posts set to display featured images.
3. Turn off the "Display on single posts" option in the **Featured Images** section of the Content Options in Customizer.
4. Try to see the featured image in your blog posts block on the post you added it to.

## Result

Pulled from testing following user report:

**Blog post block with the option set to the default "Display on single posts":**

image

**Blog post block with the option set to *not* "Display on single posts":**

image

## Expected

I expected the "Display on single posts" option to only impact the featured image for the post itself—not the content of blog posts blocks on posts. It seems the way the theme hides featured images on posts is too broad, since it catches things that were added in the body of the page as well.

* User report: 3720405-zen

### LINKED ISSUE #3462: Spatial: Unexpected Behavior with Content Options and Posts Carousel block
## Steps to replicate

1. Set Spatial theme on site
2. Add Posts Carousel block to homepage
3. Uncheck the Content Options box for displaying Featured Images on Pages
4. The Posts Carousel block will show in the Editor but not in Preview or on the live site

## Result

Instead of displaying the Posts Carousel, you see only the Pause or Play button.

Screen Shot 2021-03-13 at 2 49 49 PM

The orange box in this screenshot is everything that is displaying for the Posts Carousel block on Spatial.

Unable to display a Posts Carousel block on a page, unless the Customize > Content Options checkbox for showing Featured Images on Pages is checked. 

## Expected

For the block to work and show the posts in a carousel on the site, to match the editor. Generally, this setting would only affect the Featured Images for Pages, and not blocks added to the homepage.

* User report: 3816139-zen

### LINKED ISSUE #3609: Floral: featured images not visible in Blog Posts block or Post Carousel block on published posts or pages
## Steps to replicate

1. Activate Floral theme.
2. Add a Blog Posts block or Post Carousel block to post or page edit screen
3.  For Blog Posts block, enable 'Show Featured Image' setting. (Featured image is default behaviour for Post Carousel, so no need.)
4. See your featured images show up in both blocks in the edit screen: [screen1](https://snipboard.io/I1ZzP5.jpg) and [screen2](https://snipboard.io/HJWrUh.jpg)
5. Preview or Publish and view your post. 

## Result

No featured images show on Blog Posts block: https://snipboard.io/0NRjJF.jpg 
Post Carousel won't show at all, as it's so dependent on featured image: https://snipboard.io/NkluHD.jpg

## Expected

I expected featured images to show on the Blog Posts block, and for the Posts Carousel to show.

I replicated on a test site and changed the theme on the site to test this behaviour. Featured images showed up as expected using:

Twentytwentyone: [screen1](https://snipboard.io/6qPEVj.jpg) and [screen2](https://snipboard.io/kTFJ3I.jpg)
Spearhead: [screen1](https://snipboard.io/nL2cGp.jpg) and [screen2](https://snipboard.io/VgdZDc.jpg)

## Reported in

3872936-zen

### LINKED ISSUE #6034: Photos: not showing blog posts block on home page
### Quick summary

When you use a blog posts block on the home page of the Photos theme, the feature images do not show.

### Steps to reproduce

1. Set a blog posts block on the home page and set it to show featured images
2. Set the home page as a static page in the customizer on the Photos theme
3. Check the home page. No featured images are displayed

### What you expected to happen

The static page to appear as designed

### What actually happened

No images appear.

Markup 2022-05-11 at 13 06 11

### Context

Part of - 5206030-zd

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Photos theme
It works on the very similar Mayland theme

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

Switch to another theme

### LINKED ISSUE #29286: Thumbnails in the Latest Posts block are displayed or not depending if Jetpack is connected
### Impacted plugin

Jetpack

### Quick summary

There is a significant inconsistency in the **Latest Posts** block layout depending on if Jetpack is connected or not.
This issue does not affect all themes, but I was able to confirm it with Twenty Twenty-One, Twenty Twenty and Twenty Nineteen and 

It does not affect block themes (no Customizer).

### Steps to reproduce

1. Add a few posts and set featured images for them.
2. Add a new **page** and add the **Latest Posts** block.
3. In the block settings, switch on **Display featured image**.
4. Install, activate and connect Jetpack, this will add the **Content Options** tab in **Appearance > Customize**
5. Open **Customize > Content Options** and UNCHECK **Display on pages** in the **Featured Images** section
6. Check the frontend view of the page with the Latest posts block - thumbnails are not displayed
7. Disconnect Jetpack
8. Check the frontend view of the page with the Latest posts block again - thumbnails are displayed.

### A clear and concise description of what you expected to happen.

We should have consistent behavior regardless if Jetpack is activated or now. 

I am not sure if thumbnails should be or not be displayed on the page (given the unchecked **Display on pages** setting). Still, this should not depend on the Jetpack connection. 

### What actually happened

When Jetpack is connected, image thumbnails within the Latest Posts block are not displayed on the frontent. They appear when you disconnect Jetpack.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### LINKED ISSUE #59280: [Block] Blog Posts - Featured Images hidden by Customizer settings: Customize > Content Options > Featured Images
### Quick summary

The Blog Posts Block is showing featured images **in the editor but not in the public post**.

Editor view:

Screen Shot on 2021-12-16 at 00:34:01

Public View:

Screen Shot on 2021-12-16 at 00:34:18

 

### Steps to reproduce

1. Creat multiple posts and give them featured images
2. Create a separate post and insert a Blog Posts Block.
3. Change the block's setting to make sure it displays images.
4. Head to the Customizer and uncheck the "Display on single posts" and "Display on blog and archives" options

### What you expected to happen

Featured images should show

### What actually happened

Featured images within the Blog Posts block will not show on the public site (but they do show in the editor). This seems to be caused by the "Display featured images" setting in the customizer:
Screen Shot on 2021-12-16 at 10:39:00

This setting is stored and is causing the issue even if you switch to a different theme. The problem is compounded by the fact that not all themes have this option in the Customizer, which makes it very difficult for users (or anyone!) to figure out and fix.

### Context

Dogfooding on one of my public sites https://mrfoxtalbot.wordpress.com/

### Simple, Atomic or both?

Simple & AT

### Theme-specific issue?

The problem is caused by the theme option being stored and applied even if we switch themes. I believe that the problem is not so much due to any given theme, but the way the Blog Posts Block handles that preference. 

There are a number of related issues we should close once this is solved:

Floral: https://github.com/Automattic/themes/issues/3609
Intergalactic 2: https://github.com/Automattic/themes/issues/4904
Unspecified theme: https://github.com/Automattic/newspack-blocks/issues/718
Twenty Twenty-One: https://github.com/Automattic/themes/issues/3540
Radcliffe 2: https://github.com/Automattic/themes/issues/3540#issuecomment-917317694
Apostrophe & Button 2: https://github.com/Automattic/themes/issues/4324
Unspecified theme: https://github.com/Automattic/newspack-blocks/issues/399
Possibly related: https://github.com/Automattic/newspack-blocks/issues/973

### Browser, operating system and other notes

N/A

### Reproducibility

Consistently

### Severity

It affects all sites that had unchecked the "Display on single posts" and "Display on blog and archives" options, even if they later changed to a different theme.

### Available workarounds?
We can do this to fix the problem:

1. Switch back to a theme that has this option in the customizer, such as Independent Publisher 2
2. Make sure the two boxes are checked, as seen below:

Screen Shot on 2021-12-16 at 10:39:00

### LINKED ISSUE #73069: [Block] Post Carousel - Featured Images hidden by Customizer settings: Customize > Content Options > Featured Images
### Quick summary

The Post Carousel block is impacted by the Content Settings selections in the Customizer. If a theme has the option to hide featured images on posts or pages, and a Post Carousel block is added to posts or pages, then these settings also hide the Post Carousel block's features images, breaking the function of the block.

### Steps to reproduce

1. Activate a theme that uses Content Settings to hide featured images, such as Apostrophe 2
2. Add a Post Carousel block to a Post or Page and publish that
3. In the Customizer, view the page/post in question, then open **Content Settings** and uncheck the option to show featured images on that post type

### What you expected to happen

The featured image on the post or page should be the only thing that's hidden by this setting.

### What actually happened

The Post Carousel block is also responding and hiding featured images too.

https://user-images.githubusercontent.com/27249804/217405197-b15e6b70-9515-4fef-8e75-23689e54a8b9.mov

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- User report: 5934004-zd-woothemes 
     - (asked for an update when the issue is resolved so they can remove the CSS workaround)
- Troubleshooting notes where the issue was discovered: p1675705661312809-slack-C03TY6J1A

Workaround is to provide CSS to hide the page/post featured images, allowing the Post Carousel block to work normally. This won't work for customers whose plans do not include CSS support

```
.single .entry-thumbnail {
	display: none;
}
```

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #29286
Fixes Automattic/wp-calypso#85672
Fixes Automattic/wp-calypso#85369
Fixes Automattic/wp-calypso#59280
Fixes Automattic/wp-calypso#73069
Fixes Automattic/wp-calypso#86094
Fixes Automattic/themes#7580
Fixes Automattic/themes#3255
Fixes Automattic/themes#3462
Fixes Automattic/themes#6034
Fixes Automattic/themes#3609
Fixes Automattic/themes#1943
Fixes Automattic/newspack-blocks#399
Fixes Automattic/newspack-blocks#851 

(that's a lot!)

## Proposed changes:

* Ensures that the Content Options' Featured Images selection doesn't override the user's selection for the Latest Posts, Homepage Articles, Post Carousel and Query Loop blocks.

**Update:** rather than using CSS as I first did, I've used the approach recommended by @anomiex here: https://github.com/Automattic/jetpack/issues/29286#issuecomment-1876043341. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A.

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Go to the WordPress.com theme directory and install any theme which uses Content Options (any child theme of Varia, such as Stow, will work - but you can also use others like Canard) - https://wordpress.com/theme/stow
* Under the "Content Options" settings in the Customizer, hide Featured Images for posts or pages
* Create a post or a page with a Latest Posts block, the a8c Blog Posts block or the Query Loop block, and ensure that thumbnails are set to be displayed
* Set a Featured Image for that post or page
* Confirm that the Featured Image is hidden, but that the thumbnails within the blocks aren't

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Works in my testing.
* Featured images from the Featured Image block and from the Latest Posts block are showing up as expected despite the Content Options being turned off
* The featured image isn't being displayed on the posts and homepage listing as expected with the relevant Content Options turned off.

I'd like for someone else to do the approval though, since the code here was originally my suggestion. 😀

**Comment by CGastrell** [comment]
Worked as described for me. Tested on Stow as I couldn't find the option on Canard

**Review by CGastrell — APPROVED** [review]
LGTM!

**Comment by Aurorum** [comment]
Updated with `trunk` so that tests pass. Thanks for the review @CGastrell! :)

**Pull request merged**
