### PR TITLE
Tiled Gallery: Increasing accessibility of gallery images with respect to opening carousels

### LINKED ISSUE #28291: A11Y error with keyboard navigation on gallery when using full screen carousel
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable the "Display images in a full screen carousel gallery" feature
2. Add a gallery to a post or page
3. Verify that clicking on the gallery items opens the carousel
4. Close the carousel and attempt to navigate the page with a keyboard
5. Note it is impossible to trigger the carousel because images are not focusable
6. Turn on a screen reader and attempt to navigate the page
7. Note it is impossible to trigger the carousel because images are not focusable

### A clear and concise description of what you expected to happen.

At the minimum tabindex=0 should be added to the images and they should get role=button.

This may also benefit from additional aria attributes such as `aria-controls` and `aria-expanded`. 

The JS trigger may need to include an event listener for space and enter if that doesn't already exist. Since this is a "button" it must respond to space, trigger, click, and tap (touch) events.

### What actually happened

It is impossible to trigger the carousel because images are not focusable

This is a failure of WCAG 2.1.1 Keyboard.

This is a level A success criterion which means this is a critical issue as sites cannot be considered accessible if this feature is enabled. 

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes #28291

## Proposed changes:

* This PR adds a tabIndex of 0 and the role of button to images added via the Tiled Gallery block (and to Tiled Galleries added using the Classic Editor) to aid in ensuring the images can be focusable.
  * Note that choosing 'Attachment Page' or 'Media File' instead of 'None' as the 'Link To' option is actually a workaround in order to focus on the image using a screenreader / keyboard, but only if using full-screen carousels instead, as we are doing here.
* For Tiled Gallery blocks, an aria-label has also been added to the published gallery images - previously this only existed in the editor. For both Classic and block Tiled Gallery's the aria-label exists in the carousel image already. Adding the aria-label to the image in the gallery itself in the Classic Editor proved difficult, so due to this being likely less used than the block version I opted not to dig in too much more here.
*  It also updated the carousel JavaScript to listen out for more than just a click event in order to open the carousel - now it listens for 'keydown' (space or enter) (when the 'Link To' option is set to 'None', otherwise enter will work). Touch events are already picked up.
* This is in order to ensure that the carousel can be triggered when using the keyboard or a screen reader for navigation.
* I've not added `aria-controls` or `aria-expanded` - we'd be better off with something like a toggle to open up the carousel full-screen mode in that case and that would involve a redesign which wouldn't be a priority here.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/28291

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

To replicate the issue:

* On trunk, enable the 'Display images in a full-screen carousel gallery' feature - `/wp-admin/admin.php?page=jetpack#/writing`
* On a post or page add a Tiled Gallery block, and publish the post/page. Ensure that the Tiled Gallery block is set to link to 'None' from the settings sidebar (note that choosing Attachment Page or Media File is actually a workaround in order to focus on the image using a screenreader / keyboard)
* On the front-end, click on a gallery image, and the carousel should open.
* Close the carousel, and use a keyboard to navigate to the images (tabbing for example). You'll notice you tab right past them (the images are missed)
* Similarly if you have access to a screen reader, attempt to navigate to the images, ad it won't be possible.
* To replicate the issue using the Classic Editor plugin, follow the steps here: https://jetpack.com/support/classic-tiled-galleries/. Make sure to select 'None' under 'Gallery Settings'->'Link To'

To test the fix:
* Follow the same steps as above. When using the keyboard or a screen-reader to navigate to the gallery images you should now be able to open the carousel when focussing on an image with either: 'enter', 'space', clicking or touching/tapping if that is an option for you.
* The same should apply to galleries created within the Classic Editor.
* Check the source for the aria-labels for images before opening a carousel (Tiled Gallery block).

### CODE REVIEW

**Review by monsieur-z — CHANGES_REQUESTED** [review]
The code changes look good, and I haven't seen any issues with version compatibility. I've tested on both self-hosted and simple sites.

I noticed a couple of things:
- With the Gutenberg editor, the images seem to lack a visible focus state in the frontend (tested with the Twenty Twenty Four theme). That wasn't the case when I tested the classic editor, though.
- I'm not seeing any `aria-label` on the images in the frontend. I'm not sure if I missed something or not. How is the value of the attribute determined?
Screenshot 2024-06-18 at 11 25 21 AM

**Review by coder-karen — COMMENTED** [review]
Thank you for testing!

> With the Gutenberg editor, the images seem to lack a visible focus state in the frontend (tested with the Twenty Twenty Four theme).

This will likely be my lack of experience with accessibility here - clicking enter when you should be tabbed over an image should open up the carousel for that image though, so I took that as meaning the image had been in focus. It sounds like I should be adding some styling to make sure it's clear the image is in focus?




> I'm not seeing any aria-label on the images in the frontend. I'm not sure if I missed something or not. How is the value of the attribute determined?

The aria-label will only work for the Tiled Gallery block on the front-end.
Out of curiousity, based on your screenshot, how are you checking for the added aria-label attribute? 
I've assumed that adding into the HTML as an additional prop in the IMG component would work as I can see it in the HTML.
I've not changed how the aria-label itself is determined as there is some functionality in `layout/index.js` originally that does that (visible only in the editor at the moment). All that appeared to be missing was the prop wasn't being brought through in `gallery-image/save.js` - so this would add the label to the image on the front-end, before opening the carousel.
This is the HTML on my site: 


Screenshot 2024-06-18 at 16 54 40

This is where the aria-label is originally created: https://github.com/Automattic/jetpack/blob/81009c4dcc7382b583a56699e48a612f9a1e3a51/projects/plugins/jetpack/extensions/blocks/tiled-gallery/layout/index.js#L33

**Comment by monsieur-z** [comment]
> It sounds like I should be adding some styling to make sure it's clear the image is in focus?

Yes! It's visible now, thanks for adding that :)

> Out of curiousity, based on your screenshot, how are you checking for the added aria-label attribute?

I checked the DOM and the accessibility panel in Chrome. But as I'm testing again, I can see the labels.
Screenshot 2024-06-19 at 10 06 15 AM

I must have done something wrong in my earlier testing. Sorry!

I'm thinking since the `aria-label` is added to a button, it could make sense to make it a call-to-action: e.g., `Open image x of y in full screen` or `Open image [alt text] in full screen`.

**Review by monsieur-z — DISMISSED** [review]

**Comment by coder-karen** [comment]
Thanks @monsieur-z !

> I'm thinking since the aria-label is added to a button, it could make sense to make it a call-to-action: e.g., Open image x of y in full screen or Open image [alt text] in full screen.

Nice idea, I've now opted for the first suggestion you made there.

**Review by monsieur-z — APPROVED** [review]
I haven't tested the PR again but the updates in the latest commit look straightforward. :shipit:

**Pull request merged**
