### PR TITLE
AI Assistant: hide usage bar when site supports AI assistant feature

### PR DESCRIPTION
**Pull request by retrofox**
This PR iterates over the Usage Panel:

* Hide the usage bar when the site supports unlimited requests 
* Show a help when the site supports unlimited requests

Fixes #

## Proposed changes:

* Metered billing: hide usage bar when site has AI plan

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

([discussion](p1698171772640649/1697829634.443029-slack-C054LN8RNVA))

## Testing instructions:

* Go to the block editor
* Open the Jetpack AI panel

. | Before | After
------|-------|-------
Jetpack site / AI plan | image |image
Simple site | image | image

### CODE REVIEW

**Comment by retrofox** [comment]
Follow-up of https://github.com/Automattic/jetpack/pull/33714

**Comment by CGastrell** [comment]
Should/Could we add a link to the site's purchases/plan on that "Unlimited requests" message?

**Comment by CGastrell** [comment]
Removed a subscription from a simple site and it's not looking like your screenshot at all:

image

- no "reset" message
- upsell as a link

After getting a plan, things look as your screenshot:
image

**Comment by retrofox** [comment]
> Should/Could we add a link to the site's purchases/plan on that "Unlimited requests" message?

We could, and we thought about that, but I regretted it since Simple sites have "Unlimited requests" as default, even with a Free plan.

Also, what's the point of providing a link that leads to the plan to the site when it already has it?

**Comment by retrofox** [comment]
> Removed a subscription from a simple site and it's not looking like your screenshot at all:

What's the Simple site that you using to test?

**Comment by lhkowalski** [comment]
> no "reset" message

@CGastrell this message should not be there, it's hidden because requests do not reset on the current plans.

**Comment by lhkowalski** [comment]
> Simple sites have "Unlimited requests" as default, even with a Free plan

@retrofox this is not 100% true. Free Simple sites do not include the feature and have a 20 free requests allowance. The unlimited requests are only include on paid Simple sites.

**Review by lhkowalski — APPROVED** [review]
Code looks good and is working as described.

_Simple site without the plan, the usage bar is visible:_

Screenshot 2023-10-25 at 17 08 27

_Simple site with the plan, the usage bar was removed, as expected:_

Screenshot 2023-10-25 at 17 09 17

_Jetpack site with the plan, the usage bar was also removed, as expected:_

Screenshot 2023-10-25 at 16 59 15

**Pull request merged**
