### PR TITLE
SEO: standardize sanitization for seo inputs

### LINKED ISSUE #19414: SEO Tools: standardize title and description sanitizing
#### Steps to reproduce the issue

1. Start from a site connected to WordPress.com, and go to Jetpack > Settings > Traffic
2. Add some custom titles and a custom description, save your changes.
3. You'll notice that the 2 fields do not handle sanitizing the same way: some strip, some escape;

```
// Title:
[tagline]<script>alert('foo')</script>
// becomes:
[tagline]&lt;script&gt;alert('foo')&lt;/script&gt;

// Description:
Lorem ipsum <script>alert('foo')</script>
// becomes:
Lorem ipsum
```

Original report: p8oabR-DS-p2#comment-5185

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

- `sanitize_front_page_meta_description` will use `wp_strip_all_tags`
- `sanitize_title_formats` will use code from `wp_strip_all_tags`, but
we need to preserve the spacing (e.g. no trim)

Fixes #19414

#### Jetpack product discussion

* Internal: p8oabR-DS-p2#comment-5185

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* After applying changes, navigate to `/wp-admin/admin.php?page=jetpack#/traffic`, and down to the front page meta description section.
* Try saving a string like: `test <script>alert('hi');</script>` After saving the `<script>` portion should be removed.
* The same should be repeated for a custom page title structure.

### CODE REVIEW

**Comment by samiff** [comment]
Both the front page meta description and custom SEO titles are now using `esc_html` for sanitization. I like the idea of always saving the sanitized input to the db, so I think this makes sense.

The issue I was having with that is for the inputs or live previews, they were showing those encoded HTML entities which seemed not great. I couldn't figure out a way to have React just "render" these without using something like `dangerouslySetInnerHTML` which also doesn't seem great.

So I've tried using `@wordpress/html-entities` here to decode those for the inputs/previews. From what I gather this should be safe in the context of an input/text-area or when outputting via JSX since React will escape that by default.

Definitely could use a second look here though in case I've overlooked something. cc: @jeherve 

If this makes sense, then Calypso will need an update as well.

Markup on 2021-04-05 at 15:14:07

**Review by jeherve — CHANGES_REQUESTED** [review]
I'm honestly not sure what's best here. Part of me wonders if it wouldn't be best to use something like `wp_strip_all_tags` and trim for all SEO inputs, so we wouldn't have to deal with tags at all. I worry I'm missing a use-case, but right now this seems like a good idea to me. What do you think?

**Comment by jeherve** [comment]
Adding this internal reference as something to keep in mind for future work on this: p3btAN-Fj-p2

**Comment by samiff** [comment]
Thanks for that link @jeherve

I think `wp_strip_all_tags` would be ok `advanced_seo_front_page_description`. Users could always manually enter in the HTML entities if needed to get around them being stripped out if necessary.

Though `wp_strip_all_tags` calls `trim` by itself, which isn't great for the `advanced_seo_title_formats` since we want to preserve the spacing around each non-token:

```
Welcome to [site_name] | [tagline]
would be stripped of the spacing:
Welcome to[site_name]|[tagline]
```

How awful would it be to copy/paste from [wp_strip_all_tags](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/):

```php
$string = preg_replace( '@<(script|style)[^>]*?>.*?</\\1>@si', '', $string );
$string = strip_tags( $string );
```

To be used in the `sanitize_title_formats` function? 

Just for context, prior to any of the recent SEO in wp-admin work, there wasn't any sanitization being done for the `advanced_seo_title_formats` option; and `advanced_seo_front_page_description` was using `sanitize_text_field`.

**Comment by jeherve** [comment]
> wp_strip_all_tags calls trim by itself, which isn't great for the advanced_seo_title_formats since we want to preserve the spacing around each non-token

I didn't think about that, good call.

> How awful would it be to copy/paste from wp_strip_all_tags:

I like that idea. Maybe we could have tests accompanying this, to test different inputs and how things get sanitized?

**Comment by samiff** [comment]
> Maybe we could have tests accompanying this, to test different inputs and how things get sanitized?

@jeremy I've given that a shot in b2abf77 let me know how it looks 👍

**Review by jeherve — APPROVED** [review]
This looks good to me, nice work! 👏 🚢

**Comment by kraftbj** [comment]
r224802-wpcom

**Pull request merged**
