### PR TITLE
Avoid errors on related posts when the main DIV is not in the DOM

### PR DESCRIPTION
**Pull request by leogermani**
In our [support documentation for Related Posts](https://jetpack.com/support/related-posts/customize-related-posts/#delete), we recommend a code snippet to remove the Related Posts section from the post content. This snippet completely removes the main Related Posts DIV causing JS to trigger an error.

See 6959-gh-jpop-issues

The snippet is:

```PHP
function jetpackme_remove_rp() {
    if ( class_exists( 'Jetpack_RelatedPosts' ) ) {
        $jprp = Jetpack_RelatedPosts::init();
        $callback = array( $jprp, 'filter_add_target_to_dom' );
 
        remove_filter( 'the_content', $callback, 40 );
    }
}
add_action( 'wp', 'jetpackme_remove_rp', 20 );
```

This PR avoids JS to trigger error in the case the Related Posts DIV is not present in the DOM.

#### Changes proposed in this Pull Request:

* Avoid errors on related posts when the main DIV is not in the DOM

#### Jetpack product discussion

6959-gh-jpop-issues

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Ping me if you want a JN site ready for testing

* First confirm the bug (master branch):
* On a new site with some content and Related Posts enabled
* Visit a single post and make sure Related Posts is working normally
* Add the code snippet above to your theme's `functions.php`
* Reload the page and confirm you see an error in the console from related posts `Uncaught Type Error: ...`
* Checkout this branch, rebuild the branch, and make sure there are no errors in the console
* Remove the Code snippet and make sure Related Posts is working normally again

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
This should work. Could you bust the cache for that file?
https://github.com/Automattic/jetpack/blob/6a784afb360f04993f63dd82eaef67c77df29504/projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php#L8

**Comment by leogermani** [comment]
> This should work. Could you bust the cache for that file?
> 
> https://github.com/Automattic/jetpack/blob/6a784afb360f04993f63dd82eaef67c77df29504/projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php#L8

Good catch. Done

**Review by samiff — APPROVED** [review]
Testing instructions worked well for me 👍

**Comment by samiff** [comment]
cherry-picked to jetpack/branch-10.2 in 1b0b60af5a663e6c29cdf362ae4cf8552cc343e4

**Comment by leogermani** [comment]
r232591-wpcom

**Pull request merged**
