### PR TITLE
General: Update the Jetpack plugin name

### PR DESCRIPTION
**Pull request by kraftbj**
Per request from Rob Pugh, remove "by WordPress.com" from the plugin name and update the description.

#### Changes proposed in this Pull Request:

* Update the plugin name.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

n/a
#### Testing instructions:

* Verify the updated name in the Plugins list.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This should be good to merge. I will say, for the record, that "made by the WordPress experts" it still odd to me, since there are many WordPress experts in the community  ¯\_(ツ)_/¯

**Comment by kraftbj** [comment]
@jeherve "made by some of the best WordPress experts"? "made by the experts at WordPress.com"?

I 100% support tweaking the exact wording.

**Comment by jeherve** [comment]
I like your second alternative best, personally. 👍

**Comment by kraftbj** [comment]
Going with just striking "the" per p1620818588110700/1620771107.102600-slack-GQK64C7B4

**Pull request merged**
