### PR TITLE
Jetpack Boost: Improve the image guide

### PR DESCRIPTION
**Pull request by pyronaur**
Minor tweaks to the image guide feature.

#### Changes proposed in this Pull Request:
* Change the backdrop method when hovering over an image bubble, this makes the feature look nicer.
* Fix Jetpack logo position in admin bar
* Make sure the Jetpack logo is grayed out when paused state is active
* Listen for window resize events and recalculate image dimensions
* Update severity level colors

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pc9hqz-1lh-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Apply patch and try it out.

### CODE REVIEW

**Review by dilirity — DISMISSED** [review]
Looks good.

**Review by dilirity — DISMISSED** [review]
Looks good (again).

**Review by thingalon — DISMISSED** [review]
These changes look fine, but some linting issues need fixing.

**Review by thingalon — APPROVED** [review]

**Comment by haqadn** [comment]
Cherry-picked 3bd9f8e3551099

**Pull request merged**
