### PR TITLE
VideoPress plugin: Hijack the edit attachment page

### PR DESCRIPTION
**Pull request by leogermani**
#### Changes proposed in this Pull Request:

In the VideoPress plugin, we will have a central place to edit video details. This will be the one source of truth for video metadata.

This PR disables the editing of metadata from the Media library, that currently only works in the Jetpack plugin, and hijacks the link to the edit page of the video (this page is not implemented yet)

This will still need an iteration of design in a following PR.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pe4Cmx-40-p2#comment-13

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Make sure you have at least a couple of attachments and one VideoPress video uploaded to your site
* Activate VideoPress plugin
* Go to Media
* In your Media library, browse your attachments
* Make sure attachments that are not videopress video still work as usual
* Make sure the video details on the right does not give you the option to edit and show only info like the image below
Captura de tela de 2022-08-22 15-50-03

* Make sure the "Edit video details" links to the plugins page, with a `#/video/$ID/edit` route in the URL

* Create a new post
* Add a VideoPress block
* Click "Media Library"
* click on a VideoPress video
* Make sure the video details on the right does not give you the option to edit and show only info like the image below
Captura de tela de 2022-08-22 15-49-54

* Make sure the "Edit video details" links to the plugins page, with a `#/video/$ID/edit` route in the URL

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202813985335453

### CODE REVIEW

**Comment by jeffgolenski** [comment]
@leogermani Just for clarity, what kind of design input are you requesting from design? If it's simply the "edit video details" placement, I'd say it's fine since it uses the built in WordPress UI. 

I'll tag @keoshi to confirm since he commented on the original post though!

**Review by keoshi — DISMISSED** [review]
UX and UI-wise this is looking great! Beautiful simplification of the default UI, Leo!

**Comment by keoshi** [comment]
Question though @leogermani: could we add a small "Jetpack VideoPress" logo here to denote the special type of content even more clearly?

**Comment by leogermani** [comment]
@keoshi What do you think?

Captura de tela de 2022-08-23 10-33-40
Captura de tela de 2022-08-23 10-33-34

**Comment by keoshi** [comment]
That looks great, @leogermani — for our purposes though, I wonder if we should use the same logo present on the following page (Edit video details):

image

image

What do you think?

**Comment by leogermani** [comment]
@keoshi, sure, this should be doable. Can you detail how this logo should be applied in that context?

**Comment by keoshi** [comment]
@leogermani How does this look? 

image

Screen Shot 2022-08-25 at 14 00 11

**Review by retrofox — APPROVED** [review]
Probably we'd like to increase the space there...
image

... according on [this commit](https://github.com/Automattic/jetpack/pull/25732#issuecomment-1227224137).

Anyway, LGTM. 🚢

**Pull request merged**
