### PR TITLE
Convert class variable declarations form "var" to "public"

### PR DESCRIPTION
**Pull request by mospaw**
Replacing a deprecated definition from PHP4.

### CODE REVIEW

**Comment by zinigor** [comment]
@mospaw this looks good, but can you please rebase so we can test again and merge?

**Comment by dereksmart** [comment]
punting unless @mospaw is able to get the rebase in before monday

**Comment by mospaw** [comment]
It will be easier to re-do the changes on a later version of master. Too many conflicts for my git-fu to deal with. Unless someone wants to help...

**Comment by samhotchkiss** [comment]
@mospaw -- hope all is well!  I've moved this to #2521 so that we can modify it, you can follow along there.

Thanks!

**Pull request closed without merging**
