### PR TITLE
[RNMobile] Add replace functionality

### LINKED ISSUE #5585: Add Replace control
## Description

Add replace control to allow replacing the video with:
- Local video from the device.
- Take a video.
- Video from Media Library.
- Insert from URL
- Other apps (only on iOS)

**NOTE:** The functionality will be the same as we have on other media blocks.

### PR DESCRIPTION
**Pull request by fluiddot**
Closes https://github.com/wordpress-mobile/gutenberg-mobile/issues/5585.

## Proposed changes:

* https://github.com/Automattic/jetpack/commit/92f04aab27b135dbfc7a8df755d39d94ebe039c3: Implement `ReplaceControl`, similarly to the logic of the Video block ([reference](https://github.com/WordPress/gutenberg/blob/88e97c48648a4ffb2aa15def3ded14be8b65eb51/packages/block-library/src/video/edit.native.js#L217-L235)).
* https://github.com/Automattic/jetpack/commit/d7a76ea1e4dbcb6005751f1d6b5e9fb394cc21e4: Communicate to `VideoPressUploader` component when replacing the video with a new upload.
* https://github.com/Automattic/jetpack/commit/b1214721b259db0b8b485aced41914cb5dc7fbf6: Render the `ReplaceControl` in the block controls and add the handlers. The logic of the handlers is also quite similar to the web version.
* https://github.com/Automattic/jetpack/commit/5f135540baf00f54627317445324870bb98094dc: Following the web version, when replacing with a new upload, the entire block is replaced with a new one merging old and new attributes.
* https://github.com/Automattic/jetpack/commit/d58433fdaaaff2e10bbd71539080ffe4e01b6e4a: I noticed when testing that replacing with a video from the media library was setting the `src` attribute. This attribute is not set when adding a video from the media library in an empty block, so for consistency, I removed this logic. The `src` attribute is populated in the web version but seems the value comes from the VideoPress metadata, which we don't support yet.
* https://github.com/Automattic/jetpack/commit/cf4f67a9b3882fe43c91a1a250f361f4fd6c1d29: The web version of the block restores the previous attributes of the block when canceling an upload triggered by a replacement. I saw that we don't have this functionality in the Video block, however, I implemented it for this block as it's a helpful and easy feature.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

N/A

## Testing instructions:

**Preparation:**
1. Create a post.
2. Add VideoPress block.
3. Add a video from any of the sources.
4. Observe that the video is displayed.

### Upload local video
1. Tap on the  button to replace the video.
2. Select the "Choose from device" option.
3. Select a video.
4. Observe that a progress bar is displayed while the upload is in progress.
5. Once the upload finishes, observe that the video is displayed.

### Take a video
1. Tap on the  button to replace the video.
2. Select the "Take a Video" option.
3. Record a video and upload it.
4. Observe that a progress bar is displayed while the upload is in progress.
5. Once the upload finishes, observe that the video is displayed.

### WordPress Media Library
1. Tap on the  button to replace the video.
2. Select "WordPress Media Library" option.
3. Select a video.
4. Observe that the video is displayed.

### Insert from URL
1. Tap on the  button to replace the video.
2. Select the "Insert from URL" option.
3. Add a VideoPress URL (e.g. https://videopress.com/v/YzEZpv1G).
4. Observe that the video is displayed.

### Other Apps _(only available on iOS)_
1. Tap on the  button to replace the video.
2. Select the "Other Apps" option.
3. Select a video.
4. Observe that a progress bar is displayed while the upload is in progress.
5. Once the upload finishes, observe that the video is displayed.

### Attributes are persisted
When replacing a video, most of the attributes should be persisted.

1. Open the block settings and change some of the settings.
3. Follow any of the above test cases to replace the video.
4. Open the block settings and observe that the settings haven't changed.

**NOTE:** Title and Description attributes might change when inserting a video from the media library, these attributes are populated using the media's metadata.

### Cancel upload
1. Follow the steps from _Upload local video_ to replace the video with a new upload.
2. Before the upload finish, tap on the block and cancel the upload.
3. Observe that the block displays the previous video and that attributes haven't changed.

### CODE REVIEW

**Review by SiobhyB — DISMISSED** [review]
@fluiddot, I went through all the flows and this works super well for me 🚀

A suggestion I have is related to error handling. I noticed that no error pops up when going through the replace flow and attempting to insert a video from an incorrect URL. It would be great to add an error as either part of this PR or a separate PR. 

I'll go ahead to approve this PR as it's not necessarily a blocker to merging. 🙇‍♀️ 

| Test | iOS | Android |
| :---         |     :---:      |          ---: |
| Upload local video   | ✅ | ✅ |
| Take a video     | ✅ | ✅ |
| Insert from URL (valid)     |  ✅      | ✅ |
| Insert from URL (invalid)     | ❓ | ❓ |
| Other apps    |  ✅  | N/A |
| Attributes persisted    | ✅ | ✅ |
| Cancel upload    | ✅ | ✅ |

**Comment by fluiddot** [comment]
> A suggestion I have is related to error handling. I noticed that no error pops up when going through the replace flow and attempting to insert a video from an incorrect URL. It would be great to add an error as either part of this PR or a separate PR.

Good catch! I completely overlooked that case. I'll handle that error in this PR as I expect it as a small update. Thanks @SiobhyB 🙇  !

**Comment by fluiddot** [comment]
> > A suggestion I have is related to error handling. I noticed that no error pops up when going through the replace flow and attempting to insert a video from an incorrect URL. It would be great to add an error as either part of this PR or a separate PR.
> 
> Good catch! I completely overlooked that case. I'll handle that error in this PR as I expect it as a small update. Thanks @SiobhyB 🙇 !

Fix applied in https://github.com/Automattic/jetpack/pull/29662/commits/ecc67d9c6a5ebd69178465698d58e2f1c3848a53. Let me know @SiobhyB if you could take another look at the PR, thanks!

**Review by SiobhyB — DISMISSED** [review]
Fix works perfectly, thanks @fluiddot! 🎉 

Simulator Screen Shot - iPhone 14 Pro - 2023-03-24 at 14 14 58

**Comment by fluiddot** [comment]
@SiobhyB seems your approval has been dismissed due to a conflict resolution when merging `trunk` into the branch (https://github.com/Automattic/jetpack/pull/29662/commits/8d5f5f5fce0ee15cb0bf7f71eae2dab024c80a79). Let me know if you could approve the PR again, thanks 🙇 !

**Review by SiobhyB — APPROVED** [review]
@fluiddot, looks great to me! 🚀

**Pull request merged**
