### PR TITLE
Carousel: disable WordPress Core' Lightbox option

### LINKED ISSUE #32668: Carousel: conflict with Gutenberg Lightbox behavior
### Impacted plugin

Jetpack

### Quick summary

With the release of Lightbox for Image Blocks in the Gutenberg plugin, there's a conflict between Jetpack's Carousel and the core Lightbox behavior when using a core Gallery Block.

Somewhat similar to https://github.com/Automattic/jetpack/issues/19496 and https://github.com/Automattic/jetpack/issues/17484

### Steps to reproduce

1. Turn on Carousel
2. Add a core Gallery Block
3. In the Image Block inside the Gallery Block, select "Lightbox" in Advanced > Behaviors
4. Open the post/page and click on the image - it will show Carousel first, and after a second click it will show GB's lightbox

### A clear and concise description of what you expected to happen.

In core blocks, if I select the Lightbox behavior, it should use that instead of Carousel, as that action is more specific, since it's defined at block-level

### What actually happened

Carousel was shown in the first click, and core's Lightbox after trying to exit, creating a confusing experience

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

WordPress 6.3, Gutenberg 16.5

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #32668

## Proposed changes:

It's best to keep only one lightbox option, to avoid any confusion. Since Jetpack's Carousel feature currently offers more features, let's keep ours in favor of Core's for now.
In the future, when core's lightbox option becomes more robust, we can consider deprecating Jetpack's Carousel feature altogether.

> [!WARNING]
> This currently breaks some tests on WordPress.com, but I'm not sure how to best address that. Should I simply update the tests to expect that data added by Carousel for now?

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No
## Testing instructions:

> [!NOTE]
> This currently requires the `trunk` version of the Gutenberg plugin. When using the current stable version of the plugin, or no Gutenberg plugin at all, that fix will not work.

* Start with a site using a block-based theme like Twenty Twenty Four
* Go to Jetpack > Settings > Writing and enable the Carousel feature.
* Go to Posts > Add New
* Add a new Image block, and upload an image.
* In the block's toolbar, under the linking options, you should see an option to "expand on click".
* Now switch to this branch.
* Go to Posts > Add New
* Add a new Image block and insert a new image.
* The option should now be gone from the block's toolbar.
* Go to Jetpack > Settings > Writing and disable the Carousel feature.
* Go to Posts > Add New
* Add a new Image block and insert a new image.
* The option should be back in the block toolbar's link settings.

### CODE REVIEW

**Review by monsieur-z — APPROVED** [review]
Works as advertised.

**Comment by jeherve** [comment]
@david-binda I'd like to have your opinion on this. What would be the best way for me to solve this problem? 

In short, this PR makes changes to themes' configuration when the Carousel feature is enabled. Since it is always enabled on WordPress.com Simple, it causes the unit tests to fail (more precisely, the `Tests_Theme_wpThemeJsonResolver` tests).
How should I work around that, short of not making the changes when tests are running like so:

```diff
diff --git a/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
index cac86b3a6d..5a8e1180fe 100644
--- a/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
+++ b/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php
@@ -218,6 +218,11 @@ class Jetpack_Carousel {
 	 * @param WP_Theme_JSON_Data $theme_json Class to access and update theme.json data.
 	 */
 	public function disable_core_lightbox( $theme_json ) {
+		// Do not customize the theme configuration in unit tests.
+		if ( defined( 'TEST_REQUEST' ) && TEST_REQUEST ) {
+			return $theme_json;
+		}
+
 		return $theme_json->update_with(
 			array(
 				'version'  => 2,
```

Thank you!

**Comment by david-binda** [comment]
> Since it is always enabled on WordPress.com Simple, it causes the unit tests to fail

Could it the tests in question be adjusted to reflect that? IMHO, it's bette to adjust the tests accordingly rather than disabling the feature when tests are run, as the tests should reflect the code run in production.

**Comment by jeherve** [comment]
Merging this now. The WordPress.com tests will need to be updated to match that change:

- p1711547897084499-slack-CBG1CP4EN
- D143627-code

**Comment by liviopv** [comment]
@jeherve what will happen on sites where customers have intentionally activated core lightbox on specific images or via global styles?

**Comment by jeherve** [comment]
@liviopv Existing images should not be impacted, but you won't be able to add the core lightbox to new image blocks you add (unless you go and deactivate the Carousel feature in Jetpack > Settings).

**Comment by jeherve** [comment]
> will this affect self-hosted sites too?

It will, yes, if they've activated the Carousel feature on their site.

> Aside from showing metadata and captions (which I don't think are part of core yet) what other features do you have in mind?

This is indeed what I had in mind. On top of this, Core's Lightbox is built with single images in mind, so although it is available for images in galleries it doesn't support galleries yet. Jetpack's Carousel, on the other hand, was built with galleries in mind.

**Pull request merged**
