### PR TITLE
Jetpack Blocks: Migrate the Timeline block from ETK

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/dotcom-forge/issues/8032, https://github.com/Automattic/dotcom-forge/issues/8036

## Proposed changes:

* Migrate the Timeline block to Jetpack Blocks

| Editor | Frontend |
| - | - |
| image | image |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your site
* Go to the editor
* Insert the `Timeline` block
* Add any timeline entry
* Configure the `Alternative` setting of the `Timeline` block
  image
* Configure the left/right setting of the `Timeline Entry` block
  image
* Configure the background color of the `Timeline Entry` block
  image
* Make sure everything works as expected
* Preview your changes
* Make sure the `Timeline` block looks good on your frontend page

### CODE REVIEW

**Comment by okmttdhr** [comment]
I may not be up to date 🙏, but could you explain why this uses the `jetpack/extensions/blocks` directory instead of `jetpack-mu-wpcom`? Will this block be available only to wpcom?

**Review by okmttdhr — APPROVED** [review]
The block worked as expected for me 👍

**Comment by arthur791004** [comment]
> I may not be up to date 🙏, but could you explain why this uses the jetpack/extensions/blocks directory instead of jetpack-mu-wpcom? Will this block be available only to wpcom?

These blocks are designed for Jetpack but they were implemented in ETK plugin first. So, I think it makes sense to migrate them to Jetpack. See https://github.com/Automattic/wp-calypso/pull/37889

**Review by taipeicoder — APPROVED** [review]
Works nicely 👍

**Comment by ChrisBegley** [comment]
Hello, the release notes for 13.7 say that the Event Countdown and Timeline blocks were added: https://wordpress.org/plugins/jetpack/#developers

However, I don't see these blocks on my websites running Jetpack 13.7. I confirmed that I have "Jetpack Blocks" turned on under "Jetpack Settings > Writing > Composing"

This is a problem on multiple websites across multiple hosts, including locally with WordPress.com Studio.

**Comment by arthur791004** [comment]
Referring to https://github.com/Automattic/dotcom-forge/issues/8036#issuecomment-2222306034, we [moved those blocks to jetpack-mu-wpcom](https://github.com/Automattic/jetpack/pull/38298) so it's only available on atomic sites with the mu-wpcom plugin.

**Comment by ChrisBegley** [comment]
@arthur791004 I see, so what does a self-hosted Jetpack user need to do to use the new Timeline block?

**Comment by arthur791004** [comment]
> The blocks in Jetpack will be shipped in a new Jetpack Extras plugin instead.

As [discussion](https://github.com/Automattic/dotcom-forge/issues/8036), we don't want to expose blocks in the Jetpack plugin. If the Timeline block is useful for Jetpack users, I think we can consider to include the Timeline block in the new Jetpack Extras plugin in the future cc @jeherve

**Comment by ChrisBegley** [comment]
@arthur791004 thanks for the clarification, I don't have access to this page: https://github.com/Automattic/dotcom-forge/issues/8036

I guess I'm confused by the WordPress.org changelog for Jetpack 13.7. It says: https://wordpress.org/plugins/jetpack/#developers

>**Changelog**
>**13.7 – 2024-08-06**
>**Enhancements**
> Blocks: Add the EventCoutdown block.
> Blocks: Add the Timeline block.

But those blocks aren't actually available to be used? They'll be coming later to a new Jetpack Extras plugin?

**Comment by arthur791004** [comment]
> But those blocks aren't actually available to be used? They'll be coming later to a new Jetpack Extras plugin?

It's a mistake we forgot to remove that changelog 🙈 Now it's only for WordPress.com users

**Comment by ChrisBegley** [comment]
Ohh ok. Thanks for clearing that up.

**Pull request merged**
