### PR TITLE
Fix: When footer is not enabled, avoid JS errors

### LINKED ISSUE #15348: Infinite Scroll: broken when footer is set to false
#### Steps to reproduce the issue

1. Install a theme such as [Cubic](https://wordpress.com/theme/cubic/) on a Jetpack site.
    - Another theme would do, the important part is that the theme must set the `footer` parameter to `false` when declaring support for Infinite Scroll, like so:
```php
function cubic_jetpack_setup() {
        /**
         * Add theme support for Infinite Scroll.
         * See: http://jetpack.me/support/infinite-scroll/
         */
        add_theme_support( 'infinite-scroll', array(
                'container'      => 'main',
                'footer'         => false,
                'wrapper'        => false,
                'posts_per_page' => 9,
        ) );
}
add_action( 'after_setup_theme', 'cubic_jetpack_setup', 11 );
```
2. Create many posts so IS can be triggered.
3. Not that IS is not triggered, and the following JS error appears:
```js
Uncaught TypeError: Cannot read property 'setAttribute' of null at Scroller.gotop (infinity.min.js?ver=8.4-alpha-is5.0.0:3)
```

This was caused by #15017. Since those themes do not have a footer, this won't find an element:
https://github.com/Automattic/jetpack/blob/30140ab4e188bda3820346b9d2a83e6eb244d9ad/modules/infinite-scroll/infinity.js#L202

Until we have a fix, I would recommend forcing Infinite Scroll to show a footer, and then hide that footer with CSS. This can be done [in a functionality plugin](https://jetpack.com/support/adding-code-snippets/):

```php
function jetpackcom_fix_broken_is() {
	add_theme_support( 'infinite-scroll', array(
		'type'           => 'scroll',
		'container'      => 'main',
		'footer'         => true,
		'wrapper'        => false,
		'posts_per_page' => 9,
	) );
}
add_action( 'after_setup_theme', 'jetpackcom_fix_broken_is', 12 );

function jetpackcom_hide_is_footer() {
	wp_add_inline_style( 'the-neverending-homepage', '#infinite-footer{display:none;}' );
}
add_action( 'wp_enqueue_scripts', 'jetpackcom_hide_is_footer' );
```

### PR DESCRIPTION
**Pull request by dero**
Fixes #15348

#### Changes proposed in this Pull Request:
* Makes explicit checks for the existence of footer and the blog title element within in order to not initialize any logic that depend on footer being present on the page.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This is a fix that applies to the Infinite Scroll module.

#### Testing instructions:
* Follow the steps outlined in #15348
* Observe no JS errors being reported.
* Observe a working IS.

#### Proposed changelog entry for your changes:
* Fixes an Infinite Scroll bug that prevented its functionality on themes without footers.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Could you rebase now that #15366 is merged? That should fix the tests. Thanks!

**Comment by dero** [comment]
@jeherve Done.

**Review by jeherve — APPROVED** [review]
This seems to test well for me. Leaving it for a second review too.

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.4` in 5ed2d6d03a321a6548c273540add799bfba676b4

**Pull request merged**
