### PR TITLE
ci: Automatically tag project releases

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

This will automatically create tags like "packages/autoloader@3.0.2" or "plugins/jetpack@12.9" as projects are released.

The logic used is similar to the autotagger: on push to trunk or prerelease for projects without a release-branch-prefix and on push to corresponding release branches for projects with a release-branch-prefix, if the `/changelog/` directory for the project is empty and the first entry in CHANGELOG.md is a release version number, it'll create the corresponding tag for the project.

Note that when this is first merged, it'll probably create a bunch of tags incorrectly pointing to that commit for things that were recently released and haven't been bumped since. We'll have to fix those manually. We'll also have to manually create tags for all the previous releases if we want them. A list of tags and what I could find for corresponding commits is here: [tags.tsv](https://github.com/Automattic/jetpack/files/13444537/tags.txt)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes https://github.com/Automattic/garage-backlog/issues/23

## Testing instructions:

* Merge this into a fork, push various commits, and see what happens.

### CODE REVIEW

**Comment by anomiex** [comment]
BTW, in case anyone is interested, I created that [tags.tsv](https://github.com/Automattic/jetpack/files/13444537/tags.txt) like this:

* The list of possible tags is from checking out all the mirror repos and looking at the tags. 😀
* Where the tagged commit includes the "Committed via a GitHub action" line and the linked run still exists, I read the corresponding commit from that.
* Where it included that line but the linked workflow run no longer exists (I guess GH deletes old runs), I looked for an exact match to the commit summary.

**Review by sdixon194 — APPROVED** [review]
Let's give this a go 👍

**Comment by anomiex** [comment]
* [x] Tags created for backlog.

**Comment by sdixon194** [comment]
Screenshot 2023-11-29 at 1 11 30 PM

:D

**Comment by anomiex** [comment]
😀

I wound up creating 3504 tags total: the ones in the tsv linked above, plus tags for two releases since I created that, plus I matched up old tags like "[1.1](https://github.com/Automattic/jetpack/releases/tag/1.1)" and "[automattic/jetpack-assets@1.0.0](https://github.com/Automattic/jetpack/releases/tag/automattic/jetpack-assets@1.0.0)". 750 potential tags I didn't have a commit to match them with.

pdWQjU-D3-p2

**Pull request merged**
