### PR TITLE
Update the styling and formatting of the form submission page

### LINKED ISSUE #27295: Form Block: Improve Styling/Formatting of Form Submission View
Currently the submission view looks a bit off.

The feedback to users "Message sent" is shown in a H3 and can depending on the theme be pretty big.
The label of a data field is in the same styling as the response, which makes it hard to read.

Image

### PR DESCRIPTION
**Pull request by donnchawp**
The styling of the page shown after a form is submitted is updated by this PR. It is a visual only change.

Fixes  #27295.

#### Changes proposed in this Pull Request:
* The styling of the form submission page is updated. The exact styling of fonts used will depend on styling of the theme.

pcsBup-py-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:
* Using this branch, create a contact form block in a post or page.
* Preview the page and fill in the survey and submit it.
* The page shown after submitting should look much like that in #27295

Before:

200317711-c58ec9bb-a503-4a12-b42a-c7e467782482

After:
Screenshot 2022-11-14 at 16 00 48

### CODE REVIEW

**Review by digitalwaveride — DISMISSED** [review]
Thanks so much Donncha!!!
Looking good! 🚀

**Comment by CGastrell** [comment]
Looking good on .com:
image

Looking good on AT:
image

**Comment by bindlegirl** [comment]
@donnchawp I see a bunch of failed tests. Could you check them out?

**Review by samiff — DISMISSED** [review]
Liking the updated look 👍 

- Updated the tests to match the new output in a3af55a
- Just noting that the left-arrow dashicon will only load/display for logged in users
- I'm not quite sure if using an `h4` makes semantic sense if the only reason is the font sizing. But it can't be worse than an `h3` with no particular reason 🤷

**Comment by donnchawp** [comment]
Thanks, @samiff, for updating the test. I was afk last week with Covid. The left arrow has been removed, and the "go back" link is now left-aligned. I think h4 is being used for font styling, that's all. We'll let the theme style it.

**Comment by bisko** [comment]
There are still some failing tests, that fail the match of the updated messaging, e.g.:

```
[test-extensions]     -       "customThankyouHeading": "Message Sent",
[test-extensions]     +       "customThankyouHeading": "Your message has been sent",
```

**Comment by CGastrell** [comment]
Works well on AT site

**Review by CGastrell — DISMISSED** [review]
Code looks good, works nicely on AT sites

**Comment by CGastrell** [comment]
Working nicely on .com as well

**Review by samiff — APPROVED** [review]
Looks good :shipit:

**Pull request merged**
