### PR TITLE
Add Unified Admin Color Schemes module skeleton

### PR DESCRIPTION
**Pull request by getdave**
Adds a new module skeleton to provide a starting point for all code required for the admin color scheme unification on Dotcom.

#### Changes proposed in this Pull Request:

* Adds new module `unified-admin-color-schemes`.

#### Jetpack product discussion

https://github.com/Automattic/wp-calypso/issues/45675

#### Does this pull request change what data or activity we track or use?
Nope

#### Testing instructions:

* Checkout PR.
* Add some debugging to the `uacs_setup_admin` function.
* Check the debugging is run.

#### Proposed changelog entry for your changes:

* Adds `unified-admin-color-schemes` module.

### CODE REVIEW

**Review by marekhrabe — COMMENTED** [review]
This works okay as described. Let's add the file to the list as the bot comment above suggests.

The place for the module looks good to me but for this case, I'd rather have a secondary check from somebody in the crew, just to make sure we land it appropriately.

My other note is about the `uacs` shorthand. These always seem cryptic to me and I'm not sure whether that's a built-in system name or something we came up with. Would it make sense to write those words out or do something like `jetpack_color_schemes` instead? I'll leave this up to you, since I don't think it breaks any rule.

**Review by jeherve — CHANGES_REQUESTED** [review]
> The place for the module looks good to me but for this case, I'd rather have a secondary check from somebody in the crew, just to make sure we land it appropriately.

Discussion: p1604926678074100-slack-CJS75TX3R

My personal preference would be for us to expand the existing `masterbar` module, which already gets preferential treatment on Atomic sites, to include all those UI tweaks we'll be making for Atomic sites.

As part of the changes, we could even rename the module; as long as the module slug (the entry point's file name, `modules/masterbar.php`, remains the same, we won't lose anything. 

> My other note is about the uacs shorthand. These always seem cryptic to me and I'm not sure whether that's a built-in system name or something we came up with.

I think it'd be okay, and more readable to switch to a namespace that better describes this?

**Comment by obenland** [comment]
See #17629 for a first attempt at adding to the masterbar module

**Comment by getdave** [comment]
Note it we proceed with this approach we'll want to structure it as a class similar to how we'd done in https://github.com/Automattic/jetpack/pull/17762. We could also consider namespacing.

**Comment by obenland** [comment]
Fixed in #17762

**Pull request closed without merging**
