### PR TITLE
Justify presence of empty scss file

### PR DESCRIPTION
**Pull request by guarani**
The scss file was left blank to avoid the web-specific file from being imported into the native-mobile project.

#### Changes proposed in this Pull Request:

- Adds a note to an empty file to justify why the file wasn't deleted.

#### Jetpack product discussion

https://github.com/Automattic/jetpack/pull/21849#issuecomment-1015617082

#### Does this pull request change what data or activity we track or use?
No, it does not.

#### Testing instructions:
Make sure all valid CI checks pass.

### CODE REVIEW

**Comment by guarani** [comment]
> Tests / PHP tests: PHP 8.1 WP master (pull_request) 

The only failing test is the optional PHP 8.1 test which is known to fail.

**Review by mchowning — APPROVED** [review]
Thanks Paul! 🙇

**Comment by guarani** [comment]
Thank you @mchowning!

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
r238483-wpcom

**Pull request merged**
