### PR TITLE
Change VideoPress processing image to 142x142

### PR DESCRIPTION
**Pull request by dbtlr**
The icon that we're using for the jetpack image processing is too large for the given media box.

Changing it to be 142x142 works better. However, it still is not ideal, given that the size needs change depending on whether-on-not there is a title.

This is what it looks like now:

screen shot 2016-12-15 at 2 50 12 pm

Ideally, we would use a smaller icon with a transparent background so that it would center properly like the default icon does.

### CODE REVIEW

**Comment by dereksmart** [comment]
lgtm 
screen shot 2016-12-16 at 10 56 23 am

**Comment by jeffgolenski** [comment]
I can create a transparent icon for you early next week!

**Comment by dereksmart** [comment]
@jeffgolenski so then should we merge this?

**Comment by dbtlr** [comment]
Yes, let's merge this and we can add a new icon as another PR when that is completed.

**Comment by dereksmart** [comment]
👌

**Comment by dereksmart** [comment]
4.5 in fd9baed

**Pull request merged**
