### PR TITLE
Fix unnecessary calls to functions using filters in sources. 

### PR DESCRIPTION
**Pull request by NicoleA**
Reference additional comments on #2046 

Because the $share_url and $share_title are only used in the "smart" version of the source, the calls to the get_share_url() and get_share_title() functions has been moved into the if statement. This prevents the functions from being called unnecessarily.

The reason for has become apparent in a use case where the sharing_permlink filter is used to alter the link, but requires a call to an external api to do so. Having the get_share_url() outside the if statement means that the function is called every time the button is rendered. Whereas, moving it inside the conditional ensures it is only called where necessary.

Because the use case is not using "smart" buttons, the function doesn't get called until the process_request() function is called after clicking the share button. This ensures that the api call is only made when an action is taken on the button.

Having filters in these two functions, get_share_url() and get_share_title(), means that we should avoid calling them unnecessarily, preventing extraneous processing and potential pitfalls such as that encountered in this use case.

### CODE REVIEW

**Comment by georgestephanis** [comment]
I like it, I'm just concerned about inlining the functions instead of simply moving the variable declarations.  I've got a fix based on this coming, one sec.

**Comment by NicoleA** [comment]
Half of them were already inlined. The consistency is all over the map.

**Comment by georgestephanis** [comment]
@NicoleA: Does #2060 work for you?  I set you as the commit author for the retooled version if that's alright with you.

**Comment by georgestephanis** [comment]
My concern re: inlining isn't necessarily consistency between methods at the moment, it's more avoiding churn in blame histories and more granular commits.  If you wanted to fire off a whitespace fix pull request like you had bundled in the last pass, it'd certainly be welcome, but just try to keep it in a distinct changeset from the functional changes.

**Comment by NicoleA** [comment]
Understood. Thx

**Pull request closed without merging**
