### PR TITLE
RNA Base styles - Move RNA styles to base-styles package.

### PR DESCRIPTION
**Pull request by fgiannar**
Removes repeated `rna-styles.scss` files and imports them from the base-styles package instead.

#### Changes proposed in this Pull Request:
* Adds a `style.scss` in `base-styles` package
* Updates all corresponding imports to use those styles instead
* Removes duplicate `rna-styles.scss`

#### Jetpack product discussion

p9dueE-3MR-p2

It's important to note that **this PR does not solve the issues** mentioned in the Jetpack product discussion. 
It simply handles the multiple repeated `rna-styles` found in many packages/plugins by importing them from a single place.
Further optimizations, including:

1. handling global styles, 
2. breaking down the `base-styles/style.scss` to partials and 
3. importing ONLY what we need in component styles

should be handled in follow up PRs. 

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
- Ensure nothing has visually changed in the Jetpack-plugin Connect Screen
- Ensure nothing has visually changed in the Backup plugin
- Run storybook and verify all components are also the same

Finally look at the code to ensure we didn't miss any variables defined only in one of the multiple `rna-styles`.

### CODE REVIEW

**Comment by leogermani** [comment]
Hey Foteini, thanks for working at this.

I looked at the code and apparently everything that was on the deleted rna-style files are there. 

But I did notice some visual differences. See screenshots:

Captura de Tela 2021-11-17 às 15 47 28
Captura de Tela 2021-11-17 às 15 47 34

The background is grey and the button width is smaller. 

In Storybook, the connection Screen background is white, but the button is also smaller.

I'll try to look deeper at this but leaving a comment in case I can't do anything before you see this.

**Comment by fgiannar** [comment]
Hey @leogermani ,

With which branch are you comparing? I'm testing on a JN site with Jetpack and Backup running on Bleeding Edge and can reproduce both issues?

I don't mind fixing those in this PR, however want to make sure it's not introducing those issues here.

**Comment by leogermani** [comment]
> Hey @leogermani ,
> 
> With which branch are you comparing? I'm testing on a JN site with Jetpack and Backup running on Bleeding Edge and can reproduce both issues.
> 
> I don't mind fixing those in this PR, however want to make sure it's not introducing those issues here.

You`re right. I was comparing it with stable.

Well this is a problem! I`m gonna try and see where this was broken!

**Review by leogermani — APPROVED** [review]
I say let's merge it and continue improving the CSS organization in following PRs

**Comment by anomiex** [comment]
r235277-wpcom

**Pull request merged**
