### PR TITLE
Licensing: Display notice when user has unactivated licenses

### PR DESCRIPTION
**Pull request by elliottprogrammer**
This PR displays a ""You have an inactive product. Activate now" notice in the dashboard if the user has unactivated product license keys available.

#### Changes proposed in this Pull Request:

- Register API route (/jetpack/v4/licensing/user/counts)  for fetching user license counts.
- Fetch user license counts and store them in initialState.
- Create reducer, actions, and selector for retrieving and updating user license counts in redux state.
- Display notice when `hasDetachedUserLicenses( state )` is `true`.
- Removes notice after a license key is activated (if `hasDetachedUserLicenses( state )` is `false`).

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

- Spin up a site using this Jetpack branch. (If using a JN site, you'll want to select 'More options' and include the "Code Snippets" plugin because we'll need to add a filter)
- Connect Jetpack to your WordPress.com user account.
- Enable the license-key input box UI on the "My plan" page by adding `add_filter( 'jetpack_licensing_ui_enabled', '__return_true' );`
- Go to `/wp-admin/?page=jetpack#/dashboard#/my-plan` (aka "My plan" page)
- Verify you **do not see a notice** at the top that says, "You have an inactive product. Activate now." 
- Verify you can see the License Key input field (at the bottom of the "My Plan" section).

Now obtain a 'user' product license key:

- log into your wpcom sandbox, and in file `wp-content/mu-plugins/0-sandbox.php` add: `add_filter( 'jetpack_license_checkout_m2_enabled', '__return_true' );`. (Enabling this flag makes Jetpack checkout issue you a license when completing checkout).
- Point `public-api.wordpress.com` to your sandbox IP (in your hosts file).
- Open a new command-line window in your sandbox and `tail -f /tmp/php-errors`
- Make sure you are proxied and go to https://wordpress.com/checkout/jetpack/jetpack_scan (siteless checkout flow).
- Complete checkout (using credits is fine).
- View your error log, you should see the output: `Jetpack user license was created for subscription_id:17829922, belonging to user_id:78351100 and blog_id:198416894`, but with different id values corresponding to your user and site. And you'll also see, `License key is: jetpack_scan_monthly_oRhIEF4ckyVP6mCuHaD1vYnw5`, but with your unique key.
- Copy the license key from the error log output.
- un-sandbox `public-api.wordpress.com`.

Test that the notice appears now that you have been provisioned a detached license, and that it disappears when the license is attached (if you no longer have any detached licenses left):

- Go to your Jetpack site and reload `/wp-admin/?page=jetpack#/dashboard#/my-plan` (aka "My plan" page).
- Verify that you see a notice at the top that says, **"You have an inactive product. Activate now."**
- Paste the license key into the License Key input box and submit.
- Verify the "You have an inactive product. Activate now." notice **disappears** (Also you should see that the Jetpack Scan product has been provisioned for your site(You may need to refresh the page to see that))

### CODE REVIEW

**Review by rcanepa — COMMENTED** [review]
From a functional perspective, these changes are sound. The only thing I observed that we need to adjust is the banner's dismiss button. I think we need to persist a dismissal for some time or until a new unattached license appears. Otherwise, users who have multiple unattached licenses will be seeing the banner all the time. Can we add that?

Code changes look definitely in the right direction, but I'll let Jetpack Crew folks comment on that.

Awesome job, Bryan!

**Comment by rcanepa** [comment]
> Are you aware of anything like that for Jetpack? I'll look deeper into it, and maybe Crew may have some insight into this also. 👍

Not really, but I'm sure there must be a mechanism already in place for it. 

It might be worth looking into the `Initial_State.dismissedNotices` piece of state. Its name makes me think it might be exactly what we want.

**Comment by jeherve** [comment]
> I'm not sure whats going on with the failing Changelogger validity check. It tells me that the error is a version mismatch in js-packages/api package.json - expected 0.3.2-alpha but found 0.3.1.

That's indeed the problem here. Since you're making changes to that package, you'll need to highlight that by bumping the version, as mentioned here:
https://github.com/Automattic/jetpack/pull/21426/files#file-projects-js-packages-api-package-json-L3

> after I do this, then I get a bunch more errors in the Monorepo package version refs check and Build all projects check and maybe others. I don't understand it! 🤦🏼‍♂️

Since you bump the version, you need to update the places that use the package as a dependency to indicate that you now want to use the new alpha version. There is another script you can run to update all those references. You'll see the exact prompt in the next check, but I suspect `tools/check-intra-monorepo-deps.sh -u` may help you get ahead. :)

**Review by rcanepa — APPROVED** [review]
Once we fix the failing tests, I'm okay with leaving the dismiss button working as is because soon we will have to come back to this banner and change the link to make it point to the activation flow (it's going to live in a different URL). At that point, we can take care of implementing the right behavior of the dismiss button.

**Comment by elliottprogrammer** [comment]
> Once we fix the failing tests, I'm okay with leaving the dismiss button working as is because soon we will have to come back to this banner and change the link to make it point to the activation flow (it's going to live in a different URL). At that point, we can take care of implementing the right behavior of the dismiss button.

Oh perfect. Yes, I was also just about to suggest we handle the dismiss button in a follow-up PR also. Sounds good, thanks! 🙂

**Comment by elliottprogrammer** [comment]
I'm closing this PR in favor of https://github.com/Automattic/jetpack/pull/21426

I could not, for the life of me, get this PR to pass all the changelogger validity errors and package version refs errors and merge conflicts. I attempted running various tools and fixes but things just got even more mixed up beyond repair, so I decided to abandon this PR, and recreate a new PR from a freshly updated master branch. 🤦‍♂️  😊

**Pull request closed without merging**
