### PR TITLE
Convert Jetpack_XMLRPC_Server to a classmapped package

### LINKED ISSUE #12538: Jetpack DNA: XMLRPC package
The class Jetpack XMLRPC server needs to be its own package. We can likely use a lot of classmapping.

The connection package and API package will depend on it.

### PR DESCRIPTION
**Pull request by mdawaffe**
Fixes #12538

#### Changes proposed in this Pull Request:
* Moves `class.jetpack-xmlrpc-server.php` to `packages/xmlrpc-server`.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
N/A

#### Testing instructions:
* `phpunit --filter=WP_Test_Jetpack_XMLRPC_Server`

#### Proposed changelog entry for your changes:
None required.

#### TODO
- [ ] Move tests to package
- [ ] Resolve dependencies (`JetpackTracking`, `Jetpack_Options`, `Jetpack`, `Jetpack_Error`, `Jetpack_Client_Server`, `Jetpack_IXR_Client`, `WP_Error`, `IXR_Error`, `Jetpack_Data`, `WPCOM_JSON_API`, …?)

### CODE REVIEW

**Comment by mdawaffe** [comment]
I don't think this is the right approach. Rather than a package that provides all the XML-RPC methods, we should have a package that makes it easy to register XML-RPC methods:

```
namespace ….

class XMLRPC_Methods {
  public function add( string $method_name, array $auth_reqs ) {
    // $auth_reqs = [  }
}

**Comment by mdawaffe** [comment]
I think we can hold off on this until #12630 settles. It may be this PR isn't needed.

**Review by lezama — APPROVED** [review]
why not

**Comment by lezama** [comment]
hmm, merged to the wrong branch, @dereksmart @jeherve shouldn't we delete `feature/jetpack-packages`?

**Pull request merged**
