### PR TITLE
tools: Allow for multiple release branch prefixes in a plugin

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

We want to allow for releasing plugins in groups, for example the weekly release should include both jetpack and mu-wpcom-plugin, and the monthly should include jetpack, mu-wpcom-plugin, backup, and social.

However, as can be seen in the list above, we sometimes don't release _all_ the plugins in a group. And when we don't, that makes some tests fail because they can't tell the difference between "plugin in the group didn't get updated for release" and "plugin is not being released".

The solution to this is to allow a plugin to be in multiple groups, represented by it belonging to multiple prefixes.

This PR also removes the ability to release anything other than an entire prefix via `create-release-branch.sh`: you can no longer list multiple plugins on the command line, and you can no longer choose to release just one plugin if the plugin is always grouped.

This also loosens the check for a release branch in `jetpack changelog` and the pre-push hook, to accept release branches that use something other than a version number after the `/branch-`.

`tools/get-contributor-list.sh` is rewritten to not rely on release branches at all, instead it looks through the git history for the commits where the top entry in CHANGELOG.md matches the target version. There's a slight possibility for a race there to miss a contributor (if their one contribution is merged in between the prerelease branch cut and it getting merged back), but that seems fairly unlikely.

Note `tools/release-plugin.sh` is broken after this commit; we'll fix it as part of #29323.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Do all the changed things still work?

### CODE REVIEW

**Comment by anomiex** [comment]
Note that, before this can be merged, we'll want to update the regexes in https://betadownload.jetpack.me/plugins.json to reflect the added prefixes.

**Comment by anomiex** [comment]
> Note that, before this can be merged, we'll want to update the regexes in https://betadownload.jetpack.me/plugins.json to reflect the added prefixes.

Updated. After merging this (and after any existing release branches are done with) we should update it again to remove "jetpack" as an option for non-Jetpack plugins.

**Comment by kraftbj** [comment]
Needs a rebase. Would it make sense to wait to merge until after the Jetpack beta week just to avoid any possible issues during crunch time?

**Comment by anomiex** [comment]
@zinigor was already considering the relation of this to the beta earlier in the week. I don't know what his current thinking on that is, if he wants to wait until after the release next week or if he was thinking of going ahead now-ish now that be beta has been cut.

**Review by zinigor — APPROVED** [review]
I haven't really tested it, but the logic makes sense. Let's battle test it next week, and also merging this will unblock your other PRs.

**Pull request merged**
