### PR TITLE
Search: Auto-open/close modal in Customizer -> Jetpack Search

### LINKED ISSUE #50979: Customizing Jetpack search broken; modal gets hidden
When customizing the Jetpack search, the modal doesn't stay open, making the experience feel very broken and overall hard.

1. Enable Jetpack search and click "customize" from settings:

    image

2. Land in the customizer, modal is not open:

    image

    https://user-images.githubusercontent.com/87168/110758220-effb0000-8254-11eb-986c-03341bc2e11d.mov

3. Enabling light/dark mode will show the modal:

    Screenshot 2021-03-11 at 10 32 01

4. Changing other options will hide it, and I can get it to show again by switching light/dark mode:

    https://user-images.githubusercontent.com/87168/110758379-233d8f00-8255-11eb-8a46-7571907ddf10.mov

#### Test setup

- Tested in Firefox, a simple site.

- Tested using Blank Canvas theme, with header and footer disabled (as they are by default in this theme).
    image

- Tested also using Twenty Twenty-One theme, same results.

cc @gibrown @cathymcbride seems like a high prio bug?

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes https://github.com/Automattic/wp-calypso/issues/50979.

#### Changes proposed in this Pull Request:
The Jetpack Search interface will automatically be summoned when the Jetpack Search section of the Customizer is open.

* Adds a message event emitter within the Customizer to indicate when the Jetpack Search section is opened/closed.
* Adds a message event handler within the search application to automatically opens/closes the interface when the Jetpack Search section is open in the Customizer.
* Fixes incorrectly named script handles and dependencies for custom Customizer controls for Jetpack Search.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your site with a Jetpack Search subscription.
* Navigate to the Jetpack Search section of the WordPress Customizer.
* Ensure that the Jetpack Search interface opens automatically in the Customizer preview.
* Try changing various Jetpack Search settings; some will live-update the interface, others will refresh the Customizer preview.
* Ensure that the Jetpack Search interface opens automatically following a Customizer preview refresh.

### CODE REVIEW

**Review by bluefuton — COMMENTED** [review]
Wow! This feels so much better.

As we're now auto-spawing the modal when you enter the 'Jetpack Search' section, can we also automatically close it when you leave that section?

It doesn't feel intuitive to have to manually close the modal to use other sections of the Customizer:

Screen Shot 2021-03-18 at 15 02 25

**Comment by jsnmoon** [comment]
> As we're now auto-spawning the modal when you enter the 'Jetpack Search' section, can we also automatically close it when you leave that section? (@bluefuton)

Done!

**Review by bluefuton — APPROVED** [review]
Feels a much smoother experience! Nice one. Tested out well in FF and Edge.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by jsnmoon** [comment]
Deployed in r223065-wpcom.

**Pull request merged**
