### PR TITLE
Widgets: refactor Internet Defense League widget to work locally

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

The Internet Defense League widget is pretty old at this point, and the service behind it (Internet Defense League) doesn't exist anymore. The campaigns do not exist anymore, and the website now redirects to the company who first came up with the Internet Defense League.

The widget isn't offered to new Jetpack users today, since #22676. You can only add the widget if you use the Classic Widgets plugin.
Still, site owners who had added the widget some time in the past can still view and modify it. Since the campaign website doesn't exist anymore, we must refactor the widget so it still works:

- We remove the campaign script entirely, as well as the logic to select a campaign.
- We load the images locally instead of loading them from the remote site.
- We redirect to https://www.fightforthefuture.org/ instead of the old domain.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

See p1690903216438169-slack-CBG1CP4EN

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Go to Plugins > Add New, install and activate the Classic Widgets plugin.
* Go to Appearance > Themes and switch to a non-block theme, like Twenty Twenty.
* Go to Appearance > Widgets, and add an Internet Defense Widget.
* Ensure it is displayed properly on the frontend.

### CODE REVIEW

**Review by zinigor — COMMENTED** [review]
I can see that this is mostly removing code that will not get used anymore, and it looks fine. However, what do you think about leaving methods behind with a deprecation notice instead of removing them completely? I mean, it will probably be redundant, but just to be super extra cautious+ :)

**Comment by jeherve** [comment]
> I can see that this is mostly removing code that will not get used anymore, and it looks fine. However, what do you think about leaving methods behind with a deprecation notice instead of removing them completely? I mean, it will probably be redundant, but just to be super extra cautious+ :)

I don't think many folks out there are using those methods, but it doesn't hurt to leave them around for a few releases. Better be safe than sorry! Done in 70a1177bd96d72bcffa141345c2e36c48e84e53d

**Review by zinigor — APPROVED** [review]
Thank you for making the changes!

**Comment by zinigor** [comment]
Ouch, you will need to rebase this now.

**Pull request merged**
