### PR TITLE
Use the whole locale slug instead of just a prefix.

### PR DESCRIPTION
**Pull request by zinigor**
Fixes the problem with languages where the locale is specified as a combination of two, like `fr_BE` or `de_CH`.

#### Changes proposed in this Pull Request:
* Using the whole locale slug instead of just a prefix.
* Properly recognizing locale slugs like `formal` or `informal` for various languages that support them.

#### Testing instructions:
* To see the difference in the client side you need to run `yarn build-languages`, and to successfully do it you first need to have #6800 merged. Just run the script and see that your client side translations work for languages like `Deutsch (Schweiz, Du)` or `Français de Belgique`. To make sure they do you can check the state tree, the variable `jetpack.initialState.locale` should have locale data in it, even if it's mostly `null` values.

#### Proposed changelog entry for your changes:
* Fixed administrator area translations for several languages.
* Added proper support for Formal/Informal translation versions for languages that support them.

### CODE REVIEW

**Comment by eliorivero** [comment]
It's working! Changed to Deutsch and got

captura de pantalla 2017-03-29 a las 16 49 22

and the translations

captura de pantalla 2017-03-29 a las 16 49 57

**Comment by akirk** [comment]
This doesn't work for me because of two errors during the build process:
```
/* translators: %(username) is the WordPress user login name. */
__( "Connected as {{span}}%(username)s{{/span}}", "jetpack" ), // _inc/client/at-a-glance/connections.jsx:124
```
The `%(username)` in the comment is transformed to `[username]` in the array which makes the json decode fail (`SyntaxError: Unexpected token u in JSON at position 5880`).

```
__( "Add, organize, and display {{testimonialLink}}testimonials{{/testimonialLink}}. If your theme doesn’t support testimonials yet, you can display them using the shortcode	( [testimonials] ).", "jetpack" ), // _inc/client/writing/custom-content-types.jsx:72
```
This contains a tab character (just ahead of `(`) which also leads to an error (`parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 22643`).

**Comment by akirk** [comment]
Other than that, it seems to work. I tested with `Deutsch (Schweiz, Du)` (which has almost no translations) and `Deutsch (Sie)` (de_de_formal) which worked:
screen shot 2017-03-29 at 16 50 02


screen shot 2017-03-29 at 16 50 26

**Comment by akirk** [comment]
Just to be clear, normal German (`"localeSlug":"de_DE"`) still works:
screen shot 2017-03-29 at 16 52 05
screen shot 2017-03-29 at 16 52 38

**Comment by zinigor** [comment]
Thanks for the thorough testing Alex and Elio!
Alex: the problem with invalid translations getting picked up was solved in #6800.

**Comment by zinigor** [comment]
Ported to `branch-4.8` in 075ff34.

**Pull request merged**
