### PR TITLE
Instant Search: updates behavior and styling of filtering options

### PR DESCRIPTION
**Pull request by keoshi**
Fixes https://github.com/Automattic/jetpack/issues/14607

#### Changes proposed in this Pull Request:
* Adds filtering area on mobile.
* Adds relevance selector on both mobile and desktop.
* Adds necessary styles for both the light and dark overlay themes.

image

image

@jsnmoon As discussed, can you pick this up and drive it home by hooking all the necessary things, please? Thanks in advance! Here's what I can think of:

- [ ] Hook up ordering options.
- [ ] Remove ordering options from inside the popover.
- [ ] Possibly moving ordering options to the sidebar on desktop? FWIW, I kinda like how it works right now and the transition between mobile/desktop (see below), so pinging @gibrown as well for your thoughts.

jps-filtering-options

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
1. Follow [these setup instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) to set up Jetpack Instant Search on your site. Ensure that you've added a Jetpack Search widget with search filters into the Jetpack Sidebar.
2. Perform a search on your site and resize your viewport to be narrower than 768 pixels.
3. Click on the filter toggle button adjacent to the overlay search input. Ensure that the mobile filter popover appears.
4. Click on any search filter toggle. Ensure that the filter is applied and the popover is automatically closed.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by folletto** [comment]
Design wise: 👍

**Comment by gibrown** [comment]
On 2016 theme I am seeing some weirdness:

Screen Shot 2020-02-18 at 8 57 41 AM

**Comment by keoshi** [comment]
@gibrown I believe those are due to the unmerged changes on https://github.com/Automattic/jetpack/pull/14664 and unrelated to this PR in particular.

Would be good to get that in to get a clean slate for testing, since all of them are connected in one way or another.

**Review by jeffgolenski — APPROVED** [review]
Visual design has my approval. I think it looks outstanding.

**Comment by jsnmoon** [comment]
@keoshi The new sort buttons now work as expected. 

I also merged the latest `instant-search-master` code into this branch; can you confirm that the latest input updates have been merged properly?

**Comment by keoshi** [comment]
@jsnmoon This is looking really good, and I like how immediate the ordering options now are. Thank you!

**Review by gibrown — APPROVED** [review]
Wow. I really love how this direction has turned out. Played with it on my phone too. Slick.

**Pull request merged**
