### PR TITLE
Restructure feedback responses table in WP Admin

### LINKED ISSUE #27367: Restructure WP Admin Feedback responses table
In order to provide a better experience we need to re-organize the feedback responses page in WP Admin.  
As a first step, we're just going to update the columns to display data in a better format  and eventually build on that.

Image

### PR DESCRIPTION
**Pull request by ice9js**
Fixes #27367

#### Changes proposed in this Pull Request:
This PR updates the structure of the feedback responses table in WP admin to match the new designs.

Screenshot 2022-11-10 at 22 04 16

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

pcsBup-f2-p2

#### Does this pull request change what data or activity we track or use?

N/A

#### Testing instructions:

- Go to WP Admin -> Feedback on your test site
- The feedback table should now consist of four columns: From, Source, Date and Response.
- The 'Response' column should contain data from all the fields arranged in a grid format.

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Awesome Kuba!
As mentioned in our call today, the restructuring of the table looks good, and the data parts work!

The missing parts described here (pcsBup-oK-p2) are: 

-> Filtering
(... allowing users to filter for the new column “Source”)

-> Export feature
(We bring the export button to the top right of the table.
The exported CSV file would be based on the data currently shown (filtered) on the table.)

-> Hiding "edit/quick edit"

**Comment by ice9js** [comment]
>-> Filtering
>(... allowing users to filter for the new column “Source”)
>
>-> Export feature
>(We bring the export button to the top right of the table.
>The exported CSV file would be based on the data currently shown (filtered) on the table.)
>
>-> Hiding "edit/quick edit"

Just to be clear, all of these are meant to go in separate PRs. This one just lays down the groundwork by updating the table structure and content.

**Comment by CGastrell** [comment]
Looking good on .com:
image

Looking good on AT sites:
image

**Review by CGastrell — DISMISSED** [review]
LGTM!

I'd remove the "Quick Edit" action, I think it's only gonna bring problems, but not a blocker at all.

Something like:

```
add_filter( 'post_row_actions', 'grunion_feedback_remove_quick_edit_action', 10, 2 );

function grunion_feedback_remove_quick_edit_action( $actions, $post ) {
	if ( $post->post_type === 'feedback' ) {
		unset( $actions['inline hide-if-no-js'] );
	}
	return $actions;
}
```

**Comment by ice9js** [comment]
Since you keep asking for it and I already had it on a different branch, I added the commit that removes all actions from the "name" column (as per the design) and cleans up the implementation for the ones in the "responses" column.

**Comment by digitalwaveride** [comment]
Two little glitches:

- Responsive views are creating issues in the first three columns:

image

- The "expand/collapse chevron" feature is broken as well:

image

**Comment by ice9js** [comment]
I fixed the RWD issues, it seems all of them stem from changing the primary column to 'Response' instead of 'From' which is the first column.

I moved the actions back to the 'From' column and made it primary which fixed the issue and I guess it should work for now anyway.

**Review by digitalwaveride — DISMISSED** [review]
Thank you Kuba!!! Works for me! 🚀

**Review by CGastrell — DISMISSED** [review]
Looking good on AT sites 

Did you test on .com? If so... :shipit:

**Review by samiff — APPROVED** [review]
Tested well on local dev and simple wpcom for me 🚢

**Comment by lgrzegorski** [comment]
Hi [CGastrell](https://github.com/CGastrell) ,
Is there any possibility to restore "Quick Edit" menu in  post_row_actions filter? 
It is commonly used to moderate user responses.

**Pull request merged**
