### PR TITLE
Admin Page: Add module overrides to react UI

### LINKED ISSUE #8800: Admin Page: Disable/hide setting when module is forced on/off
It is currently possible to force a module to be enabled, or disabled, via the [jetpack_active_modules](https://developer.jetpack.com/hooks/jetpack_active_modules/) filter. Here's an example of using that filter to force the Photon module on:

```php
add_filter( 'option_jetpack_active_modules', 'jetpack_docs_filter_active_modules' );
function jetpack_docs_filter_active_modules( $modules ) {
	return array_values( array_merge( $modules, array( 'photon' ) ) );
}
```

However, while that filter does force the module on, the UI is not aware that the Photon module is forced on. Because of this, I am able to deactivate Photon in the admin UI. But, when I refresh the page, the module is still active.

We should find some way to manage the UI when modules are forced on. It seems like we should either 1) disable the setting in the UI with a message that it is forced to active or 2) just hide the setting like we do when the module is filtered with the [jetpack_get_available_modules filter](https://developer.jetpack.com/hooks/jetpack_get_available_modules/).

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #8800

__In Progress__

### CODE REVIEW

**Comment by ebinnion** [comment]
I just pushed a commit that takes a first pass at adding module override support to the writing tab. It doesn't yet handle infinite scroll or custom content types as those modules have some unique logic. Here are some screenshots for early review:

Lazy Images and Photon forced on:

screen shot 2018-02-20 at 2 08 49 pm

Masterbar, minileven, and post by email forced off:

screen shot 2018-02-20 at 2 08 53 pm
screen shot 2018-02-20 at 2 09 03 pm

Currently, the toggles are disabled, but there is no explanation of why. I'm currently debating adding an explanation at the end of the module description or adding a popover to the disabled toggle. What do you think?

**Comment by oskosk** [comment]
Last time I had to diable a piece of ui for settings I was recommended to hide it instead of disabling (It was the case of the masterbar for AT sites where we force the activation of the module via a filter). https://github.com/Automattic/jetpack/pull/8290#issuecomment-349449499

**Comment by ebinnion** [comment]
I had considered that approach. I went with this approach so far for two reasons:

1) Devs can completely removed the module using the `jetpack_get_available_modules` filter.
2) What happens if a user reads about a setting and expects to see it in their Jetpack admin, but we've completely removed it? I think this would make me feel that Jetpack is broken as opposed to my host configuring the module on/off.

**Comment by rickybanister** [comment]
@oskosk I'd asked @ebinnion and crew to provide two different pathways for module activation—one where we fully hide a piece of UI from the interface (so that that code can't run at all OR to ensure a feature is always on behind the scenes without any user interaction) as well as a visible 'always on' or 'always off' mode. This would be desirable in certain situations where a site builder or agency would like to require their clients use or do not use a certain feature.

@ebinnion in this case (the feature being forced into an on or off position) I think the work you did here is perfect. I was going to suggest we add an inline 'info' style notice to each settings card if they are in the 'always on' or 'off' position explaining what's going on, but that may be a bit overbearing. Another solution would be to swap the (i) icon for a warning icon (!) (make the icon red perhaps instead of gray), and use the popover component to display the reason the controls are disabled. Does that make sense?

Something like this:

image

It may be useful to switch the info icon to something like the warning icon to make it more apparent that something has changed. 

My copy works well I think (outside of `thingy thing`), but obviously we'll need to properly explain why the feature is on or off.

**Comment by oskosk** [comment]
@rickybanister that's fine. I just wanted to drop a designer opinion about the first time this was done in the admin page. 

This was done after having received feedback from a user of an atomic site that just thought the option was there for him to take the masterbar out of his site because we showed him the toggle. Although after seeing the toggle wasn't doing it and was remaining enabled after page refresh, he just thought it was a bug.

**Comment by ebinnion** [comment]
At this point, toggles and radios should be disabled when overridden for the writing, sharing, and discussion tabs.

**Comment by ebinnion** [comment]
Closing in favor of #8934

**Pull request closed without merging**
