### PR TITLE
Plans: Remove premium theme info

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

* Removes premium theme mentions/info.

#### Jetpack product discussion

* Internal: p1HpG7-cbM-p2

#### Does this pull request change what data or activity we track or use?

* No.

#### Testing instructions:

* After pulling down changes, visit `/wp-admin/admin.php?page=jetpack#/my-plan` and make sure no JS errors are present and cards display as normal there.
* Review other proposed changes.

### CODE REVIEW

**Comment by samiff** [comment]
Regarding https://github.com/Automattic/jetpack/pull/20052/commits/76f57994eba51c8f41d8d1271511a70e2480ccc2

We were checking:

```
const premiumThemesActive = includes(
    this.props.activeFeatures,
    FEATURE_UNLIMITED_PREMIUM_THEMES
),
```

But that logic appears outdated perhaps and was not working to show a card from what I could tell:

Markup on 2021-06-09 at 15:00:06

Just noting for in the future if we want to start showing a premium theme card again.

**Comment by samiff** [comment]
@jeherve Any reason we'd want to keep around the following?

https://github.com/Automattic/jetpack/blob/829ee26a16e5ec36dc7a5310caabb7492d2a6230/projects/plugins/jetpack/_inc/client/lib/plans/constants.js#L103-L106

I don't see them being utilized in our repo, and Calypso defines their own to use.

**Review by jeherve — DISMISSED** [review]
> Any reason we'd want to keep around the following?

I think they're safe to nuke at this point. 👍

I would also update:
https://github.com/Automattic/jetpack/blob/8c47c21a296f3e93d8526edd05bbd74d97a9aa4c/projects/plugins/jetpack/_inc/client/my-plan/my-plan-header/index.js#L110

**Comment by samiff** [comment]
@jeherve Do you think this card needs adjusting?

Screen Shot 2021-06-10 at 11 41 02 AM

Maybe something more like:

Screen Shot 2021-06-10 at 11 45 15 AM

https://github.com/Automattic/jetpack/blob/4235562d3e63ac31541ea749a917006744d7ed39/projects/plugins/jetpack/_inc/client/my-plan/my-plan-body.jsx#L608-L633

**Comment by jeherve** [comment]
> Maybe something more like:

I personally like it! 👍

**Review by jeherve — APPROVED** [review]

**Pull request merged**
