### PR TITLE
Story block: remove wp-components frontend dependency

### PR DESCRIPTION
**Pull request by sgomes**
The story block frontend currently enqueues `wp-components`, which is an absolutely massive 200KB (compressed) dependency, and which comes with other large dependencies of its own.

It does this for two different reasons:
- To reuse some SVG-related components. While this is ripe for a deeper refactor, an immediate improvement we can apply is to use `wp-primitives` instead; it has the exact same components (`wp-components` reexports them), and `wp-primitives` has a massively smaller footprint.
- To reuse the `<Button>` component. None of the usage seems to justify it, so I simply replaced it with `<button>`.

Note: I can't find a particular team that is currently responsible for this block, so I'm assigning to @Automattic/jetpack-crew. Please feel free to reassign!

This PR should save ~250KB compressed (!!) on pages with story blocks.

## Proposed changes:
* Story block: remove dependency on `wp-components` SVG-related components by replacing it with a dependency on the `wp-primitives` equivalents
* Story block: remove dependency on `wp-components` `<Button>` and replace with plain `<button>`

### Other information:

- N/A Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None, this is a simple performance improvement with no functionality changes.

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
- Create a page with a story block
- Load the page and ensure that `wp-components` is not loaded
- Smoke-test the story block and ensure it works correctly

### CODE REVIEW

**Comment by sgomes** [comment]
The Boost E2E test failure seems unrelated (it's unrelated code, and the failures are timeouts), but I'm not sure how to validate that.

**Comment by anomiex** [comment]
Yeah, it's unrelated. p1675373367797419-slack-CBG1CP4EN

**Comment by sgomes** [comment]
Rebased after the `@wordpress` package updates.

**Comment by sgomes** [comment]
~~Looks like the build keeps failing (5 attempts so far) because of "the weird bug" 🤷~~

Finally succeeded after a new rebase.

**Comment by jeherve** [comment]
@twstokes Is that something someone on your team may be able to test? The Story block is an integral part of the app experience, we'd want to make sure it still works as expected from your end as well.

Thank you!

**Comment by twstokes** [comment]
> @twstokes Is that something someone on your team may be able to test? The Story block is an integral part of the app experience, we'd want to make sure it still works as expected from your end as well.
> 
> Thank you!

Thank you @jeherve for putting this on our radar! 🙇 @dcalhoun will give it a look. 👀

**Comment by dcalhoun** [comment]
I tested the proposed changes by creating Story blocks in the WordPress app on both iOS and Android. I encountered several issues within the mobile editor, but the issues also occur in `trunk` and the published app release. So, I do not believe the issues to be directly related to these changes. I captured the issues in https://github.com/wordpress-mobile/gutenberg-mobile/issues/5472. I do not believe these issues should block this PR. 

Additionally, I noticed that videos within the Story block generally never load within the web editor. Instead, a loading indicator is displayed indefinitely. This occurs in `trunk` and the current WordPress.com version too. So, this also appears unrelated to these changes. Do others experience this in the web editor too?

* Safari 16.3
* macOS 13.2.1
* Gutenberg 15.0.1
* Jetpack 11.8.3

<details><summary>Web Editor: Storyblock Video Loading</summary>

story-block-web-front-end

</details>

**Review by jeherve — APPROVED** [review]
This tests well for me! 🚢

**Comment by sgomes** [comment]
Thank you for the reviews, @dcalhoun and @jeherve! 👍

**Pull request merged**
