### PR TITLE
Sharing: Deprecate Google+ Sharing Button

### PR DESCRIPTION
**Pull request by mdawaffe**
See #10950.

#### Changes proposed in this Pull Request:
* Removes from available buttons.
* Adds style and warning tooltip to enabled buttons, preview, and front-end display.
* Removes from front-end display unless `current_user_can( 'manage_options' )`.

#### Copy
The button says:
> Google+ has shut down

The tooltip says:
> The Google+ service has shut down. This sharing button is not displayed to your visitors and should be removed.

#### Screenshots
Settings -> Sharing -> Sharing Buttons:
screen shot 2019-01-24 at 5 47 44 pm

Blog Post:
screen shot 2019-01-24 at 5 48 07 pm

#### Testing instructions:
1. `git checkout master`
2. Go to Settings -> Sharing -> Sharing Buttons
3. Add a "Google" button
4. Make "Show buttons on" is checked for at least "Posts".
5. `git checkout deprecate/google-plus-sharing-button`
6. `yarn build`
7. Go to Settings -> Sharing -> Sharing Buttons
8. See that the "Google+" button is dimmed, crossed-out, and has a "has shut down" title/tooltip.
9. In the preview section, see that the "Google+" button says "has shut down", is dimmed, crossed out, and has a "has shut down" title/tooltip.
10. Go to a blog post as a site admin. See the dimmed, etc. Google+ button.
11. Go to a blog post as as a logged out visitor. See no Google+ button.
12. Play around with different "Button style" options both in the admin preview and on the front-end.

#### Proposed changelog entry for your changes:
Deprecate the Google+ Sharing Button.

### CODE REVIEW

**Comment by mdawaffe** [comment]
The "Icon only" button style is currently slightly broken. I'll get it working soon.

**Review by jeherve — CHANGES_REQUESTED** [review]
This tests well, the only thing left seems to be the icon-only styles.

I would also recommend that we remove the Google+ names and keywords from `Jumpstart Description:` and `Additional Search Queries` in the module header in `modules/sharedaddy.php`. I pushed that change in d4b1991f0ff3f8537605c4884caa25003f946e9b

**Comment by mdawaffe** [comment]
Icon Only styles fixed in 3bf82822e841681b86c646313f3f5ec15cd3fc44.

**Review by jeherve — APPROVED** [review]
This works well in my tests. Merging.

**Comment by mdawaffe** [comment]
Nice find in e36770c!

**Comment by rachelmcr** [comment]
Thank you for this excellent deprecation! I just spotted it on one of my sites using the Icon Only styles, and both the icon and tooltip were very clear. The attention to detail is much appreciated. :)

**Comment by kraftbj** [comment]
Removed the Google+ assets from the wpcom side in r189688-wpcom.

**Pull request merged**
