### PR TITLE
Social Menu & Social Media Icons: Add Mastodon Icon

### LINKED ISSUE #10338: Social Menu & Social Media Icons: Add Mastodon Support
Please add support for [Mastodon](https://joinmastodon.org/), a distributed, decentralized, federated micro-blogging platform popular among people abandoning Twitter and Free software/Free culture enthusiasts ([many nodes exist](https://the-federation.info/mastodon))

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #10338

#### Changes proposed in this Pull Request:

* Adds Mastodon to the Social Menu and Social Icons Widget

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Adds to an exciting feature

#### Testing instructions:

Go to the Customizer with a theme that supports social menus and add a social menu using the link `mastodon.social`, and do the same with the Social Icons widget, then verify the icon displays as expected.

Screenshot 2020-03-21 at 07 57 48

#### Proposed changelog entry for your changes:

*Social Menu & Social Icon Widget: Add Mastodon support

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Limiting Mastodon to `mastodon.social` seems like it could be problematic, since there are so many other instances:
https://joinmastodon.org/

Even `mastodon.social` is also available via `mstdn.social`.

If we add the icon, I would suggest supporting at least a small list of the most popular instances out there, as well as introducing a filter that can be used to add an additional domain just for Mastodon.

**Comment by jeherve** [comment]
I'll close this PR for now because of the lack of activity on this. We can always reopen in the future if needed, but it will need a rebase, so it may be easier to start a new PR at this point.

**Comment by sophiegyo** [comment]
Would it be possible to use their [API](https://docs.joinmastodon.org/api/oauth-scopes/) to ping an instance when a URL is added to a social menu, just for an "is this Mastodon?" check?

1. Edit social menu
2. Add custom link
3. Checkbox: is Mastodon?
4. If checked, then ping instance using API to get a yes/no on whether it's Mastodon
5. If yes, then icon

One of our fabulous forum volunteers brought it up again and pointed out it's even more relevant than before.

Edit: I have no idea how any of that works I'm just wondering if it's A Thing Which Is Possible! Also it sounds like 3 and 4 are redundant but I know there will be occasional typos to catch.

**Comment by kraftbj** [comment]
I don't know that it would be feasible to do that, but maybe.

With the move toward full-site editing themes and the Social Icons block that is available there, I am also unsure if this will reach priority to tackle though too.

**Pull request closed without merging**
