### PR TITLE
Add/ai chat block

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Proposed changes:

* Adds an experimental AI chat block to link with the AI blog search that is being worked on by AI team - as discussed with @artpi 

Some background discussion here peGwbA-2b-p2

Still very draft at the moment - more details coming soon.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
In order to avoid linting errors like the ones we're seeing there, it may be easier to use the CLI tool to generate the new block: `jetpack docker wp jetpack docker wp jetpack scaffold block ai-chat`. You could create a first PR that adds that scaffolding as a beta block, and then iterate on it (add the guts of it) in follow-up PRs.

**Comment by glendaviesnz** [comment]
Thanks @jeherve  - I took a look at the errors and at a basic scaffold setup, and the errors were pretty minor, so I have fixed them and shifted the block to beta status, but let me know if you still want me to go back through the process of an initial commit with just the basic scaffold code in place.

**Comment by glendaviesnz** [comment]
@jeherve when trying to do a fresh install of the jetpack docker setup i just end up with an endless loop of these logs 👍 

```
[Warning] Access denied for user 'root'@'172.23.0.2' (using password: YES)
jetpack_dev-db-1          | Auto-updater waiting for DB to be up...
```

despite not having changed the database usernames/passwords in the .env file - have tried removing all the docker containers and volumes and starting again, and setting the mysql root password in .env to the default '', but no joy - have you come across this problem before?

I just manually fixed all the lint/build issues in the mean time.

**Review by jeherve — APPROVED** [review]
> I took a look at the errors and at a basic scaffold setup, and the errors were pretty minor, so I have fixed them and shifted the block to beta status

That works for me. If you want to merge this one and iterate in follow-up PRs, 🚢

**Comment by glendaviesnz** [comment]
Great, thanks for the minor fixes @jeherve  - you are as helpful as ever, brings back fond memories of the Explorer/View team jetpack block days!

**Pull request merged**
