### PR TITLE
Try updating to React 15 and newer dops-components

### PR DESCRIPTION
**Pull request by gravityrail**
As part of a separate project, I wanted to upgrade dops-components and its dependencies and build system, including an update to React 15 (to match Calypso)

This patch tries to do the smallest amount of the work so that Jetpack's UI still builds and works.

To test:

- checkout dops-components master (this [PR](https://github.com/Automattic/dops-components/pull/109) was just merged)
- cd dops-components and run `npm install` and `npm link`
- cd jetpack and run `npm link @automattic/dops-components`
- `gulp react:build`

Click around the UI. This is a cross-cutting change that could affect every React component. Hopefully everything works just fine.

This PR also fixes a couple of warnings I was getting in the browser. Not sure if they're new or not. e.g. enable-background prop in React SVG elements should be enableBackground.

### CODE REVIEW

**Comment by georgestephanis** [comment]
We're currently in beta for shipping a release on August 1st.  Can this wait until the September release, or is this somehow super urgent to get in?

**Comment by zinigor** [comment]
@gravityrail are there any breaking changes in the merged dops-components PR? I'm pretty sure we're building Jetpack with `yarn` and it *should* preserve the version that is specified in `yarn.lock` but surprises happen. What if Jetpack gets built with the updated dops-components but with the old client code?

**Comment by zinigor** [comment]
screenshot from 2017-08-15 22-20-00

**Comment by gravityrail** [comment]
@zinigor I just pushed some uncommitted changes I had made to this branch (whoops! Sorry). Just got back from AFK. Let me know if these fix the problem for you.

**Comment by gravityrail** [comment]
@zinigor can you take another look? As a bonus I upgraded webpack too :)

**Comment by gravityrail** [comment]
btw I know there are some react warnings due to invalid props - could you take a look at those?

**Comment by zinigor** [comment]
Rebased again because `yarn.lock` got in conflict due to an earlier merged PR with dops-components update.

**Comment by zinigor** [comment]
Oh, about those `PropType` warnings - let's handle those in a separate PR.

**Comment by gravityrail** [comment]
Turns out you need Node 8.x to build on OS X, due to libsass breakage. Docs updated.

**Pull request merged**
