### PR TITLE
Settings UI: update support block

### PR DESCRIPTION
**Pull request by eliorivero**
captura de pantalla 2017-03-22 a las 13 30 42

captura de pantalla 2017-03-22 a las 14 15 08

#### Changes proposed in this Pull Request:

* in addition to the UI changes, the info for HEs gravatars now includes the names since they're used below the image.

### CODE REVIEW

**Comment by rickybanister** [comment]
Looking really good @eliorivero 

cc @ashleighaxios

**Comment by jeffgolenski** [comment]
This looks fantastic!

**Comment by dereksmart** [comment]
I see that there is a banner for getting priority support when in `free` mode, but I don't see any difference in the links between free and priority.  How do I access the priority support when on pro versions?

**Comment by dereksmart** [comment]
If my above comment is a non-issue, then this is good to merge! 🐑

**Comment by eliorivero** [comment]
@dereksmart it's the same link. See Slack p1490202455104220-jpop-support

**Comment by dereksmart** [comment]
Ok, putting my user hat on: 

If I purchase a plan with the intent to use the priority support immediately, I may be lost in how to access that priority support.  Probably been discussed and solved elsewhere.  This PR LGTM

**Comment by jeherve** [comment]
> If I purchase a plan with the intent to use the priority support immediately, I may be lost in how to access that priority support.

Should the wording on the "Ask a question" button be different when you have an active upgrade, to indicate that you're asking a question that will be answered quickly?

**Comment by ashleighaxios** [comment]
Yay - looks great. Look at those HEs!

@dereksmart @jeherve 
The language above the button changes to include "priority-speed Jetpack support" once the plan has been upgraded to address the same thing a button change would address. It is subtle, so we can try changing the button in a future iteration as well to see if it gets more click throughs. Step one might be seeing if we compel folks to purchase plans to get faster support if that's what they need. Step two can be adjusting the experience once they do upgrade, ensuring we're supporting their next steps. I think we're not quite at the point where we know they will upgrade.

Question: Are Tracks enabled on this so that we can compare pre and post-fix engagement? I don't know much about Tracks so fill me in if that is actually an automatic thing.

**Comment by dereksmart** [comment]
Tracks aren't yet integrated, but it's something we'll be doing for this release for sure.  We'll be tracking from which upgrade banners they are coming from, so we'll be able to answer these types of questions after a while :)

**Pull request merged**
