### PR TITLE
readme.txt - update screenshot captions

### PR DESCRIPTION
**Pull request by MichaelArestad**
Updates the captions. We are reducing the number of screenshots to four that align with our Jetpack.com home page content.

#### Changes proposed in this Pull Request:

* Just updates readme.txt captions for the screenshots

#### Testing instructions:

* Read the diff

#### Images to accompany the captions

[Images](https://cloudup.com/cqDSBeqPck1)

#### Proposed changelog entry for your changes:

* No changelog needed

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@michelleweber Could you please do us another big favor and review the captions in this PR? I think they're probably good to go, but you have a great eye for this stuff and I would love a second opinion.

**Comment by crunnells** [comment]
LGTM!

**Review by jeherve — DISMISSED** [review]
It looks good. I wonder if it's a problem that we are deleting keywords like "content delivery network" or "social networks", that may help with our rankings?

**Comment by michelleweber** [comment]
These look good! I have a couple of small notes, but they're more take-or-leave things:

"Prevent unwanted intrusions" Feels a little formal. I might just say something like "Keep hackers out" -- it communicates "this is about safety" in a more direct/quickly understandable way.

"our global network of servers" > I might add a qualifier, like powerful or massive.

"WordPress themes, useful blocks, and custom widgets." > I might take out "useful" and "custom" for a snappier sentence.

**Comment by MichaelArestad** [comment]
@michelleweber Thanks!
@jeherve good point! Fixed!

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Merged to SVN via r2079476-plugins

**Pull request merged**
