### PR TITLE
Add mocker runner for WAF blocked requests

### PR DESCRIPTION
**Pull request by bhoop**
#### Changes proposed in this Pull Request:

* Adds a new runner to the Mocker module in the Debug Helper that inserts mocked blocked requests into the WAF's database log.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1660581402530939-slack-C03LQF5FALB

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Ensure the Firewall is turned on in Jetpack Settings
* Ensure the **Jetpack Debug Tools** plugin is activated.
* In the Jetpack Debug menu, ensure the **Mocker** tool is activated.
* In the Jetpack Debug Mocker tool, select "Firewall blocked requests" from the `Data` dropdown, specify a number of entires to generate, and click "Run!"
* After completing, ensure that the `wp_jetpack_waf_blocklog` table now has new rows in it.

### CODE REVIEW

**Review by miguelxpn — DISMISSED** [review]

**Comment by singerb** [comment]
Do we need a way here to clear out the requests (while being very clear that that's what we're doing)?

**Comment by bhoop** [comment]
We could, but there's no "clear mocked data" for any of the other types.

Clearing the data could also be done with a single `TRUNCATE` SQL query (or a more targeted (`DELETE ... WHERE`).

**Review by kraftbj — DISMISSED** [review]

**Comment by samiff** [comment]
@bhoop Looks like there are a couple PHP lint [warnings](https://github.com/Automattic/jetpack/actions/runs/3047649762/jobs/4911873117) that need to be addressed or ignored.

```
Warning: /home/runner/work/jetpack/jetpack/projects/plugins/debug-helper/modules/inc/mockers/class-waf-runner.php:53:9: warning - Usage of a direct database call is discouraged. (WordPress.DB.DirectDatabaseQuery.DirectQuery)
Warning: /home/runner/work/jetpack/jetpack/projects/plugins/debug-helper/modules/inc/mockers/class-waf-runner.php:53:9: warning - Direct database call without caching detected. Consider using wp_cache_get() / wp_cache_set() or wp_cache_delete(). (WordPress.DB.DirectDatabaseQuery.NoCaching)
```

**Comment by bhoop** [comment]
Thanks! After searching around I couldn't find a "safer" way to write those queries, so I went ahead and ignored them.

**Review by samiff — APPROVED** [review]

**Pull request merged**
