### PR TITLE
Subscribe block: add "show login" toggle

### PR DESCRIPTION
**Pull request by simison**
Adds a toggle to "show login" (better copy needed) under subscribe block.

Then in the rest of the features using subscribe block we can simply add attribute to show login e.g. at paywall and subscribe modal.

Screenshot 2023-10-25 at 18 27 21

## Proposed changes:

* Add "show login" toggle to subscribe block settings

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Add subscribe block without this branch; then switch to branch and ensure the block works and doesn't invalidate.
* Enable "show login" and ensure editor and frontend look good.
* Make sure the link still works.

### CODE REVIEW

**Comment by lezama** [comment]
We should change this method name: https://github.com/Automattic/jetpack/pull/33781/files#diff-9164d71f603706b3c6cc58c71ba3f2fbb12b1dba772adca76793f60c24ddbca7L969

UPDATE [[done](https://github.com/Automattic/jetpack/pull/33781/commits/e0b59998eba990316a26288f8c74f197c06d7968)]

**Review by lezama — APPROVED** [review]

**Review by lezama — CHANGES_REQUESTED** [review]
some tests failing 🤔

**Comment by lezama** [comment]
Rebased here: https://github.com/Automattic/jetpack/pull/34191

**Comment by lezama** [comment]
seems to work, force pushed here 😅

**Review by lezama — DISMISSED** [review]

**Comment by lezama** [comment]
@TimBroddin do we need here a `deprecated/v*` like you did here: https://github.com/Automattic/jetpack/pull/27443 ?

**Comment by lezama** [comment]
looks like yes 😄

**Comment by TimBroddin** [comment]
I always add a deprecation when things fail 😄

**Comment by pkuliga** [comment]
Related issue: https://github.com/Automattic/jetpack/issues/32062

**Comment by pkuliga** [comment]
Closing it since it's not our priority right now. Will reopen if needed.

p1709908298333419-slack-C052XEUUBL4

**Pull request closed without merging**
