### PR TITLE
Search Package: Add watch command

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
* Adds a watch command to package.json.
* Adds a watch command to composer.json

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Run `pnpm install && pnpm run watch`. Ensure it builds the requisite assets as expected.
* Run `pnpx jetpack watch packages/search`. Ensure it executes the same command as above.

### CODE REVIEW

**Comment by oskosk** [comment]
@jsnmoon Check the commands you're prompted to run on the File changes view... You've mentiond this is a `minor` change in the changelog file and thus the system is asking you to bump versions. So :
```
$ tools/fixup-project-versions.sh
$ git comit.....
````

**Review by jeherve — CHANGES_REQUESTED** [review]
You'll need to update versions here before we can merge this.

**Comment by jsnmoon** [comment]
@oskosk @jeherve: I somehow missed the outdated version notice; thank you for the heads up! This has now been fixed.

**Review by jeherve — APPROVED** [review]

**Comment by bluefuton** [comment]
Thanks for adding this @jsnmoon! I'll update the internal docs.

**Pull request merged**
