### PR TITLE
Search: Porting back 1.1.0 changelog and readme updates to trunk

### PR DESCRIPTION
**Pull request by coder-karen**
#### Changes proposed in this Pull Request:

* This PR includes the changelog and readme updates that were added to the Search release, so that they can be ported back to trunk (plus the readme.txt version update).

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Shouldn't need anything changed as it would differ from the production version, however if there is anything glaring it's likely worth fixing that up. Plus confirm the readme.txt stable tag is 1.1.0.

### CODE REVIEW

**Comment by sdixon194** [comment]
>  Failed to parse changelog: Heading seems to have a linked version, but link was not found: ## [1.1.0] - 2022-08-02. Please ensure this version has a URL defined at the end of the changelog.

Looks like we need to make sure to add a linked version at the bottom of the changelog.

**Comment by coder-karen** [comment]
Oh yes! Probably better if I remove the brackets since there is nothing to link to? Tests are passing now as a result of doing that, anyway.

**Comment by sdixon194** [comment]
We could compare it to 1.0.0: `https://github.com/Automattic/jetpack-search-plugin/compare/1.0.0...1.1.0`

**Comment by coder-karen** [comment]
> We could compare it to 1.0.0:

Ah! I tried comparing to the beta version - the link seems to work - will this work?

**Review by sdixon194 — APPROVED** [review]
Perfect!

**Pull request merged**
