### PR TITLE
Conflicting plugins: remove duplicate keys

### LINKED ISSUE #3198: $plugins_to_deactivate has two duplicate keys
The public property `$plugins_to_deactivate` of Jetpack object has two duplicate key "contact-form" and "widget-visibility"

``` php
public $plugins_to_deactivate = array(
    ...
    'contact-form'        => array( 'grunion-contact-form/grunion-contact-form.php', 'Grunion Contact Form' ),
    'contact-form'        => array( 'mullet/mullet-contact-form.php', 'Mullet Contact Form' ),
    ...
    'widget-visibility'   => array( 'jetpack-widget-visibility/widget-visibility.php', 'Jetpack Widget Visibility' ),
    'widget-visibility'   => array( 'widget-visibility-without-jetpack/widget-visibility-without-jetpack.php', 'Widget Visibility Without Jetpack' ),
    ...
);
```

### PR DESCRIPTION
**Pull request by jubstuff**
Fixes #3198 .

Duplicate keys have been merged.

---
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If [Grunt](http://gruntjs.com/) is installed on your testing environment, run `grunt jshint` before to commit your changes. It will allow you to [detect errors in Javascript files](http://jshint.com/about/).
- [ ] Did you create a **new action or filter**? [Add inline documentation](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters) to help others understand how to use the action or the filter.
- [ ] Create **[unit tests](https://github.com/Automattic/jetpack/tree/master/tests)** if you can. If you're not familiar with Unit Testing, you can check [this tutorial](https://pippinsplugins.com/series/unit-tests-wordpress-plugins/).

### CODE REVIEW

**Comment by samhotchkiss** [comment]
@jubstuff, thanks for this!

This fixes the duplicate key issue, but doesn't actually work, since the code that deactivates only looks at the first two arguments (https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2578)

I'd be open to using nested arrays like:
```php
'sharedaddy' => array( 
	array( 'sharedaddy/sharedaddy.php', 'Sharedaddy' ), 
	array( 'jetpack-sharing/sharedaddy.php', 'Jetpack Sharing' )
),
```

But that would also require that class.jetpack.php be updated to handle the new format

**Comment by jubstuff** [comment]
Hello @samhotchkiss ,

Sorry for this late reply!

I just pushed the code to handle the new format that you proposed :)
I'm still working on it, but I think it could be a good first step.

**Comment by rcoll** [comment]
This seems to work as expected, so I'm going to mark it review complete.

However, one interesting thing that I noticed while testing is that the [Random Redirect plugin](https://wordpress.org/plugins/random-redirect/) does not seem to get deactivated like it should. I tested master branch for this behavior and got the same results, so I don't think this is a symptom of this PR, but something that could be looked at anyways.

**Comment by eliorivero** [comment]
Hi @jubstuff! Great work with this!

I tested this installing and activating Shareddady plugin and found some issues that must be addressed before merging:

1. This is working for me only when I visit `admin.php?page=jetpack_modules`. After I activate Sharing, Sharedaddy is deactivated.

2. after activating Sharing the page reloads and there's a PHP notice issued:
    ```
    Notice: Array to string conversion in /wp-content/plugins/jetpack/class.jetpack.php on line 3594
    ```

3. when Sharing is active, and I activate Sharedaddy, I get 13 notices like
    ```
    Notice: Array to string conversion in /wp-content/plugins/jetpack/class.jetpack.php on line 3005
    ```

4. in `admin.php?page=jetpack`, the Jetpack React UI, I get a red notice when I activate Sharing. 
    ```
    Sharing failed to activate. Error: No route was found matching the URL and request method
    ```
This is not quite true because the module is activated. However, there's a 302 redirection (maybe caused by `Jetpack::state`?) that adds `?jetpack_restate=1` to the endpoint `wp-json/jetpack/v4/module/sharedaddy/active?jetpack_restate=1`
so the request server fails to serve the response thus returning `rest_no_route` and causing the red notice to show up with the message above.

Thanks for working on this!

**Comment by samhotchkiss** [comment]
Removed from the pipeline until we hear back from @jubstuff

**Comment by eliorivero** [comment]
@jubstuff I'm tagging this as Abandoned and will be closed if it doesn't have any update by the end of the week it will be closed.

**Comment by samhotchkiss** [comment]
Closing as abandoned.  Feel free to reopen in the future if active development is resumed.

**Pull request closed without merging**
