### PR TITLE
My Jetpack: Update/my jetpack cant install plugin

### LINKED ISSUE #22982: My Jetpack: Handle manually install for plugins
When site does not have write access to the filesystem, we should prompt the user to download the plugin and install it by themselves.

_Free Plugins_

image

_Paid Plugins_

image

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #22982

This PR explores how to handle the situations in which we are not able to automatically install a plugin for the user.

The proposal is to:
* Disable the button
* Add a notice above the button with a link to the plugin on the .org repository

Captura de tela de 2022-06-24 10-27-32

Another option I considered was to use the `Notice` core component, but it didn't fit in very well on a first try:

Captura de tela de 2022-06-17 18-35-15

What do you think?

#### Changes proposed in this Pull Request:

* Display an alert when we can't install the plugin for the user

#### Jetpack product discussion

1202184803119163-as-1202324040023250

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Easiest way to test this PR is by modifying the `class-initializer.php` file inside the my-jetpack package folder, on line 151 and make it read like:

```PHP
'fileSystemWriteAccess' => 'no',
```

* Go to My Jetpack
* Click on "Add CRM" (or any other card for which you don't have the plugin installed

### CODE REVIEW

**Comment by retrofox** [comment]
> Note: The Alert component has a bug and is not handling multi-line content properly. This needs to be fixed.

Asana card created

**Review by retrofox — COMMENTED** [review]
I think the implementation of this should be done at `js-packages/components`, straight in the ProductOffer component. In fact, the error property is already done. We could even add a new warning property or replace it with a new message, or `alert` property.

image

Take a look via the [story](https://automattic.github.io/jetpack-storybook/?path=/story/plugins-protect-product-offer--default&args=isCard:true). Show the error message by clicking on the `Get started with Jetpack Protect`

The challenge here is not to break the layout when the components show an error, alter, etc. That's why the space reserved is only for one line. Quite fragile tbh.

I'm afraid we'll need designer feedback here. Something that we could do is show the message in a tooltip with absolute position, thus it won't break the layout or reproduce a jump.

**Comment by retrofox** [comment]
> > Note: The Alert component has a bug and is not handling multi-line content properly. This needs to be fixed.
> 
> Asana card created

https://github.com/Automattic/jetpack/pull/24788

**Comment by leogermani** [comment]
>  Something that we could do is show the message in a tooltip with absolute position, thus it won't break the layout or reproduce a jump.

In this case there's no jump because the warning is there from the moment the component is loaded. And the button is disabled. But I'll check how to use the error in the button component instead

**Comment by leogermani** [comment]
Closed in favor of https://github.com/Automattic/jetpack/pull/24884 

Reconstructed due to merge problems here

**Pull request closed without merging**
