### PR TITLE
WordAds: Updated snippet for DDG expansion

### PR DESCRIPTION
**Pull request by dbspringer**
A slightly updated loader to for our project with Duck Duck Go.

#### Changes proposed in this Pull Request:

* A small update to help us differentiate sites for our partnership with Duck Duck Go ads.

#### Jetpack product discussion
pMyNb-4V9-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* Enable the Ads module in Jetpack Settings -> Traffic on a Jetpack test site with Premium+ plan.
* Enable some ad units/widgets/etc.
* Ads should load as you'd expect.

#### Proposed changelog entry for your changes:

* No changelog needed.

### CODE REVIEW

**Comment by dbspringer** [comment]
This diff does a better job of showing exactly what changed.

Screen Shot 2020-09-16 at 4 18 11 PM

**Review by cphilleo — APPROVED** [review]
Ads show correctly. No JS console errors. 👍

**Comment by jeherve** [comment]
Is this ready for review? Would you want to have this in before the code freeze tonight?

**Comment by dbspringer** [comment]
@jeherve Thanks for keeping an eye out -- I was literally just coming here to turn the status to `needs review`. Should be all set 👍

**Review by jeherve — APPROVED** [review]
This seems to work well for me. 🚢

**Pull request merged**
