### PR TITLE
Simple payments: update block description

### PR DESCRIPTION
**Pull request by simison**
Update Simple payment block's description.

The description could elaborate a bit more about the potential use cases for the block so that customers would be more encouraged to try it.

Also modified old sentence little bit "create and embed" sounded complicated and technical, changed to "add".

#### Before:

> Lets you create and embed credit and debit card payment buttons with minimal setup.

#### After:

> Lets you add credit and debit card payment buttons with minimal setup.
>
> Good for collecting donations or payments for products and services.

Thoughts?

#### Changes proposed in this Pull Request:
* Update block description.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
- Modifying an old feature.

#### Testing instructions:
- In block editor, insert simple payments button
- Choose the block and check the sidebar's description

#### Proposed changelog entry for your changes:
*

### CODE REVIEW

**Comment by scruffian** [comment]
Could we add it to the `keywords` too?

**Comment by simison** [comment]
>Could we add it to the keywords too?

Great idea! Currently we have _Ship, Sell_ and _PayPal_ — since we can have max 3, I'll drop "Ship".

**Comment by simison** [comment]
Actually lemme pull out some stats about keywords and I'll get back to this.

**Review by jeherve — APPROVED** [review]
This looks good to me.

**Comment by kraftbj** [comment]
@simison Are you good with this or still looking into the keywords?

**Comment by simison** [comment]
This is good to go — sorry I was on long AFK. :-)

**Pull request merged**
