### PR TITLE
PHP 8 compatibility updates

### PR DESCRIPTION
**Pull request by nelsonec87**
## Proposed changes:

These are minor changes as part of our PHP 8.1 compatibility update initiative pdqkMK-UN-p2

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* pdqkMK-UN-p2
* #23695 
## Testing instructions:

These are minor enough that I think visual inspection should be sufficient but please let me know if you need more information.

### CODE REVIEW

**Comment by markbiek** [comment]
@nelsonec87 I notice this is getting a linting error on `array_key_first`. Does this PR need rebasing?

**Comment by nelsonec87** [comment]
> @nelsonec87 I notice this is getting a linting error on `array_key_first`. Does this PR need rebasing?

Let's try!

**Comment by nelsonec87** [comment]
@markbiek It's still throwing `The function array_key_first() is not present in PHP version 7.2 or earlier (PHPCompatibility.FunctionUse.NewFunctions.array_key_firstFound)` even after rebase :(

**Comment by markbiek** [comment]
> @markbiek It's still throwing `The function array_key_first() is not present in PHP version 7.2 or earlier (PHPCompatibility.FunctionUse.NewFunctions.array_key_firstFound)` even after rebase :(

OK, we'll have to see what information we can get from #30616 when we hear back there. It seems like we'll need to make another phpcs rule change. I'm just not sure what the change needs to be.

**Comment by nelsonec87** [comment]
Rebased as check was failing

**Review by markbiek — APPROVED** [review]
LGTM!

**Pull request merged**
