### PR TITLE
Jetpack Options Package: just class map existing options class

### PR DESCRIPTION
**Pull request by roccotripaldi**
Jetpack Options will be a dependency of many of the packages we plan to build.
It makes sense that we just class map it for now.

### CODE REVIEW

**Comment by tyxla** [comment]
I've requested to revert this because it broke the connection package tests (see https://travis-ci.org/Automattic/jetpack/jobs/541622250) and it also broke the dependency tree of a package requiring another package (see https://travis-ci.org/Automattic/jetpack/jobs/541593344).

**Comment by tyxla** [comment]
Merged #12571, maybe we can do another pass of this one, Rocco?

**Comment by roccotripaldi** [comment]
> Merged #12571, maybe we can do another pass of this one, Rocco?

Idk, maybe it's not even necessary?

**Comment by tyxla** [comment]
> Idk, maybe it's not even necessary?

I'm totally leaving this to your judgement 👍

**Pull request merged**
