### PR TITLE
Settings UI: align and space elements

### LINKED ISSUE #6554: Settings: toggles are not positioned correctly
Toggles are like this in At a Glance

captura de pantalla 2017-03-03 a las 11 00 28

Probably due to this https://github.com/Automattic/dops-components/commit/982ecf16e9bdf82e17a3dea064a26ff7b1f25ebd#diff-d8783ec4987010d013a8709b0e0f8ff3

which also affected toggles in current UI in a worse way

captura de pantalla 2017-03-02 a las 16 20 56

### PR DESCRIPTION
**Pull request by eliorivero**
#### Changes proposed in this Pull Request:

fixes #6554

* **align learn more icons, mobile and desktop**

    captura de pantalla 2017-03-15 a las 12 04 03
    captura de pantalla 2017-03-15 a las 11 25 47

* **evenly space toggle explanation**
    Before

    captura de pantalla 2017-03-15 a las 12 25 19
    captura de pantalla 2017-03-15 a las 12 44 31

    After

    captura de pantalla 2017-03-15 a las 12 25 40
    captura de pantalla 2017-03-15 a las 12 44 16

* **vertically align text with toggle**
    Before
    captura de pantalla 2017-03-15 a las 12 37 25
    captura de pantalla 2017-03-15 a las 12 40 55

    After
    captura de pantalla 2017-03-15 a las 12 37 43
    captura de pantalla 2017-03-15 a las 12 41 06

* **align toggles and notice in dash items, also solves bad positioning issue for notice in dash item on mobile**
captura de pantalla 2017-03-15 a las 16 57 51
captura de pantalla 2017-03-15 a las 17 01 34captura de pantalla 2017-03-15 a las 17 01 50

* **indent explanation for Photon toggle**
    captura de pantalla 2017-03-15 a las 18 10 24

* **update texts for Protect settings card, "Brute force login blocking" for header and "Block suspicious-looking login activity" for toggle description**

### CODE REVIEW

**Comment by MichaelArestad** [comment]
It looks like the infoPopover has inconsistent spacing in the foldable cards:

image

image

image

Other than that, this PR is golden.

**Comment by MichaelArestad** [comment]
The only other thing left to align is the Banner button and I think I can swing that pretty quickly.

**Comment by eliorivero** [comment]
* **Updated spacing and alignment of info icon inside foldable card**

Before

captura de pantalla 2017-03-16 a las 10 25 07

After

captura de pantalla 2017-03-16 a las 11 16 17

* **Aligned elements on mobile**

captura de pantalla 2017-03-16 a las 11 16 31

* **Fixed line height for foldable card header**

Before

captura de pantalla 2017-03-16 a las 11 17 31

After

captura de pantalla 2017-03-16 a las 11 19 13

**Comment by MichaelArestad** [comment]
LGTM

**Pull request merged**
