### PR TITLE
Options: Add wpcom_newsletter_categories_enabled site option #32569

### LINKED ISSUE #80728: Newsletter Categories: Add a master switch that enable/disable Newsletter Categories.
### Details

Figma: hTkvvHDX8yafXQpycivyEX-fi-466_16509

This setting should be stored in site settings. We can reuse existing API endpoints that store site settings for this. The settings name can be decided when creating the PR.

When disabled, the categories UI is not shown.

When enabled, the categories UI is shown.

### PR DESCRIPTION
**Pull request by phcp**
Closes https://github.com/Automattic/wp-calypso/issues/80728

## Proposed changes:

* Adds `wpcom_newsletter_categories_enabled` site option.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pdDOJh-2gO-p2

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Apply the PR to your sandbox (see how to: PCYsg-eg0-p2)
* Sandbox `public-api.wordpress.com`
* Make a GET request to `https://public-api.wordpress.com/rest/v1.4/sites/{site-id}/settings`
* The `wpcom_newsletter_categories_enabled` should be present on the response body under `settings`

### CODE REVIEW

**Comment by TimBroddin** [comment]
Just a personal note: couldn't get it to work with 

``` bin/jetpack-downloader test jetpack add/newsletter-categories-site-option ```

Worked fine with `bin/jetpack-downloader test jetpack add/newsletter-categories-site-option --production`

I need to investigate this later.

**Review by TimBroddin — DISMISSED** [review]
Tested & works!

**Review by TimBroddin — DISMISSED** [review]
Approving again since it's just a rebase

**Review by mashikag — DISMISSED** [review]
Tested, works as expected. 👍

**Review by jeherve — DISMISSED** [review]

**Review by yansern — APPROVED** [review]
Re-approving since this is a rebase.

**Pull request merged**
