### PR TITLE
Fix/swiper css specificity issues

### LINKED ISSUE #20579: Conflict with Elementor and Jetpack Swiper Library
Elementor support has reported that there is a conflict with the Swiper styles in Jetpack versions v9.9 and up (including v9.9.1 and v10).

#### Steps to reproduce the issue

A user reported the following to Elementor:

> Our catalogue which has been set to show 1 column on mobile view has been displaying 2 columns which makes product window too thin, hence shows all details garbled-up, so I contacted Elementor as I use their plugin to set the number of columns which is set to 1 column.

Elementor responded with:

> I understood the case and have solution for this. The issue is not due to Elementor but Jetpack latest version 9.9 conflicting with swiper library Elementor certain widget uses. If you roll back to Jetpack v9.8.1, issue will not happen. You can download it by going to the below URL: https://wordpress.org/plugins/jetpack/advanced/

> For now, either you can roll back Jetpack or use this below temporary CSS code in affected widget custom CSS area to fix the issue -

```
/* Temporary fix for Jetpack CSS conflict with Elementor Slides & Carousel widgets */
selector .swiper-container{
width: 100%;
}
```

Reported on 4197462-zen

### PR DESCRIPTION
**Pull request by glendaviesnz**
Fixes #20579

#### Changes proposed in this Pull Request:

* Adds a jetpack specific selector to the swiperjs css to prevent clashes with other plugins that use swiper.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Check out this PR to local dev and check that all the css still operates as expected on desktop, mobile and RTL

### CODE REVIEW

**Comment by ramonjd** [comment]
Tested on the following:
- mobile and desktop browser - things look as expecgted ✅  
- added a slider to a post - both work ✅ 
- light and dark modes  - both look good ✅ 
- rtl ✅ 
- installed elementor and added an elementor gallery ❌ 

Not related to this PR, but I couldn't test the latter due some JS conflicts. 

The Jetpack tiled gallery stopped working all together, and although the elementor gallery was usable, it threw the following errors:

Screen Shot 2021-08-09 at 11 15 44 am

Uploading elementor-gallery.mp4…

Not exactly sure yet what's going on, but I suspect that we have some globals that are clashing? 🤕

**Comment by ramonjd** [comment]
> I'm not even sure it's an issue since the tiled gallery isn't available as widget when I activate Elementor anyway 🤷

Hmmm, even adding galleries in a fresh elementor page triggers and error in our [jetpack-carousel.js](https://github.com/Automattic/jetpack/blob/84c013c77fb057a16403d60570be1dab58cbee46/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1545)

```js
swiper.on( 'slideChange', function ( swiper ) {
...
if ( swiper.activeIndex === 0 ) { // swiper  is undefined
...
```

**Review by ramonjd — DISMISSED** [review]
Approving as the CSS works as expected.
The JS errors I'm seeing, I'm pretty sure, are unrelated.
Thanks!

**Review by jeherve — DISMISSED** [review]

**Comment by glendaviesnz** [comment]
Sorry @jeherve I did a rebase to make sure the php test failures were not related, and then remembered that I had removed the php changes that I initially had in this PR anyway, so definitely not related! Feel free to go ahead and merge when you give it another tick and I will merge the related diff tomorrow

**Review by jeherve — APPROVED** [review]

**Pull request merged**
