### PR TITLE
Publicize: add Fediverse meta tag on posts when available

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

See https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

If we have an existing Mastodon connection on the site, let's add it as meta tag on each post.

> [!NOTE]
> This first iteration picks up the first available Mastodon connection. I think we should aim to make sure we pick the one that's assigned to the post author. @automattic/jetpack-reach Do you have any ideas on how I could do that?

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* peLCyI-nZ-p2

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Go to Jetpack > Settings > Sharing
* Enable Jetpack Social, and connect your site to a test Mastodon account.
* Go to Posts > Add New
* Write a post and publish it. In the post sidebar, ensure the post is shared to Mastodon.
* Check the source of the post on the frontend: you should see this: `<meta name="fediverse:creator" content="@tests@fedi.jeremy.hu" />`

### CODE REVIEW

**Comment by pablinos** [comment]
This looks good. Thanks for working on it @jeherve!

It's an edge case, but what should we do when there is more than one Mastodon connection? This change will pick the first, but that could be a shared connection from another author on the site. We could check that the connection is owned by the author of the post, but they might not want to promote the post on that account.

Perhaps we live with that for now, as it will be a rare occurrence, and we can tackle it when we look at meta tags in general? We currently have similar problems with picking OpenGraph images and conflicts with SEO plugins.

**Comment by jeherve** [comment]
>  what should we do when there is more than one Mastodon connection? This change will pick the first, but that could be a shared connection from another author on the site. We could check that the connection is owned by the author of the post, but they might not want to promote the post on that account.

Yes, this was my concern as well, as per my question in the PR description.

> Perhaps we live with that for now, as it will be a rare occurrence

I'd be okay with that but wanted y'all to make the call.

> we can tackle it when we look at meta tags in general? We currently have similar problems with picking OpenGraph images and conflicts with SEO plugins.

Is that something that's on the Reach roadmap?

**Comment by pfefferle** [comment]
> It's an edge case, but what should we do when there is more than one Mastodon connection?

I can't say something about the shared connection case (I have not yet looked into the code), but it is possible to add multiple accounts. For now Mastodon will pick the first one, but they think about supporting multiple in the future.

> If multiple tags are present on the page, the first one will be displayed, but we may add support for showing multiple authors in the future.

**Comment by spsiddarthan** [comment]
Hi @jeherve!

I just found the time to review this, my apologies for jumping in on this late. 

In the proposed change, we are picking the first connection that's either owned by the author or a connection that's shared. 
This [line](https://github.com/Automattic/jetpack/blob/ca355dacf1daccce58d362bc72c096211e85f9b7/projects/packages/publicize/src/class-publicize.php#L257) determines whether the connection is shared. We could choose to not add the tags only for non-shared connection for now.  

In a subsequent iteration, even if a connection is shared, we could add a flag to determine whether a shared connection was created by the author. If yes, we could add the tags in that case as well. This is the line fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Schoyvpvmr%2Schoyvpvmr%2Qjcpbz.cuc%3Se%3Q8681o875%26sv%3Qtrg_nyy_pbaarpgvbaf_sbe_oybt_vq%232134-og that populates the connection data. The @reach-team can pick it up, I am not sure of timelines yet, but we can do it within a couple of sprints. 


Screenshot 2024-07-12 at 7 29 51 PM

No, nothing specific towards it at the moment.

**Comment by jeherve** [comment]
Thanks for the feedback!

I just pushed 44cef09429033a078cfaa81ca05063b7cf16457b to add some extra logic:

1. We now keep all existing Mastodon connections for a post, as long as that post was published to that connection. If you (the post author) have opted not to share that post to Mastodon, we do not keep that connection.
2. We keep both your own connections as well as any other global connections on the site.
3. We then sort through those connections:
    * We prioritize your own connections, and pick the first of them,
    * If you haven't published that specific post to a Mastodon connection, we look for global Mastodon connections. If there are some, we pick the first.

Would that logic align with what you had in mind?

**Review by spsiddarthan — APPROVED** [review]
This looks good, @jeherve! We can merge it. 

I tested it on both shared and non-shared connections.

**Pull request merged**
