### PR TITLE
WordAds: don't show ads on unsafe sites

### PR DESCRIPTION
**Pull request by rclations**
#### Changes proposed in this Pull Request:

* Prevents ads from showing on sites marked as unsafe (fetched daily via api)

#### Testing instructions:

Follow the testing instructions in D17303-code, using the new corresponding api work.

#### Proposed changelog entry:

Proposing no changelog entry.

### CODE REVIEW

**Comment by kraftbj** [comment]
Out of curiosity, do we tell WordAds site owners when they are marked as unsafe? This could potential expose someone to that status—just want to be sure that's intentional.

**Comment by rclations** [comment]
That's ok - this isn't hidden information. We likely don't yet have adequate notifications of this status for users, but this is a first step towards getting there as well.

WordAds has a strict "family-friendly" content policy, and it's our duty to ensure that advertisers are only bidding for ad space on sites that meet this policy.

**Comment by rclations** [comment]
Update: D17303-code is live now, so this is ready to go.

**Comment by dbspringer** [comment]
Update looks good, any notes I have reflect some API-side decisions we'll need to make (notably which was should consider "unsafe").

**Pull request merged**
