### PR TITLE
JITMs: remove pre-connection JITMs and only load scripts on Jetpack and Woo pages

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This PR does 2 things:

- It introduces a new method to detect Jetpack and Woo admin pages, so the JITM scripts are only enqueued on those pages. We do not want to display JITMs anywhere else.
- It removes JITMs that were hardcoded in the Jetpack plugin and still displayed on other pages in wp-admin.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* p1HpG7-r5K-p2

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

1. Start with a brand new site, not connected to WordPress.com yet.
2. Go to Appearance > Themes, install and activate a classic theme like Twenty Ten.
3. Go to Plugins > Add New, and add the Classic Widgets plugin.
4. Go to Appearance > Widgets
    * You should see a JITM there
5. Go to the main dashboard, `/wp-admin/`
6. Open the JavaScript console.
    * `jitm_config` should be an object with info that can be used by JITMs.
 7. Now switch to the branch from this PR.
 8. Repeat steps 4 to 6
     * The JITM and the object should be gone.

### CODE REVIEW

**Review by monsieur-z — COMMENTED** [review]
@jeherve, the JITM is gone indeed. `jitm_config` is still available on the `window` object, though.

**Comment by jeherve** [comment]
> jitm_config is still available on the window object, though.

Do you see it on all pages of wp-admin right now?

**Comment by monsieur-z** [comment]
> Do you see it on all pages of wp-admin right now?

It's present on the window object in both the Jetpack and My Jetpack pages but not the other pages it seems (whether I checkout trunk or this branch).

**Comment by jeherve** [comment]
> It's present on the window object in both the Jetpack and My Jetpack pages but not the other pages it seems (whether I checkout trunk or this branch).

That's good, that's the expected behaviour!

**Comment by monsieur-z** [comment]
> The JITM and the object should be gone.

Oh, that referred to the `/wp-admin/` URL specifically?

**Comment by monsieur-z** [comment]
It just needs a rebase, then.

**Review by monsieur-z — APPROVED** [review]
I haven't tested it again after the rebase/merge, but let me know if you'd like someone to give it another go.

**Comment by jeherve** [comment]
Your review is good enough for me, thank you! :)

**Pull request merged**
