### PR TITLE
SEO Tools: make feature available on non-connected sites.

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

The module was previously restricted to paid Jetpack plans. When we added the options to customize the different SEO options to wp-admin (in the block editor and in Jetpack settings), we made the module available to all plans. It is still restricted to paid plans on WordPress.com though.

As a result:

- On self-hosted, we do not need to be checking if the feature is available; it always is.
- On WordPress.com, we should be checking if the feature is available.
- On self-hosted, the feature can consequently be available on offline mode.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Start a brand new JN site.
* Go to Settings > Jetpack constants and enable offline mode.
* Go to Jetpack > Settings > Traffic and enable SEO tools.
* Change some of the settings on that page, and see if they're correctly reflected on your site.
* Go to Posts > Add New
* Open the Jetpack plugin sidebar
    * You should see SEO options there.
* Try changing some of the options and publish your post.
    * The options should be reflected on the frontend.

Now test on WordPress.com simple:

* Sandbox a free WordPress.com site.
* Go to Tools > Marketing > Traffic
    * The SEO options are still not available to you.
* Go to Posts > Add New
    * The SEO options in the sidebar are still not available to you.
* Sandbox a paid WordPress.com site and repeat the steps above.
    * The SEO options are available to you, and making changes should be reflected on the frontend.

### CODE REVIEW

**Review by monsieur-z — COMMENTED** [review]
It tested well with a self-hosted Jetpack site.

However, on WordPress.com, I was able to see the SEO settings in the sidebar panel. Can you reproduce this?
Screenshot 2024-03-26 at 2 55 13 PM
Screenshot 2024-03-26 at 2 55 35 PM

**Comment by jeherve** [comment]
That's interesting. I see this on my end for a free site:

image
image

I can't seem to be able to reproduce the issue. I wonder if the Build task maybe wasn't finished when you tested, and you consequently tested without the last commit. I don't really have any other explanation. :(

Would you mind giving it another try, and letting me know how that goes?

**Comment by monsieur-z** [comment]
Unfortunately, it's still happening to me. I updated the copy both times to verify that I was testing with the correct build.

I pulled the PR, built the plugin, and synced it (along with the `jetpack-mu-wpcom` package) with my sandbox with `rsync`. I verified my sandbox site had no subscriptions at all. Could I be missing something?

**Comment by monsieur-z** [comment]
It works as expected in `Tools > Marketing > Traffic`, for what it's worth.

**Comment by jeherve** [comment]
@monsieur-z I figured it out, it should be okay now!

**Review by monsieur-z — APPROVED** [review]
Looks good now!

**Pull request merged**
