### PR TITLE
Boost: Prevent display issues / crashes from leftover Critical CSS Error data

### PR DESCRIPTION
**Pull request by thingalon**
Jetpack Boost 1.2.0 changes the way that Critical CSS errors are raised and stored, making them more consistent and appropriate for display in the new UI.

However, if there is old error data left in the database from a previous version, it can cause crashes or display issues in the current beta. 

This PR fixes the issue by filtering out old Critical CSS failure information, instead showing a very generic error message for these cases: 

image

This will only affect users who have previously had issues generating Critical CSS, and have since upgraded to 1.2.0. It will encourage them to try again, and they will then receive the updated error flow. 

#### Changes proposed in this Pull Request:
* Filter out invalid Critical CSS error data, ensuring leftover old errors from previous versions do not cause crashes or display issues.

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
1. Install Jetpack Boost 1.1.1 on a test site.
2. Ensure that Critical CSS generation will fail by causing errors in core pages. (e.g.: 500 error on front page)
3. Attempt Critical CSS generation, leaving errors in the system. 
4. Upgrade to 1.2.0 and try to view the Jetpack Boost dashboard.

It should not generate any PHP or JavaScript warnings. The dashboard should clearly show that Critical CSS generation was not successful last time, and encourage users to try again. 

*Also, importantly:* Successful Critical CSS results should not be removed or affected when upgrading from 1.1.1 to 1.2.0.

### CODE REVIEW

**Comment by davidlonjon** [comment]
Hi @thingalon,

It tooks me a while to test this (got to setup a test site and few other things to get a patch version of Boost) and the patch does stop having a display issue. However I have a difference in the UI after the patch for as shown in these 2 videos:

- 

https://user-images.githubusercontent.com/927932/128872967-d8da60d0-28fa-4e94-8f72-cb6154fbc772.mov


https://user-images.githubusercontent.com/927932/128873009-2e9562e9-8fe2-4c14-a048-ebfb6f4dc7e1.mov

It might be that my test is not fully accurate. The first demo is where I put a redirection to the default hello world page. The second demo is when I forced an error on the homepage.

I am running out of time for today to look more into it. I'll make myself available tomorrow to see your feedback and to test the PR again if there are any changes to it.

**Review by davidlonjon — APPROVED** [review]
Following our discussion with on Slack, this is good to go.

**Comment by thingalon** [comment]
Adding @kraftbj and @jeherve as reviewers as a stop-gap until we get David able to approve Boost-specific PRs.

**Review by jeherve — APPROVED** [review]

**Comment by thingalon** [comment]
Cherry-picked to `boost/branch-1.2.0` in 2c6328562.

**Pull request merged**
