### PR TITLE
Shorten publicize message about Facebook Page restrictions

### PR DESCRIPTION
**Pull request by belcherj**
Updates copy on Publicize Facebook Notice

#### Changes proposed in this Pull Request:

* Changes copy for Facebook publicize for previously connected accounts.

#### Testing instructions:

Make 'modules/publicize/publicize.php' L423 ( is_valid_facebook_connection ) return false to simulate a invalid facebook connection

* Go to Gutenberg
* Click Jetpack logo
* Have Facebook connected
* Under "Share this post" observe the error block with correct copy

#### Proposed changelog entry for your changes:

* Updates copy on Publicize Facebook Notice

### CODE REVIEW

**Comment by belcherj** [comment]
I think I messed this up, closing and going to retry.

**Review by gravityrail — DISMISSED** [review]
Works great. I definitely tested this manually.

**Review by oskosk — APPROVED** [review]
LGTM!

**Review by jeherve — APPROVED** [review]
👍 	Merging.

**Pull request merged**
