### PR TITLE
Search: Add upgrade link at the top right of the page

### LINKED ISSUE #26730: Search: Add upgrade CTA on the top-right of the page
Always show the upgrade link for free tier users on the top-right of the page.

From i5 design specs: `p1HpG7-hEH#comment-56620-p2`

截圖 2022-10-11 上午2 08 12

### PR DESCRIPTION
**Pull request by dognose24**
Fixes #26730 

#### Changes proposed in this Pull Request:

* Add a link Button component on the top right of the page for upgrading from the `free` plan.
* Replace JetpackLogo with `JetpackSearchLogo` on the dashboard page.
* Apply the upgrade action to the `UpgradeTrigger` as well.
* Retire the `UsageMeter` component.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1HpG7-hEH-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

> Note: Since the new pricing API is still in progress, this PR replies on the other codebase update `D88792-code`.

* Purchase the Jetpack Search `Free` plan.
* Navigate to the site with URL `/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`.
* Ensure an upgrade link is at the page's top right.
* Click on the upgrade link.
* Ensure the page redirects outside to the checkout flow for upgrading `Jetpack Search`.

> Note: Since the upgrade path from plan `Free` to plan `Paid` is still in progress, the checkout flow will fail until it is completed.

截圖 2022-10-11 下午4 10 16

### CODE REVIEW

**Review by a8ck3n — DISMISSED** [review]
This looks good and test well. The only question I have is about the button visibility. Are we supposed to have this gated behind the `isNewPricing` check? If not, this is probably good to go!

**Comment by a8ck3n** [comment]
I spoke too soon! The "Upgrade Jetpack Search" button is still visible even though I have a payed plan. We should probably hide this if the site already has a paid plan, right?

**Comment by dognose24** [comment]
Update the gate for upgrade link with `isNewPricing` and plan `Free` in [fb2ea3b](https://github.com/Automattic/jetpack/pull/26737/commits/fb2ea3bafca12cc6d2ca925c78bdcfcc6dfb178d).

**Review by jsnmoon — APPROVED** [review]
Works as described 🚢 

In a follow-up PR, we need to ensure that the upgrade links point to the checkout flow instead of the connect + checkout flow.

**Pull request merged**
