### PR TITLE
Super Cache: Fix deprecation notices

### LINKED ISSUE #32336: [Super Cache] More PHP 8 warnings
We have [new reports of PHP 8 warnings](https://wordpress.org/support/topic/php-8-1-php-deprecated-strstr/#post-16929870). These include:

```
[28-Jul-2023 11:49:59 UTC] PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 227

[28-Jul-2023 11:49:59 UTC] PHP Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /home/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 808
```

These should be quick fixes to squeeze in, in advance of the 1.10 release.

### PR DESCRIPTION
**Pull request by haqadn**
Fixes #32336

## Proposed changes:

* Ensure `$wp_cache_request_uri` is always set to a string.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

None

### CODE REVIEW

**Review by donnchawp — CHANGES_REQUESTED** [review]
I confirmed that `$_SERVER['REQUEST_URI']` is NULL in a script run from the command line, so that is likely where the null value is coming from.

I saw in `get_wp_cache_key` in wp-cache-phase2.php (around line 40) that we fixed the same problem by checking for null. I think we can probably remove that check now with this fix.

**Review by donnchawp — APPROVED** [review]
Looks great. I checked where $wp_cache_request_uri is used and it's good.

**Comment by donnchawp** [comment]
deb8585fed7941dab2e30d76bd218be2c5eed10a

**Comment by A-Printer** [comment]
@donnchawp The removal of the `if ( null === $url )` check causes a Deprecated notice to be thrown on the frontend when logged as an admin:

Capture d’écran 2023-08-18 à 13 26 52

Also, the Deprecated notice causes the REST API check to fail on the Site Health page:

Capture d’écran 2023-08-18 à 11 56 20

**Comment by donnchawp** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/32629

**Pull request merged**
