### PR TITLE
Pr/7794 Redux -- Core 4.9 / Custom CSS

### PR DESCRIPTION
**Pull request by georgestephanis**
Fixes #7794 

Minimum revision of core to test against: https://core.trac.wordpress.org/changeset/41992

### CODE REVIEW

**Comment by georgestephanis** [comment]
This PR is dependent on https://core.trac.wordpress.org/changeset/41974 being in your core checkout.  If something's screwy, try a `svn up` first.

**Comment by georgestephanis** [comment]
Please test this for functionality and behavior, as well as regressions.

**Comment by georgestephanis** [comment]
Vizrec:

Old version in core 4.8.2:

screen shot 2017-10-24 at 11 05 09 am

New version in Core 4.9-beta?

screen shot 2017-10-24 at 11 04 04 am

I had to adjust the editor height down a bit, which shrunk the old one a bit too, but that's small potatoes and only for folks running older versions of core.

**Comment by georgestephanis** [comment]
If testing this, make sure you're up to https://core.trac.wordpress.org/changeset/41992 on your core checkout.

**Comment by zinigor** [comment]
Tested with Core both before 41992 and after, everything seems to be working correctly. There's one minor problem that I have noticed. If you follow these steps:
- start with a blank CSS;
- type up a valid CSS modification with SASS (or LESS) that's not backwards CSS compatible, like `a { &:hover{ color: red; } }`;
- abandon customizing;
- return to the customizer and restore the revision;
- see the errors that only disappear after you toggle the preprocessor.

**Comment by georgestephanis** [comment]
To clarify, the errors only display when the mode is set to CSS right? That's expected as it's invalid css.

**Comment by georgestephanis** [comment]
Or do you mean that the css persists but preprocessor selection doesn't? @zinigor

**Comment by zinigor** [comment]
Yes, sorry, I meant that the selector persists, but the errors still get displayed as though it's set to be simple CSS.

**Comment by georgestephanis** [comment]
Got the design review from @MichaelArestad yesterday, clearing the tag.

**Pull request merged**
