### PR TITLE
Nav-unification: update nudge to support Pro plan.

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

This PR updates Jetpack following similar changes on WordPress.com.

﻿- Masterbar: Update nudge for Pro plan
- Update tests

WordPress.com references:
- D77832-code
- D77823-code

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* See diffs above for instructions.
* Is CI happy?

### CODE REVIEW

**Comment by sdixon194** [comment]
Looks like two tests are failing - one in `projects/plugins/jetpack/tests/php/modules/masterbar/test-class-atomic-additional-css-manager.php` and one in `projects/plugins/jetpack/tests/php/modules/masterbar/test-class-wpcom-additional-css-manager.php`. The first one looks like an easy fix, but not sure where the mock WP_Customize_Manager is getting `premium` from still.

**Comment by jeherve** [comment]
@gmovr Do you think you could take a look at this? Thank you!

**Comment by coder-karen** [comment]
@gmovr just following up here, to see if you can take a look at the failing tests here :)

**Comment by gmovr** [comment]
@coder-karen  Sorry! I must have missed the first ping here. I'll sort this now and ping you once done. We changed the test for CTA url and text in the masterbar to deploy D77823-code.

**Comment by gmovr** [comment]
@jeherve @coder-karen The tests pass now. The one failing test is because this repo has now diverged from WPcom. I've done the same changes in the wpcom repo now - as the `ENABLE_PRO_PLAN` flag is redundant. Once D79218-code is deployed, the last failing wpcom test should also pass :)

**Pull request merged**
