### PR TITLE
Full Site Editing: sync callable for FSE theme support

### PR DESCRIPTION
**Pull request by mattwiebe**
This effectively returns the value of `gutenberg_is_fse_theme()` so that the WPCom REST API can take action on FSE support properly.

Fixes https://github.com/Automattic/wp-calypso/issues/52981

#### Changes proposed in this Pull Request:

* returns `is_fse_theme` under Sync callables

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
nope

#### Testing instructions:
Testing instruction in D63759-code

### CODE REVIEW

**Comment by mattwiebe** [comment]
PHP Unit tests incoming once I can get them working (Docker can clearly feel my hatred and is on strike)

**Comment by enejb** [comment]
Nice work. This worked well in my testing. 

I tested switching themes, enabling disabling the Gutenberg plugin while running wp 5.7
It worked as expected for me.

**Review by enejb — APPROVED** [review]
The code looks good!

**Review by jeherve — APPROVED** [review]
It seems you still have some lock files to update

**Pull request merged**
