### PR TITLE
Update class.jetpack.php to improve environment test

### PR DESCRIPTION
**Pull request by Cais**
Adds additional conditional tests for common "local" environments that may have a "." in their site_url() such as ".dev" and ".local"

### CODE REVIEW

**Comment by georgestephanis** [comment]
I think this is a probably a good improvement, but I'd rather see it swapped perhaps with a `switch()` statement to make it easier to add conditionals -- for example perhaps a `filter_var()` call, testing the server ip against `FILTER_FLAG_NO_PRIV_RANGE` and `FILTER_FLAG_NO_RES_RANGE ` (with appropriate tests to handle cases where the server is behind a load balancer and its ip may be an internal ip in one of those ranges)

**Comment by Cais** [comment]
Wow ... um, well, I'm glad it's "probably a good improvement" but you started losing me somewhere after using a `switch()` and `filter_var()` call. Those I understand but you might have seen my eyes glazing over as I read the rest  (*grin*). I'll look into these ideas further and see if I can grok what you are suggesting.

I know the patch is not very elegant; more a kluge than anything else ... but I also did not want to let the idea slip away without getting it out there in some functional form.

**Comment by georgestephanis** [comment]
Ah yeah, sorry -- was just using the pull request more as an internal scratch pad than anything else.

Thanks!

**Comment by Cais** [comment]
Oh, cool. I'm still going to look at a nicer approach all the same. The `switch()` idea would make it much easier to extend going forward ...

**Comment by Cais** [comment]
I have a different approach using the `switch()` function. I'm not seeing how I can change this "patch" so should another "pull request" be made, or is there a better method?

**Comment by kraftbj** [comment]
@Cais: To update the PR, just add a commit to the `site_url-conditional-update` branch that you made originally. Once that's pushed to your fork, it'll automatically update the PR.

+1 to expanding the automatic checks to .dev, .local, and private IP ranges (as noted withe checks re behing LBs).

**Comment by Cais** [comment]
@kraftbj Thanks! I want to tighten up the code a bit more, but I should be able to write the commit to that branch later today ... although I'm still sorting out the "private IP ranges" idea so it may not be there immediately.

**Comment by Cais** [comment]
I still would like to look into the "private IP ranges" but the additional filter hook used in the `switch()` statement should allow for the idea being externally checked for the time being.

**Comment by samhotchkiss** [comment]
I think we should only look for URLs that *end* with .dev or .local-- as is, it would flag "www.devtools.com" or "www.localrestaurants.com" as dev sites...

**Comment by rcoll** [comment]
I agree with @samhotchkiss. @Cais If you do something like 

`case ( 0 !== substr_compare( site_url(), '.local', -strlen( '.local' ) ) ) :`

instead of 

`case ( ! strpos( site_url(), '.local' ) ) :`

it will detect that .local is only at the end of the site_url().

Additionally, I believe George was recommending the use of [filter_var()](http://php.net/manual/en/function.filter-var.php) with some [flags](http://php.net/manual/en/filter.filters.flags.php) to detect if the server's IP address is a local or restricted address.

If you can handle these changes I'd be happy to see what's eligibe for merge in 4.4.

**Comment by Cais** [comment]
@rcoll I'm not sure if/when I will have time to look further into this ticket (at least this week, if not longer ... just too much life going on right now). If this is wanted sooner then please feel free to make the changes as needed.

**Pull request closed without merging**
