### PR TITLE
External Media: Update source icons

### LINKED ISSUE #17472: External Media: Source icons in the wrong spot
We're offering a choice of three different sources for media - browsing the media library, adding photos from Google Photos, or through Pexels. The icons for each option are displayed after the text, which looks really unbalanced and isn't following design standards we have everywhere else in calypso. 

#### Steps to reproduce

1. Create a new post or a page. Add Image block.
2. Click the "Select source" option. Notice the icons placement for each of the options.
3. Insert an image, then select it and click the "Replace" button on the toolbar. Again, notice the icons placement for each of the options.
4. Compare to the options in the Paragraph block, where all the icons are placed on the left.

Same issues apply to the Gallery block.

#### Screenshot / Video
image

Image block, replace image options. This one is particularly problematic because **some of the icons are aligned to the right, while others are placed right after** the text. Also, note that **the icon for the media library in this one is different** than in the next screenshot.

image

Image block, insert new image through "Select source" option. Compare this to the Paragraph block below:

image

#### Context / Source
#dogfooding

### PR DESCRIPTION
**Pull request by obenland**
Fixes #17472 

Updates external media provider icons to be properly aligned in the latest Gutenberg version (without breaking existing versions). Also updates Media Library icon.

#### Changes proposed in this Pull Request:

* Adds html class for icons to be properly aligned
* Adds `@wordpress/icon` library to replace old media library Icon
* Updates `yarn.lock`, not sure if that's desired.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Go to the Editor
* Click to add a Featured Image in the right sidebar and make sure (1) the Icons are aligned to the right (or left, depending on Gutenberg version) and (2) the media library icon is updated (an SVG rather than dashicon)
* Insert a media & text block and add an image to the media part.
* Click on "Replace" and make sure the icons are aligned properly

#### Proposed changelog entry for your changes:

* External Media: updated iconography and better forward compatibility.

Before | After
--- | ---
Screen Shot 2020-10-09 at 1 11 00 PM | Screen Shot 2020-10-09 at 1 25 56 PM
Screen Shot 2020-10-09 at 1 11 17 PM | Screen Shot 2020-10-09 at 1 27 17 PM

### CODE REVIEW

**Comment by obenland** [comment]
@jeherve When I added the icons package it also updated `yarn.lock`, not sure if that's desired.

**Review by mreishus — APPROVED** [review]
Looks good in my testing, and I'll let someone else answer about the `yarn.lock`.

**Before**:





**After**:

**Review by marekhrabe — APPROVED** [review]
Looking good, including yarn.lock updates.

**Review by jeherve — APPROVED** [review]
This should be fine. 

Related conversation about the need for the new dependency:
p1602499422174100-slack-CJS75TX3R

**Comment by obenland** [comment]
r215160-wpcom

**Comment by jeherve** [comment]
Note: in #17476, @alaczek pointed out there are still some alignment issues in the image block sidebar.

**Pull request merged**
