### PR TITLE
wpcomsh: Update WooCommerce Calypso Bridge to 2.5.2

### PR DESCRIPTION
**Pull request by ivan-ottinger**
## Proposed changes:

This PR bumps the version of `wc-calypso-bridge` to `2.5.2`, which includes the following change:

https://github.com/Automattic/wc-calypso-bridge/pull/1484

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No, it does not.

## Testing instructions:

The changes related to the `wc-calypso-bridge` were already tested in the related PR (https://github.com/Automattic/wc-calypso-bridge/pull/1484).

If you would like to test further with WoA, you can follow the Jetpack rsync steps in pf4qpu-sv-p2.

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
Hey @zinigor 👋🏼 I have added you as a reviewer since this will probably be the first `wc-calypso-bridge` version bump after the move (pf4qpu-sv-p2#comment-388).

Of course, no pressure to review, this is just if you would like to take a look. My home @Automattic/apex can review the PR.

**Comment by zinigor** [comment]
Hi @ivan-ottinger ! Great stuff, thank you for working on this, welcome to the new wpcomsh in the Monorepo!
The PR looks good, everything is as it should be, my only question is about the changelog entry. You chose the minor version update instead of the patch level update, is that because of the changes between the two versions of wc-calypso-bridge? I'm curious because the dependency bump is from patch level to patch level version.

**Comment by zinigor** [comment]
As for the conflict - you can fix it by merging trunk, checking out conflicting files from trunk so you don't have to merge manually, and re-run the `tools/fixup-project-versions.sh` script.

**Comment by ivan-ottinger** [comment]
Thank you for your feedback, @zinigor! I appreciate it.

> The PR looks good, everything is as it should be, my only question is about the changelog entry. You chose the minor version update instead of the patch level update, is that because of the changes between the two versions of wc-calypso-bridge?

Yes, that's right. I considered the `wc-calypso-bridge` change small, so that's why I picked `minor` in the changelog.

> I'm curious because the dependency bump is from patch level to patch level version.

I think you are referring to the combination of using `minor` in the changelog and version bump from `3.22.14-alpha` to `3.23.0-alpha`, right? To be honest, I did not notice it myself until you pointed it out. The `tools/fixup-project-versions.sh` script changed the version that way. So maybe the it would be better to use `patch` instead of `minor` in the changelog as well, right? 🤔

**Comment by zinigor** [comment]
Yes, that's what I mean - the patch level is changing the third version number in the three possible in semver, while minor is changing the second. If you change the added changelog file in the `changelog/` folder, the fixup script is going to fix the version automatically on the next run.

**Review by zinigor — APPROVED** [review]
Looks great, thanks!

**Comment by ivan-ottinger** [comment]
Hey @zinigor 👋🏼 Thank you for your review here. I just wanted to check one thing, now we only have three files changed there - as opposed to the previous PR version that was updating the version in `projects/plugins/wpcomsh/wpcomsh.php` and `projects/plugins/wpcomsh/package.json`.

When I run the script to update the versions, it doesn't update anything more. 🤔

**Comment by zinigor** [comment]
That's exactly how it should be now, the automation is going to use the correct version when we release it. The next release I'm going to conduct very soon today - I'm going to release both Jetpack weekly, and wpcomsh along with all its dependencies. It's going to receive a corresponding version at that time.

**Comment by ivan-ottinger** [comment]
> That's exactly how it should be now, the automation is going to use the correct version when we release it. The next release I'm going to conduct very soon today - I'm going to release both Jetpack weekly, and wpcomsh along with all its dependencies. It's going to receive a corresponding version at that time.

Perfect! Thank you for the details, Igot. That helped!

**Pull request merged**
