### PR TITLE
Remove the `blip` shortcode

### PR DESCRIPTION
**Pull request by lancewillett**
Service is extinct.

Removed from WP.com in r147173-wpcom.

### CODE REVIEW

**Comment by dereksmart** [comment]
Thanks for porting this over 👍 

Related reading about why blip.tv is no longer: http://variety.com/2015/digital/news/disney-owned-maker-studios-shuts-down-pioneering-video-site-blip-1201575041/

**Comment by eliorivero** [comment]
@lancewillett my only concern with removing the shortcode is that if users have it in their content, it will show up as text now that the shortcode doesn't exist.

Perhaps we should do something like:
```php
function blip_shortcode() {
    return '';
}
add_shortcode( 'blip.tv', 'blip_shortcode' );
```

**Comment by dereksmart** [comment]
I was thinking of this yesterday too.  We could also take it one step further. 

```
function blip_shortcode() {
    if ( current_user_can( 'edit_post' ) ) { 
        return esc_html_e( 'Blip shortcode has been deprecated. Only authors of this site can see this message.', 'jetpack' );
    }
    return '';
}
add_shortcode( 'blip.tv', 'blip_shortcode' );
```

**Comment by lancewillett** [comment]
I love the idea of the deprecation message.

A small improvement over returning the empty string for non-site-owners would be returning the bare URL or making a nice permalink. Because the service could return someday; or be resurrected with redirects. So that way at least the site content would show a link to something.

**Comment by dereksmart** [comment]
Marking as in progress.  @georgestephanis volunteered to get a simple version of this working today :)

**Comment by dereksmart** [comment]
Merging as we're working on the deprecation in #5862

**Pull request merged**
