### PR TITLE
Make sure when the user clicks on the Media -> Add New menubar item VideoPress works

### PR DESCRIPTION
**Pull request by dbtlr**
#### Changes proposed in this Pull Request:

WordPress has 2 media uploaders, the one embedded in the Media Library and an older one inside the `wp-admin/media-new.php`. This replaces the submenu item and adds in a method to have the uploader opened up when the standard media library is loaded.

#### Testing instructions:

1) Click: Media -> Add New
2) You should be directed to `wp-admin/upload.php?action=add-new`
3) This will open the media library with the Add New media item box open

### CODE REVIEW

**Comment by ebinnion** [comment]
If the user has the list view of the media library enabled, then clicking "Add New" takes the user to `/wp-admin/media-new.php`.

**Comment by dbtlr** [comment]
This isn't a bug, this is how default WordPress works. It doesn't use the JavaScript uploader except in the grid view. I'm closing this, as this cannot be "fixed" without replacing the media library as a whole.

There are unfortunately limitations to what we can override. :(

**Comment by dbtlr** [comment]
@ebinnion: This is not something that is an error, so much as something we cannot override. The core media library has several versions under the hood and only the grid view is built on JavaScript and can be changed. The list view is rendered in PHP and would need to be replaced to be changed.

The only way I'd be able to do this would be the hijack the Add New button with JS and redirect it's click to the grid view upload box, which would in effect remove the list view the user selected. No good solutions unfortunately.

**Comment by zinigor** [comment]
Ported to `branch-4.4` in dd43063.

**Pull request merged**
