### PR TITLE
My Jetpack: Set post-checkout redirect URL on the plan purchase link

### LINKED ISSUE #27559: My Jetpack: fix the redirect URL after a plan purchase from My Jetpack screen when Jetpack is not present
After we buy a plan using the My Jetpack "Purchase a plan" flow, we get redirected to `/wp-admin/admin.php?page=jetpack#/recommendations`.

This screen will not work when the Jetpack plugin is not enabled and we have just Jetpack VideoPress plugin available (or any other standalone plugin). We need to set the right redirect destination for this scenario.

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #27559.

#### Changes proposed in this Pull Request:

* Set a post-checkout redirect destination on the "Purchase a plan" link, so the user is redirected back to the "My Jetpack" screen after buying a plan

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Install and activate the Jetpack VideoPress standalone plugin
* Make sure you don't have the full Jetpack plugin active
* Make sure you are not logged into Jetpack Cloud
* Go to `Jetpack > VideoPress` and choose to start using a free plan on VideoPress

Screen Shot 2022-12-01 at 13 53 52

* Go to `Jetpack > My Jetpack`
* On the bottom of the page, click the "Purchase a plan" link

Screen Shot 2022-12-01 at 13 57 50

* You will land on the page offering products and bundles
* On the "Products" section, select the VideoPress plan and proceed with the checkout 

Screen Shot 2022-12-01 at 13 58 51

* After you finish the checkout, you will be redirected to a page inside your site
* Before the change, the page would be `/wp-admin/admin.php?page=jetpack#/recommendations`, a page that would not exists on our test scenario since Jetpack is not installed or enabled
* After the change, the page will be the My Jetpack page, that was the page where the user started the purchase flow

### CODE REVIEW

**Comment by renatoagds** [comment]
@lhkowalski can you rebase this one? it still `in progress`?

**Comment by oskosk** [comment]
@lhkowalski is this one still valid?

**Comment by renatoagds** [comment]
I added it to the `My Jetpack` board. So we can look on it

**Comment by lhkowalski** [comment]
I will figure out if the issue is still valid and if we need to change something on this PR before shipping it.

**Comment by lhkowalski** [comment]
@oskosk @renatoagds the issue described by #27559 is still happening, so this fix is still valid.

I changed the original fix to redirect the user back to My Jetpack instead of using the top-most item on the Jetpack menu, so it's more generic and provides a better UX: the user started the purchase on My Jetpack, so he will get back to it after the purchase.

Feel free to review it when you have some bandwidth.

**Review by dhasilva — CHANGES_REQUESTED** [review]
The redirect URL is propagated correctly, but it seems to be ignored and we are redirected to the recommendations page regardless. :disappointed:

**Comment by lhkowalski** [comment]
The `query` parameter on the URL seems not to work the way I expected, so I am going to use some internal checkout URL generation hook to get a more reliable way of doing it.

**Comment by lhkowalski** [comment]
> The `query` parameter on the URL seems not to work the way I expected, so I am going to use some internal checkout URL generation hook to get a more reliable way of doing it.

EDIT: It's actually working. The issue is on another place.

The checkout flow is different if the user is logged or not to `cloud.jetpack.com`.

If the user is logged, they will be prompted to add a product to the cart and proceed to checkout after it:

Screen Shot 2023-05-03 at 19 41 37

If the user is not logged, they will be prompted to get a product, and clicking this button will lead directly to checkout:

Screen Shot 2023-05-03 at 19 41 47

When the user is not logged, the fix on this PR works.

When the user is logged, the `redirect_to` parameter is being ignored.

I think we can review this PR as an initial fix to the issue that is valid for not logged users, and then contact the team responsible for checkout to see if we can help them make the `redirect_to` parameter work on the logged flow as well.

**Review by dhasilva — APPROVED** [review]
SGTM. Thanks for the investigation!

**Pull request merged**
