### PR TITLE
Sync: Plugin action links set on current_screen instead of admin_init

### PR DESCRIPTION
**Pull request by enejb**
I took https://github.com/Automattic/jetpack/pull/9960 and made the test pass. 

Props to @TheCrowned for 9960. 

### Testing instructions
Same as #9960 

### Proposed changelog entry
Move the call set_plugin action links to a later filet so that more plugins can add their action links.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
Unfortunately it looks like the tests are still failing.

**Comment by jeherve** [comment]
Tests are passing 🎉 	

How do I test this? The original PR isn't too helpful unfortunately:

> Load admin pages (in particular plugins page).

**Comment by enejb** [comment]
The way to test this would be to add a plugin that will generate the action links. 

 
Then check that they show up as expected on the mobile app as well as in calypso individual plugin section. Mobile app adds uses the synced action links in the API. Calypso uses the calculated data from the shadow site.

**Review by jeherve — COMMENTED** [review]
> Then check that they show up as expected on the mobile app as well as in calypso individual plugin section.

I tried activating Jetpack with this patch on a site with the following plugins:

- All In One SEO
- Google Analytics for WordPress by MonsterInsights
- WPForms Lite
- Yoast SEO
- UpdraftPlus

All these plugins include action links in wp-admin, and those work. However, I only saw action links in Calypso for one of them, All In One SEO.

Is that expected?

**Comment by enejb** [comment]
calypso is working for me as expected see
screen shot 2019-01-24 at 9 27 19 pm
screen shot 2019-01-24 at 9 29 26 pm
screen shot 2019-01-24 at 9 33 03 pm

Altough there is still something not working as expected. :/

**Comment by enejb** [comment]
I investigated this further and it turns out that the reason why you didn't see the links right away is probably due to the 1 day long transient cache that is in place. 

I pushed a change to the PR so that the cache is ignored if you are on the plugins page.

**Review by jeherve — APPROVED** [review]
This works well now. Merging.

**Pull request merged**
