### PR TITLE
Admin Page: activate Publicize before to link to its settings

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* See https://github.com/Automattic/wp-calypso/issues/45288#issuecomment-701184609

After connecting a brand new site to your WordPress.com account, you are directed to Jetpack > My Plan when you want to go back to wp-admin. There, we offer a number of Jetpack features you can start using. One of those is Publicize. We suggest you "start sharing" by clicking a button that leads you to Publicize settings in Calypso. However, at that point Publicize is most likely not active yet; that Publicize settings screen is consequently not available yet.

In this PR, when the module is not active, instead of linking to Publicize settings we offer a button to activate the feature. If the feature is active, we then link to Publicize settings.

In addition to this change, I've also made sure we do not show the card if [someone deliberately chose to make Publicize unavailable on the site](https://jetpack.com/support/module-overrides/).

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No 

#### Testing instructions:

* On a brand new site, connect to WordPress.com and do not buy a plan.
* Head back to Jetpack > My Plan
* By then, the Publicize module has not been active yet. You should see an option to "activate publicize"
* Clicking it should activate the module
* You should then be able to click "start sharing"

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by pento** [comment]
Is it possible to just automatically enable Publicize when the "Start sharing" button is clicked, rather than requiring the site owner to a) know what Publicize is, and b) click twice to enable sharing?

**Comment by jeherve** [comment]
It should be possible, yes. I mostly followed the existing pattern we have for other features (Re-Publicize, Google Analytics, VideoPress, Ads, SEO) on this page, that all seem to require that the feature first be activated, then configured.

Maybe we should change all of them into a single "activate and configure" button, but maybe in a follow-up PR?

**Comment by pento** [comment]
> It should be possible, yes. I mostly followed the existing pattern we have for other features (Re-Publicize, Google Analytics, VideoPress, Ads, SEO) on this page, that all seem to require that the feature first be activated, then configured.

Some of those modules are a little different, since activating them makes immediate changes to how the site functions, while activating Publicize does nothing until after you've connected to an external service, and published a post. It's something of a semantic argument, though. I agree with your broader point:

> Maybe we should change all of them into a single "activate and configure" button, but maybe in a follow-up PR?

Yup, the NUX for all of them could probably do with some attention. 🙂 I'm cool with doing this now (so people can at least activate it and use it), then polish later.

**Comment by jeherve** [comment]
> Some of those modules are a little different, since activating them makes immediate changes to how the site functions, while activating Publicize does nothing until after you've connected to an external service, and published a post

That's true, makes sense. 

> the NUX for all of them could probably do with some attention

I created an issue here to keep track of this:
https://github.com/Automattic/jetpack/issues/17320

**Review by pento — APPROVED** [review]
Let's go with this, to at least ensure the feature works.

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.0` in a8a64b2782614a70e209243f9edc90eab768b885

**Pull request merged**
