### PR TITLE
Boost: Update Image Size Analysis to use real data for last updated timestamp

### LINKED ISSUE #31503: Boost: Update Image Analysis report to use `updated_at` column
### Impacted plugin

Boost

### Quick summary

Currently, the [`updated_at` is hard-coded](https://github.com/Automattic/jetpack/pull/31234/files#diff-7ba42299653af66b6ea82699feed3aa0db9603f359a8b84d7faac58971983dcdR49).

### PR DESCRIPTION
**Pull request by dilirity**
Depends on D115367-code. Merge this PR into trunk after deploying it.

Fixes https://github.com/Automattic/jetpack/issues/31503

## Proposed changes:

* Updates the last_updated property to use data provided by wp.com.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup Boost with Image Size Analysis;
* Make sure to apply this patch on your sandbox D115367-code;
* Request a report;
* After the report is done, go to the detailed page;
* The `Latest report` should show the correct time now (was previously hard-coded).

CleanShot 2023-07-05 at 21 42 13@2x

### CODE REVIEW

**Review by thingalon — DISMISSED** [review]
I feel like `. 000` is a bit strange compared to `* 1000` but... ok. I don't think it's an issue.

**Comment by thingalon** [comment]
Merged trunk as e2e tests were broken. Hoping that fixes them.

**Comment by dilirity** [comment]
> I feel like . 000 is a bit strange compared to * 1000 but... ok. I don't think it's an issue.

🤦🏻 You're right. I will fix that.

**Review by donnchawp — APPROVED** [review]
Looks good!

**Pull request merged**
