### PR TITLE
Add PHP 7.1 testing

### LINKED ISSUE #5959: Unit Tests: add PHP 7.1
It would be nice to add PHP 7.1 to our list of Unit Tests, as it includes a few breaking changes from PHP7, and is getting more and more popular with site owners.

### PR DESCRIPTION
**Pull request by kraftbj**
Adds PHP 7.1 released December 1st and unit tested by Core. Fixes #5959

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Why are we running PHP 5.6 twice?

Really, it seems like running against 5.2 and 7.1 should cover us pretty well-- I don't think we've ever run into an issue that is present in some versions, but not our minimum or maximum versions.

**Comment by dereksmart** [comment]
@samhotchkiss the purpose of the first instance of 5.6 is just a base where we test the js client/admin UI build.  The 2nd in the list actually runs the phpunit stuff.

**Comment by dereksmart** [comment]
The 7.1 test is the only one failing :) Let's address this in the same PR.

**Comment by kraftbj** [comment]
Punting out of 4.5 with today's beta deadline. Haven't had any errors in support yet.

**Comment by zinigor** [comment]
Since we're doing tests, I have fixed deprecated mock usage, fixed 7.1 errors and removed annoying test output. The problem is that 4.6 is incompatible with 7.1, so we'll have to work on that separately, let's leave it for 4.6.

**Comment by jeherve** [comment]
#6106

**Comment by zinigor** [comment]
Fixes #5810

**Pull request merged**
