### PR TITLE
Make wordads discoverable

### LINKED ISSUE #33165: WordAds: make block available in editor, even when the module is not active yet
See Primary issue: #32401

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Fixes https://github.com/Automattic/jetpack/issues/33165

## Proposed changes:

This change will alow registering Wordads Block even if the Wordads module is disabled. It should show the placeholder allowing to enable the module in one click. This is aimed at making our blocks more discoverable.

Note: it will only show up if user owns a plan that allow WordAds.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Spin up the branch locally and tunnel with JT to your sandbox
* Build `plugins/jetpack`
* Navigate to `/wp-admin/admin.php?page=jetpack_modules` and make sure that Ads module is disabled
* Make sure you don't have plan that supports Ads (No Complete)
* Create a new post `/wp-admin/post-new.php`
* In blocks menu make sure you **don't** see the `Ad` block.
* Purchase 'Jetpack Complete' plan
* Create a new post `/wp-admin/post-new.php` and you should see 'Ad' block.
* Adding it should show loading and/or a placeholder with the ability to activate the module. 

Screenshot at Sep 14 15-35-30

Screenshot at Oct 19 18-48-39

* Activate the module and check that the form works as expected.

### CODE REVIEW

**Review by monsieur-z — COMMENTED** [review]
It works as expected. There are some concerning points, however:
- In my instance, the placeholder stayed on the screen for a long time (5-10s) before rendering the final state. Did you experience the same?
- I could see several errors in the console that I didn't see on `trunk`. Can you see them too?
- Screenshot 2023-10-20 at 9 50 35 AM

**Comment by andrii-lysenko** [comment]
@monsieur-z Thanks for the review. I indeed experience long waiting periods, but it mostly due to the fact we use tunnels. It loads faster in prod. However, with the deployment of https://github.com/Automattic/jetpack/pull/33397 we should have it even smoother.
As per second issue, I can't reproduce it, however, I did `build --all` before the start. In what particular case you experience these?

**Comment by monsieur-z** [comment]
Thanks for the clarification @andrii-lysenko.

I saw the errors when I added the block to the page. You didn't see them so it's likely it was because of the state of my builds when I tested. Please go ahead with this PR.

**Review by monsieur-z — DISMISSED** [review]

**Comment by andrii-lysenko** [comment]
@monsieur-z sorry, I found potential issue, so I had to push another commit

**Review by monsieur-z — APPROVED** [review]
LGTM! Just need a rebase.

**Pull request merged**
