### PR TITLE
Instant Search: Implement cancellable API requests

### LINKED ISSUE #13366: Instant Search: handle API failures and displaying failure info
We should handle the API errors based on whether we got a response and what the error code is. Any 4xx should not be run again. 5xx should probably be retried after a bit of time.

I am not sure what we should display in the UI. Depends a lot on if there is already data getting displayed.

### PR DESCRIPTION
**Pull request by jsnmoon**
Part of #13366.

#### Changes proposed in this Pull Request:
* Replaces `unfetch` ponyfill with `axios`, which supports cancellable requests using a cancel token API.
* When a new search request is fired, old search requests will be cancelled.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Using a Jetpack site, test these changes by searching your site. Confirm that XHR network requests are being canceled by newer requests in the browser network console. @bluefuton note: it's easiest to see this in Chrome.
* Using a private Atomic site, repeat the above test step.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by bluefuton** [comment]
Rebased package.json as there were a couple of conflicts 👍

**Review by bluefuton — APPROVED** [review]
Works as described:

Screen Shot 2020-11-17 at 15 04 41

**Review by jeherve — APPROVED** [review]
This works well for me. I would, however, have expected the request to get cancelled when I typed (a first search is launched), then added another letter before the first search is completed. As it is right now, it only seems to get cancelled if you delete your search and then search for something else?

**Comment by jsnmoon** [comment]
> I would, however, have expected the request to get cancelled when I typed (a first search is launched), then added another letter before the first search is completed. 

You just described our current implementation, actually. We bind to the input event on the search input, which kicks off a search API request. Before sending out the current API request, we cancel any prior API requests in flight.

In other words, requests should be getting canceled as you type. I took a quick swing testing this locally and on WPCOM and was able to cancel redundant network requests by slowly typing out "hi there" (which spawned 8 network requests, 7 of which were canceled).

**Comment by jsnmoon** [comment]
Deployed in r216963-wpcom.

**Pull request merged**
