### PR TITLE
Custom Post Types: Changing Nova methods to be public

### LINKED ISSUE #25077: Restaurant menu: Why making certain methods private in `Nova_Restaurant` class?
### Impacted plugin

Jetpack

### Steps to Reproduce

If you use my theme [Auberge](https://wordpress.org/themes/auberge/) which is compatible with Restaurant Menu custom post type functionality of Jetpack plugin, it does not work as intended anymore.

### A clear and concise description of what you expected to happen.

The theme stopped displaying food menu on-page navigation, heading structure is compromised on front page, and there are possibly other issues.

### What actually happened

This issue happens due to certain methods in [`Nova_Restaurant` class](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/custom-post-types/nova.php) been set as `private` in #24212.

My [Auberge](https://wordpress.org/themes/auberge/) theme [extends `Nova_Restaurant` class](https://github.com/webmandesign/auberge/blob/master/includes/plugins/jetpack/class-nova-restaurant.php) and now I can not change these methods as PHP class extension does not work on private methods. Here are specific methods affected (but could be applied on others):
- `get_menu_item_menu_leaf()`
- `menu_item_loop_header()`
- `menu_item_loop_open_element()`
- `get_menu_item_loop_markup()`

**Can you explain why these methods were set as private?**
**Can these be reverted back to public scope?**

### Other information

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

There seems to be no way for me to "fix" this issue via the theme as I would have to rewrite more methods in the class just because I have to introduce my custom methods replacing the private originals. It does not seem the correct way as I would basically duplicate a lot of code unnecessary.

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
This PR should fix #25077

#### Changes proposed in this Pull Request:

* All private functions have been changed to public.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* I've not been able to replicate issues and therefore check fixes as of yet, however testing the [Auberge theme](https://en-gb.wordpress.org/themes/auberge/) to make sure any of the extended functions work as expected would be the best way to test this.

### CODE REVIEW

**Comment by kraftbj** [comment]
@webmandesign Could you confirm this PR would resolve the issue for your theme? Thank you for the report!

**Comment by webmandesign** [comment]
> @webmandesign Could you confirm this PR would resolve the issue for your theme? Thank you for the report!

I can confirm everything works perfectly now!

That was amazingly fast, guys. Thank you very much @coder-karen and @kraftbj

**Review by kraftbj — APPROVED** [review]
I think this would be safe for the point release if you're open to it @coder-karen

**Comment by coder-karen** [comment]
Cherry-picked to release branch in a6213aa96eac3885d1a464a13021a7d58f0de5b9

**Comment by coder-karen** [comment]
r249092-wpcom

**Pull request merged**
