### PR TITLE
WordPress.com Block Editor: disable if blocks are disabled

### LINKED ISSUE #18958: Disabling JP Gutenberg does not Disable all JP Gutenberg features
#### Steps to reproduce the issue

1. Add the following to a theme or plugin: `add_filter( 'jetpack_gutenberg', '__return_false' );`
2. Load the block editor
3. Inspect the registered formats and the formatting toolbar

#### What I expected

I expected that disabling jetpack gutenberg features would disable jetpack gutenberg featurees

#### What happened instead

Blocks were disabled but formats were not. `wpcom/justify` and `wpcom/underline` remained, in addition to the wp.com block editor library and module. I did not enable this in settings, and it's served from a remote server too. In particular `wpcom-block-editor-default-editor-script` is enqueued, it should not have been enqueued.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #18958

#### Changes proposed in this Pull Request:

* One can use the `jetpack_gutenberg` filter to disable all Jetpack blocks at once. When you do so, you should not expect any other Jetpack block editor enhancements from being loaded on the site.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* On a site that's connected to WordPress.com, load the block editor.
* You should see `https://widgets.wp.com/wpcom-block-editor/default.editor.min.js` being loaded. You should also see the Jetpack blocks available.
* Add `add_filter( 'jetpack_gutenberg', '__return_false' );` somewhere on your site.
* Refresh the editor.
* No Jetpack blocks should appear, and the file above should not be loaded anymore.

#### Proposed changelog entry for your changes:

* WordPress.com Block Editor: disable if all Jetpack blocks are disabled via a filter.

### CODE REVIEW

**Review by leogermani — COMMENTED** [review]
Hi Jeremy,

I've tested it and the blocks are gone from the UI, but the script is still being loaded. See screenshots

Without the Filter:
Captura de Tela 2021-03-02 às 10 25 03

With the Filter
Captura de Tela 2021-03-02 às 10 25 40

Apparently, the reason for that is that the `Jetpack_WPCOM_Block_Editor` is initialized too early, before everything is loaded (I've added the hook on my theme's `function.php`).

One solution for that is to make all the hooks in this class to be added only after `init`, instead of right at `__construct`. What do you think?

https://github.com/Automattic/jetpack/blob/update%2Fwpcom-block-editor-shortcircuit/projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L604

**Comment by jeherve** [comment]
> I've added the hook on my theme's function.php

Ah right, I had tested from a plugin.

> One solution for that is to make all the hooks in this class to be added only after init, instead of right at __construct. What do you think?

I suppose we could try that, but that doesn't seem to be a pattern we usually follow in other parts of Jetpack. Would it be okay to instead encourage folks to not edit their theme to customize plugins' behaviour?

**Comment by anomiex** [comment]
> Would it be okay to instead encourage folks to not edit their theme to customize plugins' behaviour?

That would make sense to me, but I don't know that much about it.

Anyway, this needs a master merge for changelogger now.

**Comment by leogermani** [comment]
> > One solution for that is to make all the hooks in this class to be added only after init, instead of right at __construct. What do you think?
> 
> I suppose we could try that, but that doesn't seem to be a pattern we usually follow in other parts of Jetpack. Would it be okay to instead encourage folks to not edit their theme to customize plugins' behaviour?

It won't solve the issue. We don't have full control over the order the plugins are loaded, so if we leave it as it is now, it can happen that a filter added by another plugin will run too late, just as it happened to me using the theme's `functions.php`.

That's why anything that happens in a plugin and can be modified by other plugins should be triggered at some hook, and not directly as the file is loaded, so we can control the order things happen by modifying the hook priority.

**Comment by jeherve** [comment]
@leogermani Is this what you had in mind?
f43ed67a050a483097bfbfae137348ae2185b48e

**Review by leogermani — APPROVED** [review]
Yep! Tests well for me now and we are sure that this will work no matter where the filter is added (a plugin or a theme)

There was one failing test that required a refresh with master, I did but it's still failing

**Pull request merged**
