### PR TITLE
Revise upgrade banner text

### PR DESCRIPTION
**Pull request by MichaelArestad**
I update little bits of text. Nothing drastic. Let's discuss and see if we can't refine the strings available while @zinigor adds the missing banners. Either update our shared doc and ping me or comment/commit to this PR. Thanks!

We're missing:

- [x] one spam filtering banners
- [x] one ads banner
- [x] one premium video banner (maybe set it off when space is running out?)

CC @richardmuscat @ashleighaxios @rickybanister @zinigor

### CODE REVIEW

**Comment by rickybanister** [comment]
Good changes, merge it!

**Comment by rickybanister** [comment]
Can we just get this merged and move those three to-dos into an issue?

**Comment by MichaelArestad** [comment]
@rickybanister I believe @ashleighaxios made changes to the doc (easier to collaborate) that one of our JP devs can implement in this PR. @eliorivero or @dereksmart are you up for it?

**Comment by eliorivero** [comment]
@MichaelArestad I can do it. Ping me the doc in slack

**Comment by MichaelArestad** [comment]
@eliorivero I made one minor change. I think it's good to go.

**Comment by eliorivero** [comment]
Added banner for Akismet.

**Pull request merged**
