### PR TITLE
Contact Form: Revised the email validation regex to include length limit

### LINKED ISSUE #3734: Contact Form: Email validation regex needs updating
A sharp-eyed user has noticed that the email validation regex here:

https://github.com/Automattic/jetpack/blob/4.0.2/modules/contact-form/js/grunion.js#L502

... no longer matches the one specified here:

http://www.regular-expressions.info/email.html

Perhaps we should update? This also applies to WP.com's version of `grunion.js`.

2635373-t

### PR DESCRIPTION
**Pull request by stevenlin-x**
Fixes #3734

#### Changes proposed in this Pull Request:

* Revised the email validation regex to include length limit, in order to match the latest practical implementation of RFC 5322 in [regular-expressions.info/email.html](https://www.regular-expressions.info/email.html).

* Regex used:

PHP version: the very bottom one on [regular-expressions.info/email.html](https://www.regular-expressions.info/email.html). The one after the sentence "...modern regex flavors aren't truly regular, so we can add length limit checks using lookahead like we did before:" Take note, the redundant pink-colored white spaces in the middle of the regex must be removed.

```
\A(?=[a-z0-9@.!#$%&'*+/=?^_`{|}~-]{6,254}\z)(?=[a-z0-9.!#$%&'*+/=?^_`{|}~-]{1,64}@)[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:(?=[a-z0-9-]{1,63}\.)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+(?=[a-z0-9-]{1,63}\z)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\z
```
JavaScript version:

```
^(?=[a-z0-9@.!#$%&'*+/=?^_\`{|}~-]{6,254}$)(?=[a-z0-9.!#$%&'*+/=?^_\`{|}~-]{1,64}@)[a-z0-9!#$%&'*+/=?^_\`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_\`{|}~-]+)*@(?:(?=[a-z0-9-]{1,63}\.)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+(?=[a-z0-9-]{1,63}$)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$
```

#### Testing instructions:

1.) Checkout the code in this PR on a test WP site.
2.) Use the Contact Form and enter some test data in each field.
3.) In the email field, test different email addresses that are expected to pass and fail.
4.) Use an email you've access to, submit the form and make sure you get the email.
5.) Revert the code back to its previous state.

#### Proposed changelog entry for your changes:
* Contact Form: Revised the email validation regex to include length limit.

### CODE REVIEW

**Comment by stevenlin-x** [comment]
I think I got what was causing the issues. The regex was correct but two things must be done to apply it to javascript, due to regex flavors:

1.) The `\A` and `\z` must be either be replaced (with caret `^` and dollar `$`) or removed (if the subject string is the email string) since javascript does not support `\A` and `\z`, but only `^` and `$`.

   For the previous regex on the website, there were only `\A` and `\z` at the beginning and end.

   Unlike the previous regex, the latest regex version not only has `\A` and `\z` in the beginning and end, but also `\z` in the middle (due to lookahead). In my previous commit, I only removed `\A` and `\z` in the beginning and end, but not all the `\z` the middle.

2.) The white spaces in the middle of regex must also be removed, which was part of web page layout. In the previous regex, there were no white space that need to be removed.


I've push a new commit with the revised regex.

=====

Tests:

user@example.com
https://regex101.com/r/sGpumM/1

local part (64 char.):
https://regex101.com/r/AZTNg9/1
expected: pass
result: pass

local part (65 char.):
https://regex101.com/r/AZTNg9/2
expected: fail
result: fail

part of domain (63 char.):
https://regex101.com/r/AZTNg9/3
expected: pass
result: pass

part of domain (64 char.):
https://regex101.com/r/AZTNg9/4
expected: fail
result: fail

total length (254 char.):
https://regex101.com/r/AZTNg9/5
expected: pass
result: pass

https://regex101.com/r/AZTNg9/6
expected: fail
result: fail

**Comment by oskosk** [comment]
@stevenlin-x can you please clarify in this PR's description which expression is the one you're taking as appropriate from https://www.regular-expressions.info/email.html and then, right next to it, the JS version you're implementing.

Some time has passed and there's a lot of regex translation happening

**Comment by stevenlin-x** [comment]
@oskosk

I've added the regex of both PHP and JS versions to the ticket description.

**Comment by brbrr** [comment]
I played a bit with this PR. I made a simple jsFiddle with some valid and invalid emails according to https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses and http://codefool.tumblr.com/post/15288874550/list-of-valid-and-invalid-email-addresses

https://jsfiddle.net/f9dkotb8/1/

Here are the results:
```
====================
Testing valid emails
====================
email@example.com isValid: true
firstname.lastname@example.com isValid: true
email@subdomain.example.com isValid: true
firstname+lastname@example.com isValid: true
email@123.123.123.123 isValid: true
email@[123.123.123.123] isValid: **false**
"email"@example.com isValid: false
1234567890@example.com isValid: true
email@example-one.com isValid: true
_______@example.com isValid: true
email@example.name isValid: true
email@example.museum isValid: true
email@example.co.jp isValid: true
firstname-lastname@example.com isValid: true
much."more unusual"@example.com isValid: **false**
very.unusual."@".unusual.com@example.com isValid: **false**
very."(),:;<>[]".VERY."very@\\\ "very".unusual@strange.example.com isValid: **false**

====================
Testing invalid emails
====================
plainaddress isValid: false
#@%^%#$@#$@#.com isValid: false
@example.com isValid: false
Joe Smith <email@example.com> isValid: false
email.example.com isValid: false
email@example@example.com isValid: false
.email@example.com isValid: false
email.@example.com isValid: false
email..email@example.com isValid: false
あいうえお@example.com isValid: false
email@example.com (Joe Smith) isValid: false
email@example isValid: false
email@-example.com isValid: false
email@example.web isValid: **true**
email@111.222.333.44444 isValid: **true**
email@example..com isValid: false
Abc..123@example.com isValid: false
"(),:;<>[]@example.com isValid: false
just"not"right@example.com isValid: false
this is"really"not\\allowed@example.com isValid: false
```

@stevenlin-x do you think we should cover these failing cases too?

**Comment by brbrr** [comment]
FWIW: I looked into ways to cover this change with unit-tests. Unfortunately, it's not easy(or even possible) to write tests for a specific function for this file due to its structure. We might want to refactor it to make sure every function is testable.

**Comment by stevenlin-x** [comment]
@brbrr 

1.)
In the code samples you provided above, I replaced the regex with the original regex (i.e. the present regex in use in production). It also run into false positives with those valid and invalid emails samples.

2.)
I'm no regex expert by any means. The author of regular-expressions.info is much more than I do.

The present regex in use was derived from
regular-expressions.info/email.html

Issue #3734 pointed out the regex no longer matches the one on the updated page.

So I was merely reflecting the update for character length limits.

3.)
If you think those samples should be addressed, is it possible that you open a separate ticket and provide the reasons on why those samples should be addressed? Or even better, provide the regex you would use.

**Pull request merged**
