### PR TITLE
License Activation Notice: fix issue in license activation notice that appears even after being dismissed

### PR DESCRIPTION
**Pull request by yashwin**
Fixes 1202619025189113-as-1202655518335358

#### Changes proposed in this Pull Request:

It fixes an issue in the user license activation notice banner that appears even after being dismissed.

#### Other information:

- [x] ~~Have you written new tests for your changes, if applicable?~~
- [x] Have you checked the E2E test CI results and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

**No**

#### Testing instructions:

1. Set up a new test site using JN with this branch.
2. Visit the newly created site -> Click on **Jetpack** nav item -> Activate Jetpack.
3. Go to https://jetpack.com/ and buy any product and skip the site selection.
4. Now, go to your site -> Jetpack(refresh if you are on the same page), and you should see the activation notice with the message `Activate <PRODUCT_NAME> ...`
5. Now dismiss the notice by clicking on the `X` icon on the notice and verify that the notice doesn't appear again

Example notice

Screenshot 2022-07-26 at 5 18 54 PM

> **_NOTE:_**  This issue is caused by merging [Show product name on activation notice](https://github.com/Automattic/jetpack/pull/23409.) The expected behavior is to hide the notice banner when a user activates a license until a new license is issued; check [Display notice when a user has unactivated product license keys](https://github.com/Automattic/jetpack/pull/21474) for more details.

### CODE REVIEW

**Comment by coder-karen** [comment]
@yashwin I'll be cutting the Beta for Jetpack 11.2 in half an hour - is the intention to have this in the Jetpack 11.2 release?

**Comment by yashwin** [comment]
> @yashwin I'll be cutting the Beta for Jetpack 11.2 in half an hour - is the intention to have this in the Jetpack 11.2 release?

@coder-karen Not really, I would like to release this as early as possible. I have removed the milestone for now.

**Review by rcanepa — DISMISSED** [review]
LGTM.

Everything worked as expected, and I couldn't find any regression.

**Review by rcanepa — APPROVED** [review]
LGTM again since nothing changed in terms of logic.

**Review by sdixon194 — APPROVED** [review]
👍

**Comment by yashwin** [comment]
@sdixon194 - Is it ok if I go ahead and merge this?

**Comment by sdixon194** [comment]
>  Is it ok if I go ahead and merge this?

Oh yeah! Anytime it has the `Ready to Merge` label and the approval, you can merge whenever you're ready!

The PR was out of date now, so I just merged with trunk. Assuming all the CI checks pass you can merge when it's done 👍

**Pull request merged**
