### PR TITLE
Removing box-sizing:border-box from Base Styles

### LINKED ISSUE #27622: Customizer: Theme name fields are cropped
### Impacted plugin

Jetpack, None / Other

### Steps to Reproduce

Using a classic theme, without support for the Site Editor;

- Visit the customzier
- Click to change your current theme
- Observe the theme names being cut short

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Browser

_No response_

### Other information

Image showing the title section of themes being smaller than intended
A screenshot indicating the shortened theme name fields.

The cause is the following style implemented by `jetpack/_inc/blocks/editor.css`;

```
* {
    box-sizing: border-box
}
```

This only impacts the theme selector within the Customizer, the standalone Themes screen is not showing this behavior.

### Platform (Simple, Atomic, or both?)

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes #27622

#### Changes proposed in this Pull Request:

* This PR removes the `box-sizing: border-box;` CSS which exists in `js-packages/base-styles/style.scss`. The style was added one year ago, initially via [this PR](https://github.com/Automattic/jetpack/pull/21730), but the styling side effect it caused was only spotted a few months ago when the base-styles were imported into `jetpack/extensions/index.scss` [here](https://github.com/Automattic/jetpack/pull/25852).
* The primary observable issue it caused was that theme names were cropped in the Customizer when browsing installed themes (see the linked issue).

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

Slack: p1669287540640319-slack-CDLH4C1UZ

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* To test without this PR applied, visit the Customizer on a site - `wp-admin/customize.php` - then click Change to change the active theme. The result should show the theme names cropped.
* Then apply this PR to a test site connected to Jetpack, and visit the same Customizer themes page. No theme names should be cropped.
* The base styles are also imported in several other places, namely connection / disconnection dialogs, IDC error messaging,  icon tooltip components, pricing card components, VideoPress chapter modals in particular. It would be worth taking a look at any of these features where possible to make sure styling hasn't been affected.

Before applying the PR:

Screen Shot 2022-12-20 at 4 09 40 pm

After applying the PR:

Screen Shot 2022-12-20 at 4 14 23 pm

### CODE REVIEW

**Comment by anomiex** [comment]
FYI, we got a second bug report about the issue this PR is fixing at #28038.

**Review by anomiex — DISMISSED** [review]
It seems like the presence of this styling is breaking more than it fixes. I'll hit "approve" on this, and someone can do a followup adding a more specific styling if they determine someplace where it's needed.

**Review by anomiex — APPROVED** [review]

**Comment by coder-karen** [comment]
> someone can do a followup adding a more specific styling if they determine someplace where it's needed.

Good idea.

I've confirmed removing this box-sizing also fixes the Gutenberg reading time issue, and have tested several other features which may be affected by the base styles changing (where those base styles are imported), where possible, covered in the testing instructions. I'll merge this.

**Comment by simison** [comment]
Excellent! Thanks for fixing this.

If I may suggest next steps, something along these would be great:

- Separate CSS colour variables into their own file. That way they can be imported only where they are needed without pulling in extra CSS, e.g. in [this file](https://github.com/Automattic/jetpack/pull/28039) which depends on a single colour variable only.
- Separate Sass mixins into their own file; same as above, then one can import only mixins if only those are needed.
- Find if CSS rules affecting `body` tag directly can be removed, or if those rules should moved into CSS selector unique to Jetpack. If they're needed in multiple places, consider turning it into mixin.
- Move rest of the CSS selectors (`jp-wrap` etc) to their own file, or directly be with JS component or somewhere where its clear where they are used, what they do, and only get imported when meant to be imported.
- Further down the road I suggest exploring use of [`@use`](https://sass-lang.com/documentation/at-rules/use) as it avoids loading e.g. colour variables multiple times, and ensures they get loaded just once. Improves devex and performance. :-)

Thanks again!

**Comment by anomiex** [comment]
You're welcome to contribute PRs to help modernize our styles!

> Further down the road I suggest exploring use of [`@use`](https://sass-lang.com/documentation/at-rules/use) as it avoids loading e.g. colour variables multiple times, and ensures they get loaded just once. Improves devex and performance. :-)

I think at the moment that that doesn't matter for color variables (but does for other CSS in there), since [our use](https://github.com/Automattic/jetpack/blob/dc53a7bd748112d5922c5775e27337fd711d8070/projects/plugins/jetpack/tools/postcss.config.js#L3-L16) of [postcss-custom-properties](https://www.npmjs.com/package/postcss-custom-properties) with `preserve: false` means the color variables get stripped from the bundle anyway. For example, I see [_inc/blocks/editor.css](https://github.com/Automattic/jetpack-production/blob/trunk/_inc/blocks/editor.css) that is built from the file you pointed to doesn't contain any of the color variables imported from the package, although it does contain two copies of some of the other rules.

Also I note `@use` won't help with the fact that every separate bundle using the style would still be embedding a copy of the shared stuff (and someday we really should split that giant "editor" bundle to use [the modern block registration mechanism](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/)). What we probably need to do is to have [@wordpress/dependency-extraction-webpack-plugin](https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin) extract references to the package providing the color variables and shared CSS, so all that can be loaded just once via WordPress's dependency mechanism instead of being part of every bundle.

**Comment by simison** [comment]
>I think at the moment that that doesn't matter for color variables (but does for other CSS in there), since [our use](https://github.com/Automattic/jetpack/blob/dc53a7bd748112d5922c5775e27337fd711d8070/projects/plugins/jetpack/tools/postcss.config.js#L3-L16) of [postcss-custom-properties](https://www.npmjs.com/package/postcss-custom-properties) with preserve: false


The problem is reverse; now there's [extra CSS](https://github.com/Automattic/jetpack/blob/d3fe8d6103b6bff2f263bddb1ca4efddeee7f620/projects/js-packages/base-styles/style.scss#L86-L196), some of it very generic (`body`), that gets included even if one only intends to import colours.

Pretty sure CSS applied to the generic `body` just by enabling Jetpack blocks will come back hit us dome day, too.

> You're welcome to contribute PRs to help modernize our styles!

I'd love to help improve this myself but I'm just about to leave for sabbatical so won't have time currently. Hence just documenting some thoughts — hope this helps!

**Pull request merged**
