### PR TITLE
add query_vars to visibility widget option

### PR DESCRIPTION
**Pull request by drrobotnik**
Add additional option input to the visibility widget. Use case: I'd like this promo text widget to be hidden if the lang query_var is set.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Hey @drrobotnik -- sorry this has gone so long without action.  If you're interested in rebasing, we can reopen and look at getting this in, I'll close for now, but feel free to update.

**Comment by drrobotnik** [comment]
Hi Sam, I'm interested. I'm in the middle of a non-open source project so it might take me a little time to get back at this.

**Comment by samhotchkiss** [comment]
No worries!

**Comment by jeherve** [comment]
#5781

**Comment by zinigor** [comment]
Rebasing in progress...

**Comment by zinigor** [comment]
Closing in favour of #6330

**Pull request closed without merging**
