### PR TITLE
Add broadcast channel listener to ensure login messages are received

### PR DESCRIPTION
**Pull request by heavyweight**
This PR sets up verbum to listen to the broadcasting channel created here: D138915-code
Users with passwordless login can open the login link in a new tab, and in this case `parent.opener` is not available and we can't post the verbum message.
The listener on the channel reuses the same logic as before, but now we ensure that the popup we open for login is always closed after the message is received.

Fixes #

## Proposed changes:

* Listen to the broadcast channel

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sync this PR
* Sync D138915-code as well
* Open a post and login with passwordless user
* The login popup should be closed, and the user successfully logged in.
* Test the login by clicking on the email link and by pasting the link in a new tab.

### CODE REVIEW

**Comment by agrullon95** [comment]
Changes are working well on Simple Site, but theyre not working on my atomic site. The popup login window doesn't receive the broadcastChannel message, so it doesn't properly login until I refresh.

**Comment by renancarvalho** [comment]
@heavyweight same as Anthony wrote, it did work well on simple sites but did not work on my atomic, could it be related to the site origin? I read that it can only communicate between browsing contexts with the same origin. Since Jetpack is playing on atomic, it might be the issue.

**Comment by heavyweight** [comment]
Agh nice catch! It has issues on atomic.
Will looks for a fix.

**Review by agrullon95 — APPROVED** [review]
Lets merge and add solution for Atomic sites in another PR

**Comment by simison** [comment]
> Changes are working well on Simple Site, but theyre not working on my atomic site. The popup login window doesn't receive the broadcastChannel message, so it doesn't properly login until I refresh.

Could be also an issue for simple sites with custom domains?

**Comment by heavyweight** [comment]
> > Changes are working well on Simple Site, but theyre not working on my atomic site. The popup login window doesn't receive the broadcastChannel message, so it doesn't properly login until I refresh.
> 
> Could be also an issue for simple sites with custom domains?

Hi and sorry for the late reply, we've been busy with sso user changes.
Unfortunately, there is still a problem with simple + custom domain. After the remote login, the connect redirect goes to https://TheFreeSite.wordpress.com/public.api/connect/?action=verify&service=wordpress&domain=ThePaidDomain.com.
Which in turn will redirect to the proper domain. Since the domains are different the broadcast channel will not work. 
Will look for a fix for this.

**Pull request merged**
