### PR TITLE
WIP - Use register_settings for Social options

### PR DESCRIPTION
**Pull request by pablinos**
## Proposed changes:
This is on experiment to see if we can use register_setting in order to utilise the core functions and rest endpoints.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by pablinos** [comment]
image


Using this we can call the core endpoint to get the settings in one go. The code to update the settings is untested, but in principle it should work.

I don't understand the current format of the SIG settings. There's a defaults array, but all the settings are the defaults, so that doesn't seem to make sense to me. I've flattened it for now, but that would mean we would need to migrate the SIG settings too

Similarly, I think we should simplify the auto conversion settings. I don't know when we're going to do videos, and we're future proofing in a way that just adds maintenance. I think just having a boolean makes things simpler.

**Comment by gmjuhasz** [comment]
I tested this, but it gives me unknown route:
CleanShot 2023-11-10 at 13 30 05 png

On the https://developer.wordpress.com/docs/api/console/ it was working with `wp/w2/sites/<siteid>/settings`.

Also I know it's WIP, but so far I see some errors if I try to load my site because of some format issues with the initial state. I'm trying to find a place for this action where it could be registered on simple sites too, then we could just use the same w2 API to get and update the settings for WPCOM site

**Comment by pablinos** [comment]
> I tested this, but it gives me unknown route:

I think that's because the route is wrong. It should be v2 not w2

> On the https://developer.wordpress.com/docs/api/console/ it was working with wp/w2/sites/<siteid>/settings.

Yes, on simple sites the route changes to having the /sites/<site id>/ part of the path. We cope with that by passing the URL in the initial state for the other endpoints. We might be able to make it more generic by passing an API base URL or something similar.

> Also I know it's WIP, but so far I see some errors if I try to load my site because of some format issues with the initial state.

Yeah it's definitely not in a working state, I was trying to prove concept with using register_setting and the core endpoints, which I think is possible. My main concern is register the settings based on the feature being available, and whether the feature checks might end up being too expensive to be run during `rest_api_init`. If it hits the database, I think that could be a problem.

**Comment by pablinos** [comment]
@gmjuhasz I think this has been superseded by work we've done since. Is that right?

**Comment by gmjuhasz** [comment]
> @gmjuhasz I think this has been superseded by work we've done since. Is that right?

Yes, looking at Pulicize setup, we already do this.

fbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scnpxntrf%2Schoyvpvmr%2Sfep%2Spynff%2Qchoyvpvmr%2Qfrghc.cuc%3Se%3Q24s18726-og

**Pull request closed without merging**
