### PR TITLE
WPCOM API: Fix incompatible method signature in json endpoints inheriting from the update endpoint

### LINKED ISSUE #8186: Sync: Fatal error on PHP 7.2RC coming from WPCOM_JSON_API_Bulk_Delete_Post_Endpoint::callback
Declaration of `WPCOM_JSON_API_Bulk_Delete_Post_Endpoint::callback` is not compatible with ` WPCOM_JSON_API_Update_Post_v1_1_Endpoint::callback`.

#### Steps to reproduce the issue

* Get to Calypso and try to run a full sync for a site running on PHP 7.2

#### What I expected

* No fatal in the site.

#### What happened instead
* Logs on the site show this Fatal error
  ```
    Declaration of WPCOM_JSON_API_Bulk_Delete_Post_Endpoint::callback($path = '', $blog_id = 0) must be compatible with WPCOM_JSON_API_Update_Post_v1_1_Endpoint::callback($path = '', $blog_id = 0, $post_id = 0)
    Type: PHP Fatal error Line: 0
    File: json-endpoints/class.wpcom-json-api-bulk-delete-post-endpoint.php
  ```
* Calypso shows this warning  
image

### PR DESCRIPTION
**Pull request by oskosk**
Updates the signature for the `callback()` method overriden by these classes.

Fixes #8186

#### Changes proposed in this Pull Request:

Modifies the following endpoints to have the same signature as the update endpoint for their `calback()` method.

* Bulk Restore Endpoint
* Bulk Delete Endpoint
* Active Theme endpoint
* Check compatibility endpoint

#### Testing instructions:

1. Start with a site running on PHP 7.2RC and Jetpack connected...
1. Get to calypso and try to run a full sync from [Settings/General/Manage Connection](https://wordpress.com/settings/manage-connection).
1. Verify you get an error.
1. Repeat after checking out this PR (Can be done easily by using the [Jetpack Beta Tester Plugin](github.com/Automattic/jetpack-beta))
1. Confirm that triggering he full sync works and you get no errors.

#### Before

image

#### After

image

image

image

### CODE REVIEW

**Comment by oskosk** [comment]
@roccotripaldi, for reference, The changes here first tackled only one file as #8205  does, but then going to calypso and triggering a full sync, showed that there was another file doing the same, and so on until I got calypso to not error after modifying these four signatures and could see the Full sync happening without loggin any errors on the Jetpack site.

**Comment by enejb** [comment]
Instead of using `$post_id = 0` can we set it to `$object_id = null`? 
See https://github.com/Automattic/jetpack/blob/764a699120ca6795dac3d264207713516200ee7b/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php#L15

**Comment by oskosk** [comment]
Renamed to `$object_id` in 28169ed

**Comment by oskosk** [comment]
I'm not sure if `null` will work here as a default. I'm going to check now.

**Comment by oskosk** [comment]
Renamed to `$object` and defalting to `null` in 9a877c7

**Comment by enejb** [comment]
Works as expected for me :shipit:

**Pull request merged**
