### PR TITLE
Calendly Block: Add edit button to block toolbar

### LINKED ISSUE #15357: Calendly: add Edit button toolbar
#### Steps to reproduce the issue

1. Create a calendly block
2. Try to change the address it points to from the block itself.
3. Ya can't

#### What I expected

To be able to change the address (in this case, the URL of my event page had been changed)

#### What happened instead

Ya can't.

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes #15357

#### Changes proposed in this Pull Request:
* Adds an Edit button to the Calendly block toolbar
* Fixes width of form field in Calendly block's placeholder form

#### Does this pull request change what data or activity we track or use?
No changes.

#### Testing instructions:
* Edit a post adding a Calendly block
* Apply this PR
* Confirm existing Calendly block functions as expected and toolbar has new Edit button
* Add a new Calendly block and then edit that block's Calendly URL or embed code
* Ensure block updates appropriately

#### Before

Screen Shot 2020-08-11 at 1 36 13 pm

#### After

Calendly-EditButton

#### Proposed changelog entry for your changes:
* Calendly Block: Add edit button to toolbar

### CODE REVIEW

**Comment by glendaviesnz** [comment]
Tested well for me with an existing block and adding a new one.

**Comment by jeherve** [comment]
@aaronrobertshaw Do you think you could commit the matching wpcom diff for this change?

Thank you!

**Comment by aaronrobertshaw** [comment]
@jeherve That diff has just been approved and merged. Thanks 🙂

**Comment by jeherve** [comment]
r212332-wpcom

**Pull request merged**
