### PR TITLE
My Jetpack: Allow  rendering for non-admins

### PR DESCRIPTION
**Pull request by oskosk**
## Proposed changes:

This PR refines user permission handling across various aspects of My Jetpack, ranging from endpoint permissions to UI rendering for different user roles.

The minimum requirement is to be a contributor (able to write but not publish).

**Note: these links don't work. They should be addressed in a follow-up PR**

image

<table>
<tr>
 <td>image
 <td> image
<tr>
 <td>Admin
 <td>Non-admin
</table>

**Commits' details**

* Allows **My Jetpack** menu item rendering for non-admins.
* Update permission callback on purchases endpoint to edit_posts.
* Make it so we don't render the plans section footer with manage and purchase links if the user is not an admin.
* Forwards a useIsAdmin variable to the frontend.

links to more information are shown and these links do not work. Will be tackled in another PR
### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* p1691616562377759/1691614027.240459-slack-C01U2KGS2PQ
* p1HpG7-o03-p2#comment-65305

## Does this pull request change what data or activity we track or use?
Doesn't add new events, but starts tracking activity on the My Jetpack page for authors, editors and contributors

## Testing instructions:

* Connect the site as an admin
* Create a user with role Contributor
* Run this branch, and visit wp-admin
* Confirm the Jetpack -> My Jetpack menu item is shown
* COnfirm that visiting it works
* Confirm the plans section footer where links for managing or purchasing usually are, don't render for this user
* Confirm action buttons are not shown
* Confirm links to more information are shown and these links do not work. Will be tackled in another PR

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
Testing

* Create a user with role Contributor 🍏 
* Run this branch, and visit wp-admin 🍏
* Confirm the Jetpack -> My Jetpack menu item is shown 🍎 

image

I don't see the Menu. Is it because the site is not connected?

**Comment by oskosk** [comment]
@retrofox yes. The site needs to be connected first by the admin. I added that as a first step in the testing instructions now

**Review by retrofox — APPROVED** [review]
* Connect the site as an admin 🍏
* Create a user with role Contributor 🍏
* Run this branch, and visit wp-admin 🍏
* Confirm the Jetpack -> My Jetpack menu item is shown 🍏

image

* COnfirm that visiting it works 🍏

image

* Confirm the plans section footer where links for managing or purchasing usually are, don't render for this user 🍏

image

* Confirm action buttons are not shown 🍏 


* Confirm links to more information are shown and these links do not work. Will be tackled in another PR 🍏
I guess you refer to `Learn about...` links

**Review by renatoagds — APPROVED** [review]
LGTM

**Review by lhkowalski — APPROVED** [review]
Code looks good.

Before the change, the menu was invisible and accessing the direct link would show an error.

After the change:

- I can see the menu
Screenshot 2023-08-11 at 11 42 07

- The page works, shows the "Learn about ..." links and does not show the links on the plan info section at the bottom:

Screenshot 2023-08-11 at 11 50 45

**Comment by oskosk** [comment]
Thanks folks!

**Pull request merged**
