### PR TITLE
Social Logos: update to the most recent version of the package

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

This includes 2 things:

- Fixes to the X and Threads logos, to avoid invalid SVG warnings (see https://github.com/Automattic/social-logos/pull/127#discussion_r1356363587 ).
- An updated X logo to match updated branding guidelines (in practice, the logo is now aligned a bit differently on the grid).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

**Testing sharing buttons**

* Go to Jetpack > Settings > Social and enable sharing buttons.
* Go to Settings > Sharing and add some sharing buttons to your site. Use the icon-only sharing type.
* The buttons should look good in the admin preview, as well as on the frontend when your changes are saved. **Make sure all buttons look good, not just the X one.**

**Testing the post-publish modal**

* Create a new post and hit publish or for an existing post, run this in browser console
    - `wp.data.dispatch('core/edit-post').togglePublishSidebar();`
* On the post publish panel, confirm that you see the X icon; it should look good
* Confirm that it works as expected
* Open Jetpack sidebar
* Under "Share this post", click on the Quick Share icon
* Confirm that you see the X icon
* Confirm that you see no warnings in your JS console.

### CODE REVIEW

**Review by monsieur-z — COMMENTED** [review]
**Testing sharing buttons**

I don't know if that's related to this PR, but the Facebook blues on WordPress.com and in a post are different.
Screenshot 2023-10-13 at 3 29 05 PM
Screenshot 2023-10-13 at 3 30 05 PM

Definitely not related to this PR, so I could bring it up where appropriate: I find it odd that we use the white background Facebook and LinkedIn icons inside a blue circle, instead of using a white "f" or "in" as we do in `wordpress.com/marketing/connections/:site`.
Screenshot 2023-10-13 at 3 40 34 PM

**Testing the post-publish modal**
I could see the X icon in the post publish panel, and the feature works as expected. However I can't see a Quick share icon in the "Share this post" panel (with either a free or Social plan). What might I have missed?
Screenshot 2023-10-13 at 3 32 34 PM

**Comment by jeherve** [comment]
> the Facebook blues on WordPress.com and in a post are different.

This Calypso PR should help with that:

https://github.com/Automattic/wp-calypso/pull/83036

> I find it odd that we use the white background Facebook and LinkedIn icons inside a blue circle

This is due to the design of the sharing buttons. That's something we had discussed a bit in #15954. I think this is something we could address when we tackle #19694.

> I could see the X icon in the post publish panel, and the feature works as expected. However I can't see a Quick share icon in the "Share this post" panel (with either a free or Social plan). What might I have missed?

I'll leave that question to @manzoorwanijk, who is more familiar with the feature than me.

**Comment by manzoorwanijk** [comment]
> > I could see the X icon in the post publish panel, and the feature works as expected. However I can't see a Quick share icon in the "Share this post" panel (with either a free or Social plan). What might I have missed?
> 
> I'll leave that question to @manzoorwanijk, who is more familiar with the feature than me.

You need to click on this Share icon

Screenshot 2023-10-16 at 5 02 45 PM

May be it's not too obvious and can be improved, what do you think @Automattic/jetpack-reach & @ilonagl?

**Review by monsieur-z — APPROVED** [review]

**Comment by monsieur-z** [comment]
Thanks for the clarification @manzoorwanijk, I could test the rest of the instructions.

> May be it's not too obvious and can be improved

I think so too. The sharing icon doesn't look like it's activable and the buttons inside the panel call for attention.

Here are 2 points regarding accessibility, in case improving this is considered:
- A label next to the button is lacking. It is essential for screen reader users and generally useful for all users.
- 2 clickable areas should probably not overlap, at least when one of them is so small. Depending on the user's device and/or ability, the icon button may be hard to hit.

**Comment by manzoorwanijk** [comment]
Thank you @monsieur-z. I have created a task for the a11y improvements and it's linked above.

**Pull request merged**
