### PR TITLE
AI Assistant: Add disclaimer to image generation input

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #

## Proposed changes:

This is an attempt to address feedback, as some people get frustrated with text errors that are beyond the capability of current models and maybe they are expecting it to work perfectly.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to an image generation modal (logo, featured or general image)
* Check that the disclaimer is there
* Check that the links work as expected

You can also run Storybook locally with `( cd projects/js-packages/storybook && pnpm run storybook:dev --no-open --debug-webpack )` and visiting `http://localhost:50240/?path=/docs/js-packages-ai-client-aimodalfooter--docs`

Screenshot from 2024-12-03 20-00-22
Screenshot from 2024-12-03 19-58-59

### CODE REVIEW

**Review by CGastrell — DISMISSED** [review]
LGTM! Thanks! :shipit:

**Comment by ederrengifo** [comment]
About the positioning, let's try to use the bottom area with a message that is more contextual to the image generation. Here examples for the general image generation modal:

Frame 1000007785

And for the logo generation modal:

Frame 1000007786

cc @dhasilva

**Review by mwatson — DISMISSED** [review]
Disclaimer appears on all image generation modals 🚀

**Comment by ederrengifo** [comment]
@dhasilva LGTM! Just a minor thing, can we be sure the external icon we use is consistent with this one, for example?

Screenshot 2024-12-04 at 12 34 50

I'm not sure if we are using the same character there 🤔

**Pull request merged**
