### PR TITLE
Documentation: reorganize current docs and create new ones.

### PR DESCRIPTION
**Pull request by jeherve**
- Make contributing less frightening and easier for all potential contributors.
- Make our guidelines and requirements clearer.
- Surface all data in our contributing guide.
- Offer options to contribute to everyone, even if it's not via code.
- Outline our release management process, and approach to code reviews and Pull Requests.

### Still To do:

- [x] Review all links to make sure they're correct.
- [x] Proofread and catch typos.
- [ ] Create redirections from existing documentation.
- [ ] Remove documentation in the Wiki.

#### Proposed changelog entry for your changes:
- Documentation: refresh our contributing guide.

### CODE REVIEW

**Comment by coderkevin** [comment]
When I recently followed the directions from the main README, I got this:

```$ npm install -g yarn
npm WARN deprecated yarn@0.18.1: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install```

So it looks like we should change our docs to go to that install page instead of recommending an `npm install`. Would you mind adding that change to this PR so we can keep it all together?

Thanks!

**Comment by jeherve** [comment]
@coderkevin The problem is this makes it more difficult to install a specific version of Yarn; most of the native installers install the latest version by default.

@eliorivero What would you suggest?

**Comment by coderkevin** [comment]
Is it particularly bad if someone has a newer version of yarn? I would hope it would still work. I hope developers don't have to change versions of yarn just to build this if they already have a newer version installed for another project!

**Comment by eliorivero** [comment]
@coderkevin what was the instruction in the readme that gave you that warning? I don't have any warning and I'm running 0.17.9 which is what the doc suggests to install.

@jeherve let's stick to what we currently have in the doc. We've had some issues in the past with the newest versions and that's why we locked the version for now.

**Comment by jeherve** [comment]
Fixes #6236

**Comment by oskosk** [comment]
Awesome @jeherve. The new section for Unit Testing is great.!!!

Just an observation: at first I went for the **Files Changed** view of this PR and everything looked good.

I then, went to browse the repo's homepage for the `add/docs` branch just to check out how the content redistribution felt. And there, I found out that It took me some real time until I realized that access to everything development related was behind a small link reading `here`. 

image

I'd vote to keep the redistribution of the content, which I liked, but maybe adding an H2 that reads **Development** and inside that section, more or less the same sentence but, with the link text being a little more explanatory, and visible. Specially for people who's just trying to get back to the readme and grepping "develop..." just to remember how to run tests or build stuff. e.g.: me :trollface: .

Something like:

image

**Comment by jeherve** [comment]
@osk I like the idea! I've just made that that change. :+1:

**Comment by oskosk** [comment]
LGTM 🐑

**Pull request merged**
