### PR TITLE
Blocks: provide nice error message for workaround in dev env

### PR DESCRIPTION
**Pull request by kraftbj**
Without running `jetpack build plugins/jetpack`, we'd fatal in the post editor without a nice message. This is temporary ( #20357 ).

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by jeherve** [comment]
Do you have a bit more background on this issue, and what this PR addresses? I'm not quite sure I understand the relationship with the issue you linked to.

Thank you!

**Comment by kraftbj** [comment]
Sorry—it was a directly reported thing to me that folks with dev env will get a php fatal if they haven't built (recently) without a helpful error message on why things are broken, mentioning the difficult dev experience of running into that.

The relationship to the issue is just that whole code block is temporary for the note in the original code.

**Review by jeherve — APPROVED** [review]
This doesn't break anything for me. 🚢

**Comment by alshakero** [comment]
Thank you for this <3 The error message saved me a lot of trouble.

**Pull request merged**
