### PR TITLE
Sitemaps: lower the max bytes to less than 1Mb

### PR DESCRIPTION
**Pull request by eliorivero**
#### Changes proposed in this Pull Request:

* lower the maximum byte size to be strictly less than 1Mb

### CODE REVIEW

**Comment by dereksmart** [comment]
merged to 4.8 3935b36ce

**Comment by mjangda** [comment]
If we're basing the max on the [my note about memcached limits](https://github.com/Automattic/jetpack/pull/6821#issuecomment-290621723), going 1 byte lower won't help much since the full post object includes many other fields while the limit here only applied to the content field.

**Comment by dereksmart** [comment]
@mjangda what is the ideal limit you would like to see?

**Comment by mjangda** [comment]
I don't really have a good number. 600-700Kb is probably a safe bet.

We can probably make an more intelligent guess by estimating the average size of a sitemap entry, multiplying by `2000` (default max items) and adding some buffer for header/footer and additional data.

**Pull request merged**
