### PR TITLE
* My Jetpack: tweak plan sections box model

### PR DESCRIPTION
**Pull request by retrofox**
This PR tweaks the plans sections according to the feedback described here. For this purpose, I've created a couple of components to be reused in the whole UI of the app.

Fixes https://github.com/Automattic/jetpack/issues/23542

#### Changes proposed in this Pull Request:

* My Jetpack: tweak plan sections box model.

#### Testing instructions:

* With Storybook
* Check the heading components
* Confirm the margin values:
image

Screen Shot 2022-03-24 at 7 18 35 PM

image

* Testing with My Jetpack dashboard
image
* Confirm margins look right.

### CODE REVIEW

**Comment by oskosk** [comment]
@keoshi Can you help us identify how to handle this for making these two sections consistent. Here's how these end up looking after the chages to the plan text here 

image

**Comment by keoshi** [comment]
@oskosk Those two sections will not line up in most situations because the content is fundamentally different, but one thing that caught my eye that we could change pretty easily is using the same headline size from “Your plan(s)” in “Connection”.

Right now it seems a tad smaller, and with that change it should anchor the two sections at the top nicely.

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by oskosk** [comment]
@keoshi tracking that recommendation here # 23627 !

**Pull request merged**
