### PR TITLE
Search: fix modal close button has dark background in light mode (Twenty Twenty One theme)

### LINKED ISSUE #19693: Instant Search: modal close button has dark background in light mode (Twenty Twenty One theme)
#### Steps to reproduce the issue

1. Go to a site set up for Jetpack Search using the Twenty Twenty One theme.
2. Enter text in a search input to open the search modal.

#### What I expected
The close button matches the rest of the modal.

#### What happened instead
The close button looks too dark.

**Screenshots**

Screen Shot 2021-04-29 at 15 27 53

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #19693

#### Changes proposed in this Pull Request:
Override `background-color` for close button for just Twenty Twenty-One theme. 

Fixed two issues,
- The selector of original CSS to fix this doesn't work, as there's no parent `.theme-twentytwentyone` class
- Corrected the fix and moved it to theme-tools module, where Jetpack modules have style fixes for official themes that could be loaded per theme, meaning if it's not Twenty Twenty-One theme, the fix wouldn't be load at all.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to a website with Jetpack Search subscription and Twenty Twenty-One theme enabled
- In customizer, set search overly colour to light
- Ensure the close button background is light but not dark
image

### CODE REVIEW

**Comment by bluefuton** [comment]
> The selector of original CSS to fix this doesn't work, as there's no parent .theme-twentytwentyone class

Good spot! 👍 

Do other themes no longer have the `theme-` parent class? I notice we rely on it in other places in our stylesheet, like `theme-argent` for the Argent theme (from https://github.com/Automattic/jetpack/pull/18852/files).

**Review by jsnmoon — COMMENTED** [review]
Excellent sleuthing, @kangzj. I like how this solution reuses an existing mechanism already built into Jetpack (that I hadn't even heard of before...)

@bluefuton's question does raise an issue, however. I don't think Jetpack's `theme-tools` has any `compat` definition for Argent; in other words, we may need to write our own to properly support Argent in the future. We will likely need to repeat this for any other themes we'd like to tweak in the future.

To avoid the above scenario, I wonder if it might be easier for us to just go ahead and inject the theme name into the body? It should be possible to do so by doing something like:

```php
add_filter( 'body_class', 'some_function' );

function some_function() {
	return 'jps-theme-' . get_stylesheet();
}
```

What do you think?

**Comment by kangzj** [comment]
> Do other themes no longer have the `theme-` parent class? I notice we rely on it in other places in our stylesheet, like `theme-argent` for the Argent theme (from https://github.com/Automattic/jetpack/pull/18852/files). 

Thanks @bluefuton 
I don't think these are working anymore. We'll need to fix these as well.

>To avoid the above scenario, I wonder if it might be easier for us to just go ahead and inject the theme name into the body?  

Thanks @jsnmoon. I think this totally works as an immediate fix for the problem we have now and which would have minimal side effects. I'll do that in this pull request.

However, I think it's better to put fix-up code for themes in separate modules/files, i.e. not in our main style sheets, because of their nature, they don't belong to our product, they change all the time. This is something we might want to look at in the future.

**Comment by bluefuton** [comment]
Just spotted that the Barnsbury theme has the same problem. Perhaps we should just override the theme color in all cases for the close button?

**Comment by kangzj** [comment]
> Just spotted that the Barnsbury theme has the same problem. Perhaps we should just override the theme color in all cases for the close button?

Added forced background color styling for the close button in https://github.com/Automattic/jetpack/pull/19874/commits/c55173519570a209e74e7826b04ef78c1536c832

**Review by jsnmoon — APPROVED** [review]
Merged master and updated changelog for accuracy. 

Ship it!

**Comment by kangzj** [comment]
Thanks @jsnmoon 
🚢  Shipped in r226174-wpcom

**Pull request merged**
