### PR TITLE
Flickr Widget: do not display widget table when there are no images

### PR DESCRIPTION
**Pull request by jeherve**
Instead, we will display a warning message to site admins to let them know
their widget doesn't work properly.

#### Testing instructions:

Try entering a Flickr Feed URL where all images are marked as private ([example](https://href.li/?https://api.flickr.com/services/feeds/photos_public.gne?id=154104018@N06&lang=en-us&format=rss_200)).

Here is how it currently looks:

screen shot 2017-04-28 at 14 23 35
(the link redirects to Flickr but no images are displayed there)

Here is how it looks for admins with this PR:

screen shot 2017-04-28 at 14 19 56

Reported here:
p8oabR-2x-p2

### CODE REVIEW

**Comment by dereksmart** [comment]
Code looks fine but what do you think about adding an "Only you can see this" type of message as well?

**Comment by jeherve** [comment]
That makes sense. How should I phrase it?

**Comment by dereksmart** [comment]
@jeherve how about just appending `(Only admins can see this message)` on a new line?

**Comment by jeherve** [comment]
@dereksmart How does e52310397004ce77c2a80355d7c88b3d965357bf look?

**Comment by eliorivero** [comment]
Looks good, merging.

**Comment by eliorivero** [comment]
Cherry picked to 4.9 fc556daa55b9fb5331e3ce9de2beb12dc0064b06

**Pull request merged**
