### PR TITLE
Dependencies: Fix broken prod dependencies

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request:

- Drop production-only dependency installation. There's very limited benefit to skipping `devDependency` installation (save some time in an infrequent process) and it leads to issues that _only_ occur when making the production bundle.
- Add all [upgrade-nudge dependencies](https://github.com/Automattic/jetpack/blob/190301ba02a13ef148513348279e1f579f13a927/extensions/shared/components/upgrade-nudge/index.jsx#L4-L11) to dependencies. With upgrade-nudge SSR (https://github.com/Automattic/jetpack/pull/13070), these dependencies will be required.

This was working because `@wordpress/url` is installed as a transitive dependency, `@wordpress/e2e-test-utils` (a devDependency) causes it to be installed. If `@wordpress/e2e-test-utils` (like with `yarn install --production`) - `@wordpress/url` is not installed.

I believe, this is only a problem with extensions that have "SSR" from the implementation in https://github.com/Automattic/jetpack/pull/13070, at the moment only Simple Payments. At runtime in the browser, `@wordpress/*` dependencies are _externals_, meaning they are pulled from the runtime environment. That makes the presence or absence of a `@wordpress/*` package irrelevant. However, with https://github.com/Automattic/jetpack/pull/13070 SSR, some of these dependencies will be required _at build time_.

See p1566905517230900-slack-luna / d871cf9983b11e37dea0e1f70009b4ec84571857

#### Testing instructions:
* `yarn build-production` builds without errors.
* Add a Simple Payments block to a site on a free plan. The upgrade nudge should be visible in the editor and on the frontend for admin users (see https://github.com/Automattic/jetpack/pull/13070)

### CODE REVIEW

**Comment by ockham** [comment]
> I believe, this is only a problem with extensions that have "SSR" from the implementation in #13070, at the moment only Simple Payments. At runtime in the browser, `@wordpress/*` dependencies are _externals_, meaning they are pulled from the runtime environment. That makes the presence or absence of a `@wordpress/*` package irrelevant. However, with #13070 SSR, some of these dependencies will be required _at build time_.

Yes, that's the exact reason why I was adding those [as devDeps](https://github.com/Automattic/jetpack/pull/13070/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by ockham** [comment]
> * Add all [upgrade-nudge dependencies](https://github.com/Automattic/jetpack/blob/190301ba02a13ef148513348279e1f579f13a927/extensions/shared/components/upgrade-nudge/index.jsx#L4-L11) to dependencies. With upgrade-nudge SSR (#13070), these dependencies will be required.

Not entirely sure I'm following the rationale here. Should it not be enough to [keep them as `devDeps`](https://github.com/Automattic/jetpack/pull/13070/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) (and proably add `@wordpress/url` there) if we're dropping production-only dependency installation anyway? (My main point would be to use deps vs devDeps to visibly distinguish between deps that actually need to be installed, vs external ones.)

**Comment by sirreal** [comment]
> > * Add all [upgrade-nudge dependencies](https://github.com/Automattic/jetpack/blob/190301ba02a13ef148513348279e1f579f13a927/extensions/shared/components/upgrade-nudge/index.jsx#L4-L11) to dependencies. With upgrade-nudge SSR (#13070), these dependencies will be required.
> 
> Not entirely sure I'm following the rationale here. Should it not be enough to [keep them as `devDeps`](https://github.com/Automattic/jetpack/pull/13070/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) (and proably add `@wordpress/url` there) if we're dropping production-only dependency installation anyway? (My main point would be to use deps vs devDeps to visibly distinguish between deps that actually need to be installed, vs external ones.)

Yes, if we drop the production-only installation it doesn't matter where dependencies are declared. I'd remove `devDependencies` entirely and consider a lint rule to prohibit its use. That's my preference for simplicity and would obviate the rest of this response.

For an application like Jetpack which isn't a published package, there's no clear distinction about what dependencies and devDependencies are. It's one set of dependencies and a superset of those, we can make an arbitrary decision between dependencies and devDependencies.

At runtime, we don't need _any_ dependencies. @zinigor mentioned that some devDependencies are large, take a lot of time and space to install, and cause problems with the beta builder. That would mean that one place we can make the `dep`/`devDep` separation is "necessary for building the application" or not. That aligns with Jetpack, the (unpublished) Jetpack npm app is really only serves the purpose of building assets for the Jetpack plugin. `calypso-build` is a dependency, it's required for running the core functionality of the app - building assets. `devDependencies` can become the extras that aren't essential for building the assets - things like e2e testing packages.

**Comment by ockham** [comment]
Okay, sounds like a good approach! :+1:

**Review by jeherve — APPROVED** [review]
It works well as is. Merging.

**Pull request merged**
