### PR TITLE
Add Advanced General menu item

### PR DESCRIPTION
**Pull request by tjcafferkey**
Fixes https://github.com/Automattic/wp-calypso/issues/51189

#### Changes proposed in this Pull Request:

* When the advanced dashboard toggle is enabled we need to add an "Advanced General" menu item so that Calypso settings are still accessible.
#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

**Simple Sites**

* Apply the WPCOM patch D61023-code to your Sandbox
* Check that Settings > Advanced General exists regardless of whether the "Advanced Dashboard" toggle is enabled or not and that it goes to WP Admin
* Check that Settings > General exists and goes to Calypso settings

**Atomic Sites**

* Install Jetpack Beta and activate this branch.
* Check that Settings > Advanced General exists regardless of whether the "Advanced Dashboard" toggle is enabled or not and that it goes to WP Admin
* Check that Settings > General exists and goes to Calypso settings

### CODE REVIEW

**Review by mmtr — COMMENTED** [review]
> Atomic Sites
> Check that Settings > Advanced General does not exist when "Advanced Dashboard" toggle is disabled.

This doesn't work for me, but I think this is expected. Otherwise we would be reverting the changes we implemented in https://github.com/Automattic/jetpack/pull/18804.

IMO, we should always show both links in both Simple and Atomic, regardless of the toggle.

**Comment by tjcafferkey** [comment]
>This doesn't work for me, but I think this is expected. Otherwise we would be reverting the changes we implemented in #18804.

Yeah, you're right. I'm making some updates here to ensure it's always present regardless of toggle.

**Comment by tjcafferkey** [comment]
>IMO, we should always show both General and Advanced General links in both Simple and Atomic sites, regardless of the toggle.

@mmtr Done in https://github.com/Automattic/jetpack/pull/19745/commits/aacdb1cce994b9af5c411c50d0824d88777d1a82

**Review by cpapazoglou — APPROVED** [review]
I can confirm that both "General" and "Advanced General" appear simultaneously in Simple & Atomic and redirect to the correct page regardless of the toggle state.

LGTM!

**Comment by tjcafferkey** [comment]
@jeherve have you any idea why the JS tests are failing. It's reporting `Cannot find module '@wordpress/components'` which seems to have only [been added 2 hours ago](https://github.com/Automattic/jetpack/commit/564d2bf8c1cddb8a72d367446d3bcc8d29a609c2#diff-6102404abf6292dd4603292ea4b49b9c336c71f4210dc2b8b8cc5c97918225d3) but I'm not sure why there's an issue trying to resolve this module...

**Comment by jeherve** [comment]
cc @sergeymitr who may have more info about this.

**Review by mmtr — APPROVED** [review]
JS tests failures seem unrelated, but they are required to pass before merging. Let's see if @sergeymitr can take a look, since this may be affecting other PRs.

**Comment by tjcafferkey** [comment]
@sergeymitr something that @mmtr mentioned is that perhaps new dependencies (`@wordpress/components`) also needs to be listed in the root `package.json` as well?

**Comment by mmtr** [comment]
Opened https://github.com/Automattic/jetpack/pull/19758 to see if the CI failures get solved.

**Review by jeherve — APPROVED** [review]

**Comment by tjcafferkey** [comment]
Deployed to WPCOM in r225339-wpcom

**Pull request merged**
