### PR TITLE
Widgets: Social icons: Add multiple ccTLDs for Pinterest to support icon display

### PR DESCRIPTION
**Pull request by arunsathiya**
Fixes https://github.com/Automattic/jetpack/issues/8422

#### Changes proposed in this Pull Request:

* Adds multiple ccTLDs for Pinterest, to support showing Pinterest icon - addresses the issue on https://github.com/Automattic/jetpack/issues/8422

This list was obtained from another project mentioned [here](https://github.com/matomo-org/searchengine-and-social-list/pull/45). I couldn't see an official list of ccTLDs owned by Pinterest so far. Happy to update with more ccTLDs, as suggested.

#### Testing instructions:

* Fire up a Jetpack site
* Add the `Social icons (Jetpack)` widget
* Try adding Pinterest links with the domains list below.
* Ensure the Pinterest icon shows up when you view the live site

---

- pinterest.com
- pinterest.ca
- pinterest.ch
- pinterest.co.uk
- pinterest.de
- pinterest.dk
- pinterest.es
- pinterest.fr
- pinterest.ie
- pinterest.jp
- pinterest.nz
- pinterest.pt
- pinterest.se

---

#### Before

The image below shows all icons for all the Pinterest ccTLDs, in the order listed earlier. Notice that the Pinterest icon does not appear for all TLDs that are not `.com` 

screenshot 2018-12-22 at 20 54 30

#### After

The image below shows all icons for all the Pinterest ccTLDs, in the order listed earlier as well. Notice that all the Pinterest icons appear fine.

screenshot 2018-12-22 at 20 53 32

#### Proposed changelog entry for your changes:

* I guess no changelog entry is required, but feel free to let me know if I can mention "Social media widget now supports icon display for more ccTLDs" or something more clear. I think it's a very minor change that does not require an explicit changelog entry.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
While this works, I wonder if we should take a different approach and have a single entry accepting just about any Pinterest ccTLDs, as I can imagine that the list of countries they will support will only grow in the future. It would avoid having to update the plugin every time a new country gets added.

**Comment by arunsathiya** [comment]
Thanks for reviewing, @jeherve! I thought so as well, but I noticed that Amazon links were listed so and wanted to maintain the same format. It's a great time to improve that though!

I took a stab at this, and the closest I could come is 4343f7b.

It matches all links with a `www` or a different subdomain, and immediately requires `pinterest.`.

Examples that match this pattern:

- https://pinterest.com
- http://pinterest.com
- https://test.pinterest.com
- http://test.pinterest.com
- https://www.pinterest.com
- http://www.pinterest.com

But this matches incorrect links like the following as well:

- https://pinterest.example.com
- https://pinterest.example.co.uk

I would like to hear your thoughts at this stage. If the incorrect links require a fix, I shall closing closing this PR and submit one afresh I find a way through this.

**Comment by arunsathiya** [comment]
Side note: Amazon links could be updated as well with this logic when Pinterest's is updated. I can update the PR description as required. Or would you recommend submitting a fresh PR for Amazon?

**Comment by arunsathiya** [comment]
Closing this PR in favour for @torres126's logic here - https://github.com/Automattic/jetpack/pull/11252#issuecomment-461296206 :)

**Pull request closed without merging**
