### PR TITLE
Widgets: support new YouTube channel link

### PR DESCRIPTION
**Pull request by colomet**
youtube channel user name, now start with c

### CODE REVIEW

**Comment by jeherve** [comment]
Fixes #3011

Could you give us an example of a channel URL that uses a `c` and works? I tried several channels, but all of them seem to use `channel`, and `c` just returns an error page.

Also worth noting that in this PR you changed the user URL instead of the channel URL.

**Comment by colomet** [comment]
https://www.youtube.com/c/illustrastock/

**Comment by jeherve** [comment]
Interesting. It doesn't seem like the change was rolled out to every Youtube channel just yet.

Take OK Go's channel URL for example:
https://www.youtube.com/channel/UC194cPvPaGJjhJBEGwG6vxg

This, on the other hand, won't work:
https://www.youtube.com/c/UC194cPvPaGJjhJBEGwG6vxg

It might be best to keep using the old channel URLs for now:
https://www.youtube.com/channel/UCneI1gskMBoOyKNi5Oc_2FA/

**Comment by kraftbj** [comment]
Custom YouTube channel names appear to use `/c/`, while the default "permalink" hash uses `/channel/`

Example from my channel: https://www.youtube.com/c/Dadsdrinkingbeerblog is the customized URL via the G+ pages process. The default, and still functional, hash URL is https://www.youtube.com/channel/UCTJxnyd_1plfy3HM-Kk5hXA

**Comment by lancewillett** [comment]
See also 7286-wpcom

**Comment by lancewillett** [comment]
Fixed in 4d581ed

**Pull request closed without merging**
