### PR TITLE
Update Authorize URL iframe to include affiliate code

### PR DESCRIPTION
**Pull request by oikeme**
Update the url on the authorization flow to include the affiliate code if the option is set along with the connection flow.d

Fixes #
N/A

#### Changes proposed in this Pull Request:

* The iframe for the in place connection flow currently does not include the affiliate code if the option is set. This updates the existing logic that builds the connection url and adds the affiliate code to also do the same for the authorization url.

#### Jetpack product discussion
https://wp.me/pbtFPC-E2-p2

#### Testing instructions:
* Pull down the branch on a site that does not yet have Jetpack connected. 
* Add the option `jetpack_affiliate_code` to the site options.
* When attempting to connect the site verify that the iframe url associated with the final connection step at "Connecting as {user}" also includes `aff=jetpack_affiliate_code` in the url query args.

#### Proposed changelog entry for your changes:

* Update the authorize url in the connection iframe in the final connection step to include the affiliate code similar to the existing connection url.

### CODE REVIEW

**Comment by ebinnion** [comment]
I've pushed a small fix for this PR. Here's a screenshot that shows the `aff` query param in the iFrame `src`

Screen Shot 2020-08-24 at 1 27 09 PM

**Comment by ebinnion** [comment]
Of note - With the redirect to Calypso after in-place connection going in for the 8.9 release. This PR absolutely has to make it into the 8.9 release so that we can continue tracking affiliate sales for partners correctly.

**Comment by kbrown9** [comment]
Travis is reporting a few failing unit tests:

```
1) WP_Test_Jetpack::test_partner_codes_are_added_to_connect_url with data set "subsidiary_code" ('subsidiary', 'jetpack_partner_subsidiary_id', 'subsidiaryId')
Failed asserting that an array has the key 'subsidiaryId'.
/tmp/wordpress-previous/src/wp-content/plugins/jetpack/tests/php/general/test_class.jetpack.php:1099
```
```
2) WP_Test_Jetpack::test_partner_codes_are_added_to_connect_url with data set "affiliate_code" ('affiliate', 'jetpack_affiliate_code', 'aff')
Failed asserting that an array has the key 'aff'.
/tmp/wordpress-previous/src/wp-content/plugins/jetpack/tests/php/general/test_class.jetpack.php:1099
```

**Comment by ebinnion** [comment]
Thanks @kbrown9! I've updated the failing tests. The tests were actually kind of broken themselves. 

The `build_connect_url()` conditionally returns either a register URL (which points to the local site) or a URL on `jetpack.wordpress.com` to connect the site. The test wasn't properly setup to test the latter, so the URL was always coming back as being the register URL (the former).

I swapped out the test to call to `build_authorize_url()` which should more closely test the logic that we're interested in.

**Comment by ebinnion** [comment]
There are still some failing E2E tests, but they don't seem related to this PR at all. It's mentioning:

```
ERROR: WP_SITE_URL is not set after launching an ngrok
The command "./tests/e2e/bin/env.sh start" failed and exited with 1 during .
```

**Comment by kbrown9** [comment]
> There are still some failing E2E tests, but they don't seem related to this PR at all. It's mentioning:

> ERROR: WP_SITE_URL is not set after launching an ngrok
The command "./tests/e2e/bin/env.sh start" failed and exited with 1 during .

I restarted the E2E tests, which will hopefully clear that error.

**Pull request merged**
