### PR TITLE
Merge/master updates 9 02 17

### PR DESCRIPTION
**Pull request by eliorivero**
When reviewing, make sure the files
```
_inc/client/components/module-settings/index.jsx
_inc/client/state/settings/reducer.js
```
are the same than in `feature/settings-overhaul`
https://github.com/Automattic/jetpack/pull/6299/files

### CODE REVIEW

**Comment by dereksmart** [comment]
Builds and loads ok, files mentioned in the PR comments look fine!

**Comment by samhotchkiss** [comment]
@eliorivero and @dereksmart -- In the future, updating a feature branch to be current with master shouldn't require a PR-- just merge straight into the feature branch and push away, IMO!

**Comment by samhotchkiss** [comment]
(marking as "Has Changelog" because no changelog is needed)

**Comment by zinigor** [comment]
I have deleted the commit that this PR has created because it wasn't a merge commit, but a "squash and merge" commit. The real merge commit is now 904a1c8.

**Pull request merged**
