### PR TITLE
Masterbar: Remove unwanted Appearance submenu items

### LINKED ISSUE #18235: Nav Unification: items are duplicated in "Appearance" sub-menu
#### Steps to reproduce

- On an account with the unified navigation enabled:
- Hover over "Appearance" menu item
- Sub-menu items are duplicated

#### What I expected

- A single instance of each sub-menu item :)

#### Screenshot / Video

Screen Shot 2020-12-28 at 1 56 33 PM

#### Context / Source

This causes a duplicate key React warning: `Warning: Encountered two children with the same key, 'customize-phpreturn…'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

### PR DESCRIPTION
**Pull request by obenland**
Fixes #18235.

#### Changes proposed in this Pull Request:

* Removes default header and background submenu items.
* Maintains toplevel menu item ID as JS/CSS selector.
* Escapes removal URLs so they match the registered URLs.
* Sets the correct parent file, so menu expands when submenu items are active.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

This is not easy to test because it requires a bit of a setup. 
* With nav-unification enabled, install & activate [the Singl theme](https://wordpress.org/themes/singl/). Easiest way is probably to go though the theme installer in wp-admin for that
* Navigate to `/wp-admin/themes.php` and make sure that there is only one instance of Header or Background menu items.

On wp.com:
* Apply D55017-code and D55018-code to your sandbox.
* With nav-unification enabled, activate the Singl theme on your test site.
* Navigate to `/wp-admin/themes.php` and make sure that there is only one instance of Header or Background menu items.

#### Proposed changelog entry for your changes:

* None.

### CODE REVIEW

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Both on my sandbox (simple site) and atomic (with current branch), while the duplicate "Header" menu is now not showing, I still have duplicate "Background" menus



Respective urls:
1) `https://wordpress.com/customize/[DOMAIN]?autofocus%5Bcontrol%5D=background_image`
2) `https://[DOMAIN]/wp-admin/customize.php?autofocus%5Bsection%5D=colors_manager_tool`

**Comment by obenland** [comment]
@cpapazoglou I've not been able to reproduce it but I did find the plugins that add the `colors_manager_tool` modifications and updated it accordingly. Could you take another look and see if that fixes it for you?

**Comment by obenland** [comment]
I was able to reproduce and fix the background link issue. Thanks @cpapazoglou, nice catch!

**Review by michaeldcain — APPROVED** [review]
This works well for me.

**Review by jeherve — APPROVED** [review]
This seems to test well for me.

**Comment by jeherve** [comment]
Before we merge this; @cpapazoglou Do you think you could give this another spin, see if that solves the problem for you too?

Thanks!

**Comment by cpapazoglou** [comment]
> Before we merge this; @cpapazoglou Do you think you could give this another spin, see if that solves the problem for you too?
> 
> Thanks!

Yes, it. Both for my atomic site & my sandbox!

**Review by cpapazoglou — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.3` in 692fa4e7a4f67ff6c1009a23f5d0d7b0b1b24acc

**Comment by cpapazoglou** [comment]
Deployed r219189-wpcom & r219190-wpcom.

**Pull request merged**
