### PR TITLE
SSO: Different CTA on user profile page when user is not linked

### LINKED ISSUE #1216: SSO: error when linking wpcom account in profile
Steps to reproduce:

1. Connect Jetpack to WordPress.com on your site
2. Go to Users > Add New, and create a new user
3. Log out, and log back in with that user.
4. Go to Users > My Profile and click on the link to link that account to your WordPress.com account
    You get the following error: `-10520: Jetpack: [missing_token]`

If, however, you go to the Jetpack menu and link that account to a WordPress.com account first, you'll be able to enable SSO in your profile afterwards.

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #1216

Prompt users to link their account before letting them try to sign in via SSO.

### CODE REVIEW

**Comment by richardmuscat** [comment]
LGTM, but

Will it cause a conflict here: https://github.com/Automattic/jetpack/commit/6d7e5e006f6f6292070af50b89162eeed5ffee8e#diff-078d381f399235cd03b25dc4f4bfa1afL984

**Comment by dereksmart** [comment]
You referring to the string changes?  May be a merge conflict, but function won't be affected.

**Comment by richardmuscat** [comment]
Yeah just string changes.

**Comment by richardmuscat** [comment]
Woot

**Pull request merged**
