### PR TITLE
FSE: FSE menu item platform parity

### PR DESCRIPTION
**Pull request by mattwiebe**
This PR provides the previously WPCom Simple-only changes to FSE menu item positioning introduced in #18800 to Atomic sites.

Fixes Automattic/wp-calypso#50894

#### Changes proposed in this Pull Request:

* Atomic and Jetpack sites now also reposition the FSE menu
* Gutenberg plugin menu removed on WPCom Simple and Jetpack
* Keep the Customizer removed when it's been removed by FSE

#### Jetpack product discussion
Unifying behaviour is the whole Nav Unification deal right?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

For WPCom Simple and Atomic, you should see:
**Site Editor with no (beta) label, underneath Appearance**

##### WPCom Simple:
* Apply D58831-code  to your sandbox
* Sandbox a site created through the [Horizon FSE flow](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor)
* Sandbox `public-api.wordpress.com`
* Visit your test site's `wp-admin`
* Verify that both wp-admin and Caplyso should show the menu as above.

##### Atomic:
1. Have/create an Atomic site
2. Install and activate Jetpack, Gutenberg, Jetpack Beta plugins
3. Install and activate an FSE theme
4. Checkout this branch in the Jetpack Beta plugin
5. Verify that both wp-admin and Caplyso should show the menu as above.

##### Jetpack:
1. This doesn't apply to non-Atomic Jetpack

### CODE REVIEW

**Review by mmtr — CHANGES_REQUESTED** [review]
I got a duplicated "Site Editor" menu both in Calypso and WP Admin while checking the Simple site scenario:

Screen Shot 2021-03-17 at 11 34 37

I think this is because you're calling `add_gutenberg_menus` twice now and this one should probably be removed:

https://github.com/Automattic/jetpack/blob/156f5981e698e5703a44161226dffebe05df5837/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L50

It works fine on Atomic sites.

**Comment by mattwiebe** [comment]
> I got a duplicated "Site Editor" menu both in Calypso and WP Admin while checking the Simple site scenario

Nice catch @mmtr, I missed removing that in the migration over from the previous PR. Cleaned that up now. 👍

**Review by mmtr — APPROVED** [review]
LGTM 👍

**Review by jeherve — APPROVED** [review]

**Comment by mattwiebe** [comment]
^ Had to port those changes to D59064-code because they weren't applying cleanly. Everything should be aligned though.

**Pull request merged**
