### PR TITLE
Launchpad: Add checklist endpoint args sanitization and validation

### PR DESCRIPTION
**Pull request by jeyip**
Fixes https://github.com/Automattic/jetpack/pull/30023#discussion_r1163369333

## Proposed changes:

* Sanitizes and validates query param arguments to the Launchpad Checklist API endpoint

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Simple Sites

- Checkout this branch.
- **METHOD 1:**
  - Build the jetpack `mu-wpcom-plugin` : `jetpack build plugins/mu-wpcom-plugin`
  - Use the jetpack rsync command in the jetpack project root directory to sync changes to your sandbox 
  - `jetpack rsync mu-wpcom-plugin {sandbox_here}:~/public_html/wp-content/mu-plugins/jetpack-mu-wpcom-plugin/production`
- **METHOD 2:**
  - Execute `bin/jetpack-downloader test jetpack-mu-wpcom-plugin add/launchpad-checklist-endpoint-args-sanitization-and-validation` on your sandbox.
- Use `developer.wordpress.com/docs/api/console/` to make a GET request to the new endpoint (WP REST API: `wpcom/v2/sites/{SITE_SLUG}/launchpad/checklist?checklist_slug=newsletter`)
- Verify that the endpoint returns the expected checklist
- Use the same dev console to make a request to the same endpoint but with a nonexistent checklist slug (WP REST API: `wpcom/v2/sites/{SITE_SLUG}/launchpad/checklist?checklist_slug=fake`)
- Verify that the endpoint returns an error in the browser dev console

image

### CODE REVIEW

**Review by edanzer — DISMISSED** [review]
Code changes are straightforward and good to see. And this tests as expected. 

I guess one small question is do we want to return an error from the endpoint in all cases if someone provides and empty or malformed checklist_slug? Trying to think if there's any value in returning an empty array, as we were before, or a 'default' checklist?

I think this makes sense, but I thought I'd raise the question once before proceeding...

**Comment by jeyip** [comment]
> I guess one small question is do we want to return an error from the endpoint in all cases if someone provides and empty or malformed checklist_slug?

Thinking more about this, as a developer, I'd prefer an explicit error stating that I'm not using the endpoint properly. We can always update this in the future

**Comment by sharpirate** [comment]
### Testing
image

#### Valid Slug
When I pass a valid slug I get the back the correct data from the endpoint

#### Invalid Slug
When I pass an invalid slug I get a `400` Error Code and the following error message:
`checklist_slug is not one of build, free, link-in-bio, link-in-bio-tld, newsletter, videopress, and write.`

**Comment by edanzer** [comment]
Just re-tested this following latest updates and still tests as expected.

**Review by sharpirate — APPROVED** [review]

**Pull request merged**
