### PR TITLE
Compatibility issues with latest version of WordPress (version 4.8)

### PR DESCRIPTION
**Pull request by ranvo**
Fixes # Replaced a few ctype_digits() functions with is_numeric() functions
I am running WordPress 4.8 and the jetpack plugin was having several issues from initial login to updating posts.
I ran a debugger and the line numbers were shown with undefined ctype_digit() function being called. After a few Google searches I though is_numeric function might just work and it did.
https://twitter.com/NonLinearNygma/status/878608299066667008 this tweet is an example of a typical error I was facing regularly.

Some issues still persist, but it is usuable
https://twitter.com/NonLinearNygma/status/879617631560400897
#### Changes proposed in this Pull Request:

*

#### Testing instructions:

* I managed to reproduce this error twice on digitalocean's hosting platform running php5.6 and php7 on different instances.

### CODE REVIEW

**Comment by kraftbj** [comment]
This isn't a compat issue with WP. It sounds your server is using a version of PHP without a standard pre-installed library: http://php.net/manual/en/ctype.installation.php

**Comment by kraftbj** [comment]
That said, it sounds core doesn't use ctype functions ( https://core.trac.wordpress.org/ticket/11620 ). ctype_digits and is_numberic does different things, though. 

I don't recall hearing a case of this via support before.

**Comment by ranvo** [comment]
Have you guys tested it on WordPress 4.8 with php 7. Also I am running
FreeBSD as my host system. Might have to go through the docs to see if all
the php files are available.

**Comment by kraftbj** [comment]
On FreeBSD, run `pkg install php70-ctype` per the link in my first comment.

**Comment by ranvo** [comment]
Any other dependency that I should be aware of?
I got another error related to Class DOMDocument
Uncaught Error: Class 'DOMDocument' not found in
/usr/local/www/apache24/data/wp-content/plugins/jetpack/modules/shortcodes/class.filter-embedded-html-objects.php:246

**Comment by kraftbj** [comment]
Try php70-xml. That's required for some functions of WP too.

**Comment by ranvo** [comment]
Already done. Thanks for your time though! That helps me a lot :)

**Comment by kraftbj** [comment]
Try http://php.net/manual/en/dom.setup.php

All i'm doing is googling for the function and checking the PHP.net result for install instructions.

All of these are part of a default install but seems like FreeBSD is doing the absolute minimum, not the default.

**Comment by ranvo** [comment]
Of course, I will follow-up on this and maybe try and spread the word. If
anything new comes up, others should know about it

**Comment by kraftbj** [comment]
I'm going to suggest closing this PR and look into maybe a pre-function to check for all of these libraries. Ideally, I think this would be good in Core (php-xml, php-mysql, etc) but can be extended by plugins for extras (php-ctype).

**Comment by ranvo** [comment]
Yeah, seems like a good place to start.

**Comment by kraftbj** [comment]
https://core.trac.wordpress.org/ticket/5235

**Pull request closed without merging**
