### PR TITLE
Tools: remove all Yarn scripts and continue using package.json. Also fix error in Travis.

### PR DESCRIPTION
**Pull request by eliorivero**
With this PR, the yarn tasks can be called using the same syntax and we don't need any files for this.
```
yarn build
yarn watch
yarn distclean
```

Plus, this fixes a Yarn error found in Travis
```
yarn install v0.16.1
error `install` has been replaced with `add` to add new dependencies. Run "yarn add gulp-cli" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install v0.16.1
```

#### Changes proposed in this Pull Request:
- remove all Yarn scripts and continue using the `scripts` entry in `package.json`
- replaces `yarn install gulp-cli` with `yarn add gulp-cli`

#### Testing instructions:
* make sure all tasks work

### CODE REVIEW

**Comment by oskosk** [comment]
> yarn build watch
Does this work ?

**Comment by eliorivero** [comment]
@oskosk it works for me, is it not working for you?

**Comment by oskosk** [comment]
Nope. `run build watch` does not keep watching apparently

**Comment by oskosk** [comment]
Although `yarn watch` does

**Comment by oskosk** [comment]
I'd say to just leav the commands like 

```
yarn build
yarn build production
yarn build languages
yarn lint
yarn watch
yarn clean
yarn distclean
```

Introducing a `build` sub-command is IMO out of de-facto standards both from `npm` and `yarn` and may cause confusion when trying to parse what `yarn build clean` does, as it doesn't build anything, but it removes things. 

I'd vote for taking advantage of `yarn` feature of not demanding a `run` sub-command, but not for introducing a subcommand of our own.

**Comment by eliorivero** [comment]
Right, `build` is not a subcommand though, it's the name of the script. That said, it looks like calling one of the cases defined in the script correctly loads the `build.sh` and passes it the right parameter. So `yarn watch` results in a call like `/tools/build.sh watch` which is correct.
So in the end, yeah, we can use it as you pointed.

**Comment by oskosk** [comment]
Nice. I was mostly talking about leaving the simplified versions on the documentation (readme.md) regardless of how the implementation is done. 

The rationale behind my opinion is that we're using a lot of tools that provide CLIs and are well known like `gulp`, `npm`, `yarn`, `webpack`, `sass`, `eslint`, `mocha`, etc.

We've already seen that a lot of devs or Happiness Engineers, try to run `gulp` on its own (or even `webpack` maybe ) because it's intuitive if you see a `webpack.config.js` file or even a `gulpfile.js` lying there. Which in some cases do not work if run on their own. 

So, consolidating everything into `yarn` intuitive commands leaves us in a safe place when in need to debug other's build problems.

**Comment by eliorivero** [comment]
@zinigor as per our talk, I've changed `clean` to `clean-client`

**Comment by zinigor** [comment]
Thanks, LGTM!

**Pull request merged**
