### PR TITLE
Search: Fix antipattern where components are returned from functions called renderXXXX() instead of just being components

### PR DESCRIPTION
**Pull request by oskosk**
Fixes unnecessary re-renders and lack of visibility in React Dev tools

### This PR is better reviewed seeing what each commit is doing

It's quite straightforward and if something here is wrong, the immediate effect is that the dashboard crashes

#### Changes proposed in this Pull Request:

* [x] Refactors renderFilterOption to be a component (Cherry-picked into #26426)
* [x] Refactors renderSearchResult to be a component (Cherry-picked into #26427)
* [x] Refactors renderInstantSearchToggle to be a component (Cherry-picked into #26428)
* [x] Refactors renderConnectScreen to be a component  (Cherry-picked into #26430)
* [x] Refactors renderConnectionFooter to be a component (cherry-picked into #26433)
* [x] Refactors renderHeader to be a component (Cherry-picked into #26435)
* [x] Refactors renderFooter to be a component  (Cherry-picked into #26435)
* [x] Refactors renderMockedSearchInterface to be a component (Cherry-picked into #26437)
* [x] Refactors renderModuleControl to just render component (Cherry-picked into #26437)

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
None

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
1. Launch a [JN site with Search standalone and this branch](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack-search=fix/render-pattern-search&wp-debug-log)
2. Keep the JS console open and expect to see no warning for the following steps
3. Connect, navigate the page. Expect to see no crashing page

### CODE REVIEW

**Comment by oskosk** [comment]
Pused rebase in https://github.com/Automattic/jetpack/pull/26415/commits/95327bd176d8fdd6e1156d84ef8e85d5b0142f89 after #26426 got merged

**Comment by oskosk** [comment]
Pushed rebase in https://github.com/Automattic/jetpack/pull/26415/commits/c50e8f1078c3676a1f08d0087ba7ee48062e0537 after #26427 got merged

**Comment by oskosk** [comment]
Pushed rebase in [b232592](https://github.com/Automattic/jetpack/pull/26415/commits/b23259257e2b524be9ff9f3a938ae5e826a14fbe) after #26428 got merged

**Comment by oskosk** [comment]
Force-pushed a rebase so the history looks clean for cherry-picking in follow-up PRs

**Comment by oskosk** [comment]
Pushed rebase in [8dc3f53](https://github.com/Automattic/jetpack/pull/26415/commits/8dc3f534aba2cb0c81307293414ce011463728bd) after #26433 got merged

**Comment by jsnmoon** [comment]
Looks like every commit was cherry-picked and merged into trunk! Closing.

**Pull request closed without merging**
