### PR TITLE
Modules List Table: enhancement: define the "name" column as primary …

### PR DESCRIPTION
**Pull request by stephdau**
…column.

See https://core.trac.wordpress.org/ticket/25408#comment:58

### CODE REVIEW

**Comment by georgestephanis** [comment]
Would this change be backwards compatible with the status quo?  I don't think anything would break in old versions with the extra value.

**Comment by stephdau** [comment]
It'll be fine in older versions of WP, as it uses `list()`.

```
[epsi@mobilus wpdev]$ php
<?php
$ar = array( 'zero', 'one', 'two', 'three' );
list( $var0, $var1, $var2, $var3, $var4 ) = $ar;
^D
PHP Notice:  Undefined offset: 4 in - on line 3

[epsi@mobilus wpdev]$ php
<?php
$ar = array( 'zero', 'one', 'two', 'three' );
list( $var0, $var1, $var2 ) = $ar;
^D
```

**Comment by georgestephanis** [comment]
Solid.  Good to merge for me, then.  Can I get a second review?

**Comment by jeherve** [comment]
:+1: 
I tested with 4.1, 4.2, and `trunk`, on a site using PHP 5.2, and it seems to work.

**Comment by dereksmart** [comment]
Nice, also :+1: from me

**Pull request merged**
