### PR TITLE
Payment Block: fix payment block upgrade message obscured

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes [#61419](https://github.com/Automattic/wp-calypso/issues/61419)

Currently, the upgrade nudge interferes with the block controls, this PR solves the issue.

#### Changes proposed in this Pull Request:

* The necessary rules were already in place, we just had to create a rule with more specificity so that the default wp-core behavior can be overridden without the need to use `!important`.
* This PR fixes the issue not only for the Payment Block but for all the blocks that require/show the upgrade nudge.

#### Testing instructions:

* Create or Edit a new Post
* Add any/all the blocks that require an upgraded subscription.
* You shall see that the block controls are shown without interfering with the upgrade nudge.

#### Test evidence

https://user-images.githubusercontent.com/1989914/156790069-dbf6c875-e5d9-46a8-8bb6-4974ae0df0e5.mp4

### CODE REVIEW

**Comment by dsas** [comment]
This is working fine in Chrome but not in firefox.

image

**Comment by dsas** [comment]
This rule `.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > * + *` with `margin-top: var( --wp--style--block-gap );` is out-specifying it.

If it matters i'm testing on the twenty twenty-two theme

**Comment by rcrdortiz** [comment]
> This is working fine in Chrome but not in firefox.
@dsas It's working for me on a clean Firefox install. 

https://user-images.githubusercontent.com/1989914/157041896-cb0a01ec-d314-41c4-99e7-c92b31dcdfcd.mp4

**Comment by dsas** [comment]
Ok, I tried again and it does work. It must've been cache - though I had dev tools open which is supposed to block caching....

**Review by dsas — APPROVED** [review]

**Review by sdixon194 — APPROVED** [review]
Hmm I couldn't reproduce the original issue, but change seems logical to me.

**Comment by BogdanUngureanu** [comment]
Deployed in r241378-wpcom

**Pull request merged**
