### PR TITLE
Blocks: load different bundle in the block-based widget editor

### LINKED ISSUE #20357: Editor: solve conflict between Jetpack blocks' @wordpress/editor dependencies and Block-based Widgets Editor
WordPress 5.8 introduces a new Block-based Widgets Editor, and both our block bundle and the WordPress.com Block Editor conflicts with it at the moment.

#### Steps to reproduce the issue

1. Start with a site using WordPress 5.8 RC
2. Ensure that your site is connected to WordPress.com.
3. Now go to Appearance > Widgets; it generates the following notice:

```
Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) in wp-includes/functions.php on line 5535
````

- Related Core ticket: https://core.trac.wordpress.org/ticket/53437
- Dev Note: https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/
- Primary issue: #19654
- Discussion: p1626276936278000/1626276764.276600-slack-C01U2KGS2PQ , p1626278473009100-slack-CBTN58FTJ
 
We have different things to address here:

**********

- [x] Do not load the WordPress.com Block Editor in the widgets editor, where wp-editor, one of the dependencies of the WordPress.com Block Editor, is not accepted. #20358 

**********

- [ ] Address `@wordpress/editor` dependencies in our own blocks.

Jetpack's block bundle (also loaded on WordPress.com Simple) has some blocks and extensions that rely on `@wordpress/editor`:
- We want to check if a post's type supports Publicize, Likes, or shares before to display the Publicize / Likes / Sharing panel in the sidebar.
- The toolbar button added to the Twitter block that allows you to import Twitter Threads into a post relies on the package to look for post meta, to see if the thread you're importing is from your own Twitter account.
    - https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/plugins/jetpack/extensions/blocks/gathering-tweetstorms/editor.js#L5
    - https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/blocks/gathering-tweetstorms/use-gather-tweetstorm.js#L30
- We use `mediaUpload` from the package to upload media in the Slideshow, Video, and Tiled Gallery blocks.

However, that `@wordpress/editor` package cannot be used in the new block-based widget editor, since we're not in a post editor.
For this reason, Core started outputting a `_doing_it_wrong()` notice for folks using that package in the block-based widget editor.

I'm not quite sure how to approach that problem at this point.

- Since all our blocks and extensions are part of one big bundle, it also includes blocks and extensions that really do not make sense (and in this case output a warning) in the widget editor, such as sharing.
- At the same point, some of our blocks really would make sense in that context.

How should we approach this?

### PR DESCRIPTION
**Pull request by jeherve**
Related: #20357

#### Changes proposed in this Pull Request:

As described in #20357, we cannot use blocks that rely on post information and the `@wordpress/editor` package in the block-based widget editor that will ship in WordPress 5.8.

We happen to have an existing alternative bundle, that was built for P2, and that had a similar goal: see #15467 and D41999-code for more info. One potential solution to #20357 would be to use that same bundle in the widget editor.
This PR leverages that existing bundle, and updates it to remove the blocks that are problematic in the widget editor.

This has an advantage: we do not have to come up with a new solution.
And some disadvantages:

- Although named `no-post-editor`, I believe that bundle mostly meant "No blocks that only appear in the sidebar". I believe we may be able, and want to be using blocks such as our Video block or the Tiled Gallery block on P2. cc @lezama.
- Additionally, it also means that from now on, we would have to manually maintain the 2 bundles and remove where each one belongs. That same problem was highlighted in https://github.com/Automattic/jetpack/pull/15467#issuecomment-614740859
- It's also a problem for folks using the `jetpack_blocks_variation` filter to overwrite the block variation used anywhere on a site. Maybe we should force the use of the no-post-editor bundle after that filter has been applied.

#### Jetpack product discussion

* p1626278473009100-slack-CBTN58FTJ

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start from a site using WP 5.8 RC
* Go to Appearance > Widgets
* You should see some Jetpack blocks available there.
* The Tiled gallery block should not be available.
* You should see no errors in your logs.

### CODE REVIEW

**Comment by sdixon194** [comment]
Thinking out loud, while the error notices are annoying and less than ideal, is it worth only fixing the notice at the expense of the user not being able to add whatever block they want at all? Unless we have more reasons to restrict the kinds of blocks that can be used in the widget editor (although some might not make sense to add to a widget area), I think I'd prefer the ability to add most of them. The blocks themselves still work and don't break anything, just some don't make sense, right?

**Comment by samiff** [comment]
> > @lezama This would stop us from uploading videos to VideoPress via the P2 editor, is that okay?
> 
> Not okay 😅 , I see the problem now, I will check what we need to do P2 side and get back to you this week.

@lezama Did you have any other feedback on this?

**Comment by lezama** [comment]
p2editor has sidebar these days, I think this shouldn't be a problem p2 side

**Comment by jeherve** [comment]
I'll close this now since we haven't progressed on this imperfect solution lately. I believe we should be able to solve this properly by fixing the problems outlined in #17099.

**Pull request closed without merging**
