### PR TITLE
Change all instances of jetpack.me to jetpack.com

### PR DESCRIPTION
**Pull request by dereksmart**
:tada:

### CODE REVIEW

**Comment by kraftbj** [comment]
Should we change most of them to https too? I would not change the debugger call to check if support is open as some servers balk at https, but the rest?

**Comment by dereksmart** [comment]
@kraftbj yeah let's do it in a separate PR

**Comment by zinigor** [comment]
As far as I can see, it doesn't actually need string changes, which is :cool:, but it does need a rebase, which is not :cool:

**Comment by dereksmart** [comment]
:cool: @zinigor rebased :cool:

**Pull request merged**
