### PR TITLE
Use PlanIcon component in the My Plan section

### PR DESCRIPTION
**Pull request by monsieur-z**
### Changes proposed in this Pull Request

This PR gets rid of the references to products and plans icons in the _My Plan_ section, in favor of the _PlanIcon_ component.

Fixes 1164141197617539-as-1151269793214129

### Implementation notes

A next step could be to import `ProductIcon` from `@automattic/components`. For the moment, icons have been copied from Calypso to this PR.

### Testing instructions

- Run the plugin locally
- Visit `/wp-admin/admin.php?page=jetpack#/my-plan`
- Choose a couple of plans/products, and verify that you see its icon (see capture below)

### Screenshots
merge_from_ofoct

### Does this pull request change what data or activity we track or use?
No

### Proposed changelog entry for your changes:
Refactor icons in the My Plan section

### CODE REVIEW

**Review by rcanepa — DISMISSED** [review]
LGTM! 

The only minor detail I found is that we no longer need to import `imagePath` so we can delete this line: https://github.com/Automattic/jetpack/blob/88ab4db1e65317d9677ce75e60a62442817c79c2/_inc/client/my-plan/my-plan-header/index.js#L14

**Comment by monsieur-z** [comment]
> LGTM!
> 
> The only minor detail I found is that we no longer need to import `imagePath` so we can delete this line:
> 
> https://github.com/Automattic/jetpack/blob/88ab4db1e65317d9677ce75e60a62442817c79c2/_inc/client/my-plan/my-plan-header/index.js#L14

Good catch!

**Comment by monsieur-z** [comment]
@jeherve, this PR is related to #17243. Could I get it approved before the freeze? Thanks!

**Review by jeherve — APPROVED** [review]
Tests well for me. Merging.

**Pull request merged**
