### PR TITLE
Sync: Namespace the sync sender

### PR DESCRIPTION
**Pull request by tyxla**
In #12712 and all the related PRs we are making an effort to namespace all the sync modules. We also need to start namespacing the rest of the Sync core, see #12751. 

This PR adds a namespace to the sync sender, and updates the sync package to also autoload those classes from the root `src` directory of the package.

#### Changes proposed in this Pull Request:
* Sync: Namespace the sender

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Part of the Jetpack DNA project - p1HpG7-70O-p2

#### Testing instructions:
* Checkout the branch.
* Enable `WP_DEBUG_LOG`.
* Trigger a full sync.
* Verify sync works well and you have no errors logged.
* Verify tests pass and CI is green.

#### Proposed changelog entry for your changes:
* Sync: Namespace the sender

### CODE REVIEW

**Review by lezama — DISMISSED** [review]
tested and it still syncs, let's merge!

**Comment by lezama** [comment]
rebased

**Comment by tyxla** [comment]
Can I get another ✅ on this one?

**Review by lezama — APPROVED** [review]
Tested, it sends! no errors! 🚢 ing

**Pull request merged**
