### PR TITLE
package.json: Add packageManager field for corepack compatibility

### PR DESCRIPTION
**Pull request by mreishus**
## Proposed changes:

* Adds a `packageManager` field to `package.json` to specify `pnpm@9.3.0`.

This aligns with the version currently used in the GitHub Actions workflow and falls within the engines.pnpm range.

When using the repo with Devbox and Corepack, Corepack may attempt to download a newer pnpm version outside this range. Adding the packageManager field improves compatibility for Corepack users, ensuring consistency across local development and CI environments without impacting others.

I chose 9.3 specifically because it lines up with that's in the github actions.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by anomiex** [comment]
We didn't stay with 9.3.0 specifically. We don't want to constantly chase updates, so as long as things keep working we let the `^9.3.0` in `.engines.pnpm` allow later versions to be used. To keep that behavior, it looks like we should set `manage-package-manager-versions=false` in `.npmrc` so pnpm 10 (once that comes out and we switch to it) doesn't try to exactly match this field.

Probably we should also add something to [the existing version checks](https://github.com/Automattic/jetpack/blob/4c314a7077a38c8f1f9b1cad41a3d926f1e7485b/.github/files/lint-project-structure.sh#L624-L644) to verify that this aligns with all the other pnpm version fields.

**Comment by mreishus** [comment]
So, I first tried 9.11 and one of the checks failed. I'll repush that to see what it was.
Sadly, it seems like this field cannot take a range. If I don't provide this value and use devbox+corepack, it starts writing to it, like: `+       "packageManager": "pnpm@9.11.0+sha512.0a203ffaed5a3f63242cd064c8fb5892366c103e328079318f78062f24ea8c9d50bc6a47aa3567cabefd824d170e78fa2745ed1f16b13
2e16436146b7688f19b"`

**Comment by mreishus** [comment]
I see, so it says this:
```
Run pnpm/action-setup@v4.0.0
Running self-installer...
  Error: Multiple versions of pnpm specified:
    - version 9.3.0 in the GitHub Action config with the key "version"
    - version pnpm@9.11.0 in the package.json with the key "packageManager"
 ```
 
 In reference to this which is also not autoupdating:
 https://github.com/Automattic/jetpack/blob/5878fb5a5a07b94580fe4dec8c057e7b6125c124/.github/versions.sh#L5

**Comment by mreishus** [comment]
We could try this, is this too many static versions? I know @sgomes is currently trying to get JP to work in devbox without corepack (we're both using devbox now). Maybe we won't need this..

**Comment by mreishus** [comment]
Ok, we found two ways to get JP to work in Devbox; but both require changing files committed to the repo.

* Option 1: Add `"packageManager": "pnpm@9.11.0"` to package.json.
  * Devbox users turn corepack on and let it install the pnpm version specified here. 
  * This lines up with the `engines.pnpm` in the same file as well as `PNPM_VERSION` in `.github/versions.sh`.
* Option 2: Add `use-node-version=22.9.0` to `.npmrc`.
  * Devbox users turn corepack off and add a pnpm version satisfying the current requirements to their devbox. Then pnpm will install this node version.
  * This aligns with `.nvmrc`.

**Comment by anomiex** [comment]
I didn't have any objection to setting `packageManager` to 9.3.0, matching `.github/version.sh`. As long as we set the npmrc setting so local pnpm doesn't try to enforce that version once we move to v10.

> Option 2: Add `use-node-version=22.9.0` to `.npmrc`. 

Again, we don't really want to force a particular version of node on everyone.

**Comment by mreishus** [comment]
OK, I updated it to provide the info for corepack users.

**Review by anomiex — APPROVED** [review]
I added the linting check I had asked for earlier. If that looks good to you, let's go ahead.

**Pull request merged**
