### PR TITLE
Move JITM's REST API endpoints into the package

### PR DESCRIPTION
**Pull request by leogermani**
This PR moves the REST APIs endpoints used by the JITM into the package to make it independent from the Jetpack plugin

#### Changes proposed in this Pull Request:

* Move JITM's REST API endpoints into the package

#### Jetpack product discussion

1199702491434901-as-1199702491434934

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Checkout this PR
* Make sure to refresh the composer autoloader for the Jetpack plugin and the JITM package ( `composer dump-autoload` in their folders should do it)
* Visit your admin and make sure JITMs are still working
* Open the Network inspector
* Edit `Automattic\Jetpack\JITMS\Rest_Api_Endpoints::delete_jitm_message_permission_callback` and force it to return the `WP_Error`.
* On the browser, click to dismiss the JITM
* Check the debugger and make sure the error code and message are correct.
* Undo your changes to the file
* Dismiss the message and make sure it works

QUESTION:

I had to enable the JITM always, and not only in `is_admin` otherwise the REST endpoints would not be registered. I tried checking on the `REST_REQUEST` constant but apparently we are too early in the flow there. Do you think that's ok? Any ideas?

I thought about adding a `is_admin` check inside the package, but I guess once the package files were loaded the worse in terms of performance has already happened...

### CODE REVIEW

**Comment by kbrown9** [comment]
> I had to enable the JITM always, and not only in is_admin otherwise the REST endpoints would not be registered. I tried checking on the REST_REQUEST constant but apparently we are too early in the flow there. Do you think that's ok? Any ideas?

I suppose one alternative is to have the consumer plugin add the `rest_api_init` hook that sets up the JITM endpoints. I don't know that we want to add complexity for the consumer plugin though.

**Comment by leogermani** [comment]
> > I had to enable the JITM always, and not only in is_admin otherwise the REST endpoints would not be registered. I tried checking on the REST_REQUEST constant but apparently we are too early in the flow there. Do you think that's ok? Any ideas?
> 
> I suppose one alternative is to have the consumer plugin add the `rest_api_init` hook that sets up the JITM endpoints. I don't know that we want to add complexity for the consumer plugin though.

As we spoke in the call today, JITM is a very small package and it should not be a problem if we load it by default. It actually does nothing besides loading the files, and it does not interfere with anything that gets to the client. It should be impossible to detect any difference in performance.

**Review by kbrown9 — APPROVED** [review]
I tested using the provided testing instructions, and this worked well for me. I also used the `wp jetpack options get hide_jitm` command to verify that a successful JITM dismissal added the dismissed JITM to Jetpack's `hide_jitms` options. 

I agree that the performance impact of loading the JITM package files on non-admin page loads should be negligible.

**Comment by kbrown9** [comment]
It looks like Jetpack's `composer.lock` file needs to be updated:

`Error: projects/plugins/jetpack/composer.lock is not up to date!`

**Comment by leogermani** [comment]
> It looks like Jetpack's `composer.lock` file needs to be updated:
> 
> `Error: projects/plugins/jetpack/composer.lock is not up to date!`

Done!

**Comment by kbrown9** [comment]
I can't open this branch on a JN site because of an Incompatible Archive error. The PR needed a master merge anyway, so I pushed a commit for that. Hopefully that will also resolve the incompatible archive.

**Review by kbrown9 — APPROVED** [review]
I retested after the recent commits, and everything is still working as expected.

**Pull request merged**
