### PR TITLE
Settings: Improve Instant Search toggle UX

### LINKED ISSUE #19386: Search: Enable instant search toggle strange behavior
#### Steps to reproduce the issue

1. Go to Jetpack Settings > Performance
2. Toggle on Enable Search
3. Toggle off and watch the "Enable instant search" toggle go on and off again

Could only reproduce that on my self hosted site ^

Also: 

4. Toggle on Enable Search
5. Toggle off Enable Instant Search
6. Toggle off Enable Search
7. See the Enable Instant Search Toggle go on again before going off.

Can reproduce everywhere including JN sites.

#### What I expected

The child toggles to behave like others - just stay off when turning off the parent toggle.

**Screenshots**

Surfaced in 9.6 testing, but happens in 9.5 as well. Video here: p8oabR-DS-p2#comment-5124

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #19386. Reported originally by @atanas-dev.

#### Changes proposed in this Pull Request:
* Changes the toggle behavior for the Search card in the Performance settings section.
  * Before: Instant Search toggle would be disabled if the search module was disabled.
  * After: Instant Search toggle is always enabled. If toggled on while the search module is disabled, the search module will also be toggled on.

This fixes a bug where the Instant Search toggle would flip on and off when disabling both Search and Instant Search settings via the Search toggle.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change on your site with a Jetpack Search subscription.
* Navigate to `/wp-admin/admin.php?page=jetpack#/performance`.
* Try toggling the Search module toggle and the Instant Search setting toggle. Ensure that they all work as expected. For example:
  a) With both toggles disabled, toggle on the search module.
  b) With both toggles disabled, toggle on the Instant Search setting.
  c) With just the search module enabled, toggle off the search module.

### CODE REVIEW

**Comment by jeherve** [comment]
I find it makes for a bit of an odd behaviour when you disable the Search module:

https://user-images.githubusercontent.com/426388/113411651-a6ff1d00-93b6-11eb-8bd2-bd23445ac126.mov

Maybe we could work around that?

I've moved this PR into the next milestone, since that's not an issue that was introduced in this release. We can take our time to iterate on this until the next release.

**Comment by jsnmoon** [comment]
> I find it makes for a bit of an odd behaviour when you disable the Search module:
> [...]
> Maybe we could work around that? (@jeherve)

Are you sure you've built the assets for the page via `yarn build`/`watch`? Here's what I'm seeing on Chrome:

https://user-images.githubusercontent.com/4044428/113783856-a38acf00-96f1-11eb-8fda-793ea5e319cc.mp4

**Comment by sdixon194** [comment]
Hmm yeah, this PR works for me without an issue and fixes the bug. Are you able to test again @jeherve or were we missing something?

**Review by jeherve — APPROVED** [review]
I cannot actually reproduce anymore, so this should be good to go 👍

**Pull request merged**
