### PR TITLE
Remove/site editor styles entry point

### LINKED ISSUE #57997: Follow up on site editor "Styles" entry point.
With the nav menu changes in Gutenberg v11.9, we updated the new entry point "Editor (styles)" to load the editor in the calypso iframe.  We also hid the new "Styles" button for the time being.  This was all done in https://github.com/Automattic/jetpack/pull/21691.

While there is already some discussion (p1636465118016400-slack-C01A7D4GPGC) about removing the "Styles" button in core Gutenberg, if this does end up sticking around we will need to do some extra calypso-side work to make this function as expected so that we can stop hiding it.  Essentially it opens the site editor with an extra query param to ensure the global styles sidebar starts open, so instead of having the button open our general site-editor URL as normal we will somehow need to pass the extra query params down to the iframe that is loading the editor.

### PR DESCRIPTION
**Pull request by agrullon95**
#### Changes proposed in this Pull Request:

* These changes remove the nonexistent site editor "styles" entry point under the Calypso "Appearance" sidebar menu.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

**Atomic Site**

- Use an existing atomic site or create a new one.
- Install and activate [Jetpack beta](https://jetpack.com/download-jetpack-beta/) (Calypso "Plugin > Add New" sidebar menu then click the `Upload` button on the top right side of the page).
- Go to `wp-admin/admin.php?page=jetpack-beta&plugin=jetpack`
- Click on Search for a Feature Branch and enter this branch name: 
- Refresh the site and ensure that the "Editor (styles)" submenu does not appear under the Calypso "Appearance" sidebar menu.

**Simple Site**

- Use an existing simple site or create a new one.
- SSH into your sandbox and make sure you’ve CD’d into `/home/wpcom/public_html/`
- Run this script: `bin/jetpack-downloader test jetpack remove/site-editor-styles-entry-point`
- Make sure your test site is sandboxed and test things out to make sure they work/nothing breaks/etc
- Refresh the site and ensure that the "Editor (styles)" submenu does not appear under the Calypso "Appearance" sidebar menu.
- Extra: Run this script to revert the changes (clean up jetpack plugin in your sandbox): `bin/jetpack-downloader reset jetpack`

Fixes Automattic/wp-calypso#57997

### CODE REVIEW

**Comment by edanzer** [comment]
Changes look straightforward and tests as corrected. 

**Atomic**
 - [x] Loaded branch via Jetpack beta plugin and confirmed Editor (styles) menu item does not appear. Also lightly tested related menu links and site and confirmed no other obvious issues.

**Simple**
 - [x] Loaded branch via sandbox ssh commands and confirmed Editor (styles) menu item does not appear. Also just lightly tested related menu links and site and confirmed no other obvious issues.

**Other**
- Note there does still seem to be a check failing that should be resolved before merging.

**Review by edanzer — DISMISSED** [review]

**Review by jeyip — DISMISSED** [review]
## Testing
### Requirements
- [x] On atomic sites, Editor (styles)" submenu does not appear under the Calypso "Appearance" sidebar menu
- [x] On simple sites, Editor (styles)" submenu does not appear under the Calypso "Appearance" sidebar menu

### Browsers
- [x] Chrome

**Review by zinigor — DISMISSED** [review]

**Comment by zinigor** [comment]
This will require a merge from trunk, after which it should automatically merge.

**Comment by agrullon95** [comment]
Merged new PR with these changes: https://github.com/Automattic/jetpack/pull/27263.

**Pull request closed without merging**
