### PR TITLE
Social: Remove share limits UI and data logic

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Before we can migrate shares data initial state, we need to remove the share limits UI  and the corresponding data store logic, which uses initial state, otherwise we will need to migrate that unused initial state as well as the corresponding logic. Thus we want to remove that first.

## Proposed changes:

* <s>Remove unused `show_advanced_plan_upgrade_nudge` and the related components because it was already disabled in  D151913-code</s> Extracted to #38926
* Remove share limits UI and data store logic

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Goto Social admin page
* Confirm that the page loads correctly and the shares data is displayed as before
* Create a new post and open Jetpack/Social sidebar
* Wait for connection test results to finish
* Confirm that the connections remain enabled after test results, because we previously it depended upon `numberOfSharesRemaining`

### CODE REVIEW

**Review by spsiddarthan — COMMENTED** [review]
We are removing quite a few things here, and some of them are unrelated to each other. We are likely to not test something in one of the four environments (jetpack/simple/atomic/social plugin) in such a big change. 

Let's break it down into smaller shippable segments, feel free to break it down as you deem fit, I thought the following will be a good way to do it. 

- The first PR can just remove the Advanced Plan Nudge . Your commit [here](https://github.com/Automattic/jetpack/pull/38904/commits/1748a43d4a308d2ec545b37a446e0193729b91a5) can be a PR of its own for example. 
- The share count nudge can be removed in the second one. 
- The connection checks can be the third PR. It is fiddling with things  like `isRePublicizeFeatureAvailable` and it would be good to test those in its own PR.

**Comment by manzoorwanijk** [comment]
> We are removing quite a few things here, and some of them are unrelated to each other. We are likely to not test something in one of the four environments (jetpack/simple/atomic/social plugin) in such a big change.
> 
> Let's break it down into smaller shippable segments, feel free to break it down as you deem fit, I thought the following will be a good way to do it.
> 
> * The first PR can just remove the Advanced Plan Nudge . Your commit [here](https://github.com/Automattic/jetpack/pull/38904/commits/1748a43d4a308d2ec545b37a446e0193729b91a5) can be a PR of its own for example.
> * The share count nudge can be removed in the second one.
> * The connection checks can be the third PR. It is fiddling with things  like `isRePublicizeFeatureAvailable` and it would be good to test those in its own PR.

Thank you for your suggestion SId. Here is the first PR - [Remove unused show_advanced_plan_upgrade_nudge](https://github.com/Automattic/jetpack/pull/38926#top)

**Review by spsiddarthan — COMMENTED** [review]
Code looks good, but I couldn't see the upgrade nudge on the free plan. 

This Branch 

Screenshot 2024-08-19 at 12 24 46

Bleeding Edge

Screenshot 2024-08-19 at 12 25 19

A note for myself/next reviewer for few additional things to test:
- [ ] Ensure sharing to Instagram on Jetpack, Social, Simple and Atomic with 1 non-Instagram connection
- [ ] Ensure sharing to Instagram on Jetpack, Social, Simple and Atomic with 1 Instagram and 1 non-instagram connection
- [ ] Ensure sharing to 1 Instagram connection on Jetpack, Social, Simple and Atomic with 1 non-Instagram connection
- [ ] Test for upgrade nudges
- [ ] Test resharing on Jetpack, Social, Simple (need a paid plan) and Atomic
- [ ] Test advanced plan features on Jetpack/Social

**Comment by manzoorwanijk** [comment]
> Code looks good, but I couldn't see the upgrade nudge on the free plan.

Fixed. Thanks

**Comment by spsiddarthan** [comment]
Screenshot 2024-08-19 at 20 00 40


We are showing the nudges on Atomic.

**Comment by manzoorwanijk** [comment]
> We are showing the nudges on Atomic.

Thank you for catching that. I have restored the logic as before that used a WPCOM check for that updrade nudge.

**Review by gmjuhasz — DISMISSED** [review]
The removals are resonable and tested well on jp/simple/atomic without errors

**Review by gmjuhasz — APPROVED** [review]

**Pull request merged**
