### PR TITLE
Search should not require user connection

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
A site level connection is enough for Search to work. And actually in previous versions, we only checked site connection, and I think we should keep doing so.

If user want to connect an account, then he could go to My Jetpack page / or if the user doesn't have a subscription, he could get user connected by purchasing search product on the upsell page.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Prepare a disconnected site with Jetpack Search subscription
* Open `/wp-admin/admin.php?page=jetpack-search`
* Click `login` or `Get Jetpack Search` button, but don't authorize on the next page
* Open `/wp-admin/admin.php?page=jetpack-search` again
* Ensure Search dashboard works
* Ensure Search front end works
* Open `/wp-admin/admin.php?page=my-jetpack`
* Ensure Search doesn't require user connection on My Jetpack page

Screen Shot 2022-07-25 at 4 47 21 PM

Screen Shot 2022-07-25 at 4 51 54 PM

### CODE REVIEW

**Comment by leogermani** [comment]
Hi Jasper,

What's the use case here? I think the main reason we were requiring a user connection is because in order to buy a paid product the user needs to connect anyway...

**Comment by kangzj** [comment]
Hi @leogermani, Thanks for the question. The scenario might be a bit rare but just want to loosen the requirements running search - If a user only connects the site but not with a user (interrupted or sth), and the site has a subscription already (which might not be under the same user that clicks the button), then Search should be still just working. Does that make sense? Or you think it's totally not necessary?

**Comment by leogermani** [comment]
ok @kangzj , sorry for take so long to get back here.

I wanted to test it to make sure the initial flow would not break if I was only site connected. Everything seems fine and I don't see any issues. I also tested the edge case you described and Search works.

If there is no problem from the Search perspective for the site to run without a connected user, we should be fine.

If you'd like to refresh the PR I'm happy to approve it

**Comment by kangzj** [comment]
Hi @leogermani Thanks for looking into this 👍 

I've updated it and would appreciate another look please 😄 

Cheers

**Comment by leogermani** [comment]
Sorry Jasper, it seems there are still a bunch of conflicts to be resolved

**Comment by kangzj** [comment]
@leogermani It went out of date so fast 😄 Let's try again 🤞 Thanks

**Review by leogermani — APPROVED** [review]

**Comment by kangzj** [comment]
Thanks @leogermani 🙌

**Pull request merged**
