### PR TITLE
Clarify GPLv2 or later

### PR DESCRIPTION
**Pull request by pesieminski**
Added header to clarify that license is GPL 2+, not GPL 2

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

### CODE REVIEW

**Comment by jeherve** [comment]
Related: #6609

**Comment by jeherve** [comment]
Fixes #7876

**Comment by dereksmart** [comment]
Thanks @pesieminski!

**Comment by dereksmart** [comment]
added to the 5.4 release 6aedc4e1c

**Pull request merged**
