### PR TITLE
Connection: show full screen connection banner modal in JP dash

### LINKED ISSUE #8618: Update disconnected landing page in Jetpack dashboard view
The disconnected landing page (aka our dismissible full-screen banner) in the Jetpack dashboard view needs to be updated to align with our Jetpack.com site content and styles.

Though this landing page appears on both the Plugin directory view and the Jetpack dashboard view, the Jetpack dashboard view will not have a dismissible x in the upper right corner and "not now" text link below the first CTA button—this view will be full-screen. I've created a separate Issue for the Plugin directory view [here](https://github.com/Automattic/jetpack/issues/8617).

ref: p6TEKc-1P8-p2

**UPDATE (Dec 07, 2018)**
We have updated designs for this page that use the same layout, add one additional section, and update the copy to align with recent Jetpack.com homepage updates. See related issue: #10563 for links to assets and all updated copy.

disconnected full-screen banner

cc @richardmuscat @jeffgolenski @rickybanister

### LINKED ISSUE #10563: Connection banner: add new Performance section
Introduce new Performance section in the disconnected connection banner that appears on the Plugins page and Jetpack Dashboard. Update copy to better align with updates made to the Jetpack.com homepage ([#](https://github.com/Automattic/jetpack-com/issues/96)).

ref: p1HpG7-5J1#comment-28364

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10563
Fixes #8618

#### Changes proposed in this Pull Request:

That modal was only loaded in the Plugins screen; let's load it in the Jetpack menu as well.

#### Notes

Since we are getting rid of the old connection component that used to be displayed on the Jetpack dashboard page, we now have to reload the page when you disconnect your site from WordPress.com, so the new modal can appear again.

By doing so, we do not see the notice that appears at the top of the Jetpack dashboard after a disconnection, inviting you to take a survey to tell us why you disconnected.

screenshot 2018-12-10 at 16 49 07

#### Testing instructions:

* Start from a site where Jetpack is not active.
* Activate the plugin.
* Check the connection modal appearing after the plugin is activated.
* Go to the Jetpack menu. You should see the same modal.

#### Proposed changelog entry for your changes:

* Improve the connection flow for new Jetpack users.

### CODE REVIEW

**Comment by joanrho** [comment]
@jeherve Thank you! This looks wonderful and works as expected. 

The Plugins page modal is just perfect and the Jetpack Dashboard page looks great as well (I saw your note above about the layout issue at the bottom of the connection modal on this page—that was my only comment while testing).

**Comment by jeherve** [comment]
Note that we'll also need to test what happens when you disconnect from WordPress.com, as I removed elements from the dashboard that are usually displayed there once you disconnect.

**Comment by joanrho** [comment]
Props to @MichaelArestad for the commit that fixed the CSS! 🌟🎉

**Review by keoshi — CHANGES_REQUESTED** [review]
> Go to the Jetpack menu. You should see the same modal.

I did not see the modal appear on this page after activating the plugin. Am I doing something wrong?

**Comment by keoshi** [comment]
@jeherve Nope, fresh site with no previous connection.

**Review by keoshi — DISMISSED** [review]
Finally was able to test this properly. Jetpack beta seems to lose the branch association every time I deactivate JP, but this worked for me:

> Deactivated JP > Opened JP Beta > Reselected the branch (nothing seemed to be selected) > JP was auto-activated > Opened Jetpack and saw the modal

Looks good, let's 🚢

**Comment by oskosk** [comment]
Was about to rebase but I don't know what's happening here with jetpack-speed.svg. Seems like you're introducing it here but also @jeffgolenski already introduced it in  #10867

**Comment by jeherve** [comment]
I have now rebased.

**Review by oskosk — APPROVED** [review]
LGTM!

**Pull request merged**
