### PR TITLE
Backup: Use real site title (name) when showing progresss text on admin page

### LINKED ISSUE #23619: Backup: Admin page - Fix site title on progress bar
The Figma files used the fantasy site title Groovy Site for communicating the "here goes site title" on designs.

It seems that we ended hardcoding that title in production for representing the state of progress of a site backup

image

To reproduce.

1. On a fresh site,  install Backup and connect it paying for a plan
2. Expect to be back on the Backup admin page and see the progress bar reading "Backin up your Groovy Site"

### PR DESCRIPTION
**Pull request by oskosk**
Fixes rendering of rogue site title

  image

Fixes #23619

#### Changes proposed in this Pull Request:

* Leverages the site title in the message shown while a backup is in progress

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

**Fresh site**
1. On a fresh site running this branch ([JN link](https://jurassic.ninja/create?jetpack-beta&branches.jetpack-backup=fix/backup-site-title-on-progress&wp-debug-log)), install Backup and connect it paying for a plan
2. Expect to be back on the Backup admin page and see the progress bar reading "Backing up your Site Name" (where Site Name) should be your real site name)
    image

**On a dev environment**
1. Checkout this branch
2. Visit the Backup admin page, and open the dev console, then switch to the Component tab
4. Find the <Backups/> component and updated the first "Select" entry to read `1`.   
  image
5. Expect to see the progress status showing your site's title
  image

### CODE REVIEW

**Review by vianasw — APPROVED** [review]
Tested and it works as intended. The code is pretty straightforward. Thanks for these changes!

**Review by keoshi — APPROVED** [review]
LGTM. Thanks for doing this, Oscar!

**Comment by bindlegirl** [comment]
Tested and it looks good 👍

**Comment by oskosk** [comment]
Thanks folks!

**Review by retrofox — APPROVED** [review]
LGTM

**Pull request merged**
