### PR TITLE
Updates Travis to generate code coverage reports

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Changes phpunit to do code coverage and sends it to Codecov

#### Changes proposed in this Pull Request:

* This integrates codecov.io and Travis-CI.

#### Testing instructions:

* Check to see if coverage reports are generated by Travis.
* Check to see if Codecov gets reports.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by jeherve** [comment]
Tests seem to pass 🎉 
https://travis-ci.org/Automattic/jetpack/jobs/614124146?utm_medium=notification&utm_source=github_status

**Comment by ChaosExAnima** [comment]
@jeherve - yeah, but it's still not sending the results to Code Climate: https://travis-ci.org/Automattic/jetpack/jobs/614124146#L1430

This worked on my local, will continue tinkering. I think I'm pretty close :)

**Comment by ChaosExAnima** [comment]
Okay, confirm that Code Climate says it's getting the test results: https://travis-ci.org/Automattic/jetpack/jobs/614140847#L1430

Can I get a review? :)

**Review by jeherve — APPROVED** [review]
Nicely done! Let's merge this and see how it behaves with the next few PRs in the next few days!

**Pull request merged**
