### PR TITLE
Remove local IP check as IPs can resolve differently from localhost

### PR DESCRIPTION
**Pull request by gravityrail**
When developing on VVV with a public domain, VVV sets up the domain to resolve to localhost, or another non-routable address, EVEN THOUGH it is visible to other hosts as a public IP via `vagrant share`.

Many hosts (particularly dev hosts) have a similar setup. Currently our `is_usable_domain` check is failing for hosts with this setup by incorrectly assuming that the domain resolves to the same IP everywhere on the internet.

Since we already do an IP lookup by domain from WPCOM during the register() step, I think we can safely remove this check from the Jetpack codebase in favour of just failing when the user hits register().

### CODE REVIEW

**Comment by kraftbj** [comment]
For history, the check was added a couple years ago in https://github.com/Automattic/jetpack/pull/2207 to make the process faster for abort vs waiting for WP.com.

**Comment by gravityrail** [comment]
@kraftbj - perhaps instead of removing this, we should try first to resolve the current site's domain using an external DNS like 8.8.8.8. Then we can see if it resolves _publicly_ to a routable IP.

**Comment by kraftbj** [comment]
@gravityrail I don't think we can do that in PHP without extra packages that wouldn't be on anyone's server. I don't feel strongly about it; just wanted to provide context for why it was there in the first place.

**Comment by gravityrail** [comment]
Can't we? ;)

Added a DNS client in PHP. Took me way longer to do this than was probably worthwhile.

**Comment by kraftbj** [comment]
I should have known better than to say `can't` to you.

**Comment by gravityrail** [comment]
TODO: remove those `echo` statements

**Comment by withinboredom** [comment]
oh no ... here's my unsolicited 2¢

1. It's likely any host worth their salt will be transparently rerouting port 53 UDP to *their* dns servers. This is also VERY common in home routers. You'll end up getting an internal network IP instead of the public ip depending on how this is set up.
2. Some linux installations do this by default, see [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html). There's extremely good reasons to do this on your personal linux box or server. So, you'll end up getting the same result that you would if you used the system libraries.
3. You should use both of Google's public dns servers, in case one is down (it happens, believe it or not. They don't have an SLA...)
4. Some countries forbid using their public dns servers
5. Google Public DNS validates DNSSEC, which might cause problems if it's invalid. We should handle that case.
6. For non-ascii characters in the domain you need to use punycode ... but double check that.
7. People may not agree to Google's privacy policy, and the information Google collects by using their resolver.
8. There's probably more if I stop and think about this longer.

If the only reason to do this is because we don't want users to wait a couple seconds, we should just remove this code and have them wait a couple seconds.

**Comment by withinboredom** [comment]
One thing I forgot, Google *does* offer dns over https, which means you'll know you're talking to Google's servers. Because hey, ssl.

**Comment by kraftbj** [comment]
I think removing the check outright (and relying on WordPress.com to verify it can reach the site) is better than trying to make this check do hoops to verify the site is externally accessible.

**Comment by gravityrail** [comment]
Closing in favor of #9792

**Pull request closed without merging**
