### PR TITLE
Try to fix failing recommendations.test.js and waf-blocking.test.js E2E tests

### PR DESCRIPTION
**Pull request by pypt**
"Jetpack post-connection e2e tests" have been failing since forever:

https://github.com/Automattic/jetpack/actions/workflows/e2e-tests.yml

e.g. here for https://github.com/Automattic/jetpack/pull/34739:

https://github.com/Automattic/jetpack/actions/runs/7348501314/job/20006837157?pr=34739

As per https://github.com/Automattic/jetpack/pull/34796#pullrequestreview-1798540385, I've updated XPath selectors that check for the plan in the rendered webpage.

@jboland88, @ArSn, you've last touched this code, could you maybe have a look? I'm not familiar with those tests myself.

## Proposed changes:

See above.

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Make sure the tests succeed.
* Make sure what needs to get tested still gets tested.

### CODE REVIEW

**Comment by pypt** [comment]
This PR makes the two tests flaky:

https://github.com/Automattic/jetpack/actions/runs/7349027801/job/20008327659?pr=34796

```
Running 2 tests using 1 worker

Warning: Plugin 'jetpack' is already active.

  ✘  1 specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) (43.3s)
Warning: Plugin 'jetpack' is already active.

  ✓  2 specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) (retry #1) (22.8s)
Warning: Plugin 'jetpack' is already active.

  ✓  3 specs/post-connection/waf-blocking.test.js:23:2 › WAF Blocking › Block a simple request (841ms)


  1) specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) › Verify Site Accelerator is disabled 

    Error: Site Accelerator should be disabled

    expect(received).toBeTruthy()

    Received: false

      124 | 		const isSiteAcceleratorFeatureEnabled =
      125 | 			await recommendationsPage.isSiteAcceleratorFeatureEnabled();
    > 126 | 		expect( isSiteAcceleratorFeatureEnabled, 'Site Accelerator should be disabled' ).toBeTruthy();
          | 		                                                                                 ^
      127 | 	} );
      128 | } );
      129 |

        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:126:[84](https://github.com/Automattic/jetpack/actions/runs/7349027801/job/20008327659?pr=34796#step:12:85)
        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:123:2

    attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────
    output/results/specs-post-connection-recommendations-Recommendations-Jetpack-Assistant-/test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #3: video (video/webm) ──────────────────────────────────────────────────────────────
    output/results/specs-post-connection-recommendations-Recommendations-Jetpack-Assistant-/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 flaky
    specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) ───────
  1 passed (5.5m)
Error:   1) specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) › Verify Site Accelerator is disabled 
    Error: Site Accelerator should be disabled

    expect(received).toBeTruthy()

    Received: false

      124 | 		const isSiteAcceleratorFeatureEnabled =
      125 | 			await recommendationsPage.isSiteAcceleratorFeatureEnabled();
    > 126 | 		expect( isSiteAcceleratorFeatureEnabled, 'Site Accelerator should be disabled' ).toBeTruthy();
          | 		                                                                                 ^
      127 | 	} );
      128 | } );
      129 |

        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:126:84
        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:123:2
Notice:   1 flaky
    specs/post-connection/recommendations.test.js:17:1 › Recommendations (Jetpack Assistant) ───────
  1 passed (5.5m)
```

...but somehow on a retry they seem to pass, so maybe that's still better?

**Review by andrii-lysenko — DISMISSED** [review]
Thanks for working on this. These failing tests definitely need to be fixed.
 
Generally, I don't have strong knowledge on tests, but it seems reasonable to include Plans here. The thing I noticed with these tests though, is that it can't confirm the plan:
Screenshot 2023-12-28 at 17 17 35

It seems that the issue is actually appeared after this change: https://github.com/Automattic/jetpack/pull/34715 . We removed `alt` name, however, `isPlan` function actually relies on the plan here:
https://github.com/Automattic/jetpack/blob/trunk/tools/e2e-commons/pages/wp-admin/jetpack-my-plan.js#L13

Maybe we should update `isPlan` function to correctly check the plan not relying on `alt`. Something like `//h2[contains(@class, "my-plan-card__title") and text()="Jetpack Free"]`. What do you think?

**Comment by pypt** [comment]
Thanks @andrii-lysenko , reverted my hack and applied your suggestion in 06ad8b2.

The [first attempt to run one of the tests still fails, but the retry (and thus the whole test) succeeds](https://github.com/Automattic/jetpack/actions/runs/7398323571/job/20127424825?pr=34796#step:12:136):

```
Running 2 tests using 1 worker

Warning: Plugin 'jetpack' is already active.

  ✘  1 specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) (4ms)
Warning: Plugin 'jetpack' is already active.

  ✓  2 specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) (retry #1) (21.7s)
Warning: Plugin 'jetpack' is already active.

  ✓  3 specs/post-connection/waf-blocking.test.js:27:2 › WAF Blocking › Block a simple request (929ms)


  1) specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) ──────

    Error: 'Jetpack Start provisioning failed: -10520

       at ../../../../../tools/e2e-commons/helpers/partner-provisioning.js:38

      36 | 		logger.cli( 'Successful provisioning' );
      37 | 	} else {
    > 38 | 		throw new Error( `'Jetpack Start provisioning failed: ${ json.error }` );
         | 		      ^
      39 | 	}
      40 |
      41 | 	await execWpCommand(

        at provisionJetpackStartConnection (/home/runner/work/jetpack/jetpack/tools/e2e-commons/helpers/partner-provisioning.js:38:9)
        at connect (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:121:3)
        at ensureConnectedState (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:107:3)
        at buildPrerequisites (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:[85](https://github.com/Automattic/jetpack/actions/runs/7398323571/job/20127424825?pr=34796#step:12:86):5)
        at Object.build (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:63:4)
        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:8:2

    attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────
    output/results/specs-post-connection-recommendations-Recommendations-Jetpack-Assistant-/test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 flaky
    specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) ───────
  1 passed (4.8m)
Error:   1) specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) ──────
    Error: 'Jetpack Start provisioning failed: -10520

       at ../../../../../tools/e2e-commons/helpers/partner-provisioning.js:38

      36 | 		logger.cli( 'Successful provisioning' );
      37 | 	} else {
    > 38 | 		throw new Error( `'Jetpack Start provisioning failed: ${ json.error }` );
         | 		      ^
      39 | 	}
      40 |
      41 | 	await execWpCommand(

        at provisionJetpackStartConnection (/home/runner/work/jetpack/jetpack/tools/e2e-commons/helpers/partner-provisioning.js:38:9)
        at connect (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:121:3)
        at ensureConnectedState (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:[107](https://github.com/Automattic/jetpack/actions/runs/7398323571/job/20127424825?pr=34796#step:12:108):3)
        at buildPrerequisites (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:85:5)
        at Object.build (/home/runner/work/jetpack/jetpack/tools/e2e-commons/env/prerequisites.js:63:4)
        at /home/runner/work/jetpack/jetpack/projects/plugins/jetpack/tests/e2e/specs/post-connection/recommendations.test.js:8:2
Notice:   1 flaky
    specs/post-connection/recommendations.test.js:18:1 › Recommendations (Jetpack Assistant) ───────
  1 passed (4.8m)
```

I guess we could leave it at that?

**Review by anomiex — APPROVED** [review]
Looks sensible to me, and tests pass now.

I couldn't reproduce the flakiness when I tried running it locally. 🤷

**Review by andrii-lysenko — APPROVED** [review]
LGTM! Thanks for fixing that!

**Comment by pypt** [comment]
Thank you both!

**Pull request merged**
