### PR TITLE
Minileven: add hook before footer

### PR DESCRIPTION
**Pull request by virendrachandak**
https://github.com/Automattic/jetpack/issues/2105

### CODE REVIEW

**Comment by kraftbj** [comment]
Without making comment on adding this hook or not, couple of nit-picky things regarding the inline docs:
1. Could you update the `@since` to 3.6. We wouldn't add this to a point release.
2. Could you expand the description to include reference to the mobile theme (example: https://github.com/Automattic/jetpack/blob/master/modules/minileven/theme/pub/minileven/footer.php#L37 ). We're working on having an automated directory of hooks, so the extra detail (even though the name of the hook is pretty obvious) would be nice to have.

Thanks for the pull request!

**Comment by virendrachandak** [comment]
Updated the inline docs in https://github.com/Automattic/jetpack/commit/a4f28a3b9e56814f28ba813924ca5d510e84b101

**Comment by virendrachandak** [comment]
Updated inline docs in https://github.com/virendrachandak/jetpack/commit/a4f28a3b9e56814f28ba813924ca5d510e84b101 and https://github.com/virendrachandak/jetpack/commit/cac254283824808c13f079a4d0df80b0454feebe

**Comment by dereksmart** [comment]
I don't see why not. :+1:

**Pull request merged**
