### PR TITLE
Subscriptions Block: Remove logged in view for wpcom

### LINKED ISSUE #15474: Subscriptions Block: Improve different states
The blog subscription block has four states depending on visitors being logged in/out and subscription status.

subscribe_block_states

Yet in the editor you can only see the logged-out state, with no easy way of previewing or changing other states.

image

#### Describe the solution you'd like
At the very least it would be great to have alignment option for other states - as seen in the example above things look particularly bad if a heading/text above the subscription block is centered.

### LINKED ISSUE #18085: Subscriptions Block: Unable to create logged-in centred layout
It appears that it may be difficult to create a centered layout with the subscriptions block in the following scenario. (Active theme: Spearhead, Chrome, MacOS.)

Block in Editor, as added by user …

image

Result logged-in on the front-end.

image

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/Automattic/jetpack/issues/15474
Fixes https://github.com/Automattic/jetpack/issues/18085

#### Changes proposed in this Pull Request:

* Remove the logged in view for WordPress.com so that the Subscriptions block always renders what is in the editor. When a user is logged in to WordPress.com they will still see the email subscription form and can subscribe as normal.

| Before      | After |
| ----------- | ----------- |
|  |  |

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Apply D56029-code to your sandbox.
* Apply this branch to a local Jetpack install
* Confirm that this works correctly on WordPress.com based on testing instructions on D56029-code
* Confirm the subscriptions form works on your Jetpack site still (you will need it to be a publicly accessible site via jurrassic.tube or ngrok) and the subscriptions Jetpack setting turned on.
* Try subscribing and confirm that you can still subscribe to a site.

#### Proposed changelog entry for your changes:

* Not needed.

### CODE REVIEW

**Review by stacimc — CHANGES_REQUESTED** [review]
On wpcom, I was able to see the subscription form both as a logged-in and a not-logged-in user.

When I submitted the form as a logged-in user, it worked as expected, and I received the follow up email at the address I used:
Screen Shot 2021-01-28 at 11 24 22 AM

~~However when I tested as a logged-out user, I got a message saying I was already subscribed (I made 100% sure the email I was using was _not_ already subscribed), and received no email:~~ <-- After rebuilding jetpack, this is no longer happening. It is now working for both logged-in and logged-out users.

**Comment by apeatling** [comment]
> **Update -- I just tried this on a different sandboxed site, and it worked even as a logged-out user. I'm not sure what was different.

Just checked this on a sandboxed site, and it seemed to work okay logged in and logged out.

**Review by stacimc — DISMISSED** [review]
Tested well for me on Jetpack, and the error I saw on wpcom for logged-out is working fine after a rebuild. LGTM!

**Review by jeherve — CHANGES_REQUESTED** [review]
The linting errors will stop us from merging this I'm afraid.

**Comment by apeatling** [comment]
> The linting errors will stop us from merging this I'm afraid.

I think I'll need to mark to ignore these errors because removing these extra escapes breaks the reg ex.

**Comment by apeatling** [comment]
I've added the jetpack textdomain since the ignore does not work. The wpautop() pre-existed this PR, but I can't escape html with this since, or remove it since it will break existing usage.

**Comment by apeatling** [comment]
@jeherve This one look good now?

**Comment by apeatling** [comment]
Nevermind! Seeing one last lint error 🤦🏻  Fixing.

**Review by jeherve — APPROVED** [review]
This looks good to me. It's a big change for WordPress.com so I think it may be good to warn Happiness about the change, but I think it makes for a good change.

**Comment by jeherve** [comment]
r222134-wpcom

**Pull request merged**
