### PR TITLE
Debugger: General Updates

### PR DESCRIPTION
**Pull request by kraftbj**
See p7pQDF-3yz-p2

#### Changes proposed in this Pull Request:

* Removes the contact form.
* Always display advanced debug info.

#### Testing instructions:

* Visit the Jetpack debugger via the footer of the Jetpack admin page.
* Does the Advanced Debug Info automatically show? If yes, that's good.
* Is there a form to contact support? If so, that's not good.

#### Proposed changelog entry for your changes:

Debugger: Improves display of debugging information.

### CODE REVIEW

**Comment by kraftbj** [comment]
There's more to do overall with the in-plugin debugger, but aiming for this to be included in 6.7. Other work can come in future releases; no need to hold up small progress.

**Review by jeherve — CHANGES_REQUESTED** [review]
It works well for me, but I would have one remark regarding the overall layout:

screenshot 2018-10-26 at 10 58 46

I think the "contact us" does not really belong in the list that is defined as "It may be caused by one of these issues, which you can diagnose yourself:". I think it is something you can do afterwards.

It would also stand out more if it was not the last item of a list.

What do you think?

**Review by jeherve — DISMISSED** [review]
I like it better now, thank you.

I wonder if that's not a little too many exclamation marks tough?

> Ask us for help! We are here to help! Contact our Happiness team!. 

What if you were to remove "We are here to help!" and the exclamation mark after "Happiness team"?

**Comment by kraftbj** [comment]
I was just really excited about someone asking for help. Removed in https://github.com/Automattic/jetpack/pull/10253/commits/b6d45bae6809294450b501992faa1f0858e0a50f

**Comment by kraftbj** [comment]
Included some manual code styling and security hardening. There are still a few more left, but require more testing than I'd want to do with the code freeze around the corner. I'll pick up those on a (6.8||Future) PR.

**Review by jeherve — APPROVED** [review]
This works well for me now! 🚢

**Comment by jeherve** [comment]
@danjjohnson This new debugger will ship with Jetpack 6.7. You'll most likely have to update some predefs since we won't have a contact form on the debug page anymore.

Here is how it will look:

screenshot 2018-10-26 at 18 43 25

**Pull request merged**
