### PR TITLE
AI Assistant: simplify prompt logic

### PR DESCRIPTION
**Pull request by nunyvega**
Fixes #

## Proposed changes:

* Simplify prompt to avoid limiting too much the AI, which can cause issues

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1685640365126249-slack-C054LN8RNVA
## Does this pull request change what data or activity we track or use?

No
## Testing instructions:

* Go to the editor
* Use the block to create content
* Modify it with the block. 
* Add your own content and improve it with the block
* Confirm that features work as expected

### CODE REVIEW

**Review by dhasilva — APPROVED** [review]
LGTM! Excellent one

**Review by retrofox — APPROVED** [review]
LGTM

**Review by lhkowalski — APPROVED** [review]
I tested it with different cases that were failing before, like follow up changes on the tone of the generated content, and it's working nicely.

It's really possible to chat with the block.

**Comment by kraftbj** [comment]
[monthly/branch-2023-05-29 d8def2a939]

**Pull request merged**
