### PR TITLE
My Jetpack: Add missing TOS in the product interstitials.

### LINKED ISSUE #29610: TOS missing on My Jetpack upgrade interstitial [Core, Backup, Scan, Akismet]
When a user is not connected, we need to show TOS below the buttons on the plan upgrade My Jetpack interstitials.

Image

p1HpG7-l2l-p2
See task 42 for video walkthrough

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR fixes missing Term of service texts in some of the product interstitial screens. Note that there are guidelines on where TOS should be displayed. Refer to this link for the discussion: p1HpG7-jRz

Screen Shot 2023-03-31 at 4 17 10 PM
Screen Shot 2023-03-31 at 4 18 07 PM
Screen Shot 2023-03-31 at 4 18 24 PM

Fixes #29610

## Proposed changes:
* Update **Product interstitial** component in **My Jetpack** package to render `TermOfService` component.
* Update **Product description** component in **Jetpack** plugin to render `TermOfService` component.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Spin up a  local WP site and checkout in this branch (`add/missing-interstitial-tos`).
    * Build both my jetpack package and jetpack plugin by running the command below
```
jetpack build packages/my-jetpack
jetpack build plugins/jetpack
```
* Or you can Spin up a JN site with Jetpack beta pointing to this branch (`add/missing-interstitial-tos`)
* Connect your site w/ your WPCOM account (You will need jurassic tube to do this if you are running a local WP site)
* Visit all screens below and confirm that the TOS is rendered in the correct place.

URL |  requires connection?
---   | ---
/wp-admin/admin.php?page=my-jetpack#/add-anti-spam   | No
/wp-admin/admin.php?page=my-jetpack#/add-backup   | No
/wp-admin/admin.php?page=my-jetpack#/add-boost  | No
/wp-admin/admin.php?page=my-jetpack#/add-crm  | No
/wp-admin/admin.php?page=my-jetpack#/add-extras  | No
/wp-admin/admin.php?page=my-jetpack#/add-protect  | No
/wp-admin/admin.php?page=my-jetpack#/add-scan   | No
/wp-admin/admin.php?page=my-jetpack#/add-social  | No
/wp-admin/admin.php?page=my-jetpack#/add-search   | No
/wp-admin/admin.php?page=my-jetpack#/add-videopress  | No
/wp-admin/admin.php?page=jetpack#/product/akismet   | ✅  
/wp-admin/admin.php?page=jetpack#/product/backup   | ✅ 
/wp-admin/admin.php?page=jetpack#/product/scan   | ✅ 
/wp-admin/admin.php?page=jetpack#/product/search  | ✅ 
/wp-admin/admin.php?page=jetpack#/product/security  | ✅ 
/wp-admin/admin.php?page=jetpack#/product/videopress  | ✅

### CODE REVIEW

**Comment by jkguidaven** [comment]
@grbicsanja would be nice if you can also review the PR 🙏

**Review by grbicsanja — CHANGES_REQUESTED** [review]
Can we make sure 'Terms of Service' link is not split, maybe carry it to the next line?
Screenshot 2023-03-24 at 12 15 27
Screenshot 2023-03-24 at 12 14 58
Screenshot 2023-03-24 at 12 15 06
Screenshot 2023-03-24 at 12 15 12

**Comment by grbicsanja** [comment]
@jkguidaven I also posted a question here: p1HpG7-lr0 to check if the TOS is positioned correctly because of the vertical spacing.

**Comment by jkguidaven** [comment]
@grbicsanja 'Term of Service' text should no longer split after my change. 👍 
Screen Shot 2023-03-27 at 2 18 44 PM

**Comment by jkguidaven** [comment]
> @jkguidaven I also posted a question here: p1HpG7-lr0 to check if the TOS is positioned correctly because of the vertical spacing.

I'm following the P2 post for updates on the design. 👍

**Comment by grbicsanja** [comment]
@jkguidaven let's add the TOS above each button. Thanks for your patience :).

TOS - option A

**Comment by jkguidaven** [comment]
@grbicsanja I have updated the PR with the new change. Can you have another look?

Just so you know, there is a slight difference between the copy you provided versus the actual implementation. This matches the current pattern used on other screens with the Term of service text.

Screen Shot 2023-03-31 at 4 29 44 PM

I also would like to ask for your input on the TOS text here, particularly on this screen. 
Screen Shot 2023-03-31 at 4 18 24 PM

**Review by grbicsanja — DISMISSED** [review]
LGTM! Thank you @jkguidaven

**Review by monsieur-z — DISMISSED** [review]
It all looks good 👍 

I noticed that in product pages (`/wp-admin/admin.php?page=jetpack#/product/[product-name]`) links are not accessible (they're only distinguishable by their color — they should be underlined in this instance). I know fixing them is not in the scope of this issue, but if that's easy to fix it'd be a nice addition. Let me know if you'd rather have me create a new issue!

Screenshot 2023-04-03 at 11 04 06 AM

**Comment by jkguidaven** [comment]
> It all looks good 👍
> 
> I noticed that in product pages (`/wp-admin/admin.php?page=jetpack#/product/[product-name]`) links are not accessible (they're only distinguishable by their color — they should be underlined in this instance). I know fixing them is not in the scope of this issue, but if that's easy to fix it'd be a nice addition. Let me know if you'd rather have me create a new issue!
> 
> Screenshot 2023-04-03 at 11 04 06 AM

Good catch @monsieur-z 👍. I have fixed that one.

**Review by samiff — APPROVED** [review]

**Pull request merged**
