### PR TITLE
Slideshow Block: Make play/pause icons visible

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes the play/pause button mentioned [here](https://github.com/Automattic/wp-calypso/issues/71453#issuecomment-1448395015) in https://github.com/Automattic/wp-calypso/issues/71453

## Proposed changes:

* Change the fill color for the play/pause icons

Before
before

After

https://user-images.githubusercontent.com/6586048/223654596-bcafa35f-e594-4f4c-b3ce-63fd6791d33e.mp4

### Other information:

- [ ] ~Have you written new tests for your changes, if applicable?~
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None, it's a bug fix

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

1. Pull up a testing site that uses Dara as the theme and has a static homepage. For testing on WP.com run [this command](https://github.com/Automattic/jetpack/pull/29330#issuecomment-1457800976) in sandbox.
2. Add a slideshow to the homepage and let it autoplay
3. Check if the play/pause icons are visible now

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
Looks great, good job 🎉

**Review by DustyReagan — APPROVED** [review]
I see the play and pause buttons now!

**Comment by khristiansnyder** [comment]
It appears the prev/next buttons are fixed, but the pause button still doesn't show the correct icon in my tests. when the block is set to autoplay.

Markup 2023-03-12 at 17 42 37

**Comment by jeherve** [comment]
> It appears the prev/next buttons are fixed, but the pause button still doesn't show the correct icon in my tests. when the block is set to autoplay.

Could you let me know what platform you see this on? (self-hosted, WoA, Simple)?

**Comment by davemart-in** [comment]
@jeherve it can be seen in the wild on https://pontcannapaa.com/ (just make sure your screen resolution is < 600px).

**Comment by khristiansnyder** [comment]
> Could you let me know what platform you see this on? (self-hosted, WoA, Simple)?

This was tested on two simple sites using Dara. 

```
Gutenberg: v15.3.1
Editing Toolkit: 3.58986
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.3
```

Markup on 2023-03-13 at 11:55:54

**Pull request merged**
