### PR TITLE
General: update colors to match upcoming WP 5.7 color changes

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* See https://core.trac.wordpress.org/ticket/49999
* This excludes changes to the Atomic Admin Color Schemes feature.
* That's a lot of color changes, but if I'm being honest I don't really notice the difference for most colors.
* I'm marking this for the 9.6 milestone, so we can have time with these changes sitting in `master` for a while so we can spot any issues.

#### Jetpack product discussion

* Primary issue: #18842 

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Since the changes are spread across many features, you'll need to check colors across all the dashboard.

#### Proposed changelog entry for your changes:

* General: update colors to match upcoming color changes in WordPress 5.7.

### CODE REVIEW

**Comment by jsnmoon** [comment]
> That's a lot of color changes, but if I'm being honest I don't really notice the difference for most colors.

Haha, agreed. The changes for Search are minimal, so this is good to go from our team's perspective 👍

**Review by kraftbj — APPROVED** [review]
I checked out a test site and confirmed the new colors are being used. I did not spot anything that requires additional work. Approving.

**Comment by jeherve** [comment]
I'll merge this now, to avoid having to rebase later on since it touches so many files.

**Comment by jeherve** [comment]
r221672-wpcom

**Comment by kraftbj** [comment]
thanks @jeherve. I meant circle up after the wpcom tests finished, but got pulled off. Thanks for bringing it across the line.

**Pull request merged**
