### PR TITLE
[Carousel]: Handle error if swiper fails to load

### LINKED ISSUE #20235: Error handling needed for when the carousel fails to load
When the Swiper JS fails to load, the spinner will remain permanently displayed, interfering with page functionality.

#### Steps to reproduce the issue

1. Modify the `jetpackSwiperLibraryPath.url` global in your browser console to point to an invalid URL, to simulate an error when loading the carousel JS
2. Click on an image, to open the carousel

#### What I expected
The spinner should initially appear, and then disappear when the error occurs, allowing for the user to resume using the page. Bonus points for showing an error message somewhere.

#### What happened instead
The spinner remained on screen, preventing correct interaction with the page due to its modal nature.

### PR DESCRIPTION
**Pull request by stacimc**
Fixes #20235

#### Changes proposed in this Pull Request:

* Currently if Swiper JS fails to load when a user clicks a gallery image to open the carousel, the loading spinner will spin indefinitely, locking up the page. This PR detects the error and removes the loading spinner so that the user can continue using the rest of the page.

#### Testing instructions:

* Modify the jetpackSwiperLibraryPath.url global in your browser console to point to an invalid URL, to simulate an error when loading the carousel JS
* Click on an image, to open the carousel
* The loading spinner should appear for a moment and then disappear. You should be able to continue using the page.

### CODE REVIEW

**Comment by stacimc** [comment]
Hiding the spinner allows the page to be usable. I'm a bit stumped on what a useful error message would be here, but happy to add one.

**Comment by glendaviesnz** [comment]
I wonder it we should move the `e.preventDefault();  & e.stopPropagation();` from the initial click handler into the `loadSwiper` method and run them in the `jsScript.onload` handler, that way it should fall back to the default click if the swiper load fails, eg. in the case of images linked to media or attachment it will just open the individual photo page?

**Review by andrewserong — APPROVED** [review]
Works nicely, thanks for the fix @stacimc!

**Comment by andrewserong** [comment]
Oh, apologies I didn't see your comment @glendaviesnz — that sounds like a good fallback option, too.

**Comment by stacimc** [comment]
@glendaviesnz I like this idea, but I'm not able to move `e.preventDefault()` and `e.stopPropagation()` into the `onload` because it's asynchronous, so we don't successfully prevent the default behavior. Are you thinking of trying to explicitly re-trigger the default event `onerror`?

**Comment by glendaviesnz** [comment]
> but I'm not able to move `e.preventDefault()` and `e.stopPropagation()` into the `onload` because it's asynchronous,

🤦 Doh, yeh, didn't think of that - I think we should just merge this as is in that case so at least it doesn't leave the carousel in a broken state and circle back to it later to either have a fallback or some sort of error to suggest a page reload

**Comment by stacimc** [comment]
> circle back to it later to either have a fallback or some sort of error to suggest a page reload

Agreed 👍 I'll create a ticket for circling back.

**Review by jeherve — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to release branch in a814c27a8c94b4d7bff08a56c1c7688bd90ec09c

**Pull request merged**
