### PR TITLE
Slideshow Gallery Updates

### PR DESCRIPTION
**Pull request by danielwrobert**
Moved logic to set slide dimensions out of JS and PHP files and added styles to set intrinsic ratio on slide images for responsive sizing.

### CODE REVIEW

**Comment by danielwrobert** [comment]
Updated slide image margins to properly align within themes that have negative margins set. Also updated RTL stylesheet to be in sync with these recent changes.

**Comment by danielwrobert** [comment]
Updated container padding to specify important. If container padding is overwritten by theme styles, the
gallery slides will not display properly.

**Comment by jeffgolenski** [comment]
Tested on: 
iphone 5s: chrome, safari
ipad 2: chrome, safari
mac OSX: chrome, safari, opera, firefox (latest versions)

windows 7: ie8, ie9
windows 8: ie10
windows 10: ie11

The CSS is looking good. 

In the future, I'd love to find a way to execute this code without using important tags. Not just the above changes, but all the lines within these css files. 

cc @dereksmart

**Comment by danielwrobert** [comment]
> In the future, I'd love to find a way to execute this code without using important tags. Not just the above changes, but all the lines within these css files.

@jeffgolenski - I definitely agree. I dislike using `!important` just as much as anyone and I tried to limit where I'd used them above. A couple of the instances were to override some inline styles being added via the jQuery plugin being used to drive the slideshow  that also attempts to add sizing to the image containers on page load. The instances targeting the padding on the main container were to ensure that the padding was not overridden in the theme styles. There were a few bugs related to that and if the padding is altered, the slides will not show up properly - a reasonable case for `!important`. But I am definitely all for re-writing the styles to make the selectors more specific, where needed and ditch the `!important` rules wherever possible! :)

**Comment by danielwrobert** [comment]
@jeffgolenski no worries, I didn't take it that way at all!

I was just specifying why I _did_ use them and also noting that I totally agree with you on ditching as many as possible. :)

**Comment by dereksmart** [comment]
Tested and works well!  Thanks @danielwrobert

**Pull request merged**
