### PR TITLE
Redirects old IE versions to the fallback page.

### LINKED ISSUE #4112: Admin: Create "Unsupported" view for IE10 and below
Wordpress.com drops support for IE10 and below, and since we're essentially an extension of wpcom, we should follow suit as well. 

We need to create a custom "view" for IE10 and below, similar to this:

screen shot 2016-06-13 at 12 57 40 pm

### PR DESCRIPTION
**Pull request by zinigor**
Fixes #4112.

#### Changes proposed in this Pull Request:
- Adds a new redirection header inside a conditional comment that will make older IE versions redirect to the fallback page.
- Adds a notice on the fallback page for older IE versions.

#### Testing instructions:
- Get a device that has Internet Explorer on it.
- Make IE work in IE9 mode.
- Visit the Jetpack settings page, you should be redirected to the fallback page with `page=jetpack_modules` in the URL.
- You should also see a notice saying that your browser is not supported.

#### Problems with this PR:
- ~~The issue that this PR aims to fix says that we need a fallback view for all old IE versions including IE10. But IE10 does not support conditional comments, on which this PR is based. We can probably let IE10 handle the React page - it works pretty well based on my cursory glance.~~ IE10 is now handled similarly to previous IE versions. No React for you, IE!

#### Awesome preview
img_20160803_174641980

### CODE REVIEW

**Comment by oskosk** [comment]
@zinigor I've tried this branch from inside Browserstack IE10. In IE9 Browser mode and couldn't get to see the redirect nor the notice. 

Regarding how the Admin Page looks on IE10. Apparently our navigation component is not there, and some things are floating around. 


image

**Comment by oskosk** [comment]
I'll check again! thanks!

**Comment by eliorivero** [comment]
@zinigor I've pushed a commit replacing ES6's `Array.prototype.includes()` with lodash's `includes()`. It's not supported in IE 10 so it was throwing a JS error when I clicked Settings in the menu bar; after that, everything stopped working. Introducing lodash's `includes()` solves this.

**Comment by zinigor** [comment]
Thanks Elio! Your changes look good to me!

**Comment by eliorivero** [comment]
lgtm 🐑

**Pull request merged**
