### PR TITLE
Monetize: Move into Jetpack menu and open the page on Jetpack Cloud

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/dotcom-forge/issues/6488

## Proposed changes:

* Move the Monetize submenu from Hosting to Jetpack
* Change the link to Jetpack Cloud, `https://jetpack.com/redirect/?source=calypso-monetize&site=<your_site>`

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply this change to your classic atomic site by Jetpack Beta Tester (WordPress.com Features)
* Make sure the Monetize under the Hosting menu is removed
* Make sure you can see `Jetpack > Monetize`
* Make sure the link points to `https://jetpack.com/redirect/?source=calypso-monetize&site=<your_site>`
* The redirection of the link is handled by D144776-code

### CODE REVIEW

**Review by candy02058912 — COMMENTED** [review]
Tested in
### Atomic
atomic

### Jetpack sites
Monetize not present in Jetpack sites, double checking if this is the behavior we want 🤔 
jetpack

**Review by jeherve — COMMENTED** [review]
Since this is something that will only be needed on the WordPress.com platform, maybe it shouldn't ship in the Jetpack plugin; could it be shipped in the mu-wpcom plugin instead?

**Comment by arthur791004** [comment]
> could it be shipped in the mu-wpcom plugin instead?

Make senses! Registered the submenu by mu-wpcom, https://github.com/Automattic/jetpack/pull/36799/commits/fb6f7014c4b827929317dafc6e36c9e3f978834f.

**Review by candy02058912 — DISMISSED** [review]
Retested and LGTM 👍

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
