### PR TITLE
Jetpack Blocks: Set default editor style to be registered along with blocks if no editor styles are provided

### PR DESCRIPTION
**Pull request by andrewserong**
This change ensures that the default Jetpack editor styles are added as an `editor_style` dependency when registering Jetpack blocks within the Jetpack plugin. In the new FSE site editor , where the editor canvas is rendered within an iframe, styles are copied to the iframe based on whether they're registered against the block ([here](https://github.com/WordPress/gutenberg/blob/9484b1ed1dd60ad9cbc721e91e35f4b7b5ed7143/lib/client-assets.php#L698)'s where the logic happens).

Without this change, when the Jetpack styles are loaded via an external link (as they are in wpcom) they're not picked up in the fallback [styleSheetsCompat](https://github.com/WordPress/gutenberg/blob/748421d1980b1aeb486283d90d09a9bfefde068d/packages/block-editor/src/components/iframe/index.js#L32) call, and we're left with unstyled blocks in the editor. For example:

### Unstyled blocks in the new site editor

| Donation | Business Hours |
| --- | --- |
| image | image |
| Cover | Pay with Paypal |
| image | image |

### After (with this change applied)

| Donation | Business Hours |
| --- | --- |
| image | image |
| Cover | Pay with Paypal |
| image | image |

Related to https://github.com/Automattic/wp-calypso/issues/50407

#### Changes proposed in this Pull Request:

* When running in a Jetpack plugin context (the `Jetpack_Gutenberg` class is available):
  * If there is no `editor_style` set for the block, set it to the default editor styles that are registered by the plugin.
  * If there is an `editor_style` set for the block, don't change it.
* When running outside of a Jetpack plugin context (the `Jetpack_Gutenberg` class is not available, then don't make any changes to the `editor_style`.
* Add an `is_standalone_block` method to abstract away the `Jetpack_Gutenberg` class check.
* Add tests to cover this behaviour.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

At the moment, I can test this change in my sandbox by manually copying the changes over to the `mu-plugins/jetpack-plugin/vendor/automattic/jetpack-blocks/src/` directory. To do so you might use a command like: `scp ~/dev/a8c-projects/jetpack/projects/packages/blocks/src/class-blocks.php wpcom:/home/wpcom/public_html/wp-content/mu-plugins/jetpack-plugin/vendor/automattic/jetpack-blocks/src/class-blocks.php`.

1. Create a test FSE site at https://horizon.wordpress.com/new?flags=gutenboarding/site-editor
2. In your `0-sandbox` file set the following and sandbox s0.wp.com, s1.wp.com, s2.wp.com:

```
add_filter( 'wpcom_sandbox_staticize_domain', '__return_true' );
```

More context in p7H4VZ-2qv-p2

3. Open up the site editor (the FSE editor, e.g. `https://wordpress.com/site-editor/mytestsitedomain.com`) and try adding the Donation, Business Hours, or Pay with Paypal blocks and note that the styling isn't being loaded correctly. If you add the Cover block, you'll see the upgrade nudge, even though it shouldn't be visible.
4. Manually update the `class-blocks.php` file as in this PR and ensure your test site is sandboxed.
5. Reload the editor, and the styling should be fixed.

### CODE REVIEW

**Comment by andrewserong** [comment]
@jeherve or @Automattic/view-engineering since this is a change to one of the packages, I wasn't sure how to get it added to a Jetpack build for testing / or for a wpcom diff — is there existing documentation for this? Apologies if I missed it, I couldn't quite figure it out.

While we try not to include Jetpack-plugin specific things in the packages, it seemed neater to me to add the fallback for registering the editor style dependency here, otherwise we need to update all of the individual calls to `jetpack_register_block` within the Jetpack plugin, which seemed like a more complex change, and we'd then potentially risk folks forgetting to add it when creating new blocks.

Happy to go in a different direction, of course, if anyone has a preference for handling this different! 🙇‍♂️

**Comment by jeherve** [comment]
> since this is a change to one of the packages, I wasn't sure how to get it added to a Jetpack build for testing / or for a wpcom diff — is there existing documentation for this? Apologies if I missed it, I couldn't quite figure it out.

We don't really have a process yet, so that's definitely going to be hacky. You'd need to manually edit the file in `wp-content/mu-plugins/jetpack-plugin/vendor` to test it on WordPress.com right now, and the change will only be shipped to WordPress.com when we release a new version of that package and then update the package to use the new version of WordPress.com (that is something the release lead usually handles).

> While we try not to include Jetpack-plugin specific things in the packages, it seemed neater to me to add the fallback for registering the editor style dependency here, otherwise we need to update all of the individual calls to jetpack_register_block within the Jetpack plugin, which seemed like a more complex change, and we'd then potentially risk folks forgetting to add it when creating new blocks.

Yeah, that's probably a good call. 👍
For the tests, part of me wonders if it could be useful to add a new `is_standalone_block` method, or something similar, so we could rely on that in tests and most likely also within the class later on. What do you think?

**Comment by andrewserong** [comment]
> For the tests, part of me wonders if it could be useful to add a new is_standalone_block method, or something similar, so we could rely on that in tests and most likely also within the class later on. What do you think?

Thanks @jeherve, that makes good sense to me, I was a little stuck on the hacky approach I was using declaring `Jetpack_Gutenberg` in the tests (and there were lots of complaints from CI!)

I've gone ahead and added an `is_standalone_block` method, is the way that I've implemented it what you had in mind? I also needed to add a hook in order to get this under test, because we're dealing with static methods and I don't think it's possible to mock them in PHPUnit. The tests are now much neater, but it does mean we have a new hook that doesn't really have any other uses. I don't think that's a problem, but thought I'd defer to you 🙂

The other complaint from CI was that I hadn't bumped the `branch-alias` in `projects/packages/blocks/composer.json#L48`, so I ran `tools/project-version.sh -u 1.3.0-alpha packages/blocks` as the Changelogger step instructed me to, and it's updated it to `1.3.x-dev`.

**Comment by andrewserong** [comment]
> We don't really have a process yet, so that's definitely going to be hacky. You'd need to manually edit the file in wp-content/mu-plugins/jetpack-plugin/vendor to test it on WordPress.com right now

I've updated the testing instructions with an `scp` command that might make it slightly easier for folks testing.

**Review by jeherve — DISMISSED** [review]
This looks good to me now. :ship:

> It's now complaining that the main composer.json isn't referencing the new version, but I wasn't sure if all the version bumps should happen in the one PR?

It should be fine in one PR. I took care of the update in a33b0e3a6da48d7c6bc2c1dbf205b32bdc96251d.

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
This is now available on WordPress.com simple sites: r223203-wpcom

**Comment by andrewserong** [comment]
Perfect, thanks so much @jeherve!

**Pull request merged**
