### PR TITLE
Jetpack: lossless image optimization, part 3

### PR DESCRIPTION
**Pull request by danluu**
This is a continuation of #38398 and #38573, which has been split into multiple parts to avoid hitting the wpcom size limit, which happened on Automattic/themes#7671. Please see #38398 for more details and context.

As a rough estimate for size of files touch that go into wpcom, we have

```
% git diff --name-only | grep -v "w.org-assets" | xargs du -ch  
5.8M    total 
```
#38573 had some instructions for getting a better estimate on wpcom sizes. I can try that and add a comment about that in a bit.

## Proposed changes:

* This PR does lossless image optimization on the images not already optimized in #38398 and #38573, so this should be the final PR in this series. There's room for improvement in other ways, even when it comes to images, but those would be different kinds of optimizations.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Can test via imagemagick compare or by eyeballing the images to check that they don't appear to have visually changed.

### CODE REVIEW

**Comment by anomiex** [comment]
Needs a trunk merge or rebase.

Ran the non-SVGs through ImageMagick's `compare`, no differences highlighted.

**Comment by anomiex** [comment]
Also, looks like you'll need to run `jetpack build js-packages/social-logos` then commit the change it makes to `projects/js-packages/social-logos/src/react/social-logo-data.tsx`.

**Review by anomiex — DISMISSED** [review]
Change looks reasonable.

As for the failing WordPress.com Tests CI check, I think that's the Phabricator issue described at https://secure.phabricator.com/T9069. We could either drop `projects/js-packages/connection/components/disconnect-dialog/images/disconnect-thanks.jpg` from this PR, or we could merge this and then deploy it to Simple right away (which may need an extra step of deleting the built copies of that file from the inactive sun/moon dir first to avoid the Phab bug during the deployment).

**Comment by anomiex** [comment]
`du` check on the sandbox suggests it'll be 14M, BTW.

**Comment by anomiex** [comment]
`du` check on the sandbox suggests it'll be 18M, BTW.

**Review by anomiex — APPROVED** [review]

**Comment by danluu** [comment]
> We could either drop projects/js-packages/connection/components/disconnect-dialog/images/disconnect-thanks.jpg from this PR, or

I feel like the impact of this specific file (or almost any specific file) is small enough that I might as well just drop the file to make things easier. I checked out the previous version of the file into a commit, which seems to have at least caused the failing test to pass (other tests are still running). I'll commit this if/when the other tests pass.

**Pull request merged**
