### PR TITLE
Gravatar Hovercard Settings: removed extra form visually

### LINKED ISSUE #4986: Admin Page: duplicate settings for Gravatar Hovercards
The Gravatar Hovercards settings are confusing:

screen shot 2016-08-26 at 14 37 42

Since there is no point in activating the module if you aren't going to enable the hovercard display, I think we could just remove that option.

- If the module is active and the `gravatar_disable_hovercards` option is active, let's display the module as active, without a radio button.
- If the module is active is the `gravatar_disable_hovercards` option is not set, let's deactivate the module.
- If the module is inactive, do nothing.

That would be the occasion to get rid of the setting in the Discussion settings.

cc @oskosk who worked on #4405 and #4381

### PR DESCRIPTION
**Pull request by MichaelArestad**
Fixes #4986 .

#### Changes proposed in this Pull Request:
* remove duplicate settings

Before:
image

After:
image

@dereksmart or @oskosk I only made the visual changes.  It doesn't actually work I don't think. Could one of you fix this up?

### CODE REVIEW

**Comment by oskosk** [comment]
@MichaelArestad I think this change you did is fine client-wise. Another change php-side will be needed to either:

* Set the `enabled` option automatically when activating the module
* Remove the dependency on this option for this functionality.

cc @eliorivero as this requires either an update on the endpoint or a refactor on the module's behaviour.

**Comment by eliorivero** [comment]
thanks @oskosk will work on this updating the endpoint so when the module is activated the option is set to show avatars, and the opposite case too.

**Comment by eliorivero** [comment]
I've pushed a commit so it will set `gravatar_disable_hovercards` to `enabled` when the module is activated, and to `disabled` when the module is deactivated.

I'd like some feedback from @zinigor or @dereksmart about _where_ I put the PHP code.

**Comment by MichaelArestad** [comment]
@zinigor or @dereksmart can you give @eliorivero some feedback ^

**Comment by rcoll** [comment]
This all looks fine to me and tests great. 👍  on the preventative escaping, @eliorivero! :ship:

**Pull request merged**
