### PR TITLE
My Jetpack: Turn search into a hybrid product

### LINKED ISSUE #23771: 2.11 My Jetpack integration
#### The problem

When Jetpack Search runs without Jetpack the plugin:

- The status of Jetpack Search is not correctly reflected by My Jetpack.

| Search Dashboard      | My Jetpack |
| ----------- | ----------- |
| image      | image       |

- Clicking activating Search module in My Jetpack, Jetpack plugin is activated and then search module is enabled. 
Screen Capture on 2022-04-04 at 14-53-49

#### Expected bahaviour: 

- My Jetpack only needs to only activate the search module when Jetpack Search already exists.
- My Jetpack should activate/install Jetpack Search plugin instead of Jetpack when clicking button `Activate`

#### Related API

API already added to Jetpack Client:

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/js-packages/api/index.jsx#L472-L489

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/packages/search/src/class-rest-controller.php#L149-L154

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/packages/search/src/class-rest-controller.php#L221-L224

### LINKED ISSUE #23909: My Jetpack: redirect Search's “Manage” to Search landing page
When clicking/tapping on the “Manage” button in Search:

image

The customer is redirected to the Search customizer experience @ `/wp-admin/admin.php?page=jetpack-search-configure`:

image

Ideally, we should redirect users to the landing page for that product, where there's a lot more context to introduce the product and remind users of its benefits. For Search that's `/wp-admin/admin.php?page=jetpack-search`:

image

---

Presumably it comes from this line:

https://github.com/Automattic/jetpack/blob/60ff8e8f3400ab8e8bf7c68f1377e506d6f1cfd9/projects/packages/my-jetpack/src/products/class-search.php#L172

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #23771
Fixes #23909

This PR turns Search into a Hybrid product, which means:

* it will consider that Search plugin is active if either Jetpack or Search stand-alone plugin is active
* If none of the plugins are active, it will favor the installation/activation of the Search plugin

In progress - I still need to make sure Jetpack search module is activated upon product activation.

WARNING - This must be shipped only after the Search stand-alone plugin is released, otherwise it will fail to install the plugin when Jetpack plugin is not present.

#### Changes proposed in this Pull Request:

* Turn search into a hybrid product

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Test activating Search product from different combinations (e.g. with only Jetpack active, with only Boost active, with both active, with none of them installed, etc...)

### CODE REVIEW

**Review by jsnmoon — COMMENTED** [review]
My Jetpack appears to incorrectly equate an active Search plugin to active Search functionality. It's possible to have the Search plugin installed with disabled Search functionality, like so:

Screen Shot 2022-04-08 at 1 37 24 PM

Screen Shot 2022-04-08 at 1 37 08 PM

Reproduction steps:
1. Spin up a new Jurassic Ninja site without the Jetpack plugin and with the Jetpack Beta plugin setting Jetpack Search to this branch.
2. Navigate to Jetpack -> Search on the sidebar and click "Get Jetpack Search".
3. Complete the connection/purchase flow.
4. Ensure you're redirected to the Search Dashboard post-purchase (`/wp-admin/admin.php?page=jetpack-search`)
5. Ensure that Search is marked active in My Jetpack.
6. Navigate back to the Search Dashboard and deactivate Jetpack Search using the top toggle.
7. Search is incorrectly marked active within My Jetpack.

**Comment by leogermani** [comment]
Hi @jsnmoon 

Thanks for looking at it.

In fact, My Jetpack is not looking at the internal details of how each product work to determine if it's active or not. It just looks at plugin activation and purchased plans.

If we add this check, we should also add an action that would activate the Search feature if we clicked "Activate". We have to think if this works well for Search, as it might not work very well for all products that require more complicated configuration and we rather ask the user to go to the plugin's page to "Manage" it. So that's why we consider it active and link it o Manage where they can look at the details of the product.

However, we could go ahead and do this. The way to do this IMO is by My Jetpack offering an API (hooks?) for stand-alone plugins to define how it will work. This is in our plan but we haven't had any use case until now.

The idea is that a plugin could even tweak the action button label and link, card states, etc.

We could start by allowing you to modify the check for the product status and also to hook into the activation process. But I'd suggest to do it in another PR, what do you think?

**Comment by jsnmoon** [comment]
> If we add this check, we should also add an action that would activate the Search feature if we clicked "Activate". We have to think if this works well for search, as it might not work very well for all products that require more complicated configuration and we rather ask the user to go to the plugin's page to "Manage" it. So that's why we consider it active and link it o Manage where they can look at the details of the product.

I see — thank you for the explanation.

> However, we could go ahead and do this. The way to do this IMO is by My Jetpack offering an API (hooks?) for stand-alone plugins to define how it will work. This is in our plan but we haven't had any use case until now.
> 
> The idea is that a plugin could even tweak the action button label and link, card states, etc.
> 
> We could start by allowing you to modify the check for the product status and also to hook into the activation process. But I'd suggest to do it in another PR, what do you think?

Got it. Tackling this in a separate PR sounds good to me! Search already has an established post-purchase auto-configuration step that we could invoke as the activation step from My Jetpack.

---

From what I know so far, there are five possible scenarios with Search and My Jetpack. Here are my findings:

1. ✅ The Search plugin is installed and active with search functionality enabled. My Jetpack correctly represents this as "Active."

2. ✅ The Jetpack plugin is installed with an active search module. My Jetpack correctly represents this as "Active."

3. ⚠️ Any other standalone plugin is installed on a site with no search functionality.
My Jetpack correctly marks Search as "Inactive;" clicking "Activate" throws an error since the Jetpack Search plugin has not yet been published to the plugin directory.

4. ⚠️ The Search plugin is installed and active, but the search functionality is disabled.
As previously discussed, My Jetpack marks this as "Active," and any further refinements will be handled in a future PR. Ideally, we would mark this as "Inactive" and clicking "Activate" will enable both Classic and Instant Search experiences.

5. ⚠️ The Jetpack plugin is installed with an inactive search module.
My Jetpack correctly represents this "Inactive," but pressing the "Activate" button enables the module without enabling instant search. Because of this, the "Manage" link for the Search card doesn't work as expected since it refers to `/wp-admin/admin.php?page=jetpack-search-configure` (known as "Customberg") — a page only available when Instant Search is enabled.

    a. Suggestion: Can we change the "Manage" link to `/wp-admin/admin.php?page=jetpack-search`, the Search wp-admin dashboard?

**Comment by leogermani** [comment]
>3. Any other standalone plugin is installed on a site with no search functionality.
My Jetpack correctly marks Search as "Inactive;" clicking "Activate" throws an error since the Jetpack Search plugin has not yet been published to the plugin directory.

This should not happen. As we discussed, My Jetpack will install Jetpack plugin in this situation. In the future, after Search plugin is released, we can change it and favor the stand-alone plugin itself.

I just tested it and it worked as expected. Do you see errors still?

> 4. The Search plugin is installed and active, but the search functionality is disabled.
As previously discussed, My Jetpack marks this as "Active," and any further refinements will be handled in a future PR. Ideally, we would mark this as "Inactive" and clicking "Activate" will enable both Classic and Instant Search experiences.

Deal.

> 5. The Jetpack plugin is installed with an inactive search module.
My Jetpack correctly represents this "Inactive," but pressing the "Activate" button enables the module without enabling instant search. Because of this, the "Manage" link for the Search card doesn't work as expected since it refers to `/wp-admin/admin.php?page=jetpack-search-configure` (known as "Customberg") — a page only available when Instant Search is enabled.

Sorry, I was not aware that `/wp-admin/admin.php?page=jetpack-search` was also available in the Jetpack plugin. Implemented suggested solution in https://github.com/Automattic/jetpack/pull/23868/commits/86b3560122aa88c23a0d98d7a740e7f8505095a4

**Comment by oskosk** [comment]
Rebased and pushed 31e9bbb59499c81ee8f7eff72a070eda61e18559 to update versions

**Review by oskosk — APPROVED** [review]

**Comment by oskosk** [comment]
Tests well. I lost the comment on the approval but was mentioning that I faced this state in the checkout  when starting the flow from Protect being connected (only site level connection). 

image

So to reproduce:

1. Have just Protect and connected
2. Click on Add Search
3. Expect to be led to Checkout and see those notices. The Jetpack plugin Is installed properly on the site

**Comment by leogermani** [comment]
> So to reproduce:
> 
>     1. Have just Protect and connected
> 
>     2. Click on Add Search
> 
>     3. Expect to be led to Checkout and see those notices. The Jetpack plugin Is installed properly on the site

This usually happens when I test the flow many times in a row. Something related to cookies or caching in WPCOM... If I start over, then it works again.

I just tested the flow you described and it works fine

**Pull request merged**
