### PR TITLE
Update webpack globally 

### PR DESCRIPTION
**Pull request by gravityrail**
We previously updated to webpack 5, plus the latest `@automattic/calypso-build` (v9.0.0) for Jetpack. This applies those same version updates, plus the latest webpack-cli, to all the places where we use them.

#### Changes proposed in this Pull Request:

* Update all projects to latest webpack, webpack-cli and calypso-build

#### Jetpack product discussion
p1629397551142600-slack-jetpack-crew

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Nothing should change, though we may get a few new deprecation warnings.

### CODE REVIEW

**Comment by retrofox** [comment]
sorry I was taking a look at the PR and changed the title accidentally :-(

**Review by anomiex — APPROVED** [review]
Looks sensible to me. I fixed lazy-images to continue using calypso-build, see a72fa61ca1748c9072fc01be99da5d32160f5fc9 for an explanation of what was breaking there.

**Comment by gravityrail** [comment]
@anomiex thanks for the patch. Unfortunately it broke es5 validation for the built lazy-images package.

```
 > @ validate-es5 /home/runner/work/jetpack/jetpack/projects/packages/lazy-images
  > eslint --parser-options=ecmaVersion:5 --no-eslintrc --no-ignore "./dist/"
  
  
  /home/runner/work/jetpack/jetpack/projects/packages/lazy-images/dist/intersection-observer.js
    1:3  error  Parsing error: Unexpected token )
  
  /home/runner/work/jetpack/jetpack/projects/packages/lazy-images/dist/lazy-images.js
    1:3  error  Parsing error: Unexpected token )
```

I'll jump in and fix this, since I already fixed it previously.

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
> I'll jump in and fix this, since I already fixed it previously.

Oops, I already did before I saw your comment.

**Comment by gravityrail** [comment]
@anomiex I reverted the change to es9 validation since it emits code that won't run in some browsers. Better to just emit es2015 as before, just in case. If we want to make a change to which browsers we support it should probably happen in a different PR.

**Comment by anomiex** [comment]
We already did drop support for IE11. p1HpG7-c8n-p2

**Comment by anomiex** [comment]
Actually... I don't have any idea what calypso-build is doing, but just adding the
```
       "browserslist": [
               "extends @wordpress/browserslist-config"
       ],
```
bit (and the dep on `@wordpress/browserslist-config`) is somehow enough to restore IE11 support when I build locally. All the other stuff you added in 9b17538 seems unnecessary.

I have no idea what's going on with that, since `@wordpress/browserslist-config` 4.1.0 doesn't include IE11 so if anything I'd think it should be the opposite.

**Comment by gravityrail** [comment]
Good catch. I'm not at my computer right now so if you want to revert my
change and add browserlist back in go right ahead, otherwise I'll take a
look later or tomorrow.

**Comment by anomiex** [comment]
Turning off auto-merge to get review of my own change to the PR.

**Review by anomiex — APPROVED** [review]

**Comment by gravityrail** [comment]
Looks great @anomiex - thanks for getting to the bottom of it. I did think a few times "how the hell did this ever work, and how does that other thing still work, and..." but you managed to get to the bottom of it with that op_mini thing.

**Comment by anomiex** [comment]
r230707-wpcom

**Pull request merged**
