### PR TITLE
My Jetpack: hide Jetpack Manage menu item

### PR DESCRIPTION
**Pull request by miksansegundo**
Fixes https://github.com/Automattic/dotcom-forge/issues/5824

## Proposed changes:
We are changing the sidebar navigation as part of the Untangling Calypso project. See pfsHM7-J-p2

* Hide the Jetpack Manage menu item by not calling the code that adds it.

> [!NOTE]
> This PR removes the call and the tests while it still leaves the class introduced in https://github.com/Automattic/jetpack/pull/34353

### Other information:

- [X] Have you written new tests for your changes, if applicable?
- [X] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [X] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
See p1709175739921149/1709107709.312399-slack-C06DN6QQVAQ

## Testing instructions:

* On an atomic site and a Jetpack site connected to WordPress.com
* Go to the admin dashboard and verify the "Jetpack > Jetpack Manage" menu item does not appear in the sidebar.

### Jetpack

|BEFORE|AFTER| 
|-|-|
|Screenshot 2567-02-29 at 16 51 07|Screenshot 2567-02-29 at 16 48 57|

### Atomic
|BEFORE|AFTER| 
|-|-|
|Screenshot 2567-02-29 at 16 28 34|Screenshot 2567-02-29 at 16 26 11|

### CODE REVIEW

**Review by fushar — APPROVED** [review]
Tested and it works. Code looks correct, too!

**Comment by arthur791004** [comment]
I'm unsure whether to remove the menu on self-hosted sites 🤔

**Comment by vitozev** [comment]
Let's leave this for self-hosted sites if possible. Jetpack Manage will likely continue to exist as a separate product.

**Comment by autumnfjeld** [comment]
>  Let's leave this for self-hosted sites if possible. Jetpack Manage will likely continue to exist as a separate product.

Yes.  This was only meant to be for atomic sites.
https://github.com/Automattic/dotcom-forge/issues/5824#issuecomment-1972241406

**Comment by autumnfjeld** [comment]
This should be done in wpcomsh.

**Comment by miksansegundo** [comment]
Closing this in favor of https://github.com/Automattic/wpcomsh/pull/1725

**Pull request closed without merging**
