### PR TITLE
MU WPCOM: Fix the value of the wpcom_public_coming_soon option isn't configured correctly

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes #

## Proposed changes:

* Fix the value of the wpcom_public_coming_soon option isn't configured correctly by the following steps
  * Set the Privacy to Coming Soon
  * Set the Privacy to Private
  * Set the Privacy to Coming Soon
* The reason was the `wpcom_public_coming_soon` option would be updated automatically when you set the `blog_public` option from `0` to `-1` (Coming Soon to Private). As a result, the updated fields of response wouldn't contain the `wpcom_public_coming_soon` field because it was changed automatically and the value was the same as the request. Then, the client thought the value was the same as before so that it wouldn't request to change the value of the `wpcom_public_coming_soon` when you were configuring the Privacy from Private to Coming Soon again.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your sandbox or atomic sites
* Go to `https://wordpress.com/settings/general/:site`
* Set the Privacy as below
  * Coming Soon
  * Private
  * Coming Soon
* Open your site with the Incognito mode
* Make sure you can see the Coming Soon page

### CODE REVIEW

**Comment by taipeicoder** [comment]
@arthur791004 could you clarify what's the issue? I tried switching Coming Soon → Private → Coming Soon without this PR, and it worked as intended (the site frontend showed Coming Soon).

**Comment by arthur791004** [comment]
@taipeicoder Here is the issue I encountered and it can be reproduced consistently

https://github.com/user-attachments/assets/37ff2209-31da-401c-8ba0-520aa4b4f197

You can check the response of the endpoint to update settings. The updated array won't contain the `wpcom_public_coming_soon` when you switch from Coming Soon to Private and then when you switch from Private back to Coming Soon, Calypso won't send `wpcom_public_coming_soon: 1` to update the settings as the client side think the value isn't changed.

**Comment by miksansegundo** [comment]
I have reproduced it. 

See how the site is wrongly set as `Public` after quickly saving `Coming soon > Private > Coming soon`


https://github.com/user-attachments/assets/89a5fd20-9b7c-48fa-b24d-531b7a99f94f



I'm testing the fix now.

**Review by miksansegundo — APPROVED** [review]
LGTM 🚀 
The issue is not reproducible after the fix.

### BEFORE

https://github.com/user-attachments/assets/89a5fd20-9b7c-48fa-b24d-531b7a99f94f

### AFTER

https://github.com/user-attachments/assets/7ae294d8-57d4-48ec-b3ad-99eb4da64261

**Pull request merged**
