### PR TITLE
Boost: fix e2e plugin deactivation

### PR DESCRIPTION
**Pull request by haqadn**
#### Changes proposed in this Pull Request:

* Update e2e test to properly deactivate plugin by interacting with the deactivation dialog

#### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
p1669629606043189-slack-C01U2KGS2PQ

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
None

### CODE REVIEW

**Comment by haqadn** [comment]
Note to self: Something is broken in the test process. Looks like the plugin deactivation dialog is not working while running from github.

**Comment by haqadn** [comment]
The build artifact is functional https://github.com/Automattic/jetpack/suites/9537910328/artifacts/453402448

**Comment by thingalon** [comment]
The artifacts from the test failure are reported here: p1669637602738129-slack-C1Y1F7ZM1

It looks like it's failing to find the deactivate stuff on the plugins page because Jetpack has taken it over with a "getting started" thing.

**Comment by haqadn** [comment]
> The artifacts from the test failure are reported here: p1669637602738129-slack-C1Y1F7ZM1
> 
> 
> 
> It looks like it's failing to find the deactivate stuff on the plugins page because Jetpack has taken it over with a "getting started" thing.

The video on test output shows otherwise. After clicking the deactivate button, it simply navigates.

[video.webm](https://user-images.githubusercontent.com/3737780/204442483-2debdd67-2fb5-4c2c-bab3-d8f4faf377f1.webm)

**Review by thingalon — APPROVED** [review]

**Comment by haqadn** [comment]
Cherry-picked 141199332

**Pull request merged**
