### PR TITLE
Admin Menu: Fix skipped tests

### LINKED ISSUE #21042: Unit Tests: Fix skipped Masterbar tests
To be able to unblock Jetpack's PHPUnit tests on master, `test_register_dashboard_switcher` and `test_handle_preferred_view` were skipped in https://github.com/Automattic/jetpack/pull/21030. We should fix these tests.

These tests were causing the PHPUnit process to silently exit, which was generating false positives for quite some time. 

Internal discussion: p9dueE-3sh-p2

### PR DESCRIPTION
**Pull request by mmtr**
Fixes #21042

#### Changes proposed in this Pull Request:

Adds back the `test_handle_preferred_view` and `test_register_dashboard_switcher` tests that were skipped in #21030. 

Seems that these tests were unintentionally terminating the `phpunit` process because some AJAX requests were executing the `handle_preferred_view` function hooked into the `admin_menu` action, as opposed to the one hooked into `wp_ajax_set_preferred_view` which is the only one that should kill the WordPress execution.

To fix that, we now have two separate functions which are hooked independently. 

#### Jetpack product discussion
p9dueE-3sh-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Make sure that Jetpack PHPUnit tests actually succeeds (or check [this direct link](https://github.com/Automattic/jetpack/pull/21055/checks?check_run_id=3586164579#step:9:202)).
- Additionally, check that the Nav Unification's screen switcher continues to work as expected:
  - Simple sites: Apply D66737-codee to your WP.com sandbox, and sandbox both the API and a Simple site.
  - Atomic sites: Install Jetpack Beta and activate the `fix/screen-options-switcher-tests` branch.
  - Go to https://wordpress.com.
  - Switch to your Simple or Atomic site.
  - Go to any of the following screens:
    - Posts > All posts
    - Posts > Categories
    - Posts > Tags
    - Media
    - Pages > All pages
    - Testimonials > All testimonials
    - Portfolio > All projects
    - Comments
    - Appearance > Themes
    - Users > All users
    - Tools > Import
    - Tools > Export
    - Settings > General
    - Settings > Writing
    - Settings > Discussion
  - Click on the "Screen Options" tab and then select "Classic view".
  - Make sure you're redirected to the equivalent WP Admin screen.
  - Make sure that the menu/submenu item of that screen now always links to the WP Admin screen from both Calypso and WP Admin.
  - On the WP Admin screen, click on the "Screen Options" tab and then select "Use WordPress.com view".
  - Make sure you're redirected to the equivalent Calypso screen.
  - Make sure that the menu/submenu item of that screen now always links to the Calypso screen from both Calypso and WP Admin.

### CODE REVIEW

**Review by brbrr — APPROVED** [review]
Looks good!

**Review by BogdanUngureanu — APPROVED** [review]
LGTM! 🎉

**Comment by mmtr** [comment]
Deployed to WP.com in r231627-wpcom.

**Comment by anomiex** [comment]
Fix itself looks good to me, but the reasoning is not correct.

> Seems that these tests were unintentionally terminating the `phpunit` process because some AJAX requests were executing the `handle_preferred_view` function hooked into the `admin_menu` action, as opposed to the one hooked into `wp_ajax_set_preferred_view` which is the only one that should kill the WordPress execution.

The problem is that an earlier test is defining `DOING_AJAX`, which makes `wp_doing_ajax()` return true for all the rest of the tests. The test here that was supposed to be testing a non-ajax workflow was hitting the ajax code path for that reason, and further it makes `wp_die()` actually exit instead of throwing an exception as it does for non-ajax requests.

I only mention this because more people knowing the correct cause of the problem might help if something like this shows up again at some point.

**Comment by mmtr** [comment]
> The problem is that an earlier test is defining `DOING_AJAX`, which makes `wp_doing_ajax()` return true for all the rest of the tests

Oh, that's interesting! So the proper fix would be to change that test so it doesn't override `wp_doing_ajax` for the remaining tests, right?

**Comment by anomiex** [comment]
This is still a good fix. But yes, we should also clean up [that other test](https://github.com/Automattic/jetpack/blob/cdf89f9a452119965a3dc8b654ab8629c3146bd0/projects/plugins/jetpack/tests/php/modules/contact-form/test-class.grunion-contact-form.php#L22).

**Pull request merged**
