### PR TITLE
MU WPCOM: Only load ETK features for wpcom users

### PR DESCRIPTION
**Pull request by arthur791004**
Related to p1722567163421299/1721640177.158509-slack-CRWCHQGUB

## Proposed changes:

* Only load ETK features for wpcom users because we don't want to include ETK features for A4A sites or sites that are not connected to wpcom

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your atomic site
* Disable ETK plugin
* Mark your site as a A4A site
  * `update option is_fully_managed_agency_site 1`
* Go to the Editor
* Make sure the ETK features are not loaded
  * What's new
  * Welcome Guide
  * Nux Modals
  * Timeline, Event Countdown, etc blocks
  * Global Style Upsell
  * etc

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
LGTM. The only significant "breakage" would be the Countdown/Timeline blocks suddenly not working, but we can reevaluate that if needed at later date.

**Review by fushar — COMMENTED** [review]
Sorry for late review. Can we confirm that with this PR, the blocks from https://github.com/Automattic/jetpack/pull/38454 can still be rendered on site frontend (i.e. logged-out users)?

**Comment by fushar** [comment]
> Can we confirm that with this PR, the blocks from https://github.com/Automattic/jetpack/pull/38454 can still be rendered on site frontend (i.e. logged-out users)?

I just tried `Blog Posts` and it only renders on site frontend when I am logged in as a wpcom user. So, we might want to exclude some of the block-related features from the gating.

**Comment by arthur791004** [comment]
Yep, you're right 🥲

**Comment by arthur791004** [comment]
Opened https://github.com/Automattic/jetpack/pull/38707 to revert it and proposed https://github.com/Automattic/jetpack/pull/38708 to keep loading ETK features on the frontend pages!

**Pull request merged**
