### PR TITLE
Sync: Avoid synching personal data in WooCommerce orders

### PR DESCRIPTION
**Pull request by allendav**
#### Changes proposed in this Pull Request:

* Removes some of the fields added in https://github.com/Automattic/jetpack/commit/5fbe2f5d9414426345ed4e5a66f5f8a1b483cb4a
* We will have to sync this code change to the server side too

#### Testing instructions:

* N/A - Although D9552 had them, the stats work in D9461 did not rely on these fields

### CODE REVIEW

**Comment by allendav** [comment]
@westi wrote:

> Can we change this to comment out, and explain, the fields that are not being synced.

> This will make it easier to review future updates and help these not get re-instated.

> Bonus: Can we add a test to ensure they are not re-added?

Ooh - good ideas - will do

**Comment by allendav** [comment]
@westi wrote:

> Can we change this to comment out, and explain, the fields that are not being synced.

Fixed in https://github.com/Automattic/jetpack/pull/9058/commits/4283b670a57f62e5cc42d600b1ab876661914a03

> Bonus: Can we add a test to ensure they are not re-added?

@westi - I've created a unit test which I believe is correctly written, but it is failing (so I have not added it to this PR yet - can you take a look - my Jetpack foo is limited:

https://gist.github.com/allendav/47658545cedfb8f05eb1effe918d5f08

Also noteworthy: https://github.com/Automattic/jetpack/issues/9065

**Comment by westi** [comment]
I think @enejb or @lezama probably know more about the Jetpack Sync tests than I do.

**Comment by oskosk** [comment]
@allendav can these be removed instead of commented out ?

**Comment by oskosk** [comment]
WOW, I totally missed westi's comment when I dropped mine. Thanks @allendav !

**Pull request merged**
