### PR TITLE
Pay with Paypal block: Increased the size of the Pay with Paypal button

### LINKED ISSUE #17324: Pay with Paypal: button layout issues where there are more supported payment methods
This was reported by someone in the UK; this may have an impact on whether you can reproduce or not.

In some cases, the Pay with Paypal button displays one more payment method, thus breaking the layout of the button:

**Good**

image

**With one extra provider**

image

It would be good if we could support that.

******

Reported here:
p8oabR-y3-p2/#comment-4613

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Increased the size of the Pay with Paypal button in Pay with Paypal block in order to display the card icons shown below the button.

Besides this, I've also changed the icons that are used in Gutenberg so that it better reflect the actual size rendered on the front-end.

Fixes #17324

#### Changes proposed in this Pull Request:

* Mark the button as responsive
* Changed the png icons used in Gutenberg

#### Testing instructions:

* Atomic/Jetpack: switch to this branch using Jetpack Beta
* WPCOM:  Run `arc patch-image D73251` to apply the patch, since it contains images. 
* Go to Posts > Add new and add the Pay with Paypal button
* Save the post.
* Make sure that the button is larger in Gutenberg
* Preview the newly created post and make sure that the card icons beneath the button are not truncated.

**Before**:
Screenshot 2022-01-18 at 17 00 12

**After**:
Screenshot 2022-01-18 at 17 00 35

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
Isn't it a problem that in the editor, you may end up with a preview that doesn't match what you'll see on the frontend, because the list of providers isn't the same in your country?

**Comment by BogdanUngureanu** [comment]
Hey @jeherve, yes, the card icons would be different, but that was already happening before these changes. One way to have the same icons would probably be to load the Paypal library in the editor but that might affect the performance and imho I don't think it's worth it.

**Review by dsas — APPROVED** [review]
This works as explained in Jetpack.

On wpcom I struggled to test this though I don't have `arc patch-image` (related to git beta?) and a normal `arc patch` got a bunch of conflicts on the built files. I used the manual fusion tool and it updated phab (except the images which I downloaded to add manually) but I still got a conflict in `paypal-express-checkout.js` when checking out. Resolving it manually and uploading the image files all worked as it should though. The bad news is that it's probably made a mess of your phab diff.

Maybe it would be better to load the paypal library and make the preview more accurate but that could be done separately. If that's quick to try it'd be interesting to see what the performance impact is.

**Review by jeherve — APPROVED** [review]

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM with r238669-wpcom

**Pull request merged**
