### PR TITLE
Backup Plugin: Allow non owner admins to access the Backup dashboard

### PR DESCRIPTION
**Pull request by oskosk**
#### Changes proposed in this Pull Request:

We were checking if the current user is connected but instead we need to check if the site has an owner

See #26100 for a similar approach introduced in Jetpack Search

#### Before

image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Launch a JN site with Jetpack Backup on it
- Connect and purchase Backup
- Create a secondary administrator
- Sign in as this other administrator
- Visit the Jetpack Backup page
- Confirm you can see the Backup dashboard

### CODE REVIEW

**Comment by oskosk** [comment]
Updating this PR. first shot wasn't enough apparently

**Comment by oskosk** [comment]
Pushed another commit with a definitive fix. @nunyvega can you review?

**Comment by nunyvega** [comment]
Code change looks reasonable, testing it now.

**Comment by oskosk** [comment]
Seems like the `fetch-capabilities` endpoint returns empty so this ends up happening now for the secondary admin

image

**Comment by nunyvega** [comment]
While testing this we noticed that the issue is actually that the secondary admin is not connected to WPCOM, and therefore it does not pass the authentication checks to query the site capabilities API endpoint.

I pushed in aadcd2238e a proposal to show a placeholder message letting the user know that the site backups are managed by the owner of this site's Jetpack connection:

Screen Shot 2022-09-09 at 22 16 35

As a follow-up, we can add a button to connect to WordPress.com.

**Comment by oskosk** [comment]
Pushed rebase in https://github.com/Automattic/jetpack/pull/26105/commits/052644205614be4dd36be41fd02b0120dc1c2f79

**Comment by nunyvega** [comment]
While the current proposal shows who can currently manage the backup, the ideal solution would be to request the user to connect to wpcom and add a connection prompt, so they can also manage it, and so we don't have the links to cloud whenever the user is not connected. 

I sent a request to the design team to provide that design. Request here:
1199980337313591-as-1203004705036701

**Review by nunyvega — APPROVED** [review]

**Pull request merged**
