### PR TITLE
Jetpack Google Fonts: Print font faces that are in use instead of ALL

### LINKED ISSUE #34163: Google Fonts: all font faces are printed, even when not in use
### Impacted plugin

Jetpack

### Quick summary

Core prints all registered fonts in `theme.json`. Since Jetpack's Google Fonts feature registers quite a few fonts, that makes for a lot of additional fonts loaded on each site where the feature is active, even if the fonts are not in use on the site.

### Steps to reproduce

1. Start with a brand new site running the latest version of WordPress (6.4).
2. Install the latest version of the Gutenberg plugin.
3. Install the Jetpack plugin and connect it to WordPress.com.
4. Go to Jetpack > Settings > Modules, and activate the “Google Fonts (Beta)” module
5. Go to Appearance > Site Editor > Styles > Typography > Text > Font
6. See additional Google Fonts provided by the module.
7. Load any page on the frontend.
8. Open your browser's dev tools
9. Search for `wp-fonts-local` under the “Elements” tab

### A clear and concise description of what you expected to happen.

Only active fonts should be loaded on the frontend.

### What actually happened

 You will see the full list of fonts loaded there.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

This was reported here:

- https://core.trac.wordpress.org/ticket/59863
- https://wordpress.com/forums/topic/hundreds-of-fonts-loaded-via-wp-fonts-local-action-on-front-end-and-dashboard/
- https://wordpress.org/support/topic/6-4-wordpress-loading-hundreds-of-fonts-via-wp-fonts-local-action/

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes #34163

## Proposed changes:

This is a follow-up to #33203

* Turn off Font Face hooks in Core that print **ALL** fonts from theme json. Instead, this PR collects fonts that are used by global styles or block-level settings first and then prints the necessary fonts
  * The hooks registered in Core are [here](https://github.com/WordPress/wordpress-develop/blob/0b8ca16ea3bd9722bd1a38f8ab68901506b1a0e7/src/wp-includes/default-filters.php#L749) and [here](https://github.com/WordPress/wordpress-develop/blob/0b8ca16ea3bd9722bd1a38f8ab68901506b1a0e7/src/wp-admin/includes/admin-filters.php#L174)

* In the follow-up iteration, we can continue to detect the font style & font weight that are in use. The difficult is the global styles or block-level settings might only define the font family, and we need a way to know what's the default font style & font weight.

For example, global styles might define a font weight for ALL headings (h1, h2, ..., h6). Hence, we have to include the specific font weight for the font families that are defined by other headings (e.g.: h1) here. However, we might not be able to know the default font style & font weight for all blocks. Any thoughts?

```json
{
  "h1": {
    "typography": {
      "fontFamily": "var(--wp--preset--font-family--spectral)"
    }
  },
  "heading": {
    "typography": {
      "fontWeight": "600"
    }
  }
}
```

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* p1700040028362329-slack-C4GAQ900P
* p7DVsv-jib-p2

## Does this pull request change what data or activity we track or use?

* No

### Preparation

**JN Sites**

* Create a [Jurassic Ninja sandbox](https://jurassic.ninja/create/?jetpack-beta&branch=feat/print-font-faces-in-use) against this PR.
* Ensure the WP version is 6.4 and above
* Install [the latest Gutenberg](https://github.com/WordPress/gutenberg/releases), e.g.: v17.0.2
* Go to `/wp-admin/admin.php?page=jetpack_modules` to activate the “Google Fonts (Beta)” module

**Atomic sites**

* Install Jetpack Beta Tester plugin
* Install changes from this branch, feat/print-font-faces-in-use

### Steps

* Go to the Site Editor
* Select Styles > Typography > Text > Font
* Ensure you're able to see all Google Fonts in the list
* Go to your homepage (e.g. `https://<your_site_domain>`)
* Open the Dev Tool
* Search for `wp-fonts-local` under the “Elements” tab
* Ensure the content of the `wp-fonts-local` style only contains the fonts that are in use instead of ALL

### CODE REVIEW

**Comment by mreishus** [comment]
In my test on atomic, this is not removing the extra styles being printed (both front-end and admin), because they're not coming from `wp_print_font_faces()` (which isn't running at all). They're being printed by `wp_print_fonts()` in `wp-content/plugins/gutenberg/lib/experimental/fonts-api/fonts-api.php`.
```
$e = new Exception();
error_log("Current hook: " . current_filter() );
error_log("Stack trace: " . $e->getTraceAsString());
```
```
[16-Nov-2023 14:27:11 UTC] Current hook: wp_head
[16-Nov-2023 14:27:11 UTC] Stack trace: #0 /wp-includes/class-wp-hook.php(324): wp_print_fonts('')
#1 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 wp-includes/general-template.php(3052): do_action('wp_head')
#4 wp-includes/template-canvas.php(17): wp_head()
#5 wp-includes/template-loader.php(106): include('/srv/htdocs/__w...')
#6 wp-blog-header.php(19): require_once('/srv/htdocs/__w...')
#7 index.php(17): require('/srv/htdocs/__w...')
```

**Comment by mreishus** [comment]
In chat, we found an unhooking solution that works:
```
        public function __construct() {
                // Turns off Font Face hooks in Core.
                // @since 6.4.0.
                add_action( 'init', array( $this, 'remove_wp_print_font_hooks' ), 99 );
                add_action( 'admin_init', array( $this, 'remove_wp_print_font_faces_hooks' ), 10 );

                // Collect and print fonts in use
                add_action( 'wp_head', array( $this, 'print_font_faces' ), 50 );
                add_filter( 'pre_render_block', array( $this, 'collect_block_fonts' ), 10, 2 );
        }

        public function remove_wp_print_font_hooks() {
                remove_action( 'wp_head', 'wp_print_fonts', 50 );
                remove_action( 'admin_print_styles', 'wp_print_fonts', 50 );
        }

        public function remove_wp_print_font_faces_hooks() {
                remove_action( 'admin_print_styles', 'wp_print_font_faces', 50 );
        }
```

**Comment by anomiex** [comment]
In testing this on a JN site, I find that it's still printing all the fonts due to [this code](https://github.com/WordPress/WordPress/blob/fddf7e9fae5e166a6187054322b9f3facc638225/wp-includes/fonts.php#L43-L45) that re-reads the entire list when the passed `$fonts` is empty.

**Comment by arthur791004** [comment]
> In testing this on a JN site, I find that it's still printing all the fonts due to [this code](https://github.com/WordPress/WordPress/blob/fddf7e9fae5e166a6187054322b9f3facc638225/wp-includes/fonts.php#L43-L45) that re-reads the entire list when the passed $fonts is empty.

Hmmm...TT4 uses the slug defined in [theme.json](https://github.com/WordPress/twentytwentyfour/blob/df92472089ede6fae5924c124a93c843b84e8cbd/theme.json#L215) and it doesn't match the font name so that the `$fonts_to_print` becomes empty 😂

Let me think about how to resolve it...

**Comment by mreishus** [comment]
Seeing the same thing on my atomic+twentytwentythree test setup.
I had a blog that contained the `Overpass` font; with this PR the css correctly only included overpass. 
After deleting that blog post, the `wp_print_font_faces() -> empty( $fonts ) -> $fonts = WP_Font_Face_Resolver::get_fonts_from_theme_json();` pathway runs and prints all of the unneeded fonts.

Could something simple like this work (or at least be a last-chance guard)?
```diff
diff --git a/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php b/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php
index c43424b4cc..8f48585594 100644
--- a/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php
+++ b/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php
@@ -62,7 +62,9 @@ class Jetpack_Google_Font_Face {
                        }
                }
 
-               wp_print_font_faces( $fonts_to_print );
+               if ( ! empty( $fonts_to_print ) ) {
+                       wp_print_font_faces( $fonts_to_print );
+               }
        }
 
        /**
```

**Comment by arthur791004** [comment]
> Could something simple like this work (or at least be a last-chance guard)?

Yes, I added this check to avoid printing all fonts when we cannot detect fonts in use correctly. However, it will lead to some fonts in use that cannot be displayed correctly, so I also made a change to collect the fonts by their slug to resolve the TT4 issue.

image

**Comment by arthur791004** [comment]
The quick fix (this change) shipped via wpcomsh https://github.com/Automattic/wpcomsh/pull/1576 seems to work well. See p1700232615923879/1700040028.362329-slack-C4GAQ900P.

**Review by fushar — APPROVED** [review]
Nice, it works! Tested using a fresh JN site:

- WP 6.4.1
- Gutenberg 17.0.2
- Default TT4 theme
- Editing the homepage

|Case|Step|Result|
|-|-|-|
|Without this PR|-|600+ lines<br><br>image|
|With this PR|Default fonts from [TT4's theme.json](https://github.com/WordPress/twentytwentyfour/blob/df92472089ede6fae5924c124a93c843b84e8cbd/theme.json#L198): <br>image|image|
|With this PR + Global Styles -> Elements|image|image|
|With this PR + Global Styles -> Blocks|image|image|
|With this PR + Global Styles -> {Elements, Blocks}|Everything above|image|

**Pull request merged**
