### PR TITLE
VideoPress: Introduce `VideoPressUploader` component

### PR DESCRIPTION
**Pull request by renatoagds**
This is the first step to improving the uploading experience for VP new block.

Based on the idea of splitting the VideoPress experience into 2 moments: `Uploading` and `Previewing`, having a specific component for handling the `Upload` part could make easier the time to implement new uploading features such as uploading editor ( #24556 ) or error improvements.

#### Changes proposed in this Pull Request:

* Extract upload logic to `VideoPressUploader`.
* Keep the current behavior.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Start `Jetpack` plugin with support of `beta blocks`.
* Interact with `VideoPress (beta)`.
* Nothing should change in the experience.

### CODE REVIEW

**Comment by retrofox** [comment]
needs rebase :-/

**Comment by renatoagds** [comment]
@retrofox done!

**Review by retrofox — APPROVED** [review]
LGTM 👍

**Comment by renatoagds** [comment]
r248352-wpcom

**Pull request merged**
