### PR TITLE
Use docker image automattic/jetpack-wordpress-dev instead of local build for the docker environment

### PR DESCRIPTION
**Pull request by oskosk**
Introduce usage of the published image [automattic/jetpack-wordpress-dev](https://hub.docker.com/r/automattic/jetpack-wordpress-dev) which is built from the Dockerfile contained in this repo: See [docker/Dockerfile](https://github.com/Automattic/jetpack/blob/master/docker/Dockerfile)

## Why

The current approach to getting the environment running implies bulding of a docker image which consumes much battery and bandwidth. On top of that one needs to install node packages and such, thus adding to the consumption of battery and bandwidth. **Less than ideal for meetup situations**.

Usage of a pre-built image should decrease significantly the time from cloning Jetpack to having the docker environment running locally, **by a factor 7** approximately. (That is if the whole setup currently takes 3 mins, now it will take 25 seconds). This mostly depends on bandwidth available. It also reduces CPU consumption **significantly** as we don't need to buld the image.

**Notes:** I'd like to discuss the naming of the image and the implications of switching to using this image for people already using the environment. (Should be null). 

#### Changes proposed in this Pull Request:

* Updates the docker-compose.yml file to not declare the need for building the image locally and to depend on `automattic/jetpack-wordpress-dev`.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

Incoming link to P2 post.

#### Testing instructions:

For current users of the Jetpack Docker Environment

1. Checkout this branch
2. Run `yarn docker:up`.
3. Confirm the WordPress container is running by visiting the site as you usually do with the docker environment. 
4. Confirm that your WordPress works exactly the same as before. The database will be the same, the content inside the `wordpress` (and thus anything in `wp-content` will be the same

#### Proposed changelog entry for your changes:

* None needed

### CODE REVIEW

**Comment by leogermani** [comment]
Tested it and works smoothly.

Just wondering:

* Were there any changes to the Dockerfile worth of note?
* Is there anything we should add to our workflow with this change to make sure we keep this image up to date?

**Comment by oskosk** [comment]
Thanks for testing @leogermani 

> Were there any changes to the Dockerfile worth of note?

Not a single change to the Dockerfile. It worked and built as-is.

> Is there anything we should add to our workflow with this change to make sure we keep this image up to date?

Not actually. if we change `Dockerfile` here, the image in Docker Hub gets rebuilt automatically with those new settings that you may or not need. But if the image gets updated on Docker Hub and you want the updates, you can just  `docker pull automattic/jetpack-wordpress-dev`.  Maybe we can put that on a yarn script

**Comment by kraftbj** [comment]
> you can just docker pull automattic/jetpack-wordpress-dev. Maybe we can put that on a yarn script

Yeah, it would be good to have something like that. Would running `yarn docker:build-image` a second time not be sufficient?

First off, I love this. First run of testing it, it's a dream. I didn't believe it worked it was so fast.

Also, would there be any advantage (or could we technically even) leverage what the Foundation has https://hub.docker.com/r/wordpressdevelop/php/tags while we're at it?

Thinking that if we can leverage (and thus improve as we find areas for improvement) what Core has, it could be a win-win for us and for the broader ecosystem. cc: @pento

**Comment by oskosk** [comment]
@kraft: 

> Yeah, it would be good to have something like that. Would running yarn docker:build-image a second time not be sufficient?

It would be ok, indeed. But you'll be building the image locally yourself. By pulling the image built up there you can save bandwidth and battery. Building the images fetches a lot of stuff from Ubuntu, WordPress, etc

> Understanding how to keep it updated would be good too; how easy/hard is it, how do we ensure enough of us have permission to, etc.

We haz enough permissions giving building is automated with pushes (or merges) to master. Apart form that a tools is being built in MC for triggering builds. For more info on how this stuff works, you can check the FG page **Automattic on Docker Hub**,  the section titled **https://fieldguide.automattic.com/automattic-on-docker-hub/#mc-tool-for-images-on-docker-hub** . Currently deployed although the trigger for rebuilding is not shipped yet. That would be a nice way to overcome the lack of individual accounts on Docker Hub.

> Also, would there be any advantage (or could we technically even) leverage what the Foundation has https://hub.docker.com/r/wordpressdevelop/php/tags while we're at it?

This was actually on my plans after we could start relying on pre-built images as this PR proposes.

**Comment by kraftbj** [comment]
@oskosk After I commented, I tried it and very quickly understood the difference. I'm going to approve this for now so we can merge it, getting more people touching it.

With something like this, I'm okay with a lot of smaller PRs (updating docs, making small improvements) as long it doesn't backtrack from the day-to-day experience upon merge. Since this is a net-positive, let's get it in and keep moving forward IMO.

**Comment by sergeymitr** [comment]
The speed is impressive, nicely done!

**Comment by kraftbj** [comment]
r207717-wpcom

**Pull request merged**
