### PR TITLE
Add support jetpack Metadata for web stories plugin

### PR DESCRIPTION
**Pull request by spacedmonkey**
As of https://github.com/ampproject/amp-wp/pull/4315 in March, stories functionality was removed  from the [AMP plugin](https://github.com/ampproject/amp-wp) ( in [1.5.0](https://github.com/ampproject/amp-wp/releases/tag/1.5.0) ).

The functionality for stories was move to it's own plugin called [web-stories](https://github.com/google/web-stories-wp). With move of code base to it's own plugin, filters and actions were renamed. For example `amp_story_head` was renamed `web_stories_story_head`. This meant that the existing jetpack SEO / metadata that broke as action was not changed on the jetapck side. This PR fixes that. 

Fixes https://github.com/google/web-stories-wp/issues/3092

#### Changes proposed in this Pull Request:

* Change action name. 

#### Testing instructions:
This was extremely hard to test locally, any advice would be extremely useful here. 

#### Proposed changelog entry for your changes:

* Add support for Google Web Stories plugin

### CODE REVIEW

**Comment by spacedmonkey** [comment]
CC @swissspidy

**Review by jeherve — COMMENTED** [review]
Should we keep supporting old versions of the plugin as well?

**Comment by swissspidy** [comment]
> Should we keep supporting old versions of the plugin as well?

The legacy editor in the AMP plugin was experimental and opt-in, and removed quite a while ago. I don't think any sites are using it anymore.

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
Internal reference: r214828-wpcom

**Comment by swissspidy** [comment]
Sweet, thanks!

**Pull request merged**
