### PR TITLE
REST API: Site endpoint: Add updates

### PR DESCRIPTION
**Pull request by lezama**
Add array of available updates

### CODE REVIEW

**Comment by enejb** [comment]
The code looks good! Thank for the sync up.

**Comment by zinigor** [comment]
@lezama Looks like this code is already both in `master` and in `branch-3.7`. I'm not sure how github wants to merge this and even shows the green button, can you please check again if there's everything you need in `master`?

**Comment by lezama** [comment]
We broke GitHub yay! @enejb could you confirm that everything you need is merged already?

**Comment by enejb** [comment]
There is part of the code that shouldn't be in jetpack 
Line
https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L327

```
if ( get_option( 'jetpack_updates' ) ) {
     $response['options']['updates'] = (array) get_option( 'jetpack_updates' );
}
```
Needs to be removed since it is a duplicate.

**Comment by enejb** [comment]
Closing this in favour of https://github.com/Automattic/jetpack/pull/2585

**Pull request closed without merging**
