### PR TITLE
Dashboard: fix some styles in AAG cards.

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

Following the redesign of the Jetpack dashboard, this little style adjustment aims to fix ~2~ 1 layout issue in the cards appearing below the stats graph in the At a Glance dashboard:

**Scan card**

| Before | After |
| ------ | ----- |
| Screenshot 2023-04-27 at 15 02 49 | Screenshot 2023-04-27 at 15 02 54 |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* p1HpG7-lx8-p2

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* You'll want to start with a site running this branch, connected to WordPress.com, and where you have purchased a Jetpack Scan Daily plan.
* Go to Jetpack > Dashboard
* Check the cards below the stats graph, following the screenshots above.

### CODE REVIEW

**Comment by jeherve** [comment]
@sergeymitr I see now that you've addressed some of those things in #30324 already?

**Comment by sergeymitr** [comment]
Hi @jeherve, sorry for miscommunication.
I did address the Akimet button, but don't remember seeing the credentials icon issue.

**Comment by jeherve** [comment]
> Hi @jeherve, sorry for miscommunication. I did address the Akimet button, but don't remember seeing the credentials icon issue.

No this was my fault!

Should I close this PR and let you take the Scan icon fix to your own PR?

**Review by sergeymitr — APPROVED** [review]
👍

**Comment by zinigor** [comment]
Cherry picked in https://github.com/Automattic/jetpack/commit/d40f6d6ce37f36fe0af466fb5f3d1e319343d163.

**Pull request merged**
