### PR TITLE
SSO: Fix Button Text Alignment on Mobile  

### LINKED ISSUE #18658: SSO: Button text not centered on mobile
#### Steps to reproduce the issue

1. Ensure that you have a connected Jetpack site with SSO on
2. Log out if you are currently logged in
3. Go to `$site.com/wp-admin`
4. Resize your browser to mimic a mobile viewport and notice that the text in the button is near th top

#### What I expected

The button text to be vertically and horizontally centered

#### What happened instead

Text was not vertically centered

**Screenshots**

In these screenshots, note how the text placement in the button is correct for web but incorrect for mobile.

Screen Shot 2021-02-01 at 2 26 46 PM

Screen Shot 2021-02-01 at 2 26 49 PM

### PR DESCRIPTION
**Pull request by sdixon194**
Fixes #18658

#### Changes proposed in this Pull Request:

* Fixes issue with login alignment on mobile.

#### Jetpack product discussion
N/a

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Create a Jetpack site and enable SSO/WordPress.com Login
* Log out (or open the site in an incognito window) and visit WP-Admin
* Resize the screen to less than 782px
* See how the text in the login button isn't vertically aligned 
* Apply this branch
* Refresh and see how the button is now centered.

Checked multiple browsers and it works fine. Did some digging, but unsure why the line height is not-needed now or why it was added. Maybe a CSS wizard can shed some light ¯\_(ツ)_/¯

**Before**

Screen Shot on 2021-02-09 at 17:23:44

**After**

Screen Shot on 2021-02-09 at 17:28:23

#### Proposed changelog entry for your changes:

* fixes login button alignment when SSO is enabled

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
It feels like there is still something misaligned; there seems to be more space below the text than above:

image

**Comment by sdixon194** [comment]
> Is it just me?

I investigated this a good amount last night and I also _thought it was just me._

I played around some more and inversed the rule (so the line height only gets applied on larger screens), which seems to have done it. That seem better?

**Comment by jeherve** [comment]
Flagging this for a design review since they're the pros with those kinds of changes :)

**Comment by eeeeevon13** [comment]
We may have a math problem here. The logo looks to be coming in at 21px which will always create uneven margins top and bottom. 
vspace

**Comment by jeherve** [comment]
@eeeeevon13 How do you think we should go about fixing this? Should we make the whole button a bit higher?

**Comment by eeeeevon13** [comment]
@jeherve  Sorry for dropping off there, this one fell through the cracks!  The easiest thing would be to make the logo 1px smaller in order to keep all of our buttons consistent. Most of our icons are at 24px, this one is already less than that at 21, might as well go down to 20 so it's even.

**Comment by keoshi** [comment]
IMO changing the icon size could have other side effects that we're not necessarily taking into consideration right now, so I'd try to fix this by using the same logic as the base button.

The code being applied in large desktop is:

```
height: 36px;
line-height: 34px;
```

So using the same principle of using a line-height value of `height - 2px` (1px for both top and bottom) and considering `.wp-core-ui .button` has a `min-height: 40px` on these resolutions we get:

```
@media screen and (max-width: 782px) {
    .jetpack-sso.button {
        line-height: 38px;
    }
}
```

It looks like this:

image

**Review by keoshi — APPROVED** [review]
@renatoagds Sorry that I missed that before, that looks like a great solution! Ship it. 🚀

**Comment by sdixon194** [comment]
This works for me! But I don't think I can approve since I started the PR, even though it's not my work anymore :D

**Review by samiff — APPROVED** [review]

**Pull request merged**
