### PR TITLE
Changes copy upon jetpack activation

### PR DESCRIPTION
**Pull request by leogermani**
NOTE: This PR assumes user-less connections are active for all users and should only be merged if and when we decide we are shipping it.

With user-less, when the users click on "Set up Jetpack" and see the in-place connection UI to authorize a user, the connection is already established.

This PR makes the title of this step more clear, to inform the user that Jetpack has been activated.

In our testings, some people reported confusion after bailing the connection flow and realizing Jetpack was connected even though they didn't make it to the end.

#### Changes proposed in this Pull Request:

* Changes the title of the in-place connection page after Jetpack is connected on a site level

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Launch a new site with user-less testing mode
* Click "Set up Jetpack" either in the WP-admin dashboard or from the Jetpack Dashboard
* Make sure that, while the loader is being displayed in the page, that the title remains the same: "Activate essential WordPress security and performance tools by setting up Jetpack"
* When the loader disappears and the option to log in a user shows up, make sure the title of the page changed to "Jetpack is activated!<br>Unlock more amazing features by connecting a user account"

Captura de Tela 2021-04-21 às 18 28 25

Repeat the flow above:
* in a window where you're logged in to WPCOM
* in a window you're not logged in to WPCOM
* in a window without support to 3rd party cookies

Note: For browsers without 3rd party cookies support (except Safari) there's a known issue in the experience, where the page loads and takes a while before redirecting to Calypso. This PR does not solve that, we just want to make sure things work.

Also, we might need to change the copy on the Calypso side.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This looks good to me. I'll let someone from Editorial review the copy. 👍

**Comment by kristastevens** [comment]
I think we may have already [taken care of this request](https://jetpackcrew.wordpress.com/2021/04/19/deciding-the-user-less-mvp-flow/?c=4889#comment-4889).

**Comment by kristastevens** [comment]
I think we may have already taken care of this request. Let me know if I'm missing something. 

Screen Shot 2021-04-22 at 10 13 27 AM

**Comment by leogermani** [comment]
> I think we may have already taken care of this request. Let me know if I'm missing something.
> 
> Screen Shot 2021-04-22 at 10 13 27 AM

Yes! -> p9dueE-2Ky-p2#comment-4881

**Comment by jeherve** [comment]
> I think we may have already taken care of this request

Perfect! Is "Unlock more amazing features by connecting a user account" fine too? It looks good to me, just curious about "user account" in that sentence. Either way, this should be ready to merge for now, we can always revisit later if needed. :)

**Comment by kristastevens** [comment]
I think it's fine.

**Pull request merged**
