### PR TITLE
Widget Visibility: Restrict to top level blocks

### LINKED ISSUE #20057: Widget Visibility: add controls to widget block editor
Related issue: https://github.com/WordPress/gutenberg/issues/31181

Jetpack's [Widget Visibility](https://jetpack.com/support/widget-visibility/) module adds visibility controls to the widgets available in Appearance > Customize > Widgets and Appearance > Widgets

image

Those controls are added here:
https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php#L12

With the upcoming version of WordPress, the widget UI changes to allow you to insert legacy widgets as well as blocks, in two areas:
- Under Appearance > Customize > Widgets in a refreshed UI.
- Under a new interface at Appearance > Widgets, now loading `themes.php?page=gutenberg-widgets` instead of `widgets.php`.

We'll need to do a few things to ensure that Widget Visibility is compatible with those changes:

- [x] Revisit the changes that were introduced in #17413 to allow the use of Widget Visibility in the block widget editor.
- [x] Update the Widget Visibility JS so it can hook its buttons into the block widget editor as well as the old interface.
- [x] Update its CSS to ensure its layout looks good in the old and the new UI.
- [ ] Ensure that widget visibility controls are displayed for blocks.

*******

Primary issue: #19654 

Related discussion: pbAok1-2dI-p2

### PR DESCRIPTION
**Pull request by mreishus**
Fixes #20057

#### Changes proposed in this Pull Request (TLDR):
* Reduce the scope of the Widget Visibility feature: No longer support recursive filtering and completely remove the `render_block()` call from `filter_widget()`. Users are only allowed to set visibility rules on the top level block of each widget.

#### Changes proposed in this Pull Request:
* In #20731, we added "Widget Visibility", an enhancement to gutenberg block widgets which allow users to apply rules that decide when blocks inside widgets display.
* When this was deployed to wpcom, we saw many crashes happening in user configurations that were not happening in a stock configuration. For example, one culprit was wpcom's infinite scroll homepage plugin.
* There is more detail about these crashes here: 
  * https://github.com/Automattic/wp-calypso/issues/56526 
  * https://github.com/Automattic/wp-calypso/issues/56546
* In all known cases, crashes were related to `filter_widget()` running `render_block()`. Before Widget Visibility was implemented, `filter_widget()` only returned its argument unchanged or returned false. With Widget Visibility, sometimes it would change the content of the block passed to it by re-rendering the block, and return that.
  * Re-rendering blocks was needed to provide support for nested rules. For example, if a widget was a column block, and the left column had visibility rules XYZ, and the right column had visibility rules ABC, we would rerender the entire column block so we could apply the visibility rules to children of the widget, instead of only the widget itself.
  * `filter_widget()` running `render_block()` is risky because so many plugins modify rendering behavior. For example, we saw an infinite loop bug where `render_block()` would need to seek out sidebar settings, which would end up getting a list of widgets and calling `filter_widget()`, which would call `render_block()`, which called `filter_widget()`.. etc.
* I was able to prevent infinite loops by using a static flag on the `Jetpack_Widget_Conditions` class, but there was at least one render related bug I couldn't fix (wp-calypso#56546).
* My solution is to reduce the scope of the Widget Visibility feature: No longer support recursive filtering and completely remove the `render_block()` call from `filter_widget()`.
  * Now `filter_widget()` works the same as before: It only ever returns false or returns its argument unchanged.
  * Scope of potential bugs is drastically reduced.
  * Now users may only set visibility settings on the outermost block of each widget.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* `jetpack docker up`
* Make sure WP is installed and you can visit /wp-admin. You may need to use `jetpack docker install`, and possibly edit one of the env files such that your password isn't easily guessable if you decide to use a tunneling solution in the future.
* In another terminal, `jetpack watch plugins/jetpack`
  * You might also need to `jetpack build plugins/jetpack` first.
* Make sure this setting is turned on in jetpack settings.

* Visit http://localhost/wp-admin/widgets.php
* Add a block based widget here
* In the outermost block of any widget, go to the advanced section of the gutenberg sidebar

You should see the following in the sidebar, which lets you set up rules:

When visiting the frontend of the site, those widgets should follow those rules.

* If you select a non-outermost block, you will see a message asking you to select the outermost block. For example, add a columns block, then add a paragraph block inside one of the columns, and attempt to set visibility rules on that paragraph block.

#### Testing instructions (wpcom)

We need to make a custom patch, since https://github.com/Automattic/jetpack/issues/20057 is merged in JP but reverted on wpcom.

#### Testing instructions (Unit Tests)

* `jetpack docker phpunit -- --filter=Widget_Conditions`
  * In order to get the tests working, I had to: `jetpack docker sh`, then `cd /tmp/wordpress-develop/tests/phpunit/data`, then `svn up -r44722`, then `cd ../includes/` , then again `svn up -r44722`. This was done a few weeks ago and I am no longer certain this is working with new docker images.

### CODE REVIEW

**Comment by sixhours** [comment]
I'm testing this locally, and I'm able to see the widget visibility settings when in `/wp-admin/widgets.php`, but not in the Customizer for the same widget:

https://user-images.githubusercontent.com/2124984/135292557-bb65c81a-74e2-4085-9b6f-8ea39c584fda.mov

**Comment by sixhours** [comment]
The good news is the widgets behave as expected on my local test site. 👍

**Comment by mreishus** [comment]
Good catch; fixed.

**Comment by samiff** [comment]
Before patching, was able to recreate the `Fatal error: Uncaught Error: Call to a member function render() on null wp-includes/class-wp-block.php on line 21` by using a column block and setting a mix of nested visibility options.

Then I applied this PR and the fatal was no longer occurring. Was also able to see the `Please select the top level block...` message on the nested column block elements. Tried some silly nesting but wasn't able to break things.

**Review by kraftbj — APPROVED** [review]

**Comment by jeherve** [comment]
@mreishus I've created a WordPress.com diff, D67826-code, to bring us back in sync on WordPress.com.

It tests well for me. I'll let you handle the commit?

Thank you!

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-10.2` in c306f484aed65cbb27f6f51463adefec56ea6ae1

**Comment by samiff** [comment]
r232714-wpcom

Looking good on wpcom so far, keeping an eye on support channels today.

**Pull request merged**
