### PR TITLE
Add compatibility for Twenty Nineteen default theme

### PR DESCRIPTION
**Pull request by allancole**
This PR addresses issue #10335. It still needs a little more work as outlined below.

#### Changes proposed in this Pull Request:

- [x] Add Infinite Scroll support and tweak CSS to make sure the IS buttons look good.
- [x] Add support for Responsive Videos.
- [x] Add Content Options support for author-bio, blog-display, post-details, and featured-images 
- [x] Alter Gallery widget default width (possibly not necessary unless using older versions of WP).
- [ ] Style widgets and shortcodes to match the style of the theme (coming soon).
- [ ] Add Social Menu Support (requires a pending code refactor in theme, may not be possible).

#### Testing instructions:

* Test the theme against all the customizer and Jetpack settings mentioned above 
* **Note**: requires latest `master` version of Twenty Nineteen from Github here: https://github.com/WordPress/twentynineteen/

#### Proposed changelog entry for your changes:

* Add compatibility for Twenty Nineteen default theme

### CODE REVIEW

**Comment by jeherve** [comment]
Thanks for your work so far. Do you think you will have the chance to work on the widget styles today so we can review this PR and include it in Jetpack before the code freeze tomorrow?

**Comment by davidakennedy** [comment]
@jeherve @crunnells is looking at this today since @allancole hasn't quite finished it.

**Comment by jeherve** [comment]
Thank you!

**Comment by crunnells** [comment]
@jeherve I added a minor update to some widget styles, and will probably take another look at it with fresh eyes tomorrow.

**Review by jeherve — DISMISSED** [review]
This works well so far. I ran into issues when trying to hide categories from the Content Options panel (it hid tags as well), but this may be an issue with Content Options itself.

**Comment by crunnells** [comment]
> I ran into issues when trying to hide categories from the Content Options panel (it hid tags as well), but this may be an issue with Content Options itself.

I submitted a PR to fix this on the Twenty Nineteen side of things: https://github.com/WordPress/twentynineteen/pull/420

**Comment by jeherve** [comment]
Excellent, thank you! I am going to merge this as is for now, and you can keep iterating on widget styles in another PR. That will allow us to put your work in front of beta testers already 👍

**Review by jeherve — APPROVED** [review]
Looking good for now. Let's test this!

**Pull request merged**
