### PR TITLE
Untangle: Remove width overrides in the admin menu

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/dotcom-forge/issues/5284

## Proposed changes:

This PR reverts the admin menu width in Classic styles to align with core.

> [!NOTE]
> Elements such as the site card, upsell banner, and stats will be removed in separate PRs. We can merge this PR after those have already been merged.

| Before | After |
| --- | --- |
| Screenshot 2024-01-24 at 10 47 09 AM | Screenshot 2024-01-24 at 10 46 19 AM |

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Head to Settings → Hosting Configuration.
* Scroll to the Admin interface style section, and select Classic style.
* Refresh the page if needed.
* Ensure that the admin menu width is updated as described above.

### CODE REVIEW

**Comment by arthur791004** [comment]
I guess we have to remove the “Upgrades” menu before shipping this, right?

**Comment by fushar** [comment]
Looks like we have an ongoing conversation related to the width. See: pe7F0s-1E7-p2#comment-2096.

**Comment by lsl** [comment]
This should only be applied to sites using classic style toggled on. The way "Creator" scrunches up against "Upgrades" tells me this needs to be dependent on shipping https://github.com/Automattic/dotcom-forge/issues/5308 first (Adding a note there that we need to drop the plan name from the menu item at the same time)

**Comment by taipeicoder** [comment]
Yep, we need to account for the admin interface. I'm holding this PR for now as we are still discussing division of work between team Loop and us.

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/dotcom-forge/issues/5284#issuecomment-1942536195.

**Pull request closed without merging**
