### PR TITLE
Widget Visibility: Add Parent Page option

### PR DESCRIPTION
**Pull request by kraftbj**
See #1153

Note this is @odie2's code, just opening the PR to further the conversation.

### CODE REVIEW

**Comment by odie2** [comment]
Thanks for open, I have always problems with opening PR on such big repositories like Jetpack...

Note that there should be added little JS to show in-live checkbox when user select page that have children (for example could be checked inside current `<select>`). At the moment checkbox will apper for page that have children only after clicking Apply/Saving/Reloading settings' page.

**Comment by kraftbj** [comment]
:+1:  If you commit anything more against your branch, it'll automatically update the PR.

**Comment by samhotchkiss** [comment]
This needs some eyes from tdiv-- @michaeldcain ?

**Comment by michaeldcain** [comment]
I can take a look today.

**Comment by samhotchkiss** [comment]
Awesome, thank you

**Comment by richardmuscat** [comment]
@michaeldcain just wondering whether you had some time to look into this so that the PR stands a chance of making it into 3.7 :-)

**Comment by michaeldcain** [comment]
@richardmuscat sorry, got caught up last week. looking this afternoon.

**Comment by zinigor** [comment]
Closing in favour of #2582

**Pull request closed without merging**
