### PR TITLE
Dashboard: Migrate CommonJS module.exports to ESM export default

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request:

Migrate CommonJS module.exports to ESM export default. Produced by running `calypso-codemods commonjs-exports _inc/client/` ([see](https://github.com/Automattic/calypso-codemods#getting-started)).

Carried over from https://github.com/Automattic/jetpack/pull/11677#issuecomment-476560598

#### Testing instructions:

Smoke-test the heck out of Jetpack's React dashboard.

#### Proposed changelog entry for your changes:

Dashboard: Migrate CommonJS module.exports to ESM export default

### CODE REVIEW

**Review by scruffian — DISMISSED** [review]
Tested the dashboard and everything looks good. Code looks good too.

**Comment by sirreal** [comment]
I pushed changes to update a couple of `export default { /* bag of names */ }` to use named exports (and imports).

**Review by sirreal — APPROVED** [review]
Looks good and testing well 👍

**Review by eliorivero — APPROVED** [review]
Go! 🐑

**Pull request merged**
