### PR TITLE
Settings UI - At a Glance: add link to wpcom in Monitor card

### LINKED ISSUE #6226: Settings: Update Monitor DashItem to link to notification settings in Calypso
Design TBD.

This is pending addition of downtime notification options to the notification settings area. https://github.com/Automattic/wp-calypso/issues/11021

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6226 

#### Changes proposed in this Pull Request:

* add link in Monitor card in At a Glance pointing to Security settings in Calypso where user will be able to manage notifications.

This _is how it looks in this PR_, which is what @MichaelArestad suggested in #6226

captura de pantalla 2017-02-16 a las 19 32 28
captura de pantalla 2017-02-16 a las 19 32 39

Since this card also has a toggle and there were no instructions about what to do with the toggle, I assumed we should leave it and tested adding a cog icon

captura de pantalla 2017-02-16 a las 19 37 18

This is _not_ in this PR but it's trivial to implement it.

* the link is pointed to `https://wordpress.com/settings/security/%site%`. @beaulebens pointed in #6226 that it should point to `https://wordpress.com/me/notifications` but the referenced issue wasn't implemented so far https://github.com/Automattic/wp-calypso/issues/11021 and if it was implemented, it would also need a way to go straight into the relevant site, instead of the list of sites. So for now, it's pointed to security.

If we keep this, it would be good to have an `id` in the card Jetpack Monitor in Calypso so we can add it to the link and scroll the view straight to that card.

captura de pantalla 2017-02-16 a las 20 01 10

* removes props siteAdminUrl and siteRawUrl that were passed in cascade (and unused in intermediate components) and instead fetches them in DashItem where they're used.

* updates test to reflect that Monitor now has a button in addition to the toggle

#### Testing instructions:

* should not be visible in dev mode
* should not be visible when card is toggled off
* should be visible when card is toggled on and point to `https://wordpress.com/settings/security/%site%`

### CODE REVIEW

**Comment by beaulebens** [comment]
In your screenshot above, you can see that there's a "fade out" image that's showing (next to the toggle), which shouldn't be there any more (FWIW, I see it on all "disabled" cards on the dashboard):



I see the same problem on a dev-mode site:

screen shot 2017-02-19 at 7 16 40 pm

I'll defer to @MichaelArestad on whether to use the button or a cog icon.

I think the toggle was actually intended to go away, since the idea was that Monitor can run without much impact (always), and if you don't want to receive notifications then you can just turn those off (thus the settings link).

**Comment by MichaelArestad** [comment]
I would remove the toggle and just use the button.

@beaulebens created an issue: #6447

**Comment by eliorivero** [comment]
captura de pantalla 2017-02-20 a las 17 43 48
Updated to display only the button.

**Comment by MichaelArestad** [comment]
LGTM

**Pull request merged**
