### PR TITLE
My Jetpack: Show while disconnected

### PR DESCRIPTION
**Pull request by oskosk**
* Shows My Jetpack while disconnected

#### Changes proposed in this Pull Request:

* Removes check for connection from MyJetpack's initializer.
* Removes check for connection before rendering MyJetpackScreen component.
* Removes redirection when disconnected from connectionWatchter.
* Update behavior of connectivity problem preventing purchases fetch to only show if the error we get is not related to site connection to Jetpack.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### This is how My Jetpack will show when the site is not connected

image

image

image

##### This message only shows now when we can't fetch purchases due to reasons not related to the connection to WordPress.com

image

#### Jetpack product discussion
Incoming

#### Does this pull request change what data or activity we track or use?
Maybe

#### Testing instructions:
* Launch a [fresh site with this Jurassic Ninja link](https://jurassic.ninja/create?jetpack-beta&branches.jetpack=update/my-jetpack-show-while-disconnected&branches.jetpack-backup=update/my-jetpack-show-while-disconnected&branches.jetpack-boost=update/my-jetpack-show-while-disconnected&branches.jetpack-protect=update/my-jetpack-show-while-disconnected&branches.jetpack-search=update/my-jetpack-show-while-disconnected&branches.jetpack-social=update/my-jetpack-show-while-disconnected&branches.jetpack-starter-plugin=update/my-jetpack-show-while-disconnected&wp-debug-log&nojetpack)
* Confirm you see My Jetpack while the site is still not connected

### CODE REVIEW

**Review by nunyvega — COMMENTED** [review]
Code changes look good, testing now

**Comment by nunyvega** [comment]
@oskosk the MyJetpack section shows as expected, but purchase flows are broken because of the missing connection:

https://user-images.githubusercontent.com/16329583/200906363-d0c1ebc4-d075-438e-a1f4-f0cef99408e6.mov

What's the expected behavior here? Maybe we should prompt for like we do for license activation:

https://user-images.githubusercontent.com/16329583/200906475-4545d64c-47e7-47b7-9987-8a55310b0d39.mov

**Comment by lhkowalski** [comment]
I can confirm that the `My Jetpack` page is showing as expected:

Screen Shot 2022-11-09 at 17 18 55

When I clicked on the Purchase button for `Backup`, I got to the `Add Backup` page, and after clicking the `Add Jetpack Backup` button I got this error message, that may be helpful on deciding how to solve/handle this scenario:

Screen Shot 2022-11-09 at 17 26 05

Some of the products can be activated on the My Jetpack screen. They probably don't require the connection, but are they getting to a valid state in the case we activate then without the connection, thinking long term?

When I click the "Activate a license (requires user connection)" link, I correctly see the prompt to connect my user:

Screen Shot 2022-11-09 at 17 32 07

The flow to connect my user works as expected and then I can see the "Activate a license" again.

After this, the purchase buttons work as expected, redirecting me to the checkout. Also, the "Activate a license" link send me to a prompt for a license key, which seems to be the expected flow.

I also disconnected the site and went to `My Jetpack` again, and the behavior stays the same.

**Comment by oskosk** [comment]
@renatoagds I launched a JN site with this branch and tested clicking on Purchase a plan and on "Add XXXX"  buttons (e.g., Add Search), following the interstitials, and I still couldn't properly get to anywhere else other than wordpress.com/plan screen

image

**Comment by lhkowalski** [comment]
I am getting a 400 response on an AJAX call to the `purchases` endpoint, as soon as I open the "My Jetpack" menu:

Screen Shot 2022-11-22 at 14 46 26

The response body is this:

```
{"code":"not_connected","message":"Your site is not connected to Jetpack.","data":{"status":400}}
```

This is not breaking anything, but is being reported on the console.

**Comment by renatoagds** [comment]
> This is not breaking anything, but is being reported on the console.

Yep, we should avoid do this fetch if disconnected. But don't think is a block for this one.

**Comment by renatoagds** [comment]
> I launched a JN site with this branch and tested clicking on Purchase a plan and on "Add XXXX" buttons (e.g., Add Search), following the interstitials, and I still couldn't properly get to anywhere else other than wordpress.com/plan screen

@oskosk Pushed a change for this logic, can you check if looks good now?

**Comment by nunyvega** [comment]
I tried running it locally and in JN using the proposed link, in both cases I don't see My Jetpack while the site is disconnected:
Screenshot 2022-11-24 at 15 04 56
Screenshot 2022-11-24 at 15 04 36

I tried accessing My Jetpack directly using its URL and I get this:
Screenshot 2022-11-24 at 15 07 06

**Comment by renatoagds** [comment]
@nunyvega fixed ✅

**Comment by nunyvega** [comment]
My Jetpack shows now when disconnected :)

---
I'm getting this error in My Jetpack when disconnected:
Screenshot 2022-11-24 at 16 43 29



---


If I click on upgrade and then go back, or if I click on connect and then don't approve it, I get this:
Screenshot 2022-11-24 at 16 45 05
The `The Some products need a connection..` disappears

**Review by nunyvega — APPROVED** [review]
LGTM

🚢

**Pull request merged**
