### PR TITLE
General: remove deprecated core get_page_by_title

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed changes:

See #27795

Let's use direct WP queries instead, as recommended:
https://make.wordpress.org/core/2023/03/06/get_page_by_title-deprecated/

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

The changes in Jetpack's `functions.global.php` are not really used anymore. We could probably get rid of all that  logic at this point; the code exists to facilitate the migration from our own widget (https://github.com/Automattic/jetpack/blob/3104e377ae2d45ad2d4ffadfd839cee47aa871df/projects/plugins/jetpack/modules/widgets/image-widget.php#L25) to the Core widget (see #7103). This happened in WP 4.8, so we could probably remove our widget and the logic. Created #29458 to keep track of that.

The change to the Debug Helper like so;

* Activate the Jetpack Debug plugin
* Go to `/wp-admin/admin.php?page=jetpack-debug-tools`
* Activate the "Jetpack Scan Helper" module
* Go to `/wp-admin/admin.php?page=scan-helper`
* Activate each threat and validate that it is added to the site, via the Protect plugin.
* Deactivate each threat and validate that it is removed from the site.

### CODE REVIEW

**Comment by oskosk** [comment]
This looks good. I'm going through the testing instructions right now. Waiting for Protect to come back to me. One question. Do we have a preference on WP_Query over `get_posts()`

**Comment by oskosk** [comment]
I'm not able to trigger the code path for testing this. The Scan debug helper, with all the checkboxes active, makes Protect only report the EICAR Threat to me
image

**Comment by jeherve** [comment]
> One question. Do we have a preference on WP_Query over `get_posts()`

I suppose `get_posts()` would work just as well in this scenario, I only picked `WP_Query` because of personal preference. Happy to change if that's a problem.

> The Scan debug helper, with all the checkboxes active, makes Protect only report the EICAR Threat to me

Same thing for me. That may be a better question for @nateweller ; in my testing I sticked to checking that the Scan test post could be added and removed when toggling the option.

**Comment by nateweller** [comment]
I end up with seven identified threats, but it does not include the database threat. The scan tester post is added correctly, but we aren't detecting it as a threat. The scan team will have to look into this further (tasked: 1201069996155224-as-1204188299254038). Thanks for tagging!

One potential thing to check - have you previously ignored these threats? Can check here: https://cloud.jetpack.com/scan/history/example.com/ignored

The changes in this PR that affect the scan debug helper LGTM :shipit: 

Screenshot 2023-03-15 at 12 34 30 PM

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
