### PR TITLE
Boost: Fix stylesheet loading when cloud css is generating

### PR DESCRIPTION
**Pull request by karthikax**
Fixes 62-gh-Automattic/boost-hydra

#### Changes proposed in this Pull Request:

* Check for Cloud CSS generation string and if it exists, do not alter stylesheet loading. This prevents broken stylesheets during the first few frames of page load

#### Jetpack product discussion

NA

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Define constant `JETPACK_BOOST_CLOUD_CSS` as true to enable Cloud Critical CSS.
* Navigate to Jetpack boost dashboard: `wp-admin/admin.php?page=jetpack-boost`
* Open the site home page in a new browser tab and then open Inspect elements
* Open the first tab with Jetpack boost dashboard and enable Cloud CSS or click regenerate.
* Immediately open the second tab and refresh the page.
* Confirm that the Critical CSS does not exist under `head` tag.

### CODE REVIEW

**Review by eAdnan007 — CHANGES_REQUESTED** [review]
I think this approach has some limitations. Specially because there is a translated string involved. There is at least one instance where it would not work. 

Plugins like polylang lets you have multiple languages in the same site. The front-end pages may have multiple different languages. The string would then be different and wouldn't match. It is also possible that the site language is different from the admin users preference, resulting in the same issue.

I'd suggest keeping a separate flag to identify the currently generating status. In fact, now that I think of it, the css comment should probably also display depending on that flag instead of placing the string value in the db. This way we can ensure the CSS comment is also consistent with the front-end language.

**Comment by thingalon** [comment]
> in fact, now that I think of it, the css comment should probably also display depending on that flag instead of placing the string value in the db. This way we can ensure the CSS comment is also consistent with the front-end language.

☝️

**Comment by thingalon** [comment]
Closing in favor of https://github.com/Automattic/jetpack/pull/23262

**Review by thingalon — APPROVED** [review]
👍

**Review by eAdnan007 — APPROVED** [review]
🚢

**Pull request merged**
