### PR TITLE
Products: Update links on Backup/Security cards to direct to checkout for real-time products

### PR DESCRIPTION
**Pull request by mattgawarecki**
Resolves `1200412004370260-as-1201289205953284`.

#### Changes proposed in this Pull Request:

* On product pages (`/admin.php?page=jetpack#/product/*`) that feature Backup or Security, update call-to-action links so that people are sent to checkout for new real-time products instead of the older Daily products.
* Update the feature list on the Jetpack Backup card to reflect the correct amount of available backup storage (10 GB instead of unlimited).

#### Jetpack product discussion

`pbtFFM-XN-p2`

#### Does this pull request change what data or activity we track or use?

No changes 👍 

#### Testing instructions:

1.  If your Jetpack site doesn't already have a Backup subscription, go to the **Jetpack > Dashboard > At A Glance** page and click the **Upgrade** button on the **Backup** card. *(Alternatively, manually go to `/wp-admin/admin.php?page=jetpack#/product/backup` in your browser.)*
2. Verify the list of features for the Backup product are updated as shown in the right-side screenshot below (10GB of storage, not unlimited).
3. Verify the buttons for adding Backup/Security each redirect to checkout for their respective real-time version, with 10GB of storage and a yearly billing term.

#### Reference screenshot

image image

### CODE REVIEW

**Review by monsieur-z — DISMISSED** [review]
Code looks good, and everything tested as expected 👍

**Review by samiff — DISMISSED** [review]
Worked well for me 👍 

@mattgawarecki I did notice that on the `/wp-admin/admin.php?page=jetpack#/product/scan` page:

Markup on 2021-11-09 at 11:10:17

There is a small icon while the `/product/backup` page doesn't use one. Additionally on the  `/product/scan` page, it's not clear what "All Backup Features" would entail.

**Comment by mattgawarecki** [comment]
@samiff Great catch! I didn't notice the icons were missing. I just pushed a commit to fix that issue, if you could kindly confirm for me?

**Comment by mattgawarecki** [comment]
> Additionally on the /product/scan page, it's not clear what "All Backup Features" would entail.

I agree this is something that needs to be fixed, but I'm not able to get to it at the moment. To make sure it gets addressed though, I created `1164141197617539-as-1201348435861221` to capture this concern.

**Comment by samiff** [comment]
> @samiff Great catch! I didn't notice the icons were missing. I just pushed a commit to fix that issue, if you could kindly confirm for me?

Happy to take a look, did that get pushed to this branch?

**Comment by mattgawarecki** [comment]
> Happy to take a look, did that get pushed to this branch?

Ahhh, fooey -- I forgot to push! It should be on the branch now, at your convenience 🙂

**Review by samiff — APPROVED** [review]
There we go! I can see all the icons now on both scan & backup pages.

**Pull request merged**
