### PR TITLE
Subscriber Login: Move Subscriber Login block to production

### PR DESCRIPTION
**Pull request by pkuliga**
Part of https://github.com/Automattic/jetpack/issues/34884

## Proposed changes:

It moves the Subscriber Login block to production.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Make sure the Subscriber Login block is no longer marked as a beta block.

### CODE REVIEW

**Comment by jeherve** [comment]
If we're moving this block to production, would it be possible to let the WordPress.com and Jetpack support teams know, so they can work on the necessary support documents, and so they know what this new block brings to customers?

Thanks!

Also cc'ing @Automattic/jetpack-garage for general awareness for the upcoming release.

**Comment by samiff** [comment]
> Also cc'ing @Automattic/jetpack-garage for general awareness for the upcoming release.

Thanks! For reference the hard cut for Jetpack 13.1 will be on 2024-02-05

Internal testing for Jetpack 13.1 has started this week, so if we want testers to give this a spin, you can either update the testing thread or let me know and I can assist: p8oabR-1qU-p2

**Comment by pkuliga** [comment]
> Internal testing for Jetpack 13.1 has started this week, so if we want testers to give this a spin, you can either update the testing thread or let me know and I can assist: p8oabR-1qU-p2

Sure, I can do it. By "update the testing thread" you mean adding some testing scenarios below "Jetpack 13.1 Testing Items"?

**Comment by samiff** [comment]
> By "update the testing thread" you mean adding some testing scenarios below "Jetpack 13.1 Testing Items"?

Yes! Any steps you think might be helpful in surfacing any bugs in the different testing environments.

**Comment by pkuliga** [comment]
Added 😄 

p8oabR-1qU-p2#subscriber-login-block

**Review by simison — DISMISSED** [review]

**Review by simison — APPROVED** [review]

**Pull request merged**
