### PR TITLE
Subscribe block: apply correct extra padding to the block with subscriptions count on

### LINKED ISSUE #23325: Subscription Block: subscribers count element is misaligned when padding applied and published.
Screenshot 2022-03-09 at 13 48 53
Screenshot taken @ p8oabR-Oy-p2#comment-6030

### Impacted plugin

Jetpack

### Steps to Reproduce

Theme: `twenty twenty-one`
Site: `wpcom hosted`

1. Create a post, or a page, with subscription block.
2. Set the subscription count to be displayed in the subscription block. This can be done in the block's sidebar under `Settings` tab by enabling the `Show subscriber count` toggle.
3. Add padding to the block. This can be done in the block's sidebar in the `Dimensions` tab by clicking on the `+` icon, selecting `Padding` and then setting some value greater than zero. 
4. Publish the page.
5. By navigating to the published page subscribe, and confirm the subscription, with at least 2 email addresses. This is required because otherwise the subscription count text will not show up on a published page.
6. Now edit the page and have the published page opened in another tab/window. Compare how the alignment of the subscription count element differs between the two. 

### A clear and concise description of what you expected to happen.

Expected the subscription count text to be vertically aligned with the email address input and the `Subscribe` button. 

### What actually happened

The subscription count element is misaligned.

### Other information

The issue was originally reported here: p8oabR-Oy-p2#comment-6030

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by mashikag**
#### Fixes 
This PR fixes an issue where subscription blocks with extra padding and subscriptions count on, were displayed with broken padding in published content (in editor all looked just fine).

##### Editor view:
Screenshot 2022-07-04 at 09 14 10

##### Published content:
Screenshot 2022-07-04 at 09 15 26

  
#### Changes proposed in this Pull Request:

* apply container `div` to the `Save` component of subscribe block
  * that way styles applied via block settings are applied to the container `div` and are not overriding styles applied by component's classes
* apply `jetpack-subscribe-count` class directly to the `p` element of the subscriptions count's component
  * There is no need for the outer `div`
  * Now the DOM structure of the `views.php` resembles more closely the structure of the related `editor.js` component
  *  This required making a small amendment to the `view.scss` styles definition file. This ensures that the style is still properly applied to both, the subscribe block component rendered in published content and when rendered in editor 

#### Does this pull request change what data or activity we track or use?

No, it does not. 

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Go to create a new post
* Insert `Subscribe` block
* In the `Subscribe` block's settings set the following
  * `Show subscribe count` under `Settings` to on
  * `Padding` under `Dimensions` to some positive number that will make debugging easier (usually the higher value the better), e.g. 50px.
  
Screenshot 2022-07-04 at 09 23 48

* Save the post
* View the saved post and notice how the subscription's count element is misaligned.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
Taking a quick look at this, I wanted to point out that since you're changing the way block content is saved in the database, you'll need to handle deprecating previous versions of the block. If we do not add this deprecation, site owners wanting to edit posts with a previous version of the block will see a block validation error in the editor.e This topic is covered [here](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/), and you can find previous deprecations for this block in https://github.com/Automattic/jetpack/blob/e7067c4f42dac3539b1548f074088713f3384276/projects/plugins/jetpack/extensions/blocks/subscriptions/deprecated/index.js
Those previous deprecations can offer useful tips when creating a new one.

The failing tests on this PR should be resolved when you fix this issue.

**Comment by ivan-ottinger** [comment]
Here is also a [link to doc on block fixtures](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/shared/test/block-fixtures.md) that I found helpful in a similar case previously ([when I worked on the Form block backward compatibility](https://github.com/Automattic/jetpack/pull/22465)).

**Comment by yansern** [comment]
Questioning why the CSS was designed this way, specifically **the usage of absolute positioning**, which is the cause of misalignment as it is incompatible with the padding introduced by design tools, I can speculate there was an intention to be able to reposition the subscribe count in 4 different corners.
```
.wp-block-jetpack-subscriptions__subscount,
.jetpack-subscribe-count p {
	position: absolute;
	bottom: 0;
	right: 0;
	margin: 0;
	font-size: 16px;
}
````

This is likely the case with what was mentioned in the old PR 2 years ago. https://github.com/Automattic/jetpack/pull/15107#:~:text=the%20subscriber%20count-,positioning,-. (Look for "subscriber count positioning")

If I were to look at this issue from a different angle, I would say, **using flex positioning** could achieve the same 4 corner subscriber count positioning, while eliminating incompatibility with the padding on the block container.

This way, introducing an additional `<div>` container could be avoided, which avoids the need to create deprecation & fixtures.

Also IMO, it is OK for edit view & frontend view to have different HTML structure. Where I think Subscribe block could've benefited from is the separation of `view.scss` & `edit.scss`, because the first selector `.wp-block-jetpack-subscriptions__subscount` targets edit view, and the second selector `.jetpack-subscribe-count p` targets front end view.

I would try to reapproach this problem by using a simple CSS flex positioning fix. It may or may not work, but worth a try.

Since I'm on maintenance this week, I'll try this and see if it reduces all of the complexities in this PR.

**Comment by mashikag** [comment]
@yansern good job on the extent analysis of the issue. I agree with all you say. 👍 


> Since I'm on maintenance this week, I'll try this and see if it reduces all of the complexities in this PR.

Thanks

However this PR has uncovered incorrect `.html` fixture for `v6` deprecation. It should not contain `success_message` attribute. If you are not going to create a new deprecation with this PR then it is worth creating a new PR for it, so that the next person has to do so will not waste their day figuring out what is wrong like I did. 🙈

**Comment by yansern** [comment]
> However this PR has uncovered incorrect `.html` fixture for `v6` deprecation. It should not contain `success_message` attribute.

Thanks for the heads up!

**Comment by yansern** [comment]
Superceded by https://github.com/Automattic/jetpack/pull/25262

**Pull request closed without merging**
