### PR TITLE
Widget Visibility: Remove unused CSS impacting Save button

### LINKED ISSUE #1882: Widget Visibility: Styling negatively impacts Accessibility Mode
With Widget Visibility on, the Widgets Accessibility Mode's Save button is turned to grey:

31754-sample

### PR DESCRIPTION
**Pull request by kraftbj**
Testing out turning on and off this CSS, I can't figure out what it is actually supposed to be impacting. If it's that easy, we should remove it :)

I'd appreciate a designer giving me a second opinion. :)

Fixes #1882

### CODE REVIEW

**Comment by dereksmart** [comment]
cc @jeffgolenski

**Comment by jeffgolenski** [comment]
Just looked it over. It appears to be fine since that was very specific CSS you removed, I don't think it effected anything else.

**Comment by lezama** [comment]
LGTM, @samhotchkiss don't forget to regenerate the minified files before releasing.

**Comment by dereksmart** [comment]
Looks fine!

**Pull request merged**
