### PR TITLE
Docker: Add package testing shortcut

### PR DESCRIPTION
**Pull request by kraftbj**
Replaces and closes #16809

#### Changes proposed in this Pull Request:
* Adds a script to run package unit tests within the Docker env.
* Renames all packages that had `phpunit.xml` to `phpunit.xml.dist`.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
n/a

#### Testing instructions:
* `yarn docker:up`
* `yarn docker:phpunit:package autoloader` to test a specific package.
* `yarn docker:phpunit:package` to test all of them.

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Comment by kraftbj** [comment]
Running all of them takes a bit, so may want to add a "you didn't pass a package name, do you want to run them all?" check. Hmm.

**Comment by jeherve** [comment]
@kraftbj Following-up on this; since we've renamed the phpunit files, I think we'll need to update the `.gitattributes` files for each package accordingly.

**Comment by kraftbj** [comment]
Oh good catch. I'll PR that today.

**Comment by jeherve** [comment]
r212536-wpcom

**Pull request merged**
