### PR TITLE
Replace Blog Name when it is empty with domain name 

### PR DESCRIPTION
**Pull request by cpapazoglou**
Fixes https://github.com/Automattic/wp-calypso/issues/49355

#### Changes proposed in this Pull Request:

* Uses domain in Site Card when blogname is empty.

#### Testing instructions:

* Go to `/wp-admin/options-general.php`.
* Submit an empty `Site Title` .
* You should be seeing the Domain name twice.
* Please reinstate your `Site Title` and make sure it correctly appears.

Before | After
-------|------
 |

### CODE REVIEW

**Comment by mmtr** [comment]
This tests well for me on a simple site. Waiting now for the build to be available in Jetpack Beta...

**Comment by cpapazoglou** [comment]
@mmtr should we merge it to `fix/admin-menu-migrate-submenu-hooks` ? Your call!

**Review by mmtr — APPROVED** [review]

**Comment by mmtr** [comment]
> @mmtr should we merge it to `fix/admin-menu-migrate-submenu-hooks` ? Your call!

I'm not sure, to be honest! My main concern is that merging this will dismiss all the current reviews due to an unrelated change. Given that the empty site title issue is an edge case and since we can also immediately fix it for Simple sites by landing the WP.com diff, I'd say let's merge this to `trunk`.

**Review by mmtr — APPROVED** [review]

**Review by mmtr — APPROVED** [review]

**Comment by cpapazoglou** [comment]
deployed r222817-wpcom

**Pull request merged**
