### PR TITLE
Boost: Fix score auto-refresh for cloud CSS

### PR DESCRIPTION
**Pull request by eAdnan007**
Fixes 48-gh-Automattic/boost-shield-api

#### Changes proposed in this Pull Request:
* Do not auto-refresh score if cloud CSS is still generating
* Auto-refresh speed scores when cloud CSS finishes generating
* Improved detecting when to mark speed scores stale
* Clear transients on boost uninstall.

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Enable cloud CSS
* Disable and Re-enable cloud CSS
* Make sure speed score doesn't start refreshing while cloud CSS hasn't finished generating
* Wait until cloud CSS finishes generating and see if the speed score auto-refreshes
* Change the theme and come back to Boost settings page. Make sure it fetches fresh speed scores.

### CODE REVIEW

**Review by thingalon — DISMISSED** [review]
👍 changes look good

**Comment by karthikax** [comment]
Looks good to me. Cloud CSS store structure is changing in #23758. We may have to rework on either of the PR. Adding this comment for reference.

**Comment by eAdnan007** [comment]
> Looks good to me. Cloud CSS store structure is changing in #23758. We may have to rework on either of the PR. Adding this comment for reference.

Thank you. I'll keep this PR on hold until #23758 is merged.

**Review by thingalon — APPROVED** [review]
👍 Nice work! Seems to work well and the code looks clean 🚢

**Review by karthikax — APPROVED** [review]

**Pull request merged**
