### PR TITLE
Fix for missing API key field issue

### LINKED ISSUE #15384: Contact Info Widget: Error message displays but API field is missing
#### Steps to reproduce the issue

1. Go to a WordPress.com site that has plugins installed
2. Add the Contact Info & Map (Jetpack)
3. Save the widget without adding an API key

#### What I expected

I expected to see an error message and a field to enter a valid Google API key. 

#### What happened instead
The error message "Please enter a valid Google API Key." appears but there is no field to enter the API key. I was only able to replicate this issue on a WordPress.com site with plugins installed, not a self-hosted site or WordPress.com simple site.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rakmob42**
Fixes https://github.com/Automattic/jetpack/issues/15384

#### Changes proposed in this Pull Request:

**Previous logic was:**
```
if filter is not applied:
	display field
else:
	don't display field
```

**New logic is:**
```
if (filter is not applied) OR (the applied filter makes no change):
	display field
else:
	don't display field
```

[Here's how](https://github.com/Automattic/jetpack/pull/13678#issuecomment-539066276) we can check whether the applied filter made any changes.

#### Testing instructions:

1. Go to a WordPress.com site that has plugins installed (Atomic site)
2. Add the Contact Info & Map (Jetpack)
3. Save the widget without adding an API key
4. It returns an error **but this time we also see the API key field which was missing.** 

~Note: These tests are pending. I'll comment with an update as soon as I run these tests. I'm using [Jetpack Beta Plugin on Atomic site](https://jetpack.com/download-jetpack-beta/) to do so. I'm waiting for the branch to reflect in the beta plugin in order for me to test my changes.~

Tests complete on both Atomic and self-hosted site ✅

#### Proposed changelog entry for your changes:

* Fixes a minor issue with contact info widget for WordPress.com sites

#### Other:

- Thanks to @kbrown9 for her support and guidance.
- P2 reference: https://wp.me/p9F6qB-542

### CODE REVIEW

**Comment by codestor4** [comment]
The latest improved logic is based on Kim's DM (sharing it here so it gets documented) -

> I think we need to change the logic a bit. This logic doesn’t work correctly with widgets that were created prior to version 8.4, because the value of the API key from the filter function was saved, and that saved value is $instance['apikey'].

> Here’s how to replicate:
> 1. Remove the logic around the API key field so that the API key field always displays. This simulates Jetpack versions < 8.4.
> 2. Use a filter to set the API key.
> 3. Set up a contact info widget. Note the the API key field is filled with the value from the callback function. 
> 4. Save the widget. This saves the API key from the filter into the database.
> 5. Apply the new logic around the API key field.
> 6. Reload the page and open the existing widget. The API key field is displayed because the saved API key ($instance['apikey']) is the same as the API key from the filter function.  

> That is, $apikey === $instance['apikey'] evaluates to true.

> Maybe something like if ( ! has_filter( 'jetpack_google_maps_api_key' ) || false === apply_filters('jetpack_google_maps_api_key', false)  would work.

**Comment by codestor4** [comment]
Tests complete on both Atomic and self-hosted site ✅

**Comment by kbrown9** [comment]
I’m seeing `PHP Notice:  Undefined index: apikey` in the debug.log when saving a newly created widget while using the filter, This happens because `Jetpack_Contact_Info_Widget ::update()` [expects that the api key will be set](https://github.com/Automattic/jetpack/blob/master/modules/widgets/contact-info.php#L200) in `$old_instance`. Since we don’t display the API key field when the filter is used, `$old_instance` doesn’t have the `apikey` key.

I think a quick fix for this would be to add a hidden input for the api key when the filter is used. I did that in commit 8a40708.

I also included some unit tests for handling the API key in `Jetpack_Contact_Info_Widget::form()`.

**Review by kraftbj — APPROVED** [review]

**Review by jeherve — COMMENTED** [review]
I can still see the warning right now, although the map works:

image
image

Should we also take the paragraph where the error is displayed into account?

**Comment by kbrown9** [comment]
> I can still see the warning right now, although the map works:

Can you tell me more about how the widget got into this state? Which version was active when the widget was created? Was a filter with a valid key used when the widget was created? Is this an atomic site? 

I can reproduce the problem by:
1. Creating a widget, selecting 'Show Map', and saving the widget without entering a valid API key. This saves the 'Please enter a valid Google API key` message in the widget's instance data.

2. Applying this branch.

3. Adding a filter with a valid Maps API key. The API key field doesn't display because the API key is set using the filter. The map displays because a valid API key has been provided.

4. The error message displays because the error message was previously saved. If the widget is updated and saved, the error message is removed.

Is this similar to how your widget got into this state? If the widget's instance data already has the invalid API key error saved, I think the only way to clear the error is to update and save the widget.

> 
> Should we also take the paragraph where the error is displayed into account?

I think we might want to allow the error paragraph to display when the filter is used. If a user enters an invalid API key in their filter, the error message could help them troubleshoot the problem. Do you think the error message paragraph could be useful even when a filter is used to set the API key?

**Comment by jeherve** [comment]
> Can you tell me more about how the widget got into this state?

I can't seem to reproduce anymore :(

- This was a brand new JN site.
- Before to connect Jetpack to WordPress.com, I added the following snippet to the site:
```php
function wpcomsh_google_maps_api_key( $api_key ) {
	// We don't want to add the fallback API key to the Geocode API call; we'll get "referer restrictions" errors.
	// That call is only made when saving the form, to validate the address.
	if ( is_admin() ) {
		return $api_key;
	}

	// Fall back to the dotcom API key if the user has not set their own.
	return ( empty( $api_key ) ) ? 'xxx' : $api_key;
}
add_filter( 'jetpack_google_maps_api_key', 'wpcomsh_google_maps_api_key' );
```
(I used a valid API key instead of `xxx`.
- I then connected Jetpack to WordPress.com and activated the widgets module.
- I then navigated to Appearance > Customize and added the widget.
- I checked "Show map"
- At this point I shouldn't see any API key field because of the filter, but I did see it. It may be worth updating how the filter is used in wpcomsh to avoid that.
- At this point I removed the `is_admin` check in the snippet. 
- At that point things started working well. I must have done something different last time around to get to that error state.

**Comment by jeherve** [comment]
> Do you think the error message paragraph could be useful even when a filter is used to set the API key?

That's a good point. I am afraid it could be confusing since the message isn't really actionable by the admin, unless they have access to the API key. Maybe I'm overthinking this?

**Comment by kbrown9** [comment]
> > Can you tell me more about how the widget got into this state?
> 
> I can't seem to reproduce anymore :(
> 
> * This was a brand new JN site.
> ...
> * At that point things started working well. I must have done something different last time around to get to that error state.

Thanks for the info! Maybe you saved the widget without a valid API key, before removing the `is_admin` check in the snippet? That would save the error string in the widget's instance.

I think this might be an unusual situation to get into. It would require:
- The user saving the widget with 'Show Map' checked but without a valid API key, so the error message is saved.
- Then the user adding a filter for the API key, so the map can now display properly, without requiring the widget form to be updated. (I think that a user would typically add the API key in the API key field in the widget's form. That would require saving the widget, which would clear the error.)

If I'm correct about the cause of this, then saving the widget or publishing then reloading the customizer page should clear the error message.

**Comment by kbrown9** [comment]
> At this point I shouldn't see any API key field because of the filter, but I did see it. It may be worth updating how the filter is used in wpcomsh to avoid that.

I agree. We should look into updating that filter.

**Comment by kbrown9** [comment]
> > Do you think the error message paragraph could be useful even when a filter is used to set the API key?
> 
> That's a good point. I am afraid it could be confusing since the message isn't really actionable by the admin, unless they have access to the API key. Maybe I'm overthinking this?

I agree that it could be confusing, but I think it will also be confusing if the user selects 'Show Map', and they don't see the map on their site, with no indication that there's a problem. (Note that the error message will still show in the Customizer preview if the user is editing their site using that.)

**Comment by jeherve** [comment]
> We should look into updating that filter.

Could I get your review on 450-gh-wpcomsh?

Thank you!

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.4` in 1ed2be461a30608ee91e6a948fd14e6295980da8

**Pull request merged**
