### PR TITLE
4.8: updates to the changelog.

### PR DESCRIPTION
**Pull request by jeherve**

### CODE REVIEW

**Comment by jeherve** [comment]
@richardmuscat Looping you in; if Jesse is afk tomorrow, do you think you could take a look at that changelog and make changes in this branch before the release?

Thanks!

**Comment by richardmuscat** [comment]
@jeherve -- made some changes. lmk if you need anything further.

**Comment by dereksmart** [comment]
Thanks @richardmuscat !

**Comment by dereksmart** [comment]
merged to 4.8 5d264e506

**Pull request merged**
