### PR TITLE
My Plan: Free upgrade tracking

### LINKED ISSUE #12791: Add Tracking to UpgradeLink component
Following-up from #12785:

> it would be nice to take that opportunity to add tracking to clicks on UpgradeLink, so we can keep track of those things.

### PR DESCRIPTION
**Pull request by scottsweb**
Pass the correct params to the `<UpgradeLink>` component for tracking to work

https://github.com/Automattic/jetpack/blob/master/_inc/client/components/upgrade-link/index.jsx#L27-L37

Fixes #12791 

#### Testing instructions:

* Go to wp-admin/admin.php?page=jetpack#/my-plan on a free plan
* Check that no warning or errors are thrown and that events are tracked

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
Seems to work well.

**Comment by zinigor** [comment]
The conflict is caused by #12916, I'm going to fix the property name according to the changes in this PR.

**Comment by zinigor** [comment]
Please note that the feature property now has different spelling: before it was `myplan-header-free-plan-text-link`, now it's `my-plan-header-free-plan-text-link`. I'm not sure which is correct.

**Comment by scottsweb** [comment]
I like the space name so let's go with that. As far as I can see, we don't have a great deal being tracked on this yet.

**Pull request merged**
