### PR TITLE
Instant Search: Improve build process

### LINKED ISSUE #14405: Instant Search: allow output of unminified CSS in development
@jeherve suggested in https://github.com/Automattic/jetpack/pull/13138#discussion_r316195338:

> I think it would be nice to enqueue an unminified version of the CSS when `SCRIPT_DEBUG` is set to true. We usually do that in Jetpack, to help with debugging:
https://github.com/Automattic/jetpack/blob/b96f66a73398cd79dd460127fa07855ee4b85fcf/_inc/social-logos.php#L10

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #14405 
#### Changes proposed in this Pull Request:
* Removes using gulp for building Jetpack Search stylesheets.
* Generate the necessary stylesheet using Webpack. 

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
None.

#### Testing instructions:
* Run `yarn build-search`; ensure that it builds as expected without any issues.
* Apply this patch to your Jetpack site with Instant Search enabled.
* Try searching the site through the Customizer interface, toggling between Minimal and Expanded search result types. Ensure that everything works as expected.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This tests well, and cleans things nicely! 👍 This should be good to merge once the tests pass.

**Comment by jeherve** [comment]
Ah, I guess we can't merge it just yet:
https://travis-ci.com/github/Automattic/jetpack/jobs/401152499
```
ERROR in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (488 KiB). This can impact web performance.
```

**Comment by zinigor** [comment]
Two things that we can still do here is try to see why the bundle size is being increased, and by how much - maybe there's something that we're including now that shouldn't be in there, since it was working before?
Second thing that we can always do is that we can increase the bundle size :)

**Comment by jsnmoon** [comment]
> Ah, I guess we can't merge it just yet:
> [travis-ci.com/github/Automattic/jetpack/jobs/401152499](https://travis-ci.com/github/Automattic/jetpack/jobs/401152499)
> 
> ```
> ERROR in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (488 KiB). This can impact web performance.
> ```

This error is occurring because Webpack's entry point size limit is calculated via the `combined asset size`, which includes CSS, JS, and PHP payloads. I'll manually bump this limit up for now; we can address this in earnest in #17507.

**Review by jeherve — APPROVED** [review]

**Review by jeherve — CHANGES_REQUESTED** [review]
This now needs a rebase I'm afraid. :\

**Review by jeherve — DISMISSED** [review]

**Comment by jsnmoon** [comment]
Rebased again for Travis 😆

**Review by jeherve — APPROVED** [review]
Re-approving after a rebase.

**Pull request merged**
