### PR TITLE
Track boost deactivation

### PR DESCRIPTION
**Pull request by eAdnan007**
Fixes 42-gh-Automattic/boost-shield-api

#### Changes proposed in this Pull Request:
* Track Boost deactivation

#### Jetpack product discussion
pbNhbs-2k2-p2#comment-7439

#### Does this pull request change what data or activity we track or use?
Yes, the plugin now tracks when it is deactivated.

#### Testing instructions:
* Activate Jetpack Boost
* Deactivate Jetpack Boost
* Search event name `jetpack_boost_deactivate_plugin` in tracks

### CODE REVIEW

**Comment by eAdnan007** [comment]
Do we need to track `clear_cache` on deactivation? @thingalon 
https://github.com/Automattic/jetpack/blob/9cd4b2cc63c188efdd3da06be207808fba11ca83/projects/plugins/boost/app/class-jetpack-boost.php#L121

**Comment by thingalon** [comment]
> Do we need to track `clear_cache` on deactivation? @thingalon
> 
> https://github.com/Automattic/jetpack/blob/9cd4b2cc63c188efdd3da06be207808fba11ca83/projects/plugins/boost/app/class-jetpack-boost.php#L121
> 
> This line seem to be pre-monorepo. I don't think this event is relevant.

I agree; let's get rid of the `clear_cache` event. IIRC we used to have a button to let users clear all of Boost's cached values, and that made sense to track. I think it ended up there, and nobody has thought about it since. 

👍 Delete that line, and this PR is good to go

**Review by karthikax — DISMISSED** [review]
👍 LGTM

**Review by thingalon — APPROVED** [review]
🚢

**Pull request merged**
