### PR TITLE
Forms: Multiple Choice and Single Choice fields style variations

### LINKED ISSUE #30218: Contact Form: Checkboxes shrink due to too much content.
### Impacted plugin

Jetpack

### Quick summary

The multiple choice checkboxes in the jetpack contact form can shrink if the content of the checkbox is long. I saw it mainly on mobile but it would occur wherever the width is constrained.

I fixed this by just setting the checkbox to flex-shrink: 0.

### Steps to reproduce

Create a form.
Add multiple choice checkboxes.
Make at least one of them with a lot of text.
Test at different sizes.

### A clear and concise description of what you expected to happen.

The checkboxes should all stay the same size.

### What actually happened

It shrank.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jcheringer**
This PR was open as a replacement to https://github.com/Automattic/jetpack/pull/29419
#29419 got quite outdated in comparison with `trunk` and, trying to merge/rebase it was causing some trouble. 

## Proposed changes:

* Introduces the Buttons variation for the Multiple Choice and Single Choice fields

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pcsBup-TA-p2

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

**Make sure you have the Forms package enabled**

* Create a post and add a Form block
* Add a Multiple Choice and a Single Choice field
* Change the style variation to `Button` and play with the block
* Check if everything works well on the editor and on the published page

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
There is an issue if you edit a checkbox block, in the "outlined style", that changes the formating of all labels - see video:


https://user-images.githubusercontent.com/5120357/234886236-d6451d11-7f51-4efa-bf02-8be50115fd6a.mov

**Comment by jcheringer** [comment]
Thanks @digitalwaveride!
This glitch should be fixed now.
As we discussed, since these changes are in the Forms package, you'll need a site where the package is enabled.
Unfortunately, JN sites can't be used at the moment.

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Thanks a ton João!
Mentioned issue above is fixed. 👍 
We discussed the issues with certain themes in the editor... TwentyTwentyOne, Seedlet ... that are due to the theme structure (->  we raise a PR there) 

Otherwise things look good!
Just one thing, on the “animated style", I was still seeing the outlines & fields.

image



image

**Comment by jcheringer** [comment]
Hey @digitalwaveride!
I added some style changes to prevent themes like Twenty-Twenty-One and Seedlet from affecting the MC/SC inner blocks.
That will make things a bit better, but it won't be perfect.
Some of the differences we are seeing when comparing the Editor and the Frontend are happening because the Theme is defining different (or sometimes not defining) styles to the Editor and the Frontend.
This is 'out of our hands' and should be fixed on the Theme.

Regarding the outline you mentioned above, as we discussed, the Sidebar style definitions with be handled in a different PR.

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
> I added some style changes to prevent themes like Twenty-Twenty-One and Seedlet from affecting the MC/SC inner blocks.
> That will make things a bit better, but it won't be perfect.

It's so so much better João! 😻 
Thank you for fixing that!!!

There is just one little glitch that I saw, with the "+" inserter button, that is suddenly left aligned instead of right. Is this related to that PR?

image

image


> Regarding the outline you mentioned above, as we discussed, the Sidebar style definitions with be handled in a different PR.

👍  Makes sense!

**Comment by jcheringer** [comment]
It should be fixed now, @digitalwaveride.
Thanks for testing it!

**Review by digitalwaveride — APPROVED** [review]
Nice! João, thanks for fixing! 🙏 

image

**Pull request merged**
