### PR TITLE
Connection: Extract connection logic to custom hook

### PR DESCRIPTION
**Pull request by renatoagds**
This PR is a previous step for implementation of the new connect screen for auto trigger cases.

Since the new screen doesn't apply in top of any button and it's just a loading state, we need to have the connection logic outside the button and allow the trigger be made automatic or by user input.

This changes already reduce the amount of components and center the logic related with connection.

With this change we don't need more the `ConnectButton` and `ConnectUser`, since all their logic and usage was moved to `useConnection` hook, but keep them here to not break compatibility with connection consumers.

Already included new tests for `store`, `hook` and `components`, using [testing-library](https://testing-library.com/)

#### Changes proposed in this Pull Request:

* Extract connect button logic code into a custom hook (`useConnection`).
* Extract connect user logic code into a custom hook (`useConnection`).
* Add new `action` for user connection (`connectUser`).
* Add new `controls` for register site, connect user and authorization url fetch.
* Add new `resolver` for authorization url fetch.
* Introduce Testing Library for unit tests against hooks and components.
* Add new tests for `store` related (`action`, `controls` and `resolvers`).
* Inlcude `chai-dom`: https://github.com/nathanboktae/chai-dom

#### Jetpack product discussion

p6TEKc-5ks-p2

#### Does this pull request change what data or activity we track or use?

No ❗️

#### Testing instructions:

* Go to your wp admin.
* Click into Jetpack on side bar and or stay at dashboard.
* Click into `Set up Jetpack` button

#### Demo 👨🏽‍💻

https://user-images.githubusercontent.com/1663717/146260800-1c81d3ff-52ee-4f10-9254-758cd6c52d1a.mp4

https://user-images.githubusercontent.com/1663717/146260826-04cd0656-03b5-4ca6-a3e9-4eaa43d7b503.mp4

https://user-images.githubusercontent.com/1663717/146260830-5d332948-cfd1-416c-a5bc-5597305fdcdd.mp4

https://user-images.githubusercontent.com/1663717/146260833-ed3fa435-939e-475a-be95-88f2906361c1.mp4

### CODE REVIEW

**Review by leogermani — COMMENTED** [review]
Changes are looking good to me.

I think you can go ahead and change the ConnectScreen to use the ActionButton now instead.

Do you have an idea for what we can do with ConnectButton? I don't think there's anyone using it, but if we delete it, it's theoretically a breaking change. Maybe leave it with your changes (using the hook) and deprecate it?

Another question. Do you think this hook should live inside the connect-screen folder? Or should it be exported from the connection package itself? 

And last, maybe we could think of a more specific name to it? `useRegistrationHandling` or simply `useHandleRegistration` ? What do you think?

**Comment by renatoagds** [comment]
@leogermani 

> Do you have an idea for what we can do with ConnectButton? I don't think there's anyone using it, but if we delete it, it's theoretically a breaking change. Maybe leave it with your changes (using the hook) and deprecate it?

Yeah, that could be a good approach. There's someone using it outside of connection? And what about `ConnectUser`, it will be useless and don't if we could use the hook there 🤔

> Do you think this hook should live inside the connect-screen folder? Or should it be exported from the connection package itself?

That's something that I'm trying to figure out, today I put it inside the `connect-screen` folder, but I'm start to thinking that should be good to export it.

> And last, maybe we could think of a more specific name to it? useRegistrationHandling or simply useHandleRegistration ? What do you think?

Looks good. I used a generic one now, since I'm starting to know more about what exactly it does, but your suggestions are pretty good.

**Comment by leogermani** [comment]
Good job @renatoagds , this is looking pretty good.

Here are my observations:

1. I think the hook could live in the root of the connection package, and not inside any of the components

2. I think `fetchAuthorizationUrl` should be a pair of a selector and a resolver, just like we have for `connectionStatus`. Here's the context:

When you start the registration process, the request that registers the site also returns the `authorizationUrl`, which is the URL we should send the user to authorize their WPCOM account.

We then redirect the user and we don't need to make a dedicated request only to fetch this URL, because we had it on the register request. Fine.

But there are cases where we are not authorizing the user right after the registration. For example:
* Secondary users (users that authorize their accounts after the site is already registered)
* Also, the user is not obligated to authorize their accounts right away. They can skip it and use Jetpack connected only at a site level. Some features will not work while there's no user connected, but many will.

In these cases we'll need a dedicated request to fetch the authorizationUrl. So I guess the way to go is:

* Create `getAuthorizationUrl` selector - that calls the action and the control to make the API request
* On registration, after setting the `authorizationUrl`, call `finishResolution` for that resolver, so we don't need to make the API request
* Wherever need, just use the selector to get the authorizationUrl.

Makes sense?

**Comment by renatoagds** [comment]
@leogermani makes sense, already push an update in top of using `resolver` for `authorizationUrl`.

**Comment by leogermani** [comment]
Have you give it a thought about the folder in which the hook should live?

I was thinking that this hook could be used elsewhere...

Also, there is one failing test

**Comment by renatoagds** [comment]
> Have you give it a thought about the folder in which the hook should live?

Yes, it will live into root folder, just waiting to finish everything related with this component to move out.

> Also, there is one failing test

Going to fix it. Thanks

**Review by leogermani — APPROVED** [review]
Nice job!

**Comment by renatoagds** [comment]
r236866-wpcom

**Pull request merged**
