### PR TITLE
Revert "Add/shield memberships blocks for unconnected jetpack sites"

### PR DESCRIPTION
**Pull request by millerf**
Reverts Automattic/jetpack#39315

The fix was causing issue on the front-end p1726151511832309/1726141684.517209-slack-C034JEXD1RD

### CODE REVIEW

**Comment by jeherve** [comment]
Ah, I had missed testing that in the initial PR, sorry!

**Comment by millerf** [comment]
> Ah, I had missed testing that in the initial PR, sorry!
It's fine. @jeherve Any utility method to make sure the context is the editor?

**Comment by jeherve** [comment]
Nothing comes to mind. We may have to register the block, but then make the change in the blocks' editor view so we do not do the API requests unless the user is connected to WordPress.com.

**Comment by millerf** [comment]
> Nothing comes to mind. We may have to register the block, but then make the change in the blocks' editor view so we do not do the API requests unless the user is connected to WordPress.com.

I tried with `is_admin()` and it seems to work in https://github.com/Automattic/jetpack/pull/39390

**Pull request merged**
