### PR TITLE
ThreatFixerButton: Add tooltips

### PR DESCRIPTION
**Pull request by dkmyta**
## Description
Adds tooltips for the various states of the `ThreatFixerButton` component, as per designs.

Something to consider: Does this cover ever potential threat/fixer option?

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

- https://github.com/Automattic/jetpack-scan-team/issues/1524

## Does this pull request change what data or activity we track or use?

- No

## Testing instructions:

* Checkout this branch
* Load storybook with `cd projects/js-packages/storybook && npm run storybook:dev`
* View the Threats Fixer Button and the Threats Data Views component
* Review the various button states and ensure they display and react according to designs
* Review the code and ensure the implementation is correct

## Screenshots
Screen Shot on 2024-11-06 at 14-52-12

Screen Shot on 2024-11-06 at 14-40-10

Screen Shot on 2024-11-06 at 14-40-29

Screen Shot on 2024-11-06 at 14-40-49

Screen Shot on 2024-11-06 at 14-41-15

Screen Shot on 2024-11-06 at 14-41-38 (1)

Screen Shot on 2024-11-06 at 14-42-03

Screen Shot on 2024-11-06 at 14-42-25

Screen Shot on 2024-11-06 at 14-42-55

Screen Shot on 2024-11-06 at 14-43-17

Screen Shot on 2024-11-06 at 14-43-35

Screen Shot on 2024-11-06 at 14-52-43

Screen Shot on 2024-11-06 at 14-44-35

### CODE REVIEW

**Review by nateweller — CHANGES_REQUESTED** [review]
The hover-able area is rendering below the actual button:

Screenshot 2024-11-08 at 11 08 33 AM

**Comment by nateweller** [comment]
The designs appear to use the [Tooltip](https://developer.wordpress.org/block-editor/reference-guides/components/tooltip/) component from `@wordpress/components`. Could we use that component directly?

https://wordpress.github.io/gutenberg/?path=/docs/components-tooltip--docs

image

**Comment by dkmyta** [comment]
>The hover-able area is rendering below the actual button:

In my initial testing, having the `IconTooltip` wrapper overlap the button will disable the button actions.

>The designs appear to use the [Tooltip](https://developer.wordpress.org/block-editor/reference-guides/components/tooltip/) component from @wordpress/components

I was under the impression we wanted the `Tooltip` hover-able, which I do not believe is a functionality of the core option.

**Comment by dkmyta** [comment]
Closing in favour of #40111

**Pull request closed without merging**
