### PR TITLE
Forms: Style customization options for the MC/SC Buttons style

### LINKED ISSUE #30525: JP Forms - MC/SC Block - adding button customization options for "Button Style"
When the button style is selected, we need some more customization options:

- for the Color category a "Button Background".
- for the Option Styles a "Button Radius" and "Button Border Width"

See context here: https://github.com/Automattic/jetpack/pull/30437#pullrequestreview-1412785771

Image

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #30525

## Proposed changes:

* Add style customization options for the MC/SC Buttons style

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

Make sure the Forms package is enabled

* Create a post and add a Form block
* Add a Multiple Choice and/or a Single Choice field and change the style to Button
* Play with the new Sidebar style settings and check if they work as expected
* Make sure to check the published page too

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Thanks a ton João!!! 😻 

Button styling, bg color and border radius works as expected! 👍 

Just one little thing I noticed ... which feels like something we have already fixed at some point, but now sneaked in, again?
The styling of the "checks" is varying based on themes, and fits often not very well to the theme, as it seems to be a "special character". 

image


image


image




---



Any chance that we can handle that similarly to what has been done for the "Checkbox" block? Or in any way similar?

image

image

**Comment by jcheringer** [comment]
It should be fixed now, @digitalwaveride 🙂

**Comment by digitalwaveride** [comment]
Thanks João!

Testing with the themes Twenty-Twenty Three, and "Rainfall" by Automattic, I am seeing this:

image


image

🤷  ... an issue with the "reverse colors" for the select state?

**Comment by jcheringer** [comment]
Good catch, @digitalwaveride!
It should be fixed now.

**Comment by digitalwaveride** [comment]
Thanks João!!! Issue fixed. 🙏 

Apologies, for the last finetuning thing, to make things perfect:
The check characters have different font-weight in the Single Choice and MC block.
Let's make the font-weight for the MC block regular as in the SC block:

### Before:
image



### After:
image

And that would be it!  ;) Promise. 😁

**Review by CGastrell — APPROVED** [review]
Looking good! :shipit:

**Review by digitalwaveride — APPROVED** [review]
🚀 🚀 🚀

**Pull request merged**
