### PR TITLE
Incosistent use of "website" and "site"

### LINKED ISSUE #21662: Incosistent use of "website" and "site"
### Impacted plugin

Jetpack, Backup, Boost, Beta, Debug Helper, VaultPress

### Steps to Reproduce

While translating, I try to be consistent and I noticed that in Jetpack, the terms "site" and "website" are used for the same thing.

In only 25 of the 451 strings, website is used instead of site. 

To remain consistent in the plugin, I would change all the uses of "website" into "site" so the wording and term use is the same everywhere.

Sometimes, even in the same string, both terms are used. As in this example: 
image

### A clear and concise description of what you expected to happen.

N/A

### What actually happened

N/A

### Other information

N/A

### Operating System

Windows

### OS Version

Win10 21H1

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by NekoJonez**
Fixes #21662

#### Changes proposed in this Pull Request:
Every mention of website in strings to site.

Consistency is important. Let's use the same terminology through-out the whole app.

#### Testing instructions:

* None really needed, since it only changes one word in strings. 

#### Does this pull request change what data or activity we track or use?

No.

### CODE REVIEW

**Comment by coder-karen** [comment]
Thanks for looking at this @NekoJonez !

We will definitely take a closer look at this as soon as possible. In the meantime, could you please [create a changelog entry](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md) as well for these changes? 

Let us know if you need some help with that!

**Comment by NekoJonez** [comment]
> Thanks for looking at this @NekoJonez !
> 
> We will definitely take a closer look at this as soon as possible. In the meantime, could you please [create a changelog entry](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md) as well for these changes?
> 
> Let us know if you need some help with that!

Did I do that right?

**Comment by coder-karen** [comment]
> Did I do that right?

Almost! The 'Fixes:' line needs to be removed from both changelogs, and in the `my-jetpack` changelog the 'type' can’t be 'bugfix' ('fixed' would work there).

I can also jump in and do that - just let me know if so :)

**Comment by NekoJonez** [comment]
> > Did I do that right?
> 
> Almost! The 'Fixes:' line needs to be removed from both changelogs, and in the `my-jetpack` changelog the 'type' can’t be 'bugfix' ('fixed' would work there).
> 
> I can also jump in and do that - just let me know if so :)

Sorry to do it in two times... :o But, should be corrected now.

**Review by coder-karen — DISMISSED** [review]

**Comment by coder-karen** [comment]
Did a quick fix there as the 'fixed' type doesn't work for 'jetpack' to add to the confusion!

This should be good for review now, I'll add the 'needs review' label and we'll take a look at the changes as soon as we can.

**Comment by NekoJonez** [comment]
@coder-karen Is there something for me to do now?

**Comment by coder-karen** [comment]
Not just now @NekoJonez , though I apologize for the delay here. As soon as we're able to review this we'll follow up.

**Pull request closed without merging**
