### PR TITLE
Protect: Add `popover` at navigation badge

### PR DESCRIPTION
**Pull request by renatoagds**
Include popover for checked and no checked items at Navigation.

#### Changes proposed in this Pull Request:

* Add popover in `Badge`.
* Add icon for `notChecked`.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Start `Protect`
* Navigate to `admin` page.
* Make sure response_type is either incomplete or incomplete_green
* Check popover when hovering badge.
* Check different icons and text for not checked items

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
Looks great

**Comment by anomiex** [comment]
> Great news! One last step: head over to your WordPress.com diff, D79817-code, and deploy it. Once you've done so, come back to this PR and add a comment with your changeset ID.

Took care of that for you since the lack of it was blocking other stuff. r244740-wpcom

**Comment by retrofox** [comment]
how does it affect? `wpcom — Tests failed: D79872-code`, for instance?

**Comment by anomiex** [comment]
Looks like that was some unrelated transient failure. I see you re-ran the build there and it passed this time.

**Pull request merged**
