### PR TITLE
Renovate: Only one PR

### PR DESCRIPTION
**Pull request by kraftbj**
We have a ton of Renovate PRs. What if we just update deps every... week... in one go instead of dealing with as many PRs as it can throw at us?

See https://renovatebot.com/docs/faq/#use-a-single-branchpr-for-all-dependency-upgrades

#### Changes proposed in this Pull Request:
* n/a

#### Testing instructions:
* n/a

#### Proposed changelog entry for your changes:
* n/a

### CODE REVIEW

**Comment by jeherve** [comment]
We could give that a try. @brbrr What is your take on this?

**Comment by kraftbj** [comment]
We will need to figure out why some of the existing renovate PRs break and update them, so if we don't have bandwidth to do that right now, that would block this.

**Comment by brbrr** [comment]
yeah, I think we'll be blocked by deps that we can not easily update. such as `page` and `react-router`. Although we can just lock their versions.

**Comment by simison** [comment]
Also if you close those PRs, Renovate won't notify you about them again but you'll have bandwidth to new PRs.

**Pull request closed without merging**
