### PR TITLE
Sharing: add a filter to change the output of the Facebook button.

### LINKED ISSUE #1570: Sharing: Allow replacing FB "Like" button with "Recommend" button
FB's like button allows you to change the text to "Recommend":

https://developers.facebook.com/docs/plugins/like-button

screen shot 2015-01-30 at 11 19 19 am

Maybe we could add a filter that supports this?

However, if we end up switching to the Share button instead (#1441), this ticket becomes moot.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #1570 
Once this filter makes it in Jetpack, site owners could use something like this to define a custom sharing button (the Like button in this example):

```php
function jeherve_custom_fb_button( $fb_share_html, $share_url ) {
        $custom_fb_button = '<div class="fb-like" data-href="' . $share_url . '" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>';
        return $custom_fb_button;
}
add_filter( 'jetpack_sharing_facebook_official_button_output', 'jeherve_custom_fb_button', 2 );
```

cc @aduth Since the Like button includes a few other arguments that could be customized, I chose to filter the whole button output. What do you think?

### CODE REVIEW

**Comment by aduth** [comment]
I appreciate you putting a solution together. The filter name may be misleading since you've applied it only to cases where the "Official" button style is used, so custom styles couldn't be modified with this filter. There are indeed quite a few options which a user could customize here, detailed at Facebook's Developer site:

https://developers.facebook.com/docs/plugins/share-button
https://developers.facebook.com/docs/plugins/like-button

Overriding the HTML as you've done here may indeed be the simplest route (and future-proofs in case of new or modified button options).

**Comment by jeherve** [comment]
> The filter name may be misleading since you've applied it only to cases where the "Official" button style is used, so custom styles couldn't be modified with this filter. 

Good point. What filter name would you suggest? `jetpack_sharing_facebook_official_button_output`?

**Comment by aduth** [comment]
@jeherve: Sure, that or keep the filter name, but apply it to all return values of the function. I don't have a strong preference in either case. There are already quite a few filters available for customizing the output of `Sharing_Source::get_link` so it may not be necessary for custom styles.

**Comment by kraftbj** [comment]
Marking as Review Completed so ready for @dereksmart's final look over since it has been reviewed by @aduth.

**Comment by dereksmart** [comment]
:+1:

**Pull request merged**
