### PR TITLE
add promoted posts block after publishing content

### PR DESCRIPTION
**Pull request by therocket-gr**
#### Changes proposed in this Pull Request:

**This is a work in progress**

This adds a new Post-publish panel in the block editor.

**More details to come soon**

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

- pedfti-DJ-p2#comment-849
- p1HpG7-jCm-p2
- Related PR: #27906

#### Does this pull request change what data or activity we track or use?

* TBD, this will depend on the implementation

#### Testing instructions:

* Start on a Jetpack site that's connected to WordPress.com.
* Switch to this branch, or use the Jetpack Beta plugin to run this branch.
* Ensure Beta blocks are enabled on your site. If you test on a WoA site, for example, add the following: `add_filter( 'jetpack_blocks_variation', function() { return 'beta'; } );`. If you work locally, you can add 
`define( 'JETPACK_BETA_BLOCKS', true );` in your `docker/wordpress/wp-config.php`.
* Go to Posts > Add New
* In your console, check that the new extension is now available: `'post-publish-promote-post-panel' in Jetpack_Editor_Initial_State.available_blocks`
* Publish a post.
* Check the post-publish sidebar panel and click on the button.

### CODE REVIEW

**Comment by paulopmt1** [comment]
Tested, and it's working great on Atomic sites @therocket-gr!

As we discussed, our current goal is to make it work without redirecting Atomic users outside their domain. The strategy is to take advantage of the advertising widget, which was made to allow such integrations.

image

After being redirected, the user will be redirected to the advertising flow:

image

**Comment by kraftbj** [comment]
One thing we'd want to consider is this would be in only Jetpack, but it would be good to have it part of the new package that @dereksmart made so it could land in Jetpack or the Social plugin.

**Review by jeherve — COMMENTED** [review]
Looking at this PR, a few things come to mind:

- If we want to ship and iterate, it may make sense to ship a first version of the panel that just redirects to WordPress.com, without the modal. It can be implemented faster, and we can always add the modal later on.
- That post-publish panel is getting crowded, with the QR code, the podcast prompt, and in some cases the Payment prompt. Should we be worried about adding one more item?
- As @kraftbj mentions, it would be nice to move this to the new package introduced in #27906. This may be for another iteration though, since it will require extracting some Jetpack methods to the `shared-extension-utils` package first. Of course, this also depends on where the post-publish panel would be needed.
- I see a mention of the `can_promote_widget` flag, but could not find anything about it elsewhere. Is this something that is still in progress on the WordPress.com side? Is this a setting that will be different per user, or per site?

**Comment by jeherve** [comment]
I've just pushed #27928 for a replay of this. 👍
More details about the changes in the PR, and in 1386-gh-dotcom-forge

**Pull request closed without merging**
