### PR TITLE
Avoid determine_current_user filter to enter an infinite loop

### PR DESCRIPTION
**Pull request by leogermani**
Fixes a very specific situation where the `determine_current_user` filter added by the connection package can produce an infinite loop. See p9o2xV-1kz-p2#comment-4415

#### Changes proposed in this Pull Request:

* Avoid determine_current_user filter to enter an infinite loop

#### Jetpack product discussion

p9o2xV-1kz-p2#comment-4415

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Set up an ephemeral site with wpcomsh/Jetpack and jetpack-beta
* Connect Jetpack
* Break the Jetpack user token (see p9o2xV-1kz-p2#comment-4415 or use the [Debug helper plugin](https://github.com/Automattic/jetpack/tree/master/projects/plugins/debug-helper))
* Use the developer console to request WP REST API | wpcom/v2 | GET | /sites/$your-site-id/admin-menu.
* `tail -f /tmp/php-errors` on the ephemeral site should output an OOM error. The rest API response code should be 500
* Using jetpack beta, switch to this branch
* Make the request again and check that there's no OOM error and the REST response code is 400

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Should we worry about the possibility that something inside the filter throws so the `$doing_determine_current_user_filter` never gets set back to false?

We could take care of that, and simplify things here a bit, by doing something like this instead:
```php
if ( $this->doing_determine_current_user_filter ) {
    // Recursion! Log?
    return $user;
}
$this->doing_determine_current_user_filter = true;
try {
    // ... All the existing code, unchanged except for indentation ...
} finally {
    $this->doing_determine_current_user_filter = false;
}
```

**Comment by leogermani** [comment]
> Should we worry about the possibility that something inside the filter throws so the `$doing_determine_current_user_filter` never gets set back to false?
> 
> We could take care of that, and simplify things here a bit, by doing something like this instead:
> 
> ```
> if ( $this->doing_determine_current_user_filter ) {
>     // Recursion! Log?
>     return $user;
> }
> $this->doing_determine_current_user_filter = true;
> try {
>     // ... All the existing code, unchanged except for indentation ...
> } finally {
>     $this->doing_determine_current_user_filter = false;
> }
> ```

I don't think we will have a case of anything throwing there, but I like how fail proof and simple this looks. Will do it.

**Comment by leogermani** [comment]
Well, the change is simpler but the diff looks worse...

**Comment by anomiex** [comment]
Diff looks cleaner if you check "Hide whitespace changes" in the gear menu. Or just go to https://github.com/Automattic/jetpack/pull/19439/files?w=1

**Review by anomiex — APPROVED** [review]

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.6` in 9ca65b681026ee165dbe5fb7ed53fed3112a88aa

**Comment by jeherve** [comment]
Package releases will happen in #19469.

**Pull request merged**
