### PR TITLE
My Jetpack | Components: Update `AdminPage` to support `showBackground`

### PR DESCRIPTION
**Pull request by renatoagds**
Related with #22649 

It will support us to drop the `Layout` component applied on `admin.jsx` in My Jetpack.

#### Changes proposed in this Pull Request:

* Update `AdminPage` to support `showBackground` prop.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Open Storybook.
* Goes to `AdminPage` story.
* Interact with the new prop on `control` panel.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
@renatoagds Looks like this still needs committing to WordPress.com. Could you look into it?

Thanks!

**Comment by renatoagds** [comment]
@jeherve can you help me with? I do not have commit access

**Comment by retrofox** [comment]
let me try it

**Comment by retrofox** [comment]
> Hello renatoagds! These changes need to be synced to WordPress.com - If you 're an a11n, please commandeer and confirm D75432-code works as expected before merging this PR. Once this PR is merged, please commit the changes to WP.com. Thank you!

r243348-wpcom

**Pull request merged**
