### PR TITLE
Build: Remove validate-es5 from all packages

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
* Removes `validate-es5` commands and invocations from all packages in the repository. This is no longer necessary following our IE11 deprecation. 

#### Jetpack product discussion
IE11 has been deprecated in Jetpack; see p1HpG7-c8n-p2.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Ensure that the affected scripts still run as expected.

### CODE REVIEW

**Comment by jsnmoon** [comment]
I stumbled on this while working on #20369, which uses `@wordpress/babel-preset-default` that produces ES6+ code in the output bundle.

**Comment by anomiex** [comment]
Is there some validation we should keep to ensure that we're not adding stuff that older supported browsers don't support?

Also, if we're ready to drop the es5 requirement, we should probably also delete or modify `./projects/packages/lazy-images/src/.eslintrc.js`, `./projects/packages/tracking/.eslintrc.js`, and `./projects/plugins/jetpack/modules/.eslintrc.js` to reflect whatever standard we're writing to now. But maybe in separate PRs, since that will probably result in new lint errors in a bunch of JS files calling for the replacement of obsolete es5 syntax. The main question is whether someone who knows the details of the JS stuff is willing to actually write those PRs.

**Comment by jsnmoon** [comment]
> Is there some validation we should keep to ensure that we're not adding stuff that older supported browsers don't support? (@anomiex)

I was under the impression that we were mirroring [WordPress's browser support](https://make.wordpress.org/core/handbook/best-practices/browser-support/), which currently looks like the following:

	'> 1%',
	'last 1 Android versions',
	'last 1 ChromeAndroid versions',
	'last 2 Chrome versions',
	'last 2 Firefox versions',
	'last 2 Safari versions',
	'last 2 iOS versions',
	'last 2 Edge versions',
	'last 2 Opera versions',

Which translate into the following browser versions:
	  
	  and_chr 91
	  and_uc 12.12
	  android 91
	  chrome 92
	  chrome 91
	  chrome 90
	  edge 91
	  edge 90
	  firefox 90
	  firefox 89
	  ios_saf 14.5-14.7
	  ios_saf 14.0-14.4
	  op_mini all
	  opera 77
	  opera 76
	  safari 14.1
	  safari 14
	  samsung 14.0

Given that all these browsers (except Opera Mini 😔) support [ES6](https://caniuse.com/es6), I don't think any ES5 validation is necessary. Since we're using [preset-env](https://babeljs.io/docs/en/babel-preset-env), even Opera Mini should be decently supported in our output bundles.

One caveat: Babel is not universally used in all of our packages. I'd be happy to reduce the scope of this PR to packages using Babel if we're concerned about Opera Mini support in other packages.

(If we want to ensure backward compatibility with other, older browsers, we'll want to roll our own customized browserslist.)

**Comment by anomiex** [comment]
Looks like you know a lot better than I do which browsers we support! 😀

I think the cases where we have the "validate-es5" are mostly there to catch situations where something slips through Babel. For example, if a dependency switches from ES5 to ES6 so we have to start transpiling it. There might be value in keeping such a check, just updating it to check for ES6 so we're ready when ES7 (or whatever) comes out. Or if we could actually list out the versions in a config file somewhere instead of saying "ES6", that'd be cool too.

I'd guess that the cases where we're not using Babel are where we have a `.eslintrc` that is selecting ES5 for the sources. Although we may also be double-checking them with a validate-es5 check after the build, in case something slipped through.

**Comment by anomiex** [comment]
P.S. The bot is removing the "Needs Review" label and adding "Needs Author Reply" because of this bit in its comment:

> :red_circle: Action required: Please add missing changelog entries for the following projects: projects/packages/jitm, projects/packages/lazy-images, projects/plugins/jetpack
>
> Use [the Jetpack CLI tool](https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md#first-time) to generate changelog entries by running the following command: `jetpack changelog add`.
Guidelines: [/docs/writing-a-good-changelog-entry.md](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md)

**Comment by jsnmoon** [comment]
> P.S. The bot is removing the "Needs Review" label and adding "Needs Author Reply" because of this bit in its comment:
> 
> > 🔴 Action required: Please add missing changelog entries for the following projects: projects/packages/jitm, projects/packages/lazy-images, projects/plugins/jetpack
> > Use [the Jetpack CLI tool](https://github.com/Automattic/jetpack/blob/master/docs/monorepo.md?rgh-link-date=2021-07-22T13%3A39%3A22Z#first-time) to generate changelog entries by running the following command: `jetpack changelog add`.
> > Guidelines: [/docs/writing-a-good-changelog-entry.md](https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md?rgh-link-date=2021-07-22T13%3A39%3A22Z)

One day, I'll remember to add the changelog on my first try 🙂

**Comment by jsnmoon** [comment]
> I think the cases where we have the "validate-es5" are mostly there to catch situations where something slips through Babel. For example, if a dependency switches from ES5 to ES6 so we have to start transpiling it. There might be value in keeping such a check, just updating it to check for ES6 so we're ready when ES7 (or whatever) comes out. 

Gotcha, that's a good point regarding dependencies; Search actually [ran into this exact problem](https://github.com/Automattic/jetpack/blame/master/projects/plugins/jetpack/tools/webpack.config.search.js#L57) in the past. I typically err on the side of reducing code/tooling when possible, thus my desire to just chuck the `validate-es5` scripts out the window.

I wonder if it makes sense to just transpile every dependency in `node_modules`? I don't think it's been thoroughly studied, but I believe Babel results are indempotent.

> Or if we could actually list out the versions in a config file somewhere instead of saying "ES6", that'd be cool too.

I'm concerned that we may end up recreating `preset-env` functionality in our codebase if we were to pursue this.

----

At any rate, I think there's a worthwhile conversation to be had here than what's appropriate for a pull request. For now, so I'll close out this PR and get a P2 post going.

**Pull request closed without merging**
