### PR TITLE
Turn off css tidy shorthand optimisation

### PR DESCRIPTION
**Pull request by glendaviesnz**
Fixes # https://github.com/Automattic/wp-calypso/issues/52310 & https://github.com/Automattic/jetpack/issues/19224

#### Changes proposed in this Pull Request:

* Turns off the css shorthand optimisation option. More blocks are now making use of inlines styles to add extra padding and margin options, and if the jetpack css optimiser reduces these to a single selector then the block invalidates. It may be possible to get a change into gutenburg that makes the blocks aware of this optimisation but that may take a while to get tested and approved so this change will likely be needed in the interim anyway.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

- On WPcom site post add a group block within another group block
- Set the padding of the child group in the left block settings panel
- Save the post and reload the editor and notice the child block is invalid
- Apply this patch and follow steps above to add a new group block, and this time when reloading child block should be valid
- On a WPcom site also add some longhand selectors via Customizer additional css and check that these are still converted to shorthand in the frontend
- Also test an Atomic site - seems like they are not affected by this css tidy code as couldn't replicate the validation issue, but worth somebody double checking

Before:
Screen Shot 2021-05-04 at 3 34 44 PM

After:

Screen Shot 2021-05-04 at 3 38 05 PM

### CODE REVIEW

**Review by andrewserong — DISMISSED** [review]
This works nicely for me @glendaviesnz! I think disabling this setting globally makes good sense given the direction of Gutenberg inlining styles, and from my perspective the benefit of the feature doesn't outweigh the risk of breaking blocks. But let's see what other folks think, too!

Quick screenshots that it's working nicely:

| Before | After |
| --- | --- |
| image | image |

**Review by ramonjd — DISMISSED** [review]
@andrewserong is too fast! 

But I was testing too, so for the heck of it:

**Before**
Screen Shot 2021-05-04 at 1 59 52 pm

**After**
Screen Shot 2021-05-04 at 2 00 34 pm

Also agree that avoiding invalid block errors overrides any benefit of CSS optimisation from a UX perspective.

**Review by sdixon194 — DISMISSED** [review]
Works as advertised!

**Comment by jeherve** [comment]
I'll mark this as on hold pending the discussions in p7H4VZ-30a-p2

**Comment by glendaviesnz** [comment]
@jeherve I have narrowed this down so it just targets calls from gutenberg. I think we should look at merging this fix for the immediate block validation issue, and look at the removal of css tidy altogethers as a small project in its own right as I am picking it will require a detailed look at the css sanitization implications of doing this.

**Review by jeherve — APPROVED** [review]
> I think we should look at merging this fix for the immediate block validation issue, and look at the removal of css tidy altogethers as a small project in its own right as I am picking it will require a detailed look at the css sanitization implications of doing this.

That seems like a good idea. 👍

This looks good to me. Like @ramonjd, I was wondering a bit about that nonce as the best way to detect a request from the block editor, but it does seem to work.

**Comment by glendaviesnz** [comment]
rWP225562

**Pull request merged**
