### PR TITLE
Move enhanced open graph from modules/publicize to modules/

### PR DESCRIPTION
**Pull request by spsiddarthan**
#### Changes proposed in this Pull Request:
Remove the enhanced-open-graph.php file out of the Publicize module and move it into the modules directory of the Jetpack plugin. 

This PR came [out as a result of another PR ](https://github.com/Automattic/jetpack/pull/23786#discussion_r842889187)I am working on where we make Jetpack use the Publicize package, from the packages folder. It was decided that the enhanced-open-graph.php file shouldn't live in the Publicize module and be a file of its own. 

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
 
 - Create a post and add a gallery of photos to it using the /gallery block. 
 - Publish the post, go the post detail view and view the source code of the page. You will see the open graph tags added like this. 

  
Screenshot 2022-04-12 at 3 45 57 PM

    
 - Deactivate the 'publicize' and 'sharing' modules, from wp-admin. You can click on the modules at the bottom of the screen to manage your modules. 
 
 
Screenshot 2022-04-12 at 3 47 07 PM

 
- Go back to your post detail view, and view the page source again. The open graph tags won't be added.

### CODE REVIEW

**Comment by spsiddarthan** [comment]
We need to merge this WPCOM patch as soon as we make the Jetpack release when this PR gets merged. D78597-code

**Review by pablinos — DISMISSED** [review]
This looks good to me. I was concerned that we might not be including the file where we would have been previously, but I think it was only being included when the Publicize module was active.

There's the possibility that this fixes the situation where Sharing Buttons is active, and Publicize isn't, as we'll now include this where we weren't previously.

**Comment by spsiddarthan** [comment]
> This looks good to me. I was concerned that we might not be including the file where we would have been previously, but I think it was only being included when the Publicize module was active.

Thanks, Paul! Yes, it was being included only when Publicize was active!

**Review by danielpost — APPROVED** [review]

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r243762-wpcom

**Pull request merged**
