### PR TITLE
Admin: use minimzed CSS for stats widget

### LINKED ISSUE #22670: Admin Performance: Minify dashboard-widget.css
There is a script; jetpack/css/dashboard-widget.css which loads unminified. It’s a minor detail – but it includes the full MIT license text, an empty Rule, and sourcemap information. It says it’s compiled form SASS, so it’s probably just a matter of updating the SASS settings to minify on compile.

Internal reference: p1HpG7-evU-p2

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #22670

#### Changes proposed in this Pull Request:

* Use minimzed version for dashboard-widget.css. It was probably automatically created started with #23840 but we hadn't updated the enqueue to use it.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Connect Jetpack, inspect wp-admin to see if dashboard-widget.css (dev site) or dashboard-widget.min.css (production) is loaded.

### CODE REVIEW

**Comment by kraftbj** [comment]
This does use the min version... but the min version isn't _really_ minimized. Just dropped the comments. Not ideal, but progress.

**Comment by zinigor** [comment]
@bindlegirl  can you please look at this one and see if we can have truly minified CSS here? Also you might have other ideas to improve the thing.

**Comment by bindlegirl** [comment]
@kraftbj I'm not sure what I'm looking at, but the dashboard-widget.min.css appears to be minimized when it reaches the production repo: https://github.com/Automattic/jetpack-production/blob/trunk/css/dashboard-widget.min.css

If I got things right, you added the code requesting the correct file, so everything should be OK when the build runs?

**Comment by kraftbj** [comment]
@bindlegirl I think you're right and it was a PEBCAK with my misreading the devtools and misunderstanding when the devtools displays the actual source and when it renders something.

So.... can you review and approve this one? :)

**Review by bindlegirl — APPROVED** [review]
LGTM

**Pull request merged**
