### PR TITLE
VideoPress Block: New Icon for Edit Button

### PR DESCRIPTION
**Pull request by roundhill**
This PR updates the icon for the edit button in the toolbar for the VideoPress block.

**Before**
Screen Shot 2021-09-01 at 9 30 29 AM

**After**
Screen Shot 2021-09-01 at 9 34 34 AM

I made the icon a bit smaller so that it fits in with the other icons on the toolbar that are still "dashicons".

#### Changes proposed in this Pull Request:
* Updates edit icon to the svg available at: https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library

#### Jetpack product discussion
pxWta-Zz-p2

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Add or edit a VideoPress block, you should see the new icon and clicking it should take the block back to the upload/select video view.
* Hopefully the icon looks nice 😉

### CODE REVIEW

**Review by jgcaruso — APPROVED** [review]
Icon is updated to the new design, and button still works as expected.

**Comment by pablohoneyhoney** [comment]
> I made the icon a bit smaller so that it fits in with the other icons on the toolbar that are still "dashicons". 

This is definitely not best. We designed this new edit icon to work accordingly with the other icons of the toolbar which aren't or shouldn't be Dashicons (which are and will be deprecated). All of these icons are new and should be leveraged as available [in the icon library](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library), they all have a 24px footprint and work as intended [in this design library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8%3A13). 

Screen Shot 2021-09-01 at 2 38 34 PM

Pinging @jasmussen in case I'm missing something.

**Comment by jasmussen** [comment]
Yep, definitely keep the 24x24 as they were intended to be displayed, especially since Dashicons has long since been retired. I do appreciate the effort to replace the remaining instances of Dashicon usage!

**Comment by mtias** [comment]
Yes, there are no dashicons in that toolbar. You can reference `wordpress/icons` directly for the pencil.

**Comment by roundhill** [comment]
Thanks all, updated! Looks like this now:

Screen Shot 2021-09-01 at 1 06 48 PM

**Review by jgcaruso — APPROVED** [review]
Diff is much cleaner and icon size matches that of other blocks now.

**Comment by jasmussen** [comment]
In responding to the ping above by Pablo last night, I should've perhaps shared some wider context for the new iconography. Dashicons were put into maintenance mode with [WordPress 5.5](https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/). In its place is a new icon set that has been designed to be lighter with thinner strokes, bigger to be more legible, and to match the design language that's evolving from the block editor and outwards. The set already includes a great deal of icons, but if there's any icon you need currently missing from the set, I'd be super happy to help make it happen.

**Review by jeherve — APPROVED** [review]

**Comment by roundhill** [comment]
Deployed to wp.com via r231166-wpcom

**Pull request merged**
