### PR TITLE
Slideshow Block: Add a bit of CSS to support align wide and align full

### LINKED ISSUE #12178: Slideshow block: Full width and wide width display shows scaled down images
_Jump to most recent technical analysis from June 2022: https://github.com/Automattic/jetpack/issues/12178#issuecomment-1157025213_

#### Steps to reproduce
1. Activate a twenty nineteen child theme
2. Create a page/post
3. Add new Slideshow Block and add one or more large images
4. Set display mode to full width
5. Publish and view page

#### What I expected

I expected the images to extend to the edge of the browser window.

#### What happened instead

The images are displayed as a scaled down version surrounded by grey space.  

Note: This happens with wide width display as well.

#### Screenshot / Video

Annotation on 2019-3-4

Screen Shot 2019-04-25 at 6 25 08 AM

Screen Shot 2019-04-25 at 6 19 46 AM

Screen Shot 2019-04-25 at 6 20 49 AM

#### Other

#1984153-zen

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #12178

## Proposed changes

Adds a bit of Slideshow Block CSS to support align wide and align full controls:

image

I personally tested in Firefox 102, Chrome 103, and Safari 15.5 with the following themes:
* Twenty Nineteen
* Twenty Sixteen
* Twenty Twenty
* Twenty Twenty-One
* Twenty Twenty-Two
* Blockbase
* Hemingway Rewritten

### Align Full Before/After

**Before**:

image

**After**:

image

### Align Wide Before/After

**Before**:

image

**After**:

image

## Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Some prior discussion about testing in p1657651639634659-slack-CBG1CP4EN

1. Check out the branch in your preferred testing environment. 
2. Create a new post with a Slideshow Block, Cover Block, and Gallery Block, all set to "Align None". Open in a new window.
3. Copy all of the blocks into a second post, set each block to "Align Wide", and open in a new window.
4. Copy all of the blocks into a third post, set each block to "Align Full", and open in a new window.
5. View each of your three posts and verify the Slideshow Block follows the same behavior as the Cover Block and Gallery Block.
6. Switch between a few themes and verify each block displays consistent behavior in each theme.

### CODE REVIEW

**Review by vykes-mac — APPROVED** [review]
Works as described. I noticed however that it doesn't matter what alignment u select the highlighter is always set to `none`.

image


that might be a separate issue though.

**Comment by danielbachhuber** [comment]
> I noticed however that it doesn't matter what alignment u select the highlighter is always set to `none`.

@vykes-mac That's odd! I didn't have that experience. Did it reproduce across multiple themes?

**Comment by samiff** [comment]
> I noticed however that it doesn't matter what alignment u select the highlighter is always set to none.

I was also seeing this with 2022 and other themes, but it happens on Jetpack stable branch as well.

My only concern with this change would be that it may visually affect any existing slideshow blocks. For example here is a slideshow block set to wide, with a tall image pre-patch:

pre-patch

And post-patch:

post-patch

There isn't an option to constrain aspect ratios, so I guess the only option for users at that point would be to set the block width to none? @danielbachhuber what are your thoughts on this PR affecting the presentation of existing slideshow blocks?

**Comment by danielbachhuber** [comment]
> My only concern with this change would be that it may visually affect any existing slideshow blocks. For example here is a slideshow block set to wide, with a tall image pre-patch:

@samiff Personally, I'd consider the current tall image behavior on `trunk` as a bug, which this pull request would fix. However, I fully acknowledge the change in behavior could be considered a regression.

I'd be hesitant to introduce an option for this. We could potentially have some logic to only apply `object-fit: cover;` to horizontal images, keeping vertical images constrained.

Have you seen many examples of tall images with align wide in the wild?

**Comment by samiff** [comment]
> I'd be hesitant to introduce an option for this. We could potentially have some logic to only apply `object-fit: cover;` to horizontal images, keeping vertical images constrained.

I say we give this a try as-is, and hold off on any additional options/logic for now.

@coder-karen probably a good idea to mention this PR in notes for Happiness 👍

**Review by samiff — APPROVED** [review]

**Comment by danielbachhuber** [comment]
r249268-wpcom

**Comment by tvolpert** [comment]
I'm not sure if this is the right place to report this, but it didn't seem right to open a bug report for something that was already documented here -- if anyone knows a more appropriate place to add this comment, please let me know!

I have a user in 5686694-zen who doesn't want, and wasn't expecting, the `object-fit: cover` behavior on their full-width Slideshows - essentially the same issue as @samiff mentioned above.

For now, I provided them CSS below for a workaround, but it would be nice if the user could toggle this functionality somehow, or at least change the focal point like on the Cover block. As it stands now, it seems like there's basically no point in using portrait-orientation images with this block. 

```
/* remove zoom-and-crop effect from images in Slideshow blocks | 5686694-zen tcrv */
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_image, .wp-block-jetpack-slideshow.alignwide .wp-block-jetpack-slideshow_image {
    object-fit: contain;
}
/* End | 5686694-zen tcrv */
```

**Pull request merged**
