### PR TITLE
AI Extension: add a way to cancel the AI request

### LINKED ISSUE #31590: AI Extension: Implement a way to cancel the current suggesting process.
At the moment, it's not feasible to cancel the request process within the AI Extension. Let's brainstorm solutions to address this issue.

### PR DESCRIPTION
**Pull request by retrofox**
This PR introduces a functionality to cancel a request in the AI Extension dropdown. Here's an overview:

* We've integrated a cancelRequest() helper function into the suggestion hook to handle request cancellation.
* We've optimized the onClick event of the toolbar button to enable the cancellation process.
* We've utilized the isActive state to represent the ongoing request status.

Fixes issue #31590

This PR implements a way to cancel the request when the user uses the AI Extension dropdown. In summary:

* It adds a `cancelRequest()` helper to the suggestion hook
* propagates the helper between the components 
* Improve the onClick event of the toolbar button to be able to cancel the request
* It uses the `isActive` state to denote the requesting process.

Fixes https://github.com/Automattic/jetpack/issues/31590

## Proposed changes:

* AI Extension: add a way to cancel the AI request

### Other information:

- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Navigate to the block editor.
2. Create a Paragraph and add some content.
3. Use the AI dropdown to request content.
4. Verify that you can cancel the ongoing request by re-clicking the toolbar button.

https://github.com/Automattic/jetpack/assets/77539/cd150142-afcd-434d-bd3d-22784b9b7df3

### CODE REVIEW

**Comment by keoshi** [comment]
As mentioned in Slack, I think this is an acceptable solution for the moment. It is hidden, but totally ok to leave it as a pro user feature that people will have to explore and find for themselves. The animation draws the eye in and gives it a nice affordance, so I'm happy about that.

For a future iteration, I'd like to hear from our experts @jasmussen @jay on whether there's an existing visual mechanism (or component, or pattern) we could make use of here to send tips (i.e.: temporary notices) to our users letting them know of power features such as this one.

_For additional context_: what we're trying to communicate here is that users can click the AI button a second time to cancel the prompt.

**Comment by jasmussen** [comment]
> It is hidden, but totally ok to leave it as a pro user feature that people will have to explore and find for themselves. The animation draws the eye in and gives it a nice affordance, so I'm happy about that.

I'd echo this, if I ever found a need to stop the process I'd probably intuit clicking that toggle too.

> For a future iteration, I'd like to hear from our experts @jasmussen @jay on whether there's an existing visual mechanism (or component, or pattern) we could make use of here to send tips (i.e.: temporary notices) to our users letting them know of power features such as this one.

For the moment, there is not. We used to have pointers, but they didn't work very well. The closest we have now are the snackbar and the notice which exists in a gray minimal version; this notice you see in the split inspector informing you where your settings went. So as far as existing notices, you might best fire a snackbar initially or in context of a particular action. So long as you fire it contextually and not all the time, it can probably be a easy good solution.

There are some cursory explorations around showing a dot indicator, for example in context of [broken](https://github.com/WordPress/gutenberg/issues/51980#issuecomment-1610827401) or incomplete blocks, or around [responsive editing](https://github.com/WordPress/gutenberg/issues/19909), but no concrete plans at the moment.

**Comment by retrofox** [comment]
Thanks, folks, for the feedback. 

To begin with, we have made significant changes to the implementation from the user interface perspective. Now, when the user selects an option from the dropdown, the app replaces the extended block (paragraph, heading) to an AI Assistant instance. Sorry about that

Anyway, I'd like to add some comments.

>  The closest we have now are the snackbar and the notice which exists in a gray minimal version;

We explored and talked about this idea. The basic conclusion was a Notice seems to be like a response from an action that the user could do:

Save the post -> The notice shows a message
Something went wrong -> A warning notice shows up

In this scenario, it's important to inform the user that they have the option to cancel the request process by clicking on the active toolbar button. It's like we should find out a way to inform about it ahead of time.

**Comment by jasmussen** [comment]
Yep, I'll defer to Filipe on the importance of highlighting the stop ability. You could even change the AI icon to a "Stop" icon (square), or add a button when it's working, though the latter would cause a layout shift.

But just to be clear I was referring to [the snackbar](https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--default), not the [notice](https://wordpress.github.io/gutenberg/?path=/story/components-notice--default).

**Comment by retrofox** [comment]
> But just to be clear I was referring to [the snackbar](https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--default), not the [notice](https://wordpress.github.io/gutenberg/?path=/story/components-notice--default).

Correct, the bar that shows up when the user saves the post, for instance. This bar is always anchored in the same place, right (bottom, left)

**Comment by retrofox** [comment]
> You could even change the AI icon to a "Stop" icon (square)

~that would be the coup de grace~ If we change the icon, we lose the requesting animation..._ 😬

**Pull request closed without merging**
