### PR TITLE
Site Icon: Support more browsers and devices

### LINKED ISSUE #1715: Site Icon: Add more tags for increased compatibility
[RealFaviconGenerator.net](http://realfavicongenerator.net/) is the most comprehensive tool I've found for generating favicon tags. An example of what it creates for you:

```HTML
<link rel="apple-touch-icon" sizes="57x57" href="apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="manifest.json">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
```
A walkthrough of why all of these tags are needed is [in their FAQ](http://realfavicongenerator.net/faq). As it stands now, the Site Icon module only generates three tags:

```HTML
<link rel="icon" href="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-32x32.png" sizes="32x32" />
<link rel="apple-touch-icon-precomposed" href="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-128x128.png">
<meta name="msapplication-TileImage" content="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-128x128.png"/>
```

 Jetpack should consider adding whatever tags we're missing for the sake of completeness.

### PR DESCRIPTION
**Pull request by aheckler**
A good compromise between supporting too few and too many browsers/devices. Described [here](https://css-tricks.com/favicon-quiz) under "Example 2: Medium Support". 

Fixes #1715.

### CODE REVIEW

**Comment by enejb** [comment]
I haven't tried it but I think some weird results might when the user doesn't go though the regenerate of the images. Instead of getting WordPress to generate a whole bunch of images we could ask Photon to do that for us. 

Also I don't think it is really necessary to add each of the different size to the mark up. 

According to this article  https://mathiasbynens.be/notes/touch-icons and https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html
The sizes for apple should be 
180 x 180
120 x 120
120 x 120
152 x 152
76 x 76

Also It should be fine to just use one size. As long as it big enough. 

For android I think we should also add 192x192.

**Comment by aheckler** [comment]
> I haven't tried it but I think some weird results might when the user doesn't go through the regenerate of the images.

Can you explain what you mean by this? I tested my code every way I could think of (add an icon, remove an icon, add an icon on top of an existing icon, etc.) and it seemed to work as expected.

> Instead of getting WordPress to generate a whole bunch of images we could ask Photon to do that for us.

Wouldn't that mean requiring a connection to WordPress.com? The Site Icon module currently works without connecting and, IMHO, should stay that way if we can manage it.

> Also I don't think it is really necessary to add each of the different size to the mark up.

[This page](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4) shows them as present.

> The sizes for apple should be 
> 180 x 180
> 120 x 120
> 120 x 120
> 152 x 152
> 76 x 76

Yes, it looks like these are the current recommended sizes. The other sizes are added for devices on older versions of iOS per the [RealFaviconGenerator.net FAQ](http://realfavicongenerator.net/faq) (under "Why so many files?").

> Also It should be fine to just use one size. As long as it big enough.

True. It looks like the biggest Apple icon needed is 180x180, so maybe that's the only one we should be generating?

> For android I think we should also add 192x192.

I think that only works in old version of Chrome, if I am reading [their docs](https://developer.chrome.com/multidevice/android/installtohomescreen#fallback) correctly. The current solution wants you to create a `manifest.json` file that specifies everything, which we can't do.

**Comment by samhotchkiss** [comment]
@aheckler 
>> I haven't tried it but I think some weird results might when the user doesn't go through the regenerate of the images.

>Can you explain what you mean by this? I tested my code every way I could think of (add an icon, remove an icon, add an icon on top of an existing icon, etc.) and it seemed to work as expected.

Did you try adding an icon with the current version of jetpack installed, then upgrading to your branch?  If the image is already there, does it create the new sizes when it learned about them?

**Comment by aheckler** [comment]
> Did you try adding an icon with the current version of jetpack installed, then upgrading to your branch? If the image is already there, does it create the new sizes when it learned about them?

I'll test this later today.

**Comment by enejb** [comment]
@samhotchkiss Thanks for the better explanation, that's exactly what I meant. 
@aheckler Thanks for doing all the hard work and testing as well.

I thought the Android docs you linked to say that they are 'The 192px image format is recommended.' 

I also saw that you removed the windows tile icon is that intentional? 

We could generate a dynamic manifest file. Not sure if is really needed though.

The problem with trying to support every possible device out there is really hard to keep up. 
But I think as long as we cover the majority of the devices out there we should be good. 

Do you know what devices the icons are currently failing to display? Maybe instead of just trying to fix things by display each possible icon without knowing which once currently don't work, we should try to fix the broken browsers/devices. Does that make sense?

**Comment by aheckler** [comment]
> If the image is already there, does it create the new sizes when it learned about them?

Nope, this is broken. I'll need to fix it.

> I thought the Android docs you linked to say that they are 'The 192px image format is recommended.'

Correct, but that's under the heading "Supporting homescreen-installed apps prior to M39", so it's only for outdated versions of Chrome.

> I also saw that you removed the windows tile icon is that intentional?

Yes, see below.

> The problem with trying to support every possible device out there is really hard to keep up. But I think as long as we cover the majority of the devices out there we should be good.

I agree. This is why I chose the "medium support" option as described [here](https://css-tricks.com/favicon-quiz). This covers the following:

- IE11
- Chrome
- Safari
- Firefox
- iOS + Touch icons + full Retina support
- Android Chrome
- Google TV

This means we're missing:

- Old versions of IE
- Windows 8 tiles
- Opera Coast

The problem is, as you said, keeping up with new browsers/devices. This is why I drew the line where I did, because we have to stop somewhere.

Also, we do already have an issue for adding Windows 8 and Windows Phone tiles: https://github.com/Automattic/jetpack/issues/1279

**Comment by aheckler** [comment]
To do:

- [ ] Fix upgrade process with pre-existing site icon
- [ ] Remove unnecessary Apple icon sizes ([all but 180x180](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4))

**Comment by aheckler** [comment]
@samhotchkiss: I think I'm going to need your help with this one. It looks like in order to have sites with existing icons re-crop those images, I'd need to rewrite a portion of the cropping code, since I don't seem to be able to hook into it in any way. Can you give me some pointers here maybe?

**Comment by samhotchkiss** [comment]
@aheckler what happens now?

**Comment by aheckler** [comment]
@samhotchkiss — As it stands now, my PR won't re-crop anything because I'm not sure how to hook into the existing cropping code, which I *think* is here:

https://github.com/Automattic/jetpack/blob/master/modules/site-icon/jetpack-site-icon.php#L435-449

All it does is spit out the new sizes in the `<head>`. It would crop an image correctly if, after upgrading, the user went back in and re-uploaded the same image.

I was thinking we might be able to use the *absence* of a new size as an indicator that Jetpack has been upgraded, and then re-crop the image. But I don't know if I should just use roughly the same cropping code all over again, or rework it in such a way that it'd be more "modular" and easier to hook into.

Does any of that make sense?

**Comment by enejb** [comment]
I think it might be worth while to wait and see what core does. I think favicons is something that will be available in WP 4.3.

**Comment by aheckler** [comment]
> I think it might be worth while to wait and see what core does. I think favicons is something that will be available in WP 4.3.

Link?

**Comment by enejb** [comment]
https://core.trac.wordpress.org/ticket/16434

**Comment by aheckler** [comment]
Thanks! :smile: @samhotchkiss you OK nixing this?

**Comment by kraftbj** [comment]
It'd be good to follow along with core's development. There may be a place for Jetpack to be a bridge between whatever sizes Core supports and the other sizes commonly used. Since Core doesn't update as often as JP, we can be the "hotfix" for folks between a new standard and adoption by core too.

**Comment by dereksmart** [comment]
Punting, as it seems like core still plans on adopting it.

**Comment by aheckler** [comment]
Gonna close this PR for now since it's based off my fork and not a branch on the main repo. Will create a new one if/when it's needed (i.e. once core's work is done).

**Pull request closed without merging**
