### PR TITLE
DNA: Meetup Project: Minimal Jetpack – Take 1

### PR DESCRIPTION
**Pull request by lezama**
Exploration to figure out what is the minimum core that we need to have Connection and Sync.

### CODE REVIEW

**Comment by roccotripaldi** [comment]
Miguel!!

**Comment by mdawaffe** [comment]
> Delete Everything

Ship it.

**Review by mdawaffe — DISMISSED** [review]

**Comment by tyxla** [comment]
😱

**Comment by kraftbj** [comment]
This would be magical but we can't handle such powerful things. Closing until we've leveled up with some more XP.

**Pull request closed without merging**
