### PR TITLE
Masterbar: Use Calypso import/export only on simple sites

### LINKED ISSUE #18294: Nav Unification: Atomic WP-Admin > Export directs user to Calypso and then back to WP-Admin
For Atomic sites, the export tool lives in WP-Admin and isn't available in Calypso. Calypso will direct the user to WP-Admin for their Export needs.

With Nav Unification active, going to WP-Admin > Export will take the user to Calypso.  Then, they will be prompted to `Visit your site's wp-admin for all your import and export needs.` which finally drops the user in `/wp-admin/export.php` if they click the button through.

export

#### Steps to reproduce

1. Starting at URL: /WP-Admin
2. Click Tools > Export and be directed to `https://wordpress.com/export/`
3. Calypso then notes you need to visit your WP-Admin to export. Clicking `Export My WordPress site` takes the user to the proper location, `/wp-admin/export.php`

### PR DESCRIPTION
**Pull request by obenland**
Props @JoshuaGoode.
Fixes #18294.

#### Changes proposed in this Pull Request:

* Moves Import/Export removal & addition to `class-wpcom-admin-menu.php`.
* Removes unneeded unit tests for `class-admin-menu.php`.
* Updates unit tests for `class-atomic-admin-menu.php` to make sure we get the expected results.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Install the Jetpack Beta plugin on your WoA site.
* Switch Jetpack Beta to using this branch
* Make sure Tools > Import and Tools > Export point to their wp-admin pages.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
This works well for me both on Simple & Atomic.

There is one case though, which we may change:

On an Atomic site, the Calypso import screen exists

vs the wp-admin page


With both screens customers can achieve an import, but Calypso screen is more friendly for WordPress specific imports. So I would lean towards redirecting to Calypso `/import/[DOMAIN]` both for Simple & Atomic. @obenland what is your take?

**Comment by obenland** [comment]
Yeah I saw that, too. I decided to keep both export and import in wp-admin for consistency and wider array of import possibilities users have out of the box.

**Comment by cpapazoglou** [comment]
> Yeah I saw that, too. I decided to keep both export and import in wp-admin for consistency and wider array of import possibilities users have out of the box.

Customers can still access the rest importers by clicking "Choose from list" if that is the problem!

**Comment by obenland** [comment]
Sure, I'm just thinking why not show them the full list immediately? You seem to feel rather strongly we should keep it pointed to Calypso?

**Comment by cpapazoglou** [comment]
> Sure, I'm just thinking why not show them the full list immediately? You seem to feel rather strongly we should keep it pointed to Calypso?

I am leaning to Calypso side, cause the Wordpress importer can be used right away from Calypso whereas wp-admin requires an Installation step.



It also has an extra feature for importing from a URL

**Comment by JoshuaGoode** [comment]
On Atomic, WordPress.com provides users with an `Everything Importer` that is only available via Calypso. 

It's essentially our full database & wp-content migration offering.  https://wordpress.com/support/moving-from-self-hosted-wordpress-to-wordpress-com/#option-1-migrate-from-self-hosted

**Comment by obenland** [comment]
@cpapazoglou @JoshuaGoode Thank you for your feedback! I reverted the changes to the Import menu item. Should be good to go for another review now.

**Review by cpapazoglou — APPROVED** [review]
I can confirm that import is redirecting to Calypso now! Let's 🚢 !

**Review by jeherve — APPROVED** [review]
It tests well for me. 🚢

**Comment by obenland** [comment]
r219524-wpcom

**Pull request merged**
