### PR TITLE
Remove Holiday Snow

### LINKED ISSUE #8310: Holiday Snow: Couldn't Find Snow Setting
#### Steps to reproduce the issue

I'm currently recording a screencast and I show my site in that screencast. I don't want to show the snow so the screencast makes sense all year round.

I go to disable the snow feature (temporarily - otherwise it's great) and look through the Jetpack menus unable to find it. I Googled the setting & couldn't find it. Eventually I found a [WP.org forum post that mentions where the setting is](https://wordpress.org/support/topic/why-is-jetpack-making-snow-on-my-website/).

It's under Settings -> General.

#### What I expected

I assumed it would be under Jetpack -> Settings where all of the other settings are.

#### What I suggest

Since you already have Jetpack settings I recommend moving the snow feature under those settings.

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes #8310 #8309 #6260 #6007 #1349 #4615 #4472 #5807 etc etc

#### Changes proposed in this Pull Request:

* Remove Holiday Snow. It is a silly feature.

#### Testing instructions:

* Wait until December 1st
* Head to your site
* Is it snowing? Hopefully not. 

#### Proposed changelog entry for your changes:

Remove Holiday Snow

### CODE REVIEW

**Comment by jaswrks** [comment]
Code changes look good to me also. I searched for `holiday`, `snow`, and `12-01`. Nothing remains but language files. ✅ There's nothing obvious jumping out at me in the dashboard either. So it seems OK.

**Comment by Viper007Bond** [comment]
@gravityrail Calypso also has some Jetpack snow related code in it that will need to be modified to only affect WP.com sites.

**Comment by gravityrail** [comment]
@Viper007Bond We will need to wait on a Calypso PR until we figure out which release this gets merged into, since the Calypso side will probably need to keep the setting for Jetpack versions < 6.x

**Comment by gravityrail** [comment]
Merging this - if anyone objects before December we can revert this PR.

**Comment by tyxla** [comment]
Do you folks think that it makes sense to move this to a separate plugin? It's fair to say that some users might have liked it and would want to use it again.

Or are we intentionally killing it for good? 😅

**Comment by jeherve** [comment]
@tyxla Fell free to jump in here with suggestions:
p1HpG7-4VU-p2

You could also quickly come up with a separate plugin, like we have for Omnisearch:
https://github.com/georgestephanis/omnisearch

**Comment by Viper007Bond** [comment]
There's an absolute boatload of existing snow plugins: https://wordpress.org/plugins/search/snow/

I think we're fine just passing the torch to other people.

**Comment by torres126** [comment]
I'm not too sure if this is the best place to say this or if I'm a bit too late, but using alternative plugins as suggested by @Viper007Bond seems a bit ignorant to WordPress.com users, where this feature seemed popular, due to the limitation of custom plugins to the Business Plan. I highly doubt anyone would subscribe to a plan just for this feature (I mean, it was even labelled "silly" in the original post), but the official reasoning so far now that it's become sought for is that it helps make "Jetpack a more focused and robust product for small businesses". Personally, I do not see the reasoning in that, since the [Business Plan is targeted at small businesses](https://clubpenguinmountains.files.wordpress.com/2018/12/screenshot_20181201-185033.jpg), and now this feature has become exclusive for those sites. It was also an optional feature which received a lot of positive feedback, just take a look at the forum threads with the word "snow" in it today asking where it is!

I really do hope that it is considered reversing this decision to remove the Holiday Snow, because it's really frustrating for WordPress.com bloggers when something so minor is now exclusively doable through a plugin. Thanks. :)

**Comment by Rik67** [comment]
Doubt they will, they don't care about our opinion.

**Comment by Rik67** [comment]
The snow flakes were an optional feature not enabled by default.
So that reasoning isn't valid.
And you have no right to decide how website owners must manage their site.

**Comment by torres126** [comment]
It does help clarify, thanks! I do agree that you all do try to listen to your users, and though I feel self-hosted sites were prioritised for this specific issue, I don't believe those reasons warrant removal, simply because on the basis it's opt in. I know that many of my readers liked the extra touch, and clearly many site owners do too. That outweighed the site being slightly slower (if it even was that), and the very minor risk of a medical issue that probably could even be attributed to other features. There's not much design flexibility that WordPress.com bloggers have on the Free/Personal Plan, but once a year, we could really set a Christmasy "theme" on our website, and only if we wanted to. 

Right now, it seems all that can be done is hope there's enough requests for an opt-in feature, and I'm going to guess that means we're not going to get any snow this year, but I hope there is enough demand. I just struggle to get past the fact it was opt-in, but a lovely feature, that got removed for minor and incredibly rare reasons, so I do hope that it returns. :)

**Comment by jeherve** [comment]
> The snow flakes were an optional feature not enabled by default.

> I don't believe those reasons warrant removal, simply because on the basis it's opt in

While the feature was opt-in for you as a site owner, it was not opt-in for your site's visitors. If you as a site owner chose to enable it on your site, all your site's visitors would get the snow.

We did offer an opt-out option for a small subset of users, but unfortunately not to everyone seeing the snow: on WordPress.com sites, if you were logged in to a WordPress.com account, you had the option to disable snow on all WordPress.com sites you visited, as long as you were logged in.

That said, I can see how frustrating this may be to see something you used to enjoy every year disappear like this. With your feedback, we may revisit this feature and think of better ways to acclimate everyone's needs without excluding anyone.

**Comment by jeherve** [comment]
I like your suggestion, it makes sense. It's not something that is possible right now as the action bar is only available on WordPress.com sites so far (see #6848), but that's something we could implement in the future!

**Comment by torres126** [comment]
That'd be great if we could one day, thanks. :)

**Pull request merged**
