### PR TITLE
Code Sync: sync easy-markdown.php - was divergent

### PR DESCRIPTION
**Pull request by oskosk**
Brings latest changes from .com version of easy-markdown.php

Goes with D12058-code

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

### CODE REVIEW

**Comment by dereksmart** [comment]
@pento looks like you deployed most of these changes to wpcom, can you take a look here?

**Comment by oskosk** [comment]
I'm gonna drop this one out of the milestone

**Comment by zinigor** [comment]
Tested it with the following post content:
```
<table>
<tbody>
<tr>
<td>cell 1</td>
<td markdown="1">

## Header

### Header 2

</td>
</tr>
</tbody>
</table>
```

Editing works OK, but it's still pretty hairy because WordPress tends to remove whitespace and newlines, which ruins Markdown on the first and last lines of the content of the cell. But it does work, so I'd say it's OK.

**Comment by oskosk** [comment]
This one broke stuff and was reverted. See #9461

**Comment by oskosk** [comment]
Second attempt in #9647

**Pull request merged**
