### PR TITLE
Admin Page: refactor core external link component

### LINKED ISSUE #22520: Admin Page: refactor ExternalLink component
Our React dashboard includes its own `ExternalLink` component:
https://github.com/Automattic/jetpack/blob/bb1b6a9a9cfa98600441f8fa31c9f9c4ef9a04a5/projects/plugins/jetpack/_inc/client/components/external-link/index.jsx

Given that Core now includes its own `ExternalLink` component, that we already use in some places in the dashboard, it would be nice to consolidate things and only use the Core component.
We can then take this opportunity to improve on the design / layout a bit, as per the feedback in p8oabR-Nm-p2#comment-5879

*********
> image-7
> image-8
>
> - Increase the spacing from the copy a bit — margin-left: 2px seems to work well.
> - Try to better align them vertically with the copy — vertical-align: -2px works for me, but I might be ignoring some edge cases where this fixed value doesn’t work.
> - In that last one, having the link in its own line makes the layout a bit weird. Let’s remove the line break if possible.
> 
> Here’s that same card with the adjustments mentioned above:
>
> image-9

### PR DESCRIPTION
**Pull request by amustaque97**
Fixes #22520

#### Changes proposed in this Pull Request:

* Replace `ExternalLink` component to use `core` package import.

#### Testing instructions:

* build this PR
* Check if all external links works properly same as previously
* all test cases are passing

### CODE REVIEW

**Comment by amustaque97** [comment]
Hi @jeherve! Could you please take a look at the test failures? Is it okay if we remove `iconsize` from test case... It will effect overall design maybe not sure... In many places we're using iconsize as 16.... However I'm sharing PR link of Gutenberg project to take a look at icon size https://github.com/WordPress/gutenberg/pull/37859

let me know what do you think?

Thank you

**Review by jeherve — CHANGES_REQUESTED** [review]
Thanks for giving this a try!

Yes, since Core's icon is going to be smaller from now on, and have no margin, I think it would be fine for us to do the same thing. You could consequently update Jetpack to do the same.

Beyond the tests, I think it would be useful to review all instances of `ExternalLink` and remove any props that don't make sense or are not useful. For example, the core `ExternalLink` component sets `target="_blank"` and that cannot be overwritten, so we do not need to be setting `target="_blank"` anywhere when we use `ExternalLink`.

**Review by jeherve — CHANGES_REQUESTED** [review]
Nice work!

You should be able to remove the file you deleted from `tools/eslint-excludelist.json` now, so the tests can pass.

**Review by jeherve — APPROVED** [review]
This looks good to me. Nice work on this!

**Pull request merged**
