### PR TITLE
Carousel: fix photo info position

### LINKED ISSUE #19969: Carousel: Large Space Between Image and Description
#### Steps to reproduce the issue

When viewing a gallery using the Jetpack carousel on a mobile device, there's a large gap between the image and the description that wasn't there prior to the refactoring done in https://github.com/Automattic/jetpack/pull/18858

**Screenshots**
**Currently:**

Screenshot_20210528-103124
Screenshot_20210528-103129

**Prior to Refactor (Jetpack 9.6)**

Screenshot_20210528-103217
Screenshot_20210528-103221

You can see previously, the image description was visible without scrolling and the gap to click the full size link wasn't so large.

Internal: p8oabR-FS-p2#comment-5324

cc @sgomes

### PR DESCRIPTION
**Pull request by sgomes**
Fixes carousel info position, so that more of it is visible without scrolling down.

Fixes #19969.

#### Changes proposed in this Pull Request:
* Fix carousel info position

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
See the instructions in #19969.

### CODE REVIEW

**Comment by sdixon194** [comment]
I think that's a lot better on mobile! I think we may need to add a media query, since it seems this also affects desktop and it pushes the image down into the description/comment area.

Screen Shot on 2021-05-31 at 14:42:25

**Comment by sgomes** [comment]
> I think that's a lot better on mobile! I think we may need to add a media query, since it seems this also affects desktop and it pushes the image down into the description/comment area.

Thank you, @sdixon194, looks like there were some particular screen sizes where this was a problem.

I'd rather have a single size, however, since that's what was there before; the change was a side-effect of how the calculation is now performed (in CSS), rather than an intentional thing. I tweaked the values a bit, and in my testing it seems to work well at different screen sizes, but things may be different in your own configuration. Could you please take another look?

Sorry for all the back-and-forth 😞

**Comment by sgomes** [comment]
Rebased on `master`.

**Comment by sdixon194** [comment]
Nice this is working for me now, no worries about the back and forth! Glad we were able to sort it out! 🚢

**Review by sdixon194 — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you for the review, @sdixon194! 👍

**Comment by sgomes** [comment]
r226670-wpcom

**Pull request merged**
