### PR TITLE
Add/jetpack search custom results

### PR DESCRIPTION
**Pull request by robfelty**
We frequently get requests from website owners who would like specific posts to be returned for specific queries. This can be thought of as "pinned posts" or "sponsored posts". This change adds the ability to specify which posts should be put at the top of search results for given queries. 

## Proposed changes:

*

### Other information:

The queries and matching documents can be specified in PHP, e.g. in a theme's `functions.php` file like so
```
add_action( 'init', 'twentytwentyfour_pattern_categories' );

function jps_custom_results( $options ) {
  $custom_results = get_option( 'jetpack_search_custom_results' );
  if ( $custom _results ) {
    $options['customResults'] = $custom_results;
  } else {
    $options['customResults'] = array(
      array(
        'pattern' => 'best WordPress plugins',
        'ids' => array(
            "123-p-8",
            "456-9",
        ),
      ),
      array(
        'pattern' => 'regex:(how )?(to )develop WordPress',
        'ids' => array(
          "123-p-6",
        ),
      ),
    );
  }
    return $options;
}

add_filter( 'jetpack_instant_search_options', 'jps_custom_results' );
```
Note that the document ids are of the form `<blog_id>-p-<post_id>'. This format is relatively easy to understand, though it does require one to know the blog_id of their site. This can be found by inspecting the queries to the public API when performing a search in the developer tools of a browser. The format is also flexible enough such that if you are searching across multiple blogs simultaneously, it allows one to specify pinned posts from multiple blogs. Also note that the order in which the ids are coded is the order in which the results will be returned. It is possible to specify up to 100 documents IDs for a given query pattern. If you specify more, it will simply be truncated. 

There are two types of queries - by default, we will use exact matching. However, it is also possible to specify a query with a regular expression by preceding the query with "regex:". The regexes are evaluated anchored to the beginning and end of the query, such that "regex:hello.*world" will match the query string "hello beautiful world", but not "i say hello to the world" or "hello world i love you". If you would like to get rid of this anchoring, you can add ".*" at the beginning or end of your pattern (or both). This is similar to how regular expressions work in Java. The reasoning behind this is that regular expressions are complicated and it is easy for inexperience developers to get in trouble with them, so we are trying to avoid that as much as possible. Note that the order in which the rules are added is important. The first matching rule will be used.

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

For now, I think we should only implement this with advanced users in mind, thus requiring PHP code. In the future, we might want to create a UI/UX to allow users to add rules in wp-admin.

We may also want to add a way to mark that these posts are being artificially added to the top of the search results. 

## Testing instructions:
In order to test this you will need a Jetpack site with Jetpack Search installed and active. In order to activate Jetpack Search you must have a user connection and purchase it. You can purchase the free plan. You will need to make sure that the site is properly synced and that the site has been indexed. You can check this by looking at the Jetpack Debugger or by looking at the Jetpack Search settings page, which will tell you how many documents have been indexed. 

You also need to sandbox the public api, and apply this patch on your sandbox:  D165510-code
After applying that patch, edit `public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-search-site-v1-3-endpoint.php` adding a line like this around line 561: Use whatever blog_id you are testing with.
```
				$all_a8c_p2s[] = 211634998;
```
We are only allowing the custom results functionality on a limited number of sites right now. That is why you need to add it manually there. 

Add several posts of your choosing. I tested by adding a post with the title "hello universe". I then added a rule saying that searching for "hello world" should return the "hello universe" post on top, even though the default "hello world" post would be a better match. I added this in my themes functions.php file like so:
```
add_action( 'init', 'twentytwentyfour_pattern_categories' );
function jps_custom_results( $options ) {
    $options['customResults'] = array(
        array(
            'pattern' => 'regex:aff.*',
            'ids' => array( "211634998-p-6",)
        ),
        array(
            'pattern' => 'hello world',
            'ids' => array( "211634998-p-6",)
        ),
    );
    return $options;
}
add_filter( 'jetpack_instant_search_options', 'jps_custom_results' );
```
After adding this to the functions.php file, if you perform a search on your site, you should see the "hello universe" post come out as the top result

Bildschirmfoto 2024-03-13 um 19 42 30
Bildschirmfoto 2024-03-13 um 19 42 51

### CODE REVIEW

**Comment by gibrown** [comment]
I wonder if we should get some feedback from Crew on this diff in general. I feel like there may be ways to improve the UX of this filter. For instance, could we have a call something like:

```
jps_add_custom_result( 'best WordPress plugins', $blog_id, $post_id );
```

Maybe we don't want that due to wanting to support both posts and comments, but it feels like it would be good to make it more readable and allowing easily reviewing a potentially long set of customizations.

All of these customizations will also show up in the page source, which is probably fine, but feels a bit weird.

**Comment by robfelty** [comment]
> I wonder if we should get some feedback from Crew on this diff in general. I feel like there may be ways to improve the UX of this filter. For instance, could we have a call something like:
> 
> ```
> jps_add_custom_result( 'best WordPress plugins', $blog_id, $post_id );
> ```
> 
> Maybe we don't want that due to wanting to support both posts and comments, but it feels like it would be good to make it more readable and allowing easily reviewing a potentially long set of customizations.
> 
> All of these customizations will also show up in the page source, which is probably fine, but feels a bit weird.

I see your point, but I also feel like this is something we could add later. I developed this feature in this way, mimicking the `adminQueryFilter` option, which is quite similar (and also ends up in the page source). Neither of these have any PHP APIs really, they are both just available filters. Ultimately, I think that if we want to make it easier to customize Jetpack Search, especially with this option, it would be better to create a UI/UX in the settings in wp-admin which would make it easy to add custom rules, and which would not require users to know blogids, postids, or comment ids. That UI could use any number of wrapper functions which would set this option.

It is also possible that there is a better solution going forward than the way that `adminQueryFilter` is implemented. As far as I can tell though, any sort of PHP filter which we offer has to make its way into the javascript side of things in some way.

**Review by kangzj — APPROVED** [review]
Thanks for working on this Robert! This is a feature users longing for 👍 

It tests well and looks good. It doesn't break without the diff+filters , so I think it's safe to ship. I'd avoid the current release if possible tho.

**Comment by robfelty** [comment]
@kangzj - thanks for testing. I don't think it is urgent to get into the latest release. What do I need to do to put it into the next release? I would like to merge before it gets stale, but then release whenever makes sense.

**Comment by kangzj** [comment]
@robfelty :shipit:

**Pull request merged**
