### PR TITLE
Nav Unification: Set default view with a direct server request

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/21285

#### Changes proposed in this Pull Request:
Previously, when a user clicked on the button that switches from the classic view to the default view of a WP Admin screen, we triggered an AJAX request to store the newly preferred screen before the `href` attribute of the button actually redirected the user to the default view.

However, some browsers like Firefox interpret that AJAX request as a tracking intent because the domain of the AJAX request doesn't match the domain of the `href` attribute, effectively blocking the AJAX request and causing the preferred view to never be updated.

As a workaround, this PR removes the AJAX request and replaces the `href` attribute with a normal server request to ensure the preferred view is updated before we redirect the user to the default view.

#### Jetpack product discussion
N/A.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
- Make sure to use Firefox for testing.
- Prepare the testing environment:
  - Simple sites: Apply D69415-code to your WP.com sandbox, and sandbox both the API and a Simple site.
  - Atomic sites: Install Jetpack Beta and switch to the `fix/nav-unification-set-default-view` branch.
- Go to https://wordpress.com and switch to your testing site.
- Go to "Posts > All posts".
- Open the "Screen Options" tab and switch to the classic view.
- Make sure you're redirected to the WP Admin equivalent screen.
- Make sure that "Posts > All posts" points now to WP Admin.
- Open the "Screen Options" tab and switch to the default view.
- Make sure you're redirected to the Calypso equivalent screen.
- Make sure that "Posts > All posts" points now to Calypso.

### CODE REVIEW

**Comment by dsas** [comment]
While following the testing instructions I ran into a 

```
Fatal error: Uncaught Error: Access to undeclared static property: Jetpack::$instance in /home/wpcom/public_html/wp-content/mu-plugins/masterbar/admin-menu/class-base-admin-menu.php:646 

Stack trace: 

#0 /home/wpcom/public_html/wp-includes/class-wp-hook.php(303): Automattic\Jetpack\Dashboard_Customizations\Base_Admin_Menu->handle_preferred_view('') 
```

I did this:
 1. Used firefox
 2. Sandboxed a simple site and wpcom
 3. Applied diff to sandbox
 4. Went to https://wordpress.com and switch to your testing site.
 5. "Posts > All posts".
 6. Open the "Screen Options" tab and switch to the classic view.
 7. Got redirected to the WP Admin equivalent screen.
8. Hovered over the  "Posts > All posts" link and saw it pointed now to WP Admin. (i.e. same url as current but without preferred-view get var)
9. Clicked the "Posts > All posts" link and got sent back to the same page in WP Admin.
10. Opened the "Screen Options" tab and switched to the default view.
11. Got the error

**Comment by mmtr** [comment]
Good catch, @dsas! Turns out that the `Jetpack` class is not synced to Simple sites. So I changed the approach in 2437c7a and replaced `wp_safe_redirect` with `wp_redirect`, given that destination url is managed by us and defined in the mapping file.

**Comment by BogdanUngureanu** [comment]
Followed the instructions and, in Firefox and Safari, switching from Classic to Default did not persist the change; the menu was still pointing to WP-Admin.

**Review by BogdanUngureanu — APPROVED** [review]
Tested both in Simple and Atomic and works great! 🚢

**Review by jeherve — APPROVED** [review]

**Comment by mmtr** [comment]
Deployed to WP.com in r234452-wpcom.

**Pull request merged**
