### PR TITLE
Contact Info Block add manual blur to fix focus issues

### PR DESCRIPTION
**Pull request by illusaen**
Fixes bug where selecting and typing in an inner block on Contact Info and then exiting out of the block fast (clicking on a different unnested block) would cause cursor to stay in the original inner block and thus result in an unhideable keyboard.

Fixes [#3122](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3122)

Gutenberg-Mobile: [#3340](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3340)

NOTE: Codeclimate mentions that the component (function) is too long/complex; however, since I refactored the class component into a functional one, the entire component itself is a function. I tried refactoring out subcomponents but found that the code was harder to read. I'm going to ignore these suggestions as not relevant to this code.

#### Changes proposed in this Pull Request:

* Adds manual `blur()` call on text input if block is no longer selected.

#### Does this pull request change what data or activity we track or use?
No change to data/tracked activity.

#### Add changelog entries to affected projects
Added under `changelog/fix-contact-info-focus`.

#### Screenshots
<details>

| Before | After |
| - | - |
|  |  |
</details>

#### Testing instructions:
* Have Jetpack-enabled site with version > 8.5.
* Create new post
* Add contact info block
* Type 'test' into "Address Line 2"
* Quickly click on "Email"
* See that cursor is removed from "Address Line 2" and keyboard hides.

### CODE REVIEW

**Comment by jeherve** [comment]
I updated this branch with latest `master` to fix unrelated test failures.

**Review by cameronvoell — APPROVED** [review]
Hello @illusaen The changes here are working well. I see the focus correctly switching off of the address inner block now. 

One piece of feedback, it was a little hard to review the change because the block was turned from a class into a function AND had the new blur function added in a single commit. As far as I can tell, this is the only new functionality added to the class:
1. https://github.com/Automattic/jetpack/blob/0cb266c078a29011eba86f00a46d8ef20c34ef5c/projects/plugins/jetpack/extensions/blocks/contact-info/address/edit.native.js#L75-L81
2. https://github.com/Automattic/jetpack/blob/0cb266c078a29011eba86f00a46d8ef20c34ef5c/projects/plugins/jetpack/extensions/blocks/contact-info/address/edit.native.js#L122-L130
3. https://github.com/Automattic/jetpack/blob/0cb266c078a29011eba86f00a46d8ef20c34ef5c/projects/plugins/jetpack/extensions/blocks/contact-info/address/edit.native.js#L144

As you can see there is no easy way to see that this is the only new functionality, because that code was introduced in the same commit as the conversion to function here: https://github.com/Automattic/jetpack/pull/19367/commits/1168eaac3e8b7eec57ff066be265339fb7efb9fe

In the future, splitting out these two updates into two different commits would be helpful. 

In this case the change looks pretty safe, and all is working as expected. Nice job with the fix!

**Comment by illusaen** [comment]
> As you can see there is no easy way to see that this is the only new functionality, because that code was introduced in the same commit as the conversion to function here: [1168eaa](https://github.com/Automattic/jetpack/commit/1168eaac3e8b7eec57ff066be265339fb7efb9fe)
> 
> In the future, splitting out these two updates into two different commits would be helpful.

@cameronvoell Thanks for your time! I'll definitely do that next time, didn't even think of that!

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
r225432-wpcom

**Pull request merged**
