### PR TITLE
Boost: Add e2e tests to Page Cache

### LINKED ISSUE #33877: Boost: Update e2e tests to test all modules
Tests need a revision. We're not testing the newer modules we added over the past few months.

Tests missing:
- Concatenate JS
- Concatenate CSS
- Image CDN
- Image Guide
- Image Size Analyzer
- Page Cache
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/36668
- [ ] https://github.com/Automattic/jetpack/pull/36694
- [ ] https://github.com/Automattic/jetpack/pull/36716
- [x] ~Boost: Add e2e tests to Image Size Analyzer~
- [ ] https://github.com/Automattic/jetpack/pull/36501
```

### PR DESCRIPTION
**Pull request by dilirity**
Part of #33877

## Proposed changes:

* Add e2e tests for the Page Cache module:
  * Meta isn't visible while the module is deactivated;
  * Cache header isn't present while the module is deactivated;
  * There's an error when plain permalinks are used and there's an attempt to activate the module;
  * Meta is visible while the module is activated;
  * Cache header is present while the module is activated.
* Update e2e tests to allow changing permalinks on the site;
* Update Boost CLI to support activating/deactivating Page Cache;
* Update docker e2e test matrix to include tests (you can check the GH actions section to see the tests).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Run tests to see if everything is working as expected.

### CODE REVIEW

**Comment by dilirity** [comment]
Ready for review.

~This PR needs an update for making relevant parts of the site writable, as wp-config.php and wp-content aren't writable, so tests fail because cache can't be enabled.~

~I've reached out for help here p1711711037050859-slack-CBG1CP4EN~

**Review by haqadn — COMMENTED** [review]
Looks good so far, can we have a test where instead of just checking for the cache header, we look for cache-hit? This will cover more areas of the caching.

**Comment by dilirity** [comment]
@haqadn thanks for the suggestion. I've updated the tests to check the value of the header as well.

**Review by haqadn — APPROVED** [review]
👍🏼

**Pull request merged**
