### PR TITLE
Stats: Dashboard - remove box around blocked numbers

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes user report from @m

## Proposed changes:

* Remove the errant border box from the wp-admin dashboard Stats widget.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

View wp-admin.
* Go to '..'
*

Before:

2023-02-03 at 10 24 AM

After:
2023-02-03 at 10 28 AM

[from different sites; disregard the data difference]

### CODE REVIEW

**Comment by kraftbj** [comment]
@samiff Would you be okay with getting this into next week's release?

**Comment by samiff** [comment]
@kraftbj This looks good, just wondering if there are any border changes needed for the counts on the Jetpack dashboard?

Screenshot 2023-02-03 at 10 01 40 AM

**Comment by kraftbj** [comment]
We should probably remove those too. I need to step away, so I didn't actually build to confirm the commit resolved it. 😬

If it didn't or looks odd, I'll revisit over the weekend.

**Review by samiff — APPROVED** [review]
`border: begone!`

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-11.8` in 50a8c43467ab09c87b50b65593b6330b2e70ec9e

**Pull request merged**
