### PR TITLE
Removed hardcoded environment and cleaned up eslint warnings.

### PR DESCRIPTION
**Pull request by zinigor**
This will let us specify the environment that we need when building Jetpack instead of always using `production`.

### CODE REVIEW

**Comment by zinigor** [comment]
@dereksmart and @oskosk can you please take a look at this?
The main change is the removal of the hardcoded production environment. This will make sure no one gets minified excepitons, but will require us to run `npm run build-production' before bundling a release.

**Comment by oskosk** [comment]
This branch is in need of a rebase. I can test it once it's rebased

**Comment by zinigor** [comment]
Thanks for taking a look! I have just rebased it!

**Comment by oskosk** [comment]
LGTM !

**Pull request merged**
