### PR TITLE
Boost: Ensure that the media replacement retain the original media type

### LINKED ISSUE #21544: Boost: Critical CSS does not respect existing media attributes
### Impacted plugin

Boost

### Steps to Reproduce

1. Register/enqueue a stylesheet with a media parameter other than `all` or `print`. (I used `screen`)
2. Enable Critical CSS
3. Load a page

### A clear and concise description of what you expected to happen.

The stylesheet would have the specified media attribute.

### What actually happened

The stylesheet has `media="all"`.

### Other information

This bug totally breaks the "[Cutting the Mustard](https://www.sitepoint.com/cutting-the-mustard-with-css-media-queries/)" technique for progressive enhancement.

### PR DESCRIPTION
**Pull request by davidlonjon**
Fixes #21544

#### Changes proposed in this Pull Request:

* Make sure that the media type is retained when doing the replacement so the media type can be restored correctly.

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
N/A

#### Testing instructions:

* Enqueue a CSS with the `screen` media type
* Generate Critical CSS
* Look at the dev console and ensure the media type for that enqueued style is still `screen`

### CODE REVIEW

**Comment by davidlonjon** [comment]
@karthikax , this might have an impact on what you are doing in https://github.com/Automattic/jetpack/pull/21665/files. Not sure if it is worth merging this first and you can resolve conflicts in your PR or you might want to incorporate this one directly in your PR and we can close this one,

**Comment by davidlonjon** [comment]
Actually, this requires a bit more work... back to draft

**Comment by davidlonjon** [comment]
I have now made the remaining changes I missed originally.

**Comment by karthikax** [comment]
Thanks for this @davidlonjon. There were a few more changes to make. So, I have incorporated the changes from this in #21665. I think we can close this now.

**Comment by davidlonjon** [comment]
I am now closing this in favor of https://github.com/Automattic/jetpack/pull/21665

**Comment by davidlonjon** [comment]
Thank you @karthikax and great work on #21665

**Pull request closed without merging**
