### PR TITLE
VideoPress: rename block to the `videopress/video` name

### LINKED ISSUE #25794: VideoPress: rename block to videopress/video
Considering that it's possible to register the block from the VideoPress plugin, I think the `videopress` namespace is more proper than `jetpack`. It also opens the door for registering in the future more blocks.

### PR DESCRIPTION
**Pull request by retrofox**
~rebased with https://github.com/Automattic/jetpack/pull/25849. Hold on...~

This PR applies several changes in the code based on the `videopress/video` block name. It means that it not only renames the block name but folders, methods, and calls.

Fixes #

#### Changes proposed in this Pull Request:

* VideoPress Pkg: apply changes according on the `videopress/video` name convention for the video block
* Update VideoPress and Jetpack plugins

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Confirm the VideoPress block is properly registered (you'll get validation issues since it changes the block name)
* Check the item above in all environments: Local dev-env, Simple, Atomic and JN sites.

Testing on Simple sites

* Apply the patch in your sandbox to get the Fusioned changes
* Run the Jetpack downloader to apply the de-Fusiones changes
* Confirm VideoPress Video (v6) block is there. Probably you'll get some validation issues
* Confirm you can transform from/to current implement from/to v6

https://user-images.githubusercontent.com/77539/187229938-4fa5becc-1061-4cc4-83f0-5730af99a886.mov

### CODE REVIEW

**Review by oskosk — APPROVED** [review]
LGTM and tests well!

**Review by oskosk — DISMISSED** [review]
Actually, something here doesn't work in wpcom. Applied the patch and the block is not shown


1. Run arc patch DXXXX
2. Load sandboxed simple site
3. Confirm the block is not listed. 

Running the patch 

image


Running trunk

image

**Comment by retrofox** [comment]
> Actually, something here doesn't work in wpcom. Applied the patch and the block is not shown
> 
> 1. Run arc patch DXXXX
> 2. Load sandboxed simple site
> 3. Confirm the block is not listed.
> 
> Running the patch

We are changing the way to test & ship Jetpack code in Simple sites pd5faL-ej-p2

**Comment by retrofox** [comment]
Let me move again to RfR since I think the issue is mostly how to test and apply properly the changes in different envs. However, the changes suggested here are correct AFAIK.

**Review by oskosk — APPROVED** [review]
LGTM!

**Comment by retrofox** [comment]
r251520-wpcom

**Pull request merged**
