### PR TITLE
Convert E2E infrastructure to ESM

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Playwright uses a Nodejs loader hook, and the combination of that hook and changes in Node 20 results in several bugs when it comes to loading CommonJS files. It's not even clear whether the bugs are in Playwright or Node.

On the other hand, we can avoid all the bugs (whoever they belong to) by converting everything over to ESM syntax. So let's do that.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Are the E2E tests as happy as they were before?

### CODE REVIEW

**Comment by zinigor** [comment]
It looks like some E2E tests are failing with module imports, and others are timing out, so probably something related to that a well.

**Comment by anomiex** [comment]
We have a few known E2E issues at the moment
* Boost lazy-image tests are failing due to the package deprecation/removal, removal of those is planned in #33833.
* The wpcom side of Mailchimp is very flaky in the tests. p1698162491197199-slack-C02FMH4G8 didn't seem to come down to anything.

Paypal block failure should be fixed in with a trunk merge (#33889). Hopefully #33783 will also help with the timeouts. I'll do that merge once I finish up some other stuff.

**Comment by anomiex** [comment]
E2E failures look like just the known issues mentioned above.

**Comment by anomiex** [comment]
Boost lazy-image PR was merged and included in the latest trunk merge. The one failure this time around is the known MailChimp issue.

**Comment by anomiex** [comment]
Hmm. I may have managed to fix the MailChimp test by just reconnecting the test account. At least it worked locally, let's see if it works here too.

**Review by sdixon194 — APPROVED** [review]
The tests are happy! Let's do it!

**Pull request merged**
