### PR TITLE
Update/remove userless jargon

### PR DESCRIPTION
**Pull request by leogermani**
This PR replaces the `userless` we used to use to refer to the Site Connection.

It just replaces internal usage of the term and do not change any functionality

IMPORTANT: Do not merge this PR before we add support to the renamed `allow_site_connection` parameter on WPCOM. D61000-code

#### Changes proposed in this Pull Request:

* Removes the "user-less" jargon

#### Jetpack product discussion

p1HpG7-bRQ-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Are the tests passing?
* Spin up a site
* Test the connection in all states and the basic features. 
* Check the Jetpack Settings page and modules cards that are disabled on a site-level connection
* Look at the code and look for dangerous changes

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @leogermani.
Continuing the discussion that started in code-D61000.

> I think `skip_user` is fine.

I believe that since we're working on this, we should give the parameter the same name across the projects. If we're renaming this to `no_connected_owner`, we should also rename `skip_user` to `no_connected_owner`.

> Is that `userless` param you think should be kept?

Not at all 🙂 
I'm only saying that we should use something less specific than `no_connected_owner`, that wouldn't reflect the actual requirement (site having no connection owner), and the fact of offering "no-user" mode itself.
Because pretty soon `no_connected_owner` might start meaning _"site has no connected owner and no-user mode has never been offered"_, so the parameter name will no longer reflect the reality.
We need something that doesn't need to be updated as we adjust the logic.

**Comment by leogermani** [comment]
> Hi @leogermani.
> Continuing the discussion that started in code-D61000.
> 
> > I think `skip_user` is fine.
> 
> I believe that since we're working on this, we should give the parameter the same name across the projects. If we're renaming this to `no_connected_owner`, we should also rename `skip_user` to `no_connected_owner`.
> 
> > Is that `userless` param you think should be kept?
> 
> Not at all 🙂
> I'm only saying that we should use something less specific than `no_connected_owner`, a name that wouldn't reflect the actual requirement (site having no connection owner), and rather the fact of offering "no-user" mode itself.
> Because pretty soon `no_connected_owner` might start meaning _"site has no connected owner and no-user mode has never been offered"_, so the parameter name will no longer reflect the reality.
> We need something that doesn't need to be updated as we adjust the logic.

I see what you mean. I suggested this name based on the value, but I understand what your concern is now.

So this parameter is a flag to tell WPCOM and Calypso "hey, you can offer the 'skip user' option to this site/user if you want", right?

So my new suggestions are: `allow_skip_user` or `allow_site_connection`.

Then on WPCOM we can take this and decide whether to pass `skip_user` or not. For example, we don't want to offer it for Atomic sites ever.

What do you think?

**Comment by sergeymitr** [comment]
Hi @leogermani.

> So this parameter is a flag to tell WPCOM and Calypso "hey, you can offer the 'skip user' option to this site/user if you want", right?

Yes, exactly what I mean.

> So my new suggestions are: allow_skip_user or allow_site_connection.

I like them both.

The plan looks good, except that I'd like to get the `skip_user` in Calypso renamed too.
Let me know when you're about to wrap it up, and we'll synchronize the timing so I could merge the Calypso part.

**Comment by leogermani** [comment]
Thanks @sergeymitr 

I think this PR is ready for review. Let me know if you want me to work on the WPCOM counterpart for this renamed param or if you're taking over.

**Comment by sergeymitr** [comment]
Hi @leogermani.
Looks good so far.
I'll give it proper testing first thing in the morning.

**Review by sergeymitr — CHANGES_REQUESTED** [review]

**Comment by sergeymitr** [comment]
Hi @leogermani.
Looks good.
Let's merge the [Calypso PR](https://github.com/Automattic/wp-calypso/pull/52704) first, then release the WP.com one, and finally this PR.

**Comment by kraftbj** [comment]
I'll leave it to @sergeymitr to mark as approved. Removing the needs review and adding blocked. Merge whenever y'all are good with it.

**Review by sergeymitr — APPROVED** [review]
Approved, but should be merged after D61000-code goes live.

**Comment by leogermani** [comment]
r225812-wpcomis now deployed

**Pull request merged**
