### PR TITLE
Update Sync annotations versions

### PR DESCRIPTION
**Pull request by leogermani**
NOTE: Let's merge it only after 10.1 is released

This PR updates the package annotation to match them with the package verison instead of the Jetpack version.

When the annotation refers to a feature that existed before the package was created we are going to change it to the first released version of the package and add a new annotation (eg. `@since-jetpack`) to register when this was first added to the Jetpack plugin

#### Changes proposed in this Pull Request:

* Updates the annotation versions to match the package version

#### Jetpack product discussion

p9dueE-3cJ-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Look at the code
* Check if the versions changed match the conversion table in p9dueE-3cJ-p2

### CODE REVIEW

**Comment by sdixon194** [comment]
@leogermani Noting the Do Not Merge label - is this something that is still in progress, or does this need to be reviewed before the code freeze next week?

**Comment by leogermani** [comment]
thanks for the ping. I just removed the label. That was just because we didn't want to merge it in the previous release cycle

**Review by samiff — APPROVED** [review]
I fixed a version typo in a216ad2 other than that versions match up to table & looks good 👍

**Comment by leogermani** [comment]
Looks good. Thanks for the fix @samiff

**Pull request merged**
