### PR TITLE
Added copy post url button

### PR DESCRIPTION
**Pull request by spsiddarthan**
Fixes https://github.com/Automattic/jetpack/issues/12927

#### Changes proposed in this Pull Request:
This PR adds a copy link button in the share this section, which copies the link of the post to the clipboard. 

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
1. Go to Jetpack->Settings->Sharing and click on configure your sharing buttons. 
2. Make sure that you see **Copy Link** as one of the options in the available services list.
3. Move **Copy Link** to the list of enabled services. 
4. Click on "Save Changes" and visit any post and make sure that the "Copy Link" shows up in the share this section.
5. Click on the "Copy Link" button and observe that the toast, "coped post link to the clipboard" appears. 
6. Come back to the sharing buttons screen and change the button style to each of the options available (i.e Icon+Text, Icon Only, Text Only, and Official Buttons) and make sure the changes get reflected in the live preview section. 
7.  Repeat step 6 and go to any post and observe that the "Copy Link" button loads correctly corresponding to the selected button style. 

#### Video demo

https://user-images.githubusercontent.com/6594561/147484866-61c4dc3d-8fad-4dc1-83f0-8cb2199d8e0c.mov

### CODE REVIEW

**Comment by pablinos** [comment]
I think you mentioned you're using a placeholder icon for now. You might be able to find something we can use in [Dashicons](https://developer.wordpress.org/resource/dashicons/#admin-links).

Alternatively we could encode an SVG as a data URI. We've done that before in a few places [like here](https://github.com/Automattic/jetpack/blob/9bf5696b50015c14fc332477e70a9ffca6f6f242/projects/plugins/jetpack/extensions/blocks/slideshow/style.scss#L135)

**Comment by spsiddarthan** [comment]
> I think you mentioned you're using a placeholder icon for now. You might be able to find something we can use in Dashicons.

That's correct, I just used the icon for the 'print' as a placeholder now. 

> You might be able to find something we can use in Dashicons. Alternatively, we could encode an SVG as a data URI. We've done that before in a few places like here. 

Thanks for this, I wasn't sure why `\f469` mean the print icon and what controls that mapping, but I will play around with Dashicons now and figure this out. 
Screenshot 2022-01-04 at 12 32 16 PM

**Comment by pablinos** [comment]
Yes I'd guessed that was from Dashicons too but the code for the [printer icon](https://developer.wordpress.org/resource/dashicons/#printer) is `f193`, so this must be a different font.

**Comment by spsiddarthan** [comment]
I learned from Jeremy that they come [from](https://github.com/Automattic/jetpack/blob/3de92850d59b79906a71ebb01d63b37be7d2d314/projects/plugins/jetpack/modules/sharedaddy/sharing.css#L165) https://wpcalypso.wordpress.com/devdocs/design/social-logo here, we have two choices: add a new icon to the  Automattic/social-logos repo or use the generic share icon shown in the screengrab below. 

Screenshot 2022-01-04 at 2 58 38 PM

**Comment by spsiddarthan** [comment]
On second thought, it might be prudent to have a new logo added. The generic logo is already being used for the more button. 

In the image below, I used it for the button I added as well, however, I grouped it behind the more button along with print, skype, and pockets. So, it might lead to confusion and it's probably best to have a new logo added for this. 

Screenshot 2022-01-04 at 4 15 09 PM

**Comment by pablinos** [comment]
Yes, I agree, let's get a new icon added to that package. We can talk to someone that's done it before, like @porada (any chance you could help here Dom? We want to add a link icon to the Automattic/social-logos package), but it seems like you add a new SVG file to [the sources directory,](https://github.com/Automattic/social-logos/tree/trunk/sources/svg) and then run the grunt tasks to generate the files.

**Comment by pablinos** [comment]
There's actually [a link icon in Gridicons](https://github.com/Automattic/gridicons/blob/trunk/sources/svg/gridicons-link.svg), which I think is based on the same template, so we could copy it over. Gridicons also has a print icon, so there's already a little duplication.

**Comment by spsiddarthan** [comment]
I spoke with Dom yesterday and then spoke with the design team members on the design Slack channel. :) 

> There's actually a link icon in Gridicons, which I think is based on the same template, so we could copy it over. Gridicons also has a print icon, so there's already a little duplication.

I will try doing this.

**Comment by spsiddarthan** [comment]
Parking this for now

**Pull request closed without merging**
