### PR TITLE
Story block improvements

### PR DESCRIPTION
**Pull request by Tug**
Improvements to the Story block

- Improve progress indicator in story preview when there are many frames.
- Add title attribute to image and videos
- Block editor: Minor copy fix: added a comma after “upload new ones”
- Block editor: Remove the fullscreen icon from the story block preview. Replaced with a slide count
- Block editor: Fix CSS regressions on new versions of wordpress: left and right arrow too small, stopped using the Button component from `@wordpress/components`
- Minor update to the story icon, updated to match the other G2 style icons in the web block picker

#### Testing instructions:
Make sure there is no regression after this patch is applied and all the items in the list are addressed.

#### Proposed changelog entry for your changes:
* Minor visual improvements to the Story block

### CODE REVIEW

**Comment by aforcier** [comment]
Tested everything so far on a Jetpack site and also the WPcom patch, everything looks great so far 👍

**Comment by leogermani** [comment]
Sorry to as dumb questions but:

How do I find this block? I've tried enabling Beta blocks and buying a plan and I don't see it.

Also, is there a link to somewhere that shows the basics of how it works? It would be helpful to testing.

**Comment by Tug** [comment]
Hey @leogermani! The block hasn't been announced officially, but an open beta should be starting very soon (see project thread pbD5rk-h-p2).

It's a mobile-first block in the sense that the creation experience is more suited for mobile but it does support the web block editor. It's currently hidden from the inserter that's why you can't find it, but you can try it by copy pasting the following into the code editor and going back to visual editor mode.

```
<!-- wp:jetpack/story -->
<div class="wp-block-jetpack-story wp-story"></div>
<!-- /wp:jetpack/story -->
```

**Review by aforcier — APPROVED** [review]
Since this is now marked for review, converting [my earlier comment](https://github.com/Automattic/jetpack/pull/17708#issuecomment-723359011) into an approval. 👍

**Review by jeherve — APPROVED** [review]
This looks good to me. I only have a minor remark, but this can be addressed in a follow-up PR if you prefer.

**Review by jeherve — APPROVED** [review]

**Pull request merged**
