### PR TITLE
Connection: fix site registration for the `connect_url_redirect` webhook.

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request:
Fix site registration for the `connect_url_redirect` webhook.

The bug was introduced in #24529

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
1191179647901802-as-1202582656293827

#### Does this pull request change what data or activity we track or use?
No.

##### Connection flow with WP.com login
1. Disconnect Jetpack, logout of WP.com
2. Connect Jetpack logging into WP.com during the connection flow
3. Confirm it went well.

##### WP.com migration flow
1. Create a JN site with Jetpack Beta, deactivate and delete Jetpack plugin (but keep Jetpack Beta).
2. Go to https://wordpress.com/start/domains and create a WP.com site
3. Go to `https://wordpress.com/setup/import?siteSlug=your-site-slug`, enter your JN site's URL, and proceed with the steps.
4. After clicking the "Jetpack Required - Install Jetpack" button, enter your JN site's credentials and click "Install Jetpack". You will be redirected to the "Invalid request" error page.
5. Go to your JN site and use Jetpack Beta to checkout the branch `fix/user-connect-second-attempt-registration`.
6. Switch back to the tab with the "Jetpack Required - Install Jetpack" button, click on it.
7. You should be shown the "Approve" button page. Click on it and confirm the connection is established successfully.

##### Mobile "Add Site" flow
1. Create new JN site with Jetpack Beta, remove Jetpack plugin.
2. Open the WP.com mobile app, choose to add new site, enter the JN site's URL, then credentials.
3. Click "Stats" on the site's screen, then "Install Jetpack -> Set Up".
4. When it says "Jetpack installed", go to JN site's Jetpack Beta and checkout the branch `fix/user-connect-second-attempt-registration`.
5. Click "Set Up" on the "Jetpack installed" screen. You should see the "Approve" button - click it.
6. Confirm that stats are now enabled.
7. Check the JN site, confirm it's fully connected.

### CODE REVIEW

**Comment by coder-karen** [comment]
Did some connection testing, this is what I found:

Tested via wp-admin (clicking on Set Up Jetpack via the plugins page), and the connection worked fine.

Tested via iOS WordPress app:
- Clicked on Plugins > Manage > Jetpack > Installation (bottom of that next page) > Set Up Jetpack. That worked. Without this PR, that doesn't work.
- Then deactivated Jetpack via wp-admin, went back to the mobile app and clicked on Stats > Install Jetpack. That didn't work - resulted in a blank page (same result as here: p1657278614717759/1657190919.201239-slack-C011BKNU1V5). Tested the same with Jetpack 11.0 - it didn't work then either.

So it seems like this PR has fixed the issues being reported recently but we've potentially uncovered another broken flow in the process? From what I can tell though, the 'immediate' issues look fixed here.

**Review by coder-karen — APPROVED** [review]
Approving this - also noting here for anyone testing this PR that we are approving it early in order to cut a release and would really appreciate further testing still. Until the new release version is cut that would be by using Bleeding Edge, if using the Beta Tester plugin (once this PR is merged).

Edit - this can now be tested by installing Jetpack version 11.1.2 from the WordPress.org [Jetpack plugins page](https://wordpress.org/plugins/jetpack/advanced/).

**Comment by twstokes** [comment]
👋 Hi @sergeymitr - I tested the mobile flow on iOS by doing the following on a JN site:

1. Tapped "Install Jetpack" from within the Stats screen
2. Observed that Jetpack was installed in WP Admin, and used Jetpack Beta Tester to switch to this PR's branch
3. Tapped "Set Up"
4. Observed a blank screen

Removing [the locale from these URLs](https://github.com/wordpress-mobile/WordPress-iOS/blob/ddb0ba2c7e48e6e3989bc8c948592f71da7b4344/WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift#L62-L69) in the WPiOS app resulted in the prompt to log in and approve / connect Jetpack to the site. From what I can tell the installation was successful after that and the stats screen worked.

**Comment by twstokes** [comment]
[Android doesn't use the locale in the URL](https://github.com/wordpress-mobile/WordPress-Android/blob/241a175d8ddc58e852b206bcf9b95ce351ce839e/WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java#L48), so should we update iOS to remove it?

**Comment by coder-karen** [comment]
Cherry-picked to release branch in c736435bd082b31a9e9e064286f1f955323040f6

**Comment by sergeymitr** [comment]
@twstokes from what I can tell the URL part after `connect/` is meant for either a specific key (`plans`, `authorize`), or a chosen plan.
I haven't found it being used for locale, probably a legacy approach.
It works that way for other pages (e.g. login) though, but I'd assume it's safe to delete or replace with `locale` GET-parameter.

**Comment by twstokes** [comment]
Thank you @sergeymitr!

**Comment by twstokes** [comment]
I just wanted to note that I tested WordPress for Android `20.3-rc-1` (our latest beta) and it worked great. 🚀

**Comment by sdixon194** [comment]
Okay, released a new version of the plugin ( 1.41.4.1) and updated the `jetpack/branch-11.1` branch to consume it, so the release candidate branch in the beta plugin should be using the updated package/fix. Feel free to test with that.

**Comment by twstokes** [comment]
I'm not totally sure what's going on yet, but I can't hit the "Continue" button in the app to set up the connection with the release candidate. This site _did_ have Jetpack connected earlier, but then I disconnected it, so I'm unsure if there's a relation.



This succeeded on Android - the web view navigated to "Completing setup" where I could tap "Approve" to connect my .com account. iOS appears to be hung on the navigation, so I'm going to wipe the app's state and try again.

**Update:**

On iOS, performing a clean install allowed me to see the .com prompt, though it also had some quirks. This seems like more client-side issues to iron out on WPiOS, so from what I can tell these Jetpack plugin changes are OK.

**Comment by sdixon194** [comment]
Also looks like the artifact just finished building about 10 minutes ago, so if you checked too soon, it might not have made it to the beta plugin now that I look at the timeline! Should have waited till that was done before leaving a comment.

**Comment by twstokes** [comment]
> Also looks like the artifact just finished building about 10 minutes ago, so if you checked too soon, it might not have made it to the beta plugin now that I look at the timeline! Should have waited till that was done before leaving a comment.

No worries @sdixon194! I noticed that and reset my tests when the new candidate came through. This is what I used: `Release Candidate | 11.1.1-2678713169-g3ce9537`

**Comment by sergeymitr** [comment]
@twstokes can you please check if the [same problem](https://github.com/Automattic/jetpack/pull/25099#issuecomment-1185819703) happens to you when you test on Jetpack 11.0.
If it does, that's a separate issue we should look into fixing.

**Comment by twstokes** [comment]
> @twstokes can you please check if the [same problem](https://github.com/Automattic/jetpack/pull/25099#issuecomment-1185819703) happens to you when you test on Jetpack 11.0. If it does, that's a separate issue we should look into fixing.

@sergeymitr I'm going to do some deeper testing on the WPiOS client but my quick answer is:

When I tested with Jetpack 11.0 and a clean install I still experienced some of the client-side quirks:
- Stats screen didn't populate until I backed out all the way to My Site and reloaded it
- A prompt was shown after logging in to my .com account to choose a .com site

This leads me to believe that these are all client-side and this Jetpack patch isn't introducing regressions. If I find definitive proof otherwise I'll chime in here.

**Comment by sergeymitr** [comment]
@twstokes thanks for testing!
Please reach out when you get more info, and I'll be happy to help with the Jetpack and WP.com side.

**Comment by twstokes** [comment]
> @twstokes thanks for testing! Please reach out when you get more info, and I'll be happy to help with the Jetpack and WP.com side.

Thanks @sergeymitr! [Here's where we're at right now with iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/19056). The testing steps in that PR matched Jetpack 11.0 exactly (quirks and all), so I think we're OK. There's a video as well.

The [problem I posted above](https://github.com/Automattic/jetpack/pull/25099#issuecomment-1185819703) must've been a really long delay before the .com prompt (you can see the partial progress bar in the screenshot). I've tested a few times since then with no issues. 👍

**Comment by ouikhuan** [comment]
I've been testing from the WP.com migration flow and it works fine following the instructions above. However, if I skipped the step: 

> 4. After clicking the "Jetpack Required - Install Jetpack" button, enter your JN site's credentials and click "Install Jetpack". You will be redirected to the "Invalid request" error page.

Activate the release candidate (11.1.2-2679453611-g38d470c) without clicking the "Install Jetpack" beforehand it will fail. Is this something we expect?
Screen Shot 2022-07-17 at 5 46 28 PM

**Comment by coder-karen** [comment]
Jetpack 11.1.2 has now been released and is the stable version of the Jetpack plugin, so the issues that had recently been introduced should now have been fixed. It looks like there were other issues uncovered during testing that are being tracked separately.
@ouikhuan the issues you are reporting with the migration flow - do you know if they were happening in an earlier Jetpack version (eg. 11.0)? Also, is the flow via the mobile app? It may be related to issues mentioned in the comment above if so.

**Comment by ouikhuan** [comment]
@coder-karen the issues I reported above might be related to beta only. I've just created a new testing site and go through the migration flow with Jetpack 11.1.2 installed and everything looks great! Thanks for fixing this in such a short time!

**Pull request merged**
