### PR TITLE
Replace existing whatsapp api url

### PR DESCRIPTION
**Pull request by jlapitan**
Whatsapp click to chat api url has been updated. 
Reference: https://faq.whatsapp.com/en/android/26000030/ 

#### Changes proposed in this Pull Request:

* API url change, shortened url

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Existing feature

#### Proposed changelog entry for your changes:

* Whatsapp Click to Chat api url changed.

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
That doesn't seem to work for me. `wa.me` seems to expect a phone number, which the sharing button does not provide. As a result I get an error when trying to share on an Android device for example:

image

I am not sure we can use this domain in this case.

**Comment by jlapitan** [comment]
I have updated my code

**Comment by jeherve** [comment]
This won't work either.
image

That domain expects a phone number so I don't think we can use it here.

**Comment by jlapitan** [comment]
api documentation reference: https://faq.whatsapp.com/general/26000030/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Pull request closed without merging**
