### PR TITLE
Add more sharing networks

### PR DESCRIPTION
**Pull request by lsl**
Related to https://github.com/Automattic/dotcom-forge/issues/9178

## Proposed changes:

This PR adds the following sharing networks:

- Tumblr
- LinkedIn
- Pinterest
- Email

Screenshot 2024-09-25 at 2 49 54 PM

The reason these networks are added is to match the ones from the now-deprecated Sharing modal:

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes by following the instructions from https://github.com/Automattic/jetpack/pull/39353#issuecomment-2343814965.
* Head to Posts > Add New Post.
* Publish a new post and ensure that the newly added networks are available.
* Ensure that they work as intended.

### CODE REVIEW

**Review by manzoorwanijk — COMMENTED** [review]
That manual sharing is to provide an alternative for the networks that we don't support in publicize/social yet/anymore.

So, we need to think/discuss which networks we want to include here. We also don't want to take up too much real estate in that sidebar

**Comment by taipeicoder** [comment]
> That manual sharing is to provide an alternative for the networks that we don't support in publicize/social yet/anymore.
> 
> So, we need to think/discuss which networks we want to include here. We also don't want to take up too much real estate in that sidebar

Thanks for the context, what I got was that publicize/social are handling automatic sharing and these buttons are meant for manually sharing for networks that publicize/social don't support in one way or another. Is my understanding correct?

In that case, I agree that this PR doesn't fit the goal of these buttons and that if we wanted to add more buttons in the post-publish panel it will need to be via another approach. Do you have any recommendations?

**Comment by manzoorwanijk** [comment]
> what I got was that publicize/social are handling automatic sharing and these buttons are meant for manually sharing for networks that publicize/social don't support in one way or another. Is my understanding correct?

Correct.

> In that case, I agree that this PR doesn't fit the goal of these buttons and that if we wanted to add more buttons in the post-publish panel it will need to be via another approach. Do you have any recommendations?

I am not really sure yet, but we at (@Automattic/jetpack-reach) will discuss it and get back to you.

**Comment by spsiddarthan** [comment]
Thanks for the ping! Discussed with @manzoorwanijk here - p1727414149736989-slack-C02JJ910CNL.

Our recommendation is to only have networks that we don't support for auto-sharing in the manual sharing list. But, let us know if you had other ideas/thoughts around it.

**Comment by taipeicoder** [comment]
Thank you both for your inputs. Given that this change doesn't align with the feature's goals, I'll close this PR and discuss with the team regarding next actions 🙂

**Comment by simison** [comment]
@taipeicoder  wasn't the Pinterest getting good number of clicks in the modal, and it's not in Publicize's [automatically shared networks](https://github.com/Automattic/jetpack/blob/609132a9da6ba18bbb487faebdb7ea6ec9930145/projects/plugins/social/readme.txt#L69-L77)?

**Comment by taipeicoder** [comment]
@simison the numbers roughly were:
- Facebook: ~2.4k per week.
- LinkedIn: ~850 per week.
- Tumblr: ~425 per week.
- Pinterest: ~700 per week.

Not sure how the numbers match performance for auto-sharing, but in the modal it was close to LinkedIn. cc: @manzoorwanijk

**Comment by manzoorwanijk** [comment]
CC: @Automattic/jetpack-reach

**Pull request closed without merging**
