### PR TITLE
Clean `_inc/` dir

### PR DESCRIPTION
**Pull request by dereksmart**
This seeks to remove unused code from the `_inc/` directory.  

To test: 
- Make sure everything works in the old settings views at `wp-admin/admin.php?page=jetpack_modules`
- Make sure no console errors are shown anywhere in the app.

### CODE REVIEW

**Comment by eliorivero** [comment]
- the entire sidebar with `View`, `Sort By` and others is **not** working
- activation and deactivation works, both for a single module and for a batch
If the sidebar elements are not supposed to work it would be better to hide it

**Comment by dereksmart** [comment]
Yeah they should work.  Let me see what is missing

**Comment by dereksmart** [comment]
@eliorivero found the problem and fixed.

**Comment by zinigor** [comment]
I love this PR! Let's get this and the other one ASAP to catch missing stuff as early as possible.

**Pull request merged**
