### PR TITLE
Updates banner styles and behaviour.

### LINKED ISSUE #6449: Upgrade banner finesse
As promised, let's go ahead and fine-tune these banners to be as perfect as can be. For "ease of review," I have screenshots of each of the banners and which plans they are visible for.

There are four plans that step up in this order: Free, Personal, Premium, Professional

We should be reviewing placement, copy, and deciding whether to use a button instead of an arrow. 

**Note:** There is a display bug that will be addressed elsewhere with the arrow overlapping the text.

### Premium video
image

**Visible for:** Free, Personal

### SEO 1
image

**Visible for:** Free, Personal

### SEO 2
image

**Visible for:** Premium

**Difference:** No longer shows Ads selling point

### Backups and security 1
image

**Visible for:** Free

### Backups and security 2
[NOT IMPLEMENTED YET]

**Visible for:** Personal

**Difference:** No longer shows Akismet selling point

### Backups and security 3
This is up for debate. We could still offer a nudge to those on the premium plan to upgrade to get real time scanning and unlimited/realtime backups. I lean towards not having it.

CC @richardmuscat @ashleighaxios @rickybanister

### PR DESCRIPTION
**Pull request by zinigor**
Fixes #6449 

#### Changes proposed in this Pull Request:
* Made banners only appear when the site data is not being fetched.
* Used new styles for banners: one liners with call to action buttons.
* Added a condition to hide settings card children for cases when the plan doesn't allow configuration.
* Properly attached banner plan props to each feature's required plans.

### To test
* Make sure correct banners appear for correct plans.
* Make sure call to action is 'Activate' when it's not yet in the plan, and 'Upgrade' when it's in the plan but a higher tier is needed.
* Make sure the links have the right query parameters, like `settings-video-premium` for VideoPress on free and personal, and `settings-video-pro` on VideoPress for Premium.

screen shot 2017-03-15 at 2 46 07 pm
screen shot 2017-03-15 at 2 45 20 pm
screen shot 2017-03-15 at 2 44 10 pm
screen shot 2017-03-15 at 2 43 48 pm
screen shot 2017-03-15 at 2 43 26 pm

### CODE REVIEW

**Comment by zinigor** [comment]
### Video on Free and Personal
free-media

### SEO on Free and Personal
free-seo

### SEO on Premium and Business
premium-seo

### Security on Free and Personal
security-free

### Security on Premium and Business
security-premium

**Comment by zinigor** [comment]
I have removed the previous comment with screenshots because they were outdated. Please let me know if you need screenshots for the new code.

**Comment by dereksmart** [comment]
Looks good and works well.  Updated the original PR description to include recent screenshots so maybe @MichaelArestad would like to take a look

**Comment by MichaelArestad** [comment]
All of those buttons should say "Upgrade." Other than that, it's aces.

**Comment by MichaelArestad** [comment]
CC @richardmuscat I can make copy changes in another PR, but here's where we're at.

**Comment by eliorivero** [comment]
It's good. I'm going to update those buttons with the text suggested by Michael and merge.

**Comment by MichaelArestad** [comment]
@eliorivero thanks!

**Comment by MichaelArestad** [comment]
And thanks for the rapid turnaround time on these @zinigor

**Pull request merged**
