### PR TITLE
Instant Search: Add an "Expanded" search result format

### LINKED ISSUE #15013: Instant Search: Add images to search results
Add a version of the search results that display featured images.

An example layout:

screen_shot_2020-03-17_at_6 27 00_am

This is a bit different from the WIP layout we have for products in #14017 

A bit closer to the "engagement" layout that we have been planning to steal from WP.com Reader. See #13350

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #15013.

#### Changes proposed in this Pull Request:
* Adds a new "Expanded" result format.

Screen Shot 2020-06-24 at 11 20 40 AM

* Tweaks the existing "Minimal" result format.

Screen Shot 2020-06-19 at 2 39 46 PM

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your Jetpack installation.
* Try a search. You should still see the previous result format.
* To try the new format, go to the Jetpack Search section of the Customizer and select the "Expanded" result format.

#### Proposed changelog entry for your changes:
* Adds a new, default search result format configurable from the Customizer.

### CODE REVIEW

**Comment by jsnmoon** [comment]
@keoshi, would love your feedback! This is a new search result format that will be enabled by default for Jetpack Search users.

**Comment by gibrown** [comment]
This is looking very cool.

Mostly I just have some design thoughts:
- Showing the name of the post type may not work that great on some sites. I think we should remove it.
- This does seem cool as the new default, but I'm not sure we should automatically turn it on for existing sites without them explicitly changing it. Maybe the minimal version is the default in code, and we set this from our auto config?
- In a number of cases I've found that the date is not always appropriate. For instance, a support page, the date may not matter. We had discussed displaying the path instead, what if we tried that at either the top or bottom of the post?
- Smaller dimension images feel a bit weird. I think in the Reader we just zoomed and cropped them:

Screen Shot 2020-06-19 at 9 48 39 AM

- Always showing the image box feels like it takes up a lot of space to me. I guess there are cases where it makes sense to me (like if there is a video or something), but seeing a bunch of results that have the same icon doesn't give much new info. Could we use some of the logic/design from Reader search:

Screen Shot 2020-06-19 at 9 40 02 AM

So if there is an image (or video) then we display it, but otherwise we don't. We could also show multiple images, though that may be overkill. It would be cool to use an icon or something to indicate when there are multiple images or at least when there is a gallery.

**Comment by jsnmoon** [comment]
> Showing the name of the post type may not work that great on some sites. I think we should remove it.

I went ahead and removed post types from the header for now, but I think it'll be great to show some sort of grouping between search results in the topmost header.

How about the following?
- For common post types, show them as-is (e.g. "Post", "Pages", and "Products").
- For uncommon post types that aren't demarcated with an underscore, show them capitalized (e.g. "Article").
- For uncommon post types demarcated with an underscore, show "Other".

> This does seem cool as the new default, but I'm not sure we should automatically turn it on for existing sites without them explicitly changing it. Maybe the minimal version is the default in code, and we set this from our auto config?

This sounds like a better idea than the current implementation. For now, I'll go ahead and make a note in the auto-config function to set the result format customizer value in the future.

> In a number of cases I've found that the date is not always appropriate. For instance, a support page, the date may not matter. We had discussed displaying the path instead, what if we tried that at either the top or bottom of the post?

This is tricky because what's valuable to show can change depending on the site's intended purpose. For a support site, prioritizing the path over the date can make sense if the path is well-formatted. For a news site, prioritizing the date can make sense to give a chronology to the search results.

For now, I recommend that sites add custom CSS to hide the date header via CSS. I've added a dynamic class name to each search result that enables the site owner to target specific post types. I'll also recommend against adding paths to search results; could you point me to previous discussions on this?

> Smaller dimension images feel a bit weird. I think in the Reader we just zoomed and cropped them:

I've gone back and forth on whether to zoom into the image. I'll go ahead and revert one of my changes so we can compare it zoomed vs not.

> Always showing the image box feels like it takes up a lot of space to me. I guess there are cases where it makes sense to me (like if there is a video or something), but seeing a bunch of results that have the same icon doesn't give much new info. Could we use some of the logic/design from Reader search:

From what I gathered from the example screenshot in #15013, showing a placeholder image container is intended to provide visual consistency for all search results when shown in this format.

I'd recommend against eliminating the placeholder images container. Instead, I recommend we double down on increasing the relevance of the Gridicon shown inside the placeholder that changes depending on the result content. Currently, it shows corresponding Gridicons for post and page post types.

**Comment by jsnmoon** [comment]
> - For post types that aren't demarcated with an underscore, show them capitalized (e.g. "Article").
> - For uncommon post types demarcated with an underscore, show "Other".

I went ahead and added this in 4c98cff.

**Comment by jsnmoon** [comment]
> > This does seem cool as the new default, but I'm not sure we should automatically turn it on for existing sites without them explicitly changing it. Maybe the minimal version is the default in code, and we set this from our auto config?

> This sounds like a better idea than the current implementation. For now, I'll go ahead and make a note in the auto-config function to set the result format customizer value in the future.

I went ahead and added an `update_option` call in the auto-config to set the result format to `engagement`.

**Comment by gibrown** [comment]
> I'll also recommend against adding paths to search results; could you point me to previous discussions on this?

Ya, I think @keoshi and I had a long discussion about this in Portland. Ultimately I think we decided that paths and dates were not worth the space for the minimal search results. I think that is not a concern here though. The concern with showing the date is that if an older result is at the top then it feels less relevant. I can think of a bunch of sites where this will be true. Two discussions I found:
- https://github.com/Automattic/jetpack/pull/14665#issuecomment-585777386
- https://github.com/Automattic/jetpack/pull/14022

WordPress generally does a good job with paths where posts will have dates, and pages will not. Pages can also include hierarchy so you can have a path like `/support/search/customize` which feels like it gives a lot of valuable information.

We could try to reproduce some of the logic, but there are a lot of options for custom post types: https://developer.wordpress.org/reference/functions/register_post_type/. We do already fall back to displaying the path when we have no other content to show, so displaying the path would mostly just expand on that existing idea.

The other thing I'm thinking here is that all browsers do show the path, so we know that it is something that the user would expect to show an end user. That is not true of a date.

> I've gone back and forth on whether to zoom into the image. I'll go ahead and revert one of my changes so we can compare it zoomed vs not.

@bluefuton is there Reader logic it makes sense to steal for this?

> From what I gathered from the example screenshot in #15013, showing a placeholder image container is intended to provide visual consistency for all search results when shown in this format.

Ya I agree, though that is particularly from one site where most all of their posts have an image and I am not sure we can assume that in general. This really needs more design help. cc @folletto

**Comment by folletto** [comment]
This seems a discussion with a lot of variable, so apologies in advance if I'm missing any. Note that if you could also add before/after screenshots would make the evaluation easier and more precise.

> I think we decided that paths and dates were not worth the space for the minimal search results

+1

> The concern with showing the date is that if an older result is at the top then it feels less relevant

+1

>  though that is particularly from one site where most all of their posts have an image and I am not sure we can assume that in general.

In general, I'd try to not borrow much from Reader. Its layout is not great, and it's also optimized for "fill", not for scannability. Search is all about scannability, so keeping the titles aligned is very important.

There are two simple approaches for images here we can take for a first PR:

1. Put the image to the right, so the text and body remains aligned preserving scannability, and the "indentation" happens on the right
2. Remove placeholders but keep alignment:

Screenshot 2020-06-22 at 20 09 47

**Comment by jsnmoon** [comment]
> Two discussions I found: (@gibrown)
> 
> #14665 (comment)
> #14022 

Great! Thanks for the links, now I have some context to work with. I agree with how recommending older results might hurt the end-user's perception of how accurate Jetpack Search results are. What if we followed @keoshi's [recommendation here](https://github.com/Automattic/jetpack/pull/14022#issuecomment-555098416) on following Google's UX of showing the date inline with the result content?

image

Or do we really want to omit that information altogether? 

> Note that if you could also add before/after screenshots would make the evaluation easier and more precise. @folletto 

This PR adds a new "Engagement" search result format pictured below; this format did not exist prior to this PR.

Screen Shot 2020-06-19 at 2 39 08 PM

The existing search result format was named the "Minimal" search result format, also pictured below.

Screen Shot 2020-06-19 at 2 39 46 PM

> Put the image to the right, so the text and body remains aligned preserving scannability, and the "indentation" happens on the right

This makes a lot of sense, I'll take a crack at implementing this.

**Comment by gibrown** [comment]
> following Google's UX of showing the date inline with the result content?

Google is actually smarter than this. Here is "wordpress":

Screen Shot 2020-06-23 at 6 45 48 AM

There are times when a date helps, and times when it doesn't. I think our fastest shortcut to being "smart" would be to use the path. We could reprocess that path though. Split the slashes; break out dates, etc. Google does this for instance:

Screen Shot 2020-06-23 at 6 50 38 AM

We could probably try and build a "context" string in the API that could be displayed? Maybe we leave off the final slug? Some cases it would just be a date, others it would be hierarchy, and some it would be empty. This would probably also improve what our fallback in the minimal results currently looks like:

Screen Shot 2020-06-23 at 6 54 19 AM

**Comment by gibrown** [comment]
> In general, I'd try to not borrow much from Reader. Its layout is not great, and it's also optimized for "fill", not for scannability. Search is all about scannability, so keeping the titles aligned is very important.

@folletto in general I have been thinking about this layout as "engagement", meaning it is a bit more about discovery and browsing as opposed to quickly scanning results. A bit more about news as opposed to answering a question. [The third layout planned is more of a grid for e-commerce](https://github.com/Automattic/jetpack/pull/14017), though this could also serve for e-commerce. That said, we probably do need some actual names. Maybe "Minimal", "Engaging", and "Grid"?

**Comment by folletto** [comment]
> this layout as "engagement", meaning it is a bit more about discovery and browsing as opposed to quickly scanning results.

I'm a bit skeptical on this approach. This is ultimately a search, we aren't trying to create a nice layout for presentation. The user intent is to quickly get to the content they want. I feel that trying to not follow this principle isn't ideal for a search layout.

**Comment by jsnmoon** [comment]
> We could probably try and build a "context" string in the API that could be displayed? Maybe we leave off the final slug? Some cases it would just be a date, others it would be hierarchy, and some it would be empty. @gibrown 

I think it'll be worth exploring this idea in a follow-up PR in the future.

> That said, we probably do need some actual names. Maybe "Minimal", "Engaging", and "Grid"? @gibrown 

How about "Expanded" instead of "Engagement"?

> Put the image to the right, so the text and body remains aligned preserving scannability, and the "indentation" happens on the right @folletto 

Here's my first stab at moving the image container to the right:

Screen Shot 2020-06-23 at 3 27 40 PM

**Comment by jsnmoon** [comment]
Now featuring the result path instead of post types + date:

Screen Shot 2020-06-23 at 3 57 20 PM

**Comment by folletto** [comment]
> How about "Expanded" instead of "Engagement"?

+1

> Here's my first stab at moving the image container to the right:

Let's also remove blanks, and make the text flow to the edge when they are removed.

> Now featuring the result path instead of post types + date:

I'm not too convinced about this, but I'd defer to y'all on its utility.

Regardless: 

1. I'd remove the domain bit, that's not useful and just adds length.
2. I'd also go for a solution that crops it, instead of folding on multiple lines. An ellipsis would work.

**Comment by gibrown** [comment]
> How about "Expanded" instead of "Engagement"?
Great!

> I'd remove the domain bit, that's not useful and just adds length.
+1

> I'd also go for a solution that crops it, instead of folding on multiple lines. An ellipsis would work.
+1

I like having the path broken out that way. Maybe put it below the title?

I like how this result layout is coming together.

**Comment by jsnmoon** [comment]
> How about "Expanded" instead of "Engagement"?

> Let's also remove blanks, and make the text flow to the edge when they are removed. @folletto 

> I'd remove the domain bit, that's not useful and just adds length. @folletto

> I'd also go for a solution that crops it, instead of folding on multiple lines. An ellipsis would work. @folletto

> I like having the path broken out that way. Maybe put it below the title? @gibrown 

All of the above have been implemented:

Screen Shot 2020-06-24 at 11 20 40 AM

**Comment by folletto** [comment]
Ok, for me that's a good starting point 👍

**Review by gibrown — DISMISSED** [review]
There are a few bugs I came across:

Spaces in the search terms are showing as pluses (may be related to the new decode logic @bluefuton  put in?):

Screen Shot 2020-06-24 at 2 19 02 PM

The spacing when we end up falling back completely feels weird. Should we have some separators between items? (Maybe punt on this to a later PR)

Screen Shot 2020-06-24 at 2 20 47 PM

Not all images are getting aligned to the right (happens both with and without a sidebar in 2016 theme):

Screen Shot 2020-06-24 at 2 21 03 PM

Screen Shot 2020-06-24 at 2 21 15 PM

**Comment by bluefuton** [comment]
> Spaces in the search terms are showing as pluses (may be related to the new decode logic @bluefuton put in?):

Not guilty - that hasn't merged yet :)

**Comment by jsnmoon** [comment]
> Spaces in the search terms are showing as pluses (may be related to the new decode logic @bluefuton put in?)

This is tracked in #14750 and is fixed by #16243 (I think). Changes in this PR are unrelated to this logic.

> The spacing when we end up falling back completely feels weird. Should we have some separators between items? (Maybe punt on this to a later PR)

+1 for punting, this is why I was hesitant to remove the placeholders.

> Not all images are getting aligned to the right (happens both with and without a sidebar in 2016 theme)

Uh oh, I'll take a look.

**Review by gibrown — DISMISSED** [review]
LGTM. All working now

**Comment by rickalee** [comment]
Would it be possible for theme developers to register their own JSX templates for Results and include meta (price) in result?

**Comment by gibrown** [comment]
@rickalee moving this discussion over to https://github.com/Automattic/jetpack/issues/15666#issuecomment-650302175

Thanks for chiming in.

**Comment by folletto** [comment]
> +1 for punting, this is why I was hesitant to remove the placeholders.

You can keep min-height, the placeholder itself isn't needed ;)

**Comment by jsnmoon** [comment]
> You can keep min-height, the placeholder itself isn't needed ;) (@folletto)

D'oh, such an obvious fix... ✅

Screen Shot 2020-06-29 at 10 34 29 AM

**Review by jeherve — APPROVED** [review]
This is a nice improvement, and it works well in my tests! 🚢

**Pull request merged**
