### PR TITLE
My Jetpack: update My Jetpack dashboard headline

### PR DESCRIPTION
**Pull request by retrofox**
This PR updates the My Jetpack headling. Go to #23063 for more detail.

Fixes https://github.com/Automattic/jetpack/issues/23063

#### Changes proposed in this Pull Request:

* My Jetpack: update My Jetpack dashboard headline

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Go to My Jetpack
* Confirm the headline changes according to the images below

before | after
----|-----
image| image

### CODE REVIEW

**Comment by renatoagds** [comment]
There are some lint errors because of the version.

**Review by leogermani — DISMISSED** [review]
LGTM

**Review by leogermani — APPROVED** [review]

**Review by jeherve — APPROVED** [review]

**Review by keoshi — DISMISSED** [review]
Approving again!

**Review by oskosk — APPROVED** [review]

**Comment by sdixon194** [comment]
Cherry picked to jetpack release branch in af3ffad05e61291a3e210a0c7bbdc04e6976cbd9

Package updated in jetpack, boost, and backup release branches.

**Pull request merged**
