### PR TITLE
Jetpack Plugin: Fix dashboard backup link for Atomic sites

### LINKED ISSUE #26563: Jetpack Dashboard “View your site’s backups” Redirects to Jetpack Cloud on Atomic Sites
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to WordPress.com
2. Select your Atomic site in My Site(s)
3. Navigate to Jetpack > Dashboard
4. Click on **View your site’s backups**

### A clear and concise description of what you expected to happen.

I expect to be redirected to https://wordpress.com/backup/exampledomainname.com

### What actually happened

I'm redirected to Jetpack Cloud, which doesn't support Atomic sites:

https://jetpack.com/redirect/?source=my-jetpack-manage-backup&site=exampledomainname.com

### Browser

_No response_

### Other information

First reported: p1664559484886309-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

_No response_

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Navigate to My Site > Jetpack > Backups.

### PR DESCRIPTION
**Pull request by jwebbdev**
Fixes #26563

#### Changes proposed in this Pull Request:

* Adds an atomic check and uses the `calypso-backups` redirect instead of `my-jetpack-manage-backup` if the site is atomic

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No/

#### Testing instructions:

To test you'll need to utilize a WoA Dev site.
* Use Jetpack Beta or `jetpack rsync` after pulling and building the branch locally to install the plugin on your test site.
* Follow the instructions in https://github.com/Automattic/jetpack/issues/26563 and ensure the link now goes to the WordPress.com backups page for your site.

This checks specifically for WordPress.com on Atomic.  Ephemeral sites and Jurassic Ninja (and other test sites) should produce the `my-jetpack-manage-backup` redirect.  To test with these sites you'll need to manually add credentials before the link appears.

### CODE REVIEW

**Comment by jwebbdev** [comment]
Seems the check is coming back positive in JN tests, so looking more into it.

**Comment by oskosk** [comment]
I launched an ephemeral site, connected Jetpack, bought Backup, and it does not recognize my plan
image

**Comment by oskosk** [comment]
I rephrase. The plan is there, but I have to enter credentials and wait for the Backup to finish

image

**Comment by jwebbdev** [comment]
> I rephrase. The plan is there, but I have to enter credentials and wait for the Backup to finish

@oskosk I had to edit the test plan slightly as I changed from using isAtomicSite to isWoASite.  With that, Ephemeral will still have the old link, but they also work on Cloud, unlike WoA, so this seems correct.

**Review by kraftbj — APPROVED** [review]
Spun up a JN site. Confirmed cloud.jetpack.com destination.
Spun up a new WoA ev site. Confirmed production has cloud.jetpack.com incorrect dest.
Applied this branch via JP Beta. See new /redirect URL and confirmed it stays within WordPress.com.

**Pull request merged**
