### PR TITLE
Fixed several typos and grammar errors in docs

### PR DESCRIPTION
**Pull request by bitdaw**
#### Changes proposed in this Pull Request:
* No functional changes - just fixed some typos

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Only MD file changes, can perform a visual check

#### Does this pull request change what data or activity we track or use?
No

### CODE REVIEW

**Comment by bitdaw** [comment]
Updated original PR with requested info

**Comment by anomiex** [comment]
Hi! Why did you close the PR? It looks like useful fixes to me.

**Comment by bitdaw** [comment]
Hi! I started overthinking about the below stuff in my PR and thought maybe I was missing something or it sounded dumb, silly I know. I'll open a new PR with the same changes

Testing instructions:
Only MD file changes, can perform a visual check

**Comment by anomiex** [comment]
Those are perfectly reasonable testing instructions for doc changes IMO. 🙂

**Comment by bitdaw** [comment]
Thanks! Sometimes I just get a bit in my own head and worry too much, I thought maybe I was missing something and it's more complex, I'm still new to open source projects. I've submitted a new PR now 😃

**Pull request closed without merging**
