### PR TITLE
Jetpack components: Add ThemeProvider stories for typographies and colors

### PR DESCRIPTION
**Pull request by retrofox**
This PR Adds ThemeProvider stories for typographies and colors. Although the current story is useful, I think the instances feel kind of polluted with other elements. The goal here is trying to isolate the instances as much as possible.

Typographies | Colors
-----|------
image | image

Fixes #

#### Changes proposed in this Pull Request:

* Jetpack components: Add ThemeProvider stories for typographies and colors

#### Testing instructions:

* Use storybook
* Go to Typographies and Colors
* Confirm you see the instances
* Confirm you can edit the text instance for Typographies story

https://user-images.githubusercontent.com/77539/159784041-9068b095-8188-421b-8980-1b12f807ffe6.mov

### CODE REVIEW

**Comment by renatoagds** [comment]
I have a few points about this one @retrofox :

1) Colors is already available at Tokens story, it's not enough there? It already provides the same thing that we have at this new one.

2) I avoided to add the Typography examples at ThemeProvider because of Text component, IMO the examples should be there, since it is our interface for texts. The values available at ThemeProvider should be used only in internal cases IMO, aka RNA Components.

**Comment by retrofox** [comment]
> I have a few points about this one @retrofox :
> 
> 1. Colors is already available at Tokens story, it's not enough there? It already provides the same thing that we have at this new one.

> it's not enough there?

Maybe, yes.

> It already provides the same thing that we have at this new one.

Disagree. Let's compare again both stories:

Tokens | Colors
------|------
image | image

Do you really think is the same? I don't think so.

When you navigate the styles in the Tokens story, it gets confusing. Additional boxes, with the green dark color, etc, pollute what we'd like the see: The colors and their values. No more.

Do you really thing is the same?

> 2. I avoided to add the Typography examples at ThemeProvider because of Text component, IMO the examples should be there, since it is our interface for texts. 

What's the big deal providing a story to see the typography styles? Beyond that you can improve the `<Text />` one, it won't hurt anyway. I don't see why blocker honestly.

> The values available at ThemeProvider should be used only in internal cases IMO, aka RNA Components.

We don't do that now, and something that I don't expect to take as a rigid rule. It could ve highly possible that we want to use only a typography instead of a more complex component.

This story has the same purpose of the colors one. it's tricky to take a look, clearly, to the styles that the component provides:


Tokens | Typographies
------|------
image | image

**Comment by renatoagds** [comment]
> When you navigate the styles in the Tokens story, it gets confusing. Additional boxes, with the green dark color, etc, pollute what we'd like the see: The colors and their values. No more.

And why do not improve the token story instead creating a new one? Don't get the reason to duplicate instead improving.

> We don't do that now, and something that I don't expect to take as a rigid rule. It could ve highly possible that we want to use only a typography instead of a more complex component.

But this is exactly the work I'm doing, removing the directly usage of fonts in favor of Text component. And the purpose is to no have places using the variables directly, since there's no reason to do that. The component is not complex, is just a variant prop, and move us for the direction to not have places using different styles of texts.

Having a story showing how to apply the typography directly from
the variables, for me is an incentive to use it and push us to the opposite that we're trying to
achieve with components.

But this is my vision, based on the current work in top of RNA components.

**Comment by retrofox** [comment]
> > When you navigate the styles in the Tokens story, it gets confusing. Additional boxes, with the green dark color, etc, pollute what we'd like the see: The colors and their values. No more.

> And why do not improve the token story instead creating a new one? Don't get the reason to duplicate instead improving.

You can remove it the Tokens once in case you consider appropriate. The stories are different and have different goals.


> > We don't do that now, and something that I don't expect to take as a rigid rule. It could ve highly possible that we want to use only a typography instead of a more complex component.
> 
> But this is exactly the work I'm doing, removing the directly usage of fonts in favor of Text component. And the purpose is to no have places using the variables directly, since there's no reason to do that. The component is not complex, is just a variant prop, and move us for the direction to not have places using different styles of texts.
> 
> Having a story showing how to apply the typography directly from the variables, for me is an incentive to use it and push us to the opposite that we're trying to achieve with components.
> 
> But this is my vision, based on the current work in top of RNA components.

exactly.

**Comment by renatoagds** [comment]
@retrofox That's a failed action about the version, can you fix that? After that we can move forward and improve on the follow-up PRs 👍🏽

**Comment by retrofox** [comment]
> @retrofox That's a failed action about the version, can you fix that? After that we can move forward and improve on the follow-up PRs 👍🏽

https://github.com/Automattic/jetpack/pull/23582/commits/e5f067537713a301b83588b41fc63bdad86d36c3

**Review by renatoagds — DISMISSED** [review]
👍

**Review by oskosk — APPROVED** [review]

**Review by oskosk — APPROVED** [review]
double-tap

**Comment by retrofox** [comment]
> Great news! One last step: head over to your WordPress.com diff, D77427-code, and commit it. Once you've done so, come back to this PR and add a comment with your changeset ID.

r242543-wpcom

**Comment by anomiex** [comment]
Somehow D77427-code wound up not containing half the changes from this PR. Created D77677-code with the rest of them.

r242645-wpcom

**Pull request merged**
