### PR TITLE
Phpcs: Replace the requirelist with an excludelist

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

This replaces the list of files that are supposed to be clean in phpcs (`bin/phpcs-requirelist.js`) with a list of files that are known to not be clean in phpcs (`bin/phpcs-excludelist.txt`).

The end goal is to have all files being fully checked by phpcs. The progress towards that goal is easier to check when it's "no files are left in bin/phpcs-excludelist.txt" than when it's "all files are covered by bin/phpcs-requirelist.js", and it's easier to find work to do when that work is "clean up a file in excludelist" than "clean up a file that's not in requirelist".

This also makes things more straightforward when adding new files, as the default will now be to fully check the files rather than to not check them but have dangerfile.js try to complain about them.

It also avoids files accidentally falling out of the supposed-to-be-clean list if they're renamed and the requirelist isn't updated.

Plus, the existing requirelist is inaccurate: it claims everything in packages/ is required, but in practice packages/analyzer/ has never passed. This change itself won't do anything directly to prevent that sort of thing in the future, but cleaning it up is necessary if we want to start having CI run phpcs over the supposed-to-be-clean files (which is my next project).

#### Jetpack product discussion

None outside of some private Slack chats.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Check that `composer php:requirelist` shows no errors or warnings.

* If you really want, check that running phpcs on the files listed in `bin/phpcs-excludelist.txt` reports at least one warning or error in each one.

#### Proposed changelog entry for your changes:

* Developer only, none needed.

### CODE REVIEW

**Comment by anomiex** [comment]
Sticking the "Blocked/Hold" status to try to signal that this shouldn't be merged until the parent PR is merged. I'd still like review.

**Comment by kraftbj** [comment]
I'm seeing some fun returns:

```
FILE: /Users/kraft/code/jetpack/.git/logs/refs/heads/phpcs/class.photon.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
   |         | (Internal.NoCodeFound)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: /Users/kraft/code/jetpack/.git/logs/refs/remotes/origin/fix/module-headings.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
   |         | (Internal.NoCodeFound)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: /Users/kraft/code/jetpack/.git/refs/heads/phpcs/class.photon.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
   |         | (Internal.NoCodeFound)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

It's interesting to me that it is checking within the `.git` directory.

**Review by kraftbj — APPROVED** [review]

**Comment by anomiex** [comment]
Needs re-review after resolving a merge conflict.

**Review by jeherve — APPROVED** [review]

**Comment by anomiex** [comment]
I'm going to go ahead and merge this, forcing the wpcom check. D53326-code is currently passing, I don't know why this didn't update. And the resulting patch is just adding one comment in a not-in-sync file anyway, which I'm only bothering with to bring things slightly closer to being in sync, so I don't think it's very urgent to get that merged (@kraftbj or @jeherve, will you do that bit for me since I can't yet?)

**Comment by jeherve** [comment]
> I don't know why this didn't update.

It happens at times, although we haven't really looked into why this was still happening so far.

> the resulting patch is just adding one comment in a not-in-sync file anyway, which I'm only bothering with to bring things slightly closer to being in sync, so I don't think it's very urgent to get that merged

Done in r217523-wpcom

**Pull request merged**
