### PR TITLE
Add Jetpack icon to gutenberg features powered by Jetpack

### PR DESCRIPTION
**Pull request by gravityrail**
This change helps show the user which Gutenberg blocks are powered by Jetpack by putting a little Jetpack icon in the corner of the block's editor icon.

#### Changes proposed in this Pull Request:

* Add Jetpack icon in corner of blocks powered by Jetpack.

#### Testing instructions:

* Install Gutenberg
* Edit a post
* Open the "insert block" dialog
* Search for "VR"
* Should have a little green icon indicating it's a Jetpack feature :)

#### Screenshot

jetpack-gutenberg-icon

### CODE REVIEW

**Comment by gravityrail** [comment]
Related:

https://github.com/WordPress/gutenberg/pull/6636
https://github.com/WordPress/gutenberg/pull/6168

**Comment by jeffgolenski** [comment]
Jumping in for Michael while he's out. I think the concept here is great for reinforcing the brand, I just think we need to tighten up the logomark a bit here. It's almost indistinguishable at this size and doesn't resemble the real logomark much at all. 

Let me see if I can make some adjustments in a mockup, quickly! I'll get back to you @gravityrail  @oskosk

**Comment by gravityrail** [comment]
Thanks @jeffgolenski. You should know that the inserter style has changed since this patch was created, since we merged https://github.com/WordPress/gutenberg/pull/6636 in particular. It's worth building Gutenberg from Master to see the latest that will be coming out with 3.0.

**Comment by gravityrail** [comment]
cc @youknowriad @mtias

**Comment by mtias** [comment]
Also the ability to set a bg color on the block icon card is coming soon.

**Comment by keoshi** [comment]
@jeffgolenski Do you have an update on your mock? If not, @gravityrail I'd say let's stand down for now until the support for a custom background color comes through, as @mtias mentions. What are your thoughts, considering the discussing here too p6TEKc-23j-p2 ?

**Comment by keoshi** [comment]
FWIW, I think there's added value in labeling Jetpack features as `Jetpack: Feature Name`. It helps with discoverability, makes them searchable by Jetpack (as opposed to `Beautiful Math` alone), and creates a nice grouping for all of them.

**Comment by jeffgolenski** [comment]
@keoshi I do not. I never got a chance to get to it last week. Happy to stand down and defer to you for this moving forward. I like the idea about adding "Jetpack" for discoverability.

**Comment by brbrr** [comment]
Moving this into next release, since it looks like not ready yet.

@gravityrail are you still want this to be merged?

**Comment by jeffgolenski** [comment]
Just pinging @MichaelArestad since he's been thinking a bit about this

**Pull request closed without merging**
