### PR TITLE
Fix widget saving

### LINKED ISSUE #7570: Widget saving fails with Jetpack 5.2
#### Steps to reproduce the issue
On a site running Jetpack 5.2 add a widget from WP Admin or the Customizer (tested with a text widget and category widget), make a change to the widget such as adding a title, and click Save or allow auto-save to run. The changes will then disappear. This happens without error in WP Admin, but in the Customizer the error "Invalid value" is shown. The widget does appear to be added to the location it is set to, but no changes can be made to it besides location.

#### What I expected
Widgets settings to be saved properly.

#### What happened instead
Changes are lost on manual save (WP Admin) or auto save (Customizer).

WP Admin screencast:

screen capture on 2017-08-01 at 22-10-22

Customizer screenshot:

screen shot 2017-08-01 at 10 11 53 pm

### PR DESCRIPTION
**Pull request by roccotripaldi**
Fixes #7570 

In #7487, we tried to improve syncing of widgets for activity log, but manage to break instances where new widgets were added.

Team Poseidon will work on a better method for improving widget syncing.

To test:
Checkout this branch, and ensure you can add a new widget and save it's settings.

### CODE REVIEW

**Comment by DHWP** [comment]
Thanks, fixed my issue.

**Comment by lezama** [comment]
@roccotripaldi , @DHWP, I changed the fix so it doesn't break the intended behaviour.

Please let me know if it still tests 👍

**Comment by roccotripaldi** [comment]
Looks good and makes sense. Thanks @lezama 

@samhotchkiss - to add some clarity, the intended behavior of #7487 was to not sync a widget-edit event when adding a new widget.

After Miguel's commit, it is clearer to see what our mistake was. We should have returned something!

**Comment by eliorivero** [comment]
Cherry picked to 5.2.1 in 36cbcff44

**Pull request merged**
