### PR TITLE
Remove VR block

### PR DESCRIPTION
**Pull request by simison**
Stop accumulating code and features nobody uses.

#### Changes proposed in this Pull Request:
Remove source files for un-published VR block.

#### Testing instructions:
VR block is not available in the block picker even when `JETPACK_BETA_BLOCKS` is available.

### CODE REVIEW

**Review by sirreal — APPROVED** [review]
Code/functionality-wise 👍

**Comment by jeherve** [comment]
Couldn't we just ship it as is? 😢

**Comment by simison** [comment]
Here's an improvement PR to these files btw: https://github.com/Automattic/wp-calypso/pull/29398

**Comment by simison** [comment]
@jeherve I'd rather be strict about features we add. If this would've already not been done, would we work on it? If not, why would we then decide to maintain, document and support it?

**Comment by jeherve** [comment]
Good point. I suppose we can always bring the block back later if we decide to start working on it again.

**Review by jeherve — APPROVED** [review]

**Comment by simison** [comment]
PS. This could be suitable for core.

**Pull request merged**
