### PR TITLE
WPCOM Media: Add HEIC/HEIF image upload support

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/Automattic/wp-calypso/issues/55102

## Proposed changes:

Ports the existing WordPress.com HEIC/HEIF support to the `jetpack-mu-wpcom` package so it can be used on both Simple and Atomic sites.

This PR only impacts the Media Library upload experience. It doesn't affect images uploaded via the Block Editor.

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

Here's an image you can test with if needed: https://danielbachhuber.com/wp-content/uploads/2023/07/IMG_3634.heif_.zip

### Simple

1. Create a new Premium Simple site and sandbox it.
2. Apply D115429-code to your sandbox.
3. Navigate to `/wp-admin/upload.php` on your Simple site.
4. Attempt to upload a HEIC image and verify you seen an error.
5.  Inside of your sandbox, run `bin/jetpack-downloader test jetpack-mu-wpcom-plugin improve/jetpack-wpcom-heif-support`
6. Attempt to upload a HEIC image and verify it uploads as expected.

### Atomic

1. Create a new Business site, mark it as a WoA dev site, and take it Atomic.
2. Install the [Jetpack Beta Tester plugin](https://jetpack.com/download-jetpack-beta/) and add `define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true );` to your `wp-config.php` file.
3. Navigate to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack-mu-wpcom-plugin` to switch to the `improve/jetpack-wpcom-heif-support` branch.
4. Navigate to `/wp-admin/upload.php` on your Atomic site.
5. Attempt to upload a HEIC image and verify it uploads as expected.

### CODE REVIEW

**Comment by wojtekn** [comment]
@danielbachhuber in the simple site use, I could upload the HEIC file, and it was correctly saved as JPEG. However, the error was still displayed in `/wp-admin/upload.php` and `/wp-admin/media-new.php`. It looked like the error was added on the frontend side by the JS script. Should we update this part too?

> This image cannot be displayed in a web browser. For best results convert it to JPEG before uploading.

It worked for me for Atomic too, HEIC was saved as JPEG in both cases. However, I've got an error in `/wp-admin/media-new.php` and I haven't got it in `/wp-admin/upload.php`. 

I also tried uploading HEIC in the Calypso uploader, and on the Simple site HEIC was saved as JPEG, but on the Atomic site it wasn't. Is it expected?

**Comment by danielbachhuber** [comment]
> I also tried uploading HEIC in the Calypso uploader, and on the Simple site HEIC was saved as JPEG, but on the Atomic site it wasn't. Is it expected?

@wojtekn Did you have your WoA dev site connected to your sandbox, or was it connected to production?



> However, the error was still displayed in `/wp-admin/upload.php` and `/wp-admin/media-new.php`. It looked like the error was added on the frontend side by the JS script. Should we update this part too?

Can you share a screenshot of these errors?

**Comment by wojtekn** [comment]
> @wojtekn Did you have your WoA dev site connected to your sandbox, or was it connected to production?

No, I didn't. Should I create it in dev pool and add a constant to point it to the sandbox?

> Can you share a screenshot of these errors?

Sure, here you are:

Screenshot 2023-07-07 at 14 18 20

Screenshot 2023-07-07 at 14 18 44

**Comment by kozer** [comment]
Strange enough, I can't replicate the error message with a simple site ( didn't try Atomic yet )

What I did was:
- Sandboxed api
- Apply the diff mentioned
- Visited both `/upload.php` and `/media-new.php`. Here is what I see ( this is in `/media-new.php` )

no_errors_heif

Any ideas?

**Comment by wojtekn** [comment]
@kozer it looks like we display this error only for HEIC files, and you used HEIF for testing:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qvapyhqrf%2Swf%2Scyhcybnq%2Sunaqyref.wf%3Se%3Q55261613%23605-og

As far as I see, before this change, that error message made sense - we didn't block the HEIC upload, but we informed user that they won't see the preview in the browser. Now, when we automatically change HEIC to JPG, the image preview will be displayed in the browser, so message looks like not needed anymore.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/Automattic/jetpack/pull/32900

**Pull request closed without merging**
