### PR TITLE
Writing prompts: fix post meta not added when immediately publishing post

### PR DESCRIPTION
**Pull request by creativecoder**
Fixes issue raised when reviewing https://github.com/Automattic/jetpack/pull/29214#discussion_r1125784683

## Proposed changes:

Changes from using the `transition_post_status` hook to the `wp_after_insert_post` hook when adding the `_jetpack_blogging_prompt_key` post meta.

This ensures that tags included with the post on create/update through the REST API are actually added to the post before we check for them when adding the prompt post meta.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pe7F0s-uo-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Set up your wpcom sandbox for testing by applying the patch D102925-code and applying Jepack trunk to your sandbox with `bin/jetpack-downloader test jetpack trunk`.
- Set the JETPACK__SANDBOX_DOMAIN constant to your wpcom sandbox host, using a define statement on your development site, or Settings > Jetpack Constants on your jurassic.ninja site.
- Make sure your site is connected to WP.com (you will need to use local tunneling if using a local dev site PCYsg-GJ2-p2).
- Create a new post, insert a Writing Prompt block, add at least one more block, and immediately publish the post. Make sure you do not manually save a draft.
- Check to make sure the `_jetpack_blogging_prompt_key` post meta has been added with the prompt id.

### CODE REVIEW

**Review by roo2 — DISMISSED** [review]
LGTM!

**Review by jeherve — DISMISSED** [review]
Some other tests are failing, and they highlight some things that I think we should fix:

1. We'll need to add a fourth parameter here: https://github.com/Automattic/jetpack/blob/ba6503a9586a621a13f436c8aa8f791afbf70696/projects/plugins/jetpack/tests/php/sync/test_class.jetpack-sync-posts.php#L1306
2. We'll need to account for situations when `$post` isn't a regular `WP_Post` object.

I added 2 commits to try to address that. That should fix the tests and I'll approve this PR, but I'll let you take another look at my changes before you merge :)

**Comment by creativecoder** [comment]
Thanks @jeherve, this makes sense. I divided up the checks into separate conditionals because I think it's a little more readable (and merged in trunk). Should be good to go, now.

For my own benefit, are there known situations when $post is not an instance of `WP_Post` for this action?

**Comment by jeherve** [comment]
> For my own benefit, are there known situations when $post is not an instance of `WP_Post` for this action?

Since other plugins can overwrite that hook, we cannot really be 100% sure of the data in there. Our broken unit tests were a good example of that, since we define our own `wp_after_insert_post` in the tests, with a fake `$post`. I don't know of a real use-case, but better be safe than sorry I suppose :)

**Review by jeherve — APPROVED** [review]

**Pull request merged**
