### PR TITLE
Search: support search through multiple blogs

### LINKED ISSUE #26031: Search Enhancement: allow search through multiple blogs
### Impacted plugin

Search

### What

Add a filter to allow passing `additional_blog_ids` to search API

### How

More information: `panfyZ-pf#comment-1277-p2`

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #26031 

#### Changes proposed in this Pull Request:
The PR adds passing `additional_blog_ids` to the the search endpoint to support search through multiple blogs. The API support was added in `D74174-code`. And recently requested by @pablohoneyhoney in `p5uIfZ-cqA#comment-17850-p2`. The support is only for Instant Search.

Known issue: blog icon and blog name might be empty.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
`p5uIfZ-cqA#comment-17850-p2`
`panfyZ-pf-p2`

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Prepare a main blog A and an additional blog B, both have Instant Search turned on
* Go to your sandbox, allow search blog B from blog A with wpsh
* `switch_to_blog(A);`
* `update_option('jetpack_allowed_xsite_search_ids', [B]);` <- Ensure B is an integer
* Add the following snippet to blog A
```PHP
add_filter( 'jetpack_instant_search_options', function( $options ) {
	$options['additionalBlogIds'] = array( 189825737 );
	return $options;
} );
```
* Search on blog A
* Ensure results from blog B comes up too

### CODE REVIEW

**Comment by kangzj** [comment]
Hey @robfelty, when I was testing frontend support for multiple site, I found `blog_name` in fields is not returned from API even explicitly added in requests. Any idea? Thanks.

----UPDATE-----
Also in my tests, the value of `blog_icon_url` is always `https://s1.wp.com/i/void.gif`, which works for P2? 🤔

**Review by oskosk — DISMISSED** [review]
Tests great for me. Note that this PR needs an update on changelog files.

**Comment by oskosk** [comment]
Pushed dff3f1df34b30982801458e70cc3747a1de26dc1 with a rebase and 49b76d0c52981dc0a34da408a936cabd7b40840c  updating versions (Ran `tools/fixup-project-versions.sh`)

Sorry if I messed with any local changes. If you had local changes, standing on the `add/support-search-additional-blogs` branch, commit them and then run
```
git fetch origin && git rebase
```

This way your local commits will stay on top these two commits I just pushed as if nothing happened

**Comment by kangzj** [comment]
Hi @oskosk I've created an issue for the known problem, can i get a 👍 to merge it? - it doesn't affect any other functionality if not set to search thru multiple blogs which we didn't support before. Thanks.

https://github.com/Automattic/jetpack/issues/26077

**Review by oskosk — APPROVED** [review]

**Comment by robfelty** [comment]
Interesting - I tested `blog_icon_url` in the developer console and it worked for me. I did notice that `blog_name` is not currently stored though. I think the best way to fix that is to update the Elasticsearch mappings and re-index.

**Comment by robfelty** [comment]
I set `blog_name` to be stored in r252364-wpcom

It won't take effect until we re-index though. I'll keep you updated.

**Comment by robfelty** [comment]
We have deployed the change - I verified that `blog_name` is now also returned. Let me know if you continue to have issues.

**Comment by kangzj** [comment]
@robfelty I can confirm `blog_name` is returned now! Thanks 👍

**Pull request merged**
