### PR TITLE
Admin Page: don't show plugin cards when you can't install plugins

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

* Follow-up from #21866
* This adds a new check to see if one can install plugins. This is especially important, where an admin with the manage_options cap may not have the capability to install plugins. There, only superadmins have that capability.

#### Jetpack product discussion

* Internal reference: p8oabR-LV-p2#comment-5806

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Set up a Multisite network, where you create:
    * a new site
    * a new admin, with access to that site.
* Log in as the new admin, go to the Jetpack menu in that new site, and connect the site to your WordPress.com account.
* When you get back to wp-admin and the Jetpack menu, you should not see the card to install the Boost plugin at the bottom of the page.
* If you log back in as the superadmin, you should see the card.
* If you try with a single WordPress installation, you should see the card as an admin.

### CODE REVIEW

**Review by cbauerman — CHANGES_REQUESTED** [review]
It looks like Jetpack doesn't expose the individual `install_plugin` permission:

[_inc/lib/admin-pages/class-jetpack-redux-state-helper.php](https://github.com/Automattic/jetpack/blob/ddd62eca9e37e15c18f33188ee3dbee67c77ad33/projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php#L417 )
 ```
	$current_user_data = array(
		'isConnected' => $is_user_connected,
		'isMaster'    => $is_master_user,
		'username'    => $current_user->user_login,
		'id'          => $current_user->ID,
		'wpcomUser'   => $dotcom_data,
		'gravatar'    => get_avatar_url( $current_user->ID, 64, 'mm', '', array( 'force_display' => true ) ),
		'permissions' => array(
			'admin_page'         => current_user_can( 'jetpack_admin_page' ),
			'connect'            => current_user_can( 'jetpack_connect' ),
			'connect_user'       => current_user_can( 'jetpack_connect_user' ),
			'disconnect'         => current_user_can( 'jetpack_disconnect' ),
			'manage_modules'     => current_user_can( 'jetpack_manage_modules' ),
			'network_admin'      => current_user_can( 'jetpack_network_admin_page' ),
			'network_sites_page' => current_user_can( 'jetpack_network_sites_page' ),
			'edit_posts'         => current_user_can( 'edit_posts' ),
			'publish_posts'      => current_user_can( 'publish_posts' ),
			'manage_options'     => current_user_can( 'manage_options' ),
			'view_stats'         => current_user_can( 'view_stats' ),
			'manage_plugins'     => current_user_can( 'install_plugins' )
									&& current_user_can( 'activate_plugins' )
									&& current_user_can( 'update_plugins' )
									&& current_user_can( 'delete_plugins' ),
		),
```

so `userCanInstallPlugins` will never be true. In my testing, I saw the Boost card suppressed everywhere.

**Comment by jeherve** [comment]
Ah good point, thank you! I just pushed 5c75d68519b32b6f8b6ceccad98e26302f72eb28, that may simplify things a bit.

**Review by cbauerman — APPROVED** [review]

**Review by samiff — APPROVED** [review]
Was able to install Boost from the card on a subsite (subdomain).

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-10.5` in ba964eb1dff95019d42161f0a717b0aee89bef8d

**Pull request merged**
