### PR TITLE
VideoPress: Add endpoint to serve featured stats for My Jetpack

### PR DESCRIPTION
**Pull request by lhkowalski**
Relates to #29753.

Blocks #29764.

## Proposed changes:

* Added `videopress/v1/stats/featured` endpoint to provide featured stats that will be used on My Jetpack
* The following data is being provided:
   * views for the last 7 days and the 7 days before it
   * impressions for the last 7 days and the 7 days before it
   * watch time for the last 7 days and the 7 days before it

This will be enough for the first iteration of the My Jetpack VideoPress card enhancement and will set the basic structure for adding more feature stats on the next iterations.

The idea of providing this from the VideoPress package is to keep the specific logic and calculations inside the package, and just to basic consumption of it from the My Jetpack frontend.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Make sure to test on a site that has some videos and that will have views or impressions; if you don't have one, just upload a couple of videos, add them to some post and play the videos some times
* Go to some page on the `wp-admin` of your site, open the browser console and run the following snippet:

```
wp.apiFetch({ path: "/videopress/v1/stats/featured" })
  .then((data) => console.log(data));
```

* This will do a request to the endpoint and print the data on the console
* The expected response is similar to this:

```
{
    "label": "last 7 days",
    "data": {
        "views": {
            "current": 4,
            "previous": 3
        },
        "impressions": {
            "current": 8,
            "previous": 11
        },
        "watch_time": {
            "current": 0.013888888888888888,
            "previous": 0.005555555555555556
        }
    }
}
```

The response contains the label for the kind of metric we are returning (may be useful on the frontend) as well as the value for the three basic metrics for the current and the previous period (7 days window).

### CODE REVIEW

**Review by retrofox — COMMENTED** [review]
Just a comment about the namespace and its availability in dotcom. `videopress/v1` is supported yet and probably won't be in the short term. That's why we've added some endpoints to `wpcom/v2/videopress`, for instance.

In case we think these endpoints will also be helpful in dotcom.

**Review by retrofox — APPROVED** [review]
LGTM. Tested and it works as expected.
QQ and just in case: have we confirmed [this](https://github.com/Automattic/jetpack/blob/f2ad389d4773d653c12f82ba8ba173b3ee3a9832/projects/packages/videopress/src/class-videopress-rest-api-v1-stats.php#L64)?

**Review by renatoagds — APPROVED** [review]
LGTM. Works as expected

**Comment by lhkowalski** [comment]
> Just a comment about the namespace and its availability in dotcom. videopress/v1 is supported yet and probably won't be in the short term. That's why we've added some endpoints to wpcom/v2/videopress, for instance.

@retrofox I considered the dotcom availability, and seems like we don't have visible plans for using the stats there for now. 

I see these featured stats being used on the "My Jetpack" page (the motivation for the PR) and also on the VideoPress dashboard. 

Both screens are not available right now for dotcom users, and the only one that we considered adding in the future is the VideoPress dashboard, but we don't have plans for it yet. 

I think we are safe for now using this namespace, but changing it to `wpcom/v2/videopress` to be future-proof is a matter of moving code around now. What do you think?

> have we confirmed [the user capability necessary for requesting the data]?

No, we don't. This is a piece of code that we didn't touch for a good time.

Considering the capability required for seeing the "My Jetpack" screen and the "VideoPress dashboard" (the places where we may use the data), we could change the check from `read` to `manage_options`. Makes sense to you?

**Pull request merged**
