### PR TITLE
Remove old Fly Panel for showing in some scenarios

### PR DESCRIPTION
**Pull request by lupus2k**
Fixes https://github.com/Automattic/dotcom-forge/issues/6809

## Proposed changes:
Old fly panel was showing when clicking on WP & Profile in the masterbar when Jetpack is enabled but SSO is disabled.

> [!IMPORTANT]
> This PR should be merged after this diff (D151708-code) is merged since it remove the function of the Fly panel and this PR removes content.

Before:

https://github.com/Automattic/jetpack/assets/402286/2dfef4ca-c5c4-48b0-86c8-965669b33007

After:

https://github.com/Automattic/jetpack/assets/402286/60421d0e-1f73-4780-9682-74495f4b5f75

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Apply this diff: D151708-code
* Sandbox `s0.wp.com`
* Disable SSO in Jetpack Settings
* Click on W logo
* It should link to `My Home` at WPcom
* Click on the profile picture
* It should show a fly panel with the Profile & Logout link
* Check if anything is broken on self-hosted sites
* Check if everything works in mobile (Menu open, logout, profile link)
* Check if anything is broken with SSO enabled
* Check if anything is broken with Classic interface is enabled (wp-admin)

### CODE REVIEW

**Comment by jeherve** [comment]
I should note that we last attempted to remove those panels, we had to revert as it was breaking navigation in some scenarios:

#12454
p9Jlb4-R8-p2

Our work on nav-unification may have solved that potential problem on WoA sites, but it may be important to test this change on other self-hosted WordPress sites as well, to ensure we're not removing important options for site owners.

**Comment by lupus2k** [comment]
Thanks for the info @jeherve

**Comment by lupus2k** [comment]
I updated the PR, fixing some broken scenarios (like mobile or missing log-out). I also created this diff (D151708-code) with some extra details.

Btw, one test is failing on Github but I can't make it fail locally :thinking: 

cc @jeherve

**Comment by jeherve** [comment]
> one test is failing on Github but I can't make it fail locally

You'll need to update your PR to latest `trunk`, that problem should disappear. For more info: #37785

**Comment by okmttdhr** [comment]
>Old fly panel was showing when clicking on WP & Profile in the masterbar when Jetpack is enabled but SSO is disabled.

Firstly, I could reproduce the issue: https://github.com/Automattic/dotcom-forge/issues/6809 on the Atomic Default site only but not on Atomic Classic. 

I applied this patch and observed the fly panel is displayed but without content;

| before | after |
|--------|--------|
| Screenshot 2024-06-12 at 12 50 43 |Screenshot 2024-06-12 at 12 50 57 | 

badge
Are these things expected, or am I missing something?

**Comment by okmttdhr** [comment]
> Old fly panel was showing when clicking on WP & Profile in the masterbar when Jetpack is enabled but SSO is disabled.

First, I reproduced the issue described in https://github.com/Automattic/dotcom-forge/issues/6809 on the Atomic Default site but not on Atomic Classic.

After applying the patch, I observed that the issue was resolved ✅.

FWIW, I noticed different behavior on Atomic Classic, which seems appropriate given the differences between Calypso and wp-admin:

- The menu is displayed when hovering over the W icon.
- Clicking the W icon will redirect you to /wp-admin/about.php.

Screenshot 2024-06-12 at 13 09 00

I think this PR need more eyes for;

>Check if anything is broken on self-hosted sites
Check if everything works in mobile (Menu open, logout, profile link)
Check if anything is broken with SSO enabled
Check if anything is broken with Classic interface is enabled (wp-admin)

**Comment by lupus2k** [comment]
> FWIW, I noticed different behavior on Atomic Classic, which seems appropriate given the differences between Calypso and wp-admin:

As I understand, we maintain the behavior of non-classic sites.
cc @jeherve @davemart-in

**Comment by davemart-in** [comment]
I'm not sure I have a strong opinion one way or the other on this one. I could go either way.

**Review by DustyReagan — DISMISSED** [review]

**Review by candy02058912 — DISMISSED** [review]
I'm seeing the old Fly Planel from Default sites only. After applying the patch it is fixed.

Also tested with self-hosted sites to make sure nothing is outright broken.

**Review by allilevine — DISMISSED** [review]
I tested with the diff and PR and SSO enabled and disabled, Default and Classic View, self-hosted. I also tested logging out with SSO disabled on Atomic. ✅

**Review by jeherve — DISMISSED** [review]
This looks good to me on self-hosted. The current UX in Jetpack latest stable isn't great, and this doesn't really make it worse, so I'd say let's go with it (after a rebase)

**Comment by davemart-in** [comment]
So excited to finally have this gone! :-)

**Review by DustyReagan — APPROVED** [review]

**Pull request merged**
