### PR TITLE
Connection: offline mode for 127.0.0.1 and proper error messages

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:
* Add 127.0.0.1 into the list of known offline domain names to force offline mode upon it
* Display proper connection error message if trying to connect with a known local domain name

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
1. Load your monorepo site via `127.0.0.1`. Confirm Jetpack is in Offline Mode.
2. Comment out `127.0.0.1` [in the Status package](https://github.com/Automattic/jetpack/blob/0871825b0bad8f45ca966135e73855c1fc6bde85/projects/packages/status/src/class-status.php#L186).
3. Go to the Connection Screen and try connecting. You should see the error message: _"Your site host is on a private network. Jetpack can only connect to public sites."_

### CODE REVIEW

**Review by chrisbliss18 — COMMENTED** [review]
I can confirm that running the PR code shows that the site is in offline mode when trying to connect. However, when I comment out `127.0.0.1` from `projects/packages/status/src/class-status.php` and I try to connect, I do not get the error message as shown in the testing instructions. Instead, after clicking the "Connect you user account" button, I get a generic `An error occurred. Please try again.` error message as shown in the screenshot:

connection-error

**Comment by bindlegirl** [comment]
Just checked it, and found the same error as Chris did. I see the response contains correct error code and message though: IP address `127.0.0.1` just failed is_usable_domain check as it is in the private network.

**Comment by sergeymitr** [comment]
Hi @chrisbliss18, @bindlegirl
I forgot to mention that you need to rebuild Jetpack as JS component was changed.
My bad, sorry about that.

**Review by bindlegirl — DISMISSED** [review]
Works as described

**Comment by bindlegirl** [comment]
> Hi @chrisbliss18, @bindlegirl I forgot to mention that you need to rebuild Jetpack as JS component was changed. My bad, sorry about that.

I used jetpack watch but that wasn't enough. Rebuilding solved it. Thanks!

**Comment by sergeymitr** [comment]
@bindlegirl can you please re-approve it as I had to merge trunk into this branch.

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
