### PR TITLE
Jetpack Signature: Check both 80 and 443

### PR DESCRIPTION
**Pull request by kraftbj**
Previously, Jetpack used is_ssl() to determine if the port used as part of the signature verification process would be either 80 or 443 (or the corresponding constant values).

With the rise of CloudFlare SSL, Let's Encrypt, etc and the way that HTTPS sites operate when they terminate SSL on the edge (reverse proxy, load balancer, etc), there is an increase of situations where a site is SSL but the server port is 80.

This situation currently always fails and requires user intervention: either overriding the $_SERVER global or setting a PHP constant.

This change will not pass the port number if it is either 80 or 443 while still allowing the constants to be set, to retain BC.

cc: @mdawaffe this is the issue I was asking about in Belize. Can you check out this approach and offer any suggestions.

pitcrew: Do not merge unless Mike gives a green light :).

### CODE REVIEW

**Comment by mdawaffe** [comment]
The `JETPACK_SIGNATURE__HTTPS_PORT`/`JETPACK_SIGNATURE__HTTP_PORT` constants were created to fix the proxy problem, but it was never a very good fix.  The approach in this PR is better, though I'd rather see us hardcode `80` (for HTTP) and `443` (for HTTPS) than depend solely on the two constants (which people will change because they are confusing).

There's another problem with Jetpack's current code.  If there is a port-changing proxy, Jetpack cannot be run on a non-standard port.  This must be a very rare configuration, because I don't think we've ever had a bug report :)

The following diff deprecates the constants and instead encourages use of the `X-Forwarded-Port` header (which Cloudflare does not support :().

It'd be nice if we knew what the edge cases were: the code is getting a bit complicated.

```diff
diff --git a/class.jetpack-signature.php b/class.jetpack-signature.php
index a63636a..8502e6a 100644
--- a/class.jetpack-signature.php
+++ b/class.jetpack-signature.php
@@ -1,5 +1,8 @@
 <?php
 
+// These constants can be set in wp-config.php to ensure sites behind proxies will still work.
+// Setting these constants, though, is *not* the preferred method. It's better to configure
+// the proxy to send the X-Forwarded-Port header.
 defined( 'JETPACK_SIGNATURE__HTTP_PORT'  ) or define( 'JETPACK_SIGNATURE__HTTP_PORT' , 80  );
 defined( 'JETPACK_SIGNATURE__HTTPS_PORT' ) or define( 'JETPACK_SIGNATURE__HTTPS_PORT', 443 );
 
@@ -31,10 +34,26 @@ class Jetpack_Signature {
 			}
 		}
 
+		$host_port = isset( $_SERVER['HTTP_X_FORWARDED_PORT'] ) ? $_SERVER['HTTP_X_FORWARDED_PORT'] : $_SERVER['SERVER_PORT'];
+
 		if ( is_ssl() ) {
-			$port = JETPACK_SIGNATURE__HTTPS_PORT == $_SERVER['SERVER_PORT'] ? '' : $_SERVER['SERVER_PORT'];
+			// 443: Standard Port
+			// 80: Assume we're behind a proxy without X-Forwarded-Port. Hardcoding "80" here means most sites
+			//     with SSL termination proxies (self-served, Cloudflare, etc.) don't need to fiddle with
+			//     the JETPACK_SIGNATURE__HTTPS_PORT constant. The code also implies we can't talk to a
+			//     site at https://example.com:80/ (which would be a strange configuration).
+			// JETPACK_SIGNATURE__HTTPS_PORT: Set this constant in wp-config.php to the backend webserver's port
+			//                                if the site is behind a proxy running on port 443 without
+			//                                X-Forwarded-Port and the backend's port is *not* 80. It's better,
+			//                                though, to configure the proxy to send X-Forwarded-Port.
+			$port = in_array( $host_port, array( 443, 80, JETPACK_SIGNATURE__HTTPS_PORT ) ) ? '' : $host_port;
 		} else {
-			$port = JETPACK_SIGNATURE__HTTP_PORT  == $_SERVER['SERVER_PORT'] ? '' : $_SERVER['SERVER_PORT'];
+			// 80: Standard Port
+			// JETPACK_SIGNATURE__HTTPS_PORT: Set this constant in wp-config.php to the backend webserver's port
+			//                                if the site is behind a proxy running on port 80 without
+			//                                X-Forwarded-Port. It's better, though, to configure the proxy to
+			//                                send X-Forwarded-Port.
+			$port = in_array( $host_port, array( 80, JETPACK_SIGNATURE__HTTP_PORT ) ) ? '' : $host_port;
 		}
 
 		$url = "{$scheme}://{$_SERVER['HTTP_HOST']}:{$port}" . stripslashes( $_SERVER['REQUEST_URI'] );
```

**Comment by kraftbj** [comment]
> It'd be nice if we knew what the edge cases were: the code is getting a bit complicated.

The only typical one we see is https running on port 80, usually with load balancers/Varnish or some other kind of reverse proxy with SSL termination. I've seen one edge case in the wild of someone needing the constant was a person testing out WordPress on Nginx running on port 90 while not disrupting with their Apache site on 80 who needed to set the constant.

**Comment by kraftbj** [comment]
@mdawaffe I finally got back around to this. I applied your patch (and committed it under your name to give you due credit and a more accurate `blame` in the future). Does this approach still sound good to use?

**Comment by mdawaffe** [comment]
Still sounds good to me. If I recall correctly, I did zero testing.

That may be why it still sound good ;)

**Comment by kraftbj** [comment]
This would fix #779.

**Comment by kraftbj** [comment]
Needs Review/Testing :-)

**Comment by lezama** [comment]
> cc: @lezama -- you were assigned to 779.

Perfect!

Thanks for working on this, lgtm!

**Comment by jeherve** [comment]
This seems to work well in my tests. Merging.

**Pull request merged**
