### PR TITLE
My Jetpack: Product Card adjustments

### LINKED ISSUE #29904: My Jetpack: Product card adjustments
At the new Design Iteration, some adjustments were provided to push the layout close to the previous one with a menu and space for stats.

Image

Together with these adjustments from design, we're going to provide some improvements in menu visibility that will fit in the current focus on Jetpack excellence: p1HpG7-ly0-p2#comment-62015

Based on this iteration, we should update the current Product Card to:

- [x] Move the label to the right.
- [x] Show description or children, and keep the action button if it has children.
- [x] Remove menu only in `absent` or `absent_with_plan` status.

### PR DESCRIPTION
**Pull request by renatoagds**
Closes #29904 

## Proposed changes:

* Improve Product Card story.
* Move label back to right side.
* Replace description with children if applicable.
* Disable menu only if is in `plugin_absent` or `plugin_absent_with_plan` status.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1HpG7-ly0-p2#comment-61985
p1HpG7-ly0-p2#comment-61966

## Does this pull request change what data or activity we track or use?

N/A

## Testing instructions:

* Start `Storbook`
* Navigate to `My Jetpack/Components/Product Card` story.
* See `Default` story and interact with `status` in `Controls` tab.
* See `With Children` story and interact with `status` in `Controls` tab.
* See `With Menu` story and interact with `status` in `Controls` tab.
* It should reflect new proposed design.

## Demo

| Default | With Children | With Menu |
|--------|---------------|------------|
| CleanShot 2023-04-10 at 15 15 28 | CleanShot 2023-04-10 at 15 16 16 | CleanShot 2023-04-10 at 15 16 40

### CODE REVIEW

**Comment by lhkowalski** [comment]
Tested the default version and it's working as expected.

---

Tested the version with children element and it seems to work as expected. Noticed two things:

- The children element will be shown only when the status is `active`; is this the expected behavior? Seems correct to me, just want to confirm
- There is some slightly difference in the height of the card when it contains a children vs. the default textual label; we will probably need to fix this height to some default value to make sure all the cards stay aligned (but I think it will probably depends on what max height we will set to the children element)

---

Tested the version with menu and it is working as expected. Noticed that:

- we show the menu on the `error` status but maybe we should not, unless the actions are related to fixing the issue or can still work properly even on error; makes sense?

**Review by lhkowalski — DISMISSED** [review]
Nice work! Left some comments, but they are all related to fine-tunning the component as we move forward.

**Comment by renatoagds** [comment]
> The children element will be shown only when the status is active; is this the expected behavior? Seems correct to me, just want to confirm

Yes, this is the expected behavior for now.

> There is some slightly difference in the height of the card when it contains a children vs. the default textual label; we will probably need to fix this height to some default value to make sure all the cards stay aligned (but I think it will probably depends on what max height we will set to the children element)

This will happen only in Storybook, is because we won't have this element replacement when we go live, since it will render directly with the children, and the font size will be the correct one too.

> we show the menu on the error status but maybe we should not, unless the actions are related to fixing the issue or can still work properly even on error; makes sense?

Yes, we could improve this, for sure. And remove it in cases it makes no sense.

**Review by lhkowalski — APPROVED** [review]
Nice catch on the tests.

**Pull request merged**
