### PR TITLE
Jetpack Sync: Add key for full sync actions

### PR DESCRIPTION
**Pull request by darssen**
Fixes https://github.com/Automattic/vulcan/issues/616

## Proposed changes:

When processing items in WPCOM, we use an **action key** to check if the action has already been processed.

So far, all actions have used a **stringified timestamp as the key**. In addition, WPCOM has a safeguard to prevent the same action from being processed repeatedly. For example, if an action fails and isn't processed, if the action comes again in a short interval WPCOM marks it as "processed" and skips it. This ensures that the sync on the remote site can continue.

This works as expected in Incremental Sync, where the key is stored in the queue. If an action isn’t processed during Incremental Sync, it’s retried using the exact same key. The problem happens during **full syncs**. In full syncs, since there is no queue, the action keys are regenerated each time. 

The changes add a **specific key for full sync actions**. Which is the `full_sync_action_name` concatenated to a hash of `last_sent` item in the scenarios where multiple actions are sent per module.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Instructions in the Vulcan ticket since it involves checking processed actions in a sandbox.

### CODE REVIEW

**Review by fgiannar — CHANGES_REQUESTED** [review]
Thanks for working on this, Juanma!

Left some initial thoughts/issues in the linked issue with the testing instructions.

**Comment by darssen** [comment]
Thanks for reviewing @fgiannar!  Created https://github.com/Automattic/jetpack/pull/40566/commits/530bdd6aa7f6c31b98a547dbe713e66cdd56e461 to tackle the concerns.

**Comment by fgiannar** [comment]
Great work, Juanma! Tests well in general, however I'm concerned about full sync actions that come with solely the action name as key: `jetpack_full_sync_options`, `jetpack_full_sync_callables`, `jetpack_full_sync_constants`, `jetpack_full_sync_updates`.
In case 2 Full Syncs are triggered within 5 minutes (eg in cases where the later cancels the first one), we wouldn't be processing those the second time. What do you think?

**Comment by darssen** [comment]
> Great work, Juanma! Tests well in general, however I'm concerned about full sync actions that come with solely the action name as key: `jetpack_full_sync_options`, `jetpack_full_sync_callables`, `jetpack_full_sync_constants`, `jetpack_full_sync_updates`. In case 2 Full Syncs are triggered within 5 minutes (eg in cases where the later cancels the first one), we wouldn't be processing those the second time. What do you think?

That's a good question. On one hand, we shouldn't be sending multiple full syncs within 5 minutes, but if we end up in one of the run conditions regarding different plugins activation, maybe we do. 
We can always send no specific key for these modules so a timestamp will be sent. Would that be a preferred solution?

**Comment by fgiannar** [comment]
> We can always send no specific key for these modules so a timestamp will be sent. Would that be a preferred solution?

I think so, yeah. Though there's a chance of huge remote options causing OOMs I believe this is a very rare edge case.
On the other hand, it's not very rare to have two Full Sync's happening within 5 minutes, especially if the first one is a partial (eg user connecting their account) followed by a Full Sync of all content (1 minute after the site is registered).

**Comment by darssen** [comment]
> > We can always send no specific key for these modules so a timestamp will be sent. Would that be a preferred solution?
> 
> I think so, yeah. Though there's a chance of huge remote options causing OOMs I believe this is a very rare edge case. On the other hand, it's not very rare to have two Full Sync's happening within 5 minutes, especially if the first one is a partial (eg user connecting their account) followed by a Full Sync of all content (1 minute after the site is registered).

Reverted changes in these modules via [e09c4b4](https://github.com/Automattic/jetpack/pull/40566/commits/e09c4b4ca41b68b6c32eba6fa93214a2af6d428e)

**Review by fgiannar — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
