### PR TITLE
Jetpack Gutenberg: fix beta extension availability

### PR DESCRIPTION
**Pull request by roccotripaldi**
Fixes an issue that popped up when reviewing https://github.com/Automattic/wp-calypso/pull/29744, where the beta extension always showed up as unavailable.

#### Changes proposed in this Pull Request:

Beta extensions should always be available unless we've explicitly marked them as unavailable.

For example, the SEO gutenberg plugin is currently in beta, yet it appears as unavailable on the latest master of Jetpack, even when `JETPACK_BETA_BLOCKS` constant is `true`.

#### Testing instructions:

1. Get this branch running locally with docker
2. Set-up Jetpack and activate features
4. `define( 'JETPACK_BETA_BLOCKS', true );`
3. Start a new post
5. You should be able to add an SEO description in the Jetpack publishing panel

#### Proposed changelog entry for your changes:

* none

### CODE REVIEW

**Comment by ockham** [comment]
Hmm, do we need this? We have client side logic that does pretty much this -- defaults to 'available' for beta blocks. The idea was that as long as the block isn't explicitly mentioned by the availabilty endpoint, that fallback would kick in...

**Comment by roccotripaldi** [comment]
> Hmm, do we need this?

It looks like we do. Try running the SEO plugin on the latest master with the beta constant set.
Can you use the SEO description?

**Comment by sirreal** [comment]
@codebykat mentioned that #11709 (beta) was working well. Can we confirm this is a reproducible issue?

**Comment by simison** [comment]
I haven't familiarized myself with this yet but noting that SEO description specifically doesn't have PHP side block registration yet (pending https://github.com/Automattic/jetpack/pull/11659).

Hence it shows up as this in console log (it's in the build bundle already):

Screenshot 2019-03-26 at 21 42 51

**Comment by ockham** [comment]
I think with the blocks code moved to the JP repo, the original motivation for the client side fallback (make block available if not mentioned in endpoint, to avoid filing/merging a PR against a separate repo) no longer stands, so we can probably rip out a bunch of code both on the client and server to simplify things.

**Comment by simison** [comment]
> so we can probably rip out a bunch of code both on the client and server to simplify things.

@ockham how would you word out that as a task/issue? Which things specifically?

**Comment by sirreal** [comment]
> how would you word out that as a task/issue? Which things specifically?

This comes to mind, there may be more:

https://github.com/Automattic/jetpack/blob/303908fd5bd351a787fd5cfccc002c2d3d5ff86d/class.jetpack-gutenberg.php#L321-L324

**Comment by simison** [comment]
Opened an issue to keep track: https://github.com/Automattic/jetpack/issues/11738

Feel free to edit description to better capture the task.

**Pull request closed without merging**
