### PR TITLE
Move Salesforce lead form to production

### PR DESCRIPTION
**Pull request by CGastrell**
#### Changes proposed in this Pull Request:
Make Salesforce Lead form available in production

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Edit a post and add a form. You should see the Salesforce Lead form available on the variation picker without the need to enable beta blocks

### CODE REVIEW

**Review by digitalwaveride — CHANGES_REQUESTED** [review]
Nice Christian!

Two little things:

- Regarding the placement of the beta area:

image

It should be below the link "Where to find the Organ..." as that link needs to be close to the input field.

- The beta badge:

Just noticed, that there is a tiny little difference regarding font-styling, padding and border radius compared to the beta badge of the VideoPress block (screenshot below on the left).
Could we adjust that to the VP styling? 🙏  That would be awesome!

image

**Comment by CGastrell** [comment]
Thanks for catching those @digitalwaveride 

I adjusted the styles and compensated spaces to move the badge further down:
image

**Review by digitalwaveride — APPROVED** [review]
Awesome Christian! 🚀 

The Salesforce template appears and beta integration in the inspector sidebar shows as advertised! 👍

**Review by bindlegirl — APPROVED** [review]
LGTM

**Pull request merged**
