### PR TITLE
Connection: lock tokens to prevent IDC during AIOWPM export

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:
* Activate Token Lock for [AIOWPM](https://wordpress.org/plugins/all-in-one-wp-migration/) export to prevent IDC's

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
p9dueE-4Ly-p2
1204904295387809-as-1204812389918149

## Does this pull request change what data or activity we track or use?
No.

## Testing instructions:
_Easier to test in JN, you'll need two sites._

1. Switch both sites to the branch, connect Jetpack, install All-in-One-WP-Migration plugin.
2. Run DB export in the AIOWPM plugin
3. Open the exported file in a text editor, find `jetpack_private_options` and confirm that `token_lock` is in there.
4. Import the file on the second site using AIOWPM. You'll probably need to re-login into wp-admin, use the password from the first site (import file origin) as the user has been overwritten. If Jetpack got deactivated, reactivate it.
5. Confirm that Jetpack on the second site got disconnected, and the one on original site is still connected.

### CODE REVIEW

**Comment by bindlegirl** [comment]
@sergeymitr, something about this PR breaks AIOWPM export for me. I tried JN and a separate standalone Jetpack site. On a JN site, I just get an `Unable to export` notice; on that separate site, I get an `Invalid Archive Path` error, which seems weird. 

I tried exporting using Jetpack's latest release and the bleading edge, and both work fine. Can you reproduce this problem?

In console, I see some 500-type errors:
```
XHRPOST
https://testongreen.com/wp-admin/admin-ajax.php?action=ai1wm_export&ai1wm_import=1
[HTTP/3 500 Internal Server Error 343ms]
```

**Comment by sergeymitr** [comment]
Thanks for taking a look @bindlegirl.
I somehow missed the issue. Fixed now, please give it another look.

**Review by bindlegirl — DISMISSED** [review]
Tested importing & exporting. No IDC in sight 👍

**Comment by sergeymitr** [comment]
Hi @bindlegirl.
Thanks for the review!
Can you please re-approve it as I had to merge `trunk` into the branch.

**Review by bindlegirl — APPROVED** [review]

**Pull request merged**
