### PR TITLE
Blocks: Add a new shared Button component

### PR DESCRIPTION
**Pull request by Copons**
See #14935

Proposal for a new shared `Button` with:
- `ButtonEdit` component to be used in the `edit` part of a block.
- `ButtonSave` component to be used in the `save` part of a block.
- `getButtonEditProps` utility to only pass the relevant block's props to `ButtonEdit`.
- `getButtonAttributes` utility to add all the `Button` attributes to the block's attributes definition.
- `jetpack_get_button_classes` utility to get all the `Button` classes for SSR.
- `jetpack_get_button_styles` utility to get all the `Button` styles for SSR.

### The Background

Many Jetpack blocks use buttons and would love to have all the Core `Button` block niceties (colors, border radius, gradients, styles, etc.), but there's no straightforward way to reuse the Core `Button`.
- Core `Button` does not export `ButtonEdit` and `ButtonSave`.
- Core `Button` is in fact a link that looks like a button, and have an UI to set the `url` attribute.
- Core `Button` is a standalone block, so its attributes refer to itself (e.g. `backgroundColor` can only be the button's background color), while in our blocks the `Button` is often just part of a block (is `backgroundColor` the button's background color, or the whole block's?).
- Jetpack blocks use Buttons in many different ways: some server-side render it; some save it in the post content; some need an ID or extra attributes; they can be `a`, `button`, `input` elements; they can have an `onClick` handler; etc.

There are many possible solutions for each of this issues, but as far as I can see (and I might very well be wrong!) the Core `Button` would not fill _all_ our needs, and even if it did, the Jetpack minimum compatibility would mean not being able to use new Core changes for months.

For these reasons, we tried re-implementing the Core `Button` block in-house, and then we did it again, and again.
As far as I can see, we have (at least?) 3 different implementation of a button component, and no actual standard.

The `Button` component proposed is meant to be a catch-all solution, as close as possible to Core's `Button` block, but also extendable for any of our niche needs and easy enough to use as a drop-in replacement of our current implementations.

### The Ideas

1. Start from today's Core `Button`, so to have all of its most recent features.

2. Instead of straight-up copy-pasting from Core, restructure the code in smaller files, that should be more manageable and easier to keep up to date with Core changes.

3. Make the attribute naming consistent: all `Button` attributes must start with `button` (e.g. `buttonBackgroundColor`), with the sole exception of custom color attributes, that are supposed to be prepended with `custom` (e.g. `customButtonBackgroundColor`).

4. Create a handful of utilities that would drastically decrease code duplication, and promote consistency.

### Other Examples

#14931

---

#### Changes proposed in this Pull Request:

* Create a new `Button` component, complete with helpers for all common use cases, to replace the several different re-implementation of Core's `Button` block.
* Use the new `Button` component in the `Revue` block.

#### Testing instructions:

* Before applying this PR, create a new post with several Revue blocks.
  * One with named colors and gradients
  * One with custom colors.
  * One with modified button text and labels.
* Save the post!
* Apply this PR and reload the post.
* Make sure all the Revue blocks look as expected in both editor and front end.
* Add another Revue block from scratch, and try all the various button settings.
* Make sure they work as expected in both editor and front end.

#### Proposed changelog entry for your changes:

N/A

### CODE REVIEW

**Comment by glendaviesnz** [comment]
have given this a quick test, and the only thing I have noticed so far is that when the patch is applied the styles don't appear correctly on the front end until the post is re-saved, ie.

On current master:
Screen Shot 2020-03-30 at 2 26 51 PM

After patch applied:
Screen Shot 2020-03-30 at 2 27 51 PM

But once post is resaved the styles show correctly again on frontend - something to do with the block deprecation settings I am picking, which I don't know much about so about to read up on!

**Comment by Copons** [comment]
Great catch @glendaviesnz! I totally forgot to check the migration in the PHP side.

In 3522cc1 I've added another utility function inspired (as always!) by @retrofox work in Core: https://github.com/WordPress/gutenberg/blob/58e4c3c3014130b3afde936d2c6b61518d7ded46/packages/block-library/src/navigation/index.php#L139-L154

Basically it converts deprecated attributes into their valid corresponding ones (unless they are already set).
The mapping array already handles both the Revue attributes, and those from SubmitButton.

**Comment by glendaviesnz** [comment]
Have retested and this all works as advertised now with the frontend deprecation code in place. 

This seems like a reasonably sound approach to me, but I wasn't involved at all in any of the block button issues that led up to this, so will leave it to @pablinos & @scruffian to make a call on whether this is a good way forward as I think they where more involved in the previous button discussions.

**Comment by Copons** [comment]
Replaced by #15370

**Pull request closed without merging**
