### PR TITLE
Prompts to set up Boost after plugin activation

### LINKED ISSUE #20524: Connection prompt for Jetpack Boost?
#### Is your feature request related to a problem? Please describe.

I activated Jetpack Boost on Jurassic.Ninja and was expecting to be prompted to connect it using a JITM or dashboard widget, but didn't see anything like that.

#### Describe the solution you'd like
Prompt to connect after activating Boost.

### PR DESCRIPTION
**Pull request by mikestottuk**
Fixes #20524

NOTE: This isn't **_quite_** there yet. We need to disable the banner once Boost is set up, @thingalon the Q is under what circumstances do we call Boost "set up'? 

1. They've visited the page (if so, adding an option on activation, deleting it on visit of the boost page is the way to go IMO).
2. They've successfully generated critical CSS, if this is our measure of setup we can add this in (assuming we have a function which tells us)

This only shows on the `plugins.php` page and in theory, the current "Settings" link may well be good enough, this just adds a bit more fuel to the fire.

Screenshot 2022-10-19 at 19 39 01

#### Changes proposed in this Pull Request:
Adds a connection prompt for Boost. This is shown on admin. We can condition it to not show when Boost is set up BUT what would we say is a successfully set up Boost. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
-[ ] Install Jetpack Boost 
-[ ] Activate and review the set up prompt

### CODE REVIEW

**Comment by thingalon** [comment]
> NOTE: This isn't quite there yet. We need to disable the banner once Boost is set up, @thingalon the Q is under what circumstances do we call Boost "set up'?
>
> 1. They've visited the page (if so, adding an option on activation, deleting it on visit of the boost page is the way to go IMO).
> 2. They've successfully generated critical CSS, if this is our measure of setup we can add this in (assuming we have a function which tells us)

Ooh this is a very good question. IMHO we should show the banner until they are _both_ connected to jetpack, and have visited the dashboard.

That way, if they go to the dashboard and don't connect (and don't already have a Jetpack connection), we will remind them to go back and get setup.

However, once they've gone there and started the process, we won't keep bugging them.

After that, we can check on our success rates, and see if we need to iterate :)

**Comment by thingalon** [comment]
I know this isn't done yet, but two questions to consider:

1. Is this reusing CSS that is defined elsewhere in Jetpack / Boost, which we could import via a `<link` tag to save us from duplicating the CSS? 
2. Don't output any CSS if we're not showing the banner. :)

One final point: I know today is the last day before your parternity leave. If you don't get this finished, I can take over on Monday. :) I can also make sure that whatever work needs doing after review, gets taken care of.

**Comment by thingalon** [comment]
Added to sprint 1 to ensure we pick this up and roll with it soon.

**Comment by haqadn** [comment]
Could enabling a module be the threshold of setting up boost?

**Review by thingalon — CHANGES_REQUESTED** [review]
I've committed a couple of minor tidy-ups (renaming the file `Setup_Promp` -> `Setup_Prompt`, using the `jb_setup_banner_dismissed` flag the way the name implies instead of inverted). But there seems to be a bug: 


https://user-images.githubusercontent.com/1369626/198919930-7f9c3ce5-2da9-4e29-aaaf-6c1ae9cdc703.mov

If you:
- Activate Boost, get started for free.. then
- Deactivate Boost, reactivate boost, and get started for free again

It gets stuck on "getting started" / showing the banner. Check out the attached video. :)

**Comment by haqadn** [comment]
> I've committed a couple of minor tidy-ups (renaming the file `Setup_Promp` -> `Setup_Prompt`, using the `jb_setup_banner_dismissed` flag the way the name implies instead of inverted). But there seems to be a bug:
> 
>  Screen.Recording.2022-10-31.at.1.37.16.pm.mov 
> If you:
> 
> * Activate Boost, get started for free.. then
> * Deactivate Boost, reactivate boost, and get started for free again
> 
> It gets stuck on "getting started" / showing the banner. Check out the attached video. :)

Thanks for the video. I have pushed a fix. But, I have introduced a new hook. Let me know if you think this approach is ok [fa13547](https://github.com/Automattic/jetpack/pull/26934/commits/fa13547dacaeb5cffb02ebbfa8022eeb984408e4)

**Review by thingalon — DISMISSED** [review]
This approach looks ok to me :)

**Review by thingalon — APPROVED** [review]

**Pull request merged**
