### PR TITLE
Revert "Make is_development_mode() value "static""

### PR DESCRIPTION
**Pull request by eliorivero**
Reverts Automattic/jetpack#3635

We will reintroduce it soon, or a modified version that does the same, but right now we need to move on.

### CODE REVIEW

**Comment by dereksmart** [comment]
cc @rosswintle FYI this needs more attention than we have time for this release.

**Comment by dereksmart** [comment]
merged into branch-4.5 as well 9451ca1be98d9da59180eac5113f3fafeb33b94a

**Comment by rosswintle** [comment]
OK. Well, I'm slightly baffled about what's happened here. But keep me posted.

Thanks

**Comment by eliorivero** [comment]
Hi @rosswintle, thanks for the contribution. Here's an explanation about this decision:
since the `Jetpack::is_development_mode` was relying on a static variable, it was no longer possible to alter its result with the constant or the filter. In WP, functions or class methods where a filter is involved are expected to be filterable at any point during the execution.

This is why for example, the WP core function `plugins_url` doesn't use a static variable similar to the one you introduced in the PR, but instead it proceeds with the function execution and applies the filter `plugins_url` at the end.

We'll have to solve the original issue somehow, but it's likely that it won't be altering the functioning of `Jetpack::is_development_mode`.

**Comment by rosswintle** [comment]
Thanks for the explanation. The solution may just be RTFM, because it does say: "You can also enable Jetpack’s development mode through a **plugin**, thanks to the jetpack_development_mode filter:"

I was hoping there was a quick, technical solution, but perhaps not. I'll leave it with you guys.

Thanks again

**Pull request merged**
