### PR TITLE
Search: Add clear search button and polish surrounding visuals

### LINKED ISSUE #18879: Jetpack Search: modal close button could be ambigious (could be interpreted as 'clear input')
#### Steps to reproduce the issue

1. Open a search modal on a site with Instant Search enabled.

#### What I expected
It's possible to close the search modal, or to clear the search input.

#### What happened instead
The 'X' closes the modal, but may be interpreted as a 'clear search input' button.

Screen Shot 2021-02-19 at 15 05 53

This came up as feedback after @jeffgolenski's excellent presentation at the Jetpack Design Share.

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #18879.

#### Changes proposed in this Pull Request:
* Adds a `clear` button adjacent to the search input area.
* Adds a visible border between the search input area and the close overlay button.
* Refactors the DOM hierarchy for SearchResults, dark theme styles.

> Screen Shot 2021-03-02 at 1 09 45 PM
> Screen Shot 2021-03-02 at 12 59 43 PM

#### Jetpack product discussion
See #18879.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your site with a Jetpack Search subscription.
* Perform a site search. Ensure that the overlay appears with the new `clear` button adjacent to the search input.
* Click the `clear` button. Ensure that it clears the search input.

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

**Comment by bluefuton** [comment]
In some themes (e.g. Twenty Nineteen), the hover state for the button renders the text hard to read:

Screen Shot 2021-03-03 at 13 46 54

Should we override the hover state for the clear button?

**Comment by bluefuton** [comment]
Unfortunately something we've changed in this PR does seem to break modal display in IE11.

Before:

Screen Shot 2021-03-03 at 14 01 08

After:

Screen Shot 2021-03-03 at 13 58 35

**Review by bluefuton — DISMISSED** [review]
Let's fix the hover state and IE11 display issues.

**Comment by jsnmoon** [comment]
IE11 appears to work without issues on my end:

Screen Shot 2021-03-03 at 3 40 57 PM

**Comment by bluefuton** [comment]
The removal of `<main>` seems to have sorted IE11 / Twenty Nineteen out 👍

One last thing: can we add a clearer focus style to the 'clear' button (an outline) for keyboard navigation?

(Sidenote: discovered the keyboard navigation order is a bit odd - input > clear > search > sort relevance > sort newest > sort oldest > close modal > results. Will raise a separate issue.)

**Review by bluefuton — APPROVED** [review]
Looks good! Thanks for adding the focus style. 🚢

**Review by jeherve — APPROVED** [review]
This tests well for me.

**Pull request merged**
