### PR TITLE
Donations: Process payment after choosing an amount

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/44108

#### Changes proposed in this Pull Request:

Connect the donations block with the existing memberships functionality, so once a visitor chooses a donation amount and click on the donate button we display the subscribe dialog to process the payment.

Aug-10-2020 15-24-17

#### Jetpack product discussion
pbMlHh-dW-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Set up a test site:
  * [Create a JN site running this branch](https://jurassic.ninja/create/?jetpack-beta&branch=update/donations-show-payment-dialog). 
  * Go to `/wp-admin/options-general.php?page=companion_settings`.
    * Activate `JETPACK_BETA_BLOCKS`. 
    * Set `JETPACK__SANDBOX_DOMAIN` with your sandbox address (make sure you enter the short URL e.g. mysandbox.wordpress.com to avoid issues with the SSL certificate).
  * Sandbox the API, the store and `subscribe.wordpress.com` (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
  * Set up Jetpack and purchase a Premium or Professional plan.
* Go to Posts > New and insert a new Donations block.
* Set up the Stripe connection (you will be able to see a link above the form letting you to skip and instantly create a test account).
* Go back to the editor and modify the donations block at your pleasure, then publish.
* View the post on the front-end.
* Make sure the "Donate" button of the current tab is disabled by default.
* Make sure you can choose any of the prefixed amounts and the "Donate" button is enabled after that.
* Switch to a different tab.
* Make sure there is no amount selected by default after switching (and therefore the "Donate" button should've been disabled).
* Enter a custom amount.
* Make sure the "Donate" button is enabled only when entering a valid amount.
* Try multiple combinations and make sure they all behave as expected.
* After choosing a prefixed amount / entering a valid custom amount, click on the "Donate" button.
* Make sure a dialog for processing the payment shows up.
* Verify the dialog displays the interval and amount you selected. If you entered a custom amount, it should be still editable in the dialog.
* Complete the payment process and make sure it finishes successfully.

#### Proposed changelog entry for your changes:
No.

### CODE REVIEW

**Comment by leogermani** [comment]
Just noting that I started reviewing this today but had some trouble setting up the environment. Asking for help from the team and will be back on this  tomorrow

**Comment by sixhours** [comment]
I went through the above flow and tested it out; all appears to be working as intended! Great work @mmtr !

**Comment by leogermani** [comment]
hey @mmtr ,

Thanks for the support on getting this up and running for my tests.

Everything worked great, here are the few things I noticed:

* There's no way to select the "Custom value" option without modifying its value. Say you entered a value, then switched. tabs, went back to the tab where you were and want to select the custom value again. You can't unless you type in something.

* Another small thing, less critical in my opinion, is that while the page is loading, we can see the block. badly formatted (as. the screenshot below). Sometimes it's very fast, sometimes it takes a while:

Captura de Tela 2020-08-11 às 12 10 21

* On a mobile view the number can look a bit truncated

Captura de Tela 2020-08-11 às 12 20 42

* Testing it along with the Gutenberg plugin, the currencies selectbox looks a bit broken:

Captura de Tela 2020-08-11 às 12 29 41


Everything else worked as expected in the testing instructions. I tested with a logged in user and with an anonymous visitor and everything looked good.

**Comment by sixhours** [comment]
Tiny thing I just noticed this during the demo, but in the payment dialog just above the button, it says "By clicking Pay $20.00 / month ..." and I believe it should say "By clicking Donate $20.00 / month ...".

**Comment by mmtr** [comment]
Thanks for your reviews @leogermani and @sixhours!
> There's no way to select the "Custom value" option without modifying its value. Say you entered a value, then switched tabs, went back to the tab where you were and want to select the custom value again. You can't unless you type in something.

Should've been fixed in 9e3428a. The custom amount is selected now when focusing the input.

Aug-12-2020 14-39-12

> Another small thing, less critical in my opinion, is that while the page is loading, we can see the block badly formatted (as the screenshot below). Sometimes it's very fast, sometimes it takes a while:

Tried to improve this in 7233b11  by showing a spinner until the `domReady` callback is executed:

Screen Shot 2020-08-12 at 14 35 44


Note that there are a few ms where all content is still displayed since the page needs to load the block styles, but I don't think we can do any better than this.
 
> On a mobile view the numbers can look a bit truncated

Will look into it! I guess we can move each to amount to its own line.

> Testing it along with the Gutenberg plugin, the currencies select box looks a bit broken:

Will look into this as well, stay tuned 🙂 

> Tiny thing I just noticed this during the demo, but in the payment dialog, just above the button, it says "By clicking Pay $20.00 / month ..." and I believe it should say "By clicking Donate $20.00 / month ...".

This needs to be fixed separately (the dialog code lives in WP.com) so I opened a new issue: https://github.com/Automattic/wp-calypso/issues/44866

**Comment by mmtr** [comment]
> On a mobile view the numbers can look a bit truncated
>
> Testing it along with the Gutenberg plugin, the currencies select box looks a bit broken:

Both have been addressed in latest commits.

Screen Shot 2020-08-12 at 16 02 53

Screen Shot 2020-08-12 at 16 07 12

**Comment by mmtr** [comment]
> When entering an amount lower than the minimum amount defined in the predefined amounts, you get no warnings but when you open the payments popup the payment is not for the good amount:

I think you actually tested with an amount that is higher than the minimum. For EUR, the [minimum is 0.5€](https://github.com/Automattic/jetpack/blob/c95e5fdb82110b54cb5e18b89b1558e37caead50/extensions/shared/currencies.js#L18) and you entered 3€ which is higher.

However, the payment dialog doesn't have a good amount validation right now, and it checks against a hardcoded value of 5 regardless the currency. This is tracked in 129-gh-dotcom-manage and should be addressed by D48094-code.

> If I enter a custom amount with decimals, such as 55.5, the decimal is removed in the popup, and I end up paying 555.

It works for me, but I need to enter the decimals in the format expected by `@automattic/format-currency` for the selected currency.

For USD, decimals should be entered with `.`:

https://github.com/Automattic/wp-calypso/blob/b338e1464bde7aa0e9c31be551d25b0d33572af7/packages/format-currency/src/currencies.js#L875

Aug-14-2020 12-11-39


On the other hand, EUR use `,`:

https://github.com/Automattic/wp-calypso/blob/b338e1464bde7aa0e9c31be551d25b0d33572af7/packages/format-currency/src/currencies.js#L269

Aug-14-2020 12-13-24


Handling amounts is hard when we support multiple locales and currencies, so I decided to stick with what's defined in `@automattic/format-currency` which is what we use as well for displaying formatted amounts.

**Comment by jeherve** [comment]
Ok, that makes sense. In this case, this should be good to merge 👍

**Pull request merged**
