### PR TITLE
Recommendations: update button in My Plan to go to Recommendations

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

In #12277 and #12429, we added a "checklist" component to the Jetpack dashboard, as well as a CTA that would lead you to the checklist in Calypso.
We never really expanded on that checklist and its display in the React dashboard, but we now have a Recommendations component we use in Jetpack, since #18437.

This commit removes the elements from the checklist that we never used, and updates the CTA link in "My Plan" to point to the new Recommendations, when those recommendations must be shown to site owners.

#### Jetpack product discussion

* p1HpG7-asW-p2
* p1HpG7-bcl-p2#comment-44627

#### Does this pull request change what data or activity we track or use?

This PR introduces a new Tracks event that will be triggered when clicking on the button. It respects the same rules as the existing Tracks events on that page.

#### Testing instructions:

I would recommend testing this with an Atomic site as well as a Jetpack site.

* Go to Jetpack > Dashboard > My Plan on a site that's connected to WordPress.com
    * If the site is Atomic, you should not see any button
 
Screenshot 2021-02-16 at 17 09 53

    * If the site is a Jetpack site, you should see this button

Screenshot 2021-02-16 at 17 09 34

* Clicking on the button should lead you to the Recommendations tab.
* Nothing else should be broken in the dashboard.

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

**Comment by sdixon194** [comment]
This tests well for me! Going to hold off on approval until someone a bit more familiar with React can take a gander, but everything works as expected for me. 👍

**Review by leogermani — DISMISSED** [review]
Tested following the instructions on an Atomic site and on a Jetpack site. All worked as expected and I saw no errors.

I'm not a React expert either but the code changes look good. Always feel good to remove old code :) 

Well done

**Comment by jeherve** [comment]
I had to commit again to fix a linting warning. I would appreciate another review on this :)

Thank you!

**Review by sdixon194 — APPROVED** [review]
Still works!

**Pull request merged**
