### PR TITLE
Jetpack Connect URL: use correct URL to auto-approve

### LINKED ISSUE #8783: Connection: Giving Incorrect Error about Site Connected to Another Account when Connection Fails
I've noticed this a few times recently so I think it's something that we should look into. Several users have contacted us when seeing this error:

> "This site is already connected to a different WordPress.com user, you need to disconnect that user before you can connect another."

But when checking the connection, the site was connected but is actually not currently connected at all. For example:

Debug: https://jetpack.com/support/debug/?url=http%3A%2F%2Fwww.colerainesurestart.org.uk%2F
Internal ref: 753945-hc

It was connected originally on 2014/11/25 but hadn't updated with us since 2017/12/13. The site was connected to the user that is contacting us.

Seems like something's not right with the broken connection and the error message that we're sending when they try to reconnect.

Delete and reinstall has fixed each site experiencing this problem. 

Other examples: 
1745309-hc (Site: breakmytoys.com )

585295-hc (Site: annabellesattic.net )

1745646-hc (seerssee.com)

753945-hc (www.e-makul.com)

moved from 1697-gh-jpop-issues

### PR DESCRIPTION
**Pull request by roccotripaldi**
`already_authorized` is a connection URL param that lets a connecting customer know they've already connected the site.

`auth_approved` is a connection URL param that let's a connecting customer skip
the screen that shows the terms-of-service-acceptance button.

In #8544 we meant to use `auth_approved`

Fixes #8783 

To reproduce:

On an unconnected jetpack site, try connecting from the banner on the plugins page. Not that you get an odd "Already connected..." error when you land on wordpress.com

Then apply this patch to your jetpack site, and try again from the banner on the plugins page. You will not see the error, and you should skip the terms-of-service-acceptence and be auto authorized.

### CODE REVIEW

**Comment by oskosk** [comment]
Couldn't reproduce this the first times... And then I found a way to reproduce which is:
1. On a fresh site. Click the banner "Set Up Jetpack" button. 
2. When arriving the first calypso screen, go back with the browser.
3. Click the Set Up Jetpack button again.
4. Expect to see the "already connected..." notice.


Then tested with this PR and didn't see that ^ behaviour.
But I don't see any approval screen being skipped as result of  this other parameter either. I get to see this same screen regardless of the URL if I click the button.

**Comment by oskosk** [comment]
I now got to see the step skipped after trying multiple times and going back and forward...

The only thing that made it work, was switching branches on Jetpack Beta from this branch to Bleeding Edge and back. After that, clicking the Setup Jetpack button I got to skip the authorize screen...
Then, disconnected again, clicked the banner button again (with this PR's changes) and got presented with the authorize screen. So looks like the feature is working randomly.

**Comment by sirreal** [comment]
I spent some time tracking down _why_ this only happens before connection has been attempted.

Here's the short version:

The connection banner naïvely adds a query arg to the `build_connection_url`:

https://github.com/Automattic/jetpack/blob/b33be108f23999273c4e8be22e5aeaba981b9e86/class.jetpack-connection-banner.php#L82-L87

The URL may be WP Admin, which is required to get a `client_id` before going through the connection, but if the `client_id` is already known it will directly point to `jetpack.wordpress.com`:

https://github.com/Automattic/jetpack/blob/b33be108f23999273c4e8be22e5aeaba981b9e86/class.jetpack.php#L4428-L4432

That's why you must hit the endpoint at WP Admin once before this bug manifests.

The WP Admin endpoint silently discards unknown params and rebuilds the connection URL for redirection. Ideally this param would be part of `build_connect_url`.

I've pushed a commit to maintain the param through the WP Admin redirection (a017ea1b2d1f48b6e07b12d9e63bc2c8d100e6fd)

See p1519119812000072-slack-luna

**Comment by oskosk** [comment]
> I do think that the logic should be moved into build_connect_url.

@tyxla what do you think about it? Something similar happened with the onboarding param, but in this case it was problematic when the logic was inside build_connect_url() and we ended up pulling it out.

**Comment by tyxla** [comment]
@oskosk it was problematic because we were adding some extra parameters every time the user has an onboarding token. That's not the case here, so it looks safe from that point of view 👍 

I'd only be hesitant to introduce it to `build_connect_url` just because it's used in so many places, and we'd need to test a lot more cases before making sure it doesn't break anything else.

So, if we decide to move it to `build_connect_url`, let's make sure to test all places where it's called  thoroughly and in an organized manner.

**Pull request merged**
