### PR TITLE
Settings UI: move Connections to dashboard.

### LINKED ISSUE #6222: Settings: Move connection information to dashboard
We currently have a "General" tab in the Settings:

screen shot 2017-01-27 at 4 07 05 pm

Those 2 cards should be moved to the bottom of the Dashboard (with the heading "Connection") and the "General" tab should be removed completely from Settings.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6222 

#### Changes proposed in this Pull Request:
- Connection cards were moved to the bottom of At a Glance
- General tab is now removed
- Updated NavigationSettings GUI tests.
- added GUI tests for `DashConnections`.

#### Testing instructions:
* test in connected and dev mode and make sure the Connections cards work properly.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
If you switch them to be `DashItem` components, you can probably remove a bunch of those positioning styles.

**Comment by eliorivero** [comment]
Updated to use `DashItem`.

**Comment by beaulebens** [comment]
Looking pretty good, but 2 things;

1. I got an error in my console (this was on a site in DEV mode), see screenshot below.
2. Can we use the Mystery Man default for the Gravatar, so that we're not getting some random retro-generated avatar.

screen shot 2017-02-03 at 3 41 10 pm

screen shot 2017-02-03 at 3 42 42 pm

**Comment by beaulebens** [comment]
Would look like this with the `?d=mm` for the Gravatar. Unless we have/want a better default?

screen shot 2017-02-03 at 3 43 31 pm

**Comment by beaulebens** [comment]
For some reason, my head is squashed :)

screen shot 2017-02-03 at 3 47 34 pm

**Comment by beaulebens** [comment]
And I don't know if it's related to this specific PR, but when I click the Manage Connection link, and get the dialog, I think there's an unbalanced `div` or something, because the entire UI (see in the background/shaded part) jumps to the left:

screen shot 2017-02-03 at 3 48 25 pm

**Comment by beaulebens** [comment]
Opening that modal also triggers a JS error:

`Warning: Modal.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.`

**Comment by beaulebens** [comment]
As a non-Admin (in this case, an Editor) I can't see the connection cards at all. I should probably be able to see my own Account Connection card at least, right? Maybe both?

screen shot 2017-02-03 at 3 57 02 pm

**Comment by eliorivero** [comment]
Thanks for the review!

Updates:
- always use mystery man
- solve JS warning
- fix user avatar dimensions
- visible for non-admin users

The issue where the body jumps towards left [was fixed](https://github.com/Automattic/dops-components/pull/79) and is in latest dops master. You might need to do a `yarn build` or a `npm up` (in jetpack directory).

For the warning logged when the modal is launched, I've opened a issue in dops:
https://github.com/Automattic/dops-components/issues/85

**Comment by beaulebens** [comment]
Looking/working much better now!

I have 3 more questions, but they might be better handled in different PRs:

1. Since we're showing the Site Icon for the site there on the site connection side, should we have a link or something to Customizer so that you can change that icon?
2. Same question for Gravatar?
3. On the Account connection side, it felt a little bit weird that there's no way to change/manage that connection. Since we're presenting them separately like this, they feel like very separate concepts (like I should be able to connect the site on the one hand, and my user account on the other/separately). Should we have some "Manage Account" option over there? Do we need it? What would that look like/how would it work?

What you've got on this PR looks good to merge for now though, and we can discuss/look at these questions elsewhere.

**Comment by MichaelArestad** [comment]
> Since we're showing the Site Icon for the site there on the site connection side, should we have a link or something to Customizer so that you can change that icon? Same question for Gravatar?

Maybe in another PR, but definitely not needed for this.

> On the Account connection side, it felt a little bit weird that there's no way to change/manage that connection. Since we're presenting them separately like this, they feel like very separate concepts (like I should be able to connect the site on the one hand, and my user account on the other/separately). Should we have some "Manage Account" option over there? Do we need it? What would that look like/how would it work?

There is. Just not for site owners.

**Comment by MichaelArestad** [comment]
@beaulebens tested and confirmed 3 

image

image

**Comment by MichaelArestad** [comment]
@eliorivero Visually, this looks good. Once reviewed by someone else, should be good to go!

**Comment by MichaelArestad** [comment]
Note: I'll probably be tweaking the styles a little bit next week in another PR.

**Pull request merged**
