### PR TITLE
Handle the new markup of the Gutenberg Gallery blocks.

### LINKED ISSUE #10246: Carousel: support Gutenberg Gallery block
When using Core's Gallery block, Jetpack's Carousel can be triggered but there are no links between the images in the gallery:

>  It seems in Gutenberg 3.9 the Carousel is triggered when clicking on an image in the current Gutenberg Gallery Block, provided one selects "Attachment page" under "Link to" parameter. However, the Carousel doesn't have any next/previous navigation. http://recordit.co/41vNUeUrE5

Related: #8527

Originally reported by @bph

### PR DESCRIPTION
**Pull request by georgestephanis**
No biggie just needed to handle the new markup and process

Fixes #10246 

#### Testing instructions:

* Make a Guten Gallery.
* Do it?
* It do.

#### Proposed changelog entry for your changes:

* No changelog needed.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
It do! Nice work! 🚢

**Comment by dereksmart** [comment]
Was able to create a Guten Gallery and carousel seemed to work as expected. @georgestephanis Can you please take care of the Fusion diff? D20950-code

**Comment by jeherve** [comment]
Cherry-picked to `branch-6.8` in 2efbbbc21ae0b84e5428979b5bcc27fd1ddf1916

**Comment by MichaelArestad** [comment]
Thanks for fixing this up @georgestephanis

**Pull request merged**
