### PR TITLE
Update minimum pnpm version

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Picking up a few useful changes in this update:
* v7.20 brings a native implementation of `pnpm config`, which will be needed when our docker container gets updated to node 18.14.
* v7.24 brings an improved lockfile format, and the end of mystery hashes in the lockfile and virtual store.
  * v7.26.3 brings a fix to that for storybook.
* v7.26.0 brings `pnpm dedupe`, which seems likely to be useful for renovate.

This PR changes the lockfile to a new format! If you have merge conflicts after this is merged, the best thing to do is likely to `git checkout origin/trunk pnpm-lock.yaml && pnpm install` to regenerate it instead of trying to resolve the conflicts by hand.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Is everything happy?

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Tests seem happy

**Comment by artpi** [comment]
My builds. broke overnight.

In order to continue having jetpack build I have to 
```
pnpm i -g pnpm@7.27.0
```

Because the recommended
```
pnpm i -g 
```

installs 7.28.0 and that does not work.

Why do we keep requiring specific global versions of the toolchain?
I have the same problem with composer and php8 which I cannot run at that global version on my machine.

**Comment by anomiex** [comment]
We don't do anything to require 7.27.0 over 7.28.0. More likely is that some change in 7.28.0 results in changes to the lockfile, meaning we'd have random lockfile changes depending on whether each update happened to use 7.27 or 7.28, and our CI caught that.

**Comment by anomiex** [comment]
Doesn't seem to even be that, when I try using 7.28.0 everything seems fine. :shrug:

**Pull request merged**
