### PR TITLE
Tiled Gallery Block: Fix block crashing on high volume gallery (> 50 images).

### LINKED ISSUE #25017: Tiled Gallery block: The Editor has encountered an unexpected error in Bigger Galleries
### Steps to reproduce the behavior

1. Add a Tiled Gallery Block 
2. Add a big number of images, at least 50* images
3. Click the block's pencil icon in the floating toolbar to modify the images 
3. Modify one of the images by selecting a different image from the media library

You will see 

The Editor has encountered an unexpected error /Attempt Recovery Copy Post Text, Copy Error 
Screen Shot 2021-02-21 at 15 08 15

* I haven't been able to pinpoint the exact number where it breaks. For the customer in 3758951-zen , their gallery has 48 images and it already breaks when trying to modify it. In my test site, I had to add 52 images, so I guess it also depends on the images sizes. 

#### What I expected to happen

To be able to modify one of the images

#### What actually happened

The editor breaks 

#### Current Workaround

Create a separate Tiled Gallery block.

### PR DESCRIPTION
**Pull request by yansern**
Fixes https://github.com/Automattic/jetpack/issues/25017 https://github.com/Automattic/wp-calypso/issues/60335 

#### Changes proposed in this Pull Request:
Fixes the Tiled Gallery Block crashing when user updates a high volume gallery (> 50 images), e.g. adding images, remove images or simplying updating without changing anything.

**Why did it break?**
React throws a "maximum call stack depth" error.  This is because of excessive calls to `this.props.setAttributes` causing unnecessary re-rendering.

**How was it fixed?**
Add additional checks to ensure `this.props.setAttributes` is only called when necessary.

#### Jetpack product discussion
Maintenance work.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

**How to replicate the crash:**
- Add a Tiled Gallery block with more than 50 images.
- Click Edit Gallery from the block toolbar.
- Add images, remove images or just do nothing and click Update in the media modal.
- It should crash.
- Save this post where you can consistently replicate the crash.

**How to test the fix:**
- Load the post where you can consistently replicate that crash.
- Click Edit Gallery from the toolbar.
- Add images, remove images or just do nothing and click Update in the media modal.
- It should NOT crash.

Here are some videos to show the before & after:

https://user-images.githubusercontent.com/1287077/162379721-1d955629-dd8a-4989-8c29-5b52200461c5.mp4

https://user-images.githubusercontent.com/1287077/162379526-a3b2cfcc-02f8-4650-a476-09db4fa4a94f.mp4

### CODE REVIEW

**Comment by yansern** [comment]
Just want to add a note about this one. Also try testing on a small tiled gallery, like 2-3 images, and see if the attributes are updated/stored properly after adding/removing/swapping images. It should be fine I think but who knows maybe the checking is too aggressive.

**Comment by ivan-ottinger** [comment]
It looks like issue can be reproduced on Simple and WoA sites only, right? I couldn't reproduce it on a standalone Jetpack site.

**Comment by yansern** [comment]
> It looks like issue can be reproduced on Simple and WoA sites only, right? I couldn't reproduce it on a standalone Jetpack site.

Applies to all places. I was reproducing it on the standalone Jetpack sites. Interesting that you can't reproduce it on standalone.

**Comment by yansern** [comment]
The PR fix needs to be reworked as it is missing `data-*` attributes (technically not necessary for Edit's view but will rethink solution).

**Pull request closed without merging**
