### PR TITLE
VideoPress: Allow empty video description and caption

### LINKED ISSUE #26528: VideoPress: Video edit is not persisting empty description
Steps to reproduce:
1 - With at least one uploaded video , go to the VideoPress dashboard
2 - On any video, click `Edit video details`
3 - If the description is empty, add some description and hit `Save`
4 - Back to the video details screen, delete the description and hit `Save`
5 - Check that the empty description is not persisted

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #26528.

#### Changes proposed in this Pull Request:

* Change the caption and description value checks to allow empty values, but only when the field is really present on the request body

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* On your test site, upload one video and get it's attachment ID (or use one that you already uploaded before)
* Do a GET request to `http://your-site.com/wp-json/wp/v2/media/{ID}` to get the video information
* Check the value for the description and caption fields inside the `jetpack_videopress` field
* Now do a POST request to `http://your-site.com/wp-json/wpcom/v2/videopress/meta` with the following `body` to set a new value for the description

```
{
    "id": {ID},
    "description": "Some value"
}
```

* Check the value of the description inside jetpack_videopress field again; the value must be same that you put on the POST request (this was already working before this PR)
* Now do another POST request to `http://your-site.com/wp-json/wpcom/v2/videopress/meta`, but use an empty string for the the description
* Check the value of the description inside jetpack_videopress field again; the value must be empty as you sent (this is the fiexed behavior)
* Do the same for the `caption` field

Some snippets:

**getting the video details**
```cli
curl -X GET -u "user:pass" http://your-site.com/wp-json/wp/v2/media/{ID} | jq
```

**posting the new value for description...**

```cli
curl -X POST -u "user:pass" http://your-site.com/wp-json/wpcom/v2/videopress/meta -H 'Content-Type: application/json' -d '{"id": {ID},"description": "Some value"}' | jq
```

**... and for caption...**
```cli
curl -X POST -u "user:pass" http://your-site.com/wp-json/wpcom/v2/videopress/meta -H 'Content-Type: application/json' -d '{"id": {ID},"caption": "Some value"}' | jq
```

**... or both**
```cli
curl -X POST -u "user:pass" http://your-site.com/wp-json/wpcom/v2/videopress/meta -H 'Content-Type: application/json' -d '{"id": {ID},"caption": "Some value","description": "Some value"}' | jq
```

### CODE REVIEW

**Comment by lhkowalski** [comment]
For some reason, this failed on `wpcom` check the same way #26455 did. Both touched the same file. Last time it was an [unrelated issue](https://github.com/Automattic/jetpack/pull/26455#issuecomment-1258893136), not sure this time.

**Comment by retrofox** [comment]
> For some reason, this failed on `wpcom` check the same way #26455 did. Both touched the same file. Last time it was an [unrelated issue](https://github.com/Automattic/jetpack/pull/26455#issuecomment-1258893136), not sure this time.

addressing now...

**Review by retrofox — APPROVED** [review]
LGTM. It's possible to set empty values for `description` and `caption` files. I wonder whether we should do the same with `title` since currently is not possible to do.

**Comment by retrofox** [comment]
r253609-wpcom

**Pull request merged**
