### PR TITLE
My Jetpack: Add JITM container

### PR DESCRIPTION
**Pull request by dereksmart**
This PR adds a container for JITMs to the My Jetpack screen. It looks like this: 

image

#### Changes proposed in this Pull Request:

Adds JITM container to My Jetpack screen. 
Adds custom style rules in JITM css so it's compatible with the `<Col>` used in My Jetpack. 

#### Jetpack product discussion

Design convo: p1HpG7-eMU-p2
PT for showing JITM in standalone: pbNhbs-38V-p2

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

- Connect to your sandbox with D73609-code to get the JITM.
- Visit the My Jetpack admin page
- Visit My Jetpack without the JITM enabled to ensure no side effects of adding the empty container/col.

### CODE REVIEW

**Comment by oskosk** [comment]
Tried to rebase this but it's impossible. not due to the conflicts, but tooling dies

**Comment by dereksmart** [comment]
Not much here but rebased in case

**Comment by eeeeevon13** [comment]
Hmmm we've got two jetpack logos and two different color buttons... thoughts @keoshi

**Comment by retrofox** [comment]
> I wonder if we could, for this iteration and since this wasn't covered before, apply the current JITMs some custom styling to make them more compatible with the new visual language and emulate CUTs, like so:

I think it's doable. We already have the _Global notcias_ at My Jetpack level. Probably we can reorganize the code to combine both systems.
QQ: do we need to provide the `jp-admin-notices` which will act the notices placeholder?

**Comment by dereksmart** [comment]
The thing about using the arrow icon for the CTA is we lose the CTA text. So anyone adding a JITM in wpcom will need to format the message to fit.

**Comment by dereksmart** [comment]
Marking as on hold until we figure out what to do with JITMs. Internal post coming.

**Comment by dereksmart** [comment]
We're moving forward with getting JITMs into standalone plugins via My Jetpack, so this PR is relevant again. See PT p1HpG7-eMU-p2

**Comment by dereksmart** [comment]
Marking design review as complete, since we're comfortable shipping this consistent UI for now p1HpG7-eMU-p2#comment-56228

**Review by oskosk — APPROVED** [review]

**Pull request merged**
