### PR TITLE
Call actions prior to running upgrades

### PR DESCRIPTION
**Pull request by DavidAnderson684**
Explained at: https://wordpress.org/support/topic/requesting-an-action-hook

### CODE REVIEW

**Comment by jeherve** [comment]
Thanks for the patch!

Could you add [inline documentation](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters), like [here](https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-post-endpoint.php#L75)?

**Comment by DavidAnderson684** [comment]
I've added the inline documentation now...

**Comment by DavidAnderson684** [comment]
From testing, I notice that wordpress.com has a timeout of 30 seconds for the update process. That can be too low, if a backup has to sneek in before the update. (For a plugin update, what gets backed up is the database, plus the plugin files). I just did a plugin update on a big site (hundreds of thousands of rows in several of the tables). The plugin update actually worked fine - but because of the timeout, wordpress.com said that it failed.

On most sites, this'll be fine. But, it'd help us see less support requests about failed plugin updates (which actually didn't fail) if that timeout could get raised.

**Comment by enejb** [comment]
@DavidAnderson684 just to clarify you are trying to a back up the whole database before every plugin /theme/core/language packs update?

I am not sure what the best solution is here. Maybe doing backups when you detect that there is a new version of a plugin/theme/core might be a better approach. You could schedule the backup to happen then.

This way when the user updates the plugin. The backup would already have happend. 

Doing it just before the update happend would cause timeout issue like you point out above, and no matter how high our setting is they would happen for users. Since there is no limit to how long the backup process could take. 

In practice I am ok with adding the filters but don't think they would work as you expect them. I think we might have to rethink how we update files for this to work.

**Comment by DavidAnderson684** [comment]
Hi,

Thanks for getting back!

It's an existing feature that's been there for 3 years - it works well. It's very rare to see a support request related to it. Used by tens of thousands. So, it's proved solid.

Very few hosts have a PHP timeout that's as low as 30 seconds - the typical value is 90 seconds (since that's the cPanel default, with cPanel being used by ~ 80% of websites, last time I saw a stat somewhere...).

Of course, it's certainly possible for someone to have a database that could take longer than 90 seconds to dump. But, that's extremely rare, based on our support experience. Raising your limit from 30 to 90 (or 60) would leave only a very tiny tail (they'll just have to turn our auto-backup feature off, and rely on their scheduled backups instead). The range 30-90 has few, but still some. As it is, you have to be pretty large to need >30 seconds. On my non-optimised hosting, the database backup of my personal site takes ~2 seconds. But, every little helps.

David

**Comment by zinigor** [comment]
Thanks for the PR, @DavidAnderson684! We'd like to include this PR in 3.9.3, can you please update version numbers in `@since` tags?

**Comment by DavidAnderson684** [comment]
Done...

**Comment by zinigor** [comment]
Thank you! This one looks good to go!

**Comment by samhotchkiss** [comment]
PR looks good!

@roccotripaldi -- you might want to do some investigation re: timeout-- are we setting it at the right level now, or could we wait a little longer?

**Comment by roccotripaldi** [comment]
I ran into the timeout issue with #3364. I think we default to 15 seconds, and with remote connections, I bumped it up to 60 seconds, because I was testing on a site on a really slow server.

I'll do some digging to see if we can up the timeout for upgrade requests.

**Pull request merged**
