### PR TITLE
Premium Content: Fix call to subscriptions end date as array instead of object

### PR DESCRIPTION
**Pull request by apeatling**
Fixes error reported in logs.

#### Changes proposed in this Pull Request:

* Reference a call to subscriptions as an object instead of array.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* I am unable to reproduce this, but it's being reported in our logs and this should fix it. 🤷‍♂️

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

**Comment by apeatling** [comment]
See: p1612709528015700-slack-C4N88L95W

**Review by jeherve — CHANGES_REQUESTED** [review]
That should help indeed. Should we do the same in `projects/plugins/jetpack/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php`?

**Comment by apeatling** [comment]
Good spot, updated this too. :+1:

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
@apeatling Could you commit the matching WordPress.com diff? Thank you!

**Comment by jeherve** [comment]
r221693-wpcom

**Pull request merged**
