### PR TITLE
Connection: Add connected user data to the initial state

### PR DESCRIPTION
**Pull request by leogermani**
Add connected user data to the initial state and consume it in the connection status card

#### Changes proposed in this Pull Request:

* Add connected user data to the initial state

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Connect site and user
* Go to the backup plugin and/or My Jetpack page
* Check the connection status card correctly displays user information and avatar

### CODE REVIEW

**Comment by retrofox** [comment]
Leo, it gets the `Version mismatch` error:

```cli
Error: Version mismatch, expected 0.13.0-alpha but found 0.12.1!
You might use `tools/project-version.sh -f -u 0.13.0-alpha js-packages/connection` or `tools/fixup-project-versions.sh` to fix this.
```

**Comment by retrofox** [comment]
There are some linting issues to fix, too :-)

**Review by oskosk — DISMISSED** [review]
LGTM!

`SET_USER_CONNECTION_DATA` unnecessary in the reducer for now but still good to go. :shipit:

**Comment by leogermani** [comment]
Updated the PR with the latest changes we have agreed on, and also (hopefully) made all the check pass

**Comment by retrofox** [comment]
> ... and also (hopefully) made all the check pass

I'm afraid they do not. There is still [a blocking failing test yet](https://github.com/Automattic/jetpack/runs/4795532859?check_suite_focus=true). :-(

**Review by oskosk — DISMISSED** [review]

**Review by oskosk — APPROVED** [review]

**Comment by oskosk** [comment]
Introduced be176e12cca64d72e5180625384fc496cbcd2dd6 by editing here on GitHub like an old-man that I am

**Comment by oskosk** [comment]
This one looks ready to go now 🥳

**Comment by leogermani** [comment]
r238166-wpcom

**Pull request merged**
