### PR TITLE
Spinner component: Replace with Core's spinner

### PR DESCRIPTION
**Pull request by dereksmart**
Replaces the broken spinner component we've been using. 

#### Changes proposed in this Pull Request:

Replaces our custom `<Spinner />` component with [the one from Core](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/spinner) 

I removed the spinner entirely from the Search bar in /settings, because it didn't seem to be rendering anyway. 
After this change, we're only using the spinner in three places. 
- Stats area in /dashboard
- Creativemail install button in the /recommendations
- Termination (disconnect) dialoge

**Stats :: Before:**
image

**Stats:: After**
image

#### Jetpack product discussion

p1617650857426000-slack-jetpack-crew

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

Stats area:
- When the At A Glance dashboard is loading, you should see the spinner in the stats area. 

Install Button: 
- Looking at the code, I think this should be displaying somewhere in the /recommendations when someone clicks to install Creativemail. I'm not really sure how to get there to test it TBH, but it seems like the CSS removed from projects/plugins/jetpack/_inc/client/components/install-button/style.scss won't impact the positioning of the spinner at all, and I didn't see any other custom styling in there for `dops-spinner`. 

Termination dialogue 
- AKA the disconnect modal. We show a spinner there before the dialog pops up. You'll see it for a brief moment when you click "manage site connection" for the first time on a page load. Too quick to even screenshot it.

### CODE REVIEW

**Comment by kraftbj** [comment]
For context, it looks like this may have been a Chrome regression in Chrome 89 (Stable on March 2) or shortly before. Chrome 90 still displays the bad spinner. Chrome 91 displays as expected, but goes stable on May 25 per schedule: https://www.chromestatus.com/features/schedule

It works for me on FF Dev Edition as is.

All that said, I think we should use Core anywhere we can unless we have a compelling reason not to, so I support replacing our solution as this PR does.

**Comment by eeeeevon13** [comment]
Looks good to me

**Comment by dereksmart** [comment]
This needs more love - too much was dependent on the custom styling. Looks like the whole setting nav search bar is broken. If anyone knows how to fix it instead that might be a better approach.

**Comment by dereksmart** [comment]
Updated the styles, removed the spinner entirely from the Search bar, and updated the PR description. I could use some help testing the /recommendations one.

**Review by jeherve — APPROVED** [review]
This tests well for me, nice work! Merging.

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.6` in b5473e250d5dcae1fbba0e32575ee1fbed31c142

**Pull request merged**
