### PR TITLE
push-to-mirrors: Consider missing mirror as an error

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

This seems like the more useful behavior, but is technically a breaking change in the package, hence the major version bump.

In the monorepo here, this will not prevent any merges, but will result in us being pinged in Slack after every merge until the needed mirror gets created.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

p1669037520481709/1669025975.301269-slack-C01U2KGS2PQ

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create a build artifact, or download and unpack one from a recent build.
* Modify the build to include a mirror that does not exist (edit mirrors.txt and create/move the corresponding directory). Leave some valid mirrors in mirrors.txt after the invalid one.
* Run the `push-to-mirrors.sh` script locally, after setting `BUILD_BASE`, `GITHUB_ACTOR`, and `GITHUB_REF`. Be sure `CI` is **not** set in your environment so it doesn't try to actually push.
* Check that the script reported the error and still continued to process later pushes, and in the end exited with a non-zero exit code.

### CODE REVIEW

**Comment by coder-karen** [comment]
Just looking at testing this PR - what I haven't worked out yet is how do I make sure CI is not set, other than typing in CI = '' in `push-to-mirrors.sh`?

**Comment by anomiex** [comment]
You might check with `env`, which lists all environment variables that are set. `env | grep CI` could help if the list is long. Or you could just `unset CI` to make sure it's unset.

(I cribbed most of that from [StackOverflow](https://stackoverflow.com/a/24026737/634419) 😀)

**Comment by sdixon194** [comment]
Hmm I had this working, then realized I made the mirror.txt change at the end and didn't want to wait for all of them to finish, so I stopped it, added the missing mirror-repo to the top of the file, ran it again and it failed. Now when I try with a clean build, it tells me the operation isn't permitted, and when running with `sudo` for kicks,  I keep getting this:

Screen Shot 2022-11-21 at 11 08 05 AM

Not sure what's missing, the env is definitely set (and it worked a second ago!).

**Comment by anomiex** [comment]
First error there, looks like you changed the permissions on mirrors.txt so it can't be read now?

Second error with the sudo is because sudo isn't passing through all the environment variables. You could use `sudo --preserve-env` if you really want, although sudo shouldn't be needed.

**Comment by coder-karen** [comment]
Did manage to test this in the end - confirmed that I got an error:

```
::error::Mirror repo for Automattic/jetpack-pr-test does not exist.
Skipping.
```

And the script continued to process later pushes after that. Nothing happened at the end though, no error codes shown. Should there have been something?

**Comment by anomiex** [comment]
Easiest way to check the exit code in bash is to do `echo $?` immediately after running the command.

```
$ true
$ echo $?
0
$ false
$ echo $?
1
```

**Review by coder-karen — APPROVED** [review]
Re-ran this today, same error output for the demo repository, later pushes were still processed, and I did get a non-zero (1) exit code using `echo $?` immediately afterwards.

**Pull request merged**
