### PR TITLE
Subscription Site: Polishing Newsletter settings

### PR DESCRIPTION
**Pull request by pkuliga**
Part of https://github.com/Automattic/jetpack/issues/36021

See p1HpG7-rwo-p2

## Proposed changes:

It:
- reorders toggles, first Subscribe block and pop-up, then comments
- adds the "Preview and edit" link to the Subscribe block placement settings for block themes
- replaces the existing "Preview and edit the pop-up" link with the "Preview and edit" to keep the consistency
- puts the "subscription pop-up" toggle explanation to the dedicated `SupportInfo` block

### Before

Screenshot 2024-03-11 at 11 14 11

### After

Screenshot 2024-03-11 at 11 13 48

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- enable the Subscription Site feature by adding the following line to your `0-sandbox.php` file:
```php
add_filter( 'jetpack_subscription_site_enabled', '__return_true' );
```
- enable the Jetpack Newsletter Module
- go to the Newsletter settings and make sure the changes look sane
- with the block theme enabled make sure the"Preview and edit" links are visible and work as expected
- with the classic theme enabled make sure the "Preview and edit" links are not visible

### CODE REVIEW

**Comment by simison** [comment]
Nitpicking on copy; 
- other toggle copy ends in `.`, other doesn't. Which way should it be?
- Starting in lower capital feels a bit weird for translators; it might be a non-issue. Should we perhaps ditch `()` and just make the whole sentence "full" proper sentence?

[ ] Toggle label. [Preview and edit.](#)

@crisbusquets for direction.

**Comment by pkuliga** [comment]
> * other toggle copy ends in `.`, other doesn't. Which way should it be?
> * Starting in lower capital feels a bit weird for translators; it might be a non-issue. Should we perhaps ditch `()` and just make the whole sentence "full" proper sentence?
> 
> [ ] Toggle label. [Preview and edit.](#)

Fixed, thanks for spotting!

**Review by simison — APPROVED** [review]

**Comment by crisbusquets** [comment]
Hi @pkuliga !

I tested it and it works as expected.

But based on what I shared on the i3 post, can we release a version with this structure?:

Screenshot 2024-03-11 at 13 25 27

Instead of:

Screenshot 2024-03-11 at 13 24 38

**Comment by pkuliga** [comment]
@crisbusquets adding a main toggle introduces too much complexity. Let's do it when we have more toggles.

**Comment by crisbusquets** [comment]
> @crisbusquets adding a main toggle introduces too much complexity. Let's do it when we have more toggles.

But I wasn't referring to the main toggle for Newsletters (we're still discussing it in the P2).

The screenshots I shared in my previous comment were almost the same, the only difference is the structure for the toggles. It separates them into two, instead of one: one for subscriptions (modal, and automatic insertion) and one for comments-related subscriptions.

_Now I'm not sure if we're talking about the same main toggle, tho_ 😅

**Comment by pkuliga** [comment]
@crisbusquets where should be the "Let visitors subscribe to new posts and comments via email" toggle in the new structure? AFAIK, this toggle works now as a "main toggle" to enable/disable the Newsletter module. Do you want to remove it?

**Comment by crisbusquets** [comment]
> @crisbusquets where should be the "Let visitors subscribe to new posts and comments via email" toggle in the new structure? AFAIK, this toggle works now as a "main toggle" to enable/disable the Newsletter module. Do you want to remove it?

Just adding a comment here to note that we discussed this in our weekly call today.

Let's ship this version, and improve copy so it's more concise. Here's the new issue:

https://github.com/Automattic/jetpack/issues/36342

**Pull request merged**
