### PR TITLE
Accept css class as attribute for contact-field shortcode.

### LINKED ISSUE #2848: Feature request: Add custom classes to contact form field wrappers
A feature that would be great with the Jetpack Forms is being able to pass a class, or list of classes, through the [contact-field] shortcode that would be added to the wrapping div element - [contact-field label="Comments" type="textarea" class="full-width" /]

### PR DESCRIPTION
**Pull request by osiux**
Still in progress, currently it's missing that the form builder removes the class attribute when you edit and save the form.

Fixes #2848

### CODE REVIEW

**Comment by osiux** [comment]
I just noticed that the same thing happens with placeholder (and maybe other attributes). If you have them in your shortcode and edit the form with the form builder, then save it, they are removed. Should we keep this behavior?

**Comment by jeherve** [comment]
>  If you have them in your shortcode and edit the form with the form builder, then save it, they are removed. Should we keep this behavior?

I think that's okay for that Pull Request, but it would be worth opening a new issue about this, and change that behaviour for all other parameters that are not part of the form builder.

**Comment by jeherve** [comment]
This would need a rebase I'm afraid. @osiux Could you take a look?

Thanks!

**Comment by osiux** [comment]
@jeherve I think it's done :)

**Comment by jeherve** [comment]
Thanks!

**Comment by eliorivero** [comment]
lgtm :100:

**Pull request merged**
