### PR TITLE
Revert "Premium Content / Subscriptions: introduce Paid Newsletter functionality

### PR DESCRIPTION
**Pull request by coder-karen**
#### Changes proposed in this Pull Request:

* This reverts the changes made in this PR: https://github.com/Automattic/jetpack/pull/26417
* This was done as the WoA deploy resulted in a large number of fatals errors, specifically:

```
Uncaught ArgumentCountError: Too few arguments to function Automattic\Jetpack\Extensions\Subscriptions\jetpack_filter_excerpt_for_newsletter(), 1 passed
```
and

```
Uncaught ArgumentCountError: Too few arguments to function Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service::visitor_can_view_content(), 1 passed
```

... with two expected in each case.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

p9o2xV-2HN-p2#comment-6910
p1672250536716759/1672247705.462969-slack-C01U2KGS2PQ

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Apply this PR and make sure the previous (prior to the linked PR) subscriptions / premium content functionality is not impacted in any way.

### CODE REVIEW

**Comment by zinigor** [comment]
The code seems to be reverted correctly, I'm going to test the changes now.

**Review by zinigor — APPROVED** [review]
I have tested the changes - the premium filter feature is removed with this PR, the subscription block is working as before.
One thing that worries me is that I wasn't able to fully reproduce the error itself with the trunk version on an Atomic site.

**Comment by coder-karen** [comment]
Cherry-picked to the release branch in dad91f91d8f4caafec278d55c32103dda18fc6c9

**Comment by romarioraffington** [comment]
Could this be an atomic deploy issue and not a code issue?

**Comment by coder-karen** [comment]
@romarioraffington with the second example (`visitor_can_view_content`) it definitely looks like a code issue. For the first function (`jetpack_filter_excerpt_for_newsletter`) the issue is how many arguments passed via a WP core file, so I'm not too sure about that. I'll drop in more information about the errors below.

  For `jetpack_filter_excerpt_for_newsletter`, there is only [1 argument passed here](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-hook.php#L308), but two are expected in the function in subscriptions.php.

  For `visitor_can_view_content`, only [1 argument is passed here in access-check.php](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/premium-content/_inc/access-check.php#L95), but 2 are expected.

Here are the full stack traces, from an example of each error:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Automattic\Jetpack\Extensions\Subscriptions\jetpack_filter_excerpt_for_newsletter(), 1 passed in /wordpress/core/6.1.1/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/subscriptions/subscriptions.php:657
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Extensions\Subscriptions\jetpack_filter_excerpt_for_newsletter('The long-term u...')
#1 /wordpress/core/6.1.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('The long-term u...', Array)
#2 /srv/htdocs/wp-content/themes/blogmagazine/inc/dglib/core/functions.php(252): apply_filters('get_the_excerpt', 'The long-term u...')
#3 /srv/htdocs/wp-content/themes/blogmagazine/inc/dglib/core/functions.php(262): dglib_get_excerpt(150, true, 'Read More...')
#4 /srv/htdocs/wp-content/themes/blogmagazine/template-parts/layouts/classic.php(57): dglib_the_excerpt(150, true, 'Read More...')
#5 /wordpress/core/6.1.1/wp-includes/template.php(785): require('/srv/htdocs/wp-...')
#6 /wordpress/core/6.1.1/wp-includes/template.php(718): load_template('/srv/htdocs/wp-...', false, Array)
#7 /wordpress/core/6.1.1/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
#8 /srv/htdocs/wp-content/themes/blogmagazine/archive.php(37): get_template_part('template-parts/...')
#9 /wordpress/core/6.1.1/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#10 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#11 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#12 {main}
  thrown in /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/subscriptions/subscriptions.php on line 657
```

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service::visitor_can_view_content(), 1 passed in /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/premium-content/_inc/access-check.php on line 95 and exactly 2 expected in /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php:54
Stack trace:
#0 /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/premium-content/_inc/access-check.php(95): Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service->visitor_can_view_content(Array)
#1 /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/premium-content/subscriber-view/subscriber-view.php(55): Automattic\Jetpack\Extensions\Premium_Content\current_visitor_can_access(Array, Object(WP_Block))
#2 /wordpress/core/6.1.1/wp-includes/class-wp-block.php(256): Automattic\Jetpack\Extensions\Premium_Content\render_subscriber_view_block(Array, '\n<div class="wp...', Object(WP_Block))
#3 /wordpress/core/6.1.1/wp-includes/class-wp-block.php(242): WP_Block->render()
#4 /wordpress/core/6.1.1/wp-includes/blocks.php(1051): WP_Block->render()
#5 /wordpress/core/6.1.1/wp-includes/blocks.php(1089): render_block(Array)
#6 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): do_blocks('<!-- wp:premium...')
#7 /wordpress/core/6.1.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:premium...', Array)
#8 /wordpress/core/6.1.1/wp-includes/post-template.php(255): apply_filters('the_content', '<!-- wp:premium...')
#9 /wordpress/themes/pub/lodestar/components/post/content.php(41): the_content('Continue readin...')
#10 /wordpress/core/6.1.1/wp-includes/template.php(785): require('/wordpress/them...')
#11 /wordpress/core/6.1.1/wp-includes/template.php(718): load_template('/wordpress/them...', false, Array)
#12 /wordpress/core/6.1.1/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
#13 /wordpress/themes/pub/lodestar/single.php(19): get_template_part('components/post...', '')
#14 /wordpress/core/6.1.1/wp-includes/template-loader.php(106): include('/wordpress/them...')
#15 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#16 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#17 {main}
  thrown in /wordpress/plugins/jetpack/11.7-a.9/extensions/blocks/premium-content/_inc/subscription-service/class-token-subscription-service.php on line 54
```

**Comment by romarioraffington** [comment]
Thanks so much for the stacktraces as I couldn't reproduce using Jurassic tube. I'll investigate and create a new PR.

The first error appears to be theme specific. It appears that the `blogmagazine` theme is overriding the WP core [get_the_excerpt](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/post-template.php#L431-L431) filter. I was able to reproduce the issue with the theme.

Both errors should be fixed in https://github.com/Automattic/jetpack/pull/28140/commits/755de8d7b0bc276fc25cfce8556518a7a0a30ca2 and https://github.com/Automattic/jetpack/pull/28140/commits/3bb81c81031acd62214d31db0aa7987179594974.

Thanks again.

**Pull request merged**
