### PR TITLE
instant-search: Remove IE11 polyfill

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

We don't transpile for IE11 anymore since #19328, meaning IE11 won't
run our JS anymore in the first place. So there's no point in keeping
the polyfill around.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Does Instant Search still work in browsers we care about?

### CODE REVIEW

**Review by jsnmoon — DISMISSED** [review]
Works as described. 

Pinging @bluefuton since he expressed interest in implementing graceful degradation for IE11 visitors before phasing out our existing polyfill system.

**Comment by bluefuton** [comment]
> Pinging @bluefuton since he expressed interest in implementing graceful degradation for IE11 visitors before phasing out our existing polyfill system.


Still keen on this, and tracking it in https://github.com/Automattic/jetpack/issues/14885.

Am I right in saying that, since we're not transpiling for IE11 any more, search is broken in IE11 even before shipping this PR?

**Comment by anomiex** [comment]
> Am I right in saying that, since we're not transpiling for IE11 any more, search is broken in IE11 even before shipping this PR?

I don't have IE11 to check, but I'd guess that's correct. I know that the removal of IE from the browsers list resulted in Babel outputting `const` and such now, which I had thought IE11 didn't support at all but I now see https://caniuse.com/const seems to state that IE does support it partially. I don't know offhand what other stuff isn't being transpiled away anymore though.

**Review by bluefuton — APPROVED** [review]
I tried this out in IE11 using Browserstack on my test site running the Twenty Twenty One theme, and the removal of the polyfill makes no difference to the existing behaviour (falls back to the old WordPress search).

Continues to work as normal in Chrome, Safari and Firefox. 🚢

**Review by sergeymitr — APPROVED** [review]

**Comment by anomiex** [comment]
r231727-wpcom

**Pull request merged**
