### PR TITLE
[RNMobile] Show "No title"/"No description" placeholder for not belonged videos

### PR DESCRIPTION
**Pull request by fluiddot**
Follow up on https://github.com/Automattic/jetpack/pull/30759.

## Proposed changes:

* For not belonged videos that have an empty title and/or description, instead of displaying the placeholder `Add title`/`Add description`, show `No title`/`No description` to avoid confusion.

| Empty title and description | With title and description |
|--------|--------|
|  |  | 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

N/A

## Testing instructions:

- Open a post/page.
- Add a VideoPress block.
- Add a video that doesn't belong to the site and has an empty title and description (e.g. insert the video from an URL - https://videopress.com/v/XBqrRFxJ).
- Open the block settings.
- Observe that the title and description settings are disabled.
- Observe that the title field displays a placeholder with the text `No title`.
- Observe that the description field displays a placeholder with the text `No description`.
- Replace the video with another one that doesn't belong to the site, but has a title and description. (e.g. insert the video from an URL - https://videopress.com/v/E6So1Wpf).
- Observe that the title and description settings are disabled.
- Observe that the title field displays the title of the video.
- Observe that the description field displays the description of the video.

### CODE REVIEW

**Review by SiobhyB — DISMISSED** [review]
@fluiddot, LGTM! Thank you for spotting and following up on this 🙇‍♀️ 

What do you think about also updating the title placeholder? It'd be a edge case, but an `add title` placeholder does display when there's no title, which would be confusing if it can't actually be edited.

https://github.com/Automattic/jetpack/blob/87262ba1bbe42444260f05f152615687d3efdbb5/projects/packages/videopress/src/client/block-editor/blocks/video/components/details-panel/index.native.js#L31

**Comment by fluiddot** [comment]
> What do you think about also updating the title placeholder? It'd be a edge case, but an `add title` placeholder does display when there's no title, which would be confusing if it can't actually be edited.

Yeah, I could apply the same approach to that field too. I'll push an update with this suggestion, thanks!

**Comment by fluiddot** [comment]
> > What do you think about also updating the title placeholder? It'd be a edge case, but an `add title` placeholder does display when there's no title, which would be confusing if it can't actually be edited.
> 
> Yeah, I could apply the same approach to that field too. I'll push an update with this suggestion, thanks!

@SiobhyB I applied this suggestion in https://github.com/Automattic/jetpack/pull/31134/commits/9759f0ddf149078555bc91536c18ca55c020fc94. Let me know if you could take a look at the PR, thanks 🙇 !

**Review by jhnstn — APPROVED** [review]
Looks good :shipit:

**Pull request merged**
