### PR TITLE
Bugfixes to sharing code

### PR DESCRIPTION
**Pull request by sgomes**
Pointed out in #17864 and postponed to this PR.

#### Changes proposed in this Pull Request:
* Fix several issues pointed out in #17864

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
Smoke-test sharing functionality, if possible:
- Add a "More button" to your test site.
- Verify that it works correctly on hover and click, particularly in IE 11.

#### Proposed changelog entry for your changes:
- Fixed a few issues with sharing buttons, particularly in older browsers.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased to pick up new CI checks.

**Comment by sgomes** [comment]
Rebased after massive repo reorganisation.

**Review by jeherve — APPROVED** [review]
This looks good to me 🚢

**Comment by sgomes** [comment]
Thank you for the review, @jeherve! 👍

**Pull request merged**
