### PR TITLE
Form Block: add options to install/activate Jetpack CRM

### LINKED ISSUE #21439: Contact Form: add Jetpack CRM install link
### Impacted plugin

Jetpack

### What

We would like users to be able to install Jetpack CRM via the Contact Form block

### How

Currently the block's integration with Jetpack CRM detects various states of the plugin (see #17257). However, it'd be great if it were seamless like the current Newsletter integration:

image

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #21439

#### Changes proposed in this Pull Request:

* This is a first pass at this. Ideally, I think we should extract some of this functionality into the shared-extension-utils, alongside the rest of the plugin-management utils, so it could be used by other blocks, and would avoid duplicating code.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start from a site with Jetpack installed with this branch, and with the Contact form module active. A JN site can be perfect for that, launched using [Jetpack Live Branches](https://github.com/Automattic/jetpack/blob/master/tools/jetpack-live-branches/README.md).
* Also install the WP Rollback plugin, we'll need it later.
* Go to Pages > Add New, and add a form block.
* In the form settings sidebar (ensure you're selecting the form block, and not a child block of the form block), you will see option panels, including a CRM panel.
* From there, try to install the CRM plugin.
* Head over to the Plugins menu, and deactivate the plugin.
* Go back to the page editor, and try to activate the plugin.
* Play with the toggle to save form entries to the CRM. It should get saved properly when saving the page.
* Go to the Plugins menu again, and use the Rollback option to go back to an old version of the plugin, before version 3.0
* Go back to the page editor, and notice that you now have a prompt to update the plugin instead of the toggle.

### CODE REVIEW

**Comment by kraftbj** [comment]
Merged from master to get GH Actions to fire again.

**Review by cleacos — APPROVED** [review]
LGTM! It works as expected. Thank you!

image

**Review by samiff — APPROVED** [review]
Worked well for me and I didn't notice any errors 👍 

Not a blocker for this PR, but the CRM panel section seems a bit barren to me. If someone isn't totally sure what they just installed, there isn't much direction provided there:

Screen Shot 2022-03-25 at 2 45 45 PM

We should probably add some info/link like the Newsletter one.

**Comment by tbradsha** [comment]
Overall this looked good:

1. Created a new site.
2. Set up Jetpack.
3. Started a new page: `/wp-admin/post-new.php?post_type=page`
4. Added a Form block (Contact Form variety).
5. Clicked Install Jetpack CRM:
image
6. The section goes blank:
image
7. Refresh the page, and all is well:
image
8. Deactivate JPCRM.
9. Go to the page and activate JPCRM. This works well.
10. Deactivate/delete JPCRM.
11. Go to the page and install JPCRM. This works well.
12. Rollback JPCRM to v4.1.0.
13. Go to the page. The CRM Integration section has the JPCRM toggle.
12. Rollback JPCRM to v4.0.
13. Go to the page. The CRM Integration section just has a blurb about JPCRM with no interaction:
12. Rollback JPCRM to v3.0.20.
13. Go to the page. The CRM Integration section just has a blurb about JPCRM with no interaction.
14. Roll back JPCRM to 2.99.15.
15. Go to the page. The CRM Integration section suggests updating ZBSCRM → JPCRM:
image

Other than the quirk in step 6, I'd prefer we suggest updating if they're not at least on JPCRM 4.9.1 (which is when we added code to prevent the welcome wizard from hijacking the page upon activation).

**Comment by tbradsha** [comment]
Overall this looked good, with a few quirks mentioned at the bottom:

1. Created a new site.
2. Set up Jetpack.
3. Started a new page: `/wp-admin/post-new.php?post_type=page`
4. Added a Form block (Contact Form variety).
5. Clicked Install Jetpack CRM:
image
6. The section goes blank:
image
7. Refresh the page, and all is well:
image
8. Deactivate JPCRM.
9. Go to the page and activate JPCRM. This works well.
10. Deactivate/delete JPCRM.
11. Go to the page and install JPCRM. This works well.
12. Rollback JPCRM to v4.1.0.
13. Go to the page. The CRM Integration section has the JPCRM toggle.
14. Rollback JPCRM to v4.0.
15. Go to the page. The CRM Integration section just has a blurb about JPCRM with no interaction:
16. Rollback JPCRM to v3.0.20.
17. Go to the page. The CRM Integration section just has a blurb about JPCRM with no interaction.
18. Roll back JPCRM to 2.99.15.
19. Go to the page. The CRM Integration section suggests updating ZBSCRM → JPCRM:
image

Other than the quirk in step 6, I'd prefer we suggest updating if they're not at least on JPCRM 4.9.1 (which is when we added code to prevent the welcome wizard from hijacking the next `wp-admin` pageload upon activation).

The rebrand message can probably be removed, but if it is left in, the rebrand happened at 4.0, so anything below 4.0 should get this message.

**Comment by jeherve** [comment]
> the CRM panel section seems a bit barren to me. If someone isn't totally sure what they just installed, there isn't much direction provided there:
> 
> We should probably add some info/link like the Newsletter one.

That's a good point. I'll leave it to the CRM team to figure out what we could add there 👍

> The section goes blank:

This is odd, there should be a spinner appearing in that state. Do you see any JavaScript errors in your console when this happens?

> I'd prefer we suggest updating if they're not at least on JPCRM 4.9.1 (which is when we added code to prevent the welcome wizard from hijacking the next wp-admin pageload upon activation).

I'm happy to change that in a follow-up PR.

> The rebrand message can probably be removed, but if it is left in, the rebrand happened at 4.0, so anything below 4.0 should get this message.

I'll remove it.

**Comment by jeherve** [comment]
r242588-wpcom

**Comment by jeherve** [comment]
Follow-up: #23646

**Comment by tbradsha** [comment]
@jeherve There are several errors I see in the console, but perhaps the most relevant:

```
Failed to load resource: the server responded with a status of 503
```

This occurred twice:

`/wp-json/jetpack/v4/plugins?_locale=user`:
```
{"code":"invalid_user_permission_activate_plugins","message":"You do not have the correct user permissions to perform this action.\n\t\t\tPlease contact your site admin if you think this is a mistake.","data":{"status":401}}
```

`wp-json/jetpack/v4/jetpack_crm?_locale=user`:
```
{"code":"invalid_user_permission_jetpack_crm_data","message":null,"data":{"status":401}}
```

I get the same blank section each time I start a new site and try to install.

**Comment by tbradsha** [comment]
>Was this on JN?

Indeed, it was on JN. The panel is broken each time I try, despite being an admin. Adblockers/Tampermonkey were disabled. Refreshing shows the plugin as successfully installed.

**Comment by tbradsha** [comment]
Perhaps related: #23005

**Pull request merged**
