### PR TITLE
Updates Blaze entrypoint to be compatible with Woo Blaze

### PR DESCRIPTION
**Pull request by sbarbosa**
With the work being done to add a customized version of Blaze for Woo merchants, we want to make the Blaze module compatible with the new plugin. 

The main change here is that Woo Blaze will take over the menu and entry points if the new Woo Blaze plugin is installed on the site. The main idea here is to present the new merchant-customized version of Blaze if we detect WooCommerce and Woo Blaze active.

## Proposed changes:

* Hide the dashboard menu option if WooCommerce and WooBlaze are active. The new plugin will handle the menu and live under the Marketing section with other Ads marketing channels like Google and Facebook.
* Change the redirection URL to the management campaign widget, depending if WooBlaze is active

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

peeHDf-2hF-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

You will need to test this on a site with WooCommerce and the new Woo Blaze plugin. Please ping me to get the Woo Blaze plugin's zip file (it has yet to be released).

The testing steps are the same for Atomic and self-hosting.
* Verify that the Tools->Advertising menu option is not shown
* Go to Posts->All Posts and verify that the "**Promote with Blaze**" is shown in the posts actions
* Click the "**Promote with Blaze**" button and verify that you land on the new Woo Blaze customized dashboard (it is inside the marketing section).
* Now go To Posts->All Posts and create a new post
* Publish that post, and verify that the "**Promote with Blaze**" publish widget is shown.
* Click on "Blaze this post" and verify that you land on the new Woo Blaze customized dashboard.

Now, run a smoke test on a regular site (without the Woo Blaze plugin) and verify that the Blaze dashboard works correctly (the menu option is shown and links from Posts->All Posts redirects to the correct dashboard).

### CODE REVIEW

**Review by therocket-gr — DISMISSED** [review]
followed the testing steps in a local tunneled jetpack site, i confirm that \

1. no advertising menu item is shown under tools 
Screenshot 2024-01-24 at 10 23 28

2. the promote with Blaze button is there in the all posts page
Screenshot 2024-01-24 at 10 23 51


when i click the promote with blaze the link works ok 

3. when publishing a new post the blaze widget is there 

Screenshot 2024-01-24 at 10 28 57

when i click on it the widget loads ok 

code changes LGTM

**Comment by jeherve** [comment]
TIL about Woo Blaze! I must admit I don't quite understand why the Woo Blaze plugin doesn't require the Blaze package; wouldn't that avoid some duplication?

**Comment by sbarbosa** [comment]
Hi @jeherve! For now, we choose to have some duplication because we are still determining what will happen in the next iteration. 

In this iteration, we will duplicate a bit of the Dashboard code to show that new entry point. And we didn't want to include a lot of Woo-specific code in the jetpack Balze module.

But in the future, the idea is to be one of the default marketing plugins that Woo suggests installing to the user, and at that time, we may need to branch out of Jetpack and use a new Blaze Pro API (which is under construction). 

We have yet to discuss the next steps, and we are ready to move the code to another repository if needed, for example, if its decided to ship it with WooCommerce or Jetpack monorepo.


> ! I must admit I don't quite understand why the Woo Blaze plugin doesn't require the Blaze package
I will give this a try!. Right now, because we will only ship this for WooExpress stores, the jetpack plugin will be active in every site. For the next iteration, the best option is to include only the Blaze and Jetpack connect packages.

The future is still a bit uncertain, and we are aware that we may need to move the plugin code to another repository, but this will depend on the next steps towards un-connected Woo stores.

**Comment by sbarbosa** [comment]
Hi @jeherve, did you have some time to read my last answer? 
I am open to discussing and implementing a different approach here, if needed.

**Review by jeherve — COMMENTED** [review]
> did you have some time to read my last answer?
> I am open to discussing and implementing a different approach here, if needed.

Sorry for the late reply. It makes sense to go with something a bit temporary while you try things out. While I can't say I'm a big fan of adding extra plugin-specific logic, as long as things continue to work well for both WordPress.com and self-hosted site owners, that should be fine!

I tested it on WoA and on self-hosted, it worked well. You'll need to run `tools/composer-update-monorepo.sh --root-reqs "projects/plugins/jetpack"` one last time though.

**Comment by sbarbosa** [comment]
Thanks for the comments @jeherve. I just ran another test with the Woo Blaze plugin installed in a Pressable site, and the solution worked OK (The menu was hidden, and the new menu was used instead and is working fine).

Also, this PR doesn't conflict with the last changes of hiding the Posts -> Promote with Blaze button 👍. 
The change I made was to make them more dynamic, and it appears that we added a filter to hide the button. Now that we have that filter, we can think of enabling it on the plugin, which will mean that the users are opting in to use Blaze, but we will think of that in the future, not for this iteration.

Let me know if you think its ok to merge the PR. Thanks for the help!

**Review by jeherve — APPROVED** [review]

**Pull request merged**
