### PR TITLE
External Media: Updates for 8.7

### PR DESCRIPTION
**Pull request by obenland**
Changes in this PR:
* Handle 401 responses #16041
* Extend button margin to featured image #16059
* Render Media after authentication #16044
* Better reflect accepted media types #16071
* Account for multiple images #16077
* Fix Modal focus loss on arrow keypress #16055
* Add API unit tests #15988
* Improve Insert Flow #16081
* Restore focus on modal close #16102
* Disable for existing galleries #16176
* Improve upload permission check #16185

#### Changes proposed in this Pull Request:

* Adds a handler for 401 responses of the list endpoint.
* Adds margins for "Select Image" button in placeholders and the featured image panel
* Re-renders Google media modal after authentication instead of trying to fill it with a new query
* Updates button test to better reflect accepted media types
* Handles focus updates from arrow key presses
* Adds API unit tests and updates `/copy` permissions check.
* Updated image insert flow.
* Removes external media option from existing galleries.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

It might be easiest to review the merged PRs separately, including their testing instructions.
Generally, these steps should cover most if not all of what was changes here:
* Open the editor and insert the following blocks: image, media/text, gallery, cover
* Notice how the insert button text is appropriate for the types of media they accept
* Notice that there are correct margins (including featured images panel)
* Insert images into the gallery from one of the external libraries.
* Notice the new insert flow that keeps the full modal open and shows it as busy
* If you chose Google Photos, notice how the modal loads recent photos after authentication (not albums)
* After inserting images, notice that external libraries are no longer available to add more images to the gallery

#### Proposed changelog entry for your changes:

* Introducing: External Media!

### CODE REVIEW

**Comment by retrofox** [comment]
- [ ] Handle 401 responses #16041
- [ ] Extend button margin to featured image #16059
- [ ] Render Media after authentication #16044
- [ ] Better reflect accepted media types #16071
- [ ] Account for multiple images #16077
- [ ] Fix Modal focus loss on arrow keypress #16055
- [ ] Add API unit tests #15988
- [ ] Improve Insert Flow #16081
- [ ] Restore focus on modal close #16102
- [ ] Disable for existing galleries #16176

**Comment by obenland** [comment]
@jeherve @kraftbj Do you think I could elicit an initial review from one of you, despite this missing an Ajax ✅ ? 
All changes in this PR received a team review prior to having been merged. 

It would help me tremendously in giving me more time to respond to any change requests you may have.

**Comment by kraftbj** [comment]
I'm logging off right now but absolutely!

**Comment by marekhrabe** [comment]
I have identified a compatibility issue with WP 5.3. We are using `useBlockEditContext` which is only available in 5.4 and newer. Its predecesor `withBlockEditContext` is safely available in 5.3 but on the contrary, it has [just been removed from Gutenberg](https://github.com/WordPress/gutenberg/pull/22942), meaning we cannot simply switch to the older way because it will be gone in a few versions. I'll figure out some abstraction that combines both ways so we can use it in Jetpack.

**Comment by obenland** [comment]
@marekhrabe @jeherve  I can't find a reference to `useBlockEditContext` in this PR. Can you help me understand what (if anything) needs to be done here?

**Comment by obenland** [comment]
@jeherve 060b4f8 fixes the visual bug you encountered by removing access to external media library when these blocks contain images already. This brings the behavior en par with the gallery block.

**Comment by marekhrabe** [comment]
> I can't find a reference to useBlockEditContext in this PR. Can you help me understand what (if anything) needs to be done here?

It's already in master and has now been detected in this PR because we've decided to test with the older WP.

**Comment by retrofox** [comment]
> > I can't find a reference to useBlockEditContext in this PR. Can you help me understand what (if anything) needs to be done here?
> 
> It's already in master and has now been detected in this PR because we've decided to test with the older WP.

Correct, but the issue is not being introduced by this PR, does it? It's already in the primary branch. The `useBlockEditContext` hook is imported by `videopress` and `cover` blocks.

**Comment by retrofox** [comment]
minor issues / not blockers 

* margin extends when clicking on the button

externa-media-magin-resize

**Comment by retrofox** [comment]
Initially, the `gallery` block doesn't offer the external media button.

Screen Shot 2020-06-25 at 9 15 14 AM

Guessing it isn't intentional, considering https://github.com/Automattic/jetpack/pull/16176

**Comment by retrofox** [comment]
It seems that [these changes](https://github.com/Automattic/jetpack/pull/16059/files) have been lost.

**Comment by retrofox** [comment]
> Initially, the `gallery` block doesn't offer the external media button.
> Guessing it isn't intentional, considering #16176

The condition `! ( gallery && value )` defined [here](https://github.com/Automattic/jetpack/blob/d2c4f68772e755d083fd64fade7605ab952972fb/extensions/shared/external-media/index.js#L35) is `FALSE` for empty gallery blocks.

**Comment by getdave** [comment]
Would you find any value in e2e tests that could verify this entire feature? It's so large that testing and re-testing is very difficult. Happy to help if that's feasible although I'm not familiar with Jetpack testing at this point.

**Comment by obenland** [comment]
r209619-wpcom

**Pull request merged**
