### PR TITLE
Forms: Update patterns modal default view mode

### PR DESCRIPTION
**Pull request by jcheringer**
## Proposed changes:

* Updates the Form patterns modal default view mode to Grid

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Create a post and add a Form block
* Click the "Explore Forms Patterns" button
* Check if the modal opens with the grid view mode selected by default

### CODE REVIEW

**Comment by digitalwaveride** [comment]
Not sure what I might be missing, but the modal does still open for me in Carousel View ... testing on JN in Firefox:


https://user-images.githubusercontent.com/5120357/218489044-3ecb2e4d-e7d5-4fe8-8c86-ded699f8127f.mov

**Comment by jcheringer** [comment]
Hey @digitalwaveride!
Thanks for testing it.
I also tested it on a JN site, and it's not working 😕 
Not sure what's happening.
It works fine on my dev environment.
Maybe the JN isn't using the latest libraries?
I'll try to understand what's going on.

**Comment by jcheringer** [comment]
According to the Jetpack folks, we need to wait for the version of the `@wordpress/block-editor` to be upgraded in WP Core.

p1676558072052019-slack-CBG1CP4EN

**Review by digitalwaveride — APPROVED** [review]
Nice! 🤩 Worth the wait ;) 

Thank you João!

image

**Comment by jeherve** [comment]
Noting that the e2e tests are failing because of the change:
https://github.com/Automattic/jetpack/actions/runs/4864972454/jobs/8674693259?pr=28906

I've opened #30419 to update the tests; I would appreciate a review.

**Pull request merged**
