### PR TITLE
Search: handle new product purchase flow

### LINKED ISSUE #25907: Search Plugin: Create new purchase flow for Free Plan
When user connects site, we need to automatically assign Search Free Plan for the site. We could refer to How `JETPACK_FREE` Plan is provisioned in WPCOM/Calypso codebase.

### LINKED ISSUE #25908: Search Plugin: Create new purchase flow for Paid Plan
We've already have a paid plan purchase flow, what we need to do is to replace the current product slug `jetpack_search` with the new created slug.

And also, we only want the new slug to be active when we are ready to rollout the new pricing, meaning this needs to be gated by a parameter or a state etc.

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #25907 and #25908

#### Changes proposed in this Pull Request:
- Add connection support for new pricing page
- Add jetpack_search_free product flow

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Create a fresh site with Search plugin but no Search subscription
* Make sure to do a `git pull` on your sandbox
* Add the following code to your wp-content/mu-plugins/0-sandbox.php file on you sandbox, creating the file if necessary
  * `define( 'USE_STORE_SANDBOX', true );`
* Sandbox your test site: `define( 'JETPACK__SANDBOX_DOMAIN', 'xxx.xxx.xxx.xxx.com' );`
* Open `/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`
* Ensure the upsell page handles connection okay
* Ensure you could purchase paid and free products from the plan page - please refer to test instructions in `D88792-code` for how to pay with test credit cards in store sandbox

Known issues:
- The pricing is not yet right on the plan page, which would need `D88792-code` <- WIP
- After purchasing the free product, the redirection is not right, which is probably about some Calypso setup and will be addressed later.

### CODE REVIEW

**Review by jsnmoon — APPROVED** [review]
Code changes look reasonable, and the flows partially work, as described. Good to 🚢!

For both tiers:
- Checkout works as expected
- Redirection is broken, redirecting to https://wordpress.com/admin.php?page=jetpack-search. This is expected for the free tier, but I'm not sure if it is for the paid tier. Note that this is broken for the paid tier **before the pricing changes as well**.

Free tier:
- Search Dashboard is unable to fetch record usage stats.
image

**Comment by kangzj** [comment]
@jsnmoon Thanks for the quick review! 👍 

> Redirection is broken, redirecting to https://wordpress.com/admin.php?page=jetpack-search. This is expected for the free tier, but I'm not sure if it is for the paid tier.

Ha really? then I know where is probably wrong 😄

**Comment by kangzj** [comment]
>     Search Dashboard is unable to fetch record usage stats

This is expected for Free tier which is not yet supported from the indexing side, and for paid tier it should be indexing I suppose?

**Comment by jsnmoon** [comment]
> This is expected for Free tier which is not yet supported from the indexing side, and for paid tier it should be indexing I suppose?

Correct! The post-type breakdown works as expected for the new paid tier.

**Pull request merged**
