### PR TITLE
Site Migration: Add site migration endpoint for access to migration key

### PR DESCRIPTION
**Pull request by sixhours**
Related to https://github.com/Automattic/wp-calypso/issues/87393

## Proposed changes:

* Add a `/wpcom/v2/sites/${site}/site-migration` endpoint to sites with the Migrate Guru plugin, from which we can fetch the migration key on the front end.

Let me know if there's a better approach I'm missing. I haven't been able to get this to show the new endpoint for a WoA site using the Jetpack Beta plugin, or by copying the file directly to the WoA site, but it seems to work on Simple sites (although those don't have the plugin, so the migration key will be an empty string.)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply this patch to your sandbox and sandbox `public-api.wordpress.com`
* From the dev console access `/wpcom/v2/sites/%s/site-migration` for your Simple test site
* Confirm you see an array with a `migration_key => ''` -- the value will be empty because the class doesn't exist on Simple sites.

Screenshot 2024-03-06 at 4 09 13 PM

* I'm not sure how to get it working on Atomic sites; I'm running into authorization errors when I try to access the endpoint via the dev console or even internally. 🤔

### CODE REVIEW

**Comment by sixhours** [comment]
@andres-blanco I'm running into issues testing this and since it's similar to your work in D140803-code I figured I'd ping you. 😅 

Is it normal that I wouldn't be able to get the new endpoint from the AT site on the developer console? I noticed you added a test function hooked to init in the above diff.

Then endpoint is working for Simple sites but not WoA when sandboxed on dev pool.

**Comment by sixhours** [comment]
I've figured out part of the problem in testing this on Atomic - we do some class mapping for API endpoints in `jetpack-mu-wpcom` on WP.com. But I'm modeling this after the Launchpad endpoints so I'm not sure what I'm missing...

**Comment by andres-blanco** [comment]
> I've figured out part of the problem in testing this on Atomic - we do some class mapping for API endpoints in `jetpack-mu-wpcom` on WP.com. But I'm modeling this after the Launchpad endpoints so I'm not sure what I'm missing...

**Dales comment is the best approach https://github.com/Automattic/jetpack/pull/36194#issuecomment-1983452747**

@sixhours I don't know if there's something automatic happening. If I remember correctly, from Calypso we always hit Launchpad endpoints on Simple, but we sync with AT via a synced option.
So, we are not probably going to be able to hit the AT endpoint directly.
Going from there, we can do the following in the endpoint function:
1. Check to see wether we are on AT or not
2. If we are not, then we should 
  1. check to see if the current user has admin capabilities
  2. redirect the request to the AT site by doing something similar to this: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qynhapucnq.cuc%3Se%3Q4ssopo81%26sv%3Qjcpbz_ynhapucnq_hcqngr_ngbzvp_fvgr_jvgu_yrtnpl_fvgr_frghc_gnfxf%23101-og and return the key
4. If we are on AT, then we run the code that you added to get the key

Let me know if this makes sense :)

**Comment by daledupreez** [comment]
I think the endpoint needs to be set up explicitly to forward API calls to the Jetpack site, as per these instructions: PCYsg-liz-p2.

**Comment by sixhours** [comment]
Closing this out in favor of #36253 which adds the endpoint directly to Jetpack.

**Pull request closed without merging**
