### PR TITLE
Boost: Add UI for recommendations to ISA

### PR DESCRIPTION
**Pull request by dilirity**
Fixes https://github.com/Automattic/boost-cloud/issues/314

## Proposed changes:

* Add two recommendation elements to ISA UI:
  * <details><summary>Groups summary</summary>
    image
    </details>
  * <details><summary>Detailed report page</summary>
    image
    </details>

**Note**: Looking at this after creating the PR - maybe the one from the groups summary should be removed?

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup Boost ISA;
* Generate a report;
* Check the Summary UI and detailed report page to make sure the recommendation looks ok.

* Enable `Image CDN`;
* Make sure the recommendation disappears from both places.

### CODE REVIEW

**Comment by thingalon** [comment]
I softened the language a bit, as it may appear when issues the CDN can't deal with appear:
image

**Review by thingalon — DISMISSED** [review]
Awesome, let's go ahead with this.

**Review by donnchawp — APPROVED** [review]
Looks good!

**Comment by haqadn** [comment]
Cherry-picked d0940e82

**Pull request merged**
