### PR TITLE
Jetpack Social: Add share meter

### PR DESCRIPTION
**Pull request by danielpost**
This PR adds a share meter to the header of the Jetpack Social admin page, displaying to the user how many shares they have left.

#### Changes proposed in this Pull Request:

* Add shares meter to Jetpack Social admin page.
* Improve buttons in the header.

#### Other information:

- [X] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

1202436584533778-as-1202583289493859/f

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Make sure the share meter displays properly on the admin page.
* Publicize a new post.
* Make sure the meter goes up.

### CODE REVIEW

**Comment by spsiddarthan** [comment]
I think only one changelog file `projects/plugins/social/changelog/add-jetpack-social-add-share-meter` should be enough. When you use that local tool to fix dependencies, it generates some duplicate files such as these `projects/plugins/social/changelog/add-jetpack-social-add-share-meter#2` and `projects/plugins/social/changelog/add-jetpack-social-add-share-meter#3`. You can have these removed.

**Comment by danielpost** [comment]
@spsiddarthan Good catch, I've removed the redundant ones.

**Review by spsiddarthan — DISMISSED** [review]
Thanks for working on this, @danielpost ! 

It works as expected. May be in a follow-up PR, we can make also rely on `over_the_limit`  to show a red colour?

**Review by spsiddarthan — DISMISSED** [review]

**Review by coder-karen — DISMISSED** [review]
Yes, works well! I initially thought it would count post shares (via sharing buttons) as well based on the wording - if not I'm not sure if that could be something to clarify somewhere later?

**Comment by pablinos** [comment]
Thanks @coder-karen! 

> I initially thought it would count post shares (via sharing buttons) as well based on the wording

Yes, we've got a slight issue with the terminology of 'shares' at the moment. These are Publicize shares, which represents a post being shared to a social network by Publicize. We can hopefully make it a bit clearer in the documentation.

**Review by coder-karen — APPROVED** [review]

**Comment by danielpost** [comment]
r249552-wpcom

**Pull request merged**
