### PR TITLE
Admin Menu: Replace "Edit CSS" with "Additional CSS"

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes Automattic/wp-calypso#51386

#### Changes proposed in this Pull Request:

* Replaces the "Edit CSS" label with "Additional CSS" since that's the language used in the Customizer, and it's designed to add CSS rather than edit the theme's CSS

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

I don't think that I'm actually able to test this change because I'm unable to sandbox a WordPress.com site, but it should be something like this:

* Apply this change for a WP.com simple site 
* Make an API request to `/sites/ID/admin-menu`
* Check the children under the "Appearance" menu 
* Verify the label says "Additional CSS"

Screenshot 2021-04-01 at 14 43 41

### CODE REVIEW

**Comment by Aurorum** [comment]
Hi @mmtr, thanks for that explanation! Are the changes now sufficient in ensuring that the label is replaced for all sites?

**Comment by mmtr** [comment]
I think so, @Aurorum! Thanks for adding them. You also need to fix the linting issue below and merge/rebase latest changes from master in order to pass some CI checks:

```
Warning: projects/plugins/jetpack/modules/custom-css/custom-css.php:904:16: WARNING - Equals sign not aligned with surrounding assignments; expected 2 spaces but found 1 space (Generic.Formatting.MultipleStatementAlignment.NotSameWarning)
```

**Comment by Aurorum** [comment]
Thanks @mmtr! I think that both of those should be taken care of now. :)

**Review by mmtr — APPROVED** [review]
This tests well for me.

Self-hosted sites (Jetpack sites) | Atomic WP.com sites | Simple WP.com sites
--- | --- | ---
Screen Shot 2021-04-09 at 13 05 47 | Screen Shot 2021-04-09 at 13 06 57 | Screen Shot 2021-04-09 at 13 11 55

**Comment by mmtr** [comment]
Internal reference: deployed to WP.com in r224032-wpcom.

**Pull request merged**
