### PR TITLE
Search: Refactor search input detection logic

### LINKED ISSUE #22947: Enhancement: Improve Jetpack Search Compatibility with GeoDirectory + GeoDirectory Advanced Search Filters
### Impacted plugin

Jetpack

### What

Improve compatibility with GeoDirectory so Jetpack Search doesn't override search form

### How

This issue is to investigate compatibility between Jetpack Search and the [GeoDirectory](https://wpgeodirectory.com) WordPress plugin. 

Originally raised in:

7270-gh-Automattic/jpop-issues

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #22947. 

#### Changes proposed in this Pull Request:
Refactors search input selection logic to filter out inputs belonging to forms unrelated to site search.

#### Jetpack product discussion

See #22947.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Apply this change to your site with a Search subscription.
* Ensure that the overlay summoning works as expected depending on the configured overlay trigger settings.
* Try creating a post or a page containing a form mimicking a GeoDirectory form (e.g. a form with the name "geodir-listing-search"). Ensure that typing into an input with a name "s" in this form does not trigger the search overlay.
* Repeat the above for a form with a "post" method. Ensure that the overlay is not triggered.

### CODE REVIEW

**Comment by kangzj** [comment]
Hi @jsnmoon, the refactoring looks good and makes the logic much easier to read.

However I'm not sure this would solve the issue from the GeoDirectory plugin.

For one when submitting the search, if `s` param exists in URL, [the overlay would be summoned again](https://github.com/Automattic/jpop-issues/issues/7270#issuecomment-1038158628).

For two, as Instant Search is still hooking up the search process from here, which might [break other search process](https://github.com/Automattic/jpop-issues/issues/7270#issuecomment-1040258928):

https://github.com/Automattic/jetpack/blob/0fb6fad5f1fb5d2f1bd5daf4eebe3f0d9183cdc3/projects/packages/search/src/instant-search/class-instant-search.php#L170

Even I advised them to dequeue the script on the page, [the geo directory search still fails somehow](https://github.com/Automattic/jpop-issues/issues/7270#issuecomment-1040258928).

Any idea?

**Comment by jsnmoon** [comment]
> For one when submitting the search, if `s` param exists in URL, [the overlay would be summoned again](https://github.com/Automattic/jpop-issues/issues/7270#issuecomment-1038158628). (@kangzj)

As long as the form created by the GeoDirectory plugin matches [our heuristic](https://github.com/Automattic/jetpack/pull/23129/files#diff-11a303c83f84d2ea3190e958a21478100e76337e8c839803144160aa35c68913R54-R56), this should no longer be the case. The behavior mentioned in the link is caused by attaching event listeners to [form submissions](https://github.com/Automattic/jetpack/blob/0fb6fad5f1fb5d2f1bd5daf4eebe3f0d9183cdc3/projects/packages/search/src/instant-search/components/dom-event-handler.jsx#L60); such listeners should no longer be created for GeoDirectory forms.

Is the GeoDirectory form detection not working as expected in this PR?

> For two, as Instant Search is still hooking up the search process from [here](https://github.com/Automattic/jetpack/blob/0fb6fad5f1fb5d2f1bd5daf4eebe3f0d9183cdc3/projects/packages/search/src/instant-search/class-instant-search.php#L170), which might [break other search process](https://github.com/Automattic/jpop-issues/issues/7270#issuecomment-1040258928) (@kangzj)

This is true. I don't have a straightforward solution to this problem, unfortunately. There's no simple heuristic for determining whether the `s` query string was used for site search or for any other arbitrary plugin behavior. Excluding POST actions might make sense here, though it won't be our silver bullet.

**Comment by kangzj** [comment]
> As long as the form created by the GeoDirectory plugin matches [our heuristic](https://github.com/Automattic/jetpack/pull/23129/files#diff-11a303c83f84d2ea3190e958a21478100e76337e8c839803144160aa35c68913R54-R56), this should no longer be the case. The behavior mentioned in the link is caused by attaching event listeners to [form submissions](https://github.com/Automattic/jetpack/blob/0fb6fad5f1fb5d2f1bd5daf4eebe3f0d9183cdc3/projects/packages/search/src/instant-search/components/dom-event-handler.jsx#L60); such listeners should no longer be created for GeoDirectory forms.

I can confirm this part works. 

> Is the GeoDirectory form detection not working as expected in this PR?

Unfortunately no. If it's a normal form - and it is for the plugin, the page would refresh after submission. and `s` would be added to URL, which still summons the overlay if that makes sense.

**Comment by kangzj** [comment]
> This is true. I don't have a straightforward solution to this problem, unfortunately. 

I'm thinking possibly we could add another filter?

**Comment by jsnmoon** [comment]
> > This is true. I don't have a straightforward solution to this problem, unfortunately.
> 
> I'm thinking possibly we could add another filter?
> 
> ---EDIT---- I meant to provide the ability to disable instant search fully for a certain page/post etc. (@kangzj)

That's a good idea. What do you think about using route based blocklist for preventing Instant Search from loading and intercepting search results?

**Comment by kangzj** [comment]
> What do you think about using route based blocklist for preventing Instant Search from loading and intercepting search results?

**Comment by kangzj** [comment]
Hi @jsnmoon I guess since we have a filter to disable Instant/Classic Search, it is now possible combine the effort of the PR to make it work.

**Comment by jsnmoon** [comment]
Putting this on hold in order to prioritize standalone plugin tasks.

**Comment by jsnmoon** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
