### PR TITLE
Google Analytics: display deprecation notices

### PR DESCRIPTION
**Pull request by sergeymitr**
## Proposed changes:
* Display Google Analytics deprecation notice on non-Jetpack admin pages.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
https://github.com/Automattic/vulcan/issues/315

## Does this pull request change what data or activity we track or use?
No.

### Self-hosted
1. Connect Jetpack.
2. Go to "Jetpack -> Settings -> Traffic", find the "Google Analytics" card and purchase a plan.
3. Go back to "Jetpack -> Settings -> Traffic", follow the link to Calypso. Activate GA, enter a measurement ID (e.g. "G-12345").
4. Go to any non-Jetpack admin page, confirm that you see the deprecation notice (see example below), and the link works.
5. Go to Jetpack Dashboard and Jetpack Settings, confirm the notice shows up (see example below), and the link works.
6. Go to "Jetpack -> Settings -> Traffic", find the Google Analytics card, confirm the notice shows up in there (see 
example below), and the link works.
7. Go to "Jetpack -> My Jetpack", confirm the notice shows up and the link works. Confirm the (1) red bubble shows next to "Jetpack" in the sidebar menu.
7. Install/activate the [Google Analytics Legacy plugin](https://github.com/Automattic/jetpack-legacy-google-analytics), confirm all those notices disappear (non-Jeptack pages, Jetpack pages, GA settings card, My Jetpack).
8. Deactivate the plugin, confirm the notice reappears.
9. Disable Google Analytics feature in Calypso, confirm the notice disappears. Enable it back.
10. Click "X" to dismiss the non-Jetpack notice. Refresh the page, confirm it doesn't appear again.

### WoA
1. Checkout the PR via Jetpack Beta on a WoA site.
2. Activate Google Analytics, save a measurement ID.
3. Go to your site's `/wp-admin/`. Check the same pages (non-Jetpack pages, Jetpack pages, GA settings card, My Jetpack), confirm none of the notices show up.

## The notice
Non-Jetpack pages:
Screenshot 2024-06-26 at 20 09 47

Jetpack Dashboard and Settings:
Screenshot 2024-06-27 at 19 58 26

Google Analytics settings card:
Screenshot 2024-06-27 at 19 58 32

My Jetpack:
Screenshot 2024-06-28 at 14 38 46

### CODE REVIEW

**Comment by chrisbliss18** [comment]
The design of the notice is in keeping with the standard WP notice, so that works and makes sense.

The notice links to [this page](https://jetpack.com/support/google-analytics/?site=URL), which doesn't have any information on how to keep using Google Analytics on the site. Is this meant as a temp placeholder until an appropriate page can be written, is this page meant to be updated with relevant information, or are there other plans?

As for the text of the notice, I do have a couple of concerns:
1. "no longer be supported" sounds like the feature will work, but the user can no longer get technical support for it.
2. "See how to keep your site intact" is a bit odd as it suggests that the site might stop functioning.

What do you think of this text?

>Jetpack's Google Analytics feature will be removed on August 6, 2024. [Read this document for details and how to keep tracking visits with Google Analytics](URL).

**Comment by sergeymitr** [comment]
Thanks for taking a look @chrisbliss18 

> The notice links to [this page](https://jetpack.com/support/google-analytics/?site=URL), which doesn't have any information on how to keep using Google Analytics on the site. Is this meant as a temp placeholder until an appropriate page can be written, is this page meant to be updated with relevant information, or are there other plans?

The plan is to add the "Deprecated on self-hosted..." message at the top, with the link to the [Legacy plugin](https://github.com/Automattic/jetpack-legacy-google-analytics).
Similarly to what they did with Custom CSS: https://jetpack.com/support/custom-css/

> What do you think of this text?

Looks a lot better, updated in the PR.

**Review by chrisbliss18 — DISMISSED** [review]
The changes look good. I confirmed the presence and proper styling of the notice in My Jetpack, Jetpack's Dashboard, and the settings page.

I approve the changes. Thanks for the PR. :)

**Review by chrisbliss18 — APPROVED** [review]
Re-approving after your trunk merge.

**Pull request merged**
