### PR TITLE
Override masterbar to show quick links on Atomic sites

### PR DESCRIPTION
**Pull request by tjcafferkey**
Fixes https://github.com/Automattic/wp-calypso/issues/49793

#### Changes proposed in this Pull Request:

* Add specificity to admin menu CSS so that they get applied on Atomic sites.
* Additional specificity will display masterbar icons on mobile

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create an Atomic site on your A8C account so that nav unification is enabled.
* Install Jetpack Beta
* Checkout this branch via Jetpack Beta plugin
* Reduce viewport to mobile view and observe changes below

Repeat steps on a non-A8C account to ensure this works as expected for non-nav unified users.

<table>
<tr>
	<td>Before</td>
	<td>After</td>
</tr>
<tr>
	<td></td>
	<td></td>
</tr>
</table>

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by mmtr — DISMISSED** [review]
Pretty close, @tjcafferkey! I do see the full masterbar now, but I noted there is a weird orange box (probably related to the orange Debug menu item on the masterbar) and the avatar looks like it's misplaced.

Screen Shot 2021-02-12 at 11 37 48


Is that something that can be fixed?

**Comment by tjcafferkey** [comment]
Hmm I encountered that avatar issue myself and thought I had fixed it. I'll continue to take a look at this thanks @mmtr! 👍🏻

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Tested both with and without a8c account and works well for me too. Can we just hide the "Debug" button for `(max-width: 782px)`

**Review by cpapazoglou — APPROVED** [review]
Thanks for fixing that last minor! LGTM 🚢 !

**Comment by cpapazoglou** [comment]
I have also applied the patch in wpcom and inspected that we haven't broken something.

**Comment by cpapazoglou** [comment]
I have restarted the failing wpcom tests

**Review by mmtr — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
This tests well for me.

**Comment by tjcafferkey** [comment]
Deploy to WPCOM in r221126-wpcom

**Pull request merged**
