### PR TITLE
Hide stats dashboard widget for users below view_Stats cap

### PR DESCRIPTION
**Pull request by tommusrhodus**
## Proposed changes:

* Removes the `wp-admin` dashboard Jetpack Stats widget for users lower than the `edit_posts` capability.
* Adds a filter to allow for this to be changed programatically.

Team51 noticed this issue whilst working with a partner who's subscribers have access to the `wp-admin` profile pages and dashboard. These stats seem like they should be hidden for certain user roles. `edit_posts` is a suggestion of the capability level I think would warrant access to this information

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/23197

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Go to your wp-admin dashboard.
* If you're logged in as a user with `edit_posts` capability or higher, ensure the stats widget can be seen.
* If you're logged in as a user without `edit_posts` capability, ensure the stats widget cannot be seen.

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
That seems like a good idea. Maybe we could map this to the `view_stats` custom capability we have, to better match the rest of the Stats access across the dashboard?

**Comment by tommusrhodus** [comment]
> Maybe we could map this to the view_stats custom capability we have, to better match the rest of the Stats access across the dashboard?

Agreed, `view_stats` is a better capability check, thanks for pointing that out @jeherve (I actually didn't know about that cap!) - I'll update the PR.

Do you have any opinion of the usefulness of the second argument of the filter exposing the capability level as a string? Does this add value to the end user, or is it somewhat pointless considering the `current_user_can()` already exposes this clearly?

**Comment by jeherve** [comment]
> Do you have any opinion of the usefulness of the second argument of the filter exposing the capability level as a string? Does this add value to the end user, or is it somewhat pointless considering the `current_user_can()` already exposes this clearly?

I would do without it, personally, and keep it simple. I don't think it brings much added value here.

Just my own opinion though :)

**Comment by tommusrhodus** [comment]
@jeherve Agreed, PR updated 👍

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍

**Pull request merged**
