### PR TITLE
Enhancement - Website Verification Tools

### PR DESCRIPTION
**Pull request by jeffgolenski**
As pointed out by @nickhamze, the Website Verification Tools for Google, Bing, Pinterest, etc, are much visually different from the rest of the elements on the tools page. They are also very difficult to use on small mobile devices. 

This PR fixes all that. I cleaned up a lot of outdated `table` code in favor of a a couple of `divs` and utilized mostly core's styles, but there are a few lines of my own, Jetpack's styles aren't loaded on this page, so I created an inline block of CSS for what style changes I need to make. I chose this route because It's not worth any extra http requests.

BEFORE:

verification-before-mobile
website-verification-tools-before

AFTER:
verification-tools-after-lrg-screen-01
verification-tools-after-mobile-01
verification-tools-after-mobile-02
verification-tools-after-mobile-03

Note: When this gets released I will also update the screenshots for http://support.wordpress.com/webmaster-tools/ because they are severely outdated and non-retina. 

#trash-pickup

### CODE REVIEW

**Comment by georgestephanis** [comment]
I like it, but it's a style enhancement, not a bug fix -- so I'd prefer to push it to 3.6.

Looks good, love the change, just bundle it in the next major release.  Holding off merging.

**Comment by jeffgolenski** [comment]
@georgestephanis Whatever works best! Thanks!

**Comment by jeherve** [comment]
Fixes #1196

**Comment by dereksmart** [comment]
Looks good!  Merging, as George gave it :+1: a while ago

**Comment by jeffgolenski** [comment]
Appreciate it!

**Pull request merged**
