### PR TITLE
[Subscription block] Fix PHP Warning

### LINKED ISSUE #27882: Subscription block: error warning
### Impacted plugin

Jetpack

### Steps to Reproduce

Check the error logs:

PHP Warning: Undefined array key "include_social_followers" in /modules/subscriptions/views.php on line 860

1203451499502244-as-1203529637089977/f

### A clear and concise description of what you expected to happen.

This new error was most likely introduced by https://github.com/Automattic/jetpack/pull/27443

### What actually happened

_No response_

### Browser

_No response_

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by TimBroddin**
Fixes #27882

#### Changes proposed in this Pull Request:
This PR fixes a PHP Warning that's caused when using the old subscription shortcode, and no `include_social_followers` parameter is set.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
https://github.com/Automattic/jetpack/issues/27882

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

1. Make sure your site is on the latest Jetpack release (or trunk)
2. On your site, create a new post and add a Shortcode block with following contents:

```
[jetpack_subscription_form show_subscribers_total=true]
```

3. Navigate to this post on the frontend
4. Examine the logs (using the CLI)
5. You'll see

```
[12-Dec-2022 11:54:37 UTC] PHP Warning:  Undefined array key "include_social_followers" in /srv/htdocs/wp-content/plugins/jetpack/modules/subscriptions/views.php on line 860
```

6. Checkout this branch, build the Jetpack plugin and (if using Atomic) sync it to your website
7. Refresh the browser
8. Verify that you didn't get a new warning

### CODE REVIEW

**Review by yansern — APPROVED** [review]

**Comment by sdixon194** [comment]
Maybe a silly question, but `[jetpack_subscription_form show_subscribers_total=true]` in the shortcode block doesn't render the form for me. Is there any Jetpack setting I'm missing that I need to enable here?

**Comment by samiff** [comment]
> `[jetpack_subscription_form show_subscribers_total=true]` in the shortcode block doesn't render the form for me. Is there any Jetpack setting I'm missing that I need to enable here?

Shortcode worked ok for me. Perhaps your Subscriptions module was turned off? `/wp-admin/admin.php?page=jetpack_modules`

**Review by samiff — APPROVED** [review]
:shipit:

**Comment by sdixon194** [comment]
> Shortcode worked ok for me. Perhaps your Subscriptions module was turned off? /wp-admin/admin.php?page=jetpack_modules

Ah that'll do it, I was checking for the contact form module, not the subscriptions one. Mondays 🤦

**Pull request merged**
