### PR TITLE
Adds post categories as classnames to search results

### PR DESCRIPTION
**Pull request by tommusrhodus**
## Proposed changes:

* Updates Jetpack instant search results to include category taxonomy names as CSS classes
* Updates all 3 search result view options (expanded, minimal, product) to include this

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

I can't see any discussion of this via an MGS search, but the idea of this PR is to allow for category based styling of search results in the ES modal. 

Context: Team51 has a VVIP partner who is requesting results in a certain category have different styling than other search results.

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Setup Jetpack instant search
* Fire off a search that returns results
* Ensure category names are attached to each search results `<li>` parent.
* TESTED: Results without categories are correctly handled.
* TESTED: Results with multiple categories are correctly handled.

Screenshot 2023-02-07 at 18 38 42

### CODE REVIEW

**Comment by sdixon194** [comment]
This works for me! I think it's a really neat change as well. Just needs a merge and some cleanup.

**Comment by tommusrhodus** [comment]
@sdixon194 Awesome! I've cleaned up the PR - is there anything else needed on this from my end?

**Review by sdixon194 — APPROVED** [review]

**Comment by sdixon194** [comment]
Nice thanks! I'm just having some trouble getting the build to finish because of the recent bug, so I keep rerunning it, but no joy so far.

Actually @tommusrhodus  would you mind taking a look at the e2e test failures? I think they may be failing related to search somehow.

**Comment by sdixon194** [comment]
Nvm looks like they're passing now! Just trying to get the build through now.

**Comment by tommusrhodus** [comment]
Thanks so much @sdixon194 ! I've run e2e locally for coverage, JS and PHP all are passing :)

This was my first PR to Jetpack, I have a few others in the works, again for features requested by Team51 partners (which should be of help to the Jetpack community) so if you have any pointers of something I could have improved to make your life easier here, please let me know!

**Comment by sdixon194** [comment]
Nice job! This was a smooth PR! The build keeps failing because of an unrelated bug, but once that's sorted we can merge this at any time.

There was some versioning conflicts that I cleaned up, but nothing really to worry about. Happens when it's the first PR after a release a lot, but `tools/project-version.sh -f -u 0.32.0-alpha packages/search` took care of it. 

If you're looking for a review from the team that usually owns the code, you can also use the `Needs Team Review` label before the `Needs Review` label (which is generally what Crew folks look at). Crew review is required for PRs that touch jetpack code, but individual teams have approval for their own projects. This one only touched Jetpack because of the composer.lock update, but we're always happy to look at any PR with the label :)

**Comment by sdixon194** [comment]
Builds passed! Good to merge whenever @tommusrhodus

**Comment by tommusrhodus** [comment]
Thank you @sdixon194! Last question... should I press the big green button? Or is that run by a specific deployer?

**Comment by sdixon194** [comment]
> Or is that run by a specific deployer?

Nope! Once it has the green button, you can merge it whenever you like.

Release wise, this will be released to WordPress.com and WordPress on Atomic sites next week, and to self hosted sites when 11.9 releases in March. (I believe VIP only uses the major monthly self hosted releases and not the weeklies)

**Comment by kraftbj** [comment]
This is marked for 11.8.1, but doesn't look like it was cherry-picked. Is this intended to go out in the point release (e.g. a broken thing) or should it go for 11.9 as part of the regular release cycle?

**Comment by tommusrhodus** [comment]
Hey @kraftbj - I think I hit that tag a bit early. @sdixon194 explained the release system and 11.9 is fine for this.

removing the milestone 👍

**Comment by kraftbj** [comment]
Sounds good. Thanks!

**Pull request merged**
