### PR TITLE
Fix/hide like button show reblog button

### PR DESCRIPTION
**Pull request by roo2**
In wpcom a reblog button is available as well as a like button. But if the reblog button is enabled, and the like button is disabled, the reblog button will not be shown. https://github.com/Automattic/wp-calypso/issues/44658

The issue is that if a user chooses to show the reblog button but hide the like button, both buttons are hidden. This is because the reblog button is part of the likes module and hiding the like button deactivates the entire module.

I've created a diff to fix this issue in wpcom D65521-code and had that tested by my team. The reblog button is not enabled in non-wpcom jetpack sites, so this change is technically not neccessary to migrate into jetpack.

But after asking in the jetpack-crew channel I was advised to port the work here in order to keep jetpack in sync with what's on wpcom. p1629372049110200-slack-CBG1CP4EN

> In general you do want to keep all files in sync, even if the changes impact something that may not change anything for the site owners on one of the platforms.
> If the files remain in sync, it's easier to port fixes from one side to the other

#### Does this pull request change what data or activity we track or use?
No

### Testing instructions
Apply D65521-code and sandbox `widgets.wp.com` and `s0.wp.com`
Enable the like and reblog buttons, this is where I'm up to in testing this for non wpcom sites: 
The settings are available in http://localhost/wp-admin/admin.php?page=jetpack#/sharing but disabled for offline sites

### CODE REVIEW

**Comment by sdixon194** [comment]
Howdy @roo2 ! Is this one ready for review, or still in progress?

**Comment by roo2** [comment]
Hey @sdixon194 it's ready for a review, but I just hadn't been able to actually test it on the dotorg end, I was hoping that you or someone on the jetpack team might have some insight on how to test it for dotorg, I set up the jetpack local docker environment but the like/reblog button settings where disabled due to being in offline mode, I hacked the settings to be enabled but still wasn't able to get the buttons to be enabled, I'm looking at a jurrasic ninja site today to get it tested.

**Comment by roo2** [comment]
I now think that I probably don't need to merge this, the reason I couldn't test this on jetpack, is it seems that the reblog feature is wpcom only. 

I'm thinking I should close this PR and fix it in wpcom only, p1629372049110200-slack-CBG1CP4EN

**Comment by sdixon194** [comment]
Did some testing on this one! Something I noticed that seemed to be a regression when this PR was applied to my test site - if I enable likes in the Jetpack settings, but then disable the Likes for a specific post, the likes still show on the post.

When testing on latest stable, even if Likes are enabled in the Jetpack settings, I can disable them on a per-post basis.

**Comment by roo2** [comment]
@sdixon194 I have another implementation of this working, it splits the checks for whether the entire module is enabled vs the like button itself is enabled and moves the check for whether the like button is enabled into the API. It fixes the issue which you found on wpcom, I will create a jetpack PR for it soon D66115-code

**Pull request closed without merging**
