### PR TITLE
Autoloader: Remove file check to improve performance.

### PR DESCRIPTION
**Pull request by jeffstieler**
https://github.com/Automattic/jetpack/blob/master/packages/autoloader/src/AutoloadGenerator.php#L68

Since we always optimize, remove expensive `file_exists()` calls from autoloader.

The current autoloader essentially enforces Composer's [Optimization Level 1](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-1-class-map-generation).

This PR seeks to enforce [Optimization Level 2]() as well.

In testing WooCommerce + WooCommerce Admin (which both use this autoloader), requests were seeing ~375 calls to `file_exists()` and spending 1+ seconds wall time. With this change, those numbers are down to ~90 calls and ~0.2 seconds.

I see that a refactor is underway.. this PR maps to this line in the refactor: https://github.com/Automattic/jetpack/pull/15106/files#diff-354912567a0f128335ec5caad8b6e3f8R124

#### Changes proposed in this Pull Request:

* Stop checking `file_exists()` before `require_once` Jetpack autoloader enqueued classes.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Tweaking the autoloader logic

#### Testing instructions:

I could use some help defining testing instructions for this PR.

Locally, I manually made these changes to the autoloaders in both WooCommerce and WooCommerce Admin in order to verify the performance improvements.

#### Proposed changelog entry for your changes:

* Improve performance of autoloader.

### CODE REVIEW

**Review by kbrown9 — APPROVED** [review]
This looks good to me! I performed a quick test of the PR by using the updated Autoloader with Jetpack. As expected, no problems occurred.

I'll leave this open for a day in case anyone else wants to take a look at it before merging. When it's merged, we'll make sure this change is included in the [new autoloader feature branch](https://github.com/Automattic/jetpack/pull/15106) that's currently in progress.

**Comment by jeffstieler** [comment]
Thanks for the quick review @kbrown9!

**Review by zinigor — APPROVED** [review]
Thanks for this PR!

**Review by jeherve — APPROVED** [review]
Tests are all good for this PR. Merging.
https://travis-ci.org/github/Automattic/jetpack/builds/666903637

**Pull request merged**
