### PR TITLE
Subscribe Block: address front-end rendering issues

### LINKED ISSUE #20162: Subscriptions block: Improve mobile layout
#### Is your feature request related to a problem? Please describe.
Subscriptions block has an option to display the button on a new or the same line. Having both button and input on the same line tends to look good on desktop, and poorly on mobile (because the button stays on the same line across all screen sizes). This leads to less than ideal situations like this:

image

or, if there was more horizontal padding, something more extreme:
image

#### Describe the solution you'd like
Given the limited space on mobile, could we either:
* make the button always be on a new line on mobile? 
* add an option for button placement on mobile?

I like the first option better because forcing the button to be on the same line on mobile leaves considerably less space for the input, making it less accessible as well. Are there any drawbacks to making that default behavior?

### PR DESCRIPTION
**Pull request by mtias**
Follow-up to #22694

This fixes a couple issues with how this block renders on the front-end.

- Ensure the right selectors are targeted for style variations.
- Use box-sizing and white space wrapping to prevent overflows.

image (55)

Closes #20162.

#### Testing instructions:

* Go to create a new post.
* Insert the Subscribe block.
* Try different combinations of styles; publish and check rendering on the front-end.

#### Does this pull request change what data or activity we track or use?

No

### CODE REVIEW

**Comment by oskosk** [comment]
Rebased and added changelog file

**Review by oskosk — APPROVED** [review]

**Comment by oskosk** [comment]
@jeherve @sdixon194 I'm not sure what's happening here with D75394-code but this one is ready to go

**Comment by jeherve** [comment]
> @jeherve @sdixon194 I'm not sure what's happening here with D75394-code but this one is ready to go

For reference, discussion in p1645513248039959/1645448233.440409-slack-C02TCEHP3HA

**Comment by jeherve** [comment]
r240669-wpcom

**Pull request merged**
