### PR TITLE
Subscription block: don't include Publicize connections in subscriber count

### LINKED ISSUE #25012: Subscription block: Confusion of follower count
### What

Since the subscription block pertains to email subscription, users tend to relate the count of `followers` shown in the block to be that of email subscribers. Users tend to get confused if the number suddenly goes up or down when a social media is connected or disconnected. 

 
image

It would be good if the follower count adds some indication that the number includes social media followers in addition to email. 

### Why

This will hopefully bring down the number of emails/ chats we get from confused user. 

### How

It would be good if the follower count shown in the frontend adds some indication that the number includes social media followers in addition to email.

### PR DESCRIPTION
**Pull request by TimBroddin**
When `Show subscriber count` is toggled on for the subscription block, a count is shown that includes all followers on all enabled Publicize connections (Twitter followers, LinkedIn followers, ...). This confuses many users.

This PR fixes that by including an extra parameter in the XML-RPC call, which when enabled only fetches the subscribers.

The patch for the XML-RPC server side can be found here D89641-code

Fixes #25012 #23727 & https://github.com/Automattic/wp-calypso/issues/66213

#### Changes proposed in this Pull Request:
* Exclude Publicize followers in the subscription block follower count

#### Does this pull request change what data or activity we track or use?
No

#### Jetpack product discussion
There has been some discussion about adding a toggle for this, but we settled on only showing the subscribers for now.  p1665388720958159/1664774419.931139-slack-C02NQ4HMJKV

#### Testing instructions:
1. Apply this PR
2. Enable Jetpack Social and connect to Twitter (Jetpack > Social > Manage Connections)
3. Add one e-mail follower to your Jetpack site + click the link in the confirmation mail
4. Create a new page/post and add the subscription block, make sure Show subscriber count is turned on in the block settings

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
Great work on figuring out how the numbers and the request work, plus putting it all together in this fix. I appreciate the detailed test instructions in the patch that make it much easier to test the changes. Thank you!, @TimBroddin  🙇🏼‍♂️ 

---

Just noting here that I gave the code a first look yesterday and started testing the changes today on WPCOM first.

The Subscribe block is displaying the correct number of (Followers + Email Followers) in the front-end (10 together):
Markup on 2022-10-12 at 10:37:13

---

Things we looked at together:

The editor's side is still displaying the total number including social followers:
Markup on 2022-10-12 at 10:39:31

We have also stared discussing whether the pre-publish panel should or should not include the social followers (it currently does include them):
Markup on 2022-10-12 at 10:44:23

**Review by ivan-ottinger — DISMISSED** [review]
Works as expected (tested again with the D89641-code patch merged).

**Review by coder-karen — COMMENTED** [review]
Nice work here. The count correctly updates within the editor and front-end, under the block.

Is it expected that the box with the subscriber count should now be missing in the block settings sidebar?

Before: 
Screen Shot 2022-10-14 at 4 12 53 pm

After has nothing at all (whereas the block itself is now showing the correct number of subscribers - 1).

**Comment by TimBroddin** [comment]
Hey Karen,

Thanks for reviewing & great bug catch. I will look into it on Monday.

Tim

**Comment by TimBroddin** [comment]
Hey Karen,

I looked into it, and it seems in [the code](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/controls.js#L56) that it only shows this block when subscriber count is greater than 1. 

```jsx
{ subscriberCount > 1 && (
<InspectorNotice>
	{ createInterpolateElement(
		sprintf(
			/* translators: %s is the number of subscribers. The \xA0 non-breaking space is to make sure the last two words are on the same line. */
			_n(
				'<span>%s reader</span> is\xA0subscribed.',
				'<span>%s readers</span> are\xA0subscribed.',
				subscriberCount,
				'jetpack'
			),
			numberFormat( subscriberCount )
		),
		{ span: <span style={ { textDecoration: 'underline' } } /> }
	) }
</InspectorNotice>
) }
```

When you have 2 or more subscribers it shows fine:
CleanShot 2022-10-17 at 09 05 50@2x

I'll make another PR to also show this for 1 subscriber because this seems like a bug to me.

**Comment by ivan-ottinger** [comment]
Hey Karen and Tim 👋🏼 This was done on purpose - as can be seen in [this discussion](https://github.com/Automattic/jetpack/pull/22694/files#r801868387).

**Comment by TimBroddin** [comment]
Thanks @ivan-ottinger, I've closed the new PR 😄

**Review by coder-karen — APPROVED** [review]

**Pull request merged**
