### PR TITLE
Admin - General tab: remove 3 cards at the bottom / Show site plan info.

### LINKED ISSUE #3832: Admin: remove the bottom 3 cards in the General tab

### LINKED ISSUE #3833: Admin: get the Jetpack Add-ons data to General tab
All we need here is the current Jetpack plan they're on.

### PR DESCRIPTION
**Pull request by eliorivero**
closes #3832
closes #3833  

## Removes cards in General tab.
```
Summary Report Settings
Import Jetpack Feature Configuration
Widget Settings
```
To test, go to Jetpack > Dashboard > General tab and make sure these cards aren't there anymore.

## Fills Jetpack Add-ons card with plan info.
To test:
1. apply D1857
2. in your wporg sandbox, edit `jetpack.php` and set `JETPACK__WPCOM_JSON_API_HOST` to your wpcom sandbox (must be permanently pointed).
3. go to Jetpack > Dashboard > General tab and click on the Jetpack Add-ons arrow, after fetching the data, it should display "Free" or whatever your plan is.

Site in dev mode. Can be seen in a local server for example.
dev mode

While data is loading...
after site data is loaded

If data can't be loaded. Can be seen if D1857 isn't applied.
data error

After data is correctly loaded and displayed.
while fetching site data

### CODE REVIEW

**Comment by dereksmart** [comment]
Works!  couple bits of feedback which were discussed in Slack: 

- display `loading` message while fetching the data
- Use QueryComponent to fetch the data

**Comment by beaulebens** [comment]
This is technically working for me, although I think we need to put something a lot more compelling in here than just "Your plan is: Free".

Happy to get this merged, but we definitely need to look at the design/content of cards like this (probably all of them) to make sure they make sense (maybe do a bunch of them as a batch).

**Comment by eliorivero** [comment]
I agree 100%. The text was added as a placeholder thinking that it can be refined later.
Perhaps @jessefriedman has some suggestion for this?

**Comment by eliorivero** [comment]
Added some extra cases when running in dev mode (can be seen when running a local dev site) and when an error occurs and data isn't available (for example, if D1857 isn't applied).

**Comment by dereksmart** [comment]
:shipit: for now, will discuss verbiage with Growth tomorrow.

**Pull request merged**
