### PR TITLE
Add Store ID in common properties.

### PR DESCRIPTION
**Pull request by puntope**
Context: p7Ldg5-4O0-p2#comment-13058

## Proposed changes:

* This PR includes the new store_id property inside the default event properties which should be included with all events in woocommerce analytics package (soon to be migrated In core).

Screenshot 2024-08-13 at 15 39 10

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Install and Connect Jetpack. 
* Without being Admin navigate to a product
* Verify that store_id is being tracked 

Note that for testing I recommend to use [Tracks Vigilante ](https://github.com/Automattic/tracks-vigilante-2-chrome-extension)

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
👋 Hi @puntope , is this PR ready for review? I've tested it and it tests well so I'd add an approval, though I did notice that the woocommerce-analytics package has not yet had a minor version bump (it's on version 0.1.7 just now), and I'm not sure this change warrants a minor version bump to 0.2.0. Changing the changelog significance to 'patch' instead of 'minor' should help prevent that, though you'd probably need to run `tools/fixup-project-versions.sh` to correct the composer version changes.

**Comment by puntope** [comment]
> 👋 Hi @puntope , is this PR ready for review? I've tested it and it tests well so I'd add an approval, though I did notice that the woocommerce-analytics package has not yet had a minor version bump (it's on version 0.1.7 just now), and I'm not sure this change warrants a minor version bump to 0.2.0. Changing the changelog significance to 'patch' instead of 'minor' should help prevent that, though you'd probably need to run tools/fixup-project-versions.sh to correct the composer version changes.

Hi @coder-karen when I did so and run `tools/fixup-project-versions.s`. I see some errors in the [Changuelogger WF](https://github.com/Automattic/jetpack/actions/runs/10528908974/job/29175662041?pr=38857)

What I'm doing wrong?

**Comment by coder-karen** [comment]
Looks good! 

It looks like `tools/fixup-project-versions.sh` would need to be run again due to changes unrelated to your pull request - a release in another plugin / package has happened in the meantime and there hasn't yet been a PR in the monorepo to update version numbers. It may get fixed in another PR by Monday in which case a trunk merge would be enough, otherwise if you were hoping to get this merged asap then running that command again and committing / pushing the change (I see 10 changed files when I run it locally) would fix that.

**Comment by puntope** [comment]
Hi @coder-karen I merged trunk to solve the discussed issue but now I get another check failing that doesn't seem related t this PR https://github.com/Automattic/jetpack/actions/runs/10663105603/job/29552254721?pr=38857

I believe we can go ahead and approve this?

**Review by coder-karen — APPROVED** [review]
That's right, it wasn't related - it was fixed in this PR: https://github.com/Automattic/jetpack/pull/39187
I did another trunk merge, so this should be good to go now.

**Pull request merged**
