### PR TITLE
Subscriptions: Handle empty email in subscribe modal.

### PR DESCRIPTION
**Pull request by TimBroddin**
Do not merge yet

## Proposed changes:

*

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

**Comment by lezama** [comment]
The scenario where this was reported was patched here: https://github.com/Automattic/jetpack/pull/34070 

I think next step would be to implement the modal with the subscribe input https://github.com/Automattic/jetpack/pull/33800

**Comment by simison** [comment]
@lezama so the bug this fixes is already fixed?

**Comment by lezama** [comment]
97% sure!

**Comment by monsieur-z** [comment]
Just doing some cleanup maintenance here: can we close this PR?

**Comment by simison** [comment]
Yep!

**Pull request closed without merging**
