### PR TITLE
Warm Welcome: Update illustrations across all paid plan welcome screens

### LINKED ISSUE #9143: Update all new plan welcome view illustrations
The illustrations across the welcome screens on all Jetpack plan levels need to be updated to be more Jetpack-ified (new brand green #00be28), and illustrations on gray backgrounds need to be edited to fill in incomplete white/color fills.

Example before/after:
screen shot 2018-03-23 at 8 03 02 pm

**To be updated:** 
Personal, Premium, Professional plan welcome screens. Top illustration differs, but three illustrations inside white box are the same. security.svg has already been updated, so only 5 illustrations need updating: connect-jetpack.svg, generating-cash-2.svg, people-around-page.svg, (shared) customize-theme.svg, (shared) wordads.svg.

screen shot 2018-03-26 at 4 26 06 pm

### PR DESCRIPTION
**Pull request by joanrho**
Resolves #9143 

This PR updates the illustrations in the welcome screens on all Jetpack plan levels need to be more Jetpack-ified (new brand green #00be28), and illustrations on gray backgrounds are updated to fill in incomplete white/color fills.

Before/After of Personal, Premium, and Professional plan welcome screens:

screen shot 2018-03-28 at 9 27 48 pm
screen shot 2018-03-28 at 9 28 00 pm
screen shot 2018-03-28 at 9 28 11 pm

**Testing Instructions:**
* Check out this branch
* Run yarn build
* Visit the Jetpack dashboard in wp-admin on a new site that has the Personal plan and verify the updated welcome dialog box has the updated "After" illustrations as in the above screenshots.
* Visit the Jetpack dashboard in wp-admin on a new site that has the Premium plan and verify the updated welcome dialog box has the updated "After" illustrations as in the above screenshots.
* Visit the Jetpack dashboard in wp-admin on a new site that has the Professional plan and verify the updated welcome dialog box has the updated "After" illustrations as in the above screenshots.

**Changelog entry**
Updated new paid plan welcome screen illustrations to include Jetpack's new brand colors.

### CODE REVIEW

**Comment by rickybanister** [comment]
the 'after' illustrations that appear above the card appear to have solid gray backgrounds behind them. That makes them look weird on the background. I think the backgrounds should be transparent and if we are concerned with bleed-through from the content behind the light gray screen we should increase its opacity.

**Comment by joanrho** [comment]
@rickybanister Good eye, but don't worry, they backgrounds are transparent, not solid. Those solid bgs are only for my frankenmockups.

**Comment by rickybanister** [comment]
👍

**Comment by jeffgolenski** [comment]
Hey hey! Looking a lot better.

Just a nitpick, but could we use the new security computer + green / white shield that we're using on the site, instead of the one with the blue stoke? I just say this, just for consistency sake—since the shield in the first image we have is also white and green? Either way, I like the addition of green to the others!  (if you want the .svgs, happy to send you the dropbox link!)

This one...

screen shot 2018-03-28 at 10 24 37 pm

which matches the shield in this one...

screen shot 2018-03-28 at 10 25 34 pm

**Comment by joanrho** [comment]
Thanks @jeffgolenski! Completely agree. Updated that asset and also updated the screenshots of mockups in my post.

**Comment by zinigor** [comment]
Ported to `branch-6.0` in 636e2a401.

**Pull request merged**
