### PR TITLE
Incompatible Plugins: removes duplicator pro.

### PR DESCRIPTION
**Pull request by cpapazoglou**
This PR is a collection of changes needed to enable `duplicator` and `duplicator-pro` installations in WordPress.com.
Related discussion p1728637897603379-slack-C07QQD54LKU

**WordPress.com Team**

- [ ] Calypso https://github.com/Automattic/wp-calypso/pull/95392
- [ ] WPCOM D163888-code
- [ ] [Documentation needs to be updated after a merge](https://wordpress.com/support/plugins/incompatible-plugins/#backup-plugins) 

**Duplicator Team**

- [x] `duplicator-pro` breaks  `wp-cli` commands in WordPress.com.

image

- [x] When importing a backup the [WordPress.com](http://wordpress.com/) user wasn’t preserved and Jetpack was deactivated. Perhaps something goes off with the `wp_users` table. Solved with a workaround 

> disabled the ability to import backups created on other websites when operating on wp.com.

- [ ] `duplicator` uses `ABSPATH` to define the location of the `wp-content` directory ( or other directories ).

```
if (!function_exists('duplicator_get_abs_path')) {
    function duplicator_get_abs_path() {
        static $absPath = null;
        if (is_null($absPath)) {
            $absPath = wp_normalize_path(ABSPATH);
            if ($absPath == '//' || $absPath == '') {
                $absPath = '/';
            } else {
                $absPath = rtrim($absPath, '/');
            }
        }
        return $absPath;
    }
}
```

can be modified to

```
define('PRESSABLE_SITE_ROOT', str_replace( 'wp-content', '', WP_CONTENT_DIR));
if (!function_exists('duplicator_get_abs_path')) {
    function duplicator_get_abs_path() {
        static $absPath = null;
        if (is_null($absPath)) {
            $absPath = wp_normalize_path(PRESSABLE_SITE_ROOT);
            if ($absPath == '//' || $absPath == '') {
                $absPath = '/';
            } else {
                $absPath = rtrim($absPath, '/');
            }
        }
        return $absPath;
    }
}
```

- [ ] When extracting/installing the duplicated site, the default filename that the plugin generates is named `installer.php` and must be uploaded and then accessed directly via URL to complete the install process. This filename is blocked for security reasons by Atomic and will return a 403 Forbidden error when you attempt to access it. This can default to anything else such as `duplicator.php` or `install.php` and then the file will be accessible.

- [ ] Nice to have - Backups tend to fill storage quickly if you make multiple backups or scheduled backups. It would be cool educating the user about storage implications of multiple backups.

## Proposed changes:

* Allows `duplicator-pro` to be installed in WordPress.com. `duplicator` was not deemed as a priority for now.

## Testing instructions:
The following are related to the changes introduced from this PR, **not** related to whether all `duplicator` issues are fixed.

* Boot a WordPress.com woa developer blog and sync the code OR follow the instructions in https://github.com/Automattic/jetpack/blob/5d37c1f09ce5083c1f150ab74ff9699211988e83/projects/plugins/wpcomsh/README.md#L1-L328
* Upload `duplicator-pro` plugin ( ping me for the zip )
* Make sure you can activate it

## Does this pull request change what data or activity we track or use?
No

### CODE REVIEW

**Comment by andreamk** [comment]
Hi @cpapazoglou 

I'm Andrea, the lead of the Duplicator project. 
Thank you for your time and for thoroughly analyzing the various issues related to Duplicator.

I would like to make a small clarification: the LITE and PRO versions of Duplicator are fundamentally different. The PRO version is more advanced and manages dynamic custom folders, along with many other features that make it compatible with wp.com.

For the moment, we have focused on resolving the issues related to the PRO version to restore its compatibility. I was unable to replicate the problem with wp-cli, but I have made some changes that generally improve the boot process when executing a wp-cli command. Additionally, I have disabled the ability to import backups created on other websites when operating on wp.com.

These two changes should resolve all potential issues related to the PRO version. If needed, I would be happy to send you the PRO version of the plugin for further testing.

I remain at your disposal for any clarifications or further needs. Thank you again for your contribution.

**Comment by cpapazoglou** [comment]
Hey @andreamk 

> I would like to make a small clarification: the LITE and PRO versions of Duplicator are fundamentally different. The PRO version is more advanced and manages dynamic custom folders, along with many other features that make it compatible with wp.com.

Noted.

> For the moment, we have focused on resolving the issues related to the PRO version to restore its compatibility. I was unable to replicate the problem with wp-cli, but I have made some changes that generally improve the boot process when executing a wp-cli command. 

Can you share the latest version with me? You can email me a link at charalampos.papazoglou@automattic.com.

> Additionally, I have disabled the ability to import backups created on other websites when operating on wp.com.

Hmm. This sounds like disabling the most used feature? Like, when a site migrates to WP.com from another hosting?

>  `duplicator` uses ABSPATH to define the location of the wp-content directory ( or other directories ).

does this apply only to the non-pro version?

**Comment by andreamk** [comment]
Hi @cpapazoglou 

> Can you share the latest version with me? You can email me a link at [charalampos.papazoglou@automattic.com](mailto:charalampos.papazoglou@automattic.com).

Done, thanks

> > Additionally, I have disabled the ability to import backups created on other websites when operating on wp.com.
> 
> Hmm. This sounds like disabling the most used feature? Like, when a site migrates to WP.com from another hosting?

The most commonly used feature is backup management and restoration, while importing from external sites to wp.com presents significant complexities. For example, Duplicator needs to merge the user tables between the source and target sites. These are implemented and working processes, but for now, we prefer to have Duplicator Pro enabled on WP.COM. Then, at a later stage, we will restore the rest once we are sure everything is working as it should.

> > `duplicator` uses ABSPATH to define the location of the wp-content directory ( or other directories ).
> 
> does this apply only to the non-pro version?

Yes, exactly. The PRO version can handle any type of custom PATH structure, while the LITE version has a much simpler logic and bases backup generation on the ABSPATH root. Making the LITE version compatible with WP.COM is planned, but it requires more work.

**Comment by cpapazoglou** [comment]
Hey @andreamk, thanks for the zip file.

I ran some tests:

- `cli` seems working as expected
- just a note that I had to enable `Client-Side kickoff.` cause the backup was stuck at 5%. https://duplicator.com/knowledge-base/how-to-resolve-builds-getting-stuck-at-a-certain-point/. Can / should this be auto enabled in WordPress.com?
- I created a backup on the server with success
- I restored a backup from the server, several files couldn't be overwritten. Probably because they are symlinked from the root. This is expected for WordPress.com.

**Comment by andreamk** [comment]
Hi @cpapazoglou 


> Hey @andreamk, thanks for the zip file.
> 
> I ran some tests:
> 
> * `cli` seems working as expected

Perfect!

> * just a note that I had to enable `Client-Side kickoff.` cause the backup was stuck at 5%. https://duplicator.com/knowledge-base/how-to-resolve-builds-getting-stuck-at-a-certain-point/. Can / should this be auto enabled in WordPress.com?

We conducted tests on our staging site on WordPress.com and did not need to enable this option.
This option is necessary when a PHP script on the server cannot call another PHP script on the same server.
In essence, it is required when the chunk engine cannot invoke itself to execute the backup in the background.

You may have some restrictions on your test site, but everything worked correctly on our end. If you believe it’s necessary, we can investigate further.

> * I created a backup on the server with success

Great!

> * I restored a backup from the server, several files couldn't be overwritten. Probably because they are symlinked from the root. This is expected for WordPress.com.

Yes, in our backups, the core WordPress files are also included, but the installer is designed so that if extracting a file fails, the entire installation does not fail. For this reason, there are all those warnings, which have no impact on the final result.

I am planning a patch to prevent writing to WordPress.com, in order to improve user feedback.

Thank you very much for your considerations and your help.

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as expected. I am able to upload and activate a backup of the `duplicator-pro` plugin. LGTM! :shipit: 

https://github.com/user-attachments/assets/af0d689d-a024-4693-abf5-ad370c4ae556

**Comment by cpapazoglou** [comment]
Since blocker issues related to `duplicator-pro` are resolved, I am merging this PR.

@andreamk let us know if issues related to `duplicator` are resolved in the future.

**Pull request merged**
