### PR TITLE
Nav Unification: Force Simple sites to use Calypso Themes.

### PR DESCRIPTION
**Pull request by kwight**
Regardless of Nav Unification, Simple sites cannot add their own themes, and should always be shown the WP.com Theme Showcase (from Calypso) – never the core `themes.php` page. This PR ensures the Appearance menu for WP.com Simple sites is always built with the `wp_admin_themes` value set to `false` (do not use the core theme page).

Fixes https://github.com/Automattic/wp-calypso/issues/51663

Screen Shot 2021-04-12 at 12 33 24 PM

#### Jetpack product discussion
Nav Unification project thread: pbAPfg-Ou-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
This patch affects only Simple sites, so testing is best done with the diff and a WP.com sandbox.

* Apply D60049-code to your sandbox and sandbox the API.
* Load https://wordpress.com/me/account, and toggle on the "Show advanced dashboard pages" setting.
* Under My Sites, switch to a Simple site.
* Click on Appearance > Themes in the sidebar menu.
* Verify you are shown the Calypso theme showcase at the `wordpress.com/themes/*` URL.

### CODE REVIEW

**Comment by mreishus** [comment]
Looks good to me. For my simple site, I was sent to themes.php before the patch, but stay inside calypso after the patch. 

I also tested on an Atomic site w/ the patch and continued to go to themes.php.

Looks like it needs a change file?

**Comment by kwight** [comment]
> Looks like it needs a change file?

@mreishus Ah, thank you – added. 👍

**Review by mreishus — DISMISSED** [review]
Looks good to me. For my simple site, I was sent to themes.php before the patch, but stay inside calypso after the patch.
I also tested on an Atomic site w/ the patch and continued to go to themes.php.

**Review by mreishus — APPROVED** [review]
Still LGTM after rebase

**Review by mmtr — APPROVED** [review]
Looks good!

**Comment by mmtr** [comment]
@kwight seems that D60049-code still needs to be deployed, correct?

**Comment by jeherve** [comment]
r225022-wpcom

**Pull request merged**
