### PR TITLE
Add locale support to the API.

### PR DESCRIPTION
**Pull request by justinshreve**
D43 is also needed from Phabricator. Once both of these patches are applied, and you have a language pack, you can test by making a request to:

https://public-api.wordpress.com/rest/v1/sites/$blog/post-formats/?pretty=true&locale=$locale

If you have the WPCom patch applied, you can load https://public-api.wordpress.com/rest/v1/sites/justin.wpsandbox.me/post-formats/?pretty=true&locale=de specifically to test in German.

and you should see the post formats translated.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Looks good!

**Comment by samhotchkiss** [comment]
@dereksmart - make sure this gets added to the to-test.txt file

**Comment by justinshreve** [comment]
The code on the .com side has been merged in already.

**Comment by dereksmart** [comment]
Tested and read through.  :+1:

**Pull request merged**
