### PR TITLE
Dotcom patterns: Show v2 pattern library with all themes

### PR DESCRIPTION
**Pull request by miksansegundo**
Related to https://github.com/Automattic/wp-calypso/pull/88985

## Proposed changes:

* Show the v2 pattern library in the editor for all themes
* Hide core and Jetpack form patterns

|BEFORE|AFTER|
|-|-|
|Screenshot 2567-01-16 at 17 48 16|Screenshot 2567-03-26 at 18 53 23|

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [X] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

### Does this pull request change what data or activity we track or use?
No

## Testing instructions:

**How to test on Atomic**
* Use the Jetpack beta plugin with the branch `fix/use-dotcom-pattern-library` for the plugin "WordPress.com Features" 
* Make sure to add `define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true );` to your `wp-config.php` file.

**How to test on Simple**
* Make sure `wpcom/public_html` repo is updated 
* Sandbox a simple site and the public api
* Apply this patch with `bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/use-dotcom-pattern-library`

**Verify the following**
* Make sure you have a theme other than Assembler active on your site
* Access the editor on that site and click the button `[ + ]` on the topbar to explore the patterns from the editor inserter
* Verify you see the same patterns and categories as when you have the Assembler theme active 
* Verify you don't see the "Forms" category (these are Jetpack forms)
Screenshot 2567-03-29 at 00 35 44

* Verify you don't see these patterns in the "Banners" category (they are from the Dotorg pattern directory)
Screenshot 2567-03-29 at 00 36 01

* Verify you cannot find a pattern named "Social links with a shared background color" (this is pattern bundled in core)
Screenshot 2567-03-29 at 00 37 27

### CODE REVIEW

**Review by arthur791004 — DISMISSED** [review]
Tested with TT4 and it looks good 🎉

**Review by arthur791004 — COMMENTED** [review]
The `$patterns_source` is no longer in use, so we have to remove it to pass the linter

**Comment by miksansegundo** [comment]
Thanks!

I have updated this PR to:

- Stop using the source site list
- Hide core and Jetpack form patterns
- Improve the cache system:
  - Disable the cache for Automatticians
  - Remove the plugin version from the key
  - Clear the cache for users every 5 minutes as in the PTK API

**Comment by miksansegundo** [comment]
This PR is ready for another review.
 
Some tests are failing but are not related to the changes in this PR:

- Three flaky tests related to themes in `WordPress.com Tests`
  - `core-theme` testsuite exited with code 1
  - See them [here](https://teamcity.a8c.com/buildConfiguration/ParallelPatchGit_TemplateRunner0/12193564?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) 
- is_automattician is protected with function_exists, but `Tests / Static analysis` fails. 
  - See [here](https://github.com/Automattic/jetpack/blob/3c4c16b8e9b34c8b6e798839ddf029a5c9a59e77/projects/packages/jetpack-mu-wpcom/src/features/error-reporting/error-reporting.php#L111) that we don't even need to protect it because this plugin runs only in Dotcom 
  - See https://github.com/phan/phan/issues/1204

**Comment by arthur791004** [comment]
We can follow https://github.com/Automattic/jetpack/pull/36627 to add the `is_automattician` into the `wpcom-functions.php`

**Comment by arthur791004** [comment]
> Hide core and Jetpack form patterns

I'm curious about the reason to hide these patterns. Do you have more context? Thank you!

**Comment by okmttdhr** [comment]
The code looked good to me!

> > Hide core and Jetpack form patterns
> 
> I'm curious about the reason to hide these patterns. Do you have more context? Thank you!

Sorry for being late to the party but I'm also curious about this!

**Comment by miksansegundo** [comment]
> We can follow https://github.com/Automattic/jetpack/pull/36627 to add the is_automattician into the wpcom-functions.php

Nice, thanks! I'm on it.

> I'm curious about the reason to hide these patterns. Do you have more context? Thank you!

See pbxlJb-5DK-p2#comment-3635

**Comment by arthur791004** [comment]
It seems we still have to run `jetpack phan --update-baseline packages/jetpack-mu-wpcom` to pass Static Analysis

image

**Comment by miksansegundo** [comment]
> It seems we still have to run jetpack phan --update-baseline packages/jetpack-mu-wpcom to pass Static Analysis

Yes, thanks for helping. I just installed it in my environment and updated the baselines.

**Review by arthur791004 — APPROVED** [review]
Looks good to me 🎉

**Pull request merged**
