### PR TITLE
Fix failing Jetpack plugin JS Tests

### PR DESCRIPTION
**Pull request by andrewserong**
Following on from https://github.com/Automattic/jetpack/pull/20512 which introduced Jetpack Boost, it appears that the Jetpack plugin JS tests have been failing (for extensions / blocks in particular). This seems to be to do with a version mismatch between the Jest version that the Jetpack plugin / Jetpack extensions tests were expecting and the one that was running. This PR updates the Jest dependency  for the Jetpack plugin to > 27.

The helpful links I found while investigating the failing tests were:

* https://github.com/facebook/jest/issues/11444#issuecomment-847909076
* https://github.com/facebook/jest/issues/7868

#### Screenshots

Before:

image

After:

image

#### Changes proposed in this Pull Request:

* Update Jest dependency for the Jetpack plugin to fix failing JS tests

#### Testing instructions:

* See if the CI JS test jobs complete, or to test locally:
* Go to `projects/plugins/jetpack` and run `pnpm test-extensions` to run tests. Check that they pass!
* Check that this hasn't caused any other tests / jobs to fail

### CODE REVIEW

**Review by glendaviesnz — APPROVED** [review]
This tested well for me. Jetpack plugin js tests failed on master, but complete successfully on this PR

**Comment by ramonjd** [comment]
> The helpful links I found while investigating the failing tests were:

The same person answered both questions! Kudos!

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
I think we'll need to manually get the lock file back working on WP.com, but this will unblock master. Thank you!

**Comment by jeherve** [comment]
r229749-wpcom

**Comment by andrewserong** [comment]
Thanks Jeremy!

**Pull request merged**
