### PR TITLE
Markdown Lib: Convert from 0-load.php load method

### PR DESCRIPTION
**Pull request by kraftbj**
See #18590

#### Changes proposed in this Pull Request:

* Updates loading structure to use preferred {lib}/{slug}.php style.

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

n/a

#### Testing instructions:

* tbd
*

#### Proposed changelog entry for your changes:

* n/a, not a functional change

### CODE REVIEW

**Comment by kraftbj** [comment]
Will need to do a little extra work in the WP.com diff. Going to get that done before marking this ready for review.

**Comment by kraftbj** [comment]
For the sake of testing, D56419-code.

Will need to do some commit shuffling with it.

**Comment by kraftbj** [comment]
D56511-code handled the second of the WP.com side changes to avoid mid-deploy fatals.
r220543-wpcom and r220545-wpcom

**Review by anomiex — APPROVED** [review]
Looks sensible to me.

**Pull request merged**
