### PR TITLE
Protect: tweak footer

### PR DESCRIPTION
**Pull request by retrofox**
This PR tweaks some visual issues in the Footer component

Fixes #

#### Changes proposed in this Pull Request:

* Protect: tweak footer section

#### Testing instructions:

* Go to Protect plugin.
* Confirm visually the footer looks good
* Take a look at the recording events, just in case (by clicking on the Get Protect button)

before | after
-----|------
image | image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202204855890077

### CODE REVIEW

**Review by keoshi — DISMISSED** [review]
Looks good to me! The only thing I noticed is we're adding left/right padding where there should be none.

The footer should sit on the grid like so, to match the content in the upper area:

image

Here's the original design reference:

image

cc @ederrengifo

**Comment by retrofox** [comment]
> Looks good to me! The only thing I noticed is we're adding left/right padding where there should be none.

image

Added the padding because currently, the space between the border and the sections is `24px.`, where it should be `76px` according to the design.

> The footer should sit on the grid like so, to match the content in the upper area:

I wonder whether we should update the spacing of other sections (header, footer, etc) to align them.

Anyway the simplest solution to remove the padding, keeping in mind the space could be 24px.

**Comment by retrofox** [comment]
> Looks good to me! The only thing I noticed is we're adding left/right padding where there should be none.
> 
> The footer should sit on the grid like so, to match the content in the upper area:

Removed lateral spacing here https://github.com/Automattic/jetpack/pull/24190/commits/815fb9ace836d2e3503ffc1d3d09a50c2160239c

**Review by leogermani — APPROVED** [review]
LGTM

**Comment by keoshi** [comment]
> where it should be 76px according to the design

To be clear, it's 76px just because the artboard is set at a size that makes the left/right spacing 76px wide, considering the width of the content. The criteria should always be the grid and how the elements fall on it.

**Pull request merged**
