### PR TITLE
Carousel: use lone description as caption

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

* If the caption and title fields for a photo are blank, but there is a description provided, use that for the `.jp-carousel-photo-caption` caption (the text you see before clicking the info icon).
* Before the carousel redesign, there were users that solely used the photo description field, which showed up on the old carousel by default. Now with the redesigned carousel, a viewer would need to click the info icon to view the description if no title/caption were added.

#### Jetpack product discussion:

None/here.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* After pulling down changes, create/have a gallery, and make sure the carousel feature is enabled.
* For one of the gallery images, only have the description set:

Markup on 2021-08-19 at 11:47:25

* Then view that gallery image on the frontend. Make sure you can see the lone description populated as the caption:

Screen Shot 2021-08-19 at 11 30 57 AM

* When it comes to deciding on what to show as the caption the priority is: caption > title > description (this PR). So if you then try setting a caption or title for the same image, that would show for the caption instead.

### CODE REVIEW

**Comment by sdixon194** [comment]
This works for me! But I wonder if maybe the intended behavior of the original carousel wasn't the best way of going about it? Are there more cases where it'd be preferable to keep a description hidden instead of showing it in the carousel as a caption? ie, people might want the description, but no caption won't have a way of doing that with this PR, but people who want both/only a caption can do that.

**Comment by samiff** [comment]
> people might want the description, but no caption won't have a way of doing that with this PR

I can't imagine that would be a large subset of users - intentionally leaving the title & caption fields blank, but wanting a description to show only when clicking the info icon.

More likely I imagine there are some users who may want to hide the `.jp-carousel-photo-caption` in full, which is doable with CSS.

**Comment by sdixon194** [comment]
> More likely I imagine there are some users who may want to hide the .jp-carousel-photo-caption in full, which is doable with CSS.

Funny, I was literally just having a conversation with someone who had a user who wanted to display the full caption/description text. Opened an issue for that here too:
https://github.com/Automattic/jetpack/issues/20770

**Review by sdixon194 — APPROVED** [review]

**Comment by samiff** [comment]
r230595-wpcom

**Pull request merged**
